### ISSUE TITLE
How to tell which attribute is the primary key?

### ISSUE THREAD

**Issue by MohiuddinM** [simolus3/moor#1]

**Comment by simolus3** [comment]
Hi,
there are two ways to specify the primary key:
1. When you have just one column in the primary key that also uses auto-increment: Just call the `autoIncrement()` method on the column getter, like this: https://github.com/simolus3/moor/blob/8fe350219c1040ff88218c12dce977cb28edf7e7/moor_flutter/example/lib/database/database.dart#L9
2. For custom primary keys: Override the `primaryKey` getter to return a set of fields. An example is here: https://github.com/simolus3/moor/blob/8fe350219c1040ff88218c12dce977cb28edf7e7/moor/test/data/tables/todos.dart#L31-L35

Is this what you need?

**Comment by MohiuddinM** [comment]
Thank you for your quick answer!
I am now using the second method, and it gives the following error:
'Xxx.primaryKey' ('() → Set<dynamic>') isn't a valid override of 'Table.primaryKey' ('() → Set<Column<dynamic, SqlType<dynamic>>>').

**Comment by simolus3** [comment]
Hm, that would indicate that the type of the overriden getter is wrong. Did you explicitly add the type annotation `Set<Column>` instead of just `Set`?
If it's not a problem, pasting your table class could also help me see what's going on (feel free to obscure the class / getter names).

**Comment by MohiuddinM** [comment]
The problem is resolved! It wanted me to import the moor.dart
