### ISSUE TITLE
Question: Should all tables and dabase be in one file?

### ISSUE THREAD

**Issue by pedromassango** [simolus3/moor#100]
Hi all. I'm just starting learning this Library.

On my first attempt to use this package I separated my models and the database in diferent files. When I run the `flutter packages pub run build_runner build` command it finished successfully but I was unable to get the _$MyDatabase reference.

I solved it by moving `MyDatabase` class to the same file where I have the models and it worked.

My question is if whe should have all the code (models and the databse) in the same file?!

**Comment by simolus3** [comment]
Moor currently generates code for `@UseMoor` annotations and puts all generated code in the same file. Do you have the `part` statement in the file where your database is? Something like this should work:
```dart
// file called tables.dart, no part statement
import 'package:moor/moor.dart';

class Users extends Table {
 // some columns
}
```
```dart
// file called database.dart
import 'package:moor_flutter/moor_flutter.dart';
import 'tables.dart';

part 'database.g.dart';

@UseMoor(tables: [Users])
class MyDatabase extends _$MyDatabase {
  // ...
}
```

**Comment by pedromassango** [comment]
It worked thank you
