### ISSUE TITLE
Strategy to embed static database

### ISSUE THREAD

**Issue by mdkess** [simolus3/moor#1002]
Thank you for this awesome library - it has been powerful and enjoyable to use.

I had a challenge that I wasn't sure how to tackle, and figured I'd ask the experts.

I have a static data set that I want to embed in the app. While the app is running this data won't change (i.e. no writes), but between app updates it might. So basically, I want to take a JSON file and at build time turn that into a static sqlite database, and then use Moor to query that data.

What is the recommended way to do this?

For some context - it's for my app FluentCard and is a database of Chinese character graphics and dictionary data.

**Comment by simolus3** [comment]
>Thank you for this awesome library - it has been powerful and enjoyable to use.

Thanks!

> While the app is running this data won't change (i.e. no writes), but between app updates it might.

I would include the database as a [flutter asset](https://flutter.dev/docs/development/ui/assets-and-images). You could extract that to [`getTemporaryDirectory`](https://pub.dev/documentation/path_provider/latest/path_provider/getTemporaryDirectory.html) with a `LazyDatabase`. You can then open that as a regular `VmDatabase` or `FlutterQueryExecutor`.
This solution is a bit complicated considering that you only need a static database, but I'm not aware of a better way unfortunately. Sqlite has in-memory databases, but I don't think we can initialize them with a binary database file.
