### ISSUE TITLE
Please support primary(unique) key ordering

### ISSUE THREAD

**Issue by glanium** [simolus3/moor#1007]
SQLite support  primary(unique) key ordering

```dart
class TestTable extends Table {

  IntColumn get id => integer()();

  IntColumn get id2 => integer()();

  @override
  List<String> get customConstraints => [
    'PRIMARY KEY (id ASC, id2 DESC)'
  ];

}
```
but this one cause issue. Primary key is not recognized by moor.

I tried using moor files.

```dart
CREATE TABLE test_table extends Table (

  id INT NOT NULL,
  id2 INT NOT NULL,
  PRIMARY KEY (id ASC, id2 DESC)

)
```
but I got moor_generator error

Supporting key ordering like the following will be good

```dart 
class TestTable extends Table {

  IntColumn get id => integer()();

  IntColumn get id2 => integer()();

  @override
  Set<Column> get primaryKey => {id, id2};

  @override
  List<String> get primaryKeyOrdering => ['ASC', 'DESC'];  <-- this

}
```
thx

**Comment by simolus3** [comment]
Thanks for the suggestion!

I'm not a big fan of the `primaryKeyOrdering` api - it feels weird to manually keep this in sync with `primaryKey`. Adding that information to `primaryKey` directly could work, but it would require a breaking change.

I adapted the generator and the SQL parser to support `DESC` and `ASC` in primary key declarations in moor files.
