### ISSUE TITLE
How To Define A Trigger ?

### ISSUE THREAD

**Issue by gloryluu** [simolus3/moor#1008]
Hello @simolus3 , I have dive through the doc but still cannot figure out how to declare a trigger

I have a tables.moor file which contains only a trigger:

```
CREATE TRIGGER IF NOT EXISTS update_station_manual AFTER UPDATE ON stations s
WHEN OLD.is_manual <> NEW.is_manual
BEGIN
   UPDATE as_manuals am
   INNER JOIN other_infos oi ON oi.id = am.other_infos_id
   INNER JOIN visits v ON oi.visits_id = v.id
   INNER JOIN stations s ON s.id = v.stations_id
   SET am.is_manual = NEW.is_manual
   WHERE s.id = NEW.id;
END;
```

And a moor_database files

```
@lazySingleton
@UseMoor(include: {
  'tables.moor'
}, tables: [
  Stations,
  OtherInfos,
  AsManuals,
], daos: [
  ... Some Daos here
])
// _$AppDatabase is the name of the generated class
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  // Bump this when changing tables and columns.
  // Migrations will be covered in the next part.
  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        // Runs if the database has already been opened on the device with a lower version
        onCreate: (migrator) async {

        },
        onUpgrade: (migrator, from, to) async {
          //await migrator.createTrigger(updateStationManual); // I did put it here but it's not generated anything
        },
        beforeOpen: (details) async {
          await customStatement('PRAGMA foreign_keys = ON');
        },
      );
}

LazyDatabase _openConnection() { .. some code here to create db }

... some tables here

class Stations extends Table {...}

```

How can I integrate a trigger into the moor_database files ? Thanks so much.

**Comment by simolus3** [comment]
That code looks alright to me, do you get an error with that approach? Are you importing the Dart files declaring tables into the moor file?

**Comment by gloryluu** [comment]
Nope, I only add the trigger in the `tables.moor` file. All the other stuff lay in the `moor_database.dart`. So the trigger sql in will be created without doing anything ?

**Comment by simolus3** [comment]
The default `onCreate` implementation should create all tables and triggers. You've overwritten yours, so you'd have to manually create the trigger then.

Does the generated database class contain a `updateStationManual` field? If so, the generator recognized the trigger successfully. Otherwise there should have been an error in the build. If neither happened, something on moor's side is broken - I'd love to take a look at a full repro then.

**Comment by gloryluu** [comment]
I moved the trigger creating code into a customStatement and it works!!. But I now falling into the issue that the propagating triggers for auto-updating streams when the data is updated. Does the library support it @simolus3 ?

**Comment by simolus3** [comment]
Moor recognizers triggers for query streams when you define them in a moor file.

You can also write them manually, by putting this into your database class:

```dart
  @override
  StreamQueryUpdateRules get streamUpdateRules {
    return const StreamQueryUpdateRules([
      WritePropagation(
        on: TableUpdateQuery.onTableName(
          'stations',
          limitUpdateKind: UpdateKind.update,
        ),
        result: [
          TableUpdate('as_manuals', kind: UpdateKind.update),
        ],
      ),
    ]);
  }
```

Be aware that foreign key constraints can also cause stream update rules, so you might have to add those too.

**Comment by gloryluu** [comment]
Is there anyway to just define the triggers in moor file and leave all the table in dart file alone ? Since I have a lot of tables and I dont want to migrate it all to the moor file.

**Comment by simolus3** [comment]
You can import Dart tables into a moor file. So if e.g. you had a file called `tables.dart` with all your table definitions (as Dart classes). Then, you can have a moor file called `triggers.moor` next to that file with the following content

```sql
import 'tables.dart'; -- so that Dart-defined tables are available here

CREATE TRIGGER IF NOT EXISTS update_station_manual AFTER UPDATE ON stations s
WHEN OLD.is_manual <> NEW.is_manual
BEGIN
   UPDATE as_manuals am
   INNER JOIN other_infos oi ON oi.id = am.other_infos_id
   INNER JOIN visits v ON oi.visits_id = v.id
   INNER JOIN stations s ON s.id = v.stations_id
   SET am.is_manual = NEW.is_manual
   WHERE s.id = NEW.id;
END;
```

**Comment by gloryluu** [comment]
Understood. It seems clear to me now. Thanks for your supporting.
