### ISSUE TITLE
Get the whole row with maximum field value in table

### ISSUE THREAD

**Issue by givip** [simolus3/moor#1009]
I found small explanation in docs here https://moor.simonbinder.eu/docs/getting-started/expressions/#comparing

But cannot figure out how to use it, e.g.

When I tried to do something like this:
```
  Future<int> getLastMessageId(String conversationId, int topicId) {
    return (select(messages)..where((tbl) => tbl.messageId.max()))
        .map((e) => e.messageId)
        .getSingle();
  }
```
I get compilation error for expression `tbl.messageId.max()`:
`error: The return type 'Expression<int>' isn't a 'Expression<bool>', as required by the closure's context. (return_of_invalid_type_from_closure)`

BTW I succeeded by creating only one column, but if I want to return whole row, how I would do that?
```
 Future<int> getLastMessageId(String conversationId, int topicId) {
    final lastMessageIdExpr = messages.messageId.max();
    return (selectOnly(messages)..addColumns([lastMessageIdExpr]))
        .map((row) => row.read(lastMessageIdExpr))
        .getSingle();
  }
```

**Comment by simolus3** [comment]
In this case, I'd just use `ORDER BY` and a `LIMIT`:

```dart
final row = await (db.select(messages)
      ..orderBy([(row) => OrderingTerm.desc(row.messageId)])
      ..limit(1))
    .getSingle();
```

Your approach would only work with a subquery (`SELECT * FROM messages WHERE id = (SELECT MAX(message_id) FROM messages)`), but moor's Dart api doesn't support them yet.

Also, feel free to ask questions like this in the [discussions](https://github.com/simolus3/moor/discussions) next time, those are more convenient for me. Thanks!
