### ISSUE TITLE
Equivalent of TRIM()

### ISSUE THREAD

**Issue by vikalpnagar** [simolus3/moor#1012]
What would be the equivalent for this query in moor.

SELECT name FROM products WHERE TRIM(type) = 'MEN';

**Comment by simolus3** [comment]
I just added the `TRIM` function on the `develop` branch, it will be part of the next moor release.

In the meanwhile, you could add

```dart
extension Trim on Expression<String?> {
  Expression<String?> trim() => FunctionCallExpression('TRIM', [this]);
}
```

And then write the query like this:

```dart
selectOnly(products)
  ..addColumn(name)
  ..where(products.type.trim().equals('MEN'))
```

**Comment by vikalpnagar** [comment]
Thanks. It worked.
