### ISSUE TITLE
Working with an existing sqlite3 database.

### ISSUE THREAD

**Issue by shellking4** [simolus3/moor#1014]
I apologize if I'm saying something wrong.
I'm relatively new to flutter and I want to use moor package in My app. For some reasons I could not insert the data in a database directly from app(the data need to be a little bit processed before). Then I externally created my sqlite db, processed my data and insert them into the db. Now I want to use that sqlite db in the app and manage db operations with moor. But I can't find a way to do this properly. Any hint how I can do it ? Thanks in advance.

**Comment by simolus3** [comment]
You can use an existing database with moor by adding it as a [Flutter asset](https://flutter.dev/docs/development/ui/assets-and-images) and extracting it in a `LazyDatabase` opener.

I've written a more in-depth tutorial for that [here](https://develop--moor.netlify.app/docs/examples/existing_databases/), is that what you were looking for?

**Comment by shellking4** [comment]
Thank you for your answer. I now  know how to get the job done. Thanks a lot for this wonderful package 🙂
 I think I'm going to close this issue now.

**Comment by shellking4** [comment]
Thank you for your answer. I now  know how to get the job done. Thanks a lot for this wonderful package 🙂
 I think I'm going to close this issue now.
