### ISSUE TITLE
Expression (isNull(Variable(null)) does not work as intended

### ISSUE THREAD

**Issue by KokeCacao** [simolus3/moor#1015]
## Describe the bug
See the sample function below where I try to query the database
```
/// This function access the database that select specific [listId] and [vocabId] and returns a stream
/// If [listId] is not provided as an argument, the function selects all variants of [listId]
/// If [vocabId] is not provided as an argument, the function selects all variants of [vocabId]
Stream<VocabListModel> watchFromDatabase({int listId, String vocabId}) {
  // commented code is not working, see error message below
  // specifically, (isNull(Variable(listId)) and (isNull(Variable(vocabId)) will result an error when listId or vocabId is specified
  // strangely, (isNull(Variable(listId)) and (isNull(Variable(vocabId)) will not result an error when listId or vocabId is unspecified
  // Expression<bool> Function($VocabSqliteTableTable tbl) filter =
  //     (tbl) => (isNull(Variable(listId)) | tbl.listId.equals(listId)) & (isNull(Variable(vocabId)) | tbl.id.equals(vocabId));

  // this code is working, but not at all intuitive
  Expression<bool> Function($VocabSqliteTableTable tbl) filter =
      (tbl) => (tbl.listId.equalsExp(coalesce([Variable(listId), tbl.listId]))) & (tbl.id.equalsExp(coalesce([Variable(vocabId), tbl.id])));
  
  // get the stream of my object using DAO
  Stream<List<VocabSqliteTableDataWithUserVocabSqliteTableData>> stream = _dao.watchVocabsWithUserWhere(filter: filter);
  
  // do the nesscary conversion to my view object
  return stream.map((stream) => VocabListModel(
      vocabs: stream.map((e) => VocabModel.fromCombinedSqlite(e)).toList()));
}
```

## Expected behavior:
My commented code
`(tbl) => (isNull(Variable(listId)) | tbl.listId.equals(listId)) & (isNull(Variable(vocabId)) | tbl.id.equals(vocabId))` has the same effect as
`(tbl) => (tbl.listId.equalsExp(coalesce([Variable(listId), tbl.listId]))) & (tbl.id.equalsExp(coalesce([Variable(vocabId), tbl.id])))`

## Actual behavior:
The following error generates when I do `(tbl) => (isNull(Variable(listId)) | tbl.listId.equals(listId)) & (isNull(Variable(vocabId)) | tbl.id.equals(vocabId))`.
```
======== Exception caught by widgets library =======================================================
The following StateError was thrown building LearningScreen(dirty, state: _LearningScreenState#5bb5a):
Bad state: Too many elements

The relevant error-causing widget was: 
  LearningScreen file:///home/koke_cacao/Documents/Koke_Cacao/Dart/WorkSpace/deep_vocab/lib/screens/navigation_screen.dart:29:19
When the exception was thrown, this was the stack: 
#0      ListMixin.singleWhere (dart:collection/list.dart:191:11)
#1      SqlTypeSystem.forDartType (package:moor/src/runtime/types/type_system.dart:32:18)
#2      Variable.mapToSimpleValue (package:moor/src/runtime/query_builder/expressions/variables.dart:58:37)
#3      Variable.writeInto (package:moor/src/runtime/query_builder/expressions/variables.dart:66:39)
#4      Expression.writeAroundPrecedence (package:moor/src/runtime/query_builder/expressions/expression.dart:84:7)
...
====================================================================================================
```

The idea of the unintuitive workaround comes from here: https://moor.simonbinder.eu/docs/getting-started/expressions/
But looking at the documentation, I have no idea why the error occurs. Can anyone tell me if commented code results in an expected behavior?

**Comment by simolus3** [comment]
Does it work if you add type parameters to `Variable`? E.g. `Variable<int>(listId)` and `Variable<String>(vocabId)`?

But I agree that the error message could be a lot clearer here, and I think we might be able to remove that requirement altogether.

**Comment by KokeCacao** [comment]
> Does it work if you add type parameters to `Variable`? E.g. `Variable<int>(listId)` and `Variable<String>(vocabId)`?
> 
> But I agree that the error message could be a lot clearer here, and I think we might be able to remove that requirement altogether.

Haven't thought about that. This worked! Thank you so much!

**Comment by KokeCacao** [comment]
> Does it work if you add type parameters to `Variable`? E.g. `Variable<int>(listId)` and `Variable<String>(vocabId)`?
> 
> But I agree that the error message could be a lot clearer here, and I think we might be able to remove that requirement altogether.

Also, in the documentation, it will be nice to show a correct line of example code
`p.price * Variable(amount);` should be changed to `p.price * Variable<int>(amount);` right?
See: https://moor.simonbinder.eu/docs/getting-started/expressions/#arithmetic

**Comment by simolus3** [comment]
I think in that case it might actually be fine, since `p.price` is an `Expression<int>` and its `*`-operator needs another `Expression<int>`. So the type of the variable should be inferred in that case.

Either way, I've since changed the implementation to allow `Variable` instances without a proper type parameter.
