### ISSUE TITLE
Mutable companion objects

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#102]
How would you recommend going about setting some additional properties on a companion before updating a table?

For example, I'd like to be able to write something like this:
```
  Future<int> updateFoo(int fooId, FooCompanion updates) {
    updates.updatedTimestamp = ...;
    updates.updatedDeviceId = ...;
    updates.updatedUsrId = userId;
    updates.uuid = generateUUID();
    return FooDAO(_db).updateFoo(fooId, updates);
  }
```
Currently this isn't possible since the companion's properties are `final`. Maybe there could be a `copyWith` method like on the data classes?

**Comment by simolus3** [comment]
I like the idea of having a `copyWith` method on companions, it should be straightforward to generate and we don't have to give up on immutability.

**Comment by simolus3** [comment]
Fixed on develop, will be a part of the next version.
