### ISSUE TITLE
OnAfterOpen?

### ISSUE THREAD

**Issue by willhaslett** [simolus3/moor#1021]
How does one know when their instantiated database is ready for use? How do I make sure that `beforeOpen:`'s Future has resolved and the connection is ready? Apologies if I'm missing something, concrete or abstract.

**Comment by simolus3** [comment]
You can use `doWhenOpened` for this, so something like this should work:

```dart
Future<void> waitForOpen() {
  final completer = Completer();
  doWhenOpened((e) => completer.complete());

  return completer.future;
}
```

Note that the database won't be opened multiple times, so you can safely use `doWhenOpened` multiple times. In fact, moor uses that method for every query sent.

But ideally, you would just use the database. All methods will wait for the database to open, so why would you need to know that? You can also override `beforeOpen` in your migration, that will get called just before the database is ready. So you could set a field at the end of that method to know when the database has been opened.

**Comment by willhaslett** [comment]
"All methods will wait for the database to open".  I see. Thank you.
