### ISSUE TITLE
customSelect with JOIN for tables with same fields

### ISSUE THREAD

**Issue by givip** [simolus3/moor#1029]
```
    return customSelect('''
      SELECT tb1.*, tb2.* FROM tb1
        LEFT JOIN tb2
	          ON tb1.field_1 = tb2. field_1 
	              AND tb1. field_2 = tb2. field_2
      ORDER BY field_3;
      ''');
```

returns List of `QueryRow` objects, where `data` property is Map with keys equal fields name, without table prefix, like this:
```
{
    'field_1' : 'value',
    'field_2' : 'value',
    'field_3' : 'value',
}
```

In this case we cannot properly parse results with
```
SomeObject.fromData(row.data, db)
```
because fields with same name (field_1, field_2) are overwritten by joined data

**Comment by simolus3** [comment]
> where `data` property is Map with keys equal fields name, without table prefix, like this:

Yeah, that's how sqlite works. Moor doesn't transform strings you pass to `customSelect`, so it can't do anything against that.

> In this case we cannot properly parse results with `SomeObject.fromData(row.data, db)`

Here, I would recommend using moor files or compiled queries on your `@UseMoor`/`@UseDao` annotation. By using [nested results](https://moor.simonbinder.eu/docs/using-sql/moor_files/#nested-results), `moor_generator` can transform your query into a form that does let you use `fromData`.
