### ISSUE TITLE
Possibility to standardize on/force use of specific line endings

### ISSUE THREAD

**Issue by adg-mh** [simolus3/moor#1037]
My colleague and I work on linux and windows respectively and as it seems OS specific line endings are generated into the sql queries every time the moor files are regenerated we end up with many "changes" between `\r\n` <-> `\n` in version control.

I'm not sure if it's reasonable to force specific line endings inside the strings (sqlite doesn't seem to care either way)...

**Comment by simolus3** [comment]
In the next moor version, you can enable the `new_sql_code_generation` [build option](https://moor.simonbinder.eu/docs/advanced-features/builder_options/) to remove comments and unnecessary whitespace from generated SQL strings. That should also fix this problem then.

**Comment by adg-mh** [comment]
Perfect.
