### ISSUE TITLE
Generated queries don't expand multiple occurrences of array variables

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#104]
I'd like to be able to apply an unknown number of WHERE clauses at runtime. To achieve this, I'm writing something like this (from example project) :
```dart
const int _absent = -1;

@UseMoor(
  tables: [Todos, Categories],
  queries: {
    '_search': '''
      SELECT * FROM todos WHERE
      (CASE WHEN $_absent IN :category THEN 1 ELSE category IN :category END)
    ''',
  },
)

class Database extends _$Database {
  Database() : super(FlutterQueryExecutor.inDatabaseFolder(path: 'db.sqlite', logStatements: true));

  void testQuery({List<int> category = const <int>[_absent]}) {
    watchSearch(category).listen(print);
  }
}

```

However this query doesn't return the expected results. This is the log output from above:
```
I/flutter ( 6108): Moor: Sent       SELECT * FROM todos WHERE
I/flutter ( 6108):       (CASE WHEN -1 IN (?) THEN 1 ELSE category IN (?) END)
I/flutter ( 6108):      with args [-1]
I/flutter ( 6108): []
```

If I add quotes around '-1' so that it's inferred as a string, and map the arguments to a string:
```dart
const int _absent = -1;

@UseMoor(
  tables: [Todos, Categories],
  queries: {
    '_search': '''
      SELECT * FROM todos WHERE
      (CASE WHEN '$_absent' IN :category THEN 1 ELSE category IN :category END)
    ''',
  },
)

class Database extends _$Database {
  Database() : super(FlutterQueryExecutor.inDatabaseFolder(path: 'db.sqlite', logStatements: true));

  void testQuery({List<int> category = const <int>[_absent]}) {
    watchSearch(category.map((i) => i.toString()).toList()).listen(print);
  }
}

```

The query returns the expected result:
```
I/flutter ( 6108): Moor: Sent       SELECT * FROM todos WHERE
I/flutter ( 6108):       (CASE WHEN '-1' IN (?) THEN 1 ELSE category IN (?) END)
I/flutter ( 6108):      with args [-1]
I/flutter ( 6108): [TodoEntry(id: 1, content: something, targetDate: null, category: null)]
```

Is there anything I'm missing here? 

Thanks!

**Comment by Mike278** [comment]
I also noticed that `?`s are used when expanding `IN` parameters:
```
I/flutter ( 6108): Moor: Sent       SELECT * FROM todos WHERE
I/flutter ( 6108):       (CASE WHEN '-1' IN (?,?,?) THEN 1 ELSE category IN (?,?,?) END)
I/flutter ( 6108):      with args [1, 2, 3]
```

To handle the same parameter multiple times, I think this should use indexed parameters instead: 
```
I/flutter ( 6108): Moor: Sent       SELECT * FROM todos WHERE
I/flutter ( 6108):       (CASE WHEN '-1' IN (?1,?2,?3) THEN 1 ELSE category IN (?1,?2,?3) END)
I/flutter ( 6108):      with args [1, 2, 3]
```

**Comment by simolus3** [comment]
Thank you for the detailed description. How the behavior of the query changes when the parameter is a string is weird indeed.
```dart
final r1 = await customSelect('SELECT (CASE WHEN -1 IN (?) THEN 1 ELSE NULL IN (?) END) AS r',
      variables: [Variable.withInt(-1)]);
final r2 = await customSelect("SELECT (CASE WHEN '-1' IN (?) THEN 1 ELSE NULL IN (?) END) AS r",
     variables: [Variable.withString('-1')]);
```
Here, `r1` returns `null` and `r2` returns `1`. If I also bind the second variable to `-1` (as int and as string, respectively), both queries return `1`. How sqlite evaluates `IN` expressions is unintuitive as well: `NULL IN <expr>` evaluates to `NULL`, and `2 IN ('-2')` is false.


Of course, the real issue here is how moor doesn't expand the variables properly. If I remember correctly we already require that array variables are not followed by a scalar variable. So, we should be able to handle the tricky case by just applying an offset equal to the highest index of a scalar variable.

**Comment by simolus3** [comment]
We now use indexed parameters when expanding array parameters. This is the most tricky query I could come up with
```sql
SELECT * FROM todos WHERE
   id = ?1 AND content LIKE ?3 AND (CASE WHEN -1 IN :category THEN 1 ELSE category IN :category END)
   OR id = ?2
```
Running it with `(1, 2, 'test', [4, 5, 6])` expands `:category` to `(?4, ?5, ?6)`, so the final bound parameters are `[1, 2, test, 4, 5, 6])`.

**Comment by Mike278** [comment]
Ah that totally makes sense! I'm kinda surprised sqlite wasn't giving any errors about not binding an appropriate number of parameters. Thanks so much as always for your quick responses :)
