### ISSUE TITLE
How to return a object for query sql, not a Future?

### ISSUE THREAD

**Issue by crossle** [simolus3/moor#1040]

**Comment by simolus3** [comment]
This is not possible - moor is asynchronous by design.

There really isn't much more to say about that, but I can try to help you use futures if you give me more context about what you're trying to do.

**Comment by crossle** [comment]
For example, I wanna implements the abstract class like this https://github.com/MixinNetwork/libsignal_protocol_dart/blob/master/lib/src/state/IdentityKeyStore.dart#L13,  the function `getIdentity` need to query the SQLite database.

**Comment by simolus3** [comment]
Unfortunately that wouldn't work - you'd have to ask the maintainers of that package to consider making those methods asynchronous. 
If everything else fails, you can import `dart:cli` and use `waitFor` to synchronously await a future, but I wouldn't recommend that.
