### ISSUE TITLE
Query not replaced in Android Platform

### ISSUE THREAD

**Issue by rrifafauzikomara** [simolus3/moor#1049]
First of all, I have a custom select like below:
```
Future<List<PayModeData>> getPayModeData(int payModeList) {
    return customSelect(
        'select LST_PAY_MODE.LSCB_ID, LST_PAY_MODE.LSCB_PAY_MODE, LST_PAY_MODE.LSCB_TTL_MONTH, LST_PAY_MODE.LSCB_KALI from LST_PAY_MODE where case when :payModeList = 1 then LSCB_ID in (0) when :payModeList = 2 then LSCB_ID in (6,1,2,3) when :payModeList = 3 then LSCB_ID in (3) when :payModeList = 4 then LSCB_ID in (6) end',
        variables: [Variable.withInt(payModeList)],
        readsFrom: {lstPayMode}).map((QueryRow row) {
      return PayModeData(
        lscbId: row.readInt('LSCB_ID'),
        lscbPayMode: row.readString('LSCB_PAY_MODE'),
        lscbTtlMonth: row.readInt('LSCB_TTL_MONTH'),
        lscbKali: row.readInt('LSCB_KALI'),
      );
    }).get();
  }
```

And when I run this function on the iOS, the logcat moor is shown like this:
```
I/flutter (25710): Moor: Sent select LST_PAY_MODE.LSCB_ID, LST_PAY_MODE.LSCB_PAY_MODE, LST_PAY_MODE.LSCB_TTL_MONTH, LST_PAY_MODE.LSCB_KALI from LST_PAY_MODE where case when :payModeList = 1 then LSCB_ID in (0) when :payModeList = 2 then LSCB_ID in (6,1,2,3) when :payModeList = 3 then LSCB_ID in (3) when :payModeList = 4 then LSCB_ID in (6) end with args [1]
```

From the above function and logcat, we see that `:payModeList` will be replaced with `1`, and the result of that query is based on `payModeList` params. For example:

If the `payModeList` is `1`, it will replaced `:payModeList` with `1` and get the result `0`,
If the `payModeList` is `2`, it will replaced `:payModeList` with `2` and get the result `6,1,2,3`,
If the `payModeList` is `3`, it will replaced `:payModeList` with `3` and get the result `3`,
If the `payModeList` is `4`, it will replaced `:payModeList` with `4` and get the result `6`,

And you can see on the logcat when I running on the iOS, the `payModeList` is `1` so the UI will show `0`. And this is successfully shown on the UI. But, when I running on Android. It's failed shown on the UI because the result is empty. Although the result of logcat it's the same when I running on the iOS platform. But the difference is in iOS the data is shown, but in Android, the data do not show.

The question is, why  `:payModeList` it's not replaced when running on the Android platform?

**Comment by simolus3** [comment]
Are you using `moor_flutter` (`FlutterQueryExecutor`) or `moor/ffi` (`VmDatabase`)? sqflite (the package used by `moor_flutter`) uses some weird hacks to work with variables on Android (can't blame that package, Android's sqlite apis are horrible). That has caused some problems in the past, it might be related to this one too.
I can do more research when you tell me which one you're using.

**Comment by rrifafauzikomara** [comment]
Hi, @simolus3 

Thanks for the response. I use `moor_flutter: ^3.1.0` and import `import 'package:moor_flutter/moor_flutter.dart';`

**Comment by simolus3** [comment]
Thank you for the additional details. I believe that this is a problem in `sqflite`, so I've opened the linked issue at that repository.

**Comment by rrifafauzikomara** [comment]
Hi @simolus3,

Thanks for followup my issue to `sqflite` package. Btw for now I already fix this bug using the `replaceAll` method 😂.

```
Future<List<PayModeData>> getPayModeData(int payModeList) {
    var query =
        'select LST_PAY_MODE.LSCB_ID, LST_PAY_MODE.LSCB_PAY_MODE, LST_PAY_MODE.LSCB_TTL_MONTH, LST_PAY_MODE.LSCB_KALI from LST_PAY_MODE where case when :payModeList = 1 then LSCB_ID in (0) when :payModeList = 2 then LSCB_ID in (6,1,2,3) when :payModeList = 3 then LSCB_ID in (3) when :payModeList = 4 then LSCB_ID in (6) end';
    var finalQuery = query.replaceAll(':payModeList', '$payModeList');
    return customSelect(finalQuery, variables: [], readsFrom: {lstPayMode})
        .map((QueryRow row) {
      return PayModeData(
        lscbId: row.readInt('LSCB_ID'),
        lscbPayMode: row.readString('LSCB_PAY_MODE'),
        lscbTtlMonth: row.readInt('LSCB_TTL_MONTH'),
        lscbKali: row.readInt('LSCB_KALI'),
      );
    }).get();
  }
```
