### ISSUE TITLE
Deleting an entity by primary key

### ISSUE THREAD

**Issue by mrdavidrees** [simolus3/moor#105]
I'm having trouble finding an easy way to delete entities by primary key.

It is possible to create a delete method on DeleteStatement<T> which accepts the primary keys that were registered?

like

    delete(userTable).delete(userId: 0)

or

    delete(userTable).delete(email: "test@test.com", age:10)

This is because I have to lookup the userId in the database before then deleting the user like so:

    final user = await (select(userTable)..where((user) => user.userId.equals(userId))).get()
    delete(userTable).delete(user)

The alternative is to create an empty User model but that has its own issues with showing warnings if there are missing fields:

    //ignore: missing_required_param
    delete(userTable).delete(User(userId:0))

You can hide the warnings but it doesn't seem like the best solution.

Sorry I haven't just submitted a PR, you're probably swamped with all the extra interest into this library lately.

Thanks, David.

**Comment by simolus3** [comment]
Hi, you can construct partial data (here, only the fields with the id) with "companions" generated for each table. So this should do the trick
```dart
delete(userTable).delete(UserTableCompanion(userId: Value(0)));
```
I see how that's less fun to write but I can't think of a simpler api that would be easy to implement (e.g. without generating a `DeleteStatement` for each table).
