### ISSUE TITLE
Moor + sqlcipher ... Invalid argument(s): Failed to load dynamic library (dlopen failed ... libsqlite3.so not found)

### ISSUE THREAD

**Issue by kemist88** [simolus3/moor#1050]

**Comment by simolus3** [comment]
There are two ways to use an encrypted database with moor:

1. Using the `encrypted_moor` package: In this case, you shouldn't use a `VmDatabase` at all. Instead, use an `EncryptedExecutor`.
2. Using the `sqlcipher_flutter_libs` package: Here, you can use a regular `VmDatabase` after a one-time setup:
```dart
open.overrideFor(
        OperatingSystem.android, () => DynamicLibrary.open('libsqlcipher.so'));
```

The docs don't really explain the second option, I'll improve them.

**Comment by kemist88** [comment]
What is the difference between the 2 methods ?

**Comment by simolus3** [comment]
Basically, they're using two different implementations:

- `encrypted_moor` uses an encrypted version of the `sqflite` package, so it uses Flutter platform channels and a platform-specific implementation for Android and iOS
- The ffi-based approach is a little more independent of Flutter since it doesn't require platform channels or a plugin implementation. We have a special `sqlcipher_flutter_libs` package, but it doesn't contain any Dart/Java/Kotlin/ObjC/Swift/whatever code. Its only responsibility it to bundle the compiled SQLCipher libraries with your app.

For regular moor I usually recommend the ffi-based library since it's a bit smaller and can be more efficient for read-heavy apps. But both approaches work well in practice.

**Comment by kemist88** [comment]
`encrypted_moor` works fine for me. The problem is I tried to do the 2nd approach ffi-based without success.

ffi-based error:

`
SqliteException(26): file is not a database, file is not a database (code 26)
`

![Untitled](https://user-images.githubusercontent.com/22894450/108074852-b5011480-707a-11eb-81f9-edba2cf040c6.png)

![1](https://user-images.githubusercontent.com/22894450/108074772-a1ee4480-707a-11eb-950b-1413511dda53.png)

![Untitled](https://user-images.githubusercontent.com/22894450/108074971-deba3b80-707a-11eb-9920-7296905bb9b5.png)


Should I myself include the file `libsqlcipher.so` ? or is it enough with the pubspec dependencies as shown above ?
because I noticed the import in main.dart is from sqlite3 NOT Sqlcipher ... you know better 

Finally, appreciate your fantastic work with moor. Thank you!

**Comment by simolus3** [comment]
> SqliteException(26): file is not a database, file is not a database (code 26)

It sounds like `libsqclipher.so` was properly included, but the password is incorrect? If `libsqlcipher.so` wasn't available, you'd get a "Failed to load dynamic library" error.

It's definitely weird that it works with `encrypted_moor` though... Are you using moor with isolates? You need to call `overrideFor` on every isolate that uses a `VmDatabase` later, but that's only the main isolate by default.

**Comment by kemist88** [comment]
Nope, I don't use isolate.
The password is the same like in `encrypted_moor`
Can I try plain sqlite db + with empty password '' ? will it work ?

**Comment by davidmartos96** [comment]
Opening a normal Sqlite db with the Sqlcipher library should work normally.

**Comment by kemist88** [comment]
> Opening a normal Sqlite db with the Sqlcipher library should work normally.

Yep it worked

**Comment by davidmartos96** [comment]
@kemist88  Are you trying to open an existing Sqlcipher database copied from assets? Maybe you are providing an incorrect password or the database is encrypted with SqlCipher 3.x or lower, which uses a different format than 4 and above.

**Comment by kemist88** [comment]
> @kemist88 Are you trying to open an existing Sqlcipher database copied from assets? Maybe you are providing an incorrect password or the database is encrypted with SqlCipher 3.x or lower, which uses a different format than 4 and above.

The password is correct cuz I already tried it with `encrypted_moor` with success.
The version of sqlcipher I don't know it. I encrypted it with sqlitemanager. till now i can't find the version. I will search the vesrion

**Comment by kemist88** [comment]
I will stick with `encrypted_moor`

I am also getting this error (when trying moor with desktop)

![image](https://user-images.githubusercontent.com/22894450/108086717-bc7aea80-7087-11eb-8a97-a9ecdc70e4d1.png)

Any solution ?

**Comment by simolus3** [comment]
> I am also getting this error (when trying moor with desktop)

I think both approaches only work on iOS and Android by default. There is [some documentation](https://moor.simonbinder.eu/docs/platforms/#desktop) around this, but effectively you'd need to download the native libraries for each OS and abi you want to support and ship them with your app.

**Comment by kemist88** [comment]
> I think both approaches only work on iOS and Android by default. There is [some documentation](https://moor.simonbinder.eu/docs/platforms/#desktop) around this, but effectively you'd need to download the native libraries for each OS and abi you want to support and ship them with your app.

actually i like this `encrypted_moor`  very much :) it's working fine. Besides, I think Desktop is in alpha and too early for me to look into it this much. Thank you guys for this great lib and keep it on.
