### ISSUE TITLE
Support json_annotation ^4.0.0

### ISSUE THREAD

**Issue by fionawhim** [simolus3/moor#1051]
The `json_annotation`/`json_serializable` packages are upgrading to 4.0 to support null safety. `json_annotation`’s 4.0.0 is stable (albeit in prerelease).

Could `moor` update its `json_annotation` dependency to allow ^4.0.0 releases, so that apps can use both `moor` and `json_serializable` null safe versions?

I did a quick look at the uses of `json_annotation` and they look like they’re still supported with 4.0.

**Comment by simolus3** [comment]
Only the generator depends on `json_annotation`. It supports the 4.x versions on `develop` (and it will depend on them with the next release).

Until then, you can use dependency overrides to fix this:

```yaml
dependency_overrides:
  json_annotation: ^4.0.0-nullsafety
```
