### ISSUE TITLE
Sqlite error hidden inside transaction

### ISSUE THREAD

**Issue by ThomasKliszowski** [simolus3/moor#1052]
Hello 👋

My application starts throwing `SqliteException` in production:
```
SqliteException(1): cannot rollback - no transaction is active
```
Moor can't rollback the transaction because sqlite is failing behind. The thing is that I can't retrieve the original sqlite error, and it was very painful to reproduce it as the error was related to memory (same as https://github.com/simolus3/moor/issues/876).

Here is the failing code:
https://github.com/simolus3/moor/blob/b3ebaeadcfb4c209c3c0f835a0fb3a5c8cae08b8/moor/lib/src/runtime/api/connection_user.dart#L367-L375

`await transactionExecutor.rollback();` is throwing, so we lost the original error.

Don't you think that we should throw the original error if the rollback fails?
Something like:
```dart
catch (e) {
  try {
    await transactionExecutor.rollback();
  } catch(_) {
    throw e;
  }

  rethrow;
}
```

Thank you 🙏

**Comment by simolus3** [comment]
Thank you for the report, I can see that the error recovery is pretty bad if `.rollback()` throws too.

On the other hand, I'm not sure if we should just swallow the fact that `rollback` threw an exception. Maybe we could introduce an exception class that wraps both exceptions and provides the original stacktrace:

```dart
catch (e, s) {
  try {
    await transactionExecutor.rollback();
  } catch(rollbackE) {
    throw CouldNotRollbackException(e, s, rollbackE);
  }

  rethrow;
}
```

A downside is that users would have to catch `CouldNotRollbackException` to get the right stack trace. Since we're not using `rethrow` in that case, the trace would appear come from moor otherwise.

**Comment by ThomasKliszowski** [comment]
I agree, ignoring the rollback exception is not ideal, even if I greatly prefer to get the original exception instead of the rollback one.

`CouldNotRollbackException` looks good to me. This change could be breaking, if users used to catch `SqliteException`, they will have to catch `CouldNotRollbackException` as well. But this change can save a lot of time to users if they encounter the same problem as I did.

Another way to do that would be wrapping all `SqliteException` with a custom moor exception that supports nested exceptions. So we will not have to deal with both `SqliteException` and `CouldNotRollbackException`. This is a bigger change but more consistent.

**Comment by simolus3** [comment]
This has now been fixed on `develop`. I opted for the `CoultNotRollBackException`. IMO changing the types of possible exceptions is not a breaking change that would justify a major version bump. The type of exceptions thrown is essentially an implementation detail, and users typically catch all exceptions either way.
