### ISSUE TITLE
Generator isn't using .named() for columns in all places

### ISSUE THREAD

**Issue by HatEmU** [simolus3/moor#1060]
Hello 👋 

I've made this table:

```
class Discount extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(max: Constants.nameMaxLength)();
  IntColumn get value => integer()();
  BoolColumn get isPercentage => boolean().named('is_percentage')();
}
```

and I'm giving my isPercentage column a name:

`BoolColumn get isPercentage => boolean().named('is_percentage')();`

I looked at the generated file and it isn't fully utilizing the `is_percentage` name I gave it:

```
class DiscountData extends DataClass implements Insertable<DiscountData> {

  ...
  
  @override
  Map<String, Expression> toColumns(bool nullToAbsent) {
    ...
    if (!nullToAbsent || isPercentage != null) {
      map['is_percentage'] = Variable<bool>(isPercentage);
    }
    ...
  }

  ...

  factory DiscountData.fromJson(Map<String, dynamic> json,
      {ValueSerializer serializer}) {
    ...
      isPercentage: serializer.fromJson<bool>(json['isPercentage']),
    ...
  }

  @override
  Map<String, dynamic> toJson({ValueSerializer serializer}) {
    ...
      'isPercentage': serializer.toJson<bool>(isPercentage),
    ...
  }

...

```

I think the issue is from the `factory DiscountData.fromJson` constructor and the `Map<String, dynamic> toJson` method where both are using `isPercentage` as the key instead of `is_percentage` which is troublesome for me because I am using a JsonSerializable model and I set it to use snake case so when I do DiscountModel.toJson() my model is sending 'is_percentage'. You can see the issue when because my `isPercentage` is required so I get an error when I try to insert new records. I can't use camel case for my model because I also get data from a backend server so my hands are tied.

I don't know if this is the intended behavior or not, let me know if it is. 

Anyways, have a nice day!

**Comment by simolus3** [comment]
Hi, and thanks for your detailed issue description.

By design, `named()` only affects the column name in SQL. Json serialization is a different concern, moor has its own `@JsonKey` annotation for that. As [the documentation](https://pub.dev/documentation/moor/latest/moor/ColumnBuilder/named.html) points out, you can annotate your getter with that to change the json name:

```dart
class Discount extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(max: Constants.nameMaxLength)();
  IntColumn get value => integer()();
  @JsonKey('is_percentage')
  BoolColumn get isPercentage => boolean().named('is_percentage')();
}
```

You probably wouldn't even need `.named()` in that case, as moor uses `camel_case` for sql columns by default.
