### ISSUE TITLE
Consider marking moor_ffi discontinued on pub.dev

### ISSUE THREAD

**Issue by mit-mit** [simolus3/moor#1067]
From the readme, looks like https://pub.dev/packages/moor_ffi is deprecated?

In that case, may I recommend marking the package discontinued on pub.dev?
https://dart.dev/tools/pub/publishing#discontinue

**Comment by mit-mit** [comment]
cc @simolus3

**Comment by simolus3** [comment]
I've just marked the package as discontinued. Apologies if I wasted your time on a pointless empty-structs migration.

**Comment by mit-mit** [comment]
No worries, thanks!
