### ISSUE TITLE
Can't generate private watch*() methods

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#107]
A definition like `queries: {'_searchTodos' : 'SELECT * FROM todos'}` correctly generates a private `Future`-returning method, but the `Stream`-returning method is public.

```dart
  Future<List<TodoEntry>> _searchTodos(
      {@Deprecated('No longer needed with Moor 1.6 - see the changelog for details')
          QueryEngine operateOn}) {
    return (operateOn ?? this).customSelect('SELECT * FROM todos',
        variables: []).then((rows) => rows.map(_rowToTodoEntry).toList());
  }

  Stream<List<TodoEntry>> watchSearchTodos() {
    return customSelectStream('SELECT * FROM todos',
        variables: [],
        readsFrom: {todos}).map((rows) => rows.map(_rowToTodoEntry).toList());
  }
```

**Comment by simolus3** [comment]
Yeah, this is unfortunate :/ It is a bug in the generator, but there are two released versions with that bug. Fixing this now would be a breaking change.

We could introduce a (opt-in) flag for the builder that fixes this in the next version. When moor 2.0 comes around (I've collected a bunch of other minor breaking changes in #61), we can remove that flag and always use the right name.

**Comment by simolus3** [comment]
I added a builder flag on `develop` to fix this. There are [some docs](https://moor.simonbinder.eu/docs/advanced-features/builder_options/) explaining how to enable the flag.
