### ISSUE TITLE
Moor not working if windows app installed with MSIX installer

### ISSUE THREAD

**Issue by SahajRana** [simolus3/moor#1074]
**Describe the bug**

A clear and concise description of what the bug is. Please briefly describe what behavior you expected, what behavior you saw, and how the bug can be reproduced.

MSIX is an installer for windows app to distribute on Windows Store as well as direct download. [https://github.com/YehudaKremer/msix](https://github.com/YehudaKremer/msix) This is recommended by flutter docs. I tried it with packaging `sqlite3.dll` with it and some additional code as explained in moor docs.

```
void main() async {
  open.overrideFor(OperatingSystem.windows, _openOnWindows);
  final db = sqlite3.openInMemory();
  db.dispose();
  runApp(new MyApp());
}

DynamicLibrary _openOnWindows() {
  final script = File(Platform.script.toFilePath());
  final libraryNextToScript = File('${script.path}/sqlite3.dll');
  return DynamicLibrary.open(libraryNextToScript.path);
}
```
But after installing the app through MSIX, sqlite doesn't seems to work. It works when run directly by .exe file but not for the MSIX installed app.

Edit: I did some debug it gives: 
`SqliteException(14): bad parameter or other API misuse, bad parameter or other API misuse (code 21)`

**Comment by simolus3** [comment]
Unfortunately I can't help you with this. How you open `sqlite3.dll` on Windows is outside of the responsibility of moor, and I don't have any experience with msix.

You could check how additional dlls can be included with msix, maybe it is possible to ship sqlite3 along with your distributed app. It needs to include the VC runtime either way. It might also be possible to configure your Flutter build scripts on Windows to statically link sqlite3.
