### ISSUE TITLE
Selctable.getSingle() causes Bad state: No element.

### ISSUE THREAD

**Issue by masahiro-ikemoto** [simolus3/moor#1075]
In the Selectable.getSingle() metod that is contained moor-3.4.0/lib/src/runtime/query_builder/statements/query.dart:
```
if (!iterator.moveNext()) {
  return null;
}
```
Above code assumes that the moveNex() returns false when iterater is empty, but it throws Bad state exception (in my environment).

flutter --vesion:
```
Flutter 2.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 60bd88df91 (34 hours ago) • 2021-03-03 09:13:17 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0
```

**Comment by masahiro-ikemoto** [comment]
Sorry, I should us getSingleOrNull(). I'll Close this issue.

**Comment by gumdum** [comment]
thanks for this comment, it helped me fix my own Bad State issue with getSingleOrNull()
