### ISSUE TITLE
Add dynamic default value into moor table

### ISSUE THREAD

**Issue by tazik561** [simolus3/moor#1090]
I am creating a class table which has 2 fields that has default value, here the code

```
import 'package:test/database/database.dart';
@DataClassName("LocationCatTable")
class LocationCategoriesTables extends Table {
  TextColumn get uid => text().clientDefault(() => uuid.v4())();
  TextColumn get categoryName => text().withDefault(const Constant("All"))();

  @override
  Set<Column> get primaryKey => {uid};
}
```

when database is creating, It generate a  SQL like that
`I/flutter (25189): Moor: Sent CREATE TABLE IF NOT EXISTS location_categories_tables (uid VARCHAR NOT NULL, category_name VARCHAR NOT NULL DEFAULT 'All', PRIMARY KEY (uid)); with args []`

As you can see, I am trying to set defaults value to this table. In Database class I initialized uuid instances:

```
final uuid = Uuid();

@UseMoor(include: {
  'index.moor'
}, tables: [
  LocationCategoriesTables,
], daos: [
  LocationCategoriesDao,
])
class Database extends _$Database {
 Database()
  : super(FlutterQueryExecutor.inDatabaseFolder(
        path: 'db.sqlite', logStatements: true));
```
But When I run my application, those defaults value are not added into table?

https://pasteboard.co/JSfjVfb.png

**Comment by simolus3** [comment]
The defaults are added to a table when you run an insert. E.g. you could run an `into(locationCategoriesTable).insert(...)` and the uid would be generated by moor. `clientDefault` does not do anything until you actually insert a row though.

**Comment by tazik561** [comment]
> The defaults are added to a table when you run an insert. E.g. you could run an `into(locationCategoriesTable).insert(...)` and the uid would be generated by moor. `clientDefault` does not do anything until you actually insert a row though.

Imaging when application is started I have a drop down menu and I want to show a default values.. Now I have call a insert before get data ? Means I have to insert a dummy data to insert a default value and then delete that dummy data?

**Comment by simolus3** [comment]
Right. In that case, I would just populate the data in the `onCreate` callback of your `MigrationStrategy`. Both `withDefault` and `clientDefault` only apply to individual rows as they are inserted.
