### ISSUE TITLE
Because moor_flutter >=4.0.0-nullsafety depends on moor ^4.0.0-nullsafety and   moor_generator >=3.0.0 <4.0.0-dev depends on moor ^3.0.0, moor_flutter

### ISSUE THREAD

**Issue by nailuj29gaming** [simolus3/moor#1091]
**Describe the bug**

When trying yo upgrade to null safety, I get an error stating
```
Because moor_flutter >=4.0.0-nullsafety depends on moor ^4.0.0-nullsafety and
  moor_generator >=3.0.0 <4.0.0-dev depends on moor ^3.0.0, moor_flutter
```

**Comment by kuhnroyal** [comment]
You need to update the generator in `dev_dependencies` as well.

**Comment by simolus3** [comment]
Yup, it should work with `moor_generator: ^4.0.0`

**Comment by nailuj29gaming** [comment]
![image](https://user-images.githubusercontent.com/54189157/110963160-bf33cd00-831f-11eb-9364-d160622b7cb4.png)

**Comment by simolus3** [comment]
Where is that from? `pub outdated`? If you want to use moor 4, you'll also have to use version 4 of `moor_generator`.

You might have other dependencies that don't allow you to use moor 4. I can take a look at that, but you need to upgrade `moor_generator` to use the latest `moor`.

**Comment by nailuj29gaming** [comment]
yeah, it was a problem with null safety. I figured it out
