### ISSUE TITLE
moor_generator requires old analyzer version and clashes with mockito and injectable_generator

### ISSUE THREAD

**Issue by NikoBoerger** [simolus3/moor#1099]
**Describe the bug**
The moor_generator requires the analyzer version  >=0.40.0 <0.43.0.

However, other libs like Mockito and injectable_generator require the analyzer version ^1.1.0.

Could you update to this version as well, so that the dependencies are compatible?
Thanks a lot :)

**Comment by simolus3** [comment]
Hi, I've upgraded the analyzer version on my development branch, but those changes haven't been released yet. For the next version, I'm also trying to support the latest version of the `build` package but I'm still waiting for some dependencies to do that as well. You can try using a version from git (https://github.com/simolus3/moor/issues/1077#issuecomment-792584974) in the meantime.
