### ISSUE TITLE
moor  near "ON": syntax error on insertOnConflictUpdate method

### ISSUE THREAD

**Issue by tazik561** [simolus3/moor#1106]
I am trying to use moor on my project . This is my table: 

```
@DataClassName("LocationTable")
class LocationTables extends Table {
  TextColumn get locationUuid => text()();
  RealColumn get latitude => real()();
  RealColumn get longitude => real()();
  TextColumn get locationCatUid => text()();
  TextColumn get title => text()();
  TextColumn get mobile => text().nullable()();
  TextColumn get phone => text().nullable()();
  TextColumn get description => text().nullable()();
  DateTimeColumn get createdAt => dateTime()();

  @override
  Set<Column> get primaryKey => {locationUuid};
}
```
and this is it's dao:

```
@UseDao(tables: [LocationTables])
class LocationDao extends DatabaseAccessor<Database> with _$LocationDaoMixin {
  final Database db;
  LocationDao(this.db) : super(db);

  Future insertTask(Insertable<LocationTable> location) =>
      into(locationTables).insert(location);

  Future insertOrUpdateLocation(Insertable<LocationTable> location) =>
      into(locationTables).insertOnConflictUpdate(location);

```
Now I am trying to use insertOrUpdateLocation . In android emulator everything is fine and I didn't get error but when I am using My mobile (Samsung A31) I got this error:
 
```
I/flutter (15938): Moor: Sent INSERT INTO location_tables (location_uuid, latitude, longitude, location_cat_uid, title, mobile, phone, description, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(location_uuid) DO UPDATE SET location_uuid = ?, latitude = ?, longitude = ?, location_cat_uid = ?, title = ?, mobile = ?, phone = ?, description = ?, created_at = ? with args [02e98b69-df0e-4f35-a667-c5a27ac925e9, 35.73528356437848, 51.487202763671874, b5671816-1e48-4c80-a2e1-c6700d4f5dc2, ubbj, 666666, 6633, htyh, 1616010052, 02e98b69-df0e-4f35-a667-c5a27ac925e9, 35.73528356437848, 51.487202763671874, b5671816-1e48-4c80-a2e1-c6700d4f5dc2, ubbj, 666666, 6633, htyh, 1616010052]
E/SQLiteLog(15938): (1) near "ON": syntax error
E/flutter (15938): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: DatabaseException(near "ON": syntax error (code 1 SQLITE_ERROR[1]): , while compiling: INSERT INTO location_tables (location_uuid, latitude, longitude, location_cat_uid, title, mobile, phone, description, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(location_uuid) DO UPDATE SET location_uuid = ?, latitude = ?, longitude = ?, location_cat_uid = ?, title = ?, mobile = ?, phone = ?, description = ?, created_at = ?) sql 'INSERT INTO location_tables (location_uuid, latitude, longitude, location_cat_uid, title, mobile, phone, description, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(location_uuid) DO UPDATE SET location_uuid = ?, latitude = ?, longitude = ?, location_cat_uid = ?, title = ?, mobile = ?, phone = ?, description = ?, created_at = ?' args [02e98b69-df0e-4f35-a667-c5a27ac925e9, 35.73528356437848, 51.487202763671874, b5671816-1e48-4c80-a2e1-c6700d4f5dc2, ubbj, 666666, 6633, htyh, 1616010052, 02e98b69-df0e-4f35-a667-c5a27ac925e9, 35.73528356437848, 51.487202763671874, b5671816-1e48-4c80-a2e1-c6700d4f5dc2, ubbj, 666666, 6633, htyh, 1616010052]}
E/flutter (15938): #0      wrapDatabaseException
package:sqflite/src/exception_impl.dart:11
E/flutter (15938): <asynchronous suspension>
E/flutter (15938): #1      BasicLock.synchronized
package:synchronized/src/basic_lock.dart:34
E/flutter (15938): <asynchronous suspension>
E/flutter (15938): #2      SqfliteDatabaseMixin.txnSynchronized
package:sqflite_common/src/database_mixin.dart:346
E/flutter (15938): <asynchronous suspension>
E/flutter (15938): #3      _ExecutorWithQueryDelegate._synchronized
package:moor/…/helpers/engines.dart:25
E/flutter (15938): <asynchronous suspension>
E/flutter (15938): #4      InsertStatement.insert.<anonymous closure>
package:moor/…/statements/insert.dart:70
E/flutter (15938): <asynchronous suspension>
E/flutter (15938): #5      InsertStatement.insert
package:moor/…/statements/insert.dart:69
E/flutter (15938): <asynchronous suspension>
E/flutter (15938): #6      PersistUserLocationInfoViewModel.saveUserInfoLocation
package:easy_life/…/persist_user_location_info/persist_user_location_info_view_model.dart:46
E/flutter (15938): <asynchronous suspension>
E/flutter (15938):

```

```
I am using `  moor_flutter: ^3.1.0` and  `moor_generator: ` . and my flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)

• No issues found!
```
Additionally I have a moor file for this table:
```
import'package:easy_life/database/location_tb.dart';

CREATE INDEX location_uuid_index ON location_tables (location_uuid);
```

And I added moor file to database class :

```
@UseMoor(include: {
  'index.moor'
}, tables: [
  LocationTables,
  LocationCategories,
], daos: [
  LocationDao,
  LocationCategoriesDao,
])
class Database extends _$Database {
  Database()
      : super(FlutterQueryExecutor.inDatabaseFolder(
            path: 'db.sqlite', logStatements: true));
  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async {
          return m.createAll();
        },
        onUpgrade: (migrator, from, to) async {},
        beforeOpen: (details) async {
          await customStatement('PRAGMA foreign_keys = ON;');
        },
      );
}
```

**Comment by simolus3** [comment]
Interesting! I'm wondering if that device uses an old sqlite3 version without support for upserts. The minimum required sqlite version is 3.24.0, released on 2018-06-04. Can you run and print a custom query with `select sqlite_version();` to find out?

If it turns out to be because of an old version, I think the only way around that is to use `sqlite3_flutter_libs` together with the `moor/ffi.dart` library. It uses `dart:ffi` to bind to an sqlite3 version you ship with your app, instead of using the one from the OS.

**Comment by TaifRaoof** [comment]
Moor: Sent SELECT COUNT(chats.total_unread) FILTER (WHERE chats.is_active = ?) AS "c0" FROM chats; with args [1]
 
E/SQLiteLog( 8884): (1) near "AS": syntax error in "SELECT COUNT(chats.total_unread) FILTER (WHERE chats.is_active = 1) AS "c0" FROM chats;"

this error appear to my when i used emulator with android version 30 and also appear to me when i used my phone Samsung Note8.

so, **How  use sqlite3_flutter_libs together with the moor/ffi.dart in pubspecl file** 
i used 
```
  moor: ^4.2.0
  moor_flutter: ^4.0.0-nullsafety
  sqflite: ^2.0.0+3
  sqlite3_flutter_libs: ^0.4.1
```
Note : 
this way i used to open connection 
` AppDatabase() : super(FlutterQueryExecutor.inDatabaseFolder(path: 'db.sqlite', logStatements: true));
`

**Comment by simolus3** [comment]
The filter syntax was added in sqlite version `3.30.0`, released on 2019-10-04. That's still fairly recent considering Android's pace of keeping up with things, [it looks like](https://android.googlesource.com/platform/external/sqlite/+/refs/heads/android11-release/README.version) Android 11 ships version `3.28.0`.

There's some documentation on how to migrate from `moor_flutter` to `moor/ffi` [here](https://moor.simonbinder.eu/docs/other-engines/vm/#migrating-from-moor_flutter-to-moor-ffi).

**Comment by tazik561** [comment]
> Interesting! I'm wondering if that device uses an old sqlite3 version without support for upserts. The minimum required sqlite version is 3.24.0, released on 2018-06-04. Can you run and print a custom query with `select sqlite_version();` to find out?
> 
> If it turns out to be because of an old version, I think the only way around that is to use `sqlite3_flutter_libs` together with the `moor/ffi.dart` library. It uses `dart:ffi` to bind to an sqlite3 version you ship with your app, instead of using the one from the OS.

After replacing moor-flutter with moor/ffi.dart now sqlite version is 3.34.1 and On my Samsung A31 my problem is gone . I just replace 
```
  moor: ^3.0.0
  sqlite3_flutter_libs: ^0.4.1 
```
instead of 
`moor_flutter: ^3.1.0`

and replace all  `import 'package:moor_flutter/moor_flutter.dart';` to `import 'package:moor/ffi.dart'`

**Comment by vaibhiarora03** [comment]
@tazik561 was your app in production when you migrated from `moor_flutter` to `moor`? Did you faced any issues?

**Comment by tazik561** [comment]
> @tazik561 was your app in production when you migrated from `moor_flutter` to `moor`? Did you faced any issues?

I do not try in production yet but in developing and testing mode I didn't  faced with any error

**Comment by vaibhiarora03** [comment]
Okay. So you just changed the packages in pubspec.yaml and updated your database connection.

**Comment by tazik561** [comment]
> Okay. So you just changed the packages in pubspec.yaml and updated your database connection.

yes, I mentioned here https://github.com/simolus3/moor/issues/1106#issuecomment-805645479

**Comment by vaibhiarora03** [comment]
Okay. Thanks

**Comment by zakihou** [comment]
iam workin with sqflite: ^2.2.8+4
i have erro in  near "ON": syntax error
E/flutter ( 9325): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DatabaseException(near "ON": syntax error (code 1): , while compiling: INSERT OR REPLACE INTO paycode  

pleass hellp me!!!!
