### ISSUE TITLE
@required annotation in data class constructor

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#111]
I like using data classes instead of companions for my insert functions to help denote which fields are required, but it looks like [nullability](https://github.com/simolus3/moor/blob/master/moor_generator/lib/src/writer/data_class_writer.dart#L26) is the only determining factor when deciding whether to generate a `@required` annotation. Would it be possible to also check if the column is rowid or alias (#112), AUTOINCREMENT or has a default value, similar to the logic in `GeneratedColumn.required`?

**Comment by simolus3** [comment]
I feel like the best approach here is to make companions easier to use. Data classes are designed to hold a full row with all data, which is the reason we only omit the `required` annotation on nullable columns. 
I see how data classes provide better hints on which fields are required, but the concept of using null to indicate absent values will only get worse in future Dart versions that have NNBD. By then, we'd have to explicitly make columns that are optional for inserts nullable, which would give the wrong nullability for select statements.

> Would it be possible to also check if the column is rowid or alias (#112), AUTOINCREMENT or has a default value, similar to the logic in `GeneratedColumn.required`?

Better guidance on which fields are required during insert is the only use case for this, right? How about an additional constructor on the companion class (say `MyTableCompanion.insert`) where values which need an explicit value during inserts are marked `@required`? We also wouldn't have to use `Value`-wrappers in that case:
```dart
class Things extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get foo => integer().withDefault(const Constant(42))();
  TextColumn get bar => text().nullable()();
  TextColumn get baz => text();
}

// generated constructor can now have this signature:
ThingsCompanion.insert({
  @required String baz,
  @required this.id = const Value.absent(), 
  // all other values would be formal initializers to Value.absent() as well  
}): this.baz = Value(baz);
```

**Comment by Mike278** [comment]
Yeah good point, the signature of a row can be different for reading vs writing so it definitely makes sense to keep that separate with data classes and companions.

> Better guidance on which fields are required during insert is the only use case for this, right?

Yeah exactly - I'd just like some way to statically determine what the minimum required fields are to not violate any constraints. The `Companion.insert` constructor could work, although in your example I'd expect it to look something like:
```dart
ThingsCompanion.insert({
  this.id = const Value.absent(), 
  this.foo = const Value.absent(), // maybe even Value(42)? Probably best to let the database do this though
  this.bar = const Value.absent(),
  @required String baz,
}): this.baz = Value(baz);
```

For me, the main downside of this approach is that it's still the same `ThingCompanion` type, so you wouldn't be able to take advantage of it when writing something like:
```dart
 Future<int> insertThing(ThingCompanion insert) {
    // hopefully the caller used ThingCompanion.insert()!
  }

 Future<int> updateThing(int thingId, ThingCompanion updates) {
    // ...
  }
```

**Comment by simolus3** [comment]
> For me, the main downside of this approach is that it's still the same `ThingCompanion` type, so you wouldn't be able to take advantage of it [...]

It's true that we can't verify this statically, but we would fail early and provide help by throwing an `InvalidDataException`, so users are very likely to catch this during development. To get proper static warnings, we'd have to introduce another type just for inserts. IMHO the additional generated code is not worth the benefit here. For almost all cases, it's clear which methods perform inserts vs updates, so it's intuitive to just use the insert constructor when calling these methods.

**Comment by simolus3** [comment]
I think generating an additional `insert` constructor is fine, it's fairly straightforward to generate and it won't be a lot of code. For people who really want less generated code, I think we can make some less-used features (like the builtin json serializazion or overridden equals/hashCode/toString in data classes) opt-out instead.
> I'd probably write a custom insert statement and use the sqlparser to generate a method with exact arguments to achieve more strict inserts

Speaking of that, we can't parse insert statements yet. I hope I get to do that soon, they could really help verify that all required columns are present.

**Comment by simolus3** [comment]
We can now parse insert statements and generate appropriate implementations. We also generate a named "insert" constructor for each companion.
