### ISSUE TITLE
Missed space in warning message

### ISSUE THREAD

**Issue by ycherniavskyi** [simolus3/moor#1111]
Currently warning message:
```
WARNING (moor): It looks like you've created the database classAppDatabase multiple times. When these two databases use the same QueryExecutor, race conditions will ocur and might corrupt the database. 
Try to follow the advice at https://moor.simonbinder.eu/faq/#using-the-database or, if you know what you're doing, set moorRuntimeOptions.dontWarnAboutMultipleDatabases = true
```

But instead `classAppDatabase` I think must be `class AppDatabase` 😊.

Here the string part without space:
https://github.com/simolus3/moor/blob/3be88813d639bde14d8f9986fec8516465680f39/moor/lib/src/runtime/api/db_base.dart#L80

**Comment by simolus3** [comment]
Thanks for the report! I've fixed this in 3eb6b75bcf4b032a7a93a0d65e2b706ae23c94ee.
