### ISSUE TITLE
Null safety issue with custom_select

### ISSUE THREAD

**Issue by philip-dakno** [simolus3/moor#1114]
I have a couple custom queries stored in moor files that use SQL aggregate functions. I've noticed those queries will fail when the tables are empty when running under nullsafety. I think this is because `custom_select.dart` is attempting to cast a validly null values, like a MAX() on an empty table, into a non-nullable type. It almost seems like all of read method for QueryRow should return nullable types. I updated a local version of moor and it seemed to resolve the issues, but I could have caused other issues I'm unaware of. Any advice would be appreciated.

**Comment by simolus3** [comment]
This is a pretty severe issue, thanks for bringing it up (and shame on me for not catching it with tests). I've fixed this in 401b4d365046f64698a9036479e02e26328b0987, I'll publish a new version of `moor_generator` with that fix soon.

**Comment by philip-dakno** [comment]
That commit fixes all of the queries that were breaking for me.

**Comment by simolus3** [comment]
Thanks for the confirmation! I've just published version 4.2.1 of `moor_generator` which contains the fix.
