### ISSUE TITLE
Rowid aliases should always be non-nullable

### ISSUE THREAD

**Issue by simolus3** [simolus3/moor#1128]
Reported by @davidmartos96 on Gitter:

>While migrating to null safety I've just found out that for one of my tables in the moor file I did `INTEGER PRIMARY KEY`. That generates a nullable id in the moor DataClass. Shouldn't it be non null? Integer primary keys get assigned an id automatically when inserted with null, but for that we have the companions, or not?
Also, INTEGER PRIMARY KEY Is an alias for ROWID so maybe it should be treated as non null for that reason as well.

I think this is caused by a misunderstanding from my side :D We do recognize aliases for rowid already, but I didn't realize that this implies the column being non-nullable:

```sql
CREATE TABLE x (id INTEGER PRIMARY KEY);
INSERT INTO x DEFAULT VALUES;
INSERT INTO x VALUES (null) -- still works! even though id is non-nullable
SELECT * FROM x; -- yields 1 and 2
```

> but for that we have the companions, or not?

Correct. But it looks like moor should already recognize that column as not being required for inserts here. We just failed to make it non-nullable.

**Comment by simolus3** [comment]
This should be fixed with the referenced commit.

**Comment by davidmartos96** [comment]
Great! As always, thanks! 😄
