### ISSUE TITLE
Option to make all named parameters required?

### ISSUE THREAD

**Issue by PiN73** [simolus3/moor#1132]
First, thank you for `named_parameters` option! It makes using queries from .moor files more clear and safe (I mean change of parameters order won't break things). 

## Context

After [6aa022e(diff)](https://github.com/simolus3/moor/commit/6aa022e547b82155bb461fb44122f6764f2ae27b#diff-4df9a31c3706b4d1eda7f1a6a158dc09ca812e464d6089c974ed8f85fdc7dabb) nullable named parameters became non-required.

## Use case

I have a table with nullable column:
```sql
CREATE TABLE product (
    id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    category INT
);
```

and want to query items in any given category, including uncategorized (null):
```sql
getProducts:
    SELECT * FROM product
    WHERE
        CASE WHEN :category IS NULL THEN
            category IS NULL
        ELSE
            category = :category
        END;
```

Then the generated function will have signature:
```dart
Selectable<ProductData> getProducts({int? category})
```
which could potentially lead to mistake in complex queries with many parameters. One could forget to pass all parameters, and nothing will signal about it.

## Solution I'd like

It would be great to have a build option to make all named parameters required.

**Comment by simolus3** [comment]
I see how that query could benefit from `category` being required, but I'm not sure if making all parameters required is the ideal solution here.

Maybe we could add an opt-in hint?

```sql
getProducts (REQUIRED :category):
    SELECT * FROM product
    WHERE
        CASE WHEN :category IS NULL THEN
            category IS NULL
        ELSE
            category = :category
        END;
```

The `REQUIRED` modifier would always make the Dart parameter required.

**Comment by PiN73** [comment]
Thank you for the answer.

This hint may help too if one will declare all query variables in headers like
```
getProducts (REQUIRED :category AS INT OR NULL):
```

Possible limitations I see are

1. The fact that all used variables are declared in header isn't checked. This may lead to inconsistent code IMHO

2. Types will be typed by user and won't be checked, e.g.:

```
getProducts (REQUIRED :category AS TEXT OR NULL):
```
won't give warnings. More on this in https://github.com/simolus3/moor/discussions/1133

**Comment by PiN73** [comment]
And another benefit from global option is that it's easy to implement and maintain IMHO: https://github.com/simolus3/moor/compare/develop...PiN73:named-required

**Comment by simolus3** [comment]
This is now done on `develop` - I opted for the `REQUIRED` syntax in moor files to keep some syntactic resemblance to Dart.

**Comment by PiN73** [comment]
Thank you for `REQUIRED`!

What do you think about this?
>     1. The fact that all used variables are declared in header isn't checked. This may lead to inconsistent code IMHO
> 
>     2. Types will be typed by user and won't be checked, e.g.:
> 
> 
> ```
> getProducts (REQUIRED :category AS TEXT OR NULL):
> ```
> 
> won't give warnings. More on this in #1133

**Comment by simolus3** [comment]
Adding warnings about unexpected types should be possible (it shouldn't even be much work with the current code), but I'm a bit skeptic if the current type inference is good enough to avoid false positives. I'll try to running that over some of my own code using moor and see how much comes up.

**Comment by PiN73** [comment]
You're saying type inference can't fully check parameters' types at the moment. Then it'd be safer to not specify parameters' types and let them be inferred. But if one don't specify parameters, they can't be made required at the moment. So I propose a simple global option for this in #1242

**Comment by simolus3** [comment]
Thanks for your contribution! But it looks like `REQUIRED` can be independent of the variable type? You can use `(REQUIRED :variable)` as an annotation and it should work.

One downside of the global option is that we may need a way to opt-out? E.g. if you specifically _don't_ want a named parameter to be required, how would that work then?

**Comment by PiN73** [comment]
Didn't know that `(REQUIRED :variable)` will work, thanks.

One remaining problem that there is no way to check if I don't forget to declare all variables.

What about the global option, opt-out is easy. If the option value is false (default), nothing will be changed. So the generation will continue work as is

**Comment by simolus3** [comment]
Yeah I'm mainly thinking about what should happen if I want most variables to be required (so I'd use the option), but then I have one variable that I don't want to be required for some reason. We wouldn't have a mechanism to express that then, but I reckon that's not a particularly common scenario either...

**Comment by PiN73** [comment]
Ah, I understand now.

Personally I have some intermediate class between database and flutter widgets. This class contains requests to database class generated by moor. So if in some cases one parameter can be null, I explicitly pass null to it from my intermediate class.

**Comment by PiN73** [comment]
For example, let moor generated db class has
```dart
Selectable<ProductData> getProducts({required int? category})
```

1. If widgets needs two separate queries, `AppDb` can have two functions:

```dart
Future<ProductData> getAllProducts() =>
  _moorDb.getProducts(category: null).get();

Future<ProductData> getProductsInCategory({required int category}) =>
  _moorDb.getProducts(category: category).get();
```

2. If widgets need one query with category specified or not, the query can be used as is:
```dart
class QueryParams {
  final int? category;
}

Future<ProductData> getProductsInCategory(QueryParams params) =>
  _moorDb.getProducts(category: params.categry).get();
```

**Comment by simolus3** [comment]
Fair enough, I think we could have a build option for this!
