### ISSUE TITLE
Can moor update table by json data?

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#1135]
i.e.  When I update **notes** table, I have to specify explicitly which fields to be updated. 

Is it possible to use json format to update table? For instance, the following json, I specify fields **name** and **age** to tell sqlite to update **ONLY** the two fields. 

I need this, because, the server responds json to me, and tell me which fields of a table are updated. I hope to update local sqlite with the json from server directly. Thanks.

```javascript
{'name':'jim', 'age':18}
```

```dart
Future<int> setNoteDeletedStatus({@required int noteId, bool isDeleted = true}) {
	return (update(notes)..where((e) => e.id.equals(15)))
	.write(NotesCompanion(isDeleted: Value(isDeleted)));
}
```

**Comment by simolus3** [comment]
Moor doesn't have anything builtin for this. You could convert your map to a [`RawValuesInsertable`](https://pub.dev/documentation/moor/latest/moor/RawValuesInsertable-class.html) though, which allows you to pass a map from column names to their respective value. Instances of that class can be used in update statements.
