### ISSUE TITLE
Category import conflict on generated my_database.g.dart

### ISSUE THREAD

**Issue by stillie** [simolus3/moor#1137]
I am using a dart class that is called Category and when I am trying to retrieve a List<Category> from the database, I get the following error in the my_database.g.dart file:

`The name 'Category' is defined in the libraries 'package:flutter/src/foundation/annotations.dart' and 'package:networking/src/data/entities/category/category.dart (via package:networking/networking.dart)'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports.`

One way to fix this issue is by renaming my Category file to something else, i was wondering if there is a way to overcome this without having to rename my category file?

If you need an example project you can find one here:

https://github.com/stillie/moor_category_bug

`flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-ZA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2020.2.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.55.1)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.`

**Comment by simolus3** [comment]
Thanks for providing a repo. I don't think this is a moor specific problem, but you can fix it by using a hide directive or named imports. If you're not using the `Category` class from flutter, you could simply use

```dart
import 'package:flutter/foundation.dart' hide Category;
```

If you want to use both classes, you could use

```dart
import 'package:flutter/foundation.dart' as foundation;
import 'category.dart';
```

and then refer to the Flutter class as `foundation.Category`.

**Comment by stillie** [comment]
The problem is that i am getting the error in the generated class and am not sure on how I can avoid the error without manually modifying the generated class? Do you have any ideas?

**Comment by simolus3** [comment]
> The problem is that i am getting the error in the generated class

Ah, I see! In that case you can just use the `hide` directive in the import because it also applies to part files (like the one generated by moor).
