### ISSUE TITLE
perhaps missing tables when declaring tables in dart file and meanwhile not mentioning it in .moor file

### ISSUE THREAD

**Issue by Guoyuer** [simolus3/moor#1138]
Here I declare three tables in the base.dart and mention two of them (except ```units```) in .moor file. But the generated .g.dart file only contains two tables (no units table). 

If I add a SQL in .moor file to add an index on some column --- a way to mention it in .moor file --- in the units table, then the generated base.g.dart contains this table.

**base.dart**
```
import 'package:moor_flutter/moor_flutter.dart';

part 'base.g.dart';

class Events extends Table {
  IntColumn get id => integer().autoIncrement()();

  RealColumn get sumVal => real().withDefault(Constant(0))();
}

class Records extends Table {
  IntColumn get id => integer().autoIncrement()();

  IntColumn get eventId => integer()();

  RealColumn get value => real().nullable()();
}

class Units extends Table {
  IntColumn get id => integer().autoIncrement()();
}

@UseMoor(include: {'customizedSQL.moor'})
class AppDatabase extends _$AppDatabase {
  AppDatabase()
      : super(FlutterQueryExecutor.inDatabaseFolder(
            path: "db.sqlite", logStatements: true));
}

```

**customizedSQL.moor**
```
import 'base.dart';

create trigger addVal after insert on records when id = NEW.event_id BEGIN update events set sum_val = sum_val + NEW.value; END;
```
overview of the .g.dart file:
![image](https://user-images.githubusercontent.com/32631191/114348415-10daac00-9b99-11eb-92ab-06e92587bddc.png)

**Comment by simolus3** [comment]
Thanks for the report and the reproducible example! This actually only happens if the tables are defined in the same file as the database, everything else should be fine.

I've fixed in this in 51d5ada5c93a890da920b5c6bc10ed2be3e802ef, which will be part of the next moor release.
