### ISSUE TITLE
Is there a way to add method/mixin to entity class?

### ISSUE THREAD

**Issue by Elvis5566** [simolus3/moor#114]
It's really useful if we can add method/mixin to entity classes.
However, in current design, entity classes are generated, which we cannot modify it.
Do you think if we can declare table using annotation would be a better idea? like [jaguar_orm](https://github.com/Jaguar-dart/jaguar_orm) does.
or is there a way we can achieve similar effects?

Thank you

**Comment by simolus3** [comment]
This is not planned at the moment. A common way to achieve this would be to write a domain model class and map that from and to moor entity classes. This is what I'm doing for more complex apps where I use moor. Writing own classes that inherit from the classes generated by moor might be another idea where you save the mapping step from your own classes to moor. (You would still have to write a method to turn a response from moor to your subclass)

**Comment by Elvis5566** [comment]
The subclass way seems easier.
Thank you for such a great project and extremely fast response. :)

**Comment by simolus3** [comment]
Thanks, and I'm glad to help! I've never used the subclass approach, let me know if you run into problems. I'll keep this issue open either way to track a "proper" way to do this with moor.

**Comment by minh98** [comment]
any update ?

**Comment by simolus3** [comment]
This is not a priority for me at the moment. However, maybe we can try to work out how an api for this could look like, I'll then see how much work would be required to add that feature to moor.

To reduce the complexity, we would probably still require users to write table classes:
```dart
@MapTo(User)
class Users extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  // ... some other columns
}
class User with _$UserMixin { // moor would write the `_$UserMixin` for you.
  final int id;
  @FromColumn('name')
  final String userName;
  // other fields
  User(this.id, this.userName);
}
```

I think we can require the constructor to only consist of field initializing formals (`this.x`), and all columns must be present. Even if a custom class is used, we should probably still write companion classes for updates and inserts.

**Comment by Elvis5566** [comment]
I've made some changes to support this feature in [my branch](https://github.com/Elvis5566/moor), here is [example app](https://github.com/Elvis5566/trial_moor)
You can declare table by entity class like this: 
```dart
@JsonSerializable(includeIfNull: false)
class User extends DataClass with DirtyColumn implements Insertable<User> {
  // you can also declare column in mixin.
  User();

  @EntityPrimaryKey() // declare primary key
  String id;

  @EntityColumn(isNullable: true) // declare column
  @JsonKey(ignore: true) // you can use json_serializable to ignore column.
  String name;

  @EntityColumn(isNullable: true, converter: PreferenceConverter) // column with converter.
  Preference preference;

  @EntityToOne(AddresssDao, isNullable: true) // relation to another table.
  Address address;

  @override
  Map<String, dynamic> toJson() => _$UserToJson(this);

  @override
  T createCompanion<T extends UpdateCompanion<User>>(bool nullToAbsent) => _$createCompanion(this, nullToAbsent) as T;

  @override
  String toString() => toJsonString();
}

@UseDao(entity: User)
class UsersDao extends DatabaseAccessor<VDDatabase> with _$UsersDaoMixin {
  UsersDao(VDDatabase db) : super(db);
}
```
then add daos to db.
```dart
@UseMoor(daos: [UsersDao, AddresssDao])
class MyDatabase extends _$VDDatabase {
  MyDatabase() : super(FlutterQueryExecutor.inDatabaseFolder(path: 'db.sqlite'));
}
```
I also added helper methods like upsert/ loadAll/ load to daos, so you don't need to write basic queries for every tables.

with @EntityToOne you can also auto save/join referenced object.
for example, say we have Todo and Category, and Todo has relation to Category.
You can write something like
```dart
final category = Category()
                          .. description = 'text';
final todo = Todo()
                 ..title = 'shopping'
                 ..category = category;

db.todos.upsert(todo); // upsert will save category as well;

db.todos.loadAll(); // Todo instances will auto join Category.

```
You can also write where predicate with symbol like this:
```dart
do.todos.loadAll(where: (t) => (t.name.equals('shopping') & t.content.equals('budget 200') | t.name.equals('work'))
```
I just tried to make minimum changes to get things work, it might breaks some of your design.
for example:
1. Export Join for auto join.
2. Export Expression for some cases that I need to write general predicate.
3. Add &, | to Expression. I think it should be added in something like BoolExpression, but it's too hard for me to do so.
4. I assumed tables will not have composite key for auto join.
5. Replace build in json serializer with JsonSerializable

These features are quite useful in my case, I hope this save your time if you think it's suitable for moor.

**Comment by simolus3** [comment]
Wow, that looks amazing! I probably won't be able to take a detailed look into your code until next weekend, but I think it could provide a helpful addition to moor :+1: 
I made some major changes to the generator recently, but if you open a PR to the `develop` branch (even if your version has conflicts), I would gladly help resolve these and the remaining issues with `BoolExpression`.

**Comment by Mike278** [comment]
I think [Dart's new extension methods](https://github.com/dart-lang/language/issues/41#issuecomment-539251446) will be another great way to approach this.

**Comment by outrelouxhe** [comment]
This would be great if this feature was added to Moor. Do you have any update on this? Thank you!

**Comment by kuhnroyal** [comment]
I was trying to misuse a `MAPPED BY const FooConverter()` in order to select some other entity from the database by ID. But the converter can not be async.

Maybe something similar can be implemented, like `SELECTED BY JOIN foo on foo.ID = ID`.
Not sure how this could look in Dart classes.

**Comment by fnicastri** [comment]
This feature would allow to avoid to have duplicate models in the same app.

**Comment by ozburo** [comment]
@Elvis5566 Nice 👍 

What we really need are those reverse foreign key accessors like you've got there `@EntityToOne`.

**Comment by fgblomqvist** [comment]
Tried going with the approach suggested by @Mike278 and it was quite smooth, however, if you have your tables defined in separate files (like I do) you end up with circular dependencies (assuming you define the extension methods in your table files) since the data class is stored in the (generated) database.dart.

So, instead, I ended up making my table files `part of '../database.dart'` which is not ideal but it works, it looks clean, and it avoids any awkward import issues for now until moor has support for declaring methods on the data classes (the mixin method that @simolus3 suggested makes sense I think, since that also moves the data classes into the table files which is a win-win).

**Comment by doppio** [comment]
@Elvis5566's solution is really nice. Having more control over the data classes would be really useful to eliminate the need to map between a domain class and the generated entity class. @simolus3 have you considered this any further?

**Comment by Elvis5566** [comment]
@doppio 
We’ve discussed this issue long time ago.
I am supposed to add an orm library based on moor, but I am quite busy these days and shit happens.
Need more time to implement it.

**Comment by feltcorgi4114** [comment]
Since extension methods have been introduced in Dart, given that we have a `DataClass` `User` we could do something like this,
```Dart
part of 'database.dart';

extension AuthenticateUser on User {
  bool authenticate(String checkPassword) {
    return password == checkPassword;
  }
}
```
and call it like this,
```Dart
// Given that user is already initialised as a [User]
user.authenticate('Some random password');
```
I think this is a better solution, as we don't have to deal with any lower level stuff, and our code remains maintainable and readable.

This example is very basic, but this way, the method can be accessed directly from the data class. This solution works great for me! 

More on extension methods here 👉: https://dart.dev/guides/language/extension-methods#implementing-extension-methods

**Comment by micimize** [comment]
One pain point here is that data classes don't follow the class hierarchy of tables, making it difficult to extract common helper logic (i.e. if every record is immutable and all "updates" should be "update/inserts"

**Comment by gloryluu** [comment]
I really would love to have this functionality @simolus3 . In general, I deal with this problem by create 1:1 mapping between the entity and the model.

**Comment by simolus3** [comment]
Thanks for the interest everyone, and sorry for the slow progress so far.

I think that I've now found an interesting idea that's fairly simple to implement in moor while allowing custom data classes: https://github.com/simolus3/moor/issues/1134. The basics of that are implemented already, but I'll need to do put in more work and properly document it to make it stable. Moor does not assume any control over custom data classes, so you can add additional methods or superclasses as you see fit.

From my view, that issue represents the solution to this original feature request, but it does not cover async crawling of relations. While a more complex ORM with those features can be built on top of moor (as @Elvis5566's awesome work has shown!), I still believe that it shouldn't be part of the core moor package.

**Comment by MazetDev** [comment]
Any update ?

**Comment by simolus3** [comment]
@MathieuPaillart This issue has been resolved with the [custom row classes](https://drift.simonbinder.eu/docs/advanced-features/custom_row_classes/) feature. Are you looking for something else not covered by that?

**Comment by MazetDev** [comment]
I am so blind. I had opened the link but closed it somehow. Thank you I'll try it :D
