### ISSUE TITLE
Maven project eu.simonbinder sqlit3-native-library v3.32.3 not found

### ISSUE THREAD

**Issue by not-Ian** [simolus3/moor#1143]
Moor is pointing to a maven library `eu.simonbinder sqlit3-native-library v3.32.3`. It isn't on the maven repository website anymore and is causing an issue:

https://mvnrepository.com/artifact/eu.simonbinder/sqlite3-native-library

Is there an easy fix to this that we're not seeing? Moor has to point to a newer version (3.34.1 or 3.35.0) of the package, right?

Thanks. Otherwise Moor is great  :)

**Comment by simolus3** [comment]
Thanks for the report. It should actually be the `sqlite3_flutter_libs` package pointing towards that maven dependency, if you're using version 0.4.1 or later it should work. Older versions were hosted on bintray which has been shut down in the meantime.
