### ISSUE TITLE
Allow debugging of query plans

### ISSUE THREAD

**Issue by derolf** [simolus3/moor#1145]
It would be nice to have a flag/feature/function that allows to EXPLAIN QUERY PLAN of a select statement.

**Comment by simolus3** [comment]
Hm, I'm not really sure how this would work best (mainly from a usability perspective). Should we just print the query plan for each select running when a flag is set? FWIW it looks like you can run a `customSelect` with the `EXPLAIN QUERY PLAN` and get a reasonable result.

**Comment by simolus3** [comment]
I'll close this in favor of #1330 because that one seems to be more actionable.
