### ISSUE TITLE
flutter question : migrate null-safety moor 4.2.1

### ISSUE THREAD

**Issue by park1120** [simolus3/moor#1150]
I got this message during my migration to flutter 2.0

Because moor_generator >=1.4.0 depends on build_config >=0.3.1 <1.0.0 and build_runner >=2.0.0 depends on build_config >=1.0.0 <1.1.0, moor_generator >=1.4.0 is incompatible with build_runner >=2.0.0.

is there any way to resolve this?

Thanks

**Comment by DevKang** [comment]
Same Issue here!

**Comment by kuhnroyal** [comment]
Try to override `build_runner` to the last version before `2.0.0`

**Comment by simolus3** [comment]
I have just published version 4.2.2 of `moor_generator` which should support the latest `build_config` package.

**Comment by park1120** [comment]
Thank you for your rapid response
​
​
-----Original Message-----
