### ISSUE TITLE
"Database already closed" error in unit test expect()

### ISSUE THREAD

**Issue by m-terlinde** [simolus3/moor#1155]
Hey guys,

I'm having a hard time to do some unit tests.
If this is more suited for the discussions page, feel free to say so.

We are currently using moor 3.4.0 and moor_generator 3.4.1.

Basically, what I try to do is the following:
- Doing a unit test
- Create a new DAO object, using a in memory SQLite database
- Insert data into the DAO using an input method
- check, if everything runs without throwing an exception

This is some sample code (I'll omit the DAO class itself. if needed, just tell me):

```
test('Test insertFeedback of FeedbackDao on sane input', () async {
    FeedbackDao testDao = FeedbackDao(testDb);
    final testId = 'uuid';
    final testUserName = 'Some Name';
    final testFeedback = 1;
    final testTimestamp = DateTime.parse('1969-07-20T20:18:04');
    final testFeedbackText = 'Some Feedback!';

    var userFeedback = new UserFeedback(
        id: testId,
        userName: testUserName,
        feedback: testFeedback,
        timestamp: testTimestamp,
        feedbackText: testFeedbackText);
    expect(() async => await testDao.insertFeedback(userFeedback), returnsNormally);
  });
```

When I run this test, I'll run into a `Bad state: This database has already been closed` error in the debug console.

Full output is:
```Bad state: This database has already been closed
DatabaseImpl._ensureOpen
package:sqlite3/…/impl/database.dart:295
DatabaseImpl.execute
package:sqlite3/…/impl/database.dart:90
_VmDelegate._runWithArgs
package:moor/…/ffi/vm_database.dart:160
_VmDelegate.runCustom
package:moor/…/ffi/vm_database.dart:170
_ExecutorWithQueryDelegate.runCustom.<fn>
package:moor/…/helpers/engines.dart:79
_ExecutorWithQueryDelegate._synchronized
package:moor/…/helpers/engines.dart:25
_ExecutorWithQueryDelegate.runCustom
package:moor/…/helpers/engines.dart:76
QueryEngine.customStatement.<fn>
package:moor/…/api/query_engine.dart:301
QueryEngine.doWhenOpened.<fn>
package:moor/…/api/query_engine.dart:98
===== asynchronous gap ===========================
dart:async                                                               _asyncErrorWrapperHelper
InsertStatement.insertOnConflictUpdate
package:moor/…/statements/insert.dart:89
FeedbackDao.insertFeedback
package:somePrivatePackageName/…/user_feedback_curd/user_feedback_curd.dart:18
main.<fn>.<fn>
test\database\user_feedback_curd_test.dart:33
_ReturnsNormally.typedMatches
package:matcher/src/core_matchers.dart:153
FeatureMatcher.matches
package:matcher/src/feature_matcher.dart:16
package:test_api                                                         expect
main.<fn>
test\database\user_feedback_curd_test.dart:33
main.<fn>
test\database\user_feedback_curd_test.dart:17
2

✖ Test insertFeedback of FeedbackDao on sane input
Exited (1)
```

It seems to be a problem with the `except`. When I switch the last line of the first code block to `await testDao.insertFeedback(userFeedback);`, everything runs perfectly.
For the sake of it, I tried reading from the DAO in the same method later on and it works perfectly.

I believe there is something elementary, what I'm missing.

Any hint is much appreciated.

Thanks,
Matthias

**Comment by simolus3** [comment]
How do you close the database? In a `tearDown` block? Basically, I think what's happening here is

1. Your test code completes (since `expect` is a synchronous function)
2. Your `tearDown` handler is called, which closes the database
3. `insertFeedback` is called after an asynchronous delay

That schedule would explain the error you're seeing. In general, it's always a good practice to make sure that your test function doesn't leave some further async work behind. For asynchronous expectations, you can use `expectLater` for that:

```dart
await expectLater(() async => await testDao.insertFeedback(userFeedback), returnsNormally);
```

**Comment by m-terlinde** [comment]
Thanks for the fast reply!

Yes, you are right. I do it with tearDown:
```  setUp(() {
    testDb = AppDatabase.inMemory(VmDatabase.memory());
  });

  tearDown(() async {
    await testDb.close();
  });```

I had the strong believe, that tearDown waits.

I've switched my `expect()` line to your `expectLater()`, but it emits the error as well:

```Bad state: This database has already been closed
DatabaseImpl._ensureOpen
package:sqlite3/…/impl/database.dart:295
DatabaseImpl.execute
package:sqlite3/…/impl/database.dart:90
_VmDelegate._runWithArgs
package:moor/…/ffi/vm_database.dart:160
_VmDelegate.runCustom
package:moor/…/ffi/vm_database.dart:170
_ExecutorWithQueryDelegate.runCustom.<fn>
package:moor/…/helpers/engines.dart:79
_ExecutorWithQueryDelegate._synchronized
package:moor/…/helpers/engines.dart:25
_ExecutorWithQueryDelegate.runCustom
package:moor/…/helpers/engines.dart:76
QueryEngine.customStatement.<fn>
package:moor/…/api/query_engine.dart:301
QueryEngine.doWhenOpened.<fn>
package:moor/…/api/query_engine.dart:98
===== asynchronous gap ===========================
dart:async                                                    _asyncErrorWrapperHelper
test\database\user_feedback_curd_test.dart                    main.<fn>.<fn>
test\database\user_feedback_curd_test.dart:1
_ReturnsNormally.typedMatches
package:matcher/src/core_matchers.dart:153
FeatureMatcher.matches
package:matcher/src/feature_matcher.dart:16
package:test_api                                              expectLater
main.<fn>
test\database\user_feedback_curd_test.dart:33
main.<fn>
test\database\user_feedback_curd_test.dart:17
2

✖ Test insertFeedback of FeedbackDao on sane input
Exited (1)
```

**Comment by simolus3** [comment]
> I had the strong believe, that tearDown waits.

You're right, it does. The problem is that `expect` does not, so parts of your test and `tearDown` would run concurrently. 

I was wrong about `expectLater` though, the problem is the `returnsNormally` matcher. As you can see [here](https://github.com/dart-lang/matcher/blob/393f14d5c916a8f8417f1beb795eba40dfd3d375/lib/src/core_matchers.dart#L152-L157), it does not actually check for asynchronous errors. So it just sees that the async function returns a future and is happy with that. Meanwhile, the future keeps running and eventually hits the error. The `completes` matcher can be used to match a future that doesn't complete with an error, but it's a bit awkward to use with functions. I'd probably use it like this:

```dart
await expectLater(Future(() async => await testDao.insertFeedback(userFeedback)), completes);
```

IIRC, you don't even need `expectLater` in this case, since the test runner waits until all async matchers reported a result.

**Comment by m-terlinde** [comment]
You are my true hero of the week!

Honestly, this is amazing and makes me very happy. Wouldn't have found it on my own.

Everything works fine now, cross-tested it with:
```
  Future insertFeedback(UserFeedback feedback) =>
      throw new FormatException();
```

**Comment by zakihou** [comment]
iam workin with sqflite: ^2.2.8+4
i have erro in near "ON": syntax error
E/flutter ( 9325): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DatabaseException(near "ON": syntax error (code 1): , while compiling: INSERT OR REPLACE INTO paycode

pleass hellp me!!!!
