### ISSUE TITLE
Generate SQL raw query From SQLParser objects

### ISSUE THREAD

**Issue by MobiliteDev** [simolus3/moor#1156]
Hi,

I would like to create a project based on https://pub.dev/packages/sqlite3 and SQLParser.

Today, SQLParser takes a raw query and parse it to items, is the opposite feasible?

I would like to create a SQL Query through SQLParser objects, and next generate the raw SQL in order to execute it in sqlite3.

**Comment by simolus3** [comment]
Yes, this is possible! You can use the [node to text](https://pub.dev/documentation/sqlparser/latest/utils.node_to_text/NodeToText.html) library for this (in `package:sqlparser/utils/node_to_text.dart`). It converts any AST node to its SQL representation. Some AST nodes require a `Token` instance, you can just fill in a stub for that. Here's an example

```dart
import 'package:source_span/source_span.dart';
import 'package:sqlparser/sqlparser.dart';
import 'package:sqlparser/utils/node_to_text.dart';

void main() {
  final node = SelectStatement(
    columns: [
      StarResultColumn('foo'),
      ExpressionResultColumn(
        expression: BinaryExpression(
          NumericLiteral(
            123,
            _token(TokenType.numberLiteral),
          ),
          _token(TokenType.star),
          NumericLiteral(
            42,
            _token(TokenType.numberLiteral),
          ),
        ),
      ),
    ],
    from: TableReference('my_table', 'foo'),
  );

  print(node.toSql()); // SELECT foo.*, 123 * 42 FROM my_table AS foo
}

final _fakeSpan = SourceFile.fromString('').span(0);

Token _token(TokenType type) {
  return Token(type, _fakeSpan);
}
```

Is that what you're looking for?

**Comment by MobiliteDev** [comment]
It seems to be perfect, I will try soon.

Thank you
