### ISSUE TITLE
know database table name

### ISSUE THREAD

**Issue by MahdiPishguy** [simolus3/moor#116]
in this table definitions, whats my table name in `sqlite`? is this `User`? or `userTable`?

```dart
@DataClassName("User")
class UserTable extends Table{
  IntColumn get id =>integer().autoIncrement()();
  ...
}
```

**Comment by simolus3** [comment]
When not explicitly overridden, we use the `snake_case` of the class name, which would be `user_table` in your example. You choose a custom table name by overriding `tableName`:
```dart
@DataClassName("User")
class UserTable extends Table{
  @override
  String get tableName => 'users'; // table will now be called users
  IntColumn get id =>integer().autoIncrement()();
  ...
}
```

For more information, see the docs on [tableName](https://pub.dev/documentation/moor/latest/moor_web/Table/tableName.html). If you need to read the table name from Dart, you could use something like
```dart
@UseMoor(tables: [UserTable])
class Database extends _$Database {
  // constructor + schema version getter omitted
  String get sqlNameOfUserTable => userTable.actualTableName;
}
```

**Comment by MahdiPishguy** [comment]
@simolus3 i wish documentation better than with current version :)

for this issue i don't have any question, thanks
