### ISSUE TITLE
SharedDatabase instance for web (moor v4)

### ISSUE THREAD

**Issue by pashtostories** [simolus3/moor#1161]
**How to return SharedDatabase instance for web from `constructDb()`**

I followed [moor_shared](https://github.com/rodydavis/moor_shared) example and everything was working perfect until I updated moor to v4.

in web.dart file I was constructing SharedDatabase like this before:

web.dart

```
SharedDatabase constructDb({bool logStatements = false}) {
  return SharedDatabase(WebDatabase.withStorage(
      MoorWebStorage.indexedDbIfSupported('my_database'),
      logStatements: logStatements));
}

```
but after updating moor to v4 `MoorWebStorage` is now `Future`

`WebDatabase.withStorage(await MoorWebStorage.indexedDbIfSupported(name))`

how can I return the SharedDatabase without Future so that I can use constructDb() because for mobile constructsDb() returns simply SharedDatabase like this:

mobile.dart

```
SharedDatabase constructDb({bool logStatements = false}) {
  if (Platform.isIOS || Platform.isAndroid) {
    final executor = LazyDatabase(() async {
      final dataDir = await paths.getApplicationDocumentsDirectory();
      final dbFile =
          File(p.join(dataDir.path, 'my_database.sqlite'));
      return VmDatabase(dbFile, logStatements: logStatements);
    });
    return SharedDatabase(executor);
  }
  if (Platform.isMacOS || Platform.isLinux) {
    final file = File('my_database.sqlite');
    return SharedDatabase(
        VmDatabase(file, logStatements: logStatements));
  }
  if (Platform.isWindows) {
    final file = File('my_database.sqlite');
    return SharedDatabase(
        VmDatabase(file, logStatements: logStatements));
  }

  return SharedDatabase(
      VmDatabase.memory(logStatements: logStatements));
} 
```

**Comment by simolus3** [comment]
Unfortunately it looks like you'll have to make the `constructDb` function async as well. The reason for making `indexedDbIfSupported` return a future is that we can't reliably detect whether it is supported synchronously. IIRC, Firefox reports IndexedDb as being available in private browsing but then blocks all usages of it. So we have to attempt opening a database to make sure it all works, which we can't do synchronously.

I'll get a PR out to make Rody's example work with moor 4.

**Comment by simolus3** [comment]
Actually it looks like the moor_shared example doesn't use `indexedDbIfSupported` in the first place. But you can actually do this to get your database synchronously:

```dart
SharedDatabase constructDb({bool logStatements = false}) {
  final db = LazyDatabase(() async {
    return WebDatabase.withStorage(
      await MoorWebStorage.indexedDbIfSupported('my_database'),
      logStatements: logStatements)
    );
  });
  return SharedDatabase(db);
}
```

**Comment by pashtostories** [comment]
Thank you so much for really quick response. I'll let you know if this snippets works or not. God Bless you.
