### ISSUE TITLE
moor_generator incompatible with json_serializable

### ISSUE THREAD

**Issue by Fasuh** [simolus3/moor#1162]
I am currently unable to update the flutter nor packages versions but when i add `json_serializable` i cannot generate code for moor tables, it only generates json methods from `json_serializable`, classes are in separate files.

class example:
```
import 'package:moor_flutter/moor_flutter.dart';`

part 'texts.g.dart';

@DataClassName("Strings")
class Texts extends Table {
  TextColumn get id => text()();

  TextColumn get content => text()();
}
```
the class above doesnt generate the file named `texts.g.dart`

flutter version: 1.22.6
packages versions: 
``` 
  moor_generator: 3.4.0
  build_runner: 1.11.1
  json_serializable: 3.5.1
  ```

**Comment by simolus3** [comment]
Do you get any error messages from that? Can you run the build with `--verbose` and see if anything comes up?

**Comment by Fasuh** [comment]
Nothing shows there
```
[FINE] moor_generator:moor_generator on lib/db_model/texts.dart:Running MoorGenerator - 1 of 2
[FINE] moor_generator:moor_generator on lib/db_model/texts.dart:Running DaoGenerator - 2 of 2
...
[INFO] Build:Succeeded after 109ms with 0 outputs (0 actions)

```

**Comment by simolus3** [comment]
Just to be sure, `db_model/texts.dart` does contain a `@UseMoor` class, right? Moor only generates code for those files. Can you post a a full (small) project that reproduces this otherwise?

**Comment by Fasuh** [comment]
wait, so `texts.dart` has to be part of a file which contains `@UseMoor` ? if i understand correctly i can only use this annotation on the database classes, correct? does it mean that i cant have tables in separate files?

**Comment by simolus3** [comment]
You can declare tables in external files, but the generated data and companion classes currently go into the part file generated for the database. There's https://github.com/simolus3/moor/issues/490 to change that, but it likely requires changes to the Dart language (imports in part files) to work reliably.
