### ISSUE TITLE
JoinedSelectStatement unable to count

### ISSUE THREAD

**Issue by selvam920** [simolus3/moor#1163]
i have joined table, trying to count the record but there no method to select only count

  void addColumns(Iterable<Expression> expressions) {
    _selectedColumns.addAll(expressions);
  }

provide only one expression to select count only

**Comment by simolus3** [comment]
You can use

```dart
selectOnly(table)
  ..join([yourJoin(useColumns: false)])
  ..addColumns([yourTable.yourColumn.count()])
```

Is that what you're looking for?

**Comment by selvam920** [comment]
Yes, this only but query selected all the column in a table with count.
but i need only count

if you provide some examples in website, it will helpful to findout

**Comment by simolus3** [comment]
If you use `selectOnly` and the `useColumns: false` parameter on joins, it should not add all columns of the table. Can you post your query code to help me understand what's happening here?

**Comment by selvam920** [comment]
working thanks, pls update the documents with more example, difficult to find
