### ISSUE TITLE
Different result in android vs ios

### ISSUE THREAD

**Issue by MiguelSOliveira** [simolus3/moor#1168]
I'm trying to run the following query and I get different results in android vs ios. Is it maybe, because of the COALESCE not working in android? It does in IOS.

What I'm trying to solve is a problem where I want to create a third column where every row in the column, is a SUM of two other nullable columns, and since I can't add NULL, I want to replace all NULL values by zero, using coalesce (I also tried ifnull, which is the same as coalesce with 2 values and also does not work in android).

SELECT * FROM (select *, coalesce(X, 0) + coalesce(Y, 0) as F from Z ORDER BY F DESC) group by T ORDER BY F DESC;

**Comment by simolus3** [comment]
Interesting, are you using moor/ffi or `moor_flutter`?
