### ISSUE TITLE
Provide better error messages for unresolved references in custom queries

### ISSUE THREAD

**Issue by MahdiPishguy** [simolus3/moor#117]
i have this `query`:

```dart
queries: {
  'getUser':'SELECT * FROM userTable ORDER BY DESC LIMIT 1;'
}
```

and after rebuild in terminal i can't find class name as `GetUser`,

**Document:**

> After running the build step again, moor will have written the CategoriesWithCountResult class for you

which file have this class after rebuild successful? and i get this error:

`The sql query SELECT * FROM UserTable ORDER BY ID DESC LIMIT 1; is invalid: Error: AnalysisErrorType.referencedUnknownTable: The table User could not be found at Instance of 'TableReference'
`

because, i don't know whats table name

**Comment by simolus3** [comment]
You should be able to resolve this problem with #116, right?

Nevertheless, moor should really be more helpful here - it's not obvious how the tables are named in sql and the same thing applies to columns. 
I think making the generator catch `referencedUnknownTable` and `referencedUnknownColumn` and enhance the error message with information of what tables and columns are available could help here.

**Comment by MahdiPishguy** [comment]
i found it,

that was `user_table`

**Comment by simolus3** [comment]
Glad you could fix your problem! I'll keep this issue open until I've implemented the better error messages so I don't forget about it.

**Comment by simolus3** [comment]
There's still is a lot to improve on the error messages from the parser, but most `referencedUnknownTable` errors now provide a list of available queries. This improvement will be a part of the next moor version.
