### ISSUE TITLE
Fix warning - Allow abstract classes on moor generator

### ISSUE THREAD

**Issue by rubenferreira97** [simolus3/moor#1172]
**Is your feature request related to a problem? Please describe.**
In order to avoid code duplication (common fields on several tables) I managed to get the following code to handle abstraction:
```
abstract class CategoriesTable extends Table {
  IntColumn get id => integer()();
  IntColumn get parentId => integer().nullable()();
  TextColumn get title => text()();

  @override
  String get tableName;

  @override
  List<String> get customConstraints =>
      ['FOREIGN KEY(parentId) REFERENCES ' + tableName + '(id)'];

  @override
  Set<Column> get primaryKey => {id};
}

class OccurrenceCategoriesTable extends CategoriesTable {
  @override
  String get tableName => 'occurrence_categories';
}

class SocietiesCategoriesTable extends CategoriesTable {
  @override
  String get tableName => 'societies_categories';
}
```

```
[WARNING] moor_generator:moor_generator on lib/database/tables.dart:
line 12, column 14 of package:app_autarquias/database/tables.dart: This getter must return a string literal, and do nothing more
   ╷
12 │   String get tableName;
   │              ^^^^^^^^^
   ╵
```
The code seems to work even with the given warning, however it bloats the console and scares developers.
As a temporary fix I am implementing the tableName getter in `CategoriesTable` with a string literal 'categories', and it works as expected, however this breaks the concept of an abstract getter (need to implement on children).

**Describe the solution you'd like**
Run `flutter packages pub run build_runner build` without warnings.

**Comment by simolus3** [comment]
Good catch, I think we should just ignore an abstract `tableName` getter and treat the class as if it didn't declare one at all. I've fixed this on `develop`.
