### ISSUE TITLE
Migrations testing isn't working as expected

### ISSUE THREAD

**Issue by MiguelSOliveira** [simolus3/moor#1174]
I've opened a discussion about this already, but I believe this time is different. 

The problem:

When testing migrations and changing the same table, it appears that the migration uses the wrong schema_vX.json.. Not sure if I'm doing something wrong, but I've created a small repo that demonstrates my current problem: https://github.com/MiguelSOliveira/moor_bug

**Steps to reproduce**:
- Install dependencies as normal with `flutter pub get`
- `make build_db`
- `make test_bug`

Here is the outcome in the terminal:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/8149533/117053681-2747d380-ad11-11eb-9b65-53720be543aa.png">

It says:
`00:01 +0 -1: upgrade from v1 to v2 [E]
  SqliteException(1): no such column: third_col`

It can't find `third_col` when migrating from v1 to v2, but if we check the `moor_schema_v1`, `moor_schema_v2`, `schema_v1` and `schema_v2` they don't contain the `third_col`. This column was only added when v3 was generated...

This is not expected, right? It appears to be using the latest Database when migrating from v1 to v2.

Thank you!

**Comment by simolus3** [comment]
Thank you for the repro!

I think the source of the exception here is the use of `alterTable` when migrating from v1 to v2. Looking at the statements moor sends:

```
Upgrading v1 to v2
Moor: Sent PRAGMA foreign_keys = OFF with args []
Migrating v1
Moor: Sent BEGIN TRANSACTION with args []
Moor: Sent PRAGMA foreign_keys with args []
Moor: Sent SELECT type, name, sql FROM sqlite_master WHERE tbl_name = ?; with args [firstTable]
Moor: Sent CREATE TABLE IF NOT EXISTS tmp_for_copy_firstTable (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, first_col TEXT NOT NULL UNIQUE, second_col TEXT NOT NULL UNIQUE, third_col TEXT NOT NULL UNIQUE); with args []
Moor: Sent INSERT INTO tmp_for_copy_firstTable (id, first_col, second_col, third_col) SELECT id, first_col, 'test', third_col FROM firstTable; with args []
Moor: Sent ROLLBACK TRANSACTION with args []
``` 

As you can see, the table migration assumes that the third column is there.

> This is not expected, right? It appears to be using the latest Database when migrating from v1 to v2.

Yes, but that is expected. Your migration runs on the regular database with the regular generated code for the latest schema version, which is why it expects all three columns.
I've mainly envisioned the generated `schema_vX.dart` files as helpers for tests. They generate a clean reference schema that we can use as a starting point for migrations, which then run with the real database. They're also used to compare the result of a schema migration, ensuring that the schemas match.

But your approach of generating those files into `lib` is actually _very_ clever! Of course, you can also use the generated test helpers to write migrations with an older database version. For instance, I changed `lib/database.migrations.dart` to fix the test:

```patch
diff --git a/lib/database/migrations.dart b/lib/database/migrations.dart
index 4292a33..50fa581 100644
--- a/lib/database/migrations.dart
+++ b/lib/database/migrations.dart
@@ -2,6 +2,8 @@ import 'package:moor_flutter/moor_flutter.dart';
 
 import 'database.dart';
 
+import 'test/generated_migrations/schema_v2.dart' as v2;
+
 typedef MigrateFunction = Future<void> Function(Migrator, MoorDb);
 
 final Map<int, MigrateFunction> migrationsMap = {
@@ -12,8 +14,9 @@ final Map<int, MigrateFunction> migrationsMap = {
 Future<void> migrate1(Migrator migrator, MoorDb db) async {
   // ignore: avoid_print
   print('Migrating v1');
+  final oldDb = v2.DatabaseAtV2.connect(db.connection);
   await migrator.alterTable(TableMigration(
-    db.firstTable,
+    oldDb.firstTable,
     newColumns: [db.firstTable.secondCol],
     columnTransformer: {db.firstTable.secondCol: const Constant<String>("test")},
   ));
```

The generated schema tests don't do that by default (after all, they're supposed to test your regular database code), but I completely missed that they can also be used to easily write migrations on an older snapshot of the generated database code. Neat!

**Comment by MiguelSOliveira** [comment]
Thank you for the complement @simolus3 , means a lot coming from a person that I admire a lot for creating moor!
And also thank you for the thorough explanation and solution for my problem, I understand the behaviour now!

**Comment by MiguelSOliveira** [comment]
Just a quick question that came up, now that I'm messing around with this new approach Simon.

I get this error while running tests:

```
WARNING (moor): It looks like you've created the database class DatabaseAtV2 multiple times. When these two databases use the same QueryExecutor, race conditions will occur and might corrupt the database.
Try to follow the advice at https://moor.simonbinder.eu/faq/#using-the-database or, if you know what you're doing, set moorRuntimeOptions.dontWarnAboutMultipleDatabases = true
Here is the stacktrace from when the database was opened a second time:
#0      GeneratedDatabase._handleInstantiated (package:moor/src/runtime/api/db_base.dart:88:30)
#1      new GeneratedDatabase (package:moor/src/runtime/api/db_base.dart:59:12)
#2      new DatabaseAtV2 (file:///Users/migueloliveira/moor_test/lib/database/test/generated_migrations/schema_v2.dart:57:35)
#3      GeneratedHelper.databaseForVersion (file:///Users/migueloliveira/moor_test/lib/database/test/generated_migrations/schema.dart:18:19)
#4      VerifierImplementation.schemaAt (package:moor_generator/src/services/schema/verifier_impl.dart:63:23)
#5      VerifierImplementation.startAt (package:moor_generator/src/services/schema/verifier_impl.dart:77:12)
#6      VerifierImplementation.migrateAndValidate (package:moor_generator/src/services/schema/verifier_impl.dart:25:35)
<asynchronous suspension>
#7      StackZoneSpecification._registerUnaryCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart)
<asynchronous suspension>
```
The app appears to work as expected with the replacement I did with the "oldDb" as you provided in your example, I'm just wondering if these warnings are okay and if I can disable them.. Am I forgetting to close the db somewhere?

**Comment by simolus3** [comment]
I did get those warnings, I just overlooked them over all the other logs :D

You can't close those databases in the migration because they're connected to the real database. What you can do is define something like

```dart
QueryExecutor _stub = LazyDatabase(() => throw UnsupportedError('stub'));
```

Then you can use `v2.DatabaseAtV2(_stub)` and safely close that after running `alterTable`.

**Comment by MiguelSOliveira** [comment]
Sorry about the newb question but how would I connect after? I'm not really getting it.

```
DatabaseAtV13(QueryExecutor e) : super(SqlTypeSystem.defaultInstance, e);
  DatabaseAtV13.connect(DatabaseConnection c) : super.connect(c);
```

I can't do:
`final oldDb = v13.DatabaseAtV13(_stub).connect(db.connection);` because the connect method doesn't exist in the instance.

And what would I close, sorry? You mean use this _stub in the actual implementation and then in the tests close the stub?

**Comment by simolus3** [comment]
You don't need to use `.connect` to construct those databases at all:

```dart
QueryExecutor _stub = LazyDatabase(() => throw UnsupportedError('stub'));

Future<void> migrate1(Migrator migrator, MoorDb db) async {
  print('Migrating v1');
  final oldDb = v2.DatabaseAtV2(_stub);
  await migrator.alterTable(TableMigration(
    oldDb.firstTable,
    newColumns: [db.firstTable.secondCol],
    columnTransformer: {
      db.firstTable.secondCol: const Constant<String>("test")
    },
  ));
  oldDb.close();
}
```

**Comment by MiguelSOliveira** [comment]
Works perfectly, thanks Simon!

**Comment by MiguelSOliveira** [comment]
Hey @simolus3, I know this is closed but now that I've changed to null safety, I'm getting a similar error. Sorry to be a bother, but could you help me again?

I'm running a test similar to this:

```
test('upgrade from v1 to v2', () async {
  final schema = await verifier.schemaAt(1);

  // Insert some custom data
  final rawDb = schema.rawDatabase;
  rawDb.execute("INSERT INTO users (name) VALUES ('Test user');");

  final db = MyDatabase.connect(schema.connection);

  // Verify that the migration correctly updates the schema
  await verifier.migrateAndValidate(db, 2);
  
  // Use your own logic to verify that the data is still there. For example:
  expect(db.select(db.users).get(), completion(isNotEmpty));
});
```

The problem is I get this error:
  Null check operator used on a null value
  lib/database/database.g.dart 1181:57                                        new XfromData

This is because my `rawDb.execute` is probably using my Database.g.dart which has my latest schema with a NOT NULL column that I've introduced in an older version.

I've set up my migration to comply with what you said:
```
final oldDb = v10.DatabaseAtV10(stub);
```

The problem, I think, is that the test itself is using my Database.g.dart, so I think I need to make the test also use the v10.DatabaseAtV10? Not sure how though.

**Comment by simolus3** [comment]
You're right - the latest version of the data class expects another column so it throws an exception if it's not there. This is intended behavior.
Unfortunately it is not currently possible to use data classes from older versions, moor omits them from generated schema code because I thought they wouldn't be necessary. We could introduce a command-line flag to expand what is generated in this case.

**Comment by MiguelSOliveira** [comment]
Maybe I'm trying to use migrations testing incorrectly.. Can you explain once more what you envisioned by testing migrations? Because in my mind, I try to imagine migrations testing as a way to make sure that no matter what version a user opens my app, I'm sure that for each version up to the current version, he will migrate correctly.

I do that, by testing each migration up until my current migration.

If my app is on v3, I test the migration from v1 to v2 and from v2 to v3. Is this not the intended behaviour?

**Comment by simolus3** [comment]
Yes, that is the intended approach. I mainly envisioned them as a tool to ensure schema consistency, meaning that all your schema migrations transform tables as they should. Ensuring data consistency is another value aspect that should be testable with schema migrations, and this is where the test code is currently lacking.

I think there are valid use cases where you don't need data classes or companions in schema tests. For instance, you could use the old tables in `lib/` to implement the migrations, but you probably wouldn't need old data classes laying around in your app. For this reason, I think the best approach is to make this an opt-in behavior.

**Comment by simolus3** [comment]
I've added the two options in 4bca48fd1765b42369bb6328227d6ae3159a477e.
