### ISSUE TITLE
question about traslating custom queries

### ISSUE THREAD

**Issue by MahdiPishguy** [simolus3/moor#118]
when i add this sql for having custom query:

```dart
queries: {
  'getUser':'SELECT * FROM user_table ORDER BY ID DESC LIMIT 1;'
})
```

i have this result:

```dart
  Future<List<UserTableData>> getUser(
      {@Deprecated('No longer needed with Moor 1.6 - see the changelog for details')
          QueryEngine operateOn}) {
    return (operateOn ?? this).customSelect(
        'SELECT * FROM user_table ORDER BY ID DESC LIMIT 1;',
        variables: []).then((rows) => rows.map(_rowToUserTableData).toList());
  }
```

this is only simple question about that, with my sql query i want to get only single row from table but after translating that with `build` command in terminal, `getUser` return `List`, i'm not sure this is important or no, but i feel your mean in document was make and translate sql to query as dart

**Comment by simolus3** [comment]
Determining the amount of rows returned from a sql statement isn't that easy. We could have a check that generates a non-list method for simple cases (like your example with `LIMIT 1`), but it's hard to get it right for a variety of cases, so we don't do that check at all.

We will definitely have an API to use `getSingle` and `watchSingle` on custom queries in the future, but I'm not yet sure how that API would look like (see #120). For now, you could use something like
`(await dao.getUser()).single` or `dao.getUser().then((rows) => rows.single)`
