### ISSUE TITLE
Flutter driver version mismatch

### ISSUE THREAD

**Issue by bkekelic2** [simolus3/moor#1183]
Hi, 
recently I updated Flutter (to 2.0.6) and Dart SDK (to 2.12.3).

Of course, when I tried to build apk/pub get, a lot of errors shown for lot of different plugins, so I take them one by one and started to fix version mismatch for them. Then **moor** plugin came to fix, I've upgrade pubspec.yaml file to use `moor: ^4.2.1`,  but then I stuck with this error:

`Because every version of flutter_driver from sdk depends on convert 2.1.1 and moor >=4.1.0 depends on convert ^3.0.0, flutter_driver from sdk is incompatible with moor >=4.1.0.
So, because MY_PROJECT depends on both moor ^4.2.1 and flutter_driver any from sdk, version solving failed.
pub get failed (1; So, because MY_PROJECT depends on both moor ^4.2.1 and flutter_driver any from sdk, version solving failed.)`

Then, I tried to downgrade to `moor: 4.0.0-nullsafety.1` as suggested but then different error came for **encrypted_moor**: 

`Because every version of encrypted_moor from git depends on moor ^4.0.0 and hooxna depends on moor 4.0.0-nullsafety.1, encrypted_moor from git is forbidden.
So, because hooxna depends on encrypted_moor from git, version solving failed.
pub get failed (1; So, because hooxna depends on encrypted_moor from git, version solving failed.)`

I'm not sure what to do or even is this error related to this package or to flutter. 

Thanks in advance.

Flutter doctor: 
`[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.928], locale hr-HR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)

• No issues found!`

**Comment by simolus3** [comment]
It looks like the current Flutter beta supports the latest `convert`, so maybe using that is the easiest solution. The nullsafety pre-releases of moor 4.0 still depend on a convert 3 pre-release, so downgrading to an older moor 4.x would probably not work either.

`convert` version 3 was the first one to support null safety (AFAIK), so the null safe moor 4 has to depend on that.
