### ISSUE TITLE
Save DateTime from String in Moor

### ISSUE THREAD

**Issue by sharoonamjid** [simolus3/moor#1184]
From the server I receive date time in the following format:

```
{
    "data": [
        {
            "id": 7,
            "created_at": "2021-04-17T14:59:55.000000Z",
            "updated_at": "2021-04-17T15:00:13.000000Z"
        }
     ]
}
```
but it throws the following error when Json is being saved in database:

`type 'String' is not a subtype of type 'int'`

This is because I get the timestamps `updated_at` and `created_at` in string format from the server and Moor `DateTimeColumn` accepts `int` value. How can I fix this issue? How to make `DateTimeColumn` to accept the above string format.

This is how my `Table` looks like:

```
@DataClassName("TableName")
class TableName extends Table {
  IntColumn get id => integer()();

  @JsonKey('created_at')
  DateTimeColumn get createdAt => dateTime().nullable()();

  @JsonKey('updated_at')
  DateTimeColumn get updatedAt => dateTime().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}
```
Just for your more information, I'm using Laravel as a backend. So I can return `updated_at` and `created_at` in Milliseconds as well if needed. But It would be nice if somehow `"2021-04-17T14:59:55.000000Z"` can be saved in database with `DateTime` type.

Thank you.

**Comment by simolus3** [comment]
Is this about the json serialization functionality? I think the best way would be to use a custom [ValueSerializer](https://pub.dev/documentation/moor/latest/moor/ValueSerializer-class.html) that encodes a `DateTime` as a string. You can pass your serializer to the from/to json functions, or set it globally via `moorRuntimeOptions.defaultSerializer`.

**Comment by sharoonamjid** [comment]
Sorry I didn't understand these terms. Can you please give me an example code for my usecase? I need this `"2021-04-17T15:00:13.000000Z"` time format to be saved in `DateTimeColumn`

**Comment by simolus3** [comment]
What steps are you using to store the data from your backend in an app database? If you're calling `.fromJson` on a moor-generated class, that already expects the DateTime as an int if you don't use a custom ValueSerializer. The serializer only affects how moor reads a row from json, it does not affect how the column is stored at all.

To control how the column is stored in the database, you can use a `TypeConverter`:

```dart
class _DateTimeConverter extends TypeConverter<DateTime, String> {
  const _DateTimeConverter();

  @override
  DateTime? mapToDart(String? fromDb) {
    if (fromDb == null) return null;

    return DateTime.parse(fromDb);
  }

  @override
  String? mapToSql(DateTime? value) {
    return value?.toIso8601String();
  }
}

class YourTable extends Table {
  TextColumn get date => text().map(const _DateTimeConverter())();
}

```

**Comment by sharoonamjid** [comment]
Thank you for your time and code snippet. Yes, while storing the data from the backend, I call `.fromJson` on a moor-generated class. And yes it expects `int` value, but from the server I recieve `String` date time in this format:  `"2021-04-17T15:00:13.000000Z"`

**Comment by simolus3** [comment]
Right. For that you can write something like

```dart

class MySerializer extends ValueSerializer {
  static const defaults = ValueSerializer.defaults();

  const MySerializer();

  @override
  T fromJson<T>(json) {
    if (T == DateTime) {
      return DateTime.parse(json as String) as T;
    }

    return defaults.fromJson(json);
  }

  @override
  toJson<T>(T value) {
    if (value is DateTime) return value.toString();

    return defaults.toJson<T>(value);
  }
}
```

Then, set `moorRuntimeOptions.defaultSerializer = const MySerializer()` before using fromJson or toJson.

**Comment by ntfnd404** [comment]
I get an error when I try to build the application -
Error: Couldn't find constructor '_DateTimeConverter'.

const _DateTimeConverter();

**Comment by ntfnd404** [comment]
here are my classes:

@DataClassName('NotificationModel')
class Notifications extends Table {
  TextColumn get id => text()();
  TextColumn get title => text()();
  TextColumn get message => text()();
  BoolColumn get readed => boolean()();
  TextColumn get date => text().map(const DateTimeConverter())();
}

class DateTimeConverter extends TypeConverter<DateTime, String> {
  const DateTimeConverter();

  @override
  DateTime? mapToDart(String? fromDb) {
    if (fromDb == null) return null;

    return DateTime.parse(fromDb);
  }

  @override
  String? mapToSql(DateTime? value) {
    return value?.toIso8601String();
  }
}

**Comment by ntfnd404** [comment]
Error: Couldn't find constructor 'DateTimeConverter'.
lib/…/database/app_db.g.dart:1892
          const DateTimeConverter();
                ^^^^^^^^^^^^^^^^^
    Failed to package /Users/olegosipov/Documents/fluttersrc/clients/kegelfit.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by simolus3** [comment]
It really generates a `_DateTimeConverter` constructor call for that? Can you try running `flutter pub run build_runner build` again  after saving your sources? If you use `.map(const DateTimeConverter())` it should also generate a constructor invocation with the same (public) name.
