### ISSUE TITLE
Select specific columns  

### ISSUE THREAD

**Issue by selvam920** [simolus3/moor#1205]
pls provide sample code for select specific columns from joined tables.

**Comment by simolus3** [comment]
We have a (bit complicated) example for that [here](https://moor.simonbinder.eu/docs/advanced-features/joins/#group-by), which is the section right below joins. Does that help at all? If you're looking for a specific query I can add that to the documentation in another section.

**Comment by simolus3** [comment]
Please let me know if the existing documentation does not help you here, otherwise I'll go ahead and close this.
