### ISSUE TITLE
Moor Flutter 4.3.0

### ISSUE THREAD

**Issue by CodeDoctorDE** [simolus3/moor#1207]
It would be cool, if the moor_flutter package will be updated. I want to use custom classes :)

**Comment by rubenferreira97** [comment]
You can already use custom classes, just update moor to latest version like:
https://moor.simonbinder.eu/docs/getting-started/

**Comment by simolus3** [comment]
Yes exactly, `moor` is a transitive dependency of `moor_flutter` which implements the main features.

You can add an explicit dependency to ensure that you get

```yaml
dependencies:
  moor: ^4.3.0
```
