### ISSUE TITLE
.moor Joining the same table with INNER JOIN and LEFT JOIN causes both to be non-null

### ISSUE THREAD

**Issue by North101** [simolus3/moor#1208]
```
SELECT
  tableA1.**,
  tableA2.**, 
  tableB1.**, 
  tableB2.**
FROM tableA1

LEFT JOIN tableA1 AS tableA2
  ON FALSE

INNER JOIN tableB1
  ON TRUE

LEFT JOIN tableB1 AS tableB2
   ON FALSE
```

tableA1, tableA2, tableB1 and tableB2 will all be non-null.

Just specifying the table once in a LEFT JOIN will however correctly be nullable
```
SELECT
  tableA1.**,
  tableB1.**,
FROM tableA1

LEFT JOIN tableB1
   ON FALSE
```

tableB1 will be correctly nullable

**Comment by simolus3** [comment]
Good catch, thanks!

I think fixing this will require major changes to the way `sqlparser` resolves result sets, currently it doesn't properly distinguish between a result set itself and a reference to a result set. This behavior is also visible in scenarios like this:

```sql
SELECT * FROM table1
  WHERE table2.foo = 3 -- bizarrely, not an error in sqlparser
```

**Comment by North101** [comment]
I've got a hacky workaround:
```
SELECT
  tableA1.**,
  tableA2.**, 
  tableB1.**, 
  tableB2.**
FROM (SELECT TRUE) AS hack

LEFT JOIN tableA1
  ON TRUE

LEFT JOIN tableA1 AS tableA2
  ON FALSE

LEFT JOIN tableB1
  ON TRUE

LEFT JOIN tableB1 AS tableB2
   ON FALSE

WHERE tableA1.id IS NOT NULL
AND tableB1.id IS NOT NULL
```

It'll make them all nullable (which is better than them non-nullable)

**Comment by simolus3** [comment]
This is now fixed on `develop`, thanks again for the report!
