### ISSUE TITLE
Watching a subset of a table or using join doesn't update with results

### ISSUE THREAD

**Issue by newtonmunene99** [simolus3/moor#121]
I'm not sure if this is similar to #55 . When I update columns in a table, **update only,delete and insert works fine**, the stream builder doesn't receive the changes. 
Here's my query. I've tried two approaches, one using `join` and the other using `where`

```dart
Stream<JournalWithEntries> watchJournalWithEntries(int id) {
    final _journalQuery =
        (select(journals)..where((journal) => journal.id.equals(id)));

    final _contentQuery = select(journals).join(
      [
        innerJoin(
          entries,
          entries.journalId.equalsExp(journals.id),
        ),
      ],
    )..where(journals.id.equals(id));

    final _journalStream = _journalQuery.watchSingle();
    final _contentStream = _contentQuery.watch().map((rows) {
      return rows.map((row) => row.readTable(entries)).toList();
    });

    return Observable.combineLatest2(_journalStream, _contentStream,
        (Journal journal, List<Entry> entries) {
      return JournalWithEntries(
        journal: journal,
        entrys: entries,
      );
    });
  }
```

```dart
Stream<List<Entry>> watchAllJournalEntries({@required int id}) {
    return (select(entries)
          ..where((t) => t.journalId.equals(id))
          ..orderBy(
            ([
              (t) => OrderingTerm(expression: t.id, mode: OrderingMode.asc),
            ]),
          ))
        .watch();
  }
```

**Comment by simolus3** [comment]
We have something very similar to your second snippet in the example app, we load a list of entries for a category: https://github.com/simolus3/moor/blob/b1e6d931d5987e267c64efb5f96f95815b38c143/moor_flutter/example/lib/database/database.dart#L116-L135
I just tried that one out and couldn't reproduce the problem. If you can give me your table definitions (you can omit columns that don't appear in your example), I can try to track it down.

And, just to be sure, can you give me the moor version you're using (you can find the exact version in your `pubspec.lock`).

**Comment by newtonmunene99** [comment]
Here's my table definitions 

```dart
@DataClassName("Journal")
class Journals extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().withLength(min: 1, max: 50)();
  TextColumn get description => text().withLength(min: 1, max: 100)();
  DateTimeColumn get createdOn => dateTime().withDefault(currentDateAndTime)();
  DateTimeColumn get updatedOn => dateTime().withDefault(currentDateAndTime)();
  TextColumn get backgroundImage => text().nullable()();
}

@DataClassName("Entry")
class Entries extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get entry => text().map(const RichTextConverter()).nullable()();
  DateTimeColumn get addedOn => dateTime().withDefault(currentDateAndTime)();
  IntColumn get journalId => integer()();
}
```

I'm using 
```yaml
moor_flutter: ^1.7.0
moor_generator: ^1.7.0
```

**Comment by simolus3** [comment]
Thanks for the detailed response. Unfortunately, I still can't reproduce your issue. I tried to use your second snippet in this gist: https://gist.github.com/simolus3/78706375bd1a9c4376e2f00ec393c18c

In the stream builder, I display the amount of entries for the journal with id 1. When the floating action button is pressed, I add another entry (with journal id 1). When I run the app and press the button, the counter increases, as intended.

Is there anything major you're doing differently here? I'll try the first snipped with `Observable.combineLatest2` tomorrow, but I recently tested a similar case which worked.

**Comment by newtonmunene99** [comment]
Everything seems fine with the gist. Could you try an update on the entry field/column? The one with the type converter. Inserts and Deletes seem to work fine for me. I'm getting the issue when updating. Thanks.

**Comment by simolus3** [comment]
Still no luck :( I've added this method to the database:
```dart
Future updateEntry(int id) async {
    final updated = await (update(entries)..where((e) => e.id.equals(id)))
        .write(EntriesCompanion(
            entry: Value(DateTime.now().millisecondsSinceEpoch)));
    print('updated: $updated');
  }
```
And I'm calling that method when the floating action button is pressed. This prints "updated: 1" and the `StreamBuilder` does get rebuilt.

**Comment by newtonmunene99** [comment]
Might be something wrong with my view. I'll try and see if I can replicate the issue with your gist. Thanks

**Comment by newtonmunene99** [comment]
I've done a few more tests on this and I can confirm It's not an issue with moor. It's a problem with state management in my custom view/widget.
