### ISSUE TITLE
'isNull' is deprecated and shouldn't be used.

### ISSUE THREAD

**Issue by kilroy05** [simolus3/moor#1210]
**Describe the bug**

A clear and concise description of what the bug is. Please briefly describe what behavior you expected, what behavior you saw, and how the bug can be reproduced.

I want to select from a table where a field is null
`'isNull' is deprecated and shouldn't be used.`

Am I missing something?

Code to select is
`..where((item) => item.targetDate.isNull()))`

**Comment by simolus3** [comment]
Does that snippet really report an error? The top-level [isNull](https://pub.dev/documentation/moor/latest/moor/SqlIsNull/isNull.html) function is deprecated, but your're using the [extension](https://pub.dev/documentation/moor/latest/moor/SqlIsNull/isNull.html) which is not.

**Comment by kilroy05** [comment]
yep, in visual studio code.
So I would assume I was missing an import then or something? Must be my setup, then...

**Comment by simolus3** [comment]
Oh actually, which moor version are you using?

**Comment by kilroy05** [comment]
`moor_flutter: ^4.0.0`

**Comment by gsouf** [comment]
@kilroy05 that works well with version `4.2.1` for me. Would you try setting `4.2.1` as the minimum version?

**Comment by kilroy05** [comment]
@gsouf There is no 4.2.1 version
https://pub.dev/packages/moor_flutter
4.0.0 is the latest

**Comment by gsouf** [comment]
@kilroy05 my flutter app does not use moor_flutter it just uses [moor package](https://pub.dev/packages/moor).

I'm not sure what moor_flutter is made for, but it seems to be a legacy one according to the doc: https://moor.simonbinder.eu/docs/getting-started/

> Previous versions of this article recommended to use moor_flutter or the moor_ffi package. For new users, we recommend to use package:moor/ffi.dart to open the database - more on that below!

Might be that moor_flutter is not longer updated. @simolus3 ?

**Comment by kilroy05** [comment]
well, nice
thanks @gsouf 
Should've read the docs a bit better
Will close this issue.
