### ISSUE TITLE
Serialization broken with double? type

### ISSUE THREAD

**Issue by stx** [simolus3/moor#1211]
`_DefaultValueSerializer` code:

```
    if (_typeList is List<double> && json is int) {
      return json.toDouble() as T;
    }
```

This doesn't catch `List<double?>` and thus `double?` columns, like `RealColumn? get myColumn => real().nullable()();`

This exception will be thrown on generated code `serializer.fromJson<double?>(json['my_column'])` when `json['my_column']` is an int:

**_CastError (type 'int' is not a subtype of type 'double?' in type cast)**

I believe the fix is:

```
    if (_typeList is List<double?> && json is int) {
      return json.toDouble() as T;
    }
```

**Comment by simolus3** [comment]
Thanks for the report, I've fixed this on `develop`.
