### ISSUE TITLE
MoorIsolate stops on null safety

### ISSUE THREAD

**Issue by Pawkosss** [simolus3/moor#1213]
When I move project to null safety sometimes on update queries background database throws error and I can't interact with database anymore. 

This error throw here:
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\moor-4.3.0\lib\src\runtime\remote\protocol.dart
IIn line 210 

![image](https://user-images.githubusercontent.com/29184852/119116002-193fc580-ba28-11eb-99e0-c50b5f9f8edf.png)

**Comment by simolus3** [comment]
Thanks for the report, I've now fixed this in f726328f69c40724ee429f989a50c94df4f1b5b5.
