### ISSUE TITLE
Enum serialization issue

### ISSUE THREAD

**Issue by Pawkosss** [simolus3/moor#1216]
When i trying to serialize object to json using JsonEncode i getting error 

Class 'DocumentStatus' has no instance method 'toJson'.

![image](https://user-images.githubusercontent.com/29184852/119342273-20b7d680-bc95-11eb-9954-922b9fa2601d.png)

**Comment by simolus3** [comment]
I don't think it's in the scope of the moor project to provide proper support for serialization of enums from and to json.

I would recommend to use [custom row classes](https://moor.simonbinder.eu/docs/advanced-features/custom_row_classes/) for this, as you can annotate them with [`json_serializable`](https://pub.dev/packages/json_serializable) which supports encoding enums.
