### ISSUE TITLE
LogStatements prints are truncated

### ISSUE THREAD

**Issue by cirediew** [simolus3/moor#1229]
I'm running into the issue where very long logs are truncated `<...>` because of the use of `print`. 
```
flutter: Moor: Executing BatchedStatements([INSERT INTO properties (property, product, sending, updated, name, data_type, value, receiving, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(property) DO UPDATE SET property = ?, product = ?, sending = ?, updated = ?, name = ?, data_type = ?, value = ?, receiving = ?, updated_at = ?, DELETE FROM properties WHERE EXISTS(SELECT * FROM products WHERE products.account = 18996 AND products.product = properties.product) AND properties.updated_at < 1622194047], [ArgumentsForBatchedStatement(0, [511664, 130688, 1, 2021-05-28T09:19:00.000Z, Temperature, 12, 36.870000, 0, 1622194047, 511664, 130688, 1, 2021-05-28T09:19:00.000Z, Temperature, 12, 36.870000, 0, 1622194047]), ArgumentsForBatchedStatement(0, [511677, 130691, 1, 2021-05-28T09:24:45.000Z, Volume, 52, 15885.730000, 0, 1622194047, 511677, 130691, 1, 2021-05-28T09:24:45.000Z, Volume, 52, 15885.730000, 0, 1622194047]), ArgumentsForBatchedStatement(0, [511678, 130691, 1, 2021-05-28T09:24:45.0<…>
```
Please consider using `debugPrint(someSuperLongString, wrapWidth: 1024);` to be able to print everything, as mentioned here: https://github.com/flutter/flutter/issues/22665#issuecomment-506687219

Or change the boolean `logStatements` with the ability to pass along a custom log method.
For example:
```dart
VmDatabase(
    file, 
    logStatements: (String log) {
        myOwnLogMethod(log);
    }
);
```
Thanks!

**Comment by kuhnroyal** [comment]
`debugPrint` is not available in Dart I think.
Maybe it would be better to allow some logger implementation to be exchangeable.

**Comment by simolus3** [comment]
Unfortunately we can't use `debugPrint` because it comes from Flutter.

If you want every usage of `print` to be `debugPrint`, you can override `print` globally:

```dart
  runZoned(
    () {
      // Your app code...
    },
    zoneSpecification: ZoneSpecification(
        print: (Zone self, ZoneDelegate parent, Zone zone, String line) {
      Zone.root.run(() => debugPrint(line));
    }),
  );
```

In general, moor's printing mechanism is mainly used for debugging purposes. But I agree that we can and should use something like [package:logging](https://pub.dev/packages/logging) which would allow you to customize log output.

**Comment by cirediew** [comment]
You're absolutely right, debugPrint is Flutter only, hadn't thought of it.

Running zoned fixes my issue for now.
Thank you.

**Comment by ToniTornado** [comment]
Is it possible to add a `moorRuntimeOptions.logMethod = debugPrint` or even pass my apps custom log method that way? That way Moor is independent of any logger from a different package.

**Comment by simolus3** [comment]
Nice call, I think that's a good solution. I've added that in 8f40216528f135d7763a871efe81e97a77da682.
