### ISSUE TITLE
Try to update primary key with data.

### ISSUE THREAD

**Issue by jerryzhoujw** [simolus3/moor#123]
### story
I first create a record with local generated primary key.
After I post the data, server will generated a primary key.

I need to update the data with all data from server, also will change the primary key.

### issue

```
Future<bool> updateTableA(Table row) async {
  try {
    return await (update(tableA)..where((e) => e.otherCondition.equals(row.otherCondition)))
      .replace(row);
    } catch (e) {
      log('updateTableA: $e');
    }
   return false;
}
```

I will get error :
> package:moor/src/runtime/statements/update.dart': Failed assertion: line 100 pos 9: 'whereExpr == null': When using replace on an update statement, you may not use where(...)as well. The where clause will be determined automatically.

The information is clear: when you want update a record, it will automatically use the primary key as where condition.

###
 
So any idea ?

**Comment by simolus3** [comment]
In your method, the `row` parameter contains the data from the server, including the updated primary key, right?
In that case, `replace` is not going to work because it will apply a `where` clause that matches the _updated_ primary key from the server - which likely doesn't exist in your local database.
Maybe something like this could work:
```dart
/// Replaces the [local] row with the data sent from the server with [fromServer]
Future<bool> updateTableA(Table local, Table fromServer) async {
  try {
    return await (update(tableA)
       ..whereSamePrimaryKey(local)
       ..where((e) => e.otherCondition.equals(local.otherCondition))
    ).write(fromServer);
    } catch (e) {
      log('updateTableA: $e');
    }
   return false;
}
```
I still don't quite understand why you'd want the second `(e) => e.otherCondition.equals(local.otherCondition)` though - if you already filter by the old primary key, only one row can be matched, right?

**Comment by jerryzhoujw** [comment]
Ah, actually the `otherCondition` in my case is `url`, which normally will be unique if it's not empty.

So I will update the data base on the same `url` in the specific workflow.

And I do it like this use  `transaction`, remove and insert:

```
await transaction((_) async {
    delete(tableA)..where((e) => e.url.equals(local.url));
    into(tableA).insert(fromServer, orReplace: true);
});
```

**Comment by simolus3** [comment]
Yeah we basically have two options in moor
1. `replace`: This will apply a `WHERE` clause in sql to match the same primary key, and then update that row. This will __never__ change a primary key of a row.
2. `write`: This doesn't apply a `WHERE` clause by default. For instance, an `update(tableA).write(TableACompanion(column: Value('test)'))` will generate the query `UPDATE table_a SET column = 'test'`. Notice how there is no where clause here - the query would affect all rows in the table.

I'm not entirely sure if I understand you correctly, but is this what you want to do:
1. You create an entry in `tableA` locally, which has an `url`.
2. You get a response from the server, and you want to replace the local entry that has the same url. If what's sent by the server has a different primary key, you also update the primary key of the row locally.

If that's the case, you could just do:
```dart
Future<void> applyChangesFromServer(Table fromServer) {
  await (update(tableA)..where((e) => e.url.equals(fromServer.url))).write(fromServer);
}
```

If that's not what you want to do, let me know.

**Comment by jerryzhoujw** [comment]
yes, that's what I want.
