### ISSUE TITLE
iOS Database not encrypted

### ISSUE THREAD

**Issue by vanlooverenkoen** [simolus3/moor#1230]
I am having issues with the encrypted database.

For a medical app we are required to encrypt our database. I followed this guide

https://moor.simonbinder.eu/docs/other-engines/encryption/#encrypted-version-of-moorffi

1: adding sqlcipher_flutter_libs package
2: adding the pragma key
3: setupSqlcipher

This is my setup:

```
  Future<DatabaseConnection> provideDatabaseConnection() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(join(dbFolder.path, 'db.sqlite'));
    final receivePort = ReceivePort();

    await Isolate.spawn(
      _startBackground,
      _IsolateStartRequest(receivePort.sendPort, file.path, 'TEST'),
    );

    // ignore: avoid_as
    final isolate = await receivePort.first as MoorIsolate;
    return isolate.connect();
  }

  void _startBackground(_IsolateStartRequest request) {
    open.overrideFor(OperatingSystem.android, () => DynamicLibrary.open('libsqlite3.so'));
    final executor = VmDatabase(File(request.targetPath), logStatements: true, setup: (db) => db.execute("PRAGMA key = '${request.password}'"));
    final moorIsolate = MoorIsolate.inCurrent(
      () => DatabaseConnection.fromExecutor(executor),
    );
    request.sendMoorIsolate.send(moorIsolate);
  }


class _IsolateStartRequest {
  final SendPort sendMoorIsolate;
  final String targetPath;
  final String password;

  _IsolateStartRequest(
    this.sendMoorIsolate,
    this.targetPath,
    this.password,
  );
}

```

On android I get this error when accessing the database. 
```
E/flutter (24427): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen failed: library "libsqlite3.so" not found)
E/flutter (24427): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
E/flutter (24427): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
E/flutter (24427): #2      _startBackground.<anonymous closure> (package:my_app/di/injectable.dart:103:66)
E/flutter (24427): #3      OpenDynamicLibrary.openSqlite (package:sqlite3/src/load_library.dart:107:25)
E/flutter (24427): #4      sqlite3 (package:sqlite3/src/api/sqlite3.dart:12:38)
E/flutter (24427): #5      _VmDelegate._createDatabase (package:moor/src/ffi/vm_database.dart:159:13)
E/flutter (24427): #6      _VmDelegate.open (package:moor/src/ffi/vm_database.dart:138:7)
E/flutter (24427): #7      DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:259:22)
E/flutter (24427): <asynchronous suspension>
E/flutter (24427): #8      Lock.synchronized.callBlockAndComplete (package:moor/src/utils/synchronized.dart:18:16)
E/flutter (24427): <asynchronous suspension>
E/flutter (24427): #9      ServerImplementation._handleEnsureOpen (package:moor/src/runtime/remote/server_impl.dart:117:12)
E/flutter (24427): <asynchronous suspension>
E/flutter (24427): #10     MoorCommunication.setRequestHandler.<anonymous closure>.<anonymous closure> (package:moor/src/runtime/remote/communication.dart)
E/flutter (24427): <asynchronous suspension>
```

So I found a couple of issues that looked similar: 
I added this instead of the snippet that was provided in the docs:

```
DynamicLibrary _safeSqliteOpen() {
  DynamicLibrary libsqlite;
  try {
    libsqlite = DynamicLibrary.open('libsqlite3.so');
  } catch (e) {
    print("fail, fallback 1");
    libsqlite = DynamicLibrary.open("/data/data/<app-id>/lib/libsqlite3.so");
    print('fallback success');
  }
  return libsqlite;
}
```
But then I got this.
```
ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen failed: library "/data/data/<app-id>/lib/libsqlite3.so" not found)
E/flutter (24427): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
E/flutter (24427): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
E/flutter (24427): #2      _safeSqliteOpen (package:my_app/di/injectable.dart:118:32)
E/flutter (24427): #3      OpenDynamicLibrary.openSqlite (package:sqlite3/src/load_library.dart:107:25)
E/flutter (24427): #4      sqlite3 (package:sqlite3/src/api/sqlite3.dart:12:38)
E/flutter (24427): #5      _VmDelegate._createDatabase (package:moor/src/ffi/vm_database.dart:159:13)
E/flutter (24427): #6      _VmDelegate.open (package:moor/src/ffi/vm_database.dart:138:7)
E/flutter (24427): #7      DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:259:22)
E/flutter (24427): <asynchronous suspension>
E/flutter (24427): #8      Lock.synchronized.callBlockAndComplete (package:moor/src/utils/synchronized.dart:18:16)
E/flutter (24427): <asynchronous suspension>
E/flutter (24427): #9      ServerImplementation._handleEnsureOpen (package:moor/src/runtime/remote/server_impl.dart:117:12)
E/flutter (24427): <asynchronous suspension>
E/flutter (24427): #10     MoorCommunication.setRequestHandler.<anonymous closure>.<anonymous closure> (package:moor/src/runtime/remote/communication.dart)
E/flutter (24427): <asynchronous suspension>
```

On iOS I get no errors when running. I can add , remove & update items in the database. But when I access the database file. I can read everything. How do I fix this? And is my iOS database even encrypted at this point?

**Comment by vanlooverenkoen** [comment]
Alright I got a little further. I was still trying to import `libsqlite3 ` instead of `libsqlcipher`. Right now I got android working.

When I try to open the db in table plus I get this popup for Android. 
![image](https://user-images.githubusercontent.com/21172855/119972667-c5e2ef80-bfb2-11eb-9c4e-e507f499dd99.png)

**Comment by simolus3** [comment]
It looks like this works now that you're opening `libsqlcipher.so` on Android? On iOS it should work out of the box I think, since we're linking sqlcipher into the Flutter binary.

**Comment by vanlooverenkoen** [comment]
When reading this. https://github.com/simolus3/sqlite3.dart/tree/master/sqlcipher_flutter_libs

I get confused on what I should use. And when I should call what? 
Should it be like this?

```
await applyWorkaroundToOpenSqlCipherOnOldAndroidVersions();
open.overrideFor(
      OperatingSystem.android, openCipherOnAndroid);
```

Or like this:

```
open.overrideFor(
      OperatingSystem.android, applyWorkaroundToOpenSqlCipherOnOldAndroidVersions);
```

**Comment by vanlooverenkoen** [comment]
On iOS I can change the password and I can still access the file. In tableplus I don't get the passphrase popup. So the database is not yet encrypted out of the box

**Comment by vanlooverenkoen** [comment]
I found this:
https://github.com/simolus3/moor/issues/451#issuecomment-602062594

Where they say that we should still add the iOS native lib.

But that could not be found and throws this error:
```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (dlopen(/usr/lib/libsqlcipher.dylib, 1): image not found)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)
#2      _startBackground.<anonymous closure> (package:my_app/di/injectable.dart:107:64)
#3      OpenDynamicLibrary.openSqlite (package:sqlite3/src/load_library.dart:107:25)
#4      sqlite3 (package:sqlite3/src/api/sqlite3.dart:12:38)
#5      _VmDelegate._createDatabase (package:moor/src/ffi/vm_database.dart:159:13)
#6      _VmDelegate.open (package:moor/src/ffi/vm_database.dart:138:7)
#7      DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:259:22)
<asynchronous suspension>
#8      Lock.synchronized.callBlockAndComplete (package:moor/src/utils/synchronized.dart:18:16)
<asynchronous suspension>
#9      ServerImplementation._handleEnsu<…> 
```

**Comment by davidmartos96** [comment]
@vanlooverenkoen For iOS you can try using `DynamicLibrary.process()` instead. As Simon says, it's being compiled into the Flutter binary.

**Comment by vanlooverenkoen** [comment]
Alright yes that does the trick. 

Personally, I think the encrypted library should get more attention. We should have some extra docs. And the libraries should be released to pub.dev With an easy api.

**Comment by vanlooverenkoen** [comment]
@davidmartos96 Do you have an idea what I should use here? 

> When reading this. https://github.com/simolus3/sqlite3.dart/tree/master/sqlcipher_flutter_libs
> 
> I get confused on what I should use. And when I should call what?
> Should it be like this?
> 
> ```
> await applyWorkaroundToOpenSqlCipherOnOldAndroidVersions();
> open.overrideFor(
>       OperatingSystem.android, openCipherOnAndroid);
> ```
> 
> Or like this:
> 
> ```
> open.overrideFor(
>       OperatingSystem.android, applyWorkaroundToOpenSqlCipherOnOldAndroidVersions);
> ```
> 
> or simply
> ```
> open.overrideFor(OperatingSystem.android, () => DynamicLibrary.open('libsqlcipher.so'));
> ```

**Comment by davidmartos96** [comment]
I haven't tried Simon's sqlcipher libs yet, but looking at the methods it looks like you should call both methods for the workarounds. So the first snippet you posted. Maybe Simon has more input on this.

**Comment by vanlooverenkoen** [comment]
Yeah that is wat I currenlty have. @simolus3 can you confirm this is correct?

**Comment by simolus3** [comment]
> Personally, I think the encrypted library should get more attention. We should have some extra docs. And the libraries should be released to pub.dev With an easy api.

Those are all valid points, I'll work on them this weekend. There's a PR to also support macOS with sqlcipher_flutter_libs. I'll get that merged and applied to sqlite3_flutter_libs as well. Then I can publish that all to pub and give clearer examples in the docs.

The `applyWorkaroundToOpenSqlCipherOnOldAndroidVersions` is a method which uses some Android hacks to work around an Android bug when opening native libraries. So far, the bug only occurs on Android 6.0.1.
`open.overrideFor` is used to change the default method the `sqlite3` package uses to open the library. On Android, the default behavior is to attempt to open `libsqlite3.so` which is not what you want. So, your current code is correct:

1. Call (and await) `applyWorkaroundToOpenSqlCipherOnOldAndroidVersions` if you want to support Android 6.0.1
2. Use `open.overrideFor` so that you open `libsqlcipher.so` instead.

On iOS, you should just use `DynamicLibrary.process()` as David mentioned. This is also the default behavior, so you shouldn't need anything special for that.

**Comment by vanlooverenkoen** [comment]
Alright perfect. For now we will still use the git url.

Encrypted moor should only be used if moor_flutter is used. Right?

**Comment by simolus3** [comment]
Yes, exactly.

**Comment by simolus3** [comment]
Ok, so I've just published [`sqlcipher_flutter_libs`](https://pub.dev/packages/sqlcipher_flutter_libs) to pub. Depending on that package will include sqlcipher on Android, iOS and macOS.
I've also updated the docs on encryption ([preview here](https://60b162c12c611621e70fae58--moor.netlify.app/docs/other-engines/encryption/#encrypted-version-of-moorffi)) a bit:

- It mentions the correct override on Android
- On iOS and macOS, I still believe that the default option should work. We have an [integration test](https://github.com/simolus3/sqlite3.dart/blob/master/integration_tests/sqlcipher_flutter/test_driver/integration.dart) verifying that `sqlite3_key` is available without any additional overrides on both iOS and macOS. If it doesn't work for you I'd love to see a repro!
- It gives some pointers on how to use SQLCipher on Windows or Linux.

Please let me know if you would want more information in the docs, or if you're still having issues with the new library on pub.

**Comment by vanlooverenkoen** [comment]
Looking good. 
Regarding the iOS override. I am currently on a very tight deadline. I will create a sample project once I have some more time.

I only had 1 more question. When using the encrypted_moor on android we should add this proguard rule. This is not required anymore when using `sqlcipher_flutter_libs`? Or do we still need to add this?
```
-keep class net.sqlcipher.** { *; }
```

**Comment by simolus3** [comment]
I think you don't need to keep sqlcipher's Java classes because they're not used with `moor/ffi`.

That said, I'm wondering why we need to keep them for the sqflite based implementation @davidmartos96. Is there some reflective access that would break otherwise?

**Comment by davidmartos96** [comment]
@simolus3 It's needed when using platform channels (encrypted_moor) because of the minification and proguard configuration that Flutter does automatically on release mode.
It's a known error to miss the proguard configuration when using SQLCipher library from Java. 

https://stackoverflow.com/a/42555193/5617722
https://github.com/sqlcipher/android-database-sqlcipher/issues/442

**Comment by akshaytaru2007** [comment]
Hi All,

I am also kind of stuck. 

I am using encrypted_moor with following dependencies:

```
encrypted_moor:
    git:
      url: https://github.com/simolus3/moor.git
      path: extras/encryption

  sqlcipher_flutter_libs:
    git:
      url: https://github.com/simolus3/sqlite3.dart.git
      path: sqlcipher_flutter_libs

 moor: ^4.3.0
  
```

This is how I am opening encrypted db file:

```
(EncryptedExecutor.inDatabaseFolder(
            path: 'hello.sqlite',
            password: 'hello',
            logStatements: true,
            singleInstance: true,
            creator: (file) async {
              final blob =
                  await rootBundle.load('assets/database/hello.sqlite');
              await file.writeAsBytes(blob.buffer.asUint8List());
            }))
```


I am not sure how to get pass to this error:

```
CDN: trunk Relative path: Specs/1/2/7/SQLCipher/4.4.2/SQLCipher.podspec.json exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: Specs/1/2/7/SQLCipher/4.4.3/SQLCipher.podspec.json exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "SQLCipher":
      In Podfile:
        sqflite_sqlcipher (from `.symlinks/plugins/sqflite_sqlcipher/ios`) was resolved to 0.0.1, which depends on
          SQLCipher (= 4.4.2)
        sqlcipher_flutter_libs (from `.symlinks/plugins/sqlcipher_flutter_libs/ios`) was resolved to 0.0.1, which depends on
          SQLCipher (~> 4.4.3)

````

I would really appreciate your help. Thank you.
PS: I am Android developer and I am new to Flutter.

**Comment by simolus3** [comment]
@akshaytaru2007 You should not depend on both `encrypted_moor` and `sqclipher_flutter_libs` as those are different implementations.

Of you want to use an `EncryptedExecutor`, drop the `sqlcipher_flutter_libs` dependency.

**Comment by davidmartos96** [comment]
@akshaytaru2007 And about the pod install error you have, that happens sometimes.
You just need to run the following:
`flutter clean` and then delete the Podfile.lock file inside the iOS folder.
Then run the app as usual

**Comment by akshaytaru2007** [comment]
@simolus3 Thanks a lot. It worked! I just removed the `sqlcipher_flutter_libs`. @davidmartos96  as soon as I removed the dependency, it build correctly. :)

Thank you for awesome library!
