### ISSUE TITLE
Community packages: moor_db_viewer

### ISSUE THREAD

**Issue by vanlooverenkoen** [simolus3/moor#1233]
I saw that there is a new community page in the documentation. https://moor.simonbinder.eu/docs/community_tools/

I created [moor_db_viewer](https://pub.dev/packages/moor_db_viewer) a year ago. Is it possible to add it to the community tools page as well?

**Comment by simolus3** [comment]
I've added moor_db_viewer to that page on `develop`, it will go live to the main documentation site on the next merge to `master`. Thanks for your work on that package!
