### ISSUE TITLE
update single row using Dao

### ISSUE THREAD

**Issue by MahdiPishguy** [simolus3/moor#124]
this is my `userDao` implementation in database file:

```dart
@UseDao(tables:[UserTable])
class UserTableDao extends DatabaseAccessor<AppDb> with _$UserTableDaoMixin{
  final AppDb db;
  UserTableDao(this.db):super(db);

  ...
  Future   updateUser(Insertable user)  => update(userTable).replace(user);
  ...
}
```

this code work, but couldn't update `userActive` to `1`

my code:

```dart
final userInformation = await Provider.of<UserTableDao>(context).getSingleUser();
Provider.of<UserTableDao>(context).updateUser(userInformation.copyWith(
  userActive: 1
));
```

**Comment by simolus3** [comment]
I can't see anything wrong with that code. Can you try to turn on `logStatements` in the `FlutterQueryExecutor` constructor? Is there a statement that gets logged when you call `updateUser`?

**Comment by MahdiPishguy** [comment]
```
I/flutter (23416): Moor: Sent SELECT * FROM user_table ORDER BY id DESC LIMIT 1; with args []
I/flutter (23416): Moor: Sent UPDATE user_table SET name = ?, mobile_number = ?, email = ?, experience = NULL, insurance = NULL, job = ?, avatar = ?, api_token = ?, user_active = ?, teammate = ?, age = ?, gender = ?, height = ?, weight = ?, bmi = ?, created_at = ?, updated_at = ? WHERE id = ?; with args [, 09373036569, pishguy@gmail.com, برنامه نویس, , dqIXFBmkcrBZdy9bg4kBNjHzIXnoq05CylS897r2ay5dvTDnw1bHg8qhsYaI, 1, 0, 44, 0, 555, 80400, 0, 2019-06-23 09:26:41, 2019-08-28 11:12:28, 7]
```

**Comment by simolus3** [comment]
> i had this problem with insert data into database,in first time insert and update doesn't work, but without any change code and re-run application to insert and update, actions work fine :|

That seems weird. Is that first time insert and update reproducible? If you delete the user, then insert it and update, does it still happen? I just tried out your code myself and it worked every time.

**Comment by MahdiPishguy** [comment]
@simolus3 ok, so let me to check more, maybe my code is not correct
