### ISSUE TITLE
Schema generate compilation failed

### ISSUE THREAD

**Issue by lsaudon** [simolus3/moor#1240]
I test my migrations with "moor_generator".
I am trying to migrate to null safety.
When I run my tests I have compilation errors.

```bash
test/generated/schema_v22.dart:766:64: Error: The getter 'Decimal' isn't defined for the class 'Products'.
 - 'Products' is from 'test/generated/schema_v22.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Decimal'.
    )..clientDefault = () => const DecimalConverter().mapToSql(Decimal.zero);
                                                               ^^^^^^^
test/generated/schema_v22.dart:775:36: Error: Method not found: 'DecimalConverter'.
    )..clientDefault = () => const DecimalConverter().mapToSql(Decimal.zero);
                                   ^^^^^^^^^^^^^^^^
test/generated/schema_v22.dart:775:64: Error: The getter 'Decimal' isn't defined for the class 'Products'.
 - 'Products' is from 'test/generated/schema_v22.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Decimal'.
    )..clientDefault = () => const DecimalConverter().mapToSql(Decimal.zero);
                                                               ^^^^^^^
test/generated/schema_v22.dart:784:36: Error: Method not found: 'DecimalConverter'.
    )..clientDefault = () => const DecimalConverter().mapToSql(Decimal.zero);
                                   ^^^^^^^^^^^^^^^^
test/generated/schema_v22.dart:784:64: Error: The getter 'Decimal' isn't defined for the class 'Products'.
 - 'Products' is from 'test/generated/schema_v22.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'Decimal'.
    )..clientDefault = () => const DecimalConverter().mapToSql(Decimal.zero);
                                                               ^^^^^^^
test/generated/schema_v22.dart:970:24: Error: The getter 'StrongOfflineID' isn't defined for the class 'Employees'.
 - 'Employees' is from 'test/generated/schema_v22.dart'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'StrongOfflineID'.
    )..clientDefault = StrongOfflineID.generate;
                       ^^^^^^^^^^^^^^^
test/generated/schema_v22.dart:1599:36: Error: Method not found: 'DateTimeConverter'.
    )..clientDefault = () => const DateTimeConverter().mapToSql(DateTime.now());
                                   ^^^^^^^^^^^^^^^^^
```

**Comment by westito** [comment]
import these classes in your database file (where @UseMoor located)

**Comment by lsaudon** [comment]
I did this.
I still make the same mistakes.

```dart
@UseMoor(tables: [Clients], daos: [ClientsDao], include: {
  'converters/datetime_converter.dart',
  'converters/decimal_converter.dart',
})
```

**Comment by westito** [comment]
This include parameter is not for package imports! Simply add import statements in the dart file, as you do it regularly.

**Comment by lsaudon** [comment]
This is already the case.
It works in no null safety, but not in null safety.

**Comment by lsaudon** [comment]
I have the imports in my file db.dart

**Comment by westito** [comment]
This is still a missing import error. I not understand the code clearly. Moor generated class file ends with ".g.dart". Your files not seem moor generated files. You have to reference moor generated file in your db.dart as `part 'schema_v22.dart';`. That's how generated file gets import. As you can see in the documentation in Getting started section.

**Comment by simolus3** [comment]
These files are generated by moor to [aid with schema migration tests](https://moor.simonbinder.eu/docs/advanced-features/migrations/#verifying-migrations). These are another feature where moor generates standalone files.

@lsaudon, I'm surprised that this would work without null safety in the first place. I think moor should not include type converters in generated schema files, I'll take a look at how this can be fixed.

**Comment by westito** [comment]
Sorry, I didn't notice this is migration test. :) I haven't used that yet.

**Comment by simolus3** [comment]
Actually it looks like this is because after #1018 we generate code for the default client code. The default client code is evaluated against the database-defining Dart file though, so IMO we shouldn't add it to generated schema helpers. I've fixed this on `develop`.

**Comment by lsaudon** [comment]
Why is it okay if we haven't switched to null safety?

**Comment by simolus3** [comment]
I'm wondering about that too, it shouldn't make a difference. Did moor not generate the `clientDefault` before?

**Comment by lsaudon** [comment]
Oh no, I got confused with `defaultValue`.
Thanks and sorry.
