### ISSUE TITLE
forDartType is deprecated

### ISSUE THREAD

**Issue by afonseca69** [simolus3/moor#1243]
When generating .g.dart the final type declared is deprecated:

Ex: 
final intType = db.typeSystem.forDartType<int>();
    final stringType = db.typeSystem.forDartType<String>();
    final dateTimeType = db.typeSystem.forDartType<DateTime>();
    final doubleType = db.typeSystem.forDartType<double>();

It gives de message: 'forDartType' is deprecated and shouldn't be used. Use mapToVariable or a mapFromSql method instead.
Try replacing the use of the deprecated member with the replacement.

Can you solve this?

**Comment by simolus3** [comment]
Can you try using the latest version of `moor_generator` (or the version which corresponds to the `moor` version you're using)? Newer generator versions don't use `forDartType()` anymore.

**Comment by afonseca69** [comment]
Thank you, I really forgot to update the version of moor_generator


Atenciosamente,


[SoftServ Sistemas]<http://www.softserv.com.br/>[Google+]<https://plus.google.com/+SoftservBr1994> [Curta nossa pÃ¡gina] <https://www.facebook.com/softservsistemas/>  [Conecte-se ao Linkedin] <https://www.linkedin.com/company/softserv-sistemas>  [Siga-nos no Twitter] <https://twitter.com/softserv1994>  [Siga-nos no Instagram] <https://www.instagram.com/softservsistemas>  [Inscreva-se em nosso canal] <http://www.youtube.com/c/SoftservBr1994>    André Fonseca
Pesquisa e Desenvolvimento
Suporte
skype.softserv
(11) 3995 5200
(21) 3195 5200
(31) 3195 5200
(41) 3195 5200
(51) 3195 5200

Comercial
0800 727 2099
Ligação gratuita
São Paulo
Rio de Janeiro
Minas Gerais
Paraná
Rio Grande do Sul


Brasil
[Veja no ***@***.***,-43.271048,17z/data=!4m5!1m2!2m1!1ssoftserv!3m1!1s0x0000000000000000:0xa22666f336c06271?hl=pt-BR>    Sede
Av. Pastor Martin Luther King Jr. 126 Office 2000 Sala 226,
Shopping Nova América, Rio de janeiro - RJ, 20765-971   [http://softserv.com.br/email/assinatura/PENSE_IMPRIMIR.gif]
________________________________



________________________________
De: Simon Binder ***@***.***>
Enviado: terça-feira, 1 de junho de 2021 16:23
Para: simolus3/moor ***@***.***>
Cc: Andre Fonseca ***@***.***>; Author ***@***.***>
Assunto: Re: [simolus3/moor] forDartType is deprecated (#1243)


Can you try using the latest version of moor_generator (or the version which corresponds to the moor version you're using)? Newer generator versions don't use forDartType() anymore.
