### ISSUE TITLE
Need a correct sqlcipher.dll file to download for windows

### ISSUE THREAD

**Issue by iampopal** [simolus3/moor#1249]
I have download sqlcipher.dll file from
https://www.dll4free.com/sqlcipher.dll.html
website for windows

when i run the file 
```dart
  static DynamicLibrary sqlcipherOpen() {
    if (Platform.isLinux || Platform.isAndroid) {
      return DynamicLibrary.open('libsqlcipher.so');
    }
    if (Platform.isMacOS || Platform.isIOS) {
      return DynamicLibrary.open('/usr/lib/libsqlcipher.dylib');
    }
    if (Platform.isWindows) {
      return DynamicLibrary.open(join(
          'absolutePathTo',
          'sqlcipher.dll'));
    }

    throw UnsupportedError(
        'moor_ffi does not support ${Platform.operatingSystem} yet');
  }
```

I get the following error:
Asynchronous error
Invalid argument(s): Failed to load dynamic library 'absolutePathTo\sqlcipher.dll': 193

absolutePathTo is long path of the folder where sqlciper.dll is.

**Comment by simolus3** [comment]
Sorry, I don't have a lot of experience with Windows development so I probably can't help a lot. Looking at the [documentation for the search order](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order), absolute paths to dlls should be supported by Windows though. Maybe there's an issue with the dll you're using? 

If you're using chocolatey, you can also install it with `choco install sqlite`.
