### ISSUE TITLE
Custom inserts

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#125]
What's the recommended method for executing a custom insert statement like `INSERT INTO foo SELECT * FROM bar`? The `customUpdate` method seems to work, but it calls the executor's `runUpdate` method instead of `runInsert`, so the returned value is `changes()` instead of `last_insert_rowid()`.

**Comment by simolus3** [comment]
With a released moor version, this is not possible directly. Maybe using `runUpdate` and then running a custom select with `SELECT last_insert_rowid()` could be a workaround.

I've introduced the `customInsert` method on `develop` at a4b256f8a555c39713408dd79bd67437f453932d, which is also used for compiled insert statements.

**Comment by Mike278** [comment]
Some of my tests that call `customUpdate` immediately after instantiating a database are failing on develop with `NoSuchMethodError: The method 'execute' was called on null.` Looks like [this part](https://github.com/simolus3/moor/commit/a4b256f8a555c39713408dd79bd67437f453932d#diff-46044c83f81dc528f12adfe324bc0c4eL184) causes `doWhenOpened` to no longer be called.

**Comment by simolus3** [comment]
Thanks, it should work now.
