### ISSUE TITLE
sqlite3-native-library/3.32.3 forbidden access

### ISSUE THREAD

**Issue by MesutGunes** [simolus3/moor#1254]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':sqlite3_flutter_libs:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':sqlite3_flutter_libs:debugCompileClasspath'.
   > Could not resolve eu.simonbinder:sqlite3-native-library:3.32.3.
     Required by:
         project :sqlite3_flutter_libs
      > Could not resolve eu.simonbinder:sqlite3-native-library:3.32.3.
         > Could not get resource 'https://dl.bintray.com/sbinder/sqlite3-native-library/eu/simonbinder/sqlite3-native-library/3.32.3/sqlite3-native-library-3.32.3.pom'.
            > Could not GET 'https://dl.bintray.com/sbinder/sqlite3-native-library/eu/simonbinder/sqlite3-native-library/3.32.3/sqlite3-native-library-3.32.3.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BU�LD FAILED in 23s
Exception: Gradle task assembleDebug failed with exit code 1

moor: ^3.3.0
moor_ffi: ^0.8.0
moor_generator: ^3.3.0

flutter doctor
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.985], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

**Comment by simolus3** [comment]
`moor_ffi` is deprecated and no longer suppported.

Please:

- Use the `VmDatabase` from `package:moor/ffi.dart` instead
- Remove the dependency from `moor_ffi`
- Add a dependency on `sqlite3_flutter_libs: ^0.5.0`

**Comment by MesutGunes** [comment]
Thank you very much!
