### ISSUE TITLE
saving firebase background message into moor database error

### ISSUE THREAD

**Issue by NaarGes** [simolus3/moor#1262]
Hi. I'm using moor database for saving firebase cloud messages into my application.
there is no problem for foreground messages and they successfully insert in my notification table.
But for background messages it will throw this error:

```
I/flutter (14049): FlutterFire Messaging: An error occurred in your background messaging handler:
I/flutter (14049): NoSuchMethodError: The getter 'connection' was called on null.
I/flutter (14049): Receiver: null
I/flutter (14049): Tried calling: connection
```

I think it's about not having application context in background. In the other words I want to run moor as service while app is in background.

How can I fix this?

here is some code snippets:
notification handlers:
```
  static Future<void> _firebaseMessagingForegroundHandler(RemoteMessage message) async {
    Logger().i('@_firebaseMessagingForegroundHandler: Got a message whilst in the foreground!');
    if (message.notification != null) {
      await NotificationDao().addNotificationToLocalCache(message, false);
    }
  }

  static Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
    print('===>>> ${message.notification.title}');
    print('===>>> ${message.notification.body}');
    print('===>>> ${message.notification.apple}');
    print('===>>> ${message.notification.android.imageUrl}');
    print('===>>> ${message.notification.android.smallIcon}');
    print('===>>> ${message.sentTime}');
    await NotificationDao().insertNotification(message, false);
  }
```

notification_dao.dart
```
Future insertNotification(RemoteMessage message) =>
      into(notificationEntity).insert(NotificationEntityCompanion(
        title: Value(message.notification.title),
        body: Value(message.notification.body),
        dateTimestamp: Value(message.sentTime),
        read: Value(read),
      ));
```

**Comment by simolus3** [comment]
How are you using `NotificationDao()`, are you just creating it without an underlying moor database? Can you post the full stack trace or the constructor of `NotificationDao()` if you have anything custom?
Otherwise I recommend creating a new database in the background service and then obtain the `NotificationDao` through that.

**Comment by NaarGes** [comment]
No I have a database and it works perfectly fine.
There is nothing special about `notificationDao`

notification_dao.dart
```
import 'package:mamania_app/data/local/app_database.dart';
import 'package:mamania_app/data/local/notification/notification.entity.dart';
import 'package:mamania_app/data/model/app_notification.model.dart';
import 'package:moor/moor.dart';

part 'notification.dao.g.dart';

@UseDao(tables: [NotificationEntity])
class NotificationDao extends DatabaseAccessor<AppDatabase>
    with _$NotificationDaoMixin {
  NotificationDao(AppDatabase db) : super(db);

 Future insertNotification(RemoteMessage message) =>
      into(notificationEntity).insert(NotificationEntityCompanion(
        title: Value(message.notification.title),
        body: Value(message.notification.body),
        dateTimestamp: Value(message.sentTime),
        read: Value(read),
      ));
```


here is my database and I use a Global instance of it in my application, do I need to make the instance `static`?

app_database.dart
```

LazyDatabase _openConnection() {
  // the LazyDatabase util lets us find the right location for the file async.
  return LazyDatabase(() async {
    // put the database file, called db.sqlite here, into the documents folder
    // for your app.
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(join(dbFolder.path, 'db.v0.sqlite'));
    VmDatabase vmDatabase = VmDatabase(file);
    vmDatabase.logStatements = true;
    return vmDatabase;
  });
}

@UseMoor(tables: [
 // my tables
], daos: [
 // my daos
])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 7;

 // migrations and other stuffs
```

is there a problem in my usage? And how can I create a new database in background service and then obtain the `NotificationDao` through that?

**Comment by simolus3** [comment]
I see that `NotificationDao` has a constructor parameter, but you've used `await NotificationDao().insertNotification(...` without a parameter in your first snippet. Creating a new database in the background connection or re-using it should work.
Can you post the stack trace of the original exception?

**Comment by NaarGes** [comment]
there are no more lines of stack trace, just those 4 lines I've mentioned in my question.

no I'm sorry my bad, I'm passing `appDatabase` global variable into the constructor I just forgot to write it.
When I replace it with new database like below it throw following error:

```
  static Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
    Logger().i(
        "@_firebaseMessagingBackgroundHandler: Handling a background message: $message");
    await NotificationDao(AppDatabase()).insertNotification(message, false));
  }
```

error:
```
I/flutter ( 8245): WARNING (moor): It looks like you've created the database classAppDatabase multiple times. When these two databases use the same QueryExecutor, race conditions will ocur and might corrupt the database. 
I/flutter ( 8245): Try to follow the advice at https://moor.simonbinder.eu/faq/#using-the-database or, if you know what you're doing, set moorRuntimeOptions.dontWarnAboutMultipleDatabases = true
I/flutter ( 8245): Here is the stacktrace from when the database was opened a second time:
I/flutter ( 8245): #0      GeneratedDatabase._handleInstantiated (package:moor/src/runtime/api/db_base.dart:90:30)
I/flutter ( 8245): #1      new GeneratedDatabase (package:moor/src/runtime/api/db_base.dart:63:12)
I/flutter ( 8245): #2      new _$AppDatabase (package:mamania_app/data/local/app_database.g.dart:8204:36)
I/flutter ( 8245): #3      new AppDatabase (package:mamania_app/data/local/app_database.dart:114:19)
I/flutter ( 8245): #4      FirebaseNotificationService._firebaseMessagingBackgroundHandler (package:mamania_app/notification/notification_sevice.dart:87:27)
I/flutter ( 8245): #5      _firebaseMessagingCallbackDispatcher.<anonymous closure> (package:firebase_messag
W/android.stagin( 8245): Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
I/flutter ( 8245): Moor: Sent INSERT INTO notification_entity (title, body, image_path, action_type, action_text, action_description, date_timestamp, read) VALUES (?, ?, NULL, NULL, NULL, NULL, ?, ?) with args [test notification, 1623954455, 0]
W/FirebaseMessaging( 8245): Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.
I/FirebaseMessaging( 8245): Starting download of: https://cdn1.iconfinder.com/data/icons/twitter-ui-glyph/48/Sed-23-512.png
```

**Comment by NaarGes** [comment]
I instantiate my database global variable in the `main` before `runApp` method. Am I using it wrong?

**Comment by simolus3** [comment]
I wonder what happens when the background handler gets called when your app is not running? I'm not sure if `main` is called in that case, I don't really know how Flutter starts running Dart in that case.

You could store the database in a field with an initializer. It will only be opened when first used and then we definitely wouldn't have that problem. You could also make sure that the database is not-null in the message handler.

**Comment by NaarGes** [comment]
when application is running in background (pressing home button), `main` doesn't get called and application is onPause.

**Comment by simolus3** [comment]
I see how `main` wouldn't get called again, but I'm wondering if it would get called if your app has never been opened and you're receiving a background message. I guess no because we typically use `runApp` in `main` and that wouldn't make sense for background messages.

Either way, I think the solution is to not initialize stuff needed by the background handler in `main`. For moor, it's safe to just initialize the database in its field declaration (so a top-level `final AppDatabase db = AppDatabase()` should work).
I'm closing this as it doesn't appear to be a moor-specific issue anymore, but let me know if you run into more problems :)
