### ISSUE TITLE
get value between 2 dates, one is dynamic

### ISSUE THREAD

**Issue by heshaShawky** [simolus3/moor#1272]
I am building a finance app, created a table called wallets, the wallets table has a column called `startDate`. 

Now I need to only retrieve the latest created wallet and only if is in the range of 30 days since it been created using the value of the above field `startDate`, which means on the new month I can not get it

I'm thinking of using `isIn` but retuns a type error when trying using `tbl.startDate` with it
My Code:
```dart
Stream<Wallet> watchLatestCreatedWallet() {
  final Stream<Wallet> wallet = (
    select(wallets)
    ..orderBy([
      (wallet) => OrderingTerm(
        expression: wallet.startDate,
        mode: OrderingMode.desc
      ) 
    ])
    // somthing wrong I did, obviously always will return true
    // ..where((tbl) => tbl.startDate.isBetween(tbl.startDate, tbl.startDate + Duration(days: 30) ) )
    ..limit(1)
  )
  .watchSingle();

  return wallet;
}
```

**Comment by simolus3** [comment]
Couldn't you compute the 30 day offset in Dart and use `isBetweenValues`?

```dart
final rangeEnd = DateTime.now();
final rangeStart = rangeEnd.subtract(const Duration(days: 30));

// Then use .where((tbl) => tbl.startDate.isBetweenValues(rangeStart, rangeEnd));
```

Be aware that `subtract` does not subtract calendar days so it may be slightly inaccurate.
