### ISSUE TITLE
rename table column

### ISSUE THREAD

**Issue by MahdiPishguy** [simolus3/moor#128]
is any solution to rename column?

**Comment by simolus3** [comment]
It is not easy to do this automatically, so no. Sqlite doesn't have support for it, so there's little we can do here. Workarounds exist by
1. copying the existing table into a temporary table
2. dropping the old table
3. re-creating the old table, but with the updated column names
4. copying the data from the temporary table into the old table, for instance with an `INSERT INTO SELECT` statement

Some queries that could be used to achieve this are described in [this](https://stackoverflow.com/a/5987838) StackOverflow answer. You can use `issueCustomQuery` on the migrator to execute them.

If you only want to rename the column, I would actually recommend to rename it in Dart and keep the old sql name. So for instance,
```dart
IntColumn myFancyColumn => integer()...();
```
could be renamed with
```dart
IntColumn myRenamedColumn => integer().named('my_fancy_column')...();
```
