### ISSUE TITLE
java.security.GeneralSecurityException: decryption failed from pre null safe to null safe database

### ISSUE THREAD

**Issue by devaronius** [simolus3/moor#1284]
**Describe the bug**

I'm using encrypted_moor with sqlite3_flutter_libs for my encrypted database.
after updating the packages and enabling null safety my old encrypted db always fails with 

```
E/Finsky: [13903] aerc.b(3): Error while reading encrypted model
    java.security.GeneralSecurityException: decryption failed
        at aofr.a(PG:7)
        at aerc.b(PG:2)
        at aepd.apply(Unknown Source:3)
        at j$.util.Optional.map(Optional.java:265)
        at aeqa.<init>(PG:6)
        at adzi.apply(Unknown Source:3)
        at j$.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at j$.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at j$.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at j$.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at j$.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at j$.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at j$.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:132)
        at j$.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at j$.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at adzu.a(PG:13)
        at aedr.a(Unknown Source:38)
        at aoaz.c(PG:2)
        at aobb.run(PG:9)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at lbm.run(PG:13)
        at java.lang.Thread.run(Thread.java:923)
```
        
and later on with the error File is not a database. 
        
from a clean build the new encryption functions work without no problem.
        
Personaly I think it is the cipher version but adding the Pragma calls for compatibility or migration doesn't seems to work.
        
```dart
    return VmDatabase(
        file,
        setup: (rawDb) {
          rawDb.execute("PRAGMA key = '$key';");
          rawDb.execute("PRAGMA cipher_compatibility=3;");
        },
      );
```
      

does anyone what can be the case of this?

**Comment by simolus3** [comment]
The `VmDatabase` doesn't call Java code, so I think there's a good chance that the `java.security.GeneralSecurityException` comes from somewhere else. Do you have a demangled stack trace to check if it comes from another library?

**Comment by davidmartos96** [comment]
I think you are mixing the 2 encryption solutions. The encrypted_moor which uses platform channels, and the sqlite_flutter_libs, which actually you have sqlcipher_flutter_libs available, where it uses Dart FFI instead.

**Comment by devaronius** [comment]
> I think you are mixing the 2 encryption solutions. The encrypted_moor which uses platform channels, and the sqlite_flutter_libs, which actually you have sqlcipher_flutter_libs available, where it uses Dart FFI instead.

What should be the correct encryption path for this? I tried the EncryptedExecutor way and dropped the sqlcipher_flutter_libs for the sqflite_sqlcipher lib 2.0.0 but got the same result.

for EncryptedExecutor I couldn't find a way to implement the PRAGMA values, except for the password that it asks for.

**Comment by davidmartos96** [comment]
@devaronius you can use either approach. sqflite_sqlcipher is used under the hood by encrypted_moor, so no need to explicitly use it.
If you want to use the Sqlcipher pragmas yourself I'd recommend using the FFI approach, as the platform channel implementation won't give you that freedom. It will try to migrate a Sqlcipher v3 database for you if you are on Android though, but that is essentially a call to PRAGMA cipher_migrate.
Plus, using the platform channel approach there are a few extra steps to make it work on release mode. I don't know if that is your case

**Comment by devaronius** [comment]
I've figured it out to make the app run on DB files made with `moor 3.4.0` and `moor 4.3.2`.

But for a small introduction, I did use multiple approaches with using encrypted_moor and sqlite3_flutter_libs and moor/ffi
This resulted in a DB file that now is double encrypted somehow. so I can't either use the two approaches separately.

the original _openConnection

```
void setupSqlCipher() {
  open.overrideFor(OperatingSystem.android, () => DynamicLibrary.open('libsqlcipher.so'));
}

LazyDatabase _openConnection() {
  // the LazyDatabase util lets us find the right location for the file async.
  return LazyDatabase(() async {
    setupSqlCipher();
    await applyWorkaroundToOpenSqlite3OnOldAndroidVersions();
    // put the database file, called db.sqlite here, into the documents folder
    // for your app.
    final dbFolder = await getApplicationDocumentsDirectory();
    final path = p.join(dbFolder.path, _dbName);
    final file = File(path);
    final LocalStorageService storage = Locator.instance().get<LocalStorageService>();

    final key = await storage.key;
    return VmDatabase(
      file,
      setup: (rawDb) {
        rawDb.execute("PRAGMA key = '$key';");
      },
    );
  });
}
```

the solution was to remove the  setupSqlCipher(); function. this made my DB file unreadable apparently.
But to be announced I have no clue why this even works, the current solution is more ffi than moor_encryted but somewhere uses moor_encryped for the decryption part.

**Comment by simolus3** [comment]
> the current solution is more ffi than moor_encryted but somewhere uses moor_encryped for the decryption part

It doesn't look like you're using `encrypted_moor` anywhere in the snippet you posted. I'm also a bit surprised that it works without the `setupSqlCipher` function, do you have a dependency on both the `moor_encrypted` and `sqlcipher_flutter_libs` packages? I'd probably drop one of them since only one is necessary (depending on which approach you want to use).
