### ISSUE TITLE
delete column from table

### ISSUE THREAD

**Issue by MahdiPishguy** [simolus3/moor#129]
is any solution about deleting column from table?

**Comment by simolus3** [comment]
Same as https://github.com/simolus3/moor/issues/128#issuecomment-526941802, I'm afraid. There's no builtin support from sqlite for this, so you would need to do that manually.

**Comment by dvoloshyn** [comment]
@simolus3, Not sure when sqlite added it but it seems to support column dropping now: [https://sqlite.org/lang_altertable.html#altertabdropcol](https://sqlite.org/lang_altertable.html#altertabdropcol)
Is it possible to add the native support for this?
For now I'm using the following code:
```
const dropTargetValue = "ALTER TABLE items DROP COLUMN targetValue";
m.database.customStatement(dropTargetValue);
```

**Comment by simolus3** [comment]
`DROP COLUMN` was added in sqlite3 3.35.0, I've added a `dropColumn` method to the migrator API in 8427a18e922a43e232a67fbd13bed1ea8395ecb6.
