### ISSUE TITLE
lint Warning on generated code

### ISSUE THREAD

**Issue by hpn33** [simolus3/moor#1299]
This
![image](https://user-images.githubusercontent.com/16251202/123942528-77a97d80-d9b0-11eb-8dfd-a3431d5fa744.png)

and This
![image](https://user-images.githubusercontent.com/16251202/123942619-90199800-d9b0-11eb-8158-a8e3e175a037.png)

**Comment by simolus3** [comment]
The parameters are there for backwards compatibility, I'll remove them in the next breaking release.

In general, I think you should exclude generated files from static analysis. Analysis hints are useful for code written by humans, I don't see much value for generated code.
You can exclude generated files by creating an `analysis_options.yaml` file in your project:

```yaml

analyzer:
  exclude:
    - "**/*.g.dart"
```
