### ISSUE TITLE
update table column to add property

### ISSUE THREAD

**Issue by MahdiPishguy** [simolus3/moor#130]
in this table of database:

```dart
class UserA1cTable extends Table{
  IntColumn get id => integer().autoIncrement()();
  IntColumn get weight=>integer()();
  IntColumn get value=>integer()();
  DateTimeColumn get createdAt=>dateTime()();
}
```

i want to add `nullable()` for `weight`, is this doable with the library? or is any `sqlite` feature to do this?

**Comment by simolus3** [comment]
Sadly, this also boils down to https://github.com/simolus3/moor/issues/128#issuecomment-526941802 as this is not something that can be done easily with sqlite.
