### ISSUE TITLE
Insert should guarantee to return rowid even though it updates on conflict

### ISSUE THREAD

**Issue by zmeid** [simolus3/moor#1303]
Most of my business logic relies on inserted rowIDs. I didn't know that insert's returned value can be inaccurate until i had issues with it. Then i noticed the doc:

```
/// The returned value can be inaccurate when [onConflict] 
/// is set and the insert behaved like an update.
```

As a workaround, i have implemented a logic to all my insert methods which checks if DoUpdate(old)=>(){}) runs. If it runs, then it is an update and i run a select query with unique columns(which are in DoUpdate::target) to get the accurate rowID and return it.

I am not sure how it is technically difficult, but i was wondering if it is possible to change insert's behavior to guarantee that it returns rowID. Or any better workaround than mine?

**Comment by simolus3** [comment]
`insert` always returns the last insert rowid. If you need accurate information for non-rowid tables or upserts, I recommend using [`insertReturning`](https://pub.dev/documentation/moor/latest/moor/InsertStatement/insertReturning.html) as Peter suggested.
