### ISSUE TITLE
Generated____Column classes not found

### ISSUE THREAD

**Issue by nailuj29gaming** [simolus3/moor#1309]
**Describe the bug**

A clear and concise description of what the bug is. Please briefly describe what behavior you expected, what behavior you saw, and how the bug can be reproduced.
`Generated[Type]Column`, where type is the type of the column are not found. These appear to be in every table, so it should be able to be reproduced with any database. I am using the latest version of all packages

**Comment by simolus3** [comment]
It should work after upgrading to `moor_generator` version 4.4.0 and re-running the build.

I thought these changes wouldn't be that breaking since they can be fixed with a rebuild, but clearly I was wrong. Sorry for the inconvenience.

**Comment by nailuj29gaming** [comment]
@simolus3 I can't upgrade moor_generator to 4.4.0
![image](https://user-images.githubusercontent.com/54189157/124384066-b33c9400-dc9d-11eb-9620-f1dead048720.png)
Here is a screenshot of what happens when I run `flutter pub outdated`

**Comment by simolus3** [comment]
Can you try adding `moor_generator: ^4.4.0` to your dependencies and post the error pub gives you? Then we can figure out which package is causing the incompatibilities.

I'm afraid you'll otherwise have to add `moor_generator: '>=4.0.0 <4.4.0'` until you can use the latest generator.

**Comment by nailuj29gaming** [comment]
```
Because moor_generator >=4.3.2 depends on analyzer ^1.7.1 which depends on meta >=1.3.0 <1.4.0, moor_generator >=4.3.2 requires meta >=1.3.0 <1.4.0.
And because every version of flutter_test from sdk depends on meta 1.4.0, moor_generator >=4.3.2 is incompatible with flutter_test from sdk.
So, because time_clock depends on both flutter_test any from sdk and moor_generator ^4.4.0, version solving failed.
Running "flutter pub get" in time_clock...                              
pub get failed (1; So, because time_clock depends on both flutter_test any from
sdk and moor_generator ^4.4.0, version solving failed.)
```

**Comment by nailuj29gaming** [comment]
@simolus3 I figured out the problem: I was on an unstable branch of flutter.

**Comment by selvam920** [comment]
same issue i'm getting master branch. is it working in stable version?

**Comment by nailuj29gaming** [comment]
I was able to upgrade, so I think so
