### ISSUE TITLE
[Exception] DatabaseException(database is locked (code 5 SQLITE_BUSY[5]): , while compiling: PRAGMA journal_mode

### ISSUE THREAD

**Issue by Sp4Rx** [simolus3/moor#131]
I'm writing my data in one bloc and reading and showing it to feed from another bloc. I'm dispatching my db_read_bloc after insert is finished(there is an `await`). I'm getting this exception in my db_read_bloc.

>[Exception] DatabaseException(database is locked (code 5 SQLITE_BUSY[5]): , while compiling: PRAGMA journal_mode

```
Stack trace:
#0 wrapDatabaseException (package:sqflite/src/exception_impl.dart:11)

#1 SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:29)
#2 _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite/src/database_mixin.dart:183)
#3 _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.openDatabase (package:sqflite/src/database_mixin.dart:503)

#4 _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.doOpen (package:sqflite/src/database_mixin.dart:594)

#5 SqfliteDatabaseOpenHelper.openDatabase (package:sqflite/src/database.dart:32)

#6 _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.openDatabase. (package:sqflite/src/factory_mixin.dart:100)

#7 ReentrantLock.synchronized.. (package:synchronized/src/reentrant_lock.dart:33)
#8 _rootRun (dart:async/zone.dart:1124)
#9 _CustomZone.run (dart:async/zone.dart:1021)
#10 _runZoned (dart:async/zone.dart:1516)
#11 runZoned (dart:async/zone.dart:1463)
#12 ReentrantLock.synchronized. (package:synchronized/src/reentrant_lock.dart:32)

#13 BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31)

#14 ReentrantLock.synchronized (package:synchronized/src/reentrant_lock.dart:28)

#15 _SqfliteDatabaseFactoryImpl&Object&SqfliteDatabaseFactoryMixin.openDatabase (package:sqflite/src/factory_mixin.dart:66)
#16 openDatabase (package:sqflite/sqflite.dart:150)
#17 _SqfliteDelegate.open (package:moor_flutter/moor_flutter.dart:68)

#18 DelegatedDatabase.ensureOpen (package:moor/src/runtime/executor/helpers/engines.dart:260)

#19 QueryExecutor.doWhenOpened (package:moor/src/runtime/executor/executor.dart:26)
#20 SimpleSelectStatement._getWithQuery (package:moor/src/runtime/statements/select.dart:191)

#21 SimpleSelectStatement.get (package:moor/src/runtime/statements/select.dart:187)

#22 WaveDao.getAllWavesWithOpinion (package:leher/databases/feed/daos/wave_dao.dart:112)

#23 UserFeedDbBloc._mapUserFeedDbToState (package:leher/blocs/user_feed_db/user_feed_db_bloc.dart:34)

#24 UserFeedDbBloc.mapEventToState (package:leher/blocs/user_feed_db/user_feed_db_bloc.dart:21)

#25 Bloc._bindStateSubject. (package:bloc/src/bloc.dart:127)
#26 Stream.asyncExpand.onListen. (dart:async/stream.dart:513)
#27 _rootRunUnary (dart:async/zone.dart:1132)
#28 _CustomZone.runUnary (dart:async/zone.dart:1029)
#29 _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
#30 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336)
#31 _DelayedData.perform (dart:async/stream_impl.dart:591)
#32 _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707)
#33 _PendingEvents.schedule. (dart:async/stream_impl.dart:667)
#34 _rootRun (dart:async/zone.dart:1120)
#35 _CustomZone.run (dart:async/zone.dart:1021)
#36 _CustomZone.runGuarded (dart:async/zone.dart:923)
#37 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:963)
#38 _rootRun (dart:async/zone.dart:1124)
#39 _CustomZone.run (dart:async/zone.dart:1021)
#40 _CustomZone.runGuarded (dart:async/zone.dart:923)
#41 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:963)
#42 _microtaskLoop (dart:async/schedule_microtask.dart:41)
#43 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

What I feel is to wait for the write lock to release, then perform the read

**Comment by simolus3** [comment]
It seems like the database is opened twice for some reason. Moor should actually prohibit this, so this seems like a bug. I'll try to reproduce this locally. Just to be sure:
1. both of your blocs always use the same database instance, right?
2. you're not changing the `singleInstance` parameter on `FlutterQueryExecutor`

**Comment by Sp4Rx** [comment]
Check this pattern if it helps
```
@UseMoor(tables: [Wave, Opinion], daos: [WaveDao, OpinionDao])
class FeedDatabase extends _$FeedDatabase {
  // we tell the database where to store the data with this constructor
  FeedDatabase._internal()
      : super(FlutterQueryExecutor.inDatabaseFolder(path: 'feed.db'));

  static FeedDatabase _instance = FeedDatabase._internal();

  factory FeedDatabase() => _instance;
  @override
  int get schemaVersion => 1;
}
```

**Comment by Sp4Rx** [comment]
Check this pattern if it helps
```
class FeedDatabase extends _$FeedDatabase {
  // we tell the database where to store the data with this constructor
  FeedDatabase._internal()
      : super(FlutterQueryExecutor.inDatabaseFolder(path: 'feed.db'));

  static FeedDatabase _instance = FeedDatabase._internal();

  factory FeedDatabase() => _instance;
  @override
  int get schemaVersion => 1;
}
```

**Comment by simolus3** [comment]
I couldn't reproduce the issue you're describing. Your setup of first running an insert and then selecting right afterwards should be similar to this one
```dart
// inside the feed database
Future reproduce() {
  await into(...).insert(...);
  await select(...).get();
}
```

Does the error only occur with your bloc setup or can you write a method on your `FeedDatabase` that throws a similar error when called before anything else?

**Comment by simolus3** [comment]
Does that issue still occur when you add this to your pubspec?
```yaml
dependency_overrides:
  moor:
   git:
    url: https://github.com/simolus3/moor.git
    ref: fix-open
    path: moor/
  moor_flutter:
    git:
      url: https://github.com/simolus3/moor.git
      ref: fix-open
      path: moor_flutter/
```
```

**Comment by simolus3** [comment]
We had a bug that sometimes opened a database more than once, I think it is very likely that the bug has also caused this problem. I've fixed the bug with version 1.7.2 of the moor package. Can you try running `flutter clean` and then `flutter packages upgrade`? Let me know if you still run into any issues.

**Comment by Dooks123** [comment]
We are on `moor_flutter: ^4.0.0` and got `SqliteException(5): database is locked, database is locked (code 5)`
:/ Not happy so far (This is happening in production with a new client, not good impressions)

**Comment by nivla360** [comment]
I'm also experiencing same issue

**Comment by Dooks123** [comment]
@nivla360 We actually got around it by adding a lot more code to check the database status. It was a long time ago though. But this is what we've ended up with:

     Future<void> _registerAppDatabase({int tryCount = 0}) async {
       if (!GetIt.I.isRegistered<AppDatabase>()) {
         String databasePath = '';
         AppDatabase? appDatabase;
         try {
           databasePath = await FileManager.getDatabasePath();
           final queryExecutor = await AppDatabase.getConnection(databasePath);
     
           appDatabase = AppDatabase(queryExecutor);
           await appDatabase.testAllTables();
     
           GetIt.I.registerSingleton<AppDatabase>(appDatabase);
         } catch (error, stack) {
           await Analytics.trackException(
             EventTag.RegisterDatabase,
             error.toString(),
             stack,
           );
     
           if (appDatabase != null) {
             await appDatabase.close();
           }
           if (GetIt.I.isRegistered<AppDatabase>()) {
             GetIt.I.get<AppDatabase>().close();
             GetIt.I.unregister<AppDatabase>();
           }
     
           await FileManager.deleteFileIfExist(databasePath);
     
           if (tryCount < 5) {
             await _registerAppDatabase(tryCount: tryCount + 1);
           } else {
             throw error;
           }
         }
       } else {
         print('[GetIt] <AppDatabase> already registered');
       }
     }

**Comment by nivla360** [comment]
> @nivla360 We actually got around it by adding a lot more code to check the database status. It was a long time ago though. But this is what we've ended up with:
> 
> ```
>  Future<void> _registerAppDatabase({int tryCount = 0}) async {
>    if (!GetIt.I.isRegistered<AppDatabase>()) {
>      String databasePath = '';
>      AppDatabase? appDatabase;
>      try {
>        databasePath = await FileManager.getDatabasePath();
>        final queryExecutor = await AppDatabase.getConnection(databasePath);
>  
>        appDatabase = AppDatabase(queryExecutor);
>        await appDatabase.testAllTables();
>  
>        GetIt.I.registerSingleton<AppDatabase>(appDatabase);
>      } catch (error, stack) {
>        await Analytics.trackException(
>          EventTag.RegisterDatabase,
>          error.toString(),
>          stack,
>        );
>  
>        if (appDatabase != null) {
>          await appDatabase.close();
>        }
>        if (GetIt.I.isRegistered<AppDatabase>()) {
>          GetIt.I.get<AppDatabase>().close();
>          GetIt.I.unregister<AppDatabase>();
>        }
>  
>        await FileManager.deleteFileIfExist(databasePath);
>  
>        if (tryCount < 5) {
>          await _registerAppDatabase(tryCount: tryCount + 1);
>        } else {
>          throw error;
>        }
>      }
>    } else {
>      print('[GetIt] <AppDatabase> already registered');
>    }
>  }
> ```

Thanks for your suggestion. However, I resolved this by quitting/stopping the app and running it again. I realized hot restarting it, was causing the issue. It seems GetIt doesn't properly dispose the database class when the app is restarted.

**Comment by Murmurl912** [comment]
I’m encountering this issue exclusively on Android devices, particularly on low-end models in production, but I can't replicate it in testing. It seems related to activities starting multiple times or being restarted. I attempted to use a cached Flutter engine tied to the application process lifecycle, which resolved the database locked error but introduced other issues.

 Is it possible to reuse a database connection or close it when an activity is destroyed?

**Comment by Dooks123** [comment]
@Murmurl912 One thing to try is to use singleton connection but when there are no more queries to be run, close the connection. Create a queue and once the queue is empty, close the connection. Haven't tried this but seems like it will clear up resources for low-end devices.

**Comment by Murmurl912** [comment]
> I’m encountering this issue exclusively on Android devices, particularly on low-end models in production, but I can't replicate it in testing. It seems related to activities starting multiple times or being restarted. I attempted to use a cached Flutter engine tied to the application process lifecycle, which resolved the database locked error but introduced other issues.
> 
> Is it possible to reuse a database connection or close it when an activity is destroyed?

I discovered that my issue was actually caused by a third-party plugin crashing on `activity.onDestroy()`, which prevented the Flutter engine from properly close. As a result, when a new engine is created, it also establishes a new SQLite connection, leading to multiple open connections.

**Comment by Dooks123** [comment]
@Murmurl912 Glad you sorted it
