### ISSUE TITLE
Try changing the name to the name of an existing class, or creating a class with the name 'GeneratedIntColumn'.dartundefined_class

### ISSUE THREAD

**Issue by selvam920** [simolus3/moor#1310]
Getting below error

Flutter 2.4.0-1.0.pre.68 • channel master • https://github.com/flutter/flutter.git
Framework • revision c8884b53c6 (2 hours ago) • 2021-07-03 21:16:02 -0400
Engine • revision 5a4b9bacd5
Tools • Dart 2.14.0 (build 2.14.0-276.0.dev)

![image](https://user-images.githubusercontent.com/20491308/124371960-58f30180-dca4-11eb-80dd-bc93998b889e.png)

**Comment by simolus3** [comment]
Whne you're using `moor` version 4.4.0, please upgrade to `moor_generator` version `4.4.0` and run the build again. Sorry for the inconvenience!
