### ISSUE TITLE
Moor don't generate tables

### ISSUE THREAD

**Issue by berdibekovaG** [simolus3/moor#1317]
Hi! It were work fine, but today moor don't generate tables. How can I fix it? 
I create tables like: 

```dart
class EntityRooms extends Table {
  //IntColumn get id => integer().autoIncrement().nullable()();
  TextColumn get roomId => text().withLength(min: 1, max: 50)();

  TextColumn get eventIdName => text()
      .nullable()
      .customConstraint('NULL REFERENCES entityRooms(eventId)')();

  @override
  Set<Column> get primaryKey => {this.roomId};
}
```

but in generated file there is only:

```dart
abstract class _$MainDatabase extends GeneratedDatabase {
  _$MainDatabase(QueryExecutor e) : super(SqlTypeSystem.defaultInstance, e);
  @override
  Iterable<TableInfo> get allTables => allSchemaEntities.whereType<TableInfo>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [];
}
```
in terminal there is errors like  The type EntityRooms* is not a moor table

I did flutter clean, upgrade, but there is no result.
moor version: ^4.4.0

**Comment by simolus3** [comment]
Thanks for the report! Are there any errors on the table declaration?

**Comment by berdibekovaG** [comment]
Hi! thanks for quick reply! I have 2 db, and both of them is crashed. I
will send screenshots. If it need I will send all code of db logic. Thanks
for attention!

вт, 6 июл. 2021 г. в 20:35, Simon Binder ***@***.***>:

**Comment by berdibekovaG** [comment]
The problem had been solved. it was because I didn't upgrade
moor_inspector. thanks for attentions!

вт, 6 июл. 2021 г. в 20:41, Gaukhar Berdibekova <
***@***.***>:
