### ISSUE TITLE
How to only return the effected rows moor is watching?

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#1318]
Take this for example: 
If I have a method watching a specific note id, i.e. **noteId  = 3**, in this case how to make moor to only return the effected rows?

```dart
Stream<List<NoteEntry>> watchANoteById({int noteId}) {
  return (select(todos)
            ..where((t) => t.id.equals(noteId)))
          .watch();
}
```

Listen to it in **initState()** like this:
```dart
void initState() {
  watchANoteById(noteId = 3)..listen((row) {
    // How to make this method here to be called and passing the new record(telling me the latest row) only when the note(nodeId = 3) is actually updated or deleted?
    // I found that this method is invoked even when other notes(nodeId != 3) are updated or deleted.
    // Am I missing something?
  }
}
```

**Comment by simolus3** [comment]
Moor streams may update more often than they need to. This is because they only consider tables for stream updates, so any write to `todos` will cause the stream to re-fire.

You can fix this by filtering out duplicates manually. First, I'd make the stream return a single item only:

```dart
Stream<NoteEntry> watchANoteById({int noteId}) {
  return (select(todos)
            ..where((t) => t.id.equals(noteId)))
          .watchSingleOrNull();
}
```

Then, you could use ` watchANoteById(noteId: 3).distinct()` as a stream to remove duplicates.

**Comment by jims57** [comment]
@simolus3 
The **watchSingleOrNull()**  method isn't supportive in moor I am using, which is the min version of it supporting this method? I use **watchSingle()** to replace it. It works when I use **watchSingle()** in my project which uses **moor: ^3.4.0** and **moor_ffi: ^0.8.0** in **pubspec.yaml**.
![image](https://user-images.githubusercontent.com/1920873/124858472-b1960780-dfe0-11eb-8c15-29e58333b9af.png)


I have another question about watching a whole table. For example:
 ```dart
 Stream<List<NoteEntry>> watchNotesRowsModified() {
  // I define this method to watch notes table, 
  // but I just want to make Stream.listen() or onData() event to return those rows 
  // that are actually updated or deleted by the user,
  // rather than return all rows in notes table
    return (select(notes)).watch();
  }
```

```dart
watchNotesRowsModified().distinct().listen((rows) {
  var r = rows;
  // How to make rows only contains the rows effected,
  // i.e. if noteId = 3 and noteId = 4 are updated by moor update method,
  // I'd like rows here is only about these two rows(noteId = 3 and noteId = 4) passing new updated content in it,
  // other rows that are not updated or deleted in this operation shouldn't be passed along with the rows parameter.
});
```

By the way, if it is possible to return only effected rows, how can I know which rows are deleted or updated.
Especially, for those rows deleted by the user, I'd like to know if their status are deleted or not?
As you know, difference operation might lead to different logic in project. I don't want to add additional field in sqlite  note table to mark this operation, hoping moor itself supports it.

**Comment by simolus3** [comment]
> I use watchSingle() to replace it.

That's fine, `watchSingleOrNull` was added in moor 4.0 and is only really relevant for null safety.

> By the way, if it is possible to return only effected rows, how can I know which rows are deleted or updated.

You can use something like [diffutil](https://pub.dev/packages/diffutil_dart) to find changes (like additions or removals) between two lists.

**Comment by jims57** [comment]
@simolus3 Please see [#168 issue](https://github.com/simolus3/moor/issues/168), you mentioned that the next version will support triggers.

I am using  **moor: ^3.4.0**, I don't know if it supports triggers.

My questions:
a. Can I use triggers to record which rows are being updated, inserted or deleted, and then insert the records into another table, say **syncRows** table. In this case, my sync method just needs to get records from **syncRows** table to sync data with our server.
b. I don't find any triggers related document at **moor** site, do you have any doc about triggers?
c.By the way, can you give me a sample code about how to use **moor** triggers. Include: **insert**, **update** and **delete** operations.

**Comment by simolus3** [comment]
>I am using moor: ^3.4.0, I don't know if it supports triggers.

I think that versions supports triggers, but you must define triggers with SQL in a [moor file](https://moor.simonbinder.eu/docs/using-sql/moor_files/).

> Can I use triggers to record which rows are being updated, inserted or deleted, and then insert the records into another table, say syncRows table. In this case, my sync method just needs to get records from syncRows table to sync data with our server.

Yes, but you'd need a trigger for each operation and table:

```sql
CREATE TRIGGER users_created AFTER INSERT ON users BEGIN
  INSERT INTO syncRows (...);
END;

CREATE TRIGGER users_updated  AFTER UPDATE ON users BEGIN
  INSERT INTO syncRows (...);
END;

CREATE TRIGGER users_deleted  AFTER DELETE ON users BEGIN
  INSERT INTO syncRows (...);
END;
```

>  b. I don't find any triggers related document at moor site, do you have any doc about triggers?

Triggers are a sqlite3 feature [described here](https://sqlite.org/lang_createtrigger.html). Moor considers triggers for things like stream queries, but doesn't change them in any way so I think there's not need for moor-specific documentation on them.

**Comment by hatemragab** [comment]
Can i never watch only update
Or insert individual?

**Comment by hatemragab** [comment]
Is watchSingle
Only sink on item if insert or update happened? Not return and touch other Rows?
Only one row affected?
@simolus3

**Comment by simolus3** [comment]
> Can i never watch only update

Not directly for a query stream, but you could do `tableUpdates(TableUpdateQuery.onTable(yourTable, limitUpdateKind: UpdateKind.update)).asyncMap(yourQuery.get())`.

>  Or insert individual?

I'm not sure what you mean with this, a stream that only listens for inserts with a specific value? You can filter for inserts with the same approach as mentioned above, just use `UpdateKind.insert`.

> Is watchSingle

`watchSingle()` is just like `watch()`, expect that it assumes that your query will only return one row. This is why it returns the row directly instead of a `List`. It watches for the same events as a normal `watch()` stream.
