### ISSUE TITLE
implementing hasMany relation ship on two table

### ISSUE THREAD

**Issue by MahdiPishguy** [simolus3/moor#132]
in my application i have two table as `tickets` and `replies` 
each ticket can be have many reply and each reply belongs to one ticket, it means `ticket` hasMany `reply`

now i try to implementing that for `insert`, `update` and `select`

I'm not sure this implementation is correct

`TicketsTable` table:

```dart
class TicketsTable extends Table{
  IntColumn  get id=>integer().autoIncrement()();
  TextColumn get subject=>text()();

  IntColumn  get reply => integer()();
  IntColumn  get ticketNumber =>integer()();
}
```

`TicketRepliesTable` table:

```dart
class TicketRepliesTable extends Table{
  IntColumn  get ticketId=>integer()();
  IntColumn  get ticket =>integer()();

  @override
  Set<Column> get primaryKey => {ticket};

  TextColumn get reply=>text()();
}
```

`TicketsTableDao` dao: ( **which that have an error on join** )

```dart
@UseDao(tables:[TicketsTable])
class TicketsTableDao extends DatabaseAccessor<AppDb> with _$TicketsTableDaoMixin{
  final AppDb db;
  TicketsTableDao(this.db):super(db);

  Future<List<TicketsTableData>> getStoredTickets() => select(ticketsTable).get();
  Future<int> insertTicket(Insertable ticket) => into(ticketsTable)  .insert(ticket);

  Stream<List<TicketWithReplies>> watchAllTickets() {
    return (select(ticketsTable)
          ..orderBy(
            [(t) => OrderingTerm(expression: t.reply, mode: OrderingMode.desc)],
          ))
        .join(
          [leftOuterJoin(db.ticketRepliesTable, db.ticketRepliesTable.ticket.equalsExp(ticketsTable.reply)),],
        )
        .watch()
        .map((rows) => rows.map(
              (row) {
                return TicketWithReplies(
                  tickets: row.readTable(ticketsTable),
                  replies: row.readTable(db.ticketRepliesTable), /*<-- error*/
                );
              },
            ).toList());
    }
}
```

`TicketRepliesTableDao` dao:

```dart
@UseDao(tables:[TicketRepliesTable])
class TicketRepliesTableDao extends DatabaseAccessor<AppDb> with _$TicketRepliesTableDaoMixin{
  final AppDb db;
  TicketRepliesTableDao(this.db):super(db);

  Future<List<TicketRepliesTableData>> getStoredTicketReplies() => select(ticketRepliesTable).get();
  Future<int> insertTicketReply(Insertable reply) => into(ticketRepliesTable)  .insert(reply);
}
```

```dart
class TicketWithReplies{
  final TicketsTableData tickets;
  final List<TicketRepliesTableData> replies;

  TicketWithReplies({@required this.tickets, @required this.replies});
}
```
**now how can i save ticket replies in this hasMany relation ship?** 

save ticket with replies

**Comment by simolus3** [comment]
If you want to load a list of data (I assume your `TicketWithReplies` class looks like this), you would probably have to use more than one query. A common way to express this in sql is to
1. Load all `tickets`
2. Load all `replies` that belong to any ticket we found in 1.
3. Merge them together in your application code to create `TickerWithReplies`

We have a very similar example for one-to-many relationships that models shopping carts, see [here](https://gist.github.com/simolus3/b881d1a5cbb308d549dd484204e25776#file-shopping_cart-dart-L85-L128). Maybe that query helps, we use the `rxdart` package so that the result stream updates whenever query 1 or 2 updates. Let me know if you run into problems.

**Comment by simolus3** [comment]
Actually, I think a single join query might work, but it's not much more readable (code from the top of my head, might need some adjustments)
```dart
.watch()
.map((rows) {
  final ticketWithReplies = <TicketsTableData, TicketRepliesTableData>{};
  for (var row in rows) {
    final ticket = row.readTable(ticketsTable);
    // create entry for ticket, if it doesn't exist
    final replies =  ticketWithReplies.putIfAbsent(ticket, () => []);
    // if it exists, add the reply to list
    final reply = row.readTable(ticketRepliesTable);
    if (reply != null) replies.add(reply);
  }

  // finally, transform the map to a list of TicketWithReplies
  return [for (var entry in ticketWithReplies.entries) TicketWithReplies(t.key, t.value)];
})
```

Might be a bit easier to read and doesn't need rxdart. Downside would be that the database sends the `Ticket` for each row, where it would actually only need do that once. Shouldn't matter when talking to a local sqlite database though.

**Comment by MahdiPishguy** [comment]
@simolus3 Thanks. i try to implementing that in basic project to test how can i do that, can i reply here when i can't?

**Comment by simolus3** [comment]
Yeah sure! Just let me know if you run into problems
