### ISSUE TITLE
Moor 4.4.0 broke moor_db_viewer

### ISSUE THREAD

**Issue by vanlooverenkoen** [simolus3/moor#1326]
https://github.com/vanlooverenkoen/moor_db_viewer/issues/43

I was already able to convert most of the code by looking at the newly generated database. Shouldn't this be a breaking change?

**Comment by vanlooverenkoen** [comment]
I already fixed it here: https://github.com/vanlooverenkoen/moor_db_viewer/pull/44

**Comment by simolus3** [comment]
Sorry for breaking your package! I assumed I could get this through without marking it breaking because the `GeneratedColumn` classes are mostly an implementation detail. I didn't consider (valid) usages in your package. In hindsight, it should have been treated a breaking change.
