### ISSUE TITLE
delete many

### ISSUE THREAD

**Issue by VadimOsovsky** [simolus3/moor#133]
Is there a way to delete multiple rows by feeding it a list of ids or other fields without writing custom SQL?

**Comment by simolus3** [comment]
Yes! You can use any `where` clause on a delete statement as well. To delete a list of ids, this should do the trick.
```
(delete(table)..where((r) => isIn(r.id, listOfIds))).go()
```
Any other `where` clause you could use on a select statement would work just as well. Let me know if you have any questions.

**Comment by rohansohonee** [comment]
``isIn is deprecated`` 

Can you please provide latest solution for delete many

**Comment by VadimOsovsky** [comment]
@rohansohonee r.id.isIn(listOfIds))
