### ISSUE TITLE
type 'Null' is not a subtype of type 'int' in type cast when using enum column

### ISSUE THREAD

**Issue by vikalpnagar** [simolus3/moor#1338]
When updating an enum value to null, it throws **type 'Null' is not a subtype of type 'int' in type cast** even though the column is marked as nullable

Defined an enum column like below
`IntColumn get someEnumColumn => intEnum<SomeEnum>().nullable()();`

Below is my update query
```
(update(someTable)..where((tbl) => tbl.id.equals(id))).write(
        SomeTableCompanion(
            someEnumColumn: Value(null)));
```

When update query executes, it throws exception on below line.
package:moor/src/runtime/types/custom_type.dart:39:38

```
@override
  int? mapToSql(T? value) {
    return (value as dynamic)?.index as int;
  }:
``` 

Changing **(value as dynamic)?.index as int** to **(value as dynamic)?.index as int?** fixes the issue but these changes are lost after flutter clean or pub get.

**Comment by simolus3** [comment]
Thanks for the report, I've fixed this in c40c588f7a6c3ae267bffe44e2f601b226981b27.
