### ISSUE TITLE
Issue in storing list in a column in Moor

### ISSUE THREAD

**Issue by lakshyapunhani** [simolus3/moor#1339]
type 'List<dynamic>' is not a subtype of type 'List<String>?' in type cast

Trying to store a list inside a column with Type Converters but facing this issue. Took reference from this [https://github.com/simolus3/moor/issues/266] but could not succeed. 

This is the json I am trying to insert in DB

`"created_on": "2021-05-24T10:32:43.275648+00:00",
            "device_id": 6124,
            "id": 14,
            "parking_mode": true,
            "parking_schedule": true,
            "parking_schedule_days": [
                "Monday",
                "Tuesday"
            ],
            "parking_schedule_end_utc": null,
            "parking_schedule_start_utc": null,
            "updated_on": "2021-05-24T10:32:43.275648+00:00",
            "user_id": 4094`

And this is the code

```dart
class ParkingMode extends Table {

  IntColumn get id => integer().nullable()();
  IntColumn get device_id => integer().nullable()();
  IntColumn get user_id => integer().nullable()();
  BoolColumn get parking_mode => boolean().nullable()();
  BoolColumn get parking_schedule => boolean().nullable()();
  TextColumn get parking_schedule_days => text().map(
      const JsonConverter()).nullable()();
  TextColumn get parking_schedule_end_utc => text().nullable()();
  TextColumn get parking_schedule_start_utc => text().nullable()();

  @override
  Set<Column> get primaryKey => {id};

} 
class JsonConverter extends TypeConverter<List<String>, String> {
  const JsonConverter();


  @override
  List<String>? mapToDart(String? fromDb) {
    json.decode(fromDb!);
  }

  @override
  String? mapToSql(List<String>? value) {
    json.encode(value);
  }
}
```

Please help with this issue.

**Comment by simolus3** [comment]
Please wrap code in triple backticks (```) so that it gets formatted properly.

Your `JsonConverter` has no return statements, so both methods just implicitly return `null`. Try using this instead:

```dart
class JsonConverter extends TypeConverter<List<String>, String> {
  const JsonConverter();

  @override
  List<String>? mapToDart(String? fromDb) {
    return json.decode(fromDb!);
  }

  @override
  String? mapToSql(List<String>? value) {
    return json.encode(value);
  }
}
```

**Comment by lakshyapunhani** [comment]
Thanks a lot for replying but am still getting this error.

type 'List<dynamic>' is not a subtype of type 'List<String>?' in type cast

**Comment by kuhnroyal** [comment]
@simolus3 I actually have a similar problem with a list type converter. There seems to be something wrong with the inner type from what I saw today. I'll try to check it out tomorrow.

**Comment by kuhnroyal** [comment]
@simolus3  There is something wrong with type converters that are parameterized with `List<T>` and mapped to a text column, not sure if this is related. When generating from moor files, the nullability suffix of the inner type `T` is not correctly evaluated in `codeString` here: https://github.com/simolus3/moor/blob/develop/moor_generator/lib/src/model/types.dart#L65 which leads to generation of `List<T*>`.
In the `codeString` function only the nullability suffix of the outer type `List` is checked.

I have a converter `EnumListConverter<T> extends TypeConverter<List<T>, String>` - it has the following `DartType` `TypeConverter<List<T*>, String>`.

It seems the generator backend does not resolve the suffixes at all when NNBD is active, unless there is a `?` defined on a type. Maybe it should resolve to `none` by default with NNBD. That would remove the need to check for `*` suffix everywhere.

I only get this to generated at all when I parameterize it with `List<T?>` because then the nullability suffix is known, but then every field is also generated as `List<T?>` which is not what I want.

**Comment by simolus3** [comment]
This is actually due to a hack we employ when inferring the types of expressions in moor files. I know how to fix this, but I'll try to find a better approach first.

**Comment by simolus3** [comment]
@kuhnroyal Could you try using the generator from cea5a9119cfa5f2f62ae384ff5643e7ef87fbe41 and check if that fixes the problem?

**Comment by kuhnroyal** [comment]
Your change works and solved my problem! Thanks a lot! 👍

**Comment by fryette** [comment]
@simolus3 
Probably that is the same issue but:

if we have TypeConverter<List<String>, String?>

Then generator generates a class where the field is nullable.

**Comment by simolus3** [comment]
I think we should copy the type of the converter without making it nullable, do you have a small repro for that?

**Comment by darshansatra1** [comment]
I used the following code for converting List<String> from String for backlogs and backlogFailed. 
```
class UserDetails extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get backlogs => text().map(const JsonConvertor())();
  TextColumn get backlogFailed => text().map(const JsonConvertor())();
}

class JsonConvertor extends TypeConverter<List<String>, String> {
  const JsonConvertor();

  @override
  List<String>? mapToDart(String? fromDb) {
    return json.decode(fromDb!);
  }

  @override
  String? mapToSql(List<String>? value) {
    return json.encode(value);
  }
}
```

Error:
But it's throwing an error
```
type 'List<dynamic>' is not a subtype of type 'List<String>' in type cast
```

Am I doing something wrong?

**Comment by simolus3** [comment]
`json.decode` returns `dynamic`. If it's a list, it will be a `List<dynamic>` which indeed isn't a `List<String>`.

You can use `(json.decode(fromDb) as List).cast<String>()`.

**Comment by CodingWithTashi** [comment]
I had to use dynamic for both places 
`TypeConverter<List<dynamic>, String>`   
And maptodart and maptosql
