### ISSUE TITLE
4.0.19 - DatabaseException(no such table: feature_section (code 1 SQLITE_ERROR): , while compiling: INSERT INTO feature_section (feature_content_id, section_title, image_url, button_text, entity_link, entity_type) VALUES (?, ?, ?, ?, ?, ?))

### ISSUE THREAD

**Issue by singlakaran** [simolus3/moor#134]
I'm writing my data in one bloc

`0 wrapDatabaseException (package:sqflite/src/exception_impl.dart:11)
1 SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:29)
2 _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite/src/database_mixin.dart:183)
3 _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnRawInsert. (package:sqflite/src/database_mixin.dart:340)
4 _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnSynchronized. (package:sqflite/src/database_mixin.dart:290)
5 BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31)
6 _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnSynchronized (package:sqflite/src/database_mixin.dart:286)
7 _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnWriteSynchronized (package:sqflite/src/database_mixin.dart:307)
8 _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin.txnRawInsert (package:sqflite/src/database_mixin.dart:339)
9 _SqfliteDatabaseBase&Object&SqfliteDatabaseMixin&SqfliteDatabaseExecutorMixin.rawInsert (package:sqflite/src/database_mixin.dart:44)
10 __SqfliteDelegate&DatabaseDelegate&_SqfliteExecutor.runInsert (package:moor_flutter/moor_flutter.dart:135)
11 _DelegatedDatabase&QueryExecutor&_ExecutorWithQueryDelegate.runInsert. (package:moor/src/runtime/executor/helpers/engines.dart:62)
12 _DelegatedDatabase&QueryExecutor&_ExecutorWithQueryDelegate._synchronized (package:moor/src/runtime/executor/helpers/engines.dart:22)
13 _DelegatedDatabase&QueryExecutor&_ExecutorWithQueryDelegate.runInsert (package:moor/src/runtime/executor/helpers/engines.dart:60)
14 InsertStatement.insert. (package:moor/src/runtime/statements/insert.dart:36)
15 QueryExecutor.doWhenOpened. (package:moor/src/runtime/executor/executor.dart:26)
16 _rootRunUnary (dart:async/zone.dart:1132)
17 _CustomZone.runUnary (dart:async/zone.dart:1029)
18 _FutureListener.handleValue (dart:async/future_impl.dart:126)
19 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639)
20 Future._propagateToListeners (dart:async/future_impl.dart:668)
21 Future._complete (dart:async/future_impl.dart:473)
22 _SyncCompleter.complete (dart:async/future_impl.dart:51)
23 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28)
24 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294)
25 DelegatedDatabase.ensureOpen (package:moor/src/runtime/executor/helpers/engines.dart:0)
26 QueryExecutor.doWhenOpened (package:moor/src/runtime/executor/executor.dart:26)
27 InsertStatement.insert (package:moor/src/runtime/statements/insert.dart:35)
28 FeatureSectionDao.insertFeatureSection (package:leher/databases/explore/daos/feature_section_dao.dart:22)
29 FeatureSectionDbBloc.mapEventToState (package:leher/db_bloc/feature_section_db/feature_section_db_bloc.dart:30)
30 _AsyncStarStreamController.runBody (dart:async-patch/async_patch.dart:159)
31 _rootRun (dart:async/zone.dart:1120)
32 _CustomZone.run (dart:async/zone.dart:1021)
33 _CustomZone.runGuarded (dart:async/zone.dart:923)
34 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:963)
35 _rootRun (dart:async/zone.dart:1124)
36 _CustomZone.run (dart:async/zone.dart:1021)
37 _CustomZone.runGuarded (dart:async/zone.dart:923)
38 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:963)
39 _microtaskLoop (dart:async/schedule_microtask.dart:41)
40 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)`

**Comment by simolus3** [comment]
You probably added the `feature_section` table after you already opened the database once, right? If so, you would have to write a schema migration. The [docs](https://moor.simonbinder.eu/docs/advanced-features/migrations/) might be helpful to you here. Just bump up the schema version, and in the `onUpgrade`, so something like
```dart
onUpgrade(m, from, to) async {
  if (from == 1) {
    // add the feature_section table from version 1 to 2
    await m.createTable(featureSection);
  }
}
```
If that's not the case or you need more instructions, just let me know and I'll reopen.

**Comment by singlakaran** [comment]
@simolus3  but i did not add any column, so why i use migrartion

**Comment by simolus3** [comment]
Did you add that table though? Moor will create all tables when the database is first opened. Did you do this:
1. Declare a database with `@UseMoor(tables: [/* some tables, but not FeatureSection */])`
2. Run your app
3. Change the database to use `@UseMoor(tables: [FeatureSection, /* the other tables */])`

In that case, the `feature_section` table doesn't get created unless you explicitly tell moor to create that table in a schema migration. If you already included the `FeatureSection` in the first step, then it would sound more like a problem with moor.

**Comment by singlakaran** [comment]
no, i did not do this, my code is working fine but in some android phones it throw exception.

**Comment by simolus3** [comment]
Might be related to #135 or even #131, I'll investigate

**Comment by simolus3** [comment]
I've found and fixed a problem that could be related to this. Can you try adding this to your pubspec:
```yaml
dependency_overrides:
  moor:
   git:
    url: https://github.com/simolus3/moor.git
    ref: fix-open
    path: moor/
  moor_flutter:
    git:
      url: https://github.com/simolus3/moor.git
      ref: fix-open
      path: moor_flutter/
```
Those versions are very similar to those from `pub.dev`, but fixed a problem when opening the database. Can you check whether using these versions fixes the problem or throws another error? You might need to delete your app's data on the affected phones before using these versions. If they fix the problem I will release these versions to pub.

> in some android phones it throw exception

Do you know which phones are affected by this?

**Comment by simolus3** [comment]
This looks very similar to #135 which should be fixed by moor version 1.7.2. Can you try running `flutter clean` and then `flutter packages upgrade`? Let me know if you still run into any issues.

**Comment by singlakaran** [comment]
yes , i know its nokia phone.
i will ping you after test

**Comment by gopikm** [comment]
How did you solve this issue @singlakaran ?

**Comment by imatictz** [comment]
> How did you solve this issue @singlakaran ?
> I'm getting the same issue on a Nokia 7 plus

@gopikm were you able to solve it?

**Comment by shabeenabarde** [comment]
> How did you solve this issue @singlakaran ?
> I'm getting the same issue on a Nokia 7 plus

@gopikm hey, did you get anything? As I am looking for the same issue
