### ISSUE TITLE
Add looking 'ResultSetImplementation<T,R> table' after run 'build_runner'  in docs

### ISSUE THREAD

**Issue by dim0147** [simolus3/moor#1347]
**Is your feature request related to a problem? Please describe.**
Hi, I have three tables: `item`, `categories`, and `item_categories`. One item can have many categories so that why the `item_categories` exist, the structure will be like this:

![image](https://user-images.githubusercontent.com/44487221/125713537-e90b3545-1faf-4569-9534-764521f2ed76.png)
![image](https://user-images.githubusercontent.com/44487221/125713556-7f1d36d4-f886-47da-bed0-5873f039d61b.png)
![image](https://user-images.githubusercontent.com/44487221/125713677-48b17179-7b3b-4656-9597-3c0170aecc57.png)
- When run `flutter packages pub run build_runner build` to generate database, I execute the simple command `select(categories).get()` is fine, but with table `item_categories` I execute  `select(item_categories).get()` it getting error, after a while searching in `Database.g.dart` file which gerenate by `build_runner` scroll down to the end I found it:
![image](https://user-images.githubusercontent.com/44487221/125713849-cbb1fe6f-c99c-44b4-8948-fece31f538c7.png)
- Can you mention this one in the docs? And can you extend the data annotation for this variable when creating a table? Like
`@DataResultSetImplementation("myCustomVariable")`? thank you, the library is awesome.

**Comment by simolus3** [comment]
In general the docs have examples where the casing changed. I hoped that auto-complete would make the generated getters easy to discover. I'm not sure if it makes sense to customize the getter name in the database, what's wrong with `itemCategories`?
