### ISSUE TITLE
Invalid argument(s): Failed to load dynamic library ''/data/data/PACKAGE/lib/libsqlite3.so'': dlopen failed: library "/data/data/PACKAGE/lib/libsqlite3.so" not found

### ISSUE THREAD

**Issue by julienduchow** [simolus3/moor#1348]
In my production app I am facing an error with Moor that only happens on **some** Android 5 and Android 6 devices when opening the database:

Here is how I open the database:
```
Future<MoorIsolate> _createMoorIsolate() async {
  final dir = await paths.getApplicationDocumentsDirectory();
  final dirOfOldAndroidDatabase = Directory(dir.path + "/databases");
  if(Platform.isAndroid) {
    if (!await dirOfOldAndroidDatabase .exists()) {
      await dirOfOldAndroidDatabase .create(recursive: true);
    }
  }
  final path = Platform.isIOS ? p.join(dir.path, 'db.db') : p.join(dir.path.replaceAll("/app_flutter", "/databases"), 'db.db');
  final receivePort = ReceivePort();

  await Isolate.spawn(
    _startBackground,
    _IsolateStartRequest(receivePort.sendPort, path),
  );

  return (await receivePort.first as MoorIsolate);
}
```

The reason why I am replacing the path on Android is that I upgraded from a native Android app to Flutter and wanted to hold the old database.

**Comment by simolus3** [comment]
In `_startBackground`, can you try awaiting `applyWorkaroundToOpenSqlite3OnOldAndroidVersions` before opening the database? There's more information [here](https://github.com/simolus3/sqlite3.dart/tree/master/sqlite3_flutter_libs#problems-on-android-6).

**Comment by julienduchow** [comment]
Thanks for your quick response, in your readme you are suggesting 2 options. So to get the highest chance that it will work can I use both options together?

**Comment by simolus3** [comment]
If I remember correctly, the `applyWorkaroundToOpenSqlite3OnOldAndroidVersions` workaround works without `android.bundle.enableUncompressedNativeLibs=false`.

cc @knaeckeKami, do you remember whether opening the library in Java fixed the other loader issues too? Which one did you end up using?

**Comment by julienduchow** [comment]
I will try it. I changed the code like this is that the correct place for waiting for that call?
```
Future<MoorIsolate> _createMoorIsolate() async {

  final dir = await paths.getApplicationDocumentsDirectory();
  final dirOfOldAndroidDatabase= Directory(dir.path + "/databases");
  if(Platform.isAndroid) {
    if (!await dirOfOldAndroidDatabase.exists()) {
      await dirOfOldAndroidDatabase.create(recursive: true);
    }
  }
  final path = Platform.isIOS ? p.join(dir.path, 'pro_darts.db') : p.join(dir.path.replaceAll("/app_flutter", "/databases"), 'pro_darts.db');
  final receivePort = ReceivePort();

  await applyWorkaroundToOpenSqlite3OnOldAndroidVersions(); // <- Inserted here

  await Isolate.spawn(
    _startBackground,
    _IsolateStartRequest(receivePort.sendPort, path),
  );
  return (await receivePort.first as MoorIsolate);
}
```

**Comment by simolus3** [comment]
I think that should work, but just in case I'd probably put it inside the `_startBackground` function somewhere since that's where the database will be opened in the end.

**Comment by knaeckeKami** [comment]
I ended up using a whole combination of workarounds, but I think the applyWorkaround method fixes the issue and the other (older, partial) workarounds are not necessary anymore. But I would need to check my crash reporting logs if anything popped up.

But here's the function that I'm using currently:

```dart

// Do this once, before opening a database
// see https://github.com/simolus3/moor/issues/876
Future<void> _ensureSqlite3Initialized() async {
  //TODO maybe ensure synchronized?
  if (Platform.isAndroid) {
    await applyWorkaroundToOpenSqlite3OnOldAndroidVersions();
    final tempdir = (await getTemporaryDirectory()).path;
    final nativeLibDir = await NativeLibDir.nativeLibraryDir;
    open.overrideFor(
        OperatingSystem.android, () => _androidOpenSqlite(nativeLibDir));
    sqlite_lib.sqlite3.tempDirectory = tempdir;
  }
}

///https://github.com/simolus3/moor/issues/895
DynamicLibrary _androidOpenSqlite(String nativeLibDir) {
  if (Platform.isLinux || Platform.isAndroid) {
    try {
      return DynamicLibrary.open('libsqlite3.so');
    } catch (_) {
      debugPrint("fail opening sqlite, trying workarounds...");

      if (Platform.isAndroid) {
        try {
          final lib = DynamicLibrary.open("$nativeLibDir/libsqlite3.so");
          debugPrint(
              "successfully loaded sqlite3 with strange workaround at $nativeLibDir");
          return lib;
        } catch (_) {
          // On some (especially old) Android devices, we somehow can't dlopen
          // libraries shipped with the apk. We need to find the full path of the
          // library (/data/data/<id>/lib/libsqlite3.so) and open that one.
          // For details, see https://github.com/simolus3/moor/issues/420
          final appIdAsBytes = File('/proc/self/cmdline').readAsBytesSync();

          // app id ends with the first \0 character in here.
          final endOfAppId = max(appIdAsBytes.indexOf(0), 0);
          final appId =
              String.fromCharCodes(appIdAsBytes.sublist(0, endOfAppId));

          return DynamicLibrary.open('/data/data/$appId/lib/libsqlite3.so');
        }
      }

      rethrow;
    }
  }
  if (Platform.isIOS) {
    return DynamicLibrary.process();
  }
  if (Platform.isMacOS) {
    return DynamicLibrary.open('/usr/lib/libsqlite3.dylib');
  }
  if (Platform.isWindows) {
    return DynamicLibrary.open('sqlite3.dll');
  }

  throw UnsupportedError('Unsupported platform: ${Platform.operatingSystem}');
}
```
NativeLibDir Plugin for getting the native lib directory:

```java

  @Override
  public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
    if (call.method.equals("getNativeLibraryDir")) {
      final ApplicationInfo info = context.getApplicationInfo();
      if(info != null) {
        result.success(info.nativeLibraryDir);
      }else{
        result.success(null);
      }
    } else {
      result.notImplemented();
    }
  }

```

**Comment by simolus3** [comment]
Thanks for all the information! Btw, I think on iOS it's safer to open `sqlite3.framework/sqlite3` since `DynamicLibrary.process()` did not resolve to the version from `sqlite3_flutter_libs` in all cases. This is what `sqlite3` is doing by default on iOS:

```dart
if (Platform.isIOS) {
  try {
    return DynamicLibrary.open('sqlite3.framework/sqlite3');
    // Ignoring the error because its the only way to know if it was sucessful
    // or not...
    // ignore: avoid_catching_errors
  } on ArgumentError catch (_) {
    // In an iOS app without sqlite3_flutter_libs this falls back to using the version provided by iOS.
    // This version is different for each iOS release.
    //
    // When using sqlcipher_flutter_libs this falls back to the version provided by the SQLCipher pod.
    return DynamicLibrary.process();
  }
}
```

@julienduchow It looks like you don't need to enable uncompressed native libs if you're employing the other workaround.

**Comment by julienduchow** [comment]
Alright, thank you both for your help! :)
I will try it and see in 2-3 days when the update is in the Google Store if it worked and will comment then again.

**Comment by julienduchow** [comment]
@simolus3 
I tried to move the call in _startBackground, but that is causing an error on this line (Null check operator used on null value):
`await _platform.invokeMethod('doesnt_matter');`
So i kept the call where I wrote in my prev comment and this is working fine, just wanted to let you know.

**Comment by simolus3** [comment]
Ah right, good call. Yeah the workaround uses a platform channel which aren't available on background isolates. The workaround should still work (it involves opening the library in Java, opening the same name in Dart later will give us the opened library regardless on which thread we're opening it).

**Comment by knaeckeKami** [comment]
@simolus3 thanks, I should delete the non-android related code anyway, as it is unreachable (see 

```dart
open.overrideFor(
        OperatingSystem.android, () => _androidOpenSqlite(nativeLibDir));
```
On iOS, this is never called
