### ISSUE TITLE
It is not compatible with the latest version of freezed and json_serializable.

### ISSUE THREAD

**Issue by azeek** [simolus3/moor#1358]
It is not compatible with the latest version of freezed.

The analyzer version used by moor is too old..

json_serializable version 5.0.0 also has a dependency with analyzer version 2.0.0

```
Because no versions of moor_generator match >4.4.1 <5.0.0 and moor_generator 4.4.1 depends on analyzer ^1.7.1, moor_generator ^4.4.1 requires analyzer ^1.7.1.
And because freezed >=0.14.3 depends on analyzer ^2.0.0, moor_generator ^4.4.1 is incompatible with freezed >=0.14.3.
So, because **** depends on both freezed ^0.14.3 and moor_generator ^4.4.1, version solving failed.
```

**Comment by simolus3** [comment]
We're still blocked by no version of `analyzer_plugin` supporting analyzer 2.x. I've opened https://dart-review.googlesource.com/c/sdk/+/207302, let's hope that this changes soon.

**Comment by zs-dima** [comment]
@azeek +1

**Comment by nikitadol** [comment]
It remains to wait for the pub release
https://github.com/dart-lang/sdk/blob/master/pkg/analyzer_plugin/pubspec.yaml#L9-L12

**Comment by kuhnroyal** [comment]
@simolus3 The analyzer plugin has just been released.

**Comment by simolus3** [comment]
Thanks for letting me know, the latest analyzer is supported in 270bdc8bca3e090efa88312b72b00c40d05f6fa5.

**Comment by fernando-s97** [comment]
Even with

```yaml
dependencies:
  moor: ^4.4.1
  freezed_annotation: ^0.14.3
  json_annotation: ^4.1.0

dev_dependencies:
  moor_generator: ^4.4.1
  json_serializable: ^5.0.0
  build_runner: ^2.0.6
  freezed: ^0.14.3
```

The output of `flutter pub cache repair; flutter clean; flutter pub get` is:

```
Because no versions of moor_generator match >4.4.1 <5.0.0 and moor_generator 4.4.1 depends on analyzer ^1.7.1, moor_generator ^4.4.1 requires analy
zer ^1.7.1.
And because json_serializable 5.0.0 depends on analyzer ^2.0.0 and no versions of json_serializable match >5.0.0 <6.0.0, moor_generator ^4.4.1 is i
ncompatible with json_serializable ^5.0.0.
So, because biomaps depends on both json_serializable ^5.0.0 and moor_generator ^4.4.1, version solving failed.
Running "flutter pub get" in biomaps...
pub get failed (1; So, because biomaps depends on both json_serializable ^5.0.0 and moor_generator ^4.4.1, version solving failed.)
```

**Comment by North101** [comment]
> Even with
> 
> ```yaml
> dependencies:
>   moor: ^4.4.1
>   freezed_annotation: ^0.14.3
>   json_annotation: ^4.1.0
> 
> dev_dependencies:
>   moor_generator: ^4.4.1
>   json_serializable: ^5.0.0
>   build_runner: ^2.0.6
>   freezed: ^0.14.3
> ```
> 
> The output of `flutter pub cache repair; flutter clean; flutter pub get` is:
> 
> ```
> Because no versions of moor_generator match >4.4.1 <5.0.0 and moor_generator 4.4.1 depends on analyzer ^1.7.1, moor_generator ^4.4.1 requires analy
> zer ^1.7.1.
> And because json_serializable 5.0.0 depends on analyzer ^2.0.0 and no versions of json_serializable match >5.0.0 <6.0.0, moor_generator ^4.4.1 is i
> ncompatible with json_serializable ^5.0.0.
> So, because biomaps depends on both json_serializable ^5.0.0 and moor_generator ^4.4.1, version solving failed.
> Running "flutter pub get" in biomaps...
> pub get failed (1; So, because biomaps depends on both json_serializable ^5.0.0 and moor_generator ^4.4.1, version solving failed.)
> ```
> 
> How can I solve that?

I think you need `flutter pub upgrade`

**Comment by fernando-s97** [comment]
In Android Studio I "Invalidate cache / restart" and then `flutter pub cache repair; flutter clean; flutter pub get; flutter pub upgrade; flutter pub run build_runner build --delete-conflicting-outputs`.

Same result

**Comment by simolus3** [comment]
The generator version supporting the latest analyzer is not on pub yet. In the meantime, you could use

```yaml
dependency_overrides:
  moor_generator:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: moor_generator
```

**Comment by kuhnroyal** [comment]
Just a quick warning. This now seems to require Flutter beta channel because of a `meta: 1.7.0` requirement.

**Comment by fernando-s97** [comment]
> ```yaml
> dependency_overrides:
>   moor_generator:
>     git:
>       url: https://github.com/simolus3/moor.git
>       ref: develop
>       path: moor_generator
> ```

Got it. Woudn't it be better to keep this issue open until a version with this fix gets on pub?

**Comment by zs-dima** [comment]
Any updates are welcome

**Comment by azeek** [comment]
flutter version has been upgraded to 2.5.0 and can be used.
