### ISSUE TITLE
tables.moor file can't use the table defined in database.dart file?

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#1359]
I'd like to define **folders** table in **database.dart** file. Is it possible for me to use it from **tables.moor** file?

![image](https://user-images.githubusercontent.com/1920873/126150385-4d504628-0e4f-4488-9364-12af00d37ca1.png)

**Comment by simolus3** [comment]
Yes, this is possible. Just like how it works in Dart, you need to import files into a `.moor` file to use the tables defined in there.

So you can just do:

```sql
import 'database.dart'; -- If the two files are next to each other, but you can also use package: imports or other relative paths

CREATE TRIGGER IF NOT EXISTS folders_after_update
  -- ...
```
