### ISSUE TITLE
Documentation issue: Writing queries

### ISSUE THREAD

**Issue by Pawkosss** [simolus3/moor#1360]
Need example how to use insertReturning wih onConfilict DoUpdate 

I have table with custom constraint and no idea how to use this function to do his work when trying insert existing object to table.

**Comment by simolus3** [comment]
The documentation describes how to use upserts and it describes how to use `insertReturning`. You can use the same `onConflict` parameter on `insertReturning`, just like how you'd use it for the regular `insert` function.

If you have a more specific example I can take look at adding it to the documentation.

**Comment by Pawkosss** [comment]
Hello
I found answer for my question in other github issue. I think you should add any example how to use this feature. For beginners like me is very difficult to do their tasks without any examples.

**Comment by simolus3** [comment]
Could you link to the relevant issue or comment so that I can add a similar example to the docs?
