### ISSUE TITLE
How to use annotation in tables.moor file?

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#1363]
![image](https://user-images.githubusercontent.com/1920873/126275842-dd96c75e-a107-4e65-a06e-68143e009615.png)

By the way, how to link **.moor** file to show format like **Dart**, I don't like the plain format without any color or theme to show code.

**Comment by North101** [comment]
You need to use an SQL comment which is
```sql
-- Comment
```

**Comment by simolus3** [comment]
Yup, line comments in SQL start with `--`, you can also use C-style `*/ comments */` spanning multiple lines.

**Comment by jims57** [comment]
@North101 thx.

**Comment by jims57** [comment]
![image](https://user-images.githubusercontent.com/1920873/126422866-6206e6d0-28fd-4306-9c58-af9834dee442.png)

**Comment by jims57** [comment]
And by the way, how to show **moor** file with code theme?
> By the way, how to link **.moor** file to show format like **Dart**, I don't like the plain format without any color or theme to show code.
![image](https://user-images.githubusercontent.com/1920873/126423059-6d8403dd-7789-4d5e-9fec-9de16be5e0ff.png)

**Comment by simolus3** [comment]
If you want to use multiple moor files, you can include all of them. If you refer to tables defined in one moor file in another moor file, you must also use an import.
So for instance if you had

```sql
-- this is lib/src/database/a.moor

CREATE TABLE a (
  id INTEGER NOT NULL
);
```

And you wanted to use `a` in another moor file, you can use

```sql
-- this is lib/src/database/b.moor

import 'a.moor'; -- necessary so that we can use table a

CREATE TRIGGER my_trigger AFTER INSERT ON a BEGIN
  /* ... */
END;
```

> And by the way, how to show moor file with code theme?

You can find a potential solution here: https://github.com/simolus3/moor/issues/473
