### ISSUE TITLE
[SQLPARSER] Collation is missing in IndexedColumn

### ISSUE THREAD

**Issue by MobiliteDev** [simolus3/moor#1368]
Do you think it could be possible to add CollateConstraint on `IndexedColumn` class like in `ColumnDefinition` class ?  
in [SQLite](https://www.sqlite.org/syntax/indexed-column.html)

![image](https://user-images.githubusercontent.com/54275508/126507630-63c24d9b-5a0f-4a15-ab55-8a133d597ece.png)

**Comment by simolus3** [comment]
In sqlparser, this construct is represented as a [`CollateExpression`](https://pub.dev/documentation/sqlparser/latest/sqlparser/CollateExpression-class.html) instead. The reason is that `expr COLLATE name` can also be used as an expression in general, so there would be an ambiguity if we added it to `IndexedColumn` as well.

**Comment by MobiliteDev** [comment]
I understand but there are still some strange things in the use.
For example, this index:
![image](https://user-images.githubusercontent.com/54275508/126608132-6677a672-ada1-4cbd-9f59-18f5466120cc.png)


is interpreted like this

![image](https://user-images.githubusercontent.com/54275508/126608223-84f10e27-8bf1-4bfd-92ad-a0b062d16fe4.png)


The second indexedColumn is a ColllateExpression.  
Honestly, there is why I wrote you this issue, on `IndexedColumn` there is a `ordering` property, to have a `collation` property could be better for lisibility isn't it ?

**Comment by simolus3** [comment]
> The second indexedColumn is a ColllateExpression.

Isn't that correct though? It's an `IndexedColumn(CollateExpression(Reference(nom_pro), NOCASE), OrderingMode.descending)`. That accurately covers the AST here, right? The token span is off and I've fixed that in ed338f2fb001edf384cd0077d278f250e86fb78f, but it shouldn't make a difference.

> to have a `collation` property could be better for lisibility isn't it ?

The AST classes were mainly designed for analysis and to be constructed by the parser. Convenience when creating them manually hasn't been a design goal, and I still think that we should avoid ambiguous node constructs.

**Comment by MobiliteDev** [comment]
Ok, thank you for details.
