### ISSUE TITLE
Can't use string literals as default values

### ISSUE THREAD

**Issue by rebaz94** [simolus3/moor#137]
Hello, 
I am creating a class table which has 2 fields that has default value, here the code
```
class SocialItems extends Table {
  IntColumn get id => integer().nullable()();

  TextColumn get type => text()();

  TextColumn get data => text()();

  TextColumn get name => text().withDefault(const Constant(""))();

  TextColumn get asset => text().withDefault(const Constant(""))();

  @override
  Set<Column> get primaryKey => {id};
}
```

when database is creating, It generate a wrong SQL like that
```
CREATE TABLE IF NOT EXISTS social_items (id INTEGER NULL, type VARCHAR NOT NULL, data VARCHAR NOT NULL, name VARCHAR NOT NULL DEFAULT ?, asset VARCHAR NOT NULL DEFAULT ?, PRIMARY KEY (id));) 
```

but it must generate like this
```
CREATE TABLE IF NOT EXISTS social_items (id INTEGER NULL, type VARCHAR NOT NULL, data VARCHAR NOT NULL, name VARCHAR NOT NULL DEFAULT '', asset VARCHAR NOT NULL DEFAULT '', PRIMARY KEY (id));
```

My question is my table definition is wrong or there is an issue the library ? and how to solve this ?

Thanks

**Comment by simolus3** [comment]
The main reason we don't generate string literals for `Constant<String>` expressions is that I didn't want to deal with sql injection vulnerabilities. I guess they shouldn't be that hard to handle though, we only need to escape two chars.

That said, does the create statement not work? Moor should bind the variable `?` to the appropriate value. If sqlite rejects variables as defaults we should definitely look into generating literals instead.

**Comment by rebaz94** [comment]
Yes. The create statement not working and table not created. in the debug shows ```?``` for default value.

**Comment by simolus3** [comment]
We now support writing string literals (which are used to represent `Constant<String>` expressions in sql) on the `develop` branch, so this will be in the next version of moor.
If you really need it urgently, a current workaround would be to [create the table in sql](https://moor.simonbinder.eu/docs/using-sql/custom_tables/) instead.

**Comment by rebaz94** [comment]
Thanks so much for your quick responses.
