### ISSUE TITLE
insertReturning documentation

### ISSUE THREAD

**Issue by anisalibegic** [simolus3/moor#1371]
When using **insertReturning** and custom **sqlite3.dll** files documenation should mention that minimum **sqlite3** version should be 3.35.0.

[Source](https://www.sqlite.org/lang_returning.html#:~:text=The%20RETURNING%20syntax%20has%20been%20supported%20by%20SQLite%20since%20version%203.35.0)

**Comment by kuhnroyal** [comment]
https://github.com/simolus3/moor/blob/develop/moor/lib/src/runtime/query_builder/statements/insert.dart#L79

**Comment by anisalibegic** [comment]
> https://github.com/simolus3/moor/blob/develop/moor/lib/src/runtime/query_builder/statements/insert.dart#L79

I don't see it anywhere on the [web documenation](https://moor.simonbinder.eu/docs/getting-started/writing_queries/#returning).

**Comment by kuhnroyal** [comment]
True, that could probably be added there. You could make a small PR :)

**Comment by anisalibegic** [comment]
> True, that could probably be added there. You could make a small PR :)

There we go https://github.com/simolus3/moor/pull/1372!
