### ISSUE TITLE
How to reference table object dynamically in moor?

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#1379]
This is an example, please take a look at the following code:
Let's say, we want to delete  a row by row id, you can see, I use **folders** to reference the **folders** table in **Sqlite**.

```dart
 Future<int> deleteRow({
    @required int rowId,
  }) async {
      return await (delete(folders)
        ..where((t) => t.id.equals(rowId)))
      .go();
  }
```

Actually, we need the same logic on other tables, such as **notes**, **users**, for example. We don't want to reinvent the wheel to write something like: 
```dart
 Future<int> deleteRow({
    @required int rowId,
  }) async {
      return await (delete(notes)
        ..where((t) => t.id.equals(rowId)))
      .go();
  }
```

```dart
 Future<int> deleteRow({
    @required int rowId,
  }) async {
      return await (delete(users)
        ..where((t) => t.id.equals(rowId)))
      .go();
  }
```

How to reference the tables object dynamically?  Hoping **moor** can do it like this. 
**tableObject** is passed by code dynamically.

```dart
 Future<int> deleteRow({
    @required dynamic tableObject,
    @required int rowId,
  }) async {
      return await (delete(tableObject)
        ..where((t) => t.id.equals(rowId)))
      .go();
  }
```

**Comment by simolus3** [comment]
This should work:

```dart
 Future<int> deleteRow<T extends Table, D>({
    @required TableInfo<T, D> tableObject,
    @required int rowId,
  }) async {
      return await (delete(tableObject)
        ..where((t) => (t as dynamic).id.equals(rowId)))
      .go();
  }
```

If you want to avoid using dynamic, you can also use:

```dart
 final id = table.$columns.where((column) => column.$name == 'id').single;
 return await (delete(tableObject)
        ..where((_) => id.equals(rowId)))
      .go();
```

**Comment by jims57** [comment]
@simolus3 thanks, I got it. By the way, you missed **ClassData** for **D**, I corrected it like this:
 ```dart
 Future<int> deleteRow<T extends Table, D extends DataClass>({
    @required TableInfo<T, D> tableObject,
    @required int rowId,
  }) async {
    var effectedRowsCount = await (delete(tableObject)
          ..where((t) => (t as dynamic).id.equals(rowId)))
        .go();

    return effectedRowsCount;
  }
```

**Comment by jims57** [comment]
@simolus3 By the way, how to reference **Companions**, such as **UsersCompanion**, dynamically?
I don't want to write duplicate code to update.

For example:

Update users:
```dart
   var usersCompanion = UsersCompanion(
            id: Value(rowId),
            tcbId: Value(tcbId),
          );

    return await (update(users)..where((u) => u.id.equals(rowId)))
              .write(usersCompanion);

```

Update notes:
```dart
   var notesCompanion = NotesCompanion(
            id: Value(rowId),
            tcbId: Value(tcbId),
          );

    return await (update(folders)..where((f) => f.id.equals(rowId)))
              .write(foldersCompanion);
```

**Comment by simolus3** [comment]
Companions are independent classes that can't be constructed dynamically. You could write your own `Insertable` class for common values and use that instead.

**Comment by jims57** [comment]
@simolus3 What should I do if companions have different fields? Hoping you can give me alternative solutions. Thx.
For example:

**NotesCompanion** has **tcbId** field, whereas **UsersCompanion** hasn't.
And **UsersCompanion** has **address** field, whereas **NotesCompanion** hasn;t
```dart
var notesCompanion = NotesCompanion(
            id: Value(rowId),
            tcbId: Value(tcbId),
          );
```


```dart
var usersCompanion = UsersCompanion(
            id: Value(rowId),
            address: Value(address),
          );
```

**Comment by simolus3** [comment]
Yeah, different fields are the reason different companion classes exists 😃 You could introduce a general companion that only has the shared fields, and then your code would have to use the specialized companions if you need the fields only available on one table.
