### ISSUE TITLE
How to make toJson() make keep DateTime value as String rather than int, or how to keep its precision more accurate?

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#1380]
You can see [this](https://www.gitmemory.com/issue/simolus3/moor/40/502796243), someone once talked about why moor converts **DateTime** into **int**(timestamp). 

My questions:
a. How to make it to return as **String** type rather than **int**?
b. If question **a** isn't a good advice, how to make its precision more accurate?

As to question **b**, our biz want it like this:

![image](https://user-images.githubusercontent.com/1920873/126891035-bac0d190-b3d8-4c97-ba95-2540f705bdda.png)

**Comment by simolus3** [comment]
There are two options here:

- You could write a custom `ValueSerializer` that maps `DateTime` instances from an to strings. You can use `moorRuntimeOptions.defaultSerializer = YourSerializerClass()` to use it by default.
- You could use [custom row classes](https://moor.simonbinder.eu/docs/advanced-features/custom_row_classes/) with a custom json serialization logic, for instance by using `json_serializable` or `built_value`.
