### ISSUE TITLE
How to make moor to generate tables dynamically and inherit its parent tables's fields?

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#1381]
![image](https://user-images.githubusercontent.com/1920873/126892115-f82c6d24-65ba-4cc1-9d2c-7e6f59d9f1d9.png)

**Comment by simolus3** [comment]
Moor does not contain that functionality. You could write your own [builder](https://github.com/dart-lang/build/blob/master/docs/writing_a_builder.md) that generates a file with all the `Temp` table classes. As long as there's a source available when moor's generator runs, it will pick them up and generate tables for them.
