### ISSUE TITLE
How to watch database changes, which come from outside of Moor (platform-specific code for example)?

### ISSUE THREAD

**Issue by ivanburlakov** [simolus3/moor#1383]
I have an app with android service and foreground notification, which needs to save data to the database, even if the app is closed. In the app I use a `ListView` with a `StreamBuilder` to watch changes. But the problem is: when my app with a `ListView` is open and I insert into database from that outside service, my `ListView` does not refresh automatically, only on the reload of the widget.

I had two ideas on how to do this:
1. Listen to a `.sqlite` file update using filesystem.
2. Send message from platform-specific code to alert the change.

But I still don't know how to force a `Moor` `Stream` to update manually. And maybe there are better and simplier solutions to my problem? Thank you.

**Comment by simolus3** [comment]
I would probably recommend the second approach that you mentioned here. You can call `markTablesUpdated` or the more specific `notifyUpdates` on your database class to manually notify moor that tables have changed. Moor will then re-load all streams reading from those tables. 
So your native code could send a list of table names it changed and you could have a Dart listener translating that into calls to `markTablesUpdated`.

**Comment by henriqueArrazao** [comment]
> 1. Listen to a `.sqlite` file update using filesystem.

This does not work, although it triggers the streams it does not bring the new data, they are the same as before, and when I try to insert a register this error is thrown:
`attempt to write a readonly database, attempt to write a readonly database (code 1032)`

My code after changing the .sqlite file:
`_db.markTablesUpdated(_db.allTables);`

If I close the app and open again the data comes correctly. Am I doing something wrong?
