### ISSUE TITLE
Can't replace database sqlite file even when closed the old database instance

### ISSUE THREAD

**Issue by bahung1221** [simolus3/moor#1392]
Hi,

I facing a problem when I implementing the backup & restore feature. 

When restoring I call the `database.close()` method and then replace the current SQLite database file with the new one. Then I use [flutter_phoenix](https://github.com/mobiten/flutter_phoenix) to refresh my app and create a new database instance.
But after that, I can't query the database anymore and the console was showing below errors:

```
[logging] BUG IN CLIENT OF libsqlite3.dylib: database integrity compromised by API violation: vnode unlinked while in use: /private/var/mobile/Containers/Data/Application/.../Documents/todolist.sqlite
```

The app will work again when I kill the app or re-run `flutter run`.
It seems that the connection of SQLite wasn't close correctly when I call `database.close()` method. Or am i doing something wrong?

There is a part of my restore code:
```dart
    Database db = Provider.of<Database>(context, listen: false);

    // Close the current database
    await db.close();
    // Just added waiting 10 seconds to make sure the connection was closed
    await Future.delayed(Duration(seconds: 10));

    await CloudStorage().download(
      fileName: DB_FILE_NAME,
      destinationFilePath: dbPath,
      onProgress: (stream) {
        ...
      },
    );

   // Restart app after restored
   Phoenix.rebirth(context);
```

Thanks in advance 🍺

**Comment by bahung1221** [comment]
BTW, I'm using `moor_flutter ^4.0.0`

**Comment by simolus3** [comment]
This sounds like something that should be reproducible, you could you try to setup a small repro for this? Calling (and awaiting) `.close()` should make sure that the underlying database is closed.

If you're using a `FlutterQueryExecutor` multiple times without setting `sharedInstance: false`, the database may still be open if you have another database somewhere.

**Comment by bahung1221** [comment]
I trying to create a reproduce but this issue doesn't occur. 
It means I have something wrong with my database provider creation, sorry for that.
I will close this issue and trying to understand what happened.

Thanks 🍻
