### ISSUE TITLE
How to specify another field rather than primary key to decide insert or update when executing upsert method

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#1393]
I can see from the doc that upsert uses the primary key to check if a data exists or not.
![image](https://user-images.githubusercontent.com/1920873/127875292-3bbc6417-981d-408b-87ab-44dfb8b055c3.png)

My question:
How to specify which field is the one to decide it a row exists or not?

For example, let's say  we have this method as follows:

```dart
Future<int> upsertReviewPlan(ReviewPlansCompanion reviewPlansCompanion) {
    return into(reviewPlans).insertOnConflictUpdate(reviewPlansCompanion);
    // We hope we can specify another field to decide if reviewPlan row exists or not
    // such as name field, one of our biz logic just checks if the name field has the same value,
    // if it has the same name, we execute update operation, or we execute insert operation.
}	
```

**Comment by simolus3** [comment]
The documentation already points that out in the section below:

>Both `insertOnConflictUpdate` and `onConflict: DoUpdate` use an `DO UPDATE` upsert in sql. This requires us to provide a so-called "conflict target",  a set of columns to check for uniqueness violations. By default, moor will use the table's primary key as conflict target. That works in most cases, but if you have custom `UNIQUE` constraints on some columns, you'll need to use the `target` parameter on `DoUpdate` in Dart to include those columns.

So you can do

```dart
return into(reviewPlans).insert(reviewPlansCompanion, onConflict: DoUpdate((_) => reviewPlansCompanion, target: {reviewPlans.id}));
```

**Comment by jims57** [comment]
@simolus3 
What went wrong? Am I missing anything, thanks.
![image](https://user-images.githubusercontent.com/1920873/127947847-f6db3d29-d15a-413a-bae2-c68cc2ee6420.png)

![image](https://user-images.githubusercontent.com/1920873/127948032-ab522feb-d5cd-4d58-8d8e-b58076019909.png)

**Comment by simolus3** [comment]
Ah sorry, it should be `[storages.md5FileName]` instead of `{storages.md5FileName}`. The error in Dart is not caused by the older sqlite3 version, but you might get an exception at runtime. If you're using a `VmDatabase` and have a dependency on `sqlite3_flutter_libs`, everything should be fine.

**Comment by jims57** [comment]
> The documentation already points that out in the section below:
> 
> > Both `insertOnConflictUpdate` and `onConflict: DoUpdate` use an `DO UPDATE` upsert in sql. This requires us to provide a so-called "conflict target",  a set of columns to check for uniqueness violations. By default, moor will use the table's primary key as conflict target. That works in most cases, but if you have custom `UNIQUE` constraints on some columns, you'll need to use the `target` parameter on `DoUpdate` in Dart to include those columns.
> 
> So you can do
> 
> ```dart
> return into(reviewPlans).insert(reviewPlansCompanion, onConflict: DoUpdate((_) => reviewPlansCompanion, target: [reviewPlans.id]));
> ```

@simolus3 When I tried to write the code according to your suggestion, why this error occurred?

```dart
   var foldersCompanion = ....

    return await into(folders).insert(
      foldersCompanion,
      onConflict: DoUpdate((_) => foldersCompanion,
          target: [folders.tcbId]),
    );
```

I am sure the **tcbId** field has unique value, see:
![image](https://user-images.githubusercontent.com/1920873/129578978-36d24b18-a7fd-4222-b179-7f37c0cc7a88.png)


<details>
	  <summary>Click to show error detail</summary>
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: SqliteException(1): ON CONFLICT clause does not match any PRIMARY KEY or UNIQUE constraint, SQL logic error (code 1)
#0      throwException (package:sqlite3/src/impl/exception.dart:32:3)
#1      DatabaseImpl.prepare (package:sqlite3/src/impl/database.dart:178:7)
#2      _VmDelegate._runWithArgs (package:moor/src/ffi/vm_database.dart:162:24)
#3      _VmDelegate.runInsert (package:moor/src/ffi/vm_database.dart:175:11)
#4      _ExecutorWithQueryDelegate.runInsert.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:69:19)
#5      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
#6      _ExecutorWithQueryDelegate._synchronized (package:moor/src/runtime/executor/helpers/engines.dart:22:26)
#7      _ExecutorWithQueryDelegate.runInsert (package:moor/src/runtime/executor/helpers/engines.dart:67:12)
#8      LazyDatabase.runInsert (package:moor/src/utils/lazy_database.dart:60:17)
#9      InsertStatement.insert.<…>
</details>

**Comment by simolus3** [comment]
sqlite3 only supports conflict targets that actually form a conflict, so you'd probably have to add a `UNIQUE` constraint on `tcbId`. Sorry for not pointing this out earlier.
