### ISSUE TITLE
The getter 'year' isn't defined for the type 'GeneratedColumn<DateTime?>

### ISSUE THREAD

**Issue by Enhed** [simolus3/moor#1394]
table:

```dart
import 'package:moor/moor.dart';

enum LogModule {
  synchronization,
  system
}

class Logs extends Table {
  DateTimeColumn get timestamp => dateTime()();
  TextColumn get value => text()();
  BoolColumn get error => boolean().clientDefault(() => false)();
  IntColumn get module => intEnum<LogModule>()();

  @override
  Set<Column>? get primaryKey => { timestamp };
}
```

query (as documentation example):

```dart
db.select(db.logs)..where((u) => u.timestamp.year.isLessThan(1950));
```

has error: The getter 'year' isn't defined for the type 'GeneratedColumn<DateTime?>

how i can compare dates?

**Comment by simolus3** [comment]
I think this should work, which moor version are you using? `GeneratedColumn<DateTime?>` extends `Expression<DateTime?>` and we have an extension on that:

https://github.com/simolus3/moor/blob/a16b34c8d06c919dcd175a399c11b8c48da34bce/moor/lib/src/runtime/query_builder/expressions/datetimes.dart#L22-L24

Do you get an error message if you use `DateTimeExpressions(u.timestamp).year.isLessThan(1950)`?

**Comment by Enhed** [comment]
with DateTimeExpressions is working

**Comment by simolus3** [comment]
That's pretty weird - if the extension is applicable it should have recognized `year` as well. This looks like a problem with the analyzer or the compiler. I can't reproduce this and it doesn't appear to be a moor issue, so I think there's not much more I can do here.
