### ISSUE TITLE
How to work with foreign keys?

### ISSUE THREAD

**Issue by SocratesDz** [simolus3/moor#14]
How to indicate a foreign key in a Table object?

**Comment by simolus3** [comment]
Foreign constraints aren't supported by the library (yet). 
I'll try to implement custom table constraints for the next version, which should hopefully be ready in about one week. This would allow you to write something like:
```dart
// assuming that we have a "users" table with an id column 
class Friendships extends Table {
  IntColumn get userA => integer()();
  IntColumn get userB => integer()();
  @override
  Set<Column> get primaryKey => {todo, user};
  @override
  Set<String> get customConstraints => {
    'FOREIGN KEY(user_a) REFERENCES users(id)',
    'FOREIGN KEY(user_b) REFERENCES users(id)',
  };
}
```
The next version will also have joins, so you can load a list of friendships and their associated users like this:
```dart
var userA = alias(users, 'a');
var userB = alias(users, 'b');

// SELECT * FROM friendships
//   INNER JOIN users a ON a.id = friendships.user_a
//   INNER JOIN users b ON a.id = friendships.user_b;
var results = await select(friendships)
  .join([
    innerJoin(userA, userA.id.equalsExp(friendships.userA)),
    innerJoin(userB, userB.id.equalsExp(friendships.userB)),
  ]).get();

results.map((row) {
  var friendship = row.readTable(friendships);
  // load associated users
  var userA = row.readTable(userA);
  var userB = row.readTable(userB);
});
```

Would that suffice for your use-case?

**Comment by SocratesDz** [comment]
Yes, this looks good for my use-case. Also, will bulk insert be implemented in the next version?

**Comment by simolus3** [comment]
I have created #15 to track bulk inserts (they should be relatively easy to implement, I expect them to be available in the next version).

If it helps, I just learned that foreign keys with only one column can be expressed in the column definition, so declaring tables like this is possible with the current version of moor:
```dart
@DataClassName('TodoEntry')
class Todos extends Table {
  // ... other columns
  IntColumn get category => integer()
      .nullable()
      .customConstraint('NULLABLE REFERENCES categories(id)')();
}

@DataClassName('Category')
class Categories extends Table {
  IntColumn get id => integer().autoIncrement()();
  // ...
```
I'll still implement table constraints for the next version to support foreign keys on multiple columns.

**Comment by SocratesDz** [comment]
Thanks a lot, I'm looking forward to the next version. :smile:

**Comment by simolus3** [comment]
Just released `1.3` which let's you override the `customConstraints` getter in `Table` classes.

**Comment by 6heads** [comment]
Is this feature (foreign keys) already implemented? I can't find it anywhere in the documentation.

**Comment by simolus3** [comment]
Not yet, no. But you can achieve the same effect by overriding `customConstraints`, as discussed above. @6heads if you need a better integration of foreign keys please open an issue, this currently isn't a high priority for me as a decent workaround exists.

**Comment by JPiris88** [comment]
I can't make it work any way. I tried both overriding from the "Table" class and calling it on the property.

Overriding:

```c#
class Requests extends Table {
  IntColumn get requestId => integer()();
  IntColumn get requestTypeId => integer()();
  IntColumn get numberOfDocuments => integer()();

  @override
  Set<Column> get primaryKey => {requestId};
}

class RequestDocuments extends Table {
  IntColumn get requestId =>
      integer()();
  IntColumn get documentId => integer()();
  IntColumn get documentStateId => integer()();

  @override
  Set<Column> get primaryKey => {requestId, documentId};

  @override
  List<String> get customConstraints => [
        'FOREIGN KEY(request_id) REFERENCES requests(request_id)',
      ];
}
```

On the property:
```c#
class Requests extends Table {
  IntColumn get requestId => integer()();
  IntColumn get requestTypeId => integer()();
  IntColumn get numberOfDocuments => integer()();

  @override
  Set<Column> get primaryKey => {requestId};
}

class RequestDocuments extends Table {
  IntColumn get requestId =>
      integer().customConstraint('REFERENCES requests(request_id)')();
  IntColumn get documentId => integer()();
  IntColumn get documentStateId => integer()();

  @override
  Set<Column> get primaryKey => {requestId, documentId};
}
```

What I am doing wrong?

**Comment by Cedric921** [comment]
class User extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get username => text().named('username')();
  TextColumn get password => text().named('password')();
  TextColumn get names => text().named('names')();
  IntColumn get level => integer().named('level')();

  @override
  Set<Column> get primaryKey => {id};
}

class Entreprise extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text().named('name')();
  TextColumn get adress => text().named('adress')();
  TextColumn get businessType => text().named('businessType')();
  IntColumn get userId =>
      integer().customConstraint('REFERENCES user(id)')();
}

**Comment by cassioseffrin** [comment]
@Cedric921, is this the current way to deal with foreign keys in Drift?
 
```
IntColumn get userId =>
integer().customConstraint('REFERENCES user(id)')();
```

**Comment by simolus3** [comment]
@cassioseffrin No, we have had [dedicated support](https://drift.simonbinder.eu/dart_api/tables/#references) for foreign keys for a while :)
