### ISSUE TITLE
leftoutejoin issue

### ISSUE THREAD

**Issue by aidooyaw1992** [simolus3/moor#140]
left outer join doesnt seem to work in flutter channel stable

**Comment by simolus3** [comment]
Thank you for the report. We have some tests that use a `leftOuterJoin` and they all pass. Can you give me some additional information on what queries you run, what they return, and what you would expect them to return? That would help to diagnose this issue, thanks!

**Comment by minh98** [comment]
@aidooyaw1992

**Comment by aidooyaw1992** [comment]
Hi please, I think the error has been resolved. I was an error on my side
