### ISSUE TITLE
schema dump is not possible anymore

### ISSUE THREAD

**Issue by lyio** [simolus3/moor#1412]
**Describe the bug**

It is not possible to run `flutter pub run moor_generator schema dump` anymore. There seems to be a problem in the analyzer_plugin 0.7.0 causing this.

I get this error:
```
[...]/analyzer_plugin-0.7.0/lib/src/utilities/navigation/navigation.dart:31:29: Error: A value of type 'String?' can't be returned from a function with return type 'String' because 'String?' is nullable and 'String' isn't.
  String get path => result.path;
```

From what I can tell, the type has changed in the analyzer 2.0.0 and is now nullable.

Is there any way around this?

**Comment by simolus3** [comment]
Thanks for the report!

It looks like a newer `analyzer` version (that hasn't been released yet) will have non-nullable result paths (https://github.com/dart-lang/sdk/commit/672d66cea05306b48f34b4e9c2379f2a21993e2c). The `analyzer_plugin` from the SDK has been released _after_  the latest `analyzer` version on pub, so it is built against this unreleased API change. Great.

In 29453812133ff1f13e6dc1637addddf4bc641ebc, I removed imports to that package from the CLI entrypoint, which fixes the problem.

**Comment by lyio** [comment]
@simolus3 thank you for your effort, but the `analyzer_plugin` v0.7.0 is still being used by something internally and I still run into the issue.

I guess I just have to wait for the analyzer release.

**Comment by simolus3** [comment]
Huh, I had tried the `schema dump` command and it worked for me after those changes.

**Comment by kuhnroyal** [comment]
Not exactly sure but it seems a `2.14.0-307.0.dev+` Dart SDK is still required. (Flutter beta channel works).

**Comment by simolus3** [comment]
FWIW `analyzer: ^2.1.0` has been released, I imagine it should work with that version?

**Comment by kuhnroyal** [comment]
I assume so but can't upgrade yet. It works with 2.0.0 and the correct Dart/Flutter channel.

**Comment by jack24254029** [comment]
I can not use `drift_dev`
```
❯ dart run drift_dev 
Could not find a file named "pubspec.yaml" in "/Users/_user_name_/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-31.0.0".
#0      new Pubspec.load (package:pub/src/pubspec.dart:288:7)
#1      new Package.load (package:pub/src/package.dart:149:27)
#2      SystemCache.load (package:pub/src/system_cache.dart:113:20)
#3      Entrypoint._createPackageGraph (package:pub/src/entrypoint.dart:112:63)
#4      Entrypoint.packageGraph (package:pub/src/entrypoint.dart:107:54)
#5      getExecutableForCommand (package:pub/src/executable.dart:338:19)
#6      RunCommand.run (package:dartdev/src/commands/run.dart:232:32)
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:27)
#8      DartdevRunner.runCommand (package:dartdev/dartdev.dart:232:30)
#9      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:119:25)
#10     new Future.sync (dart:async/future.dart:296:31)
#11     CommandRunner.run (package:args/command_runner.dart:119:14)
#12     runDartdev (package:dartdev/dartdev.dart:67:29)
#13     main (file:///opt/s/w/ir/cache/builder/sdk/pkg/dartdev/bin/dartdev.dart:11:9)
#14     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:293:32)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```
