### ISSUE TITLE
Use Dart expressions in compiled sql queries

### ISSUE THREAD

**Issue by simolus3** [simolus3/moor#143]
As discussed in #142, we can have a convenient way inline moor's Dart api in compiled sql queries.

## Syntax (not settled yet)

We could introduce a `$<name>` syntax in sql queries to denote that a Dart expression is expected. So queries could look like `SELECT * FROM tbl WHERE $predicate` or `SELECT * FROM tbl WHERE a = $expr`. That syntax would parse to a new ast node inheriting from `Expression` (in the sqlparser package), so it neatly integrates with our existing type resolvers.

## Generated code
We can infer the type for these expressions using our existing resolver for variables. Then, we could generate methods with the following signature:
```dart
Selectable<Tbl> query1(Expression<bool, BoolType> predicate);
Selectable<Tbl> query2(Expression<String, StringType> expr);
```

If a type can't be inferred statically, we can generate a `Expression` parameter without type arguments.
## Restrictions
To make sure that we can still generate efficient and type-safe code, the expressions (which are bound at runtime), can't have any effect on what the query returns (which needs to be known at build time). This means that we have to disallow:

1. Expressions having an impact on column names returned by a `SELECT` query, e.g. when using `SELECT a = $expr FROM tbl`. When `a` is a column in `tbl`, we infer `expr` to have the same type, but the name of the column depends on what's used for `expr` at runtime. This would break our mapping code.
2. A column type of a select statement can't be inferred: `SELECT $expr AS e`. We can't generate a type-safe class to hold the result in that case. Maybe we can just make it have a `dynamic` field though?

### Open questions
A `Expression` in moor can contain an arbitrary amount of (not explicitly indexed) variables, which would be inserted into the query. We should evaluate if and how these might interfere with 
- variables defined in the query
- expanding array variables, which are also resolved at runtime

Another question is whether we should allow the same expression to appear multiple times: `SELECT * FROM tbl WHERE a = $expr OR b = $expr`. If we allow that, should we make variables appearing in that expression explicitly-indexed so that they only appear once?

**Comment by Mike278** [comment]
Another question is how ORDER BY expressions should be handled:

```sql
SELECT * FROM tbl 
ORDER BY $expr DESC
```
This `$expr` should only be allowed to define a single `OrderingTerm` with no `OrderingMode`.

```sql
SELECT * FROM tbl 
ORDER BY $expr
```
Whereas this `$expr` could allow multiple `OrderingTerm`s with their own `OrderingMode`s.

**Comment by simolus3** [comment]
Interesting point. In the first example, `$expr` is unambiguously an [expression](https://www.sqlite.org/syntax/ordering-term.html) as defined by sqlite, so I think the most reasonable way would be to expose it as an `Expression` in the generated method. In the second query, `$expr` could either be an expression, an ordering term or multiple ordering terms.

I wanted to focus on expressions in the initial version because they require little adaption from the parser. Later, we may extend the grammar to denote that a Dart component should be used as a `List<OrderingTerm>`:
```sql
SELECT * FROM tbl ORDER $orderingTerms; -- should generate List<OrderingTerm>
SELECT * FROM tbl ORDER BY $term; -- should generate Expression
```
Although I guess we can also support something like
```sql
SELECT * FROM tbl ORDER BY $term1, $term2, $expr DESC; -- OrderingTerm, OrderingTerm, Expression
SELECT * FROM tbl ORDER BY $term; -- List<OrderingTerm>
```
at a parser level if we make the precedence be `Expression < OrderingTerm < List<OrderingTerm>`. But in that case we'd have to support it from the very first version to avoid a breaking change later. I'll see how much more work that would actually be.

We also hit a similar issue with `LIMIT` clauses:
```sql
SELECT * FROM tbl LIMIT $lmt; -- Expression<int, ...> or LimitClause?
SELECT * FROM tbl LIMIT $a, $b; -- definitely two expressions here
```

**Comment by simolus3** [comment]
A first version of this is now on `develop`, I went for the `$name` syntax. In sqlite, `$name` is a variable declaration, but we don't support those variables and I don't think they're widely used. The `$` is annoying to use with queries defined in Dart, but I that should be ok since this feature is only necessary for dynamic queries in moor files.

We can generate parameters for expressions, single ordering terms, full order by clauses and limits, using the class that provides most flexibility in each use case. This feature should be compatible with both arrays and regular variables, but variables with an explicit index may not appear after a Dart template.

It doesn't contain the two checks that ensure expressions can't cause invalid code. Also, we would generate invalid code then the same template shows up multiple times (e.g. `WHERE x = $expr OR y  = $expr`). We should detect these cases and provide error messages for all of them.

**Comment by Mike278** [comment]
Wow that was fast! I've been playing around with it a bit and the dynamic ORDER BY is a really powerful feature... much cleaner than writing this and mapping from an enum!
```sql
ORDER BY
  CASE WHEN :order_ = 0 THEN updated_timestamp END DESC,
  CASE WHEN :order_ = 1 THEN last_name END ASC,
  CASE WHEN :order_ = 1 THEN first_name END ASC,
  CASE WHEN :order_ = 1 THEN updated_timestamp END DESC,
  id ASC
```

 I'm having some trouble getting WHERE expressions to work though. Here's my SQL (not sure if all of these should even be valid queries btw - especially `_testWhere3` vs `_testWhere4`):
```sql
create table tbl (col text);
_testWhere1: select * from tbl where $expr;
_testWhere2: select * from tbl where col = $expr;
_testWhere3: select * from tbl where col IN $expr;
_testWhere4: select * from tbl where col IN ($expr);
```

And the errors:
```
[WARNING] moor_generator:moor_generator on lib/src/database/db.dart:
Error while generating APIs for _testWhere1
Bad state: Unknown expression Instance of 'DartExpressionPlaceholder'
[WARNING] moor_generator:moor_generator on lib/src/database/db.dart:
Error while generating APIs for _testWhere2
Bad state: Unknown expression Instance of 'DartExpressionPlaceholder'
[WARNING] moor_generator:moor_generator on lib/src/database/db.dart:
Error while generating APIs for _testWhere3
Bad state: Unknown expression Instance of 'DartExpressionPlaceholder'
[WARNING] moor_generator:moor_generator on lib/src/database/db.dart:
Error while generating APIs for _testWhere4
Bad state: Unknown expression Instance of 'DartExpressionPlaceholder'
[INFO] Running build completed, took 216ms
```

**Comment by simolus3** [comment]
With c95a3badb252d03f77a9172fd63de3a451ed50db the generator will accept all 4 without complaining. It should reject the third query though, because expanding that into an expression doesn't yield valid sql (I don't think we should generate a `List<Expression>` in that case - it would be a lot of additional work and the same thing can be achieved with the first query). Rejecting that should probably happen in the parser.

**Comment by Mike278** [comment]
Yeah that makes sense to reject the third query. 

I'm having a new issue with the same sample queries - the generator is now working correctly, but the generated code has some errors:
```dart
Selectable<TblData> _testWhere1(Expression<bool, BoolType> expr) {
  final generatedexpr = $write(expr);
  $arrayStartIndex += generatedexpr.amountOfVariables;
  return customSelectQuery('select * from tbl where ${generatedexpr.sql}',
      variables: [...generatedexpr.introducedVariables],
      readsFrom: {tbl}).map(_rowToTblData);
}
```

The `Expression` class and `$arrayStartIndex` variable are both undefined

**Comment by simolus3** [comment]
Thanks for the report, it should work now. We report a syntax error for the third query, expose the `Expression` and `Limit` class from moor and make sure the `$arrayStartIndex` variable is present when it's needed.

We'll also print lints for the two problematic uses (query has a result column with an unknown type, name of the result column depends on a Dart template).
