### ISSUE TITLE
Selectable.get neither returning data nor throwing any exception - customSelect(rawSelectQuery)

### ISSUE THREAD

**Issue by KiraKmp** [simolus3/moor#1444]
Selectable? data = appDb.customSelect(queryString);
List list =await data.get();

when I try to get the list of QueryRow from selectable it breaks the code not throwing any exception.
It does not occur all the time though.

Note : I'm using MoorIsolate to estabish DB connection

**Comment by simolus3** [comment]
What do you mean by "breaks the code". Do you have a simple example that I could take a look at?

**Comment by KiraKmp** [comment]
I have a select function which takes a query and queries from DB using customSelect 

  Future<List<dynamic>> select(DBInputEntity dbInputEntity) async {
    String queryString = "SELECT * FROM ${dbInputEntity.entityName}";
    String whereClause = "";
    if (dbInputEntity.whereClause.length > 0) {
      whereClause = " WHERE ${dbInputEntity.whereClause}";
    }
    Selectable<QueryRow>? data;
    Database appDb = await DatabaseManager().getAppDB();
   
    try {
      data = appDb.customSelectQuery(queryString + whereClause);
    } catch (e) {
      Logger.logError("DatabaseManager", "replace", e.toString());
    }
    List<Map<String, dynamic>> result = [];

     if (data != null ) {
       try{
         List<QueryRow> list =await data.get();
         result = list.map((e) => e.data).toList();
       }catch(e){
         log(e.toString());
       }

    }
    return result;
  }

When this line **(List<QueryRow> list =await data.get();)** is reached it does not return anything, also not throwing exception

**Comment by KiraKmp** [comment]
The issue was due to transaction added for customSelect within isolate....Thanks
