### ISSUE TITLE
How to add multiple select in one query

### ISSUE THREAD

**Issue by heshaShawky** [simolus3/moor#1455]
I have 3 tables `wallets, transactions, categories` I have selected the `total` of transactions by `wallet` but `where` the `transaction` with a specific category and I got succeed doing this with the following code below.

What I need is to select another number in the same query, if I add another column it returns the same value as the first one!

So what the best way to achieve this, I tried to use customSelect but with no luck also.

```dart
Stream<double> watchWalletTransactionsBalanceByType({
    @required Wallet wallet,
    @required TransactionsTypes type,
    DateTime from,
    DateTime to
  }) {
    final totalTransactionsBalance = transactions.value.sum();
          
    if ( wallet == null ) {
      return Stream.value(0);
    }

    var query = (
      selectOnly(transactions)
      ..addColumns([totalTransactionsBalance])
      ..where(categories.type.equals(type.index))
      ..where(transactions.walletId.equals(wallet.id))
    );

    if ( from != null && to != null) {
      query = query..where(transactions.date.isBetweenValues(from, to));
    }


    Stream<double> val = query.join([
        leftOuterJoin(wallets, wallets.id.equalsExp(transactions.walletId)),
        leftOuterJoin(categories, categories.id.equalsExp(transactions.categoryId))
      ])
    .watchSingle()
    .map((event) => event.read(totalTransactionsBalance) ?? 0);


    return val;
  }
```

**Comment by simolus3** [comment]
> What I need is to select another number in the same query, if I add another column it returns the same value as the first one!

It looks like you're only selecting one column in the snippet you posted. Does it not work if you add another value in the `addColumns()` call?

**Comment by heshaShawky** [comment]
> > What I need is to select another number in the same query, if I add another column it returns the same value as the first one!
> 
> It looks like you're only selecting one column in the snippet you posted. Does it not work if you add another value in the `addColumns()` call?

if I add another column it gives the same value for both, every column has a different where condition, and I can't/don't know how to specify each column with its `where`.

so in the code below, I need to select all income/outcome transactions balances totals and that's required for me to add the correct condition for each column

`..where(categories.type.equals(0)) // here's my diffrent where I need 0 from income and 1 for outcome`

```dart
Stream<double> watchWalletTransactionsBalanceByType({
    @required Wallet wallet,
    @required TransactionsTypes type,
    DateTime from,
    DateTime to
  }) {
    final totalncome = transactions.value.sum();
    final totalOutcome = transactions.value.sum();
          
    if ( wallet == null ) {
      return Stream.value(0);
    }

    var query = (
      selectOnly(transactions)
      ..addColumns([totalncome, totalOutcome])
      ..where(categories.type.equals(0)) // here's my diffrent where I need 0 from income and 1 for outcome
      ..where(transactions.walletId.equals(wallet.id))
    );

    if ( from != null && to != null) {
      query = query..where(transactions.date.isBetweenValues(from, to));
    }


    Stream<double> val = query.join([
        leftOuterJoin(wallets, wallets.id.equalsExp(transactions.walletId)),
        leftOuterJoin(categories, categories.id.equalsExp(transactions.categoryId))
      ])
    .watchSingle()
    .map((event) => event.read(totalTransactionsBalance) ?? 0);


    return val;
  }

```

**Comment by simolus3** [comment]
I see, so the two columns need a different filter right?

This can be expressed in recent sqlite3 versions, but moor doesn't expose that syntax at the moment.

Of course, you can use dirty tricks:

```dart
// sum all transactions when the matching category is 0, otherwise use 0 as a summand (effectively ignoring it)
final totalIncome = categories.type.caseMatch(
  Constant(0): transactions.value,
  orElse: Constant(0)
).sum();
final totalOutcome = categories.type.caseMatch(
  Constant(1): transactions.value,
  orElse: Constant(0)
).sum();
```

I'll take a look at making aggregate filters available in moor.

**Comment by simolus3** [comment]
I've added support for filters in aggregate expressions (like `sum()`) in 9fffebbae6bd4b1db313a096e1fc8474812d8c13.

**Comment by heshaShawky** [comment]
> I've added support for filters in aggregate expressions (like `sum()`) in [9fffebb](https://github.com/simolus3/moor/commit/9fffebbae6bd4b1db313a096e1fc8474812d8c13).

I tried to git that version but not finding the new pram filter with all functions `total(), sun() ...etc`

```
  moor_flutter:
    git:
      url: https://github.com/simolus3/moor.git
      path: moor_flutter
      ref: 9fffebbae6bd4b1db313a096e1fc8474812d8c13
```

And that worked, thanks. 
```dart
Future<List<double>> watchWalletBalance({
    @required Wallet wallet
  }) async {

   final totalIncome = categories.type.caseMatch(
     when: {
       Constant(0): transactions.value
     },
     orElse: Constant(0)
   ).total();

   final totalOutcome = categories.type.caseMatch(
     when: {
       Constant(1): transactions.value
     },
     orElse: Constant(0)
   ).total();

   Future<List<double>> query = (
     selectOnly(transactions)
      ..addColumns([
        totalIncome,
        totalOutcome
      ])
      ..where(transactions.walletId.equals(wallet.id))
   )
    .join([
      leftOuterJoin(categories, categories.id.equalsExp(transactions.categoryId))
    ])
    .map((data) => [data.read(totalIncome), data.read(totalOutcome)])
    .getSingle();


    return query;
  }
```

**Comment by simolus3** [comment]
> I tried to git that version but not finding the new pram filter with all functions

It should be there (it got picked up by [dartdoc as well](https://61439a1009d01a08d3d2ca2b--moor.netlify.app/api/moor/arithmeticaggregates/sum)).

**Comment by heshaShawky** [comment]
> > I tried to git that version but not finding the new pram filter with all functions
> 
> It should be there (it got picked up by [dartdoc as well](https://61439a1009d01a08d3d2ca2b--moor.netlify.app/api/moor/arithmeticaggregates/sum)).


I don't know what the problem is but it's not!! still the functions with no prams!

I have another question and is related to this too instead of creating a new issue, I wanna make multiple  select in one query, I have the query in pure formate it will be something like this, how to formate it in data every select in an array by it self

```sql
SELECT * FROM transactions 
WHERE wallet_id = ? and categories.priority = ? 
INNER JOIN categories on categories.id = category_id
UNION ALL
SELECT * FROM transactions 
WHERE wallet_id = ? and categories.priority = ? 
INNER JOIN categories on categories.id = category_id
UNION ALL
SELECT * FROM transactions 
WHERE wallet_id = ? and categories.priority = ? 
INNER JOIN categories on categories.id = category_id
```

**Comment by simolus3** [comment]
>I don't know what the problem is but it's not!! still the functions with no prams!

Are we talking about the same function? There's a parameter [here](https://github.com/simolus3/moor/blob/9fffebbae6bd4b1db313a096e1fc8474812d8c13/moor/lib/src/runtime/query_builder/expressions/aggregate.dart#L83-L84). Maybe pub didn't grab the right git version of moor for some reason.

> how to formate it in data every select in an array by it self

I think at this point you'd just have to use `select` multiple times and merge the results in Dart, for instance by calling `get()` on all three select statements (to get three lists in Dart) and then returning the three lists.
