### ISSUE TITLE
Delete all tables in one shot

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#1456]
I have 20+ tables, when user press log out, is there a way I can delete all tables in one shot? 
Thanks

**Comment by tony123S** [comment]
I get Undefined name 'allTables' error

Repo

 `dao.deleteEverything();`
 
 Dao 
```
 Future<void> deleteEverything() async {
    await transaction(() async {
      // Deleting tables in reverse topological order to avoid foreign-key conflicts
      final tables = allTables.toList().reversed;

      for (final table in table) await delete(table).go();
    });
  }
```

**Comment by simolus3** [comment]
You need to call `allTables` on the database (use `attachedDatabase.allTables` if you're in a DAO)

**Comment by tony123S** [comment]
Thanks
