### ISSUE TITLE
batch.insertAll and onConflict: DoUpdate

### ISSUE THREAD

**Issue by shpasha** [simolus3/moor#1459]
I have a table

```
@DataClassName("DbSet")
class SetsTable extends Table {

  @override
  String get tableName => "sets";

  TextColumn get id => text()();

  TextColumn get title => text()();
  
  BoolColumn get isSelected => boolean()();

  @override
  Set<Column> get primaryKey => {id};
}
```

And i want to make batched update, but if the row exists i want to keep the previous **isSelected** value, something like this:

```
Future addSets(Iterable<DbSet> dbSets) {
    return batch((batch) => batch.insertAll<SetsTable, DbSet>(
        setsTable,
        dbSets
            .map((set) => SetsTableCompanion.insert(
                  id: set.id,
                  title: set.title,
                  isSelected: set.isSelected,
                ))
            .toList(),
        onConflict: DoUpdate((old) => SetsTableCompanion.custom(isSelected: old.isSelected)),
     ));
  }
```

But **old** is of type **SetsTable**, so i can't use previous value.

Am I doing something wrong? If not, please support this possibility.

```
  moor: ^4.5.0
  moor_generator: ^4.5.1

```

**Comment by simolus3** [comment]
> But old is of type SetsTable, so i can't use previous value.

Why not? `old.isSelected` should be assignable to `Expression<bool>`, which is what the `.custom` constructor wants for `isSelected`. What error message are you getting?

**Comment by shpasha** [comment]
@simolus3 , this error:

<img width="1206" alt="Screenshot 2021-09-20 at 20 31 38" src="https://user-images.githubusercontent.com/22001766/134047486-788af90d-9fc7-4185-a7cd-740839d93260.png">

**Comment by shpasha** [comment]
I found that columns generating with nullable generic type

```
late final GeneratedColumn<bool?> isSelected = GeneratedColumn<bool?>(
      'is_selected', aliasedName, false,
      typeName: 'INTEGER',
      requiredDuringInsert: true,
      defaultConstraints: 'CHECK (is_selected IN (0, 1))');
```

So if i cast my expression:
`onConflict: DoUpdate((old) => SetsTableCompanion.custom(isSelected: old.isSelected as GeneratedColumn<bool>)),`
then the compiler does not give errors

**Comment by shpasha** [comment]
So i found that this code works well:

```
onConflict: DoUpdate((old) => RawValuesInsertable({
              'is_selected': old.isSelected,
            })
```

I think TableCompanion.custom generates wrong, and generic type of that arguments should be nullable as in GeneratedColumn

**Comment by simolus3** [comment]
Yeah, the columns are generated as nullable because they could be nullable when coming from a left outer join. This is an unfortunate limitation.

Instead of casting with `as`, you could use `SetsTableCompanion.custom(isSelected: old.isSelected.dartCast())`.
