### ISSUE TITLE
More docs on expressions

### ISSUE THREAD

**Issue by mclark4386** [simolus3/moor#146]
Would it be possible to add a page or something to the docs about expressions and queries in general. I'm only seeing the rare bit of fairly specific docs on queries and I just had to dig through the source code to figure out how to do a `not` and a `isNotNull`... Moor is awesome!... just need a bit more in the docs department.

**Comment by simolus3** [comment]
I agree, the documentation could be better in that regard. Thanks for bringing it up!

**Comment by simolus3** [comment]
Does something like this help? https://develop--moor.netlify.com/docs/getting-started/expressions/

**Comment by mclark4386** [comment]
That's perfect! thank you!

**Comment by simolus3** [comment]
Great to hear! Those docs will be deployed to the main site with the next moor release.
