### ISSUE TITLE
Add "excluded" support for upsert

### ISSUE THREAD

**Issue by shpasha** [simolus3/moor#1460]
Continuing this ticket:
https://github.com/simolus3/moor/issues/1459#issuecomment-923131396

I found that using moor it is impossible to get data when executing a request.
For example, i have this function

```
return batch((batch) => batch.insertAll<SetsTable, DbSet>(
        setsTable,
        dbSets
            .map((set) => SetsTableCompanion.insert(
                id: set.id,
                title: set.title,
                difficulty: set.difficulty,
                isSelected: set.isSelected,
                wordsCount: Value(set.wordsCount),
                backgroundImageUrl: Value(set.backgroundImageUrl),
                color: set.color,
                isAddedByUser: set.isAddedByUser,
                language: set.language))
            .toList()
    ));
```

And i want some columns not to change and some to be replaced with new ones. 
But in DoUpdate
`onConflict: DoUpdate((old) => SetsTableCompanion.custom()` i dont have access to the conflicting row. 

SQLite makes it possible to get to the value that would be inserted, see "excluded": https://www.sqlite.org/lang_UPSERT.html

Going back to my example, for example, I want only the **title** field to be updated when a new data insert is requested. This is possible thanks to CustomExpression: 

```
return batch((batch) => batch.insertAll<SetsTable, DbSet>(
        setsTable,
        dbSets
            .map((set) => SetsTableCompanion.insert(
                id: set.id,
                title: set.title,
                difficulty: set.difficulty,
                isSelected: set.isSelected,
                wordsCount: Value(set.wordsCount),
                backgroundImageUrl: Value(set.backgroundImageUrl),
                color: set.color,
                isAddedByUser: set.isAddedByUser,
                language: set.language))
            .toList(),
        **onConflict: DoUpdate((old) => SetsTableCompanion.custom(title: CustomExpression("excluded.title")))));**
```

So, it will be great if you add "excluded" support to the library. Thanks!

**Comment by simolus3** [comment]
Thanks for opening this issue. I've added a `DoUpdate.withExcluded` API in 90e179643cadce3801fcb4425e4ebdc651d59da1.
