### ISSUE TITLE
Improve documentation on conditional imports for web

### ISSUE THREAD

**Issue by craiglabenz** [simolus3/moor#1466]
One of Moor's best features is its web compatibility, but sharing code across web and other platforms requires use of Dart's [conditional imports](https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files), which is not obvious from the [current section on sharing code](https://moor.simonbinder.eu/web/#sharing-code-between-native-apps-and-web).

I think this section of documentation would be nicely improved by adding some details about how to execute this pattern. I am happy to submit a PR that spells out the extra steps, but first I wanted to make sure that there aren't any relevant plans in the works to streamline how end developers interface with Moor's web bindings.

Thanks so much for this great package!

**Comment by simolus3** [comment]
Thanks for your helpful feedback! I read your first sentence and jumped right into expanding the documentation with 8c933ba2f29dadb769468afb22808741065631c5. Then I read on and saw that you offered to do the same, sorry :grin: . Of course, you are most welcome to add more details on this pattern if you want to.

>  wanted to make sure that there aren't any relevant plans in the works to streamline how end developers interface with Moor's web bindings.

There probably won't be, or at least nothing related to moor picking the right implementation by default. The core package can't use Flutter-specific platform mechanisms, and to me it feels like there are two many differences between files/IndexedDb to expose them under a single interface. If you have ideas on how this could be made easier for users though, I'd love to hear them.

**Comment by craiglabenz** [comment]
Great docs update - just saw one typo (`databas` -> `database`). Also, amazing turnaround time! 🎉

**Comment by simolus3** [comment]
Fixed, thanks for pointing out the typo.
