### ISSUE TITLE
This requires the 'non-nullable' language feature to be enabled

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#1468]
I want to upgrade to flutter 2. After run `dart migrate` , I get lot of errors.

```
error • Unexpected text 'late' at lib/data/db/xxx.g.dart:29765:3 • (unexpected_token)
  error • This requires the 'non-nullable' language feature to be enabled at lib/data/db/xxx.g.dart:29765:68 • (experiment_not_enabled)
  error • This requires the 'non-nullable' language feature to be enabled at lib/data/db/xxx.g.dart:29766:48 • (experiment_not_enabled)
 .......
  error • Unexpected text 'late' at lib/data/db/xxx.g.dart:29914:3 • (unexpected_token)
  error • This requires the 'non-nullable' language feature to be enabled at lib/data/network/xxx.chopper.dart:11:34 • (experiment_not_enabled)
  error • The name 'SingleChildCloneableWidget' isn't a type so it can't be used as a type argument at lib/di/global_providers.dart:9:6 • (non_type_as_type_argument)
  error • The name 'SingleChildCloneableWidget' isn't a type so it can't be used as a type argument at lib/di/global_providers.dart:14:6 • (non_type_as_type_argument)
  error • The name 'SingleChildCloneableWidget' isn't a type so it can't be used as a type argument at lib/di/global_providers.dart:22:6 • (non_type_as_type_argument)
  error • The named parameter 'title' isn't defined at lib/main.dart:26:41 • (undefined_named_parameter)

The migration tool didn't start, due to analysis errors.

We recommend fixing the analysis issues before running `dart migrate`.
Alternatively, you can run `dart migrate --ignore-errors`, but you might
get erroneous migration suggestions.

More information: https://dart.dev/go/null-safety-migration
```

**Comment by North101** [comment]
Delete `lib/data/db/xxx.g.dart` (this is a generated file so it's safe to delete as we'll just regenerate it later) then run `dart migrate` again.

After migrating (and updating moor to the latest version) run `flutter run build_runner build` to create `lib/data/db/xxx.g.dart`.

Any other errors from `dart migrate` don't look like moors fault.

**Comment by simolus3** [comment]
`--ignore-errors` may help, but in that case the suggestions might not be helpful around database code.

Essentially, it looks like you ran the build after adding `sdk: '>=2.12.0 <3.0.0'` to your pubspec, which lead to moor generating a `.g.dart` that is null-safe already. `dart migrate` does not expect null-safe files (obviously), so it complains about that. Can you restore the generated files to a version before you opted your app into null-safety? At this stage, you can run `dart migrate` but not apply the changes to the `.g.dart` files. Then at the very end (after code you wrote yourself has been migrated), you run another build.

**Comment by simolus3** [comment]
Ouch, in this case it actually looks like you'll have to re-generate with the latest dependencies, but with a `2.10.0` sdk environment. Is that possible?

Alternatively, you could temporarily use this dependency for the migration:

```yaml
dependencies:
  moor: '>=4.0.0 <4.4.0'
```

After everything is done you can upgrade to the latest moor. Sorry for that!

**Comment by tony123S** [comment]
```
[xxx] flutter pub get
Running "flutter pub get" in xxx...            
Because moor_generator >=4.4.0 depends on moor ^4.4.0 and xxx depends on moor >=4.0.0 <4.4.0, moor_generator >=4.4.0 is forbidden.
So, because xxx depends on moor_generator ^4.4.0, version solving failed.
pub get failed (1; So, because xxx depends on moor_generator ^4.4.0, version solving failed.)
exit code 1
```

This is the version I using

```
moor_generator: ^4.4.0
moor_flutter: ^4.0.0
moor: '>=4.0.0 <4.4.0'
```

**Comment by simolus3** [comment]
Right, does `moor_generator: '>=4.0.0 <4.4.0'` work?

**Comment by tony123S** [comment]
Now get another error by running `fvm flutter packages pub global run dart2_fix`.

```
error - lib/data/db/xxx.g.dart:14602 - Undefined class 'GeneratedTextColumn'
error - lib/data/db/xxx.g.dart:2741 - The method 'GeneratedTextColumn' isn't defined for the type '$CategoryOneTable'
error - lib/data/db/xxx.g.dart:17167 - Undefined class 'GeneratedTextColumn'
error - lib/data/db/xxx.g.dart:18553 - The method 'GeneratedTextColumn' isn't defined for the type '$LevelsTable'
error - lib/data/db/xxx.g.dart:6416 - Undefined class 'GeneratedIntColumn'
 ....
 error - lib/di/global_providers.dart:22 - The name 'SingleChildCloneableWidget' isn't a type so it can't be used as a type argument
error - lib/di/global_providers.dart:9 - The name 'SingleChildCloneableWidget' isn't a type so it can't be used as a type argument

Found 2817 analysis errors (in 15.7s).
pub finished with exit code 1
```

My pubspec

moor_flutter: ^4.0.0
moor: ^4.5.0
moor_generator: ^4.5.0

**Comment by simolus3** [comment]
Can you re-run the build after depending on the latest `moor` and `moor_generator`?

**Comment by tony123S** [comment]
I'm lost ..should I re-run the build using latest moor first before run dart migrate or after run dart migrate?

**Comment by simolus3** [comment]
Oh, I thought that you had already migrated your app.

To keep things simple, I'd first use the older moor versions and migrate your code with them. After that's done, it's just a matter of upgrading `moor` and running the build again.

**Comment by tony123S** [comment]
so I should use back version 3.1.0 , only upgrate to version 4 after migration done?

**Comment by tony123S** [comment]
This is the output

```
xxx@xxx-Inspiron-14-3467:~/Desktop/xxx$ fvm dart pub outdated --mode=null-safety
fvm: running Dart from Flutter "stable"

Showing dependencies that are currently not opted in to null-safety.
[✗] indicates versions without null safety support.
[✓] indicates versions opting in to null safety.

All your dependencies declare support for null-safety.
```

But after run dart migrate, I get 

```
error • '$ServiceSubTableTable.data' ('dynamic Function()') isn't a valid override of 'ServiceSubTable.data' ('Column<String> Function()') at lib/data/db/xxx.g.dart:22774:27 • (invalid_override)
  error • Undefined class 'GeneratedTextColumn' at lib/data/db/xxx.g.dart:22775:3 • (undefined_class)
  error • The method 'GeneratedTextColumn' isn't defined for the type '$ServiceSubTableTable' at lib/data/db/xxx.g.dart:22776:12 • (undefined_method)
  error • Undefined class 'GeneratedIntColumn' at lib/data/db/xxx.g.dart:22985:3 • (undefined_class)
  error • Undefined class 'GeneratedIntColumn' at lib/data/db/xxx.g.dart:22987:3 • (undefined_class)
  error • '$DefectDescriptionTableTable.id' ('dynamic Function()') isn't a valid override of 'DefectDescriptionTable.id' ('Column<int> Function()') at lib/data/db/xxx.g.dart:22987:26 • (invalid_override)
```

My pubspec

```
moor_flutter: ^4.0.0
moor: ^4.5.0
moor_generator: ^4.5.0
```

**Comment by simolus3** [comment]
Sorry, I should make this clearer.

The problem is that `moor` version `4.4.0` had some internal changes (the `GeneratedTextColumn` class has been replaced with a more general `GeneratedColumn` class). This means that, if you're using that or a later version, you also need to upgrade `moor_generator` and re-run the build to get proper generated files.

Applying the null-safety migration tool in a state where there are analysis errors will lead to unexpected results. So, before the mgiration, it's best to either

1. Temporarily downgrade moor to `>=4.0.0 <4.4.0` and continue to use the same generated code, or
2. Use the latest moor version `moor: ^4.5.0` and re-run the build

After you have done either of these things, you should be able to run `dart migrate`. After you have applied the migration, upgrade moor to the latest version and please run the build again.

**Comment by tony123S** [comment]
thanks, the first suggestion work :)
