### ISSUE TITLE
when uninstall the application, the database is not deleted, is it possible?

### ISSUE THREAD

**Issue by FetFrumos** [simolus3/moor#1470]
First, I want to thank you for this wonderful plugin.
second - I have a problem. so: I am developing an application using x and x. the structure of the database is changing, I do not use migrations yet. if the structure has changed, I ask the testers to remove the application and install again. but on one phone (samsung a20) an error occurred - it is due to the fact that the table does not exist in the database. but it should be created on a new installation. the tester says that he removed the old version of the application. I cannot verify this.

this is my constructor for the database in code:

` AppDatabase()
      : super((FlutterQueryExecutor.inDatabaseFolder(
          path: 'app.db',
          logStatements: true,
        )));`

 does it mean that when you uninstall the application, the database was not deleted? is it possible?
 
 if I didn’t change the schemaVersion, could this be the reason?

**Comment by simolus3** [comment]
Sometimes, Android likes to keep your app's data even when the app is uninstalled. A new installation would then re-use the files from a previous installation.

You could ask users to delete you app's data instead, that should definitely clear the database.

**Comment by kuhnroyal** [comment]
Probably due to auto backup since the file is in the applications directory. https://developer.android.com/guide/topics/data/autobackup
Try to exclude your database file from the backup as described in the link.

**Comment by Minhaj-hub** [comment]
@FetFrumos, I faced exactly the same problem. Can you tell me how you solved this issue and made the app work?

**Comment by siddharth-gitrepo** [comment]
There is an android feature that uses auto backup. It could be backing up the SQLite db. To disable this one can add the android:allowBackup="false" in the <application> tag in AndroidManifest.
```
<application
    ...
    android:allowBackup="false">
    ...
</application>
```
ref: https://stackoverflow.com/questions/77124293/database-is-not-deleted-after-i-uninstall-app-in-mobile-phone
