### ISSUE TITLE
Bad state: No element

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#1471]
Not getting useful log exception
```
try{
        print("testing");
        ABC? value = await _dao .checkIfImageUploaded(data.time);
        print(value);
   }catch(e){
      print(e.toString());
  }
```

**Error**
testing
Bad state: No element

**Comment by simolus3** [comment]
Well, can you print the stack trace as well?

```dart
   }catch(e, s){
      print(e.toString());
      print(s);
  }
```

Does this come from moor or from your app?

**Comment by tony123S** [comment]
Hye, I tried `catch(e,s)`, the stack trace is from my app.I have fixed it. Thanks a bunch !
