### ISSUE TITLE
where statement with onConflict update 

### ISSUE THREAD

**Issue by Ali1Ammar** [simolus3/moor#1472]
i would like to make a query like that
```sql
CREATE TABLE words(word TEXT PRIMARY KEY, occurrences INT);
INSERT INTO words(word,occurrences) VALUES('jovial',1)
  ON CONFLICT(word) DO UPDATE SET occurrences=occurrences+1 where occurrences <6
```
i could almost make it work with 
```dart
     await into(words).insert(
       WordsCompanion.insert(word: word, occurrences: 1),
       onConflict: DoUpdate((old) => WordsCompanion.custom(
         occurrences: old.occurrences + Constant(1),
       )),
     );
```
but i can't add a where statement to it `where occurrences <6`

i suggest to add new parameter to `DoUpdate` class that take a `Where` class or `Expression`
like this
```dart
 onConflict: DoUpdate((old) => WordsCompanion.custom(
         occurrences: old.occurrences + Constant(1),
       ) , where : (old)=>old.occurrences.isSmallerThanValue(5) )
```

i am happy to make a pull request if my approach ok or any other approach you see better

**Comment by simolus3** [comment]
Having a `where` parameter on `DoUpdate` sounds good to me. A pull request is much appreciated :)
