### ISSUE TITLE
DateTime query

### ISSUE THREAD

**Issue by RajanPalaniya** [simolus3/moor#152]
I want to watch over some records for current day's entry in DateTimeColumn. Currently i'm doing it like this. 

`Stream<List<Step>> get watchAllStepsData => (select(steps)..where((object) => object.endDate.equals(DateTime.now()))).watch();`

But i am not able fetch the records from DB.

can anyone please guide me through it?

**Comment by simolus3** [comment]
By using `DateTime.now()`, you would filter all steps that end at _exactly_ this time. If you need the records for today, maybe this can help:
```dart
final now = DateTime.now();
return (select(steps)..where((row) {
  final endDate = row.endDate;
  final sameYear = year(endDate).equals(now.year);
  final sameMonth = month(endDate).equals(now.month);
  final sameDay = day(endDate).equals(now.day);

  return and(sameYear, and(sameMonth, sameDay));
})).watch();
```

**Comment by RajanPalaniya** [comment]
Wow! That was fast and that worked. Much appreciated

**Comment by simolus3** [comment]
Always happy to help :)

**Comment by RajanPalaniya** [comment]
I have a one more question where currently i'm stuck at. i want to fetch records between 7 days and  12 months. how can i achieve this? i am trying to get that result from last 2 days. :(

**Comment by simolus3** [comment]
> i want to fetch records between 7 days and 12 months

Haven't tested this, but it should work
```dart
final now = DateTime.now();
final twelveMonthsAgo = DateTime(now.year - 1, now.month, now.day, now.hour, now.second);
final sevenDaysAgo = now.subtract(Duration(days: 7));

return (select(steps)..where((row) {
  final matchesLowerBound = row.startDate.isBiggerOrEqualValue(twelveMonthsAgo);
  final matchesHigherBound = row.endDate.isSmallerOrEqualValue(sevenDaysAgo);

  return and(matchesLowerBound, matchesHigherBound);
})).watch();
```
I'm not entirely sure if that causes problems when the same date doesn't exist in the previous year (e.g. if this year has a leap day then constructing a `DateTime` with `year - 1` might not yield the correct data). It looks like Dart just chooses the next date that fits in that case, but I couldn't find any quick documentation on that. There can be other problems with daylight saving offsets (see the documentation of `DateTime.subtract` for details).

I'll see if sqlite has some builtin functions to make this easier.

**Comment by jama5262** [comment]
Hi, I was trying to get single data by `id` from `now` to `7 days ago` ago but always getting null. Below is what I have tried. I am only using `timestamp` as my datetime

```dart
final now = DateTime.now();
final sevenDaysAgo = now.subtract(Duration(days: 7));

return (select(mTransactions)..where((row) {
   final matchesId = row.id.equals(id);
   final matchesLowerBound =
          row.timestamp.isBiggerOrEqualValue(sevenDaysAgo);
   final matchesHigherBound =
          row.timestamp.isSmallerOrEqualValue(now);

   return matchesId & matchesLowerBound & matchesHigherBound;
}))
.getSingle();
```

**Comment by simolus3** [comment]
Hm, that code looks alright to me. You can use `row.timestamp.isBetweenValues(sevenDaysAgo, now)` as a simplification, but that shouldn't change anything. Are you sure that there is a matching row?

**Comment by jama5262** [comment]
Hi again, I think I see a small bug here

When I do a simple insert (which works well), in the `timestamp` column, the data entered is in 13 digits like so `1579266900000`. Below is the class table

```dart
class MTransactions extends Table {

  @override
  String get tableName => 'transactions';

  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text()();
  TextColumn get body => text()();
  DateTimeColumn get timestamp => dateTime()();
}
```
But when I tried to query, the timestamp passed is in 10 digits like so `1522649479` but in the table what was inserted was in 13 digits. I think this is what makes it return null. Example is the logged select query using the following

```dart
final now = DateTime.now();
final sevenDaysAgo = now.subtract(Duration(days: 7));

return (select(mTransactions)..where((row) {
   final matchesId = row.id.equals(id);
   final matchesLowerBound =
          row.timestamp.isBiggerOrEqualValue(sevenDaysAgo);
   final matchesHigherBound =
          row.timestamp.isSmallerOrEqualValue(now);

   return matchesId & matchesLowerBound & matchesHigherBound;
}))
.getSingle();
```
What is logged out is this

```
Moor: Sent SELECT * FROM transactions WHERE id = ? AND timestamp >= ? AND timestamp <= ?; with args [28, 1522649479, 1585807879]
```
But when I tried it with the `customSelectQuery` it worked because I set the timestamp query to have 13 digits which are in milliseconds and it returned data. See below

```dart
return await customSelectQuery("""
      SELECT * FROM transactions WHERE id = '$id' AND timestamp >= '1579266900000' AND timestamp <= '1585749887000'
    """)
        .map((transaction) =>
            MTransaction.fromData(transaction.data, appDatabase))
.getSingle();
```
And this is the logged output
```
Moor: Sent  SELECT * FROM transactions WHERE id = '40' AND timestamp >= '1579266900000' AND timestamp <= '1585749887000'
```

So from what I have seen it that what is inserted is in milliseconds (that is in 13 digits) and when querying it is in seconds (that is in 10 digits)

**Comment by simolus3** [comment]
> When I do a simple insert (which works well), in the timestamp column, the data entered is in 13 digits like so 1579266900000. Below is the class table

This sounds wrong. We store date time values as unix timestamp (in seconds), as this is what most date functions in sqlite work with.

When inserting `DateTime` values, moor should encode them like that:
https://github.com/simolus3/moor/blob/e89f1c924c05b9f4cc5ff8efbed53c027691369a/moor/lib/src/runtime/types/sql_types.dart#L137

Are you doing anything special when writing the insert?
