### ISSUE TITLE
Improving documentation

### ISSUE THREAD

**Issue by lclrobert2020** [simolus3/moor#1521]
Dear Devs, 
  I am switching from RN to flutter and i found this amazing database that can help me to manage data across different isolate. But the documentation is really not easy for me to follow. I am playing with drift  and the starting guide, with the following code 
 ```
void main() {
  MyDatabase database = MyDatabase();
  getAllToDo(database);
  runApp(const MyApp());
}

void getAllToDo(MyDatabase database) async{
  addToDo(database);
  var x = await database.allTodoEntries;
  print("all todo entries run and now printing the result");
  print(x);
}

void addToDo(MyDatabase database) async{
 await database.addTodo( const TodosCompanion(
    title: Value('Important task'),
    content: Value('Refactor persistence code'),
  ),);
 print('add Done!');
}
```

and it shows error 
`Unhandled Exception: Null check operator used on a null value`

After a few hours, i found out that if i add 
`WidgetsFlutterBinding.ensureInitialized();`
in main (), the problem is gone. But I didn't see this called in the examples nor documentation

I would also want to know,
why some of the documentation use  `NativeDatabase.memory()` while the getting started page is using  `super(_openConnection());` which is `NativeDatabase(file)`, it will be nice if there is more instructions

```
class TodoDb extends _$TodoDb {
  TodoDb() : super(NativeDatabase.memory());

  // this is the new constructor
  TodoDb.connect(DatabaseConnection connection) : super.connect(connection);
}
```

**Comment by simolus3** [comment]
> After a few hours, i found out that if i add `WidgetsFlutterBinding.ensureInitialized();` in main (), the problem is gone

Sorry about that, the documentation should be clearer here. I have opened a PR to Flutter to hopefully improve the error message (https://github.com/flutter/flutter/pull/92758). I have also improved the documentation to mention this in 594b5f43c54cf03218099c895f2ada5ff12d0b09.

> I would also want to know, why some of the documentation use `NativeDatabase.memory()` while the getting started page is using `super(_openConnection());` which is `NativeDatabase(file)`

Parts of the documentation use `NativeDatabase.memory()` (a simple in-memory sql database without persistence), primarily as a placeholder for a real database database implementation that one might already use. I have added comments to explain this better in 23c912d6aaab413706021173f205d8fbfd744473.
