### ISSUE TITLE
mapFromRow.table.mapFromRow expects whole QueryRow

### ISSUE THREAD

**Issue by Rossdex** [simolus3/moor#1526]
I have been attempting to optimize my queries in my app with custom column queries rather than selecting all columns on a table.

However, I am using a custom function to map the output e.g. grouping companies by industry where the Frontend of my flutter app is expecting either a string of the industry name or a class (from moor). 

When I limit the columns in the query as below, mapFromRow throws an error because it is expecting the whole row to be there, is there an alternative function I can call within moor or do I just have to return the whole row every time? 

I am using custom DAO's and extending a base DAO so there is a lot of inheritance. 

I am using moor 4.6 and flutter 2.5.3.

Thanks for your time. 

```
StreamBuilder<List<dynamic>>(
        stream: database.companies.all(
          columnsArray: ['id', 'title', 'industry'],
          orderBy: 'industry ASC',
         mapFunction: database.companies.groupByIndustry,
 )
```

```  
Stream<List<dynamic>> all({columnsArray = const ['*'], orderBy = 'id DESC', Function? mapFunction}) {
    int userId = db.sharedPreferences.getInt('current_user_id');
    String columns = columnsArray.join(',');
    return customSelect(
      'SELECT $columns FROM ${_table.actualTableName} WHERE current_user_id = $userId ORDER BY $orderBy',
      readsFrom: {_table},
    ).watch().map((rows) {
      try {
        return mapFunction!(rows) ?? rows.map((row) => _table.mapFromRow(row)).toList();
      } catch (e, s) {
        print(e);
        print(s);
        return [];
      }
    });
  }
```

**Comment by simolus3** [comment]
A generated data class is designed to hold a full row, so using `mapFromRow` can't work with a partial result. I think it should work if you include all non-nullable columns, but that's still a bit hacky and I wouldn't recommend this approach.

So unfortunately, it looks like you'll have to write your own classes for partial results. If you know all combinations of columns before (that is, you're not creating `columnsArray` dynamically), you could also use [compiled custom queries](https://drift.simonbinder.eu/docs/using-sql/custom_queries/#statements-with-a-generated-api). If you do something like

```dart
@UseDao(
  ...,
  queries: {
    'basicCompanies': r'SELECT id, title, industry FROM companies WHERE current_user_id = ? ORDER BY $order'
  }
)
```

This would generate a `BasicCompaniesData` class and a `basicCompanies` function where you can chose the `order` parameter in Dart. You would have to repeat that for each combination of columns and tables, but at least you'll get matching data classes for those queries then.
