### ISSUE TITLE
Cannot debug Flutter on Android device, saying error: Could not determine the dependencies of task ':sqlite3_flutter_libs:compileDebugAidl

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#1529]
My code run well when debugging on iOS device, but when I tried to debug on Android device, show the following error.

<details>
	  <summary>Output on Console At Android Studio</summary>
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':sqlite3_flutter_libs:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':sqlite3_flutter_libs:debugCompileClasspath'.
   > Could not resolve eu.simonbinder:sqlite3-native-library:3.32.3.
     Required by:
         project :sqlite3_flutter_libs
      > Could not resolve eu.simonbinder:sqlite3-native-library:3.32.3.
         > Could not get resource 'https://google.bintray.com/exoplayer/eu/simonbinder/sqlite3-native-library/3.32.3/sqlite3-native-library-3.32.3.pom'.
            > Could not GET 'https://google.bintray.com/exoplayer/eu/simonbinder/sqlite3-native-library/3.32.3/sqlite3-native-library-3.32.3.pom'. Received status code 403 from server: Forbidden
      > Could not resolve eu.simonbinder:sqlite3-native-library:3.32.3.
         > Could not get resource 'https://dl.bintray.com/sbinder/sqlite3-native-library/eu/simonbinder/sqlite3-native-library/3.32.3/sqlite3-native-library-3.32.3.pom'.
            > Could not GET 'https://dl.bintray.com/sbinder/sqlite3-native-library/eu/simonbinder/sqlite3-native-library/3.32.3/sqlite3-native-library-3.32.3.pom'. Received status code 403 from server: Forbidden

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 7s
Exception: Gradle task assembleDebug failed with exit code 1

</details>

By the way, **pubspec.yaml** like this:
```yaml
dependencies:
  flutter:
    sdk: flutter
  moor: ^3.4.0
  moor_ffi: ^0.8.0
  provider: ^6.0.1
  path_provider: ^1.3.0
```

**Comment by simolus3** [comment]
Unfortunately it looks like you'll have to update your dependencies to continue building on Android. The reason is that Bintray was shutdown earlier this year, so the more recent versions of the sqlite3 native wrapper are published on Maven central. As Bintray is down, there unfortunately is no way to easily get the old versions.

Can you try adding the latest `sqlite3_flutter_libs: ^0.5.1` to your dependencies?

And you don't have to fix this right now, but you can simplify your moor dependencies a bit:

1. When you can, upgrade to `moor: ^4.6.0` and `moor_generator: ^4.6.0` and re-run the build. You can drop the dependency on `moor_ffi`  and instead import `package:moor/ffi.dart`.
2. Afterwards, you can run `flutter pub run moor_generator migrate` to migrate to the latest dependencies as described [here](https://drift.simonbinder.eu/name/).

(But that's not necessary now, adding the latest `sqlite3_flutter_libs` alone will most likely fix this build problem)

**Comment by jims57** [comment]
Thank you for your reply,

I have decided to upgrade **Flutter** to the latest version, that is **Flutter 2.5.3**, on **MacOS**.

But when I tried to debug even for iOS, it showed the following error.

<details>
	  <summary>Click to expand</summary>
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    ../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/ffi-0.1.3/lib/src/utf8.dart:63:33: Error: The getter 'addressOf' isn't defined for the class 'Utf8'.
     - 'Utf8' is from 'package:ffi/src/utf8.dart' ('../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/ffi-0.1.3/lib/src/utf8.dart').
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'addressOf'.
      String toString() => fromUtf8(addressOf);
                                    ^^^^^^^^^
    ../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/ffi-0.1.3/lib/src/utf16.dart:16:7: Error: Struct 'Utf16' is empty. Empty structs and unions are undefined behavior.
    class Utf16 extends Struct {
          ^
    ../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/ffi-0.1.3/lib/src/utf8.dart:23:7: Error: Struct 'Utf8' is empty. Empty structs and unions are undefined behavior.
    class Utf8 extends Struct {
          ^
    ../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/sqlite3-0.1.8/lib/src/ffi/sqlite3.ffi.dart:14:7: Error: Struct 'sqlite3_context' is empty. Empty structs and unions are undefined behavior.
    class sqlite3_context extends Struct {}
          ^
    ../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/sqlite3-0.1.8/lib/src/ffi/sqlite3.ffi.dart:12:7: Error: Struct 'sqlite3_value' is empty. Empty structs and unions are undefined behavior.
    class sqlite3_value extends Struct {}
          ^
    ../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/sqlite3-0.1.8/lib/src/ffi/sqlite3.ffi.dart:10:7: Error: Struct 'sqlite3_stmt' is empty. Empty structs and unions are undefined behavior.
    class sqlite3_stmt extends Struct {}
          ^
    ../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/sqlite3-0.1.8/lib/src/ffi/sqlite3.ffi.dart:8:7: Error: Struct 'sqlite3' is empty. Empty structs and unions are undefined behavior.
    class sqlite3 extends Struct {}
          ^
    ../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/sqlite3-0.1.8/lib/src/ffi/sqlite3.ffi.dart:6:7: Error: Struct 'char' is empty. Empty structs and unions are undefined behavior.
    class char extends Struct {}
          ^
    ../../../development/flutter/.pub-cache/hosted/pub.flutter-io.cn/ffi-0.1.3/lib/src/allocation.dart:47:33: Error: Expected type 'T' to be a valid and instantiated subtype of 'NativeType'.
      final int totalSize = count * sizeOf<T>();
                                    ^
    Failed to package /Users/mac/Documents/GitHub/seal_note.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
</details>

By the way, **pubspec.yaml** like this:
```yaml
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.12.2
  retry: ^3.0.1
  moor: ^3.4.0
  moor_ffi: ^0.8.0
  provider: ^6.0.1
  path_provider: ^1.3.0
  path: ^1.6.4
```

Can you tell me which version I should use after upgrading to **Flutter 2.5.3**, and I don't want this [issue](https://github.com/simolus3/moor/issues/1477) happening again after upgrading to the latest version of **Flutter**.

**Comment by simolus3** [comment]
Some of your dependencies are a bit old and might not work with the latest Dart or Flutter version. For instance, you're using `package:ffi` version 0.1.3 (the latest version is 1.1.2).

Can you try running `flutter pub oudated` and attempt to update some of your outdated dependencies?

**Comment by jims57** [comment]
I have upgraded **Flutter** to the latest version, **2.5.3**. And use the latest version of **drift** according to [this](https://drift.simonbinder.eu/docs/getting-started/#adding-the-dependency).

I found that **build_runner 2.1.4** depends on **crypto 3.0.0** rather than **crypto 2.1.3** which is required by another package called **cloudbase_core**.

**cloudbase_core** is a package of **Tencent Cloud**, the cloud service of **Tencent**, the biggest internet company in China. Since our biz has been using its cloud, we have no choice but keep using **cloudbase** now. 

The problem is that the team in **Tencent** working on **Flutter** package for **cloudbase** doesn't focus on **Flutter** very much, its upgrade is slow, I have contacted them to upgrade its package to support **crypto 3.0.0**, but they don't reply us now.

I wonder which version of **drift** and **build_runner** should I use so that no such version conflicting problem occurs, I mean which version of **drift** should I use to work well with the current version of **cloudbase_core** if **Tencent** team doesn't make any effort to upgrade its package to support **crypto 3.0.0**.

Thanks.

![image](https://user-images.githubusercontent.com/1920873/140448016-3893f2ce-6733-49e7-b776-fe27441955b6.png)

**Comment by simolus3** [comment]
> I wonder which version of drift and build_runner should I use so that no such version conflicting problem occurs

None will work, all drift versions require version 2 of the build system so they are not compatible with `crypto: 2.x`.

You can tell pub to ignore specific dependency conflicts with

```yaml
dependency_overrides:
  crypto: ^3.0.0
```

But maybe you could update the package in [their repo](https://github.com/TencentCloudBase/cloudbase-flutter-sdk)? Then you can use the custom version from git and open a PR for them to support the latest packages.
