### ISSUE TITLE
How can I use batch insert in Moor

### ISSUE THREAD

**Issue by eitguide** [simolus3/moor#153]

**Comment by simolus3** [comment]
You can use [`into(table).insertAll()`](https://pub.dev/documentation/moor/latest/moor_web/InsertStatement/insertAll.html). It works just like `insert`, but it takes a list instead of a single row that will be written.

**Comment by simolus3** [comment]
I'll close this issue for now. Please let me know if you need more information or have further questions, I'll then reopen this issue

**Comment by eitguide** [comment]
Thanks
