### ISSUE TITLE
Change List to Iterable where possible

### ISSUE THREAD

**Issue by nikitadol** [simolus3/moor#1530]
Methods that accept a `List` can actually accept an `Iterable`, since the list is immediately passed to for.
Since now these methods accept a `List` as an argument, I have to call `toList` everywhere, although this does not make sense, since the `List` is not used later, but memory is allocated for it.

Examples of methods (there may be other methods, but I use these more often, so I know about them):
https://github.com/simolus3/moor/blob/fcc60d70c4f33dbe33b989f2d6f35103d33456ef/drift/lib/src/runtime/api/batch.dart#L109-L114
https://github.com/simolus3/moor/blob/fcc60d70c4f33dbe33b989f2d6f35103d33456ef/drift/lib/src/runtime/api/batch.dart#L60-L66

**Comment by simolus3** [comment]
Good point! I had a quick look at all usages of `List` in `drift`, and it doesn't look like that many can easily be replaced with `Iterable`. The three `...All` methods in `Batch` certainly can, though. I have fixed this in 5f8b74c8df1450c1d585e0e124d15b9046f9dfa4. If I overlooked anything and there's another method that could be using an `Iterable`, please let me know!

**Comment by nikitadol** [comment]
Hi @simolus3

Is it possible to change the signature of the generated method that the `List` accepts?

From
```dart
Selectable<...> generatedMethod(List<...> var1)
```

to
```dart
Selectable<...> generatedMethod(Iterable<...> var1)
```

**Comment by simolus3** [comment]
I think this particular case doesn't provide lots of benefits. The parameter will be converted to a list internally either way, so IMO it's better to make that explicit. We're also calling `.length` to assign variable slots. As most iterables like the one returned by `.where` lazily count items in that call, there's a hidden cost here. So to be efficient and avoid iterating over it twice, we'd really have to call `.toList()` first in generated code. And then we may as well make the parameter a `List` too.

**Comment by nikitadol** [comment]
Can you change generation from
```dart
  Selectable<Result> inactive(
    List<Class1> var1,
    List<Class2> var2,
  ) {
    var $arrayStartIndex = 1;
    final expandedvar1 = $expandVar($arrayStartIndex, var1.length);
    $arrayStartIndex += var1.length;
    final expandedvar2 = $expandVar($arrayStartIndex, var2.length);
    $arrayStartIndex += var2.length;

    return customSelect(
      '...($expandedvar1) ... ($expandedvar2)',
      variables: [
        for (var $ in var1)
          Variable<int>(....$converter0.mapToSql($)!),
        for (var $ in var2)
          Variable<int>(....$converter1.mapToSql($)!),
      ],
      readsFrom: {
        ...,
      },
    );
  }
```

to
```dart
  Selectable<Row> inactive(
    Iterable<Class1> var1,
    Iterable<Class2> var2,
  ) {
    final variables = <Variable<dynamic>>[];
    var $arrayStartIndex = 1;
    final expandedvar1 = $expandVar<Class1>(
      var1,
      (item) {
        variables.add(Variable<int>(...$converter0.mapToSql(item)!));
        return $arrayStartIndex++;
      },
    );
    final expandedvar2 = $expandVar<Class2>(
      var2,
      (item) {
        variables.add(Variable<int>(...$converter1.mapToSql(item)!));
        return $arrayStartIndex++;
      },
    );

    return customSelect(
      '... ($expandedvar1) ... ($expandedvar2)',
      variables: variables,
      readsFrom: {
        ...,
      },
    )...
  }

  String $expandVar<T>(
      Iterable<T> items,
      int Function(T item) onItem,
      ) {
    final buffer = StringBuffer();

    if (items.isEmpty) {
      return '';
    }

    buffer.write('?${onItem(items.first)}');

    for (final item in items) {
      buffer.write(', ?${onItem(item)}');
    }

    return buffer.toString();
  }
```
?

**Comment by simolus3** [comment]
Yeah I guess something like this would enable iterables, but it that really worth it? We're still writing them into a list internally and array variables are almost always bounds to smallish lists so the memory overhead of calling `.toList()` before is minimal.

I fully agree that iteration-only methods like the one from `Batch` should take an iterable, but this feels different to me. Do you have places in your code where that would make things really inconvenient? I'm not fully sold on this.

**Comment by nikitadol** [comment]
@simolus3 

I mainly use this `fast_immutable_collections` package

But there are often cases when you need to map data before passing it to the generated methods
