### ISSUE TITLE
IndexedDB + Web Worker does not work in Safari

### ISSUE THREAD

**Issue by britannio** [simolus3/moor#1535]
**Describe the bug**

I'm using Drift with Flutter Web and it works in Safari when using the IndexedDB approach but not the IndexedDB + Web Worker approach.

I created a minimal example at https://github.com/britannio/drift_safari_repro

https://github.com/britannio/drift_safari_repro/commit/aeeb916cf2e6e0903907b0a7bf6ad94373a03388 breaks the app in Safari

I compiled `web/worker.dart` using `dart compile js web/worker.dart -o web/worker.dart.js`

**Comment by simolus3** [comment]
It looks like Safari has no support for shared workers 🤷 

You could use something like this to use shared workers only if they're available:

```dart
Future<MyDatabase> constructDb() async {
  if (context.hasProperty('SharedWorker')) {
    print('Using shared worker');
    final worker = SharedWorker('worker.dart.js');
    final connection = remote(worker.port!.channel());
    return MyDatabase.connect(connection);
  } else {
    print('Not using a shared worker (not supported by your browser)');
    return MyDatabase(
      WebDatabase.withStorage(await DriftWebStorage.indexedDbIfSupported('db')),
    );
  }
}
```

You could also use regular web workers, but the advantages of that are limited IMO. It might improve sqlite performance if that's a problem in your web app. The cool thing about shared workers is that drift's query streams transparently synchronize across tabs. That can't be emulated without a shared worker unfortunately.

**Comment by britannio** [comment]
> It looks like Safari has no support for shared workers 🤷
> 
> You could use something like this to use shared workers only if they're available:
> 
> ```dart
> Future<MyDatabase> constructDb() async {
>   if (context.hasProperty('SharedWorker')) {
>     print('Using shared worker');
>     final worker = SharedWorker('worker.dart.js');
>     final connection = remote(worker.port!.channel());
>     return MyDatabase.connect(connection);
>   } else {
>     print('Not using a shared worker (not supported by your browser)');
>     return MyDatabase(
>       WebDatabase.withStorage(await DriftWebStorage.indexedDbIfSupported('db')),
>     );
>   }
> }
> ```
> 
> You could also use regular web workers, but the advantages of that are limited IMO. It might improve sqlite performance if that's a problem in your web app. The cool thing about shared workers is that drift's query streams transparently synchronize across tabs. That can't be emulated without a shared worker unfortunately.

@simolus3 Thanks for the clarification! Where does `context` come from in this example?

**Comment by simolus3** [comment]
Sure! `context` is from `dart:js` in this case. We need `window` as a `JsObject` so that we can do `hasProperty`.
