### ISSUE TITLE
Some errors after upgrading to Drift from Moor, such as GeneratedIntColumn cannot be used

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#1536]
There are some errors which need me to fix before I can build the app after upgrading to **Drift** from **Moor**. Please help.

Note that my code run well before upgrading to **Drift**.

**Error 1:**
![image](https://user-images.githubusercontent.com/1920873/141079633-5894c90f-270a-44a7-988f-9751fbd2adf0.png)

**Error 2**(When executing command:  **flutter packages pub run build_runner build --delete-conflicting-outputs**)
![image](https://user-images.githubusercontent.com/1920873/141081346-6099142c-f55b-43f3-ae09-b41c17a877b7.png)

**Error 3:**
![image](https://user-images.githubusercontent.com/1920873/141081489-98b67b95-dff4-4045-a5a8-c108cfc570fe.png)

**Comment by simolus3** [comment]
Thanks for the report!

The `GeneratedXColumn` classes were internal and removed in a recent moor version. With drift you can just use `GeneratedColumn<int>` though.
Error 2 looks like a fault in generator, can you post some of the tables and queries to reproduce this?
Error 3 is likely the same as https://github.com/simolus3/moor/discussions/1534. You can fix it by adapting your `build.yaml` file.

**Comment by jims57** [comment]
@simolus3 Thanks.

Error 1, fixed.

Error 2, I am not sure what you were saying, please give me an example, thanks.

Error 3, failed, like this:
![image](https://user-images.githubusercontent.com/1920873/141124234-8ea7c3ee-8d50-4f40-acdd-df225d7be011.png)

**Comment by simolus3** [comment]
Did you re-run the build after adding the build config? Can you try running it with `--verbose` and see if anything stands out?

**Comment by jims57** [comment]
> Did you re-run the build after adding the build config? Can you try running it with `--verbose` and see if anything stands out? Does a `flutter pub run build_runner clean` help?

@simolus3 Thanks, 

The error 3 has been fixed after I run `flutter packages pub run build_runner build --delete-conflicting-outputs`.

But when I tried to run my code which was normal before I upgrading to **Drift** from **Moor**, it seem that it cannot access to the sqlite db, saying the following error.
<details>
	  <summary>Click to expand to see error</summary>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Bad state: Expected exactly one element, but got 0
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Bad state: Expected exactly one element, but got 0
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Bad state: Expected exactly one element, but got 0
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Bad state: Expected exactly one element, but got 0
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Bad state: Expected exactly one element, but got 0
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Bad state: Expected exactly one element, but got 0
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Bad state: Expected exactly one element, but got 0
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Bad state: No element
#0      List.single (dart:core-patch/growable_array.dart:342:22)
#1      Selectable.getSingle (package:drift/src/runtime/query_builder/statements/query.dart:220:26)
<asynchronous suspension>
#2      Database.getFolderNameById (package:seal_note/data/database/database.dart:891:31)
<asynchronous suspension>
#3      NoteListWidgetForTodayState._refreshNoteListPageCaptionAndHideSyncStatus (package:seal_note/ui/NoteListWidgetForToday.dart:1394:46)
<asynchronous suspension>
</details>

My code about Drift like this:
![image](https://user-images.githubusercontent.com/1920873/141167394-9859a1f8-e82b-40f6-b80c-a208346de0fb.png)

By the way, the **build.yaml** file like this, but it seem it doesn't support **targets** keyword, why?
![image](https://user-images.githubusercontent.com/1920873/141167915-722e0c18-a78a-4023-af0e-ec36296e2259.png)

**Comment by simolus3** [comment]
> Unhandled Exception: Bad state: Expected exactly one element, but got 0

What was the last moor version that you used, 3.x? In moor 4.0, the behavior of `watchSingle`/`getSingle` was changed to throw for empty result sets. In moor 3.x, `null` was returned. To account for null-safety, we now throw an exception and have the `watchSingleOrNull` and `getSingleOrNull` methods to restore the old behavior.

> By the way, the build.yaml file like this, but it seem it doesn't support targets keyword, why?

Are you using VS Code with the RedHat YAML extension? You might have selected a wrong schema for the `build.yaml` file? Personally I use

```json
    "yaml.schemas": {
        "https://json.schemastore.org/dart-build": [
            "build.yaml"
        ]
    },
```

**Comment by jims57** [comment]
> What was the last moor version that you used, 3.x?

I upgraded to **Drift** from **Moor v3.4.0**, is it the case which led to this probem? I mean, throwing for empty result sets if executing **getSingle()**.


> Are you using VS Code with the RedHat YAML extension? You might have selected a wrong schema for the `build.yaml` file? Personally I use

I am using **Android Studio**, not **VS Code**. In this case, I mean what to do and specify the scheme for **build.yaml** file in **Android Studio**?

**-------- The follwing part is my questions --------**

> Question 1：

I have tested but some of data from the server failed to insert into the Sqlite, which was normal before upgrading, by the way, I don't change the logic about this parts of code.
Please see the screenshot below, is it related to the **Error 2** I meantioned in this issue?
![image](https://user-images.githubusercontent.com/1920873/141211141-538f82f2-31b6-4595-9080-99e68146982b.png)
![image](https://user-images.githubusercontent.com/1920873/141212237-0c4f4fb2-ada0-4869-8164-3dc86905f195.png)


> Question 2:
Why does **Drift** still keep **getSingle**() method since there is such error(that is throwing for empty result sets if executing **getSingle()**)? I found that **Drift** can still invoke **getSingle()**.

**Comment by jims57** [comment]
@simolus3 Sorry for confusing you. The **Question 1** mentioned in the previous reply has been fixed. It was caused by the wrong data from the server, shouldn't blame **Drift** for it.

I can say all the errors mentioned in this issue have been fixed with your help except this following two, though it seems run well in my code, but I don't want to see these warning, which may lead to potential bugs, so I still need your guide, thanks.

### Problem a:
![image](https://user-images.githubusercontent.com/1920873/141233044-71f4be87-e200-4cd7-9fb9-0482f118190a.png)

### Problem b:

> I am using **Android Studio**, not **VS Code**. In this case, I mean what to do and specify the scheme for **build.yaml** file in **Android Studio**?

**Comment by simolus3** [comment]
I'm not sure about problem A, it sounds like a table isn't analyzed properly, if you have a simple project that reproduces it and that you can share, I can take a deeper look.

For problem B, you can select the schema in the top-right corner. It will say something like `Schema: <some default>` and you'll want to select `Dart build configuration`.

![grafik](https://user-images.githubusercontent.com/5738860/141489761-f9fa5ab0-d653-4f95-8b7c-b0d05466e960.png)

**Comment by jims57** [comment]
Thanks, as to `Problem a`, it seems normal now, after I deleted `database.g.dart` and run `flutter clean` again. But I am definitely certain it is fixed by that way. Anyway, it's normal now, for you can ignore `Problem a` now.

**Comment by Satendra9984** [comment]
[SEVERE] drift_dev:drift_dev on lib/modals/task.dart (cached):

InconsistentAnalysisException: Requested result might be inconsistent with previously ret
urned results

[SEVERE] drift_dev:drift_dev on lib/custom_widget/tasks_list.dart (cached):

InconsistentAnalysisException: Requested result might be inconsistent with previously ret
urned results

[SEVERE] Failed after 11.5s
pub finished with exit code 1


I am getting this error by using Drift after Moor

**Comment by simolus3** [comment]
@Satendra9984 I'm afraid this is probably an issue in the build system (https://github.com/dart-lang/build/issues/3271) that you're now hitting because of the new analyzer version that the old moor packages couldn't resolve to.

I've opened https://github.com/simolus3/drift/issues/1770 to track this. That issue also describes a possible workaround for this problem.
