### ISSUE TITLE
Should I go on using the moor file with moor extension after upgrading to Drift from Moor

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#1538]
I don't change the extension name(**.moor**), after upgrading to **Drift** from **Moor**. 
It works well currently, I wonder if I don't change the extension name, what will potential risks or bugs occur in the future?

Please give me suggestion about how to modify this part so that our code can abide by the conventional rules **Drift** users should follows.

![image](https://user-images.githubusercontent.com/1920873/141229920-f2000a11-7b02-4aa5-9610-983eb6439e6a.png)

**Comment by simolus3** [comment]
It's pretty trivial for the generator to keep supporting `.moor` files, so I don't think that you _need_ to migrate to `.drift` right away. For consistency, it can make sense to rename them though. And obviously I recommend new projects to use `.drift`. This is also explained in the [documentation](https://drift.simonbinder.eu/name/#optional-rename-moor-files).

By the way, you can use `flutter pub run drift_dev migrate` to rename the files and patch imports. But please commit pending changes before you do that, the command will override files without asking for confirmation.
