### ISSUE TITLE
Why does't Drift reference the right table name when there is another table with _temp as suffix

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#1540]
In order for better understand what I am talking about,  please see [this](https://github.com/simolus3/moor/issues/1536#issuecomment-965961166) for your reference.

![image](https://user-images.githubusercontent.com/1920873/141451196-8be629e3-82db-44bb-afdd-fb82208e4c01.png)

Parts of code related in `database.dart` is as follows:
```dart
mixin SyncRelatedFieldsMixin on Table {
  IntColumn get rowId => integer().named('rowId')();

  TextColumn get operationId => text().named('operationId')();

  IntColumn get actionId => integer().named('actionId')();

  // 16 bit milliseconds timestamp
  // example: 1617942350682
  IntColumn get timestamp => integer().named('timestamp')();
}

@DataClassName('StorageEntry')
class Storages extends Table {
  @override
  String get tableName => 'storages';

  IntColumn get id => integer().autoIncrement()();

  TextColumn get md5FileName => text().named('md5FileName')();

  TextColumn get ext => text().nullable().named('ext')();

  BoolColumn get isSavedAtTCBStorage => boolean()
      .withDefault(const Constant(false))
      .named('isSavedAtTCBStorage')();

  TextColumn get tcbId => text().nullable().named('tcbId')();

  TextColumn get downSyncOperationId =>
      text().nullable().named('downSyncOperationId')();
}

@DataClassName('StorageTempEntry')
class StoragesTemp extends Storages with SyncRelatedFieldsMixin {}

@DriftDatabase(include: {
  'tableTriggers/storagesTriggers.moor',
}, tables: [
  Storages,
  StoragesTemp,
])
class Database extends _$Database {
  // omitted code
}
```

**Comment by simolus3** [comment]
Can you enable `logStatements: true`? It looks like the insert is targeting the correct table, so it's not obvious to me what's happening here.

**Comment by North101** [comment]
I haven't tried inheritance with tables but I notice that `Storages` overrides `tableName` but `StoragesTemp` doesn't. So it might not be creating the table for `StoragesTemp`

**Comment by jims57** [comment]
@North101 @simolus3 

![image](https://user-images.githubusercontent.com/1920873/141746390-9e4ef5e6-6434-4c1b-b420-b02d43a24b56.png)

**Comment by jims57** [comment]
@simolus3 Thanks, this can be closed.
