### ISSUE TITLE
The plugin `sqlite3_flutter_libs` requires your app to be migrated to the Android embedding v2

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#1548]
Please help thanks.

![image](https://user-images.githubusercontent.com/1920873/141891738-aacd5b89-5aef-440b-aa50-b7f8ae73095f.png)

My Flutter is in `master` channel:
```
Flutter 2.6.0-12.0.pre.719 • channel master • https://mirrors.tuna.tsinghua.edu.cn/git/flutter-sdk.git
Framework • revision 34dbee66de (24 hours ago) • 2021-11-14 18:46:02 -0500
Engine • revision 140bd9399e
Tools • Dart 2.16.0 (build 2.16.0-10.0.dev) • DevTools 2.8.0
```

**Comment by simolus3** [comment]
Well, the solution is to migrate your app to the new Android embedding as described in that link. I'm not sure if there's a way for us to support both the old and the new embedding as a native plugin.

**Comment by jims57** [comment]
I fixed this just by change it to {appplicationName}
![image](https://user-images.githubusercontent.com/1920873/141957158-e8d81da9-aac1-4e88-935d-c6b88cb4cb8a.png)
