### ISSUE TITLE
Override == and hashCode for query result data classes

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#155]
Currently if you have a query like:

```sql
create table tbl (col1 text, col2 int, col3 int);
customDataClass: SELECT col1, col2 FROM tbl;
```

the data class that's generated for this projection looks like:
```dart
class CustomDataClassResult {
  final String col1;
  final int col2;
  CustomDataClassResult({
    this.col1,
    this.col2,
  });
}
```

Would it be possible to generate a `==` and `hashCode` override for these classes like is done with the full table data class?

**Comment by simolus3** [comment]
This doesn't sound like much work for the generator, so I think we can also override these methods in result set classes. However, I'm not sure if there are a lot of people needing these methods, so I would probably make this a configurable opt-in feature.

**Comment by Mike278** [comment]
Making them opt-in is fair. My main use case is using Stream's `distinct()` method in DAOs to prevent uncessary widget rebuilds, since stream updates work at a table-level. I'm currently supplying an equality function to `distinct()` as a workaround.

```sql
create table user (
  user_id int, 
  first_name text, 
  last_name text
);

getUserFullName: 
SELECT first_name, last_name FROM user WHERE user_id = :user_id;

getUser: 
SELECT * FROM user WHERE user_id = :user_id;

insertUser: 
INSERT INTO user VALUES (NULL, :first, :last);
```

```dart
final user = db.getUser(222).watch().distinct();
final userName = db.getUserFullName(222).watch().distinct();

await db.insertUser('John', 'Smith'); 
// The `user` stream will not emit a value but the `userName` stream will.
```

**Comment by simolus3** [comment]
I just added the `override_hash_and_equals_in_result_sets` builder option. It's documented [here](https://develop--moor.netlify.com/docs/advanced-features/builder_options/)

**Comment by Mike278** [comment]
Wow that was superspeed, thank you so much! You’ve been pumping out so many features lately
