### ISSUE TITLE
Tables with same data class name result in duplicated generated classes

### ISSUE THREAD

**Issue by reinhardbluelab** [simolus3/moor#1562]
We have 2 tables that need to share the same row class. Specifying the same name with @DataClassName causes the code generation to produce 2 data classes (and companions) with the same names, causing obvious compiler errors. I would expect only one class to be generated if the data class names are the same. Should I rather be using the @UseRowClass annotation and writing the data class myself? This seems unnecessary if the generated class is fine - we just don't want the error-causing duplicate generation.

**Comment by simolus3** [comment]
I tried implementing this, but one problem is that data classes are table-specific in ways beyond generated columns. For instance, data classes extend `Insertable<T>`, where `T` is specific to the table defining the data class. A data class couldn't extend both `Insertable<T1>`  and `Insertable<T2>`.

Of course this could be solved by looking at the inheritance chain and making the data class implement a common supertype of `T1` and `T2` if needed (see also https://github.com/simolus3/moor/issues/1134#issuecomment-888247617), but it's a lot of added complexity in the generator. So given that sharing data classes between tables is (I assume) a rarely used feature, IMHO it's not worth this complexity. I think your best bet would indeed be to write custom data classes if you need to share data classes between tables.
