### ISSUE TITLE
Deferred Foreign Keys cause transactions to silently fail & lock

### ISSUE THREAD

**Issue by micimize** [simolus3/moor#1589]
`DEFERRABLE INITIALLY DEFERRED` foreign key failures cause silent `db.transaction` errors that then lock the DB. The same does not happen for an unwrapped insert statement.

I believe this is caused by the failure only occurring at `COMMIT` time, probably in the `finally` block of transaction:
https://github.com/simolus3/moor/blob/7c828f8d977a3b7986ff4263943acf244e2bd42f/drift/lib/src/runtime/api/connection_user.dart#L435-L441

When the failure occurs:
1. The error is not logged in the example, but I see it in my main project. This is perhaps due to the usage of the catcher package.
1. The record appears to be inserted as normal (Maybe due to a watcher notification inside the transaction).
1. Subsequent reads will hang forever.
1. Subsequent writes will fail complaining the DB is locked.

Minimal reproduction: https://github.com/micimize/moor/commit/e9ce950191efcd81ed24b5e39f45b48f12068e0e
Runnable branch: https://github.com/micimize/moor/tree/deferred_fk_transaction

**Comment by simolus3** [comment]
Thanks for opening the issue and for providing the repro. This was really helpful! I've fixed the problem with 41825e058ec0be7122396e179d6bd0b28d2a87d3.

**Comment by micimize** [comment]
Thanks for the rapid response! Tested in my main project and it seems to address the issue 👍

**Comment by simolus3** [comment]
Awesome, that's great to hear! I'm investigating another bug and I hope to bundle up the fixes and release it to pub in the next days.
