### ISSUE TITLE
Documentation issue: Examples | https://github.com/rodydavis/drift_shared 404

### ISSUE THREAD

**Issue by kankadev** [simolus3/moor#1597]
Hi,

in your "Examples" page there is a link to a non-existing GitHub-Repository.

"(...) including Web and Desktop! You can check it out here. (...)" The link in "here" is https://github.com/rodydavis/drift_shared but this is a 404 page now.

**Comment by frankvollebregt** [comment]
Looks like this got confused with the Moor --> Drift conversion, the actual repository is at
https://github.com/rodydavis/moor_shared

**Comment by simolus3** [comment]
Thanks for the report! I've fixed this in 2ecc44c593e6f6e250b8c1fb9bc4a5a7176de4c1, the site should update shortly.
