### ISSUE TITLE
Error message when trying to read blob from database

### ISSUE THREAD

**Issue by yanivshaked** [simolus3/moor#1600]
While trying to read a blob field from a database which was previously created, getting the following error message:

```
I/flutter (19432): type 'String' is not a subtype of type 'Uint8List?' in type cast, Stack: #0      BlobType.mapFromDatabaseResponse (package:drift/src/runtime/types/sql_types.dart:171:21)
```

Looking at `sql_types.dart`, the following code looks suspicious:
```
  @override
  Uint8List? mapFromDatabaseResponse(dynamic response) {
    return response as Uint8List?;
  }
```
This is not the correct way to convert a String to Uint8List. The above code should be:
```
  @override
  Uint8List? mapFromDatabaseResponse(dynamic response) {
    var list = response.codeUnits;
    return Uint8List.fromList(list);
  }
```

I will test the above and submit a PR if it works.

**Comment by simolus3** [comment]
Can you share a bit more details on how to reproduce this? The `response` should really be a `Uint8List` already. If it's not, that looks like a bug in the database implementation.

**Comment by yanivshaked** [comment]
Sure. I'm using `DB Browser for SQLite` to create a database. Following is the table creation command:
```
CREATE TABLE "Cocktails" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Description"	TEXT,
	"Test1"	BLOB,
	"Test2"	BLOB,
	"Test3"	BLOB,
	"Test4"	BLOB,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
```
Error message is received for BLOB fields (All other fields are read correctly without any issue).
Please see my suggestion for a more robust approach in the PR #1601 .
