### ISSUE TITLE
update and delete method of DatabaseAccessor should be renamed

### ISSUE THREAD

**Issue by topperspal** [simolus3/moor#1604]
**Look at this:-**

```
abstract class UsersRepository {
  Future<bool> save(User user);
  Future<bool> delete(User user);
  Future<int> update(User user);
  Future<User> profile();
}
```

```
class UsersDriftRepository extends DatabaseAccessor<AppDatabase> implements UsersRepository {
  UsersDriftRepository(db) : super(db);

  @override
  Future profile() {
    ...
  }

  @override
  Future<bool> save(user) {
    ...
  }

  @override
  Future update(User user) {
    ...
  }

  @override
  Future delete(User user) {
    ...
  }
}
```

Now in `UsersDriftRepository`, I can not use `delete(table)` and `update(table)` methods of `DatabaseAccessor`. **YES** I can, if I simply change the methods names in `UsersRepository` as `updateUser(...)` and `deleteUser(...)` then everything is ok. But I want to make them   concise and same in all repositories, like 

```
abstract class TodosRepository {
  save();
  delete();
  update();
}

abstract class CategoriesRepository {
  save();
  delete();
  update();
}

..... etc.
```

So I request you to change the methods names in `DatabaseAccessor` from `update(table), delete(table)` to something more meaningful and suitable like `updateFrom(table), deleteFrom(table)` or `updateInto(table), deleteInto(table)`

ThankU:)

**Comment by simolus3** [comment]
Renaming those methods is quite a breaking change and I don't think your point is strong enough to justify this.

If you want to keep the names in your repository as is, you could also write wrappers instead:

```dart
class UsersDao extends DatabaseAccessor<AppDatabase> {

}

class UsersDriftRepository implements UsersRepository {
  final UsersDao dao;

  // implement by delegating to dao
}
```

**Comment by topperspal** [comment]
Yes, I am currently using two different class, one for dao and another for
Repository but that is boilerplate, create one entire class just for naming
conflict.

Second, the most important, I, like other people, like to use drift for
sqlite database. This is really a great package and solves a lot of
problems for me. But please think it twice. Breaking changes can be
refactored ( you already did good job while renaming the package ). Names
of the methods must be meaningful.

For example, what arguments you think this method will take?

delete(...)

And if this method is name something like this

deleteFrom(...)

Anyone can easily tell that this method will take either a Table or a
Collection.
Concise means make a word smaller but meaningful.

Have a look at these examples also

selectFrom(usersTable).get()
deleteFrom(usersTable).delete(user)

OR

select(userstable).insert(user);
select(userstable).update(user);
select(userstable).delete(user);

I know breaking changes are painful but right action must be taken as soon
as possible. On first side where drift is rescuing us from boilerplate
using code generation and on the other hand you are asking me to create
boilerplate. This is not nice.

Please consider it correctly because it is getting popular rapidly, once a
dev use it, he fall in love with it.

Again think about it.

select(userstable).insert(user);
select(userstable).update(user);
select(userstable).delete(user);

It will also help us to generate some code on top of drift generation

ThankU:)
