### ISSUE TITLE
group_concat is incorrectly declared as String, instead of String?

### ISSUE THREAD

**Issue by igbenic** [simolus3/moor#1606]
First of all, thank you for a great library!

- what you were trying to do
I'm using this select on @DriftDatabase(queries) :

```SQL
select
    first_table.name as some_name,
    first_table.id as some_id,
    group_concat(second_table.name) as names
from first_table
    left join second_table on second_table.some_id = first_table.id
group by first_table.id
```

 - what you would have expected to happen
I expected to get a table of some_name, some_id, names even with ```null``` names

 - what actually happened
I'm getting null for all data, not even an empty list, if I don't wrap group_concat in IFNULL: 
```SQL
IFNULL(group_concat(second_table.name), '') as names
```

The first SQL is working correctly outside of drift:
some_name | some_id | names
-- | -- | -- |
qwer | 1 | A,B
asdf | 2 | NULL
zxcv | 3 | NULL

**Comment by simolus3** [comment]
Thanks, fixed in bdf0dc998597c7ef0477b6c57385c4c0173f20a1.
