### ISSUE TITLE
Remove log 

### ISSUE THREAD

**Issue by cahyofendhi** [simolus3/moor#161]
How to remove log inside `moor` library, like event on insert data, are there method to disable that

**Comment by simolus3** [comment]
Do you set `logStatements: true` on the `FlutterQueryExecutor`? Moor shouldn't log anything if that option is off.

**Comment by cahyofendhi** [comment]
oh okay i see, thanks

**Comment by amreniouinnovent** [comment]
@simolus3 Where is `logStatements` in the new implementation ?
```
LazyDatabase _openConnection() {
  return LazyDatabase(
    () async {
      final Directory dbFolder = await getApplicationDocumentsDirectory();
      final File file = File(path.join(dbFolder.path, 'db.sqlite'));
      return VmDatabase(file);
    },
  );

```

**Comment by kuhnroyal** [comment]
@amreniouinnovent `VmDatabase(file, logStatements: true)`

**Comment by amreniouinnovent** [comment]
@kuhnroyal Thanks, It looks like autocomplete has an issue
