### ISSUE TITLE
Cascade delete

### ISSUE THREAD

**Issue by jaczura1977** [simolus3/moor#1610]
Hi!
I don't know if it is an SQLite or drift issue, but deleting parent entities leave the child entities undeleted with invalid data of foreign key (Id that not exists in parent entity as Id.)

CREATE TABLE IF NOT EXISTS todo (id TEXT NOT NULL, PRIMARY KEY (id));
CREATE TABLE IF NOT EXISTS todoElement (id TEXT NOT NULL, todoId TEXT NOT NULL REFERENCES todo (id), PRIMARY KEY (id));

**Comment by kuhnroyal** [comment]
You probably need to enable foreign keys.

**Comment by simolus3** [comment]
Yes, foreign keys aren't enabled by default. My suggestion is to add a `beforeOpen` callback to your migration and enable foreign keys there:

```dart
  MigrationStrategy get migration => MigrationStrategy(
    beforeOpen: (details) async {
      await customStatement('PRAGMA foreign_keys = ON');
    },
  );
```

**Comment by Mike278** [comment]
Enabling foreign keys will prevent the database from getting into an inconsistent state, but your schema is configured to throw an error when attempting to delete the parent. If you instead want to cascade delete children on parent deletion, you need to configure that explicitly - see https://www.sqlite.org/foreignkeys.html#fk_actions
