### ISSUE TITLE
type exception while using custom companions with enum field

### ISSUE THREAD

**Issue by raminsafaei** [simolus3/moor#1614]
i have a table with intEnum column(has a default value and is not nullable) and there are no problems reading/writing using other insertables. but when i try to use custom companion(entity.custom) with expressions and variables i get exceptions in runtime that the argument is not valid.
same query works if i leave enum field null(so it uses default value) or using other forms of insertable as mentioned above but i need to use a subquery for a certain field and have to use this.
some code for context:
```dart
class TodoEntries extends Table {
  TextColumn get id => text()();
  TextColumn get title => text()();
  IntColumn get priority =>
      intEnum<Priority>().withDefault(const Constant(0))();
}
```
i have not included subquery here cause it doesnt seem to affect the issue. i convert companion to custom one below(not sure if theres a better way)
```dart
TodoEntriesCompanion.custom(
      id: drift.Variable(id.value),
      title: drift.Variable(title.value),
      priority: priority.present ? drift.Variable(priority.value) : null,
    );
```
error: Invalid argument (params[4]): Allowed parameters must either be null or an int, num, String or List<int>.: Instance of 'Priority'
```
PreparedStatementImpl.execute
package:sqlite3/…/impl/statement.dart:32
_VmDelegate._runWithArgs
package:drift/…/ffi/database.dart:206
_VmDelegate.runInsert
package:drift/…/ffi/database.dart:218
```

**Comment by simolus3** [comment]
Yeah, type converters aren't applied to `Variable`s, those write their values directly. Really, the `priority` parameter should be an `Variable<int>` instead, type converters don't really make sense here as `.custom` is designed to transform SQL expressions that aren't necessarily coming from Dart. [I'm aware of the problem](https://github.com/simolus3/moor/blob/6efe6de3bacd4a81a45a7b64691c1a72be7b170b/drift_dev/lib/src/writer/tables/update_companion_writer.dart#L125), but it requires a breaking change to fix.

As an alternative, you could do `drift.Variable(todoEntries.priority.converter.mapToSql(priority.value)).dartCast()`. I see how that's annoying to write, but for `.custom` that's probably the best solution. Although from your snippet I don't understand why you have to be using `.custom`? What's the problem with using the regular constructor for companions?
