### ISSUE TITLE
Documentation issue: Drift files

### ISSUE THREAD

**Issue by albazel2004** [simolus3/moor#1617]
You've done a great work with Drift package, but I've noticed that there is one error in the documentation of Drift files as shown below:

CREATE TABLE saved_routes (
  id INTEGER NOT NULL PRIMARY KEY,
  name TEXT NOT NULL,
  "from" INTEGER NOT NULL REFERENCES coordinates (id),
  **to** INTEGER NOT NULL REFERENCES coordinates (id)
);

the constraints   **to** INTEGER NOT NULL REFERENCES coordinates (id) should've been written with like this:
  "to" INTEGER NOT NULL REFERENCES coordinates (id), because to is a reserved keyword in SQLITE

**Comment by simolus3** [comment]
Thanks! Fixed in 573bd20eb8f5e33a40ddcdc3b9ebbe91cbcfcd37.
