### ISSUE TITLE
Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)

### ISSUE THREAD

**Issue by prajwal27** [simolus3/moor#1618]
**Describe the bug**

I face this issue after updating the moor package to the latest version 4.6.1+1 . I see similar issue solve here https://github.com/simolus3/moor/issues/1593 , but it's related to drift package. 

Prior to 4.6.1+1, we were using 4.2.0 and it was working fine. So, is there anything that changed in 4.6.1+1 that is related to isolates ?

**Comment by simolus3** [comment]
If you're using `moor`, you're actually using `drift` internally as the implementation has been moved. Even if you don't want to migrate to `drift`, you can add `drift: ^1.1.1` to your pubspec to fix this problem.
