### ISSUE TITLE
Isolate configuration doesn't call close on the database

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#1629]
Hello SImon, I recently enabled WAL mode with an isolate setup and I noticed that after shutting down the isolate, the extra files "-shm" and "-wal" from SQLite are not deleted, which they should when all the connections to the database get closed (Section 4 in https://sqlite.org/wal.html)

In fact, if I remove the isolate implementation, they do get removed. Maybe the following method in the server implementation should include `await connection.executor.close()`

```dart
@override
  Future<void> shutdown() {
    if (!_isShuttingDown) {
      _done.complete();
      _isShuttingDown = true;
    }

    return done;
  }
```

Thanks for such a great library!

**Comment by simolus3** [comment]
Ouch, good point! I've added the missing close call now.
