### ISSUE TITLE
How does flutter use drift in multiple flutter engines?

### ISSUE THREAD

**Issue by ddxl123** [simolus3/moor#1643]

**Comment by simolus3** [comment]
Can you please describe your question in a bit more detail?

Dart code runs isolated across different Flutter engines. Using the same sqlite3 database across Flutter engines is fine, but you won't get cooperating query streams for updates made on another engine. You can use a `DriftIsolate` across Flutter engines though, in that case the same database connection is shared across Flutter engines.

**Comment by ddxl123** [comment]
> 

How to use DriftIsolate across Flutter engines?
How do other engines connect to the main DriftIsolate?
Does every Flutter engine have to write:
```
   final DriftIsolate isolate = await DriftIsolate.spawn(_backgroundConnection);
   final DatabaseConnection connection = await isolate.connect();
   final MyDatabase db = MyDatabase.connect(connection); 
```

**Comment by simolus3** [comment]
If you can exchange `SendPort`s and `ReceivePort`s across engines, then you can also use that to share `DriftIsolate`s across Flutter engines.

>  How do other engines connect to the main DriftIsolate?

If you have a `ReceivePort` where the main isolate is listening is on, you can obtain the corresponding `SendPort` to send to other engines. How you send those ports depends on how you spawn those engines natively and is not a concern for drift.

>  Does every Flutter engine have to write？:

No, in that case every engine would have its own `DriftIsolate` and those wouldn't share query streams among each other.

**Comment by ddxl123** [comment]
It seems that SendPortsh and ReceivePorts cannot be exchanged between flutter engines.
So can I create an instance of the database in each flutter engine?
What would be the impact of doing so?

**Comment by ddxl123** [comment]
> If you can exchange `SendPort`s and `ReceivePort`s across engines, then you can also use that to share `DriftIsolate`s across Flutter engines.
> 
> > How do other engines connect to the main DriftIsolate?
> 
> If you have a `ReceivePort` where the main isolate is listening is on, you can obtain the corresponding `SendPort` to send to other engines. How you send those ports depends on how you spawn those engines natively and is not a concern for drift.
> 
> > Does every Flutter engine have to write？:
> 
> No, in that case every engine would have its own `DriftIsolate` and those wouldn't share query streams among each other.

It seems that SendPortsh and ReceivePorts cannot be exchanged between flutter engines.
So can I create an instance of the database in each flutter engine?
What would be the impact of doing so?

**Comment by ddxl123** [comment]
@simolus3 
It seems that SendPortsh and ReceivePorts cannot be exchanged between flutter engines.
So can I create an instance of the database in each flutter engine?
What would be the impact of doing so?

**Comment by simolus3** [comment]
>  If there are 10 flutter engines, 10 database instances need to be created, how will this affect my application?

Not by much, opening sqlite3 databases is pretty cheap. The only downside is that you don't get real-time query updates, which is a Drift feature. If you don't need that across engines in your app, using one database per engine is the easiest solution by far.
