### ISSUE TITLE
Failed to create sqlite file

### ISSUE THREAD

**Issue by yaoing** [simolus3/moor#1645]
hello, I am trying to copy a flutter project with drift code to another computer with  same operation system (win 11). But there is a bug when database is called: 
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: LateInitializationError: Field 'versionDelegate' has not been initialized.
#0      _VmDelegate.versionDelegate (package:drift/src/ffi/database.dart)
#1      DelegatedDatabase._runMigrations (package:drift/src/runtime/executor/helpers/engines.dart:309:38)
#2      DelegatedDatabase.ensureOpen.<anonymous closure> (package:drift/src/runtime/executor/helpers/engines.dart:303:13)
<asynchronous suspension>
...
```
And I find that the sqlite file was not been created when `_openConnection` method is called. I have try to re-generate the db code and clean the build cache, but not working at all.

**Comment by simolus3** [comment]
There should be another exception when opening the database, can you find that somewhere? If the sqlite file was supposed to go into a subdirectory, was the parent folder created?

**Comment by yaoing** [comment]
There has no error tip when the StreamBuilder widget call for a watch operation at application running, but wrong when execute the insert funtion. In fact, I am using the initial code in official example: 
```
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(join(dbFolder.path, 'db.sqlite'));
    return NativeDatabase(file);
  });
}
```

It should be noted that I am building a windows desktop application, and the parent folder, which point to the windows document dir, have been created.

**Comment by simolus3** [comment]
The first exception should be thrown with the first actual access to the database (as drift will open the database lazily). Either way, I think I need a simple but complete repro to check out, otherwise there's no way for me to see where the error is coming from.

**Comment by cwangfr** [comment]
I have same problem, but i changed sqlite3.dll from 32bit to 64bit, The problem doesn't appear anymore. 
I hope this helps you

**Comment by DevHachi** [comment]
I have exact this error, but on Android. Does anyone now a solution how to solve this. 
It seems to happen as soon as it try to run the migration.

Here is the exception that I get, when running in debug mode. 
`Invalid argument(s): Failed to load dynamic library '/data/data/<package-name>/lib/libsqlite3.so': dlopen failed: lib`

drift version: 1.5.0
sqlite3: 1.5.1

**Comment by simolus3** [comment]
@DevHachi Can you post the Android device / version on which this happens? Are you already aware of the ideas shared [here](https://github.com/simolus3/sqlite3.dart/tree/main/sqlite3_flutter_libs#problems-on-android-6)?

**Comment by DevHachi** [comment]
@simolus3 yeah I found this [solution](https://github.com/simolus3/drift/issues/895) that seem to work now. 

thx for the fast response. :)
