### ISSUE TITLE
Default values set in object definitions are not found in newly created object companion

### ISSUE THREAD

**Issue by SergioB** [simolus3/moor#1646]
When defining: 

class Item extends Table {
  TextColumn get title => text().withDefault(const Constant('a'))();
}

Then instantiating ItemCompanion:

var itemCompanion = ItemCompanion();

the value of **itemCompanion.title** is **Value.absent()**, while expected value is the default value of **'a'** set in definition.

**Comment by simolus3** [comment]
This behavior is expected, SQL defaults are part of the database schema and not reflected in Dart classes. The main reason for this is that defaults in SQL aren't necessarily valid defaults in Dart too (just think about things like `CURRENT_TIMESTAMP` which can't be a Dart constant).

After you insert the companion, you can select the row (or just use `insertReturning`) to get the value of the default in the database.

**Comment by SergioB** [comment]
But it will make the developer multiple times set those values, which makes the code prone to errors.

May be it will be better to add a separate function like **sqlDefaults** for those times when defaults will not be compatible with Dart?
