### ISSUE TITLE
[Documentation] Update links for Drift inspector

### ISSUE THREAD

**Issue by frankvollebregt** [simolus3/moor#1657]
I was inspecting my Drift database from Android Studio, when I ran into the issue that there's no scroll bar in the table list. I proceeded to make an issue there, after which I was informed that the `drift_inspector` package is retiring soon in favor of a new, more advanced package.

https://github.com/Chimerapps/drift_inspector/issues/15

I think the Community tab should probably be updated at some point to show this new version (and maybe also replace `moor` with `drift` in the headers.

https://drift.simonbinder.eu/docs/community_tools/#moor-inspector

As an aside, on the github homepage of this repository, the link is still moor.simonbinder.eu instead of drift (it forwards you correctly but still you might want to change that).

**Comment by simolus3** [comment]
Thanks for the pointers! I have added a note on the new `storage_inspector` package in 3f165c2df7ff97bead612aea9ad26cb809194f1d. I'll keep mentioning the other packages for now since it looks like the new package doesn't support drift yet. 

I have also changed the link in the repository and the anchor names.

**Comment by NicolaVerbeeck** [comment]
@simolus3 The new package does support drift ;) It is a pluggable package and there is a drift plugin right here: https://pub.dev/packages/drift_local_storage_inspector

**Comment by simolus3** [comment]
Oh cool, I haven't seen that package! I've updated the docs in 64fde620f47c5e1d6ad21429d64fff9221c183af :)
