### ISSUE TITLE
Cached QueryStream with multiple listeners emits stale data

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#166]
```dart
    // in .moor file: create table tbl (col1 text, col2 int, col3 int);

    Stream<List<TblData>> all = db.select(db.tbl).watch();
    all.listen(print); // Comment out this line to make test pass

    await db.into(db.tbl).insert(TblData(col1: 'test'));
    List<TblData> data = await db.select(db.tbl).watch().first;
    expect(data.length, 1);
    expect(data.first.col1, 'test');
```

**Comment by simolus3** [comment]
Thanks for the report. The situation should be better on `develop` now, we delete cached data from the stream when the table updates. It's a bit tricky to get right, as the future returned by the `insert` statement could complete before the streams were updated.

I made the `QueryStream` always skip a microtask before checking for cached data and emitting it. (Previously we'd check for cached data right away and then emit it a microtask later).

**Comment by simolus3** [comment]
I guess the caching transformer can still subscribe to the underlying stream in the same microtask (b0d69f346f0aa7c11a3fc8a2ffc82d767de719f5) but only emit the cached data one microtask later, so the old behavior isn't changed.
