### ISSUE TITLE
Catching Exception

### ISSUE THREAD

**Issue by rddewan** [simolus3/moor#1670]
**Is your feature request related to a problem? Please describe.**
Can we have some sort of exception handling 

**Describe the solution you'd like**
I am using with try catch but the exception is never get caught

**Comment by kuhnroyal** [comment]
Since your queries are asynchronous, try/catch doesn't work. You need to add error handlers to the stream or future. But that is not really related to drift, that's how asynchronous execution works in most languages.

**Comment by simolus3** [comment]
Yeah, drift should report errors, either by completing a future with an error or by emitting an error through a query stream. If you post your current error handling strategy, we can help you find the issue. Of course, if you're handling asynchronous errors and drift _doesn't_ report them, then that's definitely a bug in drift.
