### ISSUE TITLE
Order of arguments in drift queries

### ISSUE THREAD

**Issue by adg-mh** [simolus3/moor#1672]
Not sure if it is intended behavior... Are the order of the arguments after the query name supposed to be used?

For example I wrote something along the lines of:

```
updateExample(:rowId AS INT, :someText AS TEXT):
    UPDATE Test
    SET some_data = :someText
    WHERE row_id = :rowId;
```

But the signature generated was:

`Future<int> updateExample(String? someText, int rowId)`

(where the order of appearance in the actual query seems to be used)

Thanks.

**Comment by simolus3** [comment]
> Are the order of the arguments after the query name supposed to be used?

At the moment, it's not. The arguments after the query name are only used to specify the types. It is perfectly valid to use additional variables in the query, or to not use all variables declared as typed parameters (even though that would probably not be too useful). So we can't reliably use that order and keep using the order of variables in the SQL statement.

(Changing that now would also be pretty breaking)

**Comment by adg-mh** [comment]
Ah yeah, that's right... I ended up using `named_parameters` in the build options which is arguably clearer anyways...

Thanks for the quick reply.
