### ISSUE TITLE
drift

### ISSUE THREAD

**Issue by bePagani** [simolus3/moor#1688]
how to make one to many relation ship?? and encode it to json???

**Comment by simolus3** [comment]
You can define one-to-many relationships just like you would define them with SQL too: Reference the "one" table from a column in the "many" table. To query those relationships, use joins. There's no builtin way to encode join results to json, but you can encode the two tables and combine the results into a new map.

**Comment by bePagani** [comment]
please can you write in docs how to make relationship like one to one one
ot many?
because in docs field "relationship" is not understandable

**Comment by bePagani** [comment]
dear friend*
