### ISSUE TITLE
Support for inheritence in table definitions?

### ISSUE THREAD

**Issue by thetrav** [simolus3/moor#169]
This is probably an odd-ball request, but here goes.

I have a case where I have numerous tables which contain a super set of fields derived from another table's fields (it's like a copy with some additions, typically requires a lot of outer joins)

Currently I'm just repeating the definition of the fields in both ParentTable and ChildTable

My instinct was to write something like:
```
class ParentEntities extends Table {
//column definitions and custom primary key
}
class ChildEntities extends ParentEntities {
//only additional column definitions
}
```
In this case the child table wants to use the same custom primary key as the parent.

The generator barfs at this, and I don't really blame it, however it would be nice if it recognized column definitions from parent classes.  Note that I don't want ChildTable to use the data from ParentTable... I actually want mostly duplicate data in different tables for this case

**Comment by simolus3** [comment]
This sounds like a reasonable request to me. I think this should already work for primary keys, but we only scan the class definition itself for columns. We can probably just expand that for superclasses as well.

**Comment by simolus3** [comment]
There's a working version the develop branch, but it'll probably take some time until the next release is ready. This is the test case I'm using, is that similar to what you had in mind?
https://github.com/simolus3/moor/blob/0b9d4c897b25d6e3c91b26a0d714daff9fe12949/moor_generator/test/analyzer/dart/table_parser_test.dart#L47-L57

**Comment by thetrav** [comment]
I guess so, though that test case shows inheriting a column definition from the mixin and overriding one from its abstract parent.

I was thinking more:
```
class Socks extends Table {
  TextColumn get name => text()();
  IntColumn get id => integer().autoIncrement()();
}

class ArchivedSocks extends Socks {
  TextColumn get archivedBy => text()();
  DateTimeColumn get archivedOn => dateTime()();
}
```

Then ArchivedSocks has all 4 columns

**Comment by simolus3** [comment]
Thanks for the feedback, I added your example as another test case in commit ff7d587339044dbf57148424c269d4cee43dd0e5.

I actually really like this feature, it makes some common patterns much more fluent to write. So thanks for the idea! :+1:
