### ISSUE TITLE
How can I perform an upsert without breaking foreign key relationship with CASCADE onDelete action?

### ISSUE THREAD

**Issue by mateoKutnjak** [simolus3/moor#1692]
When insert mode is InsertOrReplace, it increments ID of the database row and thus breaking foreign key relation. Can an entry be saved in database without deleting old one and inserting new one? Only columns with different values must be updated.

**Comment by simolus3** [comment]
Yes! It sounds like you want an `UPSERT`, which is supported in recent sqlite3 version and drift. You can use [`insertOnConflictUpdate`](https://drift.simonbinder.eu/api/drift/insertstatement/insertonconflictupdate) to replace existing rows without changing the rowid.
