### ISSUE TITLE
DoUpdate.withExcluded "old" and "excluded" are of type Object?. and have to be cast different type to be used. Which type is that?

### ISSUE THREAD

**Issue by mateoKutnjak** [simolus3/moor#1699]

**Comment by mateoKutnjak** [comment]
Types must be set at insertAll. ```await batch((batch) => batch.insertAll<TableName, EntityName>(..., onConflict: DoUpdate.withExcluded((old, excluded) { ... }))```

**Comment by ariefwijaya** [comment]
@mateoKutnjak So, what type is that?

**Comment by simolus3** [comment]
That depends on the table on which you're doing the insert.

**Comment by ariefwijaya** [comment]
@simolus3  But why doesn't show in Visual Code IDE automatically as autocomplete and just show `Object`, do we need to cast it manually?

**Comment by simolus3** [comment]
Because `insertAll` needs two type parameters that depend on each other, and type inference does not always work for that.
