### ISSUE TITLE
CRLF in .moor file causes Malformed sql: Unexpected character.

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#170]
After some git shenanigans the generator started to fail with the following error:
```
[SEVERE] moor_generator:moor_generator on ****.dart:
Error running MoorGenerator
Malformed sql: Unexpected character. at <FileLocation: 28 unknown source:1:29>, Unexpected character. at <FileLocation: 71 unknown source:2:43>, Unexpected character. at <FileLocation: 104 unknown source:3:33>, Unexpected character. at <FileLocation: 129 unknown source:4:25>, Unexpected character. at <FileLocation: 154 unknown source:5:25>, Unexpected character. at <FileLocation: 181 unknown source:6:27>, Unexpected character. at <FileLocation: 214 unknown source:7:33>, Unexpected character. at <FileLocation: 251 unknown source:8:37>, Unexpected character. at <FileLocation: 281 unknown source:9:30>, Unexpected character. at <FileLocation: 332 unknown source:10:51>
```

I was able to track it down to changes in line endings. Using something like Notepad++'s EOL Conversion tool to convert from this: 
![before](https://i.imgur.com/MdF1YF4.png) 
to this: 
![after](https://i.imgur.com/LIhaCO5.png)
makes the generator work again.

**Comment by simolus3** [comment]
I'm wondering if we could just accept `\r` for whitespace as well - it would certainly be the most easy fix. I hope it doesn't break the mapping from offsets to line/column numbers (we use another package for that). I'm also not sure how Dart treats the raw `\r` character in string literals or if we have to escape it.

> After some git shenanigans

Isn't the default behavior for Windows to use \r\n and git strips away the \r when committing? I'm wondering how that ever worked on Windows...

**Comment by Mike278** [comment]
Yeah I'm not sure either. When I create new .moor files from inside the IDE the line endings are `\n`, but maybe some of the stash/shelving nonsense caused the existing .moor files to be recreated with `\r\n`.

**Comment by git-xbits** [comment]
Hi guys, any chance to resolve this error? Same problem in my code. Using the exemple code from sql declarations, I get the exception.

**Comment by simolus3** [comment]
On the `develop` branch, moor will stop complaining about the `\r` character. You can try it out by putting this in your pubspec:
```yaml
dependency_overrides:
  sqlparser:
    git:
      url: git://github.com/simolus3/moor.git
      ref: develop
      path: sqlparser/
```

I don't know whether this fixes the problem entirely - we might have some problems when the `\r` character appears inside a Dart string as part of the generated code. I'll take a more detailed look tomorrow, I hope I can fix it then.

**Comment by simolus3** [comment]
We now escape `\r` in generated Dart literals. As sqlite accepts `\r` as whitespace, there shouldn't be any problems. I'll release an update this weekend.
