### ISSUE TITLE
Documentation issue: Documentation 

### ISSUE THREAD

**Issue by bePagani** [simolus3/moor#1702]
```
Future<void> writeDrivers(Policie entry) {
  return transaction((_) async {
    final cart = entry.cart;

    // first, we write the shopping cart
    await into(shoppingCarts).insert(cart, mode: InsertMode.replace);

    // we replace the entries of the cart, so first delete the old ones
    await (delete(shoppingCartEntries)
        ..where((entry) => entry.shoppingCart.equals(cart.id)))
        .go();

    // And write the new ones
    for (final item in entry.items) {
      await into(shoppingCartEntries).insert(ShoppingCartEntry(shoppingCart: cart.id, item: item.id));
    }
  });
}
```

i got error The argument type 'Future<void> Function(dynamic)' can't be assigned to the parameter type 'Future<void> Function()'.dart[argument_type_not_assignable](https://dart.dev/diagnostics/argument_type_not_assignable)

**Comment by simolus3** [comment]
Thanks for the report! The docs are outdated, you should drop the `_` parameter from the `transaction` callback. I've updated the docs on this in 536d5108259e6fa4d545da8fd340660765daaeb2.

I'm in the process of updating and testing the snippets used in the docs, hopefully I'll find all of those mistakes soon:D
