### ISSUE TITLE
Support boolean and datetime columns in moor files

### ISSUE THREAD

**Issue by simolus3** [simolus3/moor#171]
We currently only use [sqlite's rules](https://www.sqlite.org/datatype3.html#determination_of_column_affinity) to determine the column affinity, but we should consider adding special cases for boolean and datetime values. Maybe we can replace rule 5 from the linked document with

- if the declared type for a column contains "BOOL", it has an integer affinity with a boolean type hint
- if the declared type for a column contains "DATE", it has an integer affinity with a datetime type hint
- Otherwise, the affinity is NUMERIC

**Comment by simolus3** [comment]
Works on `develop`, will be part of the next release.

**Comment by git-xbits** [comment]
Have a date to release this new feature? unfortunatelly I need this.

**Comment by simolus3** [comment]
It'll probably be a small release that happens soon. I want to catch up on some other issues as well so I can't give an exact date, but if everything works it should be ready this weekend.
