### ISSUE TITLE
[Suggestion] In debug mode validate what the db schema should be against what it is

### ISSUE THREAD

**Issue by North101** [simolus3/moor#1718]
I think it would be really helpful to be able to validate the db file (after migrations) vs what it would be with the latest data. This way we can check that the migrations are correct.

It will also point people to what is wrong when something isn't working the way it's expected to.

**Comment by simolus3** [comment]
I really like the idea :+1: Sounds like something that should be helpful for most users.

The current implementation of the schema diff will only work with `dart:ffi` (so not on the web), but that shouldn't be a big concern since most users are on a Dart VM.

**Comment by North101** [comment]
What do you think would be the best way to do it. I was thinking something like using `PRAGMA table_info(<table>)` and then comparing it against the generated table.

**Comment by simolus3** [comment]
We happen to have this exact thing implemented with [verified schema migrations](https://drift.simonbinder.eu/docs/advanced-features/migrations/#verifying-migrations) :) It is based on reading the schema via `sqlite3_schema`, parsing the SQL with `sqlparser` and then doing a semantic diff over tables and columns.

The challenge is that the verification logic is currently implemented in `drift_dev` and I _really_ want to avoid a circular dependency between those two packages. We could move the logic over into `drift`.
We could also keep the logic in `drift_dev` and ask users to invoke it manually. That avoids drift depending on `sqlparser`, but it would require users to proactively add the assertion, which I imagine very few will even be aware of. I'm still leaning towards the later option since this an opt-in also avoids breaking users if the check turns out to be overly sensitive.

**Comment by simolus3** [comment]
I've added this as an optional API to `drift_dev` and started recommending it in the docs.

Thanks again for the suggestion, I think this can really help users a lot with minimal effort.

**Comment by North101** [comment]
That was quick! Thanks!

I actually suggested it because of some of the issues that have been coming up lately :P

**Comment by North101** [comment]
I've changed to the develop overrides and I'm not sure how to use this feature. `validateDatabaseSchema` can't be used in `beforeOpen` like in your example:
```
The instance member 'validateDatabaseSchema' can't be accessed in an initializer.
```

I've tried running:
```
  final db = Database();
  try {
    await db.validateDatabaseSchema();
    return true;
  } catch (exception) {
    print(exception);
    return false;
  } finally {
    await db.close();
  }
```
and im getting this error on a valid db:
```
LateInitializationError: Field '_delegate@1469089718' has not been initialized.
```

**Comment by simolus3** [comment]
> The instance member 'validateDatabaseSchema' can't be accessed in an initializer.

Oh right, it should probably be a getter.

> LateInitializationError: Field '_delegate@1469089718' has not been initialized.

Good catch, this happens when  `validateDatabaseSchema` is used on a closed database. Fixed in db1a4e2827670a7a8c45cc5307bb047f00502557!

**Comment by North101** [comment]
Works great! Thanks! This is my debug screen:

```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:drift_dev/api/migrations.dart';

import '/db/database.dart';

enum DatabaseState {
  none,
  valid,
  invalid,
}

final dbStateProvider = FutureProvider((ref) async {
  final dbFile = await Database.dbFilename();
  if (!await dbFile.exists()) return DatabaseState.none;

  final db = Database();
  try {
    await db.validateDatabaseSchema();
    return DatabaseState.valid;
  } catch (exception) {
    print(exception);
    return DatabaseState.invalid;
  } finally {
    await db.close();
  }
});

class DebugPage extends ConsumerWidget {
  const DebugPage({
    required this.home,
    Key? key,
  }) : super(key: key);

  final Widget home;

  Future<void> openPage(BuildContext context) {
    return Navigator.of(context).pushReplacement(
      MaterialPageRoute(
        builder: (context) => home,
      ),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final dbState = ref.watch(dbStateProvider);
    return Scaffold(
      appBar: AppBar(
        title: const Text('Debug'),
      ),
      body: dbState.when(
        loading: () => const Center(child: CircularProgressIndicator()),
        error: (error, stackTrace) => Text(error.toString()),
        data: (state) => Stack(
          children: [
            SizedBox.expand(
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Padding(
                    padding: const EdgeInsets.all(8),
                    child: ElevatedButton(
                      style: state == DatabaseState.invalid
                          ? ButtonStyle(
                              backgroundColor: MaterialStateProperty.all(Colors.red),
                            )
                          : null,
                      onPressed: () => openPage(context),
                      child: state == DatabaseState.none ? const Text('New Database') : const Text('Keep Database'),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.all(8),
                    child: ElevatedButton(
                      onPressed: state != DatabaseState.none
                          ? () async {
                              await Database.deleteDatabase();
                              ref.refresh(dbStateProvider);
                            }
                          : null,
                      child: const Text('Delete Database'),
                    ),
                  ),
                ],
              ),
            ),
            if (state == DatabaseState.invalid)
              const MaterialBanner(
                content: Text('Database not valid'),
                leading: Icon(Icons.error, color: Colors.red),
                actions: <Widget>[
                  TextButton(
                    onPressed: null,
                    child: Text(''),
                  ),
                ],
              ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by North101** [comment]
![Uploading Screenshot_20220301-204249.png…]()

**Comment by North101** [comment]
![Screenshot_20220301-204249](https://user-images.githubusercontent.com/1031451/156246045-78ac58a1-1085-4ae3-a802-ffb62fbe7a6f.png)
![Screenshot_20220301-204313](https://user-images.githubusercontent.com/1031451/156246058-05f0e075-fedc-4a83-a871-95fa119f062d.png)
![Screenshot_20220301-204355](https://user-images.githubusercontent.com/1031451/156246062-e5e4f3f3-9f5a-430d-a057-5c51eb1ba93e.png)

**Comment by simolus3** [comment]
Nice!

> Also in your examples you have `SchemaMigration` but I think it should be `MigrationStrategy`

I really messed the example up haha. At least this finally motivated me to extract the snippets in the docs from full Dart files that are analyzed in CI. Much better now :)
