### ISSUE TITLE
Option to not generate validateIntegrity and Verification code

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#173]
Would it be possible to add a builder option that prevents the `VerificationMeta` and `validateIntegrity` code from being generated? It accounts for a pretty big chunk of the generated file, and I believe sqlite performs the same type of validation. You'd miss out on the more detailed error messages that moor generates, but localized applications probably have custom error messages anyway.

**Comment by simolus3** [comment]
That's a pretty reasonable suggestion, users who only use the sql api probably won't need it at all and the new `insert` constructor on companions should make required fields hard to miss.
When the `skip_verification_code` build option is enabled, moor won't override `validateIntegrity` and won't write verification meta fields.

**Comment by Mike278** [comment]
Wow that was fast, thanks so much Simon! The `.g.dart` file is getting pretty big, so this should help significantly.
