### ISSUE TITLE
toJson and fromJson keys for tables defined in .moor files

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#176]
I'm looking for a way to make `DataClass.toJson` and `DataClass.fromJson` use the sql column name for keys instead of the dart getter name. This is possible for tables defined in dart using the `JsonKey` annotation, but it doesn't look like it's possible for tables defined in .moor files. I think it's probably reasonable to always use the sql column name for toJson/fromJson when generating a DataClass for a table defined in a .moor file, but this would be a breaking change so it would need to be configurable. Adding something to the .moor file grammar doesn't seem ideal though... any ideas?

**Comment by simolus3** [comment]
I agree that using the Dart getter name for a column declared in a .moor file is nonsense, we should have a special case for them. Introducing a flag that uses the defined column name and make it the default eventually sounds like a good idea to me.

> Adding something to the .moor file grammar doesn't seem ideal though

We should pick the column name by default, but if users want a different json key, why not? Maybe some custom column constraint like `foo INTEGER JSON KEY bar`?

**Comment by simolus3** [comment]
Just added the `use_column_name_as_json_key_when_defined_in_moor_file` option that enables the breaking behavior.

**Comment by Mike278** [comment]
@simolus3 Do you have an ETA on the next moor release? We're really missing this and #185

**Comment by simolus3** [comment]
I was a bit disappointed that there's no stable Flutter release shipping with Dart 2.6 yet. But that shouldn't stop a new release, especially not for the generator. I'll do some more polishing and try to release this weekend.
