### ISSUE TITLE
moor_flutter with chopper 3.0.1 analyzer incompatible

### ISSUE THREAD

**Issue by devaronius** [simolus3/moor#180]
Because no versions of moor_generator match >2.0.0 <3.0.0 and moor_generator 2.0.0 depends on analyzer_plugin ^0.1.0, moor_generator ^2.0.0 requires analyzer_plugin ^0.1.0.
Because analyzer_plugin 0.1.0 depends on analyzer >=0.35.3 <0.38.0 and no versions of analyzer_plugin match >0.1.0 <0.2.0, analyzer_plugin ^0.1.0 requires analyzer >=0.35.3 <0.38.0.
Thus, moor_generator ^2.0.0 requires analyzer >=0.35.3 <0.38.0.
So, because zorg_nl depends on both analyzer ^0.38.5 and moor_generator ^2.0.0, version solving failed.
pub get failed (1)

**Comment by simolus3** [comment]
Sadly there's no version of the `analyzer_plugin` that supports newer `analyzer` versions. Someone else [created a PR](https://dartbug.com/38558) for this which was merged, but the updated version hasn't been released yet.

**Comment by simolus3** [comment]
The next version of moor will work with the latest analyzer version. If everything goes well, I'll release the next version tomorrow.
