### ISSUE TITLE
Use data class name when generating companions

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#185]
#147 added support for customizing the name of the data class in .moor files like this:
```sql
CREATE TABLE google_user (
  -- some columns
) AS User
```
This generates a data class called `User`, but it generates a companion called `GoogleUserCompanion`. Could the companion name also use the customized data class name? For example, `UserCompanion`

**Comment by simolus3** [comment]
I'm not sure about this. The data class override mostly exists for cases where stripping a leading s doesn't result in a proper name (e.g. `CREATE TABLE categories (...) AS Category`). 
This is obviously subjective, but IMHO the companion belongs more to the table than it belongs to the dataclass, and its name has always been based on the table name. Overriding the dataclass name for Dart tables doesn't change the companion name either.

I don't really see a reason to change the current behavior. In your example, what's the reason the table isn't simply named "user"? In general, if that's the name you want for the data class and the companion, isn't any other table name misleading? I'm open to feedback here, but I can't come up with a scenario in which overriding both names while keeping the table name makes sense.

**Comment by Mike278** [comment]
> I can't come up with a scenario in which overriding both names while keeping the table name makes sense

The main scenario I'm dealing with is handling existing naming conventions between sql code and application-level database code. For example if my app had a Delivery module/feature, one of that feature's tables might be called `delivery_event_product_stock (event_id, product_id, stock)`, but app-level database code within the Delivery feature just refers to this as `Stock`. In an app with ~10 features and each feature having ~10 tables, this naming makes db-level work like writing custom queries and browsing tables easier, while app-level, feature-specific code doesn't necessarily need to be prefixed by feature and parent tables.

This might not be the best naming convention and it definitely doesn't work for everybody, but naming things is one of those classically hard problems, and allowing more configuration lets people be consistent with whatever they're used to.

That being said, I can understand wanting to stay closer the table representation, so maybe I'm thinking about moor's generated classes in the wrong way, and I should solve app-level naming problems with app-level model classes that wrap moor's data/companion classes.

**Comment by simolus3** [comment]
Thanks for the description, I can see how this could be very useful for modularization, but I don't think many apps are complex enough to benefit from that.
Nevertheless, we could probably introduce a build option for that naming behavior, but without the intention of making it a default eventually.

**Comment by Mike278** [comment]
A build option would be awesome!

**Comment by simolus3** [comment]
Should work with the referenced commit.

**Comment by Mike278** [comment]
Thanks so much Simon, this really helps a lot!
