### ISSUE TITLE
read big table 

### ISSUE THREAD

**Issue by wurikiji** [simolus3/moor#186]
If I read the whole records of the big table, does moor retrieve all data at once? If the size of the table is too big to fill the entire memory, what happens?

**Comment by wurikiji** [comment]
I found the `limit` operation can handle this. But I still wonder what happens. App crashes?

**Comment by simolus3** [comment]
Yeah, the app will crash when reading data larger than its available memory, there's not much moor can do about that :smile: But as you've said, with a `limit` operator in place this shouldn't happen. Let me know if you have any more questions.

**Comment by wurikiji** [comment]
@simolus3  Thanks!
