### ISSUE TITLE
customSelect doesn't support multiple column names

### ISSUE THREAD

**Issue by KeaSoft** [simolus3/moor#187]
My  table looks like following:
```
class Contacts extends Table {
  TextColumn get phone => text().nullable()();
  TextColumn get name => text().nullable()();
  BlobColumn get avatar => blob().nullable()();
  BoolColumn get isGroup => boolean().withDefault(Constant(false))();
  TextColumn get uuid => text()();
  @override
  Set<Column> get primaryKey => {uuid};
}
```
 While running of the` customSelect `:
```
customSelect(
      "SELECT phone , isgroup "
      "FROM contacts c "
      "WHERE c.uuid in ('$param')",
    )
``` 
I got the following error:
``` 
Moor: Sent SELECT phone , isGroup FROM contacts c WHERE c.uuid in ('7613dfce-898f-4e22-9bec-8b4176c29995','69c2b05c-86a3-44b4-9187-fd49192ce07a')
E/SQLiteLog( 6887): (1) no such column: isGroup
```
#### My purpose I don't want to load all fields

**Comment by simolus3** [comment]
Moor converts the column name from Dart into `camel_case`, so your Dart getter `isGroup` would be called `is_group` in sql. So if you use
```dart
customSelect(
      "SELECT phone , is_group "
      "FROM contacts c "
      "WHERE c.uuid in ('$param')",
    )
```
everything should work.

I know this can be annoying, but it would be a massive breaking change to change that behavior now. By the way, you can express the same query using "compiled custom queries", so something like:
```dart
@UseMoor(
  tables: [...],
  queries: {
    'phoneAndGroup': 'SELECT phone, is_group FROM contacts c WHERE c.uuid IN :uuids',
  },
)
```

will generate a `Future<List<PhoneAndGroupResult>>(List<String> uuids)` method that you can use. Moor can then catch sql errors at compile time (it would warn about a `isGroup` column not existing and suggest replacing it with `is_group`).

Let me know if that didn't fix your problem or you have any other questions :)
