### ISSUE TITLE
How to delete database if migration is needed

### ISSUE THREAD

**Issue by eitanaviv** [simolus3/moor#188]
As the title says, how can i delete the db if migration is needed but not provided?
I have an app currently in development and every time I modify tables I have to reinstall the app in order to avoid writing useless migrations.
Thanks!

**Comment by Mike278** [comment]
I've been doing is something like this:
```dart
beforeOpen: (openingDetails) async {
  if (isInDebugMode /* or some other flag */) {
    final m = Migrator(this, customStatement);
    for (final table in allTables) {
      await m.deleteTable(table.actualTableName);
      await m.createTable(table);
    }
  }
}
```

**Comment by vanlooverenkoen** [comment]
Or you could just do this as well.

```
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(join(dbFolder.path, 'transaction_db.sqlite'));
    if (inDevelopment) {
      await file.delete();
    }
    return VmDatabase(file);
  });
}
```

**Comment by clotodex** [comment]
In live app development you might want to recreate all tables on the click of a button.
I do it like this:

```
RaisedButton(
  onPressed: () {
    final m = Migrator(db, db.executor.runCustom);
    for (final table in db.allTables) {
      m.deleteTable(table.actualTableName).then((value) =>
        m.createTable(table).then((value) =>
          db.markTablesUpdated([table].toSet())
        )
      );
    }
  },
  child: Text("DELETE DATABASE")
),
```
This also notifies all tables to be updated so that ui depending on tables rebuilds itself.

**Comment by rommyarb** [comment]
> I've been doing something like this:
> 
> ```dart
> beforeOpen: (openingDetails) async {
>   if (isInDebugMode /* or some other flag */) {
>     final m = Migrator(this, customStatement);
>     for (final table in allTables) {
>       await m.deleteTable(table.actualTableName);
>       await m.createTable(table);
>     }
>   }
> }
> ```

Starting from moor v3.0.0, use this instead:
```dart
beforeOpen: (openingDetails) async {
  if (isInDebugMode /* or some other flag */) {
    final m = this.createMigrator(); // changed to this
    for (final table in allTables) {
      await m.deleteTable(table.actualTableName);
      await m.createTable(table);
    }
  }
}
