### ISSUE TITLE
Build don't override already existing tables(class).

### ISSUE THREAD

**Issue by git-xbits** [simolus3/moor#189]
I created the base with sql querys (like tutorial in documentation), and run 
flutter packages pub run build_runner build
All right, all normal, but, when I need to change some class , for exemple, insert new colunm in a table, I change the tables.moor and run again the code above, but don't change anything. I try run flutter clean, delete database.g.dart, restart my cpu, and nothing happens. Sometimes, without explanation, the build works and change tha class. But I don't have any idea how.

I tryied flutter packages pub run build_runner build --delete-conflicting-outputs with no results.

Don't have in documentation any information about this situation.

Doctor -v:

[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [versÃ£o 10.0.18362.418], locale pt-BR)
    • Flutter version 1.9.1+hotfix.4 at C:\SDK\flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc3)
    • Android SDK at C:\Users\Palte\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\Palte\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • 0 • 192.168.95.101:5555 • android-x86 • Android 6.0 (API 23)

• No issues found!

**Comment by git-xbits** [comment]
I tried 3 times right now and work normal. So, I close the issue until I have same problem again.

**Comment by simolus3** [comment]
Ok :+1: You can get some more information out of the build by running it with the `-v` flag, so `flutter pub run build_runner build -v`, that might help if you hit this again.
