### ISSUE TITLE
[question] Mapping data for 1:m relationships

### ISSUE THREAD

**Issue by andrewpmoore** [simolus3/moor#190]
I'm just picking up moor and liking it so far.

I've seen the example where there's a join between 2 tables and an class created to hold the data from both of these, but it seems to be a 1:1 relationship.

I'm curious if you can think of an efficient way to do similar with a 1:m relationship, so I'm wanting my data in one select statement to be more efficient, but I'm then needing to map it to a Class that will be more like

```
class EntryWithCategoryList {
  EntryWithCategory(this.entry, this.category);

  final TodoEntry entry;
  final List<Category> categoryList;
}
```

Is there anything in the library to assist with this? I can see all the data successfully retrieved but can't think of an easy way to map it into a structure like above.

**Comment by simolus3** [comment]
There's no builtin functionality to read both a single entry and an associated list. 

You can use RxDart to combine multiple queries a bit easier, but it's still not exactly convenient to write (written off the top of my head, but something like this should work):

```dart
Stream<EntryWithCategoryList> readEntry(int id) {
  final entryStream = Observable((select(entries)..where((e) => e.id.equals(id))).watchSingle());
  return entryStream.switchMap((entry) {
    final categoriesStream = (select(categories)..where((c) => c.entry.equals(entry.id)))
    return categoriesStream.map((categories) => EntryWithCategoryList(entry, categories));
  });
}
```

There's a moor fork which supports common ORM features, see https://github.com/simolus3/moor/issues/114#issuecomment-531566606. I'm afraid I didn't have a chance to take a detailed look at it yet, but I'll do that this weekend and contact the author to merge that fork into this repo.
