### ISSUE TITLE
insert(orReplace:true) does not seem to work for text primary keys

### ISSUE THREAD

**Issue by thetrav** [simolus3/moor#192]
https://github.com/thetrav/moor_test/blob/master/lib/database.dart

The two relevant snippets are the model definition:
```
class Socks extends Table {
  TextColumn get id => text()();
  TextColumn get label => text()();

  @override
  Set<Column> get primaryKey => {id};
}
```

and the upsert function:
```
Future<int> upsert(String id, String label) {
    return into(socks).insert(SocksCompanion(
      id: Value(id),
      label: Value(label)
    ), orReplace: true);
  }
```

This test app I put together calls the upsert function repeatedly with the same ID but a variable label.  It observes new entries being written to the socks table where I would have expected only one entry to ever be in that table due to primary key constraints

**Comment by thetrav** [comment]
Ok, a lot more reading reveals that the problem is due to a unique constraint not being automatically applied to the primary key.  It's fixed by:

```
class Socks extends Table {
  TextColumn get id => text().customConstraint("UNIQUE")();
```

**Comment by simolus3** [comment]
I'm pretty sure `INSERT OR REPLACE` should also work when a primary key constraint is violated.

I didn't try it with moor, but manually running
1. `CREATE TABLE IF NOT EXISTS socks (id VARCHAR NOT NULL, label VARCHAR NOT NULL, PRIMARY KEY (id));`
2. `INSERT OR REPLACE INTO socks VALUES ('a', 'b')`
3. `INSERT OR REPLACE INTO socks VALUES ('a', 'c')`
4. `SELECT * FROM socks`

Yields a single row with `(a, c)` values, and those are the queries that should be generated by moor. Could it be that you first wrote the table without the primary key, ran your app and then added the primary key? In that case the primary key wouldn't be written anymore. I copy-pasted your example (without the unique addition), and moor did write the primary key in the create table statement.

**Comment by thetrav** [comment]
Ok, sorry that was my bad.  I must have run the first test prior to adding the primary key override.  Re-testing shows that it works.

The issue I observed in my main app that I was trying to re-create relates to constraints across multiple columns, which is already spoken about at: https://github.com/simolus3/moor/issues/172

**Comment by thetrav** [comment]
Ok, I tried adding a second index field to the test and that worked as expected.

I now have no idea why my main app was entering duplicates.  I've already added unique constraints to the important columns and it no longer adds duplicates 🤷‍♂
