### ISSUE TITLE
Companion fromJson/toJson

### ISSUE THREAD

**Issue by Ahmed-elshorbagy** [simolus3/moor#1924]
**Is your feature request related to a problem? Please describe.**
in a situation we send data over network we can send insertable objects as json after they reach the server we need to convert them back to objects to insert them in database which is not available in companion

**Describe the solution you'd like**
add tojson/from json to companion objects
thanks in advance

**Comment by simolus3** [comment]
To send insertable objects over the wire, you can do `json.encode(companion.toColumns(false))`. To receive those objects, you can use `RawValuesInsertable(json.decode(serializedData) as Map<String, Object?>)`.

I think there's not much added value if companion objects have builtin serialization capabilities. It's just additional generated code that can already be expressed by encoding the columns that a companion actually holds.

**Comment by Ahmed-elshorbagy** [comment]
@simolus3 
I tried but it gives me 
`JsonUnsupportedObjectError (Converting object to an encodable object failed: Instance of 'Variable<DateTime>')`

at this line
`json.encode(companion.toColumns(false))`

i tried to bypass this
```
final rawValues = item
        .toColumns(false)
        .cast<String, Variable>()
        .map((key, value) => MapEntry(key, value.mapToSimpleValue(context)))
```
but got error while decoding
`RawValuesInsertable(json.decode(serializedData) as Map<String, Object?>)`

**Comment by Ahmed-elshorbagy** [comment]
@simolus3 
at least we need to make the `Variable `class serializable

**Comment by simolus3** [comment]
Good point, I haven't considered that companions map to expressions now. But  this seems to work for me:

```dart
extension CompanionJson<T> on Insertable<T> {
  static Insertable<T> fromJson<T>(Map<String, Object?> json) {
    return RawValuesInsertable(
        json.map((key, value) => MapEntry(key, Variable(value))));
  }

  Map<String, Object?> toJson() {
    final map = <String, Object?>{};
    final context = GenerationContext(SqlTypeSystem.defaultInstance, null);

    toColumns(false).forEach((key, value) {
      if (value is! Variable) {
        throw ArgumentError('Value for $key is not a variable');
      }

      map[key] = value.mapToSimpleValue(context);
    });

    return map;
  }
}

```

**Comment by Ahmed-elshorbagy** [comment]
@simolus3 
> Good point, I haven't considered that companions map to expressions now. But this seems to work for me:
> 
> ```dart
> extension CompanionJson<T> on Insertable<T> {
>   static Insertable<T> fromJson<T>(Map<String, Object?> json) {
>     return RawValuesInsertable(
>         json.map((key, value) => MapEntry(key, Variable(value))));
>   }
> 
>   Map<String, Object?> toJson() {
>     final map = <String, Object?>{};
>     final context = GenerationContext(SqlTypeSystem.defaultInstance, null);
> 
>     toColumns(false).forEach((key, value) {
>       if (value is! Variable) {
>         throw ArgumentError('Value for $key is not a variable');
>       }
> 
>       map[key] = value.mapToSimpleValue(context);
>     });
> 
>     return map;
>   }
> }
> ```

this code will give error if you try to encode it with json in case of DateTime and bool variables as datetime & bool are converted to ints after serialization so you can't convert them back to bool or DateTime I've bypassed this with some bad code
I hope if you have a better approach


```dart
extension CompanionJson<T> on Insertable<T> {
  static Insertable<T> fromJson<T>(Map<String, Object?> json) {
    return RawValuesInsertable((json.map((key, value) => MapEntry(
        key,
        value is Map
            ? Variable(DateTime.fromMillisecondsSinceEpoch(value["DateTime"]))
            : Variable(value)))));
  }

  Map<String, Object?> toJson() {
    return toColumns(false).cast<String, Variable>().map((key, value) =>
        MapEntry(
            key,
            value.value is DateTime
                ? {"DateTime":(value.value as DateTime).millisecondsSinceEpoch}
                : value.value));
  }
}
```
