### ISSUE TITLE
Examples/app: Record with ID 1 not shown

### ISSUE THREAD

**Issue by baeckerg** [simolus3/moor#1925]
Hello,

in the examples app the table todo_entries does not show the record in the listview on Windows if id=1. I try by removing your default 1 (which is not shown on Windows) and by adding a new record with an ID=1

Otherwise: awesome work and KUDOS

**Comment by simolus3** [comment]
Thanks for the report, and good catch! This is a bug in the example. It only shows the entries in the currently selected category (the selection can be changed in the navigation drawer), but the query to load todo entries in the current category was using a wrong join.

I've fixed this in a3109b4a6bce7e9d55dc76d195a1c53cef03d970.

**Comment by baeckerg** [comment]
Many thanks Simon
Mit freundlichen Grüssen Gernot
