### ISSUE TITLE
How to Select all rows in a table

### ISSUE THREAD

**Issue by JacksiroKe** [simolus3/moor#1927]
`List<Students> students = await select(student).get();`

is a simple function which I expect to fetch for me all the records in my table, but the worst thing is that out 5000+ rows only 100 are fecthed, why is that so? Am I suppored to write a custom select query?

**Comment by simolus3** [comment]
> is a simple function which I expect to fetch for me all the records in my table, but the worst thing is that out 5000+ rows only 100 are fecthed, why is that so?

Are you sure that they are 5000+ rows? You can enable `logStatements: true` on the `NativeDatabase` constructor to see what SQL statements drift runs, but that statement should just translate to `SELECT * FROM students`. I don't think custom select statements would help here, it really looks like there might be fewer rows in the table than the 5000 you're expecting.

**Comment by JacksiroKe** [comment]
Thank you for your prompt answer, I found the issue was elsewhere from a parse server (back4app) api which limits a select query to 100 rows such that the data am saving to my drift database is just 100 rows
