### ISSUE TITLE
[BUG] Generated custom queries only generate method that return Selectable

### ISSUE THREAD

**Issue by noxasch** [simolus3/moor#1930]
According to the [docs](https://drift.simonbinder.eu/docs/using-sql/custom_queries/) , when i run build for Statements with a generated api, it will generate two method in the mixin. But when i declare a statement in the DAO, it only generated a method that return a Selectable without `watch()` or `get()` that should return a `Future` and a `Stream`.

Of course this still can be use as follow, but if this is intended then the docs should be updated as previous version behave as what the doc says but no longer on current version.
```dart
todosDAOinstance.todosGenerated().watch();
todosDAOinstance.todosGenerated().get();
```
Version:
> drift: 1.7.1
> drift_dev: 1.7.0

Expected output:
watch and get version of the query is generated.

Here is my code:

```dart
part 'todo_dao.g.dart';

@DriftAccessor(tables: [
  Todos
], queries: {
  'todosGenerated':
      'SELECT * FROM todos ORDER BY date DESC, name;'
})
class TodoDAO extends DatabaseAccessor<MyDatabase>
    with _$TodoDAOMixin {
  TodoRepository(MyDatabase db) : super(db);

}
```

Generated code:

```dart
// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'todo_dao.dart';

// **************************************************************************
// DaoGenerator
// **************************************************************************

mixin _$TodoDAOMixin on DatabaseAccessor<MyDatabase> {
  $TodosTable get todos => attachedDatabase.todos;
  Selectable<Todo> todosGenerated() {
    return customSelect(
        'SELECT * FROM todos ORDER BY date DESC, name;',
        variables: [],
        readsFrom: {
          todos,
        }).map(todos.mapFromRow);
  }
}
```

**Comment by kuhnroyal** [comment]
You can use the Selectable to watch and get. The docs there must be really old.

**Comment by simolus3** [comment]
This is working as intended in drift, but the documentation is indeed outdated. I have updated that page in ef3ee418d4840fbf400118a84dedd155095fe1c2.

As @kuhnroyal said, we now generate a single method that does both (`yourQueryMethod().get()` to run it once, `yourQueryMethod.watch()` to get an auto-updating stream).
