### ISSUE TITLE
Retrun affected upon updating

### ISSUE THREAD

**Issue by Vedsaga** [simolus3/moor#1944]
**Is your feature request related to a problem? Please describe.**
Recently I was in need to get back the affected row during update. 

**Describe the solution you'd like**
Since version 3.35.0 (2021-03-12), SQLite includes a non-standard [RETURNING clause](https://sqlite.org/lang_returning.html) that allows for what you are looking for.

So, just like `insertReturning`
```dart
    final access = await into(userAccessTable).insertReturning(userAccess);
```

It would be great to have `updateReturing`

**Comment by simolus3** [comment]
Good idea, I have added a returning variant for updates and deletes in 080ef7210c4017b3a6b5341850af08b5596a28f9.
