### ISSUE TITLE
`validateDatabaseSchema` doesn't support `store_date_time_values_as_text`

### ISSUE THREAD

**Issue by North101** [simolus3/moor#1947]
With `store_date_time_values_as_text = true`, `validateDatabaseSchema` will fail because it was expecting an `INTEGER` but found a `TEXT`.

**Comment by simolus3** [comment]
I've also fixed this one already (thanks for opening this as separate issues though - good for visibility).

**Comment by North101** [comment]
Confirmed working. Thanks!
