### ISSUE TITLE
Different instances of _LazyExpression with the same column expression aren't equal.

### ISSUE THREAD

**Issue by North101** [simolus3/moor#1949]
```
Unhandled Exception: Invalid argument(s): Invalid call to read(): Instance of '_LazyExpression<String>'. This result set does not have a column for that expression.
```

The above error happens when I run the below code (I think... this happened while generating dynamic queries and I tried to simplify it but haven't tested it yet).

```dart
query = selectOnly(table);
query.addColumns([datetimeColumn.date]);
return query.get().map((e) => e.read(datetimeColumn.date));
```

To fix it I need to do:
```dart
final dateColumn = datetimeColumn.date;
query = selectOnly(table);
query.addColumns([dateColumn]);
return query.get().map((e) => e.read(dateColumn));
```

Is this intended?

**Comment by simolus3** [comment]
It's not, the whole concept was broken. Since it was only used to distinguish between datetimes, I have just added a special class for that which does that and also implements `==` correctly.

**Comment by North101** [comment]
Confirmed working. Thanks!
