### ISSUE TITLE
False positive for warning when using both drift file and customConstraint() on dart table

### ISSUE THREAD

**Issue by Jhonnyc** [simolus3/moor#1964]
**Describe the bug**

I created a class that extends the Table class and added some columns under it and for some of them I added a customConstraint, in addition I also added a '.drift' file that only has the indexes for tables in the project, when running my project I get the following warning -

```
[INFO] drift_dev:drift_dev on lib/logic/repository/database/database.dart:line 69, column 17 of package:test/logic/repository/entities/user.dart: This column definition is using both drift-defined constraints (like references, autoIncrement, ...) and a customConstraint(). Only the custom constraint will be added to the column in SQL!
   ╷
69 │   IntColumn get age => integer()
   │                 ^^^^^^^^^^^^^^^
   ╵
```

Since the column is not indexed in the .drift file I'm not sure if there's any action item or it's a bug or a general warning...

**Comment by simolus3** [comment]
Is `age` the column where you've added the `customConstraint`? If so, can you post the full column defintion.

`customConstraint` replaces all column constraints when generating the column. So e.g. if you did `integer().references(OtherTable, #otherColumn).customConstraint('CHECK whatever')`, the column would be generated as `INTEGER CHECK whatever` - the `REFERENCES` clause is gone! This is what drift is trying to warn you about, the index in the `.drift` file should be unrelated to that.

**Comment by Jhonnyc** [comment]
Thanks for your fast reply! here's the full column definition :

  IntColumn get age => integer()
      .nullable()
      .customConstraint("CHECK (age BETWEEN 0 AND 100)")
      .withDefault(Constant(0))();

Also - if I understand correctly - for this type of column I basically have nothing to do, no?

**Comment by simolus3** [comment]
The problem here is the `withDefault` call. Using `withDefault` will add a column constraint to the column (`DEFAULT 0`), but your `customConstraint` call is overriding that. This is what drift is complaining about. In your case, you can just use

```dart
IntColumn get age => integer()
.nullable()
.customConstraint("CHECK (age BETWEEN 0 AND 100) DEFAULT 0");
```

I'll close this since this doesn't sound like a false-positive lint.
