### ISSUE TITLE
How to access pre-defined table?

### ISSUE THREAD

**Issue by cornsauce** [simolus3/moor#197]
I intend to insert or replace a huge of entities, and each of those entities formed as a nested object. Just only access other meta-table many times to finish one operation. If I can access `sqlite_sequence`, I can finish it by reading `seq` instead of those redundancies. But I have tried `.moor` and its failure while executing build_runner.

sql.moor
```
currentSeq: SELECT seq FROM sqlite_sequence WHERE name = :table;
nextSeq: SELECT seq + 1 AS seq FROM sqlite_sequence WHERE name = :table;
```

error message:
```
[WARNING] moor_generator:moor_generator on lib/feat_v0.0.2/Component/RTC/data_moor/data.dart:
There were some errors while running moor_generator on package:enjoy_flutter/feat_v0.0.2/Component/RTC/data_moor/data.dart:
[WARNING] moor_generator:moor_generator on lib/feat_v0.0.2/Component/RTC/data_moor/data.dart:
line 1, column 29: Could not find sqlite_sequence. Available are:
  ╷
1 │ currentSeq: SELECT seq FROM sqlite_sequence WHERE name = :table;
  │                             ^^^^^^^^^^^^^^^
  ╵
[WARNING] moor_generator:moor_generator on lib/feat_v0.0.2/Component/RTC/data_moor/data.dart:
line 2, column 37: Could not find sqlite_sequence. Available are:
  ╷
2 │ nextSeq: SELECT seq + 1 AS seq FROM sqlite_sequence WHERE name = :table;
  │                                     ^^^^^^^^^^^^^^^
  ╵

```

**Comment by simolus3** [comment]
We should make the structure of internal sqlite tables (`sqlite_master`, `sqlite_sequence`, maybe also the stat tables) available to the parser so that it doesn't complain about tables not existing.

In the meantime, you could use a manual custom select statement:
```dart
@UseMoor(...)
class MyDatabase extends _$MyDatabase {
  // ...
  Future<int> currentSeq(String table) {
    return customSelectQuery(
      'SELECT seq FROM sqlite_sequence WHERE name = :table;',
      variables: [Variable.withString(table)],
    )
    .map((row) => row.readInt('seq'))
    .getSingle();
  }
}
```

**Comment by Mike278** [comment]
That reminds me I’m also using a custom select when I want to use the [rowid aliases](https://www.sqlite.org/lang_createtable.html#rowid) - typically as a stable ORDER BY for consistent LIMITing on a composite primary key table.

**Comment by simolus3** [comment]
Phew, supporting rowid aliases was more complicated than I expected (mostly name resolving when used as a result column), I hope I didn't miss anything. 

Anyway, the `sqlite_master` and `sqlite_sequence` tables and rowid aliases will be available in the next moor version.

**Comment by cornsauce** [comment]
Thinks for you. I got it.
