### ISSUE TITLE
Await onUpgrade during migration

### ISSUE THREAD

**Issue by vibhavkarthik03** [simolus3/moor#1982]
Hi @simolus3 
 
I have a custom splash screen which uses shared_preferences to decide user’s landing screen.

In the migration strategy, I’m clearing some of these preferences so that the user lands in a particular screen.

My problem is, this splash screen fetches values from shared_preferences before all the migrations are done. Is there a way where I can await onUpgrade and show a loading state until all migrations are done?

**Comment by simolus3** [comment]
Hi! Drift lazily opens the database (which potentially includes running a migration) the first time it is used. So, if you have a database instance `db`, you can just `await db.doWhenOpened((e) => null);` to await the database being fully open and migrated.

**Comment by vibhavkarthik03** [comment]
Thanks for the quick reply! @simolus3 

I did try `await db.doWhenOpened((e) => null);` , turns out `doWhenOpened` works only when `LazyDatabse` returns
`SqfliteQueryExecutor.inDatabaseFolder()`. It doesn't work if my `LazyDatabse` returns `NativeDatabase`. Am I doing anything wrong here ?

**Comment by simolus3** [comment]
Hm, that doesn't sound right. In an example from this repository, I couldn't reproduce this (doing `doWhenOpened`) opens the database and runs migrations there. Those all use a `NativeDatabase`.

What exactly was the problem you ran into with `NativeDatabase`s?

**Comment by vibhavkarthik03** [comment]
> What exactly was the problem you ran into with `NativeDatabase`s?

@simolus3 I didn't face any issues with `NativeDatabase`. It's just, `await db.doWhenOpened((e) => null);` awaits with `SqfliteQueryExecutor.inDatabaseFolder()` but doesn't await with `NativeDatabase`.

**Comment by vibhavkarthik03** [comment]
This is how I'm setting up the DB:
```
LazyDatabase _openConnection() {
  return LazyDatabase(
    () async {
      final dbFolder = await getApplicationDocumentsDirectory();
      final file = File(p.join(dbFolder.path, 'db.sqlite'));
      return NativeDatabase(file);
    },
  );
}
```

**Comment by vibhavkarthik03** [comment]
@simolus3 I've found the issue. In development while testing, my older app had `SqfliteQueryExecutor.inDatabaseFolder()` and my new app had `NativeDatabase `. This is why `await doWhenOpened` didn't work for me. 

Thanks for the quick replies and your valuable time.
