### ISSUE TITLE
Migrations - Add a not nullable column

### ISSUE THREAD

**Issue by Rossdex** [simolus3/moor#1985]
If I add a non-nullable column to a table that already has data in it and give it a default value, on migration I get this error.

```ALTER TABLE my_existsing_table ADD COLUMN completed INTEGER NOT NULL DEFAULT 0 CHECK (completed IN (0, 1));``` 

This forces me to add all new columns as nullable. There are no examples in the migration of adding a not-nullable column to an existing table. Am I missing something or is this a limitation of SQLite? 

Thanks.

**Comment by simolus3** [comment]
> it and give it a default value, on migration I get this error.

Which error exactly? That SQL statement looks correct to me, and it seems like it should work. Can you provide more details on what error you ran into?

**Comment by Rossdex** [comment]
Sorry I thought i'd pasted the error in. See Below:

```
flutter: SqliteException(1): SQL logic error
Causing statement: ALTER TABLE form_structure_resource_check_types ADD COLUMN complete 
INTEGER NOT NULL DEFAULT 0 CHECK (complete IN (0, 1));
```


This is how I have added the column in dart. 

```  BoolColumn get complete => boolean().withDefault(const Constant(false))();```

**Comment by simolus3** [comment]
Hm, running that exact statement works for me after setting up a table with the same name and inserting some data. Your column definition also looks correct to me.

Do you have a way to share a small repro of this that I could run to take a deeper look?

**Comment by not-Ian** [comment]
Hey, wanted to chime in that I'm getting a similar issue adding a BoolColumn to an already existing table.

Here's my error:

```
SqliteException (SqliteException(1): SQL logic error
  Causing statement: ALTER TABLE answers ADD COLUMN is_compliance INTEGER NULL CHECK (is_compliance IN (0, 1));)
```

I'm adding both text and int columns to this same table right before adding the bool column in my migration code, those work fine:

```
if (fromVersion < 9) {
    await migrator.addColumn(answers, answers.instructionValue);
    await migrator.addColumn(answers, answers.repetitionCount);
    await migrator.addColumn(answers, answers.repetitionSequence);
    await migrator.addColumn(answers, answers.isCompliance);
    ...
}
```

Also, I've tried each of these three options separately, seems to be more a general issue with adding a bool column rather than having to do with a null/non-null column:

```
BoolColumn get isCompliance => boolean().nullable()()

BoolColumn get isCompliance => boolean().nullable().withDefault(Constant(false))()

BoolColumn get isCompliance => boolean().withDefault(Constant(false))()
```

As for package version:

```
drift: 1.0.1
drift_dev: 1.0.2
flutter: 2.10.5
dart: 2.16.2
```

Just spent a few hours migrating, and it didn't work:

```
drift: 2.1.0
drift_def: 2.1.0
flutter: 3.3.0
dart: 2.18.0
```

**Comment by simolus3** [comment]
Thanks for the report. Given that I couldn't reproduce the logic error locally, can you check that you're using `sqlite3_flutter_libs`? If you run this in your database, what version does it print?

```dart
print(await customSelect('select sqlite_version() as r')
    .map((row) => row.read<String>('r'))
    .getSingle());
```

**Comment by not-Ian** [comment]
Good thinking. In our pubspec:

`sqlite3_flutter_libs: 0.5.2`

The output of that print statement:

`3.37.2`

**Comment by simolus3** [comment]
Can you try upgrading to the latest version (`0.5.9` for `sqlite3_flutter_libs`)? Maybe this query is unintentionally relying on a new sqlite3 feature, but I'll also try to reproduce this on `3.37.2`.

**Comment by simolus3** [comment]
Hm this also seems to work for me when using version `3.37.2` of sqlite.

**Comment by DevHachi** [comment]
I am not sure if this is intended or just a copy paste error, but you have two different drift version

```
drift: 2.1.0 <---
drift_def: 2.1.0
flutter: 3.3.0
drift: 2.18.0 <---
```

**Comment by simolus3** [comment]
This is a [sqlite3 bug](https://sqlite.org/forum/info/3c1a00b66fca81fe) that has since been fixed.
