### ISSUE TITLE
Unable to have a nullable column with additional checks

### ISSUE THREAD

**Issue by davidhsoftware** [simolus3/moor#1989]
Hi there, 

Firstly thanks for the great library! After migrating to Drift 2.0.0 I'm unable to have a nullable column with contstraints, e.g.

`TextColumn get description => text().withLength(max: 250).nullable()();`

It happens if any `additionalCheck`  exists on the `GeneratedColumn`, when inserting a row it's `value` gets force unwrapped.

Is this intended?

**Comment by davidhsoftware** [comment]
@simolus3  #1990 fixes this issue

**Comment by simolus3** [comment]
Good catch, thanks for opening the issue and for your contribution. I've released version `2.0.1` of drift to pub.dev which contains the fix.
