### ISSUE TITLE
documentation_snippet_test.dart makes package:drift depend on package:drift_docs

### ISSUE THREAD

**Issue by bryanoltman** [simolus3/moor#1994]
drift/test/documentation_snippet_test.dart should be moved to the drift_docs package, as it is testing drift_docs functionality and not drift functionality.

**Comment by simolus3** [comment]
I've moved the test in 74ab9d4f806467539e9fc3045ef4197ff4a26b3c. I'll release and merge that into `latest_release` after fixing the other issues that came up with the 2.0 release.

**Comment by bryanoltman** [comment]
Thanks! What other issues are you referring to?

**Comment by simolus3** [comment]
In addition to the other one you've opened about moving the `drift_dev` schema test, there were a few new issues after the 2.0 release, namely #1991, #1992 and #1998. They're all fixed and published on pub.dev as well as `latest_release` now.

**Comment by bryanoltman** [comment]
Awesome! Thank you as always for your hard work :)
