### ISSUE TITLE
Compiler warnings in queries: Operand of null-aware operation '!' has type 'X' which excludes null

### ISSUE THREAD

**Issue by kuhnroyal** [simolus3/moor#1998]
**Describe the bug**

Not really a bug but could probably be improved.

```
Warning: Operand of null-aware operation '!' has type 'int' which excludes null.
        Variable<int>(Foo.$converter0.toSql(state)!),
```

The case here https://github.com/simolus3/drift/blob/develop/drift_dev/lib/src/writer/queries/query_writer.dart#L675 probably only needs to run if the sqlType is nullable?

**Comment by simolus3** [comment]
Good catch! I have removed the code entirely in ea1c635da8519c494c7d94bd99496b331e2db014. There's a check ensuring that converters with nullable SQL types cannot be applied to non-nullable columns (a safety advantage of the breaking type converter change in drift 2.0).
So we'd only generate invalid code if that warning gets ignored by the user (and it wouldn't really be broken code either way, `Variable` can take null as a value).
