### ISSUE TITLE
RTree module missing

### ISSUE THREAD

**Issue by FaFre** [simolus3/moor#2008]
The code generator gives me following output:

"Could not extract schema information for this table: Could not read table schema: Unknown module "rtree", did you register it?"

There is been an old issue (https://github.com/simolus3/drift/issues/655) saying that ´moor_ffi´ is containing it. However, I could not find any traces in this package. Do I miss something? In case not I can help with an PR.

**Comment by simolus3** [comment]
The `moor_ffi` package was the precursor to the `sqlite3_flutter_libs` + `sqlite3` + `package:drift/native.dart` libraries. The issue you've found refers to the module not being available at runtime, but it is available when using `sqlite3_flutter_libs`  and a `NativeDatabase` now.

Static analysis support for the rtree module has never been implemented. If you want to help with a PR, that'd be great! You can define an extension in the `sqlparser` package, similar to the one you've already implemented for fts5vocab. To make it available as a build option, you'd also have to add it to the `SqlModule` enum in `drift_dev` and handle it in `MoorSession.spawnEngine`. If you have any questions this, let me know!

**Comment by FaFre** [comment]
Alright, I will submit a PR.

I have also added support for spellfix (https://www.sqlite.org/spellfix1.html) in another branch and updated the `sqlite3` package. Everything is working, but I would need help to add the native compilation in the `sqlite3_flutter_libs` package for Mac and iOS, since I'm foreign to podfiles (Android + Linux is already implemented and Windows would also be easy to add). 

It is an official extension but not included in the amalgamation, that's why it requires to statically link an additional source file. Let me know if you want to support this extension and I will get it ready for a PR.

**Comment by simolus3** [comment]
I don't think there's much harm in including any extension from the sqlite sources as long as it's clearly maintained and doesn't increase binary size by too much. spellfix1 should be fine.

I currently use https://github.com/clemensg/sqlite3pod/blob/master/sqlite3.podspec as a source for sqlite3 on iOS and macOS (at least in `sqlite3_flutter_libs`). That pod doesn't seem to support the spellfix1 extension at the moment. It will probably be a bit challenging to add support for that in there since it requires an additional source to include. I can take a look at adding support for that in that pod if you want me to.

**Comment by simolus3** [comment]
> (Android + Linux is already implemented and Windows would also be easy to add)

Btw, how did you implement it on these platforms? I've tried changing the CI pipeline of this project to include the extension, but it looks like we need to compile it as a shared library:

https://github.com/simolus3/drift/blob/4e4444522da1c77793d4a5dab07266edb1d75d7f/.github/workflows/main.yml#L35

Do you think there's a way to statically link it into the main shared library?

**Comment by FaFre** [comment]
I think Linux and android is already compile with shared flag. It was just minimal work to get it linked. I just issued an PR. You can look it up for Linux here: https://github.com/simolus3/sqlite3.dart/pull/115/commits/4256a6379ea3a50e7216faff24e7d0a98ff69e53
