### ISSUE TITLE
Syntax error in generated CREATE TABLE statement

### ISSUE THREAD

**Issue by VadimOsovsky** [simolus3/moor#201]
DatabaseException(near "in": syntax error (code 1 SQLITE_ERROR): , while compiling: CREATE TABLE IF NOT EXISTS folders (local_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, guid VARCHAR NOT NULL, parent_guid VARCHAR NULL, account_id INTEGER NOT NULL, type INTEGER NOT NULL, `order` INTEGER NOT NULL, name VARCHAR NOT NULL, full_name VARCHAR NOT NULL, full_name_raw VARCHAR NOT NULL, full_name_hash VARCHAR NOT NULL, delimiter VARCHAR NOT NULL, is_subscribed BOOLEAN NOT NULL CHECK (is_subscribed in (0, 1)), is_selectable BOOLEAN NOT NULL CHECK (is_selectable in (0, 1)), `exists` BOOLEAN NOT NULL CHECK (exists in (0, 1)), extended BOOLEAN NULL CHECK (extended in (0, 1)), always_refresh BOOLEAN NOT NULL CHECK (always_refresh in (0, 1)));) sql 'CREATE TABLE IF NOT EXISTS folders (local_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, guid VARCHAR NOT NULL, parent_guid VARCHAR NULL, account_id INTEGER NOT NULL, type INTEGER NOT NULL, `order` INTEGER NOT NULL, name VARCHAR NOT NULL, full_name VARCHAR N

**Comment by simolus3** [comment]
Thanks for the report - the bug is fixed on `develop` and will be part of the next moor release.

As a workaround, you should be able to fix the error by changing the declaration of the `exists` column to:
```dart
BoolColumn get exists => boolean('folder_exists')();
```

**Comment by VadimOsovsky** [comment]
got it, thank you!
