### ISSUE TITLE
How can insert a table row only if it doesn't exist yet?

### ISSUE THREAD

**Issue by VadimOsovsky** [simolus3/moor#202]

**Comment by simolus3** [comment]
That should actually be the default behavior. If you insert a row that already exists, sqlite will reject the insert and an exception should be thrown.

For sqlite, the definition of "row that already exists" is a row with the same primary or unique key.

**Comment by VadimOsovsky** [comment]
can I check by another field, the situation is that I recieve data from the server, can check if there is a row with a specific field, if not - insert?

**Comment by simolus3** [comment]
If you're using the Dart api for inserts, you'd have to use a select first to check if the row exists.

In sql, you could probably use the approach from [this SO answer](https://stackoverflow.com/a/19337206). You can put that in a custom query and use variables like
```dart
@UseMoor(
  tables: [...]
  queries: {
    'createMemo': '''
     INSERT INTO memos(id,text) 
       SELECT :id, :text 
       WHERE NOT EXISTS(SELECT 1 FROM memos WHERE id = :id AND text = :text);
    '''
  },
)
```

which should generate a `Future<int> createMemo(int id, String text)` method. I'm not sure if moor's type inference algorithm would pick that up correctly, I'll check that tomorrow.

**Comment by knaeckeKami** [comment]
what about `ON CONFLICT IGNORE`?
https://www.sqlite.org/lang_conflict.html
You just have to make that field that you care about unique or primary key.

**Comment by simolus3** [comment]
> You just have to make that field that you care about unique or primary key.

Yeah @VadimOsovsky I would recommend to create a unique key if the column you want to check is unique. It sounds like a unique constraint would apply here, as you only write new rows if an old value doesn't exist already. If that doesn't work for you, you'd probably have to use a `customInsert` manually, or first send a select statement and then conditionally send another insert. In the next moor version, we'll have support for `ON CONFLICT IGNORE` and others in the Dart apis.

`moor_generator` doesn't infer the types from my previous reply correctly, but it should work with an `ON CONFLICT` clause. Inferring types across multiple usages of variables is a lot of work unfortunately, we'd probably have to express type constraints as a system of logical terms and SAT that. It sounds interesting to work on, but would probably a long time to get right so it's not a priority at the moment.
