### ISSUE TITLE
Broken link on documentation website - docs/example

### ISSUE THREAD

**Issue by osaxma** [simolus3/moor#2021]
Caught this broken link while reading the docs:

<img width="980" alt="Screen Shot 2022-08-27 at 6 53 53 PM" src="https://user-images.githubusercontent.com/46427323/187037909-ddd2a476-6a4b-4040-b60c-776cc5ee9e43.png">

URL: https://drift.simonbinder.eu/docs/examples/

**Comment by simolus3** [comment]
Good catch, thank you! I have updated that page in ca6758d8b1907ce0be839a527cb6626fa7e420b7.
