### ISSUE TITLE
pub get failed when installing latest version of moor

### ISSUE THREAD

**Issue by KKRoko** [simolus3/moor#203]
```
Running "flutter pub get" in appName...                            
Because appName depends on moor_flutter ^2.0.0 which depends on moor ^2.0.0, moor ^2.0.0 is required.
So, because appName is 1.0.0+1, version solving failed.

pub get failed (1)
```

**Comment by simolus3** [comment]
Is that the full error message? I can't see how pub would reject moor based on your apps version...
Is your app's name the same as some package on pub.dev by any chance?

**Comment by simolus3** [comment]
I strongly believe the problem is that you named your project "moor", which clashes with [this package](https://pub.dev/packages/moor) imported by moor_flutter.

If that's not the problem, please reply and I'll re-open this issue.

**Comment by KKRoko** [comment]
yes you're right thank you for your help
