### ISSUE TITLE
Documentation issue: Type converters

### ISSUE THREAD

**Issue by JCKodel** [simolus3/moor#2045]
There is no examples on how using `intEnum<Status>()()` on drift files.

**Comment by simolus3** [comment]
It's mentioned at the end of [this section](https://drift.simonbinder.eu/docs/advanced-features/type_converters/#using-converters-in-moor):

![image](https://user-images.githubusercontent.com/5738860/189856353-6e051f91-9f59-4875-a1a8-54673bb66f17.png)

I've also added this information to the section on supported column types in drift files to make it easier to find. 68552501cc89f87a99c78bbc7171ac0209bc90d3
