### ISSUE TITLE
How to perform upsert if certain condition between old and excluded (onConflict) is satisified?

### ISSUE THREAD

**Issue by mateoKutnjak** [simolus3/moor#2046]
I want to take in account `updated_at` column. If new object (`excluded`) has `updated_at` smaller then existing object in database, I want to ignore insert/update query. Can this be done without additional select prior to insert/update query?

```
await into(_table).insert(entry,
        onConflict: DoUpdate.withExcluded((old, excluded) {
          isInserted = false;
          return onConflictCompanion(old: old, excluded: excluded);
        }, target: [
          db.visitors.targetColumn1,
          db.visitors.targetColumn2,
        ]));
```

**Comment by simolus3** [comment]
You can use the optional `where` parameter on `DoUpdate` to determine whether the row should actually be inserted or not:

```dart
onConflict: DoUpdate.withExcluded(
  (old, excluded) => onConflictCompanion(old: old, excluded: excluded),
  target: [db.visitors.targetColumn1, db.visitors.targetColumn2],
  // Only run the update if the new row is newer than the one it is replacing
  where: (old, excluded) => excluded.updatedAt.isBiggerThan(old.updatedAt),
)
```

Btw, please be aware that the callbacks in the `DoUpdate` constructor are always executed, regardless of whether a conflict actually occurs. So setting `isInserted = false` in that callback is not a reliable way of determining whether an upsert has happened or not. Drift runs these functions to build the SQL statement to run, sqlite3 determines whether the upsert is needed or not. If you need to determine which row has been inserted, you can use `insertReturning` which would return the old row if it's newer.
