### ISSUE TITLE
How to do nested join?

### ISSUE THREAD

**Issue by mateoKutnjak** [simolus3/moor#2056]
How do I fetch data from Drift through nested join?

Let's say I have `TableA` which has one-to-many relationship with `TableB` which has one-to-many relationship with `TableC`. I would like to fetch data class of this type:

```
class TableAWithTableB {
  final TableAEntity tableAEntity;
  final TableBWithTableC nestedData;

  TableAWithTableB(
      {required this.tableAEntity,
      required this.nestedData,});
```

```
class TableBWithTableC {
  final TableBEntity tableBEntity;
  final TableCEntity tableCEntity;

 // constructor here
}
```

How do I write query function? Do I use subqueries?

```
return result.map((rows) => rows.map((row) {
          return TableAWithTableB(
              tableA: row.readTable(tableA),
              nestedData: row.readTable(???),) // how to read
        }).toList());
```

**Comment by simolus3** [comment]
I noticed you don't have any list in your result classes. So the intention is, if a row in `A` has multiple matches in `B` or `C`, that there would be multiple `TableAWithTableB` instances with the same `tableAEntity`, right?

In that case, it's pretty easy to do. You just join all three tables and then use

```dart
return TableAWithTableB(
  tableA: row.readTable(tableA),
  nestedData: TableBWithTableC(
    tableB: row.readTable(tableB),
    tableC: row.readTable(tableC)
  ),
);
```

Is that what you were looking for?
