### ISSUE TITLE
A lot of unnecessary information in the README.md

### ISSUE THREAD

**Issue by ghost** [simolus3/moor#2059]
**Is your feature request related to a problem? Please describe.**

Drift's README file contains the following points:

- Flexible: Drift lets you write queries in both SQL and Dart, providing fluent apis for both languages. You can filter and order results or use joins to run queries on multiple tables. You can even use complex sql features like WITH and WINDOW clauses.
- 🔥 Feature rich: Drift has builtin support for transactions, schema migrations, complex filters and expressions, batched updates and joins. We even have a builtin IDE for SQL!
- 📦 Modular: Thanks to builtin support for daos and imports in sql files, drift helps you keep your database code simple.
- 🛡️ Safe: Drift generates typesafe code based on your tables and queries. If you make a mistake in your queries, drift will find it at compile time and provide helpful and descriptive lints.
- ⚡ Fast: Even though drift lets you write powerful queries, it can keep up with the performance of key-value stores. Drift is the only major persistence library with builtin threading support, allowing you to run database code across isolates with zero additional effort.
- Reactive: Turn any sql query into an auto-updating stream! This includes complex queries across many tables
- ⚙️ Cross-Platform support: Drift works on Android, iOS, macOS, Windows, Linux and the web. [This template](https://github.com/simolus3/drift/tree/develop/examples/app) is a Flutter todo app that works on all platforms
- 🗡️ Battle tested and production ready: Drift is stable and well tested with a wide range of unit and integration tests. It powers production Flutter apps.

I think they're unnecessary because it is very similar to the liars like hive/getx and actually these points can be shorten to something like: "Drift is a reactive persistence library for Dart and Flutter, built on top of sqlite".

**Describe the solution you'd like**
Remove this from README

**Comment by PlugFox** [comment]
### Let's not be like these guys and rewrite the readme normally?

![telegram-cloud-photo-size-2-5267315881879388583-y](https://user-images.githubusercontent.com/7805176/190507116-53745691-d463-46ef-a323-caf8454656bb.jpg)
![telegram-cloud-photo-size-2-5267315881879388579-y](https://user-images.githubusercontent.com/7805176/190507144-c3bc348e-c1ad-4f90-b541-799b16704d2c.jpg)
![telegram-cloud-photo-size-2-5267315881879388582-y](https://user-images.githubusercontent.com/7805176/190507190-bd6d4996-0442-4d39-a0f7-778b500bfaeb.jpg)

### We can add the benefits of SQLite, such as testability and reliability
https://www.sqlite.org/testing.html

**Comment by ghost** [comment]
Closed as resolved.

**Comment by simolus3** [comment]
Is it resolved though? :D I didn't change anything, but I I don't think any of the points mentioned in the readme is dishonest. If they feel sketchy to you, could you help point out the problematic ones?

I'm not too happy with the current state of the readme either, there should probably be a short example in there highlighting the awesome things drift can do.
I also agree that there could be a stronger focus on the safety benefits provided by relational/ACID databases in general and, more specifically, drift's typesafety, testability and correctness.

**Comment by ghost** [comment]
> Is it resolved though? :D I didn't change anything, but I I don't think any of the points mentioned in the readme is dishonest. If they feel sketchy to you, could you help point out the problematic ones?
> 
> I'm not too happy with the current state of the readme either, there should probably be a short example in there highlighting the awesome things drift can do.
> I also agree that there could be a stronger focus on the safety benefits provided by relational/ACID databases in general and, more specifically, drift's typesafety, testability and correctness.
> 

Yes, it makes sense. Especially we don't want users to think that drift is the "Silver bullet". IMHO just try to focus on ease of use and sqlite benefits.
