### ISSUE TITLE
database credentials

### ISSUE THREAD

**Issue by VadimOsovsky** [simolus3/moor#206]
When I try to access a moor created database in intellij database plugin it asks for database credentials, what might they be?

**Comment by simolus3** [comment]
> When I try to access a moor created database in intellij database plugin

If you're using `moor_flutter` or `moor_ffi`, that's an unencrypted sqlite file, so there shouldn't be any credentials. The database is only encrypted with the experimental encryption database that's not available on pub.

It's pretty unusual that it would ask you about credentials for a simple sqlite file though, can you share more details on your setup? In particular, how did you obtain a database file to open in IntelliJ?

**Comment by VadimOsovsky** [comment]
@simolus3 i try to access the .sqlite file through device file explorer in debug mode. and then in intellij's standart Database plugin, I try to open the file located on my device it goes "Permission denied", I click detatils (see screenshot 1). it spits out this pop up (screenshot 2)

![Screenshot 2019-10-25 at 10 12 59](https://user-images.githubusercontent.com/39897981/67550867-360efc80-f710-11e9-8de5-8963dfc8cac5.png)
![Screenshot 2019-10-25 at 10 12 08](https://user-images.githubusercontent.com/39897981/67550877-3b6c4700-f710-11e9-9523-23675d470adf.png)

**Comment by VadimOsovsky** [comment]
And it won't let me continue with the fields being empty either
![Screenshot 2019-10-25 at 10 17 01](https://user-images.githubusercontent.com/39897981/67551100-c0576080-f710-11e9-909d-0e3da0c20f87.png)

**Comment by simolus3** [comment]
Does it work if you copy the sqlite file to your computer and open it from there? sqlite writes some additional lockfiles when opening the database, that might cause problems on a connected device.

**Comment by simolus3** [comment]
> piece of software freezes when I try to copy the file

The IntelliJ database plugin is freezing? Maybe you can use the [Android File Transfer](https://www.android.com/filetransfer/) tool? This is probably not a moor-specific thing (in the end moor creates the database file like any other Android App would)...

**Comment by VadimOsovsky** [comment]
the whole IDE freezes, I'll report to JetBrains and check your suggestion about copying the file. Thanks for help!

**Comment by simolus3** [comment]
Did you get anything back from them? I'll close this issue since it doesn't seem like moor is causing this (the database isn't encrypted, sqlite doesn't even support that out of the box). Please let me know if you have any more questions.
