### ISSUE TITLE
SELECT fieldName1, fieldName2 FROM TABLE;

### ISSUE THREAD

**Issue by phamconganh** [simolus3/moor#2061]
Can the select statement has select with field name to remove some redundant field?

**Comment by simolus3** [comment]
Yes, you can limit a query to some columns with [`selectOnly`](https://drift.simonbinder.eu/api/drift/databaseconnectionuser/selectonly). Essentially, you'd do something like:

```dart
final query = selectOnly(table)..addColumns([table.fieldName1, table.fieldName2]);
final results = await query.get();

for (final row in results) {
  final fieldName1 = row.read(table.fieldName1);
  final fieldName2 = row.read(table.fieldName2);
  // use the result here
}
```
