### ISSUE TITLE
Migration tests is failing with table with `uniqueKeys`

### ISSUE THREAD

**Issue by gianmarcocalbi** [simolus3/moor#2069]
Hello!

I have just added a new table `companion` in my DB with a unique constraint:

```dart
@override
List<Set<Column>> get uniqueKeys => [
  {diaryId, companionUuid}
];
```

If I generate and test the migration I get
```
Schema does not match
companion:
 constraints:
  Expected the table to have 0 table constraints, it actually has 1.
```

While if I comment out the `uniqueKeys` method override and regenerate the db and the migrations, the tests work fine.

I notice that the generated_migrations/schema_vXX.dart and the drift_schemas/drift_schemas_vXX.json do not change regardless having `uniqueKeys` in the table or not. Is it expected?

---

- To generate the migrations I run, in order:
  1. `dart run drift_dev schema dump lib/access/database.dart drift_schemas/`
  2. `dart run drift_dev schema generate drift_schemas/ test/generated_migrations/`
- versions:
  - drift: ^1.7.1
  - sqlparser: ^0.22.0

**Comment by simolus3** [comment]
Thanks for the detailed and helpful report! I've fixed this in the linked commit.

If you want to try it out, you can add this to your pubspec:

```yaml
dependency_overrides:
  drift_dev:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift_dev
```

Then you can re-generate the schema file with that so that the unique keys get serialized in the generated json. Afterwards, you can re-generate the schema which should fix this problem.

**Comment by gianmarcocalbi** [comment]
> Thanks for the detailed and helpful report! I've fixed this in the linked commit.
> 
> If you want to try it out, you can add this to your pubspec:
> 
> ```yaml
> dependency_overrides:
>   drift_dev:
>     git:
>       url: https://github.com/simolus3/drift.git
>       ref: develop
>       path: drift_dev
> ```
> 
> Then you can re-generate the schema file with that so that the unique keys get serialized in the generated json. Afterwards, you can re-generate the schema which should fix this problem.

@simolus3 Thank you for the quick reply!

I have migrated to drift 2.1.0 and then tried the migration with the dependency override you suggested but I am getting this error:

```
Failed to build drift_dev:drift_dev:
../../.pub-cache/git/drift-8c1a62ae1b65373d1403d80569b67cc959394d8b/drift_dev/lib/src/analyzer/session.dart:49:59: Error: Couldn't find constructor 'Spellfix1Extension'.
        if (options.hasModule(SqlModule.spellfix1)) const Spellfix1Extension(),
                                                          ^^^^^^^^^^^^^^^^^^
```

May it be that drift_dev version at `develop` is using a version of `sqlparser` (latest is 0.23.2) that does not export `Spellfix1Extension` (introduced by cd893796276547e306a47a19240c0998bf3fa91c)?

**Comment by simolus3** [comment]
Yes exactly, you would have to add a similar dependency override for the `sqlparser` package until the next release (hopefully soon 🤞)
