### ISSUE TITLE
Tests fail locally

### ISSUE THREAD

**Issue by dnfield** [simolus3/moor#2070]
Steps:

clone repo locally on macOS, run tests

Failures like:

```
00:00 +2 ~1 -1: with default options DateTime modifiers [E]                                                                                                                                                         
  SqliteException(1): no such function: unixepoch, SQL logic error (code 1)
    Causing statement: SELECT unixepoch(?, 'unixepoch', '2 days') AS "c0" FROM users;
  package:sqlite3/src/ffi/impl/exception.dart 38:3                                        throwException
  package:sqlite3/src/ffi/impl/database.dart 247:9                                        DatabaseImpl._prepareInternal
  package:sqlite3/src/ffi/impl/database.dart 149:19                                       DatabaseImpl.prepare
  package:drift/src/sqlite3/database.dart 120:27                                          Sqlite3Delegate.runSelect
  package:drift/src/runtime/executor/helpers/engines.dart 71:19                           _BaseExecutor.runSelect.<fn>
  package:drift/src/runtime/executor/helpers/engines.dart 55:20                           _BaseExecutor._synchronized
  package:drift/src/runtime/executor/helpers/engines.dart 68:26                           _BaseExecutor.runSelect
  package:drift/src/runtime/query_builder/statements/select/select_with_join.dart 223:24  JoinedSelectStatement._getRaw.<fn>
  package:drift/src/runtime/api/connection_user.dart 156:64                               DatabaseConnectionUser.doWhenOpened.<fn>
  ===== asynchronous gap ===========================
  package:drift/src/runtime/query_builder/statements/select/select_with_join.dart 216:17  JoinedSelectStatement.get
  ===== asynchronous gap ===========================
  package:drift/src/runtime/query_builder/statements/query.dart 230:13   
```

**Comment by kuhnroyal** [comment]
The `unixepoch` function was added in SQLite 3.38.0 in february - https://database.guide/sqlite-introduces-the-unixepoch-function/

You likely have an older sqlite installed. Not sure if you can update it.
I have it installed via brew and override the location in the test config.

The problem here is that the database code for the test is generated and committed based on the expectation that the correct sqlite version is available when the tests are run.

See https://drift.simonbinder.eu/docs/platforms/#macos

> For tests or using a custom sqlite3 version without sqlite3_flutter_libs, see the following section.

For the override you can check out my answer from here: https://github.com/simolus3/drift/discussions/1745#discussioncomment-2326294

**Comment by kuhnroyal** [comment]
Oh and I forgot, the answer is a bit old. On Apple Silicon you have a different brew install paths:

```dart
  if (Platform.isMacOS) {
    os = OperatingSystem.macOS;
    library = File('/usr/local/opt/sqlite/bin/sqlite3');
    if (!library.existsSync()) {
      /// On Apple Silicon the homebrew path is different
      /// This is the x86 variant
      library = File('/usr/local/homebrew/opt/sqlite/bin/sqlite3');
    }
    if (!library.existsSync()) {
      /// On Apple Silicon the homebrew path is different
      /// This is the arm64 variant which currently doesn't work
      library = File('/opt/homebrew/opt/sqlite/bin/sqlite3');
    }
  }
```

**Comment by simolus3** [comment]
Yes, this is due to what @kuhnroyal describes. Note that this is not representative of actual app behavior, since Flutter apps with a dependency on `sqlite3_flutter_libs` statically link the latest sqlite3 version. So you wouldn't see this in a Flutter integration test.

These workarounds are helpful when unit testing your app if you want to run those tests against the expected sqlite3 version. For drift itself, I think the best solution is to just skip those unit tests when running against an older sqlite3. That's also what we're doing for some features in tests for the `sqlite3` package.

**Comment by dnfield** [comment]
Is there a way that the tests could somehow not depend on the systems sqlite installation but instead have the expected one?

**Comment by dnfield** [comment]
Brew tends not to work very well for me. I can certainly otherwise update my sqlite3 install but it'd be nice if the test somehow just had the right things it needed to test against.

**Comment by simolus3** [comment]
I've skipped the failing tests in 8a8d1fce808ddec949ef644ebdc8b1089d22f5fd.

> Is there a way that the tests could somehow not depend on the systems sqlite installation but instead have the expected one?

I'm not aware of a way to make `dart test` run setup code which we'd need to do this automatically (something similar to `flutter_test_config.dart`). I think I can put a script together which should get you close though. I can configure melos to run that script after running `melos bootstrap` and I can setup a test printing out a warning if that script hasn't been run.

**Comment by dnfield** [comment]
Alternatively, a setup step could check the version of `sqlite3` and either fail at that point or set a variable that causes some tests to be skipped.

**Comment by dnfield** [comment]
Ah I see that's what you did haha

**Comment by dnfield** [comment]
Well I'm satisified as far as this bug is concerned. I now get a skip message that informs me I should try to upgrade sqlite if I want to run more tests. Feel free to re-open if you plan to do more.

**Comment by simolus3** [comment]
I've uploaded a script to download and compile a sqlite3 build that drift's test will pick up automatically. It also gives more actionable advice now.

![grafik](https://user-images.githubusercontent.com/5738860/191627236-49e94622-e052-4bc5-ac2b-b10d932a7fb4.png)

This should hopefully make it a lot easier to properly run drift's unit tests for everyone.

I've thought about running that script automatically in `melos bootstrap`, but most users probably just expect that to do a `pub get`, so running a custom script during that command feels insensitive. The tests work by default now and we have an easy and actionable way to upgrade sqlite3 without affecting anything else in the system. I think that's an improvement, thanks for filing this issue :)
