### ISSUE TITLE
Error after clone with Spellfix1Extension()

### ISSUE THREAD

**Issue by Carapacik** [simolus3/moor#2075]
In sqlparser: ^0.23.2 does not contains Spellfix1Extension(). 
https://github.com/simolus3/drift/blob/8c1a62ae1b65373d1403d80569b67cc959394d8b/drift_dev/pubspec.yaml#L30
Could you please update the package version on pub.dev and update it here?
https://github.com/simolus3/drift/blob/8c1a62ae1b65373d1403d80569b67cc959394d8b/drift_dev/lib/src/analyzer/session.dart#L49

**Comment by simolus3** [comment]
We use [melos](https://melos.invertase.dev/) to manage dependencies between different packages in this repository. So after cloning this project, you need to run `dart pub global activate melos` and `melos bootstrap` once to set up proper dependencies. Afterwards you can run the regular `pub get`.

The use of this tool is described in the [main readme](https://github.com/simolus3/drift#working-on-this-project). I wish there was a way to provide a better error message in this case, but I'm not aware of a great way to do that. If you have any ideas on how we could make this more obvious, please let me know.
