### ISSUE TITLE
Problem with enum

### ISSUE THREAD

**Issue by oarshad** [simolus3/moor#2078]
Have a table like below:
```
enum SymbolPosition {
  prefix,
  postfix
}

class AppLocalConfig extends Table {
  TextColumn get id => text().withLength(min: 1, max: 10)();

  TextColumn get data => text().withLength(min: 1, max: 200)();

  IntColumn get currencyPosition => intEnum<SymbolPosition>()();

  @override
  Set<Column<Object>>? get primaryKey => {id};
}
```
The saving of the entity works just fine. However, when retrieving, it throws the following error:

```
Unhandled Exception: Converting object to an encodable object failed: Instance of 'SymbolPosition'
```

**Comment by simolus3** [comment]
> However, when retrieving, it throws the following error:

Do you have a stack trace? It looks like that error might happen when an instance of the row class is serialized to JSON, but not when loading it from the database.

Drift does not apply type converters to json serialization by default, but you could add support for that manually:

```dart
class JsonAwareIntEnumConverter<E extends Enum> extends EnumIndexConverter<E> {
  JsonAwareIntEnumConverter(super.values);
}

class AppLocalConfig extends Table {
  TextColumn get id => text().withLength(min: 1, max: 10)();

  TextColumn get data => text().withLength(min: 1, max: 200)();

  IntColumn get currencyPosition => integer().map(const JsonAwareIntEnumConverter(SymbolPosition.values))();

  @override
  Set<Column<Object>>? get primaryKey => {id};
}
```

**Comment by oarshad** [comment]
> > However, when retrieving, it throws the following error:
> 
> Do you have a stack trace? It looks like that error might happen when an instance of the row class is serialized to JSON, but not when loading it from the database.
> 
> Drift does not apply type converters to json serialization by default, but you could add support for that manually:
> 
> ```dart
> class JsonAwareIntEnumConverter<E extends Enum> extends EnumIndexConverter<E> {
>   JsonAwareIntEnumConverter(super.values);
> }
> 
> class AppLocalConfig extends Table {
>   TextColumn get id => text().withLength(min: 1, max: 10)();
> 
>   TextColumn get data => text().withLength(min: 1, max: 200)();
> 
>   IntColumn get currencyPosition => integer().map(const JsonAwareIntEnumConverter(SymbolPosition.values))();
> 
>   @override
>   Set<Column<Object>>? get primaryKey => {id};
> }
> ```

That worked
