### ISSUE TITLE
Drift does not reload data after changing .sqlite file

### ISSUE THREAD

**Issue by henriqueArrazao** [simolus3/moor#2087]
> 1. Listen to a `.sqlite` file update using filesystem.

This does not work, although it triggers the streams it does not bring the new data, they are the same as before, and when I try to insert a register this error is thrown:
`attempt to write a readonly database, attempt to write a readonly database (code 1032)`

My code after changing the .sqlite file:
`_db.markTablesUpdated(_db.allTables);`

If I close the app and open again the data comes correctly. Am I doing something wrong?

_Originally posted by @henriqueArrazao in https://github.com/simolus3/drift/issues/1383#issuecomment-1263016908_

**Comment by simolus3** [comment]
Do you have a small repro that you could share?

Perhaps listening to FS events on the raw database file is not ideal, but I'd expect a "database locked" error instead in that case. In more recent versions of the sqlite3 package, you could also listen to table changes with a sqlite3 API but I don't know whether those propagate across different connections to the same database.

**Comment by henriqueArrazao** [comment]
> Do you have a small repro that you could share?
> 
> Perhaps listening to FS events on the raw database file is not ideal, but I'd expect a "database locked" error instead in that case. In more recent versions of the sqlite3 package, you could also listen to table changes with a sqlite3 API but I don't know whether those propagate across different connections to the same database.

I created a small project that you can run to test it, very simple with the download, sync with previous db & add button.
https://github.com/henriqueArrazao/drift_example


**Reproduction steps after it is opened:**
1. Add a todo (click one time on the '+' button);
2. Save the DB backup (click on the download button);
3. Make the current DB different from the previous by adding one more (1st step);
4. Now sync with the previous DB by clicking on the now enabled back button;
5. Here we can see that the list does not update as it should and if you try to add one more it throws an error.

**Comment by henriqueArrazao** [comment]
**Solved, the cause of the problem was the way I was replacing the .sqlite file in use**

Throwing error
`file.rename(p.join(directory.path, AppDatabase.fileName));`

Working
`file.copy(p.join(directory.path, AppDatabase.fileName));`
