### ISSUE TITLE
[develop] Error parsing insert statement CTE

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#209]
I know it's not released yet, but I was playing around with the new CTE parsing on `develop` and found an issue with this query:
```sql
CREATE TABLE foreign_keys (
  parent_table TEXT NOT NULL,
  parent_key TEXT NOT NULL,
  child_table TEXT NOT NULL,
  child_key TEXT NOT NULL
);

CREATE TABLE table_priority (
  tbl_name TEXT NOT NULL,
  priority INTEGER NOT NULL
);

_populateTablePriorities:
INSERT INTO table_priority
WITH RECURSIVE traverse(tbl_name, priority) AS (
  SELECT foreign_keys.parent_table, 0 FROM foreign_keys
  LEFT OUTER JOIN foreign_keys AS f2
  ON foreign_keys.parent_table = f2.child_table
  WHERE f2.child_table IS NULL
UNION ALL
  SELECT DISTINCT foreign_keys.child_table, traverse.priority + 1
  FROM traverse
  INNER JOIN foreign_keys
  ON foreign_keys.parent_table = traverse.tbl_name
)
SELECT * FROM traverse
GROUP BY tbl_name
ORDER BY MAX(priority);
```
```
Error running MoorGenerator
NoSuchMethodError: The setter 'parent=' was called on null.
Receiver: null
Tried calling: parent=Instance of 'InsertStatement'
```

**Comment by simolus3** [comment]
Thanks for the report - the problem is that the sqlparser package doesn't parse `WITH` clauses for selects that aren't top-level statements._Parsing_ that particular query should work now, I didn't try analyzing it yet. I'll also have to update more places where an inner select statement is used. It's good to have a more complex query to test things though :+1:

**Comment by Mike278** [comment]
Gotcha - I figured this might be a tricky one because of the weird INSERT SELECT, but looks like it was actually a pretty small code change!

**Comment by simolus3** [comment]
Yeah, to be honest I was a bit surprised to see that that's even possible (`WITH ... INSERT SELECT` vs your `INSERT WITH ... SELECT`) but it makes sense to only use the CTEs where they're actually needed. I've updated the other references to inner select statements as well, so using `WITH` clauses on inner select statements should work everywhere now.
