### ISSUE TITLE
Error on code generation

### ISSUE THREAD

**Issue by KaungZawHtet** [simolus3/moor#2096]
when i run this cmd :

`flutter pub run build_runner build --delete-conflicting-outputs`

I found this err:

```
[INFO] Generating build script...
[INFO] Generating build script completed, took 174ms

[INFO] Precompiling build script......
[WARNING] ../../../flutter/.pub-cache/hosted/pub.dartlang.org/drift_dev-2.2.0/lib/src/analyzer/session.dart:49:59: Error: Couldn't find constructor 'Spellfix1Extension'.
        if (options.hasModule(SqlModule.spellfix1)) const Spellfix1Extension(),
                                                          ^^^^^^^^^^^^^^^^^^
[INFO] Precompiling build script... completed, took 455ms

[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

This is my db file :

```dart
import 'dart:io';
import 'package:drift/native.dart';
import 'package:employee_book/data/local/entity/employee_entity.dart';
import 'package:path/path.dart' as path;
import 'package:drift/drift.dart';
import 'package:path_provider/path_provider.dart';

part 'app_db.g.dart';

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(path.join(dbFolder.path, 'employee.sqlite'));
    return NativeDatabase(file);
  });
}

@DriftDatabase(tables: [Employee])
class AppDb extends _$AppDb {
  AppDb() : super(_openConnection());

  @override
  int get schemaVersion => 1;
}

```

**Comment by simolus3** [comment]
This looks like https://github.com/simolus3/drift/issues/2092, could you check that you're on the latest version? If `pub upgrade` doesn't fix this, can you share the versions of `drift_dev` and `sqlparser` that are in your `pubspec.lock`?

**Comment by KaungZawHtet** [comment]
I don't use sqlparser. There is the only ones I use :

<img width="260" alt="Screen Shot 2022-10-08 at 8 51 31 PM" src="https://user-images.githubusercontent.com/15225530/194712255-3ec89a9f-9c7d-4024-90bd-c0410ce2de19.png">

**Comment by simolus3** [comment]
There's a transitive dependency on `sqlparser`, you'll find it in the pubspec.__lock__ file generated after you get packages.

Does changing the dependency to `drift_dev: ^2.2.0+1` fix the problem?

**Comment by KaungZawHtet** [comment]
yes, yes, yes. It works now after change to `^2.2.0+1`.
I use [pubspec assist ](https://marketplace.visualstudio.com/items?itemName=jeroen-meijer.pubspec-assist) and `^2.2.0` is the one it adds into pubspec.

**Comment by simolus3** [comment]
Hm yeah. I've retracted version 2.2.0 of `drift_dev` due to this issue, my assumption was that pub would then give you 2.2.0+1 by default.

Either way, glad to hear that it's working now!
