### ISSUE TITLE
Custom queries

### ISSUE THREAD

**Issue by wurikiji** [simolus3/moor#210]
In the document, `customXXX` methods are deprecated. But I want to execute a `select count(*) from table;` query.
For now, I use `customSelectQuery` method with dart-declared table. If I want to use `.moor` file with dart-declared table, is it possible?

**Comment by simolus3** [comment]
> In the document, `customXXX` methods are deprecated

`customSelect` and `customSelectStream` are deprecated, but you can replace them with `customSelectQuery(...).get()` or `customSelectQuery(...).watch()`, respectively. They behave exactly the same.

> If I want to use .moor file with dart-declared table, is it possible?

It only works if the Dart file imported is the one with the `@UseMoor` annotation (this is a limitation in Dart's build system). So if you had something like
```dart
// file called db.dart

class Users extends Table {...}

@UseMoor(tables: [Users], include: {'queries.moor'})
class MyDatabase extends _$MyDatabase {...}
```
and another moor file
```sql
-- file called queries.moor
import 'db.dart';

countUsers: SELECT COUNT(*) FROM users;
```

that should work, but it's rather unreliable. Until this is supported by Dart's build system, I'd recommend to use `customSelectQuery` instead.

**Comment by wurikiji** [comment]
@simolus3 Thanks a lot!
