### ISSUE TITLE
insertOnConflictUpdate return allawys 0

### ISSUE THREAD

**Issue by mstfkhazaal** [simolus3/moor#2109]
`insertOnConflictUpdate` **return allawys 0**

**Comment by simolus3** [comment]
All insert methods return the rowid of the most recently inserted row. In the case where an `insertOnConflictUpdate` does an update, no insert happens and the rowid of the _previous_ insert is returned. This can be a bit confusing, but I don't think there's a way to transparently get the rowid of an update for upserts.

You can use `insertReturning` to get the inserted or returned row back. You can check the returned id on that row.
