### ISSUE TITLE
watch() updates

### ISSUE THREAD

**Issue by wurikiji** [simolus3/moor#211]
I am using a stream `select(db).watch()`. When I `insert` new rows, the stream emits the tables as expected. But when I `update(db).write(newData)`, it does not react. I confirmed that my query affects at least 1 row. 
Is it intended? If so, how can I use a stream to watch any of `insert`, `update`, `delete` and others?

**Comment by wurikiji** [comment]
I saw the code of `moor_flutter`, and I found that this should work as expected. But it does not right now. 
I am attaching the codes in case it helps. 

```dart
import 'package:moor_flutter/moor_flutter.dart';
import 'package:singleton_class_annotation/singleton_class_annotation.dart';

part 'app_info_database.g.dart';

class AppInfos extends Table {
  TextColumn get packageName => text()();
  TextColumn get appName => text()();
  BoolColumn get enabled => boolean().withDefault(const Constant(false))();

  @override
  Set<Column> get primaryKey => {packageName};
}

@SingletonClass()
@UseMoor(
  tables: [AppInfos],
)
class AppSettingDatabase extends _$AppSettingDatabase {
  AppSettingDatabase()
      : super(FlutterQueryExecutor.inDatabaseFolder(path: 'pdbox.sqlite'));

  Stream<List<AppInfo>> getAppSettingsStream() => select(appInfos).watch();

  Future updateSetting(AppInfo info) {
    return (update(appInfos)..whereSamePrimaryKey(info)).write(info);
  }

  Future<int> getNumApps() async =>
      (await customSelectQuery('SELECT COUNT(*) as count from appInfos;')
              .getSingle())
          .readInt('count');

  Future insertNewApp(AppInfo info) async {
    bool ret = true;
    try {
      await into(appInfos).insert(info);
    } catch (e) {
      ret = false;
    } finally {}
    return ret;
  }

  Future transactionStart(Function exec) async {
    return transaction(() async {
      if (exec != null) await exec();
    });
  }

  @override
  int get schemaVersion => 1;
}
```

I get a stream using `getAppSettingsStream()`, and update a table with `updateSetting()`.

**Comment by Mike278** [comment]
Can you confirm your `updateSetting` call actually updates the database? 
```dart
Future<int> updateSetting(AppInfo info) async {
  int rowsAffected = await (update(appInfos)..whereSamePrimaryKey(info)).write(info);
  print('updateSetting affected $rowsAffected rows');
  return rowsAffected;
}
```
Enabling sql statement logging also helps when debugging: `FlutterQueryExecutor.inDatabaseFolder(path: 'pdbox.sqlite', logStatements: true)`. 

Are `getAppSettingsStream()` and `updateSetting()` being called on the same `AppSettingDatabase` instance?

**Comment by wurikiji** [comment]
Thanks @Mike278. After your comment, I found the typo which makes the app creating new instance of `AppSettingDatabase`. This problem is gone now! Appreciate!

**Comment by wurikiji** [comment]
It will be great to improve this package to be a singleton style preventing facing the issue like this.
