### ISSUE TITLE
Error when adding new column with blob (Uint8List) type.

### ISSUE THREAD

**Issue by DenisMrGnusa** [simolus3/moor#2111]
**1.** when i adding new column with blob type for my image with something like below:

`BlobColumn get logo => blob().nullable()();`

**2.** and in MigrationStrategy like:

`await migrator.addColumn(applications, GeneratedColumn<Uint8List>('logo', 'applications', true, type: DriftSqlType.blob));`

**3.** then i have error:

lib/services/moor/moor_database.g.dart:1356:9: Error: The getter '$driftBlobEquality' isn't defined for the class 'Application'.
 - 'Application' is from 'package:gnusa_developer_kit/services/moor/moor_database.dart' ('lib/services/moor/moor_database.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named '$driftBlobEquality'.
        $driftBlobEquality.hash(logo)

**Comment by simolus3** [comment]
The `moor` package should now export `drift`, which contains the [symbol you've mentioned](https://pub.dev/documentation/drift/latest/drift/$driftBlobEquality-constant.html).

Do you have any `dependency_overrides` in your pubspec? Are you on the latest version of your dependencies? To get the latest version of drift (formally `moor`), there's a [simple tool](https://drift.simonbinder.eu/docs/upgrading/#automatic-migration) to help you migrate from `moor` to `drift` which will make it easier to update.
