### ISSUE TITLE
add EnumNameConverter

### ISSUE THREAD

**Issue by clragon** [simolus3/moor#2115]
**Is your feature request related to a problem? Please describe.**
drift offers an inbuilt `EnumIndexConverter`, but I woud prefer them being stored as a String that is their name.

**Describe the solution you'd like**
Add something like
```dart
class EnumNameConverter<T extends Enum> extends TypeConverter<T, String> {
  /// All values of the enum.
  final List<T> values;

  /// Constant default constructor.
  const EnumNameConverter(this.values);

  @override
  T fromSql(String fromDb) => values.asNameMap()[fromDb]!;

  @override
  String toSql(T value) => value.name;
}
```
This relies on the dart version which introduced the enum names, but afaik drift already uses dart 2.17 so that should be fine.

**Comment by simolus3** [comment]
I like the idea, especially since we have a decent way to do this now in Dart 2.17. I think there could be a builder option to store enums as text, similar to the one we have for datetimes.

**Comment by North101** [comment]
I already use a custom version of this for my enums. It would be great to have official support. 

Instead of 
```dart
values.asNameMap()[fromDb]!;
```
Use
```dart
values.byName(fromDb);
```
