### ISSUE TITLE
Recursive SQL query only returns single result

### ISSUE THREAD

**Issue by enwi** [simolus3/moor#2119]
I am trying to get a recursive SQL query to work, which is added as a named SQL query to drift.

The query:
```sql
WITH RECURSIVE ParentCategory(p, n) AS (
  SELECT parent, name FROM category WHERE id = ?
  UNION ALL
  SELECT parent, name FROM category
  JOIN ParentCategory
  ON ParentCategory.p=category.id
)
SELECT n AS name FROM ParentCategory;
```

The table:
```sql
CREATE TABLE "category" (
	"id" INTEGER NOT NULL,
	"parent" INTEGER NULL,
	"name" TEXT NOT NULL,
	"description" TEXT NOT NULL,
	"keywords" TEXT NULL,
	PRIMARY KEY ("id"),
	CONSTRAINT "0" FOREIGN KEY ("parent") REFERENCES "category" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
```

The example database including the query can be found on [SQL Fiddle](http://sqlfiddle.com/#!5/e9913/2), which works just fine there.

Now on to my problem, essentially drift is only returning a single result from the query, where I would expect a list of 4 strings.
Maybe this can be fixed really easily and I might have missed sth.

**Comment by enwi** [comment]
I thought it was fixed using the development version, but I found that the query works for all elements in the db, except for the first one

**Comment by enwi** [comment]
Nevermind it all works just fine

**Comment by simolus3** [comment]
Did you find out what the issue was? :D

**Comment by enwi** [comment]
Yes @simolus3 as always user error 🤣 I had another query giving me the wrong category id and thought it was the recursive query not working, but in reality it was just fed the wrong data.

Thanks for this awesome library 🚀
