### ISSUE TITLE
Allow to insert multiple values (without batch/transaction)

### ISSUE THREAD

**Issue by rubenferreira97** [simolus3/moor#2123]
**Is your feature request related to a problem? Please describe.**
Currently when I try to insert a `batch.insertAll` on a table with a foreign key I must insert them in order or else it fails.

**Example:** 

I think drift is following this approach under the hood. This fails with `pragma foreign_keys = on`, since foreign keys are `IMMEDIATE` by default and not `DEFERRED` (check constraints at the end of the transaction).
```sql
CREATE TABLE Folders(
   id          INTEGER  NOT NULL PRIMARY KEY 
  ,title       VARCHAR(25) NOT NULL
  ,parentId    INTEGER REFERENCES Folders(id)  
);

BEGIN TRANSACTION;
INSERT INTO Folders(id,title,parentId) VALUES (15,'Child Folder',4);
INSERT INTO Folders(id,title,parentId) VALUES (4,'Parent Folder',NULL);
COMMIT;
```
This works:
```sql
INSERT INTO Folders(id,title,parentId) VALUES
 (15,'Child Folder',4)
,(4,'Parent Folder',NULL)
```

The equivalent dart code would be; 

```dart
final folders = [Folder.insert(15, 'Child Folder', 4), Folder.insert(4, 'Child Folder', null)];
await batch((batch) {
  batch.insertAllOnConflictUpdate(foldersTable, folders);
});
```

**Describe the solution you'd like**
Allow to insert multiple values, like `into(foldersTable).insertAll(folders)`, `into(foldersTable).insertAllOnConflictUpdate(folders)`, etc... 

Performance wise this solution should also be faster.

**Comment by simolus3** [comment]
I like the idea of having an `insertAll` convenience method that uses a batch behind the scenes. :+1: 

I don't fully understand what you were asking for with the deferred constraints though. Should drift implicitly re-order statements in a batch to get foreign keys to work? I don't think that's a good idea (or even something that could be implemented in a reliable way). I think it should be your responsibility to either use a deferred constraint or to insert values in the right order, regardless of whether you're using a batch or not.

**Comment by rubenferreira97** [comment]
> Should drift implicitly re-order statements in a batch to get foreign keys to work? 

@simolus3 No, I really think this is a bad idea as well. 

Sqlite (and others databases) supports a multiple value insert syntax like:

```sql
INSERT INTO Folders(id,title,parentId) VALUES
 (15,'Child Folder',4),
 (4,'Parent Folder',NULL)
```
https://stackoverflow.com/questions/1609637/is-it-possible-to-insert-multiple-rows-at-a-time-in-an-sqlite-database/1609688#1609688

This syntax does not care about the order of foreign keys (it only checks contraints after the whole insert, as a single transaction) and it's probably faster than a batch insert. Either `parentId` IMMEDIATE or DEFERRED works in this example.

Playground example:
```sql
pragma foreign_keys = on

CREATE TABLE Folders(
   id          INTEGER  NOT NULL PRIMARY KEY 
  ,title       VARCHAR(25) NOT NULL
  ,parentId    INTEGER REFERENCES Folders(id)  
);

/* Multiple values insert - WORKS */
INSERT INTO Folders(id,title,parentId) VALUES
 (15,'Child Folder',4),
 (4,'Parent Folder',NULL)
 
/* Multiple inserts within a single transaction - FAILS */
BEGIN TRANSACTION;
INSERT INTO Folders(id,title,parentId) VALUES (15,'Child Folder',4); /* FAILS HERE SINCE id 4 isn't available*/
INSERT INTO Folders(id,title,parentId) VALUES (4,'Parent Folder',NULL);
COMMIT;
```

Seems `drift` is going for the second implementation since it calls insert for each row (completely fine, since Batch is the main object here):
```dart
void insertAll<T extends Table, D>(
    TableInfo<T, D> table, Iterable<Insertable<D>> rows,
    {InsertMode? mode, UpsertClause<T, D>? onConflict}) {
  for (final row in rows) {
    insert<T, D>(table, row, mode: mode, onConflict: onConflict);
  }
}
```

**Comment by simolus3** [comment]
Oh! Yeah I've completely missed that point. That's a nice idea I think. However, it might be difficult to generate those statements in general. Say you have a table like this:

```sql
CREATE TABLE foo (
  a INTEGER PRIMARY KEY,
  b INTEGER
);
```

Now, let's say you do something like this in Dart

```dart
into(foo).insertAll([
  FooCompanion(a: Value(2), b: Value(3)),
  FooCompamion(b: Value(3))
]);
```

This would generate two different insert statements (one with two columns, one with just one). I don't think we can combine these into a single statement. We could try to find the cases where we can and then do that as an optimization, but:

> Performance wise this solution should also be faster.

It's hard to say for sure without running a benchmark, but I'm not sure if this is really true. If you're inserting lots of data like this, we'd generate a very large SQL statement if we combined everything into one `INSERT`. So the parsing cost of this may be higher than in a batch. In a batch, we'll only compile the short insert statement once and then run the compiled statement multiple times.

However, I also see the benefit of not having to care about statement ordering. There's the [`defer_foreign_keys`](https://www.sqlite.org/pragma.html#pragma_defer_foreign_keys) pragma which can be used to make all foreign key constraints deferred inside a single transaction. You can probably use that as a custom statement in a batch.

If that works, I'm happy to add a `insertAll` convenience method that starts a batch, enables deferred keys, and finally runs each insert as a logically separate statement in that batch.

**Comment by simolus3** [comment]
I've added a utility method for this in f09322aeb564f66f084150d94305faa2178c2e17. So in the next version, you'll be able to use `foo.insertAll([...])`. The order in which you pass the rows does not matter here.

For multiple tables, I recommend using `pragma defer_foreign_keys = on` manually in a batch or a transaction.
