### ISSUE TITLE
A column with default null value is still NOT NULL

### ISSUE THREAD

**Issue by ShahoodulHassan** [simolus3/moor#2127]
Hi,

If we set the default value of a column to NULL with `.withDefault(const Constant(null))`, we still have to explicitly make the column nullable with `.nullable()`. Shouldn't a column having default value of null be set as nullable automatically?

**Comment by simolus3** [comment]
We need to determine nullability at compile time, but the parameter to `withDefault` can be any dynamic expression. So unfortunately I don't think we can reliably detect this case and make the column nullable.

I also think it's less surprising to only make columns nullable if they are explicitly declared as such. As database schemas are hard to change later (relatively speaking), I don't think we should be looking at default constraints to determine the column's full type.
