### ISSUE TITLE
Custom SQL query

### ISSUE THREAD

**Issue by eitanaviv** [simolus3/moor#213]
Hi there,
Any way of making a custom SQL query and return a string or dynamic value?

For example:
`SELECT ? FROM ?` - passing `email` as first parameter and `user` as second parameter.
I'm trying to make dynamic queries according to parameters I'm extracting from a string from a server with a REGEX pattern - `${user.email}`.

Thank you!

**Comment by simolus3** [comment]
Sadly, those kind of constructions aren't supported by sqlite, the underlying database engine. Those variables (`?` in sql) can only be used for expressions. Both column and table names aren't expressions.

What you can do is call `customSelectQuery` manually and construct the string in there. So for instance
```dart
Future<List<String>> loadColumnFromTable(String column, String table) {
  final query = 'SELECT $column FROM $table';
  return customSelectQuery(query)
     .map((row) => row.readString(column))
     .get();
}
```

That should work, but I advise you to be very careful with [sql injection](https://www.w3schools.com/sql/sql_injection.asp) vulnerabilities that could happen when constructing sql queries at runtime.

**Comment by eitanaviv** [comment]
Wow, thanks for the fast reply!!
