### ISSUE TITLE
Log statement listener

### ISSUE THREAD

**Issue by ebelevics** [simolus3/moor#2132]
**Is your feature request related to a problem? Please describe.**
While NativeDatabase(..., **logStatements**) is great feature itself, I would like see is there a possibility to add a listener to DB statements. Problem lies, if I want to log these DB statement in file or send to BE service, I can't find clear way to do it.

**Describe the solution you'd like**
For example, Dio package (https://pub.dev/packages/dio) allows you to add interceptors to listen to onRequest, onResponse, onError calls. Bloc package (https://pub.dev/packages/bloc) allows you to add BlocObserver to listen to its states. But for Drift Sqlite DB solution, seems like there is none for SQLite raw query or I just couldn't find it

**Comment by simolus3** [comment]
You can set `driftRuntimeOptions.debugPrint` to a callback you chose, which can be used to intercept or log these debug statements.

If you want to properly log statements, I recommend writing a custom `QueryExecutor` that wraps a drift implementation with your own logging logic, e.g.

```dart
abstract class _LoggingExecutor extends QueryExecutor {
  QueryExecutor get inner;

  @override
  SqlDialect get dialect => inner.dialect;

  @override
  TransactionExecutor beginTransaction() {
    // todo: log
    return _LoggingTransactionExecutor(inner.beginTransaction());
  }

  @override
  Future<void> runBatched(BatchedStatements statements) {
    // todo: log
    return inner.runBatched(statements);
  }

  @override
  Future<void> runCustom(String statement, [List<Object?>? args]) {
    // todo: log
    return inner.runCustom(statement, args);
  }

  @override
  Future<int> runDelete(String statement, List<Object?> args) {
    // todo: log
    return inner.runDelete(statement, args);
  }

  @override
  Future<int> runInsert(String statement, List<Object?> args) {
    // todo: log
    return inner.runInsert(statement, args);
  }

  @override
  Future<List<Map<String, Object?>>> runSelect(
      String statement, List<Object?> args) {
    // todo: log
    return inner.runSelect(statement, args);
  }

  @override
  Future<int> runUpdate(String statement, List<Object?> args) {
    // todo: log
    return inner.runUpdate(statement, args);
  }

  @override
  Future<void> close() {
    // todo: log
    return inner.close();
  }

  @override
  Future<bool> ensureOpen(QueryExecutorUser user) {
    // todo: log
    return inner.ensureOpen(user);
  }
}

class LoggingQueryExecutor extends _LoggingExecutor implements QueryExecutor {
  @override
  QueryExecutor inner;

  LoggingQueryExecutor(this.inner);
}

class _LoggingTransactionExecutor extends _LoggingExecutor
    implements TransactionExecutor {
  @override
  final TransactionExecutor inner;

  _LoggingTransactionExecutor(this.inner);

  @override
  Future<void> rollback() {
    // todo: log
    return inner.rollback();
  }

  @override
  Future<void> send() {
    // todo: log
    return inner.send();
  }

  @override
  bool get supportsNestedTransactions => inner.supportsNestedTransactions;
}
```

Then, use a `LoggingQueryExecutor(LazyDatabase(...))` or a `LoggingQueryExecutor(NativeDatabase())` instead of the original database.

**Comment by ariefwijaya** [comment]
I've tried `driftRuntimeOptions.debugPrint` but it doesn't work. It still printout the log using default `print` @simolus3 
<img width="1126" alt="image" src="https://user-images.githubusercontent.com/24664153/217692732-2dfdeddf-5036-4457-afc1-b3642d65e4e7.png">
