### ISSUE TITLE
Build error on Windows, gradle failing

### ISSUE THREAD

**Issue by Dev-Owl** [simolus3/moor#2140]
Since today, our build is breaking with the below error. We did not change any dependency, nevertheless after some tinkering we found moving the` sqlite3_flutter_libs` package back to `0.5.10` (from  `0.5.11`)  prevents the issue.  
I hope this is the right place to report this, any assistance is appreciated. 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sqlite3_flutter_libs:extractReleaseAnnotations'.
> Error while evaluating property 'hasAndroidAnnotations' of task ':sqlite3_flutter_libs:extractReleaseAnnotations'
   > Could not resolve all artifacts for configuration ':sqlite3_flutter_libs:releaseCompileClasspath'.
      > Failed to transform sqlite3-native-library-3.39.4.jar (eu.simonbinder:sqlite3-native-library:3.39.4) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
         > Could not find sqlite3-native-library-3.39.4.jar (eu.simonbinder:sqlite3-native-library:3.39.4).
           Searched in the following locations:
               https://repo.maven.apache.org/maven2/eu/simonbinder/sqlite3-native-library/3.39.4/sqlite3-native-library-3.39.4.jar

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by Dev-Owl** [comment]
Little update, build was fixed as described above BUT now we get runtime errors for type casting from the compiled APK. I'm uncertain if its related, getting the impression I can't trust the build server anymore ;) 

`type '_Smi' is not a subtyoe of 'string' in type cast`

**Comment by RoarGronmo** [comment]
Ran into same issue: 
![image](https://user-images.githubusercontent.com/11217296/200657383-89b1bca6-3345-4825-b197-388c232502bf.png)

Just checked  this site: 
https://repo.maven.apache.org/maven2/eu/simonbinder/sqlite3-native-library/3.39.4/

it seems that the mentioned file in the error `sqlite3-native-library-3.39.4.jar` doesn't exist there.

![image](https://user-images.githubusercontent.com/11217296/200657790-faa3138b-668c-4e0a-a056-c8dcb98e1a6f.png)

...but thats a little bit strange, since I cannot see similar file in the other versions either... ...not that I know how this library is assembled.

**Comment by Dev-Owl** [comment]
@RoarGronmo we did exactly the same like you and asked us the same question 😅 I hope somebody else has an idea.. would love to get my Jenkins back to live

**Comment by simolus3** [comment]
> we found moving the sqlite3_flutter_libs package back to 0.5.10 (from 0.5.11) prevents the issue.

Yup, something went wrong publishing the new native artifact to maven central. I have retracted 0.5.11 from pub.dev in the meantime.

> `type '_Smi' is not a subtyoe of 'string' in type cast`

I don't think this is related.

**Comment by RoarGronmo** [comment]
Saw that now, removed and reintroduced `sqlite3_flutter_libs` and it "downgraded" to `0.5.10` from `0.5.11`.

Works fine now.

@Dev-Owl I think you need just to do `flutter pub upgrade` to fix, am I right @simolus3 ?.

**Comment by simolus3** [comment]
Should work with `sqlite3_flutter_libs` version `0.5.11+1`, which I've just released. If you're running into more issues, please let me know.

Apologies again for the inconvenience!

**Comment by Dev-Owl** [comment]
@simolus3  No worries, will check our infrastructure tomorrow morning. Thanks a lot for the quick reply and the work in general 👍

**Comment by Dev-Owl** [comment]
Confirmed, all is good now  👍 

The other error seems to come from a change in code generation and is not related to Drift.
