### ISSUE TITLE
I cloned the current repo and I cannot build the example app.

### ISSUE THREAD

**Issue by dkumamoto** [simolus3/moor#2143]
**Describe the bug**

Example app will not build.  I'm using Android Studio Dolphin 2021.3.1 Patch 1. (built on Sep 30, 2022).  I'm running on macOS 12.6.1 on Apple Silicon. I cloned the repo, and opened the project found in path drift/examples/app and tried to build and run.  I get:

```
Running "flutter pub get" in app...
The current Dart SDK version is 2.16.2.

Because go_router >=0.2.0 <4.0.0 depends on flutter_web_plugins from sdk which depends on js 0.6.3, go_router >=0.2.0 <4.0.0 requires js 0.6.3.
And because sqlite3 >=1.6.0 <1.7.1 depends on js ^0.6.4 and sqlite3 >=1.7.1 requires SDK version >=2.17.0 <3.0.0, go_router >=0.2.0 <4.0.0 is incompatible with sqlite3 >=1.6.0.
So, because app depends on both go_router ^3.0.6 and sqlite3 ^1.7.0, version solving failed.
pub get failed (1; So, because app depends on both go_router ^3.0.6 and sqlite3 ^1.7.0, version solving failed.)
```

Any help would be appreciated.  Thanks.

**Comment by simolus3** [comment]
> The current Dart SDK version is 2.16.2.

The problem is very likely that you have an outdated Flutter version. For me, the latest state on `develop` builds just fine with Flutter 3.3.7.
