### ISSUE TITLE
 Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null) #0      PathProviderApi.getApplicationDocumentsPath (package:path_provider_ios/messages.g.dart:108:7) <asynchronous suspension> #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:115:24) <asynchronous suspension>

### ISSUE THREAD

**Issue by lucasjinreal** [simolus3/moor#2150]
```
 Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
#0      PathProviderApi.getApplicationDocumentsPath (package:path_provider_ios/messages.g.dart:108:7)
<asynchronous suspension>
#1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:115:24)
<asynchronous suspension>
```

code

```
LazyDatabase _openConnection() {
  // the LazyDatabase util lets us find the right location for the file async.
  return LazyDatabase(() async {
    // put the database file, called db.sqlite here, into the documents folder
    // for your app.
    // final dbFolder = await getApplicationDocumentsDirectory();
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'chat.sqlite'));
    if (!await file.exists()) {
      print('!!!!!!!!!!!!! sql not exist! create it.');
      dbFolder.create();
    }
    return NativeDatabase(file);
  });
}
```

specifically on iOS

**Comment by simolus3** [comment]
This doesn't seem to be related to drift - it's a call to `getApplicationDocumentsDirectory` that is failing. This API is provided by the `path_provider` package.

- If you're setting up the drift database before calling `runApp`, please call `WidgetsFlutterBinding.ensureInitialized()` first.
- If you're doing this setup in a background isolate, please note that platform channels are not available there. Instead, try the setup described [here](https://drift.simonbinder.eu/docs/advanced-features/isolates/#initialization-on-the-main-thread) and use the platform channel on the main isolate.

**Comment by lucasjinreal** [comment]
@simolus3 hello, thnaks for your information.

I just got with this legacy error using LazyDatabase, to be honest speacking, I don't know how to modify it, (upgrade)

```

LazyDatabase _openConnection() {
  // the LazyDatabase util lets us find the right location for the file async.
  return LazyDatabase(() async {
    // put the database file, called db.sqlite here, into the documents folder
    // for your app.
    // final dbFolder = await getApplicationDocumentsDirectory();
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'chat.sqlite'));
    if (!await file.exists()) {
      print('!!!!!!!!!!!!! sql not exist! create it.');
      dbFolder.create();
    }
    return NativeDatabase(file);
  });
}

@DriftDatabase(
    tables: [Contacts, Users, Messages, Invitations, UsersUranus],
    daos: [UserDao, ContactDao, MessageDao, InvitationDao, UserUranusDao])
class MyDatabase extends _$MyDatabase {
  static MyDatabase? _instance;
  static MyDatabase? instance() {
    if (_instance == null) {
      _instance = MyDatabase._();
    }
    return _instance;
  }

// we tell the database where to store the data with this constructor
  MyDatabase._() : super(_openConnection());

  // you should bump this number whenever you change or add a table definition. Migrations
  // are covered later in this readme.
  @override
  int get schemaVersion => 2;
}
```

this code, actually, work pretty well previously, but recently I upgraded flutter and keeping get above errors.

How should I make a minimal modification to make the error go away and work? (I don't know how to replace LazyeDatabase with DatabaseConnection0

**Comment by simolus3** [comment]
Where are you first using the database? That's the place where `getApplicationDocumentsDirectory()` will get called. Can you guarantee that this is after `runApp` has been called?

I don't think there's anything wrong with that code. It should work if you're on a isolate where Flutter has been initialized.

**Comment by lucasjinreal** [comment]
@simolus3 Hi, as you can see, this `**getApplicationDocumentsDirectory()**` is called right after the `MyDatabase` class initialized, the MyDatabase class is created along with the app start.

**Comment by simolus3** [comment]
It doesn't really matter where the `MyDatabase` class is getting instantiated. A `LazyDatabase` will run the callback when the database is first _used_ (e.g. a query is sent).

Flutter should also give you a warning for this, but it is important to either call `runApp` before using the database or to call `WidgetsFlutterBinding.ensureInitialized()` as a first line in your `main()`. Can you check that you're doing that?

**Comment by lucasjinreal** [comment]
@simolus3  Do I still need the above code if I have  `WidgetsFlutterBinding.ensureInitialized()` before runAPP?

**Comment by lucasjinreal** [comment]
@simolus3  hello, I tried this but it was not work!

```
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}
```

can u please give me more specific advice??

**Comment by simolus3** [comment]
I assumed that it should work with that snippet.

Do you get the same error with the example app from this project? https://github.com/simolus3/drift/tree/develop/examples/app I'm trying to figure out if there's more to consider that I could have forgotten.
