### ISSUE TITLE
the primaryKey and unique do not work

### ISSUE THREAD

**Issue by cruvie** [simolus3/moor#2151]
the table like this 
```dart 

class Messages extends Table {
  TextColumn get id => text()();

  TextColumn get fromId => text()();

  TextColumn get toId => text()();

  Int64Column get sendTime => int64().unique()();

  Int64Column get readTime => int64()();

  TextColumn get type => text()();

  TextColumn get content => text()();

  @override
  Set<Column> get primaryKey => {id};

}

```

it should be error when I insert the same "id" or "sendTime" ,but it works fine
```dart 

  await DBUtil.db.into(DBUtil.db.messages).insert(MessagesCompanion.insert(
      id: "1",
      fromId: "2",
      toId: "33",
      sendTime: BigInt.from(232),
      readTime: BigInt.from(123),
      type: "232",
      content: "232"));
  // Simple select:
  List<Message> msg;
  msg = await DBUtil.db.select(DBUtil.db.messages).get();
  for (var element in msg) {
    debugPrint(element.toString());
  }

```

the output

```

Performing hot restart...
Syncing files to device iPhone 14 Pro Max...
Restarted application in 271ms.
flutter: Message(id: 1, fromId: 2, toId: 33, sendTime: 232, readTime: 123, type: 232, content: 232)
flutter: Message(id: 1, fromId: 2, toId: 33, sendTime: 232, readTime: 123, type: 232, content: 232)

```

**Comment by simolus3** [comment]
When I add your exact table to my database and run the insert twice, I get this error: `UNIQUE constraint failed: messages.id, constraint failed (code 1555)`. So it seems like it's working in general.

Did you add the `primaryKey` and `unique` constraints later (i.e. after already running the application with a version of the table that didn't include them)? In that case, you need to write a [migration](https://drift.simonbinder.eu/docs/advanced-features/migrations/) for it. Otherwise, these constraints are not visible in the database. Could you post the results of this to help me diagnose this?

```dart
  final test = await DBUtil.db
      .customSelect("SELECT sql FROM sqlite_schema WHERE name = 'messages'")
      .getSingleOrNull();
  print(test?.read<String>('sql'));
```

**Comment by cruvie** [comment]
> When I add your exact table to my database and run the insert twice, I get this error: `UNIQUE constraint failed: messages.id, constraint failed (code 1555)`. So it seems like it's working in general.
> 
> Did you add the `primaryKey` and `unique` constraints later (i.e. after already running the application with a version of the table that didn't include them)? In that case, you need to write a [migration](https://drift.simonbinder.eu/docs/advanced-features/migrations/) for it. Otherwise, these constraints are not visible in the database. Could you post the results of this to help me diagnose this?
> 
> ```dart
>   final test = await DBUtil.db
>       .customSelect("SELECT sql FROM sqlite_schema WHERE name = 'messages'")
>       .getSingleOrNull();
>   print(test?.read<String>('sql'));
> ```

thanks, you are right I have changed the table column but didn't migrate it ,I try this 
```dart 

      final m = Migrator(DBUtil.db);
        await m.deleteTable(DBUtil.db.messages.actualTableName);
        await m.createTable(DBUtil.db.messages);

```
 It words right ;

AND I think it is better to alter the table automatically while  run ` flutter pub run build_runner build` ,which means I am sure to change the table. If there's any wrong with the existing data it should gives the exception, if no it should alter the table directly
