### ISSUE TITLE
createFunction stub in .drift files?

### ISSUE THREAD

**Issue by North101** [simolus3/moor#2156]
Custom functions can't be used in .drift files. Is it possible to add a createFunction stub to allow their use?

Maybe something like:
```
CREATE STUB my_function(arg1 AS TEXT, arg2 AS INT);
```

**Comment by simolus3** [comment]
I like the idea of specifying custom functions. The same pattern could apply to virtual tables or table-valued functions.

I'm not fully sure about the right way to expose this functionality though. Maybe it could also be a simpler json or yaml file doing the configuration. Perhaps the configuration should also just be part of the regular builder options, similar to how json1 and fts5 are enabled today. That might also be simpler to implement in the generator.

**Comment by North101** [comment]
json / yaml (probably yaml as dart already uses yaml for configuration?) sounds ok to me.

I was thinking it could also generate a wrapper as well:

```
void createMyFunction(sqlite3.CommonDatabase db, String Function(String arg1, int arg2) function) {
  db.createFunction(
    functionName: 'my_function',
    function: (args) => function(args[0] as String, args[1] as int),
    argumentCount: const sqlite3.AllowedArgumentCount(2),
    deterministic: true,
    directOnly: false,
  );
}

NativeDatabase(
  filename,
  setup: (db) {
    createMyFunction(db, (arg1, arg2) {
      return '';
    });
  },
);
```

**Comment by North101** [comment]
Just to make sure. There is currently no way to use custom functions in .drift files?

Would something like
```
SELECT custom('my_function', ...);
```

Work in the mean time?

**Comment by North101** [comment]
With the modular generation I can use custom functions though drift will still complain and assume the return value is a string.

**Comment by simolus3** [comment]
I've added support for custom functions. When modular code generation is enabled, we also generate an extension to easily register these functions on a database.

At the moment, this is only supported in the modular generation mode because we need to add an import to the generated code for this, something we can't do with part files.
