### ISSUE TITLE
Allow shutting down DriftIsolate from QueryExecutor

### ISSUE THREAD

**Issue by clragon** [simolus3/moor#2157]
**Is your feature request related to a problem? Please describe.**
`NativeDatabase` allows us to call `close` which will then close and release all resources associated with it.
This is not the case when we are using a `DriftIsolate` to spawn a server and connect to it.

In my code, the shortcut function I made to open and connect to a `DriftIsolate` database looks something like this:

```dart
DatabaseConnection connectDatabase(String name) => DatabaseConnection.delayed(
      _createDriftIsolate(name).then((e) => e.connect()),
    );
```

Note how the `DriftIsolate` never leaves the function, only the `DatabaseConnection`.
In my app, I am normally do not have multiple isolates that would access my drift database, nor would I pass it to other isolates* so they could access it. I am using my database in an isolate only for performance reasons, it is otherwise treated exactly like a `NativeDatabase`, that is only ever opened from one place and then closed again.

However, this style of usage isnt exactly supported currently.

**Describe the solution you'd like**
It would be nice to either signal that I would like to kill the isolate when closing my connection (as a parameter), 
or signal that the isolate should be killed once the first (or all?) connection is closed when creating the isolate.

This of course demands caution from the user as killing the isolate when other connections are open would be undesirable.

---
*I havent seen any way of signaling that you would like to reuse the existing isolate from other isolates without passing it around.

**Comment by simolus3** [comment]
Nice call, I like the idea! I've added a `shutdownOnClose` parameter which can be used to shutdown the whole isolate after closing the single connection.
