### ISSUE TITLE
Insert statement being called when updating a row

### ISSUE THREAD

**Issue by nickolasdeluca** [simolus3/moor#2159]
**Describe the bug**

This is the code I wrote for a function within my app. What it should do: whenever I press on one of the actions of my app's home screen, it should write on this table called `RecentActions` the name of the action and the count of usages, the latter being increased every time.

``` dart
try {
  RecentAction recentAction =
      await Database().getRecentActionByName(identifier);

  RecentActionsCompanion entity = RecentActionsCompanion(
    id: drift.Value(recentAction.id),
    name: drift.Value(recentAction.name),
    count: drift.Value(recentAction.count + 1),
  );

  Database().updateRecentAction(entity);
} on StateError {
  RecentActionsCompanion entity = RecentActionsCompanion(
    name: drift.Value(identifier),
    count: const drift.Value(1),
  );
  Database().insertRecentAction(entity);
}
```

As I was testing it, I came across a `StateError`, when the element didn't exist to begin with. So I wrote a catch to my function that inserts the record whenever it didn't exist. After that, my problem with the `StateError` was solved and I moved along with my tests.

Then, I came across this issue, where, sometimes, the `updateRecentAction` function will throw an error: 
```
SqliteException (SqliteException(1555): UNIQUE constraint failed: open_connections.database_pointer, constraint failed (code 1555)
  Causing statement: INSERT INTO open_connections VALUES (?, ?))
```

I see this as an error, because there should be no way of an insert being called when I'm trying to update a record.

Here is the code for the `updateRecentAction` function:
``` dart
Future<bool> updateRecentAction(RecentActionsCompanion entity) async {
  return await update(recentActions).replace(entity);
}
```

Can anyone shed some light on this issue? 
Am I missing something? 
Am I doing something wrong?
<sub>(it could be, since I just recently started messing with drift) (great ORM by the way)</sub>

Also, I should clarify that I did debug my function end the error was being thrown by the `updateRecentAction` method.

**Comment by North101** [comment]
The state error is probably from the `getRecentActionByName` function. If you are using `getSingle()` then it will error if there are no entities or more than 1. You could replace this with `getSingleOrNull` and it'll instead return `null` if there are no entities.

However, looking at your code, i think the best way to handle this is to replace the whole code with an insert `onConflict` instead:
```dart
db.into(db.recentActions).insert(RecentActionsCompanion.insert(
    name: Value(identifier),
    count: const Value(1),
  ), onConflict: DoUpdate((old) => RecentActionsCompanion.custom(
    count: old.count + const Constant(1),
  )));
```

This will attempt to insert the row into the database and (assuming that `name` has to be unique) if there is a conflict then it will instead run the update.

**Comment by simolus3** [comment]
I agree with what @North101 said about using an `onConflict` clause to combine the write with an conditional update. However,

> `SqliteException (SqliteException(1555): UNIQUE constraint failed: open_connections.database_pointer, constraint failed (code 1555)`

This is probably a bug in drift. `open_connections` is an internal database drift uses to properly close databases upon hot restarts. Now that we have finalizers in Dart, it's probably best to just get rid of this functionality.

You're doing `Database()` for every statement. Is this a factory returning a singleton instance or are you creating a new instance of your database class every time? I strongly recommend using a singleton (well, managed in some maintainable approach like `provider`, `riverpod` or `get_it` to properly dispose it) for efficiency. Creating a new instance for every operation has a lot of overhead. It's also likely to cause this problem, although I blame that error on drift ;)

**Comment by simolus3** [comment]
Should be fixed in the linked commit. That said, my recommended solution is to not open the database multiple times. If you need more pointers on how to manage a drift database instance (where to open and close it), please let me know and I'll be happy to help!

**Comment by nickolasdeluca** [comment]
> The state error is probably from the `getRecentActionByName` function. If you are using `getSingle()` then it will error if there are no entities or more than 1. You could replace this with `getSingleOrNull` and it'll instead return `null` if there are no entities.
> 
> However, looking at your code, i think the best way to handle this is to replace the whole code with an insert `onConflict` instead:
> 
> ```dart
> db.into(db.recentActions).insert(RecentActionsCompanion.insert(
>     name: Value(identifier),
>     count: const Value(1),
>   ), onConflict: DoUpdate((old) => RecentActionsCompanion.custom(
>     count: old.count + const Constant(1),
>   )));
> ```
> 
> This will attempt to insert the row into the database and (assuming that `name` has to be unique) if there is a conflict then it will instead run the update.

I'll try your suggestion, thanks a lot! I found lots of source material on how to implement basic stuff with drift, sadly there are few that show us how to do this "properly".

**Comment by nickolasdeluca** [comment]
> I agree with what @North101 said about using an `onConflict` clause to combine the write with an conditional update. However,
> 
> > `SqliteException (SqliteException(1555): UNIQUE constraint failed: open_connections.database_pointer, constraint failed (code 1555)`
> 
> This is probably a bug in drift. `open_connections` is an internal database drift uses to properly close databases upon hot restarts. Now that we have finalizers in Dart, it's probably best to just get rid of this functionality.
> 
> You're doing `Database()` for every statement. Is this a factory returning a singleton instance or are you creating a new instance of your database class every time? I strongly recommend using a singleton (well, managed in some maintainable approach like `provider`, `riverpod` or `get_it` to properly dispose it) for efficiency. Creating a new instance for every operation has a lot of overhead. It's also likely to cause this problem, although I blame that error on drift ;)

I'll make changes to comply with your suggestion as well. Thank you! 
As I said, I barely began working with drift, it's all new to me, your suggestion means a lot.
