### ISSUE TITLE
Transactions can't be started in the before open callback

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#216]
I'm trying to insert into two tables after the database is opened. The inserts need to be one atomic operation so I'm using a transaction, but moor is throwing this exception. How come this is a restriction? Can it be removed?

**Comment by simolus3** [comment]
Yeah the restriction is pretty artificial, this should be supported on all backends. In the old times we used some callback from `sqflite` where (if I remember correctly) we couldn't start transactions. We now have a different implementation that doesn't require that restriction, I'll see if it can be lifted.

**Comment by Mike278** [comment]
Sweet, thanks so much Simon!
