### ISSUE TITLE
Watching customSelectQuery only emits once

### ISSUE THREAD

**Issue by siegesmund** [simolus3/moor#217]
I have a SQL query that I am using customSelectQuery(Query).watch() to try to watch for database changes. The generated stream only emits one event, when it is initialized. I can verify by looking at the SQLite database that changes have taken place to the table. There are just no change events being emitted.

I'm a little stumped. I've reviewed the docs and examples. 
1) Would this be related to any limitation that I may have missed in the docs?
2) Is this a known issue (watching a customSelectQuery query)?

**Comment by simolus3** [comment]
Are you setting the `tables` parameter on the call to `customSelectQuery`? It's required for auto-updating streams to work. The way those streams are implemented is that each update is supposed to signal which tables it's going to affect, so we can use that information to reload the query when the underlying data changes.

If you use compiled select statements, either by putting them in a [moor file](https://moor.simonbinder.eu/docs/using-sql/moor_files/) or in the [`queries`](https://moor.simonbinder.eu/docs/using-sql/custom_queries/#statements-with-a-generated-api) parameter of a `@UseMoor` annotation, the compiler should infer what tables you're reading from and do this automatically. We could do that at runtime, but the additional overhead and code size doesn't justify that in my opinion.

**Comment by siegesmund** [comment]
I am using Dart objects that extend Table to define my tables. This approach isn't compatible with using .moor files, so for the moment need to use customSelectQuery. 

Regarding the 'tables' parameter: This is the signature for customSelectQuery. 

`Selectable<QueryRow> customSelectQuery(String query,                                        {List<Variable<dynamic, SqlType<dynamic>>> variables = const [],                                        Set<TableInfo<Table, DataClass>> readsFrom = const {}})`

Do you mean the readsFrom parameter? When I use that, I don't even get the first event, on initialization.

**Comment by simolus3** [comment]
> Do you mean the `readsFrom` parameter?

Sorry - yeah, that's the parameter I meant
> When I use that, I only get the first event.

That sounds like a bug in moor. To help diagnose this, can you provide more details on how you use the streams? In particular, are you just passing them to a `StreamBuilder` or are you listening to them manually? Are you applying transformers to the stream, etc. If you could construct a simple reproduction that would be perfect, but anything helps.

**Comment by siegesmund** [comment]
Ok, let me see if I can reproduce it in a simpler context. I may have to do that on the weekend. Also, FWIW, the SQL query is a nested select query (both queries on the same table) in case that is a part of the problem.
