### ISSUE TITLE
Error: The argument type 'String' can't be assigned to the parameter type 'void Function(GenerationContext)?'.  - 'GenerationContext' 

### ISSUE THREAD

**Issue by JeffTyfoom** [simolus3/moor#2173]
Sample Table:

```dart

class SampleTable extends Table {
  IntColumn get id => integer()();

  DateTimeColumn get updatedAt => dateTime()();

  BoolColumn get videoCaching => boolean().nullable()();

  @override
  Set<Column> get primaryKey => <Column>{id};
}

```

Generated code that cause the error

```dart
@override
  late final GeneratedColumn<bool> videoCaching = GeneratedColumn<bool>(
      'video_caching', aliasedName, true,
      type: DriftSqlType.bool,
      requiredDuringInsert: false,
      defaultConstraints: 'CHECK ("video_caching" IN (0, 1))');
      
 ```     
 
 Compile Error
 
 lib/persistent/cache_database.g.dart:6292:27: Error: The argument type 'String' can't be assigned to the parameter type 'void Function(GenerationContext)?'.
 - 'GenerationContext' is from 'package:drift/src/runtime/query_builder/query_builder.dart' ('../../../.pub-cache/hosted/pub.dev/drift-2.3.0/lib/src/runtime/query_builder/query_builder.dart').
      defaultConstraints: 'CHECK ("video_caching" IN (0, 1))');
      
 ## Version
      2.3.0

**Comment by simolus3** [comment]
I've created a new project depending on `drift` and `drift_dev` version 2.3.0 - everything generated as it should.

Could you make sure that you've re-run the generator with `build_runner build` after the upgrade? For reference, this is what the generated code looks like for me:

```dart
          defaultConstraints: GeneratedColumn.constraintsDependsOnDialect({
            SqlDialect.sqlite: 'CHECK ("video_caching" IN (0, 1))',
            SqlDialect.mysql: '',
            SqlDialect.postgres: '',
          }));
```

**Comment by JeffTyfoom** [comment]
@simolus3  yeah you're right, I'm sorry I forgot to re-run the code generator after I updated the package. Sorry for the inconvenience.
