### ISSUE TITLE
tables names in drift files can't be found when upgrading drift 2.2.0 -> 2.3.0 (drift_dev 2.2.0+1 -> 2.3.2)

### ISSUE THREAD

**Issue by em6m6e** [simolus3/moor#2178]
I define the database tables in dart files like this:
```
@DataClassName('DFoo')
class FooTable extends Table {
  @override
  String get tableName => 'foo';

  IntColumn get fooId => integer()();
}
```
and use drift files for some queries:
```
import 'database.dart';

selectAll: SELECT * FROM foo;
```
It worked fine with drift 2.2.0 and when I upgraded to drift 2.3.0 I got errors like:
```
[WARNING] drift_dev on lib/models/db/foo.drift:
line 12, column 26: `foo` could not be found in any import.
```

**Comment by simolus3** [comment]
Thanks for the report. I've tried to reproduce this, but unfortunately couldn't. I've pushed a [small project](https://github.com/simolus3/drift/tree/reproduce-2178/examples/issue2178) with a drift file importing a Dart table also added to the database and another one from another file.

This builds fine for me - the generated code looks alright and there are no compilation warnings emitted by drift.

**Comment by em6m6e** [comment]
I solved the issue: in fact I was using dao files along the drift files.
In each drift file I had just a single import: `import 'dao.dart';` (without importing directly `tables.dart`)
In the dao file I had : 
```
import 'tables.dart';
import 'database.dart';
```
This was working until 2.3.0. Now by adding `import 'tables.dart';` in the drift file it works well with 2.3.0.

Thank you very much for your small project, it made me found the solution.

**Comment by simolus3** [comment]
Hm that should actually still work as well - I'll take another look.

**Comment by simolus3** [comment]
Actually I misread that - tables imported into a Dart file should not be exposed by default. The behavior in previous drift versions was unintentional.

Maybe we should look into respecting `export` statements eventually, but I'll close this issue as a wontfix.
