### ISSUE TITLE
Generate code from alternate schema sources

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#218]
Currently moor can generate data classes from CREATE TABLE statements in .moor files, or from `Table` subclasses in Dart. Would it be possible to also support generating data classes from an existing sqlite database file?

The motivation behind this request is to simplify migrations. Currently when you change the database schema you have to:
- Update the CREATE TABLE statement (or the `Table` subclass) and regenerate code
- Bump the schema version
- Write a migration

There are a few downsides to this approach
- Have to make edits in 3 different places, which introduces the possibility for skew between the CREATE TABLE statement and the migration
- Unit tests will create the database from scratch (onCreate is called instead of onUpgrade), meaning tests will still pass even if you forget to write a migration (this happened!)
- Issues managing a single schema version with multiple developers working on the same repository

Instead, this is how we're thinking of doing migrations:
- The database has a `migration` table: `CREATE TABLE migrations (migration_id INTEGER NOT NULL PRIMARY KEY)`
- The app code has a `Map<int, Future<void> Function(Database)> migrations = {...}`
- When you change the database schema, add a new entry to this map 
    - key is migration_id (the current timestamp)
    - value is a function that takes a database (or query executor?) runs a migration
- Migrations should be deterministic raw SQL statements (they shouldn't use generated code or variables)
- In the beforeOpen callback, apply any migrations that haven't been applied yet. Something like:
```dart
Future<bool> runMigrations() async {
  bool hadMigrations = false;
  await ensureMigrationTableCreated();
  List<int> pendingMigrations = /* Keys from the `migrations` map that don't exist in the migrations table */;
  for (int migrationId in pendingMigrations) {
    //await transaction(() async { <- #216
    await migrations[migrationId](db);
    await markMigrationApplied(migrationId); // INSERT INTO migrations VALUES ($migrationId)
    hadMigrations = true;
    //});
  }
  return hadMigrations;
}
```

With this approach:
- it's impossible to forget a migration step since there's only 1 step - add the migration to the map
- no possible skew between migration code and CREATE TABLE statements
- there's a single migration path (no onCreate vs onUpgrade), meaning all migrations are implicitly tested since they're the only way to change the schema
- more conducive to multiple developers writing migrations for the same repository

How we're planning to implement this approach:
- Don't commit the database.g.dart file to version control
- Write a build script that will:
    - Use moor_ffi to create an in-memory sqlite database
    - Run the migrations on that database
    - Generate a .moor file containing the CREATE TABLE statements from the database schema using PRAGMA table_info or the sqlite_master table
    - Run the moor generator to create data classes

This looks like it'll work for our case, but I figured I'd open an issue describing our problem and solution to see if you think moor could help in any way.

**Comment by simolus3** [comment]
From the other issue it sounds like you've already started to work on this, how did that work out so far? While this sounds like a feature that would be nice to have, we already have two different apis to describe a schema (Dart DSL and moor files). I feel like adding a third could confuse users. If you're interested, maybe this could be published as a third-party package?

> see if you think moor could help in any way.

If you run into any problems on the way where moor could make things easier, then that's always worth an issue of course. The generator is a bit hard to understand at the moment, I want to document it better and provide some sort of stable api. If you need anything specific, like creating in-memory "fake" moor files as strings and generating Dart code based on that, I could look into those areas more.

**Comment by Mike278** [comment]
Mostly replied in https://github.com/simolus3/moor/issues/240#issuecomment-559580855. 

One of the main issues I anticipated with this approach was that having the schema strewn across multiple files would make it inconvenient to view the current schema. 

This ended up not being as big of an issue, since part of our workflow already involves dumping the schema to a file (or pulling it from the device/simulator) and opening it in a 3rd party database tool (like the IntelliJ "Database tools and SQL" plugin) to expriment with queries.

The other issue with this approach is that we have to get a bit hacky if we want to use `.moor` file features like `CREATE TABLE ... AS MyTable` or the upcoming `MAPPED BY` - we're just using a config file for now with a map of tableName:dataClassName.

**Comment by simolus3** [comment]
Cool, thanks for sharing the results!

> we're just using a config file for now with a map of tableName:dataClassName.

I assume you're doing some parsing for that feature? So if there was `foo: CustomName` in that map, you'd automatically replace a `CREATE TABLE foo (...)` with `CREATE TABLE foo (...) AS CustomName` when writing the moor file?

> The other issue with this approach is that we have to get a bit hacky if we want to use .moor file features like `CREATE TABLE ... AS MyTable`

Ah right. But if you're creating moor files automatically there's not much that the generator could do about that. Maybe it could expose an api to "desugar" those features, so that some constraints are stripped away from the sql. You could then adapt the build script to 
- create moor-style `CREATE TABLE` statements in the migration functions
- strip those constraints away using apis provided by the generator (if you don't care about performance a lot, you could do this on a very low-level, for instance by wrapping a `QueryExecutor` and performing the transformations there)
- add the original create table statement to a moor file
- execute the stripped create table statement on the vm database

Downsides are that you could no longer use the mechanism reading from `sqlite_master`, so that's a bit of uncertainty introduced. But I imagine that for constraints on columns, like `JSON KEY` or `MAPPED BY`, it could work more reliably than a config file.

**Comment by Mike278** [comment]
> So if there was foo: CustomName in that map, you'd automatically replace a CREATE TABLE foo (...) with CREATE TABLE foo (...) AS CustomName when writing the moor file?

Yeah exactly - the script creates `all_tables.moor` (gitignored) with [this](https://gist.github.com/Mike278/c62ef4616a73d8695fb8bf32b557dbc9), then runs `build_runner`.

> create moor-style CREATE TABLE statements in the migration functions

Hmm interesting idea, although it might get kinda complicated trying to figure out which of a table's .moor constraints are "current" across multiple migrations. Those constraints don't affect the actual schema on disk, so keeping them in a config file instead of in migrations seems more natural to me.

Also since we manually call `MigrationHandler(proxyDb).runMigrations();` before opening the database, the desugaring would have to happen at runtime. That's probably fine since migrations are only run once and the performance hit from desugaring would be tiny compared to the actual time running the whole migration, but the extra complexity probably isn't worth it imo.
