### ISSUE TITLE
Generation fails on 2.3.0

### ISSUE THREAD

**Issue by kuhnroyal** [simolus3/moor#2185]
I have my migrations laid out as part files which are used inside a broader `migrations.dart` file.

After upgrading from 2.1.0 to 2.3.0 the code generation fails because the part files are now analyzed as Dart library.
It still works with 2.2.0.

```
[SEVERE] drift_dev:not_shared on lib/db/migrations/17_fix_table.dart:

Asset [my_app|lib/db/migrations/17_fix_table.dart] is not a Dart library. It may be a part file or a file without Dart source code.
```

**Comment by kuhnroyal** [comment]
I can work around this by restructuring the code but something changed here :)

**Comment by simolus3** [comment]
Technically this shouldn't be a problem since drift still generates sources for the main database (at least that's what I hope?). But of course it's super annoying and is a regression in drift. I've improved the UX for these cases in dafa07a88a6d05e21218c6a53cb38582c23d0eea.
