### ISSUE TITLE
Exception on `drift_dev schema generate`

### ISSUE THREAD

**Issue by maxstubbersfield** [simolus3/moor#2191]
Hi there,

When I run the command 
`flutter pub run drift_dev schema generate lib/src/database/schemas/json lib/src/database/schemas/generated` 

I get the following exception:

```
Unhandled exception:
type 'Null' is not a subtype of type 'List<dynamic>' in type cast
#0      SchemaReader._readTrigger (package:drift_dev/src/services/schema/schema_files.dart:291:61)
#1      SchemaReader._processById (package:drift_dev/src/services/schema/schema_files.dart:252:18)
#2      Iterable.forEach (dart:core/iterable.dart:325:35)
#3      SchemaReader._read (package:drift_dev/src/services/schema/schema_files.dart:216:19)
#4      new SchemaReader.readJson (package:drift_dev/src/services/schema/schema_files.dart:194:30)
#5      GenerateUtilsCommand._parseSchema (package:drift_dev/src/cli/commands/schema/generate_utils.dart:95:35)
<asynchronous suspension>
#6      GenerateUtilsCommand.run (package:drift_dev/src/cli/commands/schema/generate_utils.dart:64:20)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#8      MoorCli.run (package:drift_dev/src/cli/cli.dart:66:5)
<asynchronous suspension>
#9      run (package:drift_dev/src/cli/cli.dart:18:12)
<asynchronous suspension>
```

It looks like this is because the key _'references_in_body'_ isn't found for the triggers in the older schemas. Am I doing something wrong here?

Many thanks!

**Comment by simolus3** [comment]
Ah, right. Recently there's been a larger refactoring in `drift_dev` which also affected the schema writer. Previously, body references in triggers were encoded as `refences_in_body`. I must have fixed the typo without considering existing files - in hindsight, not a smart move...

I'll fix this in the next drift version. As a workaround, you can also find and replace `refences_in_body` with `references_in_body` in your existing schema jsons.

**Comment by maxstubbersfield** [comment]
Thank you!
