### ISSUE TITLE
CustomStatement does not fire watch event.

### ISSUE THREAD

**Issue by Jozott00** [simolus3/moor#2195]
Hi, I am implementing CRDTs for my app and therefore I got the following table:

```sql
CREATE TABLE crdt (
    collection TEXT NOT NULL,
    id TEXT NOT NULL,
    field TEXT NOT NULL,
    value BLOB,
    hlc TEXT NOT NULL,
    modified TEXT NOT NULL,
    PRIMARY KEY (collection, id, field)
);
```

Since `value` has to be dynamic (it could be any sql data type), I use Blob for it. However, the typed table generated by Drift uses `Uint8List` as the type for the `value` column. Since type serialisation to and from `Uint8List` is difficult, I take advantage of the fact that sql3 stores the value dynamically, so I can write and read dynamic types without having to serialise them. Of course, this means that I cannot use the typed table (with the `Uint8List` value) provided by Drift, but have to use custom queries instead.

Now to the actual problem I have:
I have a simple query to determine the maximum modified value:
```sql
getMaxModified: SELECT MAX(modified) FROM crdt;
```
(Side Question: This query is not achievable as Drift query, since the max expression is not available for String/Text, am I correct?)

And I am watching this query:
```dart
Stream<Hlc> get canonicalTimeStream {
  return getMaxModified()
      .map((modified) =>
          modified?.asHlc ?? Hlc.zero(nodeId: const Uuid().v4()))
      .watchSingle();
}
```

When I subscribe to the stream and print the output, I do not get new results when I insert new values using custom statements.

So when I insert some new value e.g. with this:
```dart
  Future<void> saveCrdt(CrdtTableModel r) async {
    final crdtTbl = crdt.actualTableName;
    final query = """
      INSERT INTO $crdtTbl
      (collection, id, field, value, hlc, modified)
      VALUES (?1, ?2, ?3, ?4, ?5, ?6)
      ON CONFLICT (collection, id, field) DO UPDATE
      SET value = excluded.value, hlc = excluded.hlc, modified = excluded.modified
      """;
    final vars = [
      r.collection,
      r.id,
      r.field,
      _encodeValue(r.value),
      r.hlc,
      r.modified.toString()
    ];
    await customStatement(query, vars);
  }
```
the subscriber does not receive a new value.

However, when I use Drift's `insertOnConflictUpdate` the trigger works fine...
```dart
into(crdt).insertOnConflictUpdate(CrdtData(
        collection: "test",
        id: "test",
        field: "test",
        value: Uint8List.fromList([1]),
        hlc: "2022-12-12T06:18:49.417Z#0000#0f04f467-78f0-4fb8-9151-26e5927ddef6",
        modified: "2022-12-12T06:18:49.417Z#0000#0f04f467-78f0-4fb8-9151-26e5927ddef6"
));
```

Unfortunatly this is not an option for me since I don't want to use Uint8List, as described above.

Thanks for your great work!

**Comment by simolus3** [comment]
I'll take a look at the other issue soon, but the behavior you're seeing is expected - query streams are a drift feature, so if you bypass much of drift and use raw statements, it can't update query streams for you.

You can use `await customInsert(statement, vars, {crdt});` to inform drift that you're about to do an insert on `crdt`.

**Comment by Jozott00** [comment]
@simolus3 Thanks for the fast answer! Does something similar like `customInsert()` exist for batches?

**Comment by simolus3** [comment]
It should! I've added this method in 5f887b8d2a5fe8be0e16cefa371ac9384e3578e3, so it will be available in the next drift release.

**Comment by Jozott00** [comment]
Awesome!
