### ISSUE TITLE
BLOB column with dynamic dart type

### ISSUE THREAD

**Issue by Jozott00** [simolus3/moor#2196]
# The Problem
Currently Drift generates Blob columns to `Uint8List` types, which is great for certain use cases where we actually store binary data. But in some use cases Blob is also used for unknown/dynamic data types, which are determined at runtime. 

At the moment if one wants to store undefined SQL datatypes, they would have to workaround the Drift generated table and instead use custom statements to be able to write and read dynamic data from the Blob column. 

A concrete example for this problem is described in issue #2195.

# The Feature
It would be great if there was direct drift support for dynamic SQL datatypes (TEXT, INTEGER, NULL, REAL). This means that the type of the columns data would be `dynamic` and the user of Drift is responsible for the correct type conversion.

Example table:
```sql
CREATE TABLE item (
    id TEXT PRIMARY KEY NOT NULL,
    value dynamic
);
```
And we could write the following
```dart
int writtenValue = 3;
await into(item).insert(ItemData(id: "someId", value: writtenValue);
int readValue = (await select(item).single()).value as int;
expect(readValue, writtenValue);
```

If this feature is already possible with Drift and I just don't know it, let me know! ^^

**Comment by simolus3** [comment]
I think we should generally support something like this (and sqlite already has a good way to express this with the `ANY` type in `STRICT` tables).

However, a problem is that drift's type mapping is not a bijection - different Dart values (with different types, even) may be mapped to the same SQL value. How do we know whether a `1` in SQL is a `1`, a `true` or a `DateTime.fromMillisecondsSinceEpoch(1)` in Dart? By default, those are all stored the same way.

We could introduce a `DriftAny` class to wrap these dynamic values, with typed methods to interpret the SQL value in different types. So it would be something like `int readValue = (await select(item).single()).value.readAs<int>`.

**Comment by Jozott00** [comment]
Yes, I noticed this problem, therefore I explicitly was talking about SQL Types. But I agree that it would be confusing for the user to be able to write `true` but actually getting an integer back. 

I think `DriftAny` is a great idea! How would it be annotated in the drift file SQL scheme?

**Comment by simolus3** [comment]
I've added the `DriftAny` type in e2265eb597a2a72a2459306756c4ea16bbee04e0.

> How would it be annotated in the drift file SQL scheme?

You declare the table as [strict](https://www.sqlite.org/stricttables.html) and then use `ANY` as a column type.
