### ISSUE TITLE
ERROR PlatformChannel flutter/src/services/platform_channel.dart 300:7

### ISSUE THREAD

**Issue by gabulsavul** [simolus3/moor#22]
ERROR: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
package:flutter/src/services/platform_channel.dart 300:7  MethodChannel.invokeMethod
===== asynchronous gap ===========================
dart:async                                                _AsyncAwaitCompleter.completeError
package:flutter/src/services/platform_channel.dart        MethodChannel.invokeMethod
===== asynchronous gap ===========================
dart:async                                                _asyncThenWrapperHelper
package:flutter/src/services/platform_channel.dart        MethodChannel.invokeMethod
package:sqflite/src/sqflite_impl.dart 18:34               invokeMethod

**Comment by simolus3** [comment]
Weird. Can you try stopping the app, running `flutter clean` and then starting your app again?

**Comment by gabulsavul** [comment]
Hi man, i solved it. The error happened because running in version flutter/test
