### ISSUE TITLE
Issues using the VmDatabase directly

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#220]
(context: I'm trying to implement the build script mentioned in #218)

```dart
void main() async {
  final driver = VmDatabase.memory(logStatements: true);
  await driver.runSelect('select 1', []);
}
```
```
Moor: Sent select 1 with args []
Unhandled exception:
NoSuchMethodError: The method 'prepare' was called on null.
Receiver: null
Tried calling: prepare("select 1")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _VmDelegate.runSelect (package:moor_ffi/src/vm_database.dart:91:28)
<asynchronous suspension>
#2      _ExecutorWithQueryDelegate.runSelect.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:37:19)
#3      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:26)
<asynchronous suspension>
#4      _ExecutorWithQueryDelegate._synchronized (package:moor/src/runtime/executor/helpers/engines.dart:19:26)
```

Manually calling `await driver.ensureOpen();` before the `runSelect` fixes this error, but gives a new error:
```
Unhandled exception:
NoSuchMethodError: The getter 'schemaVersion' was called on null.
Receiver: null
Tried calling: schemaVersion
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      DelegatedDatabase._runMigrations (package:moor/src/runtime/executor/helpers/engines.dart:263:41)
<asynchronous suspension>
#2      DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:255:13)
<asynchronous suspension>
#3      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:26)
<asynchronous suspension>
#4      DelegatedDatabase.ensureOpen (package:moor/src/runtime/executor/helpers/engines.dart:248:25)
#5      main (file:///home/mike.croptracker.local/webapp/dart/croptracker_flutter/tool/generate_dataobjects.dart:6:16)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Am I using the VmDatabase incorrectly? It's a QueryExecutor, so maybe I should be passing it to some `GeneratedDatabase` or `DatabaseConnectionUser` subclass and using that?

**Comment by simolus3** [comment]
For a low level database that runs without moor, I would probably recommend to use the [`Database`](https://pub.dev/documentation/moor_ffi/latest/database/Database-class.html) class from `package:moor_ffi/database.dart` directly. There's a very basic [example](https://pub.dev/packages/moor_ffi#-example-tab-) in the library.

The `QueryExecutor` is designed to be used with moor, and it's sort of an internal api that's rather poorly documented. The first thing is that you need to call `ensureOpen` (or wrap code in `doWhenOpened`) before starting to send queries. The other thing is that a `QueryExecutor` contains a reference to a `GeneratedDatabase`. The `sqflite` implementation uses it to pass the correct user version when opening the database, we also use it to run migrations.
You can manually subclass `GeneratedDatabase` with something like
```dart
class EmptyDb extends GeneratedDatabase {
  EmptyDb(QueryExecutor executor)
      : super(executor);
  @override
  final List<TableInfo> allTables = const [];
  @override
  int schemaVersion = 1;
}
```
And then use something like
```dart
final driver = VmDatabase.memory(logStatements: true);
driver.databaseInfo = EmptyDb(driver);
await driver.ensureOpen();
```

This tight coupling is a bad design choice, but splitting that up would cause a breaking version change between `moor_flutter` and `moor` that I'm trying to avoid from the 2.0 release. I regularly stumble upon this myself, so I'll definitely look at that for the next breaking release. Before that, I should probably add some better error messages...

**Comment by Mike278** [comment]
Yeah I started using that `Database` class, but my MigrationHandler needs to use the common `QueryExecutor` interface to run both on the device (with the sqflite driver) and in this build script (with the native ffi driver). That `GeneratedDatabase` subclass did the trick, and a little helper to set the `databaseInfo` makes it easy to use :)

**Comment by simolus3** [comment]
There are some asserts on `develop` that should provide more helpful error messages when `beforeOpen` or `databaseInfo` wasn't called/set.

**Comment by nhingo-312** [comment]
> For a low level database that runs without moor, I would probably recommend to use the [`Database`](https://pub.dev/documentation/moor_ffi/latest/database/Database-class.html) class from `package:moor_ffi/database.dart` directly. There's a very basic [example](https://pub.dev/packages/moor_ffi#-example-tab-) in the library.
> 
> The `QueryExecutor` is designed to be used with moor, and it's sort of an internal api that's rather poorly documented. As you already found out, you need to call `ensureOpen` (or wrap code in `doWhenOpened`) before starting to send queries. The other thing is that a `QueryExecutor` contains a reference to a `GeneratedDatabase`. The `sqflite` implementation uses it to pass the correct user version when opening the database, we also use it to run migrations.
> You can manually subclass `GeneratedDatabase` with something like
> 
> ```dart
> class EmptyDb extends GeneratedDatabase {
>   EmptyDb(QueryExecutor executor)
>       : super(executor);
>   @override
>   final List<TableInfo> allTables = const [];
>   @override
>   int schemaVersion = 1;
> }
> ```
> 
> And then use something like
> 
> ```dart
> final driver = VmDatabase.memory(logStatements: true);
> driver.databaseInfo = EmptyDb(driver);
> await driver.ensureOpen();
> ```
> 
> This tight coupling is a bad design choice, but splitting that up would cause a breaking version change between `moor_flutter` and `moor` that I'm trying to avoid from the 2.0 release. I regularly stumble upon this myself, so I'll definitely look at that for the next breaking release. Before that, I should probably add some better error messages...

Hi, I'm using the latest version of both moor and sqlite3_flutter_libs but got the same issue about vm_database, could you please have a look and suggest any idea for debugging, I'll be thankful so much!

Here my logcat:
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'open' was called on null.
    Receiver: null
    Tried calling: open()
    #0      _VmDelegate.open (package:moor/src/ffi/vm_database.dart:126)
    #1      DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:255)
    <asynchronous suspension>
    #2      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:34)
    <asynchronous suspension>
    #3      QueryEngine.doWhenOpened.<anonymous closure> (package:moor/src/runtime/api/query_engine.dart)
    <asynchronous suspension>

**Comment by simolus3** [comment]
Did you get an exception before that message? If you're using `sqlite3_flutter_libs` version `0.4.0`, can you try using `0.4.0+1` instead?

**Comment by nhingo-312** [comment]
@simolus3 I got this exception and the android device couldn't load data from its local, and I'm indeed using moor version 3.4.0 and sqlite3_flutter_libs: ^0.4.0+1, not working at all :(

**Comment by nhingo-312** [comment]
@simolus3 Is it possible that an unstable network led to this issue, sir?

**Comment by simolus3** [comment]
> Is it possible that an unstable network led to this issue, sir?

I don't think so, moor doesn't access the network.

The exception happens if sqlite3 can't be loaded at runtime, but I would expect another exception to happen before. Are you also using a `VmDatabase` directly (e.g. _without_ a database class generated by moor)? If you have a repro for me to look at, I can try to figure out what's going wrong here.
