### ISSUE TITLE
Flutter web app - clearing all rows on refresh (F5)

### ISSUE THREAD

**Issue by crisperit** [simolus3/moor#2206]
Hello,
I've tried to use drift web implementation in my app by following
https://github.com/simolus3/drift/tree/develop/examples/flutter_web_worker_example

It works fine - until I'm trying to refresh the page - then all data disappears (?)

You can see that on following record from mine test page 
https://prappser-app.netlify.app/#/

![drift-web-bug](https://user-images.githubusercontent.com/17547300/207710019-eaf89ce9-cb51-48c7-a4fc-49e5dcad7f1d.gif)

Flutter version:
```
Flutter 3.3.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision eb6d86ee27 (2 months ago) • 2022-10-04 22:31:45 -0700
Engine • revision c08d7d5efc
Tools • Dart 2.18.2 • DevTools 2.15.0
```

Drift version: 2.3.0

database.dart
```
@DriftDatabase(tables: [ApplicationEntity])
class Database extends _$Database {
  Database(QueryExecutor queryExecutor) : super(queryExecutor);

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (migrator) async {
        await migrator.createAll();
      },
    );
  }
}
```

database_web.dart
```
import 'dart:html';

import 'package:drift/drift.dart';
import 'package:drift/remote.dart';
import 'package:drift/web.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'database.dart';

final databaseProvider = Provider<Database>((ref) {
  final webDatabase = LazyDatabase(() async {
    final worker = SharedWorker(
        kReleaseMode ? 'worker.dart.min.js' : 'worker.dart.js', 'worker');
    var conn = remote(worker.port!.channel());
    return conn.executor;
  });
  return Database(webDatabase);
});

```

web/worker.dart
```
void main() {
  final self = SharedWorkerGlobalScope.instance;
  self.importScripts('sql-wasm.js');

  final db = WebDatabase.withStorage(DriftWebStorage.indexedDb('worker',
      migrateFromLocalStorage: false, inWebWorker: true));
  final server = DriftServer(DatabaseConnection(db));

  self.onConnect.listen((event) {
    final msg = event as MessageEvent;
    server.serve(msg.ports.first.channel());
  });
}
```

Let me know if you have any ideas on what direction should I check it and what more data should I provide. Have you some brief ideas what can go wrong?

Cheers :)

**Comment by crisperit** [comment]
From what I can see - no matter how many queries I perform - they do not seem to be saved in indexeddb - the blob size is not changing at all 🤔

**Comment by simolus3** [comment]
I can reproduce the issue in your app, but not with the `flutter_web_worker_example` included in this repository. Do you have a way to share those sources with me? The worker looks very similar what I'm doing.

**Comment by crisperit** [comment]
All sources can be seen through devtools on https://prappser-app.netlify.app/#/
![obraz](https://user-images.githubusercontent.com/17547300/208295141-658dfcfb-2e00-45e6-9ce2-f5b4ccc1b1a2.png)

**Comment by crisperit** [comment]
@simolus3 Btw - on Chrome I do not see worker.dart.js logs - but they're visible on Mozilla Firefox. Do you know why?

**Comment by crisperit** [comment]
Ah - nvm
`chrome://inspect/#workers`

**Comment by crisperit** [comment]
@simolus3 
I've found the issue.. after being able to inspect worker logs

The issue is that 
```
.into(database.applicationEntity)
        .insertReturning(...)
```
...is invalidly treated as a `SELECT` query
![image](https://user-images.githubusercontent.com/17547300/208310057-e993e43c-c020-4601-8fab-c0890f296bca.png)

After changing it into...
```
.into(database.applicationEntity)
        .insert(...)
```
...the method is resolved correctly as INSERT and the data is persisted

![image](https://user-images.githubusercontent.com/17547300/208310111-8a7a96f9-08ce-4434-bb14-0a45c5131ad0.png)

I've deployed the fixed version in here:
https://prappser-app-fix.netlify.app/#/

The same issue is for the updating queries
```
  @override
  Future<String> updateOne(Application application) async {
    return (database.update(database.applicationEntity)
          ..whereSamePrimaryKey(_createApplicationData(application)))
        .writeReturning(_createApplicationData(application))
        .asStream()
        .map((event) => event[0].id)
        .first;
  }
```

I believe that all that have `Returning` suffix are not working correctly

@simolus3  I think that it might be called a bug IMO

**Comment by simolus3** [comment]
Thanks for the in-depth analysis!! You're absolutely right, this _is_ a bug. I have fixed the `WebDatabase` to also emit a write for `RETURNING` queries in 4644bce9dddc6298272cbd04fe27ffa23a240d9c. 

We need to run the query as `select` because that's the only way we get the rows back. Of course, we then have the problem that the database doesn't know it needs to be saved (which we have to do explicitly with `sql.js`).

**Comment by crisperit** [comment]
Nice!

Waiting for the release then :D
