### ISSUE TITLE
Using drift_dev schema generate in MigrationStrategy

### ISSUE THREAD

**Issue by North101** [simolus3/moor#2207]
In my migration code I have been using the classes generated by `dart pub run drift_dev schema generate`. However, `schema.dart` has references to classes in `drift_dev`. Does it make sense to move these classes to `drift`?

```dart
onUpgrade: (m, from, to) async {
  if (from < 2) {
    final db = v2.DatabaseAtV2($db.executor);
    ...
  }
  if (from < 3) {
    final db = v3.DatabaseAtV3($db.executor);
    ...
  }
}
```

**Comment by ycherniavskyi** [comment]
The same is related to [Verifying a database schema at runtime](https://drift.simonbinder.eu/docs/advanced-features/migrations/#verifying-a-database-schema-at-runtime) - particularly to `validateDatabaseSchema` function.

Currently, this function usage led to the following analysis warning:

> info: Depend on referenced packages. (depend_on_referenced_packages at [project] lib/data/app_database/app_database.dart:9)

so `drift_dev` must be moved from `dev_dependencies` to `dependencies`, which seems not right.

**Comment by simolus3** [comment]
In my opinion, APIs you use for development can reasonably be part of `drift_dev`. This includes the `validateDatabaseSchema` function, which should only be called during development.

> so `drift_dev` must be moved from `dev_dependencies` to `dependencies`, which seems not right.

As long as you're not writing a library, there's not much of a difference between `dev_dependencies` and `dependencies`. It doesn't make your app any larger: As long as `validateDatabaseSchema` is only called in debug builds, `drift_dev` is not part of your compiled  code. And as long as you're not importing drift's internal builder definitions, the Dart compiler doesn't even see the large parts of `drift_dev`.
To me, `drift_dev` is the natural place for development utilities, which is what `validateDatabaseSchema` is. 

That said, using the generated schema files as part of your regular app to create tables at specific versions is a recommended way to use them, and not just for development. So I agree that `schema.dart` should not import `drift_dev` and I've moved the import to the core `drift` package in add680b8bfc4cd9b1b3322da02721d3255b391c9.
