### ISSUE TITLE
Schema does not match error when upgrading to Drift 2

### ISSUE THREAD

**Issue by jeannelim** [simolus3/moor#2213]
### Discussed in https://github.com/simolus3/drift/discussions/2211

<div type='discussions-op-text'>

<sup>Originally posted by **cal-g** December 15, 2022</sup>
Hi,
I upgraded Drift in my project from 1.7 to the latest and get an error when `db.validateDatabaseSchema()` is called.
```
Schema does not match
recent_projects:
columns:
  time_created:
   Not equal: `NULL DEFAULT (CAST(strftime('%s', CURRENT_TIMESTAMP) AS INTEGER))` (expected) and `NULL DEFAULT (strftime('%s', CURRENT_TIMESTAMP))` (actual)
```

only for columns defined as such:
![Screenshot 2022-12-15 at 10 53 46 AM](https://user-images.githubusercontent.com/98470469/207906888-6e248b36-d5a6-4b54-9c39-e7f8771c00a1.png)

No table changes were made during the upgrade process so I wouldn't think upgrading the schema number is required. 
Do you know where I must have gone wrong ?

Thanks :)</div>

**Comment by simolus3** [comment]
See the comment https://github.com/simolus3/drift/discussions/2211#discussioncomment-4414744 - this is annoying, but unfortunately I think it has to stay this way in drift. I have shared two ways to bypass this issue in there, please let me know if they don't work for you.
