### ISSUE TITLE
JSON KEY constraint fails generation

### ISSUE THREAD

**Issue by TrueNight** [simolus3/moor#2214]
When adding `JSON KEY` constraint generation fails.

```sql
CREATE TABLE waybills (
    parent    INT      JSON KEY parentDoc        NULL,
    id        INT                            NOT NULL,
    dataType  TEXT                           NOT NULL
);
```

[WARNING] drift_dev:not_shared on lib/db/db.dart:
Could not analyze DriftElementId(.../db/schema.drift, waybills)
Exception: Did not expect JsonKey as a ColumnConstraint

**Comment by simolus3** [comment]
Thanks for the report! Unfortunately, `JSON KEY` constraints were broken in drift 2.3.0 and it seems the test coverage around this feature was rather poor.

I have fixed the issue and added tests in 0e395bbef37b31d47abfa66e2efc81fed0129535.
