### ISSUE TITLE
Db property is missing from MigrationStrategy.beforeOpen

### ISSUE THREAD

**Issue by jbarat** [simolus3/moor#222]
I was following the documentation on migration. It was suggesting to populate the database on the `beforeOpen` method. But while in the documentation the method looks like `beforeOpen: (db, details)` in version `2.0.0` the `db` is missing.

Is this intentional? Where should I populate the database?

the documentation: https://moor.simonbinder.eu/docs/advanced-features/migrations/

**Comment by simolus3** [comment]
Thanks for the report, the documentation is outdated. I've fixed the docs on `develop` and just cherry-picked that commit to master, so the site should update soon. The `beforeOpen` callback is still the right place to populate data.

The parameter has been removed in moor 2.0, you can just remove it:
```dart
beforeOpen((db, details) async {
  await db.into(...); // old
}
```
would now be
```dart
beforeOpen((details) async {
  await into(...); // new - just don't use db
}
```
