### ISSUE TITLE
Can `batch` return data as `insertReturning`

### ISSUE THREAD

**Issue by phamconganh** [simolus3/moor#2224]
** `batch` return data as `insertReturning`.**
My case is to insert or update many rows, then need to return data to perform other function

**Comment by simolus3** [comment]
No, unfortunately this is not possible. We don't have a way to get the results of individual statements in all database implementations, so we can't have `batch` return data.

You could put the batch in a transaction and get the highest rowid of the affected table first. Then, you can run the batch and know how many rows you've just inserted. With that, you can do a select `where oid BETWEEN ?lastRowID AND ?lastRowID + ?rowsInsertedInBatch` to get the inserted rows back.
