### ISSUE TITLE
Support built_value_generator 7.0.0

### ISSUE THREAD

**Issue by knaeckeKami** [simolus3/moor#223]
built_value_generator released a new major version, 7.0.0.
https://pub.dev/packages/built_value_generator#-changelog-tab-

moor_generator should be updated to support this new release. 

As far as I checked it, no code changes should be necessary.

**Comment by simolus3** [comment]
Right, thanks! I've just removed the dependency entirely on `develop`. We don't use built_value a lot, so the dependency doesn't justify the ~10 LOC saved in moor_generator.
I'm not sure when the next moor version is ready yet, but I can release a minor update to the existing generator with the updated version range if you need it.
