### ISSUE TITLE
Manually run migrations

### ISSUE THREAD

**Issue by henriqueArrazao** [simolus3/moor#2236]
My application allows the user to import the database file, but the there's no method provided by Drift to migrate that file manually (using the same MigrationStrategy as declared in the beginning). It would be something like this:

```dart
final restoreFile = await userChooseFile();

// SOMETHING LIKE THIS
// could throw in case the version number is higher than the current one for example
// case it was success, the db file is returned migrated and with the proper version number set
final migratedFileWithoutErrors = await _db.migrateMannually(restoreFile)

// replace the current database
migratedFileWithoutErrors.writeAsBytes(dbPath);

// refresh tables
_db.markTablesUpdated(_db.allTables);
```

**Comment by henriqueArrazao** [comment]
For now I'm doing this

```dart
      final sqfliteDb = await sqflite.openDatabase(_temporarySQLFilePath);
      final importedVersion = await sqfliteDb.getVersion();
      await sqfliteDb.close();

      if (importedVersion > _db.schemaVersion) {
        throw _HigherDBVersionException();
      }

      await compute<FileManipulationModel, void>(
        _replaceFile,
        FileManipulationModel(
          from: File(_temporarySQLFilePath),
          to: File(_dbPath),
        ),
      );

      if (importedVersion != _db.schemaVersion) {
        await _db.beforeOpen(
          _db.executor,
          OpeningDetails(importedVersion, _db.schemaVersion),
        );
      }

      _db.markTablesUpdated(_db.allTables);

      await _registerLastBackup(type: BackupOperation.import);
```

**Comment by simolus3** [comment]
Couldn't you just open the `restoreFile` as a database with your database class? That will also run all migrations. You can close the database used for migrations afterwards.

I think having a general API for this in drift is rather complicated, because users can write complex migrations themselves and we can't guarantee that they don't have weird side effects (calling `beforeOpen` with an executor not attached to the main database will work by default, but conceptually it feels a bit dangerous to me for instance).

**Comment by henriqueArrazao** [comment]
> Couldn't you just open the `restoreFile` as a database with your database class? That will also run all migrations. You can close the database used for migrations afterwards.
> 
> I think having a general API for this in drift is rather complicated, because users can write complex migrations themselves and we can't guarantee that they don't have weird side effects (calling `beforeOpen` with an executor not attached to the main database will work by default, but conceptually it feels a bit dangerous to me for instance).

That's a good option, I think it would solve as well, I will try it and then come back here.

**Comment by simolus3** [comment]
Alright, let me know if that causes further problem and I'll re-open this issue in search of a better solution then.
