### ISSUE TITLE
Auto-implied name from SQL query using IFNULL

### ISSUE THREAD

**Issue by frankvollebregt** [simolus3/moor#2242]
**Describe the bug**
I'm using `.drift` files to define my database queries in SQL.

I was trying to use `IFNULL` to set a numeric value to `0.0` by default, which works well.
```SQL
SELECT ..., IFNULL(pickup.total_pickup, 0.0), ... FROM pickup ...
```
When I use `build_runner` to generate the Dart code from the SQL above, the column name of the result is
```dart
iFNULLpickuptotalPickup00
```
Where I would intuitively expect it could simply use the column name of the first value (`total_pickup` in my case). 

I realise that the fallback (if null) value could be some other column or value, but since by default we use the first value, taking the column name from there would not be bad in my opinion.

I can just use `AS pickup_total` to force the build runner to name it `pickupTotal` in Dart, but was curious whether it was a conscious decision not to automatically imply column names in this case.

**Comment by simolus3** [comment]
Thanks for the suggestion! On the one hand, we could be smarter about this and try to use a column name if there is one as a sub-expression, but it's also worth noting that this would be a breaking change.

At the moment, the approach is "name of the column as in sqlite3, illegal chars stripped, converted to camelCase". And the column name is just the literal text of the column by default. This was a conscious decision and it works reasonably well in many cases.

So while this is not ideal for your particular query, I think it works well-enough to not justify the breaking change. Realistically, I think adding an explicit name with `AS` is the only reliable solution to the cases where the default breaks (and regardless of what the default is, there will always be cases where it's not great).

**Comment by frankvollebregt** [comment]
Thanks for the quick response (as always), it makes sense.
