### ISSUE TITLE
concurrency write issue

### ISSUE THREAD

**Issue by HuangZiquan** [simolus3/moor#2245]
Hi,
Thanks for your help in solving Issue #2244.
But when I execute Concurrent writing occurs ConnectionClosedException.
[issue_demo](https://github.com/HuangZiquan/drift_issue_demo.git)

**Comment by simolus3** [comment]
Good catch. This is an unhandled exception in the background isolate which shouldn't affect the overall operation (aside from printing an ugly stacktrace).

I've fixed this in 4723d8474e5aa9a300b210ccb44bbb83aa9d12cf and I'll release a new minor drift version with this fix soon.
