### ISSUE TITLE
schema generate is trying to create views with drift specific syntax

### ISSUE THREAD

**Issue by North101** [simolus3/moor#2249]
`schema dump` is storing the view statement as it is defined and when the view is generated with `schema generate` it is being stored as is, without stripping out anything drift specific. This causes an error when trying to create the view in a migration.

**Comment by North101** [comment]
https://github.com/simolus3/drift/blob/810ecb169ab50051f34c71ca78b281515d7aa674/drift_dev/lib/src/services/schema/schema_files.dart#L385

Unlike `DriftTrigger` and `DriftIndex`, this isn't setting `parsedStatement`. If I try parsing the sql, it fails unless `_engine.options.useDriftExtensions=true` because of the drift specific syntax.

**Comment by North101** [comment]
I forgot to mention that this happens when using the new `WITH CustomRow` syntax

**Comment by simolus3** [comment]
Fixed in 4cd7616f24db97bf6806f6ab66de410a4b5b1ac1, thanks for the report!
