### ISSUE TITLE
Why is the sqlite_sequence data queried empty?

### ISSUE THREAD

**Issue by ddxl123** [simolus3/moor#2251]
Why is the sqlite_sequence data queried empty?
```
final result = await db.customSelect("select * from sqlite_sequence").get();
print(result); // []
```

**Comment by simolus3** [comment]
Do you have a table that's using `AUTOINCREMENT`? Could this be an initial state when all those table with auto-incrementing primary keys are empty? Sqlite should insert values into `sqlite_sequence` as inserts to those tables are happening.
