### ISSUE TITLE
EncryptedDrift + FirebaseMessaging on iOS = SQLCipher assertion fails

### ISSUE THREAD

**Issue by wryczko** [simolus3/moor#2255]
Hi,

I've created flutter app using Encrypted Drift using provided [instruction](https://drift.simonbinder.eu/docs/other-engines/encryption/) and it worked like a charm, but...

Recently I've added a new package [firebase_messaging](https://pub.dev/packages/firebase_messaging) to my app and everything worked on Android, but when I tried to open an app on iOS physical device, creating NativeDatabase instance failed following assertion:

```
bool _debugCheckHasCipher(Database database) {
  return database.select('PRAGMA cipher_version;').isNotEmpty;
}
```

with an error:

```
Unhandled Exception: '../DriftContext.dart': Failed assertion: line 156 pos 18: '_debugCheckHasCipher(rawDb)': is not true.
#0      DriftCommunication.request (package:drift/src/remote/communication.dart:116:66)
#1      _RemoteQueryExecutor.ensureOpen (package:drift/src/remote/client_impl.dart:158:10)
```

I've already tried a potential solution with adding -framework SQLCipher in "Other Linker Flags" in project's settings on Xcode described [here](https://github.com/simolus3/sqlite3.dart/tree/master/sqlcipher_flutter_libs#incompatibilities-with-sqlite3-on-ios-and-macos), but this setting was already there.

Do you have any suggestions? 

I am creating NativeDatabase instance (in separate Isolate) with following code:
```
bool _debugCheckHasCipher(Database database) {
  return database.select('PRAGMA cipher_version;').isNotEmpty;
}

void setupSqlCipher() {
  if (Platform.isAndroid) {
    open.overrideFor(OperatingSystem.android, () => DynamicLibrary.open('libsqlcipher.so'));
  }
}

void _startBackground(_IsolateStartRequest request) {
  final driftIsolate = DriftIsolate.inCurrent(() => DatabaseConnection(LazyDatabase(() async {
        setupSqlCipher();

        final file = File(request.targetPath);
        return NativeDatabase(file, logStatements: false, setup: (rawDb) {
          assert(_debugCheckHasCipher(rawDb));
          rawDb.execute("PRAGMA key = 'password';");
        });
      })));

  request.sendDriftIsolate.send(driftIsolate.connectPort);
}

class _IsolateStartRequest {
  final SendPort sendDriftIsolate;
  final String targetPath;

  _IsolateStartRequest(this.sendDriftIsolate, this.targetPath);
}

await Isolate.spawn(_startBackground, _IsolateStartRequest(receivePort.sendPort, path));
```

**Comment by simolus3** [comment]
Could you try adding this to your podfile? https://github.com/simolus3/drift/issues/1810#issuecomment-1119426006

**Comment by wryczko** [comment]
I've applied the fix you mentioned and my app has started working! Thank you @simolus3!

**Comment by simolus3** [comment]
Nice, I've also added that information to `sqlcipher_flutter_libs`' README now.
