### ISSUE TITLE
app crashed when add dependency 

### ISSUE THREAD

**Issue by Mohammadfazel03** [simolus3/moor#2274]
when i add drift and sqlite3_flutter_libs in my project app crashed 

this is my log

E/FlutterLoader( 8155): Flutter initialization failed.
E/FlutterLoader( 8155): java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.isar_project-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.isar_project-2/lib/arm, /data/app/com.example.isar_project-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
E/FlutterLoader( 8155): 	at java.util.concurrent.FutureTask.report(FutureTask.java:94)
E/FlutterLoader( 8155): 	at java.util.concurrent.FutureTask.get(FutureTask.java:164)
E/FlutterLoader( 8155): 	at io.flutter.embedding.engine.loader.FlutterLoader.ensureInitializationComplete(FlutterLoader.java:239)
E/FlutterLoader( 8155): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:327)
E/FlutterLoader( 8155): 	at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:207)
E/FlutterLoader( 8155): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.setupFlutterEngine(FlutterActivityAndFragmentDelegate.java:271)
E/FlutterLoader( 8155): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:180)
E/FlutterLoader( 8155): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:498)
E/FlutterLoader( 8155): 	at android.app.Activity.performCreate(Activity.java:6760)
E/FlutterLoader( 8155): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
E/FlutterLoader( 8155): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
E/FlutterLoader( 8155): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
E/FlutterLoader( 8155): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
E/FlutterLoader( 8155): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
E/FlutterLoader( 8155): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/FlutterLoader( 8155): 	at android.os.Looper.loop(Looper.java:154)
E/FlutterLoader( 8155): 	at android.app.ActivityThread.main(ActivityThread.java:6121)
E/FlutterLoader( 8155): 	at java.lang.reflect.Method.invoke(Native Method)
E/FlutterLoader( 8155): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
E/FlutterLoader( 8155): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
E/FlutterLoader( 8155): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.isar_project-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.isar_project-2/lib/arm, /data/app/com.example.isar_project-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libflutter.so"
E/FlutterLoader( 8155): 	at java.lang.Runtime.loadLibrary0(Runtime.java:985)
E/FlutterLoader( 8155): 	at java.lang.System.loadLibrary(System.java:1562)
E/FlutterLoader( 8155): 	at io.flutter.embedding.engine.FlutterJNI.loadLibrary(FlutterJNI.java:141)
E/FlutterLoader( 8155): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:189)
E/FlutterLoader( 8155): 	at io.flutter.embedding.engine.loader.FlutterLoader$1.call(FlutterLoader.java:182)
E/FlutterLoader( 8155): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/FlutterLoader( 8155): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/FlutterLoader( 8155): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/FlutterLoader( 8155): 	at java.lang.Thread.run(Thread.java:761)

i think drift has problem with some cpu architecture
i run that in memu emulator v8 (with android 7)

**Comment by simolus3** [comment]
As indicated from the log, this happens on an armv7 device. armv7 is supported by `sqlite3_flutter_libs` because it's _possible_ to build Flutter apps for that architecture, but by default Flutter doesn't support that architecture.

You can fix this problem by restricting the architectures for which `sqlite3_flutter_libs` should be build. [The readme of that package](https://github.com/simolus3/sqlite3.dart/tree/main/sqlite3_flutter_libs#included-platforms) contains a suitable snippet to add to your `build.gradle` file for that.
