### ISSUE TITLE
Flutter 3.7 code generation failed (only one class)

### ISSUE THREAD

**Issue by bobekos** [simolus3/moor#2281]
**Describe the bug**

After upgrade to flutter 3.7 (i do not know if it has something to do with it) and upgrade drift from following dependencies:
drift from 2.3.0 to 2.4.2
drift_dev from 2.3.3 to 2.4.1

i am got some errors after code generation (this happens only on one file other files are generated correctly):
`Could not format generated source. The generated code is probably invalid, and this is most likely a bug in drift_dev.`
`This builder requires Dart inputs without syntax errors.`

The errors are always wrong nullable indicators for strings (for example):
`serializer.fromJson<String??>(json['invoiceContact']`

so if i change the String?? to String? the errors are gone.

Any idea what happened here?

**Comment by simolus3** [comment]
Thanks for the report! I suspect this happened either due to the drift or an `analyzer` upgrade. 

> The errors are always wrong nullable indicators for strings (for example):

Does the affected column (`invoiceContact`) have a type converter? Can you share the definition for that column or the converter if there is one?

>  This builder requires Dart inputs without syntax errors.

Which builder emits this error, is it `drift_dev`? On which file is the error reported, is it a generated file or a source file that you've written?

**Comment by bobekos** [comment]
@simolus3 

Wow thanks for the fast response.

> Does the affected column (invoiceContact) have a type converter? Can you share the definition for that column or the converter if there is one?

Yes there is a typeConverter for this. Here the table info:
`TextColumn get invoiceContact =>
      text().map(const CustomerContactModelConverter()).nullable()();`
      
The converter for that:
```
class CustomerContactModelConverter
    extends TypeConverter<CustomerContactModel?, String?>
    with JsonTypeConverter<CustomerContactModel?, String?> {
  const CustomerContactModelConverter();

  @override
  CustomerContactModel? fromSql(String? fromDb) {
    if (fromDb == null) return null;

    return CustomerContactModel.fromJson(json.decode(fromDb));
  }

  @override
  String? toSql(CustomerContactModel? value) {
    if (value == null) return null;

    return json.encode(value.toJson());
  }
}
```

and the model itself:

```
class CustomerContactModel {
  final String forename;
  final String name;
  final String tel;
  final String email;
  final String fax;

  CustomerContactModel({
    this.forename = '',
    this.name = '',
    required this.tel,
    required this.email,
    this.fax = '',
  });

  factory CustomerContactModel.fromJson(Map<String, dynamic> json) {
    return CustomerContactModel(
      forename: json['forename'],
      name: json['name'],
      tel: json['tel'],
      email: json['email'],
      fax: json['fax'],
    );
  }

  factory CustomerContactModel.empty() {
    return CustomerContactModel(tel: '', email: '');
  }

  Map<String, dynamic> toJson() => {
        'forename': forename,
        'name': name,
        'tel': tel,
        'email': email,
        'fax': fax,
      };
}
```

**Comment by bobekos** [comment]
> Which builder emits this error, is it drift_dev? On which file is the error reported, is it a generated file or a source file that you've written?

Oh i see it seems that the mockito builder is throwing this (removed the path):
```
[SEVERE] mockito:mockBuilder on .../order_taking_database_provider.dart:

This builder requires Dart inputs without syntax errors.
However, package:xxx/.../order_taking_database_provider.dart (or an existing part) contains the following errors.
order_taking_database_provider.drift.dart:288:246: Expected an identifier.
order_taking_database_provider.drift.dart:288:377: Expected an identifier.
order_taking_database_provider.drift.dart:288:501: Expected an identifier.
And 6 more...
```

**Comment by simolus3** [comment]
The problem might go away if you declare the type converter to map non-nullable types:

```dart
class CustomerContactModelConverter
    extends TypeConverter<CustomerContactModel, String>
    with JsonTypeConverter<CustomerContactModel, String> {
  const CustomerContactModelConverter();

  @override
  CustomerContactModel fromSql(String fromDb) {
    return CustomerContactModel.fromJson(json.decode(fromDb));
  }

  @override
  String toSql(CustomerContactModel value) {
    return json.encode(value.toJson());
  }
}
```

You can still apply a type converter that is non-nullable in both directions to a nullable column. Drift will just map nulls for you in that case. So the behavior should be identical.

This is still a drift bug that I'll have to investigate, but if we're lucky the workaround may resolve the syntax errors for you.

**Comment by bobekos** [comment]
@simolus3 

Nice it's working. And there is no problem, when this column was add over a migration? So drift does not calling the converter when the string db data is null?

Thank you very much for your help. This was fast ^^
