### ISSUE TITLE
A way to set condition for insert

### ISSUE THREAD

**Issue by HosseinArabbeigi** [simolus3/moor#229]
Hi 
I need a way to set condition for insert
or at least i want to update row if primarykey exists.

**Comment by simolus3** [comment]
>  I need a way to set condition for insert

In general, it's not easy to do that in sqlite, see #202. We probably won't expose shortcuts for that in moor directly. If you really need it, first use a select to check if the value exists and then conditionally send an insert.

>  or at least i want to update row if primarykey exists.

That should already be possible. Just use `into(table).insert(row, orReplace: true)`
