### ISSUE TITLE
Bad state: No element when doing insertReturning with onConflict and where 

### ISSUE THREAD

**Issue by mateoKutnjak** [simolus3/moor#2299]
I have an abstract Dao class which has `upsert` method.

```
Future<int> upsertByRemoteId(Insertable<D> entry) async {
  D result = await into(_table).insertReturning(entry,
          onConflict: DoUpdate.withExcluded(
            (old, excluded) {
              return onConflictCompanion(old: old, excluded: excluded);
            },
            target: [_table.columnsByName[DATATABLE_COLUMN_NAME_REMOTE_ID]!],
            where: (old, excluded) => isDifferent(old, excluded),
          ));
   return result.localId;
}
```

For example. My UserDao subclass has implemented `isDifferent` method which checks whether some fields differ in old entry and new entry.

```
@override
  Expression<bool> isDifferent(Users old, Users excluded) {
    return old.dateJoined.isNotExp(excluded.dateJoined) |
        old.email.isNotExp(excluded.email) |
        old.username.isNotExp(excluded.username) |
        old.syncState.isNotExp(excluded.syncState) |
        old.isGuest.isNotExp(excluded.isGuest) |
        old.isVerified.isNotExp(excluded.isVerified) |
        old.isDeletedLocally.isNotExp(excluded.isDeletedLocally);
  }
```

Commenting out `where` parameter in `DoUpdate.withExcluded` removes the error, but update is performed every time. 

What am I doing wrong?

**Comment by simolus3** [comment]
Thanks for the report. Could you also post the stack trace of that error?

**Comment by mateoKutnjak** [comment]
Stack trace is null when exception happens.

Here is the screenshot. Maybe it can help

![Screenshot from 2023-02-05 13-27-03](https://user-images.githubusercontent.com/15217029/216818635-c5e6d51b-d4c9-4e61-b6d2-266a1dd0960d.png)

**Comment by mateoKutnjak** [comment]
If I replace `insertReturning` with `insert` it works ok. It seems like returned ID after `insert` with `onConflict` is correct no matter if insert or update happens

**Comment by mateoKutnjak** [comment]
I have logged results after performing same query with `insert` (not `insertReturning`) and some strange situation happens.

Every time Insertable object is the same (`entry`) but after three times of correct behavior `insert` returns `localId` (PK) as 2 but row count stays 1. There is nothing written in row with `localId` with value 2 (`element` is just printing name of the city)

```
[log] table=Instance of '$CitiesTable' localId=1 count=1 element=Zagreb entry=CitiesCompanion(localId: Value.absent(), id: Value(48), createdAt: Value(2022-01-08 01:27:13.000Z), updatedAt: Value(2022-01-08 01:27:13.000Z), name: Value(Zagreb), location: Value(LatLng(45.8, 15.95)), country: Value(HRV), syncState: Value(S), isDeletedLocally: Value(false))
[log] table=Instance of '$CitiesTable' localId=1 count=1 element=Zagreb entry=CitiesCompanion(localId: Value.absent(), id: Value(48), createdAt: Value(2022-01-08 01:27:13.000Z), updatedAt: Value(2022-01-08 01:27:13.000Z), name: Value(Zagreb), location: Value(LatLng(45.8, 15.95)), country: Value(HRV), syncState: Value(S), isDeletedLocally: Value(false))
[log] table=Instance of '$CitiesTable' localId=1 count=1 element=Zagreb entry=CitiesCompanion(localId: Value.absent(), id: Value(48), createdAt: Value(2022-01-08 01:27:13.000Z), updatedAt: Value(2022-01-08 01:27:13.000Z), name: Value(Zagreb), location: Value(LatLng(45.8, 15.95)), country: Value(HRV), syncState: Value(S), isDeletedLocally: Value(false))
[log] table=Instance of '$CitiesTable' localId=2 count=1 element=null entry=CitiesCompanion(localId: Value.absent(), id: Value(48), createdAt: Value(2022-01-08 01:27:13.000Z), updatedAt: Value(2022-01-08 01:27:13.000Z), name: Value(Zagreb), location: Value(LatLng(45.8, 15.95)), country: Value(HRV), syncState: Value(S), isDeletedLocally: Value(false))
```

**Comment by simolus3** [comment]
Argh, another API oversight. The problem is that `insertReturning` returns a non-nullable row instance. When you use a `where` clause, it might be that the insert is not doing anything. In that case, there wouldn't be a row to return and you encounter this problem.

**Comment by mateoKutnjak** [comment]
> I have logged results after performing same query with `insert` (not `insertReturning`) and some strange situation happens.
> 
> Every time Insertable object is the same (`entry`) but after three times of correct behavior `insert` returns `localId` (PK) as 2 but row count stays 1. There is nothing written in row with `localId` with value 2 (`element` is just printing name of the city)
> 
> ```
> [log] table=Instance of '$CitiesTable' localId=1 count=1 element=Zagreb entry=CitiesCompanion(localId: Value.absent(), id: Value(48), createdAt: Value(2022-01-08 01:27:13.000Z), updatedAt: Value(2022-01-08 01:27:13.000Z), name: Value(Zagreb), location: Value(LatLng(45.8, 15.95)), country: Value(HRV), syncState: Value(S), isDeletedLocally: Value(false))
> [log] table=Instance of '$CitiesTable' localId=1 count=1 element=Zagreb entry=CitiesCompanion(localId: Value.absent(), id: Value(48), createdAt: Value(2022-01-08 01:27:13.000Z), updatedAt: Value(2022-01-08 01:27:13.000Z), name: Value(Zagreb), location: Value(LatLng(45.8, 15.95)), country: Value(HRV), syncState: Value(S), isDeletedLocally: Value(false))
> [log] table=Instance of '$CitiesTable' localId=1 count=1 element=Zagreb entry=CitiesCompanion(localId: Value.absent(), id: Value(48), createdAt: Value(2022-01-08 01:27:13.000Z), updatedAt: Value(2022-01-08 01:27:13.000Z), name: Value(Zagreb), location: Value(LatLng(45.8, 15.95)), country: Value(HRV), syncState: Value(S), isDeletedLocally: Value(false))
> [log] table=Instance of '$CitiesTable' localId=2 count=1 element=null entry=CitiesCompanion(localId: Value.absent(), id: Value(48), createdAt: Value(2022-01-08 01:27:13.000Z), updatedAt: Value(2022-01-08 01:27:13.000Z), name: Value(Zagreb), location: Value(LatLng(45.8, 15.95)), country: Value(HRV), syncState: Value(S), isDeletedLocally: Value(false))
> ```

Here I'm not using `where` clause. Because of that unexisting `localId` FK exception happens

Snippet:
```
int result = await into(_table).insert(
      entry,
      onConflict: DoUpdate.withExcluded(
        (old, excluded) {
          return onConflictCompanion(old: old, excluded: excluded);
        },
        target: [_table.columnsByName[DATATABLE_COLUMN_NAME_REMOTE_ID]!],
        // where: (old, excluded) => isDifferent(old, excluded),
      ),
    );

    int count = (await (select(_table)).get()).length;

    D? element = await (select(_table)..where((tbl) => _table.columnsByName[DATATABLE_COLUMN_NAME_LOCAL_ID]!.isValue(result))).getSingleOrNull();

    debugWhite('table=$_table localId=$result count=$count element=$element entry=$entry');
```

**Comment by simolus3** [comment]
The second observation is expected - at the moment, `insert` returns the most recent rowid. For upserts, that might not be the expected value. This is also mentioned in the [documentation](https://drift.simonbinder.eu/api/drift/insertstatement/insert):

> Returns the rowid of the inserted row. For tables with an auto-increment column, the rowid is the generated value of that column. The returned value can be inaccurate when onConflict is set and the insert behaved like an update.

I have added an `insertReturningOrNull` method in 929a554908e1146c4ad2ac6f861102a1b625fc34 that fixes this problem. It returns `null` when the insert didn't change anything instead of throwing a `StateError`. And it also doesn't update query streams when we know that no row has changed ;)
