### ISSUE TITLE
Easy way to determine if two rows have the same columns?

### ISSUE THREAD

**Issue by mateoKutnjak** [simolus3/moor#2302]
I have this method to help me determine whether old row and excluded row have same fields. I am using `insert` method with `DoUpdate.withExcluded` parameter which has `where` clause with `(old, excluded) => isDifferent(old, excluded)`

Is there any way to automatize the process? I am comparing almost all columns with same name of `old` with `excluded`. As this way is prone to logical errors that will be hard to detect, can this be done with looping through same-name columns? Maybe comparing them with something like `reduce` method while excluding some fields that we don't want to be compared?

More explanation is available in issue https://github.com/simolus3/drift/issues/2299#issue-1571171981. 

```
@override
  Expression<bool> isDifferent(Users old, Users excluded) {
    return (old.dateJoined.isExp(excluded.dateJoined) &
            old.email.isExp(excluded.email) &
            old.username.isExp(excluded.username) &
            old.username.isExp(excluded.username) &
            old.syncState.isExp(excluded.syncState) &
            old.isGuest.isExp(excluded.isGuest) &
            old.isVerified.isExp(excluded.isVerified) &
            old.isDeletedLocally.isExp(excluded.isDeletedLocally))
        .not();
  }
```

**Comment by simolus3** [comment]
You can always cast from a DSL table instance (`Users`) to the internal table object (`TableInfo`). This interface gives you full access to the columns defined in the table, which allows doing reflection over tables:

```dart
Expression<bool> isDifferent(Users old, Users excluded) {
  final oldTbl = old as TableInfo;
  final excludedTbl = excluded as TableInfo;

  return oldTbl.$columns
      .where((c) => true) // Skip columns you don't want to compare
      .map((column) {
        final excludedColumn = excludedTbl.columnsByName[column.name]!;

        return column.equalsExp(excludedColumn);
      })
      .reduce((a, b) => a & b)
      .not();
}
```
