### ISSUE TITLE
selectOnly has wrong method in its doc comment

### ISSUE THREAD

**Issue by ZhulanovAA** [simolus3/moor#2305]
`selectOnly` contains some weird method in its doc comment:

https://github.com/simolus3/drift/blob/94332a126f99f80d6e7ebb21308992e161d4398c/drift/lib/src/runtime/api/connection_user.dart#L220

Seems to be its name from some older version.

**Comment by simolus3** [comment]
Good catch, fixed in fe95c897206c3f6cdcea869d48aa4573e2fe4be9.
