### ISSUE TITLE
Documentation issue: Importing and exporting databases

### ISSUE THREAD

**Issue by YawarOsman** [simolus3/moor#2307]
This documentation not even run, it isn't clear and precise, please provide some perfect documentation like your others, for backing up the database.

**Comment by simolus3** [comment]
I agree that the documentation for backing up database files could be expanded. Can you share some more details that aren't unclear to you?

> This documentation not even run

The snippets listed on the documentation still look good to me, which error did you get while trying this out? I've also added backup and restore functionality to the example app in this repository in d30d2a1212b25f941aed15c42d810108abc612da, maybe that helps to get started?

**Comment by YawarOsman** [comment]
> I agree that the documentation for backing up database files could be expanded. Can you share some more details that aren't unclear to you?
> 
> > This documentation not even run
> 
> The snippets listed on the documentation still look good to me, which error did you get while trying this out? I've also added backup and restore functionality to the example app in this repository in [d30d2a1](https://github.com/simolus3/drift/commit/d30d2a1212b25f941aed15c42d810108abc612da), maybe that helps to get started?


i did exactly as you've done but while i copy the temp file to the database file it shows this on windows:
`FileSystemException: Cannot copy file to 'C:\Users\yawar\OneDrive\Documents\dragon.db', path = 'C:\Users\yawar\AppData\Local\Temp\import.db' (OS Error: Cannot create a file when that file already exists.`

**Comment by simolus3** [comment]
Does this happen for all files or is it some OneDrive weirdness? Because [`File.copy`](https://api.dart.dev/stable/2.19.2/dart-io/File/copy.html) says:

> If `newPath` identifies an existing file, that file is removed first. If `newPath` identifies an existing directory, the operation fails and the future completes with an exception.

If you add `await (await databaseFile).delete();` before the copy line, does that work?

**Comment by YawarOsman** [comment]
yes it still shows the same thing,

but now the error is in this line:
  backupDb
        ..execute('VACUUM INTO ?', [tempDb])
        ..dispose();

**Comment by YawarOsman** [comment]
it shows this error on restore the database, i also closed the db too:
```
FileSystemException: Cannot copy file to 'C:\Users\yawar\OneDrive\Documents\dragon.db', path = 'C:\Users\yawar\AppData\Local\Temp\import.db' (OS Error: Cannot create a file when that file already exists.
flutter: , errno = 183)
```

**Comment by khalilalilahmar** [comment]
@YawarOsman  
those are the functions i used .
`void importDatabase() async
  {
    FilePickerResult? result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ["sqlite"]
    );

    if (result != null) {
      File selectedFile = File(result.files.single.path!);
      print("file path ${selectedFile.path}");

      final dbFolder = await getApplicationDocumentsDirectory();
      final file = File(
          p.join(dbFolder.path, getUsername()! + 'crmpharma.sqlite'));
      await file.copy(p.join(
          dbFolder.path, "backup." + getUsername()! + 'crmpharma.sqlite'));
      var updatedDB = await selectedFile.readAsBytes();
      await file.writeAsBytes(updatedDB);

      await showMessage("Operation success", "Database imported successfully!");

      Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(builder: (context) =>
          SetupPage()), (Route<dynamic> route) => false);
    } else {
      // User canceled the picker
    }
  }`
`Future<void> exportDatabaseInto(File file) async {
    // Make sure the directory of the target file exists
    await file.parent.create(recursive: true);

    // Override an existing backup, sqlite expects the target file to be empty
    if (file.existsSync()) {
      file.deleteSync();
    }

    await customStatement('VACUUM INTO ?', [file.path]);
  }`

**Comment by khalilalilahmar** [comment]
@YawarOsman
those are the functions i used

 
Import
> void importDatabase() async
{
FilePickerResult? result = await FilePicker.platform.pickFiles(
type: FileType.custom,
allowedExtensions: ["sqlite"]
);
if (result != null) {
  File selectedFile = File(result.files.single.path!);
  print("file path ${selectedFile.path}");
  final dbFolder = await getApplicationDocumentsDirectory();
  final file = File(p.join(dbFolder.path, getUsername()! + 'crmpharma.sqlite'));
  await file.copy(p.join(dbFolder.path, "backup." + getUsername()! + 'crmpharma.sqlite'));
  var updatedDB = await selectedFile.readAsBytes();
  await file.writeAsBytes(updatedDB);
  await showMessage("Operation success", "Database imported successfully!");
  Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(builder: (context) =>SetupPage()), (Route<dynamic> route)=>false);
} else {
}
} 

Export
 
> Future exportDatabaseInto(File file) async {
  await file.parent.create(recursive: true);
if (file.existsSync()) {
  file.deleteSync();
}
await customStatement('VACUUM INTO ?', [file.path]);
}
