### ISSUE TITLE
@create does not work in modular builds

### ISSUE THREAD

**Issue by North101** [simolus3/moor#2313]
The function will generate as `special:0` which is not valid dart syntax.
https://github.com/simolus3/drift/blob/develop/drift_dev/lib/src/analysis/resolver/discover.dart#L134

With that fixed it'll fail to find the query in `input.importedQueries`
https://github.com/simolus3/drift/blob/develop/drift_dev/lib/src/writer/database_writer.dart#L172

**Comment by simolus3** [comment]
Thanks for the report! This should be fixed in 21ff422f19a003b20a08b56dc6bb1721865809b1.
