### ISSUE TITLE
Code generation won't work in files using new experemental records feature

### ISSUE THREAD

**Issue by ZhulanovAA** [simolus3/moor#2315]
In one of my DAOs I'm using the new record type and it seems code generator interprets it as a error in code. This is understandble, as it's still an experemental feature, but maybe it can be enabled without too much troubles?

To enable it in my project I've added
```
analyzer:
  enable-experiment:
    - records
```
to my `analysis_options.yaml`. Maybe something like this can be done for the code generator? I guess the problem is only with analyser and won't require any changes to the generation code. Currently I can bypass this issue by commenting out the function which uses records, generating code and then uncommenting it back.

**Comment by simolus3** [comment]
> In one of my DAOs I'm using the new record type and it seems code generator interprets it as a error in code.

Can you post the source code that causes the failure and the error message from running the build?

**Comment by simolus3** [comment]
Ah actually, I think you need to pass `--enable-experiment records` to `build_runner` for this to work in the builders - there is not much drift can do about that.

**Comment by ZhulanovAA** [comment]
Yes, you're right, this has solved the issue, wasn't drift related. Sorry, wasn't aware it is handeled on the `build_runner` side
