### ISSUE TITLE
Is there any how to log the sql operation errors?

### ISSUE THREAD

**Issue by henriqueArrazao** [simolus3/moor#2326]
I wanted to log the errors automatically in the Crashlytics. Something like this:

```
return NativeDatabase(
  File(
    customPath ?? p.join(directory.path, DBPaths.fileName),
  ),
  onError: (error, stackTrace) {           <<<----------------- (onError)
     FirebaseCrashlytics.instance.recordError(error, stackTrace);
  },
);
```

**Comment by simolus3** [comment]
Drift doesn't swallow errors, they should be reported through `get` or `watch()`. Do you have a setup that makes it hard to log the errors from there?

I don't oppose the `onError` callback on database implementations in general, but I also don't fully understand why we should report them twice.

**Comment by henriqueArrazao** [comment]
> Drift doesn't swallow errors, they should be reported through `get` or `watch()`. Do you have a setup that makes it hard to log the errors from there?
> 
> I don't oppose the `onError` callback on database implementations in general, but I also don't fully understand why we should report them twice.

Yeah, I will do it, just wanted to know it there's some way of doing this way. It would spare some error log calls.

**Comment by simolus3** [comment]
Thinking about this some more, there probably shouldn't be something like this built into drift - after all, drift returns the error in the higher-level operations. If we had a lower-level `onError` callback, I think it could lead to confusion on whether the error is handled twice.

If you think such a callback works better for your app, you can add it yourself. With this class, you can use `ErrorLoggingDatabase(NativeDatabase(...), FirebaseCrashlytics.instance.recordError)` for error handling.

```dart
import 'package:drift/backends.dart';

class ErrorLoggingDatabase implements QueryExecutor {
  final QueryExecutor inner;
  final void Function(Object, StackTrace) onError;

  ErrorLoggingDatabase(this.inner, this.onError);

  Future<T> _handleErrors<T>(Future<T> Function() body) {
    return Future.sync(body).onError<Object>(
      (error, stackTrace) {
        onError(error, stackTrace);
        throw error; // Rethrow
      },
    );
  }

  @override
  TransactionExecutor beginTransaction() {
    return _ErrorLoggingTransactionExecutor(inner.beginTransaction(), onError);
  }

  @override
  Future<void> close() {
    return _handleErrors(inner.close);
  }

  @override
  SqlDialect get dialect => inner.dialect;

  @override
  Future<bool> ensureOpen(QueryExecutorUser user) {
    return _handleErrors(() => inner.ensureOpen(user));
  }

  @override
  Future<void> runBatched(BatchedStatements statements) {
    return _handleErrors(() => inner.runBatched(statements));
  }

  @override
  Future<void> runCustom(String statement, [List<Object?>? args]) {
    return _handleErrors(() => inner.runCustom(statement, args));
  }

  @override
  Future<int> runDelete(String statement, List<Object?> args) {
    return _handleErrors(() => inner.runDelete(statement, args));
  }

  @override
  Future<int> runInsert(String statement, List<Object?> args) {
    return _handleErrors(() => inner.runInsert(statement, args));
  }

  @override
  Future<List<Map<String, Object?>>> runSelect(
      String statement, List<Object?> args) {
    return _handleErrors(() => inner.runSelect(statement, args));
  }

  @override
  Future<int> runUpdate(String statement, List<Object?> args) {
    return _handleErrors(() => inner.runUpdate(statement, args));
  }
}

class _ErrorLoggingTransactionExecutor extends ErrorLoggingDatabase
    implements TransactionExecutor {
  @override
  final TransactionExecutor transaction;

  _ErrorLoggingTransactionExecutor(
      this.transaction, void Function(Object, StackTrace) onError)
      : super(transaction, onError);

  @override
  Future<void> rollback() {
    return _handleErrors(transaction.rollback);
  }

  @override
  Future<void> send() {
    return _handleErrors(transaction.send);
  }

  @override
  bool get supportsNestedTransactions => transaction.supportsNestedTransactions;
}
```

**Comment by henriqueArrazao** [comment]
> Thinking about this some more, there probably shouldn't be something like this built into drift - after all, drift returns the error in the higher-level operations. If we had a lower-level `onError` callback, I think it could lead to confusion on whether the error is handled twice.
> 
> If you think such a callback works better for your app, you can add it yourself. With this class, you can use `ErrorLoggingDatabase(NativeDatabase(...), FirebaseCrashlytics.instance.recordError)` for error handling.
> 
> ```dart
> import 'package:drift/backends.dart';
> 
> class ErrorLoggingDatabase implements QueryExecutor {
>   final QueryExecutor inner;
>   final void Function(Object, StackTrace) onError;
> 
>   ErrorLoggingDatabase(this.inner, this.onError);
> 
>   Future<T> _handleErrors<T>(Future<T> Function() body) {
>     return Future.sync(body).onError<Object>(
>       (error, stackTrace) {
>         onError(error, stackTrace);
>         throw error; // Rethrow
>       },
>     );
>   }
> 
>   @override
>   TransactionExecutor beginTransaction() {
>     return _ErrorLoggingTransactionExecutor(inner.beginTransaction(), onError);
>   }
> 
>   @override
>   Future<void> close() {
>     return _handleErrors(inner.close);
>   }
> 
>   @override
>   SqlDialect get dialect => inner.dialect;
> 
>   @override
>   Future<bool> ensureOpen(QueryExecutorUser user) {
>     return _handleErrors(() => inner.ensureOpen(user));
>   }
> 
>   @override
>   Future<void> runBatched(BatchedStatements statements) {
>     return _handleErrors(() => inner.runBatched(statements));
>   }
> 
>   @override
>   Future<void> runCustom(String statement, [List<Object?>? args]) {
>     return _handleErrors(() => inner.runCustom(statement, args));
>   }
> 
>   @override
>   Future<int> runDelete(String statement, List<Object?> args) {
>     return _handleErrors(() => inner.runDelete(statement, args));
>   }
> 
>   @override
>   Future<int> runInsert(String statement, List<Object?> args) {
>     return _handleErrors(() => inner.runInsert(statement, args));
>   }
> 
>   @override
>   Future<List<Map<String, Object?>>> runSelect(
>       String statement, List<Object?> args) {
>     return _handleErrors(() => inner.runSelect(statement, args));
>   }
> 
>   @override
>   Future<int> runUpdate(String statement, List<Object?> args) {
>     return _handleErrors(() => inner.runUpdate(statement, args));
>   }
> }
> 
> class _ErrorLoggingTransactionExecutor extends ErrorLoggingDatabase
>     implements TransactionExecutor {
>   @override
>   final TransactionExecutor transaction;
> 
>   _ErrorLoggingTransactionExecutor(
>       this.transaction, void Function(Object, StackTrace) onError)
>       : super(transaction, onError);
> 
>   @override
>   Future<void> rollback() {
>     return _handleErrors(transaction.rollback);
>   }
> 
>   @override
>   Future<void> send() {
>     return _handleErrors(transaction.send);
>   }
> 
>   @override
>   bool get supportsNestedTransactions => transaction.supportsNestedTransactions;
> }
> ```

Perfect, thank you!!!
