### ISSUE TITLE
Exceptions don't propagate from beforeOpen callback

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#233]
If an exception is thrown in the `beforeOpen` callback, I can't seem to catch it in a Flutter widget. For example, after making the following changes to the `moor_flutter` example project:
```dart
// main.dart
@override
void initState() {
  bloc = TodoAppBloc();
  _start();
  super.initState();
}
Future<void> _start() async {
  try {
    await bloc.query();
  }
  catch (e) {
    print('here');
  }
}

// bloc.dart
Future<void> query() async {
  await db.customSelectQuery("select 1").get();
}

// database.dart
beforeOpen: (details) async {
  throw Exception('catch me if you can: beforeOpen');
}
```

`here` is never printed. However if I throw the exception in `bloc.query()`:
```dart
Future<void> query() async {
  await db.customSelectQuery("select 1").get();
  throw Exception('catch me if you can: bloc');
}
```
the message is printed. I'm not able to reproduce it with a unit test though:
```dart
test("exceptions in beforeOpen are caught", () async {
  try {
    final db = MyDatabase(VmDatabase.memory());
    await db.customSelectQuery("select 1").get();
  }
  catch (e) {
    print('here');
  }
});
```
This prints `here` as expected. Any idea what's going on here? It seems related to #216 so I tried to see if it would be fixed with ed4d69a79208fd8086d713e140d445a4a8d39cf1 ~but can't due to extension methods on `develop`~ looks like the flutter beta channel has dart 2.6 support so I was able to try it out - issue still happens on `develop`.

**Comment by simolus3** [comment]
Thanks, I was able to reproduce this on develop. I think that this section is to blame: https://github.com/simolus3/moor/blob/b0a9255a075530b0f8ccc4ad6ee68a3d913b5867/moor_flutter/example/lib/bloc.dart#L38-L49

The microtask subscribing to that stream is scheduled before `bloc.query()`, so listening to that stream is the first database operation that will open the database and run the `beforeOpen` callback. In that case, we should probably add an error to the stream.

**Comment by Mike278** [comment]
I don’t have the code in front of me atm, but in our app I don’t think the first query is a stream. Could it be because the beforeOpen callback is run in a different zone?

**Comment by simolus3** [comment]
In my understanding, running them in a different zone won't have an effect on the error if we return a `Future` and await that future in the top-level zone. This is how we catch exceptions for transactions as well without loosing the stacktrace.

After removing the stream subscription from the bloc constructor, I was able to catch the error thrown in `onOpen` in a try block around `customSelectQuery`. Could it be that you're running some unawaited operation in your `onOpen` callback that throws the error? We can't catch those with our current zone setup.

I played around with some different approaches to catch errors in zones, and to me it looks like moor's current strategy works best for us, the only downside being that we can't deal with unhandled exceptions inside the `runZoned` body.
```dart
import 'dart:async';

void likeMoorDoesIt() async {
  try {
    await runZoned(() async {
      throw 'zoned error';
    });
  } catch (_) {
    // will be caught here! We can get the stacktrace of `throw 'zoned error'`, but not the stacktrace
    // that called likeMoorDoesIt()
    print('Caught the exception!');
  }
}

void moorButWithOnError() async {
  try {
    await runZoned(() async {
      throw 'zoned error';
    }, onError: (e) => print('caught in on error'));
  } catch (_) {
    // we'll never get here, and the original stack trace can't be rethrown in onError
    print('Caught the exception!');
  }
}

void notCaught() {
  try {
    runZoned(() {
      scheduleMicrotask(() => throw 'zoned error');
    });
  } catch (_) {
    // won't be caught
    print('Caught the exception!');
  }
}
```

**Comment by Mike278** [comment]
Hmm gotcha - it's definitely stream related then. The first query to open the database in our app actually is a stream method, but it calls `.first`.

```dart
Future<void> query() {
  return _db.customSelectQuery('select 1').get();
}

Future<void> queryStream() {
  return _db.customSelectQuery('select 1').watch().first;
}
```
If `query()` is used to open the database, the exception is caught as expected, but if `queryStream()` is used the exception is not caught. 
I think we'll just move our `beforeOpen` code to its own method and call it explicitly after instantiating the database so that it's clear when initialization happens and where init-related errors should be caught.

**Comment by simolus3** [comment]
> but if `queryStream()` is used the exception is not caught.

Moor should do something about that, we can emit the error on the stream so that `first` would throw. 

I'm not aware of a good way to make errors (in particular, stack traces) work across zones unfortunately. Extracting the `beforeOpen` logic and taking care of not calling anything else before it completes might be the best idea if you have complicated logic in there.

**Comment by Mike278** [comment]
Ah sorry, by 
> In that case, we should probably add an error to the stream.

I thought you meant update the example project to do that. 

Would it be possible to cherry-pick this fix to master? We use stream queries almost exclusively.

**Comment by simolus3** [comment]
067212e66c9e63832b053ce3739382a47bc26102 is on master now, but I think releasing a hotfix to pub isn't necessary here.
