### ISSUE TITLE
Getting a Dart list from a subquery: is it possible with the Dart API?

### ISSUE THREAD

**Issue by jjoelson** [simolus3/moor#2341]
Hi all, and thank you for this great package!

I came across [this issue](https://github.com/simolus3/drift/issues/1634) which led to the addition of a `LIST(...)` syntax that provides the results of subquery as a Dart list. This feature is extremely useful! I was wondering, is there a way to achieve a similar effect when writing a query using the Dart API? I'd love to be able to write a query like this (using the same profile/image example as the linked issue):
```
final query = select(profiles).addColumns([
  list(select(images)..where(images.uuid.equalsExp(profiles.uuid)))
]);
```
I prefer to use the Dart API as much as possible, but I must admit I keep running into scenarios that require switching to manually-written SQL.

**Comment by simolus3** [comment]
Nice idea, I agree that this would be neat. The `LIST` column in SQL requires scanning dependencies and replacing them with variables. In the query you've posted, we'd first have to run a select on `profiles` and then run an inner select for every row in `profiles` that does `SELECT * FROM images WHERE uuid = ?`, with `?` being expanded to the row that we get. To do this dynamically at runtime, we probably need more information exposed in the select statements to see which columns or references are used.

Having this built in is definitely a big improvement over the [current way to do this in Dart](https://drift.simonbinder.eu/docs/examples/relationships/), but it looks like a lot of work to implement.

**Comment by jjoelson** [comment]
Thanks for pointing me to that example, I had missed that in the docs!
