### ISSUE TITLE
Experimental IDE enabled but nothing happening in editor

### ISSUE THREAD

**Issue by austinried** [simolus3/moor#2342]
I'm trying to get the IDE integration working but it doesn't seem to do anything at all for me. I've followed the guide and have enabled the plugin in my analysis options and added the line to my settings.json, but it acts like I've done nothing at all. I get no extra completion in .drift files, no warnings from the analyzer when my SQL syntax is off, etc.

I can run `dart run drift_dev analyze` which take a pretty long time (maybe 10-20 seconds), but then does work and gives me errors about syntax. Not sure if it matter but I'm using VS Codium.

```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.7, on Ubuntu 22.04.2 LTS 5.15.0-60-generic, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2022.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by simolus3** [comment]
Thanks for the report. Unfortunately, the analysis plugin is not currently functional. It has never worked reliably and caused some painful dependency issues in the past. So, after recent refactoring in `drift_dev` that would have required to re-implement the plugin from scratch, I've decided that's it not worth it for now.

Sorry for the disappointing resolution, I'll add a note to the website describing the current state.

> but then does work and gives me errors about syntax

Could you post the errors? If they're false-positives, there's probably something else going on that I should look at. The CLI analyzer should still work.

**Comment by austinried** [comment]
Ah I see, that is disappointing. The errors were good though, I was just testing to see if it was picking anything up by removing a trailing comma here and there and it seemed fine. Actual compilation of my drift file is working great.
