### ISSUE TITLE
Another way to backup

### ISSUE THREAD

**Issue by SungHyun22** [simolus3/moor#2348]
I did implement backup diffrent way. The document recommend using VACUUM. But Instead I using readAsBytes() & writeAsBytes. It work well. But I'm afraid I've broken what you intended. Is that okay to using this way?

I'm outside now so I can't attach example code. If you want some example code than I'll attach it later.

Thank you for good library 😁

**Comment by FaFre** [comment]
When using `VACUUM`, the database is getting repacked by sqlite and will be most probably optimized in size. However, you won't break anything by copying the file bitwise like you described. There is nothing wrong with that as long as the database is not in use. Close all handles before doing the copy.

**Comment by SungHyun22** [comment]
@FaFre Thank you for answer!

I have one more question. You mean I should close the database before using readAsBytes()?

**Comment by FaFre** [comment]
Well, when you actively use the database its strongly adviced to use VACUUM. You can find a `backup` method when using the native database connection via the sqlite package. Im not sure if this is getting exposed through drift tho. This would make your life easier. 

When doing bitwise copy the database must be closed. You dont want to copy the database in an unsafe state.

**Comment by SungHyun22** [comment]
@FaFre Thank you 😄
