### ISSUE TITLE
drift is not compatible with `cli_util`  0.4.0

### ISSUE THREAD

**Issue by Yesterday17** [simolus3/moor#2354]
**Describe the bug**

I'm upgrading dependency version in my project and found that `ffigen v7.2.9` is incompatible with `drift_dev` because drift requires `cli_util < 0.4.0`.

> Because ffigen >=7.2.8 depends on cli_util ^0.4.0 and drift_dev 2.5.2 depends on cli_util >=0.2.0 <0.4.0, ffigen >=7.2.8 is incompatible with drift_dev 2.5.2.
> And because no versions of drift_dev match >2.5.2 <3.0.0, ffigen >=7.2.8 is incompatible with drift_dev ^2.5.2.
So, because annix depends on both drift_dev ^2.5.2 and ffigen ^7.2.9, version solving failed.

According to the [CHANGELOG](https://github.com/dart-lang/cli_util/blob/master/CHANGELOG.md), it seems that `cli_util` only replaced `getSdkDir` with `getSdkPath`. So I guess it should be simple to upgrade?

**Comment by simolus3** [comment]
Thanks for the report, `drift` 2.6.0 is compatible with the latest `cli_util`.
