### ISSUE TITLE
The source must not have an AS alias when used in a trigger

### ISSUE THREAD

**Issue by spauldhaliwal** [simolus3/moor#2360]
Adding this statement to my drift file throws `The source must not have an AS alias when used in a trigger.`:

```sql
CREATE TRIGGER queue_library_refresh_media AFTER INSERT
ON library_refresh_queue
BEGIN
INSERT INTO library_refresh_media_queue (parent_job_id, media_id, library_id, title, created_at)
SELECT new.job_id, m.media_id, m.library_id, m.title, UNIXEPOCH()
FROM medias m
WHERE m.library_id = new.library_id AND m.server_id = new.server_id;
END;
```
As far as I understand, the above statement is valid. Is this a limitation with Drift only?

Removing the alias gets rid of the error, however it should work with the alias as well.

**Comment by simolus3** [comment]
This is indeed a false-positive error in our SQL analyzer. The intention was that something like `DELETE FROM table AS foo` is forbidden in triggers and should get lints. The implementation complains about any table reference with an alias in a trigger statement though, which unfortunately also matches subqueries.

I've fixed this in c38e9cc6c035527e85e6fe32a383ee2fa7a34afa.
