### ISSUE TITLE
Add an option to annotate generated methods (select, into,etc.) as. protected

### ISSUE THREAD

**Issue by gaetschwartz** [simolus3/moor#2361]
**Is your feature request related to a problem? Please describe.**
To help ensure that all database operations are done by `MyDatabase` and not somewhere else by using `myDb.into(...)`.

**Describe the solution you'd like**
 It would be useful to be able to annotate all these generated methods as protected.

**Comment by simolus3** [comment]
I see that you likely have a different opinion about this, but I don't really see a good reason to change the current behavior. These methods aren't generated, they're part of the core APIs in the `drift` package, and so we can't make them `@protected` without breaking existing users.

It's not like anything in drift would break when these methods are used outside of the generated class, so a restriction in visibility feels like an artificial constraint I'd be putting on users. I don't think drift actively encourages bad practices by having these methods public. In the end, it's your responsibility: If you want clean code, write clean code ;)

If you want that degree of encapsulation in your app, I think the best way would be to extract the methods into a common interface, perhaps something like

```dart
abstract class UserRepository {
  Future<User?> getById(...);
}

@DriftDatabase(...)
class MyDatabase extends _$MyDatabase implements UserRepository {
  // ...
}
```

Then, you could setup your service locator or state management approach to keep `MyDatabase` hidden and make other parts just rely on the abstract `UserRepository` (or more) interfaces? [This more complex example](https://github.com/rodydavis/clean_architecture_todo_app/blob/main/lib/data/source/database/database.dart) also illustrates the idea.

**Comment by gaetschwartz** [comment]
Fair enough, thanks for your opinion on the matter ! I agree on that aspect actually, I somehow thought the methods were generated and didn't see they were core drift API :)
