### ISSUE TITLE
Drift encryption

### ISSUE THREAD

**Issue by Harishwarrior** [simolus3/moor#2368]
Drift encryption not working in iOS. I followed this guide:
https://github.com/simolus3/drift/tree/develop/examples/encryption

When app is launching
```
(lldb) warning: libobjc.A.dylib is being read from process memory. This indicates that LLDB could not find the on-disk shared cache for this device. This will likely reduce debugging performance.
iOS Observatory not discovered after 30 seconds. This is taking much longer than expected...
process interrupt
error: Failed to halt process: Halt timed out. State = running
* thread #1, stop reason = trace
    frame #0: 0x0000000104600e38 dyld`lldb_image_notifier(dyld_image_mode, unsigned int, dyld_image_info const*) + 188
dyld`lldb_image_notifier:
->  0x104600e38 <+188>: ldur   x8, [x29, #-0x28]
    0x104600e3c <+192>: adrp   x9, 64
    0x104600e40 <+196>: add    x9, x9, #0x308            ; __stack_chk_guard
    0x104600e44 <+200>: ldr    x9, [x9]
Target 0: (Runner) stopped.
```

When trying to insert data
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field 'versionDelegate' has not been initialized.
#0      Sqlite3Delegate.versionDelegate (package:drift/src/sqlite3/database.dart)
database.dart:1
#1      DelegatedDatabase._runMigrations
engines.dart:432
#2      DelegatedDatabase.ensureOpen.<anonymous closure>
engines.dart:426
<asynchronous suspension>
#3      InsertStatement.insert
insert.dart:73
<asynchronous suspension>
#4      MyDatabase.insertInspectionForm
database.dart:47
<asynchronous suspension>
#5      _MyHomePageState.insertData
main.dart:46
<asynchronous suspension>
```

**Comment by Harishwarrior** [comment]
Fixed by following this guide:

https://stackoverflow.com/a/75319824

**Comment by simolus3** [comment]
Glad to hear you got it working. For your reference, there may also be incompatibilities with `sqlcipher_flutter_libs` and other packages that may link the normal sqlite3. If you haven't checked this already, consider the advisories [listed here](https://github.com/simolus3/sqlite3.dart/tree/main/sqlcipher_flutter_libs#incompatibilities-with-sqlite3-on-ios-and-macos).

**Comment by Harishwarrior** [comment]
> Glad to hear you got it working. For your reference, there may also be incompatibilities with `sqlcipher_flutter_libs` and other packages that may link the normal sqlite3. If you haven't checked this already, consider the advisories [listed here](https://github.com/simolus3/sqlite3.dart/tree/main/sqlcipher_flutter_libs#incompatibilities-with-sqlite3-on-ios-and-macos).

Thanks for the package 😀
