### ISSUE TITLE
Inconsistent behavior on first INSERT after CREATE TABLE.

### ISSUE THREAD

**Issue by knyghtryda** [simolus3/moor#237]
I ran into a strange issue where my inserts seem to be getting triggered before the table has had a chance to be created.  This only happened on an iOS build, as my Android build handled everything just fine.  I would get a table not found error followed by the create table query in the logs.  What was strange was that I fixed this problem by reordering how the tables are initialized in the `@UseMoor` header.  If I'm trying to insert into `table3` my previous order was `[table1, table2, table3]` but by reordering it to `[table3, table1, table2]` my inserts would complete correctly.  Whats going on here?

**Comment by simolus3** [comment]
Moor should keep the database locked until all tables were created and the order of tables shouldn't matter here. The issue you're describing sounds like some race condition though.
Can you verify that you're 100% not opening the same database twice? E.g if you have a `class Database extends _$MyDatabase`, are you sure that you only create one instance of `Database`?

**Comment by knyghtryda** [comment]
All my database interactions go through a top level provider (more specifically a top level DAO) and I have `singleInstance: true`

**Comment by simolus3** [comment]
I don't have an iPhone to test things at the moment, but can you reproduce the problem with the following snippet? I'm trying to make the database creation really slow, so if there's some kind of bug with the locking mechanism it should be triggered here.
```dart
// lib/repro.dart
import 'package:flutter/widgets.dart' hide Table;
import 'package:moor_flutter/moor_flutter.dart';

part 'repro.g.dart';

class FirstTable extends Table {
  IntColumn get id => integer().autoIncrement()();
}

class SecondTable extends Table {
  IntColumn get id => integer().autoIncrement()();
}

class ImportantTable extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get content => text()();
}

@UseMoor(tables: [FirstTable, SecondTable, ImportantTable])
class MyDatabase extends _$MyDatabase {
  MyDatabase()
      : super(FlutterQueryExecutor.inDatabaseFolder(
            path: 'repro_237.db', logStatements: true));

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(onCreate: (m) async {
      // create the tables, but very slowly
      for (var table in allTables) {
        await m.createTable(table);
        await Future.delayed(const Duration(seconds: 3));
      }
    });
  }
}

void main() {
  runApp(Container());

  final db = MyDatabase();
  // spam the database with concurrent insert statements
  Future.wait(Iterable.generate(100, (_) {
    return db
        .into(db.importantTable)
        .insert(ImportantTableCompanion.insert(content: 'content'));
  }));
}
```

**Comment by knyghtryda** [comment]
Just tested your example on the simulator.  The inserts are working fine.  I'm going to test my code again with the original table order and see if the problem comes back.  Let me know what other info you might need to diagnose this further.

**Comment by simolus3** [comment]
Thanks for testing it out, I'll also try to do some further diagnosis on an iPhone next week.

I'll definitely keep looking for bugs in moor, but maybe you can add an assertion into your app to ensure that the database is only opened once:
```dart
@UseMoor(...)
class YourDatabase extends _$YourDatabase {
  static int _timesOpened = 0;

  YourDatabase(): 
    assert(_timesOpened == 0),
    super(FlutterQueryExecutor...) {
     _timesOpened++;
   }  
}
```

Note than setting the `singleInstance` parameter on the `FlutterQueryExecutor` will not necessarily help here. That parameter would make two different moor databases on the same file re-use the underlying connection, but the opening-locks are independent from each other which causes all kinds of race conditions.

**Comment by knyghtryda** [comment]
You were right to begin with, it was a race condition.  I was using the database class once in the provider and once again (doh!) in my state class.  Probably safe to close this unless there's any merit in investigating why this seems to be an iOS only issue.

**Comment by simolus3** [comment]
Maybe Android was faster to create the third table, but I don't think doing further analysis is necessary here. That said, maybe moor could detect multiple instances of the same database being open and print a warning in that case.
