### ISSUE TITLE
Access encrypted database in native code

### ISSUE THREAD

**Issue by Harishwarrior** [simolus3/moor#2371]
I am working on an app where we are inserting large amount of data via method channel for performance reasons. The database is created and initialized using drift and sqlcipher_flutter_libs method mentioned in the documentation. The DB can be opened using this library https://www.zetetic.net/sqlcipher/sqlcipher-for-android/

But, the problem is when I try to insert data in table created via drift. It throws an error "TABLE NOT FOUND".

Can you please provide an insight on this?

**Comment by simolus3** [comment]
Well, does the database contain the affected table? Are you first opening the database in drift or on the native side? If you're doing it one the native side and set the `application_version` pragma on the database, it may be that drift doesn't consider the database uninitialized and skips the table creation steps.

**Comment by Harishwarrior** [comment]
> Well, does the database contain the affected table? Are you first opening the database in drift or on the native side? If you're doing it one the native side and set the `application_version` pragma on the database, it may be that drift doesn't consider the database uninitialized and skips the table creation steps.

1. Yes, the DB contains the affected table. I copied the table and opened it using DBrowser for SQlite and it has the table. I also checked the table name.

2. The drift opens the DB first and on the press of a button it calls the native code which opens the encrypted db and tries to insert the data to the table. I also confirmed the path was correct.

I'll share a reproducible code in a few hours.

**Comment by Harishwarrior** [comment]
I found the issue. I hardcoded the path the DB before it worked fine. But, in android studio i got a suggestion to use 

```kotlin
   private val sqliteDBPath: String = context.getDatabasePath("app.db.enc").absolutePath  // <-- this
   
   val sqliteDBPath = "/data/user/0/com.example.drift_poc/databases/app.db.enc" // <-- instead of this
```
I blindly applied it. Reverting this fixed the issue.

Also, I got another issue while updating the code to use encryption and the error message wasn't clear at first glance.

```
LateError (LateInitializationError: Field 'versionDelegate' has not been initialized.) 
```

Finally i found the solution for this after reading the encryption documentation
```dart
QueryExecutor _openDatabase() {   // <-- here i accidentally used LazyDatabase as the return type 
  return LazyDatabase(() async {
    final path = await getApplicationDocumentsDirectory();
    return NativeDatabase(
      File(p.join(path.path, 'app.db.enc')),
      setup: (db) {
        final result = db.select('pragma cipher_version');
        if (result.isEmpty) {
          throw UnsupportedError(
            'This database needs to run with SQLCipher, but that library is '
            'not available!',
          );
        }
        final escapedKey = _encryptionPassword.replaceAll("'", "''");
        db.execute("pragma key = '$escapedKey'");
      },
    );
  });
}
```

My suggestion is to improve the error message.. @simolus3

**Comment by simolus3** [comment]
The return type of `_openDatabase` shouldn't make a difference, and it certainly shouldn't cause the `LateInitializationError`.

My guess is that you're accessing the database from some place that drops exceptions. When `setup` throws an exception, it will be reported to the first one who used the database. Subsequent database accesses will get the `LateError`.
I've changed that in 39645f669c44d5bb68b4ec5e0d4ca8b784363619 so that we call `setup` multiple times if earlier invocations fail. That should improve the error message to avoid the late error here.
