### ISSUE TITLE
[drift_dev] Database is not closed after `validateDatabaseSchema`

### ISSUE THREAD

**Issue by MichaelDarkMostIo** [simolus3/moor#2380]
Since `_GenerateFromScratch` extends `GeneratedDatabase`, it is calling `_handleInstantiated` in its super constructor.
`_handleInstantiated` is checking the number of opened database instances.

`_GenerateFromScratch` must be closed after the verification.

https://github.com/simolus3/drift/blob/cb32b3418b5da778ec0b256afc9847f1ee80d19c/drift_dev/lib/api/migrations.dart#L103

**Comment by MichaelDark** [comment]
@simolus3 Found out that it is already fixed in https://github.com/simolus3/drift/commit/d6e074e7044f617d84485dbd861eddcaf9e88a12. 

Waiting for `2.7.0` 🍺 🎉

**Comment by simolus3** [comment]
Just published!
