### ISSUE TITLE
CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0

### ISSUE THREAD

**Issue by stx** [simolus3/moor#2384]
After migrating to `WasmSqlite3.loadFromUrl`, occasionally getting the below error in Sentry on production on Chrome.

```
Error: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0
```

Implementation:

```
Future<Database> openDatabase({bool logStatements = false}) async {
  IndexedDbFileSystem fs = await IndexedDbFileSystem.open(dbName: 'db');

  WasmSqlite3 sqlite = await WasmSqlite3.loadFromUrl(
    Uri.parse('sqlite3.wasm'),
    environment: SqliteEnvironment(fileSystem: fs),
  );

  return Database(
    WasmDatabase(
      sqlite3: sqlite,
      path: '/app.db',
      logStatements: logStatements,
    ),
  );
}
```

**Comment by simolus3** [comment]
If we interpret the first bytes as utf8, `3c 21 44 4f` is `<!DO` - which sounds like you're serving HTML at a wasm URL.

If that's what's happening here, it would also explain #2388, #2385 and https://github.com/simolus3/sqlite3.dart/issues/128.

**Comment by stx** [comment]
Brilliant insight! It's just a normal static file in the root directory of a Firebase Hosting project. I wonder if this is some form of rate limiting, or ad/JS blocking.

**Comment by simolus3** [comment]
It could also be Flutter's service worker doing something odd, I'll have to check. But since these issues are all very similar and probably have the same root cause, let's keep the analysis in the original issue (https://github.com/simolus3/sqlite3.dart/issues/128).
