### ISSUE TITLE
TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

### ISSUE THREAD

**Issue by stx** [simolus3/moor#2388]
After migrating to `WasmSqlite3.loadFromUrl`, occasionally getting the below error in Sentry on production on Chrome.

```
TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
```

Implementation:

```
Future<Database> openDatabase({bool logStatements = false}) async {
  IndexedDbFileSystem fs = await IndexedDbFileSystem.open(dbName: 'db');

  WasmSqlite3 sqlite = await WasmSqlite3.loadFromUrl(
    Uri.parse('sqlite3.wasm'),
    environment: SqliteEnvironment(fileSystem: fs),
  );

  return Database(
    WasmDatabase(
      sqlite3: sqlite,
      path: '/app.db',
      logStatements: logStatements,
    ),
  );
}
```

**Comment by simolus3** [comment]
Thanks for trying this out! It's weird that is haopens occasionally, but couldn't this be an issue with your server / CDN?

If it's a public app, could you share the link for me to look at? I'll try to reproduce this as well, but it doesn't sound like a kind of error a browser would make up, and we're not modifying the response in drift/sqlite3.dart.

**Comment by stx** [comment]
@simolus3 Sent you a friend request on Discord so I can share some things with you.

Re: CDN - it's Firebase Hosting and it reports application/wasm as the content type.

**Comment by simolus3** [comment]
Closing to bundle the discussion/analysis in https://github.com/simolus3/sqlite3.dart/issues/128.
