### ISSUE TITLE
Caching prepared statements

### ISSUE THREAD

**Issue by FaFre** [simolus3/moor#2390]
At the moment all statements are compiled just before they are getting executed. By caching the compiled statements we can get some performance benefit, especially for frequently executed ones and batches. Are there some arguments against this behavior?

**Comment by simolus3** [comment]
> especially for frequently executed ones and batches

Inside a batch, multiple occurrences of the same statement are already "cached" in the sense that they're only prepared once. So if you run the same insert 10k times in a batch, we will still only prepare the statement once.

I don't really see a strong argument against caching statements (in particular, for selects used in query streams). But maybe a first step is to add profiling instrumentation in drift to see where most of the time is spent? At the moment I don't really have a good end-to-end overview of how much time is spent in the query builder, the actual database implementation and the interpretation of results.

I've added some simple timeline events on the `performance-tracing` to branch to start the investigation, but contributions to add a cache or to help with tracing in drift are definitely welcome :)

**Comment by davidmartos96** [comment]
I could find some use for prepared statements as well.
Say a grid in Flutter that queries the database per each item to gather additional information asynchronously.
Caching the prepared statements could be nice, but some kind of native-backed PreparedStatement in the drift API could work as well. For the latter, the user would need to dispose the prepared statement when is not needed anymore. 

Regarding caching, what could be a good mechanism for invalidating it? In memory map with a timestamp?
