### ISSUE TITLE
IIF is not supported

### ISSUE THREAD

**Issue by JCKodel** [simolus3/moor#2392]
```console
[WARNING] drift_dev:modular on lib/data/companies.drift:
line 59, column 19: Function IIF could not be found
   ╷
59 │   SET isCurrent = IIF(companyId = :companyId, 1, 0)
```

`IIF` statement is not supported.

SQLite introduced the `IIF()` function since version 3.32.0.

**Comment by simolus3** [comment]
Thanks for the report, I've implemented analysis support for that function now.
