### ISSUE TITLE
Unable to use a partial index with insert() and `onConflict`

### ISSUE THREAD

**Issue by adg-mh** [simolus3/moor#2394]
In SQLite, the [ON CONFLICT](https://www.sqlite.org/lang_UPSERT.html) clause has two places to include a WHERE clause. The first one (after the column list) is used to select a specific partial index to use for detecting conflicts.

From looking at the code [here](https://github.com/simolus3/drift/blob/11b563f9de5fff357b12f0052df01e86baf662ca/drift/lib/src/runtime/query_builder/statements/insert.dart#L268) I can only see a way to add the second WHERE clause, so I'm unable to use a column with a partial index to do an upsert. See example below.

Thanks,

<details>
<summary>Example SQL</summary>

```sql
CREATE TABLE Two (lookup INT, data TEXT);
CREATE UNIQUE INDEX idxu_two_lookup ON Two(lookup) WHERE lookup IS NOT NULL;
INSERT INTO Two VALUES (NULL, 'aaa'), (999, 'bbb');

-- this will fail
-- ON CONFLICT clause does not match any PRIMARY lookup or UNIQUE constraint.
INSERT INTO Two (lookup, data) VALUES (999, 'zzz')
ON CONFLICT (lookup) DO UPDATE SET data = 'zzz';

-- this will succeed
INSERT INTO Two (lookup, data) VALUES (999, 'zzz')
ON CONFLICT (lookup) WHERE lookup IS NOT NULL DO UPDATE SET data = 'zzz';
```
</details>

**Comment by simolus3** [comment]
Good point, I've added a parameter generating the first `WHERE` clause in 6c9c3d068689f376b2a3e42508b4ac5b9b1a8ae4.
