### ISSUE TITLE
Improve error messages on misspelled items

### ISSUE THREAD

**Issue by JCKodel** [simolus3/moor#2396]
In a `.drift` file, I wrote this query:

```sql
getCompanyCustomersCount:
  SELECT COUNT(*) AS "count"
  FROM Customers AS c
  INNER JOIN Customer_Companies AS cc
    ON cc.customerId = c.id AND cc.companyId = :companyId;
```

Builder gave me this error:

```console
[WARNING] drift_dev:analyzer on lib/data/customers.drift:
Could not analyze DriftElementId(package:xxx/data/customers.drift, getCompanyCustomersCount)
Bad state: No element
```

Cause: the table is named Customer**s**_Companies. (notice the extra S)

I'm guessing there is a list of tables that the parser is searching with `.where` and, when not found, it just throws a generic `No element` error.

It would be nicer if the parser, at least, said:

```console
[ERROR] drift_dev:analyzer on lib/data/customers.drift:
Could not analyze DriftElementId(package:xxx/data/customers.drift, getCompanyCustomersCount)
Element not found: Customer_Companies
```

Even without any line number, it would be A LOT simpler to catch mistakes like that.

**Comment by simolus3** [comment]
Somewhat ridiculously, this actually happened because the table references are unresolved _and not entirely in lower-case_. The whole logic responsible for handling that looks pretty shady, I've fixed the error in 5caa948243c2a2d2d5c3ee542886e98fbc03f697.
