### ISSUE TITLE
Link on Drift Pub Page

### ISSUE THREAD

**Issue by acuba001** [simolus3/moor#2398]
**Describe the bug**:

- what you were trying to do: I arrived at https://pub.dev/packages/drift and saw a link "Try the Flutter Chat Tutorial  💬". I clicked the linked to try out the flutter tutorial.
- what you would have expected to happen: I expected to arrive at a webpage with a Drift tutorial with Flutter.
- what actually happened: I arrived at a webpage titled "Android Chat SDK - Kotlin Messaging SDK"

Looking at the Moore documentation at https://pub.dev/documentation/moor/latest/, there is a similar link, but this one actually  goes to a Flutter tutorial. I presume this was the intended effect. Correct me if I am wrong.

**Comment by simolus3** [comment]
Thanks, I see how the links aren't that clear at the moment. getstream.io, who are sponsoring this project, asked me to put them in the readme. I've reached out to them to see if the links should be updated and I'll fix them when I get a response.
