### ISSUE TITLE
Custom row class constructor in drift files

### ISSUE THREAD

**Issue by FaFre** [simolus3/moor#2399]
For `Table` we have an annotation to define a constructor  for custom row classes: https://drift.simonbinder.eu/docs/advanced-features/custom_row_classes/#using-another-constructor

From my research it is not possible to do this right now in combination with the `WITH` keyword in drift files, for table definitions, queries, etc.

Maybe we can make an annotation for the custom row class available to define the constructor to use there directly why can be consumed by the generator.

**Comment by simolus3** [comment]
Good call, I've added support for named constructors in 6bb2c3d2c5438c1bb61082b50217f41bac2e0fab.
