### ISSUE TITLE
How to change constructor when using drift file

### ISSUE THREAD

**Issue by AliEasy** [simolus3/moor#2406]
When using custom row classes, according to [docs](https://drift.simonbinder.eu/docs/advanced-features/custom_row_classes/#using-another-constructor) it is possible to define a custom constructor and use it instead of unnamed one .
How to manage to do that in case the table is being created by `.drift` file

**Comment by FaFre** [comment]
Use develop branch to have this right now: #2399

**Comment by simolus3** [comment]
Yes, this has been implemented but not released yet. Closing this as a duplicate.

**Comment by AliEasy** [comment]
@simolus3 Actually Im in middle of migrating to drift. Is it possible to release only this feature right away?!

**Comment by FaFre** [comment]
You can just switch to the development branch for your migration and change to the release at a later point: (https://dart.dev/tools/pub/dependencies#git-packages). You could also fork from the tag and try to cherry pick the change for a more stable solution. However, code from the development will be possibly unstable and you might experience different problems.

**Comment by AliEasy** [comment]
@FaFre 
Thanks for your explanation. but I asked for a release in order to have a stable and fixed version.
Like you said 

> code from the development will be possibly unstable
