### ISSUE TITLE
Is there a count feature to get count only for specific queries?

### ISSUE THREAD

**Issue by luohao123** [simolus3/moor#2407]
Is there a count feature to get count only for specific queries?

**Comment by luohao123** [comment]
Please help, even ChatGPT didn't know how to get length only in drfit, this is lack of doc.

<img width="698" alt="image" src="https://user-images.githubusercontent.com/49749220/235880460-cc1a4a8d-0b47-4a0d-9510-28c1369eed7f.png">

**Comment by muhleder** [comment]
@luohao123   You can use custom sql, there is an example for getting count in the docs. https://drift.simonbinder.eu/docs/using-sql/custom_queries/#custom-select-statements

**Comment by kuhnroyal** [comment]
The alternative is to use `query.getSingle().then((result) => result.length)`.

**Comment by simolus3** [comment]
If you only need the count, you can get `COUNT(*)` in SQL with `countAll()` in Dart. Assuming that the table structure somewhat represents what you need, that would be:

```dart
  Future<int> getAmountOfRoomMembers(String roomId) async {
    final count = countAll();
    final query = selectOnly(roomMember)
      ..addColumns([count])
      ..where(roomMember.roomId.equals(roomId));

    return query.map((row) => row.read(count)!).getSingle();
  }
```

The documentation mentions a few more aggregate functions [as well](https://drift.simonbinder.eu/docs/advanced-features/joins/#group-by).

We might also be able to give better help if you are more specific about the issue you have. So if the ideas shared here don't solve your problem, please follow up with more detail about the query you're trying to write.
