### ISSUE TITLE
stream returns very strange no data

### ISSUE THREAD

**Issue by luohao123** [simolus3/moor#2408]
```
Future<bool> isTableEmpty() async {
    final record = await (select(roomMember)..limit(1)).getSingleOrNull();
    return record == null;
  }

  Stream<List<DbRoomMember>> getRoomMembers(String roomId) {
    debugPrint("[dao] get roommembers? $roomId");
    return (select(roomMember)..where((tbl) => tbl.roomId.equals(roomId)))
        .watch()
        .handleError((error) {
      debugPrint("Error executing query: $error");
    });
  }
```

I have a table, which `isTbaleEmpty`. returns False, so the table should be normal, but getRoOMMembers didn't return data (not empty, it should *at least* give me empty list, but it returns no data, the stream no data, which is unexpected.
And the error also returns nothing,

what should I do?

**Comment by simolus3** [comment]
You can pass `logStatements: true` to your `NativeDatabase` constructor to log every SQL statement that drift emits. Do you see the query for the stream being executed there?

How are you listening to the stream, with a stream builder? Drift will only start running the query as soon as there is a listener.

**Comment by luohao123** [comment]
I found it was caused by an sql error but no where noticed that, thanks for reply!! now I have another serious question!!! about primary key!!!!
