### ISSUE TITLE
Table declaration in different files

### ISSUE THREAD

**Issue by charlesrostaing** [simolus3/moor#241]
For databases with many tables, it would be useful to be able to move the table declaration into separate files. Otherwise, the file will be very long and hard to maintain.
Could you add the possibility to extract the table declaration code into different separate files that could be imported by the moor_database.dart file ?

    @DataClassName("Category")
    class Categories extends Table {
  
      IntColumn get id => integer().autoIncrement()();
      TextColumn get description => text()();
    }

**Comment by simolus3** [comment]
I think that should already work though. If `Categories` was declared in another file that's imported like this:
```dart
// file called "database.dart"
import 'categories.dart'; // file containing the Categories table

part 'database.g.dart';

@UseMoor(tables: [Categories])
class MyDatabase extends _$MyDatabase {
  // ...
}
```

Then the generator should be able to read the categories table. The generated code for the categories table will still live in `database.g.dart` (so not in the file that declared the table), but that shouldn't make the code you write harder to maintain, right?

If that doesn't work for you it's probably a bug that I can look into.

**Comment by charlesrostaing** [comment]
Ok this is indeed suitable for us.
Thanks

**Comment by matthewkooshad** [comment]
similarly, can you give an example of how to have the functions that return .get() or .watch() in another file? i would like to have them in the same file with the table definition. thanks
