### ISSUE TITLE
ON DELETE CASCADE does not work on flutter web with sqlwasm

### ISSUE THREAD

**Issue by gianmarcocalbi** [simolus3/moor#2421]
**Describe the bug**

I have few simple tables on my webapp using Drift Web with sql-wasm.js and sql-wasm.wasm

One table (`moments`) references another one (`trips`) with `onDelete: KeyAction.cascade`. When I delete a row in trips with a certain id, the delete does not get cascaded to `moments` referencing it. I am using Drift on mobile with pretty much the same tables and I have no issues, leading me to guess it may be related to working on the web.

```dart
class TripsTable extends Table {
  @override
  String get tableName => 'trips';
	
  IntColumn get id => integer().autoIncrement()();
}

class MomentsTable extends Table {
  @override
  String get tableName => 'moments';

  IntColumn get tripId => integer().references(
        TripsTable,
        #id,
        onDelete: KeyAction.cascade,
      )();

  IntColumn get id => integer().autoIncrement()();
}


//========================

final sqlId; //=1

final deleteCount =
    await (_db.delete(_db.tripsTable)
		..where((tbl) => tbl.id.equals(sqlId))).go();

print(deleteCount); // 1

final moments = await (_db.select(_db.momentsTable)
      ..where((tbl) => tbl.tripId.equals(sqlId)))
    .get();

print(moments.first.tripId); // 1
// meaning the first "moment" references 
// the just deleted "trips" row
```

The foreign_keys are ON:

```dart
// database.dart
//...
  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      beforeOpen: (details) async {
        await customStatement('PRAGMA foreign_keys = ON');
      },
      onCreate: (m) async {
        logger.i('Creating database. $schemaVersion..');
        await m.createAll();
        logger.i('Database created successfully');
      },
      onUpgrade: (m, from, to) async {
        logger.i('Upgrading database from v$from to v$to...');

        logger.i('Database migration completed.');
      },
    );
  }
//...
```

**Comment by simolus3** [comment]
Thanks for the report. Unfortunately, I couldn't reproduce the issue. This is the database file that I'm using:

```dart
import 'package:drift/drift.dart';

part 'database.g.dart';

// MomentsTable and TripsTable as you have defined them...

@DriftDatabase(tables: [TripsTable, MomentsTable])
class MyDatabase extends _$MyDatabase {
  MyDatabase(QueryExecutor conn) : super(conn);

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      beforeOpen: (details) async {
        await customStatement('PRAGMA foreign_keys = ON');
      },
      onCreate: (m) async {
        await m.createAll();
      },
      onUpgrade: (m, from, to) async {},
    );
  }
}
```

And this is my `main.dart`:

```dart
import 'package:drift/drift.dart';
import 'package:drift/wasm.dart';
import 'package:web_worker_example/database.dart';
import 'package:sqlite3/wasm.dart';

void main() async {
  final sqlite3 = await WasmSqlite3.loadFromUrl(Uri.parse('sqlite3.wasm'),
      environment: SqliteEnvironment(
        fileSystem: await IndexedDbFileSystem.open(dbName: 'foo'),
      ));

  final db = MyDatabase(WasmDatabase(sqlite3: sqlite3, path: 'foo'));

  final sqlId = 1;

  await db.tripsTable.insertOne(TripsTableCompanion.insert(id: Value(sqlId)));
  await db.momentsTable.insertOne(MomentsTableCompanion.insert(tripId: sqlId));

  final deleteCount = await (db.delete(db.tripsTable)
        ..where((tbl) => tbl.id.equals(sqlId)))
      .go();

  print(deleteCount); // 1

  final moments = await (db.select(db.momentsTable)
        ..where((tbl) => tbl.tripId.equals(sqlId)))
      .get();

  print(moments.first.tripId); // 1
}
```

It works in the sense that it throws an `Uncaught (in promise) Error: Bad state: No element` in the end.

**Comment by simolus3** [comment]
Did you add the foreign key constraints later (e.g. after the database already existed)? In that case you'd have to write a migration to add that constraint.

**Comment by simolus3** [comment]
If it helps, you can recover a web database for local inspection with the `sqlite3` tool like this (you'd need to replace the database and file name obviously):

```dart
  final fs = await IndexedDbFileSystem.open(dbName: 'foo');
  final file = '/foo';

  final size = fs.sizeOfFile(file);
  final blob = Uint8List(size);
  fs.read(file, blob, 0);

  final a = AnchorElement();
  document.body!.append(a);

  final domBlob = Blob([blob]);
  final url = Url.createObjectUrlFromBlob(domBlob);
  a
    ..href = url
    ..download = 'app.db'
    ..click()
    ..remove();
```

**Comment by gianmarcocalbi** [comment]
Thank you very much for the reply!

I am quite sure that the foreign constraint was added before running the app for the first time, anyway, to be sure, I tried to delete the database from the Developer Tools > Application > IndexedDb > moor_databases > Delete database, I believe that after doing this the DB is recreated thus the constrain should be applied for sure.

I will try to export the DB as you suggested to double check if the foreign key is applied.

I see that in your example you are using the new backend, sqlite3/wasm.dart, isn't it?
I tried like that and the cascade delete works but I am getting the error https://github.com/simolus3/drift/issues/2388


Instead the error that I described occurs when using the [other solution](https://drift.simonbinder.eu/web/#getting-started), with sql.js, where the DB connection is instantiated like

```dart
WebDatabase.withStorage(
  await DriftWebStorage.indexedDbIfSupported(dbName),
)
```

**Comment by simolus3** [comment]
Thanks for following up, I can reproduce the issue! Unfortunately, the root cause is a limitation in sql.js, the JavaScript library we use to access sqlite3 in `package:drift/web.dart`. The library doesn't support persistence, the only (pretty inefficient) workaround is to export the whole database as a blob and store that. Unfortunately, exporting the database resets some of its internal state, including the flag controlling whether foreign keys are enabled. But since the higher-level drift database isn't re-opened, the callback enabling them does not get executed again.

You can work around this specific issue with a lower-level mechanism to enable foreign keys:

```dart
WebDatabase.withStorage(
  await DriftWebStorage.indexedDbIfSupported(dbName),
  setup: (rawDb) => rawDb.run('pragma foreign_keys = on'),
)
```

The synchronous `setup` parameter does get executed again, which solves this particular problem. Unfortunately this is an unfixable design limitation in that web implementation. The newer `package:drift/wasm.dart` library is more reliable, and I'm currently working on an easier-to-use stable solution (#2382).
