### ISSUE TITLE
Error while preparing statement, ambiguous column name: 'x', SQL logic error (code 1)

### ISSUE THREAD

**Issue by enrique-lozano** [simolus3/moor#2425]
Hi all! 

I discover a little issue using the .drift files generator. In my .drift file have the following table, with a custom function to return the data from it;

```
CREATE TABLE IF NOT EXISTS categories (
    id TEXT NOT NULL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    iconId TEXT NOT NULL,
    parentCategoryID TEXT REFERENCES categories(id) ON DELETE CASCADE ON UPDATE CASCADE,
) AS CategoryInDB;

getCategoriesWithFullData($predicate = TRUE, :limit AS NUMBER) WITH Category: 
    SELECT a.*, parentCategory.** 
    FROM categories a 
        LEFT JOIN categories parentCategory 
        ON a.parentCategoryID = parentCategory.id 
    WHERE $predicate 
    LIMIT :limit;
```

Then in my .dart code, if I specify a predicate, it gives the error specified in the issue:

```
// Error while preparing statement, ambiguous column name: 'id', SQL logic error (code 1)
db.getCategoriesWithFullData(predicate:  (a, b) => a.id.equals('test-id'), limit: 5).watch()
```

It seems that when a table has a reference to its same table, the query gets confused. This can be easily resolved by creating a customQuery and mapping the results, or by directly creating another function in the .drift file like this:

```
getCategoriesByIdWithFullData(:id AS TEXT, :limit AS NUMBER) WITH Category: 
    SELECT a.*, parentCategory.** 
    FROM categories a 
        LEFT JOIN categories parentCategory 
        ON a.parentCategoryID = parentCategory.id 
    WHERE a.id = :id
    LIMIT :limit;
```

However, the error is a bit annoying, would be nice if we can implement the predicate directly on the generated select function.

**Comment by simolus3** [comment]
Huh, seems like this has always been broken. We generate qualified column references if there is more than one table in the query, but that doesn't consider the case when there are multiple references to the same table.

I've fixed this in f5ae3902846f7626d1bb2f5471f14f62319809dd, you can get the fix by using `drift_dev: ^2.8.2` or running `pub upgrade`.
