### ISSUE TITLE
APIs to update database when background services updated data

### ISSUE THREAD

**Issue by luohao123** [simolus3/moor#2430]
Hi, I currently got a problem, might not drift issue but just wanna ask is there a interface to notify or something to update data.

https://stackoverflow.com/questions/71919808/database-path-in-main-isolate-and-other-isolate

as this question states, 

<img width="637" alt="image" src="https://github.com/simolus3/drift/assets/49749220/3f359e2f-5567-4fff-8abd-36ade172337d">

peple are strugginng update the data when a background services insert/delete/edit data but UI actually didn't update imediately which using `watch()` to get data streams.

**Comment by simolus3** [comment]
Query streams are a Drift feature, not something that sqlite3 gives you out of the box. To have query streams work for multiple drift databases, they need to talk to each other about updates they're making.

If you're using Dart isolates (`compute` or `Isolate.spawn`), you can make two drift databases talk to each other by using [computeWithDatabase or serializableConnection](https://drift.simonbinder.eu/docs/advanced-features/isolates/#simple-sharing).

If you're using a third-party package to spawn isolates in another engine group (e.g. for work manager on Android), you need to establish some mechanism for the two isolates to exchange messages in real time. Once that is given, you can use the `package:drift/remote.dart` API to make two drift databases communicate over that channel. If it's not possible for two isolates to communicate with the package you're using to spawn them, you can't use matching query streams either.

**Comment by luohao123** [comment]
@simolus3 Hello, actually using isolates indeed, it was done by something like foreground services in native android but the service itself is dart.

but using MethodChannel send to native. 

In such case, what is the best way to do it?

The reason why I ask is that this might be most users needs, if they want using background services deal with sql and then need update UI.


Actually my question might is not decsribed as you anwsered me:

My question is mainly drift inserted data in isolates, but UI (using watch, didn't get udpate). So I just ask is there an easier way to do this job

**Comment by simolus3** [comment]
You need _some_ way to send data between the two tasks, then drift can do the rest of the work. If you're manually spawning them, you might be able to implement such a communication channel over method handles. Drift can share updates over the channel, but you need to implement it.

> So I just ask is there an easier way to do this job

You can call [notifyUpdates](https://drift.simonbinder.eu/api/drift/databaseconnectionuser/notifyupdates) on your database class to manually trigger watch events if that's easier to do in your case.

**Comment by luohao123** [comment]
@simolus3 this functions need a param which is TableUpdates, but ot do it more easily

**Comment by simolus3** [comment]
You can do `TableUpdate(yourTable)` in the database class to signal that `yourTable` was updated, is that not what you need?

**Comment by luohao123** [comment]
If I call i.e. TableUpdate(DbUser); will the thread in foreground update watch stream

**Comment by luohao123** [comment]
@simolus3 hello!, sorry for pin again, but I just confused by this:

<img width="630" alt="image" src="https://github.com/simolus3/drift/assets/49749220/16da7808-791d-4213-9fca-11d72a057650">

Is that ok I write a TableUpdate func for every single database Dao? SO that I can call it to update this table to other isolate?

But why Can not I get a tableName attribute from the table define which is the child class of Table from drift?>

**Comment by luohao123** [comment]
I tied call tableUpdate when new data inserted, but the isolate just doens;t get updated......

**Comment by simolus3** [comment]
There is no magic way drift could use to make two unrelated isolates talk to each other.  If you're using isolates that are in different Flutter engines, _you_ need to find some way to make them talk to each other. Then drift can use the channel that _you have built_ to share table updates.

**Comment by phamconganh** [comment]
@luohao123 Have you solved this problem yet? I have a download task in native Android background (like flutter_downloader)and update to database process and want to display in UI by watch
