### ISSUE TITLE
generated function does not have a watch function

### ISSUE THREAD

**Issue by rodriger06** [simolus3/moor#2432]
Hi ,

I am using drift 2.8.0 and ran the command  to generate code.  the following code was generated in the .g file:
```
 Selectable<ReportProjectionResult> reportProjection(
      String? startDate, String? endDate) {
    return customSelect(
        'SELECT id, group_id, expected_amount, actual_amount FROM income WHERE payment_date BETWEEN ?1 AND ?2 ORDER BY payment_date',
        variables: [
          Variable<String>(startDate),
          Variable<String>(endDate)
        ],
        readsFrom: {
          income,
        }).map((QueryRow row) {
      return ReportProjectionResult(
        id: row.read<int>('id'),
        groupId: row.readNullable<int>('group_id'),
        expectedAmount: row.readNullable<double>('expected_amount'),
        actualAmount: row.readNullable<double>('actual_amount'),
      );
    });
  }


class ReportProjectionResult {
  final int id;
  final int? groupId;
  final double? expectedAmount;
  final double? actualAmount;
  ReportProjectionResult({
    required this.id,
    this.groupId,
    this.expectedAmount,
    this.actualAmount,
  });
}

```

i created the following function in my database.dart file:
```
Stream<List<ReportProjectionResult >> incomeProjection(String startDate, String endDate) {
    return incomeProjection(startDate, endDate).watch().;
```

the problem here is that android studio complaints that watch() is not defined for the type of stream.  I have other function where i can specified the watch function.  I compared the code to my other functions and they are similar and i am able to specified watch() in other functions.  can someone help? what am i doing wrong?

**Comment by simolus3** [comment]
Hi! The code looks correct apart from a small typo: The generated method is called `reportProjection`, but your stream function is calling itself (`incomeProjection`). If you change the body to `return reportProjection(startDate, endDate).watch();`, it should work.
