### ISSUE TITLE
customSelect query is not running, while updating the data

### ISSUE THREAD

**Issue by msarkrish** [simolus3/moor#2438]
I'm selecting the data using below query, but UI is not updating whenever one of the table column data updated. I hace checked the log, select query is not running after updating the workorder table

Database Query

      Stream<List<WorkOrder>> getTotalWorkOrders({
        required String laborCode,
     }) {
      return customSelect(
        'select ${Queries.selectClauseForWorkOrder}'
        '${Queries.getStatusForWo(laborCode: laborCode)},CASE when '
        "(operationstate ='U' and serversync =1) then 1 ELSE 0 END AS "
        'iserror from ${Tables.workOrderTable} where  (historyflag=0 '
        "and schedstart is null and status NOT IN ('WORKDONE','COMP', "
        "'CAN','CLOSE','WAPPR','WDAPPR','CANREQ') and status in "
        "('JSCH', 'JOBSCHD', 'INPRG') and  workorderid in (select "
        'workorderid from ${Tables.assignmentsTable} where '
        "laborcode ='$laborCode' and status not in ('COMPLETE', "
        "'WAITASGN','RETURNED'))) or (historyflag=0 and status NOT IN "
        "('WORKDONE','COMP','CAN','CLOSE','WAPPR','WDAPPR','CANREQ') "
        "and status in ('JSCH', 'JOBSCHD', 'INPRG') and  workorderid in"
        ' (select workorderid from ${Tables.assignmentsTable} where '
        "laborcode ='$laborCode' and status not in ('COMPLETE', "
        "'WAITASGN','RETURNED') union select parent from "
        '${Tables.transQueueTable} where parent is not null and status in '
        "('ERROR','INFO') and parent in (select workorderid from "
        "${Tables.assignmentsTable} where laborcode ='$laborCode')))",
        readsFrom: {
          workOrderTable,
          wOAssignments,
          transQueue,
          assetTable,
          locationsTable,
        },
      ).map((queryRow) {
        print('watched');
        final workOrderMap = queryRow.data;
        return WorkOrder(
          description: workOrderMap['description'] as String?,
          reportDate: workOrderMap['reportdate'] as String,
          status: workOrderMap['status'] as String,
          assetNum: workOrderMap['assetnum'] as String?,
          location: workOrderMap['location'] as String?,
          isError: workOrderMap['iserror'] as int,
          assetDescription: workOrderMap['assetdesc'] as String?,
          locationDescription: workOrderMap['locationdesc'] as String?,
          teamActualTime: workOrderMap['teamactualtime'] as double?,
          workOrderID: workOrderMap['workorderid'] as int?,
          workType: workOrderMap['worktype'] as String?,
          jpDuration: workOrderMap['jpduration'] as double?,
          woPriority: workOrderMap['wopriority'] as int?,
          actualStartDateTime: workOrderMap['actstart'] as String?,
        );
      }).watch();
     }

Provider

    final workOrderListProvider = StreamProvider<List<WorkOrder>>((ref) {
      final database = GetIt.I.get<Database>();
      final sharedPreferenceManager = GetIt.I.get<SharedPreferenceManager>();
      final laborCode =
          sharedPreferenceManager.getString(key: SharedPrefConstants.laborCode);
      return database.getTotalWorkOrders(laborCode: laborCode ?? '');
    });

UI Code

          Expanded(
            child: workOrderListStream.when(
              data: (workOrderList) {
                return ListView.builder(
                  itemCount: workOrderList.length,
                  itemBuilder: (context, index) {
                    return WorkOrderCard(
                      workOrder: workOrderList[index],
                      isSelected: (selectedWorkOrder != null) &&
                          ((selectedWorkOrder.workOrderID ?? 0) ==
                              (workOrderList[index].workOrderID ?? 0)),
                      onTap: () async {
                        if (Breakpoints.large.isActive(context)) {
                          ref.read(selectedWorkOrderProvider.notifier).state =
                              workOrderList[index];
                        } else {
                          if (mounted) {
                            context.go(AppRoute.workorderdetail.subroute!);
                          }
                        }
                      },
                    );
                  },
                );
              },
              error: (e, s) {
                return Center(child: Text(e.toString()));
              },
              loading: () {
                return const CircularProgressIndicator();
              },
            ),
          ),

Updating workorder table with below query

    Future<void> updateWorkOrderDescription({
        required int workOrderID,
      }) async {
        await customStatement(
          "update workorder set description='filfePath' where workorderid='$workOrderID'",
        );
      }

**Comment by simolus3** [comment]
I'll clarify the documentation to make this clearer, but auto-updating streams are a drift features that requires the library to know about updated tables.

For updates constructed with its high-level Dart API, drift is able to infer which streams need updates automatically. For custom statements, there's no way to know without you providing that information.

In `customSelect`, you need to use the `readsFrom` parameter to indicate which tables the query is reading from.

On `updateWorkOrderDescription`, you need to use `customUpdate("update workorder ...", updates: [workorder])` - but it might be more convenient to just do

```dart
Future<void> updateWorkOrderDescription({
    required int workOrderID,
  }) async {
    final update = update(workorder)..where((row) => row.workOrderId.equals(workOrderID));
    await update.write(WorkOrderCompanion(description: 'fiflePath'));
  }
```

**Comment by msarkrish** [comment]
Thanks for immediate reply @simolus3 . Sure I will try your solution and I will share the results.
