### ISSUE TITLE
I am suddenly facing this issue

### ISSUE THREAD

**Issue by vimalmistry** [simolus3/moor#244]
moor_flutter: ^2.0.0
  moor: ^2.0.0
  build_runner: ^1.3.1
  moor_generator: ^2.0.0

Flutter Doctor
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.0)
[✓] Connected device (2 available)

Compiler message:
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/moor_web.dart:9:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:2:8: Error: Not found: 'dart:js'
import 'dart:js';
       ^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/browser_client.dart:6:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:42:9: Error: Type 'JsObject' not found.
  final JsObject _obj;
        ^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:57:3: Error: Type 'JsObject' not found.
  JsObject _createInternally(Uint8List data) {
  ^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:70:9: Error: Type 'JsObject' not found.
  final JsObject _obj;
        ^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:122:9: Error: Type 'JsObject' not found.
  final JsObject _obj;
        ^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/browser_client.dart:97:25: Error: Type 'HttpRequest' not found.
  void _openHttpRequest(HttpRequest request, String method, String url,
                        ^^^^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/http-0.12.0+2/lib/src/browser_client.dart:32:25: Error: 'HttpRequest' isn't a type.
  final _xhrs = new Set<HttpRequest>();
                        ^^^^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/web_db.dart:125:17: Error: Getter not found: 'window'.
    final raw = window.localStorage[_persistenceKey];
                ^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/web_db.dart:125:17: Error: The getter 'window' isn't defined for the class '_WebDelegate'.
 - '_WebDelegate' is from 'package:moor/moor_web.dart' ('../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/moor_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'window'.
    final raw = window.localStorage[_persistenceKey];
                ^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/web_db.dart:136:7: Error: Getter not found: 'window'.
      window.localStorage[_persistenceKey] = binStr;
      ^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/web_db.dart:136:7: Error: The getter 'window' isn't defined for the class '_WebDelegate'.
 - '_WebDelegate' is from 'package:moor/moor_web.dart' ('../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/moor_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'window'.
      window.localStorage[_persistenceKey] = binStr;
      ^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/web_db.dart:149:10: Error: Getter not found: 'window'.
    if (!window.localStorage.containsKey(_versionKey)) {
         ^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/web_db.dart:152:24: Error: Getter not found: 'window'.
    final versionStr = window.localStorage[_versionKey];
                       ^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/web_db.dart:149:10: Error: The getter 'window' isn't defined for the class '_WebVersionDelegate'.
 - '_WebVersionDelegate' is from 'package:moor/moor_web.dart' ('../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/moor_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'window'.
    if (!window.localStorage.containsKey(_versionKey)) {
         ^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/web_db.dart:152:24: Error: The getter 'window' isn't defined for the class '_WebVersionDelegate'.
 - '_WebVersionDelegate' is from 'package:moor/moor_web.dart' ('../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/moor_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'window'.
    final versionStr = window.localStorage[_versionKey];
                       ^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/web_db.dart:159:5: Error: Getter not found: 'window'.
    window.localStorage[_versionKey] = version.toString();
    ^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/web_db.dart:159:5: Error: The getter 'window' isn't defined for the class '_WebVersionDelegate'.
 - '_WebVersionDelegate' is from 'package:moor/moor_web.dart' ('../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/moor_web.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'window'.
    window.localStorage[_versionKey] = version.toString();
    ^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:19:8: Error: Getter not found: 'context'.
  if (!context.hasProperty('initSqlJs')) {
       ^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:26:4: Error: Getter not found: 'context'.
  (context.callMethod('initSqlJs') as JsObject)
   ^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:26:39: Error: 'JsObject' isn't a type.
  (context.callMethod('initSqlJs') as JsObject)
                                      ^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:37:53: Error: 'JsObject' isn't a type.
  _moduleCompleter.complete(SqlJsModule._(module as JsObject));
                                                    ^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:42:9: Error: 'JsObject' isn't a type.
  final JsObject _obj;
        ^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:50:7: Error: Getter not found: 'context'.
      context['db'] = dbObj;
      ^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:50:7: Error: The getter 'context' isn't defined for the class 'SqlJsModule'.
 - 'SqlJsModule' is from 'package:moor/src/web/sql_js.dart' ('../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'context'.
      context['db'] = dbObj;
      ^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:58:45: Error: 'JsFunction' isn't a type.
    final constructor = _obj['Database'] as JsFunction;
                                            ^^^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:61:14: Error: Method not found: 'JsObject'.
      return JsObject(constructor, [data]);
             ^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:63:14: Error: Method not found: 'JsObject'.
      return JsObject(constructor);
             ^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:61:14: Error: The method 'JsObject' isn't defined for the class 'SqlJsModule'.
 - 'SqlJsModule' is from 'package:moor/src/web/sql_js.dart' ('../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart').
Try correcting the name to the name of an existing method, or defining a method named 'JsObject'.
      return JsObject(constructor, [data]);
             ^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:63:14: Error: The method 'JsObject' isn't defined for the class 'SqlJsModule'.
 - 'SqlJsModule' is from 'package:moor/src/web/sql_js.dart' ('../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart').
Try correcting the name to the name of an existing method, or defining a method named 'JsObject'.
      return JsObject(constructor);
             ^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:70:9: Error: 'JsObject' isn't a type.
  final JsObject _obj;
        ^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:75:54: Error: 'JsObject' isn't a type.
    final obj = _obj.callMethod('prepare', [sql]) as JsObject;
                                                     ^^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:86:16: Error: Getter not found: 'JsArray'.
    final ar = JsArray.from(args);
               ^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:86:16: Error: The getter 'JsArray' isn't defined for the class 'SqlJsDatabase'.
 - 'SqlJsDatabase' is from 'package:moor/src/web/sql_js.dart' ('../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'JsArray'.
    final ar = JsArray.from(args);
               ^^^^^^^
../../Tools/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.0.1+1/lib/src/web/sql_js.dart:101:71: Error: 'JsArray' isn't a type.
        .callMethod('exec', const ['SELECT last_insert_rowid();']) as JsArray;

**Comment by simolus3** [comment]
Can you check whether you're importing `package:moor/moor_web.dart` anywhere? If you are, replace the import with `package:moor/moor.dart`

**Comment by vimalmistry** [comment]
No I am not importing moor_web anywhere in my project. But I am using following packages in my app. 

  http: ^0.12.0+2
  fluro: "^1.5.1" # router
  get_it: ^3.0.1
  mobx: ^0.3.8
  flutter_mobx: ^0.3.3
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.5.0
  flutter_spinkit: "^4.0.0"
  shared_preferences: ^0.5.3+4
  google_sign_in: ^4.0.11
  flutter_facebook_login: ^3.0.0
  time_formatter: ^1.0.0
  uuid: ^2.0.2
  bubble: ^1.1.9+1
  emoji_picker: ^0.0.2
  cached_network_image: ^1.1.1
  moor_flutter: ^2.0.0
  moor: ^2.0.0
  md2_tab_indicator: ^1.0.2
  xlive_switch: ^1.0.5
  connectivity_wrapper: 1.0.2
  flutter_ringtone_player: ^1.0.3 
  device_info: ^0.4.1+1

**Comment by vimalmistry** [comment]
Sorry. It was my mistake. I accidentally imported  moor_web instead of moor while refactoring my code. I wasted 6 hours for this. Thank for indicating issue @simolus3
