### ISSUE TITLE
Ignore table fields in the generated companion object

### ISSUE THREAD

**Issue by omensight** [simolus3/moor#2449]
**Is your feature request related to a problem? Please describe.**
Hello, I would like to request to only generates just some fields for the Companion object, for example I have the next classes:
```
@drift.UseRowClass(Category, generateInsertable: true)
class Categories extends drift.Table {
  drift.IntColumn get id => integer().autoIncrement()();
  drift.TextColumn get categoryName => text()();
}

@Freezed()
@JsonSerializable()
class Category with _$Category {
  const factory Category({
    @Default(-1) int id,
    required String categoryName,
  }) = _Category;
}
```
and it generates the Companion:
```
const ProgramsCompanion({
    this.id = const Value.absent(),
    this.fkCategoryId = const Value.absent(),
    this.name = const Value.absent(),
    this.description = const Value.absent(),
    this.selectedByDefault = const Value.absent(),
    this.forceInstall = const Value.absent(),
    this.programCommandStorageType = const Value.absent(),
  });
  ProgramsCompanion.insert({
    this.id = const Value.absent(),
    required int fkCategoryId,
    required String name,
    this.description = const Value.absent(),
    required bool selectedByDefault,
    required bool forceInstall,
    required ProgramCommandStorageType programCommandStorageType,
  })  : fkCategoryId = Value(fkCategoryId),
        name = Value(name),
        selectedByDefault = Value(selectedByDefault),
        forceInstall = Value(forceInstall),
        programCommandStorageType = Value(programCommandStorageType);
```

Before I use freezed I used to generate the toColumns() function but now that I'm using this package it is just impossible.
This is how I used to define the toColumns() function manually:
```
@override
  Map<String, Expression<Object>> toColumns(bool nullToAbsent) {
    return CategoriesCompanion(
      categoryName: Value(categoryName),
    ).toColumns(nullToAbsent);
  }
```

As you can see I didn't declare the CategoriesCompanion id and it worked completely fine.

**Describe the solution you'd like**
What I'm proposing is the capability to declare the fields that I don't want to include in the companion object, something like:
```
@drift.UseRowClass(Category, generateInsertable: true, fieldsNotIncludedInCompanionObject: ['id'])
class Categories extends drift.Table {
  drift.IntColumn get id => integer().autoIncrement()();
  drift.TextColumn get categoryName => text()();
}
```
Thanks in advance and thank you for this incredible package you created.

**Comment by simolus3** [comment]
I don't think it would be a good idea to exclude some fields from companions in general, even though primary keys are rarely updated.

You could enable the `write_to_columns_mixins` [builder option](https://drift.simonbinder.eu/docs/advanced-features/builder_options/) for drift and apply the mixin to your `Category` class, which would allow you to implement `toColumns` like this:

```dart
@override
  Map<String, Expression<Object>> toColumns(bool nullToAbsent) {
    return super.toColumns(nullToAbsent)..remove('id');
  }

```
