### ISSUE TITLE
Is it possible to reuse functions for the same type of table

### ISSUE THREAD

**Issue by gaowanliang** [simolus3/moor#2450]
Suppose I want to dynamically create a new table (or database file) for each user at the time of their login to allow better segregation of data. But in reality since each user operates the same programmatically, it is only necessary to write functions for one table to accommodate all user tables since they are all the same operationally just with different names, so I think it is possible to implement:

1. dynamically create a new database or table
2. reuse functions for databases or tables

**Comment by simolus3** [comment]
> Suppose I want to dynamically create a new table (or database file) for each user at the time of their login to allow better segregation of data.

You can give each user their own database by making the path to the database file a constructor parameter and then opening multiple instances of your database file. However, I don't really see a benefit of doing this - you can (and probably should) use a single table for that and use `WHERE` clauses to filter for rows relevant to the current user.
I don't recommend using dynamic tables either - you can implement them with drift, but the library is optimized for cases where it knows the entire schema at build time.

If you have a specific use case, I might be able to give better advice or look for ways that could be supported better with drift. At the moment I don't really understand why you'd want to create databases or tables dynamically, or what "reusing functions for databases or tables" would mean.

**Comment by gaowanliang** [comment]
Yes, you're right. I also filter the data of different users through `where` now. It's just that it's not in line with my daily habits. In other programming languages, when I use SQLite, I always like to create a table or database file for different users. But in fact, the operation of the database is the same between different users, so I just need to write a fixed function, and the parameter passed in is its user name.

To say that the benefits of doing so, in fact, is not obvious, so **I am not particularly concerned about whether this feature can be achieved, just to put forward a point of view.** In fact, the main benefit is reflected in the backup, assuming that the user needs to synchronize data on multiple devices, he only needs to transfer the part of the database file belonging to his own account. Of course, you can also say that it is better to transfer the whole database file directly, which is what I said at the beginning that "the advantage is not obvious". Similarly, if users want to delete data, they can simply delete the database files belonging to their own accounts. I fully understand the importance of code optimization, but I think this function may not be difficult, because it is just to create a new database file, and then use the same code to operate on another database file (of course, this is just my opinion). The only difference is that the name of the database file is different, and there is no need to dynamically add any columns.

Of course, I can use other methods to achieve the above function, which is not difficult, but I simply think it is not elegant.

**Comment by simolus3** [comment]
That's a fair point. On Android each user would get an independent app data directory either way, so I didn't consider that this might be relevant. I agree that on desktop OSes or if you have multi-user support in your app, in can make sense to have one database per user if they need to be isolated.

But again, this is something that can be done with drift. Typically, you'd construct the path to the database file in the constructor/factory of your database class. You could add a parameter for the current user and then construct multiple instances of your database class like that.

**Comment by gaowanliang** [comment]
Thank you very much for your answer, but I have one more question, what you think of as multi-user is multi-user at the system level, what I want to convey is actually multi-account. That means just like Microsoft, I might split into personal and work accounts. That is, I can't recognize if a user has changed when the program opens, but rather the operator logs into their account before I can dynamically generate a table or database file for it (assuming my program uses tables if it only needs to store one type of data, and files for multiple types of data). 

Is it possible to achieve this dynamic generation during runtime, and if so can you give an example?
