### ISSUE TITLE
Build runner failing to handle column aliases

### ISSUE THREAD

**Issue by frankvollebregt** [simolus3/moor#2453]
**Describe the bug**
I'm not quite sure what the root cause is, but after upgrading to the latest `drift_dev` and `sqlparser`, I've run into an issue where I can no longer run builds. Moreover, I can't seem to get everything downgraded to run again.

When I use a query like the following:
```sql
getCarsWithRacers: SELECT cars.*, driver.**, codriver.** FROM cars
  JOIN persons driver ON driver.id = cars.driver
  JOIN persons codriver ON codriver.id = cars.codriver
```
It used to work just fine, but now I get two warnings (and the same two for codriver)

For the second line:
```
Unknown table or view: driver
|    JOIN persons driver ON driver.id = cars.driver
|                           ^^^^^^^^^
```
And for the first line, it reads:
```
Nested star columns must refer to a table directly. They can't refer to a table-valued function or another select statement.
|    getCarsWithRacers: SELECT cars.*, driver.**, codriver.** FROM cars
|                                     ^^^^^^^^^
```
I will investigate this some more when I have time tomorrow, so I can get my app working again, but perhaps you already have an idea what might be causing this issue.

As an aside, these are obviously not my actual tables, and have been made a lot simpler than my actual queries, but using the actual names for tables/columns would only throw in some confusing jargon.

All these queries seem to work just fine in my local SQLite database browser on my PC.

For ease of testing:
```sql
CREATE TABLE persons (
  id INT NOT NULL PRIMARY KEY,
  name TEXT NULL,
  job TEXT NULL
);

CREATE TABLE cars (
  id INT NOT NULL PRIMARY KEY,
  wheels INT DEFAULT 4,
  driver INT NULL REFERENCES persons(id),
  codriver INT NULL REFERENCES persons(id)
);
```

**Comment by simolus3** [comment]
Thanks for the report, I'll take a look tomorrow as well.

> Moreover, I can't seem to get everything downgraded to run again.

Downgrading to `sqlparser: <0.30.1` in your pubspec and running `build_runner clean` once should hopefully get things working again until I come up with a fix.

**Comment by frankvollebregt** [comment]
So I figured out when this happens. The example I posted above does not do the trick. It happens when you `JOIN` the same table twice, once with an alias, and once without an alias. Moreover, it only happens when you _first_ join with an alias, and _second_ join directly.

That is, with the above two tables:
```sql
twoAliasesWorksFine: SELECT * FROM cars
  JOIN persons first_person ON first_person.id = cars.driver
  JOIN persons second_person ON second_person.id = cars.driver;

thisWorksFine: SELECT * FROM cars
  JOIN persons ON persons.id = cars.driver
  JOIN persons second_person ON second_person.id = cars.driver;

thisFails: SELECT * FROM cars
  JOIN persons second_person ON second_person.id = cars.driver
  JOIN persons ON persons.id = cars.driver;
```
I'm not sure if this is the only scenario that fails, but it seems to be the one causing the errors in my specific case.

### Note on downgrading the dependency
Even after cleaning and doing various things, including downgrading Flutter/Dart, getting it to run again seems to be a struggle. After downgrading Flutter to 3.3, and my app to a version from january, that version runs. If I then upgrade to the version from 2 weeks ago, it runs, if I then go to my latest version before the dependency update, it breaks. When I go back to the version from 2 weeks ago, it remains broken. Very confusing stuff.

**Comment by simolus3** [comment]
I've refactored the way `sqlparser` resolves columns recently, so I've thought yesterday's update was to blame for this. However, it looks like the issue here has already been there before.

As you've said, this issue occurs if there are two references to the same table in a join clause, where the first one has an alias and the second one doesn't. I'm working on a fix, but it's a bit complicated... 
Perhaps adding an explicit alias (transforming `thisFails` into the scheme of `twoAliasesWorksFine`) on the failing queries could work around this issue until I release a proper fix.

**Comment by simolus3** [comment]
I think e481f29138a77d737aa78f0769bd286bf24609ab should fix this issue. Could you try it out and let me know if you encounter and other regressions? You can try it by upgrading to the latest drift version and then adding this to your pubspec:

```yaml
  sqlparser:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: sqlparser

```

**Comment by frankvollebregt** [comment]
This new commit works perfectly with all of the queries that were failing before for me! In the meantime I had  indeed already refactored my code to use the explicit aliases as you proposed.

I'm not sure why I didn't encounter the problem any earlier, since I do check/update my dependencies quite regularly.

Thank you for now, and I'll let you know if there are other issues I run into
