### ISSUE TITLE
Example app can't finish loading in Web

### ISSUE THREAD

**Issue by arqeco** [simolus3/moor#2456]
Testing the example app (drift\examples\app):

It works perfectly in Windows, but in the Web (Chrome and Edge), the "loading icon" in the center of the screen keeps running forever and the loading is never finished.

![image](https://github.com/simolus3/drift/assets/4029456/85490667-c440-4726-8c15-af7c8498bf1a)

**Comment by arqeco** [comment]
Is there any special setup to make this run in the web?

**Comment by simolus3** [comment]
> Is there any special setup to make this run in the web?

The example app works for me in Chrome on Linux after running `build_runner build` and `flutter run -d chrome`.

Running the build is important for that example, since we also compile a web worker used by drift in that build process. Can you check that there's a `web/shared_worker.dart.js` file in the example and run build_runner if there isn't?

**Comment by arqeco** [comment]
After running
`flutter pub run build_runner build --delete-conflicting-outputs`
the app started correctly. The build_runner itself asked for this --delete-conflicting-outputs parameter.

The file ./web/shared_worker.dart.js didn't existed before the build_runner.

I also had a problem with the data not persisting between runs, but found somewhere a tip about using a fixed port to solve this, because flutter in debug mode choose a random port every run.

`flutter run -d chrome --web-port 5555`

**Comment by aefn** [comment]
Hi,
by following the instructions of @arqeco I get this :
```
Using WasmStorageImplementation.sharedIndexedDb due to unsupported browser features: {MissingBrowserFeature.dedicatedWorkersInSharedWorkers, MissingBrowserFeature.sharedArrayBuffers}
CompileError: WebAssembly.instantiateStreaming(): expected magic word 00 61 73 6d, found 2e 2e 2f 2e @+0
packages/drift/src/remote/communication.dart 113:66                  request
packages/drift/src/remote/client_impl.dart 158:10                    ensureOpen
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54   runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5   _async
packages/drift/src/remote/client_impl.dart 150:26                    ensureOpen
packages/drift/src/utils/lazy_database.dart 61:49                    <fn>
dart-sdk/lib/async/zone.dart 1407:47                                 _rootRunUnary
dart-sdk/lib/async/zone.dart 1308:19                                 runUnary
dart-sdk/lib/async/future_impl.dart 147:18                           handleValue
dart-sdk/lib/async/future_impl.dart 784:44                           handleValueCallback
dart-sdk/lib/async/future_impl.dart 813:13                           _propagateToListeners
dart-sdk/lib/async/future_impl.dart 584:5                            [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 657:7                            <fn>
dart-sdk/lib/async/zone.dart 1399:13                                 _rootRun
dart-sdk/lib/async/zone.dart 1301:19                                 run
dart-sdk/lib/async/zone.dart 1233:23                                 callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                     _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                      _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 177:15  <fn>
```

@simolus3 do you have any suggestion for me.

my doctor output :
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.10.5, on Microsoft Windows [Version 10.0.19045.3086], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0-rc2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.5.3)
[√] Android Studio (version 2022.1)
[√] VS Code (version 1.79.2)
[√] Connected device (4 available)
[√] Network resources

• No issues found!
```

**Comment by simolus3** [comment]
Is `drift/examples/app/web/sqlite3.wasm` readable for you or is there something wrong with that file?

**Comment by aefn** [comment]
@simolus3 it is solved, you were right. I assume it is difference between windows and Linux.
probably it would be good if you mention this in documents. It was symlink and it does not work in windows. I just copy the file there from extras and starts working.
btw, thank you

**Comment by data-diego** [comment]
> Is `drift/examples/app/web/sqlite3.wasm` readable for you or is there something wrong with that file?

@simolus3 This definitely should be in the readme, it would save me 2 hours 🤣

I copied the isolated example app folder, so I had no clue the file was symlinked
