### ISSUE TITLE
Unit test timeouts after upgrading to `v2.8.1`

### ISSUE THREAD

**Issue by sidlatau** [simolus3/moor#2458]
Unit test timeouts after upgrading to `v2.8.1`.
I investigated code and looks like the problem is that database timeouts when trying to close it.

Test:
```dart
    testWidgets(
      'no customers in DB - should show empty state, no fab, no searchbar',
      (tester) async {
        //deps.database = NativeDatabase.memory(logStatements: true)
        await initPump(tester);
        await tester.pumpAndSettle();
        expect(find.text(l10n.noCustomers), findsOneWidget);
        expect(find.byType(FloatingActionButton), findsNothing);
        expect(find.byType(SearchBar), findsNothing);
        await deps.database.close();
      },
    );

```
I checked what was changed, this is new code: 
https://github.com/simolus3/drift/blob/e481f29138a77d737aa78f0769bd286bf24609ab/drift/lib/src/sqlite3/database.dart#L105-L109

After changing this part to:
```dart
  @override
  @mustCallSuper
  Future<void> close() async {
    return _preparedStmtsCache.disposeAll();
  }
```

test passed, closing database action was successful. But it is quite strange that this impacts unit test execution. Should I create PR with this change or is a problem somewhere else?

**Comment by simolus3** [comment]
Indeed, it's pretty weird that this change affects the test, the two methods seem identical to me... I'll blame the magic Flutter does with async zones in tests for this, a PR with a fix would be welcome :)
