### ISSUE TITLE
Better support for table creation

### ISSUE THREAD

**Issue by JCKodel** [simolus3/moor#2461]
I always used Moor/Drift using SQL files to create my tables. While implementing a MigrationStrategy to generate some indices and triggers, I migrated that to Dart table creation (extending Table), so I could at least implement an Interface to not forget some columns that every table should have for my remote sync engine.

Doing that, I've noticed that Drift actually doesn't have any method to create indexes, triggers, etc. in the Table classes (according to https://github.com/simolus3/drift/discussions/2041, that should be done in the MigrationStrategy `onCreate` method.

Fine. But, what if every `Table` class had some empty methods that was called on migrations (whenever they exist or not), so:

```dart
class Users extends Table {
  // my columns

  // This one already exists
  @override
  Set<Column> get primaryKey = {id};

  @override 
  Future<void> onCreate(Users table, Migrator m) async {
    // Now I can create indexes and triggers here
  }

  @override
  Future<void> onUpgrade(Migrator m, int from, int to) async {
    // Doing version migrations in the same class
  }
}
```

That would not remove any functionality nor break anything. Drift engine would then run the default `MigrationStrategy` that is provided in the `migration` property (or create an empty default one) and would do a foreach in each table, calling those `onCreate` and `onUpgrade` on each table. If they are not overridden, then they are empty methods and no harm is done.

It's an easy feature to implement (I guess) that would increase the readability of our code, not segregating indices, triggers, etc. into another class.

**Comment by JCKodel** [comment]
So, what I have done so far:

I have a base class called `SyncTable` with some common columns that all my tables have (imagine this is the new Table, ignoring all sync-related stuff):

```dart
abstract class SyncTable extends Table {
  DateTimeColumn get updateDate => dateTime().clientDefault(() => DateTime.now())();
  BoolColumn get synced => boolean().clientDefault(() => false)();
  BoolColumn get deleted => boolean().clientDefault(() => false)();

  @protected
  Future<void> onCreate(Database db, Migrator m) async {}

  @protected
  Future<void> onUpgrade(Database db, Migrator m, int from, int to) async {}

  @protected
  Future<void> createIndex(Migrator m, Set<Column> columns) async {
    final tableInfo = this as TableInfo;

    final indexName = "IX_${tableInfo.entityName}_"
        "${columns.map((c) => c.name).join("_")}";

    await m.createIndex(
      Index(
        indexName,
        "CREATE INDEX ${indexName} ON \"${tableInfo.entityName}\"("
        "${columns.map((c) => c.escapedName).join(", ")}"
        ");",
      ),
    );
  }
}
```

So, when creating an actual table, I can write this:

```dart
import 'package:drift/drift.dart';

import '../../../k_authentication/k_authentication.dart';
import '../../shared/data/database.dart';
import '../../shared/data/sync_table.dart';

import 'users.dart';

@DataClassName("UserLogin")
class UserLogins extends SyncTable {
  TextColumn get id => text()();
  TextColumn get userId => text().references(Users, #id)();
  TextColumn get authenticationProvider => textEnum<AuthenticationProvider>()();

  @override
  Set<Column> get primaryKey => {id};

  @override
  Future<void> onCreate(Database db, Migrator m) async {
    createIndex({userId});
  }

  // Not needed for now
  // Future<void> onUpgrade(Database db, Migrator m, int from, int to) async {}
}
```

First, all my table-related stuff goes in the same place.

Second, it allows the creation of indices with an API (since we have the table columns here).

The `Database db` part can be covariant, so no issues there.

The Migrator is as simple as:

```dart
Future<void> _onCreate(Migrator m) async {
  for(final table in allTables) {
    table.onCreate(this, m);
  }
}

Future<void> _onUpgrade(Migrator m, int from, int to) async {
  for(final table in allTables) {
    table.onUpdate(this, m, from, to);
  }
}
```

EDIT: Added a `createIndex` that accepts a `Set` of columns and generate the index accordingly.

**Comment by dickermoshe** [comment]
@simolus3 This is resolved, right?

**Comment by simolus3** [comment]
Yes, we now have an `@TableIndex` annotation to be used on table classes.
