### ISSUE TITLE
Incorrect SQL should fail the build

### ISSUE THREAD

**Issue by dhoskins** [simolus3/moor#2472]
**Is your feature request related to a problem? Please describe.**
Drift SQL errors seem to be raised by the builder as _warnings_ rather than errors. This means that incorrect SQL can build correctly and pass CI.

**Describe the solution you'd like**
The ability to request SQL errors be raised as errors rather than warnings.

**Comment by simolus3** [comment]
Nice idea :+1: 

I've added a `fatal_warnings` [build option](https://drift.simonbinder.eu/docs/advanced-features/builder_options/) in 4411e0c45922b95b58a57aa0126ec698e50c12b1, it will be part of the next drift release (2.9.0).
