### ISSUE TITLE
override equal/hashcode to only consider some specific columns for stream(watch)

### ISSUE THREAD

**Issue by AndroidDesigner** [simolus3/moor#2477]
Hi.
I have a table with multiple columns, so that some its specific columns are updating every X seconds.
I'm using the ``watch`` method to monitor this table:
```
Stream<List<TableData>> methodName(...) => ((select(table).where(...)).watch()).distinct(const ListEquality().equals);
```
The above stream results in unwanted UI updates, because it includes unwanted columns in equal/hashcode too.
But I want to be able to monitor changes of some specific columns not all of them.

I can modify equal/hashcode methods manually in the generated ``db.g.dart`` file. But this modification will be **overridden** when I run ``flutter pub run build_runner build`` again (for possibly modifying generated db file in the future).

What is the best solution for this case?

**Comment by simolus3** [comment]
I don't think there should be an option to only consider a subset of columns for `equals` and `hashCode`.

If you need to ignore some columns for a specific stream only, you can use the `elementEquality` parameter for `ListEquality`:

```dart
class MyRowEquality implements Equality<TableData> {
  const MyRowEquality();

  @override
  bool equals(TodoItem e1, TodoItem e2) {
    return e1.col1 == e2.col1 && e1.col2 == e2.col2;
  }

  @override
  int hash(TodoItem e) => Object.hash(e.col1, e.col2);

  @override
  bool isValidKey(Object? o) => o is TableData;
}
```

And then

```
Stream<List<TableData>> methodName(...) => ((select(table).where(...)).watch()).distinct(const ListEquality(MyRowEquality()).equals);
```

If you need to ignore some columns all the time (which again, feels a bit weird for a hashCode/equals implementation), you might want to [write the result class yourself](https://drift.simonbinder.eu/docs/advanced-features/custom_row_classes/).

**Comment by AndroidDesigner** [comment]
Thank you :)
