### ISSUE TITLE
Documentation issue: Getting started

### ISSUE THREAD

**Issue by FMorschel** [simolus3/moor#2489]
Under https://drift.simonbinder.eu/docs/getting-started/#generating-the-code, both `flutter pub run build_runner build` and `flutter pub run build_runner watch` will warn that they're deprecated and we should be using `dart run build_runner build/watch`. 

Maybe do a project search for this command and replace it?

**Comment by simolus3** [comment]
Good catch, fixed in 81315c3d69fd43559c7ee6fbe5d43185cfce5673 (will take some time to go live though).
