### ISSUE TITLE
It's possible to locate .moor files in other directory

### ISSUE THREAD

**Issue by fredericomf** [simolus3/moor#250]
Hi,

I've a question. It's possible to locate the .moor files in another directory without database.dart?

Example:
```
@UseMoor(
    tables: [TABLE1],
    daos: [DAO],
    include: {'../module/feature/example2/data/example2.moor'})
```

**Comment by simolus3** [comment]
Yes. As long as the file is reachable from the build (this usually means being in the same package), it should work. If you need to include a moor file from another package, you can use the package import from Dart: `include: {'package:foo/bar.moor'}`.
Please let me know if you run into problems!
