### ISSUE TITLE
`equalsOrIgnore` method on `GeneratedColumn`

### ISSUE THREAD

**Issue by FMorschel** [simolus3/moor#2501]
**Is your feature request related to a problem? Please describe.**
I have some DAOs on my DB and since Dart 3.0, I've started using Records as my function parameters in queries. For example, for the example given in the tutorial:

```dart
class Todos extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(min: 6, max: 32)();
  TextColumn get content => text().named('body')();
  IntColumn get category => integer().nullable()();
}
```

If I wanted to create a query the way I'm doing, I would make a method like this:

```dart
Future<List<Todo>> get([List<({int? id, String? title, String? content, int? category)>? list])
```

If the list is null, I would return all data. Now, if I have, for example only one record that has only the category non-null, I would like to return all todos that have that category. If I have a second record that has only an id non-null, I would return all the ones from the previous category & the specific todo with that id.

What I've done today, is I've created loops that go through every record in the list and at the end I just sum them all up. 

But I have one small problem. I have no way of telling Drift that I want it to test for a value only if it is not null. 

My workaround:

```dart
extension GeneratedColumnExt<T extends Object> on GeneratedColumn<T> {
  Expression<bool> equalsOrIgnore(T? compare) {
    if (compare != null) return equals(compare);
    return isExp(const Constant(null)) | isNotExp(const Constant(null));
  }
}
```

**Comment by simolus3** [comment]
> I have no way of telling Drift that I want it to test for a value only if it is not null.

I think using records for that is a neat trick, but it will require custom code either way and I don't see the benefit of having an `equalsOrIgnore` in the core drift package.

By the way, you could probably construct the filter like this:

```dart
final condition = list.fold<Expression<bool>?>(null, (condition, filter) {
  void apply(Expression<bool> additionalCondition) {
    condition = switch (condition) {
      null => additionalCondition,
      var existing as Expression<bool> => existing & additionalCondition,
    };
  }

  if (filter.id != null) {
    apply(todos.id.equals(id));
  }

  return condition;
});
``` 

Which avoids adding tautologies into the where clause.
