### ISSUE TITLE
DriftRemoteException: how to handle?

### ISSUE THREAD

**Issue by hawkkiller** [simolus3/moor#2507]
I receive this exception while using Drift in isolates. I want to handle the SqliteException like unique constraint violation. But it seems to me that the underlying sqlite exception object is converted to string thefore I cannot use it.
![image](https://github.com/simolus3/drift/assets/62852417/3d14699b-bb3d-43ff-a03d-12f1110fceff)

**Comment by fbede** [comment]
I also just discovered this issue. I think it should be renamed to " 🐛 SqliteException cannot be caught".

**Comment by nazrinharris** [comment]
If you caught the `DriftRemoteException`, its `remoteCause` field contains the underlying `SqliteException`.

```dart
if (error is DriftRemoteException && error.remoteCause is SqliteException) {
    final cause = error.remoteCause as SqliteException;
```

edit: trying to pattern match with it (`remoteCause` isn't inferred correctly, so I had to cast it):
```dart
  switch (error) {
    case DriftRemoteException(remoteCause: SqliteException):
      final cause = error.remoteCause as SqliteException;
      return AccountsFailure(
        stackTrace: stackTrace,
        message: '${cause.message} \n${cause.causingStatement}',
        accountsAction: accountsAction,
        errorType: AccountsErrorType.sqliteException,
      );
  }
```

**Comment by hawkkiller** [comment]
Yes, I already tried that and it turns out that `remoteCause` is still a `DriftRemoteException`. Now I have created a helper function that will get the lowest exception. In my case, the `SqliteException` was at the second level of nesting
