### ISSUE TITLE
initialization of DRIFT database on Windows platform

### ISSUE THREAD

**Issue by francisnnumbi** [simolus3/moor#2511]
Hi,
How do I open connection of sqlite database with drift on Windows platform ? Whenever I run the app, there is an error that tables do not exist. But everything is fine on mobile platform.
Thanks

**Comment by simolus3** [comment]
> there is an error that tables do not exist

That sounds like the database file exists already (probably before you've first launched your drift app). Could you check whether the path you've chosen for your drift database may already be in use by another app?

**Comment by DonSqualo** [comment]
I had the same issue, because I copy pasted the "connections/" folder from the example/app into my project.
Fix: 
```
Future<File> get databaseFile async {
  // We use `path_provider` to find a suitable path to store our data in.
  final appDir = await getApplicationDocumentsDirectory();
  final dbPath = p.join(appDir.path, 'todos.db');
  return File(dbPath);
}
```
Rename todos.db to your db name

**Comment by dickermoshe** [comment]
This issue has not had any activity in over a year, closing
