### ISSUE TITLE
Sqlparser on pubdev engine().parse(sql).rootNode.childNodes

### ISSUE THREAD

**Issue by Somtobro** [simolus3/moor#2519]
```dart
import 'package:sqlparser/sqlparser.dart';

void parseSQL(String sql) {
  final engine = SqlEngine();
  final parseResult = engine.parse(sql);
  final rootNode = parseResult.rootNode;

  for (final node in rootNode.descendants) {
    if (node is CreateTableStatement) {
      final createTable = node as CreateTableStatement;
      // Analyze or manipulate the CREATE TABLE statement
      // Access table name, columns, constraints, etc.
      print('CREATE TABLE: ${createTable.tableName}');
    } else if (node is SelectStatement) {
      final select = node as SelectStatement;
      // Analyze or manipulate the SELECT statement
      // Access columns, tables, WHERE clause, etc.
      print('SELECT statement: ${select.toSql()}');
    } else if (node is InsertStatement) {
      final insert = node as InsertStatement;
      // Analyze or manipulate the INSERT statement
      // Access table name, column names, values, etc.
      print('INSERT statement: ${insert.toSql()}');
    } else {
      // Handle other statement types or unsupported statements
      print('Unsupported statement: ${node.toSql()}');
    }
  }
}

void main() {
  final sql = '''
    CREATE TABLE users (
      id INTEGER PRIMARY KEY,
      name TEXT,
      email TEXT
    );

    SELECT * FROM users WHERE id = 1;

    INSERT INTO users (name, email) VALUES ('John Doe', 'john@example.com');
  ''';

  parseSQL(sql);
}
```

What I expected: 3 statements in the childNodes
Behavior: I'm getting 0 statements

Please how can I successfully split this single statement?

**Comment by simolus3** [comment]
I think the current API really doesn't support this well. I've added a suitable method in the referenced commit, you can use it by adding this to your pubspec (until I release it):

```yaml
dependency_overrides:
  sqlparser:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: sqlparser

```

And then you can parse statements like this:

```dart
void parseSQL(String sql) {
  final engine = SqlEngine();
  final parseResult = engine.parseMultiple(sql);
  final rootNode = parseResult.rootNode;

  for (final node in rootNode.children) {

```

**Comment by Somtobro** [comment]
Thanks so much, but I think it's .childNodes
And when splitting it's ignoring Drop and alter query
Is that the behavior of the function?

**Comment by Somtobro** [comment]
@simolus3 I'd really appreciate your help here
Thank you

**Comment by Somtobro** [comment]
@simolus3 I'd really appreciate your help here
Thank you

**Comment by simolus3** [comment]
> Thanks so much, but I think it's .childNodes

Right, good catch.

>  And when splitting it's ignoring Drop and alter query

I'm not sure what you mean with drop, but `ALTER` statements are not currently supported by sqlparser. I don't really have a use for them at the moment so I don't think I'll work on them, but contributions are welcome of course.

You can use `ParseResult.errors` to views syntax errors (which can be caused by statements we don't support).

**Comment by Somtobro** [comment]
Thanks for the quick reply 
I meant like drop table query syntax.
Although I wish the package can add the item still in the list but as unknown then we can do this Take not of the else {}
``` dart
for (final node in rootNode.descendants) {
    if (node is CreateTableStatement) {
      final createTable = node as CreateTableStatement;
      // Analyze or manipulate the CREATE TABLE statement
      // Access table name, columns, constraints, etc.
      print('CREATE TABLE: ${createTable.tableName}');
    } else if (node is SelectStatement) {
      final select = node as SelectStatement;
      // Analyze or manipulate the SELECT statement
      // Access columns, tables, WHERE clause, etc.
      print('SELECT statement: ${select.toSql()}');
    } else if (node is InsertStatement) {
      final insert = node as InsertStatement;
      // Analyze or manipulate the INSERT statement
      // Access table name, column names, values, etc.
      print('INSERT statement: ${insert.toSql()}');
    } 

else {
      // Handle other statement types or unsupported statements
      print('Unsupported statement: ${node.toSql()}');
    }
  }


}
```
I think this would be better than not adding it to the list at all.
As for contributions, I'm not good at low level programming else I'd happily contribute to this wonderful package

**Comment by simolus3** [comment]
Good call, I've added support for that in cc83a58d8987118514edbebd78f7e66eb6bc1a09. With that commit, the parser will report instances of `InvalidStatement` in `rootNode.childNodes`. So you could do this:

```dart
else if (node is InvalidStatement) {
      // Handle other statement types or unsupported statements
      print('Unsupported statement: ${node.span?.text}');
    }
```

You can't use `toSql()` for invalid statements because we don't know what the statement is.

By the way, you probably don't want to loop over `rootNode.descendants` since that recursively returns every subtree (pretty inefficient if you just want the top-level statements).

**Comment by Somtobro** [comment]
Oh yeah thank you so much for this!
Also I didn't loop through the descendants ...that was when I was trying to figure out what the children parameter was named then I found .childNodes

**Comment by Somtobro** [comment]
And yeah also how do I update the package to use this latest changes do I just re run pub get with 
dependency_overrides:
  sqlparser:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: sqlparser
¿????

**Comment by Somtobro** [comment]
It just hit me actually
InvalidStatement might be too harsh a name because those syntaxes aren't actually Invalid (it may confuse people)
You could probably name it OtherStatements

Still OtherStatements might also have invalid statements..lol this is actually a tricky one
probably name it
OtherSxInvalidStatements..lol
You in one bruv 🤣 goodluck

**Comment by simolus3** [comment]
>  InvalidStatement might be too harsh a name because those syntaxes aren't actually Invalid (it may confuse people)

I'm going to be cheap here and say that these statements are invalid from the perspective of the parser. Note that you'd also get them for something ridiculous like

```SQL
SELECT * FROM my_table; -- statements[0] is SelectStatement
definitely not an sql statement; -- statements[1] is InvalidStatement
UPDATE my_table SET foo = bar; -- statements[2] is UpdateStatement
``` 

So there is no magic guarantee that an `InvalidStatement` is a statement at all. When the parser wants to parse a statement but can't, we just give up, fast forward to the next semicolon, and say that the range we skipped must be an invalid statement.

And `OtherStatement` would probably not be a good name to hold something like `definitely not an sql statement`, right?

**Comment by Somtobro** [comment]
But like the parser only supports a few types
For example an the parser considers an alter, drop query as invalid
statements.
That's the angle I'm coming from

**Comment by Somtobro** [comment]
Hey bro, is parseMultiple meant to split a sql statement or parse multiple?
I ask because I used it to split and it wasn't accurate, invalids weren't in the list.
I actually designed my own split function but it's like 90% accurate , and I need it to be 100 that's why I'm considering switching to this

**Comment by simolus3** [comment]
It splits statements reliably as a byproduct of parsing them, this prints the correct thing for me:

```dart
import 'package:sqlparser/sqlparser.dart';

void main() {
  const sql = '''
SELECT * FROM my_table; -- statements[0] is SelectStatement
definitely not an sql statement; -- statements[1] is InvalidStatement
UPDATE my_table SET foo = bar; -- statements[2] is UpdateStatement
''';

  final parser = SqlEngine().parseMultiple(sql);
  final root = parser.rootNode;

  for (final child in root.childNodes) {
    print('$child: ${child.span}');
  }
}
```

One exception might be an unknown statement that has semicolons as part of it. We support triggers though, and no other statement with that property comes to mind. Semicolons in string literals or identifiers are properly handled by the package.

**Comment by Somtobro** [comment]
Thanks for the explanation.

**Comment by Somtobro** [comment]
Hey bro 
Is it possible to get table name from an object of the Select Statement class?

**Comment by simolus3** [comment]
You can look at `TableReference` descendants of the select statement if that's what you mean?

**Comment by Somtobro** [comment]
Happy Sunday bro, your trouble friend is here again😅.
Im just having some difficulties with the syntax

```dart
import 'package:sqlparser/sqlparser.dart';

void main() {
  String myCommand = 'SELECT * FROM customers;';

  final engine = SqlEngine();
  final parsedStatement = engine.parse(myCommand).rootNode as SelectStatement;

  // Modify the parsed statement to include rowid in the SELECT clause
  final modifiedStatement = SelectStatement(
    columns: [
      ...parsedStatement.columns,
      Reference(entityName: 'rowid'),
    ],
    from: parsedStatement.from,
  );

  // Generate the modified SQL statement
  final modifiedSql = engine.unparse(modifiedStatement);

  //  another SelectStatement for demonstration purposes
  final anotherStatement = engine.parse('SELECT * FROM orders;').rootNode as SelectStatement;

  // Question: How can I get the table name from this SelectStatement?
  final tableName = anotherStatement.from!.first.tableName;

  print('Original SQL:');
  print(myCommand);
  print('Modified SQL:');
  print(modifiedSql);
  print('Table Name from the second SelectStatement:');
  print(tableName);
}
```

I hope you can see what I'm trying to do, I'm trying to add an extra column "rowid" but the Reference datatype isn't an object and ResultColumn is abstract
And for earlier about extracting the table name I put the example below
Appreciate your help🙏🏾

**Comment by simolus3** [comment]
This works:

```dart
import 'package:sqlparser/sqlparser.dart';
import 'package:sqlparser/utils/node_to_text.dart';

void main() {
  String myCommand = 'SELECT * FROM customers;';

  final engine = SqlEngine();
  final parsedStatement = engine.parse(myCommand).rootNode as SelectStatement;

  // Modify the parsed statement to include rowid in the SELECT clause
  final modifiedStatement = SelectStatement(
    columns: [
      ...parsedStatement.columns,
      ExpressionResultColumn(
        expression: Reference(columnName: 'rowid'),
      ),
    ],
    from: parsedStatement.from,
  );

  // Generate the modified SQL statement
  final modifiedSql = engine.unparse(modifiedStatement);

  //  another SelectStatement for demonstration purposes
  final anotherStatement =
      engine.parse('SELECT * FROM orders;').rootNode as SelectStatement;

  // Question: How can I get the table name from this SelectStatement?
  final from = anotherStatement.from;
  String tableName;

  if (from is TableReference) {
    tableName = from.tableName;
  } else {
    throw 'Not a direct FROM <table> statement, joins or subqueries are not supported.';
  }

  print('Original SQL:');
  print(myCommand);
  print('Modified SQL:');
  print(modifiedSql);
  print('Table Name from the second SelectStatement:');
  print(tableName);
}

extension on SqlEngine {
  String unparse(AstNode node) => node.toSql();
}
```

>  I'm trying to add an extra column "rowid" but the Reference datatype isn't an object and ResultColumn is abstract

That's because it can encode both "star" columns (`SELECT * FROM foo`) and columns referring to an expression (`SELECT rowid FROM foo`). Wrapping the reference in an `ExpressionResultColumn` works.

>  And for earlier about extracting the table name I put the example below

Note that there are a bunch of valid SQL queries where it's not clear what "the table name" means, e.g.

- `SELECT 123 + 456` (no `FROM` at all, still valid)
- `SELECT * FROM foo CROSS JOIN bar` (has two tables)
- `SELECT * FROM (SELECT * FROM foo)` (subquery)

Also, by constructing a `SelectStatement` cloning the columns and the `FROM` clause of the original statement, you're loosing a lof of information (like CTEs, GROUP BYs, ORDER BYs, WHERE clauses and so on). AST nodes in the `sqlparser` package are mutable, so you can just do `parsedStatement.columns.add()` to add a column if you don't need the original statement.

**Comment by Somtobro** [comment]
Thank you, thank you, thank you, thank you
This means a lot , more than you know.
Thank you👍🏾

**Comment by Somtobro** [comment]
Hey bro I think I found a bug
Try this
<try {
SqlEngine engine = SqlEngine();
 ParseResult parse = engine.parse('SELECT * FROM table_name,');//notice I ended the statement with a comma instead of a ;
catch(e){
//Log error
}>

I'm getting range error

**Comment by simolus3** [comment]
Excellent catch, that's a bug in the parser. I've fixed that in 0ed132f64261c973f6e02d39631b8361fbdc60f3, note that you won't get a `SelectStatement` in that case (it returns an `InvalidStatement` due to the syntax error).

**Comment by Somtobro** [comment]
Yeah bro, thanks for attending to the issue quick.

**Comment by Somtobro** [comment]
Hey bro,
I tried updating the package with pub get, got e98da9 (which is not the latest I assume)in sqlparser overriden.
I don't know if I'm doing it wrong or something and I don't want to make the change manually just yet 
I could use your opinion

**Comment by simolus3** [comment]
Sometimes it helps to run `pub upgrade`, you can also specify a fixed commit with `ref: 0ed132f64261c973f6e02d39631b8361fbdc60f3` in the dependency. I'll hopefully be able release the next version to pub in the next days though.

**Comment by Somtobro** [comment]
Hey bro check this out if you try to engine.parse("create") or something like create from table_name.
It throws an error, null check error instead of InvalidStatement or unknown or parsingerror

**Comment by Somtobro** [comment]
Hey bro check this out if you try to engine.parse("create") or something like create from table_name.
It throws an error, null check error instead of InvalidStatement or unknown or parsingerror

**Comment by simolus3** [comment]
Again, nice catch! Fixed in 83885791c77ce94e2f2172de5d69b45fb8904565.

**Comment by Somtobro** [comment]
Thanks.
I just recently updated my project to use the version on pubdev. This means I will have to switch back to overrides ride?
Or would running pub get again get the modified code ?

**Comment by simolus3** [comment]
No, unfortunately the fix has not yet been released to pub.dev - so you'd have to switch to the git dependency override again.

**Comment by Somtobro** [comment]
Hey bro, this is not related to the package but I need some help cooking up a sql query
Use case:
I have an insert query yeah:

INSERT INTO "Topics" ("topic", "subject_id") VALUES ('vsbsb', 2,000);

The number comma in the 2000 causes it to be 3 values instead of 2.

I was about to cook up a function to solve the issue and any similar but I thought to ask you for your opinion first or better still if I set up the sql query (ime passing the column names other parameters) using the package would that issue be handled?

**Comment by simolus3** [comment]
That issue wouldn't be handled, the `sqlparser` package would also see it as three values. You could detect and fix this case by walking the AST and manually concatenating the values if there are more values than you expect (and do `.toSql()` in the end).

**Comment by Somtobro** [comment]
Hey bro, check this out 

INSERT INTO "stories" ("title", "Contentz") VALUES ('joe', 'dhdhjfd' ');
engine.parse doesn't parse this.(because of the extra apostrophe just before the closing bracket)
I get a malformed sql exception

Expected behavior:to go under the InvalidStatement shelf

**Comment by Somtobro** [comment]
And yeahh I actually do have a question
I  parsed an insert statement variable: InsertStatement node;

How can I access it's values?(ive already figured out columns)
I'm actually going with your solution of walking through the number of columns and values to see if the lengths are equal
Thanks for that suggestion yesterday btw🙏🏾

**Comment by simolus3** [comment]
>  I get a malformed sql exception

This is sort of expected: Errors that happen during tokenization are not recoverable, so we throw instead of returning a partial state. You could catch the `CumulatedTokenizerException` and just assume that the entire block of statements is invalid.

> How can I access it's values?

You can use `InsertStatement.source`. When the insert statement has a `VALUES` clause, the `source` is going to be an instance of `ValuesSource`, which consists of a list of tuples containing the expressions to insert.

**Comment by Somtobro** [comment]
Hey brother man, this is not related to the package. I just have a question

I ran into a little challenge while coding a program, though I've solved it and my solution is reasonably good I would still love to get your opinion. I'm asking you because there's a huge probability you have ran into it to.

I was trying to construct the value part of a insert or modify statement, but the issue was when to use the apostrophe's cos a user can enter integers in a field for string and stuff like that.
I don't know if you understand what I'm saying

**Comment by simolus3** [comment]
>  I don't know if you understand what I'm saying

Not really. I understand that integers can be inserted into columns declared as strings (although you can kind of prevent this with [strict tables](https://www.sqlite.org/stricttables.html)). But how is this a problem? Is it important that single quotes are added around those values?

**Comment by Somtobro** [comment]
Hey bro, again not related and I know this is long but I would really appreciate your help and experience on this one.

So, I was using the sqflite package and I noticed something unusual or maybe a bug w the transaction

I'm running a modify table query in a transaction.
In the query below ,If I skip adding apostrophe's to indicate it's a string like I did with bbbb(default value ) below in the first line, this emptys my table when it's done, it doesn't show an error or rollback or anything (recall I'm using a transaction)  so that's what I expected

Query:
ALTER TABLE "person_organization_member_association" ADD COLUMN "COLUMN_NAME" REAL DEFAULT bbbb; CREATE TABLE "new_person_organization_member_association" ("person_id" INTEGER,"organization_id" TEXT,"COLUMN_NAME" REAL DEFAULT bbbb);INSERT INTO "new_person_organization_member_association" ("person_id","organization_id") SELECT "person_id","organization_id" FROM "person_organization_member_association";DROP TABLE "person_organization_member_association";ALTER TABLE "new_person_organization_member_association" RENAME TO "person_organization_member_association";



On the other hand, if run this exact code with a single modification i.e putting bbbb into apostrophe's like 'bbbb', it works perfectly


Still note if I run just the alter query without creating and the others(just the first single query).it also works perfectly

So I was  thinking the transaction isn't waiting for the previous one to finish before running the next one until I saw this:
https://github.com/tekartik/sqflite/issues/604

If you need to see my code please ask

**Comment by simolus3** [comment]
I can't really help you with sqflite, I'd suggest asking on StackOverflow or in their issue tracker with a more isolated case that reproduces the behavior you're seeing.

> On the other hand, if run this exact code with a single modification i.e putting bbbb into apostrophe's like 'bbbb', it works perfectly

Well, it's a syntax error without the quotes, right? Maybe sqflite splits the statements internally and runs them one-by-one, without aborting when a statement fails? But I don't know enough about that to be helpful here unfortunately.

**Comment by Somtobro** [comment]
Thanks for the advice.

**Comment by Somtobro** [comment]
Hey bro, long time I have a question.
I'm actually making a sql database app that's why I'm using every feature of this package 😅.
I have a sql editor
When the user enters a sql statement, it could be single or multiple.
How do I get the table name from this statement?
I already have something set up...I just got an error from a tester that I didn't see coming at all so I'm thinking of changing my whole current approach.
Currently I'm checking the types and then getting the table name from FROM.

It would have be cool if I could get it without checking the types  and doing #...as Select statement ...
But that's not a feature in the package which I understand .
What I'm asking now is how would you handle this personally

**Comment by simolus3** [comment]
>  How do I get the table name from this statement?

There's no well-defined answer to that because queries can operate on more than one table. Drift is using [findReferencedSchemaTables](https://pub.dev/documentation/sqlparser/latest/utils.find_referenced_tables/FindReferenceAnalysis/findReferencedSchemaTables.html), which you can call on `SqlEngine` by passing the generic `AstNode` from the statement you want to analyze. It returns a set of table names referenced in the query. It's also smart enough to not include aliases/result sets defined in the query (e.g. because they're coming from a `WITH` clause).
