### ISSUE TITLE
How to import customStatement ?

### ISSUE THREAD

**Issue by andim27** [simolus3/moor#2527]
`import 'package:drift/drift.dart'; 
 import 'package:drift/native.dart';`
But can't import customStatment

![drift_custom](https://github.com/simolus3/drift/assets/4599713/c4f31ff8-71c4-4fe8-8b8a-e8539596ce4d)

Please correct in the documentation if this is a realtime instance method

**Comment by simolus3** [comment]
[`customStatement`](https://drift.simonbinder.eu/api/drift/databaseconnectionuser/customstatement) is indeed an instance member on the database class.

The documentation mentions that the snippet should be placed inside the database class, so I think it's fine?

**Comment by andim27** [comment]
yes, explicit is better than implicit It is better to correct the documentation ))
