### ISSUE TITLE
Select query between range number

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#253]
I would like to select  data where number is between 1 and 10. Where can I find such information ?
```
Future<List<ABC>> getData(int num1, int num2) {
    return (select(abcs)..where((t) => t.number.between(num1, num2)))
        .go();
  }
```

**Comment by simolus3** [comment]
Using `t.number.isBetweenValues(num1, num2)` should do the trick.

**Comment by tony123S** [comment]
` return (delete(abcs)..where((t) => t.number.isBetweenValues(num1,num2))).go();`

**Error**

> The method 'isBetweenValues' isn't defined for the class 'GeneratedIntColumn'.
> Try correcting the name to the name of an existing method, or defining a method named 'isBetweenValues'.dart(u

Here how I define column name

` IntColumn get name => number().nullable()();`

**Comment by simolus3** [comment]
Interesting, which moor version are you using?

**Comment by tony123S** [comment]
1.6.0

**Comment by simolus3** [comment]
Oh, in that case I would definitely recommend the update to moor 2.0, where `isBetweenValues` was introduced. The [changelog](https://pub.dev/packages/moor#200) explains the breaking changes.

**Comment by tony123S** [comment]
@simolus3  After changed to drift, the method 'isBetweenValues' isn't defined for the type 'GeneratedColumn'.

**Comment by simolus3** [comment]
[It is still there](https://drift.simonbinder.eu/api/drift/comparableexpr/isbetweenvalues), can you make sure that you're importing `package:drift/drift.dart` into the file where you're calling `isBetweenValues`? Are the generated files up to date as well?

**Comment by ogak-github** [comment]
![Image](https://github.com/user-attachments/assets/1ee0be2d-e8f1-4c79-b15c-646f81ced616)

```
 drift: ^2.23.1
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.30
  sqlite3: ^2.7.4
```
this is confusing, 

solution:
import drift/drift.dart manually
