### ISSUE TITLE
Should NativeDatabase.createInBackground offer a preSetup parameter to call open.overrideFor(OperatingSystem.android, openCipherOnAndroid)?

### ISSUE THREAD

**Issue by GP4cK** [simolus3/moor#2545]
**Is your feature request related to a problem? Please describe.**
I'm trying to combine the instructions of the getting started to open an encrypted database in an isolate. The problem is that `open.overrideFor(OperatingSystem.android, openCipherOnAndroid)` needs to be called in the isolate that handles the database. However, I haven't found a way to do that with `NativeDatabase.createInBackground`.

As a workaround, I ended up copying the code of `NativeDatabase.createBackgroundConnection` and `_NativeIsolateStartup` just to add that one line in `_NativeIsolateStartup.start`.

**Describe the solution you'd like**
If you're ok, I'm happy to submit a PR to add an optional parameter (`override`, `preSetup`?) to that later, we can only do this:

```dart
NativeDatabase.createInBackground(
  File(...),
  setup: (db) { ... },
  override: () => open.overrideFor(OperatingSystem.android, openCipherOnAndroid),
)
```

**Comment by simolus3** [comment]
Good idea, thanks for the suggestion and for offering your help!

I think a good name might be `isolateSetup`, what do you think?
