### ISSUE TITLE
How to convert a Companion into an Entity?

### ISSUE THREAD

**Issue by ddxl123** [simolus3/moor#2547]
UserCompanion  to User

**Comment by simolus3** [comment]
You can call [`mapFromCompanion`](https://drift.simonbinder.eu/api/drift/tableinfo/mapfromcompanion) on the table instance (e.g. `await users.mapFromCompanion(yourUsreCompanion)`).

Note that this can only work when all fields in the companion are set, that method won't make stuff up for you.
