### ISSUE TITLE
substr function on Expression<String>

### ISSUE THREAD

**Issue by Guang-B** [simolus3/moor#2555]
I need to build SQL In clause like the following;

SELECT SUBSTR(my_column,1,23) as my_sub_column from my_table

but in the Expression<String> don't have that function.

please help me. Thank You

**Comment by simolus3** [comment]
Support for this will be added in the next drift version (added in f3e6ef26c4b84663ec9016a08dca1b3b375b720f). In the meantime, you can use `FunctionCallExpression('substr', [myColumn, Constant(1), Constant(23)])` to generate that expression.

**Comment by Guang-B** [comment]
hello [simolus3](https://github.com/simolus3), i have another case for this.
i want to substring from the right like the following :
 SELECT SUBSTR(my_column,1,length(my_column)-6) as my_sub_column from my_table

how can i get this ? thank you

**Comment by simolus3** [comment]
You can use `myColumn.substrExpr(Variable(1), myColumn.length - Variable(6))` starting from drift version 2.16.0 (which I've just released).

**Comment by Guang-B** [comment]
Thank you [simolus3](https://github.com/simolus3), Problem Solved.
