### ISSUE TITLE
Query stream doesn't receive pause event after using certain stream transformers

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#2564]
I'm guessing this is another case where the root cause is https://github.com/dart-lang/tools/issues/1778, but figured I'd check if anything here sticks out to you. 

The following shows the difference between Drift's `asyncMap` and Dart's `asyncMap` (though I'm sure it's the same case for other stream transformers too). 

```dart
import 'dart:async';

import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:test/test.dart';

void main() {
  driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;

  for (final useDriftAsyncMap in [true, false]) {
    final description = useDriftAsyncMap
      ? "query stream honors pause after being transformed by drift's asyncMap"
      : "query stream honors pause after being transformed by dart's asyncMap";
    test(description, () async {

      var counter = 0;
      final database = TestDb(() => counter++);

      var selectable = database.customSelect(
        'select 1, invoke_callback()',
        readsFrom: {database.fakeTable},
      );

      final stream = useDriftAsyncMap
          ? selectable.asyncMap((x) async => x).watchSingle()
          : selectable.watchSingle().asyncMap((x) async => x);

      await pumpEventQueue();

      expect(counter, 0, reason: 'no listener yet');

      final sub = stream.listen(null);
      await pumpEventQueue();

      expect(counter, 1, reason: 'listener attached');

      sub.pause();

      database.markTablesUpdated([database.fakeTable]);
      await pumpEventQueue();

      expect(counter, 1, reason: 'stream should not react to table updates when there are 0 un-paused listeners');

      sub.resume();
      await pumpEventQueue();

      expect(counter, 2, reason: 'resuming listening should re-execute the query');
    });
  }
}

DatabaseSetup createCallbackFunction(void Function() f) =>
  (db) => db.createFunction(
    functionName: 'invoke_callback',
    function: (_) {
      f();
      return null;
    },
  );

class TestDb extends GeneratedDatabase {
  TestDb(void Function() callback) : super(
    NativeDatabase.memory(setup: createCallbackFunction(callback))
  );

  late final fakeTable = FakeTable(this);

  @override
  List<TableInfo> get allTables => [fakeTable];
  @override
  final int schemaVersion = 1;
  @override
  MigrationStrategy get migration => MigrationStrategy(onCreate: (_) async {});
}

class FakeTable extends Table with TableInfo {
  FakeTable(this.attachedDatabase);

  @override
  final DatabaseConnectionUser attachedDatabase;

  @override
  final actualTableName = 'fake_table';

  @override
  List<GeneratedColumn<Object>> get $columns => throw UnimplementedError();

  @override
  TableInfo<Table, dynamic> createAlias(String alias) =>
      throw UnimplementedError();

  @override
  FutureOr map(Map<String, dynamic> data, {String? tablePrefix}) =>
      throw UnimplementedError();
}
```

```console
package:matcher                  expect
test\drift_pause_test.dart 42:7  main.<fn>

Expected: <1>
  Actual: <2>
stream should not react to table updates when there are 0 un-paused listeners
```

In our case since it's already a broadcast stream, we can work around this by using cancel+listen instead of pause+resume.

**Comment by simolus3** [comment]
Yeah, the problem is [asyncMap using a broadcast stream controller internally](https://github.com/dart-lang/sdk/blob/d31689ae2f68fd4022f6e12f6df130b7b23b2bac/sdk/lib/async/stream.dart#L775-L781). In that case, drift doesn't have any chance of knowing whether a subscription has been paused downstream, so there's likely no way to fix this in drift (or at least nothing comes to my mind).

From my point of view (which I kind of see being supported by lrhn's points in the issue you've referenced), the `asyncMap` implementation in Dart is technically incorrect. But it's unlikely to get fixed since it comes with a performance degradation (at the moment, all listeners of an `asyncMap` stream instance share invocations of the async mapper, this wouldn't be the case with a per-subscription transformation).

**Comment by Mike278** [comment]
Yeah makes sense - and you can see that reflected in the presence/absence of `onPause/onResume` parameters in the two `StreamController` constructors. I can definitely think of broadcast streams that should never pause regardless of whether their listeners are paused, but it'd be nice if there was a way to control that behavior. 

At least in Drift's case you can cancel+listen to get the same behavior as pause/resume, so it's straightforward fix.

Thanks as always for taking a look!
