### ISSUE TITLE
table sqlite_schema is not accessable at .drift files

### ISSUE THREAD

**Issue by pomid** [simolus3/moor#2567]
hello
i just wanted to thank you for your wonderful work mate 👍 

i was trying to access [sqlite_schema](https://www.sqlite.org/schematab.html) table in a .drift file and at building i get:
line 14, column 26: `sqlite_schema` could not be found in any import.
   ╷
14 │ getschema: select * from sqlite_schema;
   │                          ^^^^^^^^^^^^^
   ╵
from build_runner

love
h

**Comment by simolus3** [comment]
Thanks for the report. This is supposed to work, and I think apart from the error it does. The linked commit should fix the superflous error message as well, so this will be fixed in the next drift version.
