### ISSUE TITLE
Documentation Update for Firefox Private Browsing?

### ISSUE THREAD

**Issue by gokhanmeteerturk** [simolus3/moor#2570]
**Describe the bug**
Documentation [claims](https://drift.simonbinder.eu/web/#storages) Firefox does not support IndexedDB, so drift needs to fall back to an in-memory database in that case.

Well, this is not the case for a while. Firefox 115.0 and newer versions supports indexedDb in private browsing by default now.(Documentation states that the tested version is 114)
Release notes can be found [here](https://www.mozilla.org/en-US/firefox/115.0/releasenotes/).

Tried the compatibility test on Firefox 116 (private tab):
```
Chosen implementation: WasmStorageImplementation.sharedIndexedDb
Features missing: {MissingBrowserFeature.fileSystemAccess}
```

**Comment by simolus3** [comment]
Thanks for bringing this to my attention, I'll update the docs with the next drift release.
