### ISSUE TITLE
Adding spatiallite support

### ISSUE THREAD

**Issue by tiborrr** [simolus3/moor#2571]
**my app requires spatial queries, it would be great if Drift could provide me with those.**

**Describe the solution you'd like**
Adding spatiallite as optional plugin somehow would be really amazing.

**Comment by simolus3** [comment]
I haven't used Spatialite, and while contributions adding support for Spatialite would be welcome, I don't have plans to implement support for Spatialite functions myself.

But note that you can use Spatialite with drift already with a bit of work:

- When constructing queries with the Dart API, you can use a `FunctionCallExpression` to invoke any sqlite3 function, including those contributed by the Spatialite extension. You can factor out these expressions into their own methods or extensions to write a Spatialite DSL.
- When using drift files, you can define [additional functions](https://drift.simonbinder.eu/docs/advanced-features/builder_options/#known-custom-functions) to aid type inference and to avoid warnings about missing functions.
