### ISSUE TITLE
Using row.read(...) for mapping now (v2.11.0) requires the column to be added through query.addColumns()

### ISSUE THREAD

**Issue by matteoscaramuzza** [simolus3/moor#2572]
I have written a query with multiple joins and a group by. When i try to map the result, if I don't add the column that i want to read from one of the joined tables' columns using query.addColumns() before mapping it throws this error:

Invalid argument(s): Invalid call to read(): Instance of 'GeneratedColumn<int>'. This result set does not have a column for that expression.

In the previous version (v2.10.0) it was working without problems. It's very annoying because in this case I map a lot of columns from a lot of joined tables and now I'd have to add every column using addColumns().

**Comment by simolus3** [comment]
Thanks for the report, this should be fixed in b5a564f05545b9c656e1985ea7344f6b75cf9d7c - I'll probably release the next drift version early next week.
