### ISSUE TITLE
Prisma schema support

### ISSUE THREAD

**Issue by listepo** [simolus3/moor#2578]
It would be nice to be able to use a [Prisma schema](https://www.prisma.io/docs/concepts/components/prisma-schema) for code generation as an alternative way to describe a schema.
Original support is either not planned or with a very low priority.

**Comment by simolus3** [comment]
I don't think that schema level should be part of drift. Drift is not trying to be a full ORM but rather a library for making SQL more convenient to write. Things like automatically resolving joins and so on are not in the scope of the project from my point of view (even though drift is likely a great building block for such a solution if anyone wants to build that ontop of it).

You can use [drift files](https://drift.simonbinder.eu/docs/using-sql/drift_files/) as an alternative to Dart table definitions if you prefer.

**Comment by listepo** [comment]
Thanks for the feedback
