### ISSUE TITLE
Release hotfix 2.11.1

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#2580]
@simolus3 Hello!
After updating Drift to 2.11.0 I encountered with what it appears to be a regression bug that was fixed in 2.11.1, but it seems like the fix is not in pub.dev yet. Is that intentional?

Thanks!

**Comment by simolus3** [comment]
Kind of, I've been away for the last two weeks and didn't work on drift so much. I wanted to avoid releasing a new version in case something went horribly wrong. But my current plans are to release them tomorrow or on Monday.

**Comment by simolus3** [comment]
And they've just been released!
