### ISSUE TITLE
`stepByStep` should either automatically disable foreign keys or documentation should be slightly changed

### ISSUE THREAD

**Issue by f-person** [simolus3/moor#2582]
Hey there, I hope you're having a lovely day!

The docs on migration from https://drift.simonbinder.eu/docs/advanced-features/migrations/ say the following:

> * always re-enable foreign keys before using the database by enabling them in [beforeOpen](https://drift.simonbinder.eu/docs/advanced-features/migrations/#post-migration-callbacks).
> * disable foreign-keys before migrations

However, the generated `stepByStep` function doesn't include this, and the documentation providing an example of step-by-step migrations doesn't mention foreign keys at all:
```dart
    onUpgrade: stepByStep(
      from1To2: (m, schema) async {
        // we added the dueDate property in the change from version 1 to
        // version 2
        await m.addColumn(schema.todos, schema.todos.dueDate);
      },
      from2To3: (m, schema) async {
        // we added the priority property in the change from version 1 or 2
        // to version 3
        await m.addColumn(schema.todos, schema.todos.priority);
      },
    ),
```

I think either `stepByStep` should call `PRAGMA foreign_keys = OFF` (if that's ok to do?), or some info on foreign keys needs to be added to the step-by-step section of migration docs since I feel like it'd currently be easy to get confused or ignore this (which is probably bad?). 

Thank you!

**Comment by simolus3** [comment]
In the next drift version, we'll have a method to customize the `stepByStep` function by integrating it into a larger `onUpgrade` method. I've documented that in 3403161178a602907cf125a87da43d9dee42fea9, also mentioning how it can be used to implement the tips you're referencing.

I'm not sure if `stepBySteps` should do that by default. It's probably useful, but we can't reliably know whether we're in a debug mode from a pure-Dart package I think. So we can't implement all the tips.
