### ISSUE TITLE
customSelect

### ISSUE THREAD

**Issue by Manhal1994** [simolus3/moor#2583]
Watch with customSelect not work

When a new row inserted into database stream not emit a new value unlike built-in select.

` Stream<List<Category>> getCategories() {`
  `  return customSelect("Select * from categories").watch().map((rows)`
` {`
     ` return rows.map((row) =>`
       `   Category(id: row.data["id"], name: row.data["name"])).toList();`
  `  });`
 ` }`

**Comment by Mike278** [comment]
Have a look at [this part](https://drift.simonbinder.eu/docs/using-sql/custom_queries/#:~:text=for%20custom%20selects%2C%20you%20should%20use%20the%20readsfrom%20parameter%20to%20specify%20from%20which%20tables%20the%20query%20is%20reading) of the "Custom select statements" docs.
