### ISSUE TITLE
drift-dev: Connect method missing in Generated Database for generated test classes for migration

### ISSUE THREAD

**Issue by becjit** [simolus3/moor#2584]
First of all it is a wonderful package. I am blown away by its sophistication and simplicity.
Everything was a breeze till I started testing the migration. 
I have folllowed the steps mentioned in https://drift.simonbinder.eu/docs/advanced-features/migrations/ but hit a roadblock while checking data integrity

The problem is my generated DataBase class does not have a connect method

```dart
class DatabaseAtV1 extends GeneratedDatabase {
  DatabaseAtV1(QueryExecutor e) : super(e);
  late final AssessmentSessions assessmentSessions = AssessmentSessions(this);
  late final Questions questions = Questions(this);
  @override
  Iterable<TableInfo<Table, Object?>> get allTables =>
      allSchemaEntities.whereType<TableInfo<Table, Object?>>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities =>
      [assessmentSessions, questions];
  @override
  int get schemaVersion => 1;
}
```

so I am getting a compilation error with this code
```dart
 final schema = await verifier.schemaAt(1);

    // Add some data to the users table, which only has an id column at v1
    final oldDb = v1.DatabaseAtV1.connect(schema.newConnection());
```

```yaml
drift_dev: ^2.11.1
drift: ^2.11.1
sqlite3_flutter_libs: ^0.5.0
sdk: ">=3.0.0 <4.0.0"
```

Any help would be greatly appreciated

**Comment by kuhnroyal** [comment]
I think this documentation is still pre Drift 2.5 - You can now pass the connection directly to the database constructor.

Try this:
```dart
// Add some data to the users table, which only has an id column at v1
final oldDb = v1.DatabaseAtV1(schema.newConnection());
```

**Comment by becjit** [comment]
Works. Thanks @kuhnroyal ! Should I close the issue or keep it here to update the doc?

**Comment by kuhnroyal** [comment]
Probably rename and keep it open. Or provide a PR with the fix :)

**Comment by simolus3** [comment]
Indeed, the `.connect()` constructor is no longer generated by default since it's not necessary. I've updated the documentation in 043d41ee7327e798b0d8ae23d802d08ceec74bec.
