### ISSUE TITLE
build runner does not generate .g file , but .drift.dart

### ISSUE THREAD

**Issue by nyto9999** [simolus3/moor#2587]
**Describe the bug**

It was fine in few weeks ago, I have tried different Drift versions and also earlier versions of my database, no idea where is going wrong
![image](https://github.com/simolus3/drift/assets/49970020/3dfe425e-77bc-4f1d-b9ab-d1e01b554e21)

![image](https://github.com/simolus3/drift/assets/49970020/01e481dc-dc2d-42e5-a533-06c8e299660c)

![image](https://github.com/simolus3/drift/assets/49970020/6a3566f9-6e17-4044-a04a-69f377b6298e)

**Comment by simolus3** [comment]
If you want drift to emit a `.g.dart` file only, you can change the `build.yaml` to:

```yaml
targets:
  $default:
    builders:
      drift_dev:
        options:
          skip_verification_code:true
```

You can remove the other targets and the custom definition. But note that you won't be able to use drift-generated classes as inputs to other builders (like `built_value`) in that case - I guess that's where your build config originally came from?

Drift will emit a `.g.dart` file by default, so you can revert the complex build config if that's the behavior you want.

**Comment by simolus3** [comment]
Revisiting this, it looks like you want drift-generated code to be visible to other builders? That will only work with drift generating separate files, so you'd have to change `part` statements to reference the `.drift.dart` files. If you don't need that, reverting the build config will make drift emit `.g.dart` files again.
