### ISSUE TITLE
Documentation issue: Encryption

### ISSUE THREAD

**Issue by FMorschel** [simolus3/moor#2588]
The code block with:

```dart
NativeDatabase(
  File(...),
  setup: (rawDb) {
    assert(_debugCheckHasCipher());
    rawDb.execute("PRAGMA key = 'passphrase';");
  }
);
```

Should be updated to:

```dart
NativeDatabase(
  File(...),
  setup: (rawDb) {
    assert(_debugCheckHasCipher(database));
    rawDb.execute("PRAGMA key = 'passphrase';");
  }
);
```

As written in the paragraph above to match the `_debugCheckHasCipher` signature.

**Comment by simolus3** [comment]
Thanks for the report, this has been fixed in 9ada08d2d6202822357e1130cf634738cd2c5d44 (although the changes will only be published with the next drift release).
