### ISSUE TITLE
Table exists but sometimes it returns error SqliteException(1): while preparing statement, no such table:

### ISSUE THREAD

**Issue by matteoscaramuzza** [simolus3/moor#2594]
I haven't understood which are the conditions but in the same run i made a select from the table and it returns me 0 rows without throwing any error, but then i try to delete and batch insert values into it inside a transaction and it returns the error in the title.

The table exists because I have installed drift_db_viewer and I see it

**Comment by matteoscaramuzza** [comment]
It happens only on Android

**Comment by matteoscaramuzza** [comment]
I think I have resolved the problem: I had to programmatically delete the sqlite database (uninstall the app or clearing the data wasn't enough).
Maybe it was somehow corrupted

**Comment by Zhamshid** [comment]
This problem can be encountered by the user if we update the table on new versions of the application? I just met this problem too in debug mode(development stage), I deleted and installed the application and everything is ok. @matteoscaramuzza @simolus3

**Comment by simolus3** [comment]
> This problem can be encountered by the user if we update the table on new versions of the application?

After changing the schema of the database for users (e.g. by adding a new table or by altering an existing one), you need to [write a migration](https://drift.simonbinder.eu/docs/migrations/) to avoid this.
Deleting data during development is fine, but don't forget to write a migration before releasing an upgrade or your users will run into issues.
