### ISSUE TITLE
Multiple DB instances with same schema

### ISSUE THREAD

**Issue by becjit** [simolus3/moor#2597]
### Discussed in https://github.com/simolus3/drift/discussions/2596

<div type='discussions-op-text'>

<sup>Originally posted by **becjit** September  6, 2023</sup>
Hi,
  My app needs a separate database per profile. However the recommendation is to create a singleton. If I try to instantiate two Database objects using separate db files. I get the following error

 

> When these two databases use the same QueryExecutor, race conditions will occur and might corrupt the database.
> flutter: Try to follow the advice at https://drift.simonbinder.eu/faq/#using-the-database or, if you know what you're doing, set driftRuntimeOptions.dontWarnAboutMultipleDatabases = true

What is the recommended way of getting one db per user?
BTW, for all the DBs the schema remains the same</div>

**Comment by simolus3** [comment]
Please don't duplicate your questions, it won't help you get a response quicker.

**Comment by becjit** [comment]
My apologies! I got confused as there was an option to create an issue in the discussions page.
