### ISSUE TITLE
Error when using `TRIGGER` together with `validateDatabaseSchema`

### ISSUE THREAD

**Issue by muxinqi** [simolus3/moor#2600]
**Describe the bug**

The following two functions don't seem to work at the same time

1. Create triggers just like the way mentioned in [#1652 ](https://github.com/simolus3/drift/issues/1652#issuecomment-1020295482)
    ```dart
    class Todos extends Table with WithModificationTimestamps {
      IntColumn get id => integer().autoIncrement()();
      TextColumn get content => text()();
    }
    
    mixin WithModificationTimestamps on Table {
      DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
      DateTimeColumn get updatedAt => dateTime().withDefault(currentDateAndTime)();
    }
    
    @DriftDatabase(tables: [Todos])
    class MyDatabase extends _$MyDatabase {
      @override
      MigrationStrategy get migration {
        return MigrationStrategy(
          onCreate: (m) async {
            await m.createAll();
    
            for (final table in allTables) {
              if (table is WithModificationTimestamps) {
                final name = table.entityName;
    
                await customStatement('''
                CREATE TRIGGER updated_at_$name AFTER UPDATE ON $name
                BEGIN
                  UPDATE $name SET updated_at = CURRENT_TIMESTAMP;
                END;
                ''');
              }
            }
          },
        );
      }
    }
    ``` 
2. Verifying a database schema at runtime [docs](https://drift.simonbinder.eu/docs/advanced-features/migrations/#verifying-a-database-schema-at-runtime)
    ```dart
    @DriftDatabase(tables: [Todos])
    class MyDatabase extends _$MyDatabase {
      @override
      MigrationStrategy get migration {
        return MigrationStrategy(
          beforeOpen: (details) async {
            if (kDebugMode) {
              await validateDatabaseSchema();
            }
          },
        );
      }
    }
    ``` 

## Expected behavior

`validateDatabaseSchema` don't throw error

## The behavior I saw

`validateDatabaseSchema` throw error:

> Schema does not match
> additional:
> Contains the following unexpected entries:
> updated_at_todos

<img src="https://github.com/simolus3/drift/assets/42941327/4f57345e-6691-4cf9-9599-6aa9a69bae99" alt="Home page, showing thrown exceptions" width=500>

## Steps to reproduce

I've created a minimal reproducible example.

Repository: [drift_trigger_validate_demo](https://github.com/muxinqi/drift_trigger_validate_demo)

Archive: [drift_trigger_validate_demo-main.zip](https://github.com/simolus3/drift/files/12545688/drift_trigger_validate_demo-main.zip)

---

I've read the documentation carefully, and since it doesn't mention a recommended way to create triggers or a specific example, I'm not quite sure if this is a bug or if I'm creating triggers incorrectly.

Overall, thank you for the time and effort you put into this project, it is a great program and it helped me a lot.

**Comment by simolus3** [comment]
Thanks for the detailed description and the repository!

`validateDatabaseSchema` looks at the schema of the database as inferred by `drift_dev` and compares it with the actual schema of the database at runtime. When adding triggers in a migration callback, that causes a difference which will be flagged as error.

Instead of creating triggers with the migration API, you could dynamically construct them by overriding `allSchemaEntities`:

```patch
diff --git a/lib/database.dart b/lib/database.dart
index a3e5514..4a69de6 100644
--- a/lib/database.dart
+++ b/lib/database.dart
@@ -28,25 +28,34 @@ class MyDatabase extends _$MyDatabase {
   @override
   int get schemaVersion => 1;
 
+  @override
+  List<DatabaseSchemaEntity> get allSchemaEntities {
+    final result = super.allSchemaEntities;
+
+    for (final table in result.whereType<TableInfo>().toList()) {
+      if (table is WithModificationTimestamps) {
+        final name = table.entityName;
+        final triggerName = 'updated_at_$name';
+
+        result.add(
+          Trigger(
+            '''
+	       CREATE TRIGGER $triggerName AFTER UPDATE ON $name BEGIN
+	         UPDATE $name SET updated_at = CURRENT_TIMESTAMP;
+	       END;
+	      ''',
+            triggerName,
+          ),
+        );
+      }
+    }
+
+    return result;
+  }
+
   @override
   MigrationStrategy get migration {
     return MigrationStrategy(
-      onCreate: (m) async {
-        await m.createAll();
-
-        for (final table in allTables) {
-          if (table is WithModificationTimestamps) {
-            final name = table.entityName;
-
-            await customStatement('''
-            CREATE TRIGGER updated_at_$name AFTER UPDATE ON $name
-            BEGIN
-              UPDATE $name SET updated_at = CURRENT_TIMESTAMP;
-            END;
-            ''');
-          }
-        }
-      },
       beforeOpen: (details) async {
         if (kDebugMode) {
           await validateDatabaseSchema();
```

This has the same effect, except that the default `onCreate` migration will now create the triggers for you. And since they are included in `allSchemaEntities`, the schema validator will be happy too.

**Comment by muxinqi** [comment]
@simolus3 
Thank you for replying so quickly!

This solution allows triggers and database schema validation to work perfectly together.

It will definitely help those from the future.
