### ISSUE TITLE
Request: Docs for moving to stepwise migration tooling

### ISSUE THREAD

**Issue by dballance** [simolus3/moor#2601]
**Is your feature request related to a problem? Please describe.**
It's not clear from docs the best way to move from older migration patterns to the new stepwise migration pattern. 

We chose not to use codegen for generating tables and data classes, so we largely use `.drift` files and raw SQL for tables, indexes, simple and complex queries. We also use our own data classes imported into the drift files.

Because of this - we didn't have schema generation or schema dumps prior to our current schema level.

We've gone back and added schema for our deployed version and the migrations / schema between the latest deployed. We've added the new stepwise migration steps, along with tests, and really like how it works - it's much closer to how we handle schema updates on other platforms.

The pattern we've adopted is to give a floor to the `from` value in `migrator.runMigrationSteps` that equals the current migration. This allows our "legacy" migration code to play out, then we start as though we are the latest schema and migrate stepwise from that point on.

**Describe the solution you'd like**
If the below looks like a good pattern, adding it to the docs may be useful. Probably as a callout - "if you've already got a DB and looking to add the new stepwise migration" or similar. 

```dart
// Assuming you've already run your migration code up to schema 10 
// and you want to migrate to 11, 12, etc.. with stepwise, 
// pin the floor of the `from` value to 10.
await m.runMigrationSteps(
    from: math.max(10, from),
    to: to,
    steps: migrationSteps(...));
```

It could also be that you'd like to add some handling for this kind of case to the "runMigrationSteps" - like a `to10` step that handles cases before stepwise was added. Not sure this is better than the above - and I think the current functionality is fine considering this is all that is required to "move" to stepwise at a given schema point.

Happy to do the work to add to the docs, but didn't know if there was a need or opportunity to improve the docs or code here, which is why I'm opening this as a feature request.

**Comment by simolus3** [comment]
This sounds like a reliable pattern for moving towards the migration tooling, I agree that it should be pointed out in the docs.

I have plans to restructure the documentation to move towards smaller pages with more actionable advice to make them easier to access. I'll remember to add this then, but if you want to make a PR to the current docs I can also move it to the new page later. Contributions to the documentation are always much appreciated :)
