### ISSUE TITLE
Migration does not like hyphens in strings

### ISSUE THREAD

**Issue by MrTarantula** [simolus3/moor#2602]
When migrating, I am unable to use a custom expression to generate a UUID for a new column without adding my own quotes to the string:

```dart
import 'package:uuid/uuid.dart';

...

// works
final uuidExpr = CustomExpression("'${const Uuid().v4()}'");

// fails
final uuidExpr = CustomExpression(const Uuid().v4());

...

if (from < 3) {
  await m.alterTable(
    TableMigration(
      myTable,
      columnTransformer: {myTable.newUuidField: uuidExpr},
    ),
  );
}
```

As far as I'm aware, hyphens (-) do not need to be escaped in SQLite.

```
SqliteException(1): while executing, unrecognized token: "321d", SQL logic error (code 1)

     Causing statement: INSERT INTO tmp_for_copy_{{redacted}} ("id", {{redacted}}) SELECT "id", c5d96733-321d-48ec-b0a4-782926da0375, {{redacted}} FROM {{redacted}};,
```

**Comment by biloshkurskyi-ss** [comment]
Hello @MrTarantula .
Please take a look at the documentation. Also to the the examples: [link](https://github.com/simolus3/drift/tree/develop/examples).

Example from the doc:
```
await m.alterTable(
  TableMigration(
    usersAtV2,
    columnTransformer: {
      users.name: const Constant<String>('no name'),
    },
    newColumns: [usersAtV2.name],
  ),
);
```

My suggestion is that you should do the following:

```
m.alterTable(
  TableMigration(
    myTable,
    columnTransformer: {
      myTable.newUuidField: Constant<String>(const Uuid().v4());
    },
  ),
);
```

Also, I checked at my side:
Added a new column to the table: `TextColumn get testId => text()();`
Do not forget to update auto-generated files with:
`flutter pub run build_runner build --delete-conflicting-outputs`
If you are using more special migrations:
`dart run drift_dev schema dump lib/data/drift/db.dart drift_schemas/`
And also:
`dart run drift_dev schema generate drift_schemas/ lib/data/drift/generated` for getting v2, v3, etc...

Migration at the :

```
await m.alterTable(TableMigration(
  tableNameV2,
  columnTransformer: {
    tableName.testId: Constant<String>(const Uuid().v4()),
  },
  newColumns: [
    tableNameV2.testId,
  ],
)); 
```

Result:
<img width="292" alt="Screenshot 2023-09-08 at 22 10 23" src="https://github.com/simolus3/drift/assets/4133596/b7abd89d-0b1b-4d3e-82a6-75ac5046a3ca">


> As far as I'm aware, hyphens (-) do not need to be escaped in SQLite.

No, it can be with "-" which is the standard way of use UUIDs.

**Comment by MrTarantula** [comment]
> Please take a look at the documentation. Also to the the examples:

I've gotten pretty familiar with the documentation. Although there is a page on expressions, I couldn't find anything on when to use `Constant()` vs `Variable()` vs `CustomExpression()` vs some other built-in expression.

I also see these expressions in the API docs, but the `drift` namespace contains quite a bit of things that aren't expressions, so it's difficult to know what's in there.

Thank you, all the same. I do appreciate the assistance.
