### ISSUE TITLE
CHECK Feature enhancement: Check 1 out of N columns is not null

### ISSUE THREAD

**Issue by elkSal** [simolus3/moor#2604]
Hi,

I love this library and I'm grateful for all your work so far, thanks!

I recently bumped into a new constraint that I need to add to a Table that is as follows in SQL:

```
CREATE Table RandomTable (
field1_id INTEGER NOT NULL REFERENCES Table1(id),
field2_id INTEGER REFERENCES Table2(id),
field3_id INTEGER REFERENCES Table3(id),
field4_id INTEGER REFERENCES Table4(id),
CHECK (fiedl2_id IS NOT NULL + field3_id IS NOT NULL + field4_id IS NOT NULL = 1));
```

This SQL Constraint allows to check that one of the fields between field2_id, field3_id and field4_id must be not null.
I checked the whole Drift documentation but bumped only in check constraints for a row element (like lenght of an element).
Is it something that it's already possible to implement or that is not yet implemented?

Thanks!

**Comment by simolus3** [comment]
There's no Dart API for most foreign key constraints yet. You can override [ `customConstraints`](https://drift.simonbinder.eu/api/drift/table/customconstraints) on the table definition class to include the `CHECK` constraint though.

**Comment by elkSal** [comment]
Thanks @simolus3  for the quick feedback!

How would you write the above SQL table in Dart with customConstraints?
I saw the example of [customConstraints](https://drift.simonbinder.eu/docs/getting-started/advanced_dart_tables/#custom-constraints) on a single field but I found no example for a table constraint.

```
CREATE Table RandomTable (
field1_id INTEGER NOT NULL REFERENCES Table1(id),
field2_id INTEGER REFERENCES Table2(id),
field3_id INTEGER REFERENCES Table3(id),
field4_id INTEGER REFERENCES Table4(id),
CHECK (fiedl2_id IS NOT NULL + field3_id IS NOT NULL + field4_id IS NOT NULL = 1));
```

Thanks and thanks as well for the great library!

**Comment by simolus3** [comment]
This works:

```dart

class Table1 extends Table {
  IntColumn get id => integer().autoIncrement()();
}

class Table2 extends Table {
  IntColumn get id => integer().autoIncrement()();
}

class Table3 extends Table {
  IntColumn get id => integer().autoIncrement()();
}

class Table4 extends Table {
  IntColumn get id => integer().autoIncrement()();
}

class RandomTable extends Table {
  IntColumn get field1Id => integer().references(Table1, #id)();
  IntColumn get field2Id => integer().references(Table2, #id).nullable()();
  IntColumn get field3Id => integer().references(Table3, #id).nullable()();
  IntColumn get field4Id => integer().references(Table4, #id).nullable()();

  @override
  List<String> get customConstraints => [
        'CHECK (field2_id IS NOT NULL + field3_id IS NOT NULL + field4_id IS NOT NULL = 1)'
      ];
}
```
