### ISSUE TITLE
how to add a tokenize to the generated FTS5 table #5

### ISSUE THREAD

**Issue by lyyyann** [simolus3/moor#2605]
hi,In generating the FTS5 table, I need to use a Chinese tokenize for full-text indexing. What should I do?

**Comment by simolus3** [comment]
You're defining this table in a drift file, right? In that case, you can specify the tokenizer [with an option](https://www.sqlite.org/fts5.html#tokenizers).

We don't support custom tokenizers right now and I'm not sure if sqlite3 provides one for Chinese. If you need an API to define your own, that should be done in the `sqlite3` package. I can move the issue over if needed.

**Comment by lyyyann** [comment]
Thank you for your answer. I have chosen another package（  sqlite3+fts5_simple） as an alternative, i like drift's functions and features,but unfortunately I cannot use drift anymore
