### ISSUE TITLE
Postgres dialect failing when processing a numeric column

### ISSUE THREAD

**Issue by Leylan24** [simolus3/moor#2607]
When my dao processing a numeric column i get the following error:

```
type 'String' is not a subtype of type 'List<int>' in type cast
#0      PostgresBinaryDecoder.convert (package:postgres/src/binary_codec.dart:492:38)
#1      Codec.decode (dart:convert/codec.dart:30:34)
#2      _PgResultStreamSubscription.handleMessage (package:postgres/src/v3/connection.dart:509:34)
#3      PgConnectionImplementation._handleMessage (package:postgres/src/v3/connection.dart:328:25)
#4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
#7      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

I have two dialects a sqlite dialect and a postgres dialect as I am trying to read from both a postgres database and a sqlite version of the same database. The error occurs when the column is of type numeric.

My drift tables look as follows:
```
CREATE TABLE [bar_code_sell_price] (
	bar_code_sell_price_id INTEGER PRIMARY KEY,
	bar_code_id INTEGER NOT NULL,
	bar_code_sell_price_eff_start_date DATETIME NOT NULL,
	bar_code_sell_price_eff_end_date DATETIME NOT NULL DEFAULT '2099-12-31',
	bar_code_sell_price REAL NOT NULL,
	created_by TEXT NOT NULL DEFAULT 'current_user',
	created_on INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
	updated_by TEXT NOT NULL DEFAULT 'current_user',
	updated_on INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
);
```

The table that gives the error is the barcode_sell_price column.

I have also tried

```
-- bar_code_sell_price.drift

CREATE TABLE [bar_code_sell_price] (
	bar_code_sell_price_id INTEGER PRIMARY KEY,
	bar_code_id INTEGER NOT NULL,
	bar_code_sell_price_eff_start_date DATETIME NOT NULL,
	bar_code_sell_price_eff_end_date DATETIME NOT NULL DEFAULT '2099-12-31',
	bar_code_sell_price numeric(14,4) NOT NULL,
	created_by TEXT NOT NULL DEFAULT 'current_user',
	created_on INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
	updated_by TEXT NOT NULL DEFAULT 'current_user',
	updated_on INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
);

```

```
-- bar_code_sell_price.drift

CREATE TABLE [bar_code_sell_price] (
	bar_code_sell_price_id INTEGER PRIMARY KEY,
	bar_code_id INTEGER NOT NULL,
	bar_code_sell_price_eff_start_date DATETIME NOT NULL,
	bar_code_sell_price_eff_end_date DATETIME NOT NULL DEFAULT '2099-12-31',
	bar_code_sell_price REAL NOT NULL,
	created_by TEXT NOT NULL DEFAULT 'current_user',
	created_on INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
	updated_by TEXT NOT NULL DEFAULT 'current_user',
	updated_on INTEGER NOT NULL DEFAULT (strftime('%s', 'now')),
);

```

**Comment by Leylan24** [comment]
Not really sure how the cast gets set but to me it shouldnt be getting passed in as a List<int>.

**Comment by simolus3** [comment]
Could you report the exact `postgres` version from your `pubspec.lock`? I probably need it to match the stack traces.

Also, do you happen to know the query that caused it? A `SELECT * FROM bar_code_sell_price`?

**Comment by Leylan24** [comment]
```
  postgres:
    dependency: transitive
    description:
      name: postgres
      sha256: "98457afc06dd3f9d6892c178ea03ca9659e454107c9be90111e607691998d70d"
      url: "https://pub.dev"
    source: hosted
    version: "2.6.2"
```

the exact query that caused it is:

`[SELECT * FROM \"sku_bar_code_lookup_view\" WHERE \"bar_code\" = $1 LIMIT 1;](flutter: Drift: Sent SELECT * FROM central. "sku_bar_code_lookup_view" WHERE "bar_code" = $1 LIMIT 1; with args [0000002967270])`

Thats the view created from the table.

**Comment by Leylan24** [comment]
To help out and use the table i provided. i created a dao to lookup the barcode this was the query generated

`flutter: Drift: Sent SELECT * FROM  "bar_code_sell_price" WHERE "bar_code_id" = $1 LIMIT 1; with args [677374]`

the same error occurs:
```
 #0      PostgresBinaryDecoder.convert (package:postgres/src/binary_codec.dart:492:38)
flutter: #1      Codec.decode (dart:convert/codec.dart:30:34)
flutter: #2      _PgResultStreamSubscription.handleMessage (package:postgres/src/v3/connection.dart:509:34)
flutter: #3      PgConnectionImplementation._handleMessage (package:postgres/src/v3/connection.dart:328:25)
flutter: #4      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
flutter: #5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
flutter: #6      _DelayedData.perform (dart:async/stream_impl.dart:515:14)
flutter: #7      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
flutter: #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
flutter: #9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
flutter: #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by simolus3** [comment]
I couldn't even create the table you have in the drift file:

> PostgreSQLSeverity.error 22P02: invalid input syntax for type bigint: "2099-12-31"

The problem is that drift doesn't use the `datetime` type from postgres, we'd store them as timestamps and declare the column as `bigint`. Did you create the table manually outside of drift?

The stack trace seems to point toward us trying to read a postgres `NUMERIC` column which is not currently supported. I wonder why we're getting those rows though, is there really a `REAL` column in the table?

**Comment by Leylan24** [comment]
The table was created inside drift worked fine. We can remove the datetime columns it will be fine the important column is the NUMERIC column. I managed to get it to work by changing code in the postgres-dart package specifiically changing the numeric datatype to convert to a double instead of a List<int> to solve the error.

even testing without those columns and a simple database of numeric type it fails

**Comment by simolus3** [comment]
Using this table:

```sql
CREATE TABLE [bar_code_sell_price] (
	bar_code_sell_price_id INTEGER PRIMARY KEY,
	bar_code_sell_price REAL NOT NULL
);
```

Works for me when using it like this:

```dart
final database = MyDatabase(postgres);

await database.barCodeSellPrice.insertOne(BarCodeSellPriceCompanion.insert(
    barCodeSellPriceId: Value(1), barCodeSellPrice: 123.45));

print(await database.select(database.barCodeSellPrice).get());
```

I'll fix the numeric decoding bug in postgres, but that won't mean that drift will support the numeric type in postgres. Maybe we should look into supporting custom types for specific databases though.

**Comment by Leylan24** [comment]
@simolus3 relating to this line of code drift-2.11.1/lib/src/runtime/types/mapping.dart:194:
```
      case DriftSqlType.double:
        return (sqlValue as num?)?.toDouble() as T;
```
so what doesnt make sense to me is for numeric columns we will always return a String and therefore this line of code will error out.

i might not be understanding how the mapping works in relation to the generated code

**Comment by simolus3** [comment]
The regular types for this (`PgDataType.real`, `PgDataType.double` and the integer types) would work with the `as num`. So if you define a table with those types instead of `NUMERIC(...)`, this should work.

Only `PgDataType.numeric` returns a string. Arguably we should never report these as doubles since the type is meant to store numbers with exact precision. We should probably support `NUMERIC` as a custom type somehow, but at the moment we don't support that type.

**Comment by FLovisonRossi** [comment]
Hi,
I defined a column in PostgreSQL like this (drift file):

`amount NUMERIC(16, 2) NOT NULL`

(PostgreSQL 16.2 (Postgres.app) on aarch64-apple-darwin21.6.0)
I need the numeric type but a select returns a value
string as you wrote above.
To work I modified your mapping.dart file like this:
 ```
 DriftSqlType.double => switch (sqlValue) {
           BigInt() => sqlValue.toDouble(),
           String() => double.parse(sqlValue),           // ADDED THIS LINE
           _ => (sqlValue as num).toDouble(),
         },
```
Or is there a better way?
Thanks

**Comment by FLovison** [comment]
HI,
I defined a column in postgresql like this (I need _numeric_ type):

`amount numeric(16, 2) NULL`

(PostgreSQL 16.2 (Postgres.app) on aarch64-apple-darwin21.6.0)
Since the select returns me a string, I modified your _mapping.dart_ file like this:

```
      DriftSqlType.double => switch (sqlValue) {
          BigInt() => sqlValue.toDouble(),
          String() => double.parse(sqlValue),       // ADDED THIS
          _ => (sqlValue as num).toDouble(),
        },
```

I tried the money type but it's not supported, it returns a UndecodedBytes...
Or is there a better way?

Thanks

**Comment by FLovison** [comment]
Hi,
I need a numeric column with exact precision with PostgreSQL: so I'm using your CustomSqlType with Money type of money2 package:

```
class MoneyType implements CustomSqlType<Money> {
  const MoneyType();

  @override
  String mapToSqlLiteral(Money dartValue) => dartValue.amount.format('S ###.###,00');

  @override
  Object mapToSqlParameter(Money dartValue) => dartValue;

  @override
  Money read(Object fromSql) => Money.fromDecimal(Decimal.parse(fromSql as String), isoCode: 'EUR', decimalDigits: 2);

  @override
  String sqlTypeName(GenerationContext context) => 'money';
}
```

And in drift file : 

```
CREATE TABLE
  order_line (
    id INT NOT NULL PRIMARY KEY,
    amount `const MoneyType()` NOT NULL,
.....
```

And ... it works: convert from numeric (PostgreSQL) to string (drift) to money (my code) and reverse.
So, it's correct? Or is there a better way?
THANKS

**Comment by simolus3** [comment]
Generally this is the correct way to go about this, yes. I just think `mapToSqlParameter` is broken because the `postgres` package does not support the `Money` type - so mapping variables from Dart to SQL in prepared statements would likely not work. I don't think there's a way to reliably fix that without updating the postgres client though.

**Comment by FLovisonRossi** [comment]
Thanks, I'll do some more tests and then write again if necessary🙂

**Comment by FLovison** [comment]
Thanks, I'll do some more tests and then write again if necessary🙂
