### ISSUE TITLE
Step-by-step migration generation fails with specific table names

### ISSUE THREAD

**Issue by jmatth** [simolus3/moor#2610]
In my database schema I have a table called `entities`. When attempting to move to the new step-by-step style migrations, the generated code does not compile. This is because the generated schemas end up with two conflicting versions of a getter named `entities`: one inherited from `VersionedSchema` and one for my table of the same name. Here is a truncated example of the generated code to show the problem:

```dart
final class _S25 extends i0.VersionedSchema {
  _S25({required super.database}) : super(version: 25);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    campaigns,
    folders,
    entities,
    // ...
  ];
  // ...
  late final Shape26 entities = Shape26(
    // ...
  );
}
```

This issue will occur for tables with any of the following names:

- database
- version
- entities

### Officially disallow these table names

The current list of 3 forbidden table names isn't that restrictive, so it's always possible to say this is working as ~implemented~ intended and those table names just aren't supported. Personally if this is the case I would prefer if _all_ the Drift generators errored out or at least reported a warning if you used one of the reserved names. It would be a bit unfortunate to have everything working only to run into issues when you try to start using step-by-step migrations.

I'm also not sure this would fix my specific problem. I have ~25 versions of schema history I would like to migrate to the new step-by-step API. The old migrations need to continue to work, but I can't generate the step-by-step code for anything until I rename the `entities` table. Presumably I would need a way to make drift use old-style migrations up until the rename and then use step-by-step migrations afterwards. I think that's probably possible with the current set of APIs but I haven't fully investigated.

### Hide the drift getters in weird names

This is a common tactic I've seen in some Go libraries. Any fields that are reserved for the library but need to be public are given awkward, non-idomatic names to minimize the possibility of a user running into a conflict. So the three listed getters could be renamed to something like `DRIFT_database`, `DRIFT_version`, etc.

### Modify the table names to prevent conflicts

The code generator could modify the getter names to ensure there are never any conflicts. The simplest solution would probably be to just prepend or append some extra text. For example, always appending `Table` would result in my schema having `campaignsTable`, `foldersTable`, `entitiesTable`, etc.

A more complex solution would be to only modify the names of tables that would conflict with a reserved word. So my schema would become `campaigns`, `folders`, `entitiesTable`. This seems cleaner but requires more complex code to keep track of the modified getter names. Imagine I had an additional table called `entities_table`, so `entitiesTable` in camelCase. The generator would need to know that just appending `Table` to `entities` still produces a naming conflict and respond accordingly. I admit this is a bit contrived but if the generator is made more complex to solve this issue I think it makes sense to solve the issue for _every_ case.

One more option would be to generate an additional intermediate class that contains only the table getters. Something like this:

```dart
final class _S25Tables {
  const _S25Tables({
    required this.campaigns,
    required this.folders,
    required this.entities,
  });

  final Shape35 campaigns;
  final Shape17 folders;
  final Shape26 entities;
}

final class _S25 extends i0.VersionedSchema {
  _S25({required super.database}) : super(version: 25);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    tables.campaigns,
    tables.folders,
    tables.entities,
  ];

  late final tables = _S25Tables(
    campaigns: Shape35(
      //...
    ),
    folders: Shape17(
      //...
    ),
    entities: Shape26(
      //...
    ),
  );
}
```

This should solve the problem in every case (except for Dart reserved getters like `hashCode` but nothing to be done there).

Personally I like the nested `tables` object API the best, but would be happy with any of the modified generator options that make reserved table names no longer a thing. I'm happy to hack on the solution and open a PR, but wanted to get your feedback on the entire issue before going down the code generation rabbit hole.

**Comment by simolus3** [comment]
Thanks for the detailed report and the suggestions!

> This issue will occur for tables with any of the following names:

Static members are forbidden as well, so `stepByStepHelper` and `runMigrationSteps` are out too. Those might not be as relevant though :D

This is not only a problem with table names, but also with the getter names for columns potentially colliding with columns inherited from `VersionedTable` (and its superclasses).

> This is a common tactic I've seen in some Go libraries. Any fields that are reserved for the library but need to be public are given awkward, non-idomatic names to minimize the possibility of a user running into a conflict.

I've done that in some places by adding a `$` prefix to the identifiers, but I prefer the third approach you've suggested. Adding suffixes to fix this is a good approach for table names I think. We could detect duplicates by keeping a set of names, adding yet another suffix if there is a conflict. If you want to open a PR for this that would be awesome and much appreciated! [This file](https://github.com/simolus3/drift/blob/develop/drift_dev/lib/src/writer/schema_version_writer.dart) is responsible for the generation of step-by-step schemas, we can probably rename tables there.

---------

For conflicting column names, we could probably generate extensions instead of having the columns in the shape classes:

```dart
class _Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
}

extension Shape0 on _Shape0 {
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
}
```
