### ISSUE TITLE
Simple way to open WasmDatabase using inMemory implementation

### ISSUE THREAD

**Issue by velten-dev** [simolus3/moor#2611]
I am trying to make a build of my application which will serve as a demo mode. The demo mode is only built on the web mode and I want data to be ephemeral. Regardless of the browser and host config, I want to open the database using the inMemory implementation. 

I initially tried to code it using the following
```dart
return MyDb(
  LazyDatabase(() async {
    final sqlite3 =
      await WasmSqlite3.loadFromUrl(Uri.parse('/sqlite3.wasm'));
    return WasmDatabase.inMemory(sqlite3, logStatements: logStatements);
  }),
);
```

However, this failed to correctly open the database. I didn't see any exceptions from this code, but interacting with the database threw exceptions when attempting to read data. Looking at the reference Wasm implementation and the classes, I came up with the following solution which works.

```dart
return MyDb(
  LazyDatabase(() async {
    return DatabaseConnection.delayed(
      Future(
        () async {
          final probe = await WasmDatabase.probe(
            databaseName: dbName,
            sqlite3Uri: Uri.parse('/sqlite3.wasm'),
            driftWorkerUri: Uri.parse('/worker.dart.js'),
          );
          return probe.open(WasmStorageImplementation.inMemory, dbName);
        },
      ),
    );
  }),
);
```

If I missed something in my original implementation, please let me know. If not, can we expose an easier Wasm inMemory implementation similar to what we have for NativeDatabase? For either solution, adding this to the web documentation would be greatly appreciated.

Thanks for everything you've done with Drift! The changes and support for this database over the last year has been amazing!

**Comment by simolus3** [comment]
> Thanks for everything you've done with Drift! The changes and support for this database over the last year has been amazing!

Thanks, I'm happy to hear that!

> but interacting with the database threw exceptions when attempting to read data

I think this is because there is no VFS registered on the sqlite3 instance, this should work:

```dart
LazyDatabase(() async {
  final sqlite3 = await WasmSqlite3.loadFromUrl(Uri.parse('/sqlite3.wasm'));
  sqlite3.registerVirtualFileSystem(InMemoryFileSystem(), makeDefault: true);

  return WasmDatabase.inMemory(sqlite3, logStatements: logStatements);
})
````

> If not, can we expose an easier Wasm inMemory implementation similar to what we have for NativeDatabase?

I have added the snippet to the documentation of `WasmDatabase.inMemory` so that it can be used as a standalone thing more easily. I'm not sure if this is relevant enough to be mentioned on the website, I don't want to confuse new users with many different option (even the new web setup is not exactly trivial).
