### ISSUE TITLE
Delete row is not being propagated to foreign key dependent rows.

### ISSUE THREAD

**Issue by omensight** [simolus3/moor#2613]
**Describe the bug**

I have configured my tables to being deleted in case the parent table is deleted like in the next code:
```
@UseRowClass(Category, generateInsertable: true)
class Categories extends Table {
  TextColumn get id => text().map(IdToUuidConverter())();
  TextColumn get categoryName => text()();

  @override
  Set<Column<Object>>? get primaryKey => {id};
}
```
The dependent table is the next one:
```
@UseRowClass(Program, generateInsertable: true)
class Programs extends Table {
  TextColumn get id => text().map(IdToUuidConverter())();
  TextColumn get fkCategoryId => text().references(
        Categories,
        #id,
        onDelete: KeyAction.cascade,
      )();
  TextColumn get name => text()();
  TextColumn? get description => text().nullable()();
  BoolColumn get selectedByDefault => boolean()();
  BoolColumn get forceInstall => boolean()();
  IntColumn get programCommandStorageType =>
      integer().map(ProgramCommandStorageTypeConverter())();

  @override
  Set<Column<Object>>? get primaryKey => {id};
}
```

When I execute the next deletion I see that the it only deletes the Category row and it leaves orphan rows at Program table:
```
await (delete(categories)..where((tbl) => tbl.id.equals(categoryId))).go();
```
I've tried upgrading to 2.11.1 but it doesn't seem to work.
Note: The propagation is being generating:
```
WritePropagation(
            on: TableUpdateQuery.onTableName('categories',
                limitUpdateKind: UpdateKind.delete),
            result: [
              TableUpdate('programs', kind: UpdateKind.delete),
            ],
          ),
```
Thanks for your time.

**Comment by simolus3** [comment]
Did you enable the foreign keys pragma in sqlite3? Foreign keys are disabled by default.

If you haven't done that yet, a good place to enable foreign keys is in the [post-migration callback](https://drift.simonbinder.eu/docs/advanced-features/migrations/#post-migration-callbacks) by adding this to your migration strategy:

```dart
beforeOpen: (details) async {
  await customStatement('PRAGMA foreign_keys = ON');
}

```

**Comment by omensight** [comment]
I'm sorry this was


> Did you enable the foreign keys pragma in sqlite3? Foreign keys are disabled by default.
> 
> If you haven't done that yet, a good place to enable foreign keys is in the [post-migration callback](https://drift.simonbinder.eu/docs/advanced-features/migrations/#post-migration-callbacks) by adding this to your migration strategy:
> 
> ```dart
> beforeOpen: (details) async {
>   await customStatement('PRAGMA foreign_keys = ON');
> }
> ```

I made a typo, I wrote foreign_key instead foreign_keys, thank you so much, I'm so sorry.
