### ISSUE TITLE
select specify item

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#262]
```
Future<String> selectData(String id){
 return (select(datas)..where((t) => t.fid.equals(id))).go();

```
**Error**

` The method 'go' isn't defined for the class 'SimpleSelectStatement'.Try correcting the name to the name of an existing method, or defining a method named 'go'
`

**Comment by simolus3** [comment]
Is there a `.go()` call on a select statement somewhere in the docs? The correct thing would be to use `getSingle()`

**Comment by tony123S** [comment]
@simolus3  hi, what if I want to select data based on two conditions? And it should return as String.
