### ISSUE TITLE
Add a static equivalent of the table getter `actualTableName`

### ISSUE THREAD

**Issue by ValentinVignal** [simolus3/moor#2623]
**Is your feature request related to a problem? Please describe.**

In the project I'm working on. We record "updates"/"changes" of the local database in an outbox. In this outfox, there are 2 entries.
1. The name of the SQL table that was modified.
2. The modifications that were applied.

Let's say I have a table `Todos`:

```dart
class Todos extends Table {
  IntColumn get id => integer()();
  TextColumn get title => text()();
}
```

and let's say I have a method 

```dart
Future<void> recordChangesInOutbox(String tableName, Map<String, dynamic> changes);
```

When I want to record some changes I have to specify the table name `'todos'`. And I either have to hardcode it:

```dart
recordChangesInOutbox('todos', {});
```

Or I can use the generated `$TodosTable` by drift.
Unfortunately the getter `actualTableName` is not static so it forces me to instantiate the table:

```dart
recordChangesInOutbox($TodosTable(attachedDatabase).actualTableName, {});
```

**Describe the solution you'd like**

It would be useful to also generate a static getter to get the actual table name, for example:

```dart
static String get actualTableNameStatic;
```

so I don't have to instantiate the table:

```dart
recordChangesInOutbox($TodosTable.actualTableNameStatic, {});
```

**Comment by simolus3** [comment]
Is the problem not having access to the database?  `database.todos.entityName` is just as safe and possibly easier to write.

I don't have strong feelings about this, but so far the generated table info classes have been internal to drift and aren't supposed to be used as a stable API.

**Comment by ValentinVignal** [comment]
> Is the problem not having access to the database

Kind of, in that outbox code, there is no need to _"inject"_ or "_know"_ about the database
