### ISSUE TITLE
Ability to name array variable

### ISSUE THREAD

**Issue by sinhaaritro** [simolus3/moor#2633]
**Is your feature request related to a problem? Please describe.**
When a bind argument exists inside an IN clause we should able to **name the variable**. Array variables are generated with generic names like var1, var2, var3... 
This becomes a problem because now I have to look at the SQL to determine what var1, var2, or var3 means. The SQL generated is stored in a generated file so I can't use the doc comments above functions to indicate the meaning.
If we could name the variables then, the function parameter will tell us the means of the variable.

The following query 
```sql
SELECT todos.* FROM todos
INNER JOIN user
  ON user.user_id = todos.user_id
WHERE todos.todo_id IN ?
  AND user.user_id IN ?
```
generates 
`(List<int> var1, List<int> var2)`

**Describe the solution you'd like**
If we could name the variable then it would be easy to know what is var1 and var2
The query would become
```sql
SELECT todos.* FROM todos
INNER JOIN user
  ON user.user_id = todos.user_id
WHERE todos.todo_id IN ?todo
  AND user.user_id IN ?user
```
and the generates function would become
`(List<int> todo, List<int> user)`
Then with the todo and user in the function parameter, we can directly infer the type of ID needed.

**Comment by simolus3** [comment]
Although some of them are reserved for drift-specific features, the syntax for variables follows [what sqlite3 understands](https://sqlite.org/lang_expr.html#parameters).

So this works, and it generates named parameters:

```SQL
SELECT todos.* FROM todos
INNER JOIN user
  ON user.user_id = todos.user_id
WHERE todos.todo_id IN :todo_ids
  AND user.user_id IN :user_ids
```
