### ISSUE TITLE
The referenced element is not understood by drift

### ISSUE THREAD

**Issue by Rossdex** [simolus3/moor#2637]
**Describe the bug**
I have recently upgraded from drift 2.8.0 to 2.11.1, I have 50+ DAO's and since updating whenever I make a new one and build I get the below error. 

```
equipment_reservation_repository.dart: The referenced element, EquipmentReservation, 
is not understood by drift.

class EquipmentReservationRepository extends BaseEquipmentReservationRepository with 
_$EquipmentReservationRepositoryMixin { }
```

This has only happened since the update. 

For a bit of context I have all my DAO's extend through a base repository which has basic finds and gets. Each DAO is exported in this file like below: 

```
import 'package:drift/drift.dart';
import 'package:my_app/imports.dart';
part 'equipment_usage_repository.g.dart';

abstract class BaseEquipmentUsageRepository extends BaseRepository<EquipmentUsages, EquipmentUsage> {
  BaseEquipmentUsageRepository(AppDatabase db) : super(db, db.equipmentUsages);
}

@DriftAccessor(tables: [EquipmentUsage])
class EquipmentUsageRepository extends BaseEquipmentUsageRepository with _$EquipmentUsageRepositoryMixin {
  EquipmentUsageRepository(AppDatabase db) : super(db);
```

```
export 'equipment_reservation_repository.dart';
```

All tables and daos have been added to the DriftDatabase lists in base repository. 

This is **only** happening on new DAO's however I have cleared all cache on my computer and have run the build command with deletes as if fresh.

I do not have any issues with existing DAO's and the .g file is generated as normal.

**Comment by simolus3** [comment]
It's pretty weird that this only happens with new DAOs. Does `dart run build_runner clean` followed by a rebuild clear things up (it might then break all DAOs though)?

But this is likely the result of a recent build optimization made in `drift_dev`. That optimization failed to consider `export` statements until version 2.11.2, could you try upgrading to that version and see if it improves the situation?

**Comment by Rossdex** [comment]
Ah fantasic that has resolved the issue.
