### ISSUE TITLE
`setup` with `WasmDatabase.open`

### ISSUE THREAD

**Issue by Vorkytaka** [simolus3/moor#2638]
When we create NativeDatabase, we have an callback `setup`, that we use to handle some initialization with our db.
For example, for set encription key, or to create some db functions.

But WasmDatabase.open have no such option. Is that just missing or we need to make those setup some other way?

**Comment by simolus3** [comment]
It won't be possible to add a `setup` parameter for `WasmDatabase`. When using `NativeDatabase`, we can just invoke the callback on the created database. With `NativeDatabase.createInBackground`, we'll send the callback to the isolate opening the database and execute it there.  With a `WasmDatabase` however, the database might be opened in a web worker - and we can't send a callback function to that worker.

The best we'll be able to do is an API that enables you to compile your own drift worker registering the required database functions. For that it would be good to know what use cases you have in mind - custom functions that will be registered on every database instance or something more dynamic like an encryption key that needs to be communicated from the main document to the worker?

**Comment by Vorkytaka** [comment]
Well, with current native DB i'm use setup for both encryption key and registration of functions.

First one is sound optional for me, i'm not sure about sqlcypher on the web, but create functions is a very important part of my work with DB.

Maybe you can show some example of how I can do it now?
Or the only way is to not use `WasmDatabase.open`, but use some direct `WasmDatabase` constructor instead?

**Comment by simolus3** [comment]
> Maybe you can show some example of how I can do it now?

With the new `WasmDatabase.open` APIs, this will only be possible in the next drift version. You can use the old APIs though:

```dart
Future<WasmDatabase> customDatabase() async {
  final sqlite3 = await WasmSqlite3.loadFromUrl(Uri.parse('/sqlite3.wasm'));
  final fs = await IndexedDbFileSystem.open(dbName: 'my_app');
  sqlite3.registerVirtualFileSystem(fs, makeDefault: true);

  return WasmDatabase(
    sqlite3: sqlite3,
    path: '/app.db',
    setup: (db) {
      // you can register custom functions here
    },
  );
}
```
