### ISSUE TITLE
Failure to define indexes on expressions.

### ISSUE THREAD

**Issue by masahiro-ikemoto** [simolus3/moor#2643]
On Drift-2.11.1, I was able to define indexes on expressions like this:

`CREATE INDEX foo_index on foo(MAX(field1, field2));`

However, after upgrading to Drift-2.12, index creation fails with the following error

```
[WARNING] drift_dev on foo.drift:
Could not analyze DriftElementId(package:package/foo.drift, foo_index)
type 'FunctionExpression' is not a subtype of type 'Reference' in type cast
```

**Comment by simolus3** [comment]
Thanks for the report, this has been fixed in `drift_dev` version `2.12.1`.
