### ISSUE TITLE
Request for isolate message parameter in NativeDatabase.createInBackground()

### ISSUE THREAD

**Issue by jannis15** [simolus3/moor#2647]
I need to access the secret key for encrypting the database from a .env file in the setup callback function of NativeDatabase.createInBackground(). My problem is that you cannot access files from a non-root isolate, so i'd have to pass my secret through Isolate.spawn(). 

As of right now, there is no way to pass a custom message for the newly spawned isolate by NativeDatabase.createInBackground(). I would like to have access to that parameter. So far, I haven't found any other solution to ensure privacy for my pragma key.

**Comment by simolus3** [comment]
> My problem is that you cannot access files from a non-root isolate, so i'd have to pass my secret through Isolate.spawn().

Closures in recent Dart versions can be sent across isolates, so you can do

```dart
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    final secret = await loadMyDatabaseSecret();
    return NativeDatabase.createInBackground(
      file,
      setup: (rawDb) => rawDb.execute('pragma key = ?', [secret])
    );
  });
}
```

The `secret` will be transferred to the other isolate implicitly.

That said, you can also [manage drift isolates yourself](https://drift.simonbinder.eu/docs/advanced-features/isolates/#manually-managing-drift-isolates), which gives you full control over how the isolate is spawned.

**Comment by jannis15** [comment]
I will try this tomorrow. Thanks for the quick reply!
