### ISSUE TITLE
readIntsAsBigInt breaks RealColumn columns

### ISSUE THREAD

**Issue by mikemoore13** [simolus3/moor#2648]
for drift web with the option readIntsAsBigInt true it is impossible to insert a new row that contains both columns Int64Column  and RealColumn when the real column contains an integer value.

It is very important to noticed that the bug can be reproduced only if weight is an integer: 5 for example and not 5.0001
The bug is reproducable only with drift on the web
```
Int64Column and RealColumn 
@DataClassName('MY_CUSTOM_DTO_TABLE')
class MyCustomDto  extends Table {
  Int64Column get id => int64().clientDefault(() => buildId())();
  RealColumn get weight => real()();
}
```
buildId can returns 1 for example 

`return (await db.insert(dto)).id; //<-- this will cause an error:`

```
Error: Expected a value of type 'num?', but got one of type '_BigIntImpl'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 288:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 121:3       castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 529:12  cast
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/types.dart 417:9        as
packages/drift/src/runtime/types/mapping.dart 194:26                              read
packages/sporttrack/database/database.g.dart 5579:12                              map
packages/drift/src/runtime/query_builder/statements/insert.dart 178:22            <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50                <fn>
dart-sdk/lib/async/zone.dart 1661:54                                              runUnary
dart-sdk/lib/async/future_impl.dart 147:18                                        handleValue
dart-sdk/lib/async/future_impl.dart 784:44                                        handleValueCallback
dart-sdk/lib/async/future_impl.dart 813:13                                        _propagateToListeners
dart-sdk/lib/async/future_impl.dart 584:5                                         [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 657:7                                         callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                                  _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                                   _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 177:15               <fn>

```

**Comment by simolus3** [comment]
Thanks for the report, I've fixed this in d694b64e72a465d5251dd239b20f7ad098c9c3c4.

**Comment by mikemoore13** [comment]
Does it means I need to upgrade drift to lastest version In my flutter app puspec.yaml ?

Why is I needed to have this readIntsAsBigInt variable? Why not having it always true ?

**Comment by simolus3** [comment]
> Does it means I need to upgrade drift to lastest version In my flutter app puspec.yaml ?

The fix hasn't been released yet, but you could use a dependency override in the meantime:

```yaml
dependency_overrides:
  drift:
    git:
      url: https://github.com/simolus3/drift.git
      ref: d694b64e72a465d5251dd239b20f7ad098c9c3c4
      path: drift
```

> Why is I needed to have this readIntsAsBigInt variable? Why not having it always true ?

With the version of the `sql.js` library used originally, there was no way to tell it about the type of a variable when inserting into a table. It just sees a `5` and tells sqlite3 (the C library) that it's an int. When sqlite3 later reports that the `REAL` column contains an `int`, `sql.js` returns it as a bigint (which is required because we can't ask `sql.js` to only return some columns as big ints). Drift will only enable this behavior when an `in64` column is present since it is less efficient.

We can tell `sql.js` about the exact type in more recent versions, but that wouldn't fix existing databases. There has also been [a new web implementation](https://drift.simonbinder.eu/web/) that doesn't use `sql.js` and doesn't have this problem. So want to keep the old web implementation mostly as-is without any bigger changes. You could consider [migrating your database](https://drift.simonbinder.eu/web/#migrating-from-packagedriftwebdart) to the new system.

**Comment by mikemoore13** [comment]
is a fix planned ?

**Comment by mikemoore13** [comment]
i dont have yet deployed the web version, so loosing data for web is not an issue.
In case you released the fix, could i just upgrade drfit version from the yaml to benefit from it ?

**Comment by simolus3** [comment]
> is a fix planned ?

The mentioned fix has been released, so upgrading drift is enough.

> i dont have yet deployed the web version, so loosing data for web is not an issue.

In that case, consider using the new web implementation as documented [here](https://drift.simonbinder.eu/web/). It requires no external JavaScript dependencies, is easier to set up and more reliable. It never had this particular problem, for instance.

**Comment by mikemoore13** [comment]
@simolus3 after updating the code to use wasm the app stops to be able to perform write queries (or maybe it become super slow i waited around 10 minutes).
at startup i have this warining 
`Using WasmStorageImplementation.sharedIndexedDb due to unsupported browser features: {MissingBrowserFeature.dedicatedWorkersInSharedWorkers, MissingBrowserFeature.sharedArrayBuffers}`
i saw in the doc that i should add some header somewhere in the server configuration, but here i am in debug mode with android studio

```
Cross-Origin-Opener-Policy: Needs to be set to same-origin.
Cross-Origin-Embedder-Policy: Needs to be set to require-corp or credentialless.
```

Is this a known issue that drift freeze for write operation without these headers ?

```
import 'package:drift/drift.dart';
import 'package:drift/wasm.dart';
import 'package:my_app/database/database.dart';

AppDatabase constructDb() {
  return AppDatabase(
    DatabaseConnection.delayed(
      Future.sync(() async {
        final db = await WasmDatabase.open(
          databaseName: 'db',
          sqlite3Uri: Uri.parse('/sqlite3.wasm'),
          // driftWorkerUri: Uri.parse('/shared_worker.dart.js'),
          driftWorkerUri: Uri.parse('/drift_worker.js'),
        );

        if (db.missingFeatures.isNotEmpty) {
          print('Using ${db.chosenImplementation} due to unsupported '
              'browser features: ${db.missingFeatures}');
        }
        return db.resolvedExecutor;
      }),
    )
  );
}
```
in the web folder i have 
drift_worker.js
favicon.png
index.html <- i did not changed it
manifest.json <- not changed
sqlite3.wasm
sql-wasm.js
sql-wasm.wasm

**Comment by simolus3** [comment]
That sounds like a deadlock or maybe something silently failing and then blocking everything else. Are there any logs or failure indications in the console of the browser?

**Comment by mikemoore13** [comment]
there is just this log :
Using WasmStorageImplementation.sharedIndexedDb due to unsupported browser features: {MissingBrowserFeature.dedicatedWorkersInSharedWorkers, MissingBrowserFeature.sharedArrayBuffers}

nothing else in the web developper console and nothing in android studio debug console.
my html code look like this :

```
<!DOCTYPE html>
<html>
<head>

  <base href="/">

  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="tracking">

  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="st">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="icon" type="image/png" href="favicon.png"/>

  <title>st</title>
  <link rel="manifest" href="manifest.json">

  <script>
    // The value below is injected by flutter build, do not touch.
    var serviceWorkerVersion = null;
  </script>
 
  <!-- This script adds the flutter initialization JS code -->
  <script defer src="sql-wasm.js"></script>
  <script src="flutter.js" defer></script>
</head>
<body>
  <script>
    window.addEventListener('load', function(ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        },
        onEntrypointLoaded: function(engineInitializer) {
          engineInitializer.initializeEngine().then(function(appRunner) {
            appRunner.runApp();
          });
        }
      });
    });
  </script>
</body>
</html>

```

**Comment by mikemoore13** [comment]
maybe there is a way to activate more logs ?

**Comment by simolus3** [comment]
I see you still have `sql-wasm.js` as a script - you don't need that JavaScript library anymore when using `package:drift/wasm.dart`. On the other hand, it's worth noting that drift's `sqlite3.wasm` and sql.js' `sqlite3.wasm` are incompatible with each other. When using a `WasmDatabase`, you need to grab the `sqlite3.wasm` from [here](https://github.com/simolus3/sqlite3.dart/releases).

(we should still be able to detect that and throw an error though, I'll check what's going wrong here)

**Comment by mikemoore13** [comment]
i removed the script from the html and from the disk and still the same issue without any logs

as an information i added to the web folder this file as mentionend in the doc
├── drift_worker.js

and i also have this warning 
`WebGL: this extension has very low support on mobile devices; do not rely on it for rendering effects: WEBGL_polygon_mode`

**Comment by mikemoore13** [comment]
@simolus3 
i tried to open the url in firefox and it is a bit more verbose, i got this error in the browser console 

```
Error: [drift_worker.js:448:18](http://localhost:60017/drift_worker.js)
Error from backend:

Error: Bad state: Not connected to an application.

Stack Trace:
#0      DevHandler._handleConnection.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:273:13)
#1      _rootRunUnary (dart:async/zone.dart:1407:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
#7      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
#8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
#9      _rootRunUnary (dart:async/zone.dart:1415:13)
#10     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#14     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#15     _StreamController._add (dart:async/stream_controller.dart:650:7)
#16     _StreamController.add (dart:async/stream_controller.dart:598:5)
#17     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:730:21)
#18     _rootRunUnary (dart:async/zone.dart:1407:47)
#19     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#23     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#24     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#25     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:319:23)
#26     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:218:46)
#27     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#28     _rootRunUnary (dart:async/zone.dart:1407:47)
#29     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#34     _StreamController._add (dart:async/stream_controller.dart:650:7)
#35     _StreamController.add (dart:async/stream_controller.dart:598:5)
#36     _Socket._onData (dart:io-patch/socket_patch.dart:2368:41)
#37     _rootRunUnary (dart:async/zone.dart:1415:13)
#38     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#42     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:776:19)
#43     _StreamController._add (dart:async/stream_controller.dart:650:7)
#44     _StreamController.add (dart:async/stream_controller.dart:598:5)
#45     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1886:33)
#46     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1343:14)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:123:13)
#50     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:190:5)
```

**Comment by simolus3** [comment]
Did you also replace the `sqlite3.wasm` file? I think something is going wrong with the worker as well, it doesn't have any code in it that would open web sockets.

Can you try running [this example](https://github.com/simolus3/drift/tree/develop/examples/app) as a comparison and see if it works (you need to run `dart run build_runner build -d` once first). Then we know whether it's a general problem with drift and your Firefox or if it's something specific to the setup in your app.

**Comment by mikemoore13** [comment]
Sure I took the file from the release ( as mentioned in the doc) since the beginning. 
I will try running the example

**Comment by mikemoore13** [comment]
I solved the freezing issue, by taking sqlite3.wasm from the section  sqlite3_flutter_libs 0.5.20 instead of the section sqlite3 2.4.0.
i also upgraded drift to the latest version

but now i am getting again the BigInt error:
Using WasmStorageImplementation.sharedIndexedDb due to unsupported browser features: {MissingBrowserFeature.dedicatedWorkersInSharedWorkers, MissingBrowserFeature.sharedArrayBuffers}
```
Error: FormatException: Could not parse BigInt
{a: false, b: [37766, 0, 63687, 562, 0], c: 4}
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3  throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/bigint_patch.dart 134:7          parse
dart-sdk/lib/_internal/js_dev_runtime/patch/bigint_patch.dart 18:19          parse
packages/drift/src/runtime/types/mapping.dart 181:23                         <fn>
packages/drift/src/runtime/types/mapping.dart 181:13                         <fn>
packages/drift/src/runtime/types/mapping.dart 199:29                         read
packages/sporttrack/database/database.g.dart 2986:12                         map
packages/drift/src/runtime/query_builder/statements/insert.dart 178:22       <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50           <fn>
dart-sdk/lib/async/zone.dart 1661:54                                         runUnary
dart-sdk/lib/async/future_impl.dart 163:18                                   handleValue
dart-sdk/lib/async/future_impl.dart 847:44                                   handleValueCallback
dart-sdk/lib/async/future_impl.dart 876:13                                   _propagateToListeners
dart-sdk/lib/async/future_impl.dart 652:5                                    [_completeWithValue]
dart-sdk/lib/async/future_impl.dart 722:7                                    callback
dart-sdk/lib/async/schedule_microtask.dart 40:11                             _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 49:5                              _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 181:7           <fn>
```

the app is doing an insert on an empty table defined by :
`var dto = await db.into(table).insertReturning(row, mode: InsertMode.insertOrReplace);`
```
@DataClassName('SETTINGS_TABLE')
class SettingsDto  extends Table {
  Int64Column get id => int64().clientDefault(() => buildId())();
  TextColumn get key => text()();
  TextColumn get value => text()();
  @override
  Set<Column> get primaryKey => {id};
  @override
  List<Set<Column>> get uniqueKeys => [{key}];
}
```
buildId returns a BigInt

**Comment by mikemoore13** [comment]
@simolus3 any idea about this error ?

**Comment by simolus3** [comment]
That's a pretty weird structure it's trying to parse as `BigInt`, that looks like other columns may report invalid data as well. Is it possible for you to privately share a repository reproducing this behavior with me? I probably need to look at the communication between the worker and the tab to truly figure out what's going wrong here.

**Comment by mikemoore13** [comment]
I can create a minimal test case for you or we could have a call.
Weren't you able to reproduce with the struct SettingsDto   i provided ?

**Comment by simolus3** [comment]
Having a complete repro would be good, you can also reach out to me at oss@simonbinder.eu if you want to share something more privately or schedule a call. I have tried reproducing this with the `SettingsDto` table and

```dart
var dto = await into(settingsDto).insertReturning(
    SettingsDtoCompanion.insert(key: 'key', value: 'value'),
    mode: InsertMode.insertOrReplace);
print('inserted $dto');
```

But that works for me, both in Firefox and Chrome.

**Comment by mikemoore13** [comment]
Maybe to reproduce you could try to do not use this syntaxe :

`SettingsDtoCompanion.insert(key: 'key', value: 'value')`

but to proceed this way

```
var row = SettingsDtoCompanion(
      id: const Value.absent(),
      key: Value(setting.key),
      value: Value(setting.value)
    );
var table = db.settingsDto;//here db is my AppDatabase
var dto = await db.into(table).insertReturning(row, mode: InsertMode.insertOrReplace);
print('inserted $dto');
```

i am using those versions

```
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.20
```

**Comment by simolus3** [comment]
Isn't that exactly the same thing? Either way, which values have you used in `setting.key` and `setting.value`?

**Comment by mikemoore13** [comment]
Indeed the code should be equivalent, but I was wondering if a bug can hide in the conversion of the companion that I am using. 
In my test case the key is 'OnboardingDone' and the value is 'true'
Both are string

**Comment by mikemoore13** [comment]
@simolus3  for you a super nice test case :). you just have to click the plus button to reproduce the issue:
https://github.com/mikemoore13/test_case_drift

**Comment by simolus3** [comment]
Thanks a lot for that example! I can reproduce it and I've found the problem. I've fixed it in 7c0c52cdfebf56463ed34b16fbba57e0052a4e66, but regrettably it requires not only a drift version but also a new `drift_worker.js` update, as all existing workers send the value in a wrong format.

**Comment by mikemoore13** [comment]
Thanks Simon, 
Do you have an approximate date of release for both ?
I am looking forward to test both fixes

**Comment by simolus3** [comment]
If you want to test the fix, you can add this to your pubspec:

```yaml
dependency_overrides:
  drift:
    git:
      url: https://github.com/simolus3/drift.git
      ref: develop
      path: drift
```

You can grab an updated worker from https://storage.googleapis.com/simon-public-euw3/assets/drift_worker_fix.js

**Comment by mikemoore13** [comment]
it seems to work like a charm, i am looking forward the fix to be released
