### ISSUE TITLE
Method to Clear Database

### ISSUE THREAD

**Issue by codekeyz** [simolus3/moor#265]
I want to be able to clear the entire database record when user sign's out of my application.

**Comment by simolus3** [comment]
There are two options here: You could either close the database, delete the file from the device and then re-open it. Or you can delete everything from all tables, without closing the database:
```dart
Future<void> deleteEverything() {
  return transaction(() async {
    // you only need this if you've manually enabled foreign keys
    // await customStatement('PRAGMA foreign_keys = OFF');
    for (final table in allTables) {
      await delete(table).go();
    }
  });
}
```

**Comment by Holofox** [comment]
@simolus3, I encounter a problem when tables are not cleared when this method is called (most often this happens on real devices), maybe there is another way to clear all tables without closing the database? I use **moor_flutter 3.0.0**.

```dart
class Database extends _$Database {
  final LazyDatabase database;

  Database(this.database) : super(database);

  @override
  int get schemaVersion => 1;

  Future<void> deleteEverything() {
    return transaction(() async {
      for (final table in allTables) {
        await delete(table).go();
      }
    });
  }
}
```

I can’t understand the reason why this sometimes happens.

**Comment by simolus3** [comment]
Do you get an error when that happens? Or does it just not clear data?

**Comment by kuhnroyal** [comment]
Do FKs need to be disabled for this to work?

**Comment by Holofox** [comment]
> Do you get an error when that happens? Or does it just not clear data?

There are no errors. This happens only on specific real devices that I don’t have, by the way, on Android and iOS emulators there is no such problem.

**Comment by simolus3** [comment]
Are those devices known to ship with a buggy sqlite? I'd love to take a look at workarounds if there are some. But it's very weird that those statements don't do anything without causing an error. Even dropping the target table of a FK constraint seems to work.

To reduce device-specific behavior, you could try switching to [`moor_ffi`](https://moor.simonbinder.eu/docs/other-engines/vm/#migrating-from-moor-flutter-to-moor-ffi), which ships a precompiled sqlite3 library along with your app.

**Comment by Holofox** [comment]
@simolus3, in fact, the problem appears on most devices, but using the version with **moor_ffi**, it seems that users no longer have problems clearing tables.

**Comment by simolus3** [comment]
Do all records remain? Judging from the logs I would hope that only the ones inserted in the second transaction are kept, and all the deletes from the first transaction go through?

If that's the behavior, there's not much moor can do differently here (you request two transactions at roughly the same time, moor runs them sequentially as it should).

**Comment by Holofox** [comment]
@simolus3, no, not all. Previously, I had a problem with the fact that the database was not cleaned up at all, but now it’s just a similar problem, although the reason is clear.

**Comment by simolus3** [comment]
I see. I don't really have a clean solution to that problem, but you could introduce a boolean field in your database to indicate whether a close has been _requested_. You could then override `transaction` to check that field before running the transaction body, throwing an exception if it's set. But that's not really clean either since it would have to override `transaction` on each dao as well.

**Comment by tony123S** [comment]
The deleteEverything must put in database file? What if I would like to run the delete logic in repository?

**Comment by ycherniavskyi** [comment]
Do I understand it correct that in case of using the enforcement of foreign key constraints this faction must look this way (`foreign_keys` pragma must be not only `off` in the beginning but also `on` at the end):
```dart
Future<void> deleteEverything() {
  return transaction(() async {
    await customStatement('PRAGMA foreign_keys = OFF');
    for (final table in allTables) {
      await delete(table).go();
    }
    await customStatement('PRAGMA foreign_keys = ON');
  });
}
```

**Comment by joeljoy** [comment]
@simolus3 @ycherniavskyi 
```
Future<void> deleteEverything() {
  return transaction(() async {
    await customStatement('PRAGMA foreign_keys = OFF');
    for (final table in allTables) {
      await delete(table).go();
    }
  });
}
```
This did not work for me. I was getting:
```
SqliteException (SqliteException(787): FOREIGN KEY constraint failed
  Causing statement: DELETE FROM;)
```

**Comment by simolus3** [comment]
My suggestion was wrong, foreign keys can't be enabled or disabled in a transaction. Does this work for you?

```dart
Future<void> deleteEverything() async {
  await customStatement('PRAGMA foreign_keys = OFF');
  try {
    await transaction(() async {
      for (final table in allTables) {
        await delete(table).go();
      }
    });
  } finally {
    await customStatement('PRAGMA foreign_keys = ON');
  }
}
```

**Comment by joeljoy** [comment]
Yes, this works 👍

**Comment by ycherniavskyi** [comment]
Hmm, interesting. [Provided method](https://github.com/simolus3/drift/issues/265#issuecomment-1114319586) with pragma manipulation within transaction works for me. But it seems that I was just lucky with tables delete order in my case 😊. Because in description of [foreign_keys](https://www.sqlite.org/pragma.html#pragma_foreign_keys) pragma pointed - _This pragma is a no-op within a transaction_.

**Comment by NijatTagizada** [comment]
worked for me. thank you

**Comment by NijatTagizada** [comment]
> 

> My suggestion was wrong, foreign keys can't be enabled or disabled in a transaction. Does this work for you?
> 
> ```dart
> Future<void> deleteEverything() async {
>   await customStatement('PRAGMA foreign_keys = OFF');
>   try {
>     transaction(() async {
>       for (final table in allTables) {
>         await delete(table).go();
>       }
>     });
>   } finally {
>     await customStatement('PRAGMA foreign_keys = OFF');
>   }
> }
> ```

worked for me. thank you

**Comment by lifeapps-42** [comment]
> My suggestion was wrong, foreign keys can't be enabled or disabled in a transaction. Does this work for you?
> 
> ```dart
> Future<void> deleteEverything() async {
>   await customStatement('PRAGMA foreign_keys = OFF');
>   try {
>     transaction(() async {
>       for (final table in allTables) {
>         await delete(table).go();
>       }
>     });
>   } finally {
>     await customStatement('PRAGMA foreign_keys = OFF');
>   }
> }
> ```

Is there a mistake? Should we turn foreign_keys back ON after exucution instead of duplicating OFF?

**Comment by simolus3** [comment]
You're right, my bad :facepalm: I've edited the original comment to fix the typo.
