### ISSUE TITLE
Is there something like @JsonKey(ignore = true)

### ISSUE THREAD

**Issue by Varthu1337** [simolus3/moor#2650]
So i got a table which holds simple data like strings and some booleans, and all the data is provided in a Json. So i obviously wanted to use the method tableName.fromJson(response.data) which is generated from the table variables. Now the problem is the generated fromJson method wants to fill this field:  IntColumn get id => integer().autoIncrement()();  but the json cant deliver this information because it should be autoIncrement. Is there Something like @JsonKey(ignore = true) or some workarrounds for this problem ?

**Comment by simolus3** [comment]
No, this is not possible. The generated row classes are designed to always hold a full row as it appears in the database, which in this case includes the id.

The only workaround is to write your own class, use `json_serializable` to generate `fromJson` and manually convert that to the companion for inserts.
