### ISSUE TITLE
Web is described as Experimental on pub.dev

### ISSUE THREAD

**Issue by AdrasteonDev** [simolus3/moor#2651]
**Describe the bug**

I am a new user of this library. It seems that the web platform has been stable since version 2.9.0, but there is still this statement on [pub.dev](https://pub.dev/packages/drift): "Keep in mind that web support is still experimental".

Perhaps you should consider removing this statement?

**Comment by simolus3** [comment]
Good catch, thanks! I've removed the warning in 6c4654754b51fdb7444b39d4687c4dd5792f4b8d, so it will disappear in the next drift version.
