### ISSUE TITLE
How to implement the "Out of memory errors" patch ?

### ISSUE THREAD

**Issue by AdrasteonDev** [simolus3/moor#2652]
**Describe the bug**

Consulting [the documentation](https://drift.simonbinder.eu/docs/platforms/), I found this note concerning Android:

> Out of memory errors for very complex queries: Since the regular tmp directory isn't available on Android, you need to inform sqlite3 about the right directory to store temporary data. See [this comment](https://github.com/simolus3/drift/issues/876#issuecomment-710013503) for an example on how to do that.

Here is the proposed fix:

> bool _hasInitializedSqlite = false;
> 
> // Do this once, before opening a database
> // see https://github.com/simolus3/moor/issues/876
> Future<void> _ensureSqlite3Initialized() async {
>   if(_hasInitializedSqlite){
>     return;
>   }
>   //TODO prevent duplicate execution using synchronized?
>   if (Platform.isAndroid) {
>     final cachebase =  (await getTemporaryDirectory()).path;
>     sqliteLib.sqlite3.tempDirectory = cachebase;
>   }
>   _hasInitializedSqlite = true;
> }

The solution is to set the value of "sqlite3.tempDirectory", but sqlite3 is not exported by [package:drift/native.dart](https://raw.githubusercontent.com/simolus3/drift/fb2d8e8922741fdb2d26f0bbff521f9ab282b926/drift/lib/native.dart):
`export 'package:sqlite3/sqlite3.dart' show SqliteException;`

To be able to set this value, I assume that one of these fixes would have to be implemented:

- The fix can be added directly to the code of package:drift/native.dart (perhaps in the openDatabase function ?)
- sqlite3 can be exported by package:drift/native.dart (a block of code can then be added to an application to implement the correction)

But maybe I've missed something, and it is already possible to implement this fix?

**Comment by simolus3** [comment]
> The fix can be added directly to the code of package:drift/native.dart (perhaps in the openDatabase function ?)

It can't, because `drift` doesn't depend on Flutter and thus can't use `getTemporaryDirectory()`.

> sqlite3 can be exported by package:drift/native.dart (a block of code can then be added to an application to implement the correction)

You're using APIs by the `sqlite3` package here, so I think the safe way to handle this is to add `sqlite3` to your pubspec and to then import it.

**Comment by AdrasteonDev** [comment]
Thanks for the quick answer, I'll do it that way.
