### ISSUE TITLE
How to store List of Strings in moor?

### ISSUE THREAD

**Issue by sergiyvergun** [simolus3/moor#266]
I want to store list of strings in one column in table. How can it be implemented?

**Comment by simolus3** [comment]
You can use a [`TypeConverter`](https://moor.simonbinder.eu/docs/advanced-features/type_converters/) for this. In your case, you can write a `class ListInColumnConverter extends TypeConverter<List<String>, String>` that uses `json.encode` and `json.decode` to read and write lists.
