### ISSUE TITLE
Issue upgrade from moor to drift

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#2660]
After upgrade from moor to drift, my code have plenty of errors.

**First issue:**
```
ABC abc= ABC();
abc= abc.copyWith(id: id); // The argument type 'String' can't be assigned to the parameter type 'Value<String?>'
 
```
 **Second issue:**
```
 workOrder = workOrder.copyWith(asset: AssetModel()); //The argument type 'AssetModel' can't be assigned to the parameter type 
'Value<AssetModel?>
```

**Third issue:**

 ```
class UnitOwnerToSqlConverter
    extends NullAwareTypeConverter<UnitOwner?, String> {
  const UnitOwnerToSqlConverter();

  @override
  UnitOwner requireMapToDart(String fromDb) {
    return UnitOwner.fromJson(json.decode(fromDb));
  }

  @override
  String requireMapToSql(UnitOwner? unitOwner) =>
      json.encode(unitOwner!.toJson());
}


```
**Error**

```
The method doesn't override an inherited method.
Try updating this class to match the superclass, or removing the override annotation.d
```

**Comment by simolus3** [comment]
For the first and second issues, you can disable the `generate_values_in_copy_with` [builder option](https://drift.simonbinder.eu/docs/advanced-features/builder_options/) to revert to the old behavior. The reason for this change is that, by wrapping arguments in `Value`, you can reset them to `null`.

On the type converter, the methods are now named `toSql` and `fromSql` (or `requireToSql` and `requireFromSql` on `NullAwareTypeConverter`s). However, drift can automatically turn every type converter into a null-aware type converter now, so you can write the converter as:

```dart
class UnitOwnerToSqlConverter extends TypeConverter<UnitOwner, String> {
  const UnitOwnerToSqlConverter();

  @override
  UnitOwner fromSql(String fromDb) {
    return UnitOwner.fromJson(json.decode(fromDb));
  }

  @override
  String toSql(UnitOwner value) {
    return json.encode(value.toJson());
  }
}
``` 

And we also have builtin APIs to define JSON-based type converters in the latest drift version, so this works as well

```dart
final unitOwnerConverter =
    TypeConverter.json<UnitOwner>(fromJson: UnitOwner.fromJson);
```
