### ISSUE TITLE
Support more data types for postgres and mariadb

### ISSUE THREAD

**Issue by Leylan24** [simolus3/moor#2662]
Hi i am having an issue inserting a UUID string into a postgresql database.

This is the drift create statement:

```
CREATE TABLE [transaction_header] (
  trn_hdr_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  trn_hdr_guid uuid NOT NULL,
  till_no INTEGER NOT NULL
  )
```
when running the build_runner with this create Statement i cannot assign the UUID().v4() because the trn_hdr_guid is of type double.
![image](https://github.com/simolus3/drift/assets/25897680/e61d3bd5-8ef5-4190-8c64-aefca19d2f99)

if I change the column to a TEXT field I get the following error
```
CREATE TABLE [transaction_header] (
  trn_hdr_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  trn_hdr_guid TEXT NOT NULL,
  till_no INTEGER NOT NULL
  )

`PostgreSQLSeverity.error 42804: column "trn_hdr_guid" is of type uuid but expression is of type text Hint: You will need to rewrite or cast the expression. `

**Comment by simolus3** [comment]
We don't currently support "custom" SQL types, only the ones directly supported by sqlite3. It should work if you use a `TEXT` both in the drift file and in postgres, but then you'd loose the ability to properly describe the type of the database schema.

**Comment by Leylan24** [comment]
Do you know how I can work around the issue of Postgres saying i need to cast the uuid ? Im trying to implement a type converter?

**Comment by simolus3** [comment]
That wouldn't work either since the converter would convert the UUID to a `String`. You could use `TransactionHeaderCompanion.custom` and use a `CustomExpression()` to explicitly write the cast in SQL.

**Comment by simolus3** [comment]
In the next drift release, you'll be able to define your tables like this:

```sql
import 'package:drift_postgres/postgres.dart';

CREATE TABLE [transaction_header] (
  trn_hdr_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  trn_hdr_guid `PgTypes.uuid` NOT NULL,
  till_no INTEGER NOT NULL
  )
```

The syntax is a little weird since we need to embed the Dart code telling drift how the type actually works, but it will be generated as a `uuid` column and drift will then use the right types when talking to postgres.
