### ISSUE TITLE
Custom query as a subquery

### ISSUE THREAD

**Issue by 23doors** [simolus3/moor#2664]
**Describe the bug**

There doesn't seem to be a way to use custom query as a subquery (for inner join) nor as a part of isInSelect().
Custom query from .drift file is of type Selectable<result> and apparently isInSelect() and Subquery() expect BaseSelectStatement which are not compatible.

I cant define whole query in .drift file cause I got most of tables defined in dart. And seems that I cant reference dart tables in .drift file.

**Comment by simolus3** [comment]
True, at the moment drift queries are standalone methods that can't be embedded into the Dart query builder. I think this is a duplicate of #2606.

> I cant define whole query in .drift file cause I got most of tables defined in dart. And seems that I cant reference dart tables in .drift file.

You can add an `import 'tables.dart';` statement at the top of the drift file to import tables defined in Dart files. This should make the tables defined as Dart classes in `tables.dart` available to the drift file importing them.

**Comment by 23doors** [comment]
Thanks for the tip about `import 'tables.dart';`!
