### ISSUE TITLE
Xcode 15.0 & iOS 17;  Hard Crash (phone reboot) device only

### ISSUE THREAD

**Issue by ebonovic2** [simolus3/moor#2666]
_Edit by simolus3_: This appears to be a Flutter issue affecting all libraries using `dart:ffi` https://github.com/flutter/flutter/issues/136980.

-------

When running a    select(...).getSingleOrNull(), on DEVICE ONLY, it is causing a hard crash, and instant phone reboot. 
On a simulator this is working fine.

It is crashing instantly and not giving me any warnings, errors.  And a try/catch block, is not capturing anything either.
Nothing is appearing in the console that gives any indication of what happened

If we run on a legacy branch, using version 2.8.1 of drift, the same command works fine, via XCode15->iOS17
We then had an upgrade to 2.11.1, saw the error, tried to go to the latest 2.12.1, same thing. 

I have narrowed the crash to when the inner function runs the get()

This exact same code base works on: 

Xcode 14.3 -> iOS15 device 
Xcode 14.3 -> iOS16 device 
Xcode 15.0 -> iOS16 device 
It is only failing on when we are trying to run, on a build compiled with XCode15, on an iOS17 device. 

And as noted above, it does NOT fail on iOS17 simulator.

**Comment by simolus3** [comment]
That is really weird. Dart code shouldn't crash the Dart VM, and even a misbehaving Dart VM shouldn't bring down the whole phone.

Can you reproduce this with the [example app on this branch](https://github.com/simolus3/drift/tree/example-app/use-getSingleOrNull-somewhere/examples/app) as well? Are you sure that `drift` is the only dependency that has changed (and, in particular, the `sqlite3` and `sqlite3_flutter_libs` versions are on the same versions)? Does this happen on debug and release mode builds?

Unfortunately I don't have a physical iPhone to reproduce this myself, but I assume there is a combination of things that are triggering this since so far I've only gotten your report about this.

**Comment by ebonovic2** [comment]
Good News, and Bad News..  

The Good News, is that example branch that you linked to (running the "app" variation), did produce the identical instant panic/crash/reboot of the phone.    (which was updated to 17.0.3 yesterday). 

For reference the physical phone being used is an iPhone 14 Pro
That is also the Bad News. 

The weirdness continues, trying to run it on my iPad Pro, which is on iPadOS 17.0.3; and it works. 

I don't have another physical phone at the moment to test against.

**Comment by ebonovic2** [comment]
Now more fun weirdness: 

debug configuration:   panic/crash 
release configuration: works

**Comment by ebonovic2** [comment]
I wanted to check in to see if there was any insight, work arounds, or updates on this one? 
I have been able to re-create the issue on a second iOS17 phone device.

**Comment by simolus3** [comment]
No, unfortunately I don't have any updates on this - I couldn't get an iPhone to reproduce this. I'm also not sure I'd know where to look.

Maybe it's best to file a Flutter issue on this so that someone more knowledgeable about the internals is able to take a look. Are the following steps enough to reproduce this from a clean state?

```
git clone https://github.com/simolus3/drift.git -b example-app/use-getSingleOrNull-somewhere --depth 1
cd drift
dart pub global run melos bootstrap --scope app
cd examples/app/
flutter run -d ios
```

If so, I can file a Flutter issue, but since you'll probably be able to provide more details on how to reproduce this, you could do it as well. Sorry I'm of so little help here, I really don't understand how this can happen and how to diagnose it further.

**Comment by ebonovic2** [comment]
Hi there, so I was able to get back to this... and yah, those exact steps (sans me adjusting the bundle identifier and team), reproduced the failure.. :(

**Comment by simolus3** [comment]
Odd. https://github.com/flutter/flutter/issues/136197 is the only issue that looks similar - I can file a Flutter issue for you if you give me the output of `flutter doctor -v`

**Comment by ebonovic2** [comment]
[✓] Flutter (Channel stable, 3.13.7, on macOS 13.6 22G120 darwin-arm64, locale
    en-US)
    • Flutter version 3.13.7 on channel stable at
      /Users/********/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2f708eb839 (11 days ago), 2023-10-09 09:58:08 -0500
    • Engine revision a794cf2681
    • Dart version 3.1.3
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/*******/Library/Android/sdk
    • Platform android-33, build-tools 33.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode15.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.83.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.74.0

[✓] Connected device (3 available)
    • EJ-iPhone14p (mobile) • 00008120-001478803CDB401E • ios            • iOS 17.0.3 21A360
    • macOS (desktop)       • macos                     • darwin-arm64   • macOS 13.6 22G120 darwin-arm64
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 118.0.5993.88

[✓] Network resources
    • All expected network resources are available.

• No issues found!

**Comment by joergbirkhold** [comment]
I can confirm that, on Xcode 15.01 / iOS 17.0.3 I am getting a hard crash when debugging. Not in relaease

**Comment by simolus3** [comment]
Could you try this again with the latest Flutter beta released today (`3.16.0-0.4-pre`)?

**Comment by hajajmaor** [comment]
Waiting for an update on this issue.

**Comment by simolus3** [comment]
This was caused by https://github.com/flutter/flutter/issues/136980, a Flutter bug which has since been fixed.
