### ISSUE TITLE
SQL Parser doesn't accept Dart components from custom queries in dao

### ISSUE THREAD

**Issue by knyghtryda** [simolus3/moor#267]
I have this query 
```
'allContacts': 'SELECT * FROM contacts '
      'WHERE pending = :pending AND first_name LIKE :like '
      'ORDER BY :orderBy '
```

which parses out to
```
Selectable<Contact> allContactsQuery(
      bool pending, String like, String orderBy) {
    return customSelectQuery(
        'SELECT * FROM contacts WHERE pending = :pending AND first_name LIKE :like ORDER BY :orderBy',
        variables: [
          Variable.withBool(pending),
          Variable.withString(like),
          Variable.withString(orderBy)
        ],
        readsFrom: {
          contacts
        }).map(_rowToContact);
  }

  Future<List<Contact>> allContacts(bool pending, String like, String orderBy) {
    return allContactsQuery(pending, like, orderBy).get();
  }

  Stream<List<Contact>> watchAllContacts(
      bool pending, String like, String orderBy) {
    return allContactsQuery(pending, like, orderBy).watch();
  }
```

However when this query is run the results are returned in index order, not the order declared in the order by.  Here is the debug output from moor
`flutter: Moor: Sent SELECT * FROM contacts WHERE pending = :pending AND first_name LIKE :like ORDER BY :orderBy with args [1, %, first_name]`

If I hard code that `first_name` value in the query then it of course runs fine.  What's going on?

**Comment by simolus3** [comment]
This looks like the same problem as https://github.com/simolus3/moor/issues/236#issuecomment-552807981 - the `:orderBy` gets interpreted as a string, which won't work for columns. I saw your comment that using a `$orderBy` component didn't work with the parser - that's sounds like a bug.

**Comment by simolus3** [comment]
This will be fixed in the next release. If you need a workaround, you can move that query into a moor file:
```dart
// database.dart
@UseMoor(
  tables: [...],
  queries: { /* shouldn't include the allContacts query */ },
  include: {'queries.moor'},
)
```
```sql
-- queries.moor, in the same folder
import 'database.dart'; -- your database file that declares the tables

allContacts: SELECT * FROM contacts
  WHERE pending = :pending AND first_name LIKE :like
  ORDER BY :orderBy;

```
