### ISSUE TITLE
Add Date Type to PostgresSql

### ISSUE THREAD

**Issue by Leylan24** [simolus3/moor#2677]
Would it be possible to add Date Column types  from postgressql to custom sql types? Currently I write a customStatement and map the values for the date manually.

**Comment by simolus3** [comment]
Which of the date time types do you need? We'd likely have to put them in wrapper classes (`PgDateTime` wrapping a `DateTime`) since drift already expects `DateTime` values to be interpreted a certain way.

**Comment by Leylan24** [comment]
we currently have columns using the following types `date` and `timestamp` and example of the timestamp would be 2023-10-10 19:24:52.872 and the date column 2023-10-10. 

Not sure if this answers your question.

**Comment by simolus3** [comment]
I've implemented the two types using custom types in 6aa1a5d7345bc584096f5ba4f1e8de523140ad49.
