### ISSUE TITLE
Support Emscripten built sqlite3.wasm with Drift lib

### ISSUE THREAD

**Issue by peixinli** [simolus3/moor#2678]
Would it be possible to support drift library to use sqlite3.wasm built with emscripten?

**Comment by simolus3** [comment]
Emscripten emits additional JavaScript glue code, which complicates the setup. We support the [sql.js](https://github.com/sql-js/sql.js) library and use it in `package:drift/web.dart` - that library has been compiled with Emscripten. You can of course compile your own library with emscripten and write Dart bindings to the glue code, that can then be used with drift.

Is there a particular feature you need from Emscripten which is not currently possible?

Given that we support two approaches on the web (one based on Emscripten an an external JS wrapper library, and one that can use Dart directly), I don't see a reason to support a third one officially. But you can always write your own drift backend for your own custom solution, it's not that much work. If you need help with that, let me know!

**Comment by peixinli** [comment]
> Is there a particular feature you need from Emscripten which is not currently possible?

 Not really. We(the Flutter team) prefer to use the sqlite wasm file compiled by ourselves rather than downloaded precompiled binrary.

> But you can always write your own drift backend for your own custom solution, it's not that much work. If you need help with that, let me know!

That'll be great. Would you like to provide some guidance on how to build our own drift backend?

**Comment by simolus3** [comment]
> We(the Flutter team) prefer to use the sqlite wasm file compiled by ourselves rather than downloaded precompiled binrary.

Right, that's very reasonable! You can actually compile the sqlite3.wasm binary yourself though. The build scripts are in my [sqlite3.dart](https://github.com/simolus3/sqlite3.dart/) repository. It requires clang with builtins from the wasi sdk (which you can also compile yourself), the setup [is described in the readme](https://github.com/simolus3/sqlite3.dart/tree/main/sqlite3#compiling). Hopefully, setting up that build is much easier than starting from scratch :) If you need to use Emscripten directly, I can take a look at supporting that toolchain as well - recent versions support compiling to wasm modules without glue code, so the output is likely similar to what we already expect and thus straightforward for `drift` and `package:sqlite3` to use.

> Would you like to provide some guidance on how to build our own drift backend?

Sure. To write a backend from scratch, you'd implement the `DatabaseDelegate` class from the `package:drift/backends.dart`. That interface defines methods for opening the database (`open`), running statements (`runSelect`, `runUpdate`, `runInsert` and `runCustom`) and closing it. You could take a look at the shared [delegate for ffi and wasm sqlite3](https://github.com/simolus3/drift/blob/develop/drift/lib/src/sqlite3/database.dart) or the one for the [sql.js interface](https://github.com/simolus3/drift/blob/6aa1a5d7345bc584096f5ba4f1e8de523140ad49/drift/lib/src/web/web_db.dart#L76) as examples. Once you have implemented a `DatabaseDelegate`, you can pass it to `DelegatedDatabase` which implements the `QueryExecutor` interface used by all drift databases. This is what `NativeDatabase`s are doing as well ([source](https://github.com/simolus3/drift/blob/6aa1a5d7345bc584096f5ba4f1e8de523140ad49/drift/lib/native.dart#L47-L52)).
