### ISSUE TITLE
beforeOpen is not called in tests

### ISSUE THREAD

**Issue by iamstiil** [simolus3/moor#2680]
Hey,

thanks for the awesome library.
Right now I'm having the issue that my data, which I pre-populate in `beforeOpen`, don't seem to be applied to the test database.
Is that the expected the behavior?

✌🏽

**Comment by simolus3** [comment]
How are you creating a test database - with `NativeDatabase.memory()`? The `beforeOpen` callback should be called in tests as well (and I'm relying on this in drift tests too). If you're re-using a drift database across multiple tests, `beforeOpen` would not be called in every tests (just once when the database is opened). Could that be the problem?

**Comment by iamstiil** [comment]
I'll show you a few snippets from my code:

database.dart:
```dart
class AppDatabase extends _$AppDatabase {
  ...

  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) async {
          await m.createAll();
        },
        onUpgrade: stepByStep(
          from1To2: _from1To2,
          from2To3: _from2To3,
        ),
        beforeOpen: (details) async {
          _populate(details);
          await customStatement('PRAGMA foreign_keys = ON');
        },
      );

  ...

  Future<void> _populate(OpeningDetails details) async {
    if (details.wasCreated ||
        (details.hadUpgrade &&
            (details.versionBefore != null && details.versionBefore! < 2) &&
            (details.versionNow >= 2))) {
      ... // run when migration for v2 is done
    }
  }
}
```


database_test.dart:
```dart
void main() {
  ...

  test('upgrade from v2 to v3', () async {
    final schema = await verifier.schemaAt(2);
    final oldDb = v2.DatabaseAtV2(schema.newConnection());
    await verifier.migrateAndValidate(oldDb, 2);

    var model = await oldDb.select(oldDb.models).get();

    expect(exercises.isNotEmpty, true); // This is failing

    ...
  }

  ...
}
```

**Comment by simolus3** [comment]
Thanks for posting the snippets. I see three potential issues with them:

1. You're not awaiting `_populate` in `beforeOpen` (ok, this is technically not a problem since drift will run queries in the right order with `NativeDatabase`s. still, await your queries!).
2. You're calling `schemaAt(2)` followed by `migrateAndValidate(...,2)`. There is no migration if the two versions are the same - the database will think it's up-to-date and just open.
3. You're passing `DatabaseAtV2` to `migrateAndValidate`. These databases aren't capable of running a migration, they just create an older schema version. You should always pass your `AppDatabase` to `migrateAndValidate`.

Since your `if` statement matches upgrades from v1 to later versions, I guess you meant to test this in a test from v1 to v2?

```dart
void main() {
  ...

  test('upgrade from v1 to v2', () async {
    final schema = await verifier.schemaAt(1);

    final db = AppDatabase(schema.newConnection());
    // this runs the migration and should call beforeOpen
    await verifier.migrateAndValidate(db, 2);

    // 
    final oldDb = v2.DatabaseAtV2(schema.newConnection());

    var model = await oldDb.select(oldDb.models).get();

    expect(exercises.isNotEmpty, true);

    ...
  }

  ...
}
```

**Comment by iamstiil** [comment]
Hey, sorry for the late reply.

Thanks for the info on the `await` - missed that 😅

I added the `migrateAndValidate(...,2)` to force the populate to run since without it it was failing aswell.
So what I actually did was:
```dart
test('upgrade from v2 to v3', () async
  final schema = await verifier.schemaAt(2);
  final oldDb = v2.DatabaseAtV2(schema.newConnection());

  var model = await oldDb.select(oldDb.models).get();
  expect(models.isNotEmpty, true); // it fails here with Expected: <true> Actual: <false>

  ...
}
```
I expect this to actually contain data if the `_populate` function ran, since the test for upgrading from `v1` to `v2` succeeds and the table is not empty. It should be populated by running the `beforeOpen` function of `MigrationStrategy` defined in the `database.dart` with the `details.wasCreated` being `true`.

I think I can't use `AppDatabase` since it is the latest version, which would be `v3` in my case. I want to check if the changes to the table in `v3` are also applied. There is a table that has a foreign key reference to an element, which is pre-populated. And the migration to v3 changes that table.

Hope this narrows it down 😄

**Comment by simolus3** [comment]
> I expect this to actually contain data if the `_populate` function ran, since the test for upgrading from `v1` to `v2` succeeds and the table is not empty

Every time you call `schemaAt(x)`, a new temporary database is created to test schema migrations in isolation. The `upgrade from v2 to v3` test you've posted does not use `AppDatabase` at all, so `_populate` cannot be called.

> I think I can't use `AppDatabase` since it is the latest version, which would be `v3` in my case. I want to check if the changes to the table in `v3` are also applied

The way to ensure migrations don't loose data is to just create an old schema, insert values into the old database, run the migration and check the data is still there, like this:

https://github.com/simolus3/drift/blob/258210961433b7dc1339f74bd5bbca7896db17f6/examples/migrations_example/test/migration_test.dart#L46-L65
