### ISSUE TITLE
Dart components are not aware of tables for their expressions

### ISSUE THREAD

**Issue by knyghtryda** [simolus3/moor#269]
I have a query 
```
SELECT contacts.* FROM contacts 
INNER JOIN contacts_tags_map ON contacts.id = contacts_tags_map.contact_id
LEFT JOIN tags ON tags.id = contacts_tags_map.tag_id
WHERE $filter
```
and filter is `isIn(tags.id, filters)`
However when this run I get an error
```
Unhandled Exception: DatabaseException(Error Domain=FMDatabase Code=1 "ambiguous column name: id" UserInfo={NSLocalizedDescription=ambiguous column name: id}) sql 'SELECT contacts.* FROM contacts
[        ]       INNER JOIN contacts_tags_map ON contacts.id = contacts_tags_map.contact_id
[        ]       LEFT JOIN tags ON tags.id = contacts_tags_map.tag_id
[        ]       WHERE id IN (?) 
```
This is all to still try and get around that WHERE IN parsing problem from #236.  I have also tried to just build a long 'or' expression but I'm not sure how exactly to do that so that I end up with an expression.  The closest I got was mapping over the filters and then trying to fold them with a `or(...)` but fold requires an initial value and I'm not sure what to provide as it expects an expression as well.
`filters.map((filter) => tags.id.equals(filter)).fold(<what goes here?>,(prev, element) => or(prev, element))`

Thank you for all your prompt replies!

**Comment by simolus3** [comment]
Thanks for the report, and sorry that you're running into such a long series of blockers for that query. 
As a first step, I think we should make column references from a Dart component always use the table name (e.g. `WHERE tags.id IN (?)`). This could still break for table aliases (e.g. it might not work for `LEFT JOIN tags t ON ...`), but it will be useful for most queries.

As another temporary workaround, maybe a `isIn(CustomExpression('tags.id'), filters)` could help. But with `moor_flutter`, the underlying sqflite issue on Android could still mess up that query :(

>  I have also tried to just build a long 'or' expression

Good idea, but since the root cause is the `id` column not being recognized, I'm not sure it would fix the problem. Maybe a combination of an or-chain and the custom expression instead of `tags.id` could help, but I'm not sure about that.
If you're going for the `fold` approach, you could use `Constant<bool, BoolType>(false)` as an initial value, since it doesn't have any impact in an or. Or you could skip one element and use the rest:
```dart
Expression<bool, BoolType> disjunctionOf(Iterable<Expression<bool, BoolType>> terms) {
  if (terms.isEmpty) {
    // you probably don't need this case
    return const Constant<bool, BoolType>(false);
  }
  final first = terms.first;
  return terms.skip(1).fold<Expression<bool, BoolType>>(first, (prev, element) => prev | element);
}
```

**Comment by knyghtryda** [comment]
Tried fold, but without the table in the column reference that fails as well...  As for using CustomExpression(...), I get this error when trying to apply that to isIn:
```
The following StateError was thrown building ContactList(dirty, dependencies: [InheritedProvider<AppState>, InheritedProvider<SharedPreferencesProvider>], state: _ContactListState#9c442):
Bad state: Too many elements

User-created ancestor of the error-causing widget was: 
  SafeArea file:///C:/Users/yanco/Documents/Github/contax/lib/widgets/tabs/contacts_list.dart:171:13
When the exception was thrown, this was the stack: 
#0      ListMixin.singleWhere (dart:collection/list.dart:168:11)
#1      SqlTypeSystem.forDartType (package:moor/src/types/type_system.dart:32:18)
#2      Variable.mapToSimpleValue (package:moor/src/runtime/expressions/variables.dart:50:37)
#3      Variable.writeInto (package:moor/src/runtime/expressions/variables.dart:58:39)
#4      _InExpression.writeInto (package:moor/src/runtime/expressions/in.dart:49:16)
...
```
This happens as well if I try to use CustomExpression in the fold.
The Saga Continues...

**Comment by simolus3** [comment]
The "too many elements" error occurs when a `Variable` without proper type arguments exists. In that case, moor can't know how to convert the Dart value into something the backend understands. 

In this case, it seems like the `CustomExpression('tags.id')` I suggested is to blame here - sorry.  If you're using `isIn`, an explicit type argument (`isIn<IntType, int>(CustomExpression('tags.id'), [1, 2, 3])`) will fix the "too many elements" error. 
I assume you're using `Expression.equals` somewhere in your `fold` construction? In that case, you probably need to add proper type arguments to the `CustomExpression` itself. Something like `CustomExpression<int, IntType>('tags.id')` should do the trick.

All of this will hopefully get better soon, all of those workarounds aren't necessary with the next moor version and `moor_ffi`.

**Comment by simolus3** [comment]
You should be able to remove the `CustomExpression` workaround when using moor and moor_generator 2.2 or later. You can also use the `$placeholder` syntax in `@UseMoor` annotations now, a moor file is no longer required for that.
