### ISSUE TITLE
(Web): Cannot migrate data (create new table) with wasm on web

### ISSUE THREAD

**Issue by magacao** [simolus3/moor#2690]
## Description

In my project we changed the `WebDatabase` to `WasmDatabase` following the recommendation in this thread: https://github.com/simolus3/drift/discussions/2579

Since then it seems that the migration from a previous version to +1 version doesn't work. We have the following stacktrace: 

```
[NativeDatabaseProvider] INFO 2023-10-19 11:46:43.811: Using WasmStorageImplementation.sharedIndexedDb due to missing browser features: {MissingBrowserFeature.dedicatedWorkersInSharedWorkers, MissingBrowserFeature.sharedArrayBuffers}
[repository.auth] SqliteException(11): while selecting from statement, database disk image is malformed, database disk image is malformed (code 11)
  Causing statement: SELECT * FROM "active_sessions" ORDER BY "last_seen_date" DESC;
[repository.auth] dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 941:28
```

I tried reverting to the `WebDatabase` and the migration worked as expected...
So I wonder if there is something else we should call to be able to use the migration tool with Wasm.

Here's the migration
```
   int currentVersion = 3;
  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (Migrator m) async {
          await m.createAll();
        },
        onUpgrade: (Migrator m, int from, int to) async {
          if (from <= 1) {
            await m.createTable(userPhoneNumbers);
          }
          if (from <= 2) {
            await m.createTable(sessionInfoIdentifiers);
          }
        },
        beforeOpen: (details) async {
        },
      );
```

**Comment by simolus3** [comment]
Nothing should have to be changed in the migrations to work with `WasmDatabase`, this looks like a bug in drift or the `sqlite3` package. Does this happen every time after running (any? or just some?) migrations?

**Comment by magacao** [comment]
yes everytime I run this migration. We haven't had to move other kind of attributes but this new table. I can reproduce 100%

**Comment by simolus3** [comment]
I couldn't reproduce this by running a migration alone with the wasm database. How did you migrate from the old `WebDatabase` to `WasmDatabase`?

**Comment by magacao** [comment]
We used the code here:  https://github.com/simolus3/drift/discussions/2579

But I tried all the drift version and on drift 2.11.0 I don't have the problem migrating. So like you said it might be a bug introduced in 2.11.1?

**Comment by simolus3** [comment]
The snippet I've posted there doesn't implement a migration from `DriftWebStorage` to the format understood by `WasmDatabase` - that would look something like [this](https://drift.simonbinder.eu/web/#migrating-from-packagedriftwebdart). Does the switch from `WebDatabase` to `WasmDatabase` keep data in your app?

I'll check the diff from 2.11.0 to 2.11.1 though, maybe something stands out.

**Comment by magacao** [comment]
No I think when we migrate from `WebDatabase` to `WasmDatabase` we wipe the data and start from scratch. The migration was failing between two `WasmDatabase` so I think it's okay to rule that change out from what causes this bug 🤔 

Thank you for the quick responses! It really helps!

Edit: 
I tried doing the migration from 2.13.0 to 2.13.0 and it worked. So we'll force the users to use latest version. I guess it's good to know the bug seems to be fixed.

**Comment by simolus3** [comment]
I don't think there's anything in 2.13 that's different from the previous versions in this regard. So maybe this has just been a weird one-time issue, but I'm not convinced this has really been fixed. So let me know if this happens again with 2.13 (or future versions for that matter).
