### ISSUE TITLE
Please solve my problem

### ISSUE THREAD

**Issue by mahdi3800** [simolus3/moor#2693]
Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The method 'image' was called on null.
Receiver: null
Tried calling: image())

**Comment by simolus3** [comment]
I'm going to need a lot more information to act on this, with the information you've posted it's not even clear whether this is a drift issue. What query are you running and why are you expecting `image` to be non-null? Is there a stack trace pointing towards drift?

**Comment by mahdi3800** [comment]
Exception has occurred.
DioException (DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.
)
