### ISSUE TITLE
remove local database when uninstalling desctop app

### ISSUE THREAD

**Issue by jafar260698** [simolus3/moor#2694]
I want to delete the database file, when uninstalling the windows application, which is saved in local machine (Windows) as db.sqlite. How can I achieve this? 
Because after reinstalling app, local database still exist there.

**Comment by simolus3** [comment]
If you have a custom uninstaller, you could of course delete the database file there.

I'm not too experienced with Windows, so I don't know if there is a directory to put the database that would get deleted automatically when it's uninstalled. Wouldn't you have the problem with other packages like shared preferences as well?
