### ISSUE TITLE
SqliteException(6410): while selecting from statement, disk I/O error, disk I/O error (code 6410)

### ISSUE THREAD

**Issue by froccawork** [simolus3/moor#2695]
When I access a StatefulWidget, in the initState I execute the following code:

`@override
  void initState() {
   
    super.initState();

    WidgetsBinding.instance.addPostFrameCallback((_) async {

      final queryExpense = database.expenseReportTypeModel.select()
        ..orderBy([
              (t) => drift.OrderingTerm(expression: t.expenseReportTypeDescription)
        ]);
      expenseReportTypeList = await queryExpense.get();
      final queryCustomer = database.customerModel.select()
        ..orderBy(
            [(t) => drift.OrderingTerm(expression: t.customerDescription)]);
      customerList = await queryCustomer.get();
      setState(() {});
    });
  }`

Executing the second get() generates the following error: 
SqliteException(6410): while selecting from statement, disk I/O error, disk I/O error (code 6410) Causing statement: SELECT * FROM "customer_model" ORDER BY "customer_description" ASC;

if I delete the first get() the second one executes correctly

The same problem happens if I insert the code into a transaction. What do I need to do to execute two get()s one after the other?

**Comment by simolus3** [comment]
This is due to https://github.com/simolus3/drift/issues/876 and can be fixed by setting a custom temporary directory when opening the database, like this:

https://github.com/simolus3/drift/blob/8077c564d76cd4861c54915138e1fd5c6d25b8c1/examples/app/lib/database/connection/native.dart#L20-L36

I will also add this to the setup page in the documentation to make this easier to avoid.

**Comment by froccawork** [comment]
I'm having the problem on iOS, not Android

**Comment by simolus3** [comment]
Interesting, I've not seen this happen on iOS before. Does applying the `sqlite3.tempDirectory` workaround work if you also apply it on iOS?

**Comment by froccawork** [comment]
sorry for my ignorance but I didn't understand where to put that part of code. My code that initializes the database is:

`@DriftDatabase(tables: [
  CustomerModel,
  DeliveryModel,
  ExpenseReportTypeModel,
  ExpenseReportModel,
  ExpenseReportRowsModel
])
class DatabaseDrift extends _$DatabaseDrift {
  DatabaseDrift() : super(_openConnection());

  @override
  int get schemaVersion => 1;
}

LazyDatabase _openConnection() {
  // the LazyDatabase util lets us find the right location for the file async.
  return LazyDatabase(() async {
    // put the database file, called db.sqlite here, into the documents folder
    // for your app.
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    return NativeDatabase.createInBackground(file);
  });
}`

**Comment by froccawork** [comment]
I figured out where to add the piece of code. Thank you.
This workaround work also for iOS

**Comment by simolus3** [comment]
That's good to know, I'll update the documentation.
