### ISSUE TITLE
Non-nullable table field generates syntax error in view

### ISSUE THREAD

**Issue by Adam-Langley** [simolus3/moor#2696]
I have a table field which uses a converter, and is non-nullable:

`Int64Column get creationTime => int64().map(NanoDateTimeBigIntConverter())();`

This is fine, and generates correct dart for the table itself.

However, I also have a view (defined in a .drift) which sources data from this same table.
It causes the generated dart to reference an 'n-suffixed' (nullable) converter for that field - which doesnt exist...

<img width="583" alt="image" src="https://github.com/simolus3/drift/assets/16373742/d006ca66-635e-45d4-9d0a-189fa734e5c7">

It appears the convention in drift, is for all fields of views to be nullable, which is leading to this "conundrum". It feels like there is probably a compensating convention I just need to follow - maybe I just need a pointer?

My workaround for now, is a patch to drift_dev, table_writer.dart, which will ensure nullable wrapper converters are available for all fields, irrespective of the underlying field nullability, for the sake of possibly being depended on by latter views

```
 void writeConvertersAsStaticFields() {
    for (final converter in tableOrView.appliedConverters) {
      if (converter.owningColumn?.owner != tableOrView) continue;

      final typeName =
          emitter.dartCode(emitter.writer.converterType(converter));
      final code = emitter.dartCode(converter.expression);

      buffer.write('static $typeName ${converter.fieldName} = $code;');

      // Generate wrappers for non-nullable type converters that are applied to
      // nullable converters.
      final column = converter.owningColumn!;
      // if (converter.canBeSkippedForNulls && column.nullable) // disable this condition to ensure all converters have nullable versions
      {
        final nullableTypeName = emitter.dartCode(
            emitter.writer.converterType(converter, makeNullable: true));

        final wrap = converter.alsoAppliesToJsonConversion
            ? emitter.drift('JsonTypeConverter2.asNullable')
            : emitter.drift('NullAwareTypeConverter.wrap');

        final code = '$wrap(${converter.fieldName})';

        buffer
            .write('static $nullableTypeName ${converter.nullableFieldName} = '
                '$code;');
      }
    }
  }
```

Thanks,

**Comment by simolus3** [comment]
Thanks for the report! Your workaround works, but I've opted to just inline the nullable definition in 0973aa982cc0c8f7549377f1e761bad2ce103351 if the column is non nullable to avoid unnecessary fields.

**Comment by Adam-Langley** [comment]
Thanks @simolus3 - confirmed resolves issue
