### ISSUE TITLE
Errors in documentation

### ISSUE THREAD

**Issue by ouattararomuald** [simolus3/moor#2698]
**Describe the bug**

On [this](https://drift.simonbinder.eu/docs/sql-api/custom_queries/) page in the documentation, I found this example:

```dart
Stream<int> amountOfTodosInCategory(int id) {
  return customSelect(
    'SELECT COUNT(*) AS c FROM todos WHERE category = ?',
    variables: [Variable.withInt(id)],
    readsFrom: {todos},
  ).map((row) => row.read<int>('c')).watch();
}
```

- [custom queries](https://drift.simonbinder.eu/docs/sql-api/custom_queries/)

The error is that `watch` returns `Stream<List<int>>`. We should replace `watch` by `watchSingle`.

**Comment by simolus3** [comment]
Thanks for the report, I'll update the snippet.
