### ISSUE TITLE
Expression.and static method is throwing compilation error

### ISSUE THREAD

**Issue by becjit** [simolus3/moor#2705]
Hi, 
I am not able to find Expression.and static method. It is showing compile time error. Drift version ^2.11.1.

Basically what I want is to create an "and" expression if a particular field is not null (conditional). For example, let's say we have an object with two nullable fields: fieldA and fieldB. I want to create a where clause with "And" expression if only both of them are not null.

Thanks,
Abhijit

**Comment by simolus3** [comment]
`Expression.and` has been added in drift 2.13.0, you might have to update.

> Basically what I want is to create an "and" expression if a particular field is not null (conditional). For example, let's say we have an object with two nullable fields: fieldA and fieldB. I want to create a where clause with "And" expression if only both of them are not null.

You can back-port `Expression.and` if you can't use newer drift versions:

```dart
Expression<bool> whereAllNullableColumnsAreNonNull(TableInfo table) {
  final nullables = table.$columns.where((c) => c.$nullable);

  if (nullables.isEmpty) {
    return const Constant(true);
  } else {
    return nullables
        .map((c) => c.isNotNull())
        .reduce((combined, col) => combined & col);
  }
}
```

If you only have a fixed amount of columns to check, doing `a.isNotNull() & b.isNotNull()` will likely be easier.
