### ISSUE TITLE
Usage with dart-docker

### ISSUE THREAD

**Issue by wolframm** [simolus3/moor#2708]
What would be the best way to modify the Dockerfile created by `dart create -t shelf-server test_server` to include Sqlite3?

**Comment by simolus3** [comment]
If you're fine with the (somewhat outdated) sqlite3 library shipped with Debian, you can do

```Dockerfile
# Use latest stable channel SDK.
FROM dart:stable AS build

RUN apt update && apt install libsqlite3-0

# Resolve app dependencies.
WORKDIR /app
COPY pubspec.* ./
RUN dart pub get

# Copy app source code (except anything in .dockerignore) and AOT compile app.
COPY . .
RUN dart compile exe bin/server.dart -o bin/server

# Build minimal serving image from AOT-compiled `/server`
# and the pre-built AOT-runtime in the `/runtime/` directory of the base image.
FROM scratch
COPY --from=build /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 /usr/lib/x86_64-linux-gnu/libsqlite3.so
COPY --from=build /runtime/ /
COPY --from=build /app/bin/server /app/bin/

# Start server.
EXPOSE 8080
CMD ["/app/bin/server"]
```

An alternative would be to install C compiler before `FROM scratch` and download the desired sqlite3 version to compile it yourself - you'd still have to copy it. You can take a look at [this tool](https://github.com/simolus3/drift/blob/develop/drift/tool/download_sqlite3.dart) for inspiration on the commands to run.
