### ISSUE TITLE
Add support for logging SQL execution time

### ISSUE THREAD

**Issue by glanium** [simolus3/moor#2717]
**Is your feature request related to a problem? Please describe.**
I  need to get SQL execute time.
However, problem is my app uses heavily watchXXXX methods for observing, so it is hard to get SQL execution time by myself?

**Describe the solution you'd like**
Add support for logging SQL execution time.
NativeDatabase class's constructor has bool logStatements parameter.
Then add more parameter like bool logStatementsWithExecTime??

thx.

**Comment by simolus3** [comment]
> Then add more parameter like bool logStatementsWithExecTime??

We won't be able to match every possible requirement with those parameters, so I think a better approach would be something generic that can be used to log statements with more details.

This can be done with the [QueryInterceptor](https://654abec513b45231d6041540--moor.netlify.app/docs/examples/tracing/) API which will be added to the next drift version.
