### ISSUE TITLE
How to do relation classes probably structured 

### ISSUE THREAD

**Issue by heshaShawky** [simolus3/moor#2718]
I am doing a new project, and still in the structure phase doing models ...etc, I am using Drift as the main database ( Local First )

Now I created tables like this 

```dart
// @UseRowClass(SettingsRaw)
class SettingsTable extends Table {
  IntColumn get id => integer().nullable().autoIncrement()();
  IntColumn get account => integer().nullable()();
  // nullable fields
  TextColumn get token => text().nullable()();
  TextColumn get pincode => text().nullable()();
  DateTimeColumn get createdAt =>
      dateTime().nullable().withDefault(Constant(DateTime.now()))();

  // required fields
  IntColumn get theme =>
      intEnum<ThemeMode>().withDefault(Constant(ThemeMode.light.index))();
  BoolColumn get isAuthenticated =>
      boolean().withDefault(const Constant(false))();
  BoolColumn get isBiometricsEnabled =>
      boolean().withDefault(const Constant(false))();
  BoolColumn get isPincodeEnabled =>
      boolean().withDefault(const Constant(false))();
}
```

My problem is with joins and relationships, now to join the account which is from another table called accounts I have to create another class that is called `SettingsWithAccount` in order to map this, as there will be more relations not just account 

Is there a way to just add the account class prop in the SettingsTables, so be `settings.account` 

I searched and found UseRowClass but didn't quite understand how to use it to do that

**Comment by simolus3** [comment]
No, drift has no support for things which would automatically add joins when selecting from a single table.

> as there will be more relations not just account

For `SettingsTable` as well? If there is just a 1:1 relation between settings and accounts, it might be easier to just "inline" the fields from settings into the accounts table. If you want to avoid writing joins, you could store settings in a JSON structure with is stored on the accounts table in a text column with a [type converter](https://drift.simonbinder.eu/docs/advanced-features/type_converters/) instead.
