### ISSUE TITLE
Importing drift files from packages

### ISSUE THREAD

**Issue by FaFre** [simolus3/moor#2719]
I outsourced some of my drift files into separate packages to share them between packages. This used to work in older versions, but after 2.10.0 there seems to be a change that causes the issue. I tried 2.11 and 2.13, and failed to include external drift files. There is no "file not found" error in the generator, so drift_dev is aware of the file but seems to ignore its content (I validated it with trying to import an non-existing file) .

Example is:
```drift
import 'package:addon/cat.drift';

-- You can also create an index or triggers with drift files
CREATE INDEX categories_description ON categories(description);

-- we can put named sql queries in here as well:
createEntry: INSERT INTO todos (title, content) VALUES (:title, :content);
deleteById: DELETE FROM todos WHERE id = :id;
allTodos: SELECT * FROM todos; 
```

content of cat.drift in addon package:
```drift
CREATE TABLE categories (
    id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    description TEXT NOT NULL
) AS Category; -- the AS xyz after the table defines the data class name

CREATE TABLE todos (
    id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    category INTEGER REFERENCES categories(id)
);
```

Relative file imports are working as expected.

**Comment by simolus3** [comment]
Thanks for the report. Do the imported packages have a (regular, non-dev!) dependency on `drift_dev`? That is required now because files are analyzed independently to improve build performance, but the analysis results aren't visible to the main package without a `drift_dev` dependency.

**Comment by FaFre** [comment]
I added the dependency to the addon package but the problem still persists. I pushed my sample code here: https://github.com/FaFre/external_drift

**Comment by simolus3** [comment]
This is a mess, but `addon` also needs a `build.yaml` file with content like this:

```yaml
targets:
  $default:
    builders:
      drift_dev:analyzer:
        enabled: true
```

And `drift_dev` doesn't need to be a dependency of `addon`.

`addon` can't enable the default `drift_dev` builder because that builder applies `source_gen:combining_builder`, which emits source files. And only the root package in a build may apply builders emitting source files. So, by applying `drift_dev:analyzer`, the main package can see analysis results for `addon` without the build system preventing drift's analyzer from running.

**Comment by simolus3** [comment]
I've fixed the warning not showing up in d770c16d8d9790479fde55ef8d870c05beadcd3b - that also adds a message pointing to this issue for missing imports across packages.

**Comment by FaFre** [comment]
I experience more problems with the analyzer now, he is not aware of the content of the importing document and only analyzes file per file instead of compiling all imports together. My usage is her a bit hacky, since I use imports as an dependency injection for fts tables with different configurations. Not sure if this is really worth getting more investigated.

**Comment by kuhnroyal** [comment]
@simolus3 I get the warning also for imports of Dart classes and not only `.drift` files. Is this correct/expected?
In my case I am importing some converters from another package.

**Comment by simolus3** [comment]
I think I can see where that error is coming from. Builders are supposed to be stateless, so we emit hidden json files for intermediate analysis steps and read those to avoid invoking the Dart analyzer more often than we have to. When no such file exists for a given url, we assume that it's not a valid import.
Do you have a way to apply the `drift_dev` builders to the package/files defining the converters (or did you get the warning regardless of that)? I'm struggling to come up with a general solution for this in `drift_dev` that wouldn't negatively impact build times.

**Comment by kuhnroyal** [comment]
> Do you have a way to apply the drift_dev builders to the package/files defining the converters (or did you get the warning regardless of that)?

I can probably do that for this package but not sure this works everywhere, thanks!

**Comment by adg-mh** [comment]
I've run into this warning as well except my converters are defined in my local project and only the return types for those converters are imported from another package.

**Comment by HeftyCoder** [comment]
Hi! Is this warning still relevant? I have a monorepo where I define one Package with some basic classes and one Application where I use them + Drift. I get the warning but the generated code is correct.

**Comment by simolus3** [comment]
Are the "basic classes" here unrelated to drift?

**Comment by HeftyCoder** [comment]
The included Package contains some classes and is not related to Drift at all. The including Package uses these unrelated classes in Drift files. Code generation seemed to work correctly, but I still got the warning.
