### ISSUE TITLE
moor_ffy encrypted 

### ISSUE THREAD

**Issue by MP00** [simolus3/moor#272]
Hi, 

I currently use sqflite_sqlcipher by david marlos .

I'm interested in migrating to moor_ffi, but I need the encrypted data.

I read a comment talking about experimental moor_ffi encrypted:  https://github.com/simolus3/moor/issues/206#issuecomment-546046400

Are there any plans to publish this package? If so, could you give an approximate date?

Thank you!

**Comment by simolus3** [comment]
At the moment, there is no variant of `moor_ffi` with encryption support. I don't currently have plans to create one.

It is possible to use moor with encrypted databases though! The library from the referenced comment can be used already, see [the instructions here](https://moor.simonbinder.eu/docs/other-engines/encryption/). It also uses sqflite_sqlcipher internally, so it's not based on moor_ffi. If you want to use that library, you can pretty much follow the [getting started guide](https://moor.simonbinder.eu/docs/getting-started/) and replace `FlutterQueryExecutor` with `EncryptedExecutor`.
