### ISSUE TITLE
readWithType and readNullableWithType have type and key reversed in code gen

### ISSUE THREAD

**Issue by Quijx** [simolus3/moor#2721]
The methods `readWithType` and `readNullableWithType` take first the type and then the key as arguments:

https://github.com/simolus3/drift/blob/d770c16d8d9790479fde55ef8d870c05beadcd3b/drift/lib/src/runtime/query_builder/statements/select/custom_select.dart#L93-L95

https://github.com/simolus3/drift/blob/d770c16d8d9790479fde55ef8d870c05beadcd3b/drift/lib/src/runtime/query_builder/statements/select/custom_select.dart#L111-L113

However the code generation seems to generate the type last:

https://github.com/simolus3/drift/blob/d770c16d8d9790479fde55ef8d870c05beadcd3b/drift_dev/lib/src/writer/queries/query_writer.dart#L210-L214

I think `$dartLiteral` and `$typeImpl` need to be reversed.

This currently causes compile time errors in generated files when using Custom SQL types with generated queries.

**Comment by simolus3** [comment]
Well, that's embarrassing. This has been fixed in e79124e5afbdd0d4f637a8c6f6073fdb8f44e25b, I'll try to release a version with the fix this weekend. Thanks for the report!

**Comment by simolus3** [comment]
Fixed in `drift_dev` version 2.13.2.
