### ISSUE TITLE
Update null value to column is not working with UpdateStatement

### ISSUE THREAD

**Issue by msarkrish** [simolus3/moor#2722]
**Describe the bug**

Hi Simon,
I have a table called user. In my user table, the second_mobile_number column has a value. Now I'm updating that as null along with other values in that table, but second_mobile_number is not updating in the table as null. It is updated if I pass some other value to that column other than null.

    final query = update(userTable)
      ..where((t) => t.tuserid.equals(tuserid));
    final int updateResult = await query.write(userData);

Is there something I am missing?

**Comment by simolus3** [comment]
Drift generates two classes for each table: One to represent the full row as it appears in the database (`User`), and one to represent a partial row which has some fields set and others not (`UsersCompanion`). For inserts and especially for updates, you'll want to use the companion class. There, you can explicitly specify whether columns should be set to null or just kept as is. This is also explained on the [documentation](https://drift.simonbinder.eu/docs/dart-api/writes/).

**Comment by msarkrish** [comment]
Thank you, @simolus3 . I missed that in the documentation.
