### ISSUE TITLE
PgEndpoint and PgSession no longer detected

### ISSUE THREAD

**Issue by Leylan24** [simolus3/moor#2726]
I have been using the postgres drift and it has been working perfectly throughout. I am not sure what happened but I started getting this error:

```
Error: 'PgEndpoint' isn't a type.
    required PgEndpoint endpoint,
             ^^^^^^^^^^
'PgSessionSettings' isn't a type.
    PgSessionSettings? sessionSettings
```

It has been working fine for quite some time. I have checked commit history and cannot seem to find a breaking change.

```
import 'package:drift_postgres/drift_postgres.dart';
import 'package:postgres/postgres_v3_experimental.dart';
```

i see that I can no longer import postgre_v3_experimental. I get the following error:

`Target of URI doesn't exist: 'package:postgres/postgres_v3_experimental.dart'`

I changed it to 'package:postgres/postgres.dart' and changed the PgEndpoint to Endpoint and PgSessionSettings to SessionSettings and it still does not work as i get typed parameter errors

**Comment by simolus3** [comment]
You can now use the [drift_postgres](https://pub.dev/packages/drift_postgres) package on pub.dev instead of the git dependency. The one on pub.dev should support the current v3 pre-release of the `postgres` package.

**Comment by Leylan24** [comment]
Will give it a try. What changed ? I don't see anything in the commit history.

**Comment by simolus3** [comment]
The relevant commits in drift were 0e692524067155a90a90e3b64992e01685c9ff61 and 7106dfc519fc7b4d981b722f2bfa16534dbdcf70.

**Comment by Leylan24** [comment]
I have pinned drift_postgres to 0.1.0 a lot of type errors. I can list all if you want but here is some.

```
/D:/Pub/Cache/hosted/pub.dev/drift_postgres-0.1.0/lib/src/pg_database.dart:177:24: Error: Method not found: 'PgTypedParameter'.
        List<int>() => PgTypedParameter(PgDataType.byteArray, value),
                       ^^^^^^^^^^^^^^^^
/D:/Pub/Cache/hosted/pub.dev/drift_postgres-0.1.0/lib/src/pg_database.dart:187:9: Error: 'PgSession' isn't a type.
  final PgSession database;
        ^^^^^^^^^
/D:/Pub/Cache/hosted/pub.dev/drift_postgres-0.1.0/lib/src/pg_database.dart:194:32: Error: The method 'PgSql' isn't defined for the class '_PgVersionDelegate'.
 - '_PgVersionDelegate' is from 'package:drift_postgres/src/pg_database.dart' ('/D:/Pub/Cache/hosted/pub.dev/drift_postgres-0.1.0/lib/src/pg_database.dart').
Try correcting the name to the name of an existing method, or defining a method named 'PgSql'.
        await database.execute(PgSql('SELECT version FROM __schema'));
                               ^^^^^

```

**Comment by simolus3** [comment]
`drift_postgres` version 1.0.0 depends on the now stable version 3 of `postgres`, so the most recent set of published packages should work together.
