### ISSUE TITLE
Table not found exception

### ISSUE THREAD

**Issue by Elvis5566** [simolus3/moor#273]
Hi @simolus3 ,

PR #270 will cause Error: cannot commit - no transaction is active, which I don't know why...
and I realized that it doesn't seem a good solution because not every custom statements need restore.
I think restore web db after Engines._runMigrations would be better.
sorry for inconvenience.

**Comment by simolus3** [comment]
> no transaction is active, which I don't know why

Ah yeah, I completely forgot about that. On the web, saving the database resets the current transaction for some reason. This is why we're not saving the database when we're in a transaction-

> sorry for inconvenience

No problem. After all, it's my fault for not looking at it better. I've now fixed this by saving the database _after_ all migrations ran. This should solve this and your original problem.
