### ISSUE TITLE
windows  SqliteException(5): while executing statement, database is locked, database is locked (code 5)

### ISSUE THREAD

**Issue by lingg4556** [simolus3/moor#2736]
C:\Users\9022>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [版本 10.0.19045.3570], locale zh-CN)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Professional 2022 17.7.2)
[√] Android Studio (version 2022.3)
[√] Android Studio (version 2021.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!

  drift: ^2.13.1
  sqlite3_flutter_libs: ^0.5.18
  
  Some computers will lock up like this
![image](https://github.com/simolus3/drift/assets/113339400/0d606d0d-c1f3-4f67-a880-e44a601b6a29)
![image](https://github.com/simolus3/drift/assets/113339400/6e812dce-67ab-4e04-b5d4-ac74f41b66dd)
![image](https://github.com/simolus3/drift/assets/113339400/0c954011-9995-4080-abc0-e3eaf29a11be)

help me

**Comment by lingg4556** [comment]
I encountered this problem very early. In order to ensure the uniqueness of the database, I took many measures, but it still failed and reported an SqliteException(5) error.

**Comment by simolus3** [comment]
Are you using your database in multiple threads at the same time? You could try enabling wal mode and a busy timeout to reduce the likelihood of this happening:

```dart
return NativeDatabase.createInBackground(
  file,
  setup: (rawDb) {
    rawDb.execute('PRAGMA journal_mode=WAL;');
    rawDb.execute('PRAGMA busy_timeout = 100;');
  }
);
```

**Comment by lingg4556** [comment]
Yes, I have added your pattern above and am preparing to release a version to watch

**Comment by lingg4556** [comment]
This code works

return NativeDatabase.createInBackground(
  file,
  setup: (rawDb) {
    rawDb.execute('PRAGMA journal_mode=WAL;');
    rawDb.execute('PRAGMA busy_timeout = 100;');
  }
);
