### ISSUE TITLE
[DevTools]: Could not load database: Instance of 'minified:Mm'

### ISSUE THREAD

**Issue by msarkrish** [simolus3/moor#2738]
**Describe the bug**

Hi @simolus3,
While trying to check the database in devtools this exception is coming.
![image](https://github.com/simolus3/drift/assets/45334931/03c3e987-5792-41be-bd8b-5957fe41e787)

**Comment by simolus3** [comment]
Thanks for the report. Obviously the error message is not too helpful, but could you check which exact drift version you're using? Are you running the inspected app in debug mode or in profiling mode?

**Comment by msarkrish** [comment]
Hi @simolus3 
Drift version: 2.13.1 and app running in profile mode.

**Comment by simolus3** [comment]
That explains it I think, drift excludes support code for the DevTools extension outside of debug builds. I think it would be helpful to run the extension with profile mode though, so I've changed this in 4c3b12855d09619f57dfe88603d33a0dd7448664.

Could you check whether the DevTools extension works in debug mode to make sure it's not something else going wrong here?

**Comment by simolus3** [comment]
Should be fixed in version 2.14.0.
