### ISSUE TITLE
How to write a not equal expression?

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#274]
I want to select a data where the date is not equal to empty String. How should I write?

**Comment by simolus3** [comment]
With moor 2.1.0 or later, write
```dart
select(table)..where((row) => !row.column.length.equals(0))
```
in an earlier version, you'd have to use
```dart
select(table)..where((row) => not(row.column.equals('')))
```

**Comment by amreniouinnovent** [comment]
@simolus3 I used latest version `moor_flutter: ^2.1.1` 
`not` is deprecated
and using '`!`' is not working

<img width="1158" alt="Screen Shot 2020-04-14 at 12 47 38 PM" src="https://user-images.githubusercontent.com/52191652/79204774-21552b00-7e4e-11ea-93fa-cb850744739f.png">
<img width="1203" alt="Screen Shot 2020-04-14 at 12 48 09 PM" src="https://user-images.githubusercontent.com/52191652/79204819-33cf6480-7e4e-11ea-814c-e7c1391b7f77.png">

**Comment by kuhnroyal** [comment]
@amreniouinnovent It should be `offlineResponseTable.username.equals(username).not()` if  I recall correctly.

**Comment by amreniouinnovent** [comment]
@kuhnroyal Thanks, works fine
