### ISSUE TITLE
 drift-dev: Possible Regression type 'Null' is not a subtype of type 'ClassElement'

### ISSUE THREAD

**Issue by becjit** [simolus3/moor#2741]
**Describe the bug**
while running build runner I am getting the many errors from different files in my project whci are completely unrelated to drift-dev. The fact of the matter is I ran build runner for something else and not for drift

type 'Null' is not a subtype of type 'ClassElement' in type cast
[SEVERE] drift_dev on lib/screens/prescription/components/class_a.dart (cached):

type 'Null' is not a subtype of type 'ClassElement' in type cast
[SEVERE] Failed after 9.3s

I am using drift_dev: ^2.13.2

**Comment by simolus3** [comment]
Thanks for the report. Could you re-run the build with the `--verbose` flag? It should make `build_runner` report a stack trace for the error, which would be helpful to have.

**Comment by becjit** [comment]
Hi @simolus3  thanx for the response.
Here you go:

[SEVERE] drift_dev on lib/screens/home/components/reccomended_cards_widget.dart (cached):

type 'Null' is not a subtype of type 'ClassElement' in type cast
package:drift_dev/src/analysis/resolver/dart/helper.dart 56:55   new KnownDriftTypes._fromLibrary
package:drift_dev/src/analysis/resolver/dart/helper.dart 104:28  KnownDriftTypes.resolve
package:drift_dev/src/analysis/driver/driver.dart 94:28          DriftAnalysisDriver.loadKnownTypes
package:drift_dev/src/analysis/resolver/discover.dart 77:46      DiscoverStep.discover
package:drift_dev/src/analysis/driver/driver.dart 130:7          DriftAnalysisDriver.discoverIfNecessary
package:drift_dev/src/analysis/driver/driver.dart 167:7          DriftAnalysisDriver.findLocalElements
package:drift_dev/src/backends/build/analyzer.dart 36:22         DriftDiscover.build

**Comment by simolus3** [comment]
That's odd, line 56 is trying to resolve the `Table` class from drift and the error indicates that this class doesn't exist... Does `build_runner clean` help?

**Comment by becjit** [comment]
Perfect! Thanks a ton :)
