### ISSUE TITLE
Generated schema versions for `stepByStep` should probably just be public? 

### ISSUE THREAD

**Issue by dballance** [simolus3/moor#2749]
As it sits today, the schema during step-by-step migrations is only exposed in the callback. The generated `migrationSteps` method utilizes the following callbacks.

```dart
required Future<void> Function(i1.Migrator m, _S2 schema) from1To2,
```

Because of this, if you wanted to modularize migrations - you have no real way to type some consumer or other method that takes an `_S2` class - because it's private in the generated schema file. 

A very simple example: 
```dart
  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onUpgrade: stepByStep(
        from1To2: migrate1To2,
```

And the migration method:
```dart
Future<void> fromOneToTwo(Migrator m, dynamic schema) async { 
  // I MUST use dynamic here in describing the schema object, since I can't type `_S2` here.
  await m.addColumn(schema.todoEntries, schema.todoEntries.dueDate);
}
```

In my opinion, it's not really private / internal - it's being explicitly used in the callback. Further, if `_S2` was modified in some way internally, the code using the public API would still break, requiring modifications if it changes. 

**I'd like to be able to provide the schema to an implementer - be it a single method or a class based migration helper**

Just being able to break up migrations into individual methods (or maybe into a migration focused classes) would be useful for long term readability of these migrations.

```dart
class AddDueDateColumn extends SqlMigration {
  const AddDueDateColumn(
      {required AppDatabase db})
      : super(db: db);

  @override
  Future<void> up(Migrator migrator, S2 schema) async {
    // Some other notional logic here to migrate data, prune, etc...
    await db.transaction(() async {
      await migrator.addColumn(schema.todoEntries, schema.todoEntries.dueDate);
    });
  }
}

**Comment by simolus3** [comment]
Good call, I agree that they should be public :+1:

**Comment by dballance** [comment]
Wow - that was fast @simolus3. I was coming here to say that after some more thought - you could even just make the function signature public. But just making them public is probably the easiest and most long term flexible way to expose them.
