### ISSUE TITLE
More naming options

### ISSUE THREAD

**Issue by clragon** [simolus3/moor#2751]
**Is your feature request related to a problem? Please describe.**
Right now, it seems difficult for me to find a nice setup for the class names offered by drift.

**Example**
I name my Table class "AppleTable". 
Then, the generated Table will be called "AppleTableTable". 
The actual class I get out of this Table will be called "AppleTableData".
The companion will be called "AppleTableCompanion".

I dislike all of these names, although "AppleTableTable" name does not matter to me, since its not exported anywhere in my code.

I can slightly change this outcome with the `@DataClassName('Apple')`.
With that I then get `Apple` for my model. However, the other two classes stay the same.
This still bothers me, because I think "AppleTableCompanion" is not a great name.

**Another Example**
A different approach is to name my Table "Apples". 
This gives me "ApplesTable" (okay), "Apple" (great) and "ApplesCompanion" (ehh). 
This appears one of the best options (and kind of "cannonical" by drift), though I think I would prefer "AppleCompanion" over "ApplesCompanion".

**Describe the solution you'd like**

I think a nicer default behaviour would be great.
Another incredibly simple solution would be to allow directly naming the Companion class in an annotation.
In my other code I oftentimes write a class called "\<Model>Request" which is actually quite similar to a Companion.insert, meaning it is a model that simply lacks the ID. Maybe I would just start naming my Companions that way.

I must also mention that it is possible for me to simply bypass this problem with a bunch of typedefs that map the generated names to my desired names. But this is of course very inconvenient.

**Comment by simolus3** [comment]
I think the `use_data_class_name_for_companions` [builder option](https://drift.simonbinder.eu/docs/advanced-features/builder_options/) does this - with `@DataClassName('Apple')` or when naming the table `Apples`, it would give you `AppleCompanion`.

But I agree that being able to explicitly name the companion class is useful.
