### ISSUE TITLE
Debug error: 42000

### ISSUE THREAD

**Issue by VadimOsovsky** [simolus3/moor#276]
I/flutter ( 8377): Debug error: 42000
I/flutter ( 8377): 1064
I/flutter ( 8377): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') AS S1
I/flutter ( 8377): 	ORDER BY `attr_FullName` ASC #7 SORT
I/flutter ( 8377): 	 /*8 LIMIT*/  /*9 OFFSET*/' at line 16 [42000]
I/flutter ( 8377): Debug stack: null

in
```
    return (
        select(contacts)
          ..where((c) => c.idUser.equals(userServerId))
          ..where((c) => c.storage.equals(storage))
          ..orderBy([(m) => OrderingTerm(expression: m.fullName)])
    ).get();
```

**Comment by simolus3** [comment]
I assume you're using `moor_mysql`? That's great, but be aware that it's still very experimental at the moment. It should always log the statements moor sent to the database, so can you post the full generated sql statement? Then I can take a look at where things are going wrong and add a fix for mysql.

**Comment by VadimOsovsky** [comment]
@simolus3 That's all I received in the console, also I didn't specify the version in pubspec.yaml so flutter installed the latest version of moor_flutter

**Comment by simolus3** [comment]
> Is it using moor_mysql?

No. But the error you posted says `You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for ...`, that's clearly coming from MariaDB and not sqlite. Moor uses sqlite as database, so maybe the error you're seeing isn't coming from moor at all. 

MariaDB isn't commonly used on mobile, it's more of a database for servers. Maybe the error is coming from a backend or some other plugin?

**Comment by VadimOsovsky** [comment]
Could be, sorry then, I'll check, the issue is closed for now
