### ISSUE TITLE
Generated snapshots (Companions) in Migration Test don't validate maxLength constraints

### ISSUE THREAD

**Issue by ynnob** [simolus3/moor#2764]
I added a maxLength constraint to a column in V2 of the Database scheme. When writing tests and inserting data into the V2 Schema the insert via the companion class of the schema does not validate the max length constraint and allow me to insert a text with a length > max.

I use step-by-step migrations and followed the general migration guidline ([Verifying data integrity](https://drift.simonbinder.eu/docs/migrations/tests/#verifying-data-integrity))

I saw that the maxLength constraint is only validated in drift because SQLite only support checks but no real restrictions right?
Is it expected that the Migration Schema Companion classes don't check the same constraints as the regular classes?

**Comment by simolus3** [comment]
It looks like we have all the information necessary to generate these checks, but at the moment verification code is explicitly disabled for generated schema code.

Older schema versions are mostly meant to run migrations, and I'm learning towards keeping their code as small as possible. Are you running inserts with dynamic data as part of your migrations?

**Comment by ynnob** [comment]
> It looks like we have all the information necessary to generate these checks, but at the moment verification code is explicitly disabled for generated schema code.
> 
> Older schema versions are mostly meant to run migrations, and I'm learning towards keeping their code as small as possible. Are you running inserts with dynamic data as part of your migrations?

Not really sure i understand what you mean by dynamic data.
We introduced a text leghtn max value to an existing column.

`TextColumn get bezeichnung => text().withLength(max: 80)();`

We transfer the data between desktop and mobile clients so i added a migration that will substring existing values to 80 characters.

```
              await m.alterTable(
                TableMigration(
                  tds,
                  columnTransformer: {
                    tds.bezeichnung:
                        tds.bezeichnung.substr(0, 81),
                  },
                ),
              );
```

In my migration test i wanted to simulate user input before and after the migration between V1 and V2. I added data in V1 that was longer then 80 chars and validated that it has been trimmed correctly. And i wanted to validate that the max length is enforced now with V2 so i added data exceeding the 80 char limit. Thats when i was a bit surprised that i can't really validate it.

I mean i can life with that but it just threw me off. it feels a bit counterintuitive that the test for the migration can't 100% mirror the real application / database behavior.

**Comment by simolus3** [comment]
Right. Yeah the length constraints are actually checked in Dart and not added as a SQL constraint. That was a poor decision from the early days of moor, but changing it alters the schema which would make it a very breaking change.

So you could add a custom `CHECK` constraint to circumvent this, since it would then get checked by sqlite3. Even if we did add the Dart check for schema versions, it wouldn't work since the column transformer is a SQL statement - we don't see the transformed rows in Dart.
