### ISSUE TITLE
Consider generating code compliant with   implicit-dynamic: false

### ISSUE THREAD

**Issue by knaeckeKami** [simolus3/moor#278]
Context:

A dart project can contain an `analysis_options.yaml` file that enables stricter type checking.
One of these options is 
 `implicit-dynamic: false`
which will prevent the compiler from inferring `dynamic` unless it's explicitly annotated.

I propose changes to make the moor generator compatible with these stricter type checks. 
They might be enabled by default in the future, anyway.
A somewhat related option
 `implicit-casts: false` will be enabled by default, when NNBD lands. ( see https://github.com/dart-lang/sdk/issues/31410#issuecomment-510683629 ).

Projects that use  `implicit-dynamic: false` and moor_generator currently need to exclude generated files from this rule ( e.g. by using   exclude: [ `lib/**/*.g.dart]` in their `analysis_options.yaml`).
If this rule becomes the default in the future, all users of moor_generator would need to exclude thee files generated by moor_generator.

The steps needed to make the code compliant would be.

1. change the generated == methods from 

```dart
bool operator ==(other) {
```

to

```dart
bool operator ==(Object other) {
```

2. change the generated toJson() methods from

```dart
@override
Map<String, dynamic> toJson(
      {ValueSerializer serializer = const ValueSerializer.defaults()}) {
    return {
      'key': serializer.toJson<String>(key),
      ...
    };
}
```
to

```dart
@override
Map<String, dynamic> toJson(
      {ValueSerializer serializer = const ValueSerializer.defaults()}) {
    return <String, dynamic>{
      'key': serializer.toJson<String>(key),
      ...
    };
}
```

**Comment by simolus3** [comment]
Thanks for the request and the detailed description. With the next generator release, the code will be compliant with `implicit-dynamic: false`. See also #268.

**Comment by knaeckeKami** [comment]
Oh, sorry for the duplicate, I missed #268 somehow, even though it's worded nearly identical.
