### ISSUE TITLE
View with multiple GroupBy conditions generates code with an error

### ISSUE THREAD

**Issue by brinux** [simolus3/moor#2787]
I'm defining a view with a GroupBy condition made of 2 columns, like this:

..groupBy([rTimestamp, eId])

The generated code misses the "comma" in between the 2 column names, like this:

..groupBy([rTimestamp eId])

Actually the output of "dart run build_runner watch" states: "Could not format generated source. The generated code is probably invalid, and this is most likely a bug in drift_dev."

**Comment by simolus3** [comment]
Thanks for the report, I can reproduce the issue. You can work around the problem by avoiding commas in list literals (`groupBy([rTimestamp]..add(eId))`), but obviously this should be fixed in drift.
