### ISSUE TITLE
Potentially Update Documentation "Importing and exporting databases"

### ISSUE THREAD

**Issue by jakobhec** [simolus3/moor#2788]
In the [Setup documentation](https://drift.simonbinder.eu/docs/getting-started/), there are workarounds regarding Android. 

```dart
// Also work around limitations on old Android versions
if (Platform.isAndroid) {
  await applyWorkaroundToOpenSqlite3OnOldAndroidVersions();
}

// Make sqlite3 pick a more suitable location for temporary files - the
// one from the system may be inaccessible due to sandboxing.
final cachebase = (await getTemporaryDirectory()).path;
// We can't access /tmp on Android, which sqlite3 would try by default.
// Explicitly tell it about the correct temporary directory.
tempDirectory = cachebase;
```

They are not in the [Importing and Exporting Databases documentation](https://drift.simonbinder.eu/docs/examples/existing_databases/#extracting-the-database). 

Should they also be in there?

**Comment by simolus3** [comment]
I agree, I've added that snippet in ad856314c20e43a92ce01c6275678e3da90132e7.

**Comment by jakobhec** [comment]
Thanks @simolus3!
