### ISSUE TITLE
How to create a dynamic coalesce select statement?

### ISSUE THREAD

**Issue by knyghtryda** [simolus3/moor#279]
I'm trying to do a sort that's attempting to sort on available values in multiple columns (say first_name, last_name, company, etc).  The priority of these columns can change, and column values can be null (thought this is mainly for the purposes of using coalesce).  Previously I was just using `ORDER BY` on series of columns of decreasing priority but this does not interleave the results, instead it just tries to sort on the first order by, then the second, etc.  The correct approach (as far as I've found) seems to be using `COALESCE` to generate a new column with the first available value to sort on, then use that for `ORDER BY` on that generated column.  However I'm not able to generate a dynamic coalesce statement that allows for modifying the order of the columns in the `COALESCE(item1, item2, etc)`.  Is this currently possible in moor?

```sql
Example query:
SELECT contacts.*, 
COALESCE(contacts.company, contacts.first_name, contacts.last_name) sort_name 
ORDER BY sort_name ASC
```

**Comment by simolus3** [comment]
I'm not sure if that's just a typo in the issue description, but I assume you still need a `FROM` somewhere in that query. I've added the following to a moor file
```sql
create table config (
    config_key TEXT not null primary key,
    config_value TEXT
) AS "Config";

testCoalesce:
 SELECT 
   config.*,
   COALESCE(config.config_key, config.config_value) sort_name
 FROM config ORDER BY sort_name;
```
The generator accepts that and generates code for `testCoalesce`. Is that what you're looking for?

**Comment by knyghtryda** [comment]
Sorry, not only was my description bad my example was wrong :P.  Your example works fine, but I need the columns inside coalesce to be dynamic, ie. `COALESCE($columns)` or `COALESCE(:column1, :column2)` etc.  Both of those throw errors from the generator.   `$columns` gives a `Bad state: Unknown expression DartExpressionPlaceholder: $columns` error and `:columns` gives a `Bad state: No element` error.

**Comment by simolus3** [comment]
I've fixed the crash when using a variable (`:columns`) or a Dart component (`$columns`) as parameters to a function call. 
However, that's still not going to work - using a variable won't do it because it'll be the same value for each row, it can't refer to columns. Using `COALESCE($columns)` is better, but we'd only recognize that as a _single_ expression, not multiple. It's not easy to decide whether we should view a Dart component as a single expression or as multiple expressions. Changing that behavior now would also be breaking for existing users.

Do you really need to expose the `sort_name` as a result column? If you don't, you could use something like
```sql
exampleQuery: SELECT contacts.* ORDER BY $expression ASC
```
and call the method with
```dart
final expression = FunctionCallExpression('COALESCE', [/* dynamic arguments here */]);
final results = await exampleQuery(expression).get();
```

**Comment by knyghtryda** [comment]
FunctionCallExpression doesn't seem to exist.

**Comment by simolus3** [comment]
Doh, I thought we already exported that but it seems like that's only happening on `develop`. Well, it will be available in the next moor version.

You could get away with a [`CustomExpression`](https://pub.dev/documentation/moor/latest/moor_web/CustomExpression-class.html) in the meantime:
```dart
final expression = CustomExpression('COALESCE(column_1, column_2, ...)');
```

**Comment by knyghtryda** [comment]
CustomExpression is throwing this error:
```
type 'CustomExpression<dynamic, SqlType<dynamic>>' is not a subtype of type 'OrderBy'
```

**Comment by knyghtryda** [comment]
I deleted a previous comment because I thought I made a mistake, but I double checked and CustomExpression is throwing an error:
`type 'CustomExpression<dynamic, SqlType<dynamic>>' is not a subtype of type 'OrderBy'`

**Comment by simolus3** [comment]
I just tried to reproduce that type error only with moor versions on pub. I'm using this moor file:
```sql
create table config (
    config_key TEXT not null primary key,
    config_value TEXT
) AS "Config";

testQuery: SELECT * FROM config ORDER BY $expression ASC;
```
and this Dart file:
```dart
import 'package:moor/moor.dart';
import 'package:moor_ffi/moor_ffi.dart';

part 'database.g.dart';

@UseMoor(include: {'tables.moor'})
class Database extends _$Database {
  Database() : super(VmDatabase.memory());

  @override
  int get schemaVersion => 1;

  Future<void> test() async {
    final expression = CustomExpression('COALESCE(config_key, config_value)');
    await testQuery(expression).get();
  }
}

void main() async {
  final db = Database();
  await db.test();
}
```

However, it all works just fine for me (moor 2.1.1, moor_generator 2.1.1)

Can you provide more details on where that error is thrown? E.g. some stacktrace? When you go to the generated `exampleQuery` method, it should take an `Expression` as parameter, right?

**Comment by knyghtryda** [comment]
Found the issue.  You had `ASC` in the query.  I was building that in the custom expression.  I need ASC to be a modifiable as well.  Previously I had 
```sql
ORDER BY $orderBy
```
and was generating an order by with just 
```dart
OrderBy([OrderingTerm(...), ...])
```
Is it possible to have ASC/DESC be generated as well?

**Comment by simolus3** [comment]
> Is it possible to have ASC/DESC be generated as well?

I think your approach of constructing the `OrderBy` in Dart should work. If I change the query from the example to `SELECT * FROM config ORDER BY $order` (so without the `ASC), I can use the generated method like this:
```dart
final expression = CustomExpression('COALESCE(config_key, config_value)');
final order = OrderBy([OrderingTerm(expression: expression, mode: OrderingMode.asc)]);
await testQuery(order).get();
```

This still works for me without throwing a type error.

**Comment by knyghtryda** [comment]
Thats perfect.  I was just missing the connection between having the expression on its own being able to have it in the OrderingTerm as well.  Thank you!
