### ISSUE TITLE
DevTools not working with cross platform

### ISSUE THREAD

**Issue by mstfkhazaal** [simolus3/moor#2793]
After update flutter I was unable to access DevTools at all
<img width="1536" alt="Screenshot 2023-12-17 at 12 45 55 PM" src="https://github.com/simolus3/drift/assets/47450090/b30f297f-7db1-4514-bfab-87207b447135">

![image](https://github.com/simolus3/drift/assets/47450090/42a02dc7-f935-4b31-8179-3732ec4e6f2e)

**Comment by simolus3** [comment]
Which flutter and drift version are you using? It works for me with Flutter 3.16.4 and drift version 2.14.1.

**Comment by mstfkhazaal** [comment]
> Which flutter and drift version are you using? It works for me with Flutter 3.16.4 and drift version 2.14.1.

Yes i use Flutter 3.16.4 and 2.14.1

After researching, I think the problem is not related to the update
I think it's because i use cross platform connection
https://github.com/simolus3/drift/tree/develop/examples/app/lib/database/connection

**Comment by simolus3** [comment]
I don't see how that could be related. The drift extension should be shown in DevTools whenever you have an app with a dependency on `drift`. Do you have a `devtools_options.yaml` file at the root of your app that has drift enabled (I think it would be created by DevTools automatically).

**Comment by mstfkhazaal** [comment]
yes i have devtools_options.yaml with drift enable
