### ISSUE TITLE
Unable to handle multiple same db data class retrival at the same time.

### ISSUE THREAD

**Issue by lucasjinreal** [simolus3/moor#2805]
I have a demand, which need to query messages out, and also the messages which from an originalityId from that message.

I am currently using this:

```dart
 final query = select(messages).join([
      leftOuterJoin(contacts, contacts.id.equalsExp(messages.fromId)),
      innerJoin(messages, messages.id.equalsExp(messages.originalId))
    ])
      ..where(messages.roomId.equals(roomId))
      ..orderBy([
        OrderingTerm(expression: messages.sendTime, mode: OrderingMode.desc)
      ]);
```

the messages all got from:

```dart
 return query.watch().map((rows) {
      return rows.map((row) {
        DbMessage dbMessage = row.readTable(messages);
        DbMessage originalityMessage = row.readTable(messages);
        DbMessageExtra dbMessageExtra = DbMessageExtra.fromDbMessage(
          dbMessage,
          repliedMessages: null, // Set accordingly
          originalityMessage: null, // Set accordingly
        );
```

How tot distinguish them? thank u in advance

**Comment by simolus3** [comment]
Isn't this the same as https://github.com/simolus3/drift/issues/2799? Let's keep the discussion in one place. I've posted a complete snippet solving the problem in that issue.

**Comment by lucasjinreal** [comment]
@simolus3 ~~No, I don't post an issue there, but looks like sort of likely. Can u elaborate a little bit how to distinguish them? (the issue you linked are closed)~~

I have find the snippets, thanks a ton!
