### ISSUE TITLE
Nested queries got laggy on UI

### ISSUE THREAD

**Issue by lucasjinreal** [simolus3/moor#2807]
Hi, I previously consulted a way to query data nested, it works like a charm!

This is the code:

```dart
 Stream<List<DbMessageWithDbContactOrRoomMember>>
      getMessagesWithRoomMemberByRoomId(String roomId,
          {int perPage = 25, int pageNum = 0}) {
    debugPrint("[dao] roomid: $roomId, perPage: $perPage, pageNum: $pageNum");
    final outerMessages = alias(messages, 'm');
    final replies = alias(messages, 'i');
    final selectReplies = selectOnly(replies)
      ..addColumns([
        FunctionCallExpression('json_group_array', [replies.id])
      ])
      ..where(replies.originalId.equalsExp(outerMessages.id));
    final replyIds = subqueryExpression<String>(selectReplies);
    final query = select(outerMessages).join([
      leftOuterJoin(
          roomMember,
          roomMember.id.equalsExp(outerMessages.fromId) &
              roomMember.roomId.equalsExp(outerMessages.roomId))
    ])
      // ..limit(perPage, offset: pageNum * perPage)
      ..limit((pageNum + 1) * perPage, offset: 0)
      ..addColumns([replyIds])
      ..where(outerMessages.roomId.equals(roomId))
      ..orderBy([
        OrderingTerm(
            expression: outerMessages.sendTime, mode: OrderingMode.desc)
      ]);
    return query.watch().map((rows) {
      final messageById = {
        for (final row in rows)
          row.read(outerMessages.id)!: row.readTable(outerMessages),
      };

      return rows.map((row) {
        final id = row.read(outerMessages.id)!;
        DbMessage dbMessage = messageById[id]!;
        final original = switch (dbMessage.originalId) {
          null => null,
          var id => messageById[id],
        };
        final childIds =
            (json.decode(row.read(replyIds)!) as List).cast<String>();
        DbMessageExtra dbMessageExtra = DbMessageExtra.fromDbMessage(
          dbMessage,
          // originalityMessage: null, repliedMessages: null
          originalityMessage: original != null
              ? DbMessageExtra.fromDbMessage(original!,
                  repliedMessages: null, originalityMessage: null)
              : null,
          repliedMessages: [
            for (final childId in childIds)
              if (messageById.containsKey(childId))
                DbMessageExtra.fromDbMessage(messageById[childId]!,
                    repliedMessages: null, originalityMessage: null)
          ],
        );
        // print(dbMessageExtra);
        return DbMessageWithDbContactOrRoomMember(
          dbMessageExtra,
          roomMember: row.readTableOrNull(roomMember),
        );
      }).toList();
    });
  }
```

I can get the messages and originality message and replied messsages of it.

But now, I found every time a data updated, the whole things got laggy.

This is out of my scope, actually, am using Stream as you can see, it shoudldnt effect much since it async,

but the result is my UI got laggy every time new message comes in, and everytime I sned a message ,

Can u help me why it got stuck?

**Comment by simolus3** [comment]
How many messages are there? Is there an index on the room or on `messages.originalId` (there should be one if you're using foreign key constraints and have the foreign key pragma enabled)?

How are you opening the database, are you using `NativeDatabase.createInBackground`?

**Comment by lucasjinreal** [comment]
@simolus3  The laggy I didn't occured previous or not very severe, but recently, when I did something :

I using RxList to contains mssages (with GetX), then for every get have messages.bindStream() operation

Is that possible the issue to cause laggy? It looks like will subscribe streams again and again.

Also, the messages here are 32 max for one batch, and maybe 64 for 2 batch, not too much.

**Comment by simolus3** [comment]
> then for every get have messages.bindStream() operation

I wasn't aware of `RxList` before, which package is providing `messages.bindStream()` or what is that doing?

> It looks like will subscribe streams again and again.

Drift is kind of optimized for this since the `StreamBuilder` widget can cause similar things. If you cancel a subscription and then re-subscribe to it reasonably quickly (one event loop iteration between those, we cancel streams after one `Timer.run` iteration), the query should not be run again.

**Comment by lucasjinreal** [comment]
It's GetX, widely used, it provides a way to do stream like behavior but simpler, RxList a can a.bindSream to make it use streams return by drift.

Since GetX so widely used, am just wonder the reason, why I using a.bindStream in every time get data from sql and stream to UI got laggy.

One possible reasons is that, when I get data from sql and bindStream, if there is a sql update, and then same time updating UI (since it's stream), it might got some kind of race trace problem

**Comment by simolus3** [comment]
Are you calling `close()` on the rx objects after you don't need them anymore? If you have thousands of "different" streams in drift (different SQL or different parameters), the lag would be unavoidable. It looks like there is no way to unsubscribe from a stream after passing it to `bindStream` without closing the rx object.

> One possible reasons is that, when I get data from sql and bindStream

Why do you call `bindStream` every time? Do you have a way to use `switchMap` to combine multiple streams into one if you don't need all of them at once?

**Comment by lucasjinreal** [comment]
@simolus3 I didn't called close() anywhere, since this is a APP lifecycle object to be called. 
but the bindStream might called many times eveytime I enter the page, it will be called in `initState` func.

Where could I close the stream on UI? dispose or somwhere? Does bindStream many times will casued UI laggy?

**Comment by simolus3** [comment]
> dispose or somwhere? Does bindStream many times will casued UI laggy?

It looks like there is no way to cancel a stream passed to `bindStream`, so yeah - from a quick look it appears as that method inherently leaks resources.

But let's merge this discussion into https://github.com/simolus3/drift/issues/2838, which appears to be about the same problem.
