### ISSUE TITLE
Flutter windows desktop app freezes when bulk operation in database taking place

### ISSUE THREAD

**Issue by kumarkrati** [simolus3/moor#2809]
Hi, our flutter app works completely fine on Android, ios and the web. We were hoping that if we built the flutter Windows app, the performance would be much faster than the Web app. But when the bulk insertion is happening, the system just freezes till the write operation is done. Any solution for this?

**Comment by simolus3** [comment]
Are you using drift isolates / `NativeDatabase.createInBackground` already?

**Comment by kumarkrati** [comment]
No I am not, can you help me with that?
This is my current code - 

Database constructDb() {
  final executor = LazyDatabase(() async {
    final dataDir = await paths.getApplicationDocumentsDirectory();
    final dynamic dbFile = File(
      p.join(dataDir.path, 'kfdb.sqlite'),
    );
    return NativeDatabase(dbFile, logStatements: true);
  });

  return Database(executor);
}

**Comment by simolus3** [comment]
You should be able to offload some of the database work to a background isolate with:

```dart
Database constructDb() {
  final executor = LazyDatabase(() async {
    final dataDir = await paths.getApplicationDocumentsDirectory();
    final dynamic dbFile = File(
      p.join(dataDir.path, 'kfdb.sqlite'),
    );
    return NativeDatabase.createInBackground(dbFile, logStatements: true);
  });

  return Database(executor);
}
```

**Comment by simolus3** [comment]
Do you still have the problem with `createInBackground`? I'll close this issue since there has been no response, but if that doesn't fix the problem I'll re-open this for further investigation.
