### ISSUE TITLE
ON CONFLICT UPDATE not working on drift files

### ISSUE THREAD

**Issue by JCKodel** [simolus3/moor#2813]
**Describe the bug**

Consider this table:

```sql
CREATE TABLE "UserLogins"(
  "lastLogin"         INTEGER NOT NULL,
  "userId"            TEXT NOT NULL,
  "authProvider"      TEXT NOT NULL,

  "lastModified"      DATETIME NOT NULL DEFAULT(STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
  "deleted"           BOOLEAN NOT NULL DEFAULT(FALSE),
  "synced"            BOOLEAN NOT NULL DEFAULT(FALSE),
  PRIMARY KEY("lastLogin", "userId")
);

CREATE INDEX "IX_UserLogins_lastModified" ON "UserLogins"("lastModified");
CREATE INDEX "IX_UserLogins_deleted" ON "UserLogins"("deleted");
CREATE INDEX "IX_UserLogins_synced" ON "UserLogins"("synced");

CREATE TRIGGER "TR_UserLogins_lastModified"
AFTER UPDATE ON "UserLogins"
FOR EACH ROW
WHEN "authProvider" <> old."authProvider"
BEGIN
  UPDATE "UserLogins"
  SET "synced" = FALSE, "lastModified" = STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE "lastLogin" = old."lastLogin" AND "userId" = old."userId";
END;


```

and this dao:

```sql
registerLogin(REQUIRED :lastLogin AS INTEGER, REQUIRED :userId AS TEXT, REQUIRED :authProvider AS TEXT):
INSERT INTO "UserLogins"("lastLogin", "userId", "authProvider")
VALUES(:lastLogin, :userId, :authProvider)
ON CONFLICT("lastLogin", "userId")
DO UPDATE SET "authProvider" = :authProvider;
```

It complains that column `appSettings` doesn't exist, but the column really exists (I use drift_db_viewer and the column appears on it, also, I have copied and pasted all SQL into https://sqliteonline.com/ and all work fine (including the above query)).

Changing to 

```sql
registerLogin(REQUIRED :lastLogin AS INTEGER, REQUIRED :userId AS TEXT, REQUIRED :authProvider AS TEXT):
INSERT OR REPLACE INTO "UserLogins"("lastLogin", "userId", "authProvider")
VALUES(:lastLogin, :userId, :authProvider);
```

"solves" the problem.

**Comment by simolus3** [comment]
> It complains that column `appSettings` doesn't exist

Really? It doesn't do that for me and the column hasn't even been mentioned in the query.

I've pasted the definition and the query into separate drift files in the `examples/modular` package from this repository and there is no warning from the generator.

**Comment by JCKodel** [comment]
@simolus3 I'm sorry, I meant `authProvider` column.

I'm not talking about the generator, I'm talking about actually executing the code

For example:

This is the exception:

![image](https://github.com/simolus3/drift/assets/379339/66677325-f08f-43e0-b04d-380742b47334)

(same as above: no such column: authProvider)

But this is the drift_db_viewer:

![image](https://github.com/simolus3/drift/assets/379339/12f54a3d-580e-4002-b643-600e72e04fdb)

The column is there!

There are no warnings whatsoever after a `clean` and a `run build_runner`.

Copying and pasting all queries on sqliteonline.com works just fine.

Changing that query to `INSERT OR REPLACE` solves the problem (so, the column IS really there), but other updates stop working, for instance:

```
DriftRemoteException (SqliteException(1): while preparing statement, no such column: name, SQL logic error (code 1)
  Causing statement: UPDATE "Users" SET "name" = ?, "originalName" = ?, "avatarUrl" = ?, "originalAvatarUrl" = ? WHERE "id" = ? AND "deleted" = ?;)
```

At first run, this code is executed:

```dart
await into(users).insert(
            UsersCompanion.insert(
              id: principal.id,
              name: principal.name,
              email: principal.email,
              avatarUrl: principal.avatarUrl,
            ),
          );
```

On some next run, this code is executed (there is an `if` to determine if the insert or update is executed, they are in the same method)

```dart
  await (update(users)
                ..where(
                    (u) => u.id.equals(principal.id) & u.deleted.equals(false)))
              .write(
            UsersCompanion(
              name: Value(principal.name),
              originalName: Value(originalName),
              avatarUrl: Value(principal.avatarUrl),
              originalAvatarUrl: Value(originalAvatarUrl),
            ),
          );
```

It is not possible for the column to exist in `INSERT` but not on `UPDATE`.

O.o

**Comment by simolus3** [comment]
It only seems to happen with the trigger but I don't see what's wrong. I'll try to minimize the example and post an issue to the sqlite3 forum.

**Comment by simolus3** [comment]
It works with `WHEN new."authProvider" <> old."authProvider"` (note the explicit `new`). Or just use `AFTER UPDATE OF "authProvider" ON "UserLogins"` and drop the `WHEN`. I think we should reject unqualified references in triggers since they seem to cause problems.

**Comment by simolus3** [comment]
I've fixed `sqlparser` to be consistent with what sqlite3 is doing in f9fa123e4a4f347f0f3445a0e376b5c133b7d68d.

The solution is to fix the definition of the trigger to use a qualified reference or `UPDATE OF`. You'll have to write a migration dropping and re-creating the trigger afterwards if a version of the database with that trigger has already been published.
