### ISSUE TITLE
Wrong link in the docs which lead to 404

### ISSUE THREAD

**Issue by curiouslaw** [simolus3/moor#2822]
Just going through the docs and found in migration pages, in this code (below the link), the `[exporting your schema]({{ 'exports.md' }})` go to `https://drift.simonbinder.eu/docs/migrations/tests/exports.md` instead of `https://drift.simonbinder.eu/docs/migrations/exports/`, which caused 404.

https://github.com/simolus3/drift/blob/7046f24f0ef62339ac4b18f3c8c47ae99e462e08/docs/pages/docs/Migrations/tests.md?plain=1#L23

Let me know if you need more information.

Btw thanks for the package and hope this help!

**Comment by simolus3** [comment]
Thanks for the report! I've fixed this in 42a0a400551298ff55fcba2cdda6206181b57b52, it will go live with the next drift version.
