### ISSUE TITLE
Bug on built flutter web

### ISSUE THREAD

**Issue by juanccalzadilla** [simolus3/moor#2835]
I got the following error when I built flutter app on web

<img width="560" alt="Captura de pantalla 2024-01-15 a las 12 24 13" src="https://github.com/simolus3/drift/assets/78725536/85865e03-900b-45be-9d5e-6638e7d636b6">

What it could be?

**Comment by simolus3** [comment]
Do you see the network request for that worker in the network tab of the console? If it's a 404, chances are you don't have the `drift_worker.js` file in your `web` folder - you can get it from [here](https://github.com/simolus3/drift/releases) if that's the case.

**Comment by juanccalzadilla** [comment]
Perfect! it works for me, I had to add the drift_worker.js from your assets to the web/ folder

Thanks @simolus3
