### ISSUE TITLE
How to  use  OrderingMode.desc?

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#284]
```
Future<List<ABC>> getReadings() {
    return (select(readings)
          ..orderBy([(t) => OrderingMode.desc(expression:t.updatedAt)]))
        .get();
  }
```

**Error**

> The expression doesn't evaluate to a function, so it can't be invoked.

**Comment by simolus3** [comment]
At the moment, the correct way to do this would be 
```dart
[(t) => OrderingTerm(expression: t.updatedAt, mode: OrderingMode.desc)]
```

I like the idea of having `OrderingTerm.desc` and `OrderingTerm.asc` factories though, they could make this feature easier to use.

**Comment by tony123S** [comment]
Kinda weird. I want to display number based  on `OrderingMode.asc`, but I get this:

`1,10,11,2,3,4,5,6,7,8,9`

**Comment by tony123S** [comment]
I changed String to int, it works now . Thanks.
