### ISSUE TITLE
How to couple the table created by the drift file 🤔️？

### ISSUE THREAD

**Issue by greenking19** [simolus3/moor#2846]
This is a table created in the `Dart` file, which allows for coupling.
What should I do in the `Drift` file?
It seems that the **[Existing row classes](https://drift.simonbinder.eu/docs/sql-api/drift_files/#existing-row-classes)** in the document needs to be created first. My table is a bit complicated, so it would be a bit troublesome to manually create it.
If there are other ways, that would be even better.
# Example
``` dart
enum StatusEnum { open, close }

mixin WithStatus on Table {
  IntColumn get status => intEnum<StatusEnum>()();
}

class TodoItems extends Table with WithStatus {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text()();
  TextColumn get userId => text()();
}

class TaskItems extends Table with WithStatus {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text()();
  TextColumn get userId => text()();
}

void doSomething(dynamic data) {
  if (data is WithStatus) {
    // do something
  }
}
```

**Comment by simolus3** [comment]
There's no way to do declare an inheritance structure for tables in drift files, they can't share a a common mixin for columns.

But while there is no way to do this with type safety, you can still access columns of abstract tables. For instance, if you had

```sql
CREATE TABLE todo_items (
  status INTEGER ...,
  ...
);

CREATE TABLE task_items (
  status INTEGER ...,
  ...
);
```

Then you can do

```dart
void doSomething(TableInfo data) {
  if (data.columnsByName.containsKey('status')) {
    // do something
  }
}
```
