### ISSUE TITLE
Database Connection Handler. 

### ISSUE THREAD

**Issue by Leylan24** [simolus3/moor#2868]
Hi, I am having a specific issue where the connection to the Postgres Database works fine. When internet connectivity is switched on and off it seems like the connection to the database does not automatically connect or reconnect. It just attempts the insert/select until a timeout occurs. Is there a built in stream I can listen to that will allow me to perform the reconnect when a disconnect happens? 

Currently I am using the connectivity_info_plus and listening for a none connection, if there is no internet close the connection and open it again. This is not ideal because I feel like other scenarios besides connectivity could require an attempted reconnection?

**Comment by simolus3** [comment]
I think the main problem here is that the postgres package does not cleanly react to connections being dropped, I don't think there is a way for drift to react to the database being closed.
If loosing connectivity means that the TCP connection to postgres is closed (and we get an indication of that happening from the OS), it should be possible to react to that in postgres and drift - I'll take a look. But if the user is on a poor network with very long roundtrips or lots of dropped packets, I don't think we'll be able to detect that reliably and close the connection.

**Comment by simolus3** [comment]
This should be possible with version 3.0.8 of the postgres package. If you set up your drift databases like this:

```dart
  final pgDatabase = await pg.Connection.open(
    pg.Endpoint(
      host: 'localhost',
      database: 'postgres',
      username: 'postgres',
      password: 'postgres',
    ),
  );
  final database = YourDatabaseClass(PgDatabase.opened(pgDatabase));
```

Then you can get notified when the underlying `pgDatabase` closes by awaiting `pgDatabase.closed`. The future will also complete when the TCP socket to the server gets closed. Once `pgDatabase.closed` completes without you explicitly trying to close the database, you can try to reconnect.

**Comment by simolus3** [comment]
I think this should have been addressed with the postgres update - let me know if you still run into this.
