### ISSUE TITLE
Cannot use a pre-existing sqlite db in drift web

### ISSUE THREAD

**Issue by ehtiqamar** [simolus3/moor#2872]
I've gone through the docs & performed all steps correctly but there is no mention of using an existing database for web. I've gone through this link: 
https://drift.simonbinder.eu/docs/examples/existing_databases/

I've done it for native platform, but can't find anything related to web for it.

**Comment by simolus3** [comment]
This should be solved with https://github.com/simolus3/drift/discussions/2870, right?
