### ISSUE TITLE
Provide `Comparable` expressions for postgres types

### ISSUE THREAD

**Issue by prefanatic** [simolus3/moor#2884]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to use `Comparable` expressions on postgres types.

**Describe the solution you'd like**
As you would with sqlite `Comparable` expressions, it would be really nice to extend this to postgres types. For example, being able to query between `PgDateTime` ranges:

```dart
final query = _database.dates.select()
      ..where((tbl) => tbl.date.isBetween(startDate, endDate));
```

**Comment by simolus3** [comment]
I agree, and since the relational operators should work for datetime types in Postgres, it's probably as simple as making `PgDateTime` implement `Comparable` so that the extension becomes available.

**Comment by simolus3** [comment]
Added in fe578223afa017a6284b36f487b169b7d5171ca0, the date and timestamp columns can be used to form comparisons with the next release.
