### ISSUE TITLE
Error when validating database schema in Flutter DevTools

### ISSUE THREAD

**Issue by spehj** [simolus3/moor#2888]
My app works fine with Drift database, But when inspecting it with Flutter DevTools, I get an error:
`The schema could not be validated due to an error: TypeError: null: type 'minified:Dg' is not a subtype of type String`

Here is my simple database.dart file that causes this. Am I missing something?
```dart

import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import 'drift_mpn_device_repository.dart';

part 'database.g.dart';

@DataClassName('DeviceEntity')
class Devices extends Table {
  TextColumn get id => text()();
  TextColumn get name => text().nullable()();

  @override
  Set<Column> get primaryKey => {id};
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'devices.sqlite'));
    return NativeDatabase(file);
  });
}

@DriftDatabase(tables: [Devices])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;
}


```

**Comment by spehj** [comment]
I figured out this is probably an extension issue. I think this issue could be closed.

**Comment by simolus3** [comment]
Not at all, things happening in the drift tab are all handled by the drift package. This bug was caused by the explicit `primaryKey` annotation I think, it made sqlite3 generate an implicit index without a `CREATE INDEX` statement which confused the schema validator
