### ISSUE TITLE
Simple count(*)?

### ISSUE THREAD

**Issue by SBurgos00** [simolus3/moor#2890]
Hey, I'm pretty new to Dart and Flutter. I wanted to do a simple **SELECT COUNT(*) FROM MyTable** but I'm having trouble understanding how to do it. The docs have an count example with a join but I just can't get it right without just writing out the SQL statement. How can it be done?

**Comment by simolus3** [comment]
Theres actually a utility method doing exactly this: You can call `yourTable.count().get()` for a `Future<int>` thanks to [this method](https://drift.simonbinder.eu/api/drift/tableorviewstatements/count).
