### ISSUE TITLE
Add ability to override generated json field name

### ISSUE THREAD

**Issue by rosstimothy** [simolus3/moor#29]
My JSON is snake case and my getters are camel case. 

I either change my getters to snake case and get a dart warning, or change the generated code to use snake case. 

Please add a way to override the JSON key.

```
  void _writeToJson(StringBuffer buffer) {
    buffer.write('Map<String, dynamic> toJson() {\n return {');

    for (var column in table.columns) {
      final getter = column.dartGetterName;
      buffer.write("'$getter': $getter,");
    }

    buffer.write('};}');
  }
```

**Comment by simolus3** [comment]
Should be done with 8cc2c21c9a49f0390c3bbba4e535e36bb3c8ed57.

**Comment by simolus3** [comment]
I'll try to release a new version this weekend, I still need to do some testing with some other changes that would be included in that release.
