### ISSUE TITLE
Documentation issue: Setup

### ISSUE THREAD

**Issue by neiljaywarner** [simolus3/moor#2903]
documentation in https://drift.simonbinder.eu/docs/getting-started/ as is from getting started gave compile time / lint /IDE error /red squigglies

had to change to
`
@DriftDatabase(tables: [TodoItems])
class AppDatabase extends _$AppDatabase {
  AppDatabase(super.e);

  @override
  int get schemaVersion => 1;
}
`
where the docs say

`
@[DriftDatabase](https://drift.simonbinder.eu/api/drift/driftdatabase-class)([tables](https://drift.simonbinder.eu/api/drift/driftdatabase/driftdatabase): [TodoItems])
class AppDatabase extends _$AppDatabase {
}
`

**Comment by simolus3** [comment]
The only changes you've had to make were adding the `schemaVersion` override and the `super` constructor? The docs mention this one paragraph below that snippet and also give a correct snippet afterwards:

![grafik](https://github.com/simolus3/drift/assets/5738860/e52b1426-954b-4280-a98b-6e0b2ddad05a)

The idea was to build up the example step-by-step to make it easier to understand. But for users directly looking for a fully working setup to copy, perhaps the page should link to that at the top.

**Comment by neiljaywarner** [comment]
i apologize.You are totally right, i will close this issue - it is my error
for not noticing the quite reasonable words "for now" and "now looks like
this". Sorry about that.  also you get "cool points" for such a prompt response on both items ;)
