### ISSUE TITLE
because framework depends on both package_info_plus ^5.0.1 and drift_dev ^2.16.0, version solving failed.

### ISSUE THREAD

**Issue by tooooka** [simolus3/moor#2926]
Because no versions of drift_dev match >2.16.0 <3.0.0 and drift_dev 2.16.0 depends on drift >=2.16.0 <2.17.0, drift_dev ^2.16.0 requires drift >=2.16.0 <2.17.0.
And because no versions of drift match >2.16.0 <2.17.0, drift_dev ^2.16.0 requires drift 2.16.0.
And because drift 2.16.0 depends on web ^0.5.0 and package_info_plus >=5.0.1 depends on web >=0.3.0 <0.5.0, drift_dev ^2.16.0 is incompatible with package_info_plus >=5.0.1.
So, because framework depends on both package_info_plus ^5.0.1 and drift_dev ^2.16.0, version solving failed.

**Comment by simolus3** [comment]
The problem is that `package_info_plus` doesn't support the latest version of `web` yet. They did update their dependencies, but it seems they haven't published a new version yet.

Either way, you can work around this issue by using

```yaml
dependency_overrides:
  web: ^0.5.0
```
