### ISSUE TITLE
how can i know what't version of my database schema

### ISSUE THREAD

**Issue by MahdiPishguy** [simolus3/moor#293]
after installing application on device how can i know find `schemaVersion` in database file? my mean is `sqlite` file in device

**Comment by simolus3** [comment]
You could use the [`beforeOpen`](https://moor.simonbinder.eu/docs/advanced-features/migrations/#post-migration-callbacks) callback for migrations. That callback is run every time the database opens and contains all the necessary information. `details.versionBefore` contains the version of the database file before opening, `details.versionNow` contains the current version after migrations ran.
