### ISSUE TITLE
Code generation failure

### ISSUE THREAD

**Issue by canavci312** [simolus3/moor#2933]
```
type 'Null' is not a subtype of type 'InterfaceElement' in type cast
[SEVERE] drift_dev on
```
Getting this error when running buildrunner on the project. It throws this error for almost all the pages in the app after I run buildrunner. 
To fix it I delete pubspec.lock run flutter pub get then generate again. 
Is there any way to fix this permanently? It happens a couple of times a day not sure why it happens

**Comment by simolus3** [comment]
I think this is a bug in `build_runner` or `analyzer`, but I've not been able to track it down reliably. Closing this as a duplicate of #2883, let's keep the discussion there.
