### ISSUE TITLE
"Null check operator used on a null value" during update.replace call

### ISSUE THREAD

**Issue by kirqe** [simolus3/moor#2936]
Hi. I use a custom row class. The only null value that I see during debug is the id(because we do copyWith)
There's a problem with the dao part where I call `update(tasks).replace(task);`

```
Exception has occurred.
_TypeError (Null check operator used on a null value)
```

Does this look like a bug to you? Am I missing something?
Thank you!

row class

```
class Task implements Insertable<Task> {
  final int? id;

  @ja.JsonKey(name: 'order_id')
  final int orderId;

  final bool finished;

  Task({this.id, required this.orderId, required this.finished});

  factory Task.fromJson(Map<String, dynamic> json) => _$TaskFromJson(json);

  bool get isNew => id == null;

  Map<String, dynamic> toJson() => _$TaskToJson(this);

  @override
  String toString() => toJson().toString();

  TasksCompanion toCompanion(bool bool) {
    if (isNew) {
      return TasksCompanion.insert(orderId: orderId, finished: Value(false));
    } else {
      return TasksCompanion(
          id: Value(id ?? 0), orderId: Value(orderId), finished: Value(finished));
    }
  }

  @override
  Map<String, Expression<Object>> toColumns(bool nullToAbsent) {
    return TasksCompanion(orderId: Value(orderId), finished: Value(finished)).toColumns(nullToAbsent);
  }

  Task copyWith({int? orderId, bool? finished}) => Task(
      orderId: orderId ?? this.orderId, finished: finished ?? this.finished);
}
```

dao

```
  Future<void> updateReplace(Task task) => update(tasks).replace(task);
```

call

```
await db.tasksDao.updateReplace(task.copyWith(finished: isFinished));
```

<img width="626" alt="Screenshot 2024-04-01 at 15 21 51" src="https://github.com/simolus3/drift/assets/5272402/1b755617-e707-4255-a5f6-020ec4cee6fe">

https://github.com/simolus3/drift/blob/fc7e2ab1e6d0cb793a78728a48fcb77f7f24335f/drift/lib/src/runtime/query_builder/statements/query.dart#L418

**Comment by simolus3** [comment]
Thanks for the report! Do you have an empty primary key? Could you post the definition of the `Tasks` table as well?

**Comment by kirqe** [comment]
I slightly updated the table names but the structure is basically the same
During `task.copyWith` the original task has the id

```
import 'package:json_annotation/json_annotation.dart' as ja;

@UseRowClass(Task)
class Tasks extends Table {
  IntColumn get id => integer().autoIncrement()();

  IntColumn get orderId => integer().references(Orders, #id, onDelete: KeyAction.cascade)();

  BoolColumn get finished => boolean().withDefault(const Constant(false))();
}

@ja.JsonSerializable()
class Task implements Insertable<Task> {
...
```


The "tasks" are fetched from api and saved like this


```
final Set<TasksCompanion> tasksCompanions;

tasks.forEach((taskJson) {
        tasksCompanions.add(Task.fromJson({
          'order_id': orderJson['id'],
          'finished': false
        }).toCompanion(true));
      });

... call daos
```

I checked the state. The items are being saved with no issues

**Comment by simolus3** [comment]
> The only null value that I see during debug is the id(because we do copyWith)

So to be sure, you're calling `replace` with a `Task` object that has its `id` field set to `null`? That would explain the error, but I don't think drift can do much against that (except giving a better error message). Tasks are identified by their id and we need to know which task to replace, but we can't do that if `id` is null.

**Comment by kirqe** [comment]
There were no row classes in moor and originally the code worked :)

Sorry for not providing more details. I'll try to experiment with it 

```
oldTask = oldTaskWithIdThatIsPersisted.copyWith(finished: isFinished)
newTaskWithNoId = db.tasksDao.updateReplace(oldTask);

```

This is needs to be replaced with something different then 
`Future<void> updateReplace(OrderBlank orderBlank) => update(orderBlanks).replace(orderBlank);`

**Comment by kirqe** [comment]
You're right. This works. Thank you!

```
 Future<void> toggleFinish(Task task, bool state) {
    return update(tasks)
        .write(TasksCompanion(finished: state));
  }
```

edit: oh, I meant where task, passing the existing task -___-

Another option is to search through other fields. update.where.write

**Comment by simolus3** [comment]
Be careful with that, I think it would update all tasks and apply the `finished: false` column to every row. If the task has a non-null `id` then the `copyWith`/`replace` call should work.
You could also do `(update(tasks)..whereSamePrimaryKey(task)).write(TasksCompanion(finished: state))` - but again, only if `task.id` is not null.

**Comment by wisamidris77** [comment]
The problem appeared to me as well when, I even have a default value but fromJson just ignores it
