### ISSUE TITLE
WSL Ubuntu22 - app that uses drift renders as fully white screen

### ISSUE THREAD

**Issue by crisperit** [simolus3/moor#2940]
I'm using WSL setup with Ubuntu22 and I'm trying to create & run the flutter linux app which uses drift

WSL version details:
```
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3374
```

I've spotted some unexplainable error for me that app render as full white screen if the app uses drift (and it isn't even
![image](https://github.com/simolus3/drift/assets/17547300/0cbdb39d-e76a-4487-9902-54b83bde157c)
![image](https://github.com/simolus3/drift/assets/17547300/9885001c-2a2e-4fb9-82b5-32e768a2743a)

vs when I remove that async call to Drift DB then app renders correctly
![image](https://github.com/simolus3/drift/assets/17547300/647e51e0-2e31-48cb-aa1f-5e7189e56d99)
![image](https://github.com/simolus3/drift/assets/17547300/2bfa01a5-aff0-4973-ad73-bca938f26197)

Do you have any ideas how to tackle it?

I've installed `libsqlite3-dev` as written in https://drift.simonbinder.eu/docs/platforms/#linux
![image](https://github.com/simolus3/drift/assets/17547300/f165b99c-f55c-48f2-a9ea-495099dd173e)

The drift is actually returning the results but it somehow is causing the UI to not render indirectly. Not sure how to tackle it

**Comment by crisperit** [comment]
Ok.. I had a problem with the drivers on ubuntu WSL2
Mine biggest problem is that I have 2 graphic cards in mine laptop aand the Intel one was selected..
https://github.com/microsoft/wslg/issues/715#issuecomment-1937349068

1. I've installed valid drivers https://docs.nvidia.com/cuda/wsl-user-guide/index.html#cuda-support-for-wsl-2
2. I've set env variable to `MESA_D3D12_DEFAULT_ADAPTER_NAME=NVIDIA`

**Comment by simolus3** [comment]
Weird - but by the way, you don't need `libsqlite3-dev` if you have a dependency on  `sqlite3_flutter_libs` (unless you're running unit tests outside of Flutter).
