### ISSUE TITLE
Mentioning that `drift_db_viewer v2.0.0` is breaking due to changes in `Flutter v3.22+` Material implementation 

### ISSUE THREAD

**Issue by RoarGronmo** [simolus3/moor#2942]
As I understand `drift_db_viewer` is mentioned here as a tool to show drift data tables on device (and even web).

From v3.22 of Flutter (now Flutter beta channel and Flutter main/master channels) this library is breaking during build.

Please take a look here: https://github.com/vanlooverenkoen/db_viewer/issues/57

**Comment by simolus3** [comment]
Thanks for the report, I've submitted a PR to that repository.

**Comment by RoarGronmo** [comment]
I hope @vanlooverenkoen sees your PR soon...

**Comment by vanlooverenkoen** [comment]
@RoarGronmo thanks for the ping! I'm on it. You can expect a new release in the coming hours!

**Comment by vanlooverenkoen** [comment]
Fixed in 1.1.0 for db_viewer and 2.1.0 for drift_db_viewer
