### ISSUE TITLE
In app migrate v13 issue 

### ISSUE THREAD

**Issue by vidhyalakhmi** [simolus3/moor#2956]
Did billing upgradation from 4 to 5 for Android, after migration doesn't show the price for a free trial and also after 1 week trial period ends, the next billing period not extending to 30 days instead extends to another 7 days.

**Comment by simolus3** [comment]
It's impossible for me to act on this issue without a lot more detail on what tables you have, which migration you've written and which specific queries started failing after the migration. Posting what appears to be an internal bug description for your app onto drift's issue tracker just wastes a lot of time. If you have a specific, reproducible example where drift's migrations aren't working as you would have expected, I'm happy to take a look at that.

You can call `validateDatabaseSchema()` ([docs](https://drift.simonbinder.eu/docs/migrations/#verifying-a-database-schema-at-runtime)) or use the functionality from the drift devtools extension to verify that your migrations turned the database into the schema that drift expects. Maybe that helps to find the migration issue.
