### ISSUE TITLE
MacOS sqlite-src-3450100 Warnings

### ISSUE THREAD

**Issue by doug9876** [simolus3/moor#2962]
When running the example app on macOS I get a lot of warnings from sqlite3, I don't get these warnings when running on chrome.

I've attached the warnings, and below is an example.  I've double checked by downloading the repo again and running the example app (without any changes etc...).

The app still runs and seems to work fine.  I've searched through the issue, repository, and documentation site but can't see any reference to this being expected.

Is this expected?  And if not any idea what the issue could be?

Many thanks for creating Drift too!

[Drift Warnings.txt](https://github.com/simolus3/drift/files/15041133/Drift.Warnings.txt)

Thanks,
Tim

```
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006021-001228AA1E7B401E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00006021-001228AA1E7B401E, name:My Mac }
/Users/macuser/Downloads/drift-develop/examples/app/macos/Pods/sqlite3/sqlite-src-3450100/sqlite3.c:31372:25: warning: ambiguous expansion of macro 'MAX' [-Wambiguous-macro]
          szBufNeeded = MAX(e2,0)+(i64)precision+(i64)width+15;
                        ^
In module 'Darwin' imported from /Users/macuser/Downloads/drift-develop/examples/app/macos/Pods/sqlite3/sqlite-src-3450100/sqlite3.c:348:
#define MAX(a, b) (((a)>(b))?(a):(b))
        ^
# define MAX(A,B) ((A)>(B)?(A):(B))
         ^
/Users/macuser/Downloads/drift-develop/examples/app/macos/Pods/sqlite3/sqlite-src-3450100/sqlite3.c:31523:60: warning: implicit conversion loses integer precision: 'i64' (aka 'long long') to 'int' [-Wshorten-64-to-32]
                 &pAccum->zText[pAccum->nChar-nCopyBytes], nCopyBytes);
                                                           ^~~~~~~~~~
/Users/macuser/Downloads/drift-develop/examples/app/macos/Pods/sqlite3/sqlite-src-3450100/sqlite3.c:31628:18: warning: implicit conversion loses integer precision: 'i64' (aka 'long long') to 'int' [-Wshorten-64-to-32]
        length = j;
               ~ ^
/Users/macuser/Downloads/drift-develop/examples/app/macos/Pods/sqlite3/sqlite-src-3450100/sqlite3.c:36357:14: warning: implicit conversion loses integer precision: 'sqlite3_int64' (aka 'long long') to 'VList' (aka 'int') [-Wshorten-64-to-32]
    pIn[0] = nAlloc;
```

**Comment by simolus3** [comment]
Unfortunately we pretty much can't do anything about them: Patching sqlite3 just for this would be unreasonable, but individual pods can't ask for their warnings specifically to be disabled (as far as I know).

You can disable these warnings for all pods by putting `inhibit_all_warnings!` in your podspec. If you want to disable them for sqlite3 only, add `pod 'sqlite3', :inhibit_warnings => true` in the `target 'Runner' do` block.

**Comment by doug9876** [comment]
Thanks for the response, that makes sense, and good to know it isn't something to be concerned about.
