### ISSUE TITLE
duplicate column name

### ISSUE THREAD

**Issue by heiha100** [simolus3/moor#2975]
**Describe the bug**

I upgraded the database and added a new column named speed to a table. However, I encountered an intermittent error on Windows when attempting to add a new row to the table:
SqliteException(1): while executing, duplicate column name: speed, SQL logic error (code 1)
  Causing statement: ALTER TABLE "file_contents" ADD COLUMN "speed" INTEGER NOT NULL DEFAULT 0;, parameters:

I am using:
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.21

**Comment by simolus3** [comment]
Can you show the migration? Is it the latest one? Are you doing anything except adding the new column?
My best guess (but this requires more information either way) is that something in the migration goes wrong after that `ALTER TABLE` statement already ran. In that case, drift won't store the new version number and will try to re-run the migration afterwards, causing the error you're seeing. Do you see any other drift-related errors on the same devices that might indicate something with the migrations going wrong?

**Comment by heiha100** [comment]
> Can you show the migration? Is it the latest one? Are you doing anything except adding the new column? My best guess (but this requires more information either way) is that something in the migration goes wrong after that `ALTER TABLE` statement already ran. In that case, drift won't store the new version number and will try to re-run the migration afterwards, causing the error you're seeing. Do you see any other drift-related errors on the same devices that might indicate something with the migrations going wrong?

Thank you for your help. I've identified the issue causing the problem. My database's latest version is 4, but I reinstalled an older version of my app and kept the database file, which downgraded the database version to 3. However, the 'speed' column wasn't deleted during this process. When I reinstalled the newest version of the app, it tried to add the 'speed' column again. To fix this, I should either add a statement for downgrading or check if the column exists before attempting an upgrade.

**Comment by orestesgaolin** [comment]
Wondering, how can we check if the column exists before executing migration? I got the same issue the other day

**Comment by simolus3** [comment]
[This PR](https://github.com/simolus3/drift/pull/3037/files) contains code to check which columns currently exist in a database table. I'm not sure about merging it as I think the check should ideally be unnecessary in well-written migrations, but perhaps it's helpful as a pointer if you need that logic.

**Comment by orestesgaolin** [comment]
Thanks, that would be amazing to have! I came up with something similar but it seems to be now wrong compared to your solution (didn't know about `readNullable`)

```dart
extension on Migrator {
  Future<bool> columnExists(String name, String table) async {
    // check if column exists
    final tableInfo = await database.customSelect('PRAGMA table_info(${table})').get();
    final column = tableInfo.firstWhereOrNull(
      (e) => e.read<String>('name') == name,
    );

    return column != null;
  }
}
```

**Comment by albe-jj** [comment]
To check if a column exist in a certain table I use this function (adapted from above)

```dart
Future<bool> hasColumn(String tableName, String columnName) async {
  // PRAGMA doesn't support parameter binding, need to escape table name
  final escapedTableName = tableName.replaceAll('"', '""');
  final tableInfo = await customSelect(
    'PRAGMA table_info("$escapedTableName")',
  ).get();

  return tableInfo.any((row) => row.read<String>('name') == columnName);
}
```

@simolus3 the use case for this is that I have a python process that might also migrate the database. Would be useful to have such a method in the drift api.

**Comment by orestesgaolin** [comment]
For anyone wondering here are my extensions I built to handle the above issue

```dart
extension on Migrator {
  Future<void> addColumnIfNotExists({
    required GeneratedColumn<Object> column,
    required TableInfo<Table, dynamic> table,
  }) async {
    if (await columnExists(name: column.name, table: table.actualTableName)) {
      return;
    }
    await addColumn(table, column);
  }

  Future<bool> columnExists({required String name, required String table}) async {
    // check if column exists
    final tableInfo = await database.customSelect('PRAGMA table_info($table)').get();
    final column = tableInfo.firstWhereOrNull(
      (e) => e.read<String>('name') == name,
    );

    return column != null;
  }

  Future<void> createTableIfNotExists(TableInfo<Table, dynamic> table) async {
    if (await tableExists(table.actualTableName)) {
      return;
    }
    await createTable(table);
  }

  Future<void> dropTableIfExists(TableInfo<Table, dynamic> table) async {
    await database.customStatement('DROP TABLE IF EXISTS ${table.actualTableName}');
  }

  Future<void> dropTableIfExistsByName(String table) async {
    await database.customStatement('DROP TABLE IF EXISTS $table');
  }

  Future<void> dropColumnIfExists({
    required String column,
    required TableInfo<Table, dynamic> table,
  }) async {
    if (await columnExists(name: column, table: table.actualTableName)) {
      await database.customStatement('ALTER TABLE ${table.actualTableName} DROP COLUMN $column');
    }
  }

  Future<bool> tableExists(String table) async {
    final tableInfo = await database
        .customSelect("SELECT count(*) FROM sqlite_master WHERE type='table' AND name='$table'")
        .get();
    final count = tableInfo.first.read<int>('count(*)');
    return count > 0;
  }
}
```
