### ISSUE TITLE
error DioException

### ISSUE THREAD

**Issue by mahdi3800** [simolus3/moor#2978]
Exception has occurred.
DioException (DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.
)

**Comment by simolus3** [comment]
Drift has nothing to do with HTTP, so I assume this error is entirely unrelated to drift.
