### ISSUE TITLE
[drift_postgres] Cannot insert null value to default column

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#2981]
I'm running into an issue when using the `drift_postgres` package that doesn't occurr when using the `postgres` package.

For the following table:

```sql
CREATE TABLE IF NOT EXISTS public.parent (
  id INTEGER PRIMARY KEY NOT NULL,
  value TEXT,
  other INTEGER DEFAULT 0
);
```

This works using postgres:
```dart
    await db.execute('''
INSERT INTO public.parent (id, value, other) VALUES (3, 'hi', \$1);
''',
      parameters: [null],
    );
```

This doesn't work using drift
```dart
await db.customInsert('''
INSERT INTO public.parent (id, value, other) VALUES (3, 'hi', \$1);
''', variables: [Variable(null)]);
```

The error is 
`Severity.error 42804: column "other" is of type integer but expression is of type text hint: You will need to rewrite or cast the expression.`

**Comment by simolus3** [comment]
Thanks for the help finding and fixing this, I've released version 1.2.2.
