### ISSUE TITLE
Manager: Support tables with custom row classes

### ISSUE THREAD

**Issue by simolus3** [simolus3/moor#2989]
At the moment, no manager classes are generated for tables with custom row classes.

We should investigate whether it's possible to make these APIs available for existing row classes as well. It's always a good principle to have different features work well together, and I don't see why users of custom row classes shouldn't also want the manager APIs for simple queries.
If there are parts of the manager API that are harder to support with existing row classes, perhaps we can start with a subset first and gradually expand it.

**Comment by dickermoshe** [comment]
I'm putting this on the back burner. I would like to bring the manager API up to feature parity with similar ORM libraries first.
