### ISSUE TITLE
Support for Adding Methods on Generated Models

### ISSUE THREAD

**Issue by codekeyz** [simolus3/moor#299]
```dart
class Reminders extends Table {
  TextColumn get id => text().customConstraint('UNIQUE')();
  TextColumn get description => text()();
  IntColumn get priority => integer()();

  TextColumn get type =>
      text().nullable().map(CategoryConverter<ReminderType>())();
  TextColumn get category =>
      text().nullable().map(CategoryConverter<ReminderCategory>())();

  DateTimeColumn get dueDate =>
      dateTime().nullable().map(DateTimeConverter())();
  DateTimeColumn get updatedAt =>
      dateTime().nullable().map(DateTimeConverter())();
  DateTimeColumn get createdAt => dateTime().map(DateTimeConverter())();

  @override
  Set<Column> get primaryKey => {id};

  

  static bool isAnnual(ReminderCategory category) {
    return category == ReminderCategory.birthday ||
        category == ReminderCategory.anniversary ||
        category == ReminderCategory.holiday;
  }
}
```

When i ran the code generation command, the `isAnnual` model is stripped off the generated `Reminder` model.

**Comment by simolus3** [comment]
I don't think moor should copy static methods from a table definition to the generated model class. After all, you could still call `Reminders.isAnnual` instead of `Reminder.isAnnual`. This is a different story for instance methods, see #114.

**Comment by outrelouxhe** [comment]
I understand that moor shouldn't copy static methods to the generated model class. What would then be the best practice to add methods to the generated class and keep the ease of use of the stream providers with dao ? Thank you in advance for your feedback.
