### ISSUE TITLE
`enableMigrations` param for web implementation.

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#2992]
Would it be possible to use the same `enableMigrations` configuration in a Web setup like this one?

```dart
DatabaseConnection connect() {
  return DatabaseConnection.delayed(Future(() async {
    final db = await WasmDatabase.open(
      databaseName: webDbName,
      sqlite3Uri: _sqlite3Uri,
      driftWorkerUri: _driftWorkerUri,
    );

    final conn = db.resolvedExecutor;
    return conn;
  }));
}
```

**Comment by simolus3** [comment]
Good call, I was just to lazy to implement it right away because it requires changes to the protocol between the worker and the main tab. Fixed in f2299152feb29d708cc5a12d86265fb941f067be (but you'll also have to update your drift worker once that is released).
