### ISSUE TITLE
Error while trying to run in flutter web

### ISSUE THREAD

**Issue by BrijalKothari** [simolus3/moor#2997]
**Describe the bug**
My app supports both web and mobile platforms, but when I tried to run it on the web, I encountered the following error:
![Screenshot 2024-05-07 at 10 47 22 AM-1](https://github.com/simolus3/drift/assets/92941109/eb8ec1cb-0c5c-44bf-9d32-7b90937e7dcc)

**Comment by simolus3** [comment]
You can't import `package:drift/native.dart` for code supposed to run on the web. Drift has [web support](https://drift.simonbinder.eu/web/), but unfortunately it requires a bit of additional setup (downloading the sqlite3 wasm module and a worker JS bundle). The linked documentation site explains how to set this up for multiplatform projects, and we also have [this example app](https://github.com/simolus3/drift/tree/develop/examples/app) which can run on the web.
