### ISSUE TITLE
flutter web unable to build

### ISSUE THREAD

**Issue by selvam920** [simolus3/moor#3005]
Launching lib\main.dart on Edge in debug mode...
/C:/Users/sksso/AppData/Local/Pub/Cache/hosted/pub.dev/drift-2.18.0/lib/src/sqlite3/database_tracker.dart:1:8: Error: Dart library 'dart:ffi' is not available on this platform.
import 'dart:ffi';
       ^
Context: The unavailable library 'dart:ffi' is imported through these packages:

    web_entrypoint.dart => package:sksmarket/main.dart => package:sksmarket/screens/common/splash.dart => package:sksmarket/plugins/native.dart => package:sksmarket/utils/appconstants.dart => package:sksmarket/utils/util.dart => package:sksmarket/screens/core/storelist.dart => package:sksmarket/screens/core/newstore.dart => package:sksmarket/services/entityservice.dart => package:sksmarket/services/commonservice.dart => package:sksmarket/services/localtranservice.dart => package:sksmarket/utils/appmethods.dart => package:sksmarket/screens/common/apptypes.dart => package:sksmarket/screens/common/locallogin.dart => package:sksmarket/screens/managepin.dart => package:sksmarket/utils/commonwidget.dart => package:sksmarket/screens/core/myaccount.dart => package:sksmarket/utils/navigation_router.dart => package:sksmarket/screens/accounts/cashbankadjustment.dart => package:sksmarket/services/transservice.dart => package:sksmarket/services/fileservice.dart => package:sksmarket/services/settingservice.dart => package:drift/native.dart => package:sqlite3/sqlite3.dart => package:sqlite3/src/ffi/api.dart => dart:ffi

**Comment by simolus3** [comment]
As the name implies, `package:drift/native.dart` only works on native platforms.

Using drift in webapps is possible with some extra setup (you need to manually download a sqlite3 wasm library and a Dart worker, Flutter unfortunately doesn't let us bundle these within `sqlite3_flutter_libs` yet). [This page](https://drift.simonbinder.eu/web/) in the documentation describes how to set everything up.
