### ISSUE TITLE
Can't compile to wasm 

### ISSUE THREAD

**Issue by Fraa-124** [simolus3/moor#3009]
Hello, I cannot compile with wasm, despite having Drift version 2.18.0.

`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on macOS 14.2.1 23C71 darwin-arm64, locale en-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)`

```
main.dart => package:app/db-sqlite/connection/connection.dart =>
    package:app/db-sqlite/connection/web.dart => package:drift/wasm.dart => package:sqlite3/wasm.dart => package:sqlite3/src/wasm/vfs/simple_opfs.dart => package:sqlite3/src/wasm/js_interop.dart => package:sqlite3/src/wasm/js_interop/typed_data.dart => dart:html
``` 

The file package:sqlite3/src/wasm/js_interop/typed_data.dart still references to dart:html, I don't know If I am wrong or missing something.

```dart
import 'package:drift/wasm.dart';

DatabaseConnection connect({bool isInWebWorker = false}) {
  return DatabaseConnection.delayed(Future(() async {
    final result = await WasmDatabase.open(
      databaseName: 'db', // prefer to only use valid identifiers here
      sqlite3Uri: Uri.parse('sqlite3.wasm'),
      driftWorkerUri: Uri.parse('drift_worker.dart.js'),
    );

    if (result.missingFeatures.isNotEmpty) {
      kprint('Using ${result.chosenImplementation} due to missing browser '
          'features: ${result.missingFeatures}');
    }

    return result.resolvedExecutor;
  }));
```

**Comment by simolus3** [comment]
Wasm support is tracked in https://github.com/simolus3/sqlite3.dart/issues/230. Please also check that you're on the latest version of the `sqlite3` package and consider the current caveats. Properly compiling drift to wasm will be supported soon, but reliably testing this is still blocked by SDK limitations such as not being able to compile non-Flutter apps to independent web assembly modules.
