### ISSUE TITLE
[web] TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'

### ISSUE THREAD

**Issue by andrewpmoore** [simolus3/moor#3010]
I'm trying to use a drift database on the web (running `flutter run -d chome`) and I'm getting the error

`TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'` in my logs

I'm trying to open the database with the following code
```
  return LazyDatabase(() async {
    return DatabaseConnection.delayed(Future(() async {
      final result = await WasmDatabase.open(
        databaseName: 'my_app_db', // prefer to only use valid identifiers here
        sqlite3Uri: Uri.parse('sqlite3.wasm'),
        driftWorkerUri: Uri.parse('drift_worker.dart.js'),
      );

      if (result.missingFeatures.isNotEmpty) {
        // Depending how central local persistence is to your app, you may want
        // to show a warning to the user if only unrealiable implemetentations
        // are available.
        print('Using ${result.chosenImplementation} due to missing browser '
            'features: ${result.missingFeatures}');
      }

      return result.resolvedExecutor;
    }));
  });
```

Passing that into the database class
```
@DriftDatabase(
  tables: [StoreUsers, StorePlans, StoreReadings, StoreTasks, StoreEnvironments],
  daos: [EnvironmentsDao, PlansDao, UsersDao, TasksDao, ReadingsDao]
)
class AppDb extends _$AppDb {
  AppDb(super.e);

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (Migrator m) async {
        await m.createAll();
      },
      onUpgrade: (Migrator m, int from, int to) async {},
      beforeOpen: (details) async {
        if (kDebugMode) {
          // await validateDatabaseSchema();
        }
      },
    );
  }
}
```

I'm using the drift viewer package and I can see that the database tables are created correctly, but it seems that as soon as I try to interact with them (or the drift viewer package does) I get the above error.

I'm running the latest flutter version
`Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.19045.4412], locale en-GB)`
but also tried downgrading, but that didn't help.

Any ideas what the issue may be?

**Comment by andrewpmoore** [comment]
Followed the `In native Flutter apps, you can create an instance of your database with` section and it seems to be working now

**Comment by Chester-Sun** [comment]
Hi @andrewpmoore , do you mean this section? https://drift.simonbinder.eu/Platforms/web/?h=native+apps+flutter#sharing-code-between-native-apps-and-web
