### ISSUE TITLE
SqliteException(1): while preparing a statement, unrecognized token: "@"

### ISSUE THREAD

**Issue by RCVZ** [simolus3/moor#3011]
**Describe the bug**

A custom select with the query `'SELECT * FROM exercises WHERE equipment @> ["barbell","benchPress"]'` throws the error `SqliteException(1): while preparing a statement, unrecognized token: "@", SQL logic error (code 1)
 `

Equipment is a list of strings.

Shouldn't this be valid syntax since SQLite 3.38.0
If this syntax isn't valid how could I query with Drift based on if all the values of a list can be found in another list?

sqlite3_flutter_libs: 0.5.20

**Comment by simolus3** [comment]
> Shouldn't this be valid syntax since SQLite 3.38.0

I'm not sure why you'd think that, that operator has never been in sqlite3. sqlite 3.38.0 has added some json operators but all the `@` things are very much postgres-specific. The `[]` array syntax is not valid SQL either.

If you want to check whether a column is in a list of values, use `equipment IN (?, ?)` and bind the variables to the values you care about. Or use [isIn](https://drift.simonbinder.eu/api/drift/expression/isin) in drift.

**Comment by RCVZ** [comment]
My bad.

isIn doesn't seem to work it return zero results 
So if I have a column that contains a list of strings that can be a combination of strings from a fixed list.
And I only want to return the rows which are of which the values of column equipment are in the fixes list.

The column
``` TextColumn get equipment => text().map(const ExerciseEquipmentConverter())();```

**Comment by RCVZ** [comment]
Sorry, my bad. Thank you for pointing that out.

I ended up with this query
 ```
"SELECT * FROM exercises WHERE EXISTS ( SELECT * FROM json_each(equipment) WHERE value IN ($list))"
 ```
 
 isIn doesn't seem to work it returns zero results. 
 Probably because it can't handle Array with Strings in it?

**Comment by simolus3** [comment]
Yes the array syntax is not supported by sqlite3. If you put that into a drift file or into the `DriftDatabase` annotation under the `queries` parameter, drift will generate a method for you that desugars the `IN :variable`.
