### ISSUE TITLE
[Documentation] Insufficient documentation and examples on complex migration

### ISSUE THREAD

**Issue by AlexDochioiu** [simolus3/moor#3018]
**Is your feature request related to a problem? Please describe.**

I have a slightly more complex migration (yet still nothing crazy) that I need to perform, but the documentation/example/tests and/or API comments are not helping enough.

-----

In my case:

I have a table with columns:
* `cA` of type String 
* `cB` of type String?

I need to:

a) Alter the table to create `cC` column of type String
b) Assign the value from `cB` to `cC` (if it's not null). if `cB` value is null, assign the value from `cA` to `cC`.

c) Alter the table to create `cD` column of type String (textEnum)
d) Based on the values in `cA` and `cB` I need to do some logic and decide what the initial value should be

---
I feel like those may be already possible using `alterTable` and `TableMigration`. But the only examples provided are only straightforward cases. The only more complex thing that I could find is here: https://github.com/simolus3/drift/discussions/1432

I think it would be very useful for the documentation to add a migration example (and unit test) that involves introducing a new column which is a transformation of other existing columns.

**Comment by simolus3** [comment]
> I feel like those may be already possible using `alterTable` and `TableMigration`.

Yup, but it's not easy to see without knowing about `COALESCE` in SQL. Essentially, you'll want to do

```dart
await m.alterTable(
  TableMigration(
    yourTable,
    columnTransformer: {
      yourTable.cC: coalesce([yourTable.cB, yourTable.CA])
    },
  )
)
```

Column transformers have to be single SQL expressions, we can't really do complex Dart transformations. I'll add an example covering more than one column though.

> I think it would be very useful for the documentation to add a migration example (and unit test)

I think this is covered by [verifying data integrity](https://drift.simonbinder.eu/docs/migrations/tests/#verifying-data-integrity) already, right? You'd create an instance of your database at the older version, insert two rows (one where `cB` is `NULL` and one where it isn't), call `migrateAndValidate` and do a select to verify you've gotten the correct result.
