### ISSUE TITLE
Ability to mark foreign key constraint as deferrable

### ISSUE THREAD

**Issue by Adam-Langley** [simolus3/moor#3020]
I wish to declare some foreign keys as deferrable.

I see that I can achieve this by switching from defining the keys using the '.references()' API - to overriding 'customConstraints()'
 - however this more complex and potentially more error prone (as it just accepts SQL).

I'd like to request an API enhancement to the 'reference()' function, to accept an optional enum (deferrable), DEFERRED or IMMEDIATE.

**Comment by simolus3** [comment]
I've added a boolean flag to generate the column as `DEFERRABLE INITIALLY DEFERRED` in the referenced commit.

By the way, `customConstraint` is not so dangerous anymore as the SQL is parsed and validated during the build. Still it's definitely better to have an official API for this though :)
