### ISSUE TITLE
Schema verifier fails in setting DatabaseConfig.doubleQuotedStringLiterals

### ISSUE THREAD

**Issue by gnprice** [simolus3/moor#3021]
When I run [my app](https://github.com/zulip/zulip-flutter)'s unit tests against current Drift from main, I get the following exception:
```
$ flutter test test/model/database_test.dart 
00:01 +3 -1: migrations upgrade to v2, empty [E]                                                        
  SqliteException(1): not an error, not an error (code 0)
  package:sqlite3/src/implementation/exception.dart 75:3          throwException
  package:sqlite3/src/implementation/database.dart 564:7          DatabaseConfigImplementation.setIntConfig
  package:sqlite3/src/database.dart 262:5                         DatabaseConfig.doubleQuotedStringLiterals=
  package:drift_dev/src/services/schema/verifier_impl.dart 63:21  VerifierImplementation._setupDatabase
  package:drift_dev/src/services/schema/verifier_impl.dart 74:24  VerifierImplementation.schemaAt
  package:drift_dev/src/services/schema/verifier_impl.dart 92:12  VerifierImplementation.startAt
  test/model/database_test.dart 102:41                            main.<fn>.<fn>
  

To run this test again: /home/greg/n/flutter/flutter/bin/cache/dart-sdk/bin/dart test /home/greg/z/flutterz/test/model/database_test.dart -p vm --plain-name 'migrations upgrade to v2, empty'
[…]
```

The latest release, 2.18.0, is fine. Bisecting, the issue was introduced in commit fde04bb154aeaeb9eaf03d196df62085478fd179, which looks like it was the fix for #3006.

My pubspec.lock shows the latest releases of `sqlite3` and `sqlite3_flutter_libs`, namely 2.4.3 and 0.5.22 respectively.

**Comment by gnprice** [comment]
It looks like this is probably caused by my having an old version of `libsqlite3.so`. The relevant SQLite feature looks to have been introduced in 3.29.0:
https://www.sqlite.org/changes.html#version_3_29_0

which is fairly old, from 2019. My local `libsqlite3.so` is a bit older than that, 3.27.2.

It's extremely reasonable for Drift to rely on SQLite features from 2019. It'd be good for that to be explicit, though.

Is there a minimum SQLite version documented somewhere? I'm not immediately finding one. Possibly https://drift.simonbinder.eu/docs/platforms/#desktop is the most relevant spot for that information.

Better yet, it would be great to get a clear error message to that effect, rather than a traceback when a particular operation that Drift tries to do turns out not to be supported.

**Comment by frankvollebregt** [comment]
The documentation page about testing does specify that you need to download the binaries yourself https://drift.simonbinder.eu/docs/testing/ but it also doesn't provide any guidance on a minimum version

**Comment by simolus3** [comment]
> It's extremely reasonable for Drift to rely on SQLite features from 2019. It'd be good for that to be explicit, though.

At the moment we don't have an official minimal sqlite3 version we support for `package:sqlite3` and drift's tooling. I think it would be great to pick a stable minimum version (and run tests against that as well). Since tests are currently running against either a fixed sqlite3 or the one shipping with the GitHub Actions Ubuntu runner, I can't reliably say which sqlite3 version is the lowest we can support.

I completely agree about having a clear error message as well, in this case I simply didn't consider that the database option may not have always been available - another thing that would be caught by tests.

**Comment by gnprice** [comment]
Sounds great — thank you!
