### ISSUE TITLE
Drift generator doesn't strip custom row class from SQL

### ISSUE THREAD

**Issue by FaFre** [simolus3/moor#3038]
**Describe the bug**

Following the docs https://drift.simonbinder.eu/docs/advanced-features/custom_row_classes/#existing-row-classes-in-drift-files I have following view:

```sql
CREATE VIEW bang_data_view WITH BangData AS
  SELECT
    b.*,
    bf.frequency,
    bi.icon_data
  FROM
    bang b
  LEFT JOIN
    bang_frequency bf ON b."trigger" = bf."trigger"
  LEFT JOIN
    bang_icon bi ON b."trigger" = bi."trigger";
```

I expect drift to use my custom row class `BangData`, which also works as expected. However, the `WITH BangData` is not stripped from the sql statement inside the generated file:
```dart
@override
  String get entityName => 'bang_data_view';
  @override
  Map<SqlDialect, String> get createViewStatements => {
        SqlDialect.sqlite:
            'CREATE VIEW bang_data_view WITH BangData AS SELECT b.*, bf.frequency, bi.icon_data FROM bang AS b LEFT JOIN bang_frequency AS bf ON b."trigger" = bf."trigger" LEFT JOIN bang_icon AS bi ON b."trigger" = bi."trigger"',
      };
```

This leads to an SQL error during migration.

**Comment by simolus3** [comment]
Thanks for the report, definitely an embarrassing bug that should have been covered by tests :grimacing:  

I've fixed this in the referenced commit, so it'll work in the next drift release.
