### ISSUE TITLE
Select based on month

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#304]
I have this column in database

` TextColumn get createdAt => text().named('created_at').nullable()();`

where the created_at is this format "2019-07-22T11:42:01.000+08:00".

I would like to  write a select query, to retrieve data where month are July and year is 2019. 

```
Future<List<ABC>> getData() {
    return (select(abcs)..where(...)   // where the month of created_at is July and Year is 2019
          ..orderBy([
            (t) =>
                OrderingTerm(expression: t.createdAt, mode: OrderingMode.desc)
          ]))
        .get();
  }
```

How should I write?

**Comment by simolus3** [comment]
You could use the builtin `date` function from sqlite. When using moor 2.1 or later, this would look like:
```dart
..where((row) {
  // call the date(createdAt) function in sqlite, which parses the time string
  final sqliteDate = FunctionCallExpression<DateTime, DateTimeType>('date', [row.createdAt]);
  return sqliteDate.year.equals(2019) & sqliteDate.month.equals(7);
})
```

**Comment by tony123S** [comment]
> You could use the builtin date function from sqlite

Mean create a DATETIME column?

**Comment by simolus3** [comment]
That would also work, yeah. But you don't need to change the table definition. You can convert the text to a date in sqlite (see https://www.sqlite.org/lang_datefunc.html), so it shouldn't be necessary to change the column definition.

**Comment by tony123S** [comment]
I read the link you sent, but I still have no idea. How can I use that date function inside moor?

**Comment by simolus3** [comment]
Moor doesn't have anything builtin that matches the `date` function directly. However, you can call arbitrary sqlite functions by using a `FunctionCallExpression`. So, to call `DATE(created_at)`, you can use the code from [above](https://github.com/simolus3/moor/issues/304#issuecomment-569647952). The `<DateTime, DateTimeType>` means that moor will expect the function to return a date time (which it does). Then, you just need to pass the function name and the parameters.

**Comment by tony123S** [comment]
Does version 2.0.1 available right now?

**Comment by tony123S** [comment]
```
 Future<ABC> selectReadingBasedOnMonth(
      String month, String year) {
    return (select(abcs)
      ..where((t) {
        final sqliteDate = FunctionCallExpression<DateTime, DateTimeType>(
            'date', [t.createdAt]);
        return sqliteDate.year.equals(year) & sqliteDate.month.equals(month);
      }));
  }
```

**Error**

> The method 'FunctionCallExpression' isn't defined for the class 'Dao'.\nTry correcting the name to the name of an existing method, or defining a method named 'FunctionCallExpression'.",
> 
> A value of type 'SimpleSelectStatement<$ABCTable, ABC> can't be returned from method 'selectReadingBasedOnMonth' because it has a return type of 'Future<ABC>'.",
>

**Comment by tony123S** [comment]
I used the above code, but no getting any data.
This is the query displayed in log

> I/flutter (12004): Moor: Sent SELECT * FROM abc WHERE (CAST(strftime("%Y", date(created_at), "unixepoch") AS INTEGER)) = ? AND (CAST(strftime("%m", date(created_at), "unixepoch") AS INTEGER)) = ?; with args [2019, 10]

**Comment by tony123S** [comment]
created_at is String format

**Comment by tony123S** [comment]
Is it because of the unixepoch ?

**Comment by simolus3** [comment]
You're right, it fails because of the "unixepoch". My solution doesn't work, sorry for causing confusion. I just tried this, which generates a correct query:
```dart
  final asDate = FunctionCallExpression('date', [row.createdAt]);
  final year = FunctionCallExpression<String, StringType>(
      'strftime', [const Constant<String, StringType>('%Y'), asDate]);
  final month = FunctionCallExpression<String, StringType>(
      'strftime', [const Constant<String, StringType>('%m'), asDate]);

  return year.equals('2019') & month.equals('07');
```

Note that `strftime` returns a string and that there's a leading 0 in the month.

**Comment by tony123S** [comment]
Hey, thanks again, but I still can't get the data.
Is the below query correct?
`I/flutter (21317): Moor: Sent SELECT * FROM organization_sensor_readings WHERE strftime('%Y', date(created_at)) = ? AND strftime('%m', date(created_at)) = ?; with args [Instance of 'FunctionCallExpression<String, StringType>', Instance of 'FunctionCallExpression<String, StringType>']`

**Comment by tony123S** [comment]
It works !!! Thanks again

**Comment by NaarGes** [comment]
hello I'm trying to get a stream of record which are in the same day of input (like all records with date of Feb 23, 2020).
my table attribute is DateTimeColumn and here is my method

```  Stream<List<BloodSugar>> watchBloodSugarsInDate(DateTime dateTime) {

    return (select(bloodSugarsEntity)
        ..where((row) {
          final asDate = FunctionCallExpression('date', [row.date]);
          final year = FunctionCallExpression<String, StringType>(
              'strftime', [const Constant<String, StringType>('%Y'), asDate]);
          final month = FunctionCallExpression<String, StringType>(
              'strftime', [const Constant<String, StringType>('%m'), asDate]);
          final day = FunctionCallExpression<String, StringType>(
            'strftime',  [const Constant<String, StringType>('%d'), asDate]);


          return year.equals(dateTime.year.toString()) & month.equals(dateTime.month.toString()) & day.equals(dateTime.day.toString());
        }))
        .map((bloodSugarsEntity) => convertEntityToModel(bloodSugarsEntity))
        .watch();
  }```

but it still doesn't work.

**Comment by simolus3** [comment]
@NaarGes What column type did you use for `BloodSugars.date`? If it's a `dateTime()` column, you can just do
```dart
..where((row) {
  final date = row.date;
  return date.year.equals(dateTime.year) & date.month.equals(dateTime.month) & date.day.equals(dateTime.day);
});
```

Also, can you give more details on "it still doesn't work"? Do you not get the results you expect, is there any exception, etc.

**Comment by NaarGes** [comment]
I've tried that, but it's not working too. I mean it returns error.
my query: 
```
Stream<List<BloodSugar>> watchBloodSugarsInDate2(DateTime dateTime) =>
      (select(bloodSugarsEntity)
            ..where((row) {
              final date = row.date;
              return date.year.equals(dateTime.year) &
                  date.month.equals(dateTime.month) &
                  date.day.equals(dateTime.day);
            }))
          .map((bs) => convertEntityToModel(bs))
          .watch();
```

and this is the error I see in debug mode:
![Screenshot from 2020-02-23 23-18-59](https://user-images.githubusercontent.com/15056339/75118867-28a05980-5693-11ea-8bca-c08a1b7438e2.png)

I've also tried flutter clean

**Comment by simolus3** [comment]
I just tried to reproduce your problem with [this gist](https://gist.github.com/simolus3/d9a18cec5b98f43f283e9664b08109af), but I don't get any sql errors, it works as intended. Do you have a different table structure?

**Comment by NaarGes** [comment]
No my date row is the same as yours.
Here is my table:
```
class BloodSugarsEntity extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get value => integer()();
  DateTimeColumn get date => dateTime()();
  TextColumn get type => text()();
}
```

I also insert data fetched from api server in my table, maybe that makes problem. This is my insert method:
```
  insertBloodSugarList(List<BloodSugar> bsList) {
    for (BloodSugar bs in bsList) {
      insertBloodSugar(BloodSugarsEntityCompanion(
        id: Value(bs.id),
        value: Value(bs.bloodSugar),
        type: Value(bloodSugarApiMeasureState[bs.measureState]),
        date: Value(bs.measureTime),
      ));
    }
  }
``` 
bs.measureTime type is DateTime and decodes using this:
`measureTime: DateTime.parse(json['measure_time']),` 

json['measure_time'] is in this format for example:  "2020-01-11T21:46:25Z"

**Comment by simolus3** [comment]
Sorry, still no luck. I've updated my repro [here](https://gist.github.com/simolus3/d9a18cec5b98f43f283e9664b08109af#file-repro-dart) - that should be very close to what you're using, right?

**Comment by NaarGes** [comment]
Yes, That's just like my code. I guess the error is where I'm trying to get `date.year`
I can use `date.isBetweenValues` and it works alright but when I try to get `year` out of `date` it throws 'no such column: %Y, SQL logic error`
Thank you anyway

**Comment by simolus3** [comment]
You could try enabling `logStatements` on `VmDatabase` or `FlutterQueryExecutor` - it will print the full sql statement before running it. It will be easier to debug this for me when I have the full statement.

And just to be sure, are you on the latest moor version (2.4.0)?

**Comment by NaarGes** [comment]
Yes I'm using latest version on moor and moor_ffi
I've enabled logStatement and here's the log:
I/flutter ( 3815): Moor: Sent SELECT * FROM blood_sugars_entity WHERE (CAST(strftime("%Y", date, "unixepoch") AS INTEGER)) = ? AND (CAST(strftime("%m", date, "unixepoch") AS INTEGER)) = ? AND (CAST(strftime("%d", date, "unixepoch") AS INTEGER)) = ?; with args [2020, 2, 25]

**Comment by simolus3** [comment]
Thanks, this helps a lot!

I just published moor version `2.4.1`, which should fix this problem.

**Comment by NaarGes** [comment]
Thank you for your very good support :+1: 
It's now working :)

**Comment by richard457** [comment]
how to implement something like this `select * from hockey_stats 
where game_date between '2012-03-11 00:00:00' and '2012-05-11 23:59:00' 
order by game_date desc;`

**Comment by simolus3** [comment]
@richard457 If you're using a `DateTime` column, something like this should work:
```dart
select(hockeyStats)
  ..where((row) => row.gameDate.isBetweenValues(..., ...))
  ..orderBy([(row) => OrderingTerm.desc(row.gameDate)])
```

**Comment by AabhasS** [comment]
> @richard457 If you're using a `DateTime` column, something like this should work:
> 
> ```dart
> select(hockeyStats)
>   ..where((row) => row.gameDate.isBetweenValues(..., ...))
>   ..orderBy([(row) => OrderingTerm.desc(row.gameDate)])
> ```

What if we have a TextColumn for date?

**Comment by simolus3** [comment]
You could use a  [`FunctionCallExpression`](https://pub.dev/documentation/moor/latest/moor_web/FunctionCallExpression-class.html) for this purpose. If the format you're storing your dates in is one of those [time strings](https://www.sqlite.org/lang_datefunc.html), the following should work:

```dart
extension MyDateTimeExtension on Expression<String, StringType> {
  Expression<DateTime, DateTimeType> asDateTime() {
    return FunctionCallExpression('strftime', ['%s', this]);
  }
}
```
You can then use `stringColumn.asDateTime()` just like `dateTimeColumn`.

**Comment by AabhasS** [comment]
> You could use a [`FunctionCallExpression`](https://pub.dev/documentation/moor/latest/moor_web/FunctionCallExpression-class.html) for this purpose. If the format you're storing your dates in is one of those [time strings](https://www.sqlite.org/lang_datefunc.html), the following should work:
> 
> ```dart
> extension MyDateTimeExtension on Expression<String, StringType> {
>   Expression<DateTime, DateTimeType> asDateTime() {
>     return FunctionCallExpression('strftime', [Constant<String, StringType>('%s'), this]);
>   }
> }
> ```
> 
> You can then use `stringColumn.asDateTime()` just like `dateTimeColumn`.

It works when:
 Expression<String,StringType> date = Constant<String,StringType>("2020-02-01 00:00:00.000");
row.gameDate.isBiggerThan(date.asDateTime()); 
But not when I do : 
date  = DateTime.parse("2020-02-01 00:00:00.000")
row.gameDate.isBiggerThan(date); 

Thanks for the help.

**Comment by simolus3** [comment]
>  row.gameDate.isBiggerThan(date);

You would have to use `isBiggerThanValue(date)` here since we can't overload methods in Dart.

**Comment by mad0309** [comment]
How could i do if i want to get a column null, for example something like this:
```
select(hockeyStats)
  ..where((row) => row.gameDate.isBetweenValues(..., ...) | row.gameDate.equals(null))
  ..orderBy([(row) => OrderingTerm.desc(row.gameDate)])
```
i put equals null but it doesn't return me anything.

**Comment by mad0309** [comment]
> How could i do if i want to get a column null, for example something like this:
> 
> ```
> select(hockeyStats)
>   ..where((row) => row.gameDate.isBetweenValues(..., ...) | row.gameDate.equals(null))
>   ..orderBy([(row) => OrderingTerm.desc(row.gameDate)])
> ```
> 
> i put equals null but it doesn't return me anything.

Solution:
```
select(hockeyStats)
  ..where((row) => row.gameDate.isBetweenValues(..., ...) | isNull(row.gameDate))
  ..orderBy([(row) => OrderingTerm.desc(row.gameDate)])
```
[https://github.com/simolus3/moor/issues/65](url)

**Comment by tony123S** [comment]
> > How could i do if i want to get a column null, for example something like this:
> > ```
> > select(hockeyStats)
> >   ..where((row) => row.gameDate.isBetweenValues(..., ...) | row.gameDate.equals(null))
> >   ..orderBy([(row) => OrderingTerm.desc(row.gameDate)])
> > ```
> > 
> > 
> > i put equals null but it doesn't return me anything.
> 
> Solution:
> 
> ```
> select(hockeyStats)
>   ..where((row) => row.gameDate.isBetweenValues(..., ...) | isNull(row.gameDate))
>   ..orderBy([(row) => OrderingTerm.desc(row.gameDate)])
> ```
> 
> [https://github.com/simolus3/moor/issues/65](url)

Are you pasting the correct link?

**Comment by mad0309** [comment]
> > > How could i do if i want to get a column null, for example something like this:
> > > ```
> > > select(hockeyStats)
> > >   ..where((row) => row.gameDate.isBetweenValues(..., ...) | row.gameDate.equals(null))
> > >   ..orderBy([(row) => OrderingTerm.desc(row.gameDate)])
> > > ```
> > > 
> > > 
> > > i put equals null but it doesn't return me anything.
> > 
> > 
> > Solution:
> > ```
> > select(hockeyStats)
> >   ..where((row) => row.gameDate.isBetweenValues(..., ...) | isNull(row.gameDate))
> >   ..orderBy([(row) => OrderingTerm.desc(row.gameDate)])
> > ```
> > 
> > 
> > [https://github.com/simolus3/moor/issues/65](url)
> 
> Are you pasting the correct link?

Sorry this is the correct link
https://github.com/simolus3/moor/issues/65#issuecomment-509175940

**Comment by tony123S** [comment]
@simolus3  Not sure why it not working anymore.

I storing `updatedAt` as a `String`

`2021-02-22T01:18:22.000+08:00`

Here my select query

```
Future<List<OrganizationSensorReading>> selectReadingBasedOnMonth(
      String months, int years, int organId) {
    return (select(organizationSensorReadings)
          ..where((t) {
            final asDate = FunctionCallExpression('date', [t.updatedAt]);
            final year = FunctionCallExpression(
                'strftime', [const Constant('%Y'), asDate]);
            final month = FunctionCallExpression(
                'strftime', [const Constant('%m'), asDate]);
            return year.equals(years.toString()) &
                month.equals(months) &
                t.organizationSensorId.equals(organId);
          }))
        .get();
  }
```

**Error**

Bad state: Too many elements

**Comment by tony123S** [comment]
fixed 
https://github.com/simolus3/moor/issues/1063
