### ISSUE TITLE
How to initialize the database without the constructor syntax

### ISSUE THREAD

**Issue by softlore** [simolus3/moor#3058]
Hi team

I am trying to create a reusable database project for my project.

- mobile
- desktop
- database

The idea is that the reusable database project will be used in both desktop & mobile app. User will be able to select a different path to store the database(this will have the all the required table schemas)

Once it is done, I am planning to create a REST API in the desktop to sync data between the 2 databases. I may change the project architecture later in future but first I would like to go with this approach.

Can you please share an example where I can lazy initalize the database object?

```dart
class DatabaseBase {
  static final DatabaseBase _singleton =
      DatabaseBase._internal();

  factory DatabaseBase() {
    return _singleton;
  }

  DatabaseBase._internal();

  init(String dbPath) {
    // how to initialize database
  }
}
```

Thanks in advance.

**Comment by simolus3** [comment]
What does "initializing the database" mean here? Opening it and creating tables? You can open the database instance and run a simple query to ensure that drift will set everything up. That has to be asynchronous though:

```dart
Future<void> init(String dbPath) async {
 final db = YourDatabaseClass(queryExecutorFor(dbPath));
 await db.customSelect('SELECT 1').get(); // use the database, ensuring all tables have been set up.
}
```

**Comment by softlore** [comment]
thanks @simolus3
