### ISSUE TITLE
Schema migration helper fails when there are no migrations yet

### ISSUE THREAD

**Issue by dhoskins** [simolus3/moor#3064]
The command ```$ dart run drift_dev schema steps drift_schemas/ lib/database/schema_versions.dart``` as described [here](https://drift.simonbinder.eu/docs/migrations/step_by_step/) generates invalid Dart in the event that there are no schema migrations yet.

If your database is on version `1` and there are no migrations yet specified, the above command generates `schema_versions.dart` as follows:

```
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart';// ignore_for_file: type=lint,unused_import
// GENERATED BY drift_dev, DO NOT MODIFY.
i0.MigrationStepWithVersion migrationSteps({}) {
return (currentVersion, database) async {
switch (currentVersion) {
default: throw ArgumentError.value('Unknown migration from $currentVersion');
}
};
}
i1.OnUpgrade stepByStep({}) => 
i0.VersionedSchema.stepByStepHelper(step: migrationSteps());
```

The `{}` on lines 5 and 12 should not be there.

Obviously this command is not necessary if there are not yet any migrations, however ideally this would work as a pipeline on a new project, ready for when migrations are added.

**Comment by simolus3** [comment]
Good catch, thanks for the report!
