### ISSUE TITLE
drift_flutter package doesn't exist

### ISSUE THREAD

**Issue by dvdmc** [simolus3/moor#3071]
When trying to run the example, the package drift_flutter is not found. Thus, `flutter pub get` can't be executed.

**Comment by simolus3** [comment]
The `drift_flutter` package has been added very recently to simplify the setup, I haven't released it yet (I'll do that with the next drift release, hopefully soon).

You can use the tree from [an earlier commit](https://github.com/simolus3/drift/tree/59c1a08dee66a923ccda0fdc0a289c6c1b18a1c4/examples/app) to get a running example that doesn't depend on `drift_flutter` yet.

**Comment by AlexBolot** [comment]
For others that struggle with the "Setup" page of the website, I'm currently using Web Archive to access the previous version, without `drift_flutter` 😉 

https://web.archive.org/web/20240606182824/https://drift.simonbinder.eu/docs/getting-started/

**Comment by simolus3** [comment]
Well that's embarrassing, I can't believe I forgot to publish :facepalm: I've just published `drift_flutter` to pub.dev.
