### ISSUE TITLE
Missing `extensions` Import in Generated Code

### ISSUE THREAD

**Issue by toe-lie** [simolus3/moor#3079]
I'm encountering an issue with the drift package where the extensions import is missing from the generated code. After manually importing it, the error is resolved.

When I run the app, got the following error and,

![image](https://github.com/simolus3/drift/assets/11496493/943e8435-f561-4638-b863-c59522b57964)

When I check the generated drift.dart file, I noticed that extensions package is not imported and after I imported manually, the error is gone.

I'm not sure because of my implementation or the issue in lib.

Code for table declaration is
![image](https://github.com/simolus3/drift/assets/11496493/56b178f9-700b-497d-9e07-f0b6c4a86b1b)

The generated code is
![image](https://github.com/simolus3/drift/assets/11496493/eb73b615-d325-4c41-8223-46d1e5249359)

The configuration in build.yaml is the same as in the documentation found at https://drift.simonbinder.eu/docs/generation-options/modular/.
![image](https://github.com/simolus3/drift/assets/11496493/866b3e17-6d15-4e17-8968-711b278c2f3e)

**Comment by simolus3** [comment]
Thanks for the report! I have fixed this in 0a2e0e9a3f2dcd2c3bb0d7abefe6e9ce39d088b1, so the next `drift_dev` version will generate the correct code here.
In the meantime, you can work around this issue by explicitly mentioning the extension:

```dart
  TextColumn get farmId =>
      text().generatedAs(JsonExtensions(farm).jsonExtract(r'$.id'))();
```
