### ISSUE TITLE
android::register_android_database_SQLiteConnection Android Crash

### ISSUE THREAD

**Issue by FantaMagier** [simolus3/moor#3081]
**Describe the bug**

Hi some Android User get the following Bug / Crash: 

android::register_android_database_SQLiteConnection

libandroid_runtime
+0x0d1da8
android::register_android_database_SQLiteConnection

Is this Linked to a Drift or a native Android SQLite Problem? Unfortunately I only see my Sentry Crash but can't reproduce it.

  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  sqlite3: ^2.4.4
  drift_db_viewer: ^2.1.0

My OpenConnection: 
```dart
LazyDatabase _openConnection() {
  // the LazyDatabase util lets us find the right location for the file async.
  return LazyDatabase(() async {
    // put the database file, called db.sqlite here, into the documents folder
    // for your app.
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));

    // Also work around limitations on old Android versions
    if (Platform.isAndroid) {
      await applyWorkaroundToOpenSqlite3OnOldAndroidVersions();
    }

    // Make sqlite3 pick a more suitable location for temporary files - the
    // one from the system may be inaccessible due to sandboxing.
    final cachebase = (await getTemporaryDirectory()).path;
    // We can't access /tmp on Android, which sqlite3 would try by default.
    // Explicitly tell it about the correct temporary directory.
    sqlite3.tempDirectory = cachebase;

    return NativeDatabase.createInBackground(file);
  });
}
```

Newest

OS Version: Android 10 (QP1A.190711.020.J600FNXXSACVB1)
Report Version: 104

Exception Type: Unknown (SIGSEGV)

Application Specific Information:
Segfault

Thread 0 Crashed:
0   libandroid_runtime.so           0xeda56da8          android::register_android_database_SQLiteConnection
1   boot-framework.oat              0x709a1c83          <unknown> + 1889148035

EOF

**Comment by simolus3** [comment]
Do they get this consistently or is this a rare occurrence? I don't think it's a drift issue though - we're not using Android's sqlite3 API at all with `NativeDatabase`. Even `applyWorkaroundToOpenSqlite3OnOldAndroidVersions()` only calls `System.loadLibrary("sqlite3");` without interacting with it. Everything is happening in Dart using with direct FFI bindings to a custom `libsqlite3.so` build not shipped with Android.

**Comment by FantaMagier** [comment]
Maybe I used code to stop Google tracking from their SDKs: I think this code occured the crash. I will remove that. Thanks for your quick help!

```dart 
 if (Platform.isAndroid) {
        final dir = await getApplicationDocumentsDirectory();
        final path = dir.parent.path;
        final file = File('$path/databases/com.google.android.datatransport.events');
        await file.writeAsString('Fake');
      }
```
