### ISSUE TITLE
Adding unique key that is case-insensitive

### ISSUE THREAD

**Issue by kedarkarkee** [simolus3/moor#3087]
When using uniqueKeys as below, it is letting me insert two rows with same type and same name but in different cases. I want to add unique constraint that should not allowing inserting same name regardless of CASE

```dart
  @override
  List<Set<Column<Object>>>? get uniqueKeys => [
        {
          name,
          type,
        }
      ];
```

I tried using customConstraints but it is giving me SQLITEException

```dart
  @override
  List<String> get customConstraints => [
        'UNIQUE (lower(name), type)',
      ];
```

throws 
```
SqliteException(1): while executing, expressions prohibited in PRIMARY KEY and UNIQUE constraints, SQL logic error (code 1)
```

I can't even return ```name.lower()``` in either uniqueKeys or TableIndex as it gives me Expression but drift wants Column. How to solve it?

**Comment by simolus3** [comment]
> while executing, expressions prohibited in PRIMARY KEY and UNIQUE constraints

As the error message indicates, that's not supported by sqlite3. This is also mentioned in [the documentation](https://sqlite.org/lang_createtable.html#unique_constraints): "As with PRIMARY KEYs, a UNIQUE [table-constraint](https://sqlite.org/syntax/table-constraint.html) clause must contain only column names — the use of expressions in an [indexed-column](https://sqlite.org/syntax/indexed-column.html) of a UNIQUE [table-constraint](https://sqlite.org/syntax/table-constraint.html) is not supported."

It seems to work with generated columns though:

```dart
  TextColumn get lowercaseName => text().generatedAs(name.lower())();

  @override
  List<Set<Column<Object>>>? get uniqueKeys => [
        {lowercaseName, type}
      ];
```
