### ISSUE TITLE
[WEB] Can't run a transaction inside `exclusively` 

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#3089]
**Describe the bug**

I'm trying out the new `exclusively` feature and it seems to be failing on web when running a drift transaction inside a `exclusively` block.
On a VM environment it works correctly. 

```dart
await db.exclusively(() async {
  await db.transaction(() async {
    ...
  });
});
```

**Comment by simolus3** [comment]
Thanks for the report! I've fixed this in drift version 2.19.1, you'll need [a new worker though](https://github.com/simolus3/drift/releases/tag/drift-2.19.1).
