### ISSUE TITLE
404 link in QueryExecutor class documentation

### ISSUE THREAD

**Issue by curiouslaw** [simolus3/moor#3091]
**404 in one of the mention link**

In the QueryExecutor documentation here: https://github.com/simolus3/drift/blob/7449479e8d874ab4310ad5c2158083d125657dc6/drift/lib/src/runtime/executor/executor.dart#L10-L14

The link from [NativeDatabase implementation] lead to 404.

**Comment by simolus3** [comment]
Thanks for the report, fixed in 820a79cc0b17a38c6b373d106cf6c58bb2f5a478.
