### ISSUE TITLE
Renew DriftDatabase usage example

### ISSUE THREAD

**Issue by curiouslaw** [simolus3/moor#3092]
When reading the DriftDatabase class documentation, the description stated QueryExecutor but the example refer to old Moor class (FlutterQueryExecutor). Here is the documentation link: https://github.com/simolus3/drift/blob/7449479e8d874ab4310ad5c2158083d125657dc6/drift/lib/src/dsl/database.dart#L7-L17

With that being said, it might be good to renew the example on the DriftDatabase class usage.

**Comment by simolus3** [comment]
Thanks for the report! I've updated the docs in cd06d69f236178b2901dbf300cefd8066027e6c0.
