### ISSUE TITLE
Unhandled Exception: Bad state: Tried to send Request ... over isolate channel, but the connection was closed!

### ISSUE THREAD

**Issue by Unbreathable** [simolus3/moor#3094]
Hello, first of all thank you for all your amazing work with Drift. It's been a really great experience working with this package and thanks for providing us with such great ORM features on top of your already amazing work to get sqlite to work with Flutter!

**Describe the bug**

I don't know if this is even a bug or just something new with ``sqlite``, but every time I try to query something with "profile" in the where clause the database connection just suddenly breaks. I don't know what it is, but every other query works fine. Only if I query something with profile. The issue here is that I use profile in my settings table as a sort of key value store for getting the tokens of the account that's currently logged in (I know not a perfect solution but it works). I don't know why this suddenly happens, but I literally woke up today and it didn't work anymore. After updating the package to the latest version (2.19.1) the issue was still present.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Tried to send Request (id = 49): StatementMethod.select: SELECT * FROM "setting" WHERE "key" = ?; with [profile] over isolate channel, but the connection was closed!
```

I've also tried with other tabes and I get the same exact thing across the board. No matter what table I query, if I query a string value for "profile" I always get the error. It's really weird. That's why I'm asking you if there's something I'm missing here.

**Comment by Unbreathable** [comment]
Okay, I actually don't know what's going on anymore. I just restarted my PC and the issue is gone. What the heck. I'll just leave this here for documentation purposes but yeah. One of the weirdest issues I've ever encountered.

**Comment by simolus3** [comment]
> something with "profile" in the where clause the database connection just suddenly breaks

Just to be sure - not "profile" as a double-quoted string literal right? As a column it should be fine, but double-quoted string literals are disabled by `sqlite3_flutter_libs`.

Given that it doesn't occur anymore after a restart it may also be something peculiar on your system. If it happens again, can you try running your app with this database setup?

```dart
DatabaseConnection.delayed(Future(() async {
  final isolate = await DriftIsolate.spawn(() => NativeDatabase.memory());
  return await isolate.connect(
    isolateDebugLog: true,
    singleClientMode: true,
  );
}))
```

You can pass that to the super constructor of the generated database class. It will use an in-memory database then, but give detailed logs about the individual operations sent to the isolate and what exactly came back. Perhaps that provides more information to help track this down.

**Comment by Unbreathable** [comment]
After doing some more testing, the problem seems to be gone now, I have feeling it had something to do with the fact that I also have a table with the name profile.

Also I'm not using the double quotes in the actual name, just when creating the string in Dart like this ``"profile"`` and I think that should be fine since ' and " are interchangeable and do the exact same thing (at least as far as I know).

I'm just going to close this and if this ever happens again I'll look into it more and do a lot more research and also try out the code you recommended. This is just a weirdly complex issue and I have a feeling that if it's a bug it's more something to do with sqlite itself and not drift. But I can't replicate the issue anymore after renaming the key at this point, so that's why I'm closing it.
