### ISSUE TITLE
DevTools extension not working in 2.19.1

### ISSUE THREAD

**Issue by kuhnroyal** [simolus3/moor#3095]
**Describe the bug**

DevTools extensions was working for me in 2.18.0, after the update to 2.19.1 the DevTools only display an error.

> could not read file as String: /Users/USERNAME/fvm/versions/3.22.2/bin/cache/dart-sdk/bin/resources/devtools/devtools_extensions/drift/index.html

Is anyone else experiencing this?

**Comment by simolus3** [comment]
Thanks for the report! I can confirm that I've messed up the extension build with the 2.19.1 release, the `index.html` file is missing from the package.

I've re-released drift as version `2.19.1+1`, which fixes the issue.
