### ISSUE TITLE
[Question] Is there a way to define column mapping for (de)serialization

### ISSUE THREAD

**Issue by Venusdjinni** [simolus3/moor#310]
I want to define my column in a form like "myColumn" but map it both in database and json by "my_column". I'm already using the named method to achieve it in the db side but I am wondering if there's a way to do the same in serialization process.

**Comment by simolus3** [comment]
You can use the `JsonKey` annotation for this:
```dart
class Users extends Table {
  IntColumn get id => integer().autoIncrement()();
  @JsonKey('user_name')
  TextColumn get name => text().nullable()();
}
```
