### ISSUE TITLE
Setup doc contains unexecutable code. 

### ISSUE THREAD

**Issue by Gj1337** [simolus3/moor#3104]
**Describe the bug**

Setup page shows example, which won't work.

Code blocks which show `AppDatabase` initialisation try to call class method during initialisation.
[link to place with bug](https://drift.simonbinder.eu/docs/getting-started/#:~:text=()%20%3A%20super(-,_openConnection(),-)%3B%0A%0A%20%20%40override)

<img width="700" alt="Screenshot 2024-07-20 at 18 16 53" src="https://github.com/user-attachments/assets/f7f91a5c-406c-4db0-aa48-3884ffa8284d">

also for Flutter example `_openConnection` method should return `QueryExecutor` instead of `DatabaseConnection`
as it `driftDatabase` does. 

**Possible solutions**

1) Make `_openConnection` method static.
2) Take the method out of class.
3) Put `driftDatabase(name: 'my_database')` or other `QueryExecutor`s into `super` directly.

**Comment by simolus3** [comment]
Thanks for the report! I've fixed this in 5dd93e2a3e838b00bfa1fbd02ad025832a4c35bf, the public site will get updated with the next drift release.

**Comment by Gj1337** [comment]
Sorry, haven't checked dev brach. >_<

**Comment by simolus3** [comment]
No problem, it was broken everywhere at the time you've reported it :)
