### ISSUE TITLE
Potential OOM error on both Android & iOS

### ISSUE THREAD

**Issue by btrautmann** [simolus3/moor#3110]
### Context

In investigating https://github.com/simolus3/drift/issues/3099, I ran into this issue. Note that _this_ bug does not actually throw a `SqliteException` in my experience, it's a pure OOM issue.

### Description
My app has an import feature by which you can import some JSON that was previously exported by the same app to restore data (e.g on a new device). The code is not complex (will post below), but there are some cases where an OOM can be reproduced 100% reliably after importing the data and then modifying the imported data. **Importantly, once the app crashes due to OOM it can not be restarted without reinstalling.**

**The thing that sticks out to me is that _before_ performing the modification action which causes the OOM error, the memory snapshot looks normal (I mostly see my app's objects). But AFTER performing the modification action that causes the OOM error, the memory snapshot is filled up with instances of Drift objects. I'm wondering if this helps identify a potential root cause.**

### Memory snapshot

<img width="986" alt="Screenshot 2024-07-23 at 08 45 05" src="https://github.com/user-attachments/assets/22647c4a-9059-404f-94d8-0e7ee309f189">

### Import code

```dart
Future<bool> import({
  required ExportPayloadV1 payload,
}) async {
  return await transaction(() async {
    await delete(dbCategoryViews).go();
    await delete(dbQuerySpendTrackers).go();
    for (final view in payload.categoryViews) {
      await insertCategoryView(
        name: view.name,
        budgetId: view.budgetId,
        categoryIds: view.categoryIds,
        categoryGroupIds: view.categoryGroupIds,
        isDeleted: view.isDeleted,
      );
    }
    for (final tracker in payload.queriedSpendTrackers) {
      await insertQueriedSpendTracker(
        name: tracker.name,
        budgetId: tracker.budgetId,
        condition: tracker.condition,
        nickName: tracker.nickName,
        isDeleted: tracker.isDeleted,
      );
    }
    return true;
  });
}
```

_Note that the `insertQueriedSpendTracker` code is fairly complex (and I'm happy to post it) but this bug is reproducible when the import contains _no_ queried spend trackers, so I'm confident that's not the issue._

The `insertCategoryView` code is simple:

```dart
Future<int> insertCategoryView({
  required String name,
  required String budgetId,
  required List<String> categoryIds,
  required List<String> categoryGroupIds,
  bool isDeleted = false,
}) {
  return transaction(() async {
    final id = await into(dbCategoryViews).insert(
      DbCategoryViewsCompanion.insert(
        name: name,
        budgetId: budgetId,
        isDeleted: isDeleted,
      ),
    );
    for (final categoryId in categoryIds) {
      await into(dbCategoryViewCategories).insert(
        DbCategoryViewCategoriesCompanion.insert(
          categoryViewId: id,
          categoryId: categoryId,
        ),
      );
    }
    for (final categoryGroupId in categoryGroupIds) {
      await into(dbCategoryViewCategoryGroups).insert(
        DbCategoryViewCategoryGroupsCompanion.insert(
          categoryViewId: id,
          categoryGroupId: categoryGroupId,
        ),
      );
    }
    return id;
  });
}
```

Once the OOM issue occurs, I see errors similar to the ones shown in https://github.com/flutter/flutter/issues/109512, but this has nothing to do with rendering large text. AFAICT it's definitely related to drift.

The JSON I'm using to reliably reproduce this issue is simple:

```javascript
{
    "queriedSpendTrackers": [],
    "categoryViews": [
        {
            "id": 2,
            "name": "Main View",
            "budgetId": "95b4c93f-5972-453b-a759-18829b2d9e4a",
            "categoryGroupIds": [
                "4b3cf2dc-a91c-4074-ae10-b6fe74876d35"
            ],
            "categoryIds": [
                "1e3ca5cf-52ae-4c10-8001-31a8b0f750dd",
                "2de185af-112b-4628-92e7-e0d9e9544270",
                "4add0664-ff15-445a-9708-f744a6b71aa5",
                "68cc7473-b6f2-48e4-84ee-b501c6483e83",
                "837bfff3-0ac5-4ebd-a1d8-ef74e28fa0bd",
                "8ad4e9a9-a632-40b7-b7f6-d60e3342bb7f",
                "a0fba53b-f579-44ce-a419-45c8a4723ed2",
                "aeae2b3c-1ea1-4b67-9ace-2e71df7405e0",
                "afb919d4-a701-4d91-8e9c-5f7050b148b3",
                "c33fb940-0193-4675-b662-39ddb1c9fda0",
                "c4d5846c-4b92-4fd0-8143-7a0092f4d2a6",
                "ced10f9b-bd4a-4d39-bebd-76edb4dffd60",
                "d7e54083-dd3d-4429-a5e2-dd69f3b03bb9",
                "f1f5458e-89fd-4b35-b072-4bf1770215f9"
            ],
            "isDeleted": false
        }
    ]
}
```

**Comment by simolus3** [comment]
All of the `Variable` objects (and the `GenerationContext`s and related classes as well) should be GCed after completing the operation, so this looks like a drift issue.

To understand the memory profiler screenshot you've posted, was the batch insert part of the graph there or is it all afterwards? It's bad that the 1.5k variables didn't get collected, but I'd also be surprised to see 35 MB causing an OOM error.

**Comment by btrautmann** [comment]
> All of the Variable objects (and the GenerationContexts and related classes as well) should be GCed after completing the operation, so this looks like a drift issue.

So this does actually seem to happen (see attached recording).

> To understand the memory profiler screenshot you've posted, was the batch insert part of the graph there or is it all afterwards? It's bad that the 1.5k variables didn't get collected, but I'd also be surprised to see 35 MB causing an OOM error.

Yeah agreed.. Attached a recording to better show what's happening. As it happens, logs print messages along the lines of `The process has exhausted 256M for size class 2096.` similar to the attached flutter issue in the issue description.

https://github.com/user-attachments/assets/e65a3b1b-f9dc-4a24-9456-ba671fb40119

**Comment by btrautmann** [comment]
Based on those objects being GC'd I wonder if this points to drift at all. I can't fathom why the import would cause this, but if nothing sticks out to you here I think we may be able to close this until I can better isolate a root cause 🤔

**Comment by btrautmann** [comment]
OK, back with more logs:

<details><summary>Console logs</summary>

```console
I/scudo   (30159): Stats: SizeClassAllocator64: 288M mapped (0M rss) in 2121892 allocations; remains 1509795
I/scudo   (30159):   00 (    64): mapped:    256K popped:   28795 pushed:   27183 inuse:   1612 total:   2548 rss:      0K releases:      0 last released:      0K region: 0x725e457000 (0x725e44c000)
I/scudo   (30159):   01 (    32): mapped:   1792K popped:  290298 pushed:  239781 inuse:  50517 total:  51440 rss:      0K releases:      0 last released:      0K region: 0x729e456000 (0x729e44c000)
I/scudo   (30159):   02 (    48): mapped:   1024K popped:  146424 pushed:  126469 inuse:  19955 total:  20592 rss:      0K releases:      0 last released:      0K region: 0x71ae45c000 (0x71ae44c000)
I/scudo   (30159):   03 (    64): mapped:   1280K popped:   56131 pushed:   42810 inuse:  13321 total:  17424 rss:      0K releases:      0 last released:      0K region: 0x718e459000 (0x718e44c000)
I/scudo   (30159):   04 (    80): mapped:    768K popped:   17293 pushed:   10481 inuse:   6812 total:   6864 rss:      0K releases:      0 last released:      0K region: 0x71be457000 (0x71be44c000)
I/scudo   (30159):   05 (    96): mapped:   1024K popped:   33796 pushed:   30557 inuse:   3239 total:   8868 rss:      0K releases:      0 last released:      0K region: 0x720e452000 (0x720e44c000)
I/scudo   (30159):   06 (   112): mapped:    256K popped:   16130 pushed:   14349 inuse:   1781 total:   2080 rss:      0K releases:      0 last released:      0K region: 0x727e45a000 (0x727e44c000)
I/scudo   (30159):   07 (   144): mapped:    768K popped:   25524 pushed:   22911 inuse:   2613 total:   3692 rss:      0K releases:      0 last released:      0K region: 0x716e44f000 (0x716e44c000)
I/scudo   (30159):   08 (   176): mapped:    768K popped:    9641 pushed:    7807 inuse:   1834 total:   3290 rss:      0K releases:      0 last released:      0K region: 0x723e45a000 (0x723e44c000)
I/scudo   (30159): F 09 (   192): mapped: 261888K popped: 1429058 pushed:   32322 inuse: 1396736 total: 1396736 rss:      0K releases:      4 last released:     52K region: 0x714e457000 (0x714e44c000)
I/scudo   (30159):   10 (   224): mapped:    768K popped:   19438 pushed:   16916 inuse:   2522 total:   2600 rss:      0K releases:      0 last released:      0K region: 0x715e45c000 (0x715e44c000)
I/scudo   (30159):   11 (   288): mapped:    512K popped:    6214 pushed:    5330 inuse:    884 total:   1170 rss:      0K releases:    127 last released:     20K region: 0x717e44d000 (0x717e44c000)
I/scudo   (30159):   12 (   352): mapped:    512K popped:    4206 pushed:    3488 inuse:    718 total:   1108 rss:      0K releases:    128 last released:      4K region: 0x70ee45b000 (0x70ee44c000)
I/scudo   (30159):   13 (   448): mapped:    512K popped:    1494 pushed:     870 inuse:    624 total:    637 rss:      0K releases:      6 last released:      8K region: 0x711e45b000 (0x711e44c000)
I/scudo   (30159):   14 (   592): mapped:   1536K popped:   17433 pushed:   15714 inuse:   1719 total:   2370 rss:      0K releases:    424 last released:     24K region: 0x71ee453000 (0x71ee44c000)
I/scudo   (30159):   15 (   800): mapped:    768K popped:    1155 pushed:     450 inuse:    705 total:    735 rss:      0K releases:    126 last released:     24K region: 0x70ce458000 (0x70ce44c000)
I/scudo   (30159):   16 (  1104): mapped:   2560K popped:    6752 pushed:    4960 inuse:   1792 total:   2305 rss:      0K releases:    426 last released:    356K region: 0x724e45a000 (0x724e44c000)
I/scudo   (30159):   17 (  1648): mapped:   1536K popped:    1255 pushed:     588 inuse:    667 total:    811 rss:      0K releases:    141 last released:    200K region: 0x70fe44d000 (0x70fe44c000)
I/scudo   (30159):   18 (  2096): mapped:   1536K popped:    1517 pushed:    1109 inuse:    408 total:    685 rss:      0K releases:    245 last released:    152K region: 0x713e453000 (0x713e44c000)
I/scudo   (30159):   19 (  2576): mapped:    256K popped:    1051 pushed:     991 inuse:     60 total:     84 rss:      0K releases:    163 last released:     28K region: 0x71de44e000 (0x71de44c000)
I/scudo   (30159):   20 (  3120): mapped:   1024K popped:     316 pushed:      48 inuse:    268 total:    276 rss:      0K releases:    231 last released:     16K region: 0x71ce451000 (0x71ce44c000)
I/scudo   (30159):   21 (  4112): mapped:   1536K popped:    5322 pushed:    5005 inuse:    317 total:    330 rss:      0K releases:    345 last released:     12K region: 0x726e458000 (0x726e44c000)
I/scudo   (30159):   22 (  4624): mapped:    768K popped:     381 pushed:     212 inuse:    169 total:    169 rss:      0K releases:    129 last released:     16K region: 0x70be45c000 (0x70be44c000)
I/scudo   (30159):   23 (  7120): mapped:   2048K popped:    1159 pushed:     923 inuse:    236 total:    261 rss:      0K releases:   1000 last released:    152K region: 0x721e453000 (0x721e44c000)
I/scudo   (30159):   24 (  8720): mapped:   1024K popped:     136 pushed:      54 inuse:     82 total:     98 rss:      0K releases:    157 last released:    120K region: 0x722e44d000 (0x722e44c000)
I/scudo   (30159):   25 ( 11664): mapped:    768K popped:     129 pushed:     112 inuse:     17 total:     56 rss:      0K releases:    163 last released:    424K region: 0x71fe44f000 (0x71fe44c000)
I/scudo   (30159):   26 ( 14224): mapped:   1024K popped:     156 pushed:     100 inuse:     56 total:     59 rss:      0K releases:    146 last released:     56K region: 0x709e456000 (0x709e44c000)
I/scudo   (30159):   27 ( 16400): mapped:    512K popped:      25 pushed:       8 inuse:     17 total:     19 rss:      0K releases:    116 last released:     24K region: 0x712e457000 (0x712e44c000)
I/scudo   (30159):   28 ( 18448): mapped:    512K popped:      35 pushed:      17 inuse:     18 total:     26 rss:      0K releases:    251 last released:    184K region: 0x728e456000 (0x728e44c000)
I/scudo   (30159):   29 ( 23056): mapped:    512K popped:      71 pushed:      54 inuse:     17 total:     19 rss:      0K releases:    226 last released:     68K region: 0x70de44e000 (0x70de44c000)
I/scudo   (30159):   30 ( 29456): mapped:    512K popped:     443 pushed:     430 inuse:     13 total:     16 rss:      0K releases:    118 last released:    140K region: 0x70ae454000 (0x70ae44c000)
I/scudo   (30159):   31 ( 33296): mapped:   1024K popped:      43 pushed:      25 inuse:     18 total:     27 rss:      0K releases:    236 last released:    288K region: 0x710e45b000 (0x710e44c000)
I/scudo   (30159):   32 ( 65552): mapped:   3328K popped:      71 pushed:      23 inuse:     48 total:     51 rss:      0K releases:    118 last released:    192K region: 0x719e45c000 (0x719e44c000)
I/scudo   (30159): Scudo OOM: The process has exhausted 256M for size class 192.
E/FrameTracker(30159): force finish cuj, time out: J<IME_INSETS_ANIMATION::1@1@com.brandontrautmann.lumy>
E/FrameTracker(30159): force finish cuj, time out: J<IME_INSETS_ANIMATION::0@1@com.brandontrautmann.lumy>
E/FrameTracker(30159): force finish cuj, time out: J<IME_INSETS_ANIMATION::1@1@com.brandontrautmann.lumy>
E/FrameTracker(30159): force finish cuj, time out: J<IME_INSETS_ANIMATION::0@1@com.brandontrautmann.lumy>
E/FrameTracker(30159): force finish cuj, time out: J<IME_INSETS_ANIMATION::1@1@com.brandontrautmann.lumy>
5
E/DartVM  (30159): Exhausted heap space, trying to allocate 48 bytes.
E/DartVM  (30159): Exhausted heap space, trying to allocate 64 bytes.
```

</details>

One thing I find very interesting is that when doing some testing, I noticed this:

```console
E/flutter (29649): [ERROR:flutter/runtime/dart_isolate.cc(1291)] Out of memory
```

Because it had something to do with isolates, I tried to run drift _without_ isolate (using the standard `NativeDatabase` constructor). Upon doing so, the same types of logs (above) printed out but the isolate message did _not_ print. I'm wondering if that gives any further evidence that drift may be doing something weird here.

I also slimmed down the `import` function to ONLY import category views, and to even stub out some of the information from the import, using hard-coded values where possible:

```dart
for (final view in payload.categoryViews) {
  await insertCategoryView(
    name: 'Fake Name',
    budgetId: view.budgetId,
    categoryIds: [view.categoryIds.first],
    categoryGroupIds: [],
    isDeleted: false,
  );
}
// Not importing spend trackers. The above is still done in a transaction.
```

**Comment by btrautmann** [comment]
OK, more updates:

After being unsuccessful in trying to figure out exactly why this was happening, I started playing around with my production build on my physical device. I imported a JSON file I've had from my personal account (not the one in the issue description) and was able to go through the reproduction steps without any issues. I then imported the one in the issue description (the problem one) and it reproduces easily. I checked Sentry and saw this issue came up 3 times:

![Screenshot 2024-07-25 at 06 36 59](https://github.com/user-attachments/assets/3dd10b65-2c80-49f7-91e4-23aebdf2fd1e)

with a couple different stacks:

![Screenshot 2024-07-25 at 06 38 14](https://github.com/user-attachments/assets/15334aaf-1f62-47f5-837f-07c8f5786c56)

![Screenshot 2024-07-25 at 06 42 34](https://github.com/user-attachments/assets/ab826aa1-9082-49ca-861d-5f92f854bb94)

One thing that's really interesting is that at the top of the second stack it seems to be breaking reading a _column_--and I can only reproduce this with one specific JSON file, but don't see any obvious differences in them that could cause issues when reading them back.

**Comment by btrautmann** [comment]
OK, not sure why this didn't occur to me but I actually opened up a DB browser while going through the reproduction flow, and the DB is in fact getting inundated (exponentially) it seems with new rows when modifying the view. Notably, it contains a ton of duplicate rows with different ids in 2 different tables. Smells like an application bug--still figuring that out.

**Comment by btrautmann** [comment]
OK, final update: It was in fact an application logic issue. Basically, the repro steps would modify the DB correctly, but a bad query was duplicating data based on incorrect joins. This duplicated data would feed into the edit flow which would _save_ the duplicate data (I don't have unique constraints on columns like I should) and this cycle would repeat until the OOM error. The reason (I think) this only reproduced on the import in the issue description is due to the shape of the categoryIds and categoryGroup ids field. Having only 1 category group id protected against the duplication at the query level. Anyway, sorry for the noise on this issue!

**Comment by simolus3** [comment]
No problem, glad you were able to figure it out!
