### ISSUE TITLE
Why DOES THIS PACKAGE NOT WORK

### ISSUE THREAD

**Issue by kq1231** [simolus3/moor#3111]
I installed the packages and followed the *get started* guide on the docs page. But it throws errors. 
Linter says something's wrong. When I hover over driftDatabase(name: ...), this is what I get: 

A value of type 'QueryExecutor' can't be returned from the method '_openConnection' because it has a return type of 'DatabaseConnection'.dart[return_of_invalid_type](https://dart.dev/diagnostics/return_of_invalid_type)

I have used build_runner and it generated the database.g.dart file.

There is another problem with _openConnection.
The instance member '_openConnection' can't be accessed in an initializer.
Try replacing the reference to the instance member with a different expression

 Any solution?

**Comment by dballance** [comment]
Make sure you follow the instructions here: 

https://drift.simonbinder.eu/docs/getting-started/

**Comment by simolus3** [comment]
I've actually messed up here, `_openConnection` should return a `QueryExecutor` when using `driftDatabase()`. I've updated the documentation accordingly.

**Comment by norbertje** [comment]
I got here also with the same issues after following the steps in the documentation. I assume the documentation update is not released yet as it is still shows that `_openConnection` returns `DatabaseConnection` and not `QueryExecutor`.

The other issue @kq1231 mentioned ('The instance member '_openConnection' can't be accessed in an initializer.') still exist with following the steps stated in the documentation.

If anyone will run into this, my solution was simply making `_openConnection` a static function.

**Comment by simolus3** [comment]
Well this is embarrassing - thanks for pointing this out again! This was fixed, but then I've released drift 2.19.2 with cherry-picked commits backported from `develop` which then rolled this back.

It's fixed again now - the docs update for drift 2.20.0 correctly returns `QueryExecutor` and also makes the method `static`.
