### ISSUE TITLE
Error generate table with name "xxxus"

### ISSUE THREAD

**Issue by malvinpratama** [simolus3/moor#3117]
I try to generate table with name OrderStatus. But I got error from the file .g.dart.

this my code.

import 'package:drift/drift.dart';

class OrderStatus extends Table {
  TextColumn get name => text().unique()();
  TextColumn get description => text()();
}

![image](https://github.com/user-attachments/assets/8830c001-2499-45a6-a64a-19765d3cad9d)

This the error.
I try create table Order table with name Orderus for check and got same error. So I'm sure that's the cause.

**Comment by simolus3** [comment]
Unfortunately you can't have a column called `name` in the table because drift uses a field with the same name to represent the name of the table.

Is it possible to rename the column to e.g. `orderName` or something?

**Comment by malvinpratama** [comment]
> Unfortunately you can't have a column called `name` in the table because drift uses a field with the same name to represent the name of the table.
> 
> Is it possible to rename the column to e.g. `orderName` or something?

that's not the problem. I have category and product table with column "name" and that's fine. the problem is if table name end with "us" character that can be error on generate.

**Comment by simolus3** [comment]
Oh right - sorry! This is a bug in `drift_dev` which I've just fixed, you can apply a workaround as well:

```dart
@DataClassName('OrderStatusData')
class OrderStatus extends Table {
  TextColumn get name => text().unique()();
  TextColumn get description => text()();
}
```
