### ISSUE TITLE
Better update strategies for stream queries

### ISSUE THREAD

**Issue by simolus3** [simolus3/moor#313]
Currently, stream queries are invalidated on a per-table basis only. While that works, being smarter here could reduce unnecessary re-queries and hence improve performance. We should also have better runtime support for triggers.

- a considerable amount queries only watch a primary key: `SELECT * FROM foo WHERE id = ?`. We shouldn't have to invalidate that query after a `UPDATE foo ... WHERE id = ?` for ar different id
- Some propagation graph to support triggers: We should be able to express something like "an delete to table foo implies a delete on table bar"

**Comment by szotp** [comment]
Did you consider `sqlite3_update_hook`?

**Comment by simolus3** [comment]
It looks interesting, especially considering how it would solve the problem with triggers for us. But it's only available on `moor_ffi` and it doesn't fire on `WITHOUT ROWID` tables. And we'd still have to know which ids a query actually reads from.

**Comment by simolus3** [comment]
On `develop`, we now have a propagation graph for triggers. To make more precise updates, a update now consists of a table name and a kind (insert, update, delete).

This allows us to specify something like "an insert on table `transactions` causes an update to `accounts` and a delete on `pending_transactions`". The generator is able to infer this graph based on triggers, I'll look into also supporting foreign key constraints.
