### ISSUE TITLE
Having two "autoincrement" integers breaks the insert Companion

### ISSUE THREAD

**Issue by dkbast** [simolus3/moor#3130]
**Describe the bug**

UPDATE: So this seems to be a limitation from sqlite - in this case, the generator should probably fail and give a reasonable explanation.

---

I have a table definition where I want to have an id, which is auto incrementing, and also want to have a "sortIndex" which should also be auto incrementing (think of a reorderable list where I want to append, but be able to keep track of the position as well. 

If I only have the id, it works, as soon as I add the sort index with auto increment the insert makes both id and sort index required.

```
class MyAwesomeTable extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(min: 1, max: 32)();
  TextColumn get description => text()();
}

// results in 

class MyAwesomeTableCompanion extends UpdateCompanion<MyAwesomeTableData> {
  final Value<int> id;
  final Value<String> title;
  final Value<String> description;
  const MyAwesomeTableCompanion({
    this.id = const Value.absent(),
    this.title = const Value.absent(),
    this.description = const Value.absent(),
  });
  MyAwesomeTableCompanion.insert({
    this.id = const Value.absent(),
    required String title,
    required String description,
  })  : title = Value(title),
        description = Value(description);
  static Insertable<MyAwesomeTableData> custom({
    Expression<int>? id,
    Expression<String>? title,
    Expression<String>? description,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (title != null) 'title': title,
      if (description != null) 'description': description,
    });
  }
// ...
```

But as soon as I add another integer field which autoincrements I get this:

```
class MyAwesomeTable extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(min: 1, max: 32)();
  TextColumn get description => text()();
  IntColumn get sortOrder => integer().autoIncrement()();
}

// results in

class MyAwesomeTable extends UpdateCompanion<MyAwesomeTable> {
  final Value<int> id;
  final Value<String> title;
  final Value<String> description;
  final Value<int> sortOrder;
  final Value<int> rowid;
  const MyAwesomeTableCompanion({
    this.id = const Value.absent(),
    this.title = const Value.absent(),
    this.description = const Value.absent(),
    this.sortOrder = const Value.absent(),
    this.rowid = const Value.absent(),
  });
  MyAwesomeTableCompanion.insert({
    required int id,
    required String title,
    required String description,
    required int sortOrder,
    this.rowid = const Value.absent(),
  })  : id = Value(id),
        title = Value(title),
        description = Value(description),
        sortOrder = Value(sortOrder);
  static Insertable<MyAwesomeTableData> custom({
    Expression<int>? id,
    Expression<String>? title,
    Expression<String>? description,
    Expression<int>? sortOrder,
    Expression<int>? rowid,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (title != null) 'title': title,
      if (description != null) 'description': description,
      if (sortOrder != null) 'sort_order': sortOrder,
      if (rowid != null) 'rowid': rowid,
    });
  }
//...

```

Q: Is it expected behaviour that only one column can be autoincrementing? If so, I think the generator should output some warning or even an error.

Q: From what I've read, auto increment isn't supposed to work on the insert constructor at all, which is why I'm a bit confused a) that it works in the first case and b) that the second case behaves so differently.

Edit:
The documentation states that auto incrementing fields should not be required:
https://drift.simonbinder.eu/docs/dart-api/writes/#inserts

**Comment by simolus3** [comment]
Thanks for the report!

> Is it expected behaviour that only one column can be autoincrementing

Yes, in fact sqlite3 won't even let us create that table at all: 

```
Unhandled exception:
SqliteException(1): while executing, table "my_awesome_table" has more than one primary key, SQL logic error (code 1)
  Causing statement: CREATE TABLE IF NOT EXISTS "my_awesome_table" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "sort_order" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT);, 
``` 

> From what I've read, auto increment isn't supposed to work on the insert constructor at all

The intended behavior is what you're seeing in a). You don't _need_ to supply a value for the id because the database will pick one by default - so, it's not a `required` parameter on the `insert` constructor.
We shouldn't let you write a table with two primary keys at all and this is a result of an inconsistent state in `drift_dev`, but the reason the columns are required in b) is that drift no longer recognizes the "single-column integer primary key that isn't required" pattern.

I have added a warning for this in 24905dc6c23a375999c1771a1ab089f5918b4f66.
