### ISSUE TITLE
Ability to declare interfaces for data classes

### ISSUE THREAD

**Issue by Adam-Langley** [simolus3/moor#3141]
Drift has the ability to define custom data classes for row entities (`@[UseRowClass]`), which is fantastic, however...

I have several tables in my db, which conform to a similar schema (i.e, they all have Name, Description, and SortOrder).
I want to be able to write application code, which treats all these tables similarly.

I can achieve this with UseRowClass, and sharing a common superclass, however, by doing that, I need to manually define the entire table (all table fields).

This could be improved, by a declaration somewhere which would essentially say 'when declaring a Data Class of name X, declare that it implements contract Y'.

This _could_ be implemented like this:

```
/// my manually written interface
abstract class NameAndDescription {
  String get name;
  String get description;
}

/// my manually written interface
abstract class Orderable {
  int get orderIndex;
}

/// tell the code generator to append my manually written interface contracts
@[DataClassContracts([
  'NameAndDescription',
  'Orderable'
])]
// (yes, I use mixins as my table class, rather than classes. @simulous we've started a previous discussion about this, please let this annotation be used on mixins :)
[class|mixin] TodoCategories extends Table { 
  static TableField name = TableField(
    jsonKey: 'name',
    swaggerType: 'string',
    getter: (p) => p.name,
  );
  static TableField description = TableField(
    jsonKey: 'description',
    isNullable: true,
    swaggerType: 'string',
    getter: (p) => p.description,
  );
  static TableField orderIndex = TableField(
    jsonKey: 'orderIndex',
    swaggerType: 'integer',
    swaggerFormat: 'int32',
    getter: (p) => p.orderIndex,
  );
}
```

which would generate this... (note the 2 additional interfaces declared)
```class TodoCategory extends DataClass implements Insertable<TodoCategory>, NameAndDescription, Orderable {```

**Comment by simolus3** [comment]
I didn't try this, but I'm wondering if it could work for this: We already support `extending` as an option on `DataClassName`. So is it possible to do

```dart
abstract class CommonDataClass implements NameAndDescription, Orderable {}

@DataClassName.custom(extending: CommonDataClass)
class TodoCategories extends Table {}
```

**Comment by Adam-Langley** [comment]
Hi @simolus3  - thanks - yes this _almost_ works, couple of caveats....

1. `NameAndDescription` needs to extend from `DataClass`
Probably not an issue, just maybe an unnecessary limitation
2. The annotations cannot be applied to a mixin
3. This is the bigger issue - cannot pass multiple interfaces to 'extending', and if you use multiple @DataClass annotations, the generator only honors the last one - ignores the others...

I _feel_ like having another DataClassName optional argument, `implementing`? would be the least invasive. It kind of makes more sense to me also, in that the constraints on the classes passed to that argument are inherently different (set/list rather than singular, no need to extend DataClass, must be abstract etc).
