### ISSUE TITLE
Ability to disable "auto include" of table class declarations, daos, .drift files, etc

### ISSUE THREAD

**Issue by Adam-Langley** [simolus3/moor#3148]
I am trying to track down some issues in my drift configuration.
In doing so, I have stripped my '@DriftDatabase' class back to absolute minimum, then slowly add these things back until generation errors occur, then I know what's breaking it.

Examples of things I removed from the declaration, I removed items from `tables: []`, `views: []`, `daos: []`, and `include: []`

I already knew tables classes were automatically pulled in even if not explicitly included, however my drift files were also still being processed. 

What would be very helpful, is a way to turn off this "auto-include" feature, to save me having to comment out code, rename .drift files, etc.

Great work, thank you!

**Comment by Adam-Langley** [comment]
@simolus3 - actually, take this one with a grain of salt. I may have been misunderstanding what was going on.
It's possible that I had .drift files that were causing things to get pulled in that I wasn't intending - rendering this item moot.

I'll leave it open, in case any of it rings true - but if not, my fault, please feel free to close.

**Comment by simolus3** [comment]
We should only include items if they were either explicitly added to `tables` or `views` or included through a chain of `includes` / `import` statements.

If that's what was happening here then this sounds like it's working as intended.
