### ISSUE TITLE
Generator table discovery should exclude private classes

### ISSUE THREAD

**Issue by Adam-Langley** [simolus3/moor#3152]
The generator does not currently exclude private classes (ones whose names start with an underscore) from the drift file analysis process.

_To clarify - it's specifically elements discovered during `.drift` file traversal, that exhibit this issue. Private dart-file  classes do not exhibit this issue, UNLESS that dart file can also be reached via a drift file - then it also becomes problematic._

This can result in the final generated dart code creating derivatives of classes that are not legally accessible, i.e. - uncompilable code.

For example

```
// public definition of table, note the fact it derives a private class
class MyTable extends _$MyTable {
  TextColumn get customField => text()();
}

// this is a private base-class whose purpose is to define many of the fields. The public/private split of classes is a convention we follow 
class _$MyTable extends Table {
  TextColumn get name => text()();
  TextColumn get description => text()();
  TextColumn get id => text()();
}
```

following is what drift will generate
```
// this is the generated table for the public "MyTable" class
class $MyTableTable extends MyTable with TableInfo<$MyTableTable, MyTableData> {
// ...
}

// this is also generated, for the PRIVATE "_$MyTable" class - this should not be here - it won't compile because "_$MyTable" cannot be resolved
class $_$MyTableTable extends _$MyTable
    with TableInfo<$_$MyTableTable, _$MyTableData> {
// ...
}
```

I've supplied a test case, and proposed fix PR, below.

**Comment by Adam-Langley** [comment]
Example project demonstrating issue as per above report.

Using the project to repro the issue
1. from terminal, run build_runner build to produce the db.g.dart file
2. observe the syntax errors in the `db.g.dart` file

Using the project to demonstrate the fix
1. open pubspec.yaml
2. uncomment the lines which override the drift/drift_dev dependencies to point to the Adam-Langley branch
3. from terminal, run build_runner build to produce the db.g.dart file
4. observe the syntax errors in `db.g.dart` disappear - TableInfo classes will no longer be generated for the private table classes

[drift_test.zip](https://github.com/user-attachments/files/16620083/drift_test.zip)

**Comment by dickermoshe** [comment]
Love the PR, lets get some tests and we'll be good to go
