### ISSUE TITLE
Version 2.2 create analyze warning that can break pipelines

### ISSUE THREAD

**Issue by Johannes-Schiel** [simolus3/moor#3164]
**Describe the bug**

When you currently use the package, four errors or warnings are generated in the database.g.dart file. These warnings currently cause the default flutter analyze to fail. This can be easily resolved by excluding it, but it should work correctly again. The question is whether I made a mistake here or if something has changed between the last versions? My code has remained the same since then.

<img width="540" alt="Screenshot 2024-08-21 at 14 15 11" src="https://github.com/user-attachments/assets/0ba464ee-0497-4d8a-80c3-1b27d127fe1a">

**Comment by simolus3** [comment]
My stance is that static analysis doesn't provide much value for generated code, and it should be excluded from it. However, we also shouldn't annoy users with this. Drift generates a  `// ignore_for_file: type=lint` comment at the top of the file - can you check that that is present here as well?

At least the `ProcessedTableManager` warnings should have been silenced by that comment so they're surprising to me. The "operand can't be null" errors might not be lints but actual warnings, so we should look into them. I also can't reproduce them though, can you share the generated lines around that error?

**Comment by Johannes-Schiel** [comment]
@simolus3 yes sadly the comment dont work.

Maybe there is change in the flutter version?

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.0, on macOS 14.6.1 23G93 darwin-arm64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.2.0.1)
[✓] VS Code (version 1.91.1)
[✓] Connected device (5 available)
[✓] Network resources

• No issues found!
```

**Comment by simolus3** [comment]
I have the same Flutter version and I can't reproduce the issue. What tool are you using in your CI pipeline, plain `dart analyze`?

**Comment by Johannes-Schiel** [comment]
Can't recreate the error.
