### ISSUE TITLE
`Expression.and`/`Expression.or` should create parenthesis

### ISSUE THREAD

**Issue by FMorschel** [simolus3/moor#3165]
I saw on the docs the `Expression.and` and `Expression.or` constructors. I believe they should create parenthesis on the generated SQL so that the precedence is maintained when nesting them.

Like:
```
Expression.and([
  expr0, 
  Expression.or([
    expr1, 
    Expression.and([expr2, exp3]),
  ]),
]);
```

Should create an SQL like:
```
(expr0 & (expr1 | (expr2 & expr3)))
```

**Comment by simolus3** [comment]
In SQL, `AND` has a higher precedence than `OR`. So `a OR b AND c` is already the same as `a OR (b AND c)`. So if we look at

```dart
Expression.and([
  a, 
  Expression.or([
    b, 
    Expression.and([c, d]),
  ]),
]);
```

Then the fully parenthesized expression would be `a AND (b OR (c AND d))`, which is equivalent to `a AND (b OR c AND d)` -- exactly what drift is generating.

Drift actually tracks the precedence of expressions on `Expression` and only inserts parentheses where necessary (that is, lower precedence expressions are children of higher precedence expressions). So this appears to be working as intended here.

**Comment by FMorschel** [comment]
Ohh, I see. I didn't know that. Thanks!
