### ISSUE TITLE
Copy button for code block in the docs

### ISSUE THREAD

**Issue by FMorschel** [simolus3/moor#3171]
**Is your feature request related to a problem? Please describe.**
It is weird how the browser selects more code than what is inside the code block text sometimes and to copy it is a bit hard.

**Describe the solution you'd like**
I'd like the docs to have a "copy" button on code blocks.

**Comment by simolus3** [comment]
We're currently planning to migrate the documentation website to Material for MkDocs, a different static site generator. I think that has a button to copy the snippet directly. Let's keep this open until we have completed the migration, but I don't think it's worth adding this to the current system.

**Comment by FMorschel** [comment]
This has been fixed as well! Thanks much!
