### ISSUE TITLE
Can't see the full table

### ISSUE THREAD

**Issue by FMorschel** [simolus3/moor#3175]
**Is your feature request related to a problem? Please describe.**
If the table has a bit amount of columns, currently there is no way to see all columns with not scrollbar/similar in the horizontal axis.

**Describe the solution you'd like**
I'd like a scrollbar in the horizontal axis for the table view.

![image](https://github.com/user-attachments/assets/335ea98a-c45a-44f8-a117-ea0370553bc4)

**Comment by simolus3** [comment]
Thanks for the report! I remember taking a look at this one before, but I couldn't figure it out. The table is [wrapped into](https://github.com/vanlooverenkoen/db_viewer/blob/228bb7e4e053d27e79edb8caed031ecdeb610e46/db_viewer/lib/src/screen/table_content_list_screen.dart#L76-L80) a horizontal scroll view, so I think this _should_ work. Perhaps someone with better Flutter skills knows what's causing the scrollbar to not show up.

**Comment by FMorschel** [comment]
Take a look at 
- https://pub.dev/packages/two_dimensional_scrollables
- and https://m.youtube.com/watch?v=ppEdTo-VGcg

### Edit 

You would still need to create a horizontal scroll bar there but they're creating this new apis for making 2d scrolling more performant.

**Comment by FMorschel** [comment]
I could probably take a look at it if you'd like.

**Comment by simolus3** [comment]
> I could probably take a look at it if you'd like.

That would definitely be very welcome! I don't maintain the `db_viewer` package, but I know most of the internals from integrating it into drift's DevTools extensions so I'm happy to help if you run into issues with that.

> You would still need to create a horizontal scroll bar there but they're creating this new apis for making 2d scrolling more performant.

Maybe we should first check if it's something with the box constraints being passed down that makes this go wrong. I think remember seeing that the nested `SingleChildScrollView`s are supposed to work, so maybe it's something with the way the DevTools container lays out the widget that causes this. Would be a shame if you migrate this to `two_dimensional_scrollables` and the problem persists :D

**Comment by FMorschel** [comment]
Created the PR there
