### ISSUE TITLE
Writing queries documentation

### ISSUE THREAD

**Issue by Dev-Owl** [simolus3/moor#318]
The documentation for "Writing queries" is no longer correct, given:

> Multiple inserts can be batched by using insertAll - it takes a list of companions instead of a single companion.

The text should mention that you have to open a batch to call insertAll as the other way is marked as deprecated. Maybe something like this:

> Multiple inserts can be batched by starting a batch using the `batch(dynamic Function(Batch) runInBatch)` method. The batch object offers insertAll - it takes a list of companions instead of a single companion.

**Comment by simolus3** [comment]
Thanks for the notice. This should be fixed as the website rebuilds.
