### ISSUE TITLE
Migrate Android app plugin loader - examples

### ISSUE THREAD

**Issue by FMorschel** [simolus3/moor#3189]
**Describe the bug**

Running the examples/app on Android gives the following message: 

```console
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply
```

Perhaps we could simply delete the /android folder for all examples and whatever else needs this and run `flutter create .`? Or we can manually migrate everything. I volunteer to do either.

**Comment by simolus3** [comment]
We're not using anything custom, so deleting `android/` and re-creating contents should work. Thanks for all your help, a PR would be welcome!

**Comment by FMorschel** [comment]
What about the actual drift package and related? I'm not sure how to run them standalone or even if it is possible. Do they use anything custom?

**Comment by FMorschel** [comment]
If they cant run standalone than they probably won't need any changes I don't think.

**Comment by simolus3** [comment]
They're pure Dart packages and shouldn't have an `android/` folder.
