### ISSUE TITLE
too many SQL variables

### ISSUE THREAD

**Issue by robotoss** [simolus3/moor#319]
Greetings, everyone.
my spec:
**rxdart**: ^0.23.1
**moor**: ^2.2.0
**moor_flutter**: ^2.0.0
**moor_ffi**: ^0.3.1

I have the following problem:
I have a database of bus stops in town (1,300 entries). I need a list of stops and routes at these stops.
I create my code by this example - https://moor.simonbinder.eu/docs/examples/relationships/ (Selecting all carts)

And when i try to select all entries that are included in any stop that i found i catch error
SqliteException: too many SQL variables, SQL logic error.

If I creat list with 1048 items there is no error
If 1049 or higder i have this error

My code:

```
Stream<List<BusStopsWithRoutes>>  watchAllData() {
    final busStream = (select(busStops).watch());
    return busStream.switchMap((stops) {
      final idToStop = {for (var stop in stops) stop.id: stop};
      final ids = idToStop.keys;

      List<int> list = List();
      stops.forEach((f){
        if(f.id < 1047){
          list.add(f.id);
        }
      });

      final entryQuery = select(busStopRoutes).join(
        [
          innerJoin(
            busRoutes,
            busRoutes.id.equalsExp(busStopRoutes.busRouteId),
          )
        ],
      )..where(busStopRoutes.id.isIn(ids));

      return entryQuery.watch().map((rows) {
        final idToItems = <int, List<BusRoute>>{};
        for (var row in rows) {
          final item = row.readTable(busRoutes);
          final id = row.readTable(busStopRoutes).id;
          idToItems.putIfAbsent(id, () => []).add(item);
        }
        return [
          for (var id in ids)
          BusStopsWithRoutes(
            busStop: idToStop[id],
            busRoutes: idToItems[id] ?? [],
          )
        ];
    });
  });
  }
```

a small deviation:
1) In the new version of rxDart removed Observable, now it will be correct not  to
 final cartStream = Observable(select(shoppingCarts).watch());
but 
final cartStream = select(shoppingCarts). watch();
2) as well as in the latest moor
where(isIn(shoppingCartEntries.shoppingCart, ids));
but 
where(shoppingCartEntries.shoppingCart.isIn(ids));

**Comment by simolus3** [comment]
Sounds like a cool project! In the shopping cart example, I kind of assumed that there could be many items that aren't in any shopping cart. I assume that for bus stops, you'll not see many routes without any stop :) So if you're selecting all bus stops and all routes, applying a manual filter seems unnecessary as all rows will be selected either way.

So in that case, it can be more efficient to just select all entries and perform the matching in Dart. I can help you write that, but I'm not sure about `row.readTable(busStopRoutes).id`. Is the `busStopRoutes` table a pure combination mapping from routes to stops? I imagine it could contain additional data like the planned time relative to when the route starts. Do you need that data in your `BusStopsWithRoute` class as well?

**Comment by robotoss** [comment]
Thank you for your help,
The error was corrected.
busStopRoutes is a table that includes the stop id and route id, so that when it is necessary we can show Stops with routes and route  with its stops.
All we have 4 tables
The routes.
The coordinates of the route points
The stops.
and the Routes and Stops Communication Table.
