### ISSUE TITLE
`schema export --dialect postgres` produces invalid SQL for DateTimeColumn and BoolColumn when defaults are specified

### ISSUE THREAD

**Issue by ryanhanks-bestow** [simolus3/moor#3198]
Given the following table definition:

```dart
class Examples extends Table {
  BoolColumn get isDraft => boolean().withDefault(const Constant(true))();

  DateTimeColumn get createdAt => dateTime().withDefault(currentDateAndTime)();
}

```

`drift_dev schema export --dialect postgres` produces:

```sql
CREATE TABLE IF NOT EXISTS "examples" (
    "is_draft" boolean NOT NULL DEFAULT TRUE CHECK ("is_draft" IN (0, 1)),
    "created_at" bigint NOT NULL DEFAULT (CAST(strftime ('%s', CURRENT_TIMESTAMP) AS bigint))
);
```

which errors with:

```
ERROR:  42883: operator does not exist: boolean = integer
LINE 2:     "is_draft" boolean NOT NULL DEFAULT TRUE CHECK ("is_draft" IN (0, 1))
                                                                       ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```
and
```
ERROR:  42883: function strftime(unknown, timestamp with time zone) does not exist
LINE 3:     "created_at" bigint NOT NULL DEFAULT (CAST(strftime ('%s', CURRENT_TIMESTAMP) AS bigint))
                                                       ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

Note: setting the build option `store_date_time_values_as_text` will produce valid sql

```sql
CREATE TABLE IF NOT EXISTS "examples" (
    "is_draft" boolean NOT NULL DEFAULT TRUE CHECK ("is_draft" IN (0, 1)),
    "created_at" text NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);
```

**Comment by simolus3** [comment]
Thanks for the report! I think this doesn't just apply to `schema export`, this would also fail when using the regular drift migration tools.

**Comment by simolus3** [comment]
The situation for the boolean columns will improve in drift_dev 2.20.2 (1607d4b2b3d6908bf5f0e780255b17f9ef295cea).

Drift's datetime API is currently designed with sqlite3 in mind only, it doesn't support other date time types at all (contributions to expand this are welcome though!). If you're optimizing for postgres, I suggest using [`PgTypes.dateTime`](https://pub.dev/documentation/drift_postgres/latest/drift.postgres/PgTypes-class.html) as a custom column type and [`now()`](https://pub.dev/documentation/drift_postgres/latest/drift.postgres/now.html) as its default value.
