### ISSUE TITLE
Add documentation for the Drift DevTools Extension

### ISSUE THREAD

**Issue by kenzieschmoll** [simolus3/moor#3199]
I was looking through https://drift.simonbinder.eu/docs/ for documentation on the Drift DevTools Extension, but I did not find any. Including some guidance for how to use and access this tool would be great.

**Comment by simolus3** [comment]
Good call, thanks for the suggestion! I've added a page in f21d20e699833609ab4f1937c92f8ef1f918cb9f. This will get published with the next drift release, a  preview is at https://66d8c8ad176d6949e24112e8--moor.netlify.app/docs/tools/devtools/
