### ISSUE TITLE
Using with a server

### ISSUE THREAD

**Issue by gedw99** [simolus3/moor#32]
I am guessing that this is designed such that updates to data from the server can't be detected and update the corresponding views that have a SQL watch query on them because you rely on detecting a CUD to the salute database from the user interface ?

**Comment by simolus3** [comment]
Yeah, that's right. There's no way to efficiently implement auto-updating queries without knowing when data could have changed, so we either need to listen for CUDs or we need a database that supports it out-of-the-box. This library mainly targets flutter apps (for now), so we talk to sqlite, which doesn't support it.
We could implement a mechanism that just re-runs queries in regular intervals, but that's a considerable performance impact which IMHO is not worth it. If you wanted to run this on a server, I'd definitely recommend to use a streaming database instead.

**Comment by jwallat** [comment]
I am looking for a way to have my database running on a server and use moor to not deal with plain sql. For my purposes, I do not need my the auto updating part. I believe it is currently not possible to connect to remote dbs, do you plan to make this possible in the future?
