### ISSUE TITLE
Add new option to the DevTools extension to run build_runner

### ISSUE THREAD

**Issue by FMorschel** [simolus3/moor#3200]
I'd like the option to run build_runner without always having to look for the command and run into the terminal. Would it be possible for the DevTools extension to run `build` or even `watch`?

**Comment by simolus3** [comment]
This is an interesting idea! Extensions don't have this capability at the moment, but I've asked on the Flutter Discord if something like this would ever be supported. If it is or will be, I think this would be a good candidate for a DevTools extension for `build_runner`. I'll file an issue there if it's feasible.
