### ISSUE TITLE
Documentation dark mode

### ISSUE THREAD

**Issue by FMorschel** [simolus3/moor#3201]
From [this comment](https://github.com/simolus3/drift/issues/3171#issuecomment-2308408926):

> We're currently planning to migrate the documentation website to Material for MkDocs, a different static site generator.

I'm not familiar with it, but I'd like to ask if possible to add a dark mode toggle for the docs. As it is currently only in light mode when coding at night with IDE on Dark mode opening the docs is a little hard for my eyes.

**Comment by dickermoshe** [comment]
I'm going to close this because this will be done by the end of the week!!

**Comment by dickermoshe** [comment]
This was one of the main things that drove me nuts until I spent way to much time migrating things over!
