### ISSUE TITLE
Web WASM: "RuntimeError: illegal cast at InsertStatement.insert

### ISSUE THREAD

**Issue by hnvn** [simolus3/moor#3203]
I got following exception when trying to insert new item to database

<img width="758" alt="Screenshot 2024-09-06 at 10 37 04" src="https://github.com/user-attachments/assets/dcf38b17-70db-4c44-a11b-d5049abc838d">

**Comment by simolus3** [comment]
Thanks for the report - this looks related to https://github.com/simolus3/drift/issues/3194. You could try using [the current development version](https://drift.simonbinder.eu/docs/internals/) and see if that fixes the issue. I will also release a drift version with containing the fix this weekend.

**Comment by simolus3** [comment]
Should be fixed in `drift` version 2.20.1.

**Comment by hnvn** [comment]
Confirm the issue is fixed in the version 2.20.1
