### ISSUE TITLE
`distinct()` with `omit` parameter.

### ISSUE THREAD

**Issue by RoarGronmo** [simolus3/moor#3208]
**Is your feature request related to a problem? Please describe.**
I have found that using the `distinct()` "extension" in the calls i.e.
```
 stream: globals.mWorkDatabase.getSelectedOrder(
                    SettingKey.userSelectionSelectedFirm,
                    SettingKey.userSelectionSelectedOrder
                ).watchSingleOrNull().distinct(),
```

Could be benifitial if you update data in backend, but the data didn't really change, and you could then avoid refresh / flashing of your data content.

But now I have a problem, sometimes only one field, actually a reading timestamp, is the only value which is updatet. That value isn't normally visible, but the distinct function haven't any parameter where I could tell `omit this field` on the compare. I could of course explode the member extension function and compare each value, but that feels awkward when the tables may have over 30 columns...

**Describe the solution you'd like**
I wish for some kind of parameter [an array maybe] where I could give the member names which should not be tested during the compare. Like

```
 stream: globals.mWorkDatabase.getSelectedOrder(
                    SettingKey.userSelectionSelectedFirm,
                    SettingKey.userSelectionSelectedOrder
                ).watchSingleOrNull().distinct( omit:["readTime", "lastUpdated"] ),
```

**Comment by dickermoshe** [comment]
`distinct` is a [method](https://api.flutter.dev/flutter/dart-async/Stream/distinct.html) built into every stream.
You can pass a custom function to distinct which will handle your needs.

**Comment by dickermoshe** [comment]
I'm closing because this isn't really an feature request for drift.

**Comment by simolus3** [comment]
We don't have a particularly efficient way to deal with this unfortunately, but you can do this:

```dart
extension<T extends Insertable<T>> on Stream<T> {
  Stream<T> distinctIgnoring(Iterable<String> ignoredFields) {
    return distinct((previous, next) {
      final prevFields = previous.toColumns(false);
      final nextFields = next.toColumns(false);

      for (final MapEntry(:key, :value) in prevFields.entries) {
        if (ignoredFields.contains(key)) continue;
        if (nextFields[key] != value) {
          return false;
        }
      }

      return true;
    });
  }
}
```

Then you could call `distinctIgnoring(const ['read_time', 'last_updated'])`.
