### ISSUE TITLE
? Depreciate `drift_sqflite` and publish Migrations Guide ?

### ISSUE THREAD

**Issue by dickermoshe** [simolus3/moor#3212]
_Title Says It All_

@simolus3 Any reason not to do this?

**Comment by simolus3** [comment]
> Any reason not to do this?

`drift_sqflite` is a very small package that has pretty low maintenance costs. There are some advantages of using sqlite3 APIs provided from the operating system, like being able to use the database inspector in Android studio or slightly smaller app sizes.

Every deprecation and forced migration hurts existing users, so the question should be what reasons we have to remove `drift_sqflite`. Having a single sqlite3 implementation would be nice, but I don't think that's a reason strong enough to break existing users.

**Comment by dickermoshe** [comment]
> @simolus3 Any reason not to do this?

Guess there is a reason then...
