### ISSUE TITLE
Hot Reload & SchemaVersion

### ISSUE THREAD

**Issue by dickermoshe** [simolus3/moor#3215]
**Describe the bug**

Here is the current footgun which bugs me:

When adding new fields

1. Add new field/table
2. Update `@DriftDatabase` decorator
3. Bump`schemaVersion`
4. Save the file
5. Export Schema
6. Generate `StepByStep`
7. Write the migration
8. Error: Migration doesn't run!!!

Why?
Because Step 4 ran a hot reload which caused drift to update the schema version.
his happens all too often

**Solution**
Only run migration once!

@simolus3 Thoughts?

**Comment by simolus3** [comment]
So ideally a hot reload should keep your existing database without re-opening it? A hot restart is a different thing, but I think hot reloads re-opening databases doesn't happen by default (well, depending on how you setup your app). I think the hot reload just refreshes your current widget tree, but IIRC it doesn't call `main` again.

>  Only run migration once!

Per app open? That would break users having two databases. Per database? We're already doing that, but it's evidently not enough. :thinking:

**Comment by dickermoshe** [comment]
A hot reload only reruns code under `runApp`

```dart
class DB{
  static bool _ranMigrations = false;
  DB(){
    if (_ranMigrations) return;
    runMigrations().then((_){
      _ranMigrations = true;
  });
  }
}


void main(){
  final db = DB();
  runApp(...)
}
```
would only rerun migrations during a hot restart.

However I forgot about people using the same class for different databases. Dang it!

Stop ruining all my great ideas!!!
