### ISSUE TITLE
is drift support 【HAVING COUNT...】？

### ISSUE THREAD

**Issue by SAOmi567** [simolus3/moor#3217]
I wan't to white a query like this 
##
SELECT item.id, item.name
FROM item
JOIN tagItemMapping ON item.id = tagItemMapping.itemId
WHERE tagItemMapping .tagid IN (1, 2, 3)
GROUP BY item.id
HAVING COUNT(DISTINCT tagItemMapping .tagid) = 3;
##
but How can I use having in drift? I don't find it in docs
please help me  thanks

**Comment by simolus3** [comment]
You can use the `having` parameter on `groupBy` to accomplish this. All in all, the drift query follows the SQL statement pretty closely:

```dart
selectOnly(item)
  ..addColumns([item.id, item.name])
  ..join([innerJoin(tagItemMapping, tagItemMapping.itemId.equalsExp(item.id))])
  ..where(tagItemMapping.tagid.isIn([1, 2, 3]))
  ..groupBy([item.id], having: tagItemMapping.tagid.count(distinct: true).equals(3))
```
