### ISSUE TITLE
SQL Parsing Error with Special Characters (e.g., $ , ''',#) in Query

### ISSUE THREAD

**Issue by Srimathi622** [simolus3/moor#3218]
I wanted to bring up an issue we've encountered while using the SQL parser. Specifically, when an invalid character such as $,#,'''(Three quoted strings) is included in a SQL query accidentally, the parser throws an exception rather than handling it gracefully. For example, in the query:

```
String sql= 'select ''' from dual';
String sql= 'select # from dual';

 final engine = SqlEngine();
  final result = engine.parse(sql);
```

The parser throws the following exception:

```
CumulatedTokenizerException: Malformed SQL: Expected identifier after `$` at <FileLocation: 9 unknown source:1:10>
```

This behavior can potentially disrupt the flow of our application, as it results in an unhandled exception when parsing the SQL string. Ideally, we would expect the parser to either:

Ignore special characters that it doesn't recognize (e.g., $,#,'''), or
Return an error in the results object without throwing an exception, allowing us to handle the error more gracefully on our side.
Could you please consider updating the parser to handle such cases more robustly? This would help avoid issues caused by accidental inclusion of special characters like $, and improve error handling during SQL parsing.

Thank you for your time, and I look forward to your feedback.

Regards,
Srimathi

**Comment by simolus3** [comment]
>  Return an error in the results object without throwing an exception, allowing us to handle the error more gracefully on our side.

Couldn't you handle these gracefully by ... catching the exception? You're not going to get a clean result from these broken queries either way.

I agree that not throwing tokenization errors and instead reporting these as e.g. an `InvalidToken` that the parser trips over would be better for error recovery.

**Comment by Srimathi622** [comment]
Thanks for your reply. I agree that catching exceptions in our application code is a viable approach for handling such errors. I thought it would be helpful to include this in result.errors.

**Comment by simolus3** [comment]
Can you try using `sqlparser` from the linked commit and see if that matches what you had in mind? It mixes the tokenizer errors and the parsing errors in the result class - in some cases you may even get a partial AST back.

And just out of interest, what are you using `sqlparser` for?

**Comment by Srimathi622** [comment]
Hi Simolus,
Thank you for the update! The changes in the dev branch are working as expected, and the approach of mixing tokenizer and parsing errors within the result class seems ideal for our use case.

Could you please let me know if there are plans to merge these changes into the live branch? It would be great to have this functionality in a stable release for production.

Thanks again for your support and efforts!
