### ISSUE TITLE
Error G0A556F40: The return type of the method '_$Database.allTables' is wrong

### ISSUE THREAD

**Issue by anisalibegic** [simolus3/moor#3223]
In my app there is an error in the generated `database.g.dart` when trying to run it. It's mentioning that overridden getter `allTables` has invalid type.

Actual: `Iterable<TableInfo<Table/*1*/, Object?>>`
Expected: `Iterable<TableInfo<Table/*2*/, dynamic>>`

### Error
```dart
lib/database/database.g.dart(37154,43): error G0A556F40: The return type of the method '_$Database.allTables' is 'Iterable<TableInfo<Table/*1*/, Object?>>', which does not match the return type, 'Iterable<TableInfo<Table/*2*/, dynamic>>', of the overridden method, 'GeneratedDatabase.allTables'.
lib/database/database.g.dart(37154,12): error G4699A223: Type argument 'Table/*1*/' doesn't conform to the bound 'Table/*2*/' of the type variable 'TableDsl' on 'TableInfo'.
lib/database/database.g.dart(37155,35): error G4699A223: Type argument 'Table/*1*/' doesn't conform to the bound 'Table/*2*/' of the type variable 'TableDsl' on 'TableInfo'.
```

### Temporary solution
Manually editing `database.g.dart` and changing:
```dart
@override
  Iterable<TableInfo<Table, Object?>> get allTables => allSchemaEntities.whereType<TableInfo<Table, Object?>>();
```
to
```dart
@override
  Iterable<TableInfo> get allTables => allSchemaEntities.whereType<TableInfo>();
```

Is this something on my end since I can't find any info on this repo.

**Comment by simolus3** [comment]
In your database file, do you have another import to something defining `Table` (e.g. flutter or something)? Does the error say where `Table/*1*/` and `Table/*2*/` are defined?

**Comment by anisalibegic** [comment]
Indeed that was the cause. I have a table named `Table` (as a desk). I changed it to `@DataClassName('Table_')` and I works great. Thank you very much!
