### ISSUE TITLE
Batch support for deletes

### ISSUE THREAD

**Issue by MarcinusX** [simolus3/moor#325]
Hi! First of all - great package - currently doing my masters using it :)

Got a question though: Is there any reason why `Batch` doesn't support `delete` and `deleteAll`?
I can work without so it's not urgent for me - but it seems like a reasonable feature to be there. :)

Thanks again. :)

**Comment by simolus3** [comment]
Good idea, I've just added the `delete` method  for batches. 

There's no `deleteAll`, but you can use `delete(table, (row) => const Constant(true))`. I preferred to make the predicate function explicit, so that it's harder to accidentally delete everything.

**Comment by MarcinusX** [comment]
Actually, I said it wrongly. What I meant was something like `deleteAll(TableInfo<Table, D> table, List<Insertable<D>> rows)`.

My case is that I'm loading some list of entries, do some calculations on the list and then some of those entries need to be removed. So this method would be very similar to `insertAll`.

And the fact you just quickly did it is amazing to me! I'm really impressed that you are so committed to open source project :)

**Comment by simolus3** [comment]
> What I meant was something like `deleteAll(TableInfo<Table, D> table, List<Insertable<D>> rows)`

That seems reasonable. I've renamed the `delete` method taking a predicate to `deleteWhere`. A new `delete` method takes an `Insertable` and matches its primary key. You'll get the best performance by calling that method in a loop for each entry.

**Comment by MarcinusX** [comment]
THANK YOU 💙
