### ISSUE TITLE
Using specific SQLite version for tests (on MacOS)

### ISSUE THREAD

**Issue by Yegair** [simolus3/moor#3258]
# Disclaimer

Maybe there is an easy (and documented) solution to my problem. In that case I apologize for opening another issue, but so far I did not find it.

# Description

I am facing an error, that seems to be caused by an outdated SQLite version being used in unit tests.

The error message is `error in tokenizer constructor` and it is caused by a statement similar to the following, that is executed during migrations:

```sql
CREATE VIRTUAL TABLE foo_ts USING fts5 (
    value,
    content=foo,
    content_rowid=id,
    tokenize='trigram case_sensitive 0 remove_diacritics 1'
);
```

I have traced the cause of the error to the SQLite version being used (`3.43.0` in my case), which is the one installed on my Mac. Running the same statement within my Flutter app works without any problems, but there I have SQLite `3.46.1`.

I am using [mise](https://mise.jdx.dev) for managing the devtools in my project, and I assumed just installing a recent SQLite version that way should solve the issue (Mise then puts it into the `$PATH` as `sqlite3`), but it seems the SQLite version being used in unit tests is still the one installed natively on my Mac.

Ideally I would like to control the SQLite version that is being used in unit tests on a project level, without having to upgrade the System SQLite installed on my Mac.

I have read the documentation on how to do that for Linux (https://drift.simonbinder.eu/docs/platforms/#bundling-sqlite-with-your-app), but before I start wiring up paths to the Mise SQLite in a way that works for all team members, I thought I should ask if there may be a better way to achieve what I want (also not sure if the Linux way can be applied to MacOS as well).

**Comment by simolus3** [comment]
At the moment, there isn't really anything we can do to solve this automatically. Unit tests are running as Dart programs without Flutter's build tooling, so we can't make them use the sqlite3 build that would be included with `sqlite3_flutter_libs`.

I can share the (certainly not ideal) solution I'm using in drift, perhaps that is helpful for you as well:

1. I have a [CLI tool](https://github.com/simolus3/drift/blob/develop/drift/tool/download_sqlite3.dart) that downloads and compiled a fixed sqlite3 version into the `.dart_tool` folder. Note that this doesn't apply the same compile-time options as `sqlite3_flutter_libs`, so some changes might be necessary depending on how close you want the libraries to match.
2. I then have [these lines](https://github.com/simolus3/drift/blob/766581369d9bd3088a8795b3f67f54f6f8a57a14/drift/test/isolate_test.dart#L24) at the top of each test using sqlite3 as a library. They're configuring the `sqlite3` package to use a local sqlite3 installation:

https://github.com/simolus3/drift/blob/766581369d9bd3088a8795b3f67f54f6f8a57a14/drift/test/test_utils/database_vm.dart#L38-L49

For drift I have a single test that prints a warning if sqlite3 has not been compiled with the tool, you could also change that code to throw an exception instead and fail tests if the environment has not been set up correctly.
This is not ideal, but I couldn't come up with a better solution so far.

**Comment by Yegair** [comment]
I see, thank you for the quick response.

FWIW, here is how I do it now with Mise as the tool version manager

```dart
Future<void> _loadSqliteFromMise() async {
  final OperatingSystem os;
  final File library;

  final sqliteInstallPath = (await Process.run("mise", ["where", "sqlite"])).stdout.toString().trim();

  if (Platform.isMacOS) {
    os = OperatingSystem.macOS;
    library = File(p.join(sqliteInstallPath, "bin/sqlite3"));
  } else if (Platform.isLinux) {
    os = OperatingSystem.linux;
    library = File(p.join(sqliteInstallPath, "lib/libsqlite3.so"));
  } else {
    throw Exception("can not load SQLite library: unsupported OS: ${Platform.operatingSystem}");
  }

  open.overrideFor(os, () => DynamicLibrary.open(library.absolute.path));
}
```

Another note: Since I am using `NativeDatabase.createInBackground` in some of the tests, I had to ensure to override the dynamic library loading within the isolate setup as well.

```dart
NativeDatabase.createInBackground(file, isolateSetup: () async {
  await _loadSqliteFromMise();
})
```
