### ISSUE TITLE
Nested Transaction deadlock when executing from different starting points

### ISSUE THREAD

**Issue by Hunt2176** [simolus3/moor#3260]
I have an issue that started when upgrading 2.18 => 2.20.3

The initial transaction is started from GeneratedDatabase.transaction which then uses transaction/batches from individual DAOs. These inner transactions are deadlocking and causing the entire Future to not resolve.

I have it traced to line 497 of connection_user.dart where it is running:
`await transactionExecutor.ensureOpen(attachedDatabase);`

**Comment by simolus3** [comment]
Just to confirm, this is still happening with 2.20.3 (which resolved a similar issue)? Can you try replacing `NativeDatabase.createInBackground` or `driftDatabase` from `drift_flutter` with a simple `NativeDatabase.memory()` and see if the issue still occurs?

**Comment by Hunt2176** [comment]
> Just to confirm, this is still happening with 2.20.3 (which resolved a similar issue)?  
 
Yes I am experiencing this on 2.20.3. It was not an issue previously on 2.18.

> Can you try replacing `NativeDatabase.createInBackground` or `driftDatabase` from `drift_flutter` with a simple `NativeDatabase.memory()` and see if the issue still occurs?

I can confirm I am still experiencing the issue with `NativeDatabase.memory()`

**Comment by simolus3** [comment]
That's good to know, thanks! The only change in behavior that comes to mind is that, in drift 2.18, transactions were actually opened (and locked the remaining database) when the first statement in the transaction starts. In later versions, we start a transaction (and lock the database) before even calling the `transaction` callback.

This alone shouldn't cause the issues you're seeing here, but maybe some of the transactions have code that implicitly relies on the old behavior. Are the transactions completely independent or is there anything in them that might depend on the other transaction progressing / completing? Can you share some of the code you're running in a transaction so that I can try to reproduce the issue?

**Comment by Hunt2176** [comment]
> Are the transactions completely independent or is there anything in them that might depend on the other transaction progressing / completing?

Not that I can tell. It deadlocks with 100% guarantee on 2.20.3 but downgrading to 2.18 works properly.

> Can you share some of the code you're running in a transaction so that I can try to reproduce the issue?

I unfortunately cannot share the code directly causing the issue due to it being for my work.

I have tried my best to copy the implementation out into its own demo. Unfortunately, it does work properly in the demo. I added comments where the deadlocks would normally occur in the main project. Hopefully there might still be some use in me sharing this.

[Demo Link](https://github.com/Hunt2176/drift-demo)

**Comment by Hunt2176** [comment]
I will also note, that there are query watch streams open during this time, but they are not reflected in this demo if that provides anymore information to you.

**Comment by dickermoshe** [comment]
Could we provide you with a couple of commit hashes for you to test this and help locate the commit which is causing this trouble?

**Comment by Hunt2176** [comment]
> Could we provide you with a couple of commit hashes for you to test this and help locate the commit which is causing this trouble?

Yes, I would happy to assist.

**Comment by dickermoshe** [comment]
Let's start with version 2.19

**Comment by dickermoshe** [comment]
After that we'll know which way to go.

**Comment by simolus3** [comment]
I think we can be more specific - I think 9ba81d53a014fb4cf101fbedb9e431297f611a2f is most likely the commit causing this. If the issue still occurs with the parent, that would be good to know because then I need to think about another cause.

But even with a confirmation that the commit is causing this, I still need to figure out how to reproduce this - the changes still look correct to me.

**Comment by Hunt2176** [comment]
> I think we can be more specific - I think [9ba81d5](https://github.com/simolus3/drift/commit/9ba81d53a014fb4cf101fbedb9e431297f611a2f) is most likely the commit causing this. If the issue still occurs with the parent, that would be good to know because then I need to think about another cause.
> 
> But even with a confirmation that the commit is causing this, I still need to figure out how to reproduce this - the changes still look correct to me.

The parent commit, [b1a5a11](https://github.com/simolus3/drift/commit/b1a5a11eef4d8d84c81e79bcf07c2fdb8c7ddaf1), still has the same issue.

**Comment by dickermoshe** [comment]
@simolus3 What's next?

https://github.com/simolus3/drift/compare/drift-2.18.0...b1a5a11

**Comment by simolus3** [comment]
Not what I've expected, so good to know! How hard is it for you to change drift versions repeatedly? If a bisect between drift 2.18.0. and 2.19.0 is possible, it would help a lot.

**Comment by dickermoshe** [comment]
@Hunt2176 

The quickest way to do this:

1. Clone the drift repo next to your project
```
├── drift
└── my_project
```
3. Add overrides to your pubspec.yaml
```yaml
dependency_overrides:
  drift_flutter:
    path: ../drift/drift_flutter
  drift:
    path: ../drift/drift
  drift_dev:
    path: ../drift/drift_dev
  drift_postgres:
    path: ../drift/extras/drift_postgres
  sqlparser:
    path: ../drift/sqlparser
```
4. Create a single test to validate this behavior
5. Create a test script in the drift repo `script.sh`
```bash
cd ../my_project/
flutter pub get
flutter test -N "test name"
```
6. Make executable
```bash
chmod +x ./script.sh
```
7. Run this:
```bash
git checkout b1a5a11
git bisect start

# Run the script and make sure it fails
./script.sh
# Make sure the exit code is not 0
echo $?

git bisect bad
git checkout 7d1430c

# Run the script and make sure it works
./script.sh
# Make sure the exit code is 0
echo $?

git bisect good
git bisect run ./script.sh
```

**Comment by Hunt2176** [comment]
> Not what I've expected, so good to know! How hard is it for you to change drift versions repeatedly? If a bisect between drift 2.18.0. and 2.19.0 is possible, it would help a lot.

I am very sorry for the confusion but it would seem I was incorrect yesterday.
After doing the bisect with the local repo, I was not experiencing the issue. However, going back to [9ba81d5](https://github.com/simolus3/drift/commit/9ba81d53a014fb4cf101fbedb9e431297f611a2f) does produce the issue. Seems I was having issues getting pub to do it correctly for me.

9ba81d53a014fb4cf101fbedb9e431297f611a2f is the first bad commit
commit 9ba81d53a014fb4cf101fbedb9e431297f611a2f
Author: Simon Binder <oss@simonbinder.eu>
Date:   Wed Jun 12 22:18:20 2024 +0200

    Lock right away in transaction and exclusively

 drift/CHANGELOG.md                              |  2 ++
 drift/lib/src/runtime/api/connection_user.dart  |  4 ++++
 drift/test/engines/delegated_database_test.dart | 18 ++++++++++++++++++
 drift/test/integration_tests/database_test.dart | 23 +++++++++++++++++++++++
 4 files changed, 47 insertions(+)

**Comment by kuhnroyal** [comment]
Looks like https://github.com/simolus3/drift/issues/3244 then.

**Comment by dickermoshe** [comment]
This commit was present in 2.19 too.

**Comment by simolus3** [comment]
And this issue also occurs in `NativeDatabase.inMemory`, the other issue was related to using a background isolate to host the database.

Ok, next try to track this down: Could you try adding print statements to the `insertFromHttp` calls like this:

```dart
    print('insertFromHttp: $resolvedEngine');
```

And then also to the transaction runner like this:

```dart
  final runner = TransactionRunner((toExecute) async {
    print('runner: ${db.resolvedEngine}');

    // Removing this transaction and running `toExecute` directly would prevent the deadlock
    return await db.transaction(() {
      return toExecute(db);
    }, requireNew: true);
  });
```

(or whatever the in-app equivalent of those locations is). In your test project, this prints

```
runner: Instance of 'DemoDatabase'
insertFromHttp: Instance of 'Transaction'
```

If `insertFromHttp` doesn't print `Instance of 'Transaction'` in your app, it must be something with async zones getting lost. I hope it's not that because these issues suck, but the whole thing about this being somewhat bizarre and impossible to reproduce in a smaller project could point towards a weird async issue and it would explain why the change causes a deadlock.

**Comment by Hunt2176** [comment]
Runner: Instance of 'EVDatabase'
Runner: Instance of 'Transaction'
insertFromHttp: Instance of 'Transaction'
insertFromHttp: Instance of 'Transaction'

**Comment by simolus3** [comment]
Sorry for the slow response - could you check whether the transactions are the same? E.g. `print('insertFromHttp: $resolvedEngine, ${identityHashCode(resolvedEngine)}');` in the dao and `print('runner: ${db.resolvedEngine}, ${identityHashCode(db.resolvedEngine)}');`?

And is the `Runner: Instance of 'Transaction'` because of a second `print` in the `transaction` block of the `TransactionRunner` callback?

**Comment by Hunt2176** [comment]
> Sorry for the slow response - could you check whether the transactions are the same? E.g. `print('insertFromHttp: $resolvedEngine, ${identityHashCode(resolvedEngine)}');` in the dao and `print('runner: ${db.resolvedEngine}, ${identityHashCode(db.resolvedEngine)}');`?

```
Runner: Instance of 'EVDatabase', 968504248
Runner: Instance of 'Transaction', 40210757
insertFromHttp: Instance of 'Transaction', 40210757
insertFromHttp: Instance of 'Transaction', 40210757
```

**Edit:**
As a side note; The instances are outside of the dao transactions but inside of the Runner's spawned nested transactions as attempting to spawn the dao transaction causes the deadlock.

> And is the `Runner: Instance of 'Transaction'` because of a second `print` in the `transaction` block of the `TransactionRunner` callback?

No, the Runner is being used to create transactions including nested transactions of the primary transaction. The way the Runner works in production is it takes a list of items to fetch and the dependencies needed to be able to build out the database since entities from the different endpoints are related to each other. What it is doing here is it sees there are two items that have no parent, thus they can both be fetched and inserted. 

Since it is creating the parent transaction and then begins running the nested transactions since I need everything inside of the parent transaction to rollback if any of the nested transactions to fail. Dependent transactions will not launch until the results from the prior transaction are received indicating the data has reached the database.

The transactional layout looks something like this:

```
Primary Transaction
|
| => Transaction A / No dependencies, starts immediately 
|    => Dao Transaction
| => Transaction B / No dependencies, starts immediately
|    => Dao Transaction
| => Transaction C / Depends on A, starts as soon as A is completed
|    => Dao Transaction
| => Transaction D / Depends on A, starts as soon as A is completed
|    => Dao Transaction
| => Transaction E / Depends on C, starts as soon as C is completed
|    => Dao Transaction
| ... etc.
```


Running it with the other top level item removed results in:
```
Runner: Instance of 'EVDatabase', 349848717
Runner: Instance of 'Transaction', 721396968
insertFromHttp: Instance of 'Transaction', 721396968
```

Where it then freezes again.

**Comment by simolus3** [comment]
And just to be sure, this `starts as soon as A is completed` check / awaition happens outside of any nested `transaction` block potentially used for transaction C and D? E.g it's not this:

```dart
Future<void> insertForC(Future completionOfA) async {
  print('insertFromHttp/C: ...')

  await transaction(() async {
    await completionOfA; // deadlock because this transaction might have spawned before the transaction used in insertForA
    // ...
  });
}
```

**Comment by HForbus** [comment]
> And just to be sure, this `starts as soon as A is completed` check / awaition happens outside of any nested `transaction` block potentially used for transaction C and D? E.g it's not this:
> 
> ```dart
> Future<void> insertForC(Future completionOfA) async {
>   print('insertFromHttp/C: ...')
> 
>   await transaction(() async {
>     await completionOfA; // deadlock because this transaction might have spawned before the transaction used in insertForA
>     // ...
>   });
> }
> ```

Correct, the runner keeps track of the required dependencies and spawns the transactions. The individual nested transactions are not aware of each other. Each time one of the nested transactions finishes the runner checks the dependency map and will then spawn any transactions that have that dependencies met now.

I will try to get a better sample of how this is setup within our code base for you. 

Thank you for again for your time looking into this.

**Comment by Hunt2176** [comment]
> And just to be sure, this `starts as soon as A is completed` check / awaition happens outside of any nested `transaction` block potentially used for transaction C and D? E.g it's not this:
> 
> ```dart
> Future<void> insertForC(Future completionOfA) async {
>   print('insertFromHttp/C: ...')
> 
>   await transaction(() async {
>     await completionOfA; // deadlock because this transaction might have spawned before the transaction used in insertForA
>     // ...
>   });
> }
> ```

Correct, the runner keeps track of the required dependencies and spawns the transactions. The individual nested transactions are not aware of each other. Each time one of the nested transactions finishes the runner checks the dependency map and will then spawn any transactions that have that dependencies met now.

I will try to get a better sample of how this is setup within our code base for you. 

Thank you for again for your time looking into this.

**Comment by Hunt2176** [comment]
@simolus3 I have updated my demo repo with a watered down version of our sync manager that we use. It's a little messy but hopefully it will show you how the dependencies work. 

[Demo Repo](https://github.com/Hunt2176/drift-demo)

Downside is the issue is still not present which is quite frustrating.

**Comment by Hunt2176** [comment]
@simolus3 I found something in the original that I had missed around the starting execution. It seems to now reproduce the issue. I have updated the demo repo again.

[Demo Repo](https://github.com/Hunt2176/drift-demo)

The difference between this and the Flutter app is that the demo exits seemingly because nothing is executing because everything is waiting.

**Comment by simolus3** [comment]
Thanks for following up! Adding `resolvedEngine` / `identityHashCode(resolvedEngine)` prints to the `queryExecutor` manager in `SyncManager` as well as in `runner()` (the function in `buildDependencyFuture`) now reveals the problem:

```
in queryExecutor, outside of transaction: Instance of 'DemoDatabase', 1014068316
Drift: Sent CREATE TABLE IF NOT EXISTS "table_a" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "name" TEXT NULL, "external_id" INTEGER NOT NULL UNIQUE); with args []
Drift: Sent CREATE TABLE IF NOT EXISTS "table_b" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "name" TEXT NULL, "external_id" INTEGER NOT NULL UNIQUE); with args []
Drift: Sent BEGIN TRANSACTION with args []
in queryExecutor, in transaction: Instance of 'Transaction', 137099187
in queryExecutor, outside of transaction: Instance of 'Transaction', 137099187
Drift: Sent SAVEPOINT s1 with args []
in queryExecutor, in transaction: Instance of 'Transaction', 530982602
in runner(): Instance of 'Transaction', 137099187
Starting DemoDriftEntityA
```

Notice that at the time `runner()` is called, the current transaction would be `530982602`. But `runner()` runs in the context of `137099187`, completing the deadlock.
I'll offer my least helpful comment first: This setup has always been broken. Waiting for us to open the transaction before any statements changes the observed behavior from "it might work or it might roll back the wrong transaction and silently cause data corruption" to the deadlock.
And as I suspected, it is a zone issue. Drift uses [`Zones`](https://api.dart.dev/stable/3.5.4/dart-async/Zone-class.html) (if you're not familiar with the concept, "thread locals for asynchronous functions") to remember which future runs in which transaction. The basic rule for zone propagation is that asynchronous callbacks run in the zone active when the callback was registered. So if you do this:

```dart
// Here: No transaction is active
final waitForTransaction = Completer();
final future = waitForTransaction.future.then((_) async {
  // Which means that here, no transaction is active!
  await doWorkInTransaction();
});

await transaction(() async {
  waitForTransaction.complete();
  await future; // Deadlock!
});
```

This is generally the behavior you want - we can't just make the current transaction global and need these scopes (think about e.g. a touch event happening while a transaction is processing concurrently, then `onTap` would run in a transaction for no reason).

Unfortunately, that's exactly how your `buildDependencyFuture` works (the returned anonymous function runs in a transaction, the other callbacks including `runner` do not).
I've only skimmed your code, and my understanding of the dependency tracker is not good enough to offer good solutions. I know it works if you do build the dependency future in the transaction, but I suspect you've deliberately split these stages?

```dart
  await manager.queryExecutor((db) async {
    await manager.queryExecutor((db) async {
      final starter = manager.buildDependencyFuture(db);
      await starter();
    });
  });
```

**Comment by Hunt2176** [comment]
Sorry for the delayed response. I can confirm that moving this code into the same transaction block has resolved the issue.


> I suspect you've deliberately split these stages?

Honestly, it was likely something left over from a refactor of some sort but everything is working as intended. I had to jump out of the actual runner's execution to find this bit that was the root cause.

Thank you again for your assistance!
