### ISSUE TITLE
drift.simonbinder.eu/cli/#exporting

### ISSUE THREAD

**Issue by ivanesi** [simolus3/moor#3264]
[drift.simonbinder.eu/cli/#exporting](https://drift.simonbinder.eu/cli/#exporting)

Exporting docs seems outdated. How to export a list of CREATE statements ?

**Comment by simolus3** [comment]
That command is supposed to work, what error do you get running it? If the command is unavailable, what `drift_dev` version are you on?

**Comment by ivanesi** [comment]
> drift_dev: ^2.15.0

```
% dart run drift_dev schema dump ./lib/database/app_database.dart 
Expected input and output files
```
```
% dart run drift_dev schema export
Could not find a subcommand named "export" for "dart run drift_dev schema".
```

**Comment by simolus3** [comment]
The `export` subcommand has been added in `drift_dev` 2.20.0, so it's possible that you're on an older version that doesn't have the command yet.

**Comment by ivanesi** [comment]
Thanks. I had and older dart sdk version so dart pub get installed old version of the drift packages by default.
