### ISSUE TITLE
Predefined sqlite databases in moor web

### ISSUE THREAD

**Issue by simolus3** [simolus3/moor#328]
Is there any way to use a similar approach for `moor_web`?

_Originally posted by @yshahak in https://github.com/simolus3/moor/issues/26#issuecomment-571605198_

**Comment by simolus3** [comment]
Moor stores sqlite data in two local storage keys: `moor_db_str_$name` and `moor_db_version_$name`, where name is the name passed to the `WebDatabase` constructor. The first one stores binary data, stored with [this conversion](https://github.com/simolus3/moor/blob/master/moor/lib/src/web/binary_string_conversion.dart#L7). The version key just stores the version you've set on the database.
In theory, it should be possible to manually set those fields before opening the `WebDatabase` to initialize data. Moor should expose a good api for that nonetheless.

**Comment by yshahak** [comment]
That's a neat detour indeed. I didn't think about it but it supposed to work.

**Comment by simolus3** [comment]
Done on `develop`, this will be in the next moor release. The new `initializer` parameter on `WebDatabase` is called when no database exists.
