### ISSUE TITLE
Flutter Service Worker is going away; Is this something we need to take into consideration and prepare for ?

### ISSUE THREAD

**Issue by RoarGronmo** [simolus3/moor#3293]
Got an "mass"-email today from David Iglesias Teixeira on "Flutter web's default Service Worker is going away".

See link: https://flutter.dev/go/web-cleanup-service-worker 

Is there anything we should take into consideration when using `drift` on web in near future, according to the up-coming changes ?

**Comment by simolus3** [comment]
Drift does not rely on the service worker in any way. Drift is also used on the new website in a Flutter example without a service worker. So I don't expect anything that drift users would have to take into consideration to come up.
