### ISSUE TITLE
Please pass in a language version to DartFormatter()

### ISSUE THREAD

**Issue by munificent** [simolus3/moor#3302]
In [drift_dev/lib/src/backends/build/drift_builder.dart](https://github.com/simolus3/drift/blob/develop/drift_dev/lib/src/backends/build/drift_builder.dart#L464), a call to `DartFormatter()` from the dart_style package is being used to format the generated code.

We're in [the process of](https://github.com/dart-lang/dart_style/issues/1403) moving dart_style to [a new formatting style](https://github.com/dart-lang/dart_style/issues/1253). That involves making the formatter [aware of the language version of what it's formatting](https://github.com/dart-lang/dart_style/issues/1402).

That in turn means that the library API now lets you pass in a language version. In dart_style 2.3.7 [you can pass in a language version but the parameter is optional](https://pub.dev/documentation/dart_style/latest/dart_style/DartFormatter/DartFormatter.html). In the forthcoming 3.0.0 release, that parameter will become mandatory. If you can, please update drift to start passing in a language version. If you know the language version of the code being parsed, pass that in. If you just want to always format the code at the latest language version, you can use [`DartFormatter.latestLanguageVersion`](https://pub.dev/documentation/dart_style/latest/dart_style/DartFormatter/latestLanguageVersion.html). When you do, make sure to update your dependency constraint on dart_style to `^2.3.7`.

Thank you!

**Comment by simolus3** [comment]
Thanks for taking the time to file these detailed issues! I have updated drift to include the language version in 4c896a58ae0ff41198edd9a27532db92dcf9f59f.

**Comment by munificent** [comment]
Thank you for the quick turnaround! :D
