### ISSUE TITLE
document validateDatabaseScheme usage on Web

### ISSUE THREAD

**Issue by alestiago** [simolus3/moor#3317]
**Description**

In the [example app](https://github.com/simolus3/drift/tree/develop/examples/app) the [validateDatabaseScheme](https://github.com/simolus3/drift/blob/develop/examples/app/lib/database/connection/web.dart) is documented for Web as:

```dart
  // Unfortunately, validating database schemas only works for native platforms
  // right now.
  // As we also have migration tests (see the `Testing migrations` section in
  // the readme of this example), this is not a huge issue.
```

However, there is no documentation of this within the Dart Doc for `validateDatabaseScheme` (see [Dart Doc Drift Dev](https://pub.dev/documentation/drift_dev/latest/api_migrations/VerifySelf/validateDatabaseSchema.html)); neither on the [Drift for web](https://drift.simonbinder.eu/platforms/web/#supported-browsers) page.

**Comment by simolus3** [comment]
I've taken this opportunity to finally implement runtime schema validation on the web.
