### ISSUE TITLE
use sql query in .moor file with a table declared in dart code

### ISSUE THREAD

**Issue by 32mandev** [simolus3/moor#332]
Is it possible to define a sql query in a .moor file which use a table declared in dart? 
(ie use the .moor file only for some queries and not for declaring the tables)

I tried and got an error...

**Comment by simolus3** [comment]
It's possible, with the current limitation that files you import from moor must be imported from the `@UseMoor` and `@UseDao` files. So let's say you had three files: `a.dart`, `b.moor` and `c.dart`. In that case,
```dart
// a.dart
@UseMoor(include: {'b.moor'})
class Database extends _$Database
```
```sql
-- b.moor
import 'c.dart';
```
```dart
// c.dart
class SomeTable extends Table {
  // ...
```
would _NOT_ work. But if you change `a.dart` to
```dart
// a.dart, updated
import 'c.dart'; // import here so that the moor file can import it

@UseMoor(include: {'b.moor'})
class Database extends _$Database
```
it should work.

------

This is a limitation of Dart's build system. There's a more recent version available that doesn't have this limitation, but it's in conflict with the `analyzer_plugin` package moor also uses. I've opened a tiny [PR to fix this](https://github.com/dart-lang/sdk/pull/39417) around two months ago, but so far not much happened :( This is also blocking #103, so you can believe it's very annoying for me as well.

**Comment by simolus3** [comment]
This will be supported without any restrictions in the next moor release.
