### ISSUE TITLE
Cannot create a strict table without the row ID

### ISSUE THREAD

**Issue by JamesChenX** [simolus3/moor#3324]
**Describe the bug**

Cannot create a strict table without the row ID using Drift as the SQL constructed incorrectly in `_writeCreateTable` :
https://github.com/simolus3/drift/blob/d9c9ed8cf7df086f822c412cbaa8aeaa691f9933/drift/lib/src/runtime/query_builder/migration.dart#L350-L355

, which should be:

```dart
    if (dslTable.withoutRowId) {
      context.buffer.write(' WITHOUT ROWID');
      if (dslTable.isStrict) {
        context.buffer.write(', STRICT');
      }
    } else if (dslTable.isStrict) {
      context.buffer.write(' STRICT');
    }
```

**Comment by simolus3** [comment]
Good catch, thanks for the report!
