### ISSUE TITLE
Query watching gets stuck when using Isolate sharing and hot restarting

### ISSUE THREAD

**Issue by clragon** [simolus3/moor#3339]
**Describe the bug**

This is a fun one!

1. My app init process relies on a select.watch.firstOrNull of a Query of my database
2. This works fine since Drift will send the query when the stream is subscribed to for the first time
3. When I use a ` DriftNativeOptions(shareAcrossIsolates: true)` and hot restart my app, it no longer initializes!

Why is that? For some reason, the query result is no longer sent when the stream is opened.
Turning off share across isolates fixes this. This was tested on a Windows machine.

**Comment by simolus3** [comment]
Just to confirm before looking into this deeper, `shareAcrossIsolates` causes the issue even without any other isolates using the database?

I would also generally expect streams and database instances to survive hot reloads, could you check whether a new database is opened after the reload? Just knowing the general setup and how it interacts with hot reloads should help me track this down more easily.

**Comment by clragon** [comment]
Yes, gladly.

First I must note that I made a terminology error; This is about hot restarting, not hot reloading. 

The setup for the app on Windows doesnt include any background processes, so there is only one database isolate running.
I have quickly thrown a print statement into the `databasePath` callback of `DriftNativeOptions` and I can observe that this is only called exactly once, regardless of how many hot restarts I execute. The database is initialized in the main method, which is called each hot reload.
From this I think I can confirm that isolates do survive hot restarts. 

However, doing a quick lookup on the flutter repo issues: https://github.com/flutter/flutter/pull/52149 we can see that isolates should not survive a hot restart. Perhaps the IsolateNameServer keeps them alive. 

Is there an easy way to confirm whether drift isolates are running?
IsolateNameServer doesnt include a way to list available ports.

**Comment by kuhnroyal** [comment]
I have traditionally been clearing the IsolateNameServer when `kDebug == true` and starting a new Drift isolate. I think this is still required.

**Comment by kuhnroyal** [comment]
```dart
    if (isMain && kDebugMode && IsolateNameServer.lookupPortByName(_databasePortName) != null) {
      logger.info('$isolateName - Clearing isolate port mapping after hot restart');

      /// Hot restarts kills all the isolates but does not remove the
      /// port name mapping. We need to manually remove this, but ONLY
      /// in the main isolate.
      IsolateNameServer.removePortNameMapping(_databasePortName);
    }
  ```

**Comment by simolus3** [comment]
I can reproduce this with an example app, we're hitting an infinite loop here:

https://github.com/simolus3/drift/blob/b2a0d50252be3de8bc0f4cc04bc2ecdbb7e044ca/drift_flutter/lib/src/native.dart#L56-L67

We can't really assume that the isolate is unreachable because of the timeout there alone, it could also be paused on a breakpoint (in which case we do want to retry instead of starting another competing isolate).
One thing that should work more reliably (I hope lol, who knows how isolates work) is pinging the control port of the drift isolate with a timeout and immediate priority. At least from some testing the isolate seems to respond to that even when paused.

**Comment by miti-mio** [comment]
I recently encountered the same problem. Has it been resolved yet?

**Comment by simolus3** [comment]
The linked commit is supposed to fix this and did fix it in my testing, but that was a while ago. I'm not sure if a more recent Flutter update broke things again. Can you try setting a breakpoint in the snippet linked above and see if you run into the infinite loop when connecting?
