### ISSUE TITLE
Custom type documentation has invalid anchors

### ISSUE THREAD

**Issue by alestiago** [simolus3/moor#3349]
**Description**

The [Custom Types Drift documentation](https://drift.simonbinder.eu/sql_api/types/) has multiple invalid anchors.

**Aditional info**

- Screenshot of the documentation page highlighting one of the invalid anchors.
<img width="954" alt="Screenshot 2024-11-21 at 11 51 10" src="https://github.com/user-attachments/assets/2366e712-2a36-4395-9a34-6a7031da8abf">

**Comment by simolus3** [comment]
Thanks for the report! I've fixed this on `develop`, the changes will be deployed with the next drift release (hopefully soon :crossed_fingers:).
