### ISSUE TITLE
Join only one item

### ISSUE THREAD

**Issue by robotoss** [simolus3/moor#335]
Good day,
We need to gets all Routes with all points of coordinates from this route to Create route line

we have 2 table:
Firts is Routes
Second is RoutesCoordinates

and class:

```
class RouteWithCoordinates{
  final Route route;
  final List<RouteCoordinate> routesCoordinates;

  RouteWithStops({
    @required this.route,
    @required this.routesCoordinates,
  });
```
Here's the code we wrote:
```
Future<List<RouteWithCoordinates>> getAllRouteWithCoordinates() async{
      final coordinates = alias(routeCoordinates, 'r');
      final querys = await select(routes).join([
        leftOuterJoin(coordinates, coordinates.routeId.equalsExp(routes.id)),
      ]).get();

      return querys.map((resultRows) {
        List<RouteCoordinate> routesList =  List();
        routesList.add(resultRows.readTable(coordinates));
        return RouteWithCoordinates(
          route: resultRows.readTable(busRoutes),
          routesCoordinates: routesList,
        ); 
      }).toList();
}
```

but we get only one coordinate in 'coordinates', although there are 40 points in the database

**Comment by simolus3** [comment]
`resultRows.readTable` will only return a single row - it's not possible to extract more than that. So `routesList` will also only ever have one item.

When you do `routes LEFT OUTER JOIN route_coordinates` and a route has multiple coordinates, there will be multiple rows with the same route, each of them with a different coordinate. So I assume the 40 points exist somewhere, they're just splitted across 40 `RouteWithCoordinates` objects.

In this case, I'd suggest to first select all routes, then use a [custom query](https://moor.simonbinder.eu/docs/using-sql/custom_queries/#statements-with-a-generated-api) or a moor file to create a `SELECT r.* FROM route_coordinates r WHERE EXISTS (SELECT * FROM routes ON r.route_id = routes.id)` query (putting the query into the `@UseMoor` annotation will likely be the easiest approach). By running that query and a `select(routes).getAll()`, you can get all routes and all coordinates referenced by some route. You could merge both results into a list of `RouteWithCoordinates` objects in Dart.

**Comment by robotoss** [comment]
We write:
```
@UseDao(tables: [
  BusRoutes,
  BusRouteCoordinates
],
queries: {
  'coordinatesByRoute':
  'SELECT r.* FROM bus_route_coordinates r WHERE EXISTS (SELECT * FROM bus_routes ON r.bus_route_id = bus_routes.id) ;'
}
```
We get:
```
Error while trying to parse coordinatesByRoute: line 1, column 80: Error: Expected closing paranthesis to finish EXISTS expression}
  ╷
1 │ SELECT r.* FROM bus_route_coordinates r WHERE EXISTS (SELECT * FROM bus_routes ON r.bus_route_id = bus_routes.id) ;
  │                                                                                ^^
  ╵, #0      ParserBase._error (package:sqlparser/src/reader/parser/parser.dart:143:5)
```

If we use:
```
@UseDao(tables: [
  BusRoutes,
  BusRouteCoordinates
],
queries: {
  'coordinatesByRoute':
  'SELECT r.* FROM bus_route_coordinates r WHERE r.bus_route_id = 5;';'
}
```
We correct get all Coordinates with routeId 5

Our code at now look like:
 ```
   Future<List<RouteWithCoordinates>> getAllRouteWithCoordinates() async {
    final coordinates = alias(busRouteCoordinates, 'r');
    
    final querys = await select(busRoutes).get();
    final test = await coordinatesByRoute();

    return querys.map((resultRows) {
      return RouteWithCoordinates(
          busRoute: resultRows,
          busRoutesCoordinates: test,
    }).toList();
  }
```

**Comment by simolus3** [comment]
> `Error while trying to parse coordinatesByRoute`

Stupid me, that should have been a `WHERE r.route_id = routes.id` in the nested query, no `ON`.

After the query works so that all coordinates are selected, you could do this in Dart (requires the [collection](https://pub.dev/packages/collection) package)
```dart
final querys = await select(busRoutes).get();
// the query method selecting all coordinates that appear in any route
final routeCoordinates = await allCoordinates(); 

final coordinatesByRoute = groupBy(routeCoordinates, (c) => c.routeId);

return querys.map((row) {
  return RouteWithCoordinates(
    busRoute: row,
    busRouteCoordinates: coordinatesByRoute[row.id],
  );
});
```

One final thing: I'd recommend to enable the `compact_query_methods` [build option](https://moor.simonbinder.eu/docs/advanced-features/builder_options/) and then use `await allCoordinates().get()` instead of `await allCoordinates()`. In the next breaking moor release that will be the only option, so it can be a good option to enable it now while you're getting started.
