### ISSUE TITLE
Type inference when using CAST on NULL in a UNION

### ISSUE THREAD

**Issue by frankvollebregt** [simolus3/moor#3351]
**Describe the bug**
I might have created a bit of an edge case I think ;)

In my code, I am using a statement like this:
```sql
-- after generation, value is an int?
SELECT CAST(NULL AS INT) AS value;
```
Which, as expected, results in `value` being an `int?` equal to `null`. If I fill it with a value that is guaranteed to be non-null, it becomes an `int`, also in line with expectations.

But once I use a `UNION`, things get a bit unexpected:
```sql
-- after generation, value is an int
SELECT CAST(NULL AS INT) AS value

UNION

SELECT CAST(NULL AS INT);
```
Now, the type of `value` is `int`, and Drift believes it can no longer be `null`.

**Comment by simolus3** [comment]
Nice catch!
