### ISSUE TITLE
TypeConverter's generated code does not work

### ISSUE THREAD

**Issue by CaptainDario** [simolus3/moor#3353]
I am trying to implement a custom TypeConverter.
I want that my text column is automatically compressed and decompressed.
For this I  have this class

```dart
import 'dart:convert';
import 'package:archive/archive.dart';
import 'package:drift/drift.dart';



/// Class to compress and decompress text columns in SQLite
class ZlibTextConverter extends TypeConverter<String, Uint8List> {

 const ZlibTextConverter();

  // Compress the input string into a byte array for storage
  @override
  Uint8List toSql(String value) {
    final bytes = utf8.encode(value);
    final compressed = GZipEncoder().encode(bytes);
    return Uint8List.fromList(compressed);
  }

  // Decompress the stored byte array back into a string
  @override
  String fromSql(Uint8List fromDb) {
    final decompressed = GZipDecoder().decodeBytes(fromDb);
    return utf8.decode(decompressed);
  }

}
```

In my table definition I use this class as follows

```dart
import '../converters/zlib_text_converter.dart';
import 'package:drift/drift.dart';



/// Contains the kanji entries and links to the radicals table
@TableIndex(name: 'kanjiVGKanji', columns: {#kanjiVGKanji})
class KanjiVGTable extends Table {
  
  /// id of this entry
  IntColumn get id => integer().autoIncrement()();

  /// the kanji character of this entry
  /// 
  /// **Note:** this column is indexed
  TextColumn get kanjiVGKanji => text().withLength(min: 1)();

  /// The svg data of this kanji
  BlobColumn get kanjiVGSVG => blob().map(const ZlibTextConverter())();
}
```

When running the generator `dart run build_runner build --delete-conflicting-outputs`

I get this error

``` bash
lib/database/dakanji_db.g.dart:752:13: Error: Couldn't find constructor 'ZlibTextConverter'.
      const ZlibTextConverter();
```

I am trying to follow [this guide](https://drift.simonbinder.eu/type_converters/#using-converters-in-dart) and I cannot see what is different between my implementation and the instructions which makes me think something is going wrong.

**Comment by simolus3** [comment]
Is the table in a different Dart file than the database? Unfortunately, we can't generate imports in generated part files (which might explain the `Couldn't find constructor` error). If that's indeed the problem, you can fix it by importing the converter into the database file or enabling [modular code generation](https://drift.simonbinder.eu/generation_options/modular/).

**Comment by CaptainDario** [comment]
The converter was not defined in the table file. Adding an import there fixed the problem, thank you!
