### ISSUE TITLE
Not possible to run example/app

### ISSUE THREAD

**Issue by fexd12** [simolus3/moor#3355]
when try to running example/app on web im getting this error

runned with flutter run -d chrome --wasm --release but this error occurs without the flag wasm as well.

Target dart2wasm failed: ProcessException: Process exited abnormally with exit code 64:
lib/database/connection/web.dart:2:8: Error: Error when reading
'/Users/asd/.pub-cache/hosted/pub.dev/drift_dev-2.21.2/lib/api/migrations_web.dart': No such file
or directory
import 'package:drift_dev/api/migrations_web.dart';
       ^
lib/database/database.g.dart:691:28: Error: The argument type 'int?' can't be assigned to the
parameter type 'int' because 'int?' is nullable and 'int' isn't.
              .fromSql(row.readNullable<int>('color')),
                           ^
lib/database/connection/web.dart:19:11: Error: Method not found: 'VerifySelf'.
    await VerifySelf(database).validateDatabaseSchema(sqlite3: sqlite);
          ^^^^^^^^^^

**Comment by simolus3** [comment]
Works for me. Did you resolve dependencies with `melos`? The example app on the `develop` branch uses new `drift_dev` APIs that have not yet been released, so it needs to use the dependency overrides to use drift packages from path.

The app from [the last release](https://github.com/simolus3/drift/tree/drift-2.20.3/examples/app) should work with the latest `drift` and `drift_dev` packages as they have been released to pub.dev.
