### ISSUE TITLE
mode InsertMode.insertOrReplace creates duplicate key values

### ISSUE THREAD

**Issue by verscph** [simolus3/moor#3361]
When using `await into(generals).insert(entry, mode: InsertMode.insertOrReplace);` existing keys are not replaced but overwritten.

Using drift 2.22.0 with Flutter 3.24.5.

Code:
```
Future<void> addGeneralEntry(General entry) async {
    // General class
    // const General({required this.key, required this.value});

    print('addGeneralEntry: ${entry.key} ${entry.value}');
    await into(generals).insert(entry, mode: InsertMode.insertOrReplace);

    print('addGeneralEntry: ${entry.key} ${entry.value}');
    await into(generals).insert(entry, mode: InsertMode.insertOrReplace);

    final entries =
        await (select(generals)..where((t) => t.key.equals(entry.key))).get();

    for (General g in entries) {
      print('getGeneralEntry: ${g.key} ${g.value}');
    }
  }
```

Debug output:
```
flutter: addGeneralEntry: loggedIn true
flutter: addGeneralEntry: loggedIn true
flutter: getGeneralEntry: loggedIn true
flutter: getGeneralEntry: loggedIn true
```

I would expect:
```
flutter: addGeneralEntry: loggedIn true
flutter: addGeneralEntry: loggedIn true
flutter: getGeneralEntry: loggedIn true
```

Using `await into(generals).insert(entry, mode: InsertMode.replace);` results in the same output.

Can you pls check?

**Comment by simolus3** [comment]
Could you share the definition for the `Generals` table? Is `key` declared as a unique or primary key there?

**Comment by verscph** [comment]
```dart
class Generals extends Table {
  TextColumn? get key => text()();
  TextColumn? get value => text()();

  @override
  Set<Column> get primaryKey => {key!};
}
```

**Comment by simolus3** [comment]
Columns themselves should not be nullable - these fields describe the column itself, which has to exist. If you want to have columns that can store null values, explicitly declare them with `nullable()` to allow that. Allowing null values to appear in primary keys also leads to confusing behavior though (since nulls are not equal in SQL), this is also forbidden in some databases.

Making the columns nullable and then using `key!` in the primary key confuses the drift builder:

```
[WARNING] drift_dev on example/main.dart:
Unexpected entry in expression.elements: key!
```

This means that we're unable to analyze the primary key added to the table class, meaning that it will effectively be ignored. Declaring the table without nullable columns would work, but you'll have to delete the database or write a migration to apply the changes:

```dart
class Generals extends Table {
  TextColumn get key => text()();
  TextColumn get value => text()();

  @override
  Set<Column> get primaryKey => {key};
}
```

**Comment by verscph** [comment]
Thanks for your help! We inherited the app from another team, so our experience with your package is very limited. Any tips are very welcome!

**Comment by verscph** [comment]
@simolus3 this is how we fixed it:

* new table definition
```
class Generals extends Table {
  TextColumn get key => text()();
  TextColumn get value => text()();

  @override
  Set<Column> get primaryKey => {key};
}
```
* incremented schemaVersion
`int get schemaVersion => 2;`
* recreated the table in onUpgrade
```
  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      beforeOpen: (details) async {
        await customStatement('PRAGMA foreign_keys = ON;');
      },
      onUpgrade: (migrator, from, to) async {
        Logger().d('onUpgrade: ${from} -> ${to}');

        for (final table in allTables) {
          migrator.deleteTable(table.actualTableName).then((value) => migrator
              .createTable(table)
              .then((value) => this.markTablesUpdated([table].toSet())));
        }
      },
    );
  }
```
The database entries where created/updated upon App launch anyway, so that was not the issue.

tx for your help!

**Comment by simolus3** [comment]
Re-creating the tables is fine, but you should await the migrator calls :) Either add an `await` before the future chain in the loop or write them explicitly:

```dart
for (final table in allTables) {
  await migrator.deleteTable(table.actualTableName);
  await migrator.createTable(table);
  // No need to call markTablesUpdated here, that's just for query streams
}
```

**Comment by verscph** [comment]
doesn't the `.then((value) => ...)` handle the future chain?

**Comment by simolus3** [comment]
It handles the chain, but you still need to await the whole thing, you're missing an await here:

```dart

        for (final table in allTables) {
          // | this one here
          await migrator.deleteTable(table.actualTableName).then((value) => migrator
              .createTable(table)
              .then((value) => this.markTablesUpdated([table].toSet())));
        }
```

The `onUpgrade` function should not complete before all the migrations are complete, but it would not wait for the chained future without the await.
