### ISSUE TITLE
rootNode Returns Invalid Statement When Parsing SQL with Outer Join

### ISSUE THREAD

**Issue by Sarath-Chandran-P** [simolus3/moor#3365]
**Description:**
When parsing an SQL statement containing an outer join, the rootNode property of the parsed statement returns an invalid or unexpected value.

**Steps to Reproduce:**
1. Parse the following SQL using the engine.parse(sql) method:
```
select job.*  

from per_jobs_f job,  
     fnd_setid_sets sets  
where sets.set_id(+) = job.set_id;
```

2. Access the rootNode of the parsed statement:
```
parsedStatement = engine.parse(sql);  
final statement = parsedStatement.rootNode;
```

**Expected Behavior:**
The rootNode should correctly represent the parsed SQL structure, including the outer join.

**Actual Behavior:**
The rootNode returns an invalid or incorrectly structured statement.

Please investigate and provide a fix or workaround.

**Comment by simolus3** [comment]
The join is not the problem, this is:

> where sets.set_id(+) = job.set_id;

That's not valid SQL, and sqlparser tells you so in `ParseResult.errors`.
