### ISSUE TITLE
Batch example fails to compile

### ISSUE THREAD

**Issue by Monotoba** [simolus3/moor#337]
The folowing code snippet offered as an example of using batch gives the following error in the IDE:

Two positional arguments expected but one found.

From looking at the code, insertAll is expecting a TableInfo and a list of Companions.  If this is correct the example should be updated accordingly.

**Comment by simolus3** [comment]
Yes, the first argument should be a table info (`todos` in this case). Thank you for the report, I've fixed the problem and the website will rebuild shortly.
