### ISSUE TITLE
Default Flutter Drift Database in My Documents on Windows

### ISSUE THREAD

**Issue by dickermoshe** [simolus3/moor#3372]
This is really bad. There should be an enum that defaults to the current folder for backwards compat.
The default should change for drift 3.0

**Comment by simolus3** [comment]
>  The default should change for drift 3.0

Given that this lives in `drift_flutter`, we can be more aggressive about breaking changes and do a breaking release for that package only.

**Comment by dickermoshe** [comment]
Good point, I think this is worthy of a breaking release
