### ISSUE TITLE
Documentation issue: Getting Started - some conflicting information + auto-updating streams

### ISSUE THREAD

**Issue by ignis-victorious** [simolus3/moor#3373]
**Description**

Hi, just a few points that i think would help clarify the explanation on the Drift pages:

In the page (https://drift.simonbinder.eu/setup/)  under the title "Database class":

1)  The link to "Dart tables" brings you back to the top of the page. It should be pointing at (https://drift.simonbinder.eu/dart_api/tables/). Incidentally, the one under the title "Next steps", at the bottom of the page, seems to work fine.

2) The explanation: "To make the database useful, we'll also add a simple table to it. This table, TodoItems, can be used to store todo items for a todo list app." indicates that one table is created. Yet code for the creation of two tables (TodoItems and TodoCategory) appears in the example provided. For beginners this wording might prove a little confusing! 

Also, not less important, for the "support for auto-updating streams" there is not a specific page focused mainly on this topic. Many developer will chose Drift over other sqflite or other packages for its responsive capabilities. I guess that a little more help in the Docs would go a long way, or at least it would have done for me!

Finally, as an option, it would be nice to have a pointer to the "previous/next page." at the bottom of each page. It is not critical but a nice to have. It would be less cumbersome to navigate that way rather than returning to the menu each time, often after you forgot which pages you have already visited.

PS I would like to close with a big thank you as the Drift documentation is well written and complete. Whoever put it together did a great job and i am really grateful.

**Comment by simolus3** [comment]
Thank you for sharing your feedback, these are really good points! I have fixed all of them on the `develop` branch now, they will be published with the next drift release.
