### ISSUE TITLE
The Attribute "companion" of annotation @DataClassName does not affect the name of the generated companion object in any way.

### ISSUE THREAD

**Issue by sachebotarev** [simolus3/moor#3375]
**Describe the bug**

Hi,

I found that the "companion" attribute of the @DataClassName annotation does not affect the name of the generated companion object.
This is my example. In fact, it’s an example from the test drift/drift_dev/test/writer/data_class_writer_test.dart
```dart
import 'package:drift/drift.dart';

part 'main.g.dart';

@DataClassName('FirstDataClass', companion: 'FirstCompanionClass')
class FirstTable extends Table {
  TextColumn get foo => text()();
  IntColumn get bar => integer()();
}

@DataClassName.custom(
    name: 'SecondDataClass', companion: 'SecondCompanionClass')
class SecondTable extends Table {
  TextColumn get foo => text()();
  IntColumn get bar => integer()();
}

@DataClassName.custom(companion: 'ThirdCompanionClass')
class ThirdTable extends Table {
  TextColumn get foo => text()();
  IntColumn get bar => integer()();
}

@DriftDatabase(
  tables: [FirstTable, SecondTable, ThirdTable],
)
class Database extends _$Database {}

```
dependencies 
```yaml
dependencies:
  drift: ^2.22.1

dev_dependencies:
  drift_dev: ^2.22.0
  build_runner: ^2.4.13
  lints: ^5.0.0
  test: ^1.24.0

```

I expect my companion objects in the example to be named FirstCompanionClass and SecondCompanionClass, but they are named FirstTableCompanion and SecondTableCompanion, as if I did not specify any parameter at all.

Here are snippets from the main.g.dart file.
```dart
class FirstTableCompanion extends UpdateCompanion<FirstDataClass> {
  final Value<String> foo;
  final Value<int> bar;
  final Value<int> rowid;
  const FirstTableCompanion({
    this.foo = const Value.absent(),
    this.bar = const Value.absent(),
    this.rowid = const Value.absent(),
  });
// ------------

class SecondTableCompanion extends UpdateCompanion<SecondDataClass> {
  final Value<String> foo;
  final Value<int> bar;
  final Value<int> rowid;
  const SecondTableCompanion({
    this.foo = const Value.absent(),
    this.bar = const Value.absent(),
    this.rowid = const Value.absent(),
  });
```
I found the reason for this behavior, and it’s related to this: https://github.com/simolus3/drift/pull/2913.

Either I’m missing something, or this is an extremely strange pull request.

* 1. 
<img width="862" alt="1" src="https://github.com/user-attachments/assets/9f4bba70-02b9-4c47-9c66-b5152a835734" />
It should be here, the attribute is called "companion", not "companionName"

```dart
    final companionName =
        dataClassName?.getField('companion')?.toStringValue();
```
* 2.
<img width="792" alt="2" src="https://github.com/user-attachments/assets/401f4428-96a8-411a-9caa-1656f1b5784a" />
Here, the class name (if specified in companion) is used as a base, which is very strange because the word “Companion” will always be appended to the class name, preventing you from naming the class as you wish.

I think there must be something like this here
```dart
AnnotatedDartCode companionType(DriftTable table) {
  final baseName = writer.options.useDataClassNameForCompanions
      ? table.nameOfRowClass
      : table.baseDartName;
  final name = table.nameOfCompanionClass ?? '${baseName}Companion';

  return generatedElement(table, name);
}

```
* 3. 
<img width="882" alt="3" src="https://github.com/user-attachments/assets/a98046d9-5a3f-4bea-8351-fc052ce3ee97" />

This test describes incorrect behavior. 

In this pull request, several other files are also changed, but I haven’t had the chance to analyze them yet.

Please take a look. If my conclusions are correct, please correct the errors if possible, or if that’s difficult or not a priority, I could try to prepare a fix.

**Comment by simolus3** [comment]
Good catch and analysis, thanks for the detailed description! I definitely didn't review the test assertions as carefully as I should have, that's my mistake. The linked commit fixes both problems.

**Comment by sachebotarev** [comment]
Thank you very much for the correction and the "drift" in general.
