### ISSUE TITLE
Support for 64 bit integers

### ISSUE THREAD

**Issue by blaugold** [simolus3/moor#338]
Since SQLite stores up to 64 bit wide integers, [sqlite3_column_int_native_t](https://github.com/simolus3/moor/blob/master/moor_ffi/lib/src/bindings/signatures.dart#L59) could return `Int64`. Is there a limitation which requires using `Int32`?

**Comment by simolus3** [comment]
Good point, thanks! There are special 64 bit functions to bind and load integers, in the next moor_ffi version we're going to use those.
