### ISSUE TITLE
feat: allow providing a temp directory

### ISSUE THREAD

**Issue by mrverdant13** [simolus3/moor#3385]
## Details

Internally, the `driftDatabase` function that builds a `QueryExecutor` uses the `getTemporaryDirectory` function from the `path_provider` package.

In tests, this results in some warnings:
`MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)`

## Proposal

Allow devs to provide the desired temporal directory.

**Comment by simolus3** [comment]
`driftDatabase()` is for real devices and not suitable for unit tests. Drift has pretty good test support though, did you check [this article](https://drift.simonbinder.eu/testing/)?

**Comment by mrverdant13** [comment]
Thanks for the quick reply, @simolus3 ! 💙 

For unit testing, I totally get that in-memory database instances are quite handy.

Nevertheless, I am working on some E2E tests that build up database instances based on different conditions, so we need to check the actual resulting database state/snapshots, which means we need to actually interact with the database.

As a workaround for now, we are overriding the underlaying platform interfaces for path provider (i.e. we are using the `path_provider_platform_interface` package). However, providing a temp folder in advance would be beneficial so we can also have more control over these tech details.

Is there maybe another approach for these kinds of scenarios?

**Comment by simolus3** [comment]
In the next version (as of dd77435939ce06ad3da23dc97e083537c1ff5431), you'll be able to pass a custom temporary directory (or a function returning null which is more appropriate for test scenarios not running in a sandbox) for `drift_flutter`.
