### ISSUE TITLE
Best way to save data from a model in their respective fields in the table

### ISSUE THREAD

**Issue by On365** [simolus3/moor#339]
I'm sorry if I got something spelled wrong, I used google translator.

I have a **`List<UserModel> user = service.getdata`;**  and would like to know what is the best way to save each item in this list to a table.

**Model**
<img width="151" alt="Captura de Tela 2020-01-12 às 08 09 50" src="https://user-images.githubusercontent.com/18447092/72217885-ef60bf80-3512-11ea-8ec3-b44a68df6d62.png">
The table has the same fields as the model.

I know I could create a method and do:

table.id = user.id;
table.name = user.name;
.
.
.
table.nat = user.nat;

but I know this is not the best way, is there any way to iterate each field of the model and save it to its respective field in the table?

**Comment by On365** [comment]
I will try to do what is described in https://github.com/simolus3/moor/issues/263

**Comment by simolus3** [comment]
> Is there any way to iterate each field of the model and save it to its respective field in the table?

Not currently, no. Apart from the issue you linked, #114 tracks an alternative approach that would generate tables from model classes you already have.

At the moment, you'd have to write your own mapping function from model classes to moor rows or `UpdateCompanion`s. I'll close this issue, but let me know if you have any other questions.
