### ISSUE TITLE
Export Data Classes to a Specific Folder

### ISSUE THREAD

**Issue by iampopal** [simolus3/moor#3390]
## Description

I have a class `Users` that extends `Table` in the Drift package. This generates a data class named `User` with methods such as `toJson`, `fromJson`, `copyWith`, and all fields.

I want to export all these generated data classes to a specific folder, similar to how [Serverpod](https://github.com/serverpod/serverpod) has a `client` folder. This will allow us to share the data classes as a client folder with our front-end developer.

## Expected Behavior

- All generated data classes should be exported to a specified folder.
- The folder structure should resemble Serverpod's `client` folder.

## Steps to Reproduce

1. Create a class `Users` that extends `Table`.
2. Generate the data class `User`.
3. Configure Drift to export the generated data classes to a specified folder.

## Additional Context

This feature will help in organizing the generated data classes and make it easier to share them with frontend developers.

Thank you for your assistance.

**Comment by simolus3** [comment]
It's not possible to generate parts of the drift code across multiple files. You can instruct drift to [generate _all_ of its code into](https://www.simonbinder.eu/posts/build_directory_moves/#generating-into-a-directory-with-source_gen) a specific folder, but since we're generating `part` files, you don't get the data classes in isolation.

The only other option I see is to use [existing row classes](https://drift.simonbinder.eu/dart_api/rows/#custom-dataclass) - so you'd copy the drift-generated `User` into its own directory _once_ and then add `@UseRowClass(User)` to the table to stop drift from generating its own table class in favor of the copy. This allows sharing data classes between the database and other parts of the stack.

**Comment by iampopal** [comment]
Thank you so much.

**Comment by iampopal** [comment]
I was thinking to copy db.g.dart file into another repository. but the db.g.dart file is directly linked with db.dart which holds classes of all.

**Comment by simolus3** [comment]
Maybe [modular code generation](https://drift.simonbinder.eu/generation_options/modular) could help with that a bit?

**Comment by iampopal** [comment]
Can I have an Example of @UseRowClass(User). I think this will be useful?

**Comment by iampopal** [comment]
is it possible to use @UserRowClass(User) without 

```
class Account extends DataClass implements Insertable<Account> {
...
}
```

extending to DataClass and Insertable.

**Comment by iampopal** [comment]
If I make user class as the following. will it work:

```
class User {
  final int? id;
  final int userTypeId;
  final String? role;
  const User({
    this.id,
    required this.userTypeId,
    this.role,
  });

  User copyWith({
    int? id,
    int? userTypeId,
    String? role,
  }) {
    return User(
      id: id ?? this.id,
      userTypeId: userTypeId ?? this.userTypeId,
      role: role ?? this.role,
    );
  }

  Map<String, dynamic> toMap() {
    final result = <String, dynamic>{};

    if (id != null) {
      result.addAll({'id': id});
    }
    result.addAll({'userTypeId': userTypeId});
    if (role != null) {
      result.addAll({'role': role});
    }

    return result;
  }

  factory User.fromMap(Map<String, dynamic> map) {
    return User(
      id: map['id']?.toInt(),
      userTypeId: map['userTypeId']?.toInt() ?? 0,
      role: map['role'],
    );
  }

  String toJson() => json.encode(toMap());

  factory User.fromJson(String source) => User.fromMap(json.decode(source));
}
```

@simolus3 waiting for a replay.

**Comment by simolus3** [comment]
Whether the `User` class is appropriate here also depends on the structure of the users table you're applying it to, so I can't give a definite answer. The implementation looks reasonable to me though.

**Comment by simolus3** [comment]
Extending `Dataclass` for custom row classes is not typically necessary. If you want to use instances of your `User` class for updates and inserts, you would have to implement `Insertable<User>` like [shown here](https://drift.simonbinder.eu/dart_api/rows/?h=row#custom-companions). Sticking to the default companions for insert and updates is what I'd recommend though, and then you also don't have to implement `Insertable`.

**Comment by iampopal** [comment]
> Whether the `User` class is appropriate here also depends on the structure of the users table you're applying it to, so I can't give a definite answer. The implementation looks reasonable to me though.

going this way I got a problem of it was not able to insert. other all thing worked great.

**Comment by iampopal** [comment]
> Extending `Dataclass` for custom row classes is not typically necessary. If you want to use instances of your `User` class for updates and inserts, you would have to implement `Insertable<User>` like [shown here](https://drift.simonbinder.eu/dart_api/rows/?h=row#custom-companions). Sticking to the default companions for insert and updates is what I'd recommend though, and then you also don't have to implement `Insertable`.

Implementing Insertable then forces us to have an import drift package. I am thinking todo it in a way without importing Drift. is it possible?

**Comment by iampopal** [comment]
Shall I also extend it to Dataclass:
class User extend Dataclass {
....
}

**Comment by simolus3** [comment]
> Implementing Insertable then forces us to have an import drift package. I am thinking todo it in a way without importing Drift. is it possible?

Not directly, but what's the problem of importing drift? There's tree-shaking involved for every entrypoint you compile, so you won't end up with an entire compiled copy of drift just because you implement `Insertable`.

> Shall I also extend it to Dataclass:

That shouldn't be necessary.

**Comment by iampopal** [comment]
Ok Thank you for great information and amazing support
