### ISSUE TITLE
The operator '&' isn't defined for the type 'Expression<bool>'.

### ISSUE THREAD

**Issue by h-er0** [simolus3/moor#3392]
**Describe the bug**

When attempting to apply a filter to query data in Drift, I encounter an error regarding the operator '|'.

```dart
managers.todoItems.filter((f) => f.title("Title") & f.content("Content"));
```

Error:

```
The operator '&' isn't defined for the type 'Expression<bool>'.
```

I also tried using '|' operator, but the error persists regardless of the operator used.

**Comment by simolus3** [comment]
Your exact snippet works for me in the example at `drift/example/main.dart`. The operator is an extension, could you check that you're importing `package:drift/drift.dart` into the file where you're using the operator?

**Comment by h-er0** [comment]
> Your exact snippet works for me in the example at `drift/example/main.dart`. The operator is an extension, could you check that you're importing `package:drift/drift.dart` into the file where you're using the operator?

Yes, I finally found that was the problem. But before updating to the latest version, it seems to work without me having to import `package:drift/drift.dart`.

**Comment by simolus3** [comment]
It might be that something has previously exported drift, but nothing obvious that we have changed comes to mind...

**Comment by h-er0** [comment]
> It might be that something has previously exported drift, but nothing obvious that we have changed comes to mind...

Ok, thanks and sorry for the inconvenience.

**Comment by simolus3** [comment]
No problem at all, glad you were able to fix the issue.
