### ISSUE TITLE
defaultValue doesn't work on update replace

### ISSUE THREAD

**Issue by MohiuddinM** [simolus3/moor#34]
default value doesn't work when an existing row is being replaced, with another row where a required field is null

**Comment by simolus3** [comment]
Can you give me some more details in what you're trying to achieve? Reset a value to that you have defined in `withDefault`?

**Comment by MohiuddinM** [comment]
I have created a value in database, and now I want to replace that value with a new object (which was created using the fromJson method)

**Comment by MohiuddinM** [comment]
I am using update(xxx).replace(aaa)

**Comment by simolus3** [comment]
Sorry for the delay, but I think I still need more info. `UpdateStatement.replace` should set fields that are null back to null in the database. If that's not happening it would be a bug in the library. If you need a different behavior, please explain what you'd expect to happen.

**Comment by MohiuddinM** [comment]
I would expect the replace function to work exactly as create function. Remove the old row, and create a new row in its place.

**Comment by simolus3** [comment]
Sorry for the delay. This is pretty much the same problem as in #25. If a column is set to null we can't know if that's null as in "reset to the default value" or "override this column to NULL".

**Comment by MohiuddinM** [comment]
This is only a problem, when the attribute is nullable. Secondly, I have read your comment on #25 too, and I would simply disallow default values for nullable attributes if I were you.

**Comment by simolus3** [comment]
This is now implemented on `develop` - absent values will be replaced with their default value.
