### ISSUE TITLE
Advanced queries in Dart - How to store and fetch nested podo classes

### ISSUE THREAD

**Issue by rizwan-dev** [simolus3/moor#340]
I need to store nested json object containing json array. example 

{
  "itemID": "12841",
  "rfidTag": "IRYS009",
  "itemERPKey": null,
  "skuNumber": "IRYS009",
  "designNumber": "FR001",
  "imageName": "FR001",
  "itemStatus": "InStock",
  "semiFinished": [
    {
      "sfID": "775",
      "sfERPKey": "IRYS009",
      "sfType": "dia"
     
    },
    {
      "sfID": "776",
      "sfERPKey": "IRYS009",
      "sfType": "ruby"
    }
  ],
  
  "miscellaneous": [
    {
      "miscellaneousID": "459",
      "miscellaneousERPKey": "IRYS009",
      "miscellaneousType": "dia"
      
    },
    {
      "miscellaneousID": "460",
      "miscellaneousERPKey": "IRYS009",
      "miscellaneousType": "ruby"
     
    }
  ]
}

How can I insert and fetch record of this podo in moor db. I have tried searching moor doc but couldn't find solution for it.

**Comment by simolus3** [comment]
Do you need to run optimized queries on the array data (like finding all items that have a specific `miscellaneousID` somewhere)? If so, it makes sense to normalize and create three tables:
- one for items
- one for miscellaneous entries
- one to create the n-to-m relationship (references item and miscellaneous index)

If you're only selecting for items based on other properties, or if you don't care about not storing duplicate miscellaneous values when they're referenced by different items, you could [use type converters](https://moor.simonbinder.eu/docs/advanced-features/type_converters/) and just store the json. You could write a type converter that converts a list of miscellaneous data to a string (for instance with json_serializable or built_value).

I'll gladly provide more details, but I need to know more on how you want to store data. An advantage of the first approach is that you can write complex queries if you need to. However, it's also harder to write queries with that table structure. The advantage of type converters is that they're easier to use, but complex queries are harder to realize.

**Comment by rizwan-dev** [comment]
I want to directly store data to moor DB similar to hibernate does. Redundancy of data is not an issue but I want to fetch data on the basis of inner objects fields too. If I use type converters then I think query on the inner array will not be possible. Is there any possible solution to store data easily and also to write queries on the basis of inner fields.

**Comment by rizwan-dev** [comment]
First approach seems to be complex in my case while storing data to these different tables manually by creating mapping tables and inserting records in every table manually. Hibernate does it automatically.
Could you please suggest me a better approach to store data.
I also need to write queries based miscellaneousID and sfType.

**Comment by rizwan-dev** [comment]
If possible could you please cover my scenario in the moor doc.  I think many developers using moor will get help from it.

**Comment by simolus3** [comment]
Well, it's not easy to write queries on something that isn't a column... I recently introduced support for the `json1` sqlite extension, so you could use type converters and still write queries on inner object fields. There are some basic docs for that [here](https://moor.simonbinder.eu/docs/using-sql/extensions/).

Unlike Hibernate, the core moor package tries to not be an ORM. It tries to make queries much easier to write, but you still have to write the full query. See #114 for an issue that tracks ORM support with moor.

**Comment by simolus3** [comment]
With support for nested results in SQL queries and the ability to read full rows from a join, I think there's not much more for moor to do here.
