### ISSUE TITLE
Backup & Restore

### ISSUE THREAD

**Issue by ShehanMadushanka** [simolus3/moor#341]
Is there a way to backup and restore the database?

**Comment by simolus3** [comment]
The database is just a regular sqlite file, so it's definitely possible. To backup a database, you first close the database and then extract the file. To restore a backup, you just copy the file before opening the database.

How to do it exactly depends on which moor backend you're using (moor_flutter or moor_ffi). With moor_ffi, you provide a `File` directly, that file can be saved and restored. With moor_futter, you could use [`getDatabasesPath`](https://pub.dev/documentation/sqflite/latest/sqflite/getDatabasesPath.html) followed by your file name. That file can also be saved and restored.
