### ISSUE TITLE
How to use TypeConverter for List of JSON in nested data

### ISSUE THREAD

**Issue by pranay2210** [simolus3/moor#343]
Json Data:
```json
{ 
"itemID":"12841",
"rfidTag":"IRYS009",
"itemERPKey":null,
"stone":[ 
{ 
"sfID":"775",
"sfERPKey":"IRYS009",
"sfType":"dia"
},
{ 
"sfID":"776",
"sfERPKey":"IRYS009",
"sfType":"ruby"
}
]
}
```
```dart
import 'package:moor/moor.dart';
import 'package:tiara_app/models/stone_details.dart';

class StoneDetailsToSqlConverter
    extends TypeConverter<List<StoneDetails>, String> {
  const StoneDetailsToSqlConverter();

  List<StoneDetails> mapToDart(String fromDb) {
    if (fromDb == null) return null;
    var tagsJson = json.decode(fromDb);

    return (tagsJson as List).map((i) => StoneDetails.fromJson(i)).toList();
  }

  String mapToSql(List<StoneDetails> stoneDetails) =>
      json.encode(stoneDetails.toList());
}
```

**Comment by simolus3** [comment]
The `mapToDart` method looks good to me, put for `mapToSql` you'll probably want to write something like
```dart
String mapToSql(List<StoneDetails> stoneDetails) =>
    json.encode(stoneDetails.map((details) => details.toJson()).toList());
```

**Comment by pranay2210** [comment]
Can I query stored JSON, using this way?

**Comment by simolus3** [comment]
If you're using moor_ffi, you could use the [json1](https://www.sqlite.org/json1.html) extension to write queries. We have some more docs available [here](https://moor.simonbinder.eu/docs/using-sql/extensions/). For more complex queries on json values, you'll likely need a moor file.

**Comment by pranay2210** [comment]
ok what are the limitations with join queries if I try to use  this approach?

**Comment by simolus3** [comment]
At the moment we don't support table-valued functions yet (#260), so joins on `json_each` might not work.

**Comment by simolus3** [comment]
We will support table-valued functions in the next moor release, which means that you'll be able to write something like this in a moor file.
```sql
stoneForItem:
SELECT
  CAST(json_extract(stone.value, 'sfId') AS TEXT) AS sfId,
  CAST(json_extract(stone.value, 'sfERPKey') AS TEXT) AS sfERPKey,
  CAST(json_extract(stone.value, 'sfType') AS TEXT) AS sfType,
FROM items, json_each(items.stone) AS stone
  WHERE items.id = ?
```
I think this eliminates most limitations, since you can use `json_each` in a join to form complex queries.
