### ISSUE TITLE
Using moor_ffi with existing database

### ISSUE THREAD

**Issue by abahnj** [simolus3/moor#346]
I would like to enquire if it is possible to use moor with an existing sqlite database file as your documentation doesn't mention if it is supported. Any help would be greatly appreciated

**Comment by simolus3** [comment]
`moor_ffi` should support that, yes. I've added some documentation for existing databases [here](https://develop--moor.netlify.com/docs/other-engines/vm/#using-moor-ffi-with-an-existing-database) (it will go to the live website with the next moor release).

Please let me know if the docs help or if you need more info, I'm always looking for ways to improve the documentation.

**Comment by abahnj** [comment]
I was able to get it to work using the below code... Thanks a lot for your help and for the great work on moor
``` dart

LazyDatabase _openConnection() {
  // after
  return LazyDatabase(() async {
    var databasesPath = await getApplicationDocumentsDirectory();
    var path = join(databasesPath.path, 'confession.db');

    final file = File(path);
    if (!file.existsSync()) {
      // copy the file from an asset, or network, or any other source
      // Should happen only the first time you launch your application
      print('Creating new copy from asset');

      // Make sure the parent directory exists
      try {
        await Directory(dirname(path)).create(recursive: true);
      } catch (_) {}

      // Copy from asset
      var data =
          await rootBundle.load(join('assets', 'database', 'confession.db'));
      List<int> bytes =
          data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);

      // Write and flush the bytes written
      await file.writeAsBytes(bytes, flush: true);
    } else {
      print('Opening existing database');
    }
    return VmDatabase(file);
  });
}

```

**Comment by simolus3** [comment]
Looks good! If you're in an async function you can replace `file.existsSync()` with `await file.exists()` - but it doesn't make much of a difference.
