### ISSUE TITLE
CREATE TABLE on runtime (maybe with custom queries)?

### ISSUE THREAD

**Issue by SahajRana** [simolus3/moor#351]
Hi @simolus3, It's been great using this library. Recently in my project, I need to create tables & columns on runtime dynamically. How could we achieve that (for Windows Flutter application)? Thanks!

**Comment by simolus3** [comment]
I'm not sure I understand what you mean with "create tables & columns on runtime dynamically". Does the structure of your tables depend on something not known at compile time?

Moor wasn't really designed for that so it will likely need some adaptions to get working. But I don't really see a compelling use case that would require a dynamic schema. Can you provide more details on what you're trying to achieve?

**Comment by SahajRana** [comment]
For a use case, you could take an example of a visual SQL editor.

**Comment by simolus3** [comment]
> you could take an example of a visual SQL editor

That would be an interesting use-case indeed. Moor doesn't have surface-level apis to help here, but one could use some lower-level features of moor:

- to run sql queries of any kind, you could use `moor_ffi` without `moor`, like in [this example](https://pub.dev/packages/moor_ffi#-example-tab-).
- as a starting point to parse and analyze sql queries, one could use the [sqlparser](https://pub.dev/packages/sqlparser) package, which is a part of moor.

I'm not sure how higher-level moor apis could help here - most of them are designed to work together with code moor generates, and code generation obviously doesn't work for this use case. You might be able to get somewhere by dynamically creating a [`GeneratedColumn`s](https://pub.dev/documentation/moor/latest/moor_web/GeneratedColumn-class.html) and a `TableInfo` instance - those can be used to create valid sql queries at runtime.

**Comment by SahajRana** [comment]
@simolus3, Sure I will give your options a try. They certainly make sense. I appreciate your quick responses. Thanks!

**Comment by SahajRana** [comment]
@simolus3, I had one more query though. I have figured out to run SQL queries through `moor_ffi`, thanks to you! 

How can we make it easy to write queries like CREATE TABLE (id..., name....,) etc? Is there a way to use `GeneratedColumn` & `sqlparser` to give out a query in string form?

**Comment by simolus3** [comment]
You can create `GeneratedColumn`s manually to form dynamic tables. This is what the generator would normally be doing. Note that the apis are designed to be easy to generate code for, not easy to use manually :) So it's a little boilerplate, but this works:
```dart
import 'package:moor/moor.dart';
import 'package:moor_ffi/moor_ffi.dart';

class CustomTable extends Table with TableInfo {
  @override
  final List<GeneratedColumn> $columns;

  final String alias;

  @override
  final String actualTableName;

  CustomTable(this.$columns, this.alias, this.actualTableName);

  @override
  String get $tableName => alias ?? actualTableName;

  @override
  Table get asDslTable => this;

  @override
  CustomTable createAlias(String alias) {
    return CustomTable($columns, alias, actualTableName);
  }

  @override
  Map<String, Variable> entityToSql(UpdateCompanion<DataClass> instance) {
    // moor uses this for inserts and updates
  }

  @override
  DataClass map(Map<String, dynamic> data, {String tablePrefix}) {
    // moor uses this for selects
  }
}

class CustomDb extends GeneratedDatabase {
  CustomDb(QueryExecutor executor, this.allTables)
      : super(const SqlTypeSystem.withDefaults(), executor);

  @override
  final List<TableInfo> allTables;

  @override
  MigrationStrategy get migration =>
      MigrationStrategy(onCreate: (m) async {/* do nothing*/});

  @override
  int get schemaVersion => 1;
}

void main() async {
  final table = CustomTable([
    GeneratedIntColumn('id', 'foo', false,
        declaredAsPrimaryKey: true, hasAutoIncrement: true),
  ], null, 'foo');

  final db = CustomDb(VmDatabase.memory(), [table]);
  final migrator = db.createMigrator((sql, [args]) async {
    print('ran $sql with $args');
  });

  await migrator.createTable(table);
}
```

Running that file will print "ran CREATE TABLE IF NOT EXISTS foo (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT); with []", which matches the dynamically created table.

You don't need to use `sqlparser` here, it would actually be doing quite the opposite - it can be used to transform a `CREATE TABLE` statement back into a form that let's you know which columns where defined.

**Comment by Cunibon** [comment]
Moor seems to be discontinued, is there a way to do this in the current drift version?

**Comment by simolus3** [comment]
With the current API, that snippet could like this:

```dart
import 'package:drift/drift.dart';
import 'package:drift/native.dart';

class CustomTable extends Table with TableInfo {
  @override
  final List<GeneratedColumn> $columns;

  final String? alias;

  @override
  final String actualTableName;

  @override
  late final GeneratedDatabase attachedDatabase;

  CustomTable(
    this.$columns,
    this.alias,
    this.actualTableName,
  );

  @override
  Table get asDslTable => this;

  @override
  CustomTable createAlias(String alias) {
    return CustomTable($columns, alias, actualTableName)
      ..attachedDatabase = attachedDatabase;
  }

  @override
  DataClass map(Map<String, dynamic> data, {String? tablePrefix}) {
    // drift uses this for selects
    throw 'todo';
  }
}

class CustomDb extends GeneratedDatabase {
  CustomDb(super.e, this.allTables);

  @override
  final List<TableInfo> allTables;

  @override
  MigrationStrategy get migration =>
      MigrationStrategy(onCreate: (m) async {/* do nothing*/});

  @override
  int get schemaVersion => 1;
}

void main() async {
  final table = CustomTable(
    [
      GeneratedColumn(
        'id',
        'foo',
        false,
        type: DriftSqlType.int,
        hasAutoIncrement: true,
      ),
    ],
    null,
    'foo',
  );

  final db = CustomDb(NativeDatabase.memory(logStatements: true), [table]);
  table.attachedDatabase = db;

  final migrator = Migrator(db);
  await migrator.createTable(table);
}
```
