### ISSUE TITLE
flutter pub run moor_generator identify-databases errors out

### ISSUE THREAD

**Issue by knyghtryda** [simolus3/moor#352]
Was trying out some of the features of 2.3.0 and found that `flutter pub run moor_generator identify-databases` was erroring out with this error:
```
Starting to scan in C:\Users\yanco\Documents\GitHub\contax...
WARNING: Error while working on file:///C:/C:/Users/yanco/Documents/GitHub/contax/lib/constants/state.dartFileSystemException: Exists failed, path = 'C:\C:\Users\yanco\Do
cuments\GitHub\contax\lib\READONLY' (OS Error: The filename, directory name, or volume label syntax is incorrect.
```
analyze works fine however.

**Comment by simolus3** [comment]
Thanks for the report, I think I fixed the problem with c6230e628f8144a827ef7bee0f568de2a503d17e.

Can you try to temporarily add this to your pubspec and see if it works?
```yaml
dependency_overrides:
  moor_generator:
    git:
      url: git@github.com:simolus3/moor.git
      ref: develop
      path: moor_generator
```
There are no changes to the released version apart from this fix. If that solves the problem for you, I'll release that version to pub.

**Comment by knyghtryda** [comment]
that works fine.

**Comment by simolus3** [comment]
`moor_generator` version `2.3.1` contains this fix, so you can remove the `dependency_overrides` section and run `flutter pub upgrade`
