### ISSUE TITLE
Select rows with where condition

### ISSUE THREAD

**Issue by unveloper** [simolus3/moor#353]
Hi,
Let me start saying moor is a very cool library :)

I've read all the documentation and example but I can't find a way to write a simple query that extracts only one or some of the columns and uses a where condition.

Using the "Todos" table of the documentatition:

```
class Todos extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(min: 6, max: 32)();
  TextColumn get content => text().named('body')();
  IntColumn get category => integer().nullable()();
}
```

I want to have a Stream of strings containing the content where the title length is greater than 3

I can write
```
Stream<List<String>> watchEntryContent() {
    return (select(todos).map((row) {
      return row.content;
    })).watch();
  }
```
but I can't figure out how to include the where condition like so.

```
Stream<List<Todo>> watchEntryContent() {
    return (select(todos)..where((t) => t.title.length.isBiggerThanValue(3))).watch();
  }
```

If I use the map I can't use the where and viceversa.

What am I missing?
Thanks

**Comment by simolus3** [comment]
This should work:
```dart
return (select(todos)
          ..where((t) => t.title.length.isBiggerOrEqualValue(3)))
        .map((row) => row.content)
        .watch();
```

This can be hard to read, it's easier if you split the query into a local variable:
```dart
final query = select(todos)
  ..where((t) => t.title.length.isBiggerOrEqualValue(3));

return query
  .map((row) => row.content)
  .watch();
```

**Comment by unveloper** [comment]
Thank you very much!
Can I suggest to put this example in the documentation?

**Comment by simolus3** [comment]
>  Can I suggest to put this example in the documentation?

Good idea, yes. I'll re-open as a reminder

**Comment by simolus3** [comment]
Preview [here](https://develop--moor.netlify.com/docs/getting-started/writing_queries/#mapping) - this will go live with the next merge to master.
