### ISSUE TITLE
Update statements: operations on field based on previous value

### ISSUE THREAD

**Issue by unveloper** [simolus3/moor#354]
Hi!

Having a table like this

```
class CiccioPasticcio extends Table {
  IntColumn get id => integer().autoIncrement()();

  IntColumn get value => integer()();
}
```

Is there a way of writing a query like this:

`UPDATE ciccio_pasticcio SET value = value + 1 `

in pure dart without using the moor files?

Thanks

**Comment by simolus3** [comment]
At the moment there isn't a way to do that. It's won't be easy to integrate, since the companions used to provide data expect the values directly. Maybe we can generate another constructor for companions that takes expressions.

**Comment by unveloper** [comment]
I hope to see this feature soon then :)
Thank you very much!

**Comment by simolus3** [comment]
Done, this will ship with moor 3.0. To write `UPDATE ciccio_pasticcio SET value = value + 1 `, use

```dart
final incrementValue = CiccioPasticcioCompanion.custom(value: value + Constant(1));
await update(ciccioPasticcio).write(incrementValue);
```

**Comment by fedotxxl** [comment]
> CiccioPasticcioCompanion.custom(value: value + Constant(1));

Can you add it to docs and update `value + Constant(1)` part - by default it's not valid code

```
CiccioPasticcioCompanion.custom(value: Dao.ciccioPasticcioTable.value + Constant(1));
```

**Comment by simolus3** [comment]
This should work. Is `ciccioPasticcioTable.value` an `IntColumn`?
