### ISSUE TITLE
Is it possible to rename a column inside a table?

### ISSUE THREAD

**Issue by NourEldinShobier** [simolus3/moor#359]
how can I rename a column of a generated table at run time?

**Comment by simolus3** [comment]
Hi, can you provide a little more detail to help me understand what you're trying to? Do you want to rename a column in a schema migration after renaming it in the table declaration?

**Comment by NourEldinShobier** [comment]
I don't know how to code it yet... here is the example: If my table have 52 columns that represent 52 weeks, and at some point the user wants to rename the 5th column to "bla bla", how can build a table and enable such feature using moor?

**Comment by simolus3** [comment]
In that example, you should not have a table with 52 columns. Instead, you can use one table where each row stores one week:
```dart
// bad:
class MyTable extends Table {
  TextColumn get week1 => text()();
  TextColumn get week2 => text()();
  // ...
  TextColumn get week52 => text()();
}

// better:
class WeekInfos extends Table {
  IntColumn get weekNumber => integer()();
  TextColumn get content => text()();

  @override
  Set<Column> get primaryKey => {weekNumber};
}
```

> and at some point the user wants to rename the 5th column to "bla bla",

Why would a user see what name a column has? I assume he just sees the value of the associated week? In that case, you could use
```dart
Future<void> updateWeek(int week, String content) {
 return update(weekInfos).replace(WeekInfo(week: week, content: content));
}
```
