### ISSUE TITLE
Creating streams inside a transaction

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#365]
We currently only expose Streams from our data access layer (i.e. `.watch()` or `.watchSingle()`). The majority of our app UI runs on Streams, and when we need a Future we just call `Stream.first`. This approach has worked well for us so far, but we're running into an issue when we want to move some operations to a transaction. For example:
```dart
Stream<FooBar> fetchThing(String usrId, String fooId) {
  return getFoo(fooId).switchMap((foo) {
    if (foo?.barId == null) return Stream.value(null);
    return getBar(foo.barId).map((bar) => FooBar(foo, bar));
  })
}
Future<void> someAction(String usrId, String fooId) {
  return db.transaction(() async {
    final foobar = await fetchThing(usrId, fooId).first;
    // based on the state of foobar, we might insert/update/delete from multiple tables 
  });
}
```
One solution is probably to make `fetchThing` it's own query instead of `switchMap`ing, but `getFoo` and `getBar` each have their own validation/business logic that we'd like to reuse. Would it be possible to relax the restriction on creating streams inside a transaction to support this use case? The transaction docs explain: 
> Inside a transaction callback, select statements can't be .watch()ed. The reasons behind this is that it's unclear how a stream should behave when a transaction completes. Should the stream complete as well? Update to data changes made outside of the transaction? Both seem inconsistent, so moor forbids this.

Imo I think it's totally reasonable that a Stream created inside a transaction has the same scope and lifecycle as the transaction. Transactions already have their own `StreamQueryStore`, so it seems feasible to make the cached stream visible to only the transaction callback that created it, then close all streams created by the transaction when it completes. If someone writes code where a stream escapes the transaction callback, listening to the stream outside the transaction could be made to throw:

```dart
Stream<FooBar> stream;
await db.transaction(() {
  stream = fetchThing(usrId, fooId);
});
await stream.first; // somehow throw with 'stream is closed'
```

**Comment by simolus3** [comment]
Side node: Moor has the `Selectable` class which, in simple cases, can be used to express something that can be used as a stream and as a single query (by using `watch` and `get`, respectively). Obviously this stops working as soon as transformers like `switchMap` are needed.

I agree that closing streams when the surrounding transaction completes is reasonable and more useful than the current behavior. It might be a little tricky to implement because we cache streams. We should probably have an entirely isolated `StreamQueryStore` per transaction.

**Comment by Mike278** [comment]
Yeah I initially tried refactoring to `Selectable`s, but as you mentioned we have too many transformations to solve it across the board.

> It might be a little tricky to implement because we cache streams. We should probably have an entirely isolated StreamQueryStore per transaction.

Looks like the [transaction API](https://github.com/simolus3/moor/blob/master/moor/lib/src/runtime/executor/transactions.dart#L29) is already setup to partially implement an isolated `StreamQueryStore`, so hopefully not too tricky! 

This would also change how I was thinking about [implementing a second read-only connection](https://github.com/simolus3/moor/issues/320#issuecomment-579991369).

**Comment by simolus3** [comment]
> Looks like the transaction API is already setup to partially implement an isolated `StreamQueryStore`, so hopefully not too tricky!

True, this was fun and straightforward to implement. It's done on `develop` and will ship with the next moor version.

**Comment by Mike278** [comment]
Thanks so much! That’s an impressively fast turnaround, really appreciate all your work :)
