### ISSUE TITLE
Typecaste Exception while inserting Json Data {netWeight: 12} with type Double using RealColumn

### ISSUE THREAD

**Issue by pranay2210** [simolus3/moor#366]
I'm trying to insert My Json Data and getting an exception while inserting data for a particular field who's type is double.
My Code:
db.dart
RealColumn get netWeight => real()();
.............
db.g.dart
netWeight: serializer.fromJson(json['netWeight']),
Exception has occurred.
_CastError (type 'int' is not a subtype of type 'double' in type cast)

**Comment by simolus3** [comment]
Thanks for the report. Can you post the json in question? I assume it looks like this:
```json
{
  "netWeight": 34,
}
```
I.e. it has an int value in the relevant column. Moor should probably support that and call `toDouble()` implicitly.

**Comment by pranay2210** [comment]
Yeah, I have changed it

**Comment by simolus3** [comment]
This is fixed with f9424470a58b47525e8d51a758d1127e54f0d0f5, which will be part of the next moor release. If you need a fix until then, you can use a custom serializer:
```dart
class _MySerializer extends ValueSerializer {
  const _MySerializer();

  @override
  T fromJson<T>(dynamic json) {
    if (T == DateTime) {
      if (json == null) {
        return null;
      } else {
        return DateTime.fromMillisecondsSinceEpoch(json as int) as T;
      }
    }

    if (T == double && json is int) {
      return json.toDouble() as T;
    }

    return json as T;
  }

  @override
  dynamic toJson<T>(T value) {
    if (value is DateTime) {
      return value.millisecondsSinceEpoch;
    }

    return value;
  }
}

// somewhere before you use moor, say in main()
moorRuntimeOptions.defaultSerializer = const _MySerializer();
```

**Comment by a43mrk** [comment]
why DateTime only accept ints fromJson when parsing?

**Comment by a43mrk** [comment]
please add datetime parsing from string at fromJson.

**Comment by simolus3** [comment]
@a43mrk we format `DateTime`s as ints because that's how we store them in sqlite (timestamps).

It would be breaking to change this now - besides, moor can't know the right format to use. You can always write your own `ValueSerializer` with the behavior you want. By changing `moorRuntimeOptions.defaultSerializer`, moor will then use your serializer.

**Comment by a43mrk** [comment]
Thank you so much! Simon.
