### ISSUE TITLE
Exception write image

### ISSUE THREAD

**Issue by DougSiqueira** [simolus3/moor#375]
How can i save an image to my bank with moor flutter. I've tried it like String and Uint8List. ButI both get this exption when trying to access the table data.

> Exception has occurred.
> SqfliteDatabaseException (DatabaseException (Row too big to fit into CursorWindow requiredPos = 0, totalRows = 1) sql 'SELECT * FROM discard_records;' args []})

**Comment by DougSiqueira** [comment]
I resolved to selecting 50% of the image quality before the converter and save it to the bank.this is solution.
Consider a temporary solution, the interesting thing would be to be able to save an image with the original resolution.

**Comment by simolus3** [comment]
It seems like Android limits the row size to 2MB by default, I don't know if sqflite provides an api to increase that. Maybe it works better when using `moor_ffi`, but if you have content that big you should be careful with out of memory issues.
