### ISSUE TITLE
Plugin request for plugin already on the classpath must not include a version

### ISSUE THREAD

**Issue by vijaemanlapaz** [simolus3/moor#377]
Hi, i'm getting this error every time i build my app

> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'C:\Users\hardk\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\moor_ffi-0.2.0\android\build.gradle' line: 13
> 
> * What went wrong:
> Error resolving plugin [id: 'de.undercouch.download', version: '4.0.0']
> > Plugin request for plugin already on the classpath must not include a version
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s
> Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by simolus3** [comment]
Hi, it seems like your `moor_ffi` version is outdated. Can you try switching to `moor_ffi: ^0.4.0` or later? Let me know if the problem persists, thanks!
