### ISSUE TITLE
Isolates API: Closing the database causes new queries be stuck forever

### ISSUE THREAD

**Issue by knaeckeKami** [simolus3/moor#378]
So, I tried migration my app to use the Isolates API.

First, I have to thank you for the awesome work, the app is now noticeably smoother, previously, some complex queries would drop a frame or two, this is completely gone.
I did not notice an increase in latency either (subjectively, I did not measure it yet).

However, I made a mistake when migrating, and sometimes called .close() on the Database when it should not be closed yet.

Calling .close() on a database, that is, backed by the isolate API causes all queries to just be stuck forever, with no indication of what went wrong.

I would expect an exception to be thrown, or an assert() in debug mode to catch this.

Here is a minimal sample to reproduce:

```dart
import 'package:moor/isolate.dart';
import 'package:moor/moor.dart';
import 'package:moor_ffi/moor_ffi.dart';

part 'main.g.dart';

void main() async{
  MoorIsolate isolate = await MoorIsolate.spawn(_backgroundConnection);

  // we can now create a database connection that will use the isolate internally. This is NOT what's
  // returned from _backgroundConnection, moor uses an internal proxy class for isolate communication.
  DatabaseConnection connection = await isolate.connect();

  final db = IsolatesDatabase.connect(connection);
  //works finde
  final queryResult = await db.customSelectQuery("SELECT 1 +1").getSingle();

  print("awaited result; ${queryResult.data}");

  // oops, this was a mistake
  await db.close();
  
  // times out
  final queryResult2 = await db.customSelectQuery("SELECT 1 + 1").getSingle().timeout(const Duration(seconds: 5));

  print("awaited result; ${queryResult.data}");


}

@UseMoor(tables: [])
class IsolatesDatabase extends _$IsolatesDatabase {
  IsolatesDatabase.connect(DatabaseConnection connection)
      : super.connect(connection);

  @override
  int get schemaVersion => 1;
}

// This needs to be a top-level method because it's run on a background isolate
DatabaseConnection _backgroundConnection() {
  // construct the database. You can also wrap the VmDatabase in a "LazyDatabase" if you need to run
  // work before the database opens.
  final database = VmDatabase.memory();
  return DatabaseConnection.fromExecutor(database);
}
```

**Comment by simolus3** [comment]
Thank you for this detailed bug report and the repro! I agree that subsequent queries should fail instead of deadlocking. With 2b96100480b3484139ba71538ccdc013e9193538 we'll throw a `StateError` when attempting to use a closed isolate connection.
