### ISSUE TITLE
How to insert one value in row?

### ISSUE THREAD

**Issue by sonhieu85** [simolus3/moor#381]
Because i have multiple queries  insert data in loop to insert (value or field) of row in turn.
 Same my Table:

> class Mytable extend Table{
> ...Column get value1 => text()();
> ...Column get value2 => text()();
> ...Column get value3 => text()();
> }

Same my querry in Dao:

> Future insert( MytableCompanion value) => into( myrow).insert(value, orReplace : true)

I must insert value 1 then value 2 then value 3... and i don't want wait to all value have data to insert all in one time.
If i only use insert , an exception when insert( with orReplace: false) value 2 because value 1 has data. And when insert (with orReplace) if i'm only insert value 2, other value return null in database.
 Now i must using insert with insert(value, orReplace : true ):
 

> for ( var something in somethings){
>  database.mytableDao.insert(Mytable..Companion(
>       valuePrivatekey : .....;
>       value1 : value( 'acceptedvalue'),
> );
>  database.mytableDao.insert(Mytable..Companion(
>       valuePrivatekey : .....,
>       value1 : value( 'acceptedvalue'),
>       value2 : value( 'acceptedvalue'),
> ); 
> database.mytableDao.insert(Mytable..Companion(
>       valuePrivatekey : .....,
>       value1 : value( 'acceptedvalue'),
>       value2 : value( 'acceptedvalue'),
>       value3 : .....  I have a table with 31 field or value in one row :))
> );
> 
> )
> }

 I miss something for mycode shorter ? or how to insert only one value as:

> database.mytableDao.insert(Mytable..Companion(
>       valuePrivatekey : .....,
>       value2 : value( 'acceptedvalue'),
>       ... orther value not be insert to null in table?
> );

Thks U.

**Comment by simolus3** [comment]
This sounds like a perfect candidate for an [upsert](https://stackoverflow.com/a/4330694), which is available in recent sqlite versions. Issue #367 tracks support for hat in moor.

That would allow you to write something like
```dart
into(table)
  .insert(
    MyTableCompanion(valuePrivateKey: ...),
    onConflict: (_) => DoUpdate(MyTableCompanion(valueN: 'acceptedvalue')),
  )
```

If there's no row with the same `valuePrivateKey` (assuming that's your primary key), it will behave like an insert that only sets `valueN`. If there's a conflict, it will update `valueN` to the new value but keep all other columns intact.

I'll close this in favor of the other issue, but let me know if you need anything more.

**Comment by sonhieu85** [comment]
I'm only use moor_flutter before and i'm search in document not have 
```
into(table)
  .insert(
    MyTableCompanion(valuePrivateKey: ...),
    onConflict: (_) => DoUpdate(MyTableCompanion(valueN: 'acceptedvalue')),
  )
```
onConflict or upsert only have in moor_ffi ? Or i don't go on a right way? Thks U.

**Comment by simolus3** [comment]
Sorry, moor doesn't support upserts yet (#367). But when it does it will only be available on `moor_ffi`.
