### ISSUE TITLE
How to insert data with multiple List using batch.insertAll() with Companions?

### ISSUE THREAD

**Issue by pranay2210** [simolus3/moor#384]
Example: 
 Future<void> insertMultipleEntries() async{
  await batch((batch) {
 
    batch.insertAll(items, [
      ItemsCompanion.insert( //here I want to pass the  data in a List )
      // or may be here I want to pass multiple List of Same Data Table
    ]);
  });
}

**Comment by simolus3** [comment]
I'm not sure I fully understand what you want to do. You have some kind of list, and then want to insert that list into a table using companions? In that case, you'd have to transform it into companions:
```dart
batch.insertAll(items, [
  for (var entry in yourList) ItemsCompanion.insert(/* fields based on entry */)
]);
```

**Comment by pranay2210** [comment]
But I want each and every filed present in list, so do I need to define every column name insdie ItemsCompanion.insert(.....)

**Comment by simolus3** [comment]
> do I need to define every column name insdie ItemsCompanion.insert

Basically, yeah. If the json matches all column names, you could also do
```dart
[for (var jsonObject in jsonList) Item.fromJson(jsonObject)]
```
That would make it easier, but it requires all columns to be present in the json.

**Comment by pranay2210** [comment]
Thank you!
