### ISSUE TITLE
errors in app_database.g.dart file

### ISSUE THREAD

**Issue by rodriger06** [simolus3/moor#385]
Hi Moor Team,
I am using moor package in flutter for my application. im following the instructions online https://moor.simonbinder.eu/docs/getting-started/starting_with_sql/#what-moor-generates

but when i run the build command: flutter pub run build_runner build the app_database.g.dart file that gets generated has errors. here is a snapshot of errors:
<img width="960" alt="moor_table_error" src="https://user-images.githubusercontent.com/49496303/74094593-dadffa80-4ab1-11ea-8328-6febfcc1d24a.png">

<img width="960" alt="moor_table_error2" src="https://user-images.githubusercontent.com/49496303/74094597-e2070880-4ab1-11ea-8e58-8e10ddb264ea.png">

my dependencies are
cupertino_icons: ^0.1.2
  month_picker_dialog: ^0.3.1
  flutter_cupertino_localizations: ^1.0.1
  moor: ^2.3.0
  provider: ^4.0.3
  moor_ffi: ^0.4.0
  path_provider: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.1
  moor_generator: ^2.3.1
  build_runner:

the problem seems to be with 'Table' class. there is a conflict between flutter and moor. flutter has file called package:flutter/src/widgets/table.dart  which define the Table class.  moor also has a class dsl.dart which define Table.  how can i solve this problem so that my error goes away

**Comment by simolus3** [comment]
Hi, thanks for the detailed report.

>  how can i solve this problem so that my error goes away

In general, I'd recommend to not import moor and flutter in the same file. In cases where this is impossible, you can use a `hide` clause:
```dart
import 'package:moor/moor.dart';
import 'package:flutter/widgets.dart' hide Table;
```
In the rare case where you need both moor and flutter's `Table` class, you could do this
```dart
import 'package:moor/moor.dart';
import 'package:flutter/widgets.dart' hide Table;
import 'package:flutter/widgets.dart' as flutter show Table;

// use Table to refer to the moor class and flutter.Table to refer to the Flutter class
```

I agree that this can be annoying, but I'm not sure if moor should be changed here. Importing moor and flutter into the same file should be rare, and I think adding the hide clause is an acceptable solution.
