### ISSUE TITLE
is named constraint applying on json deserialization!?

### ISSUE THREAD

**Issue by a43mrk** [simolus3/moor#389]
// Hi there!
// When using named on the following Model:
@DataClassName('Issue')
class Issues extends Table {
    TextColumn get issue => text().named('case').nullable()();
}
// the output on generated fromJson is:
generated.fromJson(Map<String,dynamic> json {ValueSerializer serializer}) {
issue: serializer.fromJson<String>(json['issue']),
// ** expected issue: serializer.fromJson<String>(json['case']),
}
// ? how can i change the keyword used on deserialization ?

**Comment by simolus3** [comment]
No, `named()` doesn't affect the json key used for serialization. This is explained by the [dartdoc documentation](https://pub.dev/documentation/moor/latest/moor_web/ColumnBuilder/named.html).

You can use `@JsonKey` to change it:
```dart
@JsonKey('case')
TextColumn get issue => text().named('case').nullable()();
```

**Comment by a43mrk** [comment]
thank you
