### ISSUE TITLE
Is it possible to create tables at run-time using moor files?

### ISSUE THREAD

**Issue by NourEldinShobier** [simolus3/moor#391]
is it possible to use templates such as `_filterTodos: SELECT * FROM todos WHERE $predicate;`, but to create a table instead?

**Comment by simolus3** [comment]
At the moment this is not possible, no.

At compile time, we need to know a lot about each table and its columns for the static analysis to work. If you were able to create tables dynamically, we can't know about those in queries.

Technically, we could allow templates for some parts, e.g.
```sql
CREATE TABLE foo (
  bar TEXT DEFAULT $defaultExpr
);
```
But I'm not sure how the generated code for that would look like yet. If you share more details about what you're trying to do I can take a better look.

**Comment by simolus3** [comment]
Closing this as moor can't really do anything here. If you have a specific problem you're trying to solve, please reply or open another issue, thanks!
