### ISSUE TITLE
Is there a way to change the defaultSerializer in MoorRuntimeOptions Object?

### ISSUE THREAD

**Issue by dingming1994** [simolus3/moor#395]
Hi,

I am trying to override the fromJson method of each database entity. So what I do now is, I create a `customSerializer` and every time I call the fromJson, i need to provide this `customSerializer` in the fromJson to override the default one. 

I see the default serializer is initialized in the runtime_api.dart files, and the comments says rarely change this file. 

What i am trying to do, is to use my `customSerializer` instead of default one when generating the code. So that i dont need to override the serializer everytime i use it.

Is there a way for me to do so?

Thank you.

**Comment by simolus3** [comment]
`defaultSerializer` in `moorRuntimeOptions` is mutable, so you can just do
```dart
// somewhere before you use moor
moorRuntimeOptions.defaultSerializer = customSerializer;
```
The default serializer is then used by all generated moor code, so that should work.

**Comment by jesseframework** [comment]
Where would you put this "moorRuntimeOptions.defaultSerializer = customSerializer;" in the generated code? Am having issues with date coming from the API and giving this error 'String' is not a subtype of type 'int' in type cast. Can some one help me please am working this for 5 day and can't find any solution.

**Comment by jesseframework** [comment]
> Where would you put this "moorRuntimeOptions.defaultSerializer = customSerializer;" in the generated code? Am having issues with date coming from the API and giving this error 'String' is not a subtype of type 'int' in type cast. Can some one help me please am working this for 5 day and can't find any solution.

my issess is now resolved.
I used this link to recolved my issess https://github.com/simolus3/moor/issues/20
