### ISSUE TITLE
.named() does not seem to work when using custom type converter

### ISSUE THREAD

**Issue by a-ritwik** [simolus3/moor#396]
This does not work (No data is saved in table in which cropStage is column)
TextColumn get cropStages => text().named('cropStages').map(const CropstagevarietConverter()).nullable()();

Whereas this works
TextColumn get cropStages => text().map(const CropstagevarietConverter()).nullable()();
But column name becomes crop_stages. I want keep name of column as cropStages and not crop_stages (default behaviour of moor in camecase) due to some api constraints.

**Comment by a-ritwik** [comment]
I just checked again .named() is working as intended. 
The problem is that I want to store structure like this (CropStage is column)
"cropStages" : [ {
    "id" : 1
  }, {
    "id" : 2
  } ]

but the type converter I defined gives structure like this
"cropStages" : { abc : ["id" : 1, "id" : 2] }

I want my column name as cropStage, but don't want abc.
The class I defined is this 
class Imgs {
  List<String> abc;
  Imgs( this.profileImages);
  factory Imgs.fromJson(Map<String, dynamic> json) => _$ImgsFromJson(json);
  Map<String, dynamic> toJson() => _$ImgsToJson(this);
}

Can you please help?

**Comment by simolus3** [comment]
So you want to store this structure:
```
"cropStages" : [ {
    "id" : 1
  }, {
    "id" : 2
  } ]
```

But `Imgs.toJson()` constructs this:
```dart
"cropStages" : { abc : ["id" : 1, "id" : 2] }
```

Is that the problem? I assume you could just change the type converter so that it only returns `json['cropStages']['abs']`.  Is that what you need help with?

**Comment by a-ritwik** [comment]
Yes, we can do that by changing return statement of mapToSql and mapToDart so it only returns  
json['cropStages']['abc']. But I do not want abc at all. Because I am getting data from api which has structure 
[
{
  "id" : 1751,
  "name" : "gd",
  "cropStages" : [ {
    "id" : 1,
    "name" : "Vegetative stage"
  }, {
    "id" : 2,
    "name" : "sprouting stage"
  } ],
"field2" : "kk"
},
{
  "id" : 1752,
  "name" : "google",
  "cropStages" : [ {
    "id" : 1,
    "name" : "Vegetative stage"
  }, {
    "id" : 2,
    "name" : "sprouting stage"
  } ],
"field2" : "asj"
}
]

So if there is "cropStages" : { abc : ["id" : 1, "id" : 2] }, it would create problem in syncing. Is it possible to not use abc.

**Comment by a-ritwik** [comment]
I solved this by using converter like this


class JsonlistTypeConverter extends TypeConverter< List<dynamic>, String> {
  const JsonlistTypeConverter();
  @override
  List<dynamic> mapToDart(fromDb) {
    if (fromDb == null) {
      return null;
    }
    return jsonDecode(fromDb) as List<dynamic>;
  }

  @override
  String mapToSql(value) {
    if (value == null) {
      return null;
    }
    var conVal = json.encode(value);
    return conVal;
  }
}


This returns List<dynamic> corresponding to cropStages. From this List<dynamic> I fetched List<Map<String, dynamic>> and got individual cropStage.
Thanks for help 😊
