### ISSUE TITLE
Access MoorIsolate created by a background isolate via FlutterNativeView

### ISSUE THREAD

**Issue by ened** [simolus3/moor#399]
At the moment, Moor relies on `Isolate.spawn` to create a MoorIsolate instance. The documentation is very clear on how the MoorIsolate is then sent back to the caller via a `SendPort`.

In our App, we do run into a major issue with this approach. Our App provides relies heavily on background operations, e.g. no App UI visible. Therefore, we are running a Android `Service` when needed and will be called by iOS with special background flags. We're doing data processing & analysis via Bluetooth; hence no need for UI.

In order to still have code sharing, we decided to let a plugin control background processes. The plugin gets the system callbacks and starts the Flutter Isolate as appropriate. It is using a `FlutterNativeView` with the `background view` flag set to true.

We're now trying to let the background process share data with the main App UI. 

Given the current MoorIsolate implementations requirement to send the Isolate itself over a SendPort, the following parts from the [SendPort.send documentation](https://api.flutter.dev/flutter/dart-isolate/SendPort/send.html) applies:

> The content of [message] can be: primitive values (null, num, bool, double, String), instances of [SendPort], and lists and maps whose elements are any of these. List and maps are also allowed to be cyclic.
>
> In the special circumstances when two isolates share the same code and are running in the same process (e.g. isolates created via [Isolate.spawn]), it is also possible to send object instances (which would be copied in the process). This is currently only supported by the dart vm.

Hence, we are only able to use _primitive_ SendPort messages like mentioned in the documentation.

To make it work for this App architecture, MoorIsolate & Connection would need a major refactoring so that they can understand & translate a simple command representation.

We do expect a drop in performance due to the encoding/decoding process. Internally, Moor could use a highly efficient binary format to work around that problem.

**Comment by simolus3** [comment]
Thanks for the detailed report!

Out of interest, do you know how exactly the communication would work in the scenario with background processes? Are there two different Flutter engines that can communicate over send and receive ports? I'm a bit surprised that we can't copy objects around, since they essentially are running the same code.

> To make it work for this App architecture, MoorIsolate & Connection would need a major refactoring so that they can understand & translate a simple command representation.

It's not that major I think. We already use a [fairly simple commend representation](https://github.com/simolus3/moor/blob/master/moor/lib/src/runtime/isolate/protocol.dart) internally, so we'd just have to get rid of the classes. As a start, we could just serialize those to maps directly.
A `MoorIsolate` object is also just a tiny wrapper around a `SendPort`, so we might as well expose that port directly.

> Internally, Moor could use a highly efficient binary format to work around that problem.

List and maps tend to be quite fast already. I've considered some `dart:ffi` shenanigans to share mutable native memory between isolates, which means we only have to pass pointers around. That would probably break for true background processes though, as they don't have any shared memory.

**Comment by ened** [comment]
Thank you for your reply.

> Out of interest, do you know how exactly the communication would work in the scenario with background processes? Are there two different Flutter engines that can communicate over send and receive ports? I'm a bit surprised that we can't copy objects around, since they essentially are running the same code.

We are doing this for other components in the following way:

<details>
<summary>A Isolate instance method for class users</summary>

``` dart
class SomeBackgroundIsolate {
  SomeBackgroundIsolate._(this._sendPort);

  final SendPort _sendPort;

  static Future<SomeBackgroundIsolate> instance({
    bool createIsolate = false,
  }) async {
    final SendPort po = await _retrieveIsolateSendPort(
      createIsolate: createIsolate,
    );

    if (po == null) {
      return null;
    }

    return SomeBackgroundIsolate._(po);
  }
}
```
</details>

<details>
<summary>The interesting bits are in _retrieveIsolateSendPort</summary>

``` dart
  static Future<SendPort> _retrieveIsolateSendPort({
    // Create the isolate when needed.
    bool createIsolate = true,
  }) async {
    final SendPort lookup =
        IsolateNameServer.lookupPortByName(someSendPortName);

    if (lookup != null) {
      final ReceivePort rp = ReceivePort();
      lookup.send(['ping', rp.sendPort]);
      try {
        await rp.first.timeout(const Duration(milliseconds: 100));
        return lookup;
      } catch (e) {
        _log.warning('isolate unresponsive. Unregister and respawn');
        IsolateNameServer.removePortNameMapping(someSendPortName);
      }
    }

    if (!createIsolate) {
      return null;
    }

    _log.finest('Isolate not running yet');
    try {
      // At the moment, spawning isolates is blocked by various issues.
      // On Android, spawned isolates will not have access to Flutter plugins.
      // On iOS, the spawning is most likely blocked thanks to https://github.com/flutter/flutter/issues/14815.
      return _assignCurrentIsolate();
    } catch (e, stackTrace) {
      _log.warning('ISOLATE SPAWN FAILED - SOME BG BROKEN', e, stackTrace);
      return Future.error('someIsolate init failed');
    }
  }

  static Future<SendPort> _assignCurrentIsolate() async {
    final ReceivePort rp = ReceivePort();
    _someIsolate(rp.sendPort);
    return await rp.first;
  }
```
</details>

The actual communication protocol is quite simple and shows the simple transfer of primitive messages:

<details>
<summary>_someIsolate</summary>

``` dart
void _someIsolate(SendPort callerSendPort) {
  final ReceivePort newIsolateReceivePort = ReceivePort();

  // Register the port by name
  final res = IsolateNameServer.registerPortWithName(
    newIsolateReceivePort.sendPort,
    someSendPortName,
  );

  if (!res) {
    _log.info('can not register the isolate send port - already registered?');
    callerSendPort.send(null);
    return;
  }

  callerSendPort.send(newIsolateReceivePort.sendPort);

  newIsolateReceivePort.listen((msg) {
    WidgetsFlutterBinding.ensureInitialized();

    final String cmd = msg[0];
    final SendPort sendPort = msg[1];

    if (cmd == 'ping') {
      sendPort.send(true);
      return;
    }

    if (cmd == 'subscribe') {
      sendPort.send('ok');
    }
  });
}
```
</details>

> It's not that major I think. We already use a fairly simple command representation internally, so we'd just have to get rid of the classes. As a start, we could just serialize those to maps directly.
A MoorIsolate object is also just a tiny wrapper around a SendPort, so we might as well expose that port directly.

That's great news!

> List and maps tend to be quite fast already. I've considered some dart:ffi shenanigans to share mutable native memory between isolates, which means we only have to pass pointers around. That would probably break for true background processes though, as they don't have any shared memory.

Perhaps my comment applies to the pre-ffi days. I've seen projects like `flutter_blue` rely on Protobuf successfully, for example.

**Comment by simolus3** [comment]
I've changed moor's isolate communication protocol so that it only sends primitive objects over isolates.

Instead of sending a `MoorIsolate` across isolates you control, you will be able to obtain the underlying `SendPort` via `MoorIsolate.connectPort`. That `SendPort` can safely be sent over isolates, the receiving end can re-construct a `MoorIsolate` with the new `MoorIsolate.fromConnectPort` constructor.
