### ISSUE TITLE
How can I query for selecting items based on conditions in my List<>? 

### ISSUE THREAD

**Issue by pranay2210** [simolus3/moor#401]
Suppose I have a List containing number of items that will be used to query in select statement using where clause, for example

I'm gonna Pass a List which will contain items { "EAR", "BRC", "RNG"..}

Future<List<Item>> getClassificationsItemsOnClick(List<String> itemTypeList) {
    return (select(items)
      ..where((t) => t.itemType.equals(itemTypeList))).get();
  }

**Comment by simolus3** [comment]
Would `t.itemType.isIn(itemTypeList)` work for you?

**Comment by pranay2210** [comment]
I want to fetch all the items present in the List will it work?

**Comment by simolus3** [comment]
That query would load all items whose type is in `itemTypeList`, yes.

Be aware that this approach doesn't work for large lists (maximum is at 999 items, but I wouldn't use it if `itemTypeList` has more than 50 entries). Other approaches are more complicated though.

Let me know if you need assistance when doing this check with long lists.
