### ISSUE TITLE
fts5 queries using "^" character 

### ISSUE THREAD

**Issue by advancedtw** [simolus3/moor#403]
how to write a query using '*' or '^' in the official doc we are supposed to use a single quote  like that
` MATCH '^one' `.  i have tried various combination but moor fails to parse the query
to be more precise i'm trying to run a query like this one 
`paraphWithFts5(:token AS TEXT): SELECT * FROM paraph WHERE body MATCH :token* ORDER BY rank;`
the query paraphWithFts5 is not be generated unless i remove the *

**Comment by simolus3** [comment]
So you want to match for `token*`, where `token` is a variable? I assume string concatenation should work: `WHERE body MATCH :token || '*'`.

**Comment by advancedtw** [comment]
works as expected thanks for the tip.
