### ISSUE TITLE
Can we create a query for search inventory items where user will have the freedom to choose the table name, column name and value? 

### ISSUE THREAD

**Issue by pranay2210** [simolus3/moor#404]
Actually I want to create a search query where usr could pass tableName, columnName, and Value for search dynamically in a manner example:-
```
Future<List<foo>> getItems(tableName, columnName, value)
{
//here I would be able to search using (select * from tableName where  columnName=value)
//can i do something like this?

}
```

**Comment by simolus3** [comment]
It's hard for moor to generate apis for that because the return type would depend on what you pass as `tableName`. That said, maybe something like this could work:
```dart
Future<List> getItems<V>(String tableName, String columnName, V value) {
  final table = allTables.singleWhere((t) => t.tableName == tableName);
  final column = table.columnsByName[columnName];
  assert(column != null);

  final query = select(table)
    ..where((row) => column.equalsExp(Variable<V>(value)));

  return query.get();
}
```

**Comment by pranay2210** [comment]
it gives error for .columnsByName

**Comment by simolus3** [comment]
Which moor version are you on? That code compiles for me on the latest version.

**Comment by pranay2210** [comment]
its moor: 2.4 and moor_flutter: 2.1.1
![Screenshot 2020-02-24 at 12 09 58 PM](https://user-images.githubusercontent.com/37976696/75132938-ce3ce280-56fe-11ea-8e28-313469546cde.png)

**Comment by simolus3** [comment]
Ah right, sorry. I ran that on my develop branch. With the latest stable version this is very awkward to use:
```dart
Future<List> getItems<V, T extends SqlType<V>>(String tableName, String columnName, V value) {
  final table = allTables.singleWhere((t) => t.$tableName == tableName);
  final column = table.columnsByName[columnName];
  assert(column != null);

  final query = select(table)
    ..where((row) => column.equalsExp(Variable<V, T>(value)));

  return query.get();
}
```

You would then have to specify the type parameters when using that function, e.g. `await getItems<int, IntType>(...)`.
At least it will get better in moor 3.0

**Comment by pranay2210** [comment]
I didn't get the e.g. await getItems<int, IntType>(...). what parameters do
we need to pass? I'm confused, can you help me to resolve this?

**Comment by simolus3** [comment]
Of course. The second type parameter denotes which type a column or variable would have _in sql_. An instance of that class is also responsible to map Dart values from and to sql. When you use variables, that type needs to be set so that the variable can be mapped to sql.

The mapping is
 - `int` -> `IntType`
 - `double` -> `RealType`
 - `String` -> `StringType`
 - `DateTime` -> `DateTimeType`
 - `Uint8List` -> `BlobType`

In the next breaking moor version we'll remove this. Perhaps, a better way to write this would be
```dart
Future<List> getItems(String tableName, String columnName, Variable value) {
  final table = allTables.singleWhere((t) => t.$tableName == tableName);
  final column = table.columnsByName[columnName];
  assert(column != null);

  final query = select(table)
    ..where((row) => column.equalsExp(value));

  return query.get();
}
```
You could then just use `getItems(tableName, columnName, Variable.withInt()` instead of that weird `IntType` thing.

**Comment by pranay2210** [comment]
I'm getting the same error again and my calling is something like this
`await   appDatabase.getItems("items", "item_type", "EAR").then((t){print("Printing Values for dynamic Table fetching : $t");});`
![Screenshot 2020-02-26 at 11 53 46 AM](https://user-images.githubusercontent.com/37976696/75317767-c9a73400-588e-11ea-9ddd-6f7db49b3060.png)

**Comment by simolus3** [comment]
Yeah the type arguments need to be set on the `Variable` you pass. If you write `<String, StringType>` in the method definition, those will be type variables and won't point to an actual class.

If you know you're only going to pass strings, you could use
```dart
Future<List> getItems(String tableName, String columnName, String value) {
  // ...
    ..where((row) => column.equalsExp(Variable.withString(value))
}
```
If you want a more general approach you can use the method from my previous comment.

**Comment by pranay2210** [comment]
Thank you so much Simon, its working and keep it up!!

**Comment by pranay2210** [comment]
One more thing, can I get specific columns like `select column1, column2 from tableName..` instead of `select * from tableName...` while selecting by passing parameters?

**Comment by simolus3** [comment]
This should be possible in the latest moor version, yes. Instead of `select`, you'll want to use `selectOnly`, then you'd use `addColumns` to add the columns you need (you can look those up by their name as well).
