### ISSUE TITLE
Support for regex query?

### ISSUE THREAD

**Issue by krabbenprgr** [simolus3/moor#410]
Is it possible to execute queries with regex like this:
`SELECT * FROM tbl WHERE field REGEXP '\b3\b'` or something like this?
 I heard regex is supported for sqlite3 and higher?
I appreciate any assistance!

**Comment by simolus3** [comment]
> I heard regex is supported for sqlite3 and higher?

In sqlite, `foo REGEXP bar` is just syntax sugar for `regexp(bar, foo)`, a user-defined function. By default, `regexp` throws an error. 

In the next moor (or rather, `moor_ffi`) version, we will support the `REGEXP` operator by implementing it on top of the `RegExp` class in Dart. `moor_ffi` is the only engine where we can provide custom sql functions, so we can't support it in `moor_flutter` or in the web executor.
