### ISSUE TITLE
Support for cascading delete operation

### ISSUE THREAD

**Issue by melwinlobo18** [simolus3/moor#413]
Hey, is there support for cascade delete operation in moor. I used the **ON DELETE CASCADE** in custom constraint while creating the table but it doesn't seem to be working. When the create the parent table the child table entries aren't getting deleted.

```dart
IntColumn get transactionId => integer().nullable().customConstraint('NULL REFERENCES transaction_records(transaction_id) ON DELETE CASCADE')();
```

Am I doing this the wrong way or is there no support for **ON DELETE CASCADE**?

**Comment by simolus3** [comment]
I think this is due to foreign keys being turned off by default. Can you try doing this:
```dart
@override
MigrationStrategy get migration => MigrationStrategy(
  // ...
  beforeOpen: (details) async {
    await customStatement('PRAGMA foreign_keys = ON');
  }
);
```

**Comment by melwinlobo18** [comment]
Yup. It's working fine now. Thanks a lot 😃

**Comment by RobPFarley** [comment]
Sorry to comment on a closed ticket, but i'm having some trouble with this when using .moor files to define the tables. Here's my .moor file:

```
CREATE TABLE todos (
    id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    title TEXT,
    body TEXT,
    category INT REFERENCES categories (id) ON DELETE CASCADE
);

CREATE TABLE categories (
    id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    description TEXT
) AS Category; 

addTodo: INSERT INTO todos (
    title,
    body,
    category
) VALUES (
    :title,
    :body,
    :category
);

addCategory: INSERT INTO categories (
    description
) VALUES (
    :description
);

deleteTodos: DELETE FROM todos;
```

And my database file:

```
import 'dart:io';

import 'package:foreign_key_test/dao.dart';
import 'package:moor/moor.dart';
import 'package:moor_ffi/moor_ffi.dart';
import 'package:path_provider/path_provider.dart' as paths;
import 'package:path/path.dart' as p;

part 'database.g.dart';

@UseMoor(
  daos: [
    Dao,
  ],
  include: {'database.moor'},
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(constructDb());
  
  @override
  MigrationStrategy get migration => MigrationStrategy(
    beforeOpen: (details) async {
      await customStatement('PRAGMA foreign_keys = ON');
    },
  );

  @override
  int get schemaVersion => 1;
}

QueryExecutor constructDb({bool logStatements = false}) {
  if (Platform.isIOS || Platform.isAndroid) {
    final executor = LazyDatabase(() async {
      final dataDir = await paths.getApplicationDocumentsDirectory();
      final dbFile = File(p.join(dataDir.path, 'db.sqlite'));
      return VmDatabase(dbFile, logStatements: logStatements);
    });
    return executor;
  }
  if (Platform.isMacOS || Platform.isLinux) {
    final file = File('db.sqlite');
    return VmDatabase(file, logStatements: logStatements);
  }
  return VmDatabase.memory(logStatements: logStatements);
}
```

And my Dao file for good measure:

```
import 'package:foreign_key_test/database.dart';
import 'package:moor/moor.dart';

part 'dao.g.dart';

@UseDao(tables: [
  Todos,
  Categories
])
class Dao extends DatabaseAccessor<AppDatabase> with _$DaoMixin {
  Dao(AppDatabase db) : super(db);

  Stream<List<Todo>> getAllTodos() {
    return select(db.todos).watch();
  }
  
  Future addTodo(String title, String body, int category) {
    return db.addTodo(title, body, category);
  }

  Future addCategory(String description) {
    return db.addCategory(description);
  }

  Future deleteTodos() {
    return db.deleteTodos();
  }
}
```

When downloading the device database after adding a few Todos I can see that the foreign key is indeed setup correctly, however after deleting the Todos and redownloading the database I can see that the Todos are gone, but the corresponding Categories are still present in the database. I put together a quick app that shows this in action if you'd like to take a look at it @simolus3 , you can find it here https://github.com/RobPFarley/foreign_key_test.

Please let me know if there's anything else you'd like me to provide. FYI I'm on the current beta channel of Flutter. Thanks in advance.

**Comment by simolus3** [comment]
> after deleting the Todos and redownloading the database I can see that the Todos are gone, but the corresponding Categories are still present in the database

You're setting a `ON DELETE CASCADE` clause on `todos`. This means that deleting a category will delete all todos assigned to it. However, it doesn't mean that a category without todos gets deleted as well. I don't think there is a way to model that with cascading deletes, but triggers might do the trick:
```sql
CREATE TRIGGER delete_empty_categories AFTER DELETE ON todos BEGIN
  DELETE FROM categories c WHERE NOT EXISTS (SELECT * FROM todos WHERE category = c.id);
END;
```

**Comment by RobPFarley** [comment]
Ah brilliant, thanks for the help
