### ISSUE TITLE
Fetch all the rows when null is passed to where condition

### ISSUE THREAD

**Issue by melwinlobo18** [simolus3/moor#414]
Hey, consider the following query

```dart
Stream<List<TransactionRecord>> watchCategoryExpenses(
          {int companyId, String type, int categoryId}) =>
      (select(transactionRecords)
            ..where((transactionRecord) =>
                transactionRecord.companyId.equals(companyId))
            ..where((transactionRecord) => transactionRecord.type.equals(type))
            ..where((transactionRecord) =>
                transactionRecord.expenseCategoryId.equals(categoryId)))
          .watch();
```
So, if I don't have any value for _type_ initially, the **null** value will be passed. Initially, I want to display all the data when the user opens the page. And filter only when a particular _type_ is selected.

This was possible in firebase as when we pass null to where we get all the rows but in moor it tries to match with null value and I don't get any data.

**Comment by simolus3** [comment]
Moor matches the behavior of sql here, so I'd prefer to keep the current behavior.

If you only want to filter if a parameter is not null, you could just do
```dart
final query = select(transactionRecords);

if (companyId != null) {
  query.where((row) => row.companyId.equals(companyId));
}
// other ifs would look similar

return query.watch();
```
