### ISSUE TITLE
how to test moor database on windows (sqlite dependency is needed)

### ISSUE THREAD

**Issue by easazade** [simolus3/moor#418]
this is the error you get when trying to test your database on windows because sqlite is needed as a dependency on windows. i have tried adding it but failed. it would be great if someone could help with this since alot of developers are windows users

```
dart:ffi                                                       new DynamicLibrary.open
package:moor_ffi/src/load_library.dart 34:27                   _defaultOpen
package:moor_ffi/src/load_library.dart 80:12                   OpenDynamicLibrary.openSqlite
package:moor_ffi/src/bindings/bindings.dart 92:19              new _SQLiteBindings
package:moor_ffi/src/bindings/bindings.dart 184:53             bindings
package:moor_ffi/src/impl/database.dart 40:9                   new Database.open
package:moor_ffi/src/impl/database.dart 32:41                  new Database.memory
package:moor_ffi/src/vm_database.dart 41:22                    _VmDelegate.open
package:moor/src/runtime/executor/helpers/engines.dart 246:22  DelegatedDatabase.ensureOpen.<fn>

Invalid argument(s): Failed to load dynamic library (126)
```

**Comment by simolus3** [comment]
If you just need a setup for testing, you can just [download](https://www.sqlite.org/download.html) the dll file. You'll find the dll under "Precompiled Binaries for Windows". If you extract that dll file into somewhere in your `PATH`, `DynamicLibrary.open` should be able to pick it up.

If you use chocolatey, `choco install sqlite` should also do the trick.

**Comment by easazade** [comment]
for those who want to test this is the code that finally worked for me **after installing sqlite by chocolatey**

so first -> `choco install sqlite`

**and here is the code :** 

my database class :
```dart
class MoorDb extends _$MoorDb {
  MoorDb(QueryExecutor qe) : super(qe );

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (migrator) async {
          await migrator.createAll();
        },
        onUpgrade: (migrator, from, to) async {
          await migrator.createAll();
        },
      );

  @override
  int get schemaVersion => 1;
}

```
and here is my test file : 

```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:moor_ffi/moor_ffi.dart';
import 'package:smartschool/data/datasource.dart';
import 'package:smartschool/data/local/database.dart';
import 'package:smartschool/data/local/moor_database.dart';

void main() {
  MoorDb moorDb;


  //setup and tear down
  setUp(() {
    moorDb = MoorDb(VmDatabase.memory(logStatements: true));
  });

  tearDown(() {});

  test('simple test', () async {
    //not an actual unit test. only to check it's working
    await moorDb.into(moorDb.users).insert(User(id: 1, roll: 'teacher', mobile: '09117158746'));
    var users = await moorDb.select(moorDb.users).get();
  });
}

```

the dependencies i used for moor database :
```yaml
dependencies:
  moor: ^2.4.1
  moor_ffi: ^0.4.0
  path_provider:
dev_dependencies:
  build_runner:
  moor_generator: ^2.4.0
```

**Comment by echaparroelse** [comment]
I've copied the sqlite3.dll file into the root folder of my project, and it worked.

**Comment by Vedsaga** [comment]
> If you use chocolatey, `choco install sqlite` should also do the trick.

I have installed it but, still getting the same error.

I have tried 2nd method as well
I have installed `"Precompiled Binaries for Windows"` . I have added it to the path as well Still getting same warning. I hope I am not doing anything wrong.
![image](https://user-images.githubusercontent.com/59083528/160335592-62379aa4-9419-438e-b2c0-142fb41efe90.png)


@simolus3 pls could you check

**Comment by simolus3** [comment]
> I have added it to the path as well

The "Edit User Variable" from your screenshot isn't the `PATH` variable that Windows uses to find dlls. Can you do a `print(Platform.environment['PATH'])` in Dart and verify that the folder containing sqlite3.dll is in there?

**Comment by Vedsaga** [comment]
> print(Platform.environment['PATH'])

this is what I got when I put 
![image](https://user-images.githubusercontent.com/59083528/160430705-a50fede7-2a55-4b8b-bada-7758f1b3d0a8.png)


```
flutter: [C:\Program]() Files\Common Files\Oracle\Java\javapath;[C:\Program]() Files (x86)\Common Files\Oracle\Java\javapath;[C:\Program]() Files\Python310\Scripts\;[C:\Program]() Files\Python310\;[C:\WINDOWS\system32]();[C:\WINDOWS]();[C:\WINDOWS\System32\Wbem]();[C:\WINDOWS\System32\WindowsPowerShell\v1.0\]();[C:\WINDOWS\System32\OpenSSH\]();[C:\Program]() Files\Git\cmd;[C:\Program]() Files\dotnet\;[C:\Program]() Files\WireGuard\;[C:\Program]() Files\Docker\Docker\resources\bin;[C:\ProgramData\DockerDesktop\version-bin]();[C:\Program]() Files\PowerShell\7\;[C:\Program]() Files\Java\jdk-17.0.1;[C:\Program]() Files\apache-maven-3.8.4-bin\apache-maven-3.8.4\bin;[C:\Program]() Files\nodejs\;[C:\ProgramData\chocolatey\bin]();[C:\Program]() Files\nodejs\node.exe;[C:\Users\meera\AppData\Local\Microsoft\WindowsApps]();[C:\src\flutter\bin]();[C:\Users\meera\.dotnet\tools]();[C:\Program]() Files\kotlinc\bin;[C:\Program]() Files\Java\jdk1.7.0_72\bin;[C:\Program]() Files\MongoDB\Server\5.0\bin;[C:\Users\meera\AppData\Local\GitHubDesktop\bin]();[C:\Users\meera\AppData\Local\Pub\Cache\bin]();[C:\Users\meera\AppData\Roaming\npm]();[C:\Program]() Files\JetBrains\WebStorm 2021.3.1\bin;[C:\Users\meera\AppData\Local\Programs\Microsoft]() VS Code\bin;[C:\Users\meera\AppData\Local\atom\bin]();[C:\src\flutter\bin\mingit\cmd]()```

**Comment by Vedsaga** [comment]
in the cmd I have installed the SQLite3
![image](https://user-images.githubusercontent.com/59083528/160434350-fd88751f-68a7-4973-b71f-feff15eb80ad.png)

**Comment by simolus3** [comment]
@Vedsaga For me, chocolatey installed `sqlite3.dll` under `C:\ProgramData\chocolatey\lib\SQLite\tools`. Once I added that to `PATH`, I can use `package:sqlite3` outside of Flutter.

For Flutter apps, the latest version of `sqlite3_flutter_libs` will bundle sqlite3 with your application, so you no longer need any custom setup for that. But be aware that things like `flutter test` runs outside of Flutter, so the setup is still necessary there.

**Comment by Vedsaga** [comment]
> @Vedsaga For me, chocolatey installed `sqlite3.dll` under `C:\ProgramData\chocolatey\lib\SQLite\tools`. Once I added that to `PATH`, I can use `package:sqlite3` outside of Flutter.
> 
> For Flutter apps, the latest version of `sqlite3_flutter_libs` will bundle sqlite3 with your application, so you no longer need any custom setup for that. But be aware that things like `flutter test` runs outside of Flutter, so the setup is still necessary there.

mm, so for time being what shall I do? Because, I checked and SQLite is installed but, when I am running windows app `not test` it is returning the same error.  I hope in upcoming update it will be pre-installed for windows just like it comes with Android and iOS

**Comment by simolus3** [comment]
Can you check that you're on `sqlite3_flutter_libs: ^0.5.5`? That's the first version to manage the sqlite3 compilation for you regardless of whether you've installed sqlite3 before.

**Comment by Vedsaga** [comment]
> Can you check that you're on `sqlite3_flutter_libs: `^0.5.5`?

I checked and it was on `^0.5.0`version. I just upgraded it to  `^0.5.5`  and now, it is working fine... :)
