### ISSUE TITLE
How can we use dynamic Multiple Where Clause?

### ISSUE THREAD

**Issue by pranay2210** [simolus3/moor#424]
Example 

```
class MainItemManager
{
  final String itemsCode;
  final String stones;
  final String materials;
  MainItemManager({this.itemsCode,this.stones,this.materials});
}

 Future<List<MainItemManager>> filterMappingJoining( //here I would pass a Map where it would contain number of keys which will be column names and List of values to compare in where contion 
example:
My Map would look Like: {StoneCut: [Center, Medium, Rounded] //from stones table, costPrice: [5000,20000,100000] //from items table  }
)  async {
    final query = await ((selectOnly(items)..addColumns([items.itemID])).join([
      leftOuterJoin(stoneMappings, stoneMappings.ItemID.equalsExp(items.itemID)),
      leftOuterJoin(stones, stones.stoneID.equalsExp(stoneMappings.StoneID)),
      leftOuterJoin(materialMappings,materialMappings.itemID.equalsExp(items.itemID)),
      leftOuterJoin(materials, materials.materialID.equalsExp(materialMappings.materialID)),
      leftOuterJoin(miscellaneousMappings,miscellaneousMappings.itemID.equalsExp(items.itemID)),
      leftOuterJoin(miscellaneouses,miscellaneouses.miscellaneousID.equalsExp(miscellaneousMappings.miscID)),

    ])..where()..where().get();
//number of where() would be dynamic

 return query.map((result){
      return MainItemManager(
        itemsCode: result.read(items.itemID),
        stones: result.read(stones.stoneID),
        materials: result.read(materials.materialID)
      );
    }).toList();

```
so here my while conditions can be dynamic from any of the tables present in the joins and multiple where could be there so how can i pass the multiple conditions ?

**Comment by simolus3** [comment]
Something like this should work:
```dart
Future<List<MainItemManager>> filterMappingJoining(Map<String, List<Variable> values) async {
  final query = ((selectOnly(items)..addColumns([items.itemID])).join([
      leftOuterJoin(stoneMappings, stoneMappings.ItemID.equalsExp(items.itemID)),
      leftOuterJoin(stones, stones.stoneID.equalsExp(stoneMappings.StoneID)),
      leftOuterJoin(materialMappings,materialMappings.itemID.equalsExp(items.itemID)),
      leftOuterJoin(materials, materials.materialID.equalsExp(materialMappings.materialID)),
      leftOuterJoin(miscellaneousMappings,miscellaneousMappings.itemID.equalsExp(items.itemID)),
      leftOuterJoin(miscellaneouses,miscellaneouses.miscellaneousID.equalsExp(miscellaneousMappings.miscID)),
    ]);

  final table = allTables.singleWhere((t) => t.$tableName == yourTable);
   for (final entry in values.entries) {
     final column = table.columnsByName[entry.key];
     final columnMatches = entry.values.fold(null, (condition, element) {
       if (condition == null) return column.equalsExp(element);
       return condition | column.equalsExp(element);
     });     

     query.where(columnMatches);
   }
   
   final results = await query.get();
   // can now map those
}
```

You should probably also include stones and materials in `addColumns` - right now you're only using `items.ItemID`.

**Comment by pranay2210** [comment]
> Something like this should work:
> 
> ```dart
> Future<List<MainItemManager>> filterMappingJoining(Map<String, List<Variable> values) async {
>   final query = ((selectOnly(items)..addColumns([items.itemID])).join([
>       leftOuterJoin(stoneMappings, stoneMappings.ItemID.equalsExp(items.itemID)),
>       leftOuterJoin(stones, stones.stoneID.equalsExp(stoneMappings.StoneID)),
>       leftOuterJoin(materialMappings,materialMappings.itemID.equalsExp(items.itemID)),
>       leftOuterJoin(materials, materials.materialID.equalsExp(materialMappings.materialID)),
>       leftOuterJoin(miscellaneousMappings,miscellaneousMappings.itemID.equalsExp(items.itemID)),
>       leftOuterJoin(miscellaneouses,miscellaneouses.miscellaneousID.equalsExp(miscellaneousMappings.miscID)),
>     ]);
> 
>   final table = allTables.singleWhere((t) => t.$tableName == yourTable);
>    for (final entry in values.entries) {
>      final column = table.columnsByName[entry.key];
>      final columnMatches = entry.values.fold(null, (condition, element) {
>        if (condition == null) return column.equalsExp(element);
>        return condition | column.equalsExp(element);
>      });     
> 
>      query.where(columnMatches);
>    }
>    
>    final results = await query.get();
>    // can now map those
> }
> ```
> 
> You should probably also include stones and materials in `addColumns` - right now you're only using `items.ItemID`.

Do you mean Stone ID and Material ID? from items table

**Comment by pranay2210** [comment]
will this solution work for comparing price ranges like isBetween() in where conditions?

**Comment by pranay2210** [comment]
I have changed my code a bit I have removed Map and using a List of objects to store the selected filters, So I'll probably pass the List of objects in my query function so how can I use them for querying my code

> My class to store the tablename, columnName and list of selected values

`class StoreSelectedFilterValues
{
  String tableName;
  String columnName;
  List<String> valuesforSelectedFilters;

  StoreSelectedFilterValues(this.tableName,this.columnName,this.valuesforSelectedFilters);

}`

> My function to store the values  in a List

` StoreSelectedFilterValues storeSelectedFilterValues;
  StoreSelectedFilterValues filterGetSelectedValues(String tableName,String columnName, List<String> values)
  {
          storeSelectedFilterValues = new StoreSelectedFilterValues(tableName, columnName, values);
          return storeSelectedFilterValues;
  }

  List<StoreSelectedFilterValues> storeObj= new List<StoreSelectedFilterValues>();
    storeObj.add(filterGetSelectedValues("Items", "costPrice", sampleList));
    storeObj.add(filterGetSelectedValues("Stones", "stoneCut", sampleList));
`

> My Database Query Function
`  Future<List<MainItemManager>> testOperationForSelectedFilter(List<StoreSelectedFilterValues> values)  async {


    final query = await ((selectOnly(items)..addColumns([items.itemID])).join([
      leftOuterJoin(stoneMappings, stoneMappings.ItemID.equalsExp(items.itemID)),
      leftOuterJoin(stones, stones.stoneID.equalsExp(stoneMappings.StoneID)),
      leftOuterJoin(materialMappings,materialMappings.itemID.equalsExp(items.itemID)),
      leftOuterJoin(materials, materials.materialID.equalsExp(materialMappings.materialID)),
      leftOuterJoin(miscellaneousMappings,miscellaneousMappings.itemID.equalsExp(items.itemID)),
      leftOuterJoin(miscellaneouses,miscellaneouses.miscellaneousID.equalsExp(miscellaneousMappings.miscID)),
    ]));

    final table = allTables.singleWhere((t) ...{//the solution you provided for the map was fine but I would not be able to get tableName, I had to pass it dynamically to query all the columns from different tables and put all the where conditions so How would I do here in this case of My List which I'm passing}


    return query.map((result){
      return MainItemManager(
          itemsCode: result.read(items.itemID),
          stones: result.read(stones.stoneID),
          materials: result.read(materials.materialID)
      );
    }).toList();

  }
`

**Comment by pranay2210** [comment]
I'm getting this values and error while using your given approach  

> flutter: TABLE: Instance of '$StonesTable'
flutter: Splitted: stone_i_d
flutter: ELEMENT: 13614
flutter: COLUMN: Instance of 'GeneratedTextColumn'
flutter: ELEMENT: 13615
flutter: COLUMN: Instance of 'GeneratedTextColumn'
flutter: Error:NoSuchMethodError: Class '_Comparison' has no instance method '|'.
Receiver: Instance of '_Comparison'
Tried calling: |(Instance of '_Comparison')
flutter: Moor: Sent SELECT * FROM classifications WHERE parent_classification_i_d = ?; with args [20876]
flutter: Entered parent ID: 20876

**Comment by simolus3** [comment]
> Do you mean Stone ID and Material ID? from items table

Ah probably, yes. But if you're only interested in one table, I'm wondering why you would join all the other tables - do you need them for potential use in the where clause?

> Error:NoSuchMethodError: Class '_Comparison' has no instance method '|'.
Receiver: Instance of '_Comparison'

The `|` should be an extension method. Maybe if you use `fold<Expression<boolean, BoolType>>` it will be inferred properly.

**Comment by pranay2210** [comment]
> > Do you mean Stone ID and Material ID? from items table
> 
> Ah probably, yes. But if you're only interested in one table, I'm wondering why you would join all the other tables - do you need them for potential use in the where clause?

Actually My itemId is mapped in stoneMapping table with stoneIDs and stones table has all the details, so is that the right way to join all the tables with items table that is the main one?

**Comment by pranay2210** [comment]
> The `|` should be an extension method. Maybe if you use `fold<Expression<boolean, BoolType>>` it will be inferred properly.

I'm still confused about the fold(null,condition,element){} what is condition? and in my list I'm storing only ColumnName and their selected values so how will it get mapped with myMap.values.fold(null,condition,element){}

**Comment by simolus3** [comment]
> I'm still confused about the fold(null,condition,element){} what is condition

It will build a chain like `column = ? OR column = ? OR column = ?` in sql, where the variables will be bound to the `Variable` passed to the function. It's basically an `isIn` for variables.

> The method 'writeInto' was called on null.

Can you post a stack trace or try to figure out what exactly is `null` in this case?

**Comment by pranay2210** [comment]
Can you make an example for this part 
` final columnMatches = entry.value.fold(null,(condition,element){
if(condition==null) {
  return column.equals(element);
}
else if(//what will be this condition if I have to check 'isIN' Expression){
}
}`

or
` final columnMatches = entry.value.fold<Expresion<bool,BoolType>>{
if(condition==null) {
  return column.equals(element);
}
else if(//what will be this condition if I have to check 'isIN' Expression){
}
}`

**Comment by simolus3** [comment]
I started to use `fold` as a replacement for `isIn` since `isIn` doesn't work for variables - sorry if that caused confusion.

I see that your filter class is now this:
```dart
class StoreSelectedFilterValues {
  String tableName;
  Map<String,List<String>> valuesforSelectedFilters;
  StoreSelectedFilterValues(this.tableName,this.valuesforSelectedFilters);
}
```
If you want to apply a `List<StoreSelectedFilterValues>` as a list, you can use `fold` while iterating over all columns:
```dart
// List<StoreSelectedFilterValues> filterValues
for (final filter in filterValues) {
  final table = allTables.singleWhere((t) => t.actualTableName == filter.tableName);
  final predicate = filter.valuesforSelectedFilters.entries.fold<Expression<bool, BoolType>>(null, (condition, element) {
    // you might have to remove the () from element.key if that's how you get them
    final column = table.columnsByName[element.key]; 
    assert(column != null);
    
    final predicateForColumn = column.isIn(element.values);
    return condition == null ? predicateForColumn : condition | predicateForColumn;
  });
  query.where(predicate);
}
```

**Comment by pranay2210** [comment]
It's giving me an error while I execute and call
```
 appDatabase.testOperationForSelectedFilter(storeObj).then((t) {
      print("Printing Query Test: ${t[0].stones}");
    }).catchError((error) => print("Error:$error"));
```

> flutter: Error:RangeError (index): Invalid value: Only valid value is 0: 1

**Comment by simolus3** [comment]
Can you post the stack trace? If it happens inside your callback, can you post what value `t` has?

**Comment by pranay2210** [comment]
> NoSuchMethodError: The method 'stop' was called on null.Receiver: null Tried calling: stop()

t= {_GrowableList}size = 0

**Comment by simolus3** [comment]
Sorry for the back-and-forth on this, but I think I need more information on where the error happened. Flutter should print a trace of methods that caused the error, can you post that?

If you can post a small sample with table definitions for me to try out, I can take a direct look at the problem myself and figure out what's going on.

**Comment by pranay2210** [comment]
Thank you Simon, My issue is solved.
