### ISSUE TITLE
Documentation unclear at migration strategy

### ISSUE THREAD

**Issue by krabbenprgr** [simolus3/moor#428]
> Post-migration callbacks 
>  Starting from moor 1.5, you can use the beforeOpen parameter in the MigrationStrategy which will be called **after** migrations, but **after** any other queries are run. You could use it to populate data after the database has been created:

Is beforeOpen really called as described here in documentation?  Ether the 2nd "after" should be "before" or instead of "but" you should use "and".

**Comment by simolus3** [comment]
Ah yes, of course - thanks! I've improved this section at 51ba217484fb88d731608c117a2e6d83a003b1a5, which will go live with the next moor release.
