### ISSUE TITLE
Web support planned?

### ISSUE THREAD

**Issue by JulianBissekkou** [simolus3/moor#43]
We are currently developing an app that uses Flutter for mobile and AngularDart for Web. 
It would be cool if we could have an abstraction for creating queries and also an abstraction for the underlying framework such as SQLite or AlaSQL. 
Are there already any plans? 
How much effort would this be?

**Comment by simolus3** [comment]
I've already taken a quick look at AlaSQL and considered adding web support for moor using that library in the past. The effort would depend entirely on how different AlaSQL is to sqlite, I didn't take an in-depth look yet. I'll do that soon.

**Comment by simolus3** [comment]
Started some work for this on the `web` branch, I hope to make a working prototype out of that next week.

**Comment by JulianBissekkou** [comment]
Great news, let me know when it's ready. I will have a look at it with my team then! :)

**Comment by simolus3** [comment]
Sorry for the delay on this. Unfortunately, AlaSQL has some issues which makes it really hard to work with. It doesn't support some sqlite functions, doesn't persist table changes (so default values will be gone when reloading the page) and doesn't really support migrations. I've used some hacky workarounds to counter some of these problems, but the whole thing is still very unreliable. It also doesn't seem to be very well maintained, having many important issues open for a long time.

I'll try [sql.js](https://github.com/kripken/sql.js) next. It requires webassembly, but that should be available on most modern browsers anyway.  The big advantage is that it will behave exactly the same as sqlite, although persisting changes is a bit tricky at the moment.

**Comment by simolus3** [comment]
`sql.js` is looking more promising indeed, I managed to get a minimal prototype with persistence working. What still needs to be done:
- [ ] Transactions
- [ ] Batched statements
- [ ] Returning the insert id for `INSERT` statements
- [ ] The new "before open but after migrations" callback from version 1.5
- [ ] Tests!

**Comment by simolus3** [comment]
So this landed in `develop` and will be a part of moor 1.6! I've written some documentation on how to use moor for the web [here](https://moor.simonbinder.eu/web). 

If you want to try this out now, you'll need to use a dependency override pointing to the `moor/` folder on the `develop` branch in this repo. Also, don't consider the format in which the database is stored finalized yet, it will be changed (which breaks existing databases) before version 1.6 is released publicly.

Here is the [source code](https://github.com/simolus3/moor/tree/develop/moor/example_web) for a simple todo app built using moor and flutter for web. It's deployed [here](http://simonbinder.eu/demo/). You can see the sql statements sent in the console.

**Comment by JulianBissekkou** [comment]
Really cool 💪🏼! Thanks for the effort 🙏🏻! 
I will try it out and give you feedback asap.

**Comment by simolus3** [comment]
FYI, the breaking encoding change is now on `develop` - the way databases are stored is final now, but you need to `localStorage.clear()` pages where you've already used moor for web.

Also, web support now lives on `beta` and I'll hopefully release it on pub later this week. Closing this issue now as web support is done. If you run into any issues, please let me know by opening another issue, thanks!

**Comment by simolus3** [comment]
If you're using (or plan on using) drift with web apps, I'm currently looking for feedback to help get this feature stable. So if you have the time, sharing feedback about the ideas in https://github.com/simolus3/drift/issues/2382 would help stabilize this feature!
