### ISSUE TITLE
Transactions during onCreate and onUpgrade

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#430]
Hi, we are in the process of migrating a big Flutter project with the raw `sqflite` to `moor`. 
In the `sqflite` library, during the database opening and migration, if some unexpected error happens, the operations are rollbacked because `sqflite` internally uses a transaction when opening.
Since `moor` does not do that, we tried using the transaction method from `moor` inside the onCreate. The problem is that the transaction is never executed because it seems that internally is waiting for the moor db to be open (which technically is, but not for moor).
https://github.com/simolus3/moor/blob/808d19493990224be4768e298ace01bbfc12a8f3/moor/lib/src/runtime/api/query_engine.dart#L292
This seems to be a bug, because most times people want to make sure that when a migration / creation process runs, is not half way done from a previous execution.

**Comment by simolus3** [comment]
Yes, I think those callbacks should implicitly use a transaction on all executors. I don't see why anyone would want migrations to _not_ be transactional, so just making that the default parameter seems reasonable.

**Comment by Mike278** [comment]
One reason I can think of is that PRAGMA foreign_keys is a [no-op inside a transaction](https://www.sqlite.org/pragma.html#pragma_foreign_keys), and with sqlite’s limited ALTER TABLE support any kind of table change typically needs to go through [this procedure](https://www.sqlite.org/lang_altertable.html#otheralter)

**Comment by simolus3** [comment]
Good point, running migrations in a transaction by default doesn't seem like a good idea for moor.

In moor 3.0, you'll be able to manually use `transaction`-blocks inside of a migration.

**Comment by davidmartos96** [comment]
Thanks a lot @simolus3 ! Adding transaction blocks manually is perfectly fine, and seems reasonable from @Mike278 comment.
