### ISSUE TITLE
Isolate stuck when using MigrationStrategy with beforeOpen parameter

### ISSUE THREAD

**Issue by uocnb** [simolus3/moor#431]
**Hi!** I'm using `moor` and `moor_ffi` with isolate on Windows with Flutter. Everything stuck when using `MigrationStrategy` with `beforeOpen` parameter. All statement inside the callback stuck forever. Took me few hours to tracing the cause. I don't have problem when comment out `beforeOpen` and run the init database function from DAO outside.

The code is similar the isolate sample on the document page. I'm using `beforeOpen` to populate data with `details.wasCreated`. My code is work well without isolate mode and isolate mode without `MigrationStrategy`.

Sample code is provided as below:
```
@override
  MigrationStrategy get migration => MigrationStrategy(
    onCreate: (Migrator m) async {
      print('Database: create all tables');
      await m.createAll();
    },
    /// Migration
    onUpgrade: (Migrator m, int from, int to) async {
      if (from == 1) {
      }
    },
    /// Post-migration
    // beforeOpen: (details) async {
    //   if (details.wasCreated) {
    //     /// Init database
    //     print('Database: Init data');

    //     await dataDao.init();  // stuck with every statement here event with select
        
    //     print('Database: Init done');
    //   }
    //   await customStatement('PRAGMA foreign_keys = ON');
    // },
  );
```

**Comment by simolus3** [comment]
Thanks for the report! I've fixed this problem on master and I'll release a fix to pub tomorrow.

**Comment by uocnb** [comment]
Cool, thanks for quick action! 💯
