### ISSUE TITLE
Example for `Like` in query

### ISSUE THREAD

**Issue by erwintan96** [simolus3/moor#434]
how to use like in moor for search? Do you have any example?
`
Future<List<ProductGroupWithBrandType>> getProductGroup({int limit = 0, int offset = 40, String search = ""}) async{
    print("search  : " + search);
      final query = await ((select(productGroupTable)
          ..limit(limit, offset: offset)
          ..orderBy([
                (t) =>
                OrderingTerm(expression: t.name, mode: OrderingMode.asc)
          ])
      )..where((productGroup)=> productGroup.name.like(search)))
          .join(
          [
            leftOuterJoin(brandTable, brandTable.id.equalsExp(productGroupTable.brand)),
            leftOuterJoin(typeTable, typeTable.id.equalsExp(productGroupTable.type)),
          ])..get();

      return query.map((result){
        return ProductGroupWithBrandType(
          productGroup: result.readTable(productGroupTable),
          brand: result.readTable(brandTable),
          type: result.readTable(typeTable),
        );
      }).get();

  }
`
This is my code and always return empty. I dont know how to solve this, could you help me?
Thank you..

**Comment by joielechong** [comment]
Try to do the join first, then call the `where`, something like this in my case:

```
    final query = select(songs).join(
        [leftOuterJoin(bands, bands.id.equalsExp(songs.bandId))])
      ..where(bands.name.like(searchPattern) | songs.title.like(searchPattern));

    final rows = await query.get();
```

**Comment by simolus3** [comment]
You're calling `..get();` on the query (note the two dots). Just using `.get()` should work. See the [cascade operator](https://news.dartlang.org/2012/02/method-cascades-in-dart-posted-by-gilad.html) for details.

**Comment by simolus3** [comment]
@erwintan96 Did that solve your problem? I'll close this issue since it looks like there isn't anything substantial to add anymore. If you have more questions, please let me know. Thanks!
