### ISSUE TITLE
Get full row after insertion

### ISSUE THREAD

**Issue by apoleo88** [simolus3/moor#436]
Hi!
After a simple insert query, I would like to have the object with its new id, can I get it without having to query for it again?

```
Future insertPerson(Person task) => into(persons).insert(task, orReplace:true);

Person joe = Person(name: "Joe")
queryResult = database.insertPerson(joe);
queryResult.then((inserted_id){
  // I have the id, but not the full Person Object with the id
  // Unfortunately, joe.id is still null and I can't add the id to my existent object, 
  // because id is final:
  joe.id = inserted_id; // Error
});
```

There is a way to accomplish it?

**Comment by apoleo88** [comment]
Just found the solution on another answer https://github.com/simolus3/moor/issues/411
`joe = joe.copyWith(id: inserted_id);`

I don't agree with the reason for this design, people know that it needs an extra step to save it.

Anyway Thanks!

**Comment by zatovagul** [comment]
I am also looking for that solution
