### ISSUE TITLE
Copy database from assets which has multiple tables with content 

### ISSUE THREAD

**Issue by nbsathawara** [simolus3/moor#439]
Hi,
@simolus3  

I have already prefilled SQLite DB which I want to use in my flutter application with few new tables.
My existing DB has 4-5 tables with around 1000 rows.

So I have followed the below link;
https://moor.simonbinder.eu/docs/other-engines/vm/#using-moor-ffi-with-an-existing-database

Assets DB has copied successfully in the application, But when I query the tables, which were already existing, it shows 0 records.

My database file looks like below;

```dart
String dbPath;
String dbName = "data.sqlite";

class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;

  getAllTables() async {
    for (var table in allTables) {
     await select(table).get().then((data){
       AppDebugLog.println('table : ${table.actualTableName} : ${data.length}');
     });
    }
  }
}

LazyDatabase _openConnection() {
  try {
    return LazyDatabase(() async {
      var dbFolder = await getApplicationDocumentsDirectory();
      dbPath = p.join(dbFolder.path, dbName);

      final file = File(dbPath);
      if (!file.existsSync()) {
        // copy the file from an asset, or network, or any other source
        // Should happen only the first time you launch your application
        AppDebugLog.println('Copy DB from assets : ');

        // Make sure the parent directory exists
        await Directory(dirname(dbPath)).create(recursive: true);

        // Copy from asset
        var data = await rootBundle.load(join('assets', dbName));
        List<int> bytes =
            data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
        //AppDebugLog.println('Assets DB : $bytes');

        // Write and flush the bytes written
        await file.writeAsBytes(bytes, flush: true);
      } else {
        AppDebugLog.println('Open existing DB :');
      }
      var db = VmDatabase(file); 
      return db;
    });
  } catch (ex) {
    AppDebugLog.println('Exception in _openConnection : ' + ex.toString());
  }
  return null;
}
```

Thanks,
Nikhil Sathawara.

**Comment by simolus3** [comment]
Your code looks alright to me. Does the `actualTableName` match the table name in your pre-existing database?

**Comment by nbsathawara** [comment]
Hi,
@simolus3 
You were right, the auto generated actualTableNames were different than mine exiting table names.
I have to manually modified them.
After that I got my records.

Thanks for the help.

**Comment by simolus3** [comment]
Glad I could help!

> I have to manually modified them.

If you had to change the generated code, note that you can also override the [`tableName`](https://pub.dev/documentation/moor/latest/moor_web/Table/tableName.html) getter directly in your table class. Moor will then pick it up directly, which means that you don't have to change your code every time after running the builder.

**Comment by nbsathawara** [comment]
@simolus3 
Yes, You are right we can override tableName and moor will assign that name to tables.
I have changed code as per that.
Thanks.
