### ISSUE TITLE
Frequently asked questions

### ISSUE THREAD

**Issue by krabbenprgr** [simolus3/moor#440]
Provider with builder is deprecated as told in documentation:
`Provider<MyDatabase>(
      builder: (context) => MyDatabase(),
      child: MyFlutterApp(),
      dispose: (context, db) => db.close(),
   )`

 Better would be:
`Provider<MyDatabase>(
    create: (BuildContext context) => MyDatabase(),
    child: MyApp(),
    dispose: (context, db) => db.close(),
  )`

**Comment by simolus3** [comment]
Thanks! I've fixed this on develop, so it will eventually go live with the next moor version.
