### ISSUE TITLE
How to handle tests with mockito and mocked database class?

### ISSUE THREAD

**Issue by UtkarshKunwar** [simolus3/moor#441]
Running tests as mentioned in the documentation is working fine, but I just wanted to know why it fails when implementing the database with `mockito`.

I was following ResoCoder's tutorials and was trying to write tests for `moor` and came across this issue. Is using `mockito` with `moor` not recommended?

My test code is as follows
```
class MockAppDatabase extends Mock implements AppDatabase {}

void main() {
  /* Throws error during tests otherwise.
   * https://github.com/flutter/flutter/issues/40253
   */
  TestWidgetsFlutterBinding.ensureInitialized();

  MockAppDatabase db;
  final tItemsCompanion = ItemsCompanion (
    name: Value('test'),
    value: Value(123),
  );

  setUp(() {
    /* To expose path_provider to tests.
     * https://github.com/flutter/flutter/issues/10912#issuecomment-587403632
     */
    const MethodChannel channel =
        MethodChannel('plugins.flutter.io/path_provider');
    channel.setMockMethodCallHandler((MethodCall methodCall) async {
      return ".";
    });

    db = MockAppDatabase();
  });

  tearDown(() async {
    await db.close();
  });

  test('item can be created', () async {
    // Arrange
    final id = await db.insertItem(tItemsCompanion);
    // Act
    final item = await db.watchItemWithId(id).first;
    // Assert
    expect(item.name, 'test');
  });
}

```
where the `insertItem` and `watchItemWithId` methods (and the database with the `_openConnection()`) adhere to the ones in documentation.

I get `id` as `null` when using `mockito` but I get a valid integer when test without `mockito`.

**Comment by simolus3** [comment]
When you're mocking the whole `AppDatabase`, no moor method will be called. In your test, `insertItem` and `watchItemWithId` would be delegated to the `MockAppDatabase` class. The default implementation of mockito is to do nothing or return null, which is what you're seeing in your test.

There is nothing preventing you from mocking your database class, but it will circumvent moor functionality. If you want to add behavior to the mocked class, you'd have to use `when(db.insertItem(any)).then...`, just like with other classes. To test applications using moor, the best way is to use a in-memory sqlite database with moor_ffi, as explained [here](https://moor.simonbinder.eu/docs/testing/).
