### ISSUE TITLE
What is the best way to create indices? 

### ISSUE THREAD

**Issue by andreineacsu** [simolus3/moor#442]
What is the best way to create indices? 
My tables are defined in dart files extending the Table class. 

Any help would be highly appreciated. 

Thanks,
Andrei

![Screenshot 2020-03-14 at 12 41 17](https://user-images.githubusercontent.com/3153007/76680450-2e81be80-65f1-11ea-8e93-2f3f3bd0c490.png)

**Comment by simolus3** [comment]
At the moment, indices are only supported in moor files.

You can create a [moor file](https://moor.simonbinder.eu/docs/using-sql/moor_files/) and import Dart files into it. So if you had a moor file next to `database.dart`, you could write
```sql
import 'company_locations/company_locations.dart';

CREATE INDEX company_locations_company_index ON company_locations (company_id);
```
If you then add that moor file to the `include` section in `@UseMoor`, the index will be recognized by moor. Note that creating the index requires a schema migration, you can use `Migrator.createIndex(companyLocationsCompanyIndex)`

**Comment by andreineacsu** [comment]
@simolus3 Thanks a lot for your fast reply. 
I added the moor file but not I get an error. It seems like the table is being generate twice now? 

![Screenshot 2020-03-14 at 14 54 38](https://user-images.githubusercontent.com/3153007/76682322-dacca080-6603-11ea-97c8-e524cda858fc.png)

**Comment by simolus3** [comment]
That looks like a bug in the generator, good catch! As a workaround, I think you can remove `FieldValidationsTable` from the `@UseMoor` annotation. It will still be included since the moor file requires it.

**Comment by andreineacsu** [comment]
Thanks for the suggestion. It works and everything seems to be working just fine. 
Thank you for your help.

**Comment by simolus3** [comment]
Great! I've opened #447 for the bug you've seen, but it will be some work to resolve and it's not a high priority for me.
