### ISSUE TITLE
How to access dao without context?

### ISSUE THREAD

**Issue by Nailik** [simolus3/moor#448]
Hi,

In all the Tutorials like 
https://resocoder.com/2019/07/10/moor-room-for-flutter-2-advanced-queries-daos-fluent-sqlite-database/#Creating_a_DAO
the Daos are used in a Widget.

What is when i have a class that's maybe running in the Background and has no BuildContext, how do i access the daos?
Make the Database static in main and grab it or is there a better way?

**Comment by simolus3** [comment]
> Make the Database static in main and grab it

That's would work, yes. As long as you'll only have one database instance, you'll be fine. Moor doesn't put any limitation on how the database would be accessed, using providers is just the simplest solution.

> or is there a better way?

A framework for dependency injection (or at least a service locator) would help here. Packages like `get_it`, `kiwi` or `inject` are pretty good for this purpose. One advantage of passing the database around in constructors and managing those with a library is that it's much easier to write tests. With static fields it can get a little tricky.

**Comment by kay14** [comment]
> A framework for dependency injection (or at least a service locator) would help here. Packages like get_it, kiwi or inject are pretty good for this purpose. One advantage of passing the database around in constructors and managing those with a library is that it's much easier to write tests. With static fields it can get a little tricky.

Are there any tutorials for this somewhere? I am new to dart and flutter and some tutorials would be really helpful at this point. Thank you!

**Comment by simolus3** [comment]
There's a more detailed tutorial on `get_it` [here](https://medium.com/filledstacks/dependency-injection-in-flutter-2225d3081f61). But its [readme](https://pub.dev/packages/get_it) also contains everything you need to know.

For moor, you just have to register your database class as a singleton.
