### ISSUE TITLE
Support min/max function

### ISSUE THREAD

**Issue by vietnguyen312** [simolus3/moor#455]
It will be great if you can support min/max function similar to SQL Lite so we don't need to write raw Query to retrieve data.

**Comment by simolus3** [comment]
We already support [`max`](https://pub.dev/documentation/moor/latest/moor_web/ArithmeticAggregates/max.html) and [`min`](https://pub.dev/documentation/moor/latest/moor_web/ArithmeticAggregates/min.html) from the Dart api. More details on group by are available [here](https://moor.simonbinder.eu/docs/advanced-features/joins/#group-by). Is that what you need?

**Comment by vietnguyen312** [comment]
Sorry for providing a lack of context. I want to use **min** and **max** in **Group by** clause without joining any table. Please refer to the example below


![image](https://user-images.githubusercontent.com/12994658/77495653-ce560c80-6e7b-11ea-906a-672939a140c8.png)

I want to calculate **min/max** price **group by** SupplierId

**Comment by simolus3** [comment]
Right. You can use `selectOnly` for that:
```dart
final minPrice = table.price.min();
final maxPrice = table.price.max();
final query = selectOnly(table)
  ..addColumns([table.supplierId, minPrice, maxPrice])

return query.map((row) {
  final supplier = row.read(table.supplierId);
  // you can also read(minPrice) and read(maxPrice) here
}).get();
```

**Comment by givip** [comment]
It is not possible to use like this: 
```
final maxValue = readMarkers.updatedAt.max();
return (select(readMarkers)..where((tbl) => tbl.updatedAt.equalsExp(maxValue)))
   .getSingle();
```

got Exception `SqliteException(1): misuse of aggregate function MAX(), SQL logic error (code 1)`

**Comment by simolus3** [comment]
Yeah, you can't use aggregate functions in `WHERE` because that clause is evaluated before aggregation happens. In this case you could `OrderBy.desc(maxValue)` and limit the result to one row.
