### ISSUE TITLE
Question: How to parse json string?

### ISSUE THREAD

**Issue by pY4x3g** [simolus3/moor#459]
A simple parsing of the generated json fails if using a BlobColumn, eg.

MyClass.fromJson(myObject.toJson())

the error is:
type 'List<dynamic>' is not a subtype of type 'Uint8List' in type cast
_DefaultValueSerializer.fromJson (package:moor/src/runtime/data_class.dart:125:17)

**Comment by pY4x3g** [comment]
nvm my fault its working as expected

**Comment by pY4x3g** [comment]
Let me reformulate my problem: I want to parse the String from the toJsonString method and I do not know how to do it, i tried the following:

MyClass.fromJson(jsonDecode(myObject.toJsonString()))

but that leads me to the exception as mentioned above.

**Comment by simolus3** [comment]
Good point, thanks. This should be fixed with the referenced commit, which will be in the next moor release.

As a workaround until then, you can make moor use the fixed serializer:
```dart
class FixedSerializer extends ValueSerializer {
  const FixedSerializer);

  @override
  T fromJson<T>(dynamic json) {
    if (T == DateTime) {
      if (json == null) {
        return null;
      } else {
        return DateTime.fromMillisecondsSinceEpoch(json as int) as T;
      }
    }

    if (T == double && json is int) {
      return json.toDouble() as T;
    }

    // blobs are encoded as a regular json array, so we manually convert that to
    // a Uint8List
    if (T == Uint8List && json is! Uint8List) {
      final asList = (json as List).cast<int>();
      return Uint8List.fromList(asList) as T;
    }

    return json as T;
  }

  @override
  dynamic toJson<T>(T value) {
    if (value is DateTime) {
      return value.millisecondsSinceEpoch;
    }

    return value;
  }
}

// somewhere before you use moor:
void main() {
  moorRuntimeOptions.defaultSerializer = const FixedSerializer();
}
```

**Comment by pY4x3g** [comment]
Thank you very much for the fast fix :)
