### ISSUE TITLE
Delete using batch doesn't update stream

### ISSUE THREAD

**Issue by kira1752** [simolus3/moor#460]
So this morning i found that using **batch.delete()** inside **batch(() {})** doesn't update data that **listen** from **stream.** The same also happen when using **delete().delete()** inside **transaction().** 

Using **delete().delete()** normally with **for loop** works as expected. Sorry for my bad english.

**Comment by simolus3** [comment]
Good catch, thank you for the report!

This will be fixed in the next moor release. In the meantime, you could use the for-loop approach or manually call `database.notifyUpdates({updatedTable})`

**Comment by kira1752** [comment]
Thank you for your quick response, let me thanks you for this excellent package that you create and your hard work and quick response to solve bug in this package.

**Comment by kuhnroyal** [comment]
@simolus3
> or manually call database.notifyUpdates({updatedTable})
The correct call seems to be `database.markTablesUpdated({updatedTable})`.
I am having a similar problem with cascading deletes not updating the stream. Now that I think about this I am not sure that moor actually knows about these dependencies.
