### ISSUE TITLE
Store json as string instead of parsing

### ISSUE THREAD

**Issue by CripyIce** [simolus3/moor#462]
Hi there,
I would like to know how can I store a json object/array as a string inside a table without parsing it - just pure json string.
This is the json I'm getting and want to store as a string and parse it myself later on:
```json
{
  "id": 166,
  "activity_hours": {
    "Mon": {
      "hours": [
        [
          "08:00",
          "12:00"
        ],
        [
          "13:00",
          "15:00"
        ]
      ],
      "is_closed": false
    },
    "Tue": {
      "hours": [
        [
          "08:00",
          "09:00"
        ],
        [
          "10:00",
          "15:00"
        ]
      ],
      "is_closed": false
    },
    "Wed": {
      "hours": [],
      "is_closed": false
    }
  }
}
```

I couldn't find any answers.
Thanks!

**Comment by simolus3** [comment]
If you don't want moor to automatically parse your json, you can just save it as a `text` column. Moor then generates a `String` field in all classes, so you can parse the json yourself when you need it. When storing data in a database, you would have to manually call `json.encode()`.

Is that what you needed? I'll gladly provide more details if you run into a specific problem.
