### ISSUE TITLE
The method 'getDisplayString' isn't defined for the class 'DartType'

### ISSUE THREAD

**Issue by shadracktaeli** [simolus3/moor#463]
Upgraded to the latest flutter and getting this error when running `flutter packages pub run build_runner watch`.

Had to manually change the files to use the `displayName` property instead of `getDisplayName` function

**Comment by shadracktaeli** [comment]
oh nvm. didn't run `flutter packages pub run build_runner clean` after upgrading

**Comment by shadracktaeli** [comment]
okay, so this is not released yet. how do I use `master`?

**Comment by shadracktaeli** [comment]
this is my temp work around for now. 
```bash
find ~/.pub-cache/hosted/pub.dartlang.org/moor_generator-2.4.0/lib/src -name '*.dart' -exec sed -i "" 's/getDisplayString()/displayName/g' {} \;
```

**Comment by simolus3** [comment]
Thanks for the report. It looks like `getDisplayString` was added in analyzer 0.39.3, so `moor_generator` has an incorrect version span in its pubsec (it depends on `^0.39.0`).

Unfortunately this is almost impossible to fix after such version is on pub - I can release a new version with the fixed range, but pub might still resolve to the old one.

You could try adding an explicit `analyzer` dependency:
```yaml
dev_dependencies:
  analyzer: ^0.39.3
```

I think `flutter pub upgrade` might help as well if there aren't any conflicts.

**Comment by shadracktaeli** [comment]
`flutter pub upgrade` wasn't upgrading my `analyzer` because of a conflict. Thanks and Moor is awesome 🙂

**Comment by shadracktaeli** [comment]
Off topic question. Is there a way to get a list from a join? A join only returns a single object unless I'm doing it wrong?

**Comment by simolus3** [comment]
You're welcome! Sadly there is not a way to get a list from a join directly. If you want to have result sets where a column essentially has an array of values, you would have to split that into multiple selects. If that's what you mean with list from a join. If you just want to read multiple rows that should work with `.get()` returning a `List<TypedRow>`.
