### ISSUE TITLE
Can't run moore in isolate

### ISSUE THREAD

**Issue by cadaniel** [simolus3/moor#464]
So I'm trying to run moor in an isolate and I get the following error. 

    version=2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "ios_x64"
    thread=43275, isolate=main(0x7fdd55025800)
    pc 0x0000000100eb47a4 fp 0x0000700006bce070 dart::Profiler::DumpStackTrace(void*)
    pc 0x0000000100d96c72 fp 0x0000700006bce150 dart::Assert::Fail(char const*, ...)
    pc 0x000000010107a6cb fp 0x0000700006bce1b0 dart::kernel::ScopeBuilder::VisitExpression()
    pc 0x000000010107af58 fp 0x0000700006bce240 dart::kernel::ScopeBuilder::VisitFunctionNode()
    pc 0x000000010107a9a3 fp 0x0000700006bce2a0 dart::kernel::ScopeBuilder::VisitNode()
    pc 0x0000000101079b83 fp 0x0000700006bce400 dart::kernel::ScopeBuilder::BuildScopes()
    pc 0x0000000100eb2b78 fp 0x0000700006bce660 dart::ParsedFunction::EnsureKernelScopes()
    pc 0x000000010104fd80 fp 0x0000700006bce690 dart::kernel::StreamingFlowGraphBuilder::ParseKernelASTFunction()
    pc 0x000000010104f834 fp 0x0000700006bce8d0 dart::kernel::StreamingFlowGraphBuilder::BuildGraph()
    pc 0x000000010105eddf fp 0x0000700006bceb30 dart::kernel::FlowGraphBuilder::BuildGraph()
    pc 0x0000000101087aa6 fp 0x0000700006bced20 dart::DartCompilationPipeline::BuildFlowGraph(dart::Zone*, dart::ParsedFunction*, dart::ZoneGrowableArray<dart::ICData const*>*, long, bool)
    pc 0x0000000101088f23 fp 0x0000700006bcf380 dart::CompileParsedFunctionHelper::Compile(dart::CompilationPipeline*)
    pc 0x0000000101089ee1 fp 0x0000700006bcf540 dart::CompileFunctionHelper(dart::CompilationPipeline*, dart::Function const&, bool, long)
    pc 0x00000001010899e8 fp 0x0000700006bcf5e0 dart::Compiler::CompileFunction(dart::Thread*, dart::Function const&)
    pc 0x0000000100de4ae7 fp 0x0000700006bcf680 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
    pc 0x0000000100e5c0ee fp 0x0000700006bcf9a0 dart::EvaluateCompiledExpressionHelper(unsigned char const*, long, dart::Array const&, dart::String const&, dart::String const&, dart::Array const&, dart::TypeArguments const&)
    pc 0x0000000100e5bdc6 fp 0x0000700006bcf9f0 dart::Class::EvaluateCompiledExpression(unsigned char const*, long, dart::Array const&, dart::Array const&, dart::TypeArguments const&) const
    pc 0x0000000100f09538 fp 0x0000700006bcfa80 dart::EvaluateCompiledExpression(dart::Thread*, dart::JSONStream*)
    pc 0x0000000100f01937 fp 0x0000700006bcfbf0 dart::Service::InvokeMethod(dart::Isolate*, dart::Array const&, bool)
    pc 0x0000000100f01ee1 fp 0x0000700006bcfc10 dart::Service::HandleIsolateMessage(dart::Isolate*, dart::Array const&)
    pc 0x0000000100e139de fp 0x0000700006bcfe10 dart::IsolateMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >)
    pc 0x0000000100e3d14e fp 0x0000700006bcfe90 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)
    pc 0x0000000100e3d4d0 fp 0x0000700006bcfed0 dart::MessageHandler::HandleNextMessage()
    pc 0x00000001010e6f0f fp 0x0000700006bcff60 Dart_HandleMessage
    pc 0x0000000100ceca8e fp 0x0000700006bcffb0 tonic::DartMessageHandler::OnHandleMessage(tonic::DartState*)
    pc 0x0000000100cecd74 fp 0x0000700006bcffd0 std::__1::__function::__func<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0, std::__1::allocator<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0>, void ()>::operator()()
    pc 0x0000000100936b73 fp 0x0000700006bd0040 fml::MessageLoopImpl::FlushTasks(fml::FlushType)
    pc 0x000000010093b8b8 fp 0x0000700006bd0060 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*)
    pc 0x00007fff23bd4b94 fp 0x0000700006bd0070 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
    pc 0x00007fff23bd4882 fp 0x0000700006bd1110 __CFRunLoopDoTimer
    pc 0x00007fff23bd3eda fp 0x0000700006bd1190 __CFRunLoopDoTimers
    pc 0x00007fff23bcec4e fp 0x0000700006bd1e90 __CFRunLoopRun
    pc 0x00007fff23bce066 fp 0x0000700006bd1f20 CFRunLoopRunSpecific
    pc 0x000000010093b9e3 fp 0x0000700006bd1f50 fml::MessageLoopDarwin::Run()
    pc 0x0000000100936ab8 fp 0x0000700006bd1f70 fml::MessageLoopImpl::DoRun()
    pc 0x000000010093aeec fp 0x0000700006bd1fb0 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*)
    pc 0x00007fff52466e65 fp 0x0000700006bd1fd0 _pthread_start
    Lost connection to device.
    pc 0x00007fff5246283b fp 0x0000700006bd1ff0 thread_start
    -- End of DumpStackTrace 

my code:

    import 'dart:io';
    import 'dart:isolate';
    import 'package:flutter/foundation.dart';
    import 'package:masterbilling/src/data/sync/claim_sync.dart';
    import 'package:masterbilling/src/data/sync/patient_sync.dart';
    import 'package:masterbilling/src/service/data/database_data.dart';
    import 'package:masterbilling/src/service/hive/hive_service.dart';
    import 'package:injectable/injectable.dart';
    import 'package:moor/isolate.dart';
    import 'package:moor_ffi/moor_ffi.dart';
    import 'package:moor_flutter/moor_flutter.dart';
    
    Future<MoorIsolate> _createMoorIsolate(String dbFile) async {
      // this method is called from the main isolate. Since we can't use
      // getApplicationDocumentsDirectory on a background isolate, we calculate
      // the database path in the foreground isolate and then inform the
      // background isolate about the path.
      final receivePort = ReceivePort();
    
      await Isolate.spawn(
        _startBackground,
        _IsolateStartRequest(receivePort.sendPort, dbFile),
      );
    
      // _startBackground will send the MoorIsolate to this ReceivePort
      return (await receivePort.first as MoorIsolate);
    }
    
    void _startBackground(_IsolateStartRequest request) {
      // this is the entrypoint from the background isolate! Let's create
      // the database from the path we received
      final executor = VmDatabase(File(request.targetPath), logStatements: true);
      // we're using MoorIsolate.inCurrent here as this method already runs on a
      // background isolate. If we used MoorIsolate.spawn, a third isolate would be
      // started which is not what we want!
      final moorIsolate = MoorIsolate.inCurrent(
        () => DatabaseConnection.fromExecutor(executor),
      );
      // inform the starting isolate about this, so that it can call .connect()
      request.sendMoorIsolate.send(moorIsolate);
    }
    
    // used to bundle the SendPort and the target path, since isolate entrypoint
    // functions can only take one parameter.
    class _IsolateStartRequest {
      final SendPort sendMoorIsolate;
      final String targetPath;
    
      _IsolateStartRequest(this.sendMoorIsolate, this.targetPath);
    }
    
    @injectable
    class AppInformationSyncService {
      final HiveService hiveService;
      final DatabaseData databaseData;
    
      AppInformationSyncService(this.hiveService, this.databaseData);
    
      Future<void> syncInformation(bool syncAll) async {
        var dbFile = await databaseData.getDatabasePathAndName();
        var isolate = _createMoorIsolate(dbFile);
        var lastUpdated = 0;
        if (!syncAll) {
          lastUpdated = hiveService.getLastUpdated().millisecondsSinceEpoch;
        }
        var sendMap = {"isolate": isolate, "lastUpdated": lastUpdated};
    
        //var patientSuccess = await compute(syncPatients, sendMap);
        //var claimSuccess = await compute(syncClaims, sendMap);
    
    //    if (patientSuccess && claimSuccess) {
    //      hiveService.saveLastUpdate(DateTime.now());
    //    }
      }
    } 

flutter doctor shows green across the board. 

I'm new to isolates so I'm not sure how I should actually be doing this. But the example code gets this error on the latest version of iOS

**Comment by cadaniel** [comment]
So the original error was after letting it sit. uncommenting ```var claimSuccess = await compute(syncClaims, sendMap);```

which is a top level function in another class of 

    Future<bool> syncClaims(Map<String, dynamic> jsonData) async {
      //init dependencies
      var dbConnection = await jsonData[""].connect();
      var db = BillingDatabase.connect(dbConnection);
      return true;
    } 


gives 

    version=2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "ios_x64"
    thread=23303, isolate=main(0x7fc82c024800)
    pc 0x000000010560f7a4 fp 0x0000700002be4cf0 dart::Profiler::DumpStackTrace(void*)
    pc 0x00000001054f1c72 fp 0x0000700002be4dd0 dart::Assert::Fail(char const*, ...)
    pc 0x000000010561b793 fp 0x0000700002be4df0 dart::RawFunction::WriteTo(dart::SnapshotWriter*, long, dart::Snapshot::Kind, bool)
    pc 0x0000000105672021 fp 0x0000700002be4e20 dart::SnapshotWriterVisitor::VisitPointers(dart::RawObject**, dart::RawObject**)
    pc 0x0000000105619f50 fp 0x0000700002be4ea0 dart::RawType::WriteTo(dart::SnapshotWriter*, long, dart::Snapshot::Kind, bool)
    pc 0x000000010561aa0f fp 0x0000700002be4ef0 dart::RawTypeArguments::WriteTo(dart::SnapshotWriter*, long, dart::Snapshot::Kind, bool)
    pc 0x0000000105671736 fp 0x0000700002be4f70 dart::SnapshotWriter::WriteInstance(dart::RawObject*, dart::RawClass*, long, long, bool)
    pc 0x0000000105671736 fp 0x0000700002be4ff0 dart::SnapshotWriter::WriteInstance(dart::RawObject*, dart::RawClass*, long, long, bool)
    pc 0x000000010566f51a fp 0x0000700002be5030 dart::SnapshotWriter::WriteObject(dart::RawObject*)
    pc 0x0000000105672404 fp 0x0000700002be5150 dart::MessageWriter::WriteMessage(dart::Object const&, long long, dart::Message::Priority)
    pc 0x00000001055017bf fp 0x0000700002be52e0 dart::BootstrapNatives::DN_Isolate_spawnFunction(dart::Thread*, dart::Zone*, dart::NativeArguments*)
    pc 0x000000010559a158 fp 0x0000700002be5350 dart::NativeEntry::BootstrapNativeCallWrapper(_Dart_NativeArguments*, void (*)(_Dart_NativeArguments*))
    pc 0x0000000109d81129 fp 0x0000700002be5398 Unknown symbol
    pc 0x0000000119a9d8d5 fp 0x0000700002be5420 Unknown symbol
    pc 0x0000000119a987d8 fp 0x0000700002be5510 Unknown symbol
    pc 0x000000010bbaa697 fp 0x0000700002be5548 Unknown symbol
    pc 0x000000010bbb4e76 fp 0x0000700002be5580 Unknown symbol
    pc 0x0000000119a97c4d fp 0x0000700002be5648 Unknown symbol
    pc 0x000000011808423b fp 0x0000700002be56e8 Unknown symbol
    pc 0x0000000118dbd120 fp 0x0000700002be5738 Unknown symbol
    pc 0x0000000118dbd004 fp 0x0000700002be5798 Unknown symbol
    pc 0x0000000118dbcdaf fp 0x0000700002be5818 Unknown symbol
    pc 0x0000000118dbcbbb fp 0x0000700002be5890 Unknown symbol
    pc 0x0000000118dbc42b fp 0x0000700002be5938 Unknown symbol
    pc 0x0000000118dbbe44 fp 0x0000700002be5988 Unknown symbol
    pc 0x0000000118dbba31 fp 0x0000700002be5a00 Unknown symbol
    pc 0x0000000118dbaafb fp 0x0000700002be5a80 Unknown symbol
    pc 0x0000000118db9964 fp 0x0000700002be5ac8 Unknown symbol
    pc 0x000000010bbc1504 fp 0x0000700002be5b28 Unknown symbol
    pc 0x000000010bbc0fa5 fp 0x0000700002be5b60 Unknown symbol
    pc 0x000000011a8d8ffe fp 0x0000700002be5bf8 Unknown symbol
    pc 0x0000000118dbd120 fp 0x0000700002be5c48 Unknown symbol
    pc 0x0000000118dbd004 fp 0x0000700002be5ca8 Unknown symbol
    pc 0x0000000118dbcdaf fp 0x0000700002be5d28 Unknown symbol
    pc 0x0000000118dbcbbb fp 0x0000700002be5da0 Unknown symbol
    pc 0x0000000118dbc42b fp 0x0000700002be5e48 Unknown symbol
    pc 0x0000000118dbbe44 fp 0x0000700002be5e98 Unknown symbol
    pc 0x0000000118dbba31 fp 0x0000700002be5f10 Unknown symbol
    pc 0x0000000118dbaafb fp 0x0000700002be5f90 Unknown symbol
    pc 0x0000000118db9964 fp 0x0000700002be5fd8 Unknown symbol
    pc 0x000000010bbc1504 fp 0x0000700002be6038 Unknown symbol
    pc 0x000000010bbc0fa5 fp 0x0000700002be6070 Unknown symbol
    pc 0x0000000118dc2586 fp 0x0000700002be6108 Unknown symbol
    pc 0x0000000118dbd120 fp 0x0000700002be6158 Unknown symbol
    pc 0x0000000118dbd004 fp 0x0000700002be61b8 Unknown symbol
    pc 0x0000000118dbcdaf fp 0x0000700002be6238 Unknown symbol
    pc 0x0000000118dbcbbb fp 0x0000700002be62b0 Unknown symbol
    pc 0x0000000118dbc42b fp 0x0000700002be6358 Unknown symbol
    pc 0x0000000118dbbe44 fp 0x0000700002be63a8 Unknown symbol
    pc 0x0000000118dbba31 fp 0x0000700002be6420 Unknown symbol
    pc 0x0000000118dbaafb fp 0x0000700002be64a0 Unknown symbol
    pc 0x0000000118db9964 fp 0x0000700002be64e8 Unknown symbol
    pc 0x000000010bbc1504 fp 0x0000700002be6548 Unknown symbol
    pc 0x000000010bbc0fa5 fp 0x0000700002be6580 Unknown symbol
    pc 0x0000000118dc4f87 fp 0x0000700002be6628 Unknown symbol
    pc 0x0000000118dbd120 fp 0x0000700002be6678 Unknown symbol
    pc 0x0000000118dbd004 fp 0x0000700002be66d8 Unknown symbol
    pc 0x0000000118dbcdaf fp 0x0000700002be6758 Unknown symbol
    pc 0x0000000118dbcbbb fp 0x0000700002be67d0 Unknown symbol
    pc 0x0000000118dbc42b fp 0x0000700002be6878 Unknown symbol
    pc 0x0000000118dbbe44 fp 0x0000700002be68c8 Unknown symbol
    pc 0x0000000118dbba31 fp 0x0000700002be6940 Unknown symbol
    pc 0x0000000118dbaafb fp 0x0000700002be69c0 Unknown symbol
    pc 0x0000000118db9964 fp 0x0000700002be6a08 Unknown symbol
    pc 0x0000000118db9528 fp 0x0000700002be6a58 Unknown symbol
    pc 0x000000010bbb1d55 fp 0x0000700002be6ad0 Unknown symbol
    pc 0x000000010bbb1ae3 fp 0x0000700002be6b40 Unknown symbol
    pc 0x000000010bbb1118 fp 0x0000700002be6be0 Unknown symbol
    pc 0x0000000118db92b5 fp 0x0000700002be6c50 Unknown symbol
    pc 0x0000000118db916c fp 0x0000700002be6ca0 Unknown symbol
    pc 0x0000000118db8ea1 fp 0x0000700002be6ce0 Unknown symbol
    pc 0x0000000118db8a6b fp 0x0000700002be6d20 Unknown symbol
    pc 0x0000000118db8967 fp 0x0000700002be6d60 Unknown symbol
    pc 0x0000000109d8145c fp 0x0000700002be6dc8 Unknown symbol
    pc 0x000000010553fc5c fp 0x0000700002be6e70 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)
    pc 0x00000001058516a4 fp 0x0000700002be6f50 Dart_InvokeClosure
    pc 0x0000000105447eb9 fp 0x0000700002be6fd0 tonic::DartMicrotaskQueue::RunMicrotasks()
    pc 0x0000000105091ba4 fp 0x0000700002be7040 fml::MessageLoopImpl::FlushTasks(fml::FlushType)
    pc 0x00000001050968b8 fp 0x0000700002be7060 fml::MessageLoopDarwin::OnTimerFire(__CFRunLoopTimer*, fml::MessageLoopDarwin*)
    pc 0x00007fff23bd4b94 fp 0x0000700002be7070 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
    pc 0x00007fff23bd4882 fp 0x0000700002be8110 __CFRunLoopDoTimer
    pc 0x00007fff23bd3eda fp 0x0000700002be8190 __CFRunLoopDoTimers
    pc 0x00007fff23bcec4e fp 0x0000700002be8e90 __CFRunLoopRun
    pc 0x00007fff23bce066 fp 0x0000700002be8f20 CFRunLoopRunSpecific
    pc 0x00000001050969e3 fp 0x0000700002be8f50 fml::MessageLoopDarwin::Run()
    pc 0x0000000105091ab8 fp 0x0000700002be8f70 fml::MessageLoopImpl::DoRun()
    pc 0x0000000105095eec fp 0x0000700002be8fb0 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*)
    pc 0x00007fff52466e65 fp 0x0000700002be8fd0 _pthread_start
    pc 0x00007fff5246283b fp 0x0000700002be8ff0 thread_start
    -- End of DumpStackTrace
    [exit     : sp(0) fp(0x700002be5398) pc(0)]
    [dart     : sp(0x700002be53a8) fp(0x700002be5420) pc(0x119a9d8d5) dart:isolate_Isolate__spawnFunction@1026248 ]
    [dart     : sp(0x700002be5430) fp(0x700002be5510) pc(0x119a987d8) dart:isolate_Isolate_spawn__async_op ]
    [dart     : sp(0x700002be5520) fp(0x700002be5548) pc(0x10bbaa697) dart:core__Closure@0150898_call ]
    [dart     : sp(0x700002be5558) fp(0x700002be5580) pc(0x10bbb4e76) dart:async__AsyncAwaitCompleter@9048458_start ]
    [dart     : sp(0x700002be5590) fp(0x700002be5648) pc(0x119a97c4d) dart:isolate_Isolate_spawn ]
    [dart     : sp(0x700002be5658) fp(0x700002be56e8) pc(0x11808423b) package:masterbilling/src/data/sync/app_information_sync_service.dart_AppInformationSyncService_syncInformation__async_op ]
    [dart     : sp(0x700002be56f8) fp(0x700002be5738) pc(0x118dbd120) dart:core__Closure@0150898_call ]
    [dart     : sp(0x700002be5748) fp(0x700002be5798) pc(0x118dbd004) dart:async_::__asyncThenWrapperHelper@9048458_<anonymous closure> ]
    [dart     : sp(0x700002be57a8) fp(0x700002be5818) pc(0x118dbcdaf) dart:async_::__rootRunUnary@9048458 ]
    [dart     : sp(0x700002be5828) fp(0x700002be5890) pc(0x118dbcbbb) dart:async_::__rootRunUnary@9048458__rootRunUnary@9048458 ]
    [dart     : sp(0x700002be58a0) fp(0x700002be5938) pc(0x118dbc42b) dart:async__CustomZone@9048458_runUnary ]
    [dart     : sp(0x700002be5948) fp(0x700002be5988) pc(0x118dbbe44) dart:async__FutureListener@9048458_handleValue ]
    [dart     : sp(0x700002be5998) fp(0x700002be5a00) pc(0x118dbba31) dart:async__Future@9048458__propagateToListeners@9048458_handleValueCallback ]
    [dart     : sp(0x700002be5a10) fp(0x700002be5a80) pc(0x118dbaafb) dart:async__Future@9048458__propagateToListeners@9048458 ]
    [dart     : sp(0x700002be5a90) fp(0x700002be5ac8) pc(0x118db9964) dart:async__Future@9048458__completeWithValue@9048458 ]
    [dart     : sp(0x700002be5ad8) fp(0x700002be5b28) pc(0x10bbc1504) dart:async__AsyncAwaitCompleter@9048458_complete ]
    [dart     : sp(0x700002be5b38) fp(0x700002be5b60) pc(0x10bbc0fa5) dart:async_::__completeOnAsyncReturn@9048458 ]
    [dart     : sp(0x700002be5b70) fp(0x700002be5bf8) pc(0x11a8d8ffe) package:masterbilling/src/service/data/database_data.dart_DatabaseData_getDatabasePathAndName__async_op ]
    [dart     : sp(0x700002be5c08) fp(0x700002be5c48) pc(0x118dbd120) dart:core__Closure@0150898_call ]
    [dart     : sp(0x700002be5c58) fp(0x700002be5ca8) pc(0x118dbd004) dart:async_::__asyncThenWrapperHelper@9048458_<anonymous closure> ]
    [dart     : sp(0x700002be5cb8) fp(0x700002be5d28) pc(0x118dbcdaf) dart:async_::__rootRunUnary@9048458 ]
    [dart     : sp(0x700002be5d38) fp(0x700002be5da0) pc(0x118dbcbbb) dart:async_::__rootRunUnary@9048458__rootRunUnary@9048458 ]
    [dart     : sp(0x700002be5db0) fp(0x700002be5e48) pc(0x118dbc42b) dart:async__CustomZone@9048458_runUnary ]
    [dart     : sp(0x700002be5e58) fp(0x700002be5e98) pc(0x118dbbe44) dart:async__FutureListener@9048458_handleValue ]
    [dart     : sp(0x700002be5ea8) fp(0x700002be5f10) pc(0x118dbba31) dart:async__Future@9048458__propagateToListeners@9048458_handleValueCallback ]
    [dart     : sp(0x700002be5f20) fp(0x700002be5f90) pc(0x118dbaafb) dart:async__Future@9048458__propagateToListeners@9048458 ]
    [dart     : sp(0x700002be5fa0) fp(0x700002be5fd8) pc(0x118db9964) dart:async__Future@9048458__completeWithValue@9048458 ]
    [dart     : sp(0x700002be5fe8) fp(0x700002be6038) pc(0x10bbc1504) dart:async__AsyncAwaitCompleter@9048458_complete ]
    [dart     : sp(0x700002be6048) fp(0x700002be6070) pc(0x10bbc0fa5) dart:async_::__completeOnAsyncReturn@9048458 ]
    [dart     : sp(0x700002be6080) fp(0x700002be6108) pc(0x118dc2586) package:path_provider/path_provider.dart_::_getApplicationDocumentsDirectory__async_op ]
    [dart     : sp(0x700002be6118) fp(0x700002be6158) pc(0x118dbd120) dart:core__Closure@0150898_call ]
    [dart     : sp(0x700002be6168) fp(0x700002be61b8) pc(0x118dbd004) dart:async_::__asyncThenWrapperHelper@9048458_<anonymous closure> ]
    [dart     : sp(0x700002be61c8) fp(0x700002be6238) pc(0x118dbcdaf) dart:async_::__rootRunUnary@9048458 ]
    [dart     : sp(0x700002be6248) fp(0x700002be62b0) pc(0x118dbcbbb) dart:async_::__rootRunUnary@9048458__rootRunUnary@9048458 ]
    [dart     : sp(0x700002be62c0) fp(0x700002be6358) pc(0x118dbc42b) dart:async__CustomZone@9048458_runUnary ]
    [dart     : sp(0x700002be6368) fp(0x700002be63a8) pc(0x118dbbe44) dart:async__FutureListener@9048458_handleValue ]
    [dart     : sp(0x700002be63b8) fp(0x700002be6420) pc(0x118dbba31) dart:async__Future@9048458__propagateToListeners@9048458_handleValueCallback ]
    [dart     : sp(0x700002be6430) fp(0x700002be64a0) pc(0x118dbaafb) dart:async__Future@9048458__propagateToListeners@9048458 ]
    [dart     : sp(0x700002be64b0) fp(0x700002be64e8) pc(0x118db9964) dart:async__Future@9048458__completeWithValue@9048458 ]
    [dart     : sp(0x700002be64f8) fp(0x700002be6548) pc(0x10bbc1504) dart:async__AsyncAwaitCompleter@9048458_complete ]
    [dart     : sp(0x700002be6558) fp(0x700002be6580) pc(0x10bbc0fa5) dart:async_::__completeOnAsyncReturn@9048458 ]
    [dart     : sp(0x700002be6590) fp(0x700002be6628) pc(0x118dc4f87) package:flutter/src/services/platform_channel.dart_MethodChannel_invokeMethod__async_op ]
    [dart     : sp(0x700002be6638) fp(0x700002be6678) pc(0x118dbd120) dart:core__Closure@0150898_call ]
    [dart     : sp(0x700002be6688) fp(0x700002be66d8) pc(0x118dbd004) dart:async_::__asyncThenWrapperHelper@9048458_<anonymous closure> ]
    [dart     : sp(0x700002be66e8) fp(0x700002be6758) pc(0x118dbcdaf) dart:async_::__rootRunUnary@9048458 ]
    [dart     : sp(0x700002be6768) fp(0x700002be67d0) pc(0x118dbcbbb) dart:async_::__rootRunUnary@9048458__rootRunUnary@9048458 ]
    [dart     : sp(0x700002be67e0) fp(0x700002be6878) pc(0x118dbc42b) dart:async__CustomZone@9048458_runUnary ]
    [dart     : sp(0x700002be6888) fp(0x700002be68c8) pc(0x118dbbe44) dart:async__FutureListener@9048458_handleValue ]
    [dart     : sp(0x700002be68d8) fp(0x700002be6940) pc(0x118dbba31) dart:async__Future@9048458__propagateToListeners@9048458_handleValueCallback ]
    [dart     : sp(0x700002be6950) fp(0x700002be69c0) pc(0x118dbaafb) dart:async__Future@9048458__propagateToListeners@9048458 ]
    [dart     : sp(0x700002be69d0) fp(0x700002be6a08) pc(0x118db9964) dart:async__Future@9048458__completeWithValue@9048458 ]
    [dart     : sp(0x700002be6a18) fp(0x700002be6a58) pc(0x118db9528) dart:async__Future@9048458__asyncComplete@9048458_<anonymous closure> ]
    [dart     : sp(0x700002be6a68) fp(0x700002be6ad0) pc(0x10bbb1d55) dart:async_::__rootRun@9048458 ]
    [dart     : sp(0x700002be6ae0) fp(0x700002be6b40) pc(0x10bbb1ae3) dart:async_::__rootRun@9048458__rootRun@9048458 ]
    Lost connection to device.
    [dart     : sp(0x700002be6b50) fp(0x700002be6be0) pc(0x10bbb1118) dart:async__CustomZone@9048458_run ]
    [dart     : sp(0x700002be6bf0) fp(0x700002be6c50) pc(0x118db92b5) dart:async__CustomZone@9048458_runGuarded ]
    [dart     : sp(0x700002be6c60) fp(0x700002be6ca0) pc(0x118db916c) dart:async__CustomZone@9048458_bindCallbackGuarded_<anonymous closure> ]
    [dart     : sp(0x700002be6cb0) fp(0x700002be6ce0) pc(0x118db8ea1) dart:async_::__microtaskLoop@9048458 ]
    [dart     : sp(0x700002be6cf0) fp(0x700002be6d20) pc(0x118db8a6b) dart:async_::__startMicrotaskLoop@9048458 ]
    [dart     : sp(0x700002be6d30) fp(0x700002be6d60) pc(0x118db8967) dart:async_::__startMicrotaskLoop@9048458__startMicrotaskLoop@9048458 ]
    [entry    : sp(0x700002be6d70) fp(0x700002be6dc8) pc(0x109d8145c)] 


I use an isolate to fill the database with data on create, and that works just fine?

**Comment by cadaniel** [comment]
I am actually an idiot. 

```var isolate = _createMoorIsolate(dbFile);``` should be ```var isolate = await _createMoorIsolate(dbFile);```

**Comment by DennisMuchiri** [comment]
@cadaniel hahaha
