### ISSUE TITLE
Define Data classes and generate Daos from that

### ISSUE THREAD

**Issue by julien100000** [simolus3/moor#466]
As far as I saw it is currently possible to define tables using the `extends Table` or to write sql directly.
From ORM frameworks in other languages I am used to just define my data classes and annotate them and then the ORM framework creates the tables informtation from this. So the other way around.
Example:

```
@Table(name=player)
class Player {
   @PrimaryKey
   @AutoIncrement
   int id;
   @Constraint(maxChars=20)
   String name;
}
```

And from this I would like to create a playerDao class, which automatically serves methods for queryAll, queryOneById, insert one, update one and delete one and a create table statement like this:

```
// generated file
class PlayerDao() {
   Future<List<Player>> queryAll() {//generated}
   Future<Player> queryById(int id) {//generated}
   Future<Player> insert(Player player) {//generated}
   Future<Player> update(Player player) {//generated}
   Future<Player> delete(Player player) {//generated}
   String getCreateTableSql() {//generated}
}
```

Is something like this maybe planned or it is somehow possible to be able to do this. My problem is that I want to use JsonSerilizable on my data classes. But since I also want to use your moor framework they are generated automatically which makes it impossible for me to annotate them with the json annotation. Or maybe you have an idea.

**Comment by simolus3** [comment]
Thanks for the report! At the moment you'd have to write your own model classes and manually write mappers between them and moor's classes.

There's an open issue for this (#114), but it's a lot of work and I never found enough time to work on it. I'll close this issue as a duplicate.
