### ISSUE TITLE
Best approach to store image to moor

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#472]
Everytime when I retrieve data from server, I will delete all the data in local  before store to database.

```
Future<List<ABC>> getList() async {
    Response response;
    var list = List<ABC>();
    var imageList = List<ImageABC>();
    try {
      response = await _service.getList(authToken);
      var abcResponse = ABCResponse.fromJson(response.body);

      print('=== Delete all before store to database ===');
      await _dao.deleteAllList();
      await _dao.deleteAllImages();

      for (var i in abcResponse.list_data) {     // store data to Table data
        list.add(ABCData(
          .......));

        var response = await http.get(i.image.url);
        String path = base64.encode(response.bodyBytes);    // convert url to base64

        imageList
            .add(ImageData(....));    // store base64 to Image table
     }
      await _dao.batch((b) {
        b.insertAll(_dao.list, list);
        b.insertAll(_dao.image, imageList);
      });

      list = await _dao.getList();
      return list;
    } catch (e) {
               .......
    }
  }

```
The server will return a json, where there is a url in json element. I will convert the image url
 to base64 so I can view it when there has no network connection, but the problem is it takes time to store the image to database.

**Comment by North101** [comment]
I don't recommend storing the image in a database if you're fetching it from a server. I recommend saving the url in the database and using something like https://pub.dev/packages/cached_network_image to cache the image for you for offline use.

**Comment by tony123S** [comment]
@North101 
thanks, but what if I want to display a file image path as below ?
`/data/user/0/com.xxx/cache/image_picker3680473140637486255.jpg`

**Comment by simolus3** [comment]
>  thanks, but what if I want to display a file image path as below,I cannot use this plugin ?

If you store the image url in the database, you could also store `file://` uris in there. I'm not sure if cached_network_image picks that up automatically - if not, you could use something like

```dart
if (uri.scheme == 'file') {
  return FileImage(File(uri.path));
} else {
  return CachedNetworkImage(imageUrl: uri.toString());
}
```

**Comment by tony123S** [comment]
Thank guys, work like a charm.
