### ISSUE TITLE
Strange issue with LIKE query and whitespaces

### ISSUE THREAD

**Issue by yshahak** [simolus3/moor#479]
I have a table defined this way:
```sql
CREATE TABLE ravs(
  id INTEGER NOT NULL PRIMARY KEY,
  originalId INTEGER NOT NULL,
  sourceId INTEGER NOT NULL,
  totalCount INTEGER NOT NULL,
  rav TEXT NOT NULL
);
```
And I have a very simple 'LIKE' query:
```dart
var records = await (select(ravs))..limit(1)
          ..where((t) => t.rav.like("%$search%"))
          ..where((t) => t.sourceId.equals(sourceId)))
          .get();
print(records);
```
The records inside the table are in `Hebrew`. I have no idea if this has something to do with the issue.
When I query with one word only it's work just fine:
```
I/flutter ( 5298): Moor: Sent SELECT * FROM ravs WHERE rav LIKE ? AND sourceId = ? LIMIT 1; with args [%אלי%, 1]
I/flutter ( 5298): [Rav(id: 30711126, originalId: 26, sourceId: 1, totalCount: 84, rav: הרב נתנאל אלישיב)]
```
But when I'm adding whitespace `'  '`  to the query, suddenly there is no results at all even though supposed to be many results:
```
I/flutter ( 5298): Moor: Sent SELECT * FROM ravs WHERE rav LIKE ? AND sourceId = ? LIMIT 1; with args [%אלי ‏%, 1]
I/flutter ( 5298): []
```

Here is also `fiddle` demo to show that the query should yield results: https://www.db-fiddle.com/f/5MrZvzJuARscgHbMb2R7na/2

**Comment by simolus3** [comment]
Thanks, I will look into it. Are you using `moor_ffi`? Running [this gist](https://gist.github.com/simolus3/47cbdf7e46ec8e68293c0a2cdd8533c2) finds the row for me (on x64 Linux ).

**Comment by yshahak** [comment]
Yes, I'm using `moor_ffi`. This is quite strange behaviour indeed.  I am also using `Isolate` for the db.

**Comment by North101** [comment]
I've noticed theres some non-standard whitespace in 
`[%אלי ‏%, 1]`
(try pasting it into https://www.soscisurvey.de/tools/view-chars.php)

You might want to check both your table data and query args to make sure thats not your issue

**Comment by yshahak** [comment]
You are right. This text for do the query is coming from a search bar and it seems that it adds a character: `Unicode Character 'RIGHT-TO-LEFT MARK' (U+200F)`. When I'm copying a query with whitespace and paste it in the search bar it working just fine!
So I need to see how to get rid of this redundant character. Probably I will just remove it from the text before making the query.
