### ISSUE TITLE
Using Transformer on Streams

### ISSUE THREAD

**Issue by pkhivesara** [simolus3/moor#481]
How do we use a ``Transformer`` on a ``Stream``?
Using the following:

```
return  (select(list)..where((t) => t.id.equals(id))).watch().transform(new StreamTransformer.
   fromHandlers(handleData: (value,sink){
     sink.add(value.insert(0, NewDummy()));
   }));
```
It gives an error : ``The expression has a type of void and therefore cannot be used`` for the ``insert``method. Essentially I want to add a new element at ``index`` 0 after doing a fetch request and then send the updated ``Stream``.

Thanks!

**Comment by simolus3** [comment]
> Essentially I want to add a new element at `index` 0 after doing a fetch request and then send the updated `Stream`.

Uh, isn't this just `.watch().map((rows) => [new Dummy(), ...rows])`?

> `The expression has a type of void and therefore cannot be used`

That's because you're adding the return value of `value.insert()` to the sink, but `insert` is a `void` method that doesn't necessarily return a meaningful value. You could use

```dart
(value, sink) {
  value.insert(0, NewDummy());
  sink.add(value);
}
```
or, with some syntactic sugar:
```dart
(value, sink) => sink.add(value..insert(0, NewDummy()))
```

**Comment by pkhivesara** [comment]
I don't have access to the ``map`` method after ``watch`` here? Would that help in adding an element at ``index`` 0?

**Comment by simolus3** [comment]
> I don't have access to the map method after watch here.

`watch()`  always returns a `Stream<List<SomeRow>>`. There is a `map` function on `Stream`, so it should still be available.

> Adds the `insert` twice, since I assume its going through the `Stream` and applying it for each row

The stream won't emit individual rows. It will emit a snapshot of _all_ rows returned by the query whenever they change.

I can't reproduce that transformer adding the insert twice. With

```dart
final stream = select(someTable)
  .watch()
  .transform(StreamTransformer.fromHandlers(handleData: (value, sink) {
      sink.add(value..insert(0, null));
  }));
```

The results are always `[null, regularRow1, regularRow2, ...]`. That's what you want, right?

**Comment by pkhivesara** [comment]
@simolus3 That did work. Was adding an empty row in another place. Sorry about that!
Shall close this out. Thank you very much!
