### ISSUE TITLE
[encrypted_moor] DatabaseException(open_failed on Android on subsequent launches

### ISSUE THREAD

**Issue by seanmc86** [simolus3/moor#484]
I have been using encrypted moor, configured as per the official documentation, working well on iOS but having issues on Android. The first launch on Android prior to a db existing works fine, every subsequent launch on debug produces this error:

[db name replaced with x]
> SqfliteDatabaseException (DatabaseException(open_failed /data/user/0/com.example.mobile_app/databases/x.sqlite))
> 
> Opening db in /data/user/0/com.example.mobile_app/databases/x.sqlite with PRAGMA cipher_migrate

When checking that the db exists it returns false despite creating on prior launch: (with "await file.exists()")

Here is my configuration:

app/build.gradle
```
release {
            minifyEnabled true
            useProguard true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' 
        }
        debug {
            useProguard true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' 
        }
```

app/proguard-rules.pro
`-keep class net.sqlcipher.** { *; }`

DB initialisation:
```
factory LocalDatabase(String passPhrase) {
    _instance ??= LocalDatabase._(passPhrase);
    return _instance;
  }

  LocalDatabase._(String passPhrase)
      : super(EncryptedExecutor(
          path: dbName,
          password: passPhrase,
          singleInstance: true,
        ));
```

(Both EncryptedExecutor and EncryptedExecutor.inDatabaseFolder constructors produce the same error)

If I try recreate the file using the creator, it still produces the same exception. It looks like it cannot get access to an existing file.

**Comment by davidmartos96** [comment]
@seanmc86 Author of the underlying sqlcipher library here. If you provide a reproducible sample project I could take a look at it, with an encryped existing db like yours, but with a dumb table. Do you know the version of SqlCipher used when the db was created? When I first created the library I had an assets database with version SqlCipher 3.x, and I used  PRAGMA cipher_migrate to migrate to SqlCipher 4.x successfully with that library.

**Comment by seanmc86** [comment]
@davidmartos96  Unfortunately I have not been able to reproduce it in a sample app thus far, despite using the same table structure and process of initialising the database class.

We include the packages in pubspec as follows (as per Moor documentation), and have not changed versions since starting to use it:

> moor: ^2.4.2
>   encrypted_moor:
>    git:
>     url: https://github.com/simolus3/moor.git
>     path: extras/encryption
> 
> dependency_overrides:
>   sqflite:
>     git:
>       url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
>       path: sqflite
>       ref: fmdb_override

In my git cache, I see the following versions for encrypted_moor:

> dependencies:
>   moor: ^2.0.0
>   sqflite_sqlcipher: ^1.0.0+3

With changing a few things in the build.gradle of my existing app, I'm getting some different results (not sure if this addition helps at all):

- When leaving minifyEnabled true in my build setting, the app crashes on launch with:

> F/mple.mobile_ap(12304): java_vm_ext.cc:570] JNI DETECTED ERROR IN APPLICATION: JNI FindClass called with pending exception java.lang.NoSuchFieldError: no "J" field "mNativeHandle" in class "Lnet/sqlcipher/database/SQLiteDatabase;" or its superclasses
> F/mple.mobile_ap(12304): java_vm_ext.cc:570]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.Class) (Runtime.java:-2)
> F/mple.mobile_ap(12304): java_vm_ext.cc:570]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:1115)
> F/mple.mobile_ap(12304): java_vm_ext.cc:570]   at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.Class, java.lang.String) (Runtime.java:1069)
> F/mple.mobile_ap(12304): java_vm_ext.cc:570]   at void java.lang.Runtime.loadLibrary0(java.lang.Class, java.lang.String) (Runtime.java:1007)
> F/mple.mobile_ap(12304): java_vm_ext.cc:570]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:1667)
> F/mple.mobile_ap(12304): java_vm_ext.cc:570]   at void net.sqlcipher.database.SQLiteDatabase$a.a(java.lang.String[]) (:227)
> F/mple.mobile_ap(12304): java_vm_ext.cc:570]   at void net.sqlcipher.database.SQLiteDatabase.a(android.content.Context, java.io.File, net.sqlcipher.database.SQLiteDatabase$e) (:244)
> F/mple.mobile_ap(12304): java_vm_ext.cc:570]   at void net.sqlcipher.database.SQLiteDatabase.a(android.content.Context, java.io.File) (:223)
> F/mple.mobile_ap(12304): java_vm_ext.cc:570]   at void net.sqlcipher.database.SQLiteDatabase.a(android.content.Context) (:216)

- When removing minifyEnabled and leaving in proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro', I get the same open exception again.

**Comment by davidmartos96** [comment]
@seanmc86 It's unfortunate that you are not able to reproduce, as that would be the best way to see why it's failing.
I have some questions:

Are you using an encrypted database copied from assets or is the database created empty? If you are copying it, please share the code related to it.

Have you tried renaming the database? If you switched from regular Sqlite to SqlCipher with the same database name, maybe that is doing something strange.

You can also try to inspect the database with Sqlite Browser (it has SqlCipher support) after the db has been created on the device. You can download the db from the tool Device Explorer in Android Studio. The path would be something like `data/data/my.package/myapp/databases`

Another thing you can try is to run `select * from sqlite_master` from Dart to see if the database is created correctly the first time.

**Comment by seanmc86** [comment]
Implementation has also been constant since using these packages (i.e. only creating with the EncryptedExecutor). It is created empty from scratch using the default Moor migration strategy to create the tables specified in tables.moor.

I've used the Device Explorer and downloaded the db from the file system. All the structure and data on initial population looks fine, including the results of `select * from sqlite_master`, **however**, I can open the db without its password, so I assume it has been initially created incorrectly without encryption and then subsequently tried to access with encryption.

So if I then provide an empty password to the EncryptedExecutor constructor, it works on subsequent loads, but populating the password generates the open exception.

**Comment by seanmc86** [comment]
Okay so, it turns out this was a coding-induced problem. Sorry if this has caused you wasted time.

There was an initialisation of the db buried in another class which invariably should not have been triggered, as it was done so without the password, leading to the db being created incorrectly (I discovered this after my previous explanation of it working without a password leading me to investigate this).

**Comment by davidmartos96** [comment]
@seanmc86 Great! I was currently writing a response. I was going to tell you to verify that you were not sending an empty password by mistake. :sweat_smile:
