### ISSUE TITLE
[Q] Select Count(*) with dart_api

### ISSUE THREAD

**Issue by mbabuglia** [simolus3/moor#485]
Docs on Getting Started / Expressions mention Counting but don't provide the examples.

With dart api, how do I execute a simple "SELECT COUNT(*) FROM TodoList" ?

**Comment by simolus3** [comment]
This should work:

```dart
Stream<int> amountOfTodos() {
  final amount = todos.id.count();
  final query = selectOnly(todos)..addColumns([amount]);
  return query.map((row) => row.read(amount)).watch();
}
```

**Comment by mbabuglia** [comment]
Thanks for the quick response! Just for future reference, it should be watchSingle() at the end.
