### ISSUE TITLE
How to close stream queries?

### ISSUE THREAD

**Issue by fedotxxl** [simolus3/moor#486]
Suppose I've got stream query. How to close it when I do not need it anymore?

**Comment by rohansohonee** [comment]
Hi @fedotxxl 

- If you use the stream query with a StreamBuilder you do not have to worry about closing the stream. The StreamBuilder Widget does that for you.
- If you are manually listening to the stream like so:
```dart
yourStreamQuery.listen().......
```
You must cancel the stream after you are done listening to the events:
```dart
yourStreamQuery.cancel()
```

- You can cancel the stream in ``dispose`` method.

> NOTE:- Remember to release the database resources after you are done using it by calling ``close()``.

Hope this is useful.

**Comment by simolus3** [comment]
Yup, it's what @rohansohonee said. If you want to close a stream query, just stop listening to it.

Some more details: When a stream query doesn't have any listeners, moor won't re-run any queries. It will still listen for table updates for a small time (which is very cheap). If the stream doesn't receive another listener during that time, it's completely disposed. Still listening for updates for a small time might sound wasteful, but it's really helpful when listening and cancelling in quick succession as it allows us to determine if we need to re-run a query. This can commonly happen in Flutter, for instance when a `StreamBuilder` is rebuilt a lot.

Either way, you can be sure that all underlying resources and `StreamController`s are disposed after closing the database.

Does that answer your question? If you have any concerns, let me know and I'll re-open this.
