### ISSUE TITLE
watch() won't rebuild StreamBuilder on update

### ISSUE THREAD

**Issue by CelsoBonutti** [simolus3/moor#487]
I have an app that handles form data offline and sends them to a back-end when a connection is available, so I need to show locally if the data is uploaded or not.
For this, I'm using moor_flutter and the watch() function with a StreamBuilder. My watch function is the following:
```dart
  Stream<List<Enterprise>> watchEnterprises(String query) {
    return (select(enterprises)
          ..where((enterprise) => enterprise.name.like("%$query%")))
        .watch();
  }
```
and my StreamBuilder looks like this:

```dart
StreamBuilder<List<Enterprise>>(
  stream: dao.watchEnterprises(_query),
  builder: (context, snapshot) {
    List<Enterprise> enterprises = snapshot.data ?? List<Enterprise>();
    return SliverList(
      delegate: SliverChildBuilderDelegate((context, index) {
        if (index == 0 ||
            enterprises[index].name[0] !=
                enterprises[index - 1].name[0]) {
          return Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              InitialDivider(enterprises[index].name[0]),
              EnterpriseCard(enterprises[index])
            ],
          );
        }
        return EnterpriseCard(enterprises[index]);
      }, childCount: enterprises.length),
    );
  },
)
```

my `Enterprise` class has a localId and an id (returned by the back-end), so I show an indicator based on if id is null or not. For updating this id, I use the following function:

```dart
  Future setExternalId({localId, id}) => (update(enterprises)
        ..where((enterprise) => enterprise.localId.equals(localId)))
      .write(EnterprisesCompanion(id: Value(id)));
```

but the Stream is not auto-refreshing when I do it, and the indicator stays the same. Am I doing something wrong?

**Comment by simolus3** [comment]
Hm no, your code looks like it should work. Can you tell me which version of `moor` version you're using (this is written in the `.packages` file)?
If you enable `logStatements: true` on the `FlutterQueryExecutor` constructor, will moor re-run the select query after the update is called?

**Comment by CelsoBonutti** [comment]
Nevermind, the problem was that I was creating a new instance of AppDatabase by mistake, and the one updating was the new one.
Now it's working fine, but thanks for the help anyway! 😄
