### ISSUE TITLE
sqlparser bug: Error while trying to parse IN clause list literal

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#49]
`SELECT id FROM todos WHERE category IN (1)` parses correctly, but adding more comma separated expressions throws the following error:
```
Error while trying to parse SELECT id FROM todos WHERE category IN (1,2): line 1, column 42: Error: Expected a closing bracket}

1 │ SELECT id FROM todos WHERE category IN (1,2)
  │                                          ^
```

**Comment by simolus3** [comment]
`IN` expressions are not yet supported indeed. Super valid feature request though, will work on them soon.

**Comment by simolus3** [comment]
This works on `develop`.
