### ISSUE TITLE
Writing queries

### ISSUE THREAD

**Issue by resilientcod** [simolus3/moor#491]
In this section, there's a code example where:

`Future<List<Todo>> get allTodoEntries => select(todos).get();`
But just below there:
```
Stream<List<TodoEntry>> watchEntriesInCategory(Category c) {
    return (select(todos)..where((t) => t.category.equals(c.id))).watch();
}
```

In this section I assume that dataclass name is TodoEntry, because in my own code I make like this and with dataclass name **Todo doesn't exists!** I miss something?

**Comment by simolus3** [comment]
Good point, thanks!

The page references the "Getting started" guide, which uses 
```dart
class Todos extends Table {
  //
}
```
Without using a `@DataClassName` annotation, the correct data class that will be generated by moor is `Todo`.

**Comment by simolus3** [comment]
I've updated the documentation to consistently use `Todo` instead of `TodoEntry`.
