### ISSUE TITLE
SqliteException: no such table

### ISSUE THREAD

**Issue by apoleo88** [simolus3/moor#493]
I am stuck with this error:

> [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: SqliteException: no such table: my_entries

I have other tables that work fine, but lately I can't add other tables...

What I tried:
- Clear Flutter and rebuild everything
- Clear the Cache of the App and Uninstall and Reinstall it
- change the name of the DB like 'db2.sqlite'
- Change the Name of the new tables
- Run it on another virtual device

I read a similar issue about backup of the database but it shouldn't be this issue.

Full error:
```
E/flutter ( 6100): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: SqliteException: no such table: my_entries, SQL logic error
E/flutter ( 6100): #0      Database.prepare (package:moor_ffi/src/impl/database.dart:135:7)
E/flutter ( 6100): #1      _VmDelegate._runWithArgs (package:moor_ffi/src/vm_database.dart:63:24)
E/flutter ( 6100): #2      _VmDelegate.runInsert (package:moor_ffi/src/vm_database.dart:76:11)
E/flutter ( 6100): #3      _ExecutorWithQueryDelegate.runInsert.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:69:19)
E/flutter ( 6100): #4      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:32:26)
E/flutter ( 6100): #5      _ExecutorWithQueryDelegate._synchronized (package:moor/src/runtime/executor/helpers/engines.dart:22:26)
E/flutter ( 6100): #6      _ExecutorWithQueryDelegate.runInsert (package:moor/src/runtime/executor/helpers/engines.dart:67:12)
E/flutter ( 6100): #7      LazyDatabase.runInsert (package:moor/src/utils/lazy_database.dart:67:17)
E/flutter ( 6100): #8      InsertStatement.insert.<anonymous closure> (package:moor/src/runtime/query_builder/statements/insert.dart:44:42)
E/flutter ( 6100): #9      QueryExecutor.doWhenOpened.<anonymous closure> (package:moor/src/runtime/executor/executor.dart:29:39)
E/flutter ( 6100): #10     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 6100): #11     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 6100): #12     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter ( 6100): #13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter ( 6100): #14     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter ( 6100): #15     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter ( 6100): #16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
E/flutter ( 6100): #17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
E/flutter ( 6100): #18     BasicLock.synchronized (package:synchronized/src/basic_lock.dart)
E/flutter ( 6100): <asynchronous suspension>
E/flutter ( 6100): #19     DelegatedDatabase.ensureOpen (package:moor/src/runtime/executor/helpers/engines.dart:238:25)
E/flutter ( 6100): #20     LazyDatabase.ensureOpen.<anonymous closure> (package:moor/src/utils/lazy_database.dart:50:49)
E/flutter ( 6100): #21     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 6100): #22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 6100): #23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
E/flutter ( 6100): #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
E/flutter ( 6100): #25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
E/flutter ( 6100): #26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
E/flutter ( 6100): #27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
E/flutter ( 6100): #28     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 6100): #29     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 6100): #30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 6100): #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 6100): #32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 6100): #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 6100): 
Application finished.
Failed to list forwarded ports: ProcessException: The command failed
  Command: ..\sdk\platform-tools\adb.exe -s emulator-5554 forward --list.
```

**Comment by simolus3** [comment]
Thanks for the report. Can you try to enable `logStatements` on the `VmDatabase` and see if the `CREATE TABLE` statement for `my_entries` appears? 
Also, do you have a custom migration strategy or anything else that might cause this?

**Comment by apoleo88** [comment]
I had some migration strategy, I removed them and clean and tried everything again without success.

`I/flutter ( 5937): Moor: Sent CREATE TABLE IF NOT EXISTS my_entries (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, icon VARCHAR NOT NULL, title VARCHAR NOT NULL, notes VARCHAR NULL, title VARCHAR NOT NULL, parent_id INTEGER NOT NULL, duration INTEGER NOT NULL, ended_date INTEGER NULL, started_date INTEGER NOT NULL, inserted_date INTEGER NULL); with args []`

**Comment by apoleo88** [comment]
Something more strange is that sometimes the "no such table error" is about _my_entries_ and sometimes is about another table: _runnings_
Of the my_entries, the CREATE TABLE statement is always sent.
Of the runnings, the CREATE TABLE statement is NEVER sent.

**Comment by simolus3** [comment]
>  Of the runnings, the CREATE TABLE statement is NEVER sent.

That's weird. Is the generated code up-to-date? I don't see how there could be a state where the generated code contains generated table classes but doesn't include the table in `allTables`.

**Comment by apoleo88** [comment]
I don't know, btw if I delete the **.g.dart** file and do **flutter clean** and **package get** andthen rebuild... I get 2 out of 3 times the error:

```
[SEVERE] moor_generator:moor_generator on lib/db/db_classes.dart:
Error running DaoGenerator
InconsistentAnalysisException: Requested result might be inconsistent with previously returned results
```

Then the times it succeeds to generate the file I get those errors of **not such table**, the same operation sometimes triggers _my_entries_ sometime another table, let's called _my_runnings_.

The `CREATE TABLE` of _my_entries_ is always called:
`I/flutter ( 8240): Moor: Sent CREATE TABLE IF NOT EXISTS my_entries (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, icon VARCHAR NOT NULL, title VARCHAR NOT NULL, notes VARCHAR NULL, title VARCHAR NOT NULL, parent_id INTEGER NOT NULL, duration INTEGER NOT NULL, ended_date INTEGER NULL, started_date INTEGER NOT NULL, inserted_date INTEGER NULL); with args []`

Of _my_runnings_, it is not!

If for `allTables` you mean:

```
  Iterable<TableInfo> get allTables => allSchemaEntities.whereType<TableInfo>();
  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
        myEntries,
        runnings
      ];
```
(PS: there are a lot of other tables that I am removing in the list)

**Comment by apoleo88** [comment]
Ok, I found the stupid error while I was editing my last comment:

`I/flutter ( 8240): Moor: Sent CREATE TABLE IF NOT EXISTS my_entries (
.., title VARCHAR NOT NULL**, .., **title VARCHAR NOT NULL**, ..
); with args []`

There were two times the **title** field and in my declaration of the class **MyEntry** it was:

```
@DataClassName("MyEntry")
class MyEntries extends Table {
  ..
  TextColumn get title => text().named('title')();  // It does not make sense I know...
  TextColumn get type => text().named('title')();
  ..
}
```
The _title_ repeated 2 times in the _.named()_ made generate 2 times the column **title VARCHAR** field in the `CREATE TABLE` statement, that I guess will not make create the table without trigger any error.

**Comment by simolus3** [comment]
Did the migration throw any exception after creating the `MyEntries` table? Sqlite definitely does report an error for that `CREATE TABLE` statement. If moor is swallowing the error and attempts to continue then that's probably a bug in moor.

**Comment by apoleo88** [comment]
No error before the **not such table** one

**Comment by mohamadkenway** [comment]
Hi 
I found the solution and error cause,
if u first time with certain table name create a table with incorrect syntax , that table name doesn't responding any more and u should try other names or remove it's file in directory of phone

**Comment by bawantha** [comment]
I cannot catch this exception in my controllers

**Comment by Reitenator** [comment]
> Hi
> I found the solution and error cause,
> if u first time with certain table name create a table with incorrect syntax , that table name doesn't responding any more and u should try other names or remove it's file in directory of phone

This answer deserves more credit. Changing the database-name would also work.

**Comment by harshit82** [comment]
```
E/SQLiteLog(19033): (1) no such table: patients in "SELECT * FROM patients"
D/EGL_emulation(19033): app_time_stats: avg=9044.34ms min=25.98ms max=18062.70ms count=2
E/flutter (19033): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DatabaseException(no such table: patients (code 1 SQLITE_ERROR): , while compiling: SELECT * FROM patients) sql 'SELECT * FROM patients' args []
E/flutter (19033): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11:7)
E/flutter (19033): <asynchronous suspension>
E/flutter (19033): #1      SqfliteDatabaseMixin.txnRawQuery.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:575:30)
E/flutter (19033): <asynchronous suspension>
E/flutter (19033): #2      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
E/flutter (19033): <asynchronous suspension>
E/flutter (19033): #3      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:506:14)
E/flutter (19033): <asynchronous suspension>
E/flutter (19033): #4      PatientTable.getAllPatientData (package:CiARADS/database/patients_table.dart:213:9)
E/flutter (19033): <asynchronous suspension>
E/flutter (19033): #5      ViewModel.getData (package:CiARADS/view_model/view_model.dart:48:11)
E/flutter (19033): <asynchronous suspension>
E/flutter (19033):
```

Databases: https://github.com/harshit82/CiARADS_score/tree/main/lib/database
View Model: https://github.com/harshit82/CiARADS_score/tree/main/lib/view_model

I cannot create the database and the table on first time the app launches.
On some devices, it works while on others it doesn't.

**Comment by simolus3** [comment]
There should be an exception when running the `CREATE TABLE` statement providing more information - perhaps some devices are using an older sqlite3 version that doesn't support your query? You're not using drift, but perhaps [sqflite_common_ffi](https://pub.dev/packages/sqflite_common_ffi) with `slite3_flutter_libs` would be interesting if you need a recent sqlite3 version.

**Comment by harshit82** [comment]
> There should be an exception when running the `CREATE TABLE` statement providing more information - perhaps some devices are using an older sqlite3 version that doesn't support your query? You're not using drift, but perhaps [sqflite_common_ffi](https://pub.dev/packages/sqflite_common_ffi) with `slite3_flutter_libs` would be interesting if you need a recent sqlite3 version.

Thanks for looking into it @simolus3, I have shifted to sqflite_common_ffi but have not tried [sqlite_flutter_libs](https://pub.dev/packages/sqlite3_flutter_libs) will surely look into it and keep you updated.

**Comment by harshit82** [comment]
@simolus3 I am still facing the same issue after changing to sqlite_common_ffi, and changing the database name.

> Hi I found the solution and error cause, if u first time with certain table name create a table with incorrect syntax , that table name doesn't responding any more and u should try other names or remove it's file in directory of phone

**Comment by simolus3** [comment]
I think in your case the problem might be that `PatientsTable.createTable` is using `compute` (since the new isolate will have a new database connection which could cause issues. Does removing the `compute` (at least in `createTable`) help at all? Is that line being executed?

**Comment by harshit82** [comment]
@simolus3 See for yourself, I removed the compute

![image](https://github.com/simolus3/drift/assets/93983185/da8b6bcf-16c6-48ba-9b43-4de9f88e3cc6)
