### ISSUE TITLE
[question] is there a way to create SQLite user-defined functions.

### ISSUE THREAD

**Issue by moovida** [simolus3/moor#495]
I am coming from the java world and with the xerial jdbc drivers I would be able to add user defined functions like this:

```
     Function.create(conn, "myFunc", new Function() {
          protected void xFunc() {
              System.out.println("myFunc called!");
          }
      });
```

Is there any similar way to create user defined functions in the moor project?

**Comment by simolus3** [comment]
`moor_ffi` will experimentally support user-defined functions in the next release. This is supported on `develop` [here](https://github.com/simolus3/moor/blob/develop/moor_ffi/lib/src/impl/database.dart#L175).
The `Database` class is not currently exposed when using the `VmDatabase` wrapper for moor. It sounds like you need this for a library, right? In that case you could probably just use the `Database` [directly](https://pub.dev/packages/moor_ffi#-example-tab-) and ignore most of moor. If you want to use high-level moor apis, I can also expose the underlying `Database` if you need it.

**Comment by moovida** [comment]
Hi @simolus3, thanks a ton for this answer and amazing news. I will not take some time to study moor_ffi a bit and try to implement the functions. I will let you know how it works if you are interested.
A couple of questions:

* I assume you are right in that I should be able to use the Database directly for my purposes.
* I will import the devel branch into my project to use the functions part. Is it enough to also use the moor part from git? 
* is there an example of the function usage? Maybe a testcase?

Also, from what I read in the docs, it should be possible to create testcases that run out of the box on a macos, right?
Thanks a lot!

**Comment by simolus3** [comment]
> I will import the devel branch into my project to use the functions part. Is it enough to also use the moor part from git?

Yes. Since `moor_ffi` has a dependency on `moor` I think you'll need to add both of them as git dependencies, but that's it.

> is there an example of the function usage? Maybe a testcase?

Moor will provide some builtin custom functions, those are defined [here](https://github.com/simolus3/moor/blob/424c2febda6f7787c5bcce4bec7f2fa326f0130b/moor_ffi/lib/src/impl/moor_functions.dart#L96-L120). Note that we need to use top-level functions, `Pointer.fromFunction` doesn't support lambdas.

Tests for those functions are [here](https://github.com/simolus3/moor/blob/develop/moor_ffi/test/database/moor_functions_test.dart).

> Also, from what I read in the docs, it should be possible to create testcases that run out of the box on a macos, right?

Yes - programs using `moor_ffi` should run on macos without further setup.

**Comment by moovida** [comment]
A short update, just as an info: it is enough to add moor_ffi, because it pulls moor automatically as dependency.

```
  moor_ffi:
    git:
      url: https://github.com/moovida/moor.git
      ref: develop
      path: moor_ffi
```

The only glitch here is that if a git repo is used, all the upstream dependencies need to also be from git and can't be hosted. Since moor_ffi on the develop branch is basing on the hosted version of moor, I am getting:

```
Because every version of moor_ffi from git depends on moor from hosted and flutter_geopackage depends on moor from git, moor_ffi from git is forbidden.
So, because flutter_geopackage depends on moor_ffi from git, version solving failed.

pub get failed (1; So, because flutter_geopackage depends on moor_ffi from git, version solving failed.)
exit code 1
```

This is easy solved by forking the repo and changing the dependency to git based inside moor_ffi.

**Comment by moovida** [comment]
Hi @simolus3 , as promised an update about functions. 
Well in my first tests and testcases, they work like a charm! Fantastic! :-)

Currently it is complaining that I am using the function creation outside of your project, but I assume that will be lifted once released:

```
The member 'createFunction' can only be used within 'package:moor_ffi/src/impl/database.dart' or a test.dart(invalid_use_of_visible_for_testing_member)
```

I am trying to setup my travis build to run the testcases and I am wondering what I need to do to have it working the testcases. Do you have any hint on that?

**Comment by moovida** [comment]
Last one, since I asked. Setting up travis with moor_ffi is a piece of cake, since it is possible to set the os:
```
language: dart

os: osx
...
```

Therefore it works out of the box.

Great project. Thanks @simolus3 
This issue can be closed from my side.
