### ISSUE TITLE
[INFO] moor_generator:moor_generator on lib/db/database.dart:line 14, column 31: Expression has an unknown type, the generated code can be inaccurate.

### ISSUE THREAD

**Issue by arnzuk** [simolus3/moor#497]
Hi,

I am using moor files. Could you recommend how to avoid such warnings?

[WARNING] moor_generator:moor_generator on lib/db/database.dart:
There were some errors while running moor_generator on package:test_app/db/database.dart:
[INFO] moor_generator:moor_generator on lib/db/database.dart:line 14, column 31: Expression has an unknown type, the generated code can be inaccurate.
   ╷
14 │ getAssetsDescriptions: SELECT json_extract(json_text, '$.description') as asset_description FROM assets;
   │                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵

Arnoldas

**Comment by arnzuk** [comment]
Forgot to add my table definition:

CREATE TABLE assets (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    uuid TEXT NOT NULL,
    json_text TEXT NOT NULL
);

**Comment by simolus3** [comment]
For custom queries, the generator runs an inference algorithm to determine the the type of each column in a query. In your case, it's impossible to tell the type of `json_extract(json_text, '$.description')` for sure, as the type depends on `json_text`. In that case, the generator will assume it's a string and emit a warning.
You can use `CAST(json_extract(json_text, '$.description') AS TEXT) as asset_description` to make the type clear and suppres the warning.

**Comment by arnzuk** [comment]
Thanks.
