### ISSUE TITLE
[QUESTION] Multiple where clauses

### ISSUE THREAD

**Issue by brenoasm** [simolus3/moor#498]
Sorry to bother, I did not find anywhere showing how to do multiple where clauses in the same query. Currently I have this:

```
(select(settings)
          ..where((s) => someStatement)
          ..where(
            (s) => anotherStatement),
          ))
```

Thanks in advance.

**Comment by simolus3** [comment]
> Sorry to bother

No problem, thanks for the question!

What do you want to achieve with "multiple where clauses"? If you want to filter for rows matching both `someStatement` _and_ `anotherStatement`, calling `where` multiple times is what you need. If you want to filter rows matching `someStatement` _or_ `anotherStatement`, you'd need to write something like `..where(someStatement | anotherStatement)`

**Comment by brenoasm** [comment]
Thanks @simolus3, going to close this one.

**Comment by gsouf** [comment]
@simolus3 I'm curious to know how the "or" works. 

In dart `|` is  the bitwise or operator, right? Maybe there is a feature of dart I ignore, but how are you able to use this operator between 2 statements and get it to generate a sql OR?

Thanks

**Comment by simolus3** [comment]
@gsouf That's a good question! `|` is a [user-overriddable](https://dart.dev/guides/language/language-tour#_operators) operator in Dart, meaning that we can add it as an extension that does an `OR` in sql. If you're interested, the source code of that operator is defined here:

https://github.com/simolus3/moor/blob/8f3a976d6eec3693259e0edf8fe6259cfa066f6e/moor/lib/src/runtime/query_builder/expressions/bools.dart#L15-L17

Obviously I would have preferred to use `||` but we can't override that operator in Dart (which is probably reasonable).

**Comment by gsouf** [comment]
That's amazing, thanks for this clear answer!

**Comment by jakeaaron** [comment]
Hello @simolus3 ! Sorry if this isn't the right place for this question. Is there a way to do a bitwise expression in a where clause?

such as `tbl.syncState.equals(tbl.syncState BITWISE AND syncStateDelete)`

**Comment by gsouf** [comment]
@jakeaaron In the waiting of a better answer..Have you tried using [custom expression](https://drift.simonbinder.eu/docs/getting-started/expressions/#custom-expressions) like this:

```dart
const inactive = CustomExpression<bool, BoolType>("julianday('now') - julianday(last_login) > 60");
select(users)..where((u) => inactive);
```

**Comment by jakeaaron** [comment]
Thanks, @gsouf ! I will try this. I appreciate the advice.

**Comment by simolus3** [comment]
I have also added the `bitwiseOr` and `bitwiseAnd` methods to drift in becae40c6e0cca8ecaec0e4fb0355b448816cebc, which can be used to form these expressions in the next drift version.

**Comment by jakeaaron** [comment]
Great, thank you @simolus3 !
