### ISSUE TITLE
[QUESTION] Compound primary key

### ISSUE THREAD

**Issue by brenoasm** [simolus3/moor#499]
I've been searching on how to do compound primary keys and I was not successfully.. If I try to override the customConstraints getter, I get an error saying that no such column exists (column1):

```
 TextColumn get column1 => text()();

 TextColumn get column2 => text()();

   @override
   List<String> get customConstraints => [
         'PRIMARY KEY (column1, column2)'
       ];
```

Thanks in advance!

**Comment by simolus3** [comment]
> I get an error saying that no such column exists

That doesn't sound right - can you enable `logStatements` on the `VmDatabase` or `FlutterQueryExecutor` and check the `CREATE TABLE` statement moor sends?

You can also override the `primaryKey` getter in your table:

```dart
  TextColumn get column1 => text()();
  TextColumn get column2 => text()();
 
  @override
  Set<Column> get primaryKey => {column1, column2};
```

The `primaryKey` getter is explained in the Dart documentation, but not on the website. I've added a section to the website for this, it will be published with the next moor version.

**Comment by brenoasm** [comment]
The primaryKey override worked, thanks @simolus3.
