### ISSUE TITLE
sqlparser bug: Cannot resolve ColumnBuilder with .named() column

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#50]
In the `moor_flutter/example` project, adding the query `SELECT id FROM categories WHERE desc = ?` fails to parse: 

```
Error while trying to parse SELECT id FROM categories WHERE desc = ?: line 1, column 38: Error: Could not parse this expression}

1 │ SELECT id FROM categories WHERE desc = ?
  │                                      ^
```

Removing `.named('desc')` from the table declaration and updating the query to `SELECT id FROM categories WHERE description = ?` is a workaround.

**Comment by Mike278** [comment]
Hah - this is probably because `desc` is ambiguous with the DESC keyword. Updating to `.named('descr')` parses correctly.

**Comment by simolus3** [comment]
Yup, fails because it's a keyword. You could also escape column name with double quotes though.
