### ISSUE TITLE
rxdart 0.24 switchMap causes Bad state: Stream has already been listened to

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#500]
This test passes on 0.23.1 and fails on 0.24 with 'Bad state: Stream has already been listened to.'
```dart
  test('rxdart 0.24 switchMap', () async {
    {
      final a = BehaviorSubject<String>();
      final b = BehaviorSubject<String>();
      final c = a.switchMap((_) => b);
      a.add('a');
      b.add('b');
      expect(await a.first, 'a');
      expect(await a.first, 'a');
      expect(await b.first, 'b');
      expect(await b.first, 'b');
      expect(await c.first, 'b');
      expect(await c.first, 'b');
    }

    {
      final a = db.customSelectQuery("select 'a' as a").map(($) => $.readString('a')).watchSingle();
      final b = db.customSelectQuery("select 'b' as b").map(($) => $.readString('b')).watchSingle();
      final c = a.switchMap((_) => b);
      expect(await a.first, 'a');
      expect(await a.first, 'a');
      expect(await b.first, 'b');
      expect(await b.first, 'b');
      expect(await c.first, 'b');
      expect(await c.first, 'b'); // in rxdart 0.24: Bad state: Stream has already been listened to.
    }
  });
```

I initially reported this issue in the [rxdart repo](https://github.com/ReactiveX/rxdart/issues/448), but they helped trace it to moor's `StartWithValueTransformer`. The [rxdart changelog](https://github.com/ReactiveX/rxdart/blob/master/CHANGELOG.md#0240-dev1) mentions changes to `startWith ` logic so it seems somewhat related, but unfortunately my stream-fu isn't good enough to figure out the exact cause.

**Comment by simolus3** [comment]
Thanks for the report! This is definitely a moor bug as `db.customSelectQuery(...).watch().isBroadcast` erroneously returns `false`.

The fix is straightforward and on `develop`. There are some breaking changes to the released moor version, but I can cherry-pick this to master and release a fix version if you need it.

**Comment by Mike278** [comment]
Thanks Simon! I didn’t notice a and b weren’t broadcast streams either - interesting how we were able to call .first twice. I guess rxdart is now checking for .isBroadcast?

**Comment by simolus3** [comment]
> interesting how we were able to call .first twice

Yeah, query streams have always been broadcast streams in the sense that you could call `listen` on the same instance multiple times - they just failed to announce that. I also think that rxdart added some check for `isBroadcast`, but I didn't check.
