### ISSUE TITLE
How to use Collate

### ISSUE THREAD

**Issue by cardozaj** [simolus3/moor#503]
The docs don't seem to have covered this yet from what I could find.
I'm wondering how to use Collate.noCase with an Order By on a JoinedSelectStatement.
Here's what I have so far that does not seem to be working:
```dart
@UseDao(tables: [MyTable1, MyTable2])
class MyTable1Dao extends DatabaseAccessor<MyDatabase> with _$MyTable1DaoMixin {
...
  JoinedSelectStatement _tableJoinQuery() {
    return select(myTable1).join([
      leftOuterJoin(
          myTable2, myTable2.name.equalsExp(myTable1.name)),
    ]);
  }

  Future<List<TableJoin>> _toTableJoin(JoinedSelectStatement query) {
    return query.map(fromEntity).get();
  }

  Future<List<TableJoin>> getCritters(SearchInfo searchInfo) {
    final JoinedSelectStatement<Table, DataClass> join = _tableJoinQuery();
    GeneratedTextColumn orderByExpression = myTable1.name.collate(Collate.noCase);
    OrderingTerm orderBy = OrderingTerm(
      expression: orderByExpression,
      mode: OrderingMode.desc,
    );
    join.orderBy([orderBy]);
    return _toTableJoin(join);
  }
...
```

Looking at the Moor SELECT statement in the logs, I'm not seeing `COLLATE NOCASE` appended anywhere. 
Am I doing anything wrong here?

**Comment by simolus3** [comment]
> `GeneratedTextColumn orderByExpression = myTable1.name.collate(Collate.noCase);`

This should throw a type error at runtime - `collate` returns an `Expression<String, StringType>` that is not a subtype of `GeneratedTextColumn`.

I also couldn't reproduce the issue after fixing the type - I'm seeing a `COLLATE NOCASE` in the generated query.

**Comment by cardozaj** [comment]
Thank you. I was able to fix the issue thanks to your reply.
The code I posted wasn't the exact code I was using (as you can probably imagine). In my code I was using a switch statement to get the column to order by, and the issue was that I was calling the cascaded method (`myTable1.name..collate(Collate.noCase)`) instead of calling `.collate` directly.
