### ISSUE TITLE
Syntax error for upsert

### ISSUE THREAD

**Issue by wilkomanger** [simolus3/moor#505]
Hi, thanks again for the upsert feature! I've come across this error when using it:
`SqliteException: near "UPDATE": syntax error, SQL logic error (code 1)`

From this generated line:
`INSERT INTO my_users (sync_token) VALUES (?) ON CONFLICT DO UPDATE SET sync_token = ?`

I'm just guessing here, but might this have something to do with the Parsing Ambiguity [described here](https://www.sqlite.org/lang_UPSERT.html)?

**Comment by simolus3** [comment]
The problem is that for updates we're supposed to list the conflict targets, like this: `ON CONFLICT (id) DO UPDATE SET sync_token = ?`.

This should be fixed now, thanks for the report.

**Comment by wilkomanger** [comment]
Nice, thanks!
