### ISSUE TITLE
Required values not ignored for upserts

### ISSUE THREAD

**Issue by wilkomanger** [simolus3/moor#506]
It seems that non-nullable values must be provided even if you call for example `await into(myUsers).insertOnConflictUpdate(companion);`

Sorry if I'm reporting too quickly (I know it's on `develop`)!

**Comment by simolus3** [comment]
> Sorry if I'm reporting too quickly

No problem, this is valuable feedback!

In this case the behavior seems correct to me though? When you call `insertOnConflictUpdate`, there's a chance it behaves just like a regular insert. So I think it makes sense to enforce the same integrity checks we run for regular inserts as well.

In the more general form:

```dart
into(myUsers).insert(companionA, onConflict: DoUpdate((_) => companionB));
```

Then:
1. `companionA` is validated like an insert, meaning that required non-default values must be present and that present values must be valid
2. `companionB` is validated like an update, meaning that no values are required but present values are still validated.

I forgot to implement check 2, but I don't see a way we can really skip check 1. Am I missing something?

**Comment by wilkomanger** [comment]
Ah, okay that makes sense.

So, in the Matrix SDK I'm developing, I'm using deltas that I want to save, objects that have all properties at `null` except those that have changed. It would be nice to save those directly. I create companions for them now where if a value is a `null` it will be `Value.absent()`.

So in my case `companionA` and `companionB` are the same. When the value is inserted for the first time, it will have the required values, but if it's updated it might not have them (but these are different calls at different times, that's why both companions are the same).

Is it possible to only check the `companionA` if an insert actually takes place? Or does that already happen?

**Comment by simolus3** [comment]
I understand your use case, but I'm not sure if upserts are the right tool for the job then. If you're encoding deltas in companions, then those can only be applied if a value is already in the database, right? So why not use a regular update then? You can use `whereSamePrimaryKey` on `UpdateStatement` to apply deltas to a row that already exists.

> Is it possible to only check the `companionA` if an insert actually takes place

Unfortunately this is not possible as we can't tell if the upsert will behave like an insert or an update without sending another query. We just generate one statement.
You can turn off integrity checks entirely with the `skip_verification_code` [build option](https://moor.simonbinder.eu/docs/advanced-features/builder_options/#available-options). But if you have non-null columns and try to insert null values into them, I expect that sqlite will complain either way.

**Comment by wilkomanger** [comment]
> then those can only be applied if a value is already in the database, right?

Well, the first 'delta' will be a complete version of the data, and will require an insert. It's still a delta, but because it's new it just has all values set.

I indeed at first just checked if there was already a row with the id present, and if so did an update, otherwise an insert. But it was a bit clunky and I suspect less performant? So that's why I thought it was a nice solution to use upserts.

> Unfortunately this is not possible as we can't tell if the upsert will behave like an insert or an update without sending another query. We just generate one statement.

Ah, yeah that makes sense.

> But if you have non-null columns and try to insert null values into them, I expect that sqlite will complain either way.

Yeah, of course. But that shouldn't happen in my case (if I do things right haha). And thanks for the tips!
