### ISSUE TITLE
[moor_ffi]: Persisted data is empty when changing App Theme

### ISSUE THREAD

**Issue by rohansohonee** [simolus3/moor#512]
Hi @simolus3 

- I have encountered an issue when using ``moor_ffi`` for persisting data.
- I use the Bloc architecture to pass the database object down the tree using Provider. 
- The MaterialApp is the child of this MutliProvider.

```dart
main() {
MultiProvider(
      providers: [
        Provider<MyDatabase>(
          create: (_) => MyDatabase(), //this makes the singleton database
        ),
        // more providers here
     ],
    child: MaterialApp( ),
}
```
My app setup is very simple right now. It uses a bottom navigation bar that contains Home and Settings resp.

**Steps to produce the error:**
1. Insert some data into database.
2. Watch or await Future to see the data using StreamBuilder or FutureBuilder. **(data is inserted and shown)**
3. Now change the theme of the app from light to dark in Settings.
4. When returning to Home the data is empty.

The way to resolve this error:
1. Switch the theme back to light.
2. Or restart the app to maintain dark theme.

**Expected Behaviour:**
The data should not be empty when changing the theme of the app.

> I am unable to figure out as to why changing the MaterialApp Theme is causing database to give empty value. I am using the same database object given by the provider.
This issue has me confused.

Please do tell me if I am doing something wrong.

**Comment by kuhnroyal** [comment]
Did the database file get created correctly? Did you follow https://moor.simonbinder.eu/docs/getting-started/starting_with_sql/#generating-matching-code or did you by mistake create a memory version of the database?

**Comment by rohansohonee** [comment]
Hi @kuhnroyal 

>Did the database file get created correctly?

Yes.

I have followed the steps from the getting started guide.
>or did you by mistake create a memory version of the database?

No i used a file as shown in the guide.
```dart
LazyDatabase _openConnection() {
  // the LazyDatabase util lets us find the right location for the file async.
  return LazyDatabase(() async {
    // put the database file, called db.sqlite here, into the documents folder
    // for your app.
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    return VmDatabase(file);
  });
}
```
Data is inserted successfully always.
Reading data works as expected when I don't play around with changing the app theme.

**Comment by kuhnroyal** [comment]
Sounds really weird. How do you change the theme? Can you create a sample project?

**Comment by rohansohonee** [comment]
>How do you change the theme?

I use this package: https://pub.dev/packages/dynamic_theme

**Comment by simolus3** [comment]
That sounds really strange indeed. Can you add a `print` statement to the `MyDatabase` constructor to check it's only being called once?

**Comment by rohansohonee** [comment]
>Can you add a print statement to the MyDatabase constructor to check it's only being called once?

It gets called only once.

I tried to forcefully call ``MyDatabase`` constructor again and ``moor_ffi`` detected and said that:
```
WARNING (moor): It looks like you've created the database classMyDatabase multiple times. When these two databases use the same QueryExecutor, race conditions will ocur and might corrupt the database.
```
So ``moor_ffi`` is working correctly.

I am using this approach for creating the database, but using MultiProvider and ``dynamic_theme`` package:
```dart
void main() {
  runApp(
    Provider<MyDatabase>(
      builder: (context) => MyDatabase(),
      child: MyApp(),
      dispose: (context, db) => db.close(),
   ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return new DynamicTheme(
      defaultBrightness: Brightness.light,
      data: (brightness) => new ThemeData(
        primarySwatch: Colors.indigo,
        brightness: brightness,
      ),
      themedWidgetBuilder: (context, theme) {
        return new MaterialApp(
          title: 'Flutter Demo',
          theme: theme,
          home: new MyHomePage(title: 'Flutter Demo Home Page'),
        );
      }
    );
  }
}
```

**Comment by rohansohonee** [comment]
If I perform a hot reload the data is shown.

**Comment by kuhnroyal** [comment]
This sounds more like a provider problem. Try to put the database instance in a global variable.

**Comment by rohansohonee** [comment]
Yields the same outcome.
Provider does not seem to be the issue.

I will try and investigate this issue further and link a sample soon.

**Comment by rohansohonee** [comment]
After a few hours of debugging I found the bug. It was in my code (a really stupid error from my side).
I am really sorry for troubling you all.
Closing this issue.

**Comment by kuhnroyal** [comment]
Please enlighten us :)

**Comment by stilyng94** [comment]
@rohansohonee please share the solution with us
