### ISSUE TITLE
Unexpected exception when running with isolate in release mode

### ISSUE THREAD

**Issue by johrpan** [simolus3/moor#514]
My app works fine in debug mode. However, when running in release mode, I get the following exception when trying to insert something into the database:

```
E/flutter (17950): [ERROR:flutter/runtime/dart_isolate.cc(864)] Unhandled exception:
E/flutter (17950): Assertion failed: "Unknown _StatementMethod, this can't happen."
E/flutter (17950): #0      _MoorServer._runQuery (package:moor/src/runtime/isolate/server.dart:112)
E/flutter (17950): <asynchronous suspension>
E/flutter (17950): #1      IsolateCommunication.setRequestHandler.<anonymous closure>.<anonymous closure> (package:moor/src/runtime/isolate/communication.dart:154)
E/flutter (17950): <asynchronous suspension>
```
This is not much, but I don't really know, what other information could be useful here. I would be happy to help looking into it.

**Comment by simolus3** [comment]
Hm, there's a switch statement before that assertion covering all values, so I'm going to assume `method` was somehow `null`:

https://github.com/simolus3/moor/blob/6f87b5a5458ae9f855be2f52eba75c4df54f86c6/moor/lib/src/runtime/isolate/server.dart#L101-L110

By a quick look however, I don't really see how that value could ever be null.

If it only happens on release mode, investigating this will likely be some tedious `print`-based debugging. If you want to help, you can try to fork moor and make the thrown `AssertionError` include the `method` parameter. It would be interesting to see what value it works out to.

I've seen some issues with enums and sets when used over isolates, so this might be a Dart or Flutter bug.

**Comment by johrpan** [comment]
I included some additional information in the Exception and got the following values:

```
Unknown _StatementMethod, this can't happen.
method: _StatementMethod.custom
sql: CREATE TABLE IF NOT EXISTS persons (id INTEGER NOT NULL PRIMARY KEY, first_name VARCHAR NOT NULL, last_name VARCHAR NOT NULL);
args: []
```
Obviously, this looks like an impossible situation. I even verified (or falsified) that `method == _StatmentMethod.custom` is indeed `false`, while they seem to have the same value, well, at least the same string representation.

**Comment by johrpan** [comment]
If I understand [this comment](https://github.com/dart-lang/sdk/issues/35626#issuecomment-453304689) on dart-lang/sdk#35626 right, its impossible to send enums between isolates. I mean, if their hashCode is different, they are not the same in comparison any more, right? I would suggest to send the enum as its value and reconstruct it on the other side. Or am I misinterpreting something?

**Comment by simolus3** [comment]
Looks like it, yes. I didn't know about that limitation before, but moor will serialize enums as ints in the next version.

**Comment by mraleph** [comment]
@johrpan which devices were you testing on? Enum values should pass through isolate ports just fine and be canonicalised on the receiving end. We are starting to see similar reports from other users - and I am starting to wonder if this is an ARM CPU bug - because otherwise it is hard to explain the difference in behaviour 

See https://github.com/dart-lang/sdk/issues/41888

**Comment by johrpan** [comment]
@mraleph Unfortunately I only tested this on one device, namely a Samsung Galaxy S5 mini (it's powered by a Samsung Exynos 3470). In the newest Moor version the issue was fixed by serializing enums as ints, so it works for me since then. However, I have two newer devices available and if it would help, I could downgrade Moor and test it there too.
