### ISSUE TITLE
Generated database from .moor files brings error in @required annotation (@required generated by Moor.....) 

### ISSUE THREAD

**Issue by Kobreizhyashi** [simolus3/moor#516]
Hi, I’m using Moor but I have an issue after the database generation. In fact, I wasn't sure If it was an issue or just a problem from my side but the database.g.dart contains errors on ONE class only (the others have the same annotations but no errors shown).
The generating DB contains this annotation:
@required this.id
And the error message: “annotation must be either a const variable reference or const constructor invocation”

Have you ever faced any issue like this ?

**Comment by simolus3** [comment]
I've never seen that, no. Since this only happens for one class and `@required` apparently works in other places, I'd say that this is a bug in Dart's analyzer. Can you try to restart your IDE or type around in the generated file to reset the analyzer cache?

**Comment by Kobreizhyashi** [comment]
I've checked everything and I can't find anything. In some places on the generated code @required is known properly as meta.dart part and in only one object, it doesn't work.

**Comment by Kobreizhyashi** [comment]
In order to precise my message, this has been generated thanks to moor from sql generation, the SQL string : 

`import 'fieldsets.moor';
import 'libraries.moor';

CREATE TABLE Fields (
 id INT NOT NULL PRIMARY KEY,
 type TEXT NOT NULL,
 name TEXT,
 min INT,
 max INT,
 required TEXT,
 defaultValue TEXT,
 libraryId TEXT,
 formLink TEXT,
 isAllWords BOOLEAN,
 wordsId TEXT,
 fields TEXT,
 preFillLinks TEXT,
 hasAclInheritance INT,
 visibility TEXT,
 coordinates TEXT,
 color TEXT,
 tabId INT NOT NULL,
 fieldsetId INT NOT NULL,
 uiIndex INT NOT NULL,
 numberPastille TEXT,
 workflowAccess TEXT,
 workflowAppLaunch TEXT,
 AppLaunch TEXT,
 access TEXT,
 auditFormId INT,
 auditParam TEXT,
 auditParentId INT,
 wordConditionReference TEXT,
 restraintFromLibraries TEXT,
 wordsIdAlwaysDisplayed TEXT,
 hasUniqueInput BOOLEAN,
 hasHideSelect BOOLEAN,
 chronology TEXT,
 tooltip TEXT,
 anonymous TEXT,
 digitsAfterDecimalPoint BOOLEAN,
 nameLinks TEXT,
 saveIfHidden BOOLEAN,
 keepLink BOOLEAN,
 FOREIGN KEY(fieldsetId) REFERENCES Fieldsets(id) ON UPDATE CASCADE ON DELETE CASCADE ,
 FOREIGN KEY(libraryId) REFERENCES Libraries(id) ON UPDATE CASCADE ON DELETE SET NULL);`

**Comment by nateshmbhat** [comment]
i'm also facing similar issue : 

### Here's my Table : 

```
@DataClassName('RecentSearch')
class RecentSearches extends Table {

  IntColumn get id => integer().autoIncrement()();

  IntColumn get category_id => integer()();

  BlobColumn get category_data => blob()();

  IntColumn get timestamp => integer()();

  TextColumn get key => text()();
}

```


But the generated `RecentSearch` object contains @required annotation for all parameters including the `id` parameter which is supposed to be an auto increment column.

This is a serious blocker for using this library :/ 

```
class RecentSearch extends DataClass implements Insertable<RecentSearch> {
  final int id;
  final int category_id;
  final Uint8List category_data;
  final int timestamp;
  final String key;
  RecentSearch(
      {@required this.id,
      @required this.category_id,
      @required this.category_data,
      @required this.timestamp,
      @required this.key});
....

}
```

**Comment by kuhnroyal** [comment]
@Kobreizhyashi Your class has a field called `required` which causes this problem.
@nateshmbhat This is a different problem that I am also facing for auto-increment and default value columns and should probably be crated as separate issue.

**Comment by nateshmbhat** [comment]
Ok
