### ISSUE TITLE
sqlparser bug: Incorrect readsFrom when column with same name exists in other table

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#52]
In the `moor_flutter/example` project both the `categories` and `todos` tables have a column named `id`, so adding the query `SELECT * FROM categories WHERE id = :id` generates: 

```
Stream<List<Category>> watchEx1(int id) {
    return customSelectStream('SELECT * FROM categories WHERE id = :id',
        variables: [
          Variable.withInt(id),
        ],
        readsFrom: {
          categories,
          todos
        }).map((rows) => rows.map(_rowToCategory).toList());
  }
```

Updating the column to a unique name like `category_id` will correctly generate `readsFrom: {categories}`

**Comment by simolus3** [comment]
Thanks for the report. It's fixed on the `develop` branch now. I'll release a new version after fixing some other bugs as well.
