### ISSUE TITLE
Custom class names for generated result sets

### ISSUE THREAD

**Issue by simolus3** [simolus3/moor#520]
It would be great if we could name the generated class somehow.

```sql
queryMyList AS FooBar:
SELECT foo.**, bar.** FROM foos AS foo JOIN bars AS bar ON foo.id = bar.id;
```

_Originally posted by @kuhnroyal in https://github.com/simolus3/moor/issues/288#issuecomment-619218565_

**Comment by North101** [comment]
This would be especially great if 2 queries could return the same class. It would be an error if both queries had `as FooBar` and didn't have the same signature.

**Comment by simolus3** [comment]
Just saw that this is a duplicate of #438.
