### ISSUE TITLE
Testing - Tip to improve documentation for Windows

### ISSUE THREAD

**Issue by scostagabriel** [simolus3/moor#525]
I'm following the guide on https://moor.simonbinder.eu/docs/testing/ and it's great. The tests run normally when I run them manually but when I run with "flutter test" there are errors as shown bellow. 

`Invalid argument(s): Failed to load dynamic library (126)`
`dart:ffi                                                       new DynamicLibrary.open`
`[...]`

The solution for Windows is downloading the sqlite3.dll as explained on the documentation, but this file must be on the test folder, as well as in the application one. So I'm opening this issue just to adjust the documentation on that. Although this is a little fix, it could be of some help for Windows users that are doing unit testing with Moor. 

Thank you for this great library!

**Comment by simolus3** [comment]
Does it also work if you add `sqlite3.dll` to a directoy that is in the `PATH` variable? That sounds like the easiest approach to explain in the documentation.

**Comment by scostagabriel** [comment]
Yes, I removed from the test folder and put on a directory that is in the PATH and it worked.

**Comment by simolus3** [comment]
Great, thanks for trying it out. I've updated the documentation on this, it will go live with the next moor version.
