### ISSUE TITLE
[Feature Request]: If possible, add support for FlatBuffers in moor

### ISSUE THREAD

**Issue by rohansohonee** [simolus3/moor#526]
@simolus3 
> Why FlatBuffers? And how I learnt about this:

I saw this video https://youtu.be/IwxIIUypnTE on serialization performance.
https://github.com/google/flatbuffers

If you can implement this for moor it would be great.

**Comment by simolus3** [comment]
Do you want moor to use this to serialize data in its internal isolate communication? I'm not sure how exactly it would be a useful addition to this library. If you want to store data serialized with FlatBuffers in a database, you can always use a type converter to `Uint8List`.

**Comment by rohansohonee** [comment]
Currently I have a ``List<String>`` that I want to store in database row.
I don't want to serialize in Json & then store in database.
How must I store ``List<String>`` in database row using type converter?

**Comment by simolus3** [comment]
You can write something like the following:

```dart
class ListOfStringConverter extends TypeConverter<List<String>, Uint8List> {
  const ListOfStringConverter();

  @override
  List<String> mapToDart(Uint8List fromDb) {
    // use flatbuffers to read the byte array
  }

  @override
  Uint8List mapToSql(List<String> value) {
    // serialize using flatbuffers
  }
}
```

To use the converter, see the [documentation here](https://moor.simonbinder.eu/docs/advanced-features/type_converters/). The column type would be `blob`.
