### ISSUE TITLE
Error: The argument type 'XXX' can't be assigned to the parameter type 'Insertable<XXX>'.

### ISSUE THREAD

**Issue by MohiuddinM** [simolus3/moor#53]
This error occurs in a simple insert statement. Was working fine until yesterday.

PS: There is again a breaking change without increment major version.

**Comment by simolus3** [comment]
Can you confirm that you're on version 1.5 of `moor_generator`? It should work again after re-running the build runner.

**Comment by MohiuddinM** [comment]
It's solved. Our build pipeline is configured to automatically upgrade all packages, but the moor generator was hard coded at 1.4.0
