### ISSUE TITLE
how to parse TypedResult (joined) using isolate

### ISSUE THREAD

**Issue by wonpyohong** [simolus3/moor#531]
hi, thanks for great package.

despite of async, i have a jank on parsing joined result.
how to parse TypedResult (joined) using isolate?

I declared below code as top-level(global) function.

```
List<Todo> parseTypedResultListForIsolate(MapEntry<MyDatabase, List<TypedResult>> message) {
```

and in my dao method,

```
Future<List<Todo>> getMonthGridTodo(String startDate, String endDate) {
  ...
  var typedResultList = await joinedQuery.get();
  return await compute(parseTypedResultListForIsolate, MapEntry(db, typedResultList));
}
```

and i got error.
Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a closure - Function '_handleMessage@388331746':.)

if i edit function's parameter type to MapEntry<int, List<TypedResult>>,
then this error disappear but surely I cannot use 
```
row.readTable(db.todoTable);
```
in top level function.

actually this can be question about basic isolate. 
however, i wonder if it can be solved using MoorIsolate or other solution.

**Comment by simolus3** [comment]
You cannot send a moor database instance over isolates directly. 

You could run both the query _and_ the `parseTypedResultListForIsolate` function on a background isolate and send the parsed results back to the main isolate. Using a `MoorIsolate` for that should work. I can help you write that if you need an example.

**Comment by wonpyohong** [comment]
oh thanks. example may save my several days!!

By the way, I didn't tell that I already am using isolate on query with this doc. (https://moor.simonbinder.eu/docs/advanced-features/isolates/)
Doc was helpful and reduces many jank on db file IO (querying)
Only parsing jank remains now.


This is my code now.

```
List<Todo> parseTypedResultListForIsolate(MapEntry<BodyCalDatabase, List<TypedResult>> message) {
  final db = message.key;
  final rows = message.value;

  final List<Todo> todoPool = [];
  final Map<String, Todo> todoUuidMap = {};
  for (TypedResult row in rows) {
    final exerciseTodoData = row.readTable(db.exerciseTodo);

    Todo todo;
    if (todoUuidMap.containsKey(exerciseTodoData.todoUuid)) {
      todo = todoUuidMap[exerciseTodoData.todoUuid];
    } else {
      final spec = db.specDao.makeSpec(db, row);
      todo = Todo(spec, exerciseTodoData);
      todoUuidMap[exerciseTodoData.todoUuid] = todo;
      todoPool.add(todo);
    }

    final ExerciseTodoSetData todoSetData = row.readTable(db.exerciseTodoSet);
    if (todoSetData != null) {
      todo.todoSetDataList.add(ExerciseTodoSetDataExt(
        todoSetUuid: todoSetData.todoSetUuid,
        setNum: todoSetData.setNum,
        exerciseTodoTodoUuid: todoSetData.exerciseTodoTodoUuid,
        attrValueMap: todoSetData.attrValueMap,
        lastCheck: todoSetData.lastCheck,
        isCompleted: todoSetData.isCompleted,
      ));
    }
  }

  return todoPool;
}

class Todo {
  Spec spec = Spec.createDefault();
  ExerciseTodoData todoData = ExerciseTodoDataExt.createDefault();
  List<ExerciseTodoSetDataExt> todoSetDataList = [];

  Todo(this.spec, this.todoData);
}
```

**Comment by simolus3** [comment]
Since you're already using `MoorIsolate`s, running the query and the mapping in `compute` should be straightforward.

We won't be calling `parseTypedResultListForIsolate` across isolates anymore, so it can take its parameters directly:
```diff
-List<Todo> parseTypedResultListForIsolate(MapEntry<BodyCalDatabase, List<TypedResult>> message) {
-  final db = message.key;
-  final rows = message.value;
+List<Todo> parseTypedResultList(BodyCalDatabase db, List<TypedResult> rows) {
```

Next, you need a function that connects to an existing `MoorIsolate`, runs the query and parses the results:
```dart
class _GetMonthGridTodoParams {
  final MoorIsolate moorIsolate;
  final String startDate;
  final String endDate;

  _GetMonthGridTodoParams(this.moorIsolate, this.startDate, this.endDate);
}

Future<List<Todo>> _getMonthGridTodoBackground(_GetMonthGridTodoParams params) async {
    final db = BodyCalDatabase.connect(await params.moorIsolate.connect());
    print('getMonthGridTodo, $startDate, $endDate');
    final condition = CustomExpression<bool, BoolType>('exercise_todo.date>=\'${startDate}\' AND exercise_todo.date<=\'${endDate}\'');
    final query = select(db.exerciseTodo).join(todoJoin)
    ..where(condition);
//    debugPrint(query.constructQuery().sql, wrapWidth: 1024);

    var typedResultList = await query.get();
    return parseTypedResultList(db, typedResultList);
  }
```

Finally, you can call that function from `compute`:

```dart
Future<List<Todo>> getMonthGridTodo(MoorIsolate isolate, String startDate, String endDate) async {
  final params = _GetMonthGridTodoParams(isolate, startDate, endDate);
  return await compute(_getMonthGridTodoBackground, params);
}
```

It's surprising to see jank from parsing database results though. If you're dealing with many rows, it might make sense to introduce a `LIMIT` clause and only load some rows at the time. This works especially when using something like a lazy loading `ListView` if that's applicable for your situation.

**Comment by wonpyohong** [comment]
wow. it works with never jank.

I am developing exercise calendar app. 
A month is one page in PageView.
Someone workout more than 1000 sets in a month.
I need preload 3 pages for better user experience.

Actually, even though sets are represented as summary on calendar, all data should be loaded because it is so hard that I can't calculate it only using query (6 tables join)

LIMIT should be useful on ListView scrolling. I will keep in mind.
thanks so much!!
