### ISSUE TITLE
Primary key not set correctly

### ISSUE THREAD

**Issue by Dev-Owl** [simolus3/moor#532]
Hi,

not sure if I did something wrong but while I was testing my code I used an update replace method. The method ended with an exception complaining about a missing primary key. Please see below an example of my models starting with my data contract (shared by all tables).

```dart
class BaseModel extends Table {
  TextColumn get id => text().clientDefault(() => Uuid().v4())();
  DateTimeColumn get lastChange => dateTime().withDefault(currentDateAndTime).named('lastChange')();
  TextColumn get lastChangeBy => text().named('lastChangeBy').withDefault(Constant("not set"))();
  BoolColumn get isDeleted => boolean().named('isDeleted').withDefault(Constant(false))();

  @override
  Set<Column> get primaryKey => {id};

}
```

Below is another layer that is shared by a subset of the data:
```dart
class DataContractProject extends BaseModel {

 TextColumn get projectId => text().named('projectId')();
}
```
As you can see the DataContractProject uses the BaseModel class. Last one would be any entity in the sytem like this example below extending the DataContractProject:
```dart
class Task extends DataContractProject{

  TextColumn get name => text()();
  TextColumn get description => text().nullable()();
}
```
If the table is created like this no primary key is set, if I **add the override again** to the Task class it is set correct in the DB. I expected it to work without this (the other columns from the super classes are created correct).

Can somebody point me to the right direction here?

**Comment by simolus3** [comment]
I think this might work in moor 3.0 - can you try upgrading? Older versions didn't respect parent classes to lookup the `primaryKey` getter, but the latest moor version should do that.

**Comment by Dev-Owl** [comment]
Yes, you are right with the latest version it works. I missed the update (but looks like it's just from today).
Thanks a lot for your help.
