### ISSUE TITLE
extras/encryption branch with compiler errors after latest updates

### ISSUE THREAD

**Issue by seanmc86** [simolus3/moor#538]
Since recent updates the extras/encryption branch is now producing the below compiler errors. It is not possible to update the moor package to ^3 because encrypted_moor depends on moor ^2.0.0. To eliminate the issues, I must stick with major versions of moor + moor_generator below 3, and use an earlier commit from extras/encryption, such as 6424bd209cb2f12c34287c7ddf6671553eac843f.

My working pubspec:

```
dependencies:
  moor: ^2.4.2
    encrypted_moor:
     git:
      url: https://github.com/simolus3/moor.git
      path: extras/encryption
      ref: 6424bd209cb2f12c34287c7ddf6671553eac843f

dev_dependencies:
  moor_generator: ^2.4.0
```

Removing the ref gives these compiler errors:

> 
> Compiler message:
> ../../../SDK/flutter/.pub-cache/git/moor-3e70060ef156ae8f3dcf75710e7bf51fc457f6ae/extras/encryption/lib/encrypted_moor.dart:50:21: Error: Type 'QueryExecutorUser' not found.
>   Future<void> open(QueryExecutorUser user) async {
>                     ^^^^^^^^^^^^^^^^^
> ../../../SDK/flutter/.pub-cache/git/moor-3e70060ef156ae8f3dcf75710e7bf51fc457f6ae/extras/encryption/lib/encrypted_moor.dart:118:27: Error: Type 'BatchedStatements' not found.
>   Future<void> runBatched(BatchedStatements statements) async {
>                           ^^^^^^^^^^^^^^^^^
> ../../../SDK/flutter/.pub-cache/git/moor-3e70060ef156ae8f3dcf75710e7bf51fc457f6ae/extras/encryption/lib/encrypted_moor.dart:50:16: Error: The method '_SqfliteDelegate.open' has more required arguments than those of overridden method 'DatabaseDelegate.open'.
>   Future<void> open(QueryExecutorUser user) async {
>                ^
> ../../../SDK/flutter/.pub-cache/hosted/pub.dartlang.org/moor-2.4.2/lib/src/runtime/executor/helpers/delegates.dart:53:16: Context: This is the overridden method ('open').
>   Future<void> open([GeneratedDatabase db]);
>                ^
> 
> ../../../SDK/flutter/.pub-cache/git/moor-3e70060ef156ae8f3dcf75710e7bf51fc457f6ae/extras/encryption/lib/encrypted_moor.dart:50:21: Error: 'QueryExecutorUser' isn't a type.
>   Future<void> open(QueryExecutorUser user) async {
>                     ^^^^^^^^^^^^^^^^^
> ../../../SDK/flutter/.pub-cache/git/moor-3e70060ef156ae8f3dcf75710e7bf51fc457f6ae/extras/encryption/lib/encrypted_moor.dart:118:27: Error: 'BatchedStatements' isn't a type.
>   Future<void> runBatched(BatchedStatements statements) async {
>                           ^^^^^^^^^^^^^^^^^
> Unhandled exception:
> Crash when compiling null,
> at character offset null:
> unreachable

**Comment by davidmartos96** [comment]
@simolus3 If you are releasing a fix for this, you could also update `sqflite_sqlcipher` to `1.0.0+6` which has the sqlcipher macos implementation. (I forgot to include it in the first release of the package)

**Comment by simolus3** [comment]
It should work with 348fb655cefb1ee777c76935cdb0c873886c393e
