### ISSUE TITLE
Syntax error on update

### ISSUE THREAD

**Issue by PoloLacoste** [simolus3/moor#539]
Hi !

I got a syntax error when updating an entity, `update(learningUnits).replace(unit);`.

Here is the table LearningUnits:

```dart
@DataClassName("LearningUnit")
class LearningUnits extends Table
{
	TextColumn get id => text()();
	TextColumn get user => text()();

	TextColumn get name => text()();

	BoolColumn get save => boolean().withDefault(const Constant(false))();
	BoolColumn get create => boolean().withDefault(const Constant(false))();
	BoolColumn get delete => boolean().withDefault(const Constant(false))();

	@override
	Set<Column> get primaryKey => {id, user};
}
```

Here is the exception :

`SqfliteDatabaseException (DatabaseException(near "create": syntax error (code 1 SQLITE_ERROR): , while compiling: UPDATE learning_units SET name = ?, save = ?, create = ?, delete = ? WHERE id = ? AND user = ?;) sql 'UPDATE learning_units SET name = ?, save = ?, create = ?, delete = ? WHERE id = ? AND user = ?;' args [toto, 0, 0, 1, 2c922f5271b959100171bc5085050052, test@test.com]})`

Am I doing something wrong ?
Thanks in advance !

**Comment by simolus3** [comment]
Thanks for the report! I've uploaded moor version 3.0.2 which fixes this problem.
