### ISSUE TITLE
Row values

### ISSUE THREAD

**Issue by szotp** [simolus3/moor#540]
Not sure if this is supported or not:
```sql
SELECT * FROM contacts
WHERE (lastname,firstname) > (?1,?2)
ORDER BY lastname, firstname
LIMIT 7;
```

**Comment by szotp** [comment]
Basically, I would like to take the OrderingTerms from orderBy, and construct where clause with them, using values from already existing object to select objects after that existing object.

**Comment by simolus3** [comment]
> values from already existing object to select objects after that existing object

The `(lastname,firstname) > (?1,?2)` syntax wouldn't work in sqlite either. But I think

```sql
WHERE lastname > ?1 AND firstname > ?2
```

Should do it?

> I would like to take the OrderingTerms from orderBy, and construct where clause with them

Do you need the ordering terms to be flexible, e.g. set at runtime? If not the query should work. If you need that I can help you write it.

**Comment by szotp** [comment]
Sorry, I forgot to add url, it's from official sqlite page: https://www.sqlite.org/rowvalue.html#scrolling_window_queries

`WHERE lastname > ?1 AND firstname > ?2` does not seem correct to me. If I had such sorted list:
A A
A Z
Z A
Z Z

I would like to get items after (A Z), but `firstname > Z` would filter out everyone, I think.

So I ended up writing a little utility for this, because I will need multiple such requests for pagination (related to #412):
```dart
import 'package:moor/moor.dart';

class OrderByWhere<T extends Table> extends Expression<bool, BoolType> {
  @override
  void writeInto(GenerationContext context) {
    void writeList(List<Component> components) {
      context.buffer.write('(');

      bool addComma = false;
      for (final e in components) {
        if (addComma) {
          context.buffer.write(',');
        }
        e.writeInto(context);
        addComma = true;
      }
      context.buffer.write(')');
    }

    writeList(whereLeft);
    context.buffer.write(mode == OrderingMode.desc ? '<' : '>');
    writeList(whereRight);
  }

  OrderingMode mode = OrderingMode.asc;

  List<Component> whereLeft = [];
  List<Component> whereRight = [];
  List<OrderingTerm> terms = [];

  void add<X>(GeneratedColumn<X, SqlType> column, X value) {
    terms.add(OrderingTerm(expression: column, mode: mode));

    if (value != null) {
      whereLeft.add(column);

      whereRight.add(Constant(value));
    }
  }
}

extension OrderByWhereExtension<T extends Table, D extends DataClass> on SimpleSelectStatement<T, D> {
  /// Sorts and filters at the same time. Useful for efficient pagination, where we want to fetch items after certain item.
  /// Example usage:
  /// ```dart
  /// query.orderByWhere((x, b) {
  ///   b.add(x.firstName, anchor?.firstName);
  ///   b.add(x.lastName, anchor?.lastName)
  /// });
  /// ```
  void orderByWhere(void Function(T, OrderByWhere<T>) func) {
    final builder = OrderByWhere<T>();
    func(table as T, builder);

    orderBy(builder.terms.map((x) => (_) => x).toList());

    if (builder.whereLeft.isNotEmpty) {
      where((x) => builder);
    }
  }
}
```

**Comment by simolus3** [comment]
> Sorry, I forgot to add url, this syntax from official sqlite page: https://www.sqlite.org/rowvalue.html#scrolling_window_queries

Oh wow, I didn't know about that. Moor should definitely support that in the generator for custom queries.

Your `OrderByWhere` looks like a great way to solve this from Dart though :+1: If you need to use it in custom queries, you can use Dart templates:

```sql
SELECT * FROM contacts
WHERE $condition
ORDER BY $order
LIMIT 7;
```

Moor will generate a method taking a `(Expression<bool> condition, List<OrderingTerm> order)` as parameters. You could call that method with `OrderByWhere` and matching ordering terms.

**Comment by szotp** [comment]
I will check the custom templates solution, thanks.

Btw, I just found another cool trick with row values: https://stackoverflow.com/a/30732523

**Comment by simolus3** [comment]
Row values will be supported in the next update of `sqlparser`.
