### ISSUE TITLE
Insert: No named parameter with the name 'orReplace'

### ISSUE THREAD

**Issue by apoleo88** [simolus3/moor#541]
Did something happen to **orReplace**?

`Future insertTask(EdibleEdible task) => into(tasks).insert(task, orReplace:true);`

Now it generates this error:
`Error: No named parameter with the name 'orReplace'.`

**Comment by kuhnroyal** [comment]
This was already deprecated before, you should turn on warnings in your IDE if you didn't see this.
You can replace it with `mode: InsertMode.replace` or  `mode: InsertMode.insertOrReplace` depending on your needs.

**Comment by simolus3** [comment]
It's also mentioned in the [changelog](https://pub.dev/packages/moor#-changelog-tab-). The `orReplace` parameter was a deprecated alias for `mode: InsertMode.replace`. Since `InsertMode` has more options, I've removed `orReplace` entirely in the last breaking release.

**Comment by apoleo88** [comment]
ok, thanks! Because I saw it in the documentation of Insert:
https://moor.simonbinder.eu/docs/examples/relationships/

**Comment by simolus3** [comment]
Oops. I've updated the docs, thanks for pointing it out.
