### ISSUE TITLE
Adding the annotation "@JsonSerializable" to a DataClass

### ISSUE THREAD

**Issue by PoloLacoste** [simolus3/moor#543]
Hi,

Would it be possible to add the annotation `@JsonSerializable` to a DataClass ?

I use the library Chopper (or Retrofit) to make requests to my api. When I get the response back, I would like to let the JsonConverter build in Chopper (or Retrofit) create an object from json.

Thanks !

**Comment by kuhnroyal** [comment]
The entities have a `fromJson` and `toJson` factory/method. You can use those to create the entity from most REST client payloads and also serialize it back.

json_serializable also only generates these methods. You can use `user_name VARCHAR NOT NULL JSON KEY userName` to customize the field names for your json.

**Comment by wonpyohong** [comment]
i had the similar but little bit different issue.

my problem was that retrofit cannot make json string if object which have enum field.
In dart, enum can be json string using @JsonValue usually.

```
@JsonSerializable
class SampleClass {
  MyEnum myEnum;
}

enum MyEnum {
  @JsonValue('ENUM_VALUE1') ENUM_VALUE1,
  ..
}
```

then generated class have generatedMap. This map is used by making json string.
```
  _$MyEnumEnumMap = {
    MyEnum.ENUM_VALUE1: 'ENUM_VALUE1',
    ..
  }
```

but I could not add @JsonSerializable to SampleData generated by moor like SampleClass

so, my workaround is declaring another class extending SampleData and add @JsonSerializable.

```
@JsonSerializable
class SampleDataExt extends SampleData {
  final String fieldOfSampleData1,
  final MyEnum fieldOfSampleData2,
  ..
  
  SampleDataExt(this.fieldOfSampleData1, this.fieldOfSampleData1, ..);

  ..

  factory SampleDataExt.fromJson(Map<String, dynamic> json) => _$SampleDataExtFromJson(json);

  Map<String, dynamic> toJson({ValueSerializer serializer}) => _$SampleDataExtToJson(this);
}
```
