### ISSUE TITLE
Document that .delete returns number of deleted rows

### ISSUE THREAD

**Issue by fgblomqvist** [simolus3/moor#544]
Was a bit unclear I think what the Future<int> was when calling .delete(object).

On a side note:
Are you planning on generating external docs for the public API? The existing docs are great, but obviously different (more guide-based). I think it would be neat to have auto-generated docs for all the methods that can be used. Right now the only way to see what a specific method does and which methods exist is to utilize the autocomplete/inspect functionality in the IDE, which is okay but not always ideal.

Great work on this library so far :)

**Comment by simolus3** [comment]
I've added a comment to `.delete` and `.go` to explain that they return how many rows where deleted.

> Are you planning on generating external docs for the public API?

You can browse the dartdoc of moor [here](https://pub.dev/documentation/moor/latest/). I've thought about making those available under moor.simonbinder.eu as well, but I'm not sure if Dart can be run in netlify builds (it probably can't). I'll add a link to the website for now.
