### ISSUE TITLE
Make Companion equatable

### ISSUE THREAD

**Issue by friebetill** [simolus3/moor#545]
Is it possible that the Companions become [equatable](https://medium.com/@ayushpguptaapg/demystifying-and-hashcode-in-dart-2f328d1ab1bc) (`c1 == c2`)?

I would need the feature to compare Companions during a unit test.

**Comment by simolus3** [comment]
Done on `develop`, this will ship with the next moor version.

**Comment by friebetill** [comment]
Wow very fast, thank you very much Simon!
