### ISSUE TITLE
Consider including sqlite3 in the build and use DynamicLibrary.executable()

### ISSUE THREAD

**Issue by lvsecoto** [simolus3/moor#547]
I run moor on ios. `moor_ffi` use system sqlite library and it's version is below 3.30, and it cause the issue [#529](https://github.com/simolus3/moor/issues/529). I want to compile sqlite3.c by myself to use the latest version sqlite. Can somebody tell me what to do?

Here is the code in `moor_ffi`:
```
  if (Platform.isMacOS || Platform.isIOS) {
    // todo: Consider including sqlite3 in the build and use DynamicLibrary.
    // executable()
    return DynamicLibrary.open('/usr/lib/libsqlite3.dylib');
  }
```

**Comment by simolus3** [comment]
Unfortunately I don't have a Mac to try this out at the moment.

I would try to add [this pod](https://cocoapods.org/pods/sqlite3) to your project. For full compatibility with the way `moor_ffi` builds on Android, you can also add the relevant subspecs:
- `pod 'sqlite3/fts5'`
- `pod 'sqlite3/json1'`
- `pod 'sqlite3/perf-threadsafe'`

You can then instruct moor to use the sqlite version you ship with your binary:

```dart
import 'package:moor_ffi/open_helper.dart';

// Call this before you use moor, e.g. in main()
void setupMoorFfi() {
  open.overrideFor(OperatingSystem.iOS, () => DynamicLibrary.executable());
}
```

**Comment by lvsecoto** [comment]
It's work for me, thanks~

**Comment by simolus3** [comment]
That's great to hear! I'll keep this open to add this to moor or publicly explain this in the docs

**Comment by simolus3** [comment]
We will do this with the upcoming `moor_ffi` version 0.8.0 or the new `package:moor/ffi.dart` setup.
