### ISSUE TITLE
Column omitted during update

### ISSUE THREAD

**Issue by DennisMuchiri** [simolus3/moor#554]
I have a table that stores data and posts to an api. On response I update the received value to the corresponding db row.
Table

```dart
class Comments extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get onlineId => integer().nullable()();
  TextColumn get onlineIdTxt => text().nullable()();
  TextColumn get comment => text().nullable()();
  IntColumn get task =>
      integer().nullable().customConstraint('NULL REFERENCES tasks(id)')();
  IntColumn get subtask =>
      integer().nullable().customConstraint('NULL REFERENCES subtasks(id)')();
  IntColumn get posted_by => integer()
      .nullable()
      .customConstraint('NULL REFERENCES onlineusers(id)')();
  DateTimeColumn get created_at => dateTime().nullable()();
```

The issue is that one column the onlineId  is set to null during update whereas there is data in the oncoming json. Response is successful and has the id 25 ...but this is not set immediately to the table record until i reopen the page where i have stream listener watching for values 

```
I/flutter (25728): post_put_Comment:responseSuccessfull
I/flutter (25728): {id: 25, comment: my reassuring text, task: {id: 11, name: Upload budget}, subtask: {id: 1, name: dig holes}, posted_by: {id: 5, name: Elvis Amuni}, created_at: 2020-05-11T01:58:32.029391+03:00}
I/flutter (25728): post_put_Comment:commentRespJModel onlineid==25
I/flutter (25728): Moor: Sent SELECT * FROM tasks WHERE online_id = ?; with args [11]
I/flutter (25728): Moor: Sent SELECT * FROM subtasks WHERE online_id = ?; with args [1]
I/flutter (25728): Moor: Sent SELECT * FROM onlineusers WHERE online_id = ?; with args [5]
I/flutter (25728): syncComment:commentRespJModel.id==
I/flutter (25728): 25
I/flutter (25728): Moor: Sent UPDATE comments SET comment = ?, task = ?, subtask = ?, posted_by = ?, created_at = ? WHERE id = ?; with args [my reassuring text, 6, 2, 9, 1589151511, 19]
```

Streamlistener watch query

```dart
  Stream<List<CommentJoinClass>> getAllCommentsByCommentJoinClass() {
    String TAG = 'getAllCommentsByCommentJoinClass:';
    var query = (select(comments)
          ..orderBy([
            (t) =>
                OrderingTerm(expression: t.created_at, mode: OrderingMode.desc)
          ]))
        .join([
      leftOuterJoin(tasks, tasks.id.equalsExp(comments.task)),
      leftOuterJoin(subtasks, subtasks.id.equalsExp(comments.subtask)),
      leftOuterJoin(onlineusers, onlineusers.id.equalsExp(comments.posted_by)),
    ]);
    return query.watch().map((rows) => rows.map(
          (row) {
            return CommentJoinClass(
              comment: row.readTable(comments),
              task: row.readTable(tasks),
              subtask: row.readTable(subtasks),
              posted_by: row.readTable(onlineusers),
            );
          },
        ).toList());
  }
```

**Comment by DennisMuchiri** [comment]
Update  the column is not updated even after removing the streambuilder

**Comment by simolus3** [comment]
Thanks for the report. Can you show me the code that runs the `update`?

**Comment by DennisMuchiri** [comment]
The update code. I am using a companion  and the logged data exists:

erpcommentsCompanion.copyWith(
    comment: Value(commentRespJModel.comment),
    task: ((task != null ? Value(task.id) : Value.absent())),
    subtask: ((subtask != null ? Value(subtask.id) : Value.absent())),
    posted_by: ((onlineuserPostedby != null
        ? Value(onlineuserPostedby.id)
        : Value.absent())),
    created_at: Value(commentRespJModel.created_at),
    onlineId: Value(commentRespJModel.id),
  );

**Comment by simolus3** [comment]
Thanks. That code looks alright to me, but I can't see how moor would suddenly ignore some columns in updates.

If you call `toColumns(false)` on the `erpcommentsCompanion.copyWith` (or what you use for updates), does that map contain an entry for `online_id`?

**Comment by DennisMuchiri** [comment]
yes its from this json {id: 25, comment: my reassuring text, task: {id: 11, name: Upload budget}, subtask: {id: 1, name: dig holes}, posted_by: {id: 5, name: Elvis Amuni}, created_at: 2020-05-11T01:58:32.029391+03:00}

so am trying to set that id to that variable online_id ....the record was already existing and was created usin a companion

**Comment by simolus3** [comment]
I still don't see where the column would be dropped. After you do this:

```dart
erpcommentsCompanion.copyWith(
comment: Value(commentRespJModel.comment),
task: ((task != null ? Value(task.id) : Value.absent())),
subtask: ((subtask != null ? Value(subtask.id) : Value.absent())),
posted_by: ((onlineuserPostedby != null
? Value(onlineuserPostedby.id)
: Value.absent())),
created_at: Value(commentRespJModel.created_at),
onlineId: Value(commentRespJModel.id),
);
```

Does the result have a present `onlineId` value (you can verify this with a debugger)? Note that `copyWith` creates a new companion instead of changing the old one.

**Comment by DennisMuchiri** [comment]
The previous onlineId was not set

**Comment by simolus3** [comment]
It seems like we're talking past each other, so let me try to rephrase: What are you doing with the return value of `erpcommentsCompanion.copyWith`?

To actually apply the update, you'll need to do something like

```dart
final newCompanion = erpcommentsCompanion.copyWith(
  // ...
)

await update(comments).replace(newCompanion);
```

If you show me your full update method (or at least the part after `copyWith`) it might be easier for me to find the issue here.

**Comment by DennisMuchiri** [comment]
this is how am updating;
bool isUpdated =
      await erpcommentDao.updateErpcommentsCompanionRtn(erpcommentsCompanion);

updateErpcommentsCompanionRtn;

Future<bool> updateErpcommentsCompanionRtn(
          ErpcommentsCompanion commentsCompanion) =>
      update(erpcomments).replace(commentsCompanion);

**Comment by DennisMuchiri** [comment]
@simolus3 here

**Comment by Mike278** [comment]
```
I/flutter (25728): syncComment:commentRespJModel.id==
I/flutter (25728): 25
I/flutter (25728): Moor: Sent UPDATE comments SET comment = ?, task = ?, subtask = ?, posted_by = ?, created_at = ? WHERE id = ?; with args [my reassuring text, 6, 2, 9, 1589151511, 19]
```
You're logging the id as `25`, but the update statement uses `WHERE id = 19`. 

Check out the documentation for `replace` [here](https://pub.dev/documentation/moor/latest/moor/UpdateStatement/replace.html)

> This implicitly applies a where clause to rows with the same primary key as entity, so that only the row representing outdated data will be replaced.

You set `onlineId: Value(commentRespJModel.id)`, but onlineId isn't the primary key of the comments table. 

I'd suggest writing an explicit update statement with an appropriate WHERE clause for the row you want to update.

**Comment by DennisMuchiri** [comment]
@Mike278 
I/flutter (25728): syncComment:commentRespJModel.id==
I/flutter (25728): 25
this is the incoming response from the server

**Comment by Mike278** [comment]
Hmm I see, `online_id=?` is missing from the update statement.

**Comment by DennisMuchiri** [comment]
exactly

**Comment by Mike278** [comment]
What Simon is saying is likely the case - you aren’t assigning the return value of copyWith to anything. The code you posted doesn’t show that.

**Comment by DennisMuchiri** [comment]
so it has to be assigned to another variable?

**Comment by DennisMuchiri** [comment]
closing the issue

**Comment by Mike278** [comment]
copyWith creates a new companion instead of changing the old one

**Comment by DennisMuchiri** [comment]
okay I understand...thank you...closing the issue
