### ISSUE TITLE
Foreign key mismatch

### ISSUE THREAD

**Issue by PoloLacoste** [simolus3/moor#555]
Hi,

I have some problems getting foreign keys to work.

Here are my tables :

```{dart}
@DataClassName("Unit")
class Units extends Table
{
	TextColumn get id => text().clientDefault(() => uuid.v1())();
	TextColumn get user => text()();

	TextColumn get name => text()();

	@override
	Set<Column> get primaryKey => {id, user};
}
```

```{dart}
@DataClassName("Module")
class Modules extends Table
{
	TextColumn get id => text().clientDefault(() => uuid.v1())();
	TextColumn get unit => text().customConstraint("REFERENCES units(id)")();

	TextColumn get name => text()();

	@override
	Set<Column> get primaryKey => {id, unit};
}
```

And here is my database class.

```{dart}
@UseMoor(
	tables: [
		Units,
		Modules,
	],
	daos: [
		UnitsDao,
		ModulesDao,
	]
)
class Database extends _$Database
{
	Database() : super(FlutterQueryExecutor.inDatabaseFolder(path: 'db.sqlite'));

	@override
	MigrationStrategy get migration => MigrationStrategy(
		beforeOpen: (details) async {
			await customStatement('PRAGMA foreign_keys = ON;');
		}
	);

	@override
 	int get schemaVersion => 1;
}
```

The error I'm getting is `foreign key mismatch - modules referencing units`
Thanks for your help !

**Comment by simolus3** [comment]
This might be because `Modules.unit` won't have a `NOT NULL` constraint (it's overridden with `customConstraint`). Does it work if you use this?

```dart
TextColumn get unit => text().customConstraint("NOT NULL REFERENCES units(id)")();
```

**Comment by PoloLacoste** [comment]
I got the same error message after rebuilding everything.

`E/SQLiteLog(30276): (1) foreign key mismatch - "modules" referencing "units"`

Is there a way to display more logs to investigate ?

**Comment by simolus3** [comment]
You could enable `logStatements: true` on `FlutterQueryExecutor` or `VmDatabase`. This will make moor print the `CREATE TABLE` statements, so that we can see if there's anything wrong with them.

**Comment by PoloLacoste** [comment]
Actually I can only see `SELECT` or `INSERT` statements.

**Comment by simolus3** [comment]
That's weird, those should be logged as well. It might be because you already have a database on your device, so the migrations don't run again. Do the logs appear if you delete the file from the device? If they don't, are you on the latest moor version?

**Comment by Mike278** [comment]
Maybe something to do with `Unit`'s primary key being `(id, user)`, but the foreign key is to `units(id)`? Curious what the `CREATE TABLE` statements are, because this works for me:
```sql
create table units (id text not null, user text not null, primary key (id, user));
create table modules (id text not null, unit references units (id), primary key (id, unit));
pragma foreign_keys = on;
```

**Comment by PoloLacoste** [comment]
> 
> 
> That's weird, those should be logged as well. It might be because you already have a database on your device, so the migrations don't run again. Do the logs appear if you delete the file from the device? If they don't, are you on the latest moor version?

I completely uninstall the application several times but nothing wants to be displayed.
I'm using the latest version of moor (3.0.2) and moor_ffi (0.5.0), with the latest generator (3.0.0)

**Comment by PoloLacoste** [comment]
> 
> 
> Maybe something to do with `Unit`'s primary key being `(id, user)`, but the foreign key is to `units(id)`? Curious what the `CREATE TABLE` statements are, because this works for me:
> 
> ```sql
> create table units (id text not null, user text not null, primary key (id, user));
> create table modules (id text not null, unit references units (id), primary key (id, unit));
> pragma foreign_keys = on;
> ```
> 
> Relevant part of the sqlite docs: https://www.sqlite.org/foreignkeys.html#fk_indexes

Yes, foreign key is on `units(id)`. I would like to know too :)

**Comment by simolus3** [comment]
Moor not printing statements issued during a migration is a bug that I've just fixed. You can wrap your `onCreate` in a `transaction` as a workaround. Or you could try to set a breakpoint on [this line](https://github.com/simolus3/moor/blob/master/moor/lib/src/runtime/query_builder/migration.dart#L104) and see what `context.sql` evaluates to.

**Comment by PoloLacoste** [comment]
I wrapped the `customStatement` in a `transaction` and now I don't have any `foreign key mismatch`.

```
I/flutter (24422): Moor: Sent BEGIN TRANSACTION with args []
I/flutter (24422): Moor: Sent PRAGMA foreign_keys = ON with args []
I/flutter (24422): Moor: Sent COMMIT TRANSACTION with args []
```

But still I can't see moor table creation with SQL.

I recreated the app with juste two tables and two daos and no `CREATE TABLE` statement was displayed.

**Comment by simolus3** [comment]
Doh, sorry. The `transaction` workaround was to show the messages, but IIRC the `foreign_keys` pragma doesn't have an effect inside a transaction.

That said, the same thing happens with raw sql:

```sql
-- partial_fk.sql

CREATE TABLE units (
    id TEXT NOT NULL,
    user TEXT NOT NULL,
    name TEXT NOT NULL,
    PRIMARY KEY (id, user)
);

CREATE TABLE modules (
    id TEXT NOT NULL,
    unit TEXT NOT NULL REFERENCES units (id),
    name TEXT NOT NULL,
    PRIMARY KEY (id, unit)
);

PRAGMA foreign_keys = ON;

INSERT INTO units (id, user, name) VALUES ('id', 'user', 'name');
INSERT INTO modules (id, unit, name) VALUES ('m_id', 'id', 'm_name');
```

If I run `sqlite3 < partial_fk.sql` I also get `Error: near line 18: foreign key mismatch - "modules" referencing "units"`. It works as expected if I change the primary key of `units` to only include `PRIMARY KEY (id)`.

I've re-read the docs on foreign keys in sqlite, and it says that

> Usually, the parent key of a foreign key constraint is the primary key of the parent table. If they are not the primary key, then the parent key columns must be collectively subject to a UNIQUE constraint or have a UNIQUE index

I think that this is what might be failing here? `units (id)` is not the primary key, and doesn't span a uniqueness constraint on its own.

**Comment by PoloLacoste** [comment]
Yep I just found out too that I was using two primary keys...
It's fixing this problem actually.
