### ISSUE TITLE
How to get children using parent in one query

### ISSUE THREAD

**Issue by DennisMuchiri** [simolus3/moor#557]
Hello. I have a question about getting 1:M children together with the parent such that the children will be a list inside the parent. The reason for this is because I have not seen documentation for this anywhere

class ParentWithChildren{.
int id;
List<Children> children;
}

**Comment by simolus3** [comment]
You could take a look at [this example](https://moor.simonbinder.eu/docs/examples/relationships/#selecting-a-cart) if it helps. Essentially, you'll need two selects: One for the parent and one for the children.

For self joins however, I'd just run one query and do the matching in Dart:

```dart
Future<List<ParentWithChildren>> getParentsWithChildren() async {
  final allEntries = await select(table).get(); // where Table is your table
  final parentIdToChildren = <int, List<Entry>>{}; // where Entry is the generated Data Class for your table

  for (final entry in allEntries) {
    parentIdToChildren.putIfAbsent(entry.parent, () => []).add(entry);
  }

  return parentIdToChildren.entries
    .map((entry) => ParentWithChildren(entry.key, entry.values))
    .toList();
}
```

**Comment by DennisMuchiri** [comment]
Thank you, will this work for Stream?

**Comment by simolus3** [comment]
Since it's essentially a `map`, yes:

```dart
Stream<List<ParentWithChildren>> getParentsWithChildren() async {
 return select(table).watch().map((allEntries) {
    // rest of the method
  });
}
```

**Comment by DennisMuchiri** [comment]
Thank you
