### ISSUE TITLE
Mismatch while comparing dates

### ISSUE THREAD

**Issue by DennisMuchiri** [simolus3/moor#558]
I have noticed while querying for records of a particular day the query logged is as follows;

 Moor: Sent SELECT subtaskdays.id AS "subtaskdays.id", subtaskdays.online_id AS "subtaskdays.online_id", subtaskdays.day AS "subtaskdays.day", subtaskdays.distancecovered AS "subtaskdays.distancecovered", subtaskdays.subtask AS "subtaskdays.subtask", subtasks.id AS "subtasks.id", subtasks.online_id AS "subtasks.online_id", subtasks.name AS "subtasks.name", subtasks.kpi AS "subtasks.kpi", subtasks.assign AS "subtasks.assign", subtasks.task AS "subtasks.task", subtasks.status AS "subtasks.status", subtasks.tags AS "subtasks.tags", subtasks.date_started AS "subtasks.date_started", subtasks.end_date AS "subtasks.end_date" FROM subtaskdays LEFT OUTER JOIN subtasks ON subtasks.id = subtaskdays.subtask WHERE (CAST(strftime('%Y', subtaskdays.day, 'unixepoch') AS INTEGER)) = ? AND (CAST(strftime('%m', subtaskdays.day, 'unixepoch') AS INTEGER)) = ? AND (CAST(strftime('%d', subtaskdays.day, 'unixepoch') AS INTEGER)) = ? AND subtasks.id = ? ORDER BY subtaskdays.day DESC; with args [2020, 5, 13, 2]

the unixepoch part is where I have a question on. I have a record in the table with the date am trying to query with but it's not returning any record. Does the unixepoch  convert my date to a universal format yet am querying using my local timezone date. Please provide a clear way of doing this.

**Comment by simolus3** [comment]
Moor stores datetimes as a unix timestamp (in seconds). `CAST(strftime('%Y', subtaskdays.day, 'unixepoch')` is used to load the year from a unix timestamp, but it interprets the timestamp in UTC.

It's true that this can cause timezone issues (#286), but it's massively breaking to change now as all existing users would have to write a custom migration script.
Until I come up with a good solution in moor, you could store dates as utc (you can also write a type converter from `DateTime` to `DateTime` to make this easier).

**Comment by DennisMuchiri** [comment]
what do you mean by converter from DateTime to DateTime

**Comment by simolus3** [comment]
Sorry, nevermind that. I thought about using type converters to store `DateTime`s as utc, but since they're stored as timestamp that doesn't make any difference.
