### ISSUE TITLE
TableInfo.mapFromCompanion() on bool type was broken?

### ISSUE THREAD

**Issue by masahiro-ikemoto** [simolus3/moor#559]
The mapFromCompanion() method failed for tables that has bool fields. The value of result fields are always `true'.

The method create a Map that has raw values from toColumns() result, and execute map() method with it.

The map() invokes Table.fromData() constructor in auto-generated Table code, and the fromData() method converts values with db.typeSystem.forDataType<T>().

Results, bool type is converted by SqlType<bool>.mapFromDatabaseResponse(), but it considers only 0/1 value. So raw true/false value always converts to `true'.

**Comment by simolus3** [comment]
Thanks for the report, and good catch! This will be fixed in moor 3.1, which I'll hopefully release this weekend.
