### ISSUE TITLE
VmDatabase close with an NPE when it's never been open.

### ISSUE THREAD

**Issue by lvsecoto** [simolus3/moor#560]
Look at these code:
```dart
class VmDatabase extends DelegatedDatabase {
  /// others ...
  @override
  Future<void> open(QueryExecutorUser user) async {
    /// [_db] assign value here...
    if (file != null) {
      _db = Database.openFile(file);
    } else {
      _db = Database.memory();
    }
    _db.enableMoorFfiFunctions();
    versionDelegate = _VmVersionDelegate(_db);
    return Future.value();
  }

  Future<void> close() async {
    /// If we have never invoke [open], [_db] is null
    _db.close();
  }
}
```

Try this:
```
/// Cause NPE:
await Database.createForTest().close();
```
> The following NoSuchMethodError was thrown running a test:
> The method 'close' was called on null.
> Receiver: null
> Tried calling: close()
>
> When the exception was thrown, this was the stack:
> #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
> #1      _VmDelegate.close (package:moor_ffi/src/vm_database.dart:105:9)

**Comment by kuhnroyal** [comment]
Maybe there was an error during `open` that got swallowed.

**Comment by simolus3** [comment]
Databases are supposed to handle `close` calls without being opened. I've added support for this in the common `DelegatedDatabase`, which pretty much all implementations inherit from.
