### ISSUE TITLE
SqfliteDatabaseException when calling insertOnConflictUpdate

### ISSUE THREAD

**Issue by RyanVDW** [simolus3/moor#561]
When calling insertOnConflictUpdate i am getting the error below:

Not sure the reason for this error?

` Exception has occurred.
SqfliteDatabaseException (DatabaseException(near "ON": syntax error (code 1 SQLITE_ERROR): , 
while compiling: INSERT INTO categories (id, category, colour) VALUES (?, ?, ?) ON CONFLICT(id) DO UPDATE SET id = ?, 
category = ?, colour = ?) sql 'INSERT INTO categories (id, category, colour) VALUES (?, ?, ?) 
ON CONFLICT(id) DO UPDATE SET id = ?, category = ?, colour = ?' args [1, Shoes, #5b426c, 1, Shoes, #5b426c]})`

This only happens when there is a conflicting row in the database? 

This is the method I am calling:

`  Future insertCategory(Insertable<Category> category) =>  into(categories).insertOnConflictUpdate(category);`

Libraries and versions:

> moor: ^3.0.2
  moor_ffi: ^0.5.0
  moor_flutter: ^3.0.0`

**Comment by kuhnroyal** [comment]
What OS/Version? See https://github.com/simolus3/moor/issues/549#issuecomment-625246229

**Comment by RyanVDW** [comment]
> What OS/Version? See [#549 (comment)](https://github.com/simolus3/moor/issues/549#issuecomment-625246229)

This is running on Android 10. I have not tested on iOS yet?

**Comment by kuhnroyal** [comment]
> moor_flutter: ^3.0.0

You need to get rid of that dependency, see the issue I linked.

**Comment by simolus3** [comment]
Yes, remove the `moor_flutter` dependency and use a `VmDatabase` instead of a `FlutterQueryExecutor`. That one uses the latest sqlite version on Android. Let me know if you run into any issues with that approach, thanks!

**Comment by zakihou** [comment]
iam workin with sqflite: ^2.2.8+4
i have erro in near "ON": syntax error
E/flutter ( 9325): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DatabaseException(near "ON": syntax error (code 1): , while compiling: INSERT OR REPLACE INTO paycode

pleass hellp me!!!!
