### ISSUE TITLE
Batch inserts with .moor files

### ISSUE THREAD

**Issue by ActuarialAnalyst** [simolus3/moor#564]
I would like to use the SQL approach with moor files. I tried to use the batch insert method in my database class but receive the following error. 

The argument type 'String' can't be assigned to the parameter type 'Value<String>'.

Do you have any guidance on how to accomplish this thing. I really don't want to have to convert anything to csv. Is there a clean way to get my JSON into the database?

Here is the repo: https://github.com/ActuarialAnalyst/flashcards

**Comment by kuhnroyal** [comment]
Look at the generated code [here](https://github.com/ActuarialAnalyst/flashcards/blob/master/lib/database/database.g.dart#L90) and you will see that the argument is not a `String` but a `Value<String>`. Any IDE with Dart support would help you there.

**Comment by ActuarialAnalyst** [comment]
I took the code from the documentation on batch inserts and maybe it is worth noting that this code will not run if using sql?

**Comment by kuhnroyal** [comment]
Yes you are right, the example in den documentation is missing the `Value`s

**Comment by simolus3** [comment]
I think the documentation [here](https://moor.simonbinder.eu/docs/getting-started/writing_queries/#inserts) should be fine since it uses the `insert` constructor. `title` and `content` are required for inserts, so they're unboxed and don't need a `Value`. Is there another part of the documentation that's missing `Value`s?

**Comment by kuhnroyal** [comment]
> I think the documentation [here](https://moor.simonbinder.eu/docs/getting-started/writing_queries/#inserts) should be fine since it uses the `insert` constructor. `title` and `content` are required for inserts, so they're unboxed and don't need a `Value`. Is there another part of the documentation that's missing `Value`s?

The `content` property does not exist [here - getting started](https://moor.simonbinder.eu/docs/getting-started/starting_with_sql/) instead there is a `body` and `title`, ` body` seem to be nullable.

**Comment by simolus3** [comment]
Right - in the non-sql [getting started](https://moor.simonbinder.eu/docs/getting-started/) guide the schema is slightly different. The article has a link to the regular guide at the top, so I think it should be fine. I've added a column that requires the `Value` wrapper to the [batch example](https://develop--moor.netlify.app/docs/getting-started/writing_queries/#inserts).
