### ISSUE TITLE
[Request] Option to save dates as string

### ISSUE THREAD

**Issue by JCKodel** [simolus3/moor#570]
Although dates as ints are neat and small, it's hard to read them in development (for debug purposes, for instance, I have a SQLite viewer embedded in my application so I can see and manipulate the contents of my tables during development).

**Comment by fgblomqvist** [comment]
If you save them as strings you lose all the functionality of comparing them in queries, no?
You can achieve what you want using a normal string column combined with a TypeConverter (check the docs on that).

**Comment by JCKodel** [comment]
> If you save them as strings you lose all the functionality of comparing them in queries, no?
> You can achieve what you want using a normal string column combined with a TypeConverter (check the docs on that).

Not really. ISO dates are comparable. "2020-05-14T16:04:00.0-03:00" < "2020-05-14T16:05:00.0-03:00" is true.

**Comment by simolus3** [comment]
Strings have other advantages as well, like #286. I'll close this as duplicate, but I definitely want to look into the possibility as there were numerous timezone-related issues recently.
