### ISSUE TITLE
[Generator] Aliases are not recognized

### ISSUE THREAD

**Issue by JCKodel** [simolus3/moor#572]
This won't work:

```sql
_getCapillaryScheduleStepPhotos:
	SELECT cssp.*
	FROM CapillaryScheduleSteps AS css
	INNER JOIN CapillaryScheduleStepPhotos AS cssp ON cssp."capillaryScheduleStepId" = css."id"
	WHERE css."capillaryScheduleId" = :capillaryScheduleId AND cssp."deleted" = 0
	ORDER BY cssp."created";
```

but this will:
```sql
_getCapillaryScheduleStepPhotos:
	SELECT CapillaryScheduleStepPhotos.*
	FROM CapillaryScheduleSteps
	INNER JOIN CapillaryScheduleStepPhotos ON CapillaryScheduleStepPhotos."capillaryScheduleStepId" = CapillaryScheduleSteps."id"
	WHERE CapillaryScheduleSteps."capillaryScheduleId" = :capillaryScheduleId AND CapillaryScheduleStepPhotos."deleted" = 0
	ORDER BY CapillaryScheduleStepPhotos."created";
```

Kinda verbose =\

**Comment by simolus3** [comment]
Can you clarify what "won't work" means? The sqlparser should be able to pick up table aliases, and we have tests for that. It might be a special scenario that I've missed, can you post an isolated repro (ideally, with table definitions) for me to try out?

**Comment by JCKodel** [comment]
> Can you clarify what "won't work" means? The sqlparser should be able to pick up table aliases, and we have tests for that. It might be a special scenario that I've missed, can you post an isolated repro (ideally, with table definitions) for me to try out?

Tried to repro and now it works (I've updated moor since the last Flutter upgrade, so I guess this is not applicable).

Sorry.
