### ISSUE TITLE
Moor generates a code with a syntax error in the parameter of the RawValuesInsertable constructor in the heir UpdateCompanion

### ISSUE THREAD

**Issue by doomkin** [simolus3/moor#577]
For `tables.moor`
```sql
CREATE TABLE orgs (
  id         INT NOT NULL PRIMARY KEY AUTOINCREMENT,
  code       TEXT,
  name       TEXT
);
```
Moor generates
```dart
class OrgsCompanion extends UpdateCompanion<Org> {
  ...
  static Insertable<Org> custom({
    Expression<int> id,
    Expression<String> code,
    Expression<String> name,
  }) {
    return RawValuesInsertable({
      if (id != null) 'id': id,
      if (code != null) 'code': code,
      if (name != null) 'name': name,
    });
  }
```

**Comment by doomkin** [comment]
This requires the 'control-flow-collections' experiment to be enabled.

**Comment by simolus3** [comment]
Are you using an older Dart version? Moor should have a minimum sdk requirement to cover this.

**Comment by doomkin** [comment]
I use lastest stable **Dart 2.8.2**. Problem solved by enabling experiment `control-flow-collections` into `pubspec.yaml` 
```
analyzer:
  enable-experiment:
    - control-flow-collections
```

**Comment by simolus3** [comment]
`control-flow-collections` is enabled by default since Dart 2.3 or so.

I think you can also raise your minimum Dart SDK version in your pubspec to fix this error:

```yaml
environment:
  sdk: ">=2.8.2 <3.0.0"  
```

**Comment by doomkin** [comment]
I removed
```yaml
analyzer:
  enable-experiment:
    - control-flow-collections
```
and added
```yaml
environment:
  sdk: ">=2.8.2 <3.0.0"  
```
No error either, thank you!

**Comment by simolus3** [comment]
Good to hear. In the next version, moor will detect this automatically and it will recommend the pubspec change.
