### ISSUE TITLE
Maybe a regression in generators inference algorithm

### ISSUE THREAD

**Issue by friebetill** [simolus3/moor#583]
After the upgrade from `2.3.0` to `3.1.0` (moor) and from `0.4.0` to `0.6.0` (moor_ffi) the following problem occurred when generating the files:
```
[WARNING] moor_generator:moor_generator on lib/data/moor_database.dart:
There were some errors while running moor_generator on package:client/data/moor_database.dart:
[INFO] moor_generator:moor_generator on lib/data/moor_database.dart:Lint for getDeckWithCardCount: line 1, column 11: Expression has an unknown type, the generated code can be inaccurate.
  ╷
1 │ SELECT *, (SELECT COUNT(*) FROM cards WHERE deck_id = :id) AS "cardCount" FROM decks d WHERE d.id = :id;
  │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Previously the count expression was correctly interpreted as int.

I have seen [this issue](https://github.com/simolus3/moor/issues/497) and with the fix it works again:
```
SELECT *, CAST((SELECT COUNT(*) FROM cards WHERE deck_id = :id) AS int) AS "cardCount" FROM decks d WHERE d.id = :id;
```
But since the change `CAST(...) AS int` makes the code a bit clumsy, my question is whether it is perhaps an unintended regression in the inference algorithm of the generator.

**Comment by simolus3** [comment]
I'll take a look at it, thanks for the report. Until then, you can use the [`legacy_type_inference`](https://moor.simonbinder.eu/docs/advanced-features/builder_options/) builder option to get the moor 2.x behavior.

**Comment by simolus3** [comment]
This is fixed on `develop` and will be released in the next moor version.
