### ISSUE TITLE
[moor_flutter] Don't update db user_version if the migration fails

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#584]
I noticed that if some migration fails, the database version gets updated anyway.
I have a failing test for it in the integration tests, although I'm not sure what would be the best way to solve it. My guess is that since the `onCreate` and `onUpgrade` callbacks for the sqflite delegate never throw an error, the db remains updated.
This can probably be fixed with a try catch on the user side, but maybe it can be done automatically in moor. 

That schemaVersion is just to force throwing an error inside the migrator.
```dart
test('DB version does not update if the migration fails', () async {
    var database = Database(executor.createConnection());
    await database.executor.ensureOpen(database);
    await database.close();

    bool failed = false;
    try {
      database = Database(
        executor.createConnection(),
        schemaVersion: kDbVersionWithMigrationErrors,
      );
      await database.executor.ensureOpen(database);
    } catch (e) {
      failed = true;
    }
    if (!failed) fail("Should fail migration");

    final dbVersion = await database.getDbVersion();

    expect(dbVersion, 2);

    await database.close();
  });
```

**Comment by simolus3** [comment]
I think the implementations should be consistent here, so it makes sense for the encrypted executor and `moor_flutter` to not apply the version change if the migration failed.

We can probably drop the utility functions from `sqflite` entirely here and just issue the pragma statement manually.

**Comment by davidmartos96** [comment]
> We can probably drop the utility functions from sqflite entirely here and just issue the pragma statement manually.

Yes, that is exactly what I'm doing at the moment with a try catch block in the Migrator onUpgrade.
It works fine.

**Comment by davidmartos96** [comment]
@simolus3 Thanks Simon! 
Isn't the sqflite_sqlcipher implementation missing for this fix? Maybe it could help to add the SqlCipher executor to the integration tests.

**Comment by simolus3** [comment]
>  Isn't the sqlcipher implementation missing for this fix? Maybe it could help to add the SqlCipher executor to the integration tests.

Good idea, thanks. I've applied the changes to the encrypted executor and added it to the integration tests.

**Comment by davidmartos96** [comment]
Great!
