### ISSUE TITLE
How to run a select during a migration inside a transaction

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#585]
If during a migration I need to run a Select query, what I usually do is `executor.runSelect(...)`. But that solution hangs if it's done inside a `transaction`.
Is a valid feature request to add an `issueCustomSelect` in the Migrator? I've just tested it and it works fine for me.

```dart
  Future<List<Map<String, dynamic>>> issueCustomSelect(
    String sql, [
    List<dynamic> args,
  ]) async {
    return _resolveEngineForMigrations().doWhenOpened(
      (executor) => executor.runSelect(sql, args),
    );
  }
```

**Comment by simolus3** [comment]
Selecting inside a transaction in the migration callback works for me:

```dart
test('can select in migration and transaction', () async {
  final db = TodoDb(VmDatabase.memory());
  TodoEntry result;

  db.migration = MigrationStrategy(
    onCreate: (m) async {
      await m.createTable(db.todosTable);
      await db
          .into(db.todosTable)
          .insert(TodosTableCompanion.insert(content: 'content'));

      result =
          await db.transaction(() => db.select(db.todosTable).getSingle());
    },
  );

  await db.customSelect('SELECT 1').get();
  expect(result, TodoEntry(id: 1, content: 'content'));
});
```

Does this only happen on `moor_flutter`?

**Comment by davidmartos96** [comment]
Alright, it looks like the problem was using the executor directly `executor.runSelect(...)` instead of `customSelect(...)`

Thanks Simon!

**Comment by davidmartos96** [comment]
@simolus3 What is the reason behind marking the QueryEngine methods protected?
In my usecase, I have a whole file dedicated to db migrations. I pass the Database instance as argument to a function and I interact with it from there. Using methods such as `db.customSelect(...)` raise the warning. Could I run into errors with this approach? Is there a better alternative?
Ignoring the warning seems to work fine, but I don't know if there are cases where it could fail.

**Comment by simolus3** [comment]
I've removed the annotations in f5f6cbeffec11defa4780c951bda4c73d549170

**Comment by davidmartos96** [comment]
@simolus3 Great, thank you!
