### ISSUE TITLE
Avoid circular reference in hierarchy table

### ISSUE THREAD

**Issue by vandir** [simolus3/moor#586]
Hello,

Does Moor support a table like this in the .moor file?

```
CREATE TABLE Category (
	CategoryId INTEGER NOT NULL,
        ParentId INTEGER, 
	CONSTRAINT Category_PK PRIMARY KEY (CategoryId),
	CONSTRAINT Category_FK_1 FOREIGN KEY (ParentId) REFERENCES Category(CategoryId) ON DELETE CASCADE
);
```

I'm just obtaining the following error and a big headache:

`[WARNING] moor_generator:moor_generator on lib/database/database.dart:
There were some errors while running moor_generator on package:fitness/database/database.dart:
[INFO] moor_generator:moor_generator on lib/database/database.dart:line 11, column 7 of package:fitness/database/database.dart: Found a circular reference in your databa
se. This can cause exceptions at runtime when opening the database. This is the cycle that we found: Category -> Category
`

I need to create a hierarchy of categories, so can't I use this beautiful lib? :cry:

**Comment by simolus3** [comment]
Thanks for the report! This is a bug in the generator, I overlooked that case. It's fixed on `develop` and will ship with the next moor version,
