### ISSUE TITLE
NoSuchMethodError: Class 'GeneratedTextColumn' has no instance method 'like'. Receiver: Instance of 'GeneratedTextColumn'

### ISSUE THREAD

**Issue by wilkomanger** [simolus3/moor#588]
I get this error:

```
NoSuchMethodError: Class 'GeneratedTextColumn' has no instance method 'like'.
E/flutter (30647): Receiver: Instance of 'GeneratedTextColumn'
```
When calling the following code:
```dart
await batch((batch) async {
  for (final roomId in roomIds) {
    batch.deleteWhere(
      roomEvents,
      (tbl) => tbl.id.like('$roomId:%'),
    );
  }
});
```

Any idea why this would happen? Statically everything seems fine (in IntelliJ).

**Comment by simolus3** [comment]
`like` is implemented as an extension on `Expression<String>`, so there's something very wrong if it tries to call an instance method with that name.
Does it work if you add the table to the signature of the lambda? E.g. `(RoomEvents tbl) => ...`. It might be that `tbl` is inferred to be `dynamic`, which would explain why this isn't an analysis error.

**Comment by simolus3** [comment]
Does it work if you add the explicit type? I'll close this since it likely isn't a moor issue. Let me know if you still have this problem, I'll reopen this then.
