### ISSUE TITLE
insertAllOnConflictUpdate Batch with companion

### ISSUE THREAD

**Issue by salim-lachdhaf** [simolus3/moor#590]
i got this error when i use the code bellow 
![Capture2](https://user-images.githubusercontent.com/13780503/82694538-b3c5c700-9c63-11ea-873b-298b8c65a843.PNG)

> Sorry, Instance of  `GeneralStatisticsCompanion ` cannot be used for that because: 
> • nbTicket: This value was required, but isn't present

this is the  `data `value (a `GeneralStatistics):`

![Capture](https://user-images.githubusercontent.com/13780503/82694595-cd670e80-9c63-11ea-87b6-ab5abbd82780.PNG)

**Comment by simolus3** [comment]
It's hard to say what's wrong here without seeing the table definition of `GeneralStatistics`. Does the `companion` have all fields present except for `id` and `ndTicket`?

**Comment by salim-lachdhaf** [comment]
this is the table definition:

```
class GeneralStatistics extends Table {
  IntColumn get id => integer().autoIncrement()();

  IntColumn get nbTicket => integer().named("NB_TICKET")();

  RealColumn get sumTicket => real().named("SUM_TICKET")();

  IntColumn get nbArticle => integer().named("NBREARTICLE")();

  RealColumn get sumDeposit => real().named("SUM_DEPOSIT")();

  RealColumn get sumDiscount => real().named("SUM_DISCOUNT")();

  RealColumn get sumEscompte => real().named("SUM_ESCOMPTE")();
}
```

**Comment by salim-lachdhaf** [comment]
**_Update_** : it's not `toCompanion`,  it's `b.insertAllOnConflictUpdate(generalStatistics, entries);` that throws 

> Sorry, Instance of GeneralStatisticsCompanion cannot be used for that because:
> • nbTicket: This value was required, but isn't present

```
//insert a list of entries
  Future<void> insertEntries(
      List<GeneralStatisticsCompanion> entries) async {
    //insert all new data
    await batch((b) {
      // functions in a batch don't have to be awaited - just
      // await the whole batch afterwards.
      b.insertAllOnConflictUpdate(generalStatistics, entries);
    });
  }
```

**Comment by simolus3** [comment]
Is `GeneralStatistics.nbTicket` marked as nullable in the table definition? If it's not and you're not providing a value for `nbTicket` you'll get that error.

**Comment by salim-lachdhaf** [comment]
Yes , i did not mark the attribute as nullable for this i use companion, is batch compatible with companion ? or i have to use a loop to insert entries as companions instead of `insertAllOnConflictUpdate`

**Comment by simolus3** [comment]
If `nbTicket` is non-nullable in the database, you won't be able to insert a record with that field set to null (or it being absent). Companions can't help you here. Even if moor didn't warn about that, the insert would fail in sqlite.

If you want to allow null values, you need to make that column nullable. Then this code would work as expected.

**Comment by salim-lachdhaf** [comment]
Please tell me so when i should use companion ?

**Comment by simolus3** [comment]
Companions make it explicit if you want to write a null value or if you want to use a default.

For instance, let's say you had a nullable column with a default value. If you set the corresponding field to `null` in the data class, it's not sure if you want to explicitly set the column to null or if you want to apply the default value (e.g. provide no value at all).
With companions, you either use `Value.absent()`, which tells moor that you want to use a default value, or `Value(null)`, which makes it clear that you want to insert null.

For non-nullable columns without a default, both `Value(null)` and `Value.absent()` would be forbidden, which is what you're seeing here.
