### ISSUE TITLE
how to reference composite primary keys

### ISSUE THREAD

**Issue by Ay0ubCheurfi** [simolus3/moor#594]
meaning ,how to use composite foreign keys in moor database

**Comment by simolus3** [comment]
If you're using `moor`-files, you can just use a regular table constraint: 
```sql
CREATE TABLE other (
  a INT,
  b TEXT,
  FOREIGN KEY (a, b) REFERENCES first (d, c)
)
```

When defining the table in Dart, you need to override `customConstraints`:

```dart
class Others {
  IntColumn get a => integer()();
  TextColumn get b => text()();

  @override
  List<String> get customConstraints => ['FOREIGN KEY (a, b) REFERENCES first (d, c)'];
}
```

**Comment by Ay0ubCheurfi** [comment]
@simolus3 thank you so much that works just fine , keep up the nice work man we really appreciate it

**Comment by Ay0ubCheurfi** [comment]
so... is this correct ?! 
@DataClassName('Drug')
class Drugs extends Table {
  TextColumn get name => text().withLength(min: 10, max: 16)();
  TextColumn get labName => text().withLength(min: 4, max: 16)();
  RealColumn get price => real()();
  RealColumn get cInit => real()();
  RealColumn get cMin => real()();
  RealColumn get cMax => real()();
  IntColumn get stability => integer()();
  RealColumn get rest => real().withDefault(Constant(0))();
  BlobColumn get image => blob().nullable()();

  @override
  Set<Column> get primaryKey => {name, labName};
}

@DataClassName('Presentation')
class Presentations extends Table {
  IntColumn get id => integer().autoIncrement()();
  RealColumn get masseField => real()();
  RealColumn get volumeField => real()();
  TextColumn get name => text()();
  TextColumn get labName => text()();

  List<String> get customConstraints =>
      ['FOREIGN KEY (name, lab_name) REFERENCES drugs (name, lab_name)'];
}

**Comment by simolus3** [comment]
Yes, that should work. If you're seeing something unexpected, did you enable `PRAGMA foreign_keys=1;`?

**Comment by Ay0ubCheurfi** [comment]
yes i did , everything seems to work just fine .
thnx a lot
