### ISSUE TITLE
[Moor generator 3.1.0] The getter 'languageVersionMajor' isn't defined for the class 'LibraryElement'

### ISSUE THREAD

**Issue by deep34** [simolus3/moor#595]
I got these errors when trying to run:
flutter packages pub run build_runner build
I am using moor 3.0.0, moor_ffi 0.6.0 and moor generator 3.1.0 

> [INFO] Generating build script...
> 
> [INFO] Generating build script completed, took 389ms
> 
> [INFO] Creating build script snapshot......
> [INFO] Creating build script snapshot... completed, took 7.2s
> 
> [SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
> This is likely caused by a misconfigured builder definition.
> [SEVERE] /C:/flutter/.pub-cache/hosted/pub.dartlang.org/moor_generator-3.1.0/lib/src/backends/build/generators/moor_generator.dart:42:37: Error: The getter 'languageVersionMajor' isn't defined for the class 'LibraryElement'. - 'LibraryElement' is from 'package:analyzer/dart/element/element.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.4/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'languageVersionMajor'.      final major = library.element.languageVersionMajor;                                    ^^^^^^^^^^^^^^^^^^^^/C:/flutter/.pub-cache/hosted/pub.dartlang.org/moor_generator-3.1.0/lib/src/backends/build/generators/moor_generator.dart:43:37: Error: The getter 'languageVersionMinor' isn't defined for the class 'LibraryElement'. - 'LibraryElement' is from 'package:analyzer/dart/element/element.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.4/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or
> defining a getter or field named 'languageVersionMinor'.      final minor = library.element.languageVersionMinor;

**Comment by kuhnroyal** [comment]
This is fixed in develop. You can try running `flutter pub upgrade` to get around this or setting `analyzer: ^0.39.5` as `dev_dependency`.
See https://github.com/simolus3/moor/pull/589

**Comment by simolus3** [comment]
Yes, adding an explicit `analyzer` bound (or mostly just running `flutter packages upgrade`) should fix this.
The next `moor_generator` version will declare the proper dependency (thanks to @kuhnroyal).
