### ISSUE TITLE
[Generator] Select statement LIKE '?%' not generating _method(var argument)

### ISSUE THREAD

**Issue by aleksandrTmk** [simolus3/moor#596]
Hello, loving this lib so far, awesome work!

I'm querying the DB using select statements and using the `generator` doesn't seem to work when you have variable input into the select statement.
- `_selectZipCodesTest` works correctly and generates a function with an argument input
- `_selectZipCodes` does not generate a function with an argument input
```
@UseMoor(tables: [
  Zipcodes,
  States,
  Cities
], queries: {
  '_selectZipCodesTest': 'SELECT * FROM zipcodes WHERE zip = ?',
  '_selectZipCodes': 'SELECT DISTINCT * FROM zipcodes WHERE zip LIKE \'?%\'',
})
```

Generated methods
```
 // Where generator finds "= ?" it generates argument correctly
 Selectable<Zipcode> _selectZipCodesTest(String var1) {
    return customSelect('SELECT * FROM zipcodes WHERE zip = ?',
        variables: [Variable.withString(var1)],
        readsFrom: {zipcodes}).map(_rowToZipcode);
  }

 // Where generator only finds the "?" it does not generate an argument
  Selectable<Zipcode> _selectZipCodes() {
    return customSelect('SELECT DISTINCT * FROM zipcodes WHERE zip LIKE \'?%\'',
        variables: [], readsFrom: {zipcodes}).map(_rowToZipcode);
  }
```

As a workaround, I am hand writing this instead of using generated methods. So this isn't a huge deal but would be a lot cleaner code wise if generator would work.

I would love to help with solving this if you can point me where to get started (been reading the source but I'm not too familiar with it yet).

**Comment by aleksandrTmk** [comment]
Closing as this was `my mistake`.

Correct way to have inputs for select statements
`'_selectZipCodes': 'SELECT DISTINCT * FROM zipcodes WHERE zip LIKE ?',`

Generated method is
```
 Selectable<Zipcode> _selectZipCodes(String var1) {
    return customSelect('SELECT DISTINCT * FROM zipcodes WHERE zip LIKE ?',
        variables: [Variable.withString(var1)],
        readsFrom: {zipcodes}).map(_rowToZipcode);
  }
```

**Comment by simolus3** [comment]
Yup, the question mark doesn't count if it's inside a sql string literal. If you don't want to append the `%` manually when calling the method, you can also use a sql string concatenation: `zip LIKE ? || '%'`
