### ISSUE TITLE
how to watch a table that have a many to many relationship with another table and have a one to many relationship with another one ?

### ISSUE THREAD

**Issue by Ay0ubCheurfi** [simolus3/moor#598]

**Comment by Ay0ubCheurfi** [comment]
drugs table have a many to many relationship with stability table
drugs table have a one to many relationship with presentation

**Comment by simolus3** [comment]
In general, you'll need three queries for this:
1. A query that selects from `drugs` with the appropriate filter
2. Another query that selects from `stability` with the results that were found in 1
3. And finally a query that selects from `presentation` with the results that were found in 1.

I would recommend to use [RxDart](https://pub.dev/packages/rxdart) to do this. In this case, you could use `switchMap` to transform the results from part 1 and then use `combineLatest2` to combine queries 2 and 3.

**Comment by Ay0ubCheurfi** [comment]
i'll try that thnx, but is it the same approach when using moor files?
