### ISSUE TITLE
unable to build when upgrading to latest 3.1 version

### ISSUE THREAD

**Issue by rodriger06** [simolus3/moor#600]
I updated my moor database to 3.1 and try to build it by executing following command due to changes in my database:
flutter packages pub run build_runner build

ERROR MESSAGE I GET

[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/moor_generator-3.1.0/lib/src/backends/build/generators/moor_generator.dart:42:37: Error: The getter 'languageVersi
onMajor' isn't defined for the class 'LibraryElement'. - 'LibraryElement' is from 'package:analyzer/dart/element/element.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlan
g.org/analyzer-0.39.4/lib/dart/element/element.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'languageVersionMajor'.
    final major = library.element.languageVersionMajor;                                    ^^^^^^^^^^^^^^^^^^^^/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/moor_generat
or-3.1.0/lib/src/backends/build/generators/moor_generator.dart:43:37: Error: The getter 'languageVersionMinor' isn't defined for the class 'LibraryElement'. - 'LibraryElement
' is from 'package:analyzer/dart/element/element.dart' ('/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.4/lib/dart/element/element.dart').Try correcting the
 name to the name of an existing getter, or defining a getter or field named 'languageVersionMinor'.      final minor = library.element.languageVersionMinor;
                   ^^^^^^^^^^^^^^^^^^^^
pub finished with exit code 78

please help solve this issue.  I am not able to test my app at all after upgrading my moor version.
thanks in advance

**Comment by simolus3** [comment]
Sorry about this. Can you try to run `flutter packages upgrade` or add an explicit `dev_dependency` on `analyzer: ^0.39.5`? See https://github.com/simolus3/moor/issues/595 for context.
