### ISSUE TITLE
[suggestion] make field nullable as default

### ISSUE THREAD

**Issue by salim-lachdhaf** [simolus3/moor#606]
the current behavior of moor is if the field is not marked `nullable()` in the data base the field will be marked as `NOT NULL`, in my opinion the behavior should be the opposite, so if we declale a field is by default `Nullable`, and if we want make that field as non `nullable()` we add `.NonNullable()` for example, like this we keep the same behavior of sqlite

**Comment by kuhnroyal** [comment]
Nope, sorry.

**Comment by salim-lachdhaf** [comment]
I'm not ok with your points.
- If you remove the old `nullable()` and add new `notNullable() `this change will not make a break change because the user will be aware of that change because the compilator will detect it and it's really not that bad or hard change for user.
- it's not only sqlite behavior , it's the behavior of everthing, the default value always considered as `NULL`, in our case i compared with sqlite or sqflite...
- it would not be a bad table design because users already always used to work like this , with databases or with general variable , always default value is `NULL` if not defined.
- i would not use `.moor` files because i want to have have my own separeted `dataClass`es objets and separated `dao`s because my data base is very large.

**Comment by kuhnroyal** [comment]
I understand where you are coming from but Dart will soon be non-nullable by default so
> always default value is NULL if not defined
will no longer be true. Most modern languages try to be nun-nullable by default, Dart just got this notice a little late.

And like it or not, this is a Dart client for SQlite so it need to play by Dart rules.

And to your last point, I would even more so encourage you to try to use `.moor` files, especially with lots of tables. It will be easier to write migrations since they have to be written in sql anyway. And you get the same data class generated, you can even name it yourself.

**Comment by simolus3** [comment]
Thanks for starting this discussion. However, I agree with Peter here. The only good argument in favor of making columns nullable by default is to match the behavior of sqlite more closely. But:

> If you remove the old nullable() and add new notNullable() this change will not make a break change

It's a breaking change if existing code stops working or changes behavior after a moor update. So yeah,  this is breaking. It's noticeable and easy to fix, but still breaking.

> it's not only sqlite behavior , it's the behavior of everthing, the default value always considered as `NULL`

At least in Dart, this won't be true for much longer :) Going away from a non-nullable by default approach in moor now will likely make the library more painful to use together with NNBD Dart.

> i would not use `.moor` files because i want to have have my own separeted `dataClasses` objets and separated `daos` because my data base is very large.

You can achieve modularity with moor files as well though. They can import each other so it's possible to declare tables and queries across many moor files and then make the dao only import those it actually needs.

Overall, I prefer to keep the current behavior to avoid a breaking change and to match Dart's upcoming NNBD.
