### ISSUE TITLE
moor_ffi does not validate prepared queries

### ISSUE THREAD

**Issue by sq6jnx** [simolus3/moor#608]
Consider this code (`moor_ffi` version 0.6):

```dart
import 'package:moor_ffi/database.dart';

void main() {
  var db = Database.memory();
  db.execute('CREATE TABLE foo (i INT PRIMARY KEY);');

  var insert = db.prepare('INSERT INTO foo (i) VALUES (?)');
  List.generate(10, (index) => insert.execute([index]));
  insert.close();

  var select = db.prepare('SELECT * FROM foo WHERE i > ?;');

  // I think I should get exception here, I forgot to pass a parameter to query
  var results = select.select().toList();
  // prints [],
  print(results);

  results = select.select([5]).toList();
  // prints [{i: 6}, {i: 7}, {i: 8}, {i: 9}], as expected
  print(results);

  results = select.select().toList();
  // prints [{i: 6}, {i: 7}, {i: 8}, {i: 9}] and this is totally unexpected
  print(results);
}
```

I think that NOT passing query parameters should be considered as an error and should raise Exception like: "Your query has 1 parameter(s) but no query parameters passed".

Second thing may be related to #607: I didn't pass any parameters to query, so I'd expect getting Exception. Surprisingly, I got same output as on previous query -- were my parameters cached somewhere?

**Comment by simolus3** [comment]
This matches sqlite's behavior, and I'm not sure if it's easy to spot those errors.

> I think that NOT passing query parameters should be considered as an error

I'm not aware of an sqlite api to count the amount of expected parameters in a query, so `moor_ffi` can't warn about misuse here. The default value for an unbound parameter in sqlite is `NULL`, so the query matches no rows without reporting an error.

> `prints [{i: 6}, {i: 7}, {i: 8}, {i: 9}] and this is totally unexpected`

Yes, that can be surprising. A `PreparedStatement` essentially wraps a [`sqlite3_stmt`](https://www.sqlite.org/c3ref/stmt.html), so we use the same instance across multiple `select` or `execute` calls. Inside those methods, we call [`sqlite3_bind_*`](https://www.sqlite.org/c3ref/bind_blob.html) for each argument. When there's no argument, we're not re-binding anything. I'm not aware of an api to reset all argument values. We could manually set arguments that were bound before back to null for consistency though.

In general, `package:moor_ffi/database.dart` is a rather low-level wrapper around sqlite3's C-api (with some adoptions for memory management and error handling). So it closely matches sqlite3's behavior here, even if that can be unintuitive.

**Comment by sq6jnx** [comment]
> In general, package:moor_ffi/database.dart is a rather low-level wrapper around sqlite3's C-api 

I get your point, but please understand mine: as an end user I feel it  "buggy", not "low-level".

To the point: 

> I'm not aware of an sqlite api to count the amount of expected parameters in a query,

I think it should be easy: assuming, that `?` characters must be inside `()` brackets and after `VALUES` keyword we can count number of `?` and if it does not match length of an array it is an error. I saw similar approach in (I think) `pymssql`, a Python library for MS SQL Server.

As stated elsewhere I am too new to Dart to create a PR, but I think I can prepare MWE on parameter matching.

**Comment by Mike278** [comment]
Parsing my sql statements at runtime to give behaviour that’s different from sqlite’s is not something I’d expect from a low level sqlite wrapper library. 

Maybe have a look at the main moor library - it has a really nice higher level query builder API that can generate the correct number of query parameters.

**Comment by simolus3** [comment]
> we can count number of ? and if it does not match length of an array it is an error

We also have to take comments, string literals and identifiers (`"?"`) into account. It's even more complicated than that: `SELECT ?5` requires 5 variables, but `SELECT ?, ?1` only has one.

It's not hard to get that right (`moor_generator` and `sqlparser` should), but it requires proper scanning and has some overhead for each query. I know that `sqflite` tries to replace variables with int literals on Android, and that caused some strange bugs in the past. I would prefer to avoid something like that in `moor_ffi`, especially since the benefit seems to be rather low.

If there's a supported mechanism for this in sqlite, it should be used by `moor_ffi`. But AFAIK there isn't, and in this case it seems fragile to add our own.

**Comment by simolus3** [comment]
I just found out about `sqlite3_bind_parameter_count`, so this can be implemented relatively safely.
