### ISSUE TITLE
return a boolean expression from the where method

### ISSUE THREAD

**Issue by blackBoyCode** [simolus3/moor#611]
I've been having trouble for several days trying to get a boolean from the where expression like this:
`bool hasID = await select(exampleTable)..where((t) => t.id.isIn([id])); //this give me an error`

I've also tried to return it using  a .map() after the query but didn't work as expected. The goal I'm trying to achieve , is to check if  the database has the id with a method if not call a network request and insert that value in the database.

I 've tried customQuery like this:
 
```
int id = 8978;
String table = exampleTable.entityName;
String condition = 'id=$id';

String query = 'SELECT EXISTS(SELECT * FROM $table WHERE $condition)';

bool temp = await customSelect(query).map((r) => r.readBool(condition)).getSingle();// that also didn't work as it give me a runtime error
```

I tried to assign it with an external variable like this:

```
bool assignValue;
select(exampleTable)..where((t) => assignValue = t.id.isIn([id]));/// Error:  a value type Expression<bool> can't be assigned to variable type bool.

```
I also tried to return a bool like this:

```
bool temp;

    (select(exampleTable)..where((t) => t.id.isIn([id])))
        .getSingle()
        .then((value) {
      if (value == null) {
        temp = false;
      } else {
        temp = true;
      }
    });

```

and lastly I thought of using the NotNull expression, I figure that if the select statement return null  then return false otherwise true but I didn't found any example of it usage to give it try, I only know that it is top level function.

I wonder , is there something that I missed while reading the docs? surely there might be simpler solution to solve this.

Thanks in advance for the assistance

**Comment by loomp** [comment]
Hello,

> bool hasID = await select(exampleTable)..where((t) => t.id.isIn([id])); //this give me an error

This by design would fail, as you do not execute .get()/getSingle() here and you use ".." operator which makes like to return query object, not the results.

Try with something like:
```
final query = select(exampleTable)..where((t) => t.id.isIn([id]));
final check = (await query.get())?.isNotEmpty ?? false;
```

**Comment by blackBoyCode** [comment]
I've gave it a shot and it's worked perfectly , I tried to do the same with the `getSingle()` but since it's not a list the method `?isNotEmpty` won't be available but I'm alright with this solution, thank you!
