### ISSUE TITLE
Custom query should also have an option to get the raw data

### ISSUE THREAD

**Issue by vanlooverenkoen** [simolus3/moor#615]
I want to use the compile time option to make sure our queries are always correct and typesafe.

For this query we need to map the data ourselfs to already existing models. Currently this is not possible because there will be a newly generated model for without the option to get the raw data. I would like to see an option to get the QueryRow as a result of the compile time generated queries

```
@UseDao(tables: [
  DbChatTable,
  DbChatMessageTable,
], queries: {
  'chatWithLatestMessageAndUnreadCount' : '''
   SELECT
     *
   FROM db_chat_table
   INNER JOIN (
     SELECT *
     FROM db_chat_message_table
     ORDER BY date DESC
   ) db_chat_message_table ON db_chat_table.firebase_document_id = db_chat_message_table.chat_id
   LEFT JOIN (
     SELECT COUNT(*) AS "amount_of_unread_messages", chat_id, read
     FROM db_chat_message_table
     WHERE read = 0
     GROUP BY db_chat_message_table.chat_id
   ) db_chat_message_table2 ON db_chat_table.firebase_document_id = db_chat_message_table2.chat_id
   GROUP BY db_chat_message_table.chat_id
   ORDER BY date DESC;
  '''
})
```

**Comment by simolus3** [comment]
Have you seen [nested results](https://moor.simonbinder.eu/docs/using-sql/moor_files/#nested-results)? For your query, something like `SELECT db_chat_table.**, db_chat_message_table.*, db_chat_message_table2.*` should work. The generator will create a `dbChatTable` field to hold a row of that table, which should make the mapping easier.

**Comment by simolus3** [comment]
The next option will introduce the `raw_result_set_data` option to do just this.
