### ISSUE TITLE
Is it possible to display table rows partially?

### ISSUE THREAD

**Issue by aaartyomsss** [simolus3/moor#622]
I am trying to build an app in which the main table rows are displayed by cards. If user clicks a specific card it should navigate him to the next page, where only pecific rows from the other table are displayed and they are dedicated to the chosen card only.
Is it achievable with this packages?

**Comment by htsv** [comment]
I'm guessing you have a one-to-many relation. This can definitely be done with this package. 
In case you are looking for joining the data from two tables, here is the link to it in documentation [https://moor.simonbinder.eu/docs/advanced-features/joins/](https://moor.simonbinder.eu/docs/advanced-features/joins/).

Also, what you need is more of your implementation on Flutter side. You could pass the data of the chosen Card and send to the next screen, which uses this and fetches the entries from the second table.
