### ISSUE TITLE
Switch back to pkg:analyzer_plugin

### ISSUE THREAD

**Issue by simolus3** [simolus3/moor#623]
The official analyzer plugin package finally supports the latest analyzer, so the dependency on `analyzer_plugin_fork` can be dropped and replaced.

**Comment by Mike278** [comment]
@simolus3 Just noticed `analyzer_plugin_fork` is still in the lockfile - does moor_generator still need it [here](https://github.com/simolus3/moor/blob/master/moor_generator/pubspec.yaml#L30)?

**Comment by simolus3** [comment]
We actually needed it again, because the `analyzer_plugin` package doesn't support analyzer 0.40 yet. Once it does I'll make the switch again :)

**Comment by Mike278** [comment]
Ah gotcha - I should've looked at the commit history.
