### ISSUE TITLE
[Watch] Not receiving updates when using transaction

### ISSUE THREAD

**Issue by deep34** [simolus3/moor#625]
I receive updates only if i'm not using transaction()
It works fine without it.
The stream is created outside the transaction and i use await for all the queries inside the transaction.

moor_flutter: ^3.0.0
moor_ffi: ^0.6.0
moor_generator: ^3.0.0

**Comment by kuhnroyal** [comment]
You should only use `moor_flutter` OR `moor_ffi`.
See https://moor.simonbinder.eu/docs/getting-started/starting_with_sql/#adding-the-dependency

This probably has no impact on your issue tho.

**Comment by simolus3** [comment]
Can you post more details and possibly some code to reproduce this? Moor has tests to cover stream behavior in transactions, so I'll need more information to track this down.

**Comment by marcos930807** [comment]
> I receive updates only if i'm not using transaction()
> It works fine without it.
> The stream is created outside the transaction and i use await for all the queries inside the transaction.
> 
> moor_flutter: ^3.0.0
> moor_ffi: ^0.6.0
> moor_generator: ^3.0.0

Just remember always **await** every (query,insert,updte,etc) inside your transaction.

**Comment by simolus3** [comment]
@deep34 I can't act on this issue without further information, so I'll close this. If you still run into this problem, please provide more information about what you're doing. I'll re-open the issue in then.
