### ISSUE TITLE
[Question] Writing a selectOnly query with distinct and where.

### ISSUE THREAD

**Issue by Drkstr** [simolus3/moor#627]
I am trying to implement the following query on moor. 

`select DISTINCT garnishName from RecipeGarnishes where postGarnish = 'true'`

where garnishName and postGarnish are columns in the RecipeGarnishes table. 

This is what I have at the moment

`final query = selectOnly(recipeGarnishes, distinct: true)
                ..addColumns([recipeGarnishes.garnishName])
                ..where(recipeGarnishes.postGarnish.equals(postGarnish));

 List<TypedResult> result = await query.get();

return result.map((row) => row.readTable(recipeGarnishes)).toList();`

 I get this error when I run that : 

Moor: Sent SELECT DISTINCT recipe_garnishes.garnish_name AS "recipe_garnishes.garnish_name" FROM recipe_garnishes WHERE recipe_garnishes.post_garnish = ?; with args [1]

[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The getter 'garnishName' was called on null.

Question: How do I implement a  select query with selected columns, distinct and where conditions. 

PS: Some StackOverflow point for grabs, if anyone is into that sort of thing. 
https://stackoverflow.com/questions/62187728/adding-distinct-to-a-flutter-moor-query

**Comment by Mike278** [comment]
Since you’re only selecting a single column, try replacing “row.readTable(recipeGarnishes)” with “row.read(recipeGarnishes.garnishName)”.

The bottom of https://moor.simonbinder.eu/docs/advanced-features/joins/#group-by has a similar example.

**Comment by simolus3** [comment]
Mike is right, you need to use `read` instead of `readTable`. I've commented on your SO question with a bit more details.

I think moor should throw an error in that case instead of returning `null`, see #628.

**Comment by Drkstr** [comment]
Thanks guys :)
