### ISSUE TITLE
Writing in Moor cause UI freeze in Flutter for windows.

### ISSUE THREAD

**Issue by SahajRana** [simolus3/moor#631]
Hi @simolus3, Could you help me with, how can we make data update in moor, UI separate or fast so that it doesn't freeze the UI during updation.

Does Isolates also work for Flutter for Windows app?

**Comment by simolus3** [comment]
> Does Isolates also work for Flutter for Windows app?

They should definitely work on Windows as well, yes. I recommend using them if you're running into UI freezes.

Let me know if that doesn't improve the situation or if you have more questions, I'll reopen this issue then.

**Comment by SahajRana** [comment]
Yup, it worked. Thanks!
