### ISSUE TITLE
File libCachedImageData.db is created by the standard database path (iOS)

### ISSUE THREAD

**Issue by Holofox** [simolus3/moor#633]
By default, the iOS database is initialized in [NSDocumentDirectory](https://developer.apple.com/documentation/foundation/nssearchpathdirectory/nsdocumentdirectory), access to this folder is not available to users, but we made it accessible by setting the [UIFileSharingEnabled](https://developer.apple.com/documentation/bundleresources/information_property_list/uifilesharingenabled) key, and move the creation of the database to [getLibraryDirectory](https://pub.dev/documentation/path_provider/latest/path_provider/getLibraryDirectory.html).

```dart
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:moor/moor.dart';
import 'package:moor_ffi/moor_ffi.dart';
import 'package:path_provider/path_provider.dart';
import 'package:sqflite/sqflite.dart' show getDatabasesPath;
import 'package:path/path.dart' as p;

LazyDatabase get moorDatabaseConnection => LazyDatabase(() async {
  final targetPlatformIsiOS = defaultTargetPlatform == TargetPlatform.iOS;
  final dbFolder = targetPlatformIsiOS ? (await getLibraryDirectory()).path
      : await getDatabasesPath();
  final file = File(p.join(dbFolder, 'db.sqlite'));

  return VmDatabase(file);
});
```

<details>
  <summary>Screenshot</summary>

  ![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-17 at 18 27 28](https://user-images.githubusercontent.com/19191492/84904392-b1228a00-b0c8-11ea-800d-7182953fab64.png)

</details>

Everything is fine, the database moved to the desired path, but the file **libCachedImageData.db** is also created in [NSDocumentDirectory](https://developer.apple.com/documentation/foundation/nssearchpathdirectory/nsdocumentdirectory). Why is this file still being created at the standard path? :)

**Comment by simolus3** [comment]
Moor doesn't create any additional databases behind your back. Are you sure that the file was created by moor? It might be another package doing that (it sounds like `flutter_map` creates a file with that name).

**Comment by davidmartos96** [comment]
@Holofox I'm pretty sure that database is created by the package `cached_network_image`. Since that package uses `sqflite` under the hood, the database is created in the default location. 
I don't think there is a way to change it for the package.

**Comment by Holofox** [comment]
@simolus3, @davidmartos96, oh, really, thanks for clarifying the situation.
