### ISSUE TITLE
question about update

### ISSUE THREAD

**Issue by sk784** [simolus3/moor#636]
Hello, can you help me with one moment?
I have two tables: 

```dart
class Employer extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get surname => text().withLength(min: 1, max: 50)();
  TextColumn get name => text().withLength(min: 1, max: 50)();
  TextColumn get middleName => text().withLength(min: 1, max: 50)();
  DateTimeColumn get birthDate => dateTime().nullable()();
  TextColumn get position => text().withLength(min: 1, max: 50)();
  IntColumn get children => integer()();
}

class Child extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get parentId => integer()();
  TextColumn get surname => text().withLength(min: 1, max: 50)();
  TextColumn get name => text().withLength(min: 1, max: 10)();
  TextColumn get middleName => text().withLength(min: 1, max: 50)();
  DateTimeColumn get birthDate => dateTime().nullable()();
}
```

My goal is update quantity of children in employer table, when i update child table.
And tables must be linked (`employer.id = child.parentId`).

I was looking for a similar example in tutorial but I didn't find it.
Thank you

**Comment by simolus3** [comment]
>  tables must be linked (employer.id = child.parentId).

You can use `REFERENCES` for that:

```dart
IntColumn get parentId => integer().customConstraint('NOT NULL REFERENCES employer (id)')();
```

To enforce this, you need to enable foreign key constraints:

```dart
MigrationStrategy get migration => MigrationStrategy(
  beforeOpen: (details) async {
    await customStatement('PRAGMA foreign_keys = ON');
  }
);
```

> My goal is update quantity of children in employer table, when i update child table.

This is more complicated. You could use generated columns for that, but moor doesn't support those at the moment. If it's possible, you could just remove the `children` column and replace with a `COUNT()` in queries. Otherwise you could use a trigger to automatically update that value.
