### ISSUE TITLE
How to connect "db.execute(query);" with moor_isolates?

### ISSUE THREAD

**Issue by SahajRana** [simolus3/moor#643]
Hi @simolus3, hope you are well! As I was working on my project, I have successfully used moor_isolates for generated moor tables. But I'm wondering how can we use moor_isolates with non-generated tables which use `db.execute(queryStr);` 

```
MoorIsolate isolate = await MoorIsolate.spawn(backgroundConnection);
DatabaseConnection connection = await isolate.connect();
```
with
```
String query = r''' 
    CREATE TABLE ''' + tableName + ''' (
      ''' + columnString.toString() + '''
    );
  ''';
final db = Database.openFile(File(resolver.dbFilename));
db.execute(query);
```

**Comment by simolus3** [comment]
If you only need to run custom queries, I would still recommend to let moor generate an empty database class for you (just set `tables: []` in your `@UseMoor` annotation). Inside that generated class, you can use `customStatement` to run queries. Moor will take care of opening the underlying connection and so on.

If you want to create custom tables, you could use `customStatement` in `MigrationStrategy.onCreate` or `onUpgrade`. Moor will automatically use the right database connection under the hood, even if it's connected to another isolate.

**Comment by SahajRana** [comment]
@simolus3, Thanks for the reply. Can this approach generate a table dynamically/on runtime?

**Comment by simolus3** [comment]
You can use `customStatement` to run a `CREATE TABLE` statement, if that's what you need.

**Comment by SahajRana** [comment]
Awesome, I will give it a try and let you know.

**Comment by SahajRana** [comment]
It worked, thanks!
