### ISSUE TITLE
[moor_ffi] No flags possible to pass for REGEXP

### ISSUE THREAD

**Issue by loomp** [simolus3/moor#644]
Hello,

It looks like no flags are possible to pass into REGEXP where query.
Embedding flags into REGEXP string does not work.

Could you please extend it to be achievable?

Like the second parameter, such as:
`..where((table) => table.<column>.regexp(pattern, flags))`

Thank you in advance.

**Comment by simolus3** [comment]
Thanks for the suggestion. This is done on `develop` and will ship with the next moor release.
