### ISSUE TITLE
[moor_ffi] question: transactions?

### ISSUE THREAD

**Issue by moovida** [simolus3/moor#645]
Hi, I looked through the tests but couldn't find the answer.

Does moor_ffi support transactions?

Thanks!

**Comment by simolus3** [comment]
There's no builtin transaction support in `moor_ffi`. However, you can use `BEGIN TRANSACTION` and `COMMIT TRANSACTION` manually.

**Comment by moovida** [comment]
Thank you @simolus3 , you mean that I can execute the BEGIN , then do all my stuff and if it all goes well, execute the END. If I have problems, the ROLLBACK?

**Comment by simolus3** [comment]
Yes exactly. `moor_ffi` is a small wrapper around sqlite, so you can just follow [the documentation here](https://www.sqlite.org/lang_transaction.html).

The main `moor` package has builtin transaction support and makes this much easier of course. But if you're using raw `moor_ffi` you'll need to write the transaction logic yourself.
