### ISSUE TITLE
No such table error

### ISSUE THREAD

**Issue by SahajRana** [simolus3/moor#647]
Hi @simolus3,

I'm receiving this error when I delete the saved DB file and rebuild the application.

```
flutter: Moor: Sent SELECT * FROM my_table; with args []
[ERROR:c:\b\s\w\ir\cache\builder\src\flutter\runtime\dart_isolate.cc(875)] Unhandled exception:
SqliteException: no such table: my_table, SQL logic error
```

How can we make sure, the table exists before doing any operations?

**Comment by simolus3** [comment]
If you delete the database file and re-open, moor should create the tables automatically. But you'll need to `close` all moor databases before deleting the database. Do you have a small sample I could use to reproduce this?

**Comment by SahajRana** [comment]
It's resolved, it was due to use of the same isolate_connection handle for two different database instances.
So it wasn't calling create table on its own, due to some unknown reasons.

**Comment by firatcetiner** [comment]
I'm getting this issue for no reason from what I see. I tried deleting adding a migration strategy, cleaning the project and re-generate the database files not none of those solve the problem. I don't see any `CREATE TABLE` log statement.

**Comment by simolus3** [comment]
> I tried adding a migration strategy

Can you post that? In particular, you need an `onUpgrade` handler.

> and re-generate the database files

Just to be sure: The new tables do show up in the generated code, right? You can use them from Dart?

**Comment by firatcetiner** [comment]
> > I tried adding a migration strategy
> 
> Can you post that? In particular, you need an `onUpgrade` handler.
> 
Okay, I only add a onCreate handler since I have cleaned the project.
> > and re-generate the database files
> 
> Just to be sure: The new tables do show up in the generated code, right? You can use them from Dart?
Yes, no syntax errors with the generated code.

The isssue does not appear now, I am not sure why. 😄

**Comment by simolus3** [comment]
In general, if you already have a database file on a device and then add a new table (or do anything else that would require a schema migration), you need to increment your `schemaVersion` and add logic in your `onUpgrade` callback.
The `onCreate` callback is only invoked when a new database is created on the device, not when you re-generate code or run `flutter clean`.

**Comment by firatcetiner** [comment]
> In general, if you already have a database file on a device and then add a new table (or do anything else that would require a schema migration), you need to increment your `schemaVersion` and add logic in your `onUpgrade` callback.
> The `onCreate` callback is only invoked when a new database is created on the device, not when you re-generate code or run `flutter clean`.

Hmm, onCreate called on the first run then? I mean after deleting the application, flutter clean and rebuild. Because I tried it multiple times.

**Comment by simolus3** [comment]
> I mean after deleting the application

On some Android devices, uninstalling the application does not delete its data. Go to application settings and manually wipe its data to be sure.

**Comment by firatcetiner** [comment]
> > I mean after deleting the application
> 
> On some Android devices, uninstalling the application does not delete its data. Go to application settings and manually wipe its data to be sure.

Yes I am aware of that. I also changed autoBackup to false in AndroidManifest but the result was the same. I'm pretty sure I did something wrong when rebuilding the application.

I don't think my issue caused by moor, since it is resolved there is no need to further investigate. Thank you for the answers.
