### ISSUE TITLE
Moor files

### ISSUE THREAD

**Issue by jaredgreener** [simolus3/moor#649]
This line fails with Too many positional arguments (0 expected, 1 found):

MoorDb() : super(FlutterQueryExecutor.inDatabaseFolder('app.db'));

should it be??

MoorDb() : super(FlutterQueryExecutor.inDatabaseFolder(
    path: 'db.sqlite',
    logStatements: true
  ));

**Comment by simolus3** [comment]
Yeah, the `path` is a named argument, so the second snippet you posted is correct. I've fixed this, the website should update shortly.
