### ISSUE TITLE
where() with NULL

### ISSUE THREAD

**Issue by dricholm** [simolus3/moor#65]
I have a question about using `where()` with `NULL` values.

When using `.equals(null)` inside `where()` it does not return anything.
```dart
Stream<List<Entry>> get watchWhereNull => (select(entries)
      ..where(
        (entry) => entry.categoryId.equals(null),
      ))
    .watch();
```

But when using `customSelectStream()` the same way, it will work correctly.

```dart
customSelectStream(
  'SELECT * FROM entries WHERE category_id IS NULL',
  readsFrom: {entries},
).map(
  (rows) =>
      rows.map((row) => Entry.fromData(row.data, db)).toList(),
);
```

From what I have seen `Comparison.equal` is using `=` in that case, but checking NULL value should be using `column IS NULL` or `column IS NOT NULL`.
Is there another way to check NULL value with moor other than custom queries?
I have not found such a function.

Thank you!

**Comment by simolus3** [comment]
Yeah, there's [`isNull`](https://pub.dev/documentation/moor/latest/moor/isNull.html) which you can use, so it would just be `(entry) => isNull(entry.category)`.

Maybe we should add `expression.isNull()` for a better visibility in auto-complete 🤔

**Comment by dricholm** [comment]
I see. I didn't check the documentation, only searched it on the (Moor)[https://moor.simonbinder.eu/] website and through IDE auto-completion.

`expression.isNull()` could be a good idea, although it is not that important I think. I will leave this issue open in that case, feel free to close it.

Thank you!

**Comment by simolus3** [comment]
I think I'll just close it. If it comes up more often I can still add it later.

**Comment by giriss** [comment]
> Yeah, there's [`isNull`](https://pub.dev/documentation/moor/latest/moor/isNull.html) which you can use, so it would just be `(entry) => isNull(entry.category)`.
> 
> Maybe we should add `expression.isNull()` for a better visibility in auto-complete

Adding `expression.isNull()` will be much better

**Comment by peterpoliwoda** [comment]
Going with the empty convention in dart could there also be a isNotNull?

**Comment by simolus3** [comment]
We  [have both](https://pub.dev/documentation/moor/latest/moor/SqlIsNull.html) `isNull` and `isNotNull` now.

**Comment by peterpoliwoda** [comment]
Once trying the other one Android Studio suggested the other one as well thank you very much. This will do great 🙂 .
