### ISSUE TITLE
Update with upsert with non nullable value set to absent

### ISSUE THREAD

**Issue by friebetill** [simolus3/moor#650]
I have a question about the `onConflict` parameter of `insert`.
For example, I have the following schema:
```dart
class Foos extends Table {
  TextColumn get id => text()();
  TextColumn get name => text()();
  DateTimeColumn get createdAt => dateTime()();
  DateTimeColumn get updatedAt => dateTime()();

  @override
  Set<Column> get primaryKey => {id};
}
```

In the class `FoosDao` is an `upsert` method that should do the following:
1. If `createdAt` is `absent` during an insert, the date should be set to now (same for `updatedAt`).
2. If `createdAt` is not `absent` during the insert, the given value is set (same for `updatedAt`).
3. During an update `createdAt` should not be overwritten.

I think for this requirement the `onConflict` parameter is a good fit:
```dart
Future<int> upsert(FoosCompanion companion) async {
  final now = DateTime.now();
  final companionToUpsert = companion.copyWith(
    id:  companion.id.present ? companion.id : Uuid().v4(),
    createdAt: companion.createdAt.present ? companion.createdAt : Value(now),
    updatedAt: companion.updatedAt.present ? companion.updatedAt : Value(now),
  );

  return into(foos).insert(
    companionToUpsert,
    onConflict: DoUpdate((old) => companionToUpsert.copyWith(createdAt: const Value.absent())),
  );
}
```

Now I tested this by upserting the two companions to the database:
```dart
var foo = FoosCompanion(name: Value('NAME'));
final id = await foosDao.upsert(foo);

foo = foo.copyWith(id: Value(id), name: const Value.absent());
await foosDao.upsert(foo);
```

The date times `createdAt` and `updatedAt` worked as expected, but during the update something unexpected occurred:
```
ERROR: InvalidDataException: Sorry, Instance of 'FoosCompanion' cannot be used for that because: 
• name: This value was required, but isn't present
```

As far as I understood it, an attempt is made to execute the insert, which fails immediately, instead of going directly to the onConflict case.

A not optimal solution I came up with is to set the non nullable fields to a default value for the insert and then set them to absent during the update. Like this:
```dart
Future<int> upsert(FoosCompanion companion) async {
  final now = DateTime.now();
  final companionToUpsert = companion.copyWith(
    id:  companion.id.present ? companion.id : Uuid().v4(),
    createdAt: companion.createdAt.present ? companion.createdAt : Value(now),
    updatedAt: companion.updatedAt.present ? companion.updatedAt : Value(now),
    name: companion.name.present ? companion.name : const Value(''),
  );

  return into(foos).insert(
    companionToUpsert,
    onConflict: DoUpdate(
      (old) => companionToUpsert.copyWith(
        createdAt: const Value.absent(),
        name: companion.name
      ),
    ),
  );
}
```

Now I run the risk of upserting foo in the database without a name. Because no error message is thrown, because the name is set to an empty string.

So my question is, is there a way to update `foo` with the name set to absent that the code is still secure?

**Comment by friebetill** [comment]
It can be slightly improved that an error is thrown when inserting `foo` without `id` where `name is `absent`:
```dart
Future<int> upsert(FoosCompanion companion) async {
  final now = DateTime.now();
  final companionToUpsert = companion.copyWith(
    createdAt: companion.createdAt.present ? companion.createdAt : Value(now),
    updatedAt: companion.updatedAt.present ? companion.updatedAt : Value(now),
  );

  if (companion.id != null) {
    companionToUpsert = companionToUpsert.copyWith(
      name: companion.name.present ? companion.name : const Value('')
    );
  }

  return into(foos).insert(
    companionToUpsert,
    onConflict: DoUpdate(
      (old) => companionToUpsert.copyWith(
        createdAt: const Value.absent(),
        name: companion.name
      ),
    ),
  );
}
```
Now I think there is only one problem when `foo` is inserted with `id` but no `name`.
In this case no exception is thrown, but `name` is written to the database as an empty string.

**Comment by simolus3** [comment]
I'm not sure I understand the problem, or how moor could fix this. `name` is non-nullable and doesn't have a default value, so it needs to be set during an insert. If you try to insert a row where `name` is null or absent, moor will complain.
It could always be that an upsert behaves just like an `insert` (if there's no conflicting row in the table), so all integrity checks for inserts need to run on upserts as well.

You can declare the name as `TextColumn get name => text().nullable()();` if you want to allow null values in the database. With that change, your original snippet works for me.

**Comment by friebetill** [comment]
Thank you very much for your answer. I thought that might be an unintentional limitation of Moor. It's a bit of a bummer that SQL can't do it in general.

I now use `insert` and `update` methods  in the Dao, because I know what should be performed.

**Comment by simolus3** [comment]
> It's a bit of a bummer that SQL can't do it in general

Maybe I'm missing something, but I don't see how that could even work in theory. Where is the initial value supposed to come from if there is no row to replace and it's not set in the insert?
