### ISSUE TITLE
Is it the bug related to moor? (Error: The non-abstract class 'TodoEntry' is missing implementations for these members)

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#653]
I raised a bug to **moor_shared** team, please see [this](https://github.com/rodydavis/moor_shared/issues/8).

But I am still wondering if it is related to **moor** itself? It work fine when I use the old version of **moor** and **moor_ffi**, such as **moor 2.1.0** and **moor_ffi 0.3.0**, it show the following error(detail shown in [this](https://github.com/rodydavis/moor_shared/issues/8)) after upgrading **moor** and **moor_ffi** to to latest version.

Thanks.

**Comment by simolus3** [comment]
I assume most of this is due to a version mismatch between `moor` and `moor_generator`. I recommend to use `moor: ^3.0.0` or later and `moor_generator: ^3.0.0` or later. We'll fix the `moor_shared` example soon,  but I don't think this is a moor bug.
