### ISSUE TITLE
Foreign Key Deletion

### ISSUE THREAD

**Issue by aaditya-brt** [simolus3/moor#657]
How to allow or not allow parent table record deletion which is a foreign key of another table .
For eg: I have two tables Tasks and Tag. Tag table has a foreign key of Tasks table.So when I try to delete record from task table, it should either restrict or delete records from Tag table also.

```dart
class Tasks extends Table {
  IntColumn get id => integer().autoIncrement()();

  TextColumn get name => text().withLength(min: 1, max: 100)();

  @override
  Set<Column> get primaryKey {
    id;
  }
}

class Tag extends Table {
  IntColumn get id => integer().autoIncrement()();

  IntColumn get taskID => integer()
      .nullable()
      ();

  TextColumn get name => text().withLength(min: 1, max: 100)();

  @override
  Set<Column> get primaryKey {
    id;
  }

  @override
  List<String> get customConstraints {
    ['FOREIGN KEY(taskID) REFERENCES task(id) '];
  }
}
```

**Comment by simolus3** [comment]
Have you [enabled foreign keys](https://www.sqlite.org/foreignkeys.html#fk_enable)? To actually enforce them, you'll need to use something like

```dart
@override
MigrationStrategy get migration {
  return MigrationStrategy(
   // you can keep your onCreate and onUpgrade callbacks
    beforeOpen: (details) async {
      await customStatement('PRAGMA foreign_keys = ON;');
    }
  );
}
```

You can then use `FOREIGN KEY (task_i_d) REFERENCES tasks (id) ON DELETE RESTRICT` or `ON DELETE CASCADE`, depending on what you need. Note that moor transforms `camelCase` Dart columns to `snake_case` in sql.

**Comment by aaditya-brt** [comment]
> Have you [enabled foreign keys](https://www.sqlite.org/foreignkeys.html#fk_enable)? To actually enforce them, you'll need to use something like
> 
> ```dart
> @override
> MigrationStrategy get migration {
>   return MigrationStrategy(
>    // you can keep your onCreate and onUpgrade callbacks
>     beforeOpen: (details) async {
>       await customStatement('PRAGMA foreign_keys = ON;');
>     }
>   );
> }
> ```
> 
> You can then use `FOREIGN KEY (task_i_d) REFERENCES tasks (id) ON DELETE RESTRICT` or `ON DELETE CASCADE`, depending on what you need. Note that moor transforms `camelCase` Dart columns to `snake_case` in sql.

**Comment by aaditya-brt** [comment]
> Have you [enabled foreign keys](https://www.sqlite.org/foreignkeys.html#fk_enable)? To actually enforce them, you'll need to use something like
> 
> ```dart
> @override
> MigrationStrategy get migration {
>   return MigrationStrategy(
>    // you can keep your onCreate and onUpgrade callbacks
>     beforeOpen: (details) async {
>       await customStatement('PRAGMA foreign_keys = ON;');
>     }
>   );
> }
> ```
> 
> You can then use `FOREIGN KEY (task_i_d) REFERENCES tasks (id) ON DELETE RESTRICT` or `ON DELETE CASCADE`, depending on what you need. Note that moor transforms `camelCase` Dart columns to `snake_case` in sql.

I have enabled foreign keys and have also tried using task_i_d instead of taskID, but when I try to delete record from Task table,it gets deleted instead of restricting it.
Is there any way I can  confirm whether foreign key is enabled and also whether there is foreign key in Tag table?

**Comment by simolus3** [comment]
If you didn't set a `ON DELETE RESTRICT` clause when defining the column, it might be violated when the referenced row is deleted.

> Is there any way I can confirm whether foreign key is enabled

You can use `customSelect('PRAGMA foreign_keys;')` - if it returns `1`, foreign keys are enabled.

> whether there is foreign key in Tag table?

You could use `SELECT sql FROM sqlite_master WHERE name='tag';` to show the `CREATE TABLE` statement.

**Comment by aaditya-brt** [comment]
Thanks for the guidance.The above solution is working.
Is there any documentation for this?

**Comment by simolus3** [comment]
Great to hear that it's working! The [`beforeOpen`](https://moor.simonbinder.eu/docs/advanced-features/migrations/#post-migration-callbacks) callback is documented. The other things are very sqlite3-specifc, so not really in the realm of moor's documentation.
