### ISSUE TITLE
[proposal] Automatic migration definitions

### ISSUE THREAD

**Issue by rodydavis** [simolus3/moor#664]
This is just a proposal but wanted to get your thoughts.

Aquaduct generates migration files for you every time you run the build command 🤔

https://aqueduct.io/docs/db/db_tools/

Since we know the previous schema maybe this could be worth looking into?

**Comment by simolus3** [comment]
There has been some discussion for this at https://github.com/simolus3/moor/issues/240 I'll close this issue in favor of that one.

I agree that this is a nice feature, but it's also complicated to implement :smile: Maybe we can start with simple cases and work from there.

**Comment by rodydavis** [comment]
Agreed! And awesome 😎
