### ISSUE TITLE
multiple joins in a different table

### ISSUE THREAD

**Issue by Elias8** [simolus3/moor#665]
I have three different tables, and I want to join them and return some data. Also, I have a one-to-many relationship between `table1` and `table3`, so I expect the result to contain multiple `table3Data`. Below code it the query I wrote for it. But I only get only one row of `table3`.
```dart
final joins = [
  leftOuterJoin(
    table2,
    table2.otherId.equalsExp(table1.id),
  ),
  leftOuterJoin(
    table3,
    table3.otherId.equalsExp(table1.id),
  ),
];

Future<SomeData> getById(int id) {
  return
    (select(table1).where((tbl) => tbl.id.equals(id)))
      .join(joins)
      .map((rows) {
      final table1Data = rows.readTable(table1);
      final table2Data = rows.readTable(table2);
      final table3Data = rows.readTable(table3); // here I want to get list of table3.
      return SomeData(table1Data, table2Data, table3Data);
      })
      .getSingle();
}
```
I have also tried to check the `TypedResult` content in the debug mode, and it found only one row of 'table3`.

**Comment by simolus3** [comment]
That's just how joins work. A row can't contain multiple child-rows in some columns. For those, you'll need more than one select. We have an example on how those could look like in [the documentation](https://moor.simonbinder.eu/docs/examples/relationships/). Unfortunately it's a bit of work, but it basically looks like this:

1 Load all matching `table1` rows and their associated `table2` through a join
2. Load all `table3` rows that are associated with what we got in step 1.
3. Merge them together in Dart

**Comment by Elias8** [comment]
OK. Thanks.

**Comment by andyyapwl** [comment]
Can check if I have 2 tables i.e. Quiz and Question and they are one-to-many relationship, one quiz has many questions and can i map the query into the objects like below:

`final quiz = await (select(quizs)..where((t) => t.id.equals(id))).getSingleOrNull();`
`    if (quiz != null) {`
`      final questions =  await (select(db.questions)..where((q) => q.quizId.equals(id))).get();`
`      return QuizModel(`
`       id: quiz.id,`
`       title: quiz.title,`
`       questions: questions`
`           .map((question) => QuestionModel(`
`                 id: question.id,`
`                 title: question.title,`
`                 quizId: question.quizId,`
`                 description: question.description,`
`               ))`
`           .toList(),`
`     );`
`   }`


Or i can combine into one single query and map the result into my object model, thanks!

**Comment by simolus3** [comment]
The approach with two queries should work well here. If you want to do it with a single query, you could select all questions in the quiz and just join the quiz onto that query with an inner join. But that gives you the full quiz in each row (since they'll all have the same rows, you can just pick any of them).
But again, doing this in two queries is fine.

**Comment by andyyapwl** [comment]
thanks @simolus3   for your very fast and detailed response, and for the great library! kudos to you!
