### ISSUE TITLE
Is there a override for fromJson to convert datetime string to date before insert into data

### ISSUE THREAD

**Issue by jesseframework** [simolus3/moor#666]
factory PreferenceData.fromJson(Map<String, dynamic> json,
      {ValueSerializer serializer}) {
    serializer ??= moorRuntimeOptions.defaultSerializer;
    return PreferenceData(
      id: serializer.fromJson<int>(json['id']),
      tenantId: serializer.fromJson<int>(json['tenantId']),
      code: serializer.fromJson<String>(json['code']),
      preferenceName: serializer.fromJson<String>(json['preferenceName']),
      value: serializer.fromJson<String>(json['value']),
      description: serializer.fromJson<String>(json['description']),
      domain: serializer.fromJson<String>(json['domain']),
      isGlobal: serializer.fromJson<bool>(json['isGlobal']),
      syncError: serializer.fromJson<String>(json['syncError']),
      expiredDateTime: serializer.fromJson<DateTime>(json['expiredDateTime']),
    );
  }

**Comment by simolus3** [comment]
The json serializer doesn't affect what's written into the table. But you can read a `DateTime` from a string by providing a custom `ValueSerializer`:


```dart
class DateTimeAsStringSerializer extends ValueSerializer {
  final ValueSerializer _inner;

  const DateTimeAsStringSerializer(
      [this._inner = const ValueSerializer.defaults()]);

  @override
  T fromJson<T>(dynamic json) {
    if (T == DateTime) {
      return DateTime.parse(json as String) as T;
    }

    return _inner.fromJson<T>(json);
  }

  @override
  dynamic toJson<T>(T value) {
    if (value is DateTime) {
      // Or how you want to serialize the DateTime
      return value.toString();
    }

    return _inner.toJson(value);
  }
}

void main() {
  moorRuntimeOptions.defaultSerializer = const DateTimeAsStringSerializer();
  // ...
}
```

How exactly you read or write the `DateTime` is up to you of course.
