### ISSUE TITLE
SQLite Error 6410 when inserting large dataset into virtual table

### ISSUE THREAD

**Issue by remcoanker** [simolus3/moor#667]
I have a database with a fts5 virtual table, populated using triggers. When I try to insert a batch with a large amount of data (about 20.000 records), SQLite attempts to use a temp file, but none is set by default on Android, causing error 6410.

Two workarounds:
```
await customStatement("PRAGMA temp_store = 2");
```
OR
```
final dbFolder = await getTemporaryDirectory();
await customStatement('PRAGMA temp_store_directory="${dbFolder.path}"'); // Deprecated
```

Is it possible to set a default path for the temp directory during compilation?

Another solution is to compile SQLite on Android with `SQLITE_TEMP_STORE=2` to use memory by default.

**Comment by simolus3** [comment]
> temp directory during compilation

I don't think there is. In my understanding, each Android app has its own temporary directory, so I think a compile-time option wouldn't help here. There are some runtime options, but those are all marked as deprecated. 

> with `SQLITE_TEMP_STORE=2` to use memory by default.

I'll enable that flag with the next `moor_ffi` version, thanks!
