### ISSUE TITLE
Moor is not working on IOS 11 and lower

### ISSUE THREAD

**Issue by godzeit** [simolus3/moor#668]
Flutter: 1.17.4  
moor: ^3.1.0 
moor_ffi: 0.5.0

On higer IOS and android evrything working perfectly

**Comment by simolus3** [comment]
Older iOS versions still come with a sqlite3 library that we should be able to use. You could try to include the latest sqlite3 version with your app like this: https://github.com/simolus3/moor/issues/547#issuecomment-624526982.

But can you provide more details on what isn't working? I expect that the latest sqlite3 features aren't available on old iOS versions, but moor should work in general.

**Comment by EpicKim** [comment]
same here.

flutter: ══╡ EXCEPTION CAUGHT BY COMIC ╞═════════════════════════════════════════════════════════════════════
flutter: The following SqliteException was thrown:
flutter: SqliteException(1): near "ON": syntax error, SQL logic error or missing database (code 1)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Database.prepare 
package:moor_ffi/…/impl/database.dart:155
flutter: #1      _VmDelegate._runWithArgs 
package:moor_ffi/src/vm_database.dart:71
flutter: #2      _VmDelegate.runInsert 
package:moor_ffi/src/vm_database.dart:84
flutter: #3      _ExecutorWithQueryDelegate.runInsert.<anonymous closure> 
package:moor/…/helpers/engines.dart:69
flutter: #4      BasicLock.synchronized 
package:synchronized/src/basic_lock.dart:32
flutter: #5      _ExecutorWithQueryDelegate._synchronized 
package:moor/…/helpers/engines.dart:22
flutter: #6      _ExecutorWithQueryDelegate.runInsert 
package:moor/…/helpers/engines.dart:67
flutter: #7      LazyDatabase.runInsert 
package:moor/…/utils/lazy_database.dart:60
flutter: #8      InsertStatement.insert.<anonymous closure> 
package:moor/…/statements/insert.dart:68
flutter: #9      QueryEngine.doWhenOpened.<anonymous closure> 
package:moor/…/api/query_engine.dart:98
flutter: #18     BasicLock.synchronized (package:synchronized/src/basic_lock.dart)
flutter: <asynchronous suspension>
flutter: #19     DelegatedDatabase.ensureOpen 
package:moor/…/helpers/engines.dart:238
flutter: #20     LazyDatabase.ensureOpen.<anonymous closure>

**Comment by EpicKim** [comment]
> #547 (comment)

same here.

flutter: ══╡ EXCEPTION CAUGHT BY COMIC ╞═════════════════════════════════════════════════════════════════════
flutter: The following SqliteException was thrown:
flutter: SqliteException(1): near "ON": syntax error, SQL logic error or missing database (code 1)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0 Database.prepare
package:moor_ffi/…/impl/database.dart:155
flutter: #1 _VmDelegate._runWithArgs
package:moor_ffi/src/vm_database.dart:71
flutter: #2 _VmDelegate.runInsert
package:moor_ffi/src/vm_database.dart:84
flutter: #3 _ExecutorWithQueryDelegate.runInsert.
package:moor/…/helpers/engines.dart:69
flutter: #4 BasicLock.synchronized
package:synchronized/src/basic_lock.dart:32
flutter: #5 _ExecutorWithQueryDelegate._synchronized
package:moor/…/helpers/engines.dart:22
flutter: #6 _ExecutorWithQueryDelegate.runInsert
package:moor/…/helpers/engines.dart:67
flutter: #7 LazyDatabase.runInsert
package:moor/…/utils/lazy_database.dart:60
flutter: #8 InsertStatement.insert.
package:moor/…/statements/insert.dart:68
flutter: #9 QueryEngine.doWhenOpened.
package:moor/…/api/query_engine.dart:98
flutter: #18 BasicLock.synchronized (package:synchronized/src/basic_lock.dart)
flutter:
flutter: #19 DelegatedDatabase.ensureOpen
package:moor/…/helpers/engines.dart:238
flutter: #20 LazyDatabase.ensureOpen.

**Comment by EpicKim** [comment]
> Older iOS versions still come with a sqlite3 library that we should be able to use. You could try to include the latest sqlite3 version with your app like this: [#547 (comment)](https://github.com/simolus3/moor/issues/547#issuecomment-624526982).
> 
> But can you provide more details on what isn't working? I expect that the latest sqlite3 features aren't available on old iOS versions, but moor should work in general.

same here.

flutter: ══╡ EXCEPTION CAUGHT BY COMIC ╞═════════════════════════════════════════════════════════════════════
flutter: The following SqliteException was thrown:
flutter: SqliteException(1): near "ON": syntax error, SQL logic error or missing database (code 1)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0 Database.prepare
package:moor_ffi/…/impl/database.dart:155
flutter: #1 _VmDelegate._runWithArgs
package:moor_ffi/src/vm_database.dart:71
flutter: #2 _VmDelegate.runInsert
package:moor_ffi/src/vm_database.dart:84
flutter: #3 _ExecutorWithQueryDelegate.runInsert.
package:moor/…/helpers/engines.dart:69
flutter: #4 BasicLock.synchronized
package:synchronized/src/basic_lock.dart:32
flutter: #5 _ExecutorWithQueryDelegate._synchronized
package:moor/…/helpers/engines.dart:22
flutter: #6 _ExecutorWithQueryDelegate.runInsert
package:moor/…/helpers/engines.dart:67
flutter: #7 LazyDatabase.runInsert
package:moor/…/utils/lazy_database.dart:60
flutter: #8 InsertStatement.insert.
package:moor/…/statements/insert.dart:68
flutter: #9 QueryEngine.doWhenOpened.
package:moor/…/api/query_engine.dart:98
flutter: #18 BasicLock.synchronized (package:synchronized/src/basic_lock.dart)
flutter:
flutter: #19 DelegatedDatabase.ensureOpen
package:moor/…/helpers/engines.dart:238
flutter: #20 LazyDatabase.ensureOpen.

**Comment by simolus3** [comment]
@EpicKim Can you enable `logStatements` on the `VmDatabase` to see the statement that fails?

I suspect this might be because of an old sqlite3 version. You can ship the latest version with your app like this https://github.com/simolus3/moor/issues/547#issuecomment-624526982, maybe that fixes the issue.

**Comment by EpicKim** [comment]
> @EpicKim Can you enable `logStatements` on the `VmDatabase` to see the statement that fails?
> 
> I suspect this might be because of an old sqlite3 version. You can ship the latest version with your app like this [#547 (comment)](https://github.com/simolus3/moor/issues/547#issuecomment-624526982), maybe that fixes the issue.

I figured out why. I use `insertOnConflictUpdate` which is not supported by old-version sqlite. I repaced it with `into(xx).insert(xxx, mode:InsertMode.insertOrReplace);` and solved this issue.

**Comment by godzeit** [comment]
> > @EpicKim Can you enable `logStatements` on the `VmDatabase` to see the statement that fails?
> > I suspect this might be because of an old sqlite3 version. You can ship the latest version with your app like this [#547 (comment)](https://github.com/simolus3/moor/issues/547#issuecomment-624526982), maybe that fixes the issue.
> 
> I figured out why. I use `insertOnConflictUpdate` which is not supported by old-version sqlite. I repaced it with `into(xx).insert(xxx, mode:InsertMode.insertOrReplace);` and solved this issue.

Looks like I had the same problem. Unfortunetly, I didn't have such device to debug on my own, but when I published my app with replaced `insertOnConflictUpdate ` everything works fine. Thank you!

**Comment by zakihou** [comment]
iam workin with sqflite: ^2.2.8+4
i have erro in near "ON": syntax error
E/flutter ( 9325): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: DatabaseException(near "ON": syntax error (code 1): , while compiling: INSERT OR REPLACE INTO paycode

pleass hellp me!!!!
