### ISSUE TITLE
Support for COLLATE

### ISSUE THREAD

**Issue by knaeckeKami** [simolus3/moor#67]
I would like to see support for COLLATE.

I want to order a result alphabetically, but case insensitively.
Currently, I do this with `<query> order by <column> collate nocase;`

**Comment by simolus3** [comment]
Done on the `develop` branch, this will be a part of moor 1.6 when it comes out. You can use `collate` on a text column for this, you'll also be able to use `COLLATE` expressions in compiled queries.
