### ISSUE TITLE
I'm having this problem when creating a new project with Moor

### ISSUE THREAD

**Issue by claudneysessa** [simolus3/moor#678]
[moor] flutter pub get
Running "flutter pub get" in moor...                            
Error on line 24, column 3 of pubspec.yaml: A package may not list itself as a dependency.

   ╷

24 │   moor: ^3.2.0

   │   ^^^^

   ╵
pub get failed (65;    ╵)
exit code 65

**Comment by claudneysessa** [comment]
PS C:\Developer\Flutter\DBM\moor> flutter pub upgrade
Error on line 24, column 3 of pubspec.yaml: A package may not list itself as a dependency.
   ╷
24 │   moor: ^3.2.0
   │   ^^^^
   ╵
Running "flutter pub upgrade" in moor...
pub upgrade failed (65;    ╵)
PS C:\Developer\Flutter\DBM\moor>

**Comment by claudneysessa** [comment]
My pubspec
---------------------------

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  moor_flutter: ^3.0.0
  moor: ^3.2.0
  path_provider: ^1.6.11
  path: ^1.7.0
  dio: ^3.0.9
  flutter_mobx: ^1.1.0+1
  mobx: ^1.2.1+1
  flutter_modular: ^1.2.7+1
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  moor_generator: ^3.2.0
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

**Comment by claudneysessa** [comment]
I tried to use moor_ffi and he gives the following error

ArgumentError (Invalid argument(s): Failed to load dynamic library (dlopen failed: library "/data/data/com.example.exemplo_moor/lib/libsqlite3.so" not found))

**Comment by simolus3** [comment]
> A package may not list itself as a dependency.

Is your project called `moor` too? If so, you'd need to choose another name (like `try_moor` or something).

> I tried to use moor_ffi and he gives the following error

This is an Flutter issue unfortunately. See https://github.com/flutter/flutter/issues/55827#issuecomment-623779910 for a workaround.

**Comment by simolus3** [comment]
Update on that `libsqlite3.so` not found thing. I tried to add a workaround to the `moor_ffi` package itself. You can try it out by adding this to your pubspec:

```yaml
dependency_overrides:
  moor_ffi:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: moor_ffi
```

**Comment by claudneysessa** [comment]
Isto vai para o padrão logo?

???

dependency_overrides:
  moor_ffi:
    git:
      url: https://github.com/simolus3/moor.git
      ref: develop
      path: moor_ffi

**Comment by simolus3** [comment]
> (From Google Translate) Is this going to default soon?

If that fixes the problem with the latest Flutter stable, I can release that version to pub. I just want to be sure it doesn't break anything else.
