### ISSUE TITLE
Can't open a transaction within a transaction during database open

### ISSUE THREAD

**Issue by Sorunome** [simolus3/moor#679]
Still trying to debug push, it appears that occasionally we get the error that we can't open a transaction within a transaction when trying to open the database.

```
I/flutter ( 7758): error DatabaseException(error code 1: cannot start a transaction within a transaction) sql 'BEGIN EXCLUSIVE' args []} during open, closing...
I/flutter ( 7758): [Push] Error while processing notification: DatabaseException(error code 1: cannot start a transaction within a transaction) sql 'BEGIN EXCLUSIVE' args []}
I/flutter ( 7758): #0      SqfliteSqlCipherDatabaseFactoryImpl.wrapDatabaseException (package:sqflite_sqlcipher/src/factory_sql_cipher_impl.dart:44:9)
I/flutter ( 7758): <asynchronous suspension>
I/flutter ( 7758): #1      SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite_common/src/database_mixin.dart:208:15)
I/flutter ( 7758): #2      SqfliteDatabaseMixin.invokeExecute (package:sqflite_common/src/database_mixin.dart:370:12)
I/flutter ( 7758): #3      SqfliteDatabaseMixin.txnExecute.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:362:14)
I/flutter ( 7758): #4      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:312:26)
I/flutter ( 7758): #5      SqfliteDatabaseMixin.txnWriteSynchronized (package:sqflite_common/src/database_mixin.dart:345:7)
I/flutter ( 7758): #6      SqfliteDatabaseMixin.txnExecute (package:sqflite_common/src/database_mixin.dart:351:12)
I/flutter ( 7758): #7      SqfliteDatabaseMixin.beginTransaction (package:sqflite_common/src/database_mixin.dart:446:15)
I/flutter ( 7758): #8      SqfliteDatabaseMixin._runTransaction (package:sqflite_common/src/database_mixin.dart:471:19)
I/flutter ( 7758): #9      SqfliteDatabaseMixin.transaction.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:492:14)
I/flutter ( 7758): #10     SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:312:26)
I/flutter ( 7758): #11     SqfliteDatabaseMixin.txnWriteSynchronized (package:sqflite_common/src/database_mixin.dart:345:7)
I/flutter ( 7758): #12     SqfliteDatabaseMixin.transaction (package:sqflite_common/src/database_mixin.dart:491:12)
I/flutter ( 7758): #13     SqfliteDatabaseMixin.doOpen (package:sqflite_common/src/database_mixin.dart:692:15)
I/flutter ( 7758): <asynchronous suspension>
I/flutter ( 7758): #14     SqfliteDatabaseOpenHelper.openDatabase (package:sqflite_common/src/database.dart:46:22)
I/flutter ( 7758): #15     SqfliteDatabaseFactoryMixin.openDatabase.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:104:43)
I/flutter ( 7758): <asynchronous suspension>
I/flutter ( 7758): #16     SqfliteDatabaseFactoryMixin.openDatabase.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart)
I/flutter ( 7758): #17     ReentrantLock.synchronized.<anonymous closure>.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:33:24)
I/flutter ( 7758): #18     _rootRun (dart:async/zone.dart:1190:13)
I/flutter ( 7758): #19     _CustomZone.run (dart:async/zone.dart:1093:19)
I/flutter ( 7758): #20     _runZoned (dart:async/zone.dart:1630:10)
I/flutter ( 7758): #21     runZoned (dart:async/zone.dart:1550:10)
I/flutter ( 7758): #22     ReentrantLock.synchronized.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:32:24)
I/flutter ( 7758): #23     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:26)
I/flutter ( 7758): #24     ReentrantLock.synchronized (package:synchronized/src/reentrant_lock.dart:28:17)
I/flutter ( 7758): #25     SqfliteDatabaseFactoryMixin.openDatabase (package:sqflite_common/src/factory_mixin.dart:71:17)
I/flutter ( 7758): #26     openDatabase (package:sqflite_sqlcipher/sqflite.dart:145:26)
I/flutter ( 7758): #27     _SqfliteDelegate.open (package:encrypted_moor/encrypted_moor.dart:66:16)
I/flutter ( 7758): #28     DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:244:22)
I/flutter ( 7758): <asynchronous suspension>
I/flutter ( 7758): #29     DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart)
I/flutter ( 7758): #30     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:26)
I/flutter ( 7758): #31     DelegatedDatabase.ensureOpen (package:moor/src/runtime/executor/helpers/engines.dart:238:25)
I/flutter ( 7758): #32     QueryEngine.doWhenOpened (package:moor/src/runtime/api/query_engine.dart:98:21)
I/flutter ( 7758): #33     CustomSelectStatement._executeWithMappedArgs (package:moor/src/runtime/query_builder/statements/select/custom_select.dart:53:19)
I/flutter ( 7758): #34     CustomSelectStatement.get (package:moor/src/runtime/query_builder/statements/select/custom_select.dart:37:12)
I/flutter ( 7758): #35     _MappedSelectable.get (package:moor/src/runtime/query_builder/statements/query.dart:143:20)
I/flutter ( 7758): #36     Database.getClient (package:famedlysdk/src/database/database.dart:75:41)
I/flutter ( 7758): #37     PushNotificationPlugin._processNotification (package:famedly/models/plugins/push_notification_plugin.dart:245:40)
I/flutter ( 7758): <asynchronous suspension>
I/flutter ( 7758): #38     PushNotificationPlugin._onBackgroundMessage (package:famedly/models/plugins/push_notification_plugin.dart:177:13)
I/flutter ( 7758): #39     _fcmSetupBackgroundChannel.<anonymous closure> (package:firebase_messaging/firebase_messaging.dart:38:30)
I/flutter ( 7758): #40     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:430:55)
I/flutter ( 7758): #41     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:383:33)
I/flutter ( 7758): #42     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:265:33)
I/flutter ( 7758): #43     _invoke3.<anonymous closure> (dart:ui/hooks.dart:296:15)
I/flutter ( 7758): #44     _rootRun (dart:async/zone.dart:1190:13)
I/flutter ( 7758): #45     _CustomZone.run (dart:async/zone.dart:1093:19)
I/flutter ( 7758): #46     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
I/flutter ( 7758): #47     _invoke3 (dart:ui/hooks.dart:295:10)
I/flutter ( 7758): #48     _dispatchPlatformMessage (dart:ui/hooks.dart:170:5)
I/flutter
```

This is odd, as we cache the database so that only once instance is used at all, so basically like

```
Database _db;
Database getDb() {
  _db ??= openDatabase();
  return _db;
```

So only once instance should exist at all, except accross isolates. But these instances accross isolate shouldn't be able to see each other, and thus this error shouldn't happen. Do you have any hint / idea what may be going on?

**Comment by simolus3** [comment]
> But these instances accross isolate shouldn't be able to see each other, and thus this error shouldn't happen

Since platform channels work on different isolates now, maybe the problem is on the native platform side? If the underlying sqflite implementation isn't threadsafe, the different isolates might cause a conflict.
I'm not sure if that's really the cause, but that would be pretty bad, since there isn't really a workaround that could be done in Dart. You might be able to setup a multi-isolate lock through some hacky communication, but that sounds tedious and fragile.

You can't use `moor_ffi` because you need encryption, right? I could help you setup `moor_ffi` with `SQLCipher` if you're interested in trying it. Since there is no platform implementation, it hopefully doesn't have that problem.

**Comment by davidmartos96** [comment]
@Sorunome I think this is related https://github.com/davidmartos96/sqflite_sqlcipher/issues/15

It seems to be a difference between the Sqflite and SQLCipher Android libraries. I don't really know if it could even be "fixed", since the `sqflite_sqlcipher` library calls the Android library directly.

**Comment by Sorunome** [comment]
We are indeed using `sqflite_sqlcipher`. With the issue @davidmartos96 linked it sounds like that one isn't threadsafe, if you use transactions, which would explain *sooo* much, the random nature of this, and the random other errors that are appearing.

It would be really great if you could help us set up `moor_ffi` with `SQLCipher`!

Also, just wanted to point out that support from you has been *amazing* so far, quick and helpful replies, etc, really, it has been a really great experience asking for help here ^-^

**Comment by simolus3** [comment]
>Also, just wanted to point out that support from you has been _amazing_ so far

Thanks! :blush: 

I've found a way to use `moor_ffi` with `SQLCipher`. First, change `android/app/build.gradle` and add the following dependency:

```gradle
implementation "net.zetetic:android-database-sqlcipher:4.4.0"
```

On iOS, you can add the [SQLCipher](https://cocoapods.org/pods/SQLCipher) pod.

Next, you'll have to drop this file somewhere in your project https://gist.github.com/simolus3/5097bbd80ce59f9b957961fe851fd95a#file-cipher_db-dart It contains logic to use `libsqlcipher.so` instead of the regular `libsqlite3.so`. It also contains the `EncryptedVmDatabase` database implementation, which acts just like a regular `VmDatabase`, except that it sets the `key` pragma before opening the database.

You can follow [this article](https://moor.simonbinder.eu/docs/other-engines/vm/#migrating-from-moor-flutter-to-moor-ffi) on how to switch from an `sqflite` based moor to `moor_ffi`. Just replace `VmDatabase` with `EncryptedVmDatabase`.

I want to modularize `moor_ffi` soon, which would allow me to add a proper package that does all of this, so that no custom setup is necessary.

**Comment by Sorunome** [comment]
Thanks a lot! Should the databases be compatible, or would we have to implement migrations to migrate existing users over to this?

**Comment by simolus3** [comment]
If you use `getDatabasesPath` from `sqflite` to construct the right location, no migration should be necessary.

**Comment by Sorunome** [comment]
Heya, I forgot to reply here, sorry! Switching over to `moor_ffi` with sqlcipher seems to have fixed the issue! As `moor_ffi` is blocking we also had to put it into an isolate, but that is working fine now. Thanks a lot for all the help and sorry again for the late reply!

**Comment by simolus3** [comment]
No problem, glad to hear that you were able to fix this issue!
