### ISSUE TITLE
Import table definition dart in moor files 

### ISSUE THREAD

**Issue by akashgurava** [simolus3/moor#680]
I am trying to define a table in dart file and use that table in moor files for querying. So in the moor file I imported the dart file like docs suggested. Then in database.dart, I did

```
@UseMoor(
  tables: [Transactions],
  include: {'./schema/transactions.moor'},
)
```
But this is creating duplicates in database.g.dart for Transaction like below. 

![image](https://user-images.githubusercontent.com/13036662/86501487-d72d7700-bdb6-11ea-8a95-cc9b46fd14f4.png)

If I do this in database.dart
```
@UseMoor(
  include: {'./schema/transactions.moor'},
)
```

Then I get missing implementation error.
![image](https://user-images.githubusercontent.com/13036662/86501531-3ab7a480-bdb7-11ea-9824-d0a05502924b.png)

Also is there way I can use UUID in moor file? I am mainly creating table in dart because I cannot figure out how to use .clientDefault() in moor file?

**Comment by simolus3** [comment]
Importing a Dart file in a moor file to use its tables should work. 

Unfortunately the generator can't add import statements, so you'll need to add them yourself. You have to import the file declaring `Transactions` into the Dart file that declares the database.

**Comment by akashgurava** [comment]
I am importing the transactions table in database generation file and also in moor file where I am writing queries for that table. But that is causing the first error. I am getting Duplicates of Transaction And TransactionCompanion(from first screenshot).

**Comment by simolus3** [comment]
Does it work if you keep both imports, but remove the `tables: [Transactions]` field from `@UseMoor`?

**Comment by akashgurava** [comment]
That worked. Thanks for the help and an amazing library.
