### ISSUE TITLE
Is there a way to get database file name?

### ISSUE THREAD

**Issue by wonpyohong** [simolus3/moor#681]
I am using MoorIsolate and created the database from the path (account id)

```
void _startBackground(_IsolateStartRequest request) {
  final executor = VmDatabase(File(request.accountIdPath));            // accountIdPath
  final moorIsolate = MoorIsolate.inCurrent(
    () => DatabaseConnection.fromExecutor(executor),
  );
..
```

I need to check whether currently opened database is really what I want.
```
if (openedDatabaseFileName != '${loginAccountId}.db') {
  reinitializeDatabase(loginAccountId);
}
```

Can I get the accountIdPath using GeneratedDatabase class or something other?

**Comment by simolus3** [comment]
There's no general solution for this since some executors don't operate on a file (e.g. web or `VmDatabase.memory()`). If you need to access the file name in your database class, I'd add it to the constructor:

```dart
@UseMoor
class Database extends _$Database {
  Database(File file, DatabaseConnection connection): super.connect(connection) {
    // Check if the file is as expected...
  }
}
```
