### ISSUE TITLE
[Question] type cast error in TypeConverter

### ISSUE THREAD

**Issue by lucasnsa** [simolus3/moor#682]
Hi! I get an error when using a TypeConverter

``` Unhandled Exception: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Raca' in type cast ```

in this line

```
Animal.fromJson(i).copyWith(id: _animal.id)
```

My TyperConverter and model

```
@j.JsonSerializable()
class Raca {
  String abreviacao;
  String nome;
  String origem;

  Raca(this.abreviacao, this.nome, this.origem);

  factory Raca.fromJson(Map<String, dynamic> json) =>
      _$RacaFromJson(json);

  Map<String, dynamic> toJson() => _$RacaToJson(this);
}

class RacaConverter extends TypeConverter<Raca, String> {
  const RacaConverter();
  @override
  Raca mapToDart(String fromDb) {
    if (fromDb == null) {
      return null;
    }
    return Raca.fromJson(json.decode(fromDb) as Map<String, dynamic>);
  }

  @override
  String mapToSql(Raca value) {
    if (value == null) {
      return null;
    }

    return json.encode(value.toJson());
  }
} 
```

My table class:

```  TextColumn get raca => text().map(const RacaConverter()).nullable()(); ```

*Raca is a nested json

**Comment by simolus3** [comment]
Is `Animal` the data class of your table?

In general, type converters only apply to the SQL <-> Dart mapping, they don't have any effect on `fromJson` or `toJson`. If you want to transform those as well, you'd have to write a custom [`ValueSerializer`](https://pub.dev/documentation/moor/latest/moor/ValueSerializer-class.html).

**Comment by lucasnsa** [comment]
> Is `Animal` the data class of your table?
> 
> In general, type converters only apply to the SQL <-> Dart mapping, they don't have any effect on `fromJson` or `toJson`. If you want to transform those as well, you'd have to write a custom [`ValueSerializer`](https://pub.dev/documentation/moor/latest/moor/ValueSerializer-class.html).

Correct! Thanks!

It is my first time with the plugin.

Moor is wonderful! Congratulations for the work!
