### ISSUE TITLE
Batch insert using Companion mangles int/real values in release builds (moor_ffi)

### ISSUE THREAD

**Issue by phil-blais** [simolus3/moor#683]
Several queries seem to behave strangely in release builds. Everything is **working fine in debug** builds.

```
List<Insertable<Item>> insertables = [];
items.forEach((item) {
  insertables.add(ItemsCompanion.insert(
    id: Value(int.tryParse(item['id'])),
    name: item['name'],
    description: item['description']
  ));
});
```

Printing that companion looks like:
```
ItemsCompanion(id: Value(1), name: Value(Sample Item), description: Value(This is a test))
```

But once inserted then queried that _id_ would be ```4294967296```.

Even if I let the debug mode generate and seed the data, then run a release using the same data, the queries mostly return ```null```.

Am I missing something here?

```
Flutter 1.17.5 • channel stable
Dart 2.8.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.11
  path: ^1.6.4
  moor: ^3.2.0
  moor_ffi: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  moor_generator: ^3.2.0

**Comment by simolus3** [comment]
Are you building on Windows? This is an annoying bug in the Dart compiler unfortunately (see https://github.com/flutter/flutter/issues/54948).

As a workaround, you could try
- building on the `master` channel of Flutter
- building on another OS (Linux Subsystem for Windows should work)

I'll pin this issue for better visibility, but there's nothing moor can do about this unfortunately.
