### ISSUE TITLE
Sum/product in order by expression

### ISSUE THREAD

**Issue by runeksvendsen** [simolus3/moor#684]
I'm trying to retrieve a list of objects (that contain a GPS location) from a database sorted by their distance to some other GPS location. According to [this answer on Stackoverflow](https://stackoverflow.com/a/32365251/700597), this can be achieved using the following query:

```sql
SELECT * AS distance FROM items ORDER BY ((location_lat - lat)*(location_lat - lat)) + ((location_lng - lng)*(location_lng - lng)) ASC
```

where `lat` and `lng` are the componenets of the GPS coordinate in a given database row, and `location_lat` and `location_lng` are the components of the GPS coordinate to which we wish to calculate the distance.

I've been Googling extensively on how to achieve this using moor, but -- as far as I can see -- moor does not support arithmetic operations in the `ORDER BY` expression.

Is this either possible to achieve or planned for the future?

**Comment by simolus3** [comment]
This should work:

```dart
Future<List<Item>> getItems(double lat, double long) {
  final query = select(item)..orderBy([
    (item) {
        final deltaLat = Variable(lat) - item.locationLat;
        final deltaLong = Variable(long) - item.locationLong;
      
        return OrderingTerm.asc(deltaLat * deltaLat + deltaLong * deltaLong);
      }
  ]);
  return query.get();
}
```

**Comment by runeksvendsen** [comment]
Hi Simon,

Thank you for the quick and useful reply.

Just to clarify: did I miss some part of the documentation that explains how to write this type of query?

**Comment by simolus3** [comment]
I think the page on [expressions in Dart](https://moor.simonbinder.eu/docs/getting-started/expressions/) covers this. But maybe the documentation should point out that complex expressions can be used in an order by?

**Comment by runeksvendsen** [comment]
Indeed that page explains everything I wanted to know about expressions.

It would have been helpful for me if the [Writing queries/Ordering](https://moor.simonbinder.eu/docs/getting-started/writing_queries/#ordering) section were to expand on the `expression` argument to `OrderingTerm` simply by **(1)** stating that this can contain arbitrary expressions, and **(2)** linking to the [Expressions](https://moor.simonbinder.eu/docs/getting-started/expressions/) section (for a detailed explanation on expressions).  In other words, when searching for the documentation on `orderBy`, I was missing the fact that the form of the `expression` argument to `OrderingTerm` is documented in the [Expressions](https://moor.simonbinder.eu/docs/getting-started/expressions/) section.

**Comment by simolus3** [comment]
Thanks for the feedback on the documentation! I've added a link with 6f0fa9cde1e489669aa6817f9665d33b6d2a9992 (it will be published with the next moor release).
