### ISSUE TITLE
encrypted_moor is not working with moor 3?

### ISSUE THREAD

**Issue by andreineacsu** [simolus3/moor#688]

**Comment by simolus3** [comment]
`encrypted_moor` works with the latest moor version. What problem are you seeing?

**Comment by andreineacsu** [comment]
The error is get is: 
_Because every version of encrypted_moor from git depends on moor ^2.0.0 and ctc_wallet depends on moor ^3.2.0, encrypted_moor from git is forbidden.
So, because ctc_wallet depends on encrypted_moor from git, version solving failed.
pub get failed (1; So, because ctc_wallet depends on encrypted_moor from git, version solving failed.)_

Screenshot attached below. 

![Screenshot 2020-07-09 at 17 59 31](https://user-images.githubusercontent.com/3153007/87056318-1d973180-c20e-11ea-9c28-c56bd9ac2560.png)

**Comment by simolus3** [comment]
The package supports on the latest moor version though: https://github.com/simolus3/moor/blob/ba987b57b1a324fd0594037fe60c6a81ab2db8a9/extras/encryption/pubspec.yaml#L9-L11

Maybe you need to convince pub to fetch the latest `encrypted_moor`. `flutter pub upgrade` might do the trick?
