### ISSUE TITLE
Web database size limit

### ISSUE THREAD

**Issue by aaditya-brt** [simolus3/moor#689]
Is there any database size limitation for implementing moor database on web ?

**Comment by simolus3** [comment]
The default `WebDatabase` writes to local storage internally, which browsers typically limit to around 10 MB. You can also use `MoorWebStorage.indexedDb` to use `IndexedDB` as a storage implementation, which has more lenient limits (typically around 50 MB). But both limits can be different across browsers.

**Comment by aaditya-brt** [comment]
Is there any way I can calculate the size of existing database?

**Comment by simolus3** [comment]
Moor doesn't have a builtin api for this, no. Does [StoreManager.estimate](https://developer.mozilla.org/en-US/docs/Web/API/StorageManager/estimate) cover your use case?

**Comment by aaditya-brt** [comment]
I will check if this work,but this is only for Mozilla right?

**Comment by simolus3** [comment]
From the compatibility chart at the bottom, it seems like all major browsers should support that api now.
