### ISSUE TITLE
Phasing out the moor_ffi package

### ISSUE THREAD

**Issue by simolus3** [simolus3/moor#691]
TL,DR: I want to split `moor_ffi` into the moor-independent [sqlite3 package](https://pub.dev/packages/sqlite3) (done!) and a new `package:moor/ffi.dart` library. There will be no breaking changes for existing moor apps.

The main motivation for making `moor_ffi` an own package was that `dart:ffi` was unstable during the initial releases. This has gotten much better, so we can inline `moor_ffi` into the main moor package. The new package setup will also allow `moor_ffi` to use SQLCipher internally.

## Migrating moor usages of moor_ffi

The migration in moor is still ongoing, but I expect that users will only have to make two changes:
- change imports of `package:moor_ffi/moor_ffi.dart`  to the simpler `package:moor/ffi.dart`
- add a dependency on `sqlite3_flutter_libs` if they're using Flutter

`moor_ffi` will then export the new apis from the core `moor` package and be marked as discontinued, so that there's no breaking interruption for existing moor users at all.

## Migrating non-moor usages of moor_ffi

While the new `sqlite3` package is more complete than `moor_ffi`, I aimed for some degree of backwards compatibility.

- `package:moor_ffi/open_helper.dart` can be replaced with `package:sqlite3/open.dart`, no further changes are required.
- `package:moor_ffi/database.dart` is now called `package:sqlite3/sqlite3.dart`, but there are some changes
  - databases must now be opened through the `sqlite3` field instead of a factory
  - the `close` method on `Database` and `PreparedStatement` has been renamed to `dispose`, but otherwise behaves identically
  - `getLastInsertId` is now a getter (`lastInsertRowId`)
  - `userVersion` is now a getter and setter as well

cc @alextekartik since this could be relevant for the `sqflite_common_ffi` package, I'll open a PR to migrate. @sq6jnx, you might want to migrate from `moor_ffi` to `sqlite3` as well.

**Comment by sq6jnx** [comment]
@simolus3 thanks for mentioning me. I am still very new to dart ecosystem, but these changes look pretty straightforward.
