### ISSUE TITLE
Select NULL leftOuterJoin table

### ISSUE THREAD

**Issue by godzeit** [simolus3/moor#693]
I have a trouble of selection data from two tables by using leftOuterJoin. The problem is that if the joining table have no row with requested ID, it is not returning main table's row too. But, there it should be noted, that I also have WHERE statement related to joining table and if I will remove it, I will get data even if the joining table is have no such rowId. 

Here is my request code:

```
final max = tMessages.updateAt.secondsSinceEpoch.max();

    final query = select(tSubscriptions).join([
      leftOuterJoin(
        tChannels,
        tChannels.id.equalsExp(tSubscriptions.channelId),
      ),
      leftOuterJoin(
        tMessages,
        tMessages.channelId.equalsExp(tSubscriptions.channelId),
      ),
    ])
      ..addColumns([max])
      ..where(tMessages.isDeleted.equals(false)) // if remove this, I will get data even with joining table null
      ..where(tSubscriptions.isBlocked.equals(false))
      ..orderBy([OrderingTerm(expression: max, mode: OrderingMode.desc)])
      ..groupBy([tSubscriptions.id]);
```

**Comment by simolus3** [comment]
The issue is that, when there's no matching `tMessages` table, `tMessages.isDeleted` will be null, so the first where clause fails.

It sounds like this is what you need:

```dart
      ..where(isNull(tMessages.isDeleted) | tMessages.isDeleted.equals(false))
```

**Comment by godzeit** [comment]
Thank you! You saved my project! By the way, I believe it will be really good idea to add this in moor's documentation
