### ISSUE TITLE
Conccurrent querries don't return results

### ISSUE THREAD

**Issue by TheOnlyNurse** [simolus3/moor#694]
I'm not sure if this is a bug or I'm just simply doing something wrong.
Either way, here's the scenario: I have a grid of images (250+) that need to be fetched from an internet source. Each card within the grid pings a "cache database" for an image.
Here's the query code
```dart
    final query = select(imageFiles);
    query.where((tbl) {
      return tbl.artId.equals(artId) & tbl.type.equals(type.toString()); // the columns that need to match
    });
    if (artId == 'al-308') print('began'); // prints "began"
    final art = await query.getSingle();
    if (artId == 'al-308') print('finished'); // doesn't print
    if (art == null) {
      return _download(artId, type); // downloads the image
    } else {
      return File(art.path); // returns a file
    }
```
The above code works for most images. Some however return no results, seemingly stuck (the artId is for one that doesn't work for one particular run). The images are always random if I clear the database so it makes me think it might be an inserting issue. Here's how I'm inserting:
```dart
  Future<File> _download(String artId, ImageType type) async {
    final response = await _serverRequest(artId, type);
    if (response.hasNoData) return null;
    final file = await _bytesToFile('$artId-$type', response.bytes);

    await _addImage(ImageFilesCompanion(
      artId: Value(artId),
      type: Value(type.toString()),
      path: Value(file.path),
      size: Value(file.statSync().size),
    ));
    checkSize();
    return file;
  }

  Future<int> _addImage(ImageFilesCompanion entry) async {
    return into(imageFiles).insert(entry);
  }
```
Yet I don't think it's inserting that is the problem. Here's what the log says:
```
Sent SELECT * FROM image_files WHERE art_id = ? AND type = ?; with args [al-308, ImageType.lowDef]
```
I've tried putting mutex's on both reading and writing queries and they haven't helped. I'm at a loss. Any help would be greatly appreciated!

**Comment by simolus3** [comment]
Moor should apply some mutex internally as well, so I don't think that does anything. Maybe there is some kind of deadlock internally, but that seems unlikely.

Do you have something for me to reproduce this? Does it happen if you just do a lot of selects and inserts concurrently?

**Comment by TheOnlyNurse** [comment]
Thanks for the reply Simolus. I spent the entire day today trying to recreate the bug in a different test project and I've come up empty handed. The database loads concurrently without issue from both internet (different source) and local sources.
Anyway, I'm closing this issue, sorry for bringing up a non-issue!

**Comment by Mike278** [comment]
Is it possible that there was more than one row with artId 'al-308'? 

`await query.getSingle();` throws an exception if there’s more than one row returned - that could explain your “// doesn’t print” comment

**Comment by TheOnlyNurse** [comment]
Thanks for the reply Mike, unfortunately that doesn't seem to be the issue. The artId is only assigned once and my problem is that no exception or diagnostic message is thrown when this occurs. It just doesn't complete and gets "stuck"
