### ISSUE TITLE
[Question] How to search ignoring column diacritis?

### ISSUE THREAD

**Issue by mrverdant13** [simolus3/moor#704]
I am using the following `where` statement for a simple search:

```
..where(
  drinks.name.like('%$name%'),
)
```

Considering a table like this one:

| id | name      |
|----|-----------|
| 1  | cCafe     |
| 2  | Café      |
| 3  | caféeee   |
| 4  | tea       |
| 3  | coffee    |
| 2  | jugo      |
| 3  | water     |
| 2  | Café      |
| 3  | caféeee   |
| 4  | cafeeeeee |

If a look for the `cafe` string, the **current result** is as follows:

| id | name      |
|----|-----------|
| 1  | cCafe     |
| 4  | cafeeeeee |

The **expected result** is this one:

| id | name      |
|----|-----------|
| 1  | cCafe     |
| 2  | Café      |
| 3  | caféeee   |
| 2  | Café      |
| 3  | caféeee   |
| 4  | cafeeeeee |

I already tried using `collate` but the result is the same since their options are limited.

**Comment by simolus3** [comment]
Unfortunately, sqlite3's support for non-ascii chars is quite limited and there's not much moor can do about that.

I think your best approach would be to add a column like `normalized_name` where you remove diacritics using Dart. Then you can search over that column and still get the right name back.

**Comment by mrverdant13** [comment]
I had already done that by I was wondering if there was a more suitable way to do it.
Thanks for the reply!
