### ISSUE TITLE
how to move functions that return .get() or .watch() into separate files

### ISSUE THREAD

**Issue by matthewkooshad** [simolus3/moor#706]
similar to https://github.com/simolus3/moor/issues/241: 
can you give an example of how to have the functions that return .get() or .watch() in another file? i would like to have them in the same file with the table definition. 
my database.dart looks similarly as this currently:

...
part 'database.g.dart';

@UseMoor(tables: [Users, Books])
class Database extends _$Database {
  Database() : super(FlutterQueryExecutor.inDatabaseFolder(path: 'db.sqlite', logStatements: true));

 //various functions that return .get() or .watch() -- can i move these out to the same script where i've got my table class? if so, what would that file look like?
...
}
thanks

**Comment by matthewkooshad** [comment]
@kuhnroyal the todos is not known in the TodosDao class file for me. do i need to have the an import for the database.g.dart file? if i reference todos in a query in my database.dart, then it seems to be referencing the database.g.dart file. 

also, i'm getting a complaint about the _$TodosDaoMixin part. i don't know what i'm missing on that part.

**Comment by kuhnroyal** [comment]
The critical parts are the 2 things at the top of the DAO file.

```
part 'todos_dao.g.dart';

@UseDao(tables: [Todos])
```

You also need to generate again after every change - the generation will create the `part of` file.
You also need to add `@UseMoor(daos: [TodosDao])` to your database class.

Same for Users, Books, whatever.

**Comment by matthewkooshad** [comment]
thanks, i think i got that resolved. i'm going to test it out.

**Comment by matthewkooshad** [comment]
i think i'm having an issue with the g.dart file getting populated correctly.
for the class TodosDao file, should it be named todosDao.dart? it seems that the todos_dao.g.dart relates to the name of it.

also, should i manually create the todos_dao.g.dart file for the first time or does the build_runner take care of that?

**Comment by matthewkooshad** [comment]
@kuhnroyal  here's the complete content of the todosDao.g.dart, which appears the filename q is no issue... but it is not showing my .get and .watch methods there.

// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'todosDao.dart';

// **************************************************************************
// DaoGenerator
// **************************************************************************

mixin _$TodosDaoMixin on DatabaseAccessor<Database> {
  $TodosTable get todos => attachedDatabase.todos;
}

**Comment by matthewkooshad** [comment]
i think if i resolve todosDao.g.dart having what it should have, then it will resolve the places where i use my Database instance dbProvider's inability to locate these methods i've moved to the TodosDao class.

**Comment by kuhnroyal** [comment]
The build_runner will create and also remove the files if you run it with the `clean` command.

> //various functions that return .get() or .watch() -- can i move these out to the same script where i've got my table class? if so, what would that file look like?

I don't think there are any default functions generated in the Database or DAO. You can now add/copy/move them from your Database class to the DAO and use the generated `todos` table getter in these functions.

**Comment by matthewkooshad** [comment]
@kuhnroyal thanks for helping. i did move many of the functions into the Dao class, but they don't seem to be getting put into the generated class, and they aren't accessible from the dbProvider instance.

**Comment by matthewkooshad** [comment]
the "todos" btw are not having any syntax errors and they are referencing the "todos" from the Dao generated file.

**Comment by kuhnroyal** [comment]
They don't need to be in the generated mixin since they are in your DAO class.
You can access the DAO from your dbProvider via the db instance.

Something like `dbProvider.db.todoDao.myCustonWatch()`.

**Comment by matthewkooshad** [comment]
ah, that was my problem. i didn't know that i need to ref the Dao class on the dbProvider instance. that seems to make it happy.

i tested it, and it works as expected. thanks again @kuhnroyal !
