### ISSUE TITLE
Is there a way to update the database schema over the air?

### ISSUE THREAD

**Issue by GP4cK** [simolus3/moor#708]
Let's say we have an app in production that requires syncing data with a server. The synchronisation is basically a request where
1. the app sends the changes that the user made locally
2. the server responds with the changes made by other users

Now we need to add new features. So we will start by adding columns or creating tables on the backend (let's not consider altering or dropping a column for simplicity's sake, only adding). The server will now include additional info in its response but the app won't know how to handle it until the user updates it in the store.
Hence the idea of including the migrations to be executed in the server's response.

Will it be an issue if the database file has extra columns / tables other than the ones included in the moor files?

**Comment by simolus3** [comment]
> Will it be an issue if the database file has extra columns / tables other than the ones included in the moor files?

I don't see a problem as long as those columns are nullable or have default values. They would simply be invisible in that case.
Are you generating `INSERT` statements yourself though? Obviously moor-generated classes wouldn't be able to represent the new columns.

**Comment by GP4cK** [comment]
>Are you generating INSERT statements yourself though?
I guess we would have to, yes.
Cool then I'll close this
