### ISSUE TITLE
[Question] Delete from joined table not supported?

### ISSUE THREAD

**Issue by doppio** [simolus3/moor#709]
I'm trying to perform a join between two tables, then delete records in one of those tables that meet criteria in the join statement. Here's what the query in my Moor file looks like:

```
DELETE tableA FROM tableA
INNER JOIN tableB ON tableA.someColumn = tableB.someColumn
WHERE tableB.someOtherColumn = :someParam;
```

The code generation results in an error like this:
```
line 49, column 5: Expected a semicolon after the statement ended
   ╷
49 │     INNER JOIN tableB ON tableA.someColumn = tableB.someColumn
   │     ^^^^^
   ╵
```

I've tried a couple other variants of that first line, such as `DELETE a FROM tableA AS a` and `DELETE a FROM tableA a`.

Is this not supported, or have I formatted my query incorrectly?

**Comment by simolus3** [comment]
I don't think that `DELETE` statements can have joins on them in sqlite, at least they're not included in the [syntax diagram](https://sqlite.org/lang_delete.html).

You could rewrite your query with an `EXISTS` clause to resolve this:

```sql
DELETE FROM tableA
  WHERE EXISTS(
    SELECT * FROM tableB 
      WHERE tableA.someColumn = tableB.someColumn AND tableB.someOtherColumn = :someParam
  );

```

**Comment by doppio** [comment]
Ah-hah! That should work perfectly. Thanks! :)
