### ISSUE TITLE
Select where value does not exist

### ISSUE THREAD

**Issue by cardozaj** [simolus3/moor#710]
I have a one to many relationship with two tables. A table of times, and a table of availability (by month).

```
Item table:
string uid;
string name;
```

```
Availability table:
string uid;
int month;
```

One Item can have multiple entries in the Availability table like so:
```
Item:
--------------
| uid | name |
--------------
uid1, itemname1


Availability:
---------------
| uid | month |
---------------
uid1, 3
uid1, 4
uid1, 5
uid1, 6
uid1, 7
```

I'm trying to select all items whose availability does not exist for the next month, which would require - in this case - a where clause with `availability.month = 8` to be null
Here's what I have so far:
```dart
final JoinedSelectStatement<Table, DataClass> join = select(items, distinct: true).join([
      leftOuterJoin(
        availability,
        availability.uid.equalsExp(items.uid),
        useColumns: false,
      ),
    ]);
join.where(
  availability.month.equals(DateTime.now().month) & 
  isNull(availability.month.equals(DateTime.now().month + 1))
);
```

The resulting where clause is
```sql
availability.month = 8 IS NULL
```

I'm getting zero results from this, and I'm not sure why. Any help would be greatly appreciated.

**Comment by simolus3** [comment]
The problem is that `availability.month = 8 IS NULL` applies to the whole result set (so both the `items` table and the `availability` table). What you want is to join the `availability` table for next month and then make sure it's null.

So if you want to select items that are available in this month, but not in the next month, you could do this:

```dart
final currentAvailability = alias('t', availability);
final nextMonthAvailability = alias('n', availability);
final currentMonth = DateTime.now().month;

final join = select(items, distinct: true).join([
  innerJoin(
    currentAvailability,
    currentAvailability.uid.equalsExp(items.uid) & currentAvailability.month.equals(currentMonth),
    useColumns: false,
  ),
  leftOuterJoin(
    nextMonthAvailability,
    nextMonthAvailability.uid.equalsExp(items.uid) & nextMonthAvailability.month.equals(current % 12 + 1),
    useColumns: false,
  ),
]);
join.where(isNull(nextMonthAvailability.uid));
```

If you only want items that aren't available next month (regardless of whether they are available today), you can just remove the `currentAvailability` alias and the first join.

**Comment by cardozaj** [comment]
Just got around to testing your suggestion and it worked great.
Thanks for taking the time to reply, it's much appreciated!

**Comment by simolus3** [comment]
Great to hear that!
