### ISSUE TITLE
Cannot run after downloading

### ISSUE THREAD

**Issue by tenSunFree** [simolus3/moor#715]
The following error message will appear.
![2020-07-18_174610](https://user-images.githubusercontent.com/23090085/87850219-23cd9200-c921-11ea-87da-272d1adccb65.jpg)

The following is my solution.

Delete "database.g.dart" first, then run "flutter packages pub run build_runner build" through "open in terminal" to regenerate "database.g.dart".

Replace "row.id" with "int.parse(row.id)".
![2020-07-18_175053](https://user-images.githubusercontent.com/23090085/87850380-5e83fa00-c922-11ea-948d-06214fc64e7f.jpg)

**Comment by simolus3** [comment]
Thanks for the report! The `int.parse` thing was a generator bug that will be fixed with the next moor version. I also re-ran the generator in the example project to avoid those errors in the future.
