### ISSUE TITLE
DateTime column types documentation misleading

### ISSUE THREAD

**Issue by alexiswbr** [simolus3/moor#718]
The documentation says the DateTime column type is an Unix timestamp in seconds.   
https://moor.simonbinder.eu/docs/getting-started/advanced_dart_tables/#supported-column-types

But when creating a new object, the timestamp must be passed in milliseconds   

```dart
new Product.fromJson({'id':8415, 'created_at': 1600293600}); // product.created_at = 1970-01-19 12:31:33.600
new Product.fromJson({'id':8415, 'created_at': 1600293600000}); // product.created_at = 2020-09-16 22:00:00.000   
```

Maybe we missed some other information in the documentation, but at first we thought it was a bug.

**Comment by kuhnroyal** [comment]
Moor stores DateTime as secondsSinceEpoch for sqlite reasons, but that is not valid JSON. JSON always needs millisecondsSinceEpoch.
You will lose the millisecond precision or you need to build some custom type adapter.

**Comment by simolus3** [comment]
As @kuhnroyal said, the SQL-specific mapping doesn't affect JSON serialization. I agree that the documentation should point this out more prominently, so I added it below the table listing the supported column types.

**Comment by alexiswbr** [comment]
Oh right, thanks for pointing this out
