### ISSUE TITLE
Query result is sometimes never resolved using MoorIsolate

### ISSUE THREAD

**Issue by MartinHlavna** [simolus3/moor#722]
Hello, I have found interesting behavior using MoorIsolate, which manifests itself randomly through application.

# Our setup and some background

* Main "UI" thread, which is spawned by flutter (F)
* Background thread which is spawned by Android Work Manager via WorkManager plugin (B) - which handles synchronization with server
* MoorIsolate spawned from F, which talks to Sqlite (M) - this is mostly to ensure that UI is smooth and is not blocked while there are transactions being committed.
* When B is spawned (usually every 15min, but end user can change the settings or disable it), it detects that F is running (viac SendPort, ReceivePort communication) and delegates synchronization on F Isolate so we can indicate synchronization progress onscreen. 
* When user does some changes that needs to be propagated to server and internet connection is available, synchronization is also started on F.
* The user is usually blocked with CircularProgressIndicator on screen when fetching/writing data  from/to local database.

# The problem
* On random places application hangs showing CircularProgressIndicator which is never closed (setting breakpoint "solves" the issue)
* Future from ```_IsolateQueryExecutor```/```_TransactionIsolateExecutor```runXXX method is never resolved
* No exception is thrown
* On further investigation it looks like it is happening when there is ongoing synchronization on F
* Disabling MoorIsolate solves the problem

# Theory
* ```IsolateCommunication.request``` generates id for each query executed via Isolate and stores instance of ```Completer```  in map for that id whose future is returned
* ```Completer``` is later used to pass response from MoorIsolate
* If 2 requests are done in roughly same time, could ```++``` operation on ```_currentRequestId``` return the same number? I am not sure how "atomic" that operation is in dart but that would explain lost response
* I have tried to wrap id generation using ```synchronized``` package but that did not help.

**Comment by simolus3** [comment]
Thanks for the detailed report!

> If 2 requests are done in roughly same time, could `++` operation on `_currentRequestId` return the same number?

The `MoorIsolate` follows a client-server model, and the `_currentRequestId` is per-client (so each isolate counts up independently). The server also knows about this (e.g. it won't mix up requests from two different clients).

> I have tried to wrap id generation using `synchronized` package but that did not help.

Yeah, the `synchronized` package only affects async operations on a single isolate.


There's a `debugLog` parameter on `MoorIsolate.connect` which prints all the communication happening. Can you enable that on both isolates and post what that prints before the communication hangs?

**Comment by MartinHlavna** [comment]
Sorry for late reply I have forgotten about it. debugLog has actually pointed us to right direction. We have found issue on our side with transaction managment.

Closing the issue
