### ISSUE TITLE
How to get resulting sql statement of a dart query?

### ISSUE THREAD

**Issue by mbabuglia** [simolus3/moor#723]
I know about logStatements parameter in VmDatabase, which logs to the console.
But I need this info in production, I must send a problematic insert to Crashlytics.

Is there a way to build the command in Dart and then ask for the resulting sql?

**Comment by kuhnroyal** [comment]
Interesting question, was wondering how to get more info in production on failed FK constraints myself.

Maybe Moor could provide some Log/ReportHandler that gets all errors and the statements which caused them.
The default handler would be the current sql logging but consumers could implement their own for crashlytics, sentry etc.

**Comment by simolus3** [comment]
If you just need this for the purpose of logging, you could write a delegating `QueryExecutor`. Something like this should do it:

```dart
import 'package:moor/backends.dart';

class LoggingDatabase extends QueryExecutor with _LoggingExecutor {
  @override
  final QueryExecutor inner;

  LoggingDatabase(this.inner);
}

mixin _LoggingExecutor on QueryExecutor {
  QueryExecutor get inner;

  @override
  Future<bool> ensureOpen(QueryExecutorUser user) {
    return inner.ensureOpen(user);
  }

  @override
  TransactionExecutor beginTransaction() => _LoggingTransactionExecutor(inner);

    Future<T> _logFailure<T>(Future<T> inner, String context) {
    return inner.catchError((error, StackTrace trace) {
      // Custom error logging here: Can use the error, trace and context (which includes the statement)

      // rethrow so that the query fails in moor as well
      return Future.error(error, trace);
    });
  }

  @override
  Future<void> runBatched(BatchedStatements statements) {
    return _logFailure(inner.runBatched(statements), 'runBatched($statements)');
  }

  @override
  Future<void> runCustom(String statement, [List args]) {
    return _logFailure(
        inner.runCustom(statement, args), 'runCustom($statement, $args)');
  }

  @override
  Future<int> runDelete(String statement, List args) {
    return _logFailure(
        inner.runDelete(statement, args), 'runDelete($statement, $args)');
  }

  @override
  Future<int> runInsert(String statement, List args) {
    return _logFailure(
        inner.runInsert(statement, args), 'runInsert($statement, $args)');
  }

  @override
  Future<List<Map<String, dynamic>>> runSelect(String statement, List args) {
    return _logFailure(
        inner.runSelect(statement, args), 'runSelect($statement, $args)');
  }

  @override
  Future<int> runUpdate(String statement, List args) {
    return _logFailure(
        inner.runUpdate(statement, args), 'runUpdate($statement, $args)');
  }
}

class _LoggingTransactionExecutor extends TransactionExecutor
    with _LoggingExecutor {
  @override
  final TransactionExecutor inner;

  _LoggingTransactionExecutor(this.inner);

  @override
  Future<void> rollback() {
    return _logFailure(inner.rollback(), 'rollback');
  }

  @override
  Future<void> send() {
    return _logFailure(inner.send(), 'send');
  }
}

```

You could then wrap your `VmDatabase` in a `LoggingDatabase` which can print errors. Unfortunately it's a lot of boilerplate, but it should work.

> Maybe Moor could provide some Log/ReportHandler that gets all errors and the statements which caused them.

Interesting idea, yes. Maybe moor should contain something similar like the `LoggingDatabase` above, except with a generic logging part.

**Comment by mbabuglia** [comment]
This is great Simon!  I will try it, thank you very much for you quick response.

**Comment by kuhnroyal** [comment]
I tried this but the `QueryExecutor get inner;` in `_LoggingExecutor` is not a `TransactionExecutor` , it is the `VmDatabase` which has no methods `rollback/send`.

**Comment by simolus3** [comment]
Oh, right (how did that ever pass static analysis?). You can use

```dart
TransactionExecutor beginTransaction() => _LoggingTransactionExecutor(inner.beginTransaction());
```

**Comment by kuhnroyal** [comment]
Yea that works!

> Oh, right (how did that ever pass static analysis?).

It did not on my end but I use this in analysis_options:
```
analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-dynamic: false
```
From my understanding something like this will become default/required with NNBD so maybe it is good to start using this in the library as well.
