### ISSUE TITLE
Defining SQL and Dart Tables for generation in a single database

### ISSUE THREAD

**Issue by TJMusiitwa** [simolus3/moor#724]
Hello, I am working on a book-keeping application that has a number of features and whilst most of the tables are dart tables that I have already defined, there are a few that are SQL tables that are also defined.
What is the best method to generate tables and all CRUD operations from particularly the SQL defined tables that I would like to include in my dB.

For reference here are two gists showing the db with the dart tables and one of the sql table definitions.

- [Db File](https://gist.github.com/TJMusiitwa/bdec18fdc5d8d3a85029e727cd75b1d9)
- [Trial Balance](https://gist.github.com/TJMusiitwa/bd007773a4e16297a7b31a30edf151d1)

**Comment by simolus3** [comment]
> What is the best method to generate tables and all CRUD operations from particularly the SQL defined tables that I would like to include in my dB.

Have you seen [moor files](https://moor.simonbinder.eu/docs/using-sql/moor_files/)? You can define SQL tables and queries in them to include them in your database. Moor files can also import Dart files to use Dart tables in SQL queries, if that's what you need.

**Comment by TJMusiitwa** [comment]
I did attempt to use said moor files however it leads to a massive error. Please advise

> Running on  moor: ^3.2.0  & moor_ffi: ^0.7.0 and Flutter Version 1.17.5.

**Terminal output**

 [INFO] Generating build script...
[INFO] Generating build script completed, took 640ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 55.0s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 5.7s

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 2ms

[INFO] Running build...
[SEVERE] moor_generator:preparing_builder on lib/database/income_stmt.moor:

Malformed sql: Unexpected character at <FileLocation: 52 unknown source:3:21>, Unexpected character at <FileLocation: 62 
unknown source:3:31>, Unexpected character at <FileLocation: 82 unknown source:5:4>, Unexpected character at <FileLocation: 90 unknown source:5:12>, Unexpected character at <FileLocation: 114 unknown source:6:22>, Unexpected character at <FileLocation: 118 unknown source:6:26>, Unexpected character at <FileLocation: 454 unknown source:25:21>, Unexpected character at <FileLocation: 464 unknown source:25:31>, Unexpected character at <FileLocation: 481 unknown source:26:15>, Unexpected character at <FileLocation: 495 unknown source:26:29>, Unexpected character at <FileLocation: 519 unknown source:27:22>, Unexpected character at <FileLocation: 523 unknown source:27:26>, Unexpected character at <FileLocation: 740 unknown 
source:39:22>, Unexpected character at <FileLocation: 744 unknown source:39:26>, Unexpected character at <FileLocation: 1095 unknown source:58:12>, Unexpected character at <FileLocation: 1099 unknown source:58:16>, Unexpected character at <FileLocation: 1185 unknown source:63:21>, Unexpected character at <FileLocation: 1195 unknown source:63:31>, Unexpected character at <FileLocation: 1212 unknown source:64:15>, Unexpected character at <FileLocation: 1228 unknown source:64:31>, Unexpected character at <FileLocation: 1252 unknown source:65:22>, Unexpected character at <FileLocation: 1256 unknown source:65:26>, Unexpected character at <FileLocation: 1470 unknown source:77:22>, Unexpected character at <FileLocation: 1474 unknown source:77:26>, Unexpected character at <FileLocation: 1604 unknown source:84:21>, Unexpected character at <FileLocation: 1614 unknown source:84:31>, Unexpected character at <FileLocation: 1631 unknown source:85:15>, Unexpected character at <FileLocation: 1648 unknown source:85:32>, Unexpected character at <FileLocation: 1672 unknown source:86:22>, Unexpected character at <FileLocation: 1676 unknown source:86:26>, Unexpected character at <FileLocation: 1892 unknown source:98:22>, Unexpected character at <FileLocation: 1896 unknown source:98:26>, Unexpected character at <FileLocation: 2860 
unknown source:149:21>, Unexpected character at <FileLocation: 2870 unknown source:149:31>, Unexpected character at <FileLocation: 2887 unknown source:150:15>, Unexpected character at <FileLocation: 2898 unknown source:150:26>, Unexpected character at <FileLocation: 2922 unknown source:151:22>, Unexpected character at <FileLocation: 2926 unknown source:151:26> 
[SEVERE] moor_generator:preparing_builder on lib/database/trial_balance.moor:

Malformed sql: Unexpected character at <FileLocation: 49 unknown source:3:21>, Unexpected character at <FileLocation: 59 
unknown source:3:31>, Unexpected character at <FileLocation: 76 unknown source:4:15>, Unexpected character at <FileLocation: 86 unknown source:4:25>, Unexpected character at <FileLocation: 416 unknown source:19:4>, Unexpected character at <FileLocation: 426 unknown source:19:14>, Unexpected character at <FileLocation: 756 unknown source:34:4>, Unexpected character at <FileLocation: 767 unknown source:34:15>, Unexpected character at <FileLocation: 943 unknown source:44:21>, Unexpected character at <FileLocation: 953 unknown source:44:31>, Unexpected character at <FileLocation: 970 unknown source:45:15>, Unexpected character at <FileLocation: 980 unknown source:45:25>, Unexpected character at <FileLocation: 1297 unknown source:59:11>, Unexpected character at <FileLocation: 1307 unknown source:59:21>, Unexpected character at <FileLocation: 1624 unknown source:73:11>, Unexpected character at <FileLocation: 1635 unknown source:73:22>, Unexpected character at 
<FileLocation: 1806 unknown source:83:21>, Unexpected character at <FileLocation: 1816 unknown source:83:31>, Unexpected 
character at <FileLocation: 1833 unknown source:84:15>, Unexpected character at <FileLocation: 1843 unknown source:84:25>, Unexpected character at <FileLocation: 2160 unknown source:98:11>, Unexpected character at <FileLocation: 2170 unknown 
source:98:21>, Unexpected character at <FileLocation: 2487 unknown source:112:11>, Unexpected character at <FileLocation: 2498 unknown source:112:22>, Unexpected character at <FileLocation: 2671 unknown source:123:21>, Unexpected character at <FileLocation: 2681 unknown source:123:31>, Unexpected character at <FileLocation: 2698 unknown source:124:15>, Unexpected character at <FileLocation: 2708 unknown source:124:25>, Unexpected character at <FileLocation: 3025 unknown source:138:11>, Unexpected character at <FileLocation: 3035 unknown source:138:21>, Unexpected character at <FileLocation: 3352 unknown source:152:11>, Unexpected character at <FileLocation: 3363 unknown source:152:22>, Unexpected character at <FileLocation: 3534 unknown source:162:21>, Unexpected character at <FileLocation: 3544 unknown source:162:31>, Unexpected character at <FileLocation: 3561 unknown source:163:15>, Unexpected character at <FileLocation: 3571 unknown source:163:25>, Unexpected character at <FileLocation: 3888 unknown source:177:11>, Unexpected character at <FileLocation: 3898 unknown source:177:21>, Unexpected character at <FileLocation: 4215 unknown source:191:11>, Unexpected character at <FileLocation: 
4226 unknown source:191:22>, Unexpected character at <FileLocation: 4397 unknown source:201:21>, Unexpected character at 
<FileLocation: 4407 unknown source:201:31>, Unexpected character at <FileLocation: 4424 unknown source:202:15>, Unexpected character at <FileLocation: 4434 unknown source:202:25>, Unexpected character at <FileLocation: 4807 unknown source:218:11>, Unexpected character at <FileLocation: 4817 unknown source:218:21>, Unexpected character at <FileLocation: 5190 unknown source:234:11>, Unexpected character at <FileLocation: 5201 unknown source:234:22>, Unexpected character at <FileLocation: 5373 unknown source:244:21>, Unexpected character at <FileLocation: 5383 unknown source:244:31>, Unexpected character at <FileLocation: 5400 unknown source:245:15>, Unexpected character at <FileLocation: 5410 unknown source:245:25>, Unexpected character at <FileLocation: 5783 unknown source:261:11>, Unexpected character at <FileLocation: 5793 unknown source:261:21>, Unexpected character at <FileLocation: 6166 unknown source:277:11>, Unexpected character at <FileLocation: 6177 unknown source:277:22>, Unexpected character at <FileLocation: 6347 unknown source:286:21>, Unexpected character at <FileLocation: 6357 unknown source:286:31>, Unexpected character at <FileLocation: 6374 unknown source:287:15>, Unexpected character at <FileLocation: 6384 unknown source:287:25>, Unexpected character at <FileLocation: 6757 unknown source:303:11>, Unexpected character at <FileLocation: 6767 unknown source:303:21>, Unexpected character at <FileLocation: 7140 unknown source:319:11>, Unexpected character at <FileLocation: 7151 unknown source:319:22>, Unexpected character at <FileLocation: 7321 unknown source:328:21>, Unexpected character at <FileLocation: 7331 unknown source:328:31>, Unexpected character at <FileLocation: 7348 unknown source:329:15>, Unexpected character at <FileLocation: 7358 unknown source:329:25>, Unexpected character at <FileLocation: 7731 unknown source:345:11>, Unexpected character at <FileLocation: 7741 unknown source:345:21>, Unexpected character at <FileLocation: 8114 unknown source:361:11>, Unexpected character at <FileLocation: 8125 unknown source:361:22>, Unexpected character at <FileLocation: 8295 unknown source:370:21>, Unexpected character at <FileLocation: 8305 unknown source:370:31>, Unexpected character at <FileLocation: 8322 unknown source:371:15>, Unexpected 
character at <FileLocation: 8332 unknown source:371:25>, Unexpected character at <FileLocation: 8705 unknown source:387:11>, Unexpected character at <FileLocation: 8715 unknown source:387:21>, Unexpected character at <FileLocation: 9088 unknown source:403:11>, Unexpected character at <FileLocation: 9099 unknown source:403:22>
[INFO] Generating SDK summary...
[INFO] 28.9s elapsed, 2/18 actions completed.
[WARNING] No actions completed for 28.7s, waiting on:
  - moor_generator:moor_generator on lib/database/mally_db.dart
  - moor_generator:moor_generator on test/widget_test.dart
  - moor_generator:moor_generator on lib/main.dart
  - moor_generator:moor_generator on lib/screens/assets_liabilities/assets_screen.dart
  - moor_generator:moor_generator on lib/screens/assets_liabilities/asset_entry_screen.dart
  .. and 11 more

[INFO] Generating SDK summary completed, took 28.5s

[INFO] 30.1s elapsed, 2/18 actions completed.
[INFO] 31.1s elapsed, 2/18 actions completed.
[INFO] 32.2s elapsed, 2/18 actions completed.
[INFO] 33.2s elapsed, 2/18 actions completed.
[INFO] 34.3s elapsed, 2/18 actions completed.
[INFO] 35.3s elapsed, 2/18 actions completed.
[INFO] 36.5s elapsed, 2/18 actions completed.
[INFO] 37.6s elapsed, 2/18 actions completed.
[INFO] 38.6s elapsed, 2/18 actions completed.
[INFO] 39.7s elapsed, 2/18 actions completed.
[INFO] 40.7s elapsed, 2/18 actions completed.
[INFO] 41.8s elapsed, 2/18 actions completed.
[INFO] 42.9s elapsed, 2/18 actions completed.
[INFO] 43.9s elapsed, 2/18 actions completed.
[WARNING] No actions completed for 15.1s, waiting on:
  - moor_generator:moor_generator on lib/database/mally_db.dart
  - moor_generator:moor_generator on test/widget_test.dart
  - moor_generator:moor_generator on lib/main.dart
  - moor_generator:moor_generator on lib/screens/assets_liabilities/assets_screen.dart
  - moor_generator:moor_generator on lib/screens/assets_liabilities/asset_entry_screen.dart
  .. and 11 more

[INFO] 45.1s elapsed, 2/18 actions completed.
[INFO] 46.2s elapsed, 2/18 actions completed.
[INFO] 47.2s elapsed, 2/18 actions completed.
[INFO] 48.3s elapsed, 2/18 actions completed.
[INFO] 49.4s elapsed, 2/18 actions completed.
[INFO] 50.5s elapsed, 2/18 actions completed.
[INFO] 51.6s elapsed, 2/18 actions completed.
[INFO] 52.7s elapsed, 2/18 actions completed.
[INFO] 53.8s elapsed, 2/18 actions completed.
[INFO] 54.8s elapsed, 2/18 actions completed.
[INFO] 55.8s elapsed, 2/18 actions completed.
[INFO] 56.9s elapsed, 2/18 actions completed.
[INFO] 58.0s elapsed, 2/18 actions completed.
[INFO] 59.2s elapsed, 2/18 actions completed.
[WARNING] No actions completed for 15.1s, waiting on:
  - moor_generator:moor_generator on lib/database/mally_db.dart
  - moor_generator:moor_generator on test/widget_test.dart
  - moor_generator:moor_generator on lib/main.dart
  - moor_generator:moor_generator on lib/screens/assets_liabilities/assets_screen.dart
  - moor_generator:moor_generator on lib/screens/assets_liabilities/asset_entry_screen.dart
  .. and 11 more

[INFO] 1m 0s elapsed, 2/18 actions completed.
[INFO] 1m 4s elapsed, 2/18 actions completed.
[INFO] 1m 11s elapsed, 2/18 actions completed.
[INFO] 1m 12s elapsed, 2/18 actions completed.
[INFO] 1m 14s elapsed, 2/18 actions completed.
[WARNING] No actions completed for 15.1s, waiting on:
  - moor_generator:moor_generator on lib/database/mally_db.dart
  - moor_generator:moor_generator on test/widget_test.dart
  - moor_generator:moor_generator on lib/main.dart
  - moor_generator:moor_generator on lib/screens/assets_liabilities/assets_screen.dart
  - moor_generator:moor_generator on lib/screens/assets_liabilities/asset_entry_screen.dart
  .. and 11 more

[INFO] 1m 16s elapsed, 13/29 actions completed.
[INFO] 1m 17s elapsed, 13/29 actions completed.
[INFO] 1m 19s elapsed, 13/29 actions completed.
[WARNING] moor_generator:moor_generator on lib/database/mally_db.dart:
There were some errors while running moor_generator on package:mally_analytics/database/mally_db.dart:
[WARNING] moor_generator:moor_generator on lib/database/mally_db.dart:
Could not parse file: Malformed sql: Unexpected character at <FileLocation: 49 unknown source:3:21>, Unexpected character at <FileLocation: 59 unknown source:3:31>, Unexpected character at <FileLocation: 76 unknown source:4:15>, Unexpected character at <FileLocation: 86 unknown source:4:25>, Unexpected character at <FileLocation: 416 unknown source:19:4>, Unexpected character at <FileLocation: 426 unknown source:19:14>, Unexpected character at <FileLocation: 756 unknown source:34:4>, Unexpected character at <FileLocation: 767 unknown source:34:15>, Unexpected character at <FileLocation: 943 unknown source:44:21>, Unexpected character at <FileLocation: 953 unknown source:44:31>, Unexpected character at <FileLocation: 
970 unknown source:45:15>, Unexpected character at <FileLocation: 980 unknown source:45:25>, Unexpected character at <FileLocation: 1297 unknown source:59:11>, Unexpected character at <FileLocation: 1307 unknown source:59:21>, Unexpected character at <FileLocation: 1624 unknown source:73:11>, Unexpected character at <FileLocation: 1635 unknown source:73:22>, Unexpected character at <FileLocation: 1806 unknown source:83:21>, Unexpected character at <FileLocation: 1816 unknown source:83:31>, Unexpected character at <FileLocation: 1833 unknown source:84:15>, Unexpected character at <FileLocation: 1843 unknown source:84:25>, Unexpected character at <FileLocation: 2160 unknown source:98:11>, Unexpected character at <FileLocation: 2170 unknown source:98:21>, Unexpected character at <FileLocation: 2487 unknown source:112:11>, Unexpected character at <FileLocation: 2498 unknown source:112:22>, Unexpected character at <FileLocation: 2671 unknown source:123:21>, Unexpected character at <FileLocation: 2681 unknown source:123:31>, Unexpected character at <FileLocation: 2698 unknown source:124:15>, Unexpected character at <FileLocation: 2708 unknown source:124:25>, Unexpected character at <FileLocation: 
3025 unknown source:138:11>, Unexpected character at <FileLocation: 3035 unknown source:138:21>, Unexpected character at 
<FileLocation: 3352 unknown source:152:11>, Unexpected character at <FileLocation: 3363 unknown source:152:22>, Unexpected character at <FileLocation: 3534 unknown source:162:21>, Unexpected character at <FileLocation: 3544 unknown source:162:31>, Unexpected character at <FileLocation: 3561 unknown source:163:15>, Unexpected character at <FileLocation: 3571 unknown source:163:25>, Unexpected character at <FileLocation: 3888 unknown source:177:11>, Unexpected character at <FileLocation: 3898 unknown source:177:21>, Unexpected character at <FileLocation: 4215 unknown source:191:11>, Unexpected character at <FileLocation: 4226 unknown source:191:22>, Unexpected character at <FileLocation: 4397 unknown source:201:21>, Unexpected character at <FileLocation: 4407 unknown source:201:31>, Unexpected character at <FileLocation: 4424 unknown source:202:15>, Unexpected character at <FileLocation: 4434 unknown source:202:25>, Unexpected character at <FileLocation: 4807 unknown source:218:11>, Unexpected character at <FileLocation: 4817 unknown source:218:21>, Unexpected character at <FileLocation: 5190 unknown source:234:11>, Unexpected character at <FileLocation: 5201 unknown source:234:22>, Unexpected character at <FileLocation: 5373 unknown source:244:21>, Unexpected character at <FileLocation: 5383 unknown source:244:31>, Unexpected character at <FileLocation: 5400 unknown source:245:15>, Unexpected character at <FileLocation: 5410 unknown source:245:25>, Unexpected character at <FileLocation: 5783 unknown source:261:11>, Unexpected character at <FileLocation: 5793 unknown source:261:21>, Unexpected character at <FileLocation: 6166 unknown source:277:11>, Unexpected character at <FileLocation: 6177 unknown source:277:22>, Unexpected character at <FileLocation: 6347 unknown source:286:21>, Unexpected character at <FileLocation: 6357 unknown source:286:31>, Unexpected character at <FileLocation: 6374 unknown source:287:15>, Unexpected character at <FileLocation: 6384 unknown source:287:25>, Unexpected character at <FileLocation: 6757 unknown source:303:11>, Unexpected character at <FileLocation: 6767 unknown source:303:21>, Unexpected character at <FileLocation: 7140 unknown source:319:11>, Unexpected character at <FileLocation: 7151 unknown source:319:22>, Unexpected 
character at <FileLocation: 7321 unknown source:328:21>, Unexpected character at <FileLocation: 7331 unknown source:328:31>, Unexpected character at <FileLocation: 7348 unknown source:329:15>, Unexpected character at <FileLocation: 7358 unknown source:329:25>, Unexpected character at <FileLocation: 7731 unknown source:345:11>, Unexpected character at <FileLocation: 7741 unknown source:345:21>, Unexpected character at <FileLocation: 8114 unknown source:361:11>, Unexpected character at <FileLocation: 8125 unknown source:361:22>, Unexpected character at <FileLocation: 8295 unknown source:370:21>, Unexpected character at <FileLocation: 8305 unknown source:370:31>, Unexpected character at <FileLocation: 8322 unknown source:371:15>, Unexpected character at <FileLocation: 8332 unknown source:371:25>, Unexpected character at <FileLocation: 8705 unknown source:387:11>, Unexpected character at <FileLocation: 8715 unknown source:387:21>, Unexpected character at <FileLocation: 9088 unknown source:403:11>, Unexpected character at <FileLocation: 9099 unknown source:403:22>
[WARNING] moor_generator:moor_generator on lib/database/mally_db.dart:
Could not parse file: Malformed sql: Unexpected character at <FileLocation: 52 unknown source:3:21>, Unexpected character at <FileLocation: 62 unknown source:3:31>, Unexpected character at <FileLocation: 82 unknown source:5:4>, Unexpected character at <FileLocation: 90 unknown source:5:12>, Unexpected character at <FileLocation: 114 unknown source:6:22>, Unexpected character at <FileLocation: 118 unknown source:6:26>, Unexpected character at <FileLocation: 454 unknown source:25:21>, Unexpected character at <FileLocation: 464 unknown source:25:31>, Unexpected character at <FileLocation: 481 unknown 
source:26:15>, Unexpected character at <FileLocation: 495 unknown source:26:29>, Unexpected character at <FileLocation: 519 unknown source:27:22>, Unexpected character at <FileLocation: 523 unknown source:27:26>, Unexpected character at <FileLocation: 740 unknown source:39:22>, Unexpected character at <FileLocation: 744 unknown source:39:26>, Unexpected character at <FileLocation: 1095 unknown source:58:12>, Unexpected character at <FileLocation: 1099 unknown source:58:16>, Unexpected character at <FileLocation: 1185 unknown source:63:21>, Unexpected character at <FileLocation: 1195 unknown source:63:31>, Unexpected character at <FileLocation: 1212 unknown source:64:15>, Unexpected character at <FileLocation: 1228 unknown source:64:31>, Unexpected character at <FileLocation: 1252 unknown source:65:22>, Unexpected character at <FileLocation: 1256 unknown source:65:26>, Unexpected character at <FileLocation: 1470 unknown source:77:22>, Unexpected character at <FileLocation: 1474 unknown source:77:26>, Unexpected character at <FileLocation: 1604 unknown source:84:21>, Unexpected character at <FileLocation: 1614 unknown source:84:31>, Unexpected character at <FileLocation: 1631 unknown source:85:15>, Unexpected character at <FileLocation: 1648 unknown source:85:32>, Unexpected character at <FileLocation: 1672 unknown source:86:22>, Unexpected character at <FileLocation: 1676 unknown source:86:26>, Unexpected character at <FileLocation: 1892 unknown source:98:22>, Unexpected character at <FileLocation: 1896 unknown source:98:26>, Unexpected character at <FileLocation: 2860 unknown source:149:21>, Unexpected character at <FileLocation: 2870 unknown source:149:31>, Unexpected character at <FileLocation: 2887 unknown source:150:15>, Unexpected character at <FileLocation: 2898 unknown source:150:26>, Unexpected character at <FileLocation: 2922 unknown source:151:22>, Unexpected character at <FileLocation: 2926 unknown source:151:26>
[SEVERE] moor_generator:moor_generator on lib/database/mally_db.dart:
Error running MoorGenerator
NoSuchMethodError: The getter 'resolvedImports' was called on null.
Receiver: null
Tried calling: resolvedImports
[WARNING] moor_generator:moor_generator on lib/database/mally_db.dart:
There were some errors while running moor_generator on package:mally_analytics/database/mally_db.dart:
[WARNING] moor_generator:moor_generator on lib/database/mally_db.dart:
Could not parse file: Malformed sql: Unexpected character at <FileLocation: 49 unknown source:3:21>, Unexpected character at <FileLocation: 59 unknown source:3:31>, Unexpected character at <FileLocation: 76 unknown source:4:15>, Unexpected character at <FileLocation: 86 unknown source:4:25>, Unexpected character at <FileLocation: 416 unknown source:19:4>, Unexpected character at <FileLocation: 426 unknown source:19:14>, Unexpected character at <FileLocation: 756 unknown source:34:4>, Unexpected character at <FileLocation: 767 unknown source:34:15>, Unexpected character at <FileLocation: 943 unknown source:44:21>, Unexpected character at <FileLocation: 953 unknown source:44:31>, Unexpected character at <FileLocation: 
970 unknown source:45:15>, Unexpected character at <FileLocation: 980 unknown source:45:25>, Unexpected character at <FileLocation: 1297 unknown source:59:11>, Unexpected character at <FileLocation: 1307 unknown source:59:21>, Unexpected character at <FileLocation: 1624 unknown source:73:11>, Unexpected character at <FileLocation: 1635 unknown source:73:22>, Unexpected character at <FileLocation: 1806 unknown source:83:21>, Unexpected character at <FileLocation: 1816 unknown source:83:31>, Unexpected character at <FileLocation: 1833 unknown source:84:15>, Unexpected character at <FileLocation: 1843 unknown source:84:25>, Unexpected character at <FileLocation: 2160 unknown source:98:11>, Unexpected character at <FileLocation: 2170 unknown source:98:21>, Unexpected character at <FileLocation: 2487 unknown source:112:11>, Unexpected character at <FileLocation: 2498 unknown source:112:22>, Unexpected character at <FileLocation: 2671 unknown source:123:21>, Unexpected character at <FileLocation: 2681 unknown source:123:31>, Unexpected character at <FileLocation: 2698 unknown source:124:15>, Unexpected character at <FileLocation: 2708 unknown source:124:25>, Unexpected character at <FileLocation: 
3025 unknown source:138:11>, Unexpected character at <FileLocation: 3035 unknown source:138:21>, Unexpected character at 
<FileLocation: 3352 unknown source:152:11>, Unexpected character at <FileLocation: 3363 unknown source:152:22>, Unexpected character at <FileLocation: 3534 unknown source:162:21>, Unexpected character at <FileLocation: 3544 unknown source:162:31>, Unexpected character at <FileLocation: 3561 unknown source:163:15>, Unexpected character at <FileLocation: 3571 unknown source:163:25>, Unexpected character at <FileLocation: 3888 unknown source:177:11>, Unexpected character at <FileLocation: 3898 unknown source:177:21>, Unexpected character at <FileLocation: 4215 unknown source:191:11>, Unexpected character at <FileLocation: 4226 unknown source:191:22>, Unexpected character at <FileLocation: 4397 unknown source:201:21>, Unexpected character at <FileLocation: 4407 unknown source:201:31>, Unexpected character at <FileLocation: 4424 unknown source:202:15>, Unexpected character at <FileLocation: 4434 unknown source:202:25>, Unexpected character at <FileLocation: 4807 unknown source:218:11>, Unexpected character at <FileLocation: 4817 unknown source:218:21>, Unexpected character at <FileLocation: 5190 unknown source:234:11>, Unexpected character at <FileLocation: 5201 unknown source:234:22>, Unexpected character at <FileLocation: 5373 unknown source:244:21>, Unexpected character at <FileLocation: 5383 unknown source:244:31>, Unexpected character at <FileLocation: 5400 unknown source:245:15>, Unexpected character at <FileLocation: 5410 unknown source:245:25>, Unexpected character at <FileLocation: 5783 unknown source:261:11>, Unexpected character at <FileLocation: 5793 unknown source:261:21>, Unexpected character at <FileLocation: 6166 unknown source:277:11>, Unexpected character at <FileLocation: 6177 unknown source:277:22>, Unexpected character at <FileLocation: 6347 unknown source:286:21>, Unexpected character at <FileLocation: 6357 unknown source:286:31>, Unexpected character at <FileLocation: 6374 unknown source:287:15>, Unexpected character at <FileLocation: 6384 unknown source:287:25>, Unexpected character at <FileLocation: 6757 unknown source:303:11>, Unexpected character at <FileLocation: 6767 unknown source:303:21>, Unexpected character at <FileLocation: 7140 unknown source:319:11>, Unexpected character at <FileLocation: 7151 unknown source:319:22>, Unexpected 
character at <FileLocation: 7321 unknown source:328:21>, Unexpected character at <FileLocation: 7331 unknown source:328:31>, Unexpected character at <FileLocation: 7348 unknown source:329:15>, Unexpected character at <FileLocation: 7358 unknown source:329:25>, Unexpected character at <FileLocation: 7731 unknown source:345:11>, Unexpected character at <FileLocation: 7741 unknown source:345:21>, Unexpected character at <FileLocation: 8114 unknown source:361:11>, Unexpected character at <FileLocation: 8125 unknown source:361:22>, Unexpected character at <FileLocation: 8295 unknown source:370:21>, Unexpected character at <FileLocation: 8305 unknown source:370:31>, Unexpected character at <FileLocation: 8322 unknown source:371:15>, Unexpected character at <FileLocation: 8332 unknown source:371:25>, Unexpected character at <FileLocation: 8705 unknown source:387:11>, Unexpected character at <FileLocation: 8715 unknown source:387:21>, Unexpected character at <FileLocation: 9088 unknown source:403:11>, Unexpected character at <FileLocation: 9099 unknown source:403:22>
[WARNING] moor_generator:moor_generator on lib/database/mally_db.dart:
Could not parse file: Malformed sql: Unexpected character at <FileLocation: 52 unknown source:3:21>, Unexpected character at <FileLocation: 62 unknown source:3:31>, Unexpected character at <FileLocation: 82 unknown source:5:4>, Unexpected character at <FileLocation: 90 unknown source:5:12>, Unexpected character at <FileLocation: 114 unknown source:6:22>, Unexpected character at <FileLocation: 118 unknown source:6:26>, Unexpected character at <FileLocation: 454 unknown source:25:21>, Unexpected character at <FileLocation: 464 unknown source:25:31>, Unexpected character at <FileLocation: 481 unknown 
source:26:15>, Unexpected character at <FileLocation: 495 unknown source:26:29>, Unexpected character at <FileLocation: 519 unknown source:27:22>, Unexpected character at <FileLocation: 523 unknown source:27:26>, Unexpected character at <FileLocation: 740 unknown source:39:22>, Unexpected character at <FileLocation: 744 unknown source:39:26>, Unexpected character at <FileLocation: 1095 unknown source:58:12>, Unexpected character at <FileLocation: 1099 unknown source:58:16>, Unexpected character at <FileLocation: 1185 unknown source:63:21>, Unexpected character at <FileLocation: 1195 unknown source:63:31>, Unexpected character at <FileLocation: 1212 unknown source:64:15>, Unexpected character at <FileLocation: 1228 unknown source:64:31>, Unexpected character at <FileLocation: 1252 unknown source:65:22>, Unexpected character at <FileLocation: 1256 unknown source:65:26>, Unexpected character at <FileLocation: 1470 unknown source:77:22>, Unexpected character at <FileLocation: 1474 unknown source:77:26>, Unexpected character at <FileLocation: 1604 unknown source:84:21>, Unexpected character at <FileLocation: 1614 unknown source:84:31>, Unexpected character at <FileLocation: 1631 unknown source:85:15>, Unexpected character at <FileLocation: 1648 unknown source:85:32>, Unexpected character at <FileLocation: 1672 unknown source:86:22>, Unexpected character at <FileLocation: 1676 unknown source:86:26>, Unexpected character at <FileLocation: 1892 unknown source:98:22>, Unexpected character at <FileLocation: 1896 unknown source:98:26>, Unexpected character at <FileLocation: 2860 unknown source:149:21>, Unexpected character at <FileLocation: 2870 unknown source:149:31>, Unexpected character at <FileLocation: 2887 unknown source:150:15>, Unexpected character at <FileLocation: 2898 unknown source:150:26>, Unexpected character at <FileLocation: 2922 unknown source:151:22>, Unexpected character at <FileLocation: 2926 unknown source:151:26>
[SEVERE] moor_generator:moor_generator on lib/database/mally_db.dart:
Error running DaoGenerator
NoSuchMethodError: The getter 'resolvedImports' was called on null.
Receiver: null
Tried calling: resolvedImports
[INFO] Running build completed, took 1m 21s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 181ms

[SEVERE] Failed after 1m 21s
pub finished with exit code 1

**Comment by simolus3** [comment]
It complains about the `[Acct Code]` syntax. At the moment, the generator only supports double quotes for identifiers (so `"Acct Code"`). I'll change the parser to support square brackets as well.

**Comment by simolus3** [comment]
Done, it should work with the next moor update. As a workaround until then, you can change the `[]` syntax to `""`. Let me know if you run into more problems, thanks!
