### ISSUE TITLE
Cannot create database file in windows desktop

### ISSUE THREAD

**Issue by amasahara** [simolus3/moor#728]
I try working with sqlite database on windows desktop but i can not create database, it alway take error
My database code:
![moor 1](https://user-images.githubusercontent.com/5392719/88261959-775d2880-ccf1-11ea-9163-f562f65907c7.png)

My error
![moor 2](https://user-images.githubusercontent.com/5392719/88262062-af646b80-ccf1-11ea-9ad5-164d43720352.png)

Which way i wrong

**Comment by simolus3** [comment]
You need to install sqlite3.dll on Windows or ship it with your app. See the [readme](https://pub.dev/packages/moor_ffi#on-other-platforms) on how that could work. You can download it on https://www.sqlite.org/download.html

**Comment by amasahara** [comment]
So how could we auto generate sqlite3.dll into debug or release folder of building application and make it can know windows x86 and windows x64

**Comment by simolus3** [comment]
I don't know how Flutter builds executables on Windows - it might be possible to link sqlite3 statically and use `DynamicLibrary.executable()`. Otherwise you need to lookup the right library at runtime.
