### ISSUE TITLE
How to run a SELECT query inside a migration?

### ISSUE THREAD

**Issue by ttencate** [simolus3/moor#729]
I have migrations that are too complex to execute purely in SQL, so I need to load data, transform it in Dart code, then store it back to the database. How to do this in a moor migration?

There is [`issueCustomQuery`](https://pub.dev/documentation/moor/latest/moor/Migrator/issueCustomQuery.html) but it returns `Future<void>`, so we can't use it to read data. Of course, one has simply direct access to the database class itself, including methods like `customSelect`.  This feels a bit icky, because some methods (like `customStatement`) are probably fine, while others (like `select`) won't work. And if it's fine to use those "custom" methods from the database class, then why does `Migrator.issueCustomQuery` exist, if we could also just use `customStatement` from the surrounding database class instead?

**Comment by simolus3** [comment]
In early versions of moor, things would break when attempting to use the database inside a migration callback, so all statements had to be sent through the `Migrator`. We now have a much better implementation that doesn't have these problems. Essentially, all database methods are available in callbacks - provided that they only use tables that have already been created.

You can even use high-level apis like `select` if you make sure to create the tables beforehand. Both that and `customSelect` should work in migrations.

> then why does `Migrator.issueCustomQuery` exist

It's really just for legacy reasons. I just changed `issueCustomQuery` to just use `database.customStatement` and deprecated it.

**Comment by ttencate** [comment]
That clears things up :) Thank you for the incredibly quick and useful response!
