### ISSUE TITLE
Unexpected behavior of offset optional parameter in LIMIT.

### ISSUE THREAD

**Issue by KhatibFX** [simolus3/moor#73]
According to the documentation: If [offset] is provided as well, the first [offset] rows will be skipped and not included in the result.

When I run this query: 

(select(workers)..limit(limit, offset: 0)).watch();

I expect to get the first [limit] workers, since the query will skip the first 0 rows. However, the query doesn't return any entries at all, while running:

(select(workers)..limit(limit)).watch();

Does return the expected [limit] rows.

So am I using offset wrong? or is this a bug?

**Comment by simolus3** [comment]
Thank you for the report, this is certainly a bug!

Moor generates offset clauses like "$amount, $offset" - this is wrong, it should either be "$offset, $amount" or "$amount OFFSET $offset". This is fixed on the develop branch and will be released with the next version later this week.
