### ISSUE TITLE
 DatabaseException(table assets has no column named xxx...) 

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#732]
I keep getting this exception even though I have bump the schema version and add migration code.

1. Add a new column in Assets table

```
class Assets extends Table {
        ......
  TextColumn get vendor =>
      text().map(const VendorToSqlConverter()).nullable()();
       ....
}
```

2. run flutter `pub run build_runner build`

3 bump schema version to 2

4 Add vendor property to migration

 ```
 @override
  int get schemaVersion => 2;

  @override
  MigrationStrategy get migration => MigrationStrategy(onCreate: (Migrator m) {
        return m.createAll();
      }, onUpgrade: (Migrator m, int from, int to) async {
        if (from <= 2) {
          await m.addColumn(assets, assets.vendor);
        }
      });
```
5. Stop and run 

Here my db.g.dart

```
$AssetsTable _assets;
$AssetsTable get assets => _assets ??= $AssetsTable(this);

```

**Comment by simolus3** [comment]
It sounds like that should work - did you accidentally run your app after bumping the schema version but before writing the migration?
Can you reproduce this by installing the old version, applying the same changes and trying again?

**Comment by tony123S** [comment]
What are the correct steps?

1. Add new column then run `pub run build_runner build`.
2. Add migration and bump schema version.
3. Stop app and run again.

Are these steps correct?

**Comment by simolus3** [comment]
Yes, these steps are correct. But it might be that an unfortunate hot-reload between those steps brought your database to an invalid state, especially if you reload on save. If it's a one-time thing, you could try to stop the app before writing the migration.

**Comment by tony123S** [comment]
should I use `_assets` or `assets` ? Are they actually the same?

**Comment by tony123S** [comment]
I tried that but error still persist.

Can you tell me how to solve by using this alternative?
https://github.com/simolus3/moor/issues/184#issuecomment-615860253

**Comment by simolus3** [comment]
> should I use `_assets` or `assets` ? Are they actually the same?

Use `assets`! The other one might be `null`.

I think journal files should be unrelated to this.
