### ISSUE TITLE
Moor 3.3.0 problems

### ISSUE THREAD

**Issue by kuhnroyal** [simolus3/moor#738]
Just did some quick tests with `moor: 3.3.0` and `moor_generator: 3.3.0`:

```
CheckedFromJsonException
Could not create `MoorOptions`.
Unrecognized keys: [apply_converters_on_variables]; supported keys: [write_from_json_string_constructor, override_hash_and_equals_in_result_sets, compact_query_methods, skip_verification_code, use_data_class_name_for_companions, use_column_name_as_json_key_when_defined_in_moor_file, generate_connect_constructor, legacy_type_inference, sqlite_modules, eagerly_load_dart_ast, data_class_to_companions, mutable_classes]
[SEVERE] Failed to instantiate builder for fio_go_app with configuration:
{
 "apply_converters_on_variables": true,
 "override_hash_and_equals_in_result_sets": true,
 "skip_verification_code": true
}
pub finished with exit code 78
```

And `analyzer` needs an upper bound `<=0.39.11`.
```
Error: The setter 'useSummary' isn't defined for the class 'FolderBasedDartSdk'
```

**EDIT:**
The first problem was solved by running `pub run build_runner clean`.
The seconds problem can be solved by adding `analyzer: <=0.39.11` in `dev_dependencies` if that does not conflict with other generators.

**Comment by simolus3** [comment]
>  The first problem was solved by running `pub run build_runner clean`

I guess it's a bug in the build script invalidation logic then. You probably got an old build snapshot when adding the option for the first time.

> Error: The setter 'useSummary' isn't defined for the class 'FolderBasedDartSdk'

Does the error provide some context where it happened? The generator doesn't directly use `FolderBasedDartSdk` at all. If it happens in the `build_resolvers` package for instance, then that package should probably add that constraint (I can file a report on the build repo in that case).

**Comment by kuhnroyal** [comment]
Yea probably, this is however the first time I had this problem so I didn't immediately thing of running `clean`.

You are correct sir:
```
Failed to precompile build_runner:build_runner:
../../.pub-cache/hosted/pub.example.com/build_resolvers-1.3.9/lib/src/resolver.dart:329:7: Error: The setter 'useSummary' isn't defined for the class 'FolderBasedDartSdk'.
 - 'FolderBasedDartSdk' is from 'package:analyzer/src/dart/sdk/sdk.dart' ('../../.pub-cache/hosted/pub.intern.sk/analyzer-0.39.12/lib/src/dart/sdk/sdk.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'useSummary'.
    ..useSummary = false
      ^^^^^^^^^^
pub finished with exit code 1
```

**Comment by simolus3** [comment]
Judging by their [changelog](https://pub.dev/packages/build_resolvers/changelog), `build_resolvers: 1.3.10` should fix this. So you could try setting that as a minimal version (`flutter packages upgrade` should probably be enough too).

------

![analyzer upgrade](https://user-images.githubusercontent.com/5738860/88849849-c5d75f00-d1ea-11ea-95aa-98e773474639.jpg)

**Comment by kuhnroyal** [comment]
Thanks! Closing this as this is solved for me.
