### ISSUE TITLE
How to troubleshoot DAO not being generated?

### ISSUE THREAD

**Issue by GP4cK** [simolus3/moor#740]
It seems I have a faulty DAO file which prevents the code generation from working properly.  
My `moor_database.dart` looks something like:

```dart
part 'moor_database.g.dart';

@UserMoor(
  tables: [...],
  daos: [
    GoodDAO1,
    GoodDAO2,
    BadDAO
  ]
)
class AppDatabase extends _$AppDatabase {
  // ...
}
```

If I comment the line of `BadDAO` and run `flutter pub run build_runner build`, I can see `GoodDAO1` and `GoodDAO2` in the `moor_database.g.dart`.  
However if I uncomment it, the build_runner still builds without any error (even with --verbose) but none of the DAO are in the `moor_database.g.dart`.   
I've been through the [Debugging the builder](https://github.com/simolus3/moor/blob/master/CONTRIBUTING.md#debugging-the-builder) section, generated a launch.json in VSCode to debug it with the option "Break on Uncaught Exceptions" but the error seems to be silent.

Any idea on how I can troubleshoot this further?

**Comment by kuhnroyal** [comment]
Is the DAO missing the `@UseDao` annotation? Otherwise try running `flutter pub run build_runner clean` before the build.

**Comment by simolus3** [comment]
Are you importing all the dao classes? The generator just reads the list literal containing the dao types, it doesn't do any verification on its own:

https://github.com/simolus3/moor/blob/5510cb97b1922d44717c57d98c796c5010e3d934/moor_generator/lib/src/analyzer/dart/use_moor_parser.dart#L39-L46

You could try to set a breakpoint there and check if it contains the types you expect. Sometimes the analyzer reports weird constants if there's an error in the source code.

**Comment by GP4cK** [comment]
Finally found it. It was because of the casing in the import statement in the moor_database.dart.

```diff
- import 'package:my_app/database/entities/Daos/bad.dao.dart';
+ import 'package:my_app/database/entities/daos/bad.dao.dart';
```

`Daos` was supposed to be all lower case...
