### ISSUE TITLE
[question] Does Moor support nested transactions?

### ISSUE THREAD

**Issue by rasuru** [simolus3/moor#741]
My code breaks when I try to nest transactions. Are they supported? If no, are there any known workarounds?

**Comment by simolus3** [comment]
No, moor does not currently support nested transactions - it will just re-use the outer transaction.

The workaround would be to manually use [savepoints and release](https://www.sqlite.org/lang_savepoint.html). Moor could support nested transactions with those, it's just not implemented yet. I can take a look at that if there's interest in nested transactions.

**Comment by rasuru** [comment]
Thank you, I'll try to use savepoints. When I nest transactions, Moor just freezes forever without giving any error. It's a little hard to find the root cause, and I'm still not sure if it's because of nesting them, because I just deleted the nesting and got the same behavior. I'll debug some more, maybe there's some other thing going on.

**Comment by rasuru** [comment]
Is there any way to find out if there is an active transaction? Something like `print(db.executor.currentTransaction)`? I left only one transaction in my whole code, and it still freezes, but if I delete the last transaction wrap it suddenly works. And all the other cases except this one work fine.

**Comment by simolus3** [comment]
> When I nest transactions, Moor just freezes forever without giving any error

Well that shouldn't happen in either case. I'm happy to take a look at that if you can reproduce it easily. We have a test to ensure that nested transactions just re-user the outer one. But since it happens when there's only one transaction, this might be another problem.

> Is there any way to find out if there is an active transaction?

Moor doesn't currently expose this. If you only need this information for debugging, you could enable `logStatements: true` on the `VmDatabase`. This will log the `BEGIN` and `COMMIT` statements.

**Comment by rasuru** [comment]
Yes, I ran these tests and they work. Must be my mistake then :( Closing the issue
``` Dart
test('nested transaction returns value', () async {
final actual = await db.transaction(() async {
  return await db.transaction(() async => 1);
});

expect(actual, 1);
});

test('exceptions in nested transactions', () async {
final exception = Exception('nested exception');

await db.transaction(() async {
  return await db.transaction(() async {
    throw exception;
  }).catchError((e) {
    if (e != exception) fail(e.toString());
  });
});
});

```

**Comment by rasuru** [comment]
Oh, I just needed to await a function .__.

Basically, instead of this:
``` Dart
transaction(task.run);
```

To this:
``` Dart
transaction(() async => await task.run());
```

I thought it would await the function for some reason (and well, this worked in all other cases, so I thought nothing wrong there). Sorry for making noise
