### ISSUE TITLE
Table row as map with values as String representations of the actual values

### ISSUE THREAD

**Issue by willhaslett** [simolus3/moor#744]
There are a number of methods on a model instance that return something with column names as keys and values as the paired value, *but*, from what I can find, all of them return `Variable(theValue)`, not `theValue`.  since the type of `theValue` is dynamic, it seems like it would be useful to have a method that returns the raw values, cast to strings.

I can get the result I'm after by running `Variable(theValue).toString()' through a regex, of course, but am I missing an idiomatic way to do this, or is it missing?

**Comment by simolus3** [comment]
If you just want the string representation, what's wrong with `toString()`? You said you'd need to transform that through a regex, but I'm not sure why that's necessary?
What's wrong with this:

```dart
extension<D extends DataClass> on Insertable<D> {
  Map<String, String> stringValues() {
    return {
      for (final entry in toColumns(true).entries)
        if (entry.value is Variable)
          entry.key: (entry.value as Variable).value.toString()
    };
  }
}
```

**Comment by willhaslett** [comment]
Got it. Thank you. I was accidentally calling `toString()` on the `Variable` instance rather than correctly calling `someVariable.value.toString()`. Still getting facile with the API...
