### ISSUE TITLE
MigrationStrategy in separate dart file

### ISSUE THREAD

**Issue by matthewkooshad** [simolus3/moor#746]
hello, i couldn't see from here, https://moor.simonbinder.eu/docs/advanced-features/migrations/, but i'm wondering about: how can i have my beforeOpen function in another dart file for example? i want to have that seeded data inserts somewhere else.

with the below statement, i don't know how i can get "todos" known in this new file. it's that new file that i want to import in database.dart, and then provide the function [from that new file] for the beforeOpen function.
await into(todos).insert(const TodosCompanion(title: Value('first todo')));

thanks,

**Comment by kuhnroyal** [comment]
You can create an extension on your database class or alternatively you need to hand over a parameter referencing the database instance `this` to your migration class/function.

```dart
extension DatabaseMigrations on MyDatabase {
   Future<void> runMigrationX() async {
    await into(todos).insert(const TodosCompanion(title: Value('first todo')));
  }
}
```

**Comment by matthewkooshad** [comment]
thanks @kuhnroyal ; that worked very well with the extension class. thanks for the example code snippet!
