### ISSUE TITLE
[Question] Is it possible to use where clause over a custom column

### ISSUE THREAD

**Issue by angel1st** [simolus3/moor#748]
Hi there,
Is it possible to add a custom column and then apply where clause?
Here is my case:

```
class ScheduledActivityWithDueDate {
  final ScheduledActivity activity;
  final DateTime dueDate;
  const ScheduledActivityWithDueDate({
    @required this.activity,
    @required this.dueDate,
  });
}

  Future<List<ScheduledActivityWithDueDate>> getDateRangeOrderedByDueDate({
    @required List<ActivityTypesEnum> filter,
    @required DateTime startDate,
    @required DateTime endDate,
    OrderingMode ordering = OrderingMode.desc,
  }) {
    final dueDate = scheduledActivities.lastExecuted;
    final query = (select(scheduledActivities).addColumns([dueDate]).map((row) {
      final activity = row.readTable(scheduledActivities);
      final ScheduledActivityHelper activityHelper = ScheduledActivityHelper(scheduledActivity: activity);

      return ScheduledActivityWithDueDate(activity: activity, dueDate: dueDate.add(const Duration(days: 2));
    })); // <- I would like to apply where clause here, so I can use dueDate calculated value


    return query.get();
  }

```

**Comment by simolus3** [comment]
You can't apply a `where` clause after calling `map` since from there on it's all in Dart, and `where` clauses apply to SQL queries only.

In this case, you can perform the "+2 hours" calculation in SQL and use that:

```dart
final dueDate = scheduledActivities.lastExecuted + const Duration(days: 2);
```

Now, `dueDate` can be used in where clauses, but it needs to happen before you call `map`. Is that what you need?

**Comment by angel1st** [comment]
@simolus3 - not sure I follow you, so let's tackle your answer line by line:
1. You suggested to replace `final dueDate = scheduledActivities.lastExecuted;` with this one `final dueDate = scheduledActivities.lastExecuted + const Duration(days: 2);`?
2. Then I can use `dueDate` in typical `select` e.g.:

```
    final query = (select(scheduledActivities)
      ..where((sa) {
        
      }));
    return query.get();

```

However, if I don't have the `dueDate` calculated for each record, how can I use it in the `where` clause? The solution I thought was to simply add one more column - `dueDate` into the table and each time I updated `executed` date, to update the `dueDate` calculated as shown above. This will allow me to apply the `where` clause later. 

What I was thinking initially is if I can [apply this approach](https://stackoverflow.com/questions/2562422/use-a-named-custom-column-in-sql-2005-in-where-clause), but I guess this isn't possible...

**Comment by simolus3** [comment]
Maybe I misunderstood your question: You want to compute the `dueDate` (defined as `lastExecuted` + 2 hours) for each individual row, but also use that in a `where` clause, right? If so, this should work:

```dart
final dueDate = scheduledActivities.lastExecuted + const Duration(days: 2);
final query = select(scheduledActivities).addColumns([dueDate]);
query..where(dueDate > DateTime.now()); // Example for a where clause using dueDate

return query.map((row) {
  final activity = row.readTable(scheduledActivities);
  final activityDueDate = row.read(dueDate);
  
  return ScheduledActivityWithDueDate(activity: activity, dueDate: activityDueDate);
});
```

Note that the approach from the SO question isn't really necessary with moor: You can just store any expression in a variable (like with `dueDate` here) and use that multiple times. You could even make `dueDate` an extension on `ScheduledActivities` if you need it a lot. With that approach, you don't have much duplicate code.

Note that this doesn't make `dueDate` a custom column or anything. When generating the SQL query from Dart, moor will expand each usage of `dueDate` to `lastExecuted + 7200`.

**Comment by angel1st** [comment]
Thanks, @simolus3 - this is exactly what I need! I didn't realize that this line:
`final dueDate = scheduledActivities.lastExecuted + const Duration(days: 2);` basically creates a new expression, which you can later on use in `where` clause. One final thing (if I may) - you mentioned, that, your code doesn't create a custom column, however, you are using `.addColumns([dueDate]);`. What does this snippet add to the query?

**Comment by simolus3** [comment]
Of course! I just wanted to clarify that this is not a custom [generated column](https://www.sqlitetutorial.net/sqlite-generated-columns/) or anything. It does add a column to that select statement though.
