### ISSUE TITLE
.toJson() issue with converters

### ISSUE THREAD

**Issue by JCKodel** [simolus3/moor#749]
Consider the following table:
```sql
CREATE TABLE "Users"(
	"id" TEXT NOT NULL PRIMARY KEY,
	"displayName" TEXT NOT NULL,
	"email" TEXT NOT NULL,
	"photoUrl" TEXT NOT NULL,
	"authenticationProvider" INT MAPPED BY `authenticationProviderEnumConverter` NOT NULL,
	"hairTexture" INT MAPPED BY `hairTextureEnumConverter` NOT NULL,
	"hairLength" INT MAPPED BY `hairLengthEnumConverter` NOT NULL,
	"hairType" INT MAPPED BY `hairTypeEnumConverter` NOT NULL,
	"hairColor" INT MAPPED BY `hairColorEnumConverter` NOT NULL,
	"gender" INT MAPPED BY `genderEnumConverter` NOT NULL,
	"hairLengthCentimeters" INT NOT NULL,
	"legacyDataMigrated" BOOLEAN NOT NULL,
	"appVersion" TEXT NOT NULL,
	"lastLogin" TEXT MAPPED BY `dateTimeConverter` NOT NULL,
	"created" TEXT MAPPED BY `dateTimeConverter` NOT NULL DEFAULT(STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
	"updated" TEXT MAPPED BY `dateTimeConverter` NOT NULL DEFAULT(STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'now')),
	"synced" BOOLEAN NOT NULL DEFAULT(0)
) AS UsersEntity;
```

When using `.toJson()`, the following json is generated:

```json
{
  "authenticationProvider": AuthenticationProvider.google,
  "hairTexture": HairTexture.a3, 
  "hairLength": HairLength.long,
  "hairType": HairType.none,
  "hairColor": HairColor.none,
  "gender": Gender.none,
  "lastLogin": 1596626082478,
  "created": 1596620053405,
  "updated": 1596626082534
}
```
And Dart JSON serializer throws an exception, because it can't handle enums.

For enums, the index should be serialized (so `0` instead of `Gender.none`, for example). For dates, I'm using a dateTimeConverter to convert dates to ISO String (because Unix timestamp doesn't have timezone info). This should be used in `.toJson()` as well =\

IMO, the JSON should comply with the column type alingment (all my enums are INT and all my dates are TEXT, so .toJson() should serialize ints and strings *using* the converters).

**Comment by JCKodel** [comment]
This code seems to do the trick (it even considers booleans as `true` and `false` instead of `0` and `1`). Just not sure why I need to cast `columns[key]` to dynamic to be able to get the `value` prop =\

```dart
Map<String, dynamic> _getMap(Map<String, Expression<dynamic>> columns) {
    final json = <String, dynamic>{};

    for (final key in columns.keys) {
      json[key] = (columns[key] as dynamic).value;
    }

    return json;
  }
```

**Comment by simolus3** [comment]
Type converters only apply on the mapping from Dart from and to SQL. They don't have any effect on json serialization. As you found out, you can use `toColumns()` and convert that you json if that's more convenient for you.

> why I need to cast columns[key] to dynamic to be able to get the value prop =\

You can cast to `Variable` as well. Moor generates a `Map<String, Expression>` since it could potentially support non-variables as well. This is required for [upserts](https://moor.simonbinder.eu/docs/getting-started/writing_queries/#upserts).
