### ISSUE TITLE
Find a way to safely dispose streams

### ISSUE THREAD

**Issue by simolus3** [simolus3/moor#75]
As pointed out in, https://github.com/simolus3/moor/issues/74#issuecomment-510961063, streams can be listened to multiple times. When users write code like
```dart
var stream = getMyQueryStream();
var stream2 = getMyQueryStream();
await stream.first; // listens and cancels
stream2.listen(...)
```
The `stream` and `stream2` instances are managed by the same cache entry, in particular they share the same `BroadcastStreamController`. Of course, `stream2` should still emit data, so we can't ever close the underlying stream controller. The controller will be garbage collected when its no longer used, but we should find a way to control this nevertheless.

**Comment by North101** [comment]
Gave #3407c8e a test and it working. Thanks for the quick fix

**Comment by simolus3** [comment]
The trade-off with that fix is that we never call `.close()` on the underlying `StreamController`. I guess this is ok, as
- each listener is supposed to unsubscribe when he doesn't want to receive updates (`StreamBuilder`s do this)
- users are supposed to not reference the `Stream` returned by `.watch()` when they're done with it.

So we can assume that the `StreamController` will be garbage-collected and we don't have to call `.close()`
