### ISSUE TITLE
[Question] Performance differences between moor_flutter and (FFI + isolate)

### ISSUE THREAD

**Issue by davidmartos96** [simolus3/moor#756]
Hello! I was wondering if anyone has made any benchmark comparing moor_flutter/sqflite with FFI + an isolate. 
I know that FFI without isolate is generally faster, as it doesn't rely on platform channels communication, but I heard that communication with a separate isolate can have some overhead as well. 
How does it compare with the platform channel overhead?
My app wouldn't benefit just with FFI, as it contains some complex queries that could lock the device. 

Thanks in advance!

**Comment by simolus3** [comment]
Sorry for the slow response. So far, I didn't write any benchmarks comparing isolates to platform channels. I think that's valuable information to have though. Is there anything specific you're interested in? E.g. lots of small writes vs batch writes, simple or computationally intensive selects? Impact of large result sets?

**Comment by davidmartos96** [comment]
@simolus3 No worries!
I don't think there would be much difference running complex queries. I believe comparing lots of small read/write operations and a some queries with a large result set would be good enough.
Benchmarking multiple input arguments, (5-10) would be interesting as well.

**Comment by simolus3** [comment]
I'll close this issue because I think the question has been answered :) Let's hope isolates get even faster with the featherweight isolate feature the Dart team is working on.

**Comment by davidmartos96** [comment]
Sure! Very informative thread and topic nonetheless.
Thanks Simon!
