### ISSUE TITLE
Builder option mutable_classes set to true breaking generated code

### ISSUE THREAD

**Issue by velval** [simolus3/moor#760]
Hi there, Thanks for this library. 

I have followed the steps on https://moor.simonbinder.eu/docs/advanced-features/builder_options/ to change the builder options to be able to generate mutable data classes. However it seems to also mark the Companion classes as mutable but their constructors are still marked as const hence breaking the generated code.

`lib/db/database.g.dart:242:9: Error: Constructor is marked 'const' so all fields must be final.
  const WorkflowsCompanion({
        ^
lib/db/database.g.dart:232:14: Context: Field isn't final, but constructor is 'const'.
  Value<int> localId;`

Is there another option I need to set? Any guidance will be much appreciated. 

I am using:
moor: 3.2.0
moor_generator: 3.2.0 
Flutter 1.20.1
Dart 2.9.0

**Comment by simolus3** [comment]
I think this should be fixed in the latest generator version. Can you run `pub upgrade` and try again?

**Comment by velval** [comment]
Hey mate, thanks heaps for your quick reply. I just upgrade but now I am getting the below error after running **flutter packages pub run build_runner build**.

`Failed to precompile build_runner:build_runner:
/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.7/lib/src/resolver.dart:343:10: Error: Method not found: 'SummaryBuilder'.
  return SummaryBuilder(sdkSources, sdk.context)
         ^^^^^^^^^^^^^^
/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.3.7/lib/src/resolver.dart:332:7: Error: The setter 'useSummary' isn't defined for the class 'FolderBasedDartSdk'.
 - 'FolderBasedDartSdk' is from 'package:analyzer/src/dart/sdk/sdk.dart' ('/C:/tools/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.17/lib/src/dart/sdk/sdk.dart').
Try correcting the name to the name of an existing setter, or defining a setter or field named 'useSummary'.
    ..useSummary = false
      ^^^^^^^^^^
pub finished with exit code 1`

any ideas?

**Comment by simolus3** [comment]
Using `build_resolvers` version `1.3.7` seems a bit suspicious, since the latest version is `1.3.11`. I think `pub upgrade`should have given you that if there aren't any conflicts, but maybe you can add `build_resolvers: ^1.3.11` to your `dev_dependencies` and see if that fixes it?

**Comment by velval** [comment]
Thanks heaps, really appreciate all your help. I managed to solve it now. mutable_classes option works as expected now. 

Seems one of my dependencies had some transitive dependencies causing some dramas. 

Ran **flutter pub upgrade** and then **flutter pub outdated** to check what dependencies needed upgrade. Upgraded all and also note I had to use **build_runner: 1.10.1** as latest 1.10.2 required Dart SDK 2.10 

`environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #flutter_vasat: 0.0.1
  flutter_vasat:
    path: ../vasat-flutter/
  http: 0.12.2
  flutter_platform_widgets: 0.60.1
  shared_preferences: 0.5.8
  json_annotation: 3.0.1
  intl: 0.16.1
  image_picker: 0.6.7+4
  path_provider: 1.6.11
  url_launcher: 5.5.0
  flutter_local_notifications: 1.4.4+2
  rxdart: 0.24.1
  flutter_map: 0.9.0    # Leaflet Maps
  flutter_map_marker_popup: 0.1.4 # Leaflet Maps
  flutter_map_marker_cluster: 0.2.8 # Leaflet Maps
  latlong: 0.6.1        # Leaflet Maps
  get_it: 4.0.4          # Service locator lib / Dependency injection
  # Moor persistence library
  moor: 3.3.1
  moor_ffi: 0.8.0
  path: 1.7.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.1
  json_serializable: 3.4.0
  moor_generator: 3.3.1 # Moor persistence library`
