### ISSUE TITLE
Can't follow documentation when I use .moor files

### ISSUE THREAD

**Issue by vicenterusso** [simolus3/moor#761]
Trying to make some queries following the documentation:

https://moor.simonbinder.eu/docs/getting-started/writing_queries/

`  Future<List<SituacaoDupData>> get allSituacaoDup =>
      select(situacao_dup).get();
`

My code above gives the error:

`Undefined name 'situacao_dup'.
Try correcting the name to one that is defined, or defining the name.`

Tried everything but the doc is not very clear when using moor files

**Comment by simolus3** [comment]
Did you have a `CREATE TABLE situacao_dup (....)` in a moor file? For generated Dart apis, moor converts the table name to camcelCase, so you'd have to use `select(situacao_dup).get()`.

**Comment by vicenterusso** [comment]
> Did you have a `CREATE TABLE situacao_dup (....)` in a moor file? For generated Dart apis, moor converts the table name to camcelCase, so you'd have to use `select(situacao_dup).get()`.

Awesome! How did I miss that?

Another question.. is there any structure recomendation to avoid cluttering all queries inside MyDatabase? I would like to have it separated by tables

**Comment by simolus3** [comment]
> structure recomendation to avoid cluttering all queries inside MyDatabase

Have you seen [DAOs](https://moor.simonbinder.eu/docs/advanced-features/daos/)? They can be used to split queries across multiple Dart classes.

**Comment by vicenterusso** [comment]
DAO didn't worked for me.. same error, can't find the table

https://i.imgur.com/06kuL0B.png

**Comment by simolus3** [comment]
Can you post the generated code in `situacao_dup.db.g.dart`? Does the mixin contain the table field?

**Comment by vicenterusso** [comment]
> Can you post the generated code in `situacao_dup.db.g.dart`? Does the mixin contain the table field?

got it working using `return db.into(db.situacaodup).insert(c)`

👍
