### ISSUE TITLE
Feature request: handling GROUP_CONCAT

### ISSUE THREAD

**Issue by 32mandev** [simolus3/moor#763]
Hello,
could you add GROUP_CONCAT to the list of aggregate expressions supported by Moor?

I just add
 
```
extension StringAggregates<String> on Expression<String> {
  Expression<String> groupConcat() => _AggregateExpression('GROUP_CONCAT', this);
}
```
to the file `aggregate.dart` and it seems to work correctly.

Thanks!

**Comment by simolus3** [comment]
Thanks for the suggestion and code :) I adapted it to support a custom separator and support non-strings too. This will be available in the next moor version.

**Comment by leecommamichael** [comment]
Very excited to see this land in a release 🥇
