### ISSUE TITLE
Multiple where conditions pieced together in a single where clause from variables

### ISSUE THREAD

**Issue by matthewkooshad** [simolus3/moor#767]
i looked over https://github.com/simolus3/moor/issues/424 trying to see how to do what i'm needing. i wasn't able to figure out how to supply a variety of conditionals. could i have a hand with how to do this? the complaint is happening on the ampersand, but i'm thinking i'm not doing it correctly before that point. thank you,

    var q = select(todos);
    var whereOrphan = (v) => isNull(v.parentId); 
    var whereActive = (v) => v.deleted.equals(false);
    
    return (select(todos)..where((v) => whereOrphan & whereActive)).watch();

**Comment by North101** [comment]
If I have multiple dynamic conditions I do something like this:
```
    return (db.select(db.investigator)
          ..where((v) {
            final whereList = <Expression<bool>>[
              if (hasParent) isNull(v.parentId),
              if (onlyActive) v.deleted.equals(false),
            ];
            if (whereList.isEmpty) {
              whereList.add(const Constant(true));
            }
            return whereList.reduce((where, condition) => where & condition);
          }))
        .watch();
```

**Comment by matthewkooshad** [comment]
so, i add my expressions to that <Expression<bool>> collection. and, for the .reduce part, i wonder what does it look like if have expressions A, B, and C and want to do something like A & (B | C) ?
thanks much!

**Comment by North101** [comment]
> i wonder what does it look like if have expressions A, B, and C and want to do something like A & (B | C) ?
You'd need another <Expression>[] but this time do `orList.reduce((clause, condition) => clause | condition)`

```
    return (db.select(db.todos)
          ..where((v) {
            final orList = <Expression<bool>>[
              conditionB,
              conditionC,
            ];

            final whereList = <Expression<bool>>[
              conditionA,
              if (orList.isNotEmpty) orList.reduce((clause, condition) => clause | condition),
            ];
            if (whereList.isEmpty) {
              whereList.add(const Constant(true));
            }
            return whereList.reduce((clause, condition) => clause & condition);
          }))
        .watch();
```

**Comment by matthewkooshad** [comment]
thanks so much @North101 for these examples to help me over it!
