### ISSUE TITLE
conditional orderBy statement

### ISSUE THREAD

**Issue by matthewkooshad** [simolus3/moor#769]
i'm looking at what i learned from https://github.com/simolus3/moor/issues/767#issuecomment-674448162, but i don't see how to use it on an orderBy. it would be nice to conditionally not have a orderBy depending on my sortOption value, which could be none from the enum below. alternatively, if i can't conditionally use orderBy, i could conditionally orderBy the todo.id instead of todo.difficulty. thanks,

the orderBy portion:
`
..orderBy([
                (v) => OrderingTerm(expression: v.difficulty, mode: orderingMode),
              ]))
`

`
enum SortOptions {
  none,
  ascending,
  descending,
}
`

`
OrderingMode getOrderingMode(SortOptions sortOption) {
  return sortOption == SortOptions.descending ? OrderingMode.desc : OrderingMode.asc;
}
`

**Comment by simolus3** [comment]
If you want to change the `orderingMode` based on your `SortOptions` enum, you can just do this:

```dart
const optionsToMode = {
  SortOptions.none: OrderingMode.asc,
  SortOptions.ascending: OrderingMode.asc,
  SortOptions.descending: OrderingMode.desc
};

yourQuery..orderBy([(v) => OrderingTerm(expression: v.difficulty, mode: optionsToMode[yourDesiredMode])]);
```

> i could conditionally orderBy the todo.id instead of todo.difficulty

Of course this is possible too. You can use any Dart function to create the `OrderingTerm`, so you can have conditional logic in there:

```dart
..orderBy([(v) {
  if (sortById) {
    return OrderingTerm(expression: v.id, mode: orderingMode);
  } else {
    return OrderingTerm(expression: v.difficulty, mode: orderingMode);
  }
}])
```

**Comment by matthewkooshad** [comment]
thanks for the two examples. I see in both examples that ordering is
occurring. how to conditionally have no order by occurrence?

**Comment by simolus3** [comment]
Ah, so that's what you meant with `SortOptions.none`. You can use

```dart
final query = select(table)..where(/* and so on */);

if (mode != SortOptions.none) {
  query.orderBy([/* the ordering term function from above */]);
}
```

But be aware that the default order is technically undefined.

**Comment by matthewkooshad** [comment]
great, that worked well. thanks Simon,
