### ISSUE TITLE
Alternative API for custom queries

### ISSUE THREAD

**Issue by simolus3** [simolus3/moor#77]
We currently support custom compiled queries via an annotation on the class, so that correct implementation methods will be generated. This is sufficient for most use cases, but sometimes users want more control over the generated queries:
- they should be able to choose whether a `Stream` version of the query gets generated
- instead of returning a `List<T>`, maybe they just want one row

With the current approach, we only get the sql string, nothing more, so we can't really solve that. However, with an API like
```dart
@Query('SELECT COUNT(*) >= 1 FROM entries WHERE id = :id')
Stream<bool> isSaved(int id);
```
We know that the query should not return a `List` but only a single entry by looking at the return type. We know which type a query has thanks to the sql analyzer, so I don't think we need more than one annotation type, `@Query` should suffice.

## Mapping variables
I think it's reasonable to enforce that parameters appear in the order in which they appear in the sql statement:
```dart
@Query(SELECT * FROM t WHERE name = :name OR (id BETWEEN ?2 AND LENGTH(:name) AND name = ?1)
Future<Table> weirdQuery(String name, String alternative, int lowerBound);
```
The type mapping should support all types supported by moor plus arrays that get expanded at runtime.

## Return types
For updates and deletes, I think we should only support `Future<int>`, `Future<dynamic>`, `Future<void>` and maybe `Future<Null>`. The first two should return the amount of changed rows, the latter shouldn't complete to any value at all.

For select queries, we obviously have to handle a `Future` and a `Stream` differently. We should also handle `List<T>` versus just `T` by using a `.single` stream/future in the generated code. Finally, for `T` we should support:
- a single column: `num`, `int`, `double`, `String`, `Uint8List`, `DateTime`, `bool`
- a composed class:
   - The generated data classes for a `Table`
   - A class that doesn't exist yet? If we have `Future<MyFancyClass> queryMethod()` and `MyFancyClass` doesn't resolve to a known type, should we just write that class? I think this could get _very_ ugly to handle with subsequent builds / interference from other builders
   - A special class that is annotated to be used as a result row:
  ```dart
   @row
    class MyFancyClass {
      @FromColum('a')
      String someRow;
      String b;
      MyFancyClass(this.someRow, this.b)
    }
   ```

## Problems
We currently make users extend (database) or mixin (dao) generated classes, so we can't have abstract methods in them. I think we could have something like this:
```dart
@UseMoor(...)
abstract class MyDatabase extends MoorDb {
  factory MyDatabase() => _$MyDatabaseImpl(FlutterQueryEngine.inDatabasePath(...))
}
```
This would be a breaking change that needs a major version bump, but I think the benefit of having annotated query methods that are implemented in the generated subclass are worth it. Users would only have to change ~2 lines per database / dao, that should be acceptable when properly documented.

**Comment by Mike278** [comment]
Would this be in addition to the current API for custom compiled queries? One of the main benefits I see in the current compiled query API is that users don't have to manually make sure their dart method signature lines up with the SQL statement.

If the goal is more control over the query compiler, perhaps [this](https://github.com/simolus3/moor/blob/53d57d6a96f52077e93bb636532d48bf0e932bff/moor/test/data/tables/todos.dart#L59) approach could be revisted? Parameters could be added to `Sql` for return type, whether or not to generate a stream, and anything else users might want to comminucate to the query compiler (maybe type converters?).

**Comment by simolus3** [comment]
Thanks for the suggestions. Yes, this would definitely be an addition to the existing api. 
> One of the main benefits I see in the current compiled query API is that users don't have to manually make sure their dart method signature lines up with the SQL statement.

Fair, but at least we're able to catch these errors at build time. Ideally, we could also perform that check at edit time with an analyzer plugin. 

Providing more control by letting users specify an `Sql` class instead of just a string would certainly work. Maybe its a personal preference, but to me
```dart
@UseMoor(
  tables: [...],
  queries: {
    'isSaved': Sql(
      'SELECT COUNT(*) >= 1 FROM entries WHERE id = :id',
      mode: QueryMode.streamOnly,
      single: true,
    ),
  }
)
```
feels a bit clumsy (5 lines for a query!) while
```dart
@Query('SELECT COUNT(*) >= 1 FROM entries WHERE id = :id')
Stream<bool> isSaved(int id);
```
feels fluent to write and read. I also think that it integrates better with existing tooling: Let's say we call `.isSaved` somewhere and want to see the definition - going to our own method and being able make changes right there is more helpful than seeing generated code. It would also be more familiar for people using room or floor.

On the other hand, the `@UseMoor` annotation for complex queries isn't _that_ bad, and its certainly simpler to implement. I'll definitely think about it some more, maybe we can also simplify that API a bit.

**Comment by simolus3** [comment]
Closing in favor of #85, which wouldn't require a breaking change and allows us to provide better tooling support in the future.
