### ISSUE TITLE
more than 1 OrderingTerm with conditional logic

### ISSUE THREAD

**Issue by matthewkooshad** [simolus3/moor#770]
looking over https://moor.simonbinder.eu/docs/getting-started/writing_queries/#ordering and https://github.com/simolus3/moor/issues/769#issuecomment-674520459 -- this part below, i don't see how i can have more than 1 OrderingTerm. 
> ```dart
> ..orderBy([(v) {
>   if (sortById) {
>     return OrderingTerm(expression: v.id, mode: orderingMode);
>   } else {
>     return OrderingTerm(expression: v.difficulty, mode: orderingMode);
>   }
> }])
> ```

how can i add a 2nd OrderingTerm if i want to order by v.changeDate after v.difficulty for example in that else? thanks,

**Comment by simolus3** [comment]
Yes, that's what the list is for :)

After splitting the terms into local functions for readability, we get:

```dart
OrderingTerm byIdOrDifficulty(YourTable v) {
  if (sortById) {
    return OrderingTerm(expression: v.id, mode: orderingMode);
  } else {
    return OrderingTerm(expression: v.difficulty, mode: orderingMode);
  }
}

OrderingTerm byChangeDate(YourTable v) => OrderingTerm.desc(v.changeDate);

// Then, in your query
..orderBy([byIdOrDifficulty, byChangeDate]);
```

**Comment by matthewkooshad** [comment]
very nice, thanks.
