### ISSUE TITLE
The method 'group_by' isn't defined for the type 'SimpleSelectStatement'.

### ISSUE THREAD

**Issue by Leon-MI** [simolus3/moor#771]
Hello,

I am using trying to count the number of entries per month and per year, however I am getting
`The method 'group_by' isn't defined for the type 'SimpleSelectStatement'.`
 with the following query :

```
final filesPerMonth = dbFiles.id.count();
final query = select(dbFiles)
    ..addColumns([filesPerMonth])
    ..group_by([dbFiles.date.year])
    ..group_by([dbFiles.date.month]);
```

This is my table :
```
class DbFiles extends Table {
  TextColumn get id => text().clientDefault(() => _uuid.v4())();
  DateTimeColumn get date => dateTime()();

  @override
  Set<Column> get primaryKey => {id};
}
```

What I would like to get as a result of the query is a map withe the years containing a map with month and number of files, like this :
```
{
  2020: {01: 160, 07: 10},
  2019: {02: 55}
}
```

If any other informations are required, feel free to ask.
Thank you very much.

**Comment by simolus3** [comment]
The problem is that `addColumns` turns the `SimpleSelectStatement` to `JoinedSelectStatement`, and `groupBy` only works on the latter. So you'd have to write your query like this:

```dart
final query = select(dbFiles).addColumns([filesPerMonth]);
query.groupBy([dbFiles.date.year, dbFiles.date.month]);
```

Note how we're only using one dot before `addColumns`.

**Comment by Leon-MI** [comment]
Thank you very much this worked perfectly.
