### ISSUE TITLE
Nullable field definition - why the actual value in the DB is not null?

### ISSUE THREAD

**Issue by angel1st** [simolus3/moor#772]
Hi there,
This is my table definition:

```
class ScheduledActivities extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get plantId =>
      integer().customConstraint('REFERENCES plants(id) ON DELETE CASCADE')();
  IntColumn get activityType =>
      intEnum<ActivityTypesEnum>().withDefault(Constant(0))();
  DateTimeColumn get lastExecuted => dateTime().nullable()();
  DateTimeColumn get dueDate => dateTime().withDefault(currentDateAndTime)();
  IntColumn get count => integer().withDefault(Constant(1))();
  IntColumn get periodType => intEnum<PeriodsEnum>().withDefault(Constant(0))();
  DateTimeColumn get timeReminder =>
      dateTime().map(const TimeConverter()).nullable()();
}

```

Please note the case - field `DateTimeColumn get lastExecuted => dateTime().nullable()();` previous definition was `dateTime().withDefault(currentDateAndTime)()`

After changing the definition, I rebuilt with `flutter pub run build_runner build --delete-conflicting-outputs`. 
Hence I guess everything should be ok.
However, when I add new `ScheduledActivity`, I can see in the DB `lastExecuted` still is inserted with value `currentDateAndTime`.
What am I doing wrong?

A side note - `timeReminder` is correctly inserted with value `NULL`.

**Comment by angel1st** [comment]
I figured this out by myself, actually. Since the table exists, its structure won't change, unless I bump `schemaVersion` and make a write down a proper migration strategy.
Speaking of which, I would ask another question - given the current case (changing the field default value from `currentDateAndTime` to `nullable`), how the migration should look like. Basically the steps are clear e.g.

1. Bump `schemaVersion` to 2
2. Read all rows from `scheduled_activities` table
3. Drop the table
4. Create it again - this should apply the new default value
5. Insert all rows

I would really appreciate it if you can give me a snippet for the case or direct me to the existing examples where I can learn from.

**Comment by North101** [comment]
Not tested this myself but something like this should work:
```
  @override
  MigrationStrategy get migration =>
      MigrationStrategy(onUpgrade: (m, fromVersion, toVersion) async {
        if (toVersion == 2) {
          await customStatement('''
            ALTER TABLE scheduled_activities
              RENAME TO old_scheduled_activities
          ''');
          await m.createTable(campaign);
          await customStatement('''
            INSERT INTO scheduled_activities(column1, column2, column3, ..., columnN)
            SELECT column1, column2, column3, ..., columnN
            FROM scheduled_activities
          ''');
          await customStatement('DROP TABLE old_scheduled_activities');
        }
      });
```

I'm not sure if dart/moor guarantees order of generated columns, so I would select/insert them explicitly instead of by `*`.
I'm doing it in sql instead of reading the data into your app as its more efficient and scales better.

**Comment by angel1st** [comment]
Thanks, @North101 - the script works. One minor note `FROM scheduled_activities` should be `FROM old_scheduled_activities`. Other than that - all is good.
I am closing the issue.

**Comment by Mike278** [comment]
looks like its not a problem for this case, but that procedure might not always work - I'd recommend having a look at https://www.sqlite.org/lang_altertable.html#otheralter

**Comment by angel1st** [comment]
@Mike278 - yup, I see your point. I guess I was lucky in my case since the table is not referenced by other tables. If I have to follow the correct procedure, however, how this should look like?
I guess I should start with a custom statement for creating a table with a new name, right, since  `m.createTable(scheduledActivities)` won't allow me to specify a different name?
Any suggestions?

**Comment by Mike278** [comment]
Personally I write CREATE TABLE statements in .moor files so I don’t have any suggestions, but you might be interested in #240, which discusses adding more migration support to the dart api.
