### ISSUE TITLE
Join statement throwing an Exception on first call

### ISSUE THREAD

**Issue by fantastik78** [simolus3/moor#773]
Hi, 

I try to do a leftOuterJoin between 2 tables

The table
```dart
@UseMoor(tables: [Transactions, BudgetCategories, ], daos: [TransactionDao,BudgetCategoryDao])
class MyDatabase extends _$MyDatabase {
  MyDatabase(QueryExecutor e) : super(e);
  @override
  int get schemaVersion => 1;
}
```

The first entity
```dart
class Transactions extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(min: 1, max: 32)();
  RealColumn get amount => real()();
  DateTimeColumn get date => dateTime()();
  BoolColumn get isEssential => boolean()();
  IntColumn get categoryId => integer()();
}
```

The second entity
```dart
@DataClassName('BudgetCategory')
class BudgetCategories extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  RealColumn get planned => real()();
  IntColumn get iconDataPoint => integer()();
  TextColumn get color => text().withLength(min: 7, max: 7)();
}
```

The DAO
```dart
@UseDao(tables: [Transactions, BudgetCategory])
class TransactionDao extends DatabaseAccessor<MyDatabase>
    with _$TransactionDaoMixin {
  final MyDatabase db;

  // Called by the AppDatabase class
  TransactionDao(this.db) : super(db);

  Future<List<TransactionWithCategory>> getAllWithCategory() async {
    var results = await (select(this.db.transactions).join([
      leftOuterJoin(
          this.db.budgetCategories,
          this
              .db
              .budgetCategories
              .id
              .equalsExp(this.db.transactions._categoryId)),
    ])).get();

    return results.map((row) {
      return TransactionWithCategory(
        row.readTable(this.db.transactions),
        row.readTable(this.db.budgetCategories),
      );
    }).toList();
  }
}
```
The Exception:
> Exception has occurred.
> NoSuchMethodError (NoSuchMethodError: The method 'writeAroundPrecedence' was called on null.
> Receiver: null
> Tried calling: writeAroundPrecedence(Instance of 'GenerationContext', Instance of 'Precedence'))

![image](https://user-images.githubusercontent.com/956167/90520291-74771b80-e169-11ea-92d8-932d0b9127f0.png)

But if I call the getAllWithCategory a second time (done using a provider like the first time), the result don't throw an error et return the joined entities.

Thank you for your time :)

**Comment by simolus3** [comment]
> `this.db.transactions._categoryId`

Use `categoryId` instead of `_categoryId` and it should work. Sadly we can't hide that internal field, but you should always use the getter. The private field is set the first time the getter is invoked.

Btw, you can replace `this.db.transactions` with just `transactions` (or `this.transactions` if you prefer). Same for `budgetCategories`.

**Comment by fantastik78** [comment]
I guess I made a beginner mistake... It works now!
Thank you @simolus3 for your reactivity 👍
