### ISSUE TITLE
[Question] - Is it possible to limit watch() method for listenining only for inserts / deletes but not for updates?

### ISSUE THREAD

**Issue by angel1st** [simolus3/moor#774]
Hi there, 
Here is my case:
I have a list of activities for each plant. Hence I defined these two DAO methods:

```
  Stream<List<ScheduledActivity>> watchActivitiesByPlant(int plantId) =>
      (select(scheduledActivities)..where((sa) => sa.plantId.equals(plantId)))
          .watch();
  Future<List<ScheduledActivity>> getActivitiesByPlant(int plantId) =>
      (select(scheduledActivities)..where((sa) => sa.plantId.equals(plantId)))
          .get();

```
If I use `watchActivitiesByPlant` along with a `StreamBuilder` it triggers each time any row from the select changes. However, I would like to add more granular control.
I would like `watchActivitiesByPlant` to triggers only when a row is inserted/deleted from the select.

Is that possible and if it is, how can I achieve it?

**Comment by simolus3** [comment]
>  I would like `watchActivitiesByPlant` to triggers only when a row is inserted/deleted from the select.

You can use `notifyUpdates` to get notified for more slightly more granular updates. In this case, this could look like

```dart
Stream<List<ScheduledActivity>> watchActivitiesByPlan(int plantId) {
  final query = select(scheduledActivities)..where(...);
  final updateFilter = {
    TableUpdate.onTable(scheduledActivities, kind: UpdateKind.delete),
    TableUpdate.onTable(scheduledActivities, kind: UpdateKind.insert),
  };

  return notifyUpdates(updateFilter).asyncMap(query.get); 
}
```

That api is primarily used by generated code to support propagating updates caused by triggers or cascading foreign key constraints. So it's a bit cumbersome to use manually, but it should work well for this use case.

**Comment by angel1st** [comment]
Thanks for the prompt response, @simolus3!
