### ISSUE TITLE
Filter by the field of a second table

### ISSUE THREAD

**Issue by dartflo** [simolus3/moor#775]
I would like to perform a request like this with moor:

SELECT * FROM tablea AS a INNER JOIN tableb as b ON a.id=b.fk_id WHERE b.name LIKE '%name%' AND a.date='2020-08-19'

I tried with aliases but it doesn't work.

**Comment by simolus3** [comment]
Can you post the code you tried? Using this should get you close:

```dart
final a = alias(tableA, 'a');
final b = alias(tableB, 'b'):

final query = select(a).join([innerJoin(b, a.id.equalsExp(b.fkId))]);
query.where(b.name.like('%name%') & a.date.equals('2020-08-19'));
```

If you prefer, you cal always write [SQL with moor](https://moor.simonbinder.eu/docs/using-sql/) and get it checked at compile time.

**Comment by deep34** [comment]
thank you.

**Comment by simolus3** [comment]
@dartflo Does this work for you too? Feel free to re-open if it doesn't of if you have more questions, thanks!
