### ISSUE TITLE
[SEVERE] moor_generator:moor_generator on lib/constants.dart:

### ISSUE THREAD

**Issue by angel1st** [simolus3/moor#777]
Hi @simolus3,
After executing `flutter pub run build_runner build`

I have got this:

```
[SEVERE] moor_generator:moor_generator on lib/constants.dart:

Bad state: Unexpected diagnostics:
D:\DevTools\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
[SEVERE] moor_generator:moor_generator on lib/constants.dart:

Bad state: Unexpected diagnostics:
D:\DevTools\flutter\bin\cache\dart-sdk\lib\core\uri.dart:3259:39 - Expected an identifier.
[SEVERE] moor_generator:moor_generator on lib/constants.dart:

```

and unable to get moor files generated. What shall I do?

**Comment by simolus3** [comment]
I think this is caused by some Flutter and analyzer weirdness, see also https://github.com/dart-lang/build/issues/2763. Temporarily adding `analyzer: 0.39.14` as a `dev_dependency` should fix this.
