### ISSUE TITLE
build runner goes on forever and doesnt stop and does not generate the file

### ISSUE THREAD

**Issue by Chiratna** [simolus3/moor#783]
`
   part 'moor_database.g.dart';
   class Todos extends Table {
   IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(min: 6, max: 32)();
  TextColumn get content => text().named('body')();
  IntColumn get category => integer().nullable()();
}

LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    return VmDatabase(file);
  });
}

@UseMoor(tables: [Todos])
class MyDatabase extends _$MyDatabase {
  MyDatabase() : super(_openConnection());

  
  @override
  int get schemaVersion => 1;
}
`

i used the above code but when i ran **flutter packages pub run build_runner watch** in the terminal the build_runner never stops and doesnot generates the file also

there was **Bad state: Unexpected diagnostics:
/home/faizar/flutter/bin/cache/dart-sdk/lib/core/uri.dart:3259:39 - Expected an identifier.
[SEVERE] moor_generator:moor_generator on test/widget_test.dart:**

that came twice in the terminal..but the build runner goes on forever

**Comment by simolus3** [comment]
It should work if you change your `dev_dependency` of `build_runner` to `^1.10.1`.
