### ISSUE TITLE
Override function "dataClassNameForClassName"

### ISSUE THREAD

**Issue by vicenterusso** [simolus3/moor#786]
How can I override this function?

I spent a lot of time wondering why I had "Data" added to my DAO in only one table

Or at least use annotation to change the class name (not using moor files)

**Comment by simolus3** [comment]
> Or at least use annotation to change the class name

You can use the [`@DataClassName`](https://pub.dev/documentation/moor/latest/moor/DataClassName-class.html) annotation on the class defining the table to change the data class name.
