### ISSUE TITLE
The argument type 'Future<Null> Function(OpeningDetails, dynamic)' can't be assigned to the parameter type 'Future<void> Function(OpeningDetails)'

### ISSUE THREAD

**Issue by seema-shaikh** [simolus3/moor#794]
// Runs after all the migrations but BEFORE any queries have a chance to execute

        beforeOpen: (engine, details) async {
          engine.customStatement('PRAGMA foreign_keys = ON;'); //shows error here

          if (details.wasCreated) {
            // rest of the code

**Comment by seema-shaikh** [comment]
"The argument type 'Future<Null> Function(OpeningDetails, dynamic)' can't be assigned to the parameter type 'Future<void> Function(OpeningDetails)'" This is thrown when I write custom statement to enable foreign keys.

**Comment by seema-shaikh** [comment]
Just solved this by removing the first parameter "engine" and simply changing the code to:

        // Runs after all the migrations but BEFORE any queries have a chance to execute

        beforeOpen: (details) async {
          await customStatement('PRAGMA foreign_keys = ON');

This works.

**Comment by simolus3** [comment]
Yes, just using a single `details` parameter is the right way to go here.

Does the documentation still refer to the old `(engine, details)` function somewhere? If so, please let me know and I'll fix that, thanks!

**Comment by seema-shaikh** [comment]
@simolus3 No, it doesn't. The documentation is updated. Thanks !
