### ISSUE TITLE
List shouldn't be compared using `==`

### ISSUE THREAD

**Issue by cirediew** [simolus3/moor#796]
I have a text column which converts into a `List<int>` but the generated code compares lists by using `==` which always returns false;

My column:
```dart
TextColumn get myList =>
      text().nullable().map<List<int>>(const ListConverter())();
```

The generated code in `database.g.dart`:
```dart
@override
  bool operator ==(dynamic other) =>
      identical(this, other) ||
      (other is Item &&
        other.myList == this.myList);
}
```

```dart
  var a = [1,2,3];
  var b = [1,2,3];
  print(a==b); //false
```

Perhaps using https://pub.dev/packages/equatable could help

**Comment by simolus3** [comment]
I don't agree that moor should generate special equals/hashcode implementations for irregularities introduced by type converters. While collections are the most prominent issue here, the same problem could occur with any other class not overriding equals and hashcode, and moor can't add special support for all of them.

I would recommend to write a list wrapper that overrides equals and hashcode:

```dart
import 'dart:collection';
import 'package:collection/collection.dart';

const equality = ListEquality<dynamic>();

class EqualList<T> extends ListBase<T> {
  final List<T> inner;

  EqualList(this.inner);

  @override
  int get length => inner.length;

  @override
  set length(int value) => inner.length = value;

  @override
  T operator [](int index) => inner[index];

  @override
  void operator []=(int index, T value) => inner[index] = value;

  @override
  int get hashCode => equality.hash(this);

  @override
  bool operator ==(Object other) {
    return other is List<T> && equality.equals(other, this);
  }
}
```

Now, you can let your converter wrap lists with `EqualList` to get the behavior you want.
