### ISSUE TITLE
Missing "_$AppDatabase.connect(DatabaseConnection c) : super.connect(c);" in _$AppDatabase

### ISSUE THREAD

**Issue by angel1st** [simolus3/moor#799]
Hi there,
In my previous app, I was using the following moor dependencies:
```
  moor: ^3.3.1
  moor_ffi: ^0.5.0

```
now, in my new app, I decided to move to the most recent config e.g.:

```
  moor: ^3.3.1
  sqlite3_flutter_libs: ^0.2.0

```

Then I decided to generate the code with `flutter pub run build_runner build` - at this point, I had to add `analyzer: 0.39.14` to `dev_dependencies` due to #777 
After a successful generation however, I have one error left:
`AppDatabase.connect(DatabaseConnection connection) : super.connect(connection);`
> error: The class '_$AppDatabase' doesn't have a constructor named 'connect'. (undefined_constructor_in_initializer at [pet_diary] lib\local_data_sources\app_database.dart:76)

And indeed, when I had a look at the generated `_$AppDatabase` class in `app_database.g.dart` file, the constructor is missing, unlike what I have got in my previous app `app_database.g.dart` file.

**Comment by simolus3** [comment]
The `connect` constructor is only generated when enabling the `generate_connect_constructor` [build option](https://moor.simonbinder.eu/docs/advanced-features/builder_options/). Can you make sure that you enabled that?

**Comment by angel1st** [comment]
Yep, that's right. I missed to transfer this part of the config. Thanks, @simolus3! Closing the issue.
