### ISSUE TITLE
Desktop support

### ISSUE THREAD

**Issue by hundeva** [simolus3/moor#80]
I apologise if the answer for this is obvious, or is already answered somewhere else, I couldn't find anything related.

I'm currently evaluating solutions for an idea, which is going to need a local database. The usage of Flutter is basically decided, however I would prefer to use desktop apps for Windows and macOS instead of a web app.

I realise desktop targets are in a very early phase, but still, is there any plan (or is it even possible at the moment) to support these platforms?

**Comment by simolus3** [comment]
Thanks for the issue. We currently don't support the Dart VM, but there is #76 to track that. We're most likely going to use `dart:ffi` for to integrate sqlite, but we can't release a public VM version before `dart:ffi` is stable (its currently experimental). We can release a development version for Desktop apps sooner, and that's definitely planned, but I can't give an ETA yet.
