### ISSUE TITLE
[Question] - prefil enums in onCreate callback

### ISSUE THREAD

**Issue by angel1st** [simolus3/moor#802]
These are my table definitions:

```
@DataClassName("ActivityCategory")
class ActivityCategories extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
}

class ActivityItems extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
}

@DataClassName("ActivityCategoryItemEntry")
class ActivityCategoryItemEntries extends Table {
  IntColumn get categoryId => integer()();
  IntColumn get itemId => integer()();
  @override
  Set<Column> get primaryKey => {categoryId, itemId};
}

```
I have several predefined categories, each one consists of several items, and since some of the items are shared among categories, I need a many-to-many relationship. `ActivityCategoryItemEntries` is the junction table.
Now, since I have all these values, I would like to prefill three tables in `onCreate` `MigrationStrategy` callback.
I found your [many-to-many example](https://moor.simonbinder.eu/docs/examples/relationships/) very useful in case you have to insert rows after user interaction e.g. adding items to the shopping cart.
In my use case, let's suppose, I have these activity lists:

#### Care Category
1. Feed
1. Clean
1. Weight
1. Height

#### Medical Category
1. Surgery
1. Vaccination
1. Medications
1. Vitamins

#### Shopping Category
1. Food
1. Accessories
1. Medications
1. Vitamins

How should I flush these to the three tables above during `onCreate` callback?

**Comment by simolus3** [comment]
> How should I flush these to the three tables above during `onCreate` callback?

You can run any query during the migrations, which includes inserts:

```dart
onCreate: (Migragor m) async {
  await m.createAll();
  
  final feedId = await into(activityItems).insert(ActivityItemsCompanion.insert(name: 'Feed'));
  final cleanId = await into(activityItems).insert(ActivityItemsCompanion.insert(name: 'Clean'));
  // insert remaining activities like this...
  
  final careCategory = await into(activityCategories).insert(ActivityCategoriesCompanion.insert(name: 'Care'));
  // same here, insert remaining categories

  // now, insert combinations:
  await into(activityCategoryItemEntries).insert(ActivityCategoryItemEntry(categoryId: careCategory, itemId: feedId));
  // and so on
}
```

Of course it's a lot of repetitive code when done like this, you could also store the associations in a list and iterate over that to insert that. You could also wrap the inserts in a `transaction` to be safe.

**Comment by angel1st** [comment]
Thanks, closing the issue since the above solves my problem.
