### ISSUE TITLE
Migration to change column type

### ISSUE THREAD

**Issue by DennisMuchiri** [simolus3/moor#803]
I have a column 

TextColumn get metric => text().nullable()();

that i want to convert to a foreign key column

IntColumn get metric =>
      integer().nullable().customConstraint('NULL REFERENCES metrics(id)')();

@simolus3 how do I write a migration for this?

**Comment by simolus3** [comment]
Unfortunately, sqlite does not provide a builtin mechanism for this that moor could expose. If you don't have triggers, views or indexes on the table, a simple way to alter it is to:

- rename the old table
- re-create your table
- use an `INSERT INTO SELECT` to copy over existing data

In a migration, that could look like this:

```dart
onUprade: (Migrator m, int from, int to) async {
  if (conditionForMigration) {
    await customStatement('ALTER TABLE ${yourTable.actualTableName} RENAME TO tmp_old_table');
    await m.createTable(yourTable);
    await customStatement('''
      INSERT INTO ${yourTable.actualTableName} (first_column, second_column, metric, ...)
      SELECT first_column, second_column, CAST(metric AS INT), ... FROM tmp_old_table
   ''');
    await customStatement('DROP TABLE tmp_old_table');
  }
}
```

I'll add a method to the `Migrator` that will run the [general 12-step change](https://www.sqlite.org/lang_altertable.html#otheralter) with an api that's easier to use.

**Comment by simolus3** [comment]
In the next moor version, you will be able to just use

```dart
if (conditionForMigration) {
  await m.alterTable(TableMigration(
    yourTable,
    columnTransformer: {
      yourTable.metric: yourTable.metric.cast<int>(), 
    },
  ));
}
```
