### ISSUE TITLE
[Question] Initialize database data when create table 

### ISSUE THREAD

**Issue by svprdga** [simolus3/moor#811]
I just decided to start using Moor for my project, right now I'm migrating from sqflite.

I create the tables within dart code, but I couldn't found a way to insert initial data to a table just after its creation (the first time the app is opened and all the database created).

What is the best way to achieve that?

Many thanks.

**Comment by simolus3** [comment]
A good place to insert initial data is the [`beforeOpen`](https://moor.simonbinder.eu/docs/advanced-features/migrations/#post-migration-callbacks) callback that you can use in a migration. The link contains an example to insert some values after the database was created. Is that what you were looking for?

**Comment by svprdga** [comment]
Yes, thank you!
