### ISSUE TITLE
How to use object in where clause?

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#814]
How can I use `locationId`  in `where` clause since `unitOwner` is a `GeneratedTextColumn` ?

```
 Future<List<ABC>> getPreDefects(String locationId) {
    return (select(abcTable)
          ..where((t) => t.unitOwner.locationId.equals(int.parse(locationId)))
          ..orderBy([
            (t) =>
                OrderingTerm(expression: t.updatedAt, mode: OrderingMode.desc)
          ]))
        .get();
  }

```
**abcTable**

```
class ABCTableData extends DataClass
    implements Insertable<ABC> {
   final UnitOwner unitOwner;
  .....
   }
```
**UnitOwner**
```

JsonSerializable()
class UnitOwner {
var locationId;
}
```

**Comment by simolus3** [comment]
If you know that each row contains valid json in `UnitOwner`, you can use the `json1` extension to extract and compare the field:

```dart
import 'package:moor/extensions/json1.dart';

 Future<List<ABC>> getPreDefects(String locationId) {
    return (select(abcTable)
          ..where((t) {
            final locationId = t.unitOwner.jsonExtract<int>(r'$.locationId');
            return locationid.equals(int.parse(locationId))
           })
          ..orderBy([
            (t) =>
                OrderingTerm(expression: t.updatedAt, mode: OrderingMode.desc)
          ]))
        .get();
  }
```

This assumes that your type converter stores a `UnitOwner` like this: `{"locationId": 123, "someOtherFields": ...}`. If you store the location id differently, you'll have to change the [path argument](https://www.sqlite.org/json1.html#path_arguments). Also, the json1 extension is only reliably available when you use the latest `sqlite3_flutter_libs` package as described [here](https://moor.simonbinder.eu/docs/getting-started/#adding-the-dependency).
