### ISSUE TITLE
Web Database - Existing Asset

### ISSUE THREAD

**Issue by karthikgs-in** [simolus3/moor#816]
Hello, 

I have a read only database which is now being used in my mobile app (sqflite/VmDatabase) which I am now extending to the web. I have also created a shared database as per moor_shared, and my web program compiles. 

How do I read from an existing database on the web?

**Comment by simolus3** [comment]
You can control the underlying byte content of a `WebDatabase`, which can be used to initialize data from an asset.

If you're using a `WebDatabase(name)`, you can initialize it before using it with

```dart
final storage = MoorWebStorage(name);
await storage.store(yourAssetBytes);
```

**Comment by karthikgs-in** [comment]
That worked, thanks!
