### ISSUE TITLE
Multiple database ?

### ISSUE THREAD

**Issue by KaungZawHtet** [simolus3/moor#818]
Is it ok to work with multiple database? 
I am considering json store as another database thing. If moor code generation work with multiple db class, I will choose moor for another one too. Here is something I want :

```
//ex_db.dart
class ExteranlDatabase extends _$ExteranlDatabase {
...
}
```

```
//int_db.dart
class InternalDatabase extends _$InternalDatabase {
...
}
```

**Comment by simolus3** [comment]
Yes, you can use more than one moor database in your app if you want to. It should work if you put a `@UseMoor` annotation on both database classes.

However, moor expects that both database classes use different tables. If you want to share tables between your external and internal database, it's easier to just write one class and construct it multiple times, once for the internal and once for the external database.

**Comment by KaungZawHtet** [comment]
Thank you for your reply. This can be closed now. If something weird happen, I will report you for further issues
