### ISSUE TITLE
[Question/Enhancement] How to generate via code a true relationship between tables?

### ISSUE THREAD

**Issue by rubenferreira97** [simolus3/moor#821]
Hi, after taking a look on the documentation I have managed to create a relationship between two entities. However this code does not guarantee a valid id, present on, for example, in a category tables.

```
class Todos extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(min: 6, max: 32)();
  TextColumn get content => text().named('body')();

  // Make this line generate REFERENCES categories(id) on Todos table
  IntColumn get category => integer().nullable()(); 
}

@DataClassName("Category")
class Categories extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get description => text()();
}
```

If you generate the code manually by SQL, this is easy to achieve:
```
CREATE TABLE todos (
    id INT NOT NULL PRIMARY KEY AUTOINCREMENT,
    title TEXT,
    body TEXT,
    category INT REFERENCES categories (id)
);
```

Is there any way to achieve this by code?

**Comment by simolus3** [comment]
You can use

```dart
IntColumn get category => integer().customConstraint('REFERENCES categories(id)')();
```

Don't forget to enable foreign key constraints after [opening the database](https://moor.simonbinder.eu/docs/advanced-features/migrations/#post-migration-callbacks).

> If you generate the code manually by SQL, this is easy to achieve:

In case you haven't seen this: Moor can automatically generate Dart classes based on `CREATE TABLE` statements too by using [moor files](https://moor.simonbinder.eu/docs/using-sql/moor_files/). If you prefer sql anyway, they can be quite convenient.

**Comment by rubenferreira97** [comment]
Thanks, it's working. Another question, (don't know if I should open another ticket), is there any chance that moor supports inheritance on `DataClasses/Tables`? Imagine I have a `Category `Class, and I want to have two tables, `FooCategory` and `BarCategory`. I want to be able in my logic model to save these as `Category` objects.

**Comment by simolus3** [comment]
No, this is not currently supported. https://github.com/simolus3/moor/issues/719 would be a similar request, but this is pretty complicated to implement in the generator.

In general, moor-generated classes are supposed to be thin wrappers around rows, so IMO complex inheritance doesn't make that much sense for them. If you want a more appropriate domain layer, you'd have to write your own classes and copy between them and what moor generates.
