### ISSUE TITLE
How to select tow COUNT results with different where condition use moor api

### ISSUE THREAD

**Issue by XBaron** [simolus3/moor#822]
How to select tow COUNT results with different where condition use moor api?
eg: select (select count(id) from table where status=0) as count1, (select count(id) from table where status=1) as count2

**Comment by simolus3** [comment]
You can write these queries with a `GROUP BY` clause. Essentially, your query is equivalent to `select count(id) from table where status in (0, 1) group by status`. You can query that from moor's Dart api using:

```dart
final count = table.id.count();

final query = selectOnly(table)
  ..addColumns([count])
  ..where(table.status.isIn(const [0, 1]))
  ..groupBy([table.status]);
```

**Comment by XBaron** [comment]
Thanks for reply!
