### ISSUE TITLE
I can't generate ForeignKeys from Moor File (ref table couldn't be found)

### ISSUE THREAD

**Issue by Kobreizhyashi** [simolus3/moor#823]
Hi ! 

I have a problem with moor "from SQL" generator. I've created a table (then I built it). Next I've tried to put a ForeignKey reference inside an existing table to the new table : 

`FOREIGN KEY(visibilityId) REFERENCES Accesses(id) ON UPDATE CASCADE ON DELETE SET NULL ,
 FOREIGN KEY(accessId) REFERENCES Accesses(id) ON UPDATE CASCADE ON DELETE SET NULL`

Accesses is the new Table, this is it .moor structure : 

`
  import '../converters/condition_converter.dart';

  CREATE TABLE Accesses (
  id INT NOT NULL PRIMARY KEY,
  conditions TEXT MAPPED BY `const ConditionConverter()`,
  isAccessible BOOLEAN,
  switchOnDisplay BOOLEAN) as Access;
`

The problem is when I run build_runner in order to generate this relationship, moor_generator brings me errors specifically on those lines : 

`
[WARNING] moor_generator:moor_generator on lib/src/db/database.dart:
line 48, column 28: Referenced table Accesses could not befound.
   ╷
48 │  FOREIGN KEY(visibilityId) REFERENCES Accesses(id) ON UPDATE CASCADE ON DELETE SET NULL ,
   │                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵

[WARNING] moor_generator:moor_generator on lib/src/db/database.dart:
line 49, column 24: Referenced table Accesses could not befound.
   ╷
49 │  FOREIGN KEY(accessId) REFERENCES Accesses(id) ON UPDATE CASCADE ON DELETE SET NULL
   │                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵

[WARNING] moor_generator:moor_generator on lib/src/db/database.dart:
There were some errors while running moor_generator on package:core/src/db/database.dart:

[WARNING] moor_generator:moor_generator on lib/src/db/database.dart:
line 48, column 28: Referenced table Accesses could not befound.
   ╷
48 │  FOREIGN KEY(visibilityId) REFERENCES Accesses(id) ON UPDATE CASCADE ON DELETE SET NULL ,
   │                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵

[WARNING] moor_generator:moor_generator on lib/src/db/database.dart:
line 49, column 24: Referenced table Accesses could not befound.
   ╷
49 │  FOREIGN KEY(accessId) REFERENCES Accesses(id) ON UPDATE CASCADE ON DELETE SET NULL
   │                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
`

It's a real problem because some other Foreignkeys exists in the same file to other tables which I've took for example in order to create my new table (Models, converters etc..). 

Moor version : ^3.3.1
moor_generator: ^3.3.1
Build_runner version : ^1.10.1

**Comment by North101** [comment]
You need to import the `Accesses` `.moor` file into the file thats referencing it.

**Comment by Kobreizhyashi** [comment]
> You need to import the `Accesses` `.moor` file into the file thats referencing it.

Thanks ! It works fine & I feel fucking **dumb** ! 👍
