### ISSUE TITLE
NOT NULL constraint failed even with `nullable()`

### ISSUE THREAD

**Issue by f2acode** [simolus3/moor#824]
I'm trying to insert an entry, but I'm having a problem with `nullable()` (looks like it isn't working).

My database code:

```flutter
import 'package:moor_flutter/moor_flutter.dart';
export 'package:moor_flutter/moor_flutter.dart' show Value;

part 'moor_database.g.dart';

@DataClassName('Story')
class Stories extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get title => text().withLength(max: 20).nullable()();
  TextColumn get storyText => text().nullable()();
  TextColumn get feeling => text().withLength(max: 1).nullable()();
  DateTimeColumn get date => dateTime()();
  DateTimeColumn get createdAt => dateTime()();
}

@UseMoor(tables: [Stories])
class AppDatabase extends _$AppDatabase {
  AppDatabase()
      : super(FlutterQueryExecutor.inDatabaseFolder(
          path: 'db.sqlite',
          logStatements: true,
        ));

  @override
  int get schemaVersion => 1;

  Future<List<Story>> getAllStories() => select(stories).get();
  Stream<List<Story>> watchAllStories() => select(stories).watch();
  Future insertStory(Story story) => into(stories).insert(story);
  Future updateStory(Story story) => update(stories).replace(story);
  Future deleteStory(Story story) => delete(stories).delete(story);
}
```

Then when I try to insert:

```flutter
 _db.insertStory(Story(
            title: titleController.text,
            storyText: textController.text,
            createdAt: DateTime.now(),
            feeling: feeling,
            date: date,
          ));
```

I have the foolwing error:

> I/flutter (21170): Moor: Sent INSERT INTO stories (title, story_text, date, created_at) VALUES (?, ?, ?, ?) with args [a, , 1600278162, 1600278165]
> E/flutter (21170): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: DatabaseException(NOT NULL constraint failed: stories.feeling (code 1299 SQLITE_CONSTRAINT_NOTNULL)) sql 'INSERT INTO stories (title, story_text, date, created_at) VALUES (?, ?, ?, ?)' args [a, , 1600278162, 1600278165]}

My dependencies:

```yaml
dependencies:
  moor_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.3.1
  build_runner:

dependency_overrides:
  analyzer: '0.39.14'
```

**Comment by simolus3** [comment]
If you added `nullable()` afterwards, the table structure (with the original `NOT NULL` constraint) has already been generated. During development, you can simply clear your app's data and open the app again to recreate the tables and fix this. If you already released a version without `nullable()`, you'll need to increase your `schemaVersion` and write a proper migration.

**Comment by f2acode** [comment]
Thank you, it worked by removing the app and installing again. 
Would be possible to recreate the table in this case?

**Comment by f2acode** [comment]
Never mind, as I checked probably I should use a `MigrationStrategy` for that, right?
