### ISSUE TITLE
Unable to use property field as setter because it is final

### ISSUE THREAD

**Issue by geoffreylzf** [simolus3/moor#829]
For some reason, I query one row by using select query with `getSingle()`.

I expected that I can update the instance directly using its property and then put the instance in update query 
```
instance.remark = 'I only want to change this field';
update(todos).replace(instance);
```
but I am unable to do that because it is final field.

In the end, I need to recreate a new instance of the table 
```
final ins2 = Todo(
    id: instance.id,
    task: instance,task,
    date: instance.date,
    remark: "I only want to change this field",
);
update(todos).replace(ins2);
```

Is there any way to avoid recreate a new instance?

**Comment by simolus3** [comment]
You can use `final ins2 = instance.copy(remark: 'I only want to change this field')`, but that also creates a new instance.

Alternatively, you could enable the `mutable_classes` [build option](https://moor.simonbinder.eu/docs/advanced-features/builder_options/).

**Comment by geoffreylzf** [comment]
Thx
