### ISSUE TITLE
Is it possible to specify the output directory for the .g.dart files?

### ISSUE THREAD

**Issue by mcavazotti** [simolus3/moor#836]
The title itself is very comprehensible.

It would be very useful to keep all the generated files in a different folder. I know I can do it by hand, but I would have to do it all over again when I execute `pub run builder_runner`.

**Comment by simolus3** [comment]
Unfortunately, `build_runner` does not allow this (yet), see https://github.com/dart-lang/build/issues/1689. Since moor generates everything through `build_runner`, it can't support this either.

**Comment by mcavazotti** [comment]
Oh, I see. Anyways, thank you for your answer
