### ISSUE TITLE
widget_test.dart assert error

### ISSUE THREAD

**Issue by cristianopcortez** [simolus3/moor#837]
after run 
**flutter.bat --no-color test --machine test\widget_test.dart** 
there is a expection caught by flutter test framework:

The following TestFailure object was thrown running a test:
  Expected: exactly one matching node in the widget tree
  Actual: _TextFinder:<zero widgets with text "0" (ignoring offstage widgets)>
   Which: means none were found but one was expected

**Comment by simolus3** [comment]
This doesn't seem to be related to moor, so I'll close this issue. If you need general help writing Flutter tests, you could try reading their [docs on testing](https://flutter.dev/docs/testing) or asking on StackOverflow.
