### ISSUE TITLE
SUM returning always NULL

### ISSUE THREAD

**Issue by raedinkhaled** [simolus3/moor#839]
Hello, I'm trying to get the sum of a column but it returns null always

here is my table class : 

`class Reliquats extends Table {
  IntColumn get reliquatID => integer().autoIncrement()();
  IntColumn get medicid =>
      integer().customConstraint('NOT NULL REFERENCES medics(medic_i_d)')();
  RealColumn get quantite => real()();
  DateTimeColumn get date => dateTime()();
  BoolColumn get isvalid => boolean().withDefault(Constant(true))();
}`

here is my DAO:

```
`@UseDao(tables: [Reliquats, Medics],queries: {
  'sumOfReliquatsForSelectedMedic':
    'SELECT SUM(quantite) FROM reliquats WHERE medicid=:id'
})
class ReliquatDao extends DatabaseAccessor<AppDatabase>
    with _$ReliquatDaoMixin {
  final AppDatabase db;
  ReliquatDao(this.db) : super(db);

  Stream<List<ReliquatWithMedics>> watchAllReliquats() => select(reliquats)
      .join([
        leftOuterJoin(medics, medics.medicID.equalsExp(reliquats.medicid)),
      ])
      .watch()
      .map((rows) => rows.map((row) {
            return ReliquatWithMedics(
                medic: row.readTable(medics),
                reliquat: row.readTable(reliquats));
          }).toList());
   Future<double> getSum(Medic m) => sumOfReliquatsForSelectedMedic(m.medicID).getSingle();

          Future insertReliquat(Insertable<Reliquat> reliquat) =>
      into(reliquats).insert(reliquat);
  Future deleteReliquat(Insertable<Reliquat> reliquat) =>
      delete(reliquats).delete(reliquat);

}`

```
and here is how I'M I getting it to the UI:

```
Widget buildMedic(
    BuildContext context, Medic itemMedic, MedicDao medicDao, int value) {
  final reliquatCubit = context.bloc<ReliquatsCubit>();
 double reliquat;

  reliquatCubit.reliquatDao.getSum(itemMedic).then((value) {
    reliquat = value;
  });


  

  return Padding(
    padding: EdgeInsets.symmetric(horizontal: 5),
    child: Column(
      children: <Widget>[
        Container(
          child: Card(
            shape:
                RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
            margin: const EdgeInsets.symmetric(horizontal: 1, vertical: 12),
            child: ListTile(
              onTap: () => Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (_) => EditMedicScreen(medic: itemMedic),
                ),
              ),
              title: Text(
                '${itemMedic.medicNom.toUpperCase()}',
                style: TextStyle(
                    fontWeight: FontWeight.w500, fontSize: textSizeMedium),
              ),
              subtitle: Text('${itemMedic.medicLab}'),
              trailing: Column(
                children: <Widget>[
                  text("Reliquats",
                      fontSize: textSizeMedium,
                      textColor: t5TextColorSecondary),
                  Container(
                    padding: EdgeInsets.fromLTRB(10, 0, 10, 0),
                    decoration: boxDecoration(bgColor: t5DarkRed, radius: 16),
                    child: text("$reliquat ml",
                        fontSize: textSizeMedium, textColor: t5White),
                  ),
                ],
              ),
            ),
          ),
        ),
      ],
    ),
  );
}

```
am I missing something ?

**Comment by davidmartos96** [comment]
@raedinkhaled  SUM in SQLite will return NULL if any of the numbers summed is NULL. Your column is nullable so that is probably the issue.
You can add a WHERE quantite IS NOT NULL or SUM(COALESCE(quantite, 0)). Any of those solutions could work.

**Comment by raedinkhaled** [comment]
> @raedinkhaled SUM in SQLite will return NULL if any of the numbers summed is NULL. Your column is nullable so that is probably the issue.
> You can add a WHERE quantite IS NOT NULL or SUM(COALESCE(quantite, 0)). Any of those solutions could work.

my column isn't NULL..

**Comment by davidmartos96** [comment]
@raedinkhaled Oh, my mistake, I thought for a moment that the columns were nullable by default with the Dart syntax.

**Comment by simolus3** [comment]
I'm not sure what's going wrong here either. For a quick sanity check, you could run `SELECT * FROM reliquats WHERE medicid=:id` and verify that there aren't any null-values.

Sqlite might return an unexpected column name for some reason. Does it work if you use `SELECT SUM(quantite) as result FROM reliquats WHERE medicid=:id`?

**Comment by raedinkhaled** [comment]
> I'm not sure what's going wrong here either. For a quick sanity check, you could run `SELECT * FROM reliquats WHERE medicid=:id` and verify that there aren't any null-values.
> 
> Sqlite might return an unexpected column name for some reason. Does it work if you use `SELECT SUM(quantite) as result FROM reliquats WHERE medicid=:id`?

I checked that there no NULL VALUES and also tried your last suggestion but I still get null everytime..

**Comment by raedinkhaled** [comment]
how can I write that same SQL REQUEST with moor and dart syntax ? maybe it will work ?

**Comment by Mike278** [comment]
```dart

double reliquat;

  reliquatCubit.reliquatDao.getSum(itemMedic).then((value) {
    reliquat = value;
  });
```

`double reliquat` will be null until the future completes, which will be after the widget is already built

**Comment by raedinkhaled** [comment]
> ```dart
> double reliquat;
> 
>   reliquatCubit.reliquatDao.getSum(itemMedic).then((value) {
>     reliquat = value;
>   });
> ```
> 
> `double reliquat` will be null until the future completes, which will be after the widget is already built

any option to fix that please ?

**Comment by raedinkhaled** [comment]
I just fixed that.. the problem was that I need to get the value using a FutureBuilder.. thank you everyone for your help
