### ISSUE TITLE
serialized names for the generated data class

### ISSUE THREAD

**Issue by ahmed56734** [simolus3/moor#84]
let's say I have a field in my json response called text
but I can't make a column in my table with name text.
then I won't be able to parse the json with fromJson method that genrated with the data class .

**Comment by simolus3** [comment]
Hi, it seems like the [`JsonKey`](https://pub.dev/documentation/moor/latest/moor_web/JsonKey-class.html) annotation could be useful to you. Let me know if you run into problems or have any questions, thanks!
