### ISSUE TITLE
Getting error in declaring a variable of type MyDatabae

### ISSUE THREAD

**Issue by chughrahul** [simolus3/moor#840]
I know that an argument is required but I don't know how to use it.

Constant file :

import 'package:RaxaFlutter/database/MyDatabase.dart';
static var myDatabase = MyDatabase();  //error : 1 positional argument expected

MyDatabase.dart:

class MyDatabase extends _$MyDatabase {
   MyDatabase(QueryExecutor e) : super(e);
}

**Comment by chughrahul** [comment]
web.dart :

import 'package:moor/moor_web.dart';

import '../MyDatabase.dart';

MyDatabase constructDb({bool logStatements = false}) {
  return MyDatabase(WebDatabase('app', logStatements: logStatements));
}


mobile.dart :

import 'dart:io';

import 'package:moor/ffi.dart';
import 'package:moor/moor.dart';

import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

import '../MyDatabase.dart';

MyDatabase constructDb({bool logStatements = false}) {
  
  if (Platform.isIOS || Platform.isAndroid) {
    final executer = LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'db.sqlite'));
    return VmDatabase(file);
    });
    return MyDatabase(executer);
  }
  if (Platform.isMacOS || Platform.isLinux) {
    final file = File('db.sqlite');
    return MyDatabase(VmDatabase(file, logStatements: logStatements));
  }
  return MyDatabase(VmDatabase.memory(logStatements: logStatements));
}

**Comment by simolus3** [comment]
You can take a look at [this project](https://github.com/rodydavis/moor_shared/tree/master/lib/src/database/database) for a working example that uses moor across multiple platform.

Your common method should probably look like this:

```dart
import 'package:RaxaFlutter/database/MyDatabase.dart';

var myDatabase = constructDb();
```

**Comment by chughrahul** [comment]
Thank you @simolus3 for help, it worked fine.
