### ISSUE TITLE
Will this library update changes, if I write to SQLite from another desktop app ?

### ISSUE THREAD

**Issue by krishnatejakanchi** [simolus3/moor#842]
I am writing a program in Julia which stores some values in the SQLite database. To listen to those values and see them in realtime, I am considering to write a desktop app. Is there any way that I can listen to every change my Julia program is making in a Flutter desktop app with moor?

**Comment by simolus3** [comment]
The stream mechanism built into moor only works with updates also issued by moor, not with other programs also writing to the database.

However, you could setup some other mechanism like IPC sockets for realtime communication between your Julia program and your desktop app. If your Julia program notifies your app about the tables it changed, you can call [`markTablesUpdated`](https://pub.dev/documentation/moor/latest/moor/QueryEngine/markTablesUpdated.html) to update streams listening on those tables.
