### ISSUE TITLE
Testing daos, errors with both mocking the database and VmDatabase.memory executor

### ISSUE THREAD

**Issue by seanmc86** [simolus3/moor#843]
EDIT: Tested with the stream example from https://moor.simonbinder.eu/docs/testing/ and my version also has the same closed database error. Both createMyUser() and updateUser() are simply an insert with InsertMode.replace, while watchMyUser() is a Stream<User> using select and watchSingle().

```
test('stream emits a new user when the name updates', () async {
    await database.userDao.createMyUser(User()
      ..id = '1'
      ..firstName = 'Bob');

    final expectation = expectLater(
      database.userDao.watchMyUser().map((user) => user.firstName),
      emitsInOrder(['Bob', 'Tom']),
    );

    await database.userDao.updateUser(
        User()
          ..id = '1'
          ..firstName = 'Tom',
        isMyUser: true);
    await expectation;
  });
```

Unsure if I'm doing this incorrectly or missing something, if someone can point me in the right direction.

I'm testing the Moor database within a blocTest (from the bloc_test package). I've tried to use VmDatabase.memory from the documentation, as well as a mock database with mockito:

```
class MockDatabase extends Mock implements LocalDatabase {}

void main() {
  MockDatabase mockDatabase;
  LocalDatabase database;

setUp(() {
    WidgetsFlutterBinding.ensureInitialized();
    database = LocalDatabase.test(VmDatabase.memory());
    mockDatabase = MockDatabase();
  });

tearDown(() async {
    await database.close();
  });
```

Where LocalDatabase.test is factory constructor:

```
  factory LocalDatabase.test(QueryExecutor e) {
    _instance ??= LocalDatabase.test_(e);
    return _instance;
  }
  LocalDatabase.test_(QueryExecutor e) : super(e);
```

And the UserDao is:

```
part 'user_dao.g.dart';

@UseDao(
  include: {'../tables.moor'},
)
class UserDao extends DatabaseAccessor<LocalDatabase> with _$UserDaoMixin {
```

Using the mock database yields an error of 

> NoSuchMethodError: The method 'getUser' was called on null

from:

```
blocTest<TestBloc, TestState>(
      'emits TestUser when user is not null',
      build: () {
        when(mockDatabase.userDao.getUser())
            .thenAnswer((_) async => User()..id = '1');

        return TestBloc(TestInitial());
      },
      act: (bloc) async {
        return bloc
            .add(TestLogin(mockDatabase));
      },
      expect: [TestUser(User()..id = '1')],
    );
```

Using the VmDatabase.memory (ie the database variable) yields an error of 

> ERROR Database createUser: Exception: This database has already been closed

from:

```
blocTest<TestBloc, TestState>(
      'emits TestUser when user is not null',
      build: () {
        return TestBloc(TestInitial());
      },
      act: (bloc) async {
        final user = await database.userDao.createUser(User()..id = '1');
        return bloc
            .add(TestLogin(database));
      },
      expect: [TestUser(User()..id = '1')],
    );
```

**Comment by simolus3** [comment]
The first `stream emits a new user when the name updates` test looks alright to me. In general, you shouldn't mock your database class though. Also, your `LocalDatabase.test` factory will only ever create a single instance. So when you dispose it, it will be gone for all tests. I would just create and dispose a new `LocalDatabase` for each test.

**Comment by seanmc86** [comment]
Okay, thank you. I think I had things confused and setting up a database instance that recreates itself for every test appears to be the solution.
