### ISSUE TITLE
SqliteException(26): file is not a database, file is not a database (code 26)

### ISSUE THREAD

**Issue by Sorunome** [simolus3/moor#846]
So, I've been randomly getting these errors when trying to open a database on start. I am not sure if this is moors issue, or maybe even the operation systems (lineage os).

```
I/flutter ( 8265): "SqliteException(26): file is not a database, file is not a database (code 26)"
I/flutter ( 8265): #0      throwException (package:sqlite3/src/impl/exception.dart:32)
I/flutter ( 8265): #1      PreparedStatementImpl.select (package:sqlite3/src/impl/statement.dart:59)
I/flutter ( 8265): #2      DatabaseImpl.userVersion (package:sqlite3/src/impl/database.dart:54)
I/flutter ( 8265): #3      _VmVersionDelegate.schemaVersion (package:moor/src/ffi/vm_database.dart:146)
I/flutter ( 8265): #4      DelegatedDatabase._runMigrations (package:moor/src/runtime/executor/helpers/engines.dart:263)
I/flutter ( 8265): #5      DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart:245)
I/flutter ( 8265): <asynchronous suspension>
I/flutter ( 8265): #6      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:34)
I/flutter ( 8265): <asynchronous suspension>
I/flutter ( 8265): #7      _MoorServer._handleEnsureOpen (package:moor/src/runtime/isolate/server.dart:74)
I/flutter ( 8265): <asynchronous suspension>
I/flutter ( 8265): #8      IsolateCommunication.setRequestHandler.<anonymous closure>.<anonymous closure> (package:moor/src/runtime/isolate/communication.dart)
```

On startup of the app we try to open the database. Sometimes randomly it says the file was not a database. Killing and re-opening the app fixes it quite often, but occasionally a full data wipe is needed. We do not use app store for anything else than moor, so this seems....odd.

It could also be that this is some Lineage OS issue as it seems to only have appeared after the last LOS update?

Any ideas of what might be going on?

**Comment by simolus3** [comment]
> Killing and re-opening the app fixes it quite often

Wait what? It's a file-based database, right? It sounds very strange that this would be fixed by restarting the process. Do you open the database on multiple threads at once? Maybe it's some threading issue that for some reason only happens on the latest update.

> It could also be that this is some Lineage OS issue

I assume it would hit others as well in that case, but so far I couldn't find anything.

**Comment by Sorunome** [comment]
> Wait what? It's a file-based database, right?

Yes, that is correct

> Do you open the database on multiple threads at once?

Nope, only one thread

So it sounds like this is probably not a moor issue but rather an issue with *something else* reading files either incorrectly or not at all?

**Comment by davidmartos96** [comment]
@Sorunome I don't know if that error can throw with SQLite but for sure it can with SQLCipher when using an incorrect password or file format.
Are you using SQLCipher?

**Comment by Sorunome** [comment]
We are using SQLCipher

We currently store the passphrase using [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage) and a few things hint to that module maybe not returning the right keys. Sorry for bothering and thank you for the help!

**Comment by Abhijit-Revamp** [comment]
Is there a way to capture this exception "file is not database" and handle gracefully ?
especially when using SQLCipher 

Can we have a function IsDatabase(file) to test before opening.

**Comment by simolus3** [comment]
The database is opened with the first query, so I imagine you could use something like `customQuery('SELECT 1');` to open it and catch that exception if necessary. If there's an exception, chances are it's not a proper database file.

You could also circumvent moor and use the lower-level apis for this, depending on which implementation you're using.
