### ISSUE TITLE
Unable to get data from customer select with stream

### ISSUE THREAD

**Issue by jesseframework** [simolus3/moor#849]
Hello,
I have a stream with customer select and am trying to get data from dart but am not seeing the column in the stream.

```dart
//This section calculate discount
  Stream<List<SalesOrderDetailTempData>> qtyOfItemOnRegister(
      String transactionNumber,
      String itemId,
      String uom,
      String transactionStatus) {
    return customSelect(
        'SELECT '
        ' Sum(quantity) as quantity, '
        ' Sum(subtotal) as subtotal,'
        ' transaction_number'
        ' FROM sales_order_detail_temp'
        ' where'
        ' transaction_number = ? '
        ' and item_id = ? '
        ' and uom = ? '
        ' and transaction_status = ? '
        ' group by'
        ' transaction_number,',
        readsFrom: {
          db.salesOrderDetailTemp
        },
        variables: [
          Variable.withString(transactionNumber),
          Variable.withString(itemId),
          Variable.withString(uom),
          Variable.withString(transactionStatus)
        ]
        // used for the stream: the stream will update when either table changes
        ).watch().map((rows) {
      return rows
          .map((row) => SalesOrderDetailTempData.fromData(row.data, db))
          .toList();
    });
  }
```

I try to get data using
```dart
var qty = salesOrderDetailTempDao.qtyOfAllItemsOnRegister(
        transactionNumber, itemId, uom, transactionStatus);
```
Quantity not show any of the column in the select event if i used `qty[0]` with an index.

**Comment by simolus3** [comment]
You have a trailing `,` in your query: `'transaction_number,'`. That will probably prevent the query from working, does the stream emit an error?

**Comment by jesseframework** [comment]
I remove that it now
`
//This section calculate discount
  Stream<List<SalesOrderDetailTempData>> qtyOfItemOnRegister(
      String transactionNumber,
      String itemId,
      String uom,
      String transactionStatus) {
    return customSelect(
        'SELECT '
        ' Sum(quantity) as quantity, '
        ' Sum(sub_total) as subtotal, '
        ' transaction_number'
        ' FROM sales_order_detail_temp'
        ' where'
        ' transaction_number = ? '
        ' and item_id = ? '
        ' and sales_u_o_m = ? '
        ' and transaction_status = ? '
        ' group by'
        ' transaction_number;',
        readsFrom: {
          db.salesOrderDetailTemp
        },
        variables: [
          Variable.withString(transactionNumber),
          Variable.withString(itemId),
          Variable.withString(uom),
          Variable.withString(transactionStatus)
        ]
        // used for the stream: the stream will update when either table changes
        ).watch().map((rows) {
      return rows
          .map((row) => SalesOrderDetailTempData.fromData(row.data, db))
          .toList();
    });
  }
`
And no am not getting any error. i just need to know how to get data out.

i try

 var qty = salesOrderDetailTempDao.qtyOfItemOnRegister(
                transactionNumber, itemId, uom, transactionStatus);
            print(qty.map((e) => e.single.quantity));

and get that
flutter: Instance of '_MapStream<List<SalesOrderDetailTempData>, double>'

**Comment by simolus3** [comment]
>  flutter: Instance of '_MapStream<List, double>'

That's because you're not printing items emitted by the stream, you're printing the stream itself. Can you try

```dart
qty.map((e) => e.single.quantity).listen(print, onError: (e, s) => print('Got error $e at $s'));
```

> i just need to know how to get data out.

You mean how to get the data out of the stream? You can use a [`StreamBuilder`](https://api.flutter.dev/flutter/widgets/StreamBuilder-class.html) widget in Flutter for that if you want to display data. In other scenarios, you could use [`Stream.listen`](https://api.dart.dev/stable/2.10.1/dart-async/Stream/listen.html).

**Comment by jesseframework** [comment]
Thank you very much.
