### ISSUE TITLE
How can I dump/inspect the database content?

### ISSUE THREAD

**Issue by mcavazotti** [simolus3/moor#850]
I want to debug my code, and I would like to know if is it possible to dump the database?

**Comment by simolus3** [comment]
Moor does not have builtin functionality for this. However, since moor databases are just regular SQLite database files, you can pull them from your device/emulator and inspect them locally.

**Comment by simolus3** [comment]
Moor does not have builtin functionality for this. However, since moor databases are just regular SQLite database files, you can pull them from your device/emulator and inspect them locally.
