### ISSUE TITLE
I should be able to opt-out of "Missing part" warning for DAOs

### ISSUE THREAD

**Issue by leecommamichael** [simolus3/moor#851]
### **My Problem**
I like DAOs, but **I don't like having a lot of generated files in my project**, it gets noisy when you have a lot of persistence categories.
### **My Solution**
So I've decided to remove the generated files and use an extension at the bottom of the file for the table getters. 
### **However**
```
[INFO] 31.2s elapsed, 87/102 actions completed.
[WARNING] moor_generator:moor_generator on lib/persistence/THING_persistence.dart:
Missing "part 'THING_persistence.g.dart';".
[INFO] 33.3s elapsed, 121/137 actions completed.
```
This is now in the log when I run build_runner. I considered turning my DAOs into plain classes that are given an instance of the database and live as fields on my database class. 

```dart
class Database extends _$GeneratedDatabase {
  final MyDao thing;
  Database(QueryExecutor q):
    this.thing = MyDao(this), 
    super();
}
```
Is this inadvisable/incompatible with the current/future functionality of `moor`?

**Comment by leecommamichael** [comment]
Also, does the array of Tables into the `@useDAO` annotation affect query functionality? Is it a kind of access-modifier for privilege? Or is it only ever going to be a way to inform the generator how to generate the mixin?

**Comment by simolus3** [comment]
The "missing part file" warning is actually generated by the `source_gen` package which moor uses internally. The warning does make sense when you want packages to generate part files.

In your case, you _don't_ want moor to generate part files for daos, and that's fine! Your approach works with the current functionality of moor, you just have to remove the `@UseDao` annotation from your daos. If you do that, the generator will stop complaining about missing part files. As long as you still inherit from `DatabaseAccessor`, they will still work.

> Or is it only ever going to be a way to inform the generator how to generate the mixin?

Yes, that's the only purpose of the `tables` list in the annotation. It does have an affect on visibility if you use [compiled custom queries](https://moor.simonbinder.eu/docs/using-sql/custom_queries/), but if you don't use them everything will be fine.

**Comment by leecommamichael** [comment]
> As long as you still inherit from `DatabaseAccessor`, they will still work.

**!** This is key for me.

Thank you so much for taking the time, not only to respond, but to give a thoughtful and caring response. So I'll keep extending from `DatabaseAccessor` and provide them to `@UseMoor`... and it worked! Thank you, Simon!
