### ISSUE TITLE
queries cannot be executed in Workmanager

### ISSUE THREAD

**Issue by TKalo** [simolus3/moor#855]
GOAL:
I am trying to pull a file from the internet, parse it with Json and save the results in my moor database.
This should be done on a schedule everyday, and so must run on Workmanager.

PROBLEM:
I can access the database in the Workmanager task, but queries to the database are never executed.

It's my understanding that running Moor with MoorIsolate is the way to go for background work.
I have, however, also tried without MoorIsolate with the same results

I don't usually report issues, so please forgive if I've missed something customary.

Thanks in advance

|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|

MOOR DATABASE:
```dart
@UseMoor(tables: [Events], daos: [EventDao])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(
    LazyDatabase(() async {
      final dbFolder = await getApplicationDocumentsDirectory();
      if (! await dbFolder.exists()) {
        await dbFolder.create(recursive: true);
      }
      final file = File(p.join(dbFolder.path, 'db.sqlite'));
      return VmDatabase(file);
    }),

  );

  AppDatabase.connect(DatabaseConnection connection) : super.connect(connection);

  @override
  int get schemaVersion => 2;
}
```

DATABASE PROVIDER:
```dart
class DatabaseProvider{

  static Future<AppDatabase> futureDatabase;

  DatabaseConnection backgroundConnection() {
    // construct the database. You can also wrap the VmDatabase in a "LazyDatabase" if you need to run
    // work before the database opens.
    final database = VmDatabase.memory();
    return DatabaseConnection.fromExecutor(database);
  }

  static Future<AppDatabase> createDatabase () async {
    return AppDatabase();
  }

  static Future<AppDatabase> getDatabase () async{
    if(futureDatabase == null){
      futureDatabase = createDatabase();
    }
    return futureDatabase;
  }
}
```

BACKGROUND TASK:
```dart
void callbackDispatcher() {
  print("callbackDispatcher");
  Workmanager.executeTask((task, inputData) async {
    switch (task) {
      case myTask:

        DatabaseProvider().backgroundConnection();
        MoorIsolate isolate = await MoorIsolate.spawn((){return DatabaseProvider().backgroundConnection();});
        DatabaseConnection connection = await isolate.connect();
        AppDatabase db = AppDatabase.connect(connection);
        db.eventDao.deleteAllEvents();

        break;
    }

    return Future.value(true);
  });
}
```

|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|

**Comment by simolus3** [comment]
Well, if you're using a `VmDatabase.memory` you're not going to see anything written since it will never be saved to a file. In `backgroundConnection`, you'd also have to use the `db.sqlite` stored in the documents directory.

If you don't need real-time communication, you also don't have to use a `MoorIsolate`. You could just use a regular `AppDatabase()` in the `callbackDispatcher` too.

**Comment by TKalo** [comment]
Thanks for the quick response!

if I understand correctly, this should work:

````dart

void callbackDispatcher() {
  print("callbackDispatcher");
  Workmanager.executeTask((task, inputData) async {
    switch (task) {
      case myTask:

        //this should work?
        DatabaseProvider.getDatabase().then((database){database.eventDao.deleteAllEvents();});

        break;
    }

    return Future.value(true);
  });
}
````

here I simply use the AppDatabase, which does reference the SQLite file.
I had, however, tried this without success, which led me to think the MoorIsolate was the missing link.
(the database does work outside the callbackDispatcher by the way

**Comment by TKalo** [comment]
I managed to fix my issue after many different troubleshoots. To my great regret, I wasn't able to pinpoint what had gone wrong or what finally made it work.

**Comment by firatcetiner** [comment]
@TKalo How do you manage to ensure that you are using the same AppDatabase() instance?

**Comment by zagori** [comment]
> 

Hi all,

I am facing a same issue which involves **real-time-communication**.  

I have a stream on main-thread listening to changes in a TableA. Meanwhile, the workmanager started a process in isolate to update data in TableA.

**Problem**:
The stream is not triggered after data is updated in isolate

**Goal**: 
When data in TableA is updated in isolate, the main-thread stream should be able to receive the updated raws.

Please advise if you have any solution to such case. Appreciate it in advance. Thanks.
