### ISSUE TITLE
List<TypedResult> are empty

### ISSUE THREAD

**Issue by kira1752** [simolus3/moor#858]
So i tried to follow moor documentation about `Group by` with slight modification that suits my scenario (i only change `get()` with `watch()` for reactive purpose) but somehow the `List<TypedResult>` that returned by `StreamBuilder()` are empty. I didn't have any idea why this happened. Well this is my code:
```dart
 Stream<List<TypedResult>> watchFolderWithCount() {
    /// notes is your usual table that basically store note id and folder id
    /// for simple example purpose
    final notesCount = notes.id.count();

   /// folderNote is your usual table that basically store folder id and folder name
   /// for simple example purpose
    final query = select(folderNote).join([
      innerJoin(
        notes,
        notes.folderID.equalsExp(folderNote.id),
        useColumns: false
      )
    ]);

    query
      ..addColumns([notesCount])
      ..groupBy([folderNote.id]);

    /// i replace get() with watch() for reactive purpose
    final result = query.watch();

    return result;
  }
```

**Comment by simolus3** [comment]
Hm, your code looks alright to me though. I assume it also returns an empty list if you use `get()`? Is there an error reported through `snapshot.error` in the `StreamBuilder`?

**Comment by kira1752** [comment]
i'm sorry, my bad. Join query is actually works, it just didn't work as i expected but nonetheless it's perfectly works after some modification in my query. Thanks for your fast respond and thank for your great works @simolus3. 

I'll close this issue.
