### ISSUE TITLE
Extension on ColumnBuilder not working

### ISSUE THREAD

**Issue by Abdktefane** [simolus3/moor#859]
i have many table had user relation so i create extension to add them for more code readable :
```dart
extension ColumnBuilder_<Builder, ResultColumn extends Column<ResultDartType>,
    ResultDartType> on ColumnBuilder<Builder, ResultColumn, ResultDartType> {
  Builder addUserRelation({bool nullable = false}) {
    return this.customConstraint(
      '${nullable ? 'NULL' : ''} REFERENCES users(id) ON DELETE CASCADE');
  }
}
```
and now i use it like that 
```dart 
abstract class UserEntry extends BaseEntity {
  IntColumn get userId => integer().named('user_id').addUserRelation()();
}
```
and when i delete the user from database all entry with reference on it still in database
but when change it like that work fine 
```dart 
abstract class UserEntry extends BaseEntity {
  IntColumn get userId => integer()
      .named('user_id')
      .customConstraint('REFERENCES users(id) ON DELETE CASCADE')();
}
```
am I doing it wrong or is there a bug ?

**Comment by simolus3** [comment]
Unfortunately moor does not support that approach. It has to know the table structure at compile time, so it just looks at the source code to see what's going on. It doesn't actually run the column builders, so complicated control flow like extensions won't work.

If all tables referencing `User` have a column named `userId`, you can extract that into a mixin:

```dart
mixin UserReference on Table {
  IntColumn get userId => integer().named('user_id').customConstraint('NOT NULL REFERENCES users(id) ON DELETE CASCADE')();
}


mixin NullableUserReference on Table {
  IntColumn get userId => integer().nullable().named('user_id').customConstraint('REFERENCES users(id) ON DELETE CASCADE')();
}
```

Then, you could use `abstract class UserEntity extends BaseEntity with UserReference` for instance.
