### ISSUE TITLE
Export SqliteException

### ISSUE THREAD

**Issue by Mike278** [simolus3/moor#860]
When dropping `package:moor_ffi/moor_ffi.dart` in favour of `package:moor/ffi.dart`, I noticed `SqliteException` and a few other types that were previously [exported by moor_ffi](https://github.com/simolus3/moor/blob/master/moor_ffi/lib/database.dart#L11) are no longer available. We're only using ffi for tests so adding `export 'package:sqlite3/sqlite3.dart' show SqliteException;` to our main test file works fine (I guess you can import transitive dependencies? surprised there's no warning about that), but figured I'd make an issue!

**Comment by simolus3** [comment]
Thanks for the suggestion. However, I'm not sure if we should export those types from `package:moor/ffi.dart`. The old `package:moor_ffi/moor_ffi.dart` didn't export those types either, only `moor_ffi/database.dart` did. The successor of that library is `package:sqlite3/sqlite3.dart` which is pointed out by the deprecation notice. I assume you had to import both `moor_ffi.dart` and `database.dart` before too?

**Comment by Mike278** [comment]
Hmm I see - I think this issue is specifically about exception catching then.

So `package:moor` now provides its own `QueryExecutor` that runs on the Dart VM (`VmDatabase`), and the fact it uses `package:sqlite3` internally is an implementation detail. I think that makes sense, but currently users still have to depend on `package:sqlite3` directly if they want to catch exceptions thrown by `VmDatabase`. Maybe `VmDatabase` should catch those exceptions and rethrow them as a new type that's exported by `package:moor/ffi.dart`?

I guess we've only noticed this in tests because we're specifically referencing the type in the `on ... catch` clause. I think `package:moor_flutter`'s exceptions have a similar issue, but we don't use specific `on SomeType catch` clauses since `sqflite`'s exceptions are [at the mercy of the platform's implementation](https://github.com/tekartik/sqflite/issues/383) (currently we do stuff like `error.toString().toLowerCase().contains('not null constraint failed')`).

**Comment by simolus3** [comment]
> Maybe` VmDatabase` should catch those exceptions and rethrow them as a new type that's exported by `package:moor/ffi.dart`?

Good point. Ideally, there should be some common exception thrown by moor when the underlying engine throws, but that's a breaking change that would require a major release and announcement.

I also agree that the thrown exception shouldn't be an implementation detail, so I'll export `SqliteException` from `package:moor/ffi.dart` until we have something better.
