### ISSUE TITLE
Why Tables can't override primaryKey when using autoIncrement() after rebuilding

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#862]
<details>
	  <summary>After I execute this</summary>
	  flutter packages pub run build_runner build --delete-conflicting-outputs
</details>

![image](https://user-images.githubusercontent.com/1920873/95668700-10416880-0baa-11eb-9d22-3c668e05a060.png)

My version of moor as follows:
![image](https://user-images.githubusercontent.com/1920873/95668871-120c2b80-0bac-11eb-89c0-af9ab55b92c8.png)

**Comment by simolus3** [comment]
In sqlite3, `AUTOINCREMENT` requires that that column is the single primary key. So if you use `autoIncrement()` in moor, that column will be the primary key by default. Thus, using both `autoIncrement()` and a custom `primaryKey` could cause conflicts which is why it's not allowed by the generator.

**Comment by muhammadfaheem-pycom** [comment]
so what is the solution? is it means we should not override id as a primary key?

**Comment by simolus3** [comment]
Yes, you can't use `autoIncrement()` _and_ a custom `primaryKey` override. If you need `autoIncrement()` and another key, I would look into a `UNIQUE` table constraint. If your primary key is just the id, you don't need to override `primaryKey` at all.

**Comment by robinjohn** [comment]
`autoIncrement() on any column means it is taken as Primary Key by default and no need to override primaryKey`
Preferably helps and worth to mention this in the README doc. 
No build error in the past, so many would face this as a new error while running build_runner after long time. 

Thanks.

**Comment by simolus3** [comment]
The documentation of both `primaryKey` and `autoIncrement` point this out now.

>  No build error in the past, so many would face this as a new error while running build_runner after long time.

It has always been a problem, it just failed silently before. I think that making this an error is better than just ignoring the `primaryKey` override.
