### ISSUE TITLE
How to update table structure after deploying an app

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#863]
![image](https://user-images.githubusercontent.com/1920873/95668734-7d54fe00-0baa-11eb-9932-49ec75830c80.png)

**Comment by jesseframework** [comment]
You have to setup your migration in the app. You can look at https://resocoder.com/2019/07/17/moor-room-for-flutter-3-foreign-keys-joins-migrations-fluent-sqlite-database/ for help. or you can try this example from 

`
@override
  MigrationStrategy get migration => MigrationStrategy(
          // Runs if the database has already been opened on the device with a lower version
          onUpgrade: (doMigration, from, to) async {
        if (from == 2) {
          //await migrator.addColumn(tasks, tasks.tagName);
          //await doMigration.createTable(ApplicationLogger);
        }

        // ignore: unnecessary_statements
        (db, details) async {
          await db.customStatement(
              'PRAGMA foreign_keys = ON ' + 'PRAGMA journal_mode=WAL');
        };
      }, beforeOpen: (details) async {
        if (details.wasCreated) {
          String systemDate = await formatDate(DateTime.now().toString());
          await into(backgroundJobSchedule).insert(BackgroundJobScheduleData(
              id: 1,
              jobName: "Mobile Desktop",
              startDateTime: DateTime.tryParse(systemDate),
              syncFrequency: "Every 20 Minutes",
              enableJob: true,
              lastRun: DateTime.tryParse(systemDate),
              jobStatus: "Never Run"));
          await into(backgroundJobSchedule).insert(BackgroundJobScheduleData(
              id: 2,
              jobName: "Configuration",
              startDateTime: DateTime.tryParse(systemDate),
              syncFrequency: "Every 20 Minutes",
              enableJob: true,
              lastRun: DateTime.tryParse(systemDate),
              jobStatus: "Never Run"));
          await into(backgroundJobSchedule).insert(BackgroundJobScheduleData(
              id: 3,
              jobName: "Log Shipping",
              startDateTime: DateTime.tryParse(systemDate),
              syncFrequency: "Every Day",
              enableJob: true,
              lastRun: DateTime.tryParse(systemDate),
              jobStatus: "Never Run"));

          await into(seriesNumberGenerator).insert(SeriesNumberGeneratorData(
              id: 1,
              includeJulianDate: false,
              includePrefix: false,
              includeUserID: false,
              includeTenantId: false,
              usedAutoNumber: false,
              numberPrefix: "SO",
              endingLength: 8,
              typeOfNumber: "Sales Order"));
          await into(seriesNumberGenerator).insert(SeriesNumberGeneratorData(
              id: 2,
              includeJulianDate: false,
              includePrefix: false,
              includeUserID: false,
              includeTenantId: false,
              usedAutoNumber: false,
              numberPrefix: "INV",
              endingLength: 8,
              typeOfNumber: "Invoice"));
        }
      });`
Or look at the code in github
https://github.com/jesseframework/j3/blob/dev/lib/src/database/moor_database.dart

**Comment by simolus3** [comment]
Yes, you should follow the existing documentation on [migrations](https://moor.simonbinder.eu/docs/advanced-features/migrations/) or examples from others.

At the moment we only support adding new columns through the `Migrator` api, but in the next moor version we'll support more complex migrations too. Please let me know if you have a specific question on migrations, otherwise I'll close this issue.

**Comment by muhammadfaheem-pycom** [comment]
DO I need to run the generator again?

**Comment by simolus3** [comment]
After making changes to your tables? Yes, definitely.
