### ISSUE TITLE
How to write DateTimeColumn with default value as now() timestamp? 

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#865]
![image](https://user-images.githubusercontent.com/1920873/95669007-b3e04800-0bad-11eb-9c69-7e81c8d8edde.png)

**Comment by jims57** [comment]
I fixed it, by using **DateTime.now()**. Thanks anyway.

` DateTimeColumn get created =>dateTime().withDefault(Constant(DateTime.now())).named('created')();`

**Comment by simolus3** [comment]
> I fixed it, by using `DateTime.now()`. Thanks anyway.

This would use the time the database was opened as a default value, not the time at which a row was inserted. You could use `withDefault(currentDateAndTime)` if you needed that.

**Comment by jims57** [comment]
@simolus3 I realized this potential bug, haha. 

I have checked this issue [#26](https://github.com/simolus3/moor/issues/26#issuecomment-494815604), that case is for **DateTimeColumn**, as your suggestion above should work.

But, my precondition is that I use TextColumn to store date and time because of this issue [#871](https://github.com/simolus3/moor/issues/871#issuecomment-707865235) as you has suggested.

When I try to use it it show the following error:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/1920873/96072862-d2a94c00-0ed7-11eb-9c1b-e309a033fb09.png">

I also tried to use **toString()**, but the sqlite data doesn't store the right date and time, but a string.
<img width="668" alt="image" src="https://user-images.githubusercontent.com/1920873/96072935-f8365580-0ed7-11eb-8556-8b95051887f7.png">


Thanks.

**Comment by simolus3** [comment]
One option would be to use `clientDefault`. You can define a Dart function to return the current time as a string:

```dart
String _currentTime() {
  return const IsoDateTimeConverter().mapToSql(DateTime.now());
}
```

And then use it in your table:

```dart
TextColumn get created => text().clientDefault(_currentTime).map(const IsoDateTimeConverter());
```

Moor will run `_currentTime()` everytime you insert a new row, so you can use that to fill in the default value.

**Comment by glenfordwilliams** [comment]
@simolus3 how can i get this to work using moor files?

**Comment by jims57** [comment]
> One option would be to use `clientDefault`. You can define a Dart function to return the current time as a string:
> 
> ```dart
> String _currentTime() {
>   return const IsoDateTimeConverter().mapToSql(DateTime.now());
> }
> ```
> 
> And then use it in your table:
> 
> ```dart
> TextColumn get created => text().clientDefault(_currentTime).map(const IsoDateTimeConverter());
> ```
> 
> Moor will run `_currentTime()` everytime you insert a new row, so you can use that to fill in the default value.

Good job, it works, thanks.

**Comment by Saleh-Marji** [comment]
Why don't you use the column as a dateTime Column
like so:
```dart
DateTimeColumn get created => dateTime().generatedAs(currentDateAndTime, stored: true)();
```

**Comment by AllinProgram** [comment]
Through [official documents](https://drift.simonbinder.eu/docs/getting-started/advanced_dart_tables/#default-values) and source code analysis, the correct usage should be:

```dart
// the hour, minute and second fields will be set to null. 
DateTimeColumn get gmtCreate => dateTime().withDefault(currentDate)();
// current date and time, like [DateTime.now]
DateTimeColumn get gmtCreate => dateTime().withDefault(currentDateAndTime)();
```
