### ISSUE TITLE
Moor + isolates - Problem with transaction

### ISSUE THREAD

**Issue by Complay** [simolus3/moor#867]
Hello,

I'm trying to use Moor with isolates (following this tutorial: https://moor.simonbinder.eu/docs/advanced-features/isolates/#initialization-on-the-main-thread). Everything works as expected, except transactions. While i'm using them, i'm getting error below:

> Unhandled Exception: "Invalid argument (transactionId): Does not reference a transaction: null"
> 
>     #0      _MoorServer._transactionControl (package:moor/src/runtime/isolate/server.dart:136:7)
>     #1      _MoorServer._handleRequest (package:moor/src/runtime/isolate/server.dart:66:14)
>     #2      IsolateCommunication.setRequestHandler.<anonymous closure> (package:moor/src/runtime/isolate communication.dart:163:31)
>     #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)
>     #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
>     #5      _DelayedData.perform (dart:async/stream_impl.dart:611:14)
>     #6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
>     #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
>     #8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
>     #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
>     #10     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
>     #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

Thanks in advance.

**Comment by simolus3** [comment]
Thanks for reporting this issue. Since we have tests for transactions in isolates, I'll need more information to reproduce this. It could also be an issue on your side, can you check that you're awaiting everything in a transaction?

**Comment by Complay** [comment]
Thanks for the reply. I figured out that the queries were await-ed, but they were in a not await-ed forEach loop.

**Comment by simolus3** [comment]
Yeah, the problem with something like `list.forEach((element) async {})`  is that the inner futures generated by the callback can never be awaited. You'd have to use `Future.wait(list.map((element) async {}))` or a regular for-loop. If you're generating lots of statements with `forEach`, you could also use a `batch` which bundles synchronously-generated queries.

> but they were in a not await-ed forEach loop

Just to be sure, did awaiting them fix your problem? Can we close this issue? I also improved the error message to point out that the probably cause are unawaited operations.

**Comment by Complay** [comment]
Thank You for help. Everything works perfectly;)
