### ISSUE TITLE
How to define foreign key for tables

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#869]
As you can see, table **Notes** has a field called **folderId** which should use the **id** of **Folders** table as a **Foreign Key**. How can I define a foreign key for **folderId** field. Thanks.

```dart
@DataClassName('FolderEntry')
class Folders extends Table {
  IntColumn get id => integer().autoIncrement()();

  TextColumn get name => text().withLength(min: 1, max: 200)();
}

@DataClassName('NoteEntry')
class Notes extends Table {
  IntColumn get id => integer().autoIncrement()();

  IntColumn get folderId =>
      integer().withDefault(const Constant(3)).named('folderId')();

  TextColumn get title => text().withLength(min: 2, max: 200)();

  TextColumn get content => text().nullable()();

  DateTimeColumn get created =>
      dateTime().withDefault(Constant(DateTime.now()))();
}
```

**Comment by simolus3** [comment]
Moor doesn't support foreign key constraints in its Dart api yet. However, you can implement them with [custom constraints](https://develop--moor.netlify.app/docs/getting-started/advanced_dart_tables/#custom-constraints) on columns. You'll also need to enable the `foreign_keys` pragma in a [`beforeOpen` callback](https://develop--moor.netlify.app/docs/advanced-features/migrations/#post-migration-callbacks).

Let me know if that doesn't solve your problem, I'll re-open this issue then.
