### ISSUE TITLE
Moor files

### ISSUE THREAD

**Issue by ngxingyu** [simolus3/moor#872]
Under the nested result section, I believe this should be t instead of f
routesWithPoints: SELECT r.id, r.name, f.*, t.* FROM routes r
  INNER JOIN coordinates f ON f.id = r."from"
  INNER JOIN coordinates t ON **f**.id = r.to; // Change to t.

**Comment by simolus3** [comment]
Indeed, thanks! I've fixed this, the changes will be visible when the next moor version comes out.
