### ISSUE TITLE
calling Order by in join statement

### ISSUE THREAD

**Issue by Ara-95** [simolus3/moor#873]
I have the same issue like raphmte https://github.com/simolus3/moor/issues/36 had but you demonstrate how to solve that issue with where statement please can you help me to solve mine issue but this time is with order by I tried all the way you talked about in the raphmte issue but it did not work for me?

I wrote my code as this:
![image](https://user-images.githubusercontent.com/57654300/95949662-d5cf0a00-0dfb-11eb-9596-50322733fd45.png)

 and my error is:
![image](https://user-images.githubusercontent.com/57654300/95949458-6822de00-0dfb-11eb-9e6a-e729b165cfea.png)

thanks for your helping

**Comment by simolus3** [comment]
If you call `orderBy` after calling `join`, you don't need to pass a function, you can just provide the `OrderingTerm` directly:

```dart
..orderBy([OrderingTerm(expression: t.name)])
```

**Comment by Ara-95** [comment]
but if you don't pass the function how do you get the t parameter? like you did in OrderingTerm.

**Comment by simolus3** [comment]
You're right, it should be `incomes.name`.

>thanks for your time
thanks for your greateful library

Thank you :blush:
