### ISSUE TITLE
SELECT EXISTS query — cannot get result

### ISSUE THREAD

**Issue by SteveAlexander** [simolus3/moor#874]
What's a good way to do `SELECT EXISTS (SELECT 1 from tablename WHERE primarykey="something"` from Dart?

I've tried using a `customSelect`, but although the Select runs, there's no way to get the result out, as Moor isn't able to map the result type (`type_system.dart`). Which seems a bit odd, as it's getting a `1` or `0` back, which I can see when I use the debugger in `variables.dart` — value is `1`.

```dart
  dynamic mapToSimpleValue(GenerationContext context) {
    final type = context.typeSystem.forDartType<T>();
    return type.mapToSqlVariable(value);
  }
```

The reason I'm doing this is that this kind of query seems to be the canonical way to check existence of a row by primary key, for Sqlite: (links to a note from the Sqlite authors)

  https://stackoverflow.com/questions/9755860/valid-query-to-check-if-row-exists-in-sqlite3

**Comment by SteveAlexander** [comment]
If I add the query in the `@UseMoor` annotation, I get a warning:

```
[INFO] moor_generator:moor_generator on lib/sync/database.dart:Lint for itemExistsImpl: line 1, column 8: Expression has an unknown type, the generated code can be inaccurate.
  ╷
1 │ SELECT EXISTS(SELECT 1 FROM items WHERE base=? and path=?);
  │        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

However, the code works — I get a `List<String> ['0']` or `['1']` back from the `itemExistsImpl` method.

I guess both approaches would work okay if Moor understood that `SELECT EXISTS` returns an integer.

**Comment by kuhnroyal** [comment]
You can try to cast it in the `@UseMoor` annotation:
```sql
SELECT (CAST(EXISTS(SELECT 1 FROM items ...) AS BOOLEAN));
```

**Comment by SteveAlexander** [comment]
Thanks, that works in `@useMoor`.

I also thought it might work in the `customSelect`, but it doesn't — even with the `cast`, Moor is still confused about its type when getting the results.

**Comment by simolus3** [comment]
> If I add the query in the `@UseMoor` annotation, I get a warning

This is a bug (or rather, a case I overlooked) in the `sqlparser` package. It will be fixed in the next moor version, thanks for the report!

> Moor is still confused about its type when getting the results.

Can you post your `customSelect` usage? I haven't tried it, but I imagine that something like this should work:

```dart
final bool hasItems = customSelect(
  'SELECT EXISTS (SELECT 1 FROM items WHERE base = ? AND path = ?) AS r',
  variables: [Variable.withInt(1), Variable.withInt(2)],
).map((row) => row.readBool('r')).getSingle();
```

**Comment by kuhnroyal** [comment]
I have in the past used something like this:
```dart
import 'package:moor/moor.dart';

class ExistsStatement<T extends Table, D extends DataClass> extends Query<T, D>
    with
        SingleTableQueryMixin<T, D>,
        // ignore: prefer_mixin
        Selectable<bool> {
  ExistsStatement(QueryEngine database, TableInfo<T, D> table) : super(database, table);

  @override
  Future<List<bool>> get() async {
    final ctx = constructQuery();
    return _getWithQuery(ctx);
  }

  Future<List<bool>> _getWithQuery(GenerationContext ctx) async {
    final exists = await ctx.executor.doWhenOpened((e) async {
      final result = await e.runSelect(ctx.sql, ctx.boundVariables);
      return result.first.values.first == 1;
    });
    return [exists];
  }

  @override
  Stream<List<bool>> watch() {
    throw UnimplementedError('Watching exists queries is not implemented!');
  }

  @override
  void writeStartPart(GenerationContext ctx) {
    ctx.buffer.write('SELECT EXISTS (SELECT 1 FROM ${table.tableWithAlias}');
  }

  @override
  GenerationContext constructQuery() {
    final ctx = GenerationContext.fromDb(database);
    var needsWhitespace = false;

    writeStartPart(ctx);
    needsWhitespace = true;

    if (whereExpr != null) {
      if (needsWhitespace) {
        ctx.writeWhitespace();
      }

      whereExpr.writeInto(ctx);
      needsWhitespace = true;
    }

    ctx.buffer.write(');');
    return ctx;
  }
}

```

**Comment by SteveAlexander** [comment]
@simolus3 thanks

The following `customSelect` works for me.

```dart
  Future<bool> itemExists(int baseId, String path) async {
    final QueryRow row = await customSelect(
      'SELECT EXISTS (SELECT 1 FROM items WHERE base = ? AND path = ?) AS r',
      variables: [Variable.withInt(baseId), Variable.withString(path)],
    ).getSingle();
    return row.readBool('r');
  }
```

**Comment by simolus3** [comment]
Great! I'll close this issue then, `EXISTS` missing from the Dart api is roughly covered by #612.
