### ISSUE TITLE
How can I return a Stream from a chained query?

### ISSUE THREAD

**Issue by jasonctoms** [simolus3/moor#878]
I come from a NoSQL background so I am very much a SQL noob.  It is possible my design/thought process is totally wrong but maybe somebody can help to point me in the right direction.

I have a Parent table and a Child table.  A Parent can have multiple Children but a Child can only have one Parent. I have my tables defined like so (for example):

```
class Parents extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  BoolColumn get active => boolean()();
}

class Children extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  IntColumn get parentId => integer().nullable().customConstraint('NULLABLE REFERENCES parents(id)')();
}
```

The problem comes when I want to get a Stream<List<Child>>.  I need to query for the id of the active parent and then query for the children using that id.  I had no problems doing that to add a new child, but  I can't figure out what I need to do to for the query.

```
  Future<Parent> get activeParent {
    return (select(parents)
          ..where((c) => c.active)
          ..limit(1))
        .getSingle();
  }

  Future addChild(String name) {
    return transaction(() async {
      var parent = await activeParent;
      await into(notes).insert(ChildrenCompanion(
          name: Value(name), parentId: Value(parent.id)));
    });
  }

  //this obviously does not work and is wrong
  Stream<List<Child>> get currentChildren {
    transaction(() async {
      var parent = await activeParent;
      return (select(children)..where((n) => n.parentId.equals(parent.id))).watch();
    });
  }
```

I am too much of an SQL noob to know if my approach is totally wrong, or if I just don't know the syntax for what I am trying to do.  Any guidance is very appreciated!

**Comment by simolus3** [comment]
Logically, you'll want to select all children whose parent is `active` at the moment. In SQL, you could include the parent with a join and then check whether the parent is active or not:

```sql
SELECT children.* FROM children
  INNER JOIN parents ON children.parentId = parents.id
WHERE parents.active
```

In moor, you could write that query like this:

```dart
Stream<List<Child>> get currentChildren {
  final query = select(children).join([innerJoin(parents, parents.id.equalsExp(children.id), useColumns: false)]);
  query.where(parents.active);

  return query.map((row) => row.readTable(children)).watch();
}
```

The `useColumns: false` tells moor not to include the `parent` table in the results, since it's only needed for the where clause.

**Comment by jasonctoms** [comment]
Thanks so much! I thought I needed an inner join, but kept getting stuck on the fact that I didn't need anything from the parents table in the result.  I really appreciate the quick help.
