### ISSUE TITLE
Singleton instance of database

### ISSUE THREAD

**Issue by josephmtinangi** [simolus3/moor#882]
How can I create a single instance of database so that I can store that instance in a global variable and use it anywhere?

**Comment by simolus3** [comment]
Uh, you can just store it in a global variable?

```dart
final MyDatabase db = MyDatabase(LazyDatabase(() async {
  // ...
  return VmDatabase(...);
}));

class MyDatabase extends _$MyDatabase {
  MyDatabase._(QueryExecutor e): super(e);
}
```

This and other approaches are also explained in [the documentation](https://moor.simonbinder.eu/faq/#using-the-database).

**Comment by josephmtinangi** [comment]
Like this?

`class Globals {
  static AppDatabase appDatabase = AppDatabase();
}
`

**Comment by josephmtinangi** [comment]
thanks
