### ISSUE TITLE
How to query all these rows which are smaller or equal Today based on their TextColumn field.

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#887]
According to this [reply](https://github.com/simolus3/moor/issues/871#issuecomment-708113686), you suggest me to use `like` to query these rows for today.

I used `TextColumn` to store date time because of this [bug #871 ](https://github.com/simolus3/moor/issues/871)

like this:
```dart
TextColumn get created => text().map(const IsoDateTimeConverter())();
```

What should I do if I want to get all these rows whose `created` field, storing date and time,  are smaller or equal today?

I need all these rows to be queried, i.e, today is **2020-10-21**.
<img width="635" alt="image" src="https://user-images.githubusercontent.com/1920873/96672597-3ed3f600-1397-11eb-8bad-5ecdc8ae85c9.png">

**Comment by simolus3** [comment]
In the next moor version, you'll be able to do this:

```dart
extension ParseDateInSql on Expression<String> {
  /// Returns the unix timestamp of the start of the day represented by this formatted date time
  Expression<int> startOfDayUnix() {
    // generate strftime('%s', date(formattedString)), then cast to int
    return FunctionCallExpression<String>(
      'strftime',
      [
        const Constant<String>("%s"),
        FunctionCallExpression('date', [this]),
      ],
    ).cast();
  }
}
```

Unfortunately, `.cast()` is not available in the current version. But with that, you could use

```dart
final today = Constant<String>(const IsoDateTimeConverter().mapToSql(DateTime.now())).startOfDayUnix();
someQuery.where((row) => row.created.startOfDayUnix().isSmallerOrEqual(today));
```

**Comment by jims57** [comment]
@simolus3 Thanks for your reply. Since the current version doesn't support `.cast()`. Should I do nothing but wait for your update? 

Please tell me when the next version support `.cast()` will be released.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/1920873/96816791-85d1f200-1450-11eb-8963-9d232537a025.png">


I think this kind of query is very important, thanks.

Do you have any alternative solution to this query before the next version is released.

The version I am using as follows:
```yaml
  moor: ^3.3.0
  moor_ffi: ^0.8.0
```

**Comment by simolus3** [comment]
I hope to release the update this week, but until then you could use

```dart
class _DateTimeToStartOfDay extends Expression<int> {
  final Expression<String> _inner;

  _DateTimeToStartOfDay(this._inner);

  @override
  void writeInto(GenerationContext context) {
    context.buffer.write("CAST(strftime('%s', date(");
    _inner.writeInto(context);
    context.buffer.write(')) AS INT)');
  }
}

extension ParseDateInSql on Expression<String> {
  Expression<int> startOfDayUnix() => _DateTimeToStartOfDay(this);
}

```

**Comment by jims57** [comment]
Is the new version released? I am waiting for it. Thanks.

> I hope to release the update this week, but until then you could use
> 
> ```dart
> class _DateTimeToStartOfDay extends Expression<int> {
>   final Expression<String> _inner;
> 
>   _DateTimeToStartOfDay(this._inner);
> 
>   @override
>   void writeInto(GenerationContext context) {
>     context.buffer.write("CAST(strftime('%s', date(");
>     _inner.writeInto(context);
>     context.buffer.write(')) AS INT)');
>   }
> }
> 
> extension ParseDateInSql on Expression<String> {
>   Expression<int> startOfDayUnix() => _DateTimeToStartOfDay(this);
> }
> ```

**Comment by simolus3** [comment]
Yes, this was a part of moor `3.4.0` which is out on pub.
