### ISSUE TITLE
How to write conditional order by in a single query

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#890]
My scenario is that I'd like to `orderBy isReviewFinished asc` first  to make these items which still don't finish reviewing to be shown before those items finishing their review.

For those review finished items, in the secondary clause, I want to  `orderBy updated desc`, whereas those items which don't finish their review, I want to `orderBy nextReviewTime asc`.

All of this above should be queried in a single query. Can you tell me if **moor** will be able to do this like that? 

Thanks.

<img width="624" alt="image" src="https://user-images.githubusercontent.com/1920873/96817514-12c97b00-1452-11eb-9c36-a1293f872e6a.png">

**Comment by simolus3** [comment]
Hm, I'm not sure how one would write this in a single SQL query. The following seems to work, but I don't know if `UNION ALL` is guaranteed to keep the order of its subqueries:

```sql
WITH
  finished AS (SELECT * FROM tbl WHERE isReviewFinished ORDER BY updated DESC),
  not_finished AS (SELECT * FROM tbl WHERE NOT isReviewFinished ORDER BY nextReviewTime ASC)
SELECT * FROM not_finished UNION ALL SELECT * FROM finished
```

You could use a `customSelect` to run the query above.
