### ISSUE TITLE
Long batch query fails to respond on ios

### ISSUE THREAD

**Issue by lex-github** [simolus3/moor#894]
Hello, i am using `moor:^3.3.1` in my flutter project. I'm trying to insert a large number of entities in a batch query with conditional deletion beforehand. On iOS the result of batch operation never gets `awaited` with no errors thrown. The last message in console is `Moor: Sent ROLLBACK TRANSACTION with args []`. 
The problem probably is connected to sqlite version which is `3.28.0`, because the query executes on android. Maybe it hits maximum query length - the problem occurs starting at 1000 entities. 
Batch itself (the problem reproduces even without `insertAll` part):
```
await batch((batch) {
  batch.deleteWhere(
      translations,
      ($TranslationsTable t) => insert.fold(
          t.id.isIn(ids),
          (expression, x) =>
              expression |
              t.learningWordId.equals(x.learningWordId.value) &
                  t.language.equals(x.language.value)));
  batch.insertAll<$TranslationsTable, Translation>(translations, insert);
});
```

Regardless of internal limits it would be nice for `await batch` to complete and not hang. 
All good with:

```
await batch((batch) {
  for (int from = 0; from < insert.length; from += maxBatchLength) {
    final int to = min(from + maxBatchLength, insert.length - 1);
    final insertBatch = insert.getRange(from, to).toList(growable: false);
    final List<int> ids = insertBatch.map((item) => item.id.value).toList(growable: false);

    batch.deleteWhere(
        translations,
        ($TranslationsTable t) => insertBatch.fold(
            t.id.isIn(ids),
            (expression, x) => expression |
                t.learningWordId.equals(x.learningWordId.value) & t.language.equals(x.language.value)));
    batch.insertAll<$TranslationsTable, Translation>(translations, insertBatch);
  }
});
```

**Comment by simolus3** [comment]
Assuming that your `insert` is potentially very large, your `fold` would generate a very complex expression. I'm not sure if that would cause problems (the `ROLLBACK TRANSACTION` indicates that there was an exception somewhere).

Due to the way batches work internally, it's efficient to have many statements with the same SQL, but different variables. So I think you could just use

```dart
await batch((batch) {
  for (final item in insert) {
    batch.deleteWhere(translations, (Translations t) => t.id.equals(item.id.value) & t.learningWordId.equals(item.learningWordId.value & t.language.equals(item.language.value));
    batch.insert(translations, item);
  }
});
```

You don't need to merge everything together in a single statement.

**Comment by lex-github** [comment]
Thanks, will keep that in mind. Just wanted to let you know that there is this potential uncaught exception that leaves batch hanging.
