### ISSUE TITLE
Getting Table object from DataClass object

### ISSUE THREAD

**Issue by KaungZawHtet** [simolus3/moor#898]
Like the way I can get companion object from Dataclass object, can I get Table object from DataClass object in moor generation  ?

Eg:
`User.toTable() ;  // or User.getTable()`

**Comment by simolus3** [comment]
At the moment we don't generate that method. For what would you need that?

**Comment by KaungZawHtet** [comment]
For dynamic db operation ( I mean create, update, delete ).
Here is the flow: 
Get data from firestore -> catch the data with moor's DataClass by fromJson() -> do dynamic db operation that needs table object.

**Comment by KaungZawHtet** [comment]
Dynamic means only data would decide which operation would be on.

**Comment by KaungZawHtet** [comment]
Can this code generation be in next version or is there any recommendation or advice you want to give me ?

**Comment by simolus3** [comment]
Sorry for the slow response. If you have a generic type argument for the data class, you can use

```dart
// put this into your database class
Table tableFor<D extends DataClass>() {
  return allTables
    .where((element) => element is TableInfo<dynamic, D>)
    .first;
}
```

You need to know on which data class you called `fromJson`, so you should have that type. But in that case, you usually have the table too, so I think that moor shouldn't have builtin support for that.
