### ISSUE TITLE
Does Moor fully supports custom sql with inner join?

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#899]
I am not sure if the [issue #891 ](https://github.com/simolus3/moor/issues/891) is fully fixed.

It can build normally, when my custom sql like this:
```dart
SELECT id, folderId, title, content, created, updated, nextReviewTime, CASE WHEN reviewProgressNo IS NULL THEN 0 ELSE reviewProgressNo END AS reviewProgressNo, isReviewFinished, isDeleted, createdBy,( SELECT count( *) FROM reviewPlanConfigs WHERE reviewPlanId = ( SELECT reviewPlanId FROM folders WHERE id = ( SELECT folderId FROM notes WHERE id = n.id ) ) ) AS progressTotal FROM notes n WHERE n.isDeleted = 0 AND strftime('%Y-%m-%d %H:%M:%S', n.nextReviewTime) < strftime('%Y-%m-%d %H:%M:%S', 'now', 'localtime', 'start of day', '+1 day') AND n.isReviewFinished = 0 AND n.createdBy = :createdBy ORDER BY n.nextReviewTime ASC, n.id ASC LIMIT :pageSize OFFSET :pageSize * (:pageNo - 1); 
```

But it will show error when using `flutter packages pub run build_runner build --delete-conflicting-outputs` to build after I changed the custom sql into:
```dart
SELECT id, folderId, title, content, created, updated, nextReviewTime, CASE WHEN reviewProgressNo IS NULL THEN 0 ELSE reviewProgressNo END AS reviewProgressNo, isReviewFinished, isDeleted, createdBy,( SELECT count( *) FROM reviewPlanConfigs WHERE reviewPlanId = ( SELECT reviewPlanId FROM folders WHERE id = ( SELECT folderId FROM notes WHERE id = n.id ) ) ) AS progressTotal FROM notes n, folders f WHERE n.folderId = f.id AND f.reviewPlanId IS NOT NULL AND n.isDeleted = 0 AND strftime('%Y-%m-%d %H:%M:%S', n.nextReviewTime) < strftime('%Y-%m-%d %H:%M:%S', 'now', 'localtime', 'start of day', '+1 day') AND n.isReviewFinished = 0 AND n.createdBy = :createdBy ORDER BY n.nextReviewTime ASC, n.id ASC LIMIT :pageSize OFFSET :pageSize * (:pageNo - 1); 
```

<img width="1415" alt="image" src="https://user-images.githubusercontent.com/1920873/97841665-4abda180-1d21-11eb-8f04-d37dd748a451.png">

Actually, the difference between the two custom sql is the part I marked red:
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/1920873/97842062-fc5cd280-1d21-11eb-8426-9aef5231cbfe.png">

My question is if there is a bug when building the custom sql which is using `inner join`?

**Comment by simolus3** [comment]
It sounds like both `notes` and `folders` have a column called `id`, `created` and `createdBy`. Moor rejects ambiguous references since the behavior can be unexpected. Does it work if you use `SELECT n.id, n.created, n.createdBy ...`?

**Comment by jims57** [comment]
@simolus3 fixed by specifying the prefix for these ambiguous, such as `n.id`. Thanks.
