### ISSUE TITLE
Failed to snapshot build script .dart_tool/build/entrypoint/build.dart

### ISSUE THREAD

**Issue by gloryluu** [simolus3/moor#900]
I ran: flutter packages pub run build_runner watch --delete-conflicting-outputs

**Result:**
[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] ../../../../../Library/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.4.0/lib/src/runtime/api/query_engine.dart:331:35: Error: Expected ';' after this.    if (resolved is Transaction) {authbe                                  ^^^^^^../../../../../Library/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.4.0/lib/src/runtime/api/query_engine.dart:331:35: Error: The getter 'authbe' isn't defined for the class 'QueryEngine'. - 'QueryEngine' is from 'package:moor/src/runtime/api/runtime_api.dart' ('../../../../../Library/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.4.0/lib/src/runtime/api/runtime_api.dart').Try correcting the name to the name of an existing getter, or defining a getter or field named 'authbe'.    if (resolved is Transaction) {authbe...

**Flutter doctor:**
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-VN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.50.1)
[✓] Connected device (1 available)

**Comment by simolus3** [comment]
Could it be that you modified your local moor version? This is the actual code, there's no `authbe`:
https://github.com/simolus3/moor/blob/e29fcf93f7c28603a5cac7110eeb8b19b09dfb14/moor/lib/src/runtime/api/query_engine.dart#L330-L333

Can you try to delete `Library/flutter/.pub-cache/hosted/pub.dartlang.org/moor-3.4.0` and run `flutter pub get` again?

**Comment by gloryluu** [comment]
@simolus3 I delete the folder and it seems to be OK now. 
I dont know how and when it is modified :/. I will close the ticket.
Thanks so much for your active 👍
