### ISSUE TITLE
Select specific columns from a table

### ISSUE THREAD

**Issue by Rossdex** [simolus3/moor#901]
Hi,

I would like to retrieve specific columns from my app database using the generic select function.

Currently we have this table structure:

**Form Structures**
id => int
title => String
structure => Blob 
created_at => dateTime
updated_at => dateTime

When we want to list out the form structures in a list we only want to show the title and not load the huge amounts of unused structure data which ends up drastically increasing the load time on the page.

Is there a way to only get specific columns from a table without resorting to using an SQL query? 

Thanks

**Comment by simolus3** [comment]
Sure, you can use `selectOnly`. So if you only wanted the title, you could use

```dart
Stream<List<String>> titles() {
  final query = selectOnly(formStructures)..addColumns([formStructures.title]);
  return query.map((row) => row.read(formStructures.title)).watch();
}
```

You can use more than just one column of course, but then you'd have to write your own class to store that specific structure.
