### ISSUE TITLE
Filter duplicate Insertion

### ISSUE THREAD

**Issue by KaungZawHtet** [simolus3/moor#902]
Is there moor way to automatically filter duplicate data insertion , especially at moor files ?

**Comment by simolus3** [comment]
You could add a unique constraint and then use `INSERT OR IGNORE INTO ...` to avoid inserting data twice.

**Comment by KaungZawHtet** [comment]
Like this `INSERT OR IGNORE INTO user VALUES :userCompanion` ?

**Comment by simolus3** [comment]
I mean you can write `into(user).insert(userCompanion, mode: InsertMode.insertOrIgnore)` in Dart. I can take a look at supporting companions inside moor files too, but it'll probably be some work.

**Comment by KaungZawHtet** [comment]
This is clean too. Thx for ur help. This issue can be closed now

**Comment by KaungZawHtet** [comment]
Wait! sadly this does not filter duplication here. How insertOrIgnore works?

**Comment by KaungZawHtet** [comment]
How can I detect the duplication by a column ? Example, detect email column of incoming data for filtering.

**Comment by simolus3** [comment]
> How can I detect the duplication by a column

If you want that column to be unique, you can add a unique [column constraint](https://www.sqlite.org/syntax/column-constraint.html). That should work together with `INSERT OR IGNORE`.

Or do you want to allow duplicate values in general, but avoid them when inserting data in a batch?

**Comment by KaungZawHtet** [comment]
Cool if I can define table like this in moor file and `InsertMode.insertOrIgnore` automatically detect it
```
CREATE TABLE user (
  id INTEGER PRIMARY KEY NOT NULL,
  name TEXT,
  email TEXT,
  UNIQUE(id,email)
);

```

**Comment by simolus3** [comment]
The `UNIQUE(id, email)` key won't do much - `id` is the sole primary key, so it's unique on its own. You can just use a `UNIQUE (email)` constraint if you want them to be unique.

**Comment by knaeckeKami** [comment]
if you also insert the primary key (id), you can do that on the table level:

```sql
CREATE TABLE user (
  id INTEGER,
  name TEXT,
  email TEXT,
  primary key ("id") on conflict replace
);
```
