### ISSUE TITLE
Moor on windows getting sqlite3 is null exception

### ISSUE THREAD

**Issue by PandaGeek1024** [simolus3/moor#903]
I'm trying to run moor on windows, and follows what the [doc ](https://moor.simonbinder.eu/docs/other-engines/vm/)suggest. But somehow it is getting this error
```
NoSuchMethodError: The method 'open' was called on null.
Receiver: null
Tried calling: open("db.sqlite")
```
which means sqlite3 instance is not created. I have no clue how to solve this. Please provide some help

![image](https://user-images.githubusercontent.com/3827781/98047395-aeb2a800-1e90-11eb-9601-64b7bbf6d6dc.png)

Please check my setups here:
1. Download Precompiled Binaries for Windows and extracted sqlite3.dll, follow [this ](https://github.com/simolus3/moor/issues/420#issuecomment-624084393)to put it in user env path.
2. add code as below:

pubspec.yaml
```
  moor: ^3.1.0
  sqlite3_flutter_libs: ^0.2.0
```

db.dart
```
@UseMoor(tables: [ProjectEntitys])
class AppDatabase extends _$AppDatabase {
  AppDatabase(QueryExecutor e) : super(e);

  @override
  int get schemaVersion => 1;
}

AppDatabase initDb({bool logStatements = false}) {
  if (Platform.isIOS || Platform.isAndroid) {
       ...
  }
  if (Platform.isMacOS || Platform.isLinux || Platform.isWindows) {
    final file = File('db.sqlite');
    return AppDatabase(VmDatabase(file, logStatements: logStatements));
  }
  throw 'Unidentified native platform not supported';
}
```

main.dart
```
DynamicLibrary _openOnWindows() {
  //this method is not executed, myabe because the exception is thrown before this runs?
  final script = File(Platform.script.toFilePath());
  final libraryNextToScript = File('${script.path}/sqlite3.dll');
  return DynamicLibrary.open(libraryNextToScript.path);
}

import 'package:sqlite3/open.dart' as sqlite;
void main() async {
  if(Platform.isWindows) {
    sqlite.open.overrideFor(sqlite.OperatingSystem.windows, _openOnWindows);
  }
  WidgetsFlutterBinding.ensureInitialized();
}
```

**Comment by simolus3** [comment]
It's weird that `_openOnWindows` doesn't get called at all, do you access `sqlite3` before setting `overrideFor`? You could also try to a set a breakpoint on `OpenDynamicLibrary.overrideFor` to make sure that the override was applied.

**Comment by PandaGeek1024** [comment]
@simolus3  Found out that "script.path" returns the path to the main.dart file, so basically "${script.path}/sqlite3.dll" is pointing to the wrong address. Changing it to r"C:\developer\sqlite\sqlite3.dll" works for me. Can you please update the doc as well, it is kind of misleading.

I have also got a question, if I'm distributing this as a windows app, will it automatically take the sqlite3.dll and bundle it into the app?
Or do I need to place sqlite3.dll in the root of the project right from the beginning and use path like this
`final libraryNextToScript = File('sqlite3.dll');` to make sure sqlite3.dll comes with the app?

**Comment by simolus3** [comment]
>  Found out that "script.path" returns the path to the main.dart file, so basically "${script.path}/sqlite3.dll" is pointing to the wrong address

Oh, right - thanks for pointing it out! I'll update the documentation.

> if I'm distributing this as a windows app, will it automatically take the sqlite3.dll and bundle it into the app?

No, you'll have to manually bundle `sqlite3.dll`. Alternatively you could modify your Windows buildscripts to include `sqlite3` in your executable, but I don't know enough about Windows development to help you with that.

Using `libraryNextToScript = File('sqlite3.dll');` might not work if a user runs your app from a different working directory. I think you can use [`Platform.resolvedExecutable`](https://api.dart.dev/stable/2.10.3/dart-io/Platform/resolvedExecutable.html) for release builds to obtain your `.exe`. which you can then use to resolve the location of `sqlite3.dll`.

**Comment by matthewkooshad** [comment]
@simolus3 @PandaGeek1024 i see the snippet above still in the doc on https://moor.simonbinder.eu/docs/other-engines/vm/. i'm wondering for windows, what should i be using for these two lines below?

final script = File(Platform.script.toFilePath());
  final libraryNextToScript = File('${script.path}/sqlite3.dll');

**Comment by simolus3** [comment]
Those lines should work if you're including a copy of `sqlite3.dll` next to your final app.
