### ISSUE TITLE
Why database is locked when executing auto-save?

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#906]
I am trying to achieve an auto-save functionality, the execution interval is `500ms`, why will `moor` throw an exception sometimes, saying `database is locked`? (Just sometimes, not always)

How can I avoid this problem? Is the interval to execute the auto-save too short? Thanks.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/1920873/98225702-01bf5480-1f90-11eb-8dc7-aa9ccec6f991.png">

<img width="713" alt="image" src="https://user-images.githubusercontent.com/1920873/98225647-efddb180-1f8f-11eb-8b55-d87caaba09ff.png">

**Comment by simolus3** [comment]
What do you do to save the database? Sqlite will save the database after each statement, so I don't think this is necessary.

**Comment by jims57** [comment]
@simolus3 Maybe I didn't explain it clearly, the auto-save functionality won't execute the auto-save execution, though the interval millisecond is set to `500ms`. I will execute the auto-save only when it detects changes the user makes.

Let's put aside the question about whether it is necessary or not, I'd like to know why it shows `database is locked`. Thanks.

**Comment by simolus3** [comment]
Again, I'm not sure what you're doing that would lock the database in the first place. If you show me what your save is doing (closing & re-opening the database? copying some files?) I might be able to spot the issue here.

**Comment by simolus3** [comment]
Closing since I need more information to investigate this.
