### ISSUE TITLE
Stream does not update when joined table changes

### ISSUE THREAD

**Issue by Tiger3030** [simolus3/moor#910]
The following stream only updates when _tableOne_ changes, but not when one of the joined tables (_tableTwo_ or _tableThree_) changes:

```
Stream<List<String>> watchTables() {
    final query = (selectOnly(tableOne)
      ..where(isNull(tableThree.hidden)))
        .join([
      leftOuterJoin(tableTwo, tableTwo.id.equalsExp(tableOne.id)),
      leftOuterJoin(tableThree, tableThree.id.equalsExp(tableTwo.id))
    ])
      ..addColumns([tableThree.title])
      ..groupBy([tableThree.title]);

    return query.watch().map((rows) {
      return rows.map((row) {
        return row.read(tableThree.title);
      }).toList();
    });
  }
```
Is there a way to make the stream also update when one of the joined tables changes?

**Comment by simolus3** [comment]
Thanks for the report! I tried to reproduce this in 1f2dca0240cc40fe7534342991dcf643d2947144, but the test works for me. I faked an update on `tableTwo` and check that the stream re-emits an item in that case. Through debugging, I could also verify that the query indeed listens on all three tables as it should.

If you want to help debugging, you could check whether `watchedTables` contains what you expect here https://github.com/simolus3/moor/blob/c66210e89ee5b60655c5b687c2d15a923dda6e73/moor/lib/src/runtime/query_builder/statements/select/select_with_join.dart#L175-L179

Otherwise, I think I need a small repro to see what's going wrong here. If you can post the full code that doesn't work as you expect, I'm happy to take another look.

**Comment by Tiger3030** [comment]
Thanks for your answer. I was able to narrow down the problem.
When I update the data with the following query, the stream updates as expected:
```
Future updateTableThree() =>
      (update(tableThree)..where((row) => row.id.equals(1)))
          .write(TableThreeCompanion(hidden: Value(DateTime.now())));
```
But if I use the same query inside a `transaction`, the stream does not update.
It is mentioned in the [docs](https://moor.simonbinder.eu/docs/transactions/) that streams created inside a `transaction` behave differently. Is this the case here, although I do not create any stream directly inside a `transaction`?

**Comment by simolus3** [comment]
>Is this the case here, although I do not create any stream directly inside a `transaction`?

If the stream was created outside of a transaction, and you're updating data inside a transaction, the stream should update after the transaction completes. If the stream was created in a transaction, it will stop emitting updates after the transaction completes (but it should emit a done event when that happens).

**Comment by Tiger3030** [comment]
> Is this not the behavior you're seeing?

If I do not use a transaction to update the data, everything works as expected.

> If the stream was created outside of a transaction, and you're updating data inside a transaction, the stream should update after the transaction completes.

This is my use case, but the stream only updates when _tableOne_ changes, but not when one of the joined table changes. The transaction definitely works and is completed (change is visible in database), but the stream does not update.

> Thanks for the report! I tried to reproduce this in 1f2dca0, but the test works for me. I faked an update on tableTwo and check that the stream re-emits an item in that case. Through debugging, I could also verify that the query indeed listens on all three tables as it should.

Could you do this again, but this time do the update inside a transaction?

**Comment by Tiger3030** [comment]
> This is my use case, but the stream only updates when tableOne changes, but not when one of the joined tables changes. The transaction definitely works and is completed (change is visible in database), but the stream does not update.

Edit: The stream does NOT update when tableOne changes, neither when the joined tables change.

**Comment by simolus3** [comment]
> Could you do this again, but this time do the update inside a transaction?

Good idea! I just did that, but the test still passes. Are you doing anything special with the transaction? Can you check that you're awaiting everything in it?

**Comment by Tiger3030** [comment]
> Can you check that you're awaiting everything in it?

You are right. This was my mistake. In the queries to update streams without joins I always had the `await`, but forgot it when updating the streams with joins. This is why I thought it had something to do with _join_.
So everything works now. Thank you very much for your help!
