### ISSUE TITLE
Upon your suggestion, I have uploaded my package called moor2csv to pub and Github. I hope you check it out. Regardless, thank you for your time.

### ISSUE THREAD

**Issue by Dhi13man** [simolus3/moor#911]
It's a Support package for Moor that allows the easy conversion of any Moor/SQL database Table into CSV form, for the purpose of storing the database table externally or sharing it with others. I needed something with that utility, but couldn't find any, so I made my own. Might have mistakes as it's my first package. Do check it out, and use it as needed. Thank you.

PUB: https://pub.dev/packages/moor2csv
GITHUB: https://github.com/Dhi13man/moor2csv

**Comment by simolus3** [comment]
Cool, thanks for publishing this! I saw your first comment, but I didn't have the time to try the package yet. I'll do that soon!

**Comment by Dhi13man** [comment]
Oh. I apologize for the new thread then. Wasn't sure if comments are still notified about once a thread's been closed. Anyway, thanks.

**Comment by simolus3** [comment]
I just took a quick look at your readme and source code. It looks pretty good for a first package, I have some suggestions you might want to look into:

- There's a [csv](https://pub.dev/packages/csv) package to create csv files. You might be able to simplify your code by using that package.
- You're not escaping string values, so if a column contains a `,`, it would break your encoding. The csv package might handle this
- Your example from the readme is more complicated than it has to be. For instance, it imports and uses a `ChangeStack` from the `undo` package, but that's not necessary to demonstrate the `moor2csv` package. IMO, the complex `orderBy` logic in `getAllEmployees` could also be omitted.

**Comment by Dhi13man** [comment]
Thank you for your valuable suggestions. I have updated my package in compliance with [Standard CSV Rules.](https://tools.ietf.org/html/rfc4180)

I've also improved the documentation a bit. This was a good learning experience.
