### ISSUE TITLE
Dart components in SQL -- order by terms/clauses -- examples

### ISSUE THREAD

**Issue by PiN73** [simolus3/moor#915]
Thank you for such a great package!

I have an SQL query (in .moor file) which I want to use with different sorting modes.

I've read [docs](https://moor.simonbinder.eu/docs/using-sql/moor_files/#dart-components-in-sql)  ([github](https://github.com/simolus3/moor/blob/a4df55029c9149d717271ad2de9f0cd4655b98ce/docs/content/en/docs/Using%20SQL/moor_files.md#dart-components-in-sql)) about Dart components in SQL, in particular about order by terms/clauses.

Generated method accepts `OrderingTerm` or `OrderBy(List<OrderingTerm>)`. `OrderingTerm` accepts `Expression` and `OrderingMode` (asc/desc). Are there any examples of **expressions** that we can use here? Is it a good idea to add some examples to docs?

**Comment by PiN73** [comment]
At least we can use
```dart
OrderingTerm(
  expression: this.{tableName}.{columnName},
  mode: OrderingMode.___,
)
```

But using tables' or columns' aliases (AS ...) in SQL results in:
> Unhandled Exception: SqliteException(1): no such column: table_name.column_name, SQL logic error (code 1)

Maybe we can warn about aliases in docs

**Comment by PiN73** [comment]
Also let I have tables:
```
Shops (id, name)
Sales (id, amount, date, shop_id)
```

I want to query today and yesterday sales amount by shop.

So I must use the same table twice:
```sql
salesLastTwoDays:
    SELECT
        Shops.name,
        SalesYesterday.amount AS amount_yesterday,
        SalesToday.amount AS amount_today
    FROM Sales AS SalesYesterday,
    (
        SELECT SalesToday.amount, SalesToday.shop_id
        FROM Sales AS SalesToday
        LEFT JOIN Shops AS SalesToday.shop_id = Shops.id
        WHERE SalesToday.date = {today}
    ) AS SalesToday
    INNER JOIN Shops
        ON (SalesYesterday.shop_id = Shops.id)
        AND (SalesToday.shop_id = Shops.id)
    WHERE SalesYesterday.date = {yesterday}
    ORDER BY $order;
```

Is it any chance to supply ordering by `amount_yesterday` or `amount_today` from Dart?

**Comment by simolus3** [comment]
> Are there any examples of __expressions__ that we can use here? Is it a good idea to add some examples to docs?

We have [this page](https://moor.simonbinder.eu/docs/getting-started/expressions/) which list the most important SQL expressions available in Dart. I'll link to that page from the relevant section.

> Maybe we can warn about aliases in docs

Agreed, I'll add a warning.

> Is it any chance to supply ordering by `amount_yesterday` or `amount_today` from Dart?

I think you can order by `2` or `3`, respectively. So you could use `OrderingTerm.asc(const Constant<int>(2));`. Not really clean, but it should work.
