### ISSUE TITLE
Use of the & operator in the where clause causes syntax error

### ISSUE THREAD

**Issue by celiooliveira** [simolus3/moor#916]
I did a lot of research and couldn't find a solution.

version of the dependencies that I use in the project: 
- moor_flutter 3.1.0 and 
- moor_generator 3.4.0.

**Example:**

var db = MyDatabase.instance;
db.select(db.tabelaPrcProduto)
..where((tbl) => tbl.idProduto.equals(id) **&** tbl.idTabelaPrc.equals(idTabelaPrc));

**Syntax error:**
The operator '&' isn't defined for the type 'Expression<bool>'.
Try defining the operator '&'.

**Comment by simolus3** [comment]
Hm, that operator definitely exists, it's defined here: https://github.com/simolus3/moor/blob/bac3781a44700fa6666443a8ca008fd8512f7fef/moor/lib/src/runtime/query_builder/expressions/bools.dart#L9-L12

Did you import `package:moor/moor.dart` into that file? Are there any other errors? This definitely works for me, so I'm not really sure what's going wrong here.

**Comment by celiooliveira** [comment]
that's right! the import of the moor package was missing.
Thank you very much!
