### ISSUE TITLE
A somewhat negative user experience anecdote for a great code generation package.

### ISSUE THREAD

**Issue by GregorySech** [simolus3/moor#918]
I've found myself quite happy with the package so far, it really saves me a lot of time.
I wanted to share a little negative experience I've had today about debugging and the danger of blindly relying on code generation.

Basically I had a somewhat complex query with 3 text/string arguments and a certain number of joins and subqueries.
It was pretty yucky so today I've been refactoring it.
To do so I've taken a populated database .sqlite file and I've been testing the query during refactoring in DBeaver.

After that the new query was ready and tested I've re-applied the same parameter names to the 3 parameters, placed the modified query in the .moor file and restarted generation. 
So far, so good.

However during tests I've started getting wrong expected results on examples I've already tried before in DBeaver.
After spending a considerate amount of time trying to get the exact query that was being launched on the database (which I was unable to do anyway) I've noticed that on the generated query method the parameters changed order and not only I felt quite stupid but I've also thrown precious time in the garbage.

So, let's make it clear again: it's totally my fault I'm not saying this is an urgent issue. 

Anyway I think it would be neat for the generated methods to have a set of named parameters so that you do not get semantically broken (but syntactically valid) method calls in case of a change of order during query definition generation. 
This would make easier to join query parameter semantic with code semantic as users do not have to check parameter order for every query call when a query refactoring happens.

**Comment by simolus3** [comment]
Thanks for sharing your experience!

> After spending a considerate amount of time trying to get the exact query that was being launched on the database (which I was unable to do anyway)

All database implementations (`VmDatabase`, `FlutterQueryExecutor`, ...) have a `logStatements` parameter for this purpose. I see how that's pretty hard to find, but its rarely used so I'm not sure how much publicity it deserves. The documentation should probably mention it somewhere.

> Anyway I think it would be neat for the generated methods to have a set of named parameters so that you do not get semantically broken (but syntactically valid) method calls in case of a change of order during query definition generation.

I fully agree with this, and really like your suggestion. We could generate positional parameters for positional variables (`?`, `?123`) and named parameters for named variables (`:apply_filter`). This would be breaking for existing code so we need to make it opt-in, but we can make it the default eventually.

**Comment by simolus3** [comment]
I added a build option to generate named parameters for named SQL variables, it will be available with the next moor version. I also added documentation for the `logStatements` option to the FAQ. Thanks again for your feedback and suggestions!

**Comment by kuhnroyal** [comment]
Great idea! I also ran into this once :)
