### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by Tedesc0** [simolus3/moor#919]
I'm trying to start using MOOR as in the getting started page.  The pubspec.yaml was edited adding moor: ^3.4.0 but when running pub.get I receive the following error:

flutter pub get
Running "flutter pub get" in moor...                            

Error on line 27, column 3 of pubspec.yaml: A package may not list itself as a dependency.
   ╷
27 │   moor: ^3.4.0
   │   ^^^^
   ╵
pub get failed (65;    ╵)
Process finished with exit code 65

What do I need to do to solve this? 

Thanks in advance.

**Comment by simolus3** [comment]
Thanks for trying out moor! I assume you named your project `moor` too? That's not allowed, there can only be one moor project and its mine :P 
You need to change your `name` field in the pubspec to something other than `moor`.
