### ISSUE TITLE
How do I prepopulate table with data on its creation?

### ISSUE THREAD

**Issue by VadimOsovsky** [simolus3/moor#92]

**Comment by simolus3** [comment]
Hi, you could use the `beforeOpen` callback when overriding the `migration` getter in your Database class. Maybe this section from the example app is helpful: https://github.com/simolus3/moor/blob/1df635c067eed926f8b01c8fb5003da5df1c3833/moor_flutter/example/lib/database/database.dart#L66-L87

Let me know if you have any questions or run into problems :)
