### ISSUE TITLE
How can i efficiently query a table entry that matches either of words from Set 

### ISSUE THREAD

**Issue by KennanObura** [simolus3/moor#921]
I have a Set of String that contains words . The the Set can be of length 15 in average. 
Am wondering if i can query the entries that contains these words efficiently without having to loop the Set like i have done here. 

` Future<List<Upload>> search(Set keys, List<Upload> result) async {
    keys.forEach(
      (term) => (select(uploads)..where((tbl) => tbl.title.contains(term)))
          .get()
          .then((value) => result.addAll(value)),
    );
  }`

I can see that am running a single query multiple times. 
Any help? 

Thanks

**Comment by PiN73** [comment]
Maybe this can help https://moor.simonbinder.eu/docs/getting-started/expressions/#in-and-not-in

**Comment by KennanObura** [comment]
@PiN73 Thanks so much. I kind of didnt see this
