### ISSUE TITLE
Database initialization not executing

### ISSUE THREAD

**Issue by jpChan015** [simolus3/moor#925]
I have this versions of Flutter and moor
`Flutter 1.22.4 `
`moor 3.4.0`
`moor_generator 3.4.0`
`ffi 5.2.1`

I have this code for the Database
<img width="499" alt="Screen Shot 2020-11-19 at 11 56 37 AM" src="https://user-images.githubusercontent.com/5347519/99619430-6681b100-2a5e-11eb-968f-66a24cb165bf.png">

But when I create a new instance of AppDatabase,  it only prints `flutter: Init DB1` and not going inside the block of LazyDatabase constructor.

Also no logs.

**Comment by Mike278** [comment]
You're underestimating just how lazy a `LazyDatabase` is! It won't actually be opened until executing the first sql statement.

**Comment by jpChan015** [comment]
I tried using the instance of the `AppDatabase` to execute `into(userDetails).insert(item)`but it was stuck and it won't proceed in inserting.

Here is the function in my DAO
`Future insertUpdateItem(UserDetail item) => into(userDetails).insert(item);`

And I tried using it using the code below but it was just stuck and it wont proceed. 
`await database.userDetailDao.insertUpdateItem(user)`

**Comment by simolus3** [comment]
Mike is right - in general the databases don't do anything before being used. They usually require some async setup that we can't reasonably run from a sync constructor. 
But it's definitely weird how it doesn't even print `Init DB2` after attempting to use the database. I've never seen that before and I think I need more information to find the cause. I know it might be some work, but can you share a small project to reproduce this? I'm happy to take a look then. If  you want to take a look yourself, you could step through `await database.executor.ensureOpen(database)` and see where that gets stuck.

**Comment by jpChan015** [comment]
@simolus3 Thank you very much for your response. I was able to resolved the issue. The issue was not caused by the instance of `AppDatabase ` not being initialized, it was the insertion of a `null` value from JSON in a non nullable field. It doesn't throw or printing any error, it was just stuck in `await database.userDetailDao.insertUpdateItem(user)` and wont proceed. I just put `nullable()` to some of the fields and it already worked. I don't know if its the intended behavior when the query was not successful.

**Comment by simolus3** [comment]
> It doesn't throw or printing any error, it was just stuck in `await database.userDetailDao.insertUpdateItem(user)` and wont proceed

That doesn't sound right too, it should throw. How are you listening to the future? If it's a `FutureBuilder` you'd have to explicitly check the `snapshot.error` for instance.
