### ISSUE TITLE
Write in the moor file when inside a .zip file.

### ISSUE THREAD

**Issue by SahajRana** [simolus3/moor#927]
Hi @simolus3, hope you are doing good. 
I have a question, is there a way to read/write in a .zip file,

like

`VmDatabase(File("datafile.zip/datafile.moorFile"), logStatements: false),`
Currently, it doesn't work. 

```
Unhandled Exception: "SqliteException(14): bad parameter or other API misuse, bad parameter or other API misuse (code 21)"
#0      new DatabaseImpl.open (package:sqlite3/src/impl/database.dart:39:7)
```

But if I use `VmDatabase(File("datafile.moorFile"), logStatements: false),`, 
then it works.

My use-case needs to save images as well with moorFile so it is useful if somehow it can be all in one zip file.

I'm building a flutter windows app.

**Comment by simolus3** [comment]
You can't read files from a zip like that, it just doesn't work. You need to extract the database file before using it. This can be done with a `LazyDatabase` and the [archive](https://pub.dev/packages/archive) package for instance:

```dart
LazyDatabase(() async {
  final zipFile = File("datafile.zip");
  final target = File("datafile.moorFile");
  // extract from zip file, see package:archive

  return VmDatabase(File("datafile.moorFile"));
});
```

> My use-case needs to save images as well with moorFile so it is useful if somehow it can be all in one zip file.

Depending on the amount and size of images, its not unreasonable to store them directly in the sqlite3 database file. Sqlite3 claims to be [35% faster than the file system](https://www.sqlite.org/fasterthanfs.html) for similar workloads.

**Comment by SahajRana** [comment]
Is there a way to use [SQLite Zipfile Module](https://www.sqlite.org/zipfile.html). I think with this we can directly read-write in a zip file containing a sqlite file.

> My use-case needs to save images as well with moorFile so it is useful if somehow it can be all in one zip file.
> 
> Depending on the amount and size of images, its not unreasonable to store them directly in the sqlite3 database file. Sqlite3 claims to be 35% faster than the file system for similar workloads.

Here I mean is that I need to bundle images with sqlite file in one place i.e in .zip file like 
-data.zip
--datafile.moorFile
--images/some_image.jpg
--images/...

**Comment by simolus3** [comment]
That module can be used to use zip files as a virtual table, but it doesn't support opening databases stored inside of them.

> Here I mean is that I need to bundle images with sqlite file in one place i.e in .zip file like

How do you access the images then? I imagine you'll need to extract zip file either way?

**Comment by SahajRana** [comment]
Yaa makes sense. I didn't put thought into it. Thanks.
