### ISSUE TITLE
setState doesn't effect stream now

### ISSUE THREAD

**Issue by KaungZawHtet** [simolus3/moor#930]
```
            StreamBuilder<User>(
                stream: db.getRandomUser().watchSingle(),
                builder: (context, snapshot) {

                  print(snapshot.data); //in past this change but doesn't now whenever calling onPressed

                  ...

                 onPressed: () {
                    setState(() {
                   
                    });
                  }

                  ...
                 }
```

In previous days, the code generate random result whenever calling onPressed. But it give only one random thing of first widget build. I feel it is related to moor query cache.

**Comment by KaungZawHtet** [comment]
not only that place but also other place don't update now :

 ```
StreamBuilder<TableData>(
                stream: db.getTableData(dynamicInput).watchSingle(), // dynamicInput from user
                builder: (context, snapshot) {

                  print(snapshot.data); //in past this change but doesn't now whenever calling onPressed

                  ...

                 onPressed: () {
                    setState(() {
                   
                    });
                  }

                  ...
                 }
```

**Comment by KaungZawHtet** [comment]
Btw, those functions are generated from moor file so I think moor file has some problem. 
After testing with manual queries, it works well ( I mean select(), where() ... )

**Comment by KaungZawHtet** [comment]
srry , wrong click

**Comment by simolus3** [comment]
> In previous days, the code generate random result whenever calling onPressed

Which moor version were you using previously, and which moor version are you using now? In general we try to avoid running queries a lot, so if you call `.watch()` multiple times moor won't necessarily run the query again if there weren't any writes in between. So this sounds like the intended behavior. It doesn't really make sense to "watch" nondeterministic queries since they change all the time! For those, I'd probably use a `FutureBuilder` and just get the data once. This also means that `setState()` will cause the query to be run again.

**Comment by KaungZawHtet** [comment]
I realize its not related to moor version. Its related to moor file. I migrated all of query from dao to moor file and this happens.
Future works but cant use becasue of rx combination at somewhere.

Can query generated from moor file run again at every new state?

**Comment by KaungZawHtet** [comment]
At somewhere, my streams of StreamBuilder r complex like this: 

```
stream :  Rx.combineLatest3( 
   db.getFirstData().watchSingle(),
   db.getSecData().watchSingle(),
   db.getThirdData().watchSingle(),
        (obj1,obj2,obj3) 
        {
        ... //some processing here;
         }
   ...
```
That's why, sadly, I can't rely on future

**Comment by simolus3** [comment]
Hm. Unfortunately I don't see a solution on how moor would could provide streams for nondeterministic queries. Your old approach was to explicitly re-run the query (by calling `setState()`), so maybe you could continue to use that? You can use `Stream.fromFuture(someQuery.get())` to model that behavior - whenever you call `fromFuture` again, the query will be re-run.

**Comment by KaungZawHtet** [comment]
yes , using that `Stream.fromFuture() ` as current solution. Thx for your reply.
