### ISSUE TITLE
hello guys , when i want to install moor library (moor_flutter: ^2.1.1) i get this error  

### ISSUE THREAD

**Issue by yacinzr** [simolus3/moor#943]
[mytask] flutter pub get
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Running "flutter pub get" in mytask...                          
The current Flutter SDK version is 0.0.0-unknown.

Because moor_flutter >=2.0.0 depends on sqflite >=1.1.2 which requires Flutter SDK version >=1.2.1 <2.0.0, moor_flutter >=2.0.0 is forbidden.

So, because mytask depends on moor_flutter ^2.1.1, version solving failed.
pub get failed (1; So, because mytask depends on moor_flutter ^2.1.1, version solving failed.)
exit code 1

**Comment by yacinzr** [comment]
this is my pubspec.yaml 
name: mytask
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  moor_flutter: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by yacinzr** [comment]
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  moor_flutter: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.1.1

**Comment by simolus3** [comment]
Is there any reason you're using moor 2? The current version is 3.4. It also looks like there's something wrong with your flutter installation, since your Flutter SDK version is certainly not "0.0.0-unknown". Does `flutter doctor` show anything helpful?

**Comment by yacinzr** [comment]
> Is there any reason you're using moor 2? The current version is 3.4. It also looks like there's something wrong with your flutter installation, since your Flutter SDK version is certainly not "0.0.0-unknown". Does `flutter doctor` show anything helpful?

thx the problem is that I was having two versions of flutter sdk  on my computer

**Comment by simolus3** [comment]
Glad I could help
