### ISSUE TITLE
Do I need moor_flutter or only moor for web?

### ISSUE THREAD

**Issue by cervonwong** [simolus3/moor#946]
If I only need `moor`, when would I need `moor_flutter` (what is it used for?)

In the documentation, it looks like I only need the `moor` dependency, but from the moor tutorial by ResoCoder (for Android) he only used `moor_flutter` and not `moor`

Thanks for the clarification :)

**Comment by simolus3** [comment]
I tried to explain some of that [here](https://moor.simonbinder.eu/docs/platforms/). Basically, it should be possible to use the core `moor` package in every Dart program (most importantly, outside of Flutter). This means that we can't have it depend on Flutter-only libraries like `sqflite`. In the early stages of the project, `moor_flutter` (which implements moor by using `sqflite`) was the only implementation, it has flutter in its name to indicate that it only works on Flutter. 
`moor_flutter` is still maintained and continues to work, but now that `dart:ffi` is stable (it didn't exist when moor first came out), we can have an implementation directly in the core package.

So to answer your question, you _can_ use `moor_flutter`, but I recommend using `moor/ffi.dart` for the implementation now. The tutorial by ResoCoder was made when `moor_flutter` was the only implementation.
