### ISSUE TITLE
Does the withLength method when defining a TextColumn have exclusive max?

### ISSUE THREAD

**Issue by cervonwong** [simolus3/moor#947]
https://pub.dev/documentation/moor/latest/moor/TextColumnBuilder/withLength.html

If I define a table column as:
`TextColumn get code => text().withLength(min: 6, max: 8)();`

Will I be able to insert an entity with a code of length 8?

**Comment by simolus3** [comment]
Yes, its inclusive:

https://github.com/simolus3/moor/blob/727c30aa6bc264fd36fcbb9a305b71fd2f479079/moor/lib/src/runtime/query_builder/schema/columns.dart#L178-L181

I'll change the Dart documentation to point that out.
