### ISSUE TITLE
Support JsonKey(ignore: true) equivalent?

### ISSUE THREAD

**Issue by phijma** [simolus3/moor#952]
Would it be possible to support this?
Or is there a way already?

I have a field which I don't want to use with the `fromJson` method.

Right now I did something like

```dart
@JsonKey('nonsense')
IntColumn get id => integer()();
```

It works, but doesn't look very nice :p

**Comment by simolus3** [comment]
I think the best approach is to use custom row classes in the next moor version, see #1134.
