### ISSUE TITLE
Watch a joined table

### ISSUE THREAD

**Issue by krongnang** [simolus3/moor#953]
Hi,
I have three tables called TableA, TableB, TableC.

I have a custom query and map it to the TableD.

How can I watch TableD on table A, B, or C data changes?

**Comment by simolus3** [comment]
If you're writing a query that joins all table, then that query will update whenever _any_ table changes.

If you want something custom, you can listen for [`tableUpdates`](https://pub.dev/documentation/moor/latest/moor/QueryEngine/tableUpdates.html) directly too.
