### ISSUE TITLE
Sharing/Exposing database with other Android app.

### ISSUE THREAD

**Issue by tirth-stasis** [simolus3/moor#955]
I'll be using this plugin in my Flutter app to create a database. Is it possible to share this database with another android app, which can also read/write from the same database?

**Comment by simolus3** [comment]
If you figure out the necessary Android apis, yes. I don't have a lot of experience with the latest restrictions Android puts on the file system, but moor uses sqlite3 which is a file-backed database. If you can use a file that's accessible by other apps too, you can re-use the same database across apps.

As far as I know, the only way to do that is to use a public directory and let both apps write to external storage. With that approach, every other app with that permission will be able to read and write your app's database too. You can design a safer system with remote services, but that requires considerably more work too.
