### ISSUE TITLE
How to rename a table using the migrator ?

### ISSUE THREAD

**Issue by CalvinGonsalves** [simolus3/moor#956]
Is it possible to rename a table using the migrator or would a statement like 
`database.customStatement("ALTER TABLE oldTableName RENAME TO newTableName")` work in the onUpgrade ?

**Comment by simolus3** [comment]
The custom statement would work, but the migrator should have a method to make this easier.

**Comment by simolus3** [comment]
Done! This will be a part of the next moor version (likely 4.0 since we had to make some breaking changes for null safety).
