### ISSUE TITLE
Unable to compile on iOS: Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by stx** [simolus3/moor#958]
Can build in debug mode but not release mode. Same problem as https://github.com/tekartik/sqflite/issues/536 https://github.com/tekartik/sqflite/issues/540. Problem started when sqlflite moved to FMDB 2.7.5+. Only degrading sqlflite fixes it, but not sure how to fix that while using Moor.

flutter clean/rm symlinks/rm pods/pod upgrade/pub upgrade/regenerate podfile/bump platform target - nothing helps.

Using:
moor_flutter: ^3.1.0
sqlite3_flutter_libs: ^0.2.0

```
    ld: warning: ignoring file .../build/ios/Release-iphoneos/FMDB/FMDB.framework/FMDB, building for iOS-armv7 but attempting to link with file built for
    iOS-arm64
    Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_FMDatabaseQueue", referenced from:
          objc-class-ref in SqflitePlugin.o
    ld: symbol(s) not found for architecture armv7
```

**Comment by stx** [comment]
**Solution:** compile breaks if using iOS platform target >= 11. Change **Build Settings > Architectures** from `$(ARCHS_STANDARD)` to `arm64`.

**Comment by AtaKarakas** [comment]
I am still getting errors even though it is on these settings now, what could be the cause and what is the solution

**Comment by stx** [comment]
@AtaKarakas Try `flutter clean` and rebuild.

**Comment by AtaKarakas** [comment]
Showing Recent Errors Only
'/Users/username/Library/Developer/Xcode/DerivedData/Runner-bfxtddgnoeiguvgrhxxgtnecdjgn/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/FMDB/FMDB.framework/FMDB' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/username/Library/Developer/Xcode/DerivedData/Runner-bfxtddgnoeiguvgrhxxgtnecdjgn/Build/Intermediates.noindex/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/FMDB/FMDB.framework/FMDB' for architecture arm64


and now this error xD
