### ISSUE TITLE
is any relationship implementation?

### ISSUE THREAD

**Issue by MahdiPishguy** [simolus3/moor#96]
i try to find this feature on library documentations, but i can't find. is any relationship implementation?

**Comment by simolus3** [comment]
We don't have builtin support for relationships in moor. However, you can model relationships by using custom column constraints. For instance, in the example (a simple todo app), we can assign a category to each entry, so we model this 1:n relationship directly in our tables:
https://github.com/simolus3/moor/blob/1df635c067eed926f8b01c8fb5003da5df1c3833/moor_flutter/example/lib/database/database.dart#L14-L24

Then, if we want to load the category for each todo entry, we simply use joins:
```dart
final query = select(todos).join(
 [leftOuterJoin(categories, categories.id.equalsExp(todos.category))]);

final todosWithCategory = query.watch().map((rows) {
  return rows.map((row) {
    final todoEntry = row.read(todos);
    final category = row.read(category);  
  }
});
```
Let me know if you have any questions.

**Comment by Pr0t0b0t** [comment]
What about n:n relationship?

**Comment by simolus3** [comment]
There's an example for n:m relationships in the [docs](https://moor.simonbinder.eu/docs/examples/relationships/).
