### ISSUE TITLE
Converting object to an encodable object failed Flutter

### ISSUE THREAD

**Issue by tony123S** [simolus3/moor#962]
I want to store data into local database(moor).

```
    ABCData abc = ABCData();  
    CurrentInspection currentInspection = CurrentInspection();
    Time time = Time();
    time.readyTime = time;
    currentInspection.times.add(time);
    
    abc = abc.copyWith(currentInspection: currentInspection);
    await _dao.insert(abc);

```
**CurrentInspection**

  ```
  part 'current_inspection.g.dart';
    
    @JsonSerializable()
    class CurrentInspection {
      var times = List<Time>();
    
      CurrentInspection();
    
      factory CurrentInspection.fromJson(Map<String, dynamic> json) =>
          _$CurrentInspectionFromJson(json);
      Map<String, dynamic> toJson() => _$CurrentInspectionToJson(this);
    }

```
**ABC**

    class ABC extends Table {
     
      TextColumn get currentInspection =>
          text().map(const CurrentInspectionSqlConverter()).nullable()();
    }

    
**CurrentInspectionSqlConverter**
    
        class CurrentInspectionSqlConverter
            extends TypeConverter<CurrentInspection, String> {
          const CurrentInspectionSqlConverter();
        
          CurrentInspection mapToDart(String fromDb) {
            if (fromDb == null) return null;
            return CurrentInspection.fromJson(json.decode(fromDb));
          }
        
          String mapToSql(CurrentInspection currentInspection) => json.encode(currentInspection.toJson());
        }

**Error**

> E/flutter (14933): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)]
> Unhandled Exception: Converting object to an encodable object failed:
> Instance of 'Time'

**Comment by simolus3** [comment]
Can you post the stack trace of the exception?

**Comment by tony123S** [comment]
@simolus3  I already posted there. Thanks

**Comment by tony123S** [comment]
I have fixed it.
