### ISSUE TITLE
Dynamic table with dynamic name 

### ISSUE THREAD

**Issue by Vishnupriya-M** [simolus3/moor#963]
I need to create table at runtime  (like tables with same schema ,multiple times with different names as per requirement ).Is it possible using moor? It would be of great help if someone can explain it in detail .Thank you

**Comment by simolus3** [comment]
This doesn't sound like a reasonable requirement to me, but you can do that with moor. For instance, let's say you had a table class called `Users`. You can then define an additional class to use a custom name:

```dart
class UsersWithCustomName extends $UsersTable {
  final String dynamicName;

  DelegatedTable(GeneratedDatabase db, this.dynamicName) : super(db);

  @override
  String get actualTableName => dynamicName;
}
```

You can include that table like this:

```dart
@UseMoor(...)
class MyDatabase extends _$MyDatabase {

  // ...

  @override
  List<DatabaseSchemaEntity> get allSchemaEntities => [
    ...super.allSchemaEntities,
    UsersWithCustomName(this, 'users2')
  ];
}
```dart

**Comment by Vishnupriya-M** [comment]
Hi Simon,

Consider a case like this, there is a table with GPS trial data. Whenever a
new trip is recording we will create a gps  trial table with trip I'd
tagged in its table name. In normal Sqlite we will be defining the schema
once and will pass trip I'd as argument to table class and will create a
table with same schema and that trip I'd  appended in its table name. I was
trying to implement the same in moor. As I'm new to this I have no idea how
to implement this in moor.

Thank you.

**Comment by simolus3** [comment]
I'm not aware of any benefits associated with the approach of one table per trail. Quite contrary, having unnecessarily many tables will slow down your app as the entire schema is scanned and parsed when you open the database. Storing thousands of tracks with millions of points in two tables shouldn't be any issue with the right index, but having thousands of tables will be very noticable.

You can store trips and their tracks with two tables:

```dart
class Trips extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
  // more properties of a recorded trail
}

class TrackPoints extends Table {
  // the track containing this point
  IntColumn get tripId => integer().customConstraints('NOT NULL REFERENCES trips (id)')();
  RealColumn get lat => ...
  RealColumn get lng => ...
  // more properties of a point
}
```

If you're more comfortable using sqlite, you might want to take a look at [moor files](https://moor.simonbinder.eu/docs/using-sql/moor_files/). They allow you to declare tables and queries with direct SQL that gets verified at compile-time. You still get auto-updating streams and type-safety. You can also write Dart queries for tables defined in moor files.  

You can create tables dynamically by creating a `new Migrator(this).createTable(yourDynamicTable)` in your database class, but note that having a fixed amount of tables is probably better.

**Comment by Vishnupriya-M** [comment]
Thanks, I'll check it out.

**Comment by simolus3** [comment]
Ok. I'll close this for now, but let me know if you run into more issues.

**Comment by Vishnupriya-M** [comment]
Sure .

**Comment by Vishnupriya-M** [comment]
Hi @simolus3 
I have one more doubt , is there any limit for number of rows in a table??

**Comment by simolus3** [comment]
A row can have up to 18446744073709551616 (2⁶⁴) rows, that usually isn't a problem :) If you want to select many rows at once you might run into memory issues but if you apply an appropriate filter or limit, it won't be a problem.

**Comment by Vishnupriya-M** [comment]
Ok. Thank you.
