### ISSUE TITLE
how to specify TEXT or NULL in a .moor file query?

### ISSUE THREAD

**Issue by SteveAlexander** [simolus3/moor#969]
I'm using a null-safe database dart file.

I have the following in my .moor file:

```
_itemExistsImpl: SELECT (CAST(
        EXISTS(
            SELECT 1 FROM items WHERE base=:base and name=:name
            and folder_path IS :folderPath
    ) AS BOOLEAN));
```

It generates a method `Future<bool> _itemExistsImpl(int base, String name, String folderPath)`.

But, I want it to be `Future<bool> _itemExistsImpl(int base, String name, String? folderPath)`.

I know I can specify the params like this:

```
_itemExistsImpl(:folderPath AS TEXT): SELECT (CAST( ...
```

But, I don't know how I can specify "TEXT or NULL"

Any ideas?

**Comment by simolus3** [comment]
Thanks for opening this issue. I agree that we should have something like this, I added the `TEXT OR NULL` syntax in 6aa022e547b82155bb461fb44122f6764f2ae27b.

By the way, you can remove the `CAST`, the analyzer should pick up the proper type by now :) With efe0df519be6e8121f65c0e26ba2bb3307ffe8b2, `:folderPath` should also be recognized as nullable by default.

**Comment by SteveAlexander** [comment]
I guess the only thing with `TEXT OR NULL` is that one might also expect `TEXT OR INT` to work
