### ISSUE TITLE
Confusion in transactions

### ISSUE THREAD

**Issue by Sp4Rx** [simolus3/moor#97]
This is the transaction example in  the docs

```
Future deleteCategory(Category category) {
  return transaction((t) async {
    // first, move the affected todo entries back to the default category
    await t.customUpdate(
      'UPDATE todos SET category = NULL WHERE category = ?',
      updates: {todos},
      variables: [Variable.withInt(category.id)],
    );

    // then, delete the category
    await t.delete(categories).delete(category);
  });
}
```
I wonder if I run these queries with the db object will this have the same effect?

```
Future deleteCategory(Category category, Todos todos) {
  return transaction((t) async {
    await db.someDao.delete(categories).delete(category);
    await db.someDao.delete(todos).delete(todos);
  });
}
```

Here I'm accessing through the `db` member variable. So will these two queries be considered as single transaction?

**Comment by simolus3** [comment]
If you're on moor version 1.6 or later, then yes, they will!

----
We call the transaction callback in a new [`Zone`](https://api.dartlang.org/stable/2.4.1/dart-async/Zone-class.html). Whenever a method is called on the database class, we will check if the zone making that call was started by a transaction and delegate that call if necessary.
