### ISSUE TITLE
How to trigger rollback if any exception occurs

### ISSUE THREAD

**Issue by jims57** [simolus3/moor#971]
Say, we have a function to update folders table using **moor** transaction, how to rollback all the changes if an exception happens? Please give me a full example. Thanks.

Another question is that if **moor** can rollback these changes made in multi tables?

```dart
  Future reorderFolders(List<FoldersCompanion> foldersCompanionList) async {
    var result = await transaction(() async {
      for (var foldersCompanion in foldersCompanionList) {
        await (update(folders)
          ..where((f) => f.id.equals(foldersCompanion.id.value)))
            .write(FoldersCompanion(
          order: Value(foldersCompanion.order.value),
        ));
      }
    });

    return result;
  }
```

**Comment by simolus3** [comment]
Moor should rollback a transaction by default if there's an uncaught exception. Is that not what you're seeing?

**Comment by jims57** [comment]
@simolus3 That is fine with me if it will rollback by default. I posted this for double confirmation only. Have nothing to do with my snippet. Thanks.

**Comment by simolus3** [comment]
Ok, feel free to ask questions like that in the [discussions](https://github.com/simolus3/moor/discussions) or on [Gitter](https://gitter.im/moor-dart/community) next time.
