### ISSUE TITLE
Complex migration omits withoutRowId parameter

### ISSUE THREAD

**Issue by ThomasKliszowski** [simolus3/moor#972]
👋  Hello,

I encountered a tiny issue using the complex migration feature.

When the 12 steps migration is executed, the `bool get withoutRowId => true;` parameter is omit.
The new table always has a `rowId`, and the migration test always fails:
```
  teams:
   rowid:
    Did not expect the table to have a WITHOUT ROWID clause.
```

Do you have an idea about that?

Thank you 🙏

**Comment by simolus3** [comment]
Thanks for the report! I'm not exactly sure how to reproduce it though: Do you have a `WITHOUT ROWID` table where the 12 step migration dropped the `WITHOUT ROWID`? That sounds like what you're describing, but from the error message you posted it seems like the `WITHOUT ROWID` clause is kept and that the verification tools didn't include it.

I added a test to ensure that the 12 step migration doesn't clear the `WITHOUT ROWID` clause, but that test worked without any changes. It also looks like `moor_generator schema generate` also creates a `bool get withoutRowid => true;` for generated test code.

**Comment by ThomasKliszowski** [comment]
Oh sorry Simon, you are right, I got too fast on my analyze.

I made a small repo to reproduce that bug: https://github.com/ThomasKliszowski/moor-rowid
Run `flutter test test/database_migrations_test.dart` to get the same error.

You are right, the problem is not what I thought, the rowid is indeed preserved in the complex migrations steps. It seems that this is the `moor_generator schema dump` who omits it. I can't find any reference to the `WITHOUT ROWID` in the generated json.

**Comment by simolus3** [comment]
Ah, I see. In this case, the problem is that the `withoutRowId` getter is ignored by the generator (we only use it at runtime in the migrator). This means that Dart tables can't reliably be without an row id, which isn't great. I changed the Dart parser to recognize this, which should fix the problem. You need to re-run the schema export though (or add an `"without_rowid": true`) to the affected tables.
