### ISSUE TITLE
How to pass argument in custom SQL Query?

### ISSUE THREAD

**Issue by jaydip-pawar** [simolus3/moor#973]
```
Stream<List<Password>> watchSearchedPasswords(String query) {
    return customSelectStream('SELECT * FROM Password ORDER BY wName ASC WHERE wName CONTAINS "$query" OR wAddress CONTAINS "$query";',
    readsFrom: {passwords},).map((rows) {
      return rows.map((row) => Password.fromData(row.data, db)).toList();
    });
  }
```

I have created following method in which i want to return list of rows that contains string which i provide when method is called but  how to pass it?

**Comment by simolus3** [comment]
You can pass variables like this:

```dart
Stream<List<Password>> watchSearchedPasswords(String query) {
  return customSelectStream('SELECT * FROM Password ORDER BY wName ASC WHERE wName CONTAINS ?1 OR wAddress CONTAINS ?1;',
    variables: [Variable.withString(query)],
    readsFrom: {passwords},
  ).map((rows) {
    return rows.map((row) => Password.fromData(row.data, db)).toList();
  });
}
```

But in that case I recommend to use [build-time checked queries](https://moor.simonbinder.eu/docs/using-sql/custom_queries/#statements-with-a-generated-api) or [moor files](https://moor.simonbinder.eu/docs/using-sql/moor_files/) which can generate those methods for you.

Also, feel free to ask questions like that in the [discussions](https://github.com/simolus3/moor/discussions).

**Comment by jaydip-pawar** [comment]
I am getting following exception:
`Unhandled Exception: DatabaseException(near "WHERE": syntax error (code 1): , while compiling: SELECT * FROM Password ORDER BY wName ASC WHERE wName CONTAINS ?1 OR wAddress CONTAINS ?1;) sql 'SELECT * FROM Password ORDER BY wName ASC WHERE wName CONTAINS ?1 OR wAddress CONTAINS ?1;' args [v]}`

**Comment by simolus3** [comment]
Ah yeah, the `WHERE` must come before the `ORDER BY`, I didn't see that at first. Build-time queries or moor files would have spotted that problem ;)

**Comment by jaydip-pawar** [comment]
But Still I am getting Exception :-(

```
E/SQLiteLog(20484): (1) near "CONTAINS": syntax error
E/flutter (20484): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: DatabaseException(near "CONTAINS": syntax error (code 1): , while compiling: SELECT * FROM Password WHERE wName CONTAINS ?1 OR wAddress CONTAINS ?1 ORDER BY wName ASC ;) sql 'SELECT * FROM Password WHERE wName CONTAINS ?1 OR wAddress CONTAINS ?1 ORDER BY wName ASC ;' args [f]}
```

**Comment by simolus3** [comment]
Ah yeah, `CONTAINS` isn't a thing in sqlite3. `instr(wName, ?1) > 0 OR instr(wAddress, ?1) > 0` might work?

**Comment by jaydip-pawar** [comment]
Same Exception getting again and again:

```
E/SQLiteLog(30673): (1) near "instr": syntax error
E/flutter (30673): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: DatabaseException(near "instr": syntax error (code 1): , while compiling: SELECT * FROM Password WHERE wName instr(wName, ?1) > 0 OR instr(wAddress, ?1) > 0 ORDER BY wName ASC ;) sql 'SELECT * FROM Password WHERE wName instr(wName, ?1) > 0 OR instr(wAddress, ?1) > 0 ORDER BY wName ASC ;' args [h]}
```

I want to achieve search functionality in my application, if you have any tutorial that uses moor then please suggest :-)

**Comment by simolus3** [comment]
> but it is case sensitive so there is any way to find the substring of data with case insensitive

You could use `wName LIKE ('%' || ?1 || '%')`, which is case-insensitive for ascii chars.
