### ISSUE TITLE
When migration runs

### ISSUE THREAD

**Issue by Slava96** [simolus3/moor#977]
I have a flow, when user logins - we open/create database with name created from credentials.

So, I have a question.
Does migration runs when we open connection to DB?

**Comment by simolus3** [comment]
Every time you open a moor database, moor will check wether the database exists and what schema version it has. If it didn't exist before, we run the `onCreate` callback. If it did exist before with a different version, we'll call `onUpgrade`. Note that moor databases are opened lazily on the first statement you run, so the migration won't run by simply creating the database instance.

I hope that answers your question. For the next time, feel free to post simple questions like this to the [discussions](https://github.com/simolus3/moor/discussions/categories/q-a), thanks!
