### ISSUE TITLE
Have the ability to build many to many relationship

### ISSUE THREAD

**Issue by KeaSoft** [simolus3/moor#98]

**Comment by simolus3** [comment]
Hi, can you provide more details on what you would like moor to support? It is already possible to construct n:m relationships by creating multiple tables and then using joins.

**Comment by KeaSoft** [comment]
Hi, thank you for your feedback. What i want to construct  is tow tables (person and group) with n:m relationships. you mentioned that is possible to construct this relationships. Could you please provide me example for this case, because I didn't found anything in the documentation.

**Comment by simolus3** [comment]
You could use these tables:
```dart
@DataClassName('Person')
class People extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get name => text()();
}

class Groups extends Table {
  IntColumn get id => integer().autoIncrement()();
  TextColumn get description => text()();
}

class Memberships extends Table {
  IntColumn get person =>
      integer().customConstraint('NOT NULL REFERENCES people(id)')();
  IntColumn get group =>
      integer().customConstraint('NOT NULL REFERENCES groups(id)')();

  @override
  Set<Column> get primaryKey => {person, group};
}
```

Hard to give examples for queries without knowing what you want to achieve. Here's an example that also uses n:m relationships (by modeling shopping carts): https://gist.github.com/simolus3/b881d1a5cbb308d549dd484204e25776 Maybe that's helpful for you as well, but if you have questions on how to write a specific query in moor just let me know.

**Comment by pedromassango** [comment]
@simolus3 I have a question for you.

In my model classes I have relationship between objects like this:

```dart
class Article {
  String id;
  String title;
  int shortDescription;
  List<Comment> comments;
}

class Comment {
  String id;
  String text;
  String authorId;
  String authorName;
}
```

How Can I save the `Article` model and its comments in the database?

**Comment by simolus3** [comment]
I guess in that case it's a 1:n relationship because a comment only ever belongs to one article, right? In that case, you could have a model like this
```dart
@DataClassName('DbArticle') // to avoid name clash with your Article class
class Articles extends Table {
  TextColumn get id => text()();
  TextColumn get title => text()();
  IntColumn get shortDescription => integer()();

  @override
  Set<Column> get primaryKey => {id};
}
@DataClassName('DbComment')
class Comments extends Table {
  TextColumn get articleId => text()(); // the article where this comment was posted
  TextColumn get id => text()();
  TextColumn get text => text()();
  TextColumn get authorId => text()();
  TextColumn get authorName => text()();

  @override
  Set<Column> get primaryKey => {id};
}

// inside your database class that uses both tables:
Future<void> saveArticleAndComments(Article a) {
  return transaction((_) async {
    DbArticle articleForDb = /* you need to turn your model class into the db article here by setting id, title and shortDescription */;
    List<DbComment> commentsForDb = a.comments.map((c) => /* same here, turn model class to row */).toList();
    await into(articles).insert(articleForDb, orReplace: true);
    // delete comments that have already been stored for this article
    await (delete(comments)
          ..where((c) => c.articleId.equals(articleForDb.id)))
        .go();
    // and replace them with the new ones
    await into(comments).insertAll(commentsForDb);
  });
}
```
(just adapted the example from the shopping carts, not sure if that code is 100% valid, but that's the idea that should work)

**Comment by pedromassango** [comment]
Thanks for the tip. I going to try this code soon

**Comment by KeaSoft** [comment]
@simolus3 Thank you again for this example. It will be nice to include such examples in the documentation.
