### ISSUE TITLE
Can't find VmDatabase and package:moor/ffi.dart

### ISSUE THREAD

**Issue by vollkorntomate** [simolus3/moor#981]
I am following the [Getting Started](https://moor.simonbinder.eu/docs/getting-started/) tutorial, but IntelliJ can't find the `VmDatabase` class required by `LazyDatabase` at the end of the tutorial.

I assume, `VmDatabase` is declared in the `package:moor/ffi.dart` package which should be used according to the tutorial. However, the `package:moor/ffi.dart` can't be found either. 

Am I missing some dependency in my pubspec.yaml? Or is there an incosistency in the documentation?

**Comment by simolus3** [comment]
Maybe you're using an older moor version? The `package:moor/ffi.dart` library was added in `moor` version 3.3.0.

**Comment by vollkorntomate** [comment]
Thanks. I changed my `pubspec.yaml` from
```yaml
dependencies:
  moor:
```
to
```yaml
dependencies:
  moor: ^3.3.0
```
and then it worked.

Apparently it doesn't work without the version specified (which is weird because it would normally get the newest version then?).
