### ISSUE TITLE
MoorWebStorage.indexedDbIfSupported() tries to use IndexedDB on Firefox private mode and fails to fallback

### ISSUE THREAD

**Issue by CDDelta** [simolus3/moor#982]
Moor on web currently fails to fallback to LocalStorage when IndexedDB is unavailable in private mode on Firefox. This is because window.indexedDB is non-null in private mode on Firefox even though it isn't available for use.

The error handling to fallback to LocalStorage should be more robust to handle this case like [here](https://stackoverflow.com/questions/31159316/detecting-preventing-firefox-indexeddb-invalidstateerror-caused-by-private-brows).

Sidenote: Thank you @/simolus3 for your awesome work on Moor!

**Comment by CDDelta** [comment]
I can work on this if required. My plan would be to try and open a fake IndexedDB database and check for any errors as outlined in the SO post, a bit hacky but I don't see a way around it.

Not sure how I would add a test for that though as I don't think `dart test` allows you to launch browser instances in private mode.

**Comment by simolus3** [comment]
If you can work on this that'd be great!

> My plan would be to open a fake IndexedDB database and check for any errors as outlined in the SO post, a bit hacky but I don't see a way around it.

Hm yeah, that sounds reasonable. In that case, `supportsIndexedDb` probably needs to be async and return a future. That's ok, the next release will contain breaking changes either way.
