### ISSUE TITLE
Compare Dates

### ISSUE THREAD

**Issue by raphmte** [simolus3/moor#99]
Hello @simolus3 , can you give me an example of how to compare dates with one of the isSmallerThan or isBiggerThan functions please?
I couldn't find a way to make it work here. =/

Thanks in advance.

**Comment by simolus3** [comment]
Hi, if you want to compare the date to a value, you could use something like
```dart
select(todos)..where((entry) => entry.dueDate.isSmallerThanValue(DateTime.now()))
```
If you want to compare the date to lets say another column, you could use
```dart
select(appointments)..where((entry) => entry.startDate.isSmallerThan(entry.endDate))
```
Does that help?

**Comment by raphmte** [comment]
It helped a lot, I was trying to put DateTime.now () in the isSmallerThan function, but from what I understand this function only compares if it's another date field. I honestly had not noticed the isSmallerThanValue function.

Thank you again.

**Comment by raphmte** [comment]
Another question, how to use OR, AND and IN statements on Where clausule?

**Comment by simolus3** [comment]
You can use the top-level `and` and `or` functions to compose boolean expressions. Similarly, there's a top level function `isIn` which you can use to generate `IN` clauses. To use `LIKE`, simply call the `like` method on a text column.

**Comment by raphmte** [comment]
If not too much trouble can you provide an example of `and`, `or `and `IN `please? Like I had already figured out how it worked. And I thank you in advance.

**Comment by simolus3** [comment]
Sure:
```dart
select(todos).where((e) {
  return and(
    e.category.equals(3),
    m.isIn(e.tag, ['Important', 'Work']),
  );
});
```
This would generate `SELECT * FROM todos WHERE (category = 3) AND (tag IN ('Important', 'Work'))` (as a prepared statement with variables, of course). `or` works similar.

**Comment by raphmte** [comment]
Thanks so much, I really didn't realize it was like that.

Now I can make a better progress for my project.
And once again congratulations on Moor and the attention he has given.
