### ISSUE TITLE
Dart tables: foreign keys

### ISSUE THREAD

**Issue by matthewkooshad** [simolus3/moor#990]
looking over https://moor.simonbinder.eu/docs/getting-started/advanced_dart_tables/, i didn't see exactly about foreign keys. this was useful: https://github.com/simolus3/moor/issues/869

is the right approach for T2 having a ref to T1?
class T1 extends Table {
  IntColumn get id => integer().autoIncrement()();
}
in 
class T2 extends Table {
  IntColumn get id => integer().autoIncrement()();
  IntColumn get t1Id=> integer().customConstraint('NOT NULL REFERENCES T1 (id)')();
}

and handling insert into T1 and immediately providing a record to T2, as i need T2 to be a 1:1 with T1.
my insert for T1 right now looks like:
Future<int> insertT1(Insertable<T1> t1) => into(T1).insert(t1);
how could i work with this to always insert a T2 entry as well?

**Comment by kuhnroyal** [comment]
The foreign keys are here: https://moor.simonbinder.eu/docs/getting-started/advanced_dart_tables/#custom-constraints and you approach seems correct.
You have to manually insert T2, there is no automatism.
You can use `db.transaction()` to wrap both inserts.

**Comment by matthewkooshad** [comment]
thanks @kuhnroyal

**Comment by westito** [comment]
A made a PR for foreign key support by table definition. Moreover, type & refactor safe.
The FK constraints added table level, so not breaks column livel custom constraints.

https://github.com/simolus3/moor/pull/1251

```
IntColumn get category => integer().nullable().foreignKey(
  Categories,
  onDelete: KeyAction.restrict,
  onUpdate: KeyAction.cascade,
)();
```
