### ISSUE TITLE
should i be using moor instead of moor_flutter?

### ISSUE THREAD

**Issue by matthewkooshad** [simolus3/moor#995]
https://pub.dev/packages/moor_flutter
https://pub.dev/packages/moor

right now, i'm using latest on moor_flutter and moor_generator in the flutter app.

sometimes, i see something like this: [SEVERE] moor_generator:moor_generator on lib/db/myDao.dart:

InconsistentAnalysisException: Requested result might be inconsistent with previously returned results

**Comment by simolus3** [comment]
For the `InconsistentAnalysisException`, see #959. It's an issue with Dart's build system, but in the most recent version it provides tools to fix that.

Both the core `moor` package and `moor_flutter` are supported. `moor_flutter` uses the `sqflite` package, while the standalone `moor` uses a `dart:ffi` based implementation and needs the `sqlite3_flutter_libs` package when used with Flutter. Both have their pros and cons, a big advantage of the ffi-based implementation is that we get to use the same sqlite version on all devices.
