### ISSUE TITLE
can't be used as a setter because it's final

### ISSUE THREAD

**Issue by matthewkooshad** [simolus3/moor#996]
the classes produced for the moor tables don't seem to have setters for each of the fields. is there an easier way than using copyWith (which i think replaces the whole object value) to just set one of the properties fields? i would manually persist that change to the db in a separate method call. i'm just currently using these classes when i refer to the object type in my flutter app. is there a better way to do this field value changing? thanks!

**Comment by kuhnroyal** [comment]
moor by default generates immutable classes, if you want mutability you can try your luck with the `mutable_classes` option. https://moor.simonbinder.eu/docs/advanced-features/builder_options/

**Comment by matthewkooshad** [comment]
lol "try your luck" that made me laugh. i'll try it out and respond here if any issues. thanks!

**Comment by simolus3** [comment]
Yeah, `mutable_classes` should work. I'll close this issue in the meantime, but if you run into any issues I'll re-open it :)
