### ISSUE TITLE
Using moor in background fetch iOS  - No implementation found for method getApplicationDocumentsDirectory

### ISSUE THREAD

**Issue by Shankulkarni** [simolus3/moor#997]
Hi, 
We are using workmanager package and Moor to read data from database in background and schedule notifications in our app. As we don't want to write to database, we are not using MoorIsolate. 

We are just creating another database instance from the background process but its resulting in following error:

`2021-01-07 21:31:33.227771+0530 Runner[90363:21493510] [VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#2      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
#3      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:104:39)
#4      new DatabaseConnection._internal.<anonymous closure> (package:winoverhabits/common/store/database.dart:91:30)
#5      LazyDatabase._awaitOpened (package:moor/src/utils/lazy_database.dart:30:26)
#6      LazyDatabase.ensureOpen (package:moor/src/utils/lazy_database.dart:43:12)
#7      QueryEngine.doWhenOpened (package:moor/src/runtime/api/query_engine.dart:98:21)
#8      JoinedSelectStatement._getWithQuery (package:moor/src/runtime/query_builder/statements/select/select_with_join.dart:191:40)
#9      JoinedSelectStatement.get (package:moor/src/runtime/query_builder/statements/select/select_with_join.dart:187:12)
#10     HabitEntryBackgroundStore.listRange (package:winoverhabits/modules/habits/store/habit.dart:220:24)
#11     triggerReminderNotification.<anonymous closure> (package:winoverhabits/common/cron/cron.dart:47:29)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#19     _rootRun (dart:async/zone.dart:1190:13)
#20     _CustomZone.run (dart:async/zone.dart:1093:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)`

Our database class looks like this
```
class Database extends _$Database {
  Database() : super(DatabaseConnection().connection);

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration =>
      MigrationStrategy(onCreate: (Migrator m) async {
        return m.createAll();
      }, beforeOpen: (details) async {
          //todo 
      });
}

class DatabaseConnection {
  LazyDatabase connection;

  static final DatabaseConnection client = new DatabaseConnection._internal();

  factory DatabaseConnection() => client;

  DatabaseConnection._internal() {
    connection = LazyDatabase(() async {
      final dbFolder = await getApplicationDocumentsDirectory();
      final file = File(p.join(dbFolder.path, 'db.sqlite'));
      return VmDatabase(file);
    });
  }
}

```

Are we doing something wrong? 
Is there an any example of Moor in background mode, we can refer to?

Thanks in advance

**Comment by simolus3** [comment]
I think the problem here is that the plugin communication channel used by the `path_provider` package doesn't work on background processes. Unfortunately I don't know enough about that part to help you with that. You might have more luck asking on SO, [this question](https://stackoverflow.com/questions/60262425/how-to-make-flutter-workmanager-plugin-and-location-plugin-work-together) sounds similar.

I'm closing this as its not directly related to moor.
