### ISSUE TITLE
Allow queries generated from .moor files to have optional orderBy clauses

### ISSUE THREAD

**Issue by CDDelta** [simolus3/moor#998]
As discussed in #993, given a query like below:
```
allDrives ($order):
    SELECT * FROM drives
    ORDER BY $order;
```
it should be possible to make the `$order` component optional for callers.

Possible syntax to support this could be `allDrives ($order = NULL):`

**Comment by simolus3** [comment]
In moor 4, we'll have a `named_parameters` build option that will make `$order` a named argument. Since those can easily have default values, I think we can just always make them optional, which is what I did in the referenced commit.
